dotnet/AspNetCore.Docs

aspnetcore/breadcrumb/TOC.yml
aspnetcore/toc.yml

Contextual ToC and breadcrumbs for 16 of 20 links to other docs.ms.com doc sets.
Does not work with these, so the query strings were removed from them:
* /visualstudio/debugger/remote-debugging-azure
* /visualstudio/debugger/debug-live-azure-applications
* /visualstudio/azure/vs-azure-tools-connected-services-storage
* /azure/devops/pipelines/get-started-yaml

Contextual ToC updates

---

aspnetcore/includes/RP-mvc-shared/sqlite-warn.md
aspnetcore/tutorials/first-mvc-app/new-field.md
aspnetcore/tutorials/first-mvc-app/working-with-sql.md
aspnetcore/tutorials/razor-pages/new-field.md
aspnetcore/tutorials/razor-pages/sql.md

Fixes #9991 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-1.0&branch=pr-en-us-11364) (use ToC to view work-with-SQL and add-field tutorials in both RP and MVC series

Drop & re-create instead of migrations for sqlite

---

aspnetcore/signalr/dotnet-client.md
aspnetcore/signalr/java-client.md
aspnetcore/signalr/javascript-client.md

Add note that SignalR clients cannot call hub methods if used with SignalR Service in serverless mode.

Add notes on using clients with Azure SignalR Service serverless mode

---

aspnetcore/host-and-deploy/razor-components/configure-linker.md

Addresses #10717 
WRT the def art change here: "a" over "an" in this case (first syllable of "Microsoft" is "m YE," not "em YE") ...
* ~an Microsoft thing~ 👎 
* a Microsoft thing :+1:

Razor Components: Configure Linker updates

---

aspnetcore/client-side/spa/blazor/get-started.md
aspnetcore/razor-components/common/samples/3.x/BlazorSample/BlazorSample.csproj
aspnetcore/razor-components/common/samples/3.x/BlazorSample/JsInteropClasses/ExampleJsInterop.cs
aspnetcore/razor-components/common/samples/3.x/BlazorSample/Pages/JSInterop.cshtml
aspnetcore/razor-components/common/samples/3.x/BlazorSample/wwwroot/exampleJsInterop.js
aspnetcore/razor-components/javascript-interop.md

Fixes #11308 
[Internal Review Topic (JS Interop)](https://review.docs.microsoft.com/en-us/aspnet/core/razor-components/javascript-interop?view=aspnetcore-3.0&branch=pr-en-us-11314)
There's still a broken tutorial app (the RC one). I'll work on that separately. The tutorial text requires updates to accompany that sample's updates.
Cross-references:
* [[Discussion] Microsoft.Interop.JSRuntime.Current has been removed](https://github.com/aspnet/AspNetCore/issues/8117)
* [Reconsider static JSRuntime.Current](https://github.com/aspnet/AspNetCore/issues/6828)

Razor Components Preview3/JS interop updates

---

aspnetcore/web-api/define-controller/samples/WebApiSample.Api.22/Startup.cs

Fixes #11424
Added the missing portion of AddScoped & AddDbContext for Products and Pets to the `ConfigureServices` method, including the associated using statements.

Add missing scoped repo's and dbContext to startup.cs for WebApiSample.Api.22

---

aspnetcore/security/authentication/accconfirm.md

I highlighted the `services.AddTransient` for the custom token provider.
NB: There is also an empty code description below the line `The complete method is shown with the changed line highlighted`, which I did not correct since I do not know to what it refers to.

Missing highlighted code+remark

---

aspnetcore/grpc/basics.md
aspnetcore/includes/RP/model2.md

- Escape trailing # that gets flagged as closed_atx
- Restore old heading text
- Spacing in empty tab

fix: MD003/heading-style/header-style

---

.markdownlint.json

Added the `default:true` and then turned off all the existing rules that had failures

chore: Add Markdownlint config

---

aspnetcore/tutorials/build-your-first-razor-components-app/samples/3.x/RazorComponents/Components/Pages/ToDo.razor

The step explaining this code shows usage of `Count(predicate)` instead of `Where(predicate).Count()`.
See step 14/15 of the given example.

Updated for consistency

---

aspnetcore/fundamentals/configuration/options.md
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/localization.md
aspnetcore/fundamentals/logging/index.md
aspnetcore/includes/RP/page2.md
aspnetcore/includes/mvc-intro/adding-model4.md
aspnetcore/mvc/controllers/testing.md
aspnetcore/mvc/views/partial.md
aspnetcore/mvc/views/razor.md
aspnetcore/security/authentication/customize-identity-model.md
aspnetcore/security/authentication/social/additional-claims.md
aspnetcore/signalr/hubs.md
aspnetcore/tutorials/first-mvc-app/adding-model.md
aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/razor-pages/page.md

- Replace ` with %60 in xref links
- Remove spaces inside code span elements

fix: MD038/no-space-in-code

---

aspnetcore/client-side/spa/blazor/get-started.md

Extension now shipped as Blazor in the marketplace and in the UI.  Reduce confusion by getting rid of the old name.

Update name of Blazor extension

---

aspnetcore/tutorials/getting-started-with-NSwag.md

Addresses #11632
The build warning goes away with this update (and I go for consistency (one hash `#` for tab indicators) across the two tab groups.

NSwag tutorial tab update

---

aspnetcore/host-and-deploy/health-checks.md
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs

StartupTaskCompleted can potentially be modified by multiple threads that are executing at the same time.
This is literally [what `volatile` is for](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile).
> The volatile keyword indicates that a field might be modified by multiple threads that are executing at the same time.
Fixes #10895
(waiting for a reply in the referenced issue, but this change should be correct)

Make StartupTaskCompleted volatile

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/middleware/extensibility.md
aspnetcore/razor-components/dependency-injection.md

Fixes #11707 
* Clarify the overloaded term "request" by stating explicitly "client request (connection)" or "service request" (i.e., from the container).
* Doubt we need engineering on this one.
cc: @ScottHutchinson

Clarify service lifetimes

---

aspnetcore/data/ef-rp/intro.md

At the ## View the DB section the author describes how to find and view the table data within the EF-Core generated database.
The database name is listed as ContosoUniversity1. This is incorrect.
The database name generated is based on the dbContext name we used earlier in the course - "SchoolContext".
The database name will be generated as <dbContextName>-GUID, where the dbContextName is "SchoolContext", plus a dash (ASCII Character 45 (decimal) / 0x2D (hexadecimal), plus a GUID.

Change Database Name from ContosoUniversity1

---

aspnetcore/release-notes/aspnetcore-2.2.md

OpenAPI Initiative branding guidelines indicate that there should be no space in OpenAPI.  https://www.openapis.org/faq/style-guide

Remove space from between Open and API

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/generic-host/samples-snapshot/2.x/GenericHostSample/ServiceContainerFactory.cs
aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/GenericHostSample.csproj
aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/LifetimeEventsHostedService.cs

Addresses #5495 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1&branch=pr-en-us-11766)
* Topic was already 2.1+, but there were some updates:
* Use 3.0 moniker for versioning
* XREF API links
* Sample to 2.2 with line length adjustments

Generic Host topic+sample to 2.2

---

aspnetcore/razor-components/index.md

SEO April Effort: This topic is for ASP.NET Core 3.0 and a top keyword being used in search included "3".  It is not immediately clear the topic is for ASP.NET Core 3.0 in search or even once you look at the topic.  Changing to see if the bounce rate improves.  Following up on bounce ratings next month for this as part of SEO hackadoc.  No related issue for this PR.

SEO April: include ASP.NET Core 3.0 in title

---

.markdownlint.json

Disabling blanks-around-lists per team discussion on 4/2.

Turn off blanks-around-lists markdownlint rule

---

aspnetcore/razor-components/index.md

Part of April SEO sweep.  High traffic topic with relatively high bounce rates.  Fixed title problem I created in the first place.  Moved the version clarfication that is mid page to the top intro.  This topic will be part of a lit of topics that are followed up on next month for SEO fixes to verify if that helped.

Fixed title.  Moved version clarification to intro

---

aspnetcore/security/key-vault-configuration.md
aspnetcore/security/key-vault-configuration/sample/Program.cs
aspnetcore/security/key-vault-configuration/sample/README.md
aspnetcore/security/key-vault-configuration/sample/appsettings.json

Fixes #10790 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&branch=pr-en-us-11827)
... almost fixes. This fixes the certificate guidance recommendation from the Azure PM. It removes the ClientID/Secret approach.
Never did find out how to use the Cloud Shell for granting access to KV. We can go on with the portal as described in the topic.
We prob need to merge this work now because we're going on the road to **_Merge Conflict City_** with a future PR if we don't (e.g., a sample update or 3.x work on the topic).

Adopt certificate approach in AKV config provider topic

---

aspnetcore/host-and-deploy/windows-service.md
aspnetcore/host-and-deploy/windows-service/scripts/2.x/RegisterService.ps1

Fixes #11344 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&branch=pr-en-us-11839)
* Converting from `net user` over to PS 6.2+ `New-LocalUser`.
* I've been reading/hearing lately that "secure string" things aren't so hot any longer from a security perspective; however, this seems to be the way that the commands work in 6.2.
* The updated procedure on the PR has been checked here with :+1::smile: results.
@TravisEz13 ... Do you have a few minutes to look at this? It's a small update that shouldn't take long to review. You can scroll right down to Line 146 **(\#\# *Create a user account*)**.

Use New-LocalUser in WS topic

---

aspnetcore/client-side/spa/blazor/index.md

A platform that supports .NET Standard 2.0 supports all previous versions: 1.0, 1.1, 1.2,1.3,1.4,1.5 and 1.6. So the original statement ".NET Standard 2.0 or higher is supported" is misleading, as Blazor won't support .NET Standard 2.1 without adjustments to the platform.
So my suggestion is to just change it to "Blazor supports .NET Standard 2.0".
In addition libraries can not only be shared between browser and server side, but between different platforms.

Adjust .NET Standard paragraph

---

aspnetcore/razor-components/hosting-models.md
aspnetcore/toc.yml

Fixes #11713 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/razor-components/hosting-models?view=aspnetcore-3.0&branch=pr-en-us-11721)
* Moves this coverage UP in the TOC ... under the *Get Started* topics. Devs make the decision on which hosting model to adopt early in the software development process. Ideally, they'll pick the one they like based on characteristics of each and carry that decision into the *Build Your First* experience (the next topic).
* Cross-links to this topic are good. No changes needed.
* The code sample in the *Server-side hosting model* section (`Startup`) ... is that necessary? I don't think it provides much value. It's an implementation detail AFAICT. They can inspect the RC `Startup` easily enough when they get to the *Build Your …

Hosting Models topic updates

---

aspnetcore/razor-components/forms-validation.md
aspnetcore/toc.yml

Fixes #11715 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/razor-components/forms-validation?view=aspnetcore-3.0&branch=pr-en-us-11780)
* The starship example, which is rich and full featured, is probably a bit too much&dagger; to throw in the reader's face when introducing this content. I start with a simpler example to orient the reader to the basics of an `<EditForm>` before going into the larger, more complicated example.
*bit too much*&dagger; This is only going to get worse later because there will be *more goodies* to show in the example. As the starship example expands, it will make an even worse *First Contact* with the Borg in this topic! :smile: lol
* Withholding this one from the sample app right now: It will :boom: in a giant merge conflict for …

Razor Components Forms and Validation topic

---

aspnetcore/index.md

You can't build "Apps" with .NET Standard, as it is not a runtime. You can only build libraries with it. And those libraries can be executed by a runtime that implements .NET Standard, like .NET Core or .NET Framework. So I changed "Apps" to "Libraries" in that paragraph. I also linked the versions table from the .NET Standard GitHub repo. 
This change is a minor fix to the already closed issue #11866 (cc @guardrex)

Fix .NET Standard issue and link version table

---

aspnetcore/security/cors.md

I think this is a typo and "cors" was meant.

Typo fix: cores -> cors

---

aspnetcore/security/authorization/policies.md

Fixes #11609.
* I built a sample project to test all of this and discovered that the explanation re all handlers being called even when a handler fails also applies to when a handler succeeds, so I updated the relevant section. I fully appreciate that this wasn't part of the linked issue so I'm more than happy to revert that if needed.
* I didn't include an example of how to check whether the user is authenticated as I concluded that this is a little out of scope for the topic.
* I updated the date on the topic itself as it was dating back to 2017.

Describe how authorization handlers all run re success, failure and when unauthenticated.

---

aspnetcore/host-and-deploy/docker/index.md
aspnetcore/toc.yml

This article was deleted from the .NET Core docs repo and its URL was redirected to a completely different article.  The intent was to move the article to the ASP.NET Core repo and then the link would be accurate again, but until that can be done it will be better not to mislead people.
See #11705

remove link to deleted article

---

aspnetcore/security/data-protection/configuration/overview.md

Fixes #11401
Main changes are lines 167-168:
> \* For apps hosted in \[IIS](xref:fundamentals/servers/index#iis-http-server), the unique ID is the IIS physical path of the app. If an app is deployed in a web farm environment, this value should be stable assuming that the IIS environments are configured similarly across all machines in the web farm.
> \* For self-hosted apps running on the \[Kestrel server](xref:fundamentals/servers/index#kestrel), the unique ID is the physical path to the app on disk.

Per-app isolation: the app's unique ID

---

aspnetcore/fundamentals/environments.md

Fixes #11928 
The behavior is by-design. Let's just use the ANCM section on this, which includes a clear warning. The cross-link is already present here.
Thanks @TadeuTorres! :rocket:

Update web.config remark: Use ANCM topic section

---

aspnetcore/security/data-protection/configuration/overview.md

Fixes #11943 
@pakrym That was a blown update earlier. I *assumed* it was just **Get** and **List**. Looks like it's actually **Unwrap Key** and **Wrap Key** permissions. I also add that the dev should create the key in the first place ... if they don't, it all ends in tears :boom::cry:.
Do we want one of the Azure KV cats to look at this? This PR is based on local testing, but I still might not be covering all of the bases.
Special thanks to @brobichaud :rocket: for reminding that **_assumptions_** can be a real pit of failure. 🙈

Update AKV DP provider content

---

aspnetcore/razor-components/common/samples/3.x/BlazorSample/Pages/ChildComponent.cshtml
aspnetcore/razor-components/common/samples/3.x/BlazorSample/Pages/HeadingComponent.cshtml
aspnetcore/razor-components/common/samples/3.x/BlazorSample/Pages/Index.cshtml
aspnetcore/razor-components/common/samples/3.x/BlazorSample/Pages/ParentComponent.cshtml
aspnetcore/razor-components/common/samples/3.x/BlazorSample/wwwroot/css/site.css
aspnetcore/razor-components/common/samples/3.x/RazorComponents/Components/Pages/ChildComponent.razor
aspnetcore/razor-components/common/samples/3.x/RazorComponents/Components/Pages/HeadingComponent.razor
aspnetcore/razor-components/common/samples/3.x/RazorComponents/Components/Pages/Index.razor
aspnetcore/razor-components/common/samples/3.x/RazorComponents/Components/Pages/ParentComponent.razor
aspnetcore/razor-components/common/samples/3.x/RazorComponents/wwwroot/css/site.css
aspnetcore/razor-components/components.md

Fixes #11243 
[Internal Review Topic (EventCallback section)](https://review.docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0&branch=pr-en-us-11924#eventcallback)
* For now, I focus on basic implementation. Let's add more detail where you think it's required from here.
* Interesting bits are in the *EventCallback* section (a subsection of the *Event handling* section) and the accompanying sample updates for that content, which run lines 325-371 of *aspnetcore/razor-components/components.md*. The section is linked via the *Internal Review Topic* link. The rest of the updates here are general updates, and we can review those bits on the docs side.
* **_Layouts!_** ... is there any way to use `EventCallback`/`EventCallback<T>` across a the component-layout …

Add EventCallback content to Components topic+sample

---

aspnetcore/performance/performance-best-practices.md

I read through [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2) and noticed a few minor issues:
* In a section of **do** and **do not**, there's an item missing the **do** prefix.
* The statement explaining minification cuts of prematurely.
* The link to Gulp is broken. Rather than just fixing the existing link, I chose to link to [Use Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.2), which I think is a more useful link :crossed_fingers: for the context.
* ASP.NET is used instead of ASP.NET Core when discussing keeping up-to-date.

Minor fixes for the Performance Overview.

---

aspnetcore/mvc/views/razor.md

- Markup in code blocks were added in order to allow easy templating alternatives for users who are coming from pre-.NET Core days of Razor where `@helper` was an option.
- Expanded the Razor syntax sheet to include the markup in code blocks pieces. Didn't want to call out specifically that this is an alternative to using old school `@helper` because that could technically lead to more confusion for those who are just entering the .NET Core world and have never seen `@helper` in their lives.
@guardrex @scottaddie @RickAndMSFT how do I ensure these docs only show up when .NET Core 3.0.0 is selected in the docs?
Fixes #11647

Add docs for markup in code blocks.

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

This adds more details on using fallback providers and adds documentation for the `GetRequiredPolicyAsync` API.
Fixes #10824

Update `IAuthorizationPolicyProvider` docs

---

aspnetcore/toc.yml

Moves the Key Vault link after the Secret Manager doc, since the two docs are closely related.

Promote Azure Key Vault config provider in ToC

---

aspnetcore/web-api/advanced/conventions.md

using Microsoft.AspNetCore.Http.StatusCodes instead of numbers is much readable

Using Microsoft.AspNetCore.Http.StatusCodes instead of numbers is much readable

---

aspnetcore/toc.yml
aspnetcore/web-api/advanced/conventions/sample/Controllers/ContactsConventionController.cs

Note: I'm trying to mirror the ToC structure under the **Tutorials** node. We'll have a **Data access** child node once the EF Core Learn module publishes. There will also be a **Web apps** child node when Wade's Razor Pages Learn module publishes.

Add web API MS Learn module to ToC

---

.openpublishing.redirection.json

Fixes #11989 
I guess it just wasn't in the cards at this point to avoid it any longer.
**_Blazor is just too freak'in crazy popular!_** :tada:
Thanks @LocalJoost! :rocket:
**Recommend**: Merge to live right after this goes in.
I've already taken care of the blazor.net forwards: https://github.com/aspnet/Blazor.Docs/pull/454 and https://github.com/aspnet/Blazor.Docs/pull/453
Note: I don't think we need to (or should really) put the `/index` on the `redirect_url` when redirecting an *index.md* file. I checked one of the redirects without it, and it's working fine. Therefore, I leave that off and just go with a trailing slash.

Blazor redirects

---

aspnetcore/toc.yml

Moves the Secret Manager and Azure Key Vault config provider docs under a new **Secrets management** ToC node. This change should make it easier to locate those docs.

Improve discoverability of secrets management docs

---

aspnetcore/blazor/get-started.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/includes/blazor-prerendering.md

Fixes #12044 
Fixes #12056
Fixes #12057 
Fixes #11795
[Internal Review Topic (Get Started)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&branch=pr-en-us-12061)
This isn't meant to address the whole topic reviews for Pre4 that I'll perform next week on https://github.com/aspnet/AspNetCore.Docs/issues/10717. Hitting quick fixes here for Pre4.
* Updating VS tab template names: In my VS (and I'm not even on preview; I'm on 16.0.2), the template names are correct in the UI ["Blazor (server-side)" and "Blazor (client-side)"]. Let me know if the template names are only wrong in the VS preview (which I don't have installed); if so, I'll make a further update here to cover that.
* macOS users should only use Blazor client-side at the moment. Adding a …

Blazor Preview 4 updates

---

aspnetcore/blazor/get-started.md

The rules engine isn't providing the rendered list marker type that I would like. I'm attempting a workaround that should bypass the rules engine recognizing these inner lists as lists at all, just indented content.

Set inner lists with non-breaking space workaround

---

aspnetcore/fundamentals/metapackage-app.md

Fixes #12094
We can accomplish this by merely boxing the current content for 2.1.

Update the App implicit version guidance for 2.2

---

aspnetcore/blazor/layouts.md

Fixes #12085
There's a stray period in an `@using` statement that was copied over from the [blog post: \_Imports.razor section](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/).

Fix typo in Blazor Layouts code example

---

aspnetcore/fundamentals/metapackage-app.md
aspnetcore/fundamentals/metapackage.md
aspnetcore/host-and-deploy/iis/troubleshoot.md
aspnetcore/migration/20_21.md
aspnetcore/migration/22-to-30.md

Shared framework clarification

---

aspnetcore/fundamentals/logging/loggermessage.md

Fixes #12145 
Thanks @jasonshave! :rocket: It was the **_crazy 's'_** at the end of the link. *Rotten 's'!!!!* :smile: lol

Fix LoggerMessage sample link

---

aspnetcore/mvc/views/view-components.md

Description:  missing spaces break formatting
cc: @rick-anderson,

C86844: Adding two spaces after line 173 to avoid display issues on localized pages

---

aspnetcore/blazor/class-libraries.md

Addresses #10717 
Fixes #12117 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&branch=pr-en-us-12132)
* Overhaul the instructions for set up, including clear VS instructions.
* Enhanced coverage:
* Razor class library and client-side scenario
* Static assets and server-side scenario 
**NOTE**: Do you want to pitch [BlazorEmbedLibrary](https://www.nuget.org/packages/BlazorEmbedLibrary/) as a temp workaround with a support warning? If not, is there any workaround that can be pitched until Preview 7?
* The usual style+grammar pass.
* **QUESTION**: We say static resources are "embedded into the built assembly file," but stylesheets end up in the *_content* folder and referenced from there by *index.html*, so that doesn't …

Blazor class libraries topic updates

---

aspnetcore/blazor/components.md

There was a typo "chstml" instead of "cshtml" that caused the code section to not do proper syntax coloring

Fix language specification in one code sample

---

.markdownlint.json
aspnetcore/index.md

Leaving this PR to merge to master to avoid picking up extraneous commits, can wait until 5/6 to merge.
A heading was changed to satisfy a Markdownlint rule.  The rule disallows "trailing punctuation" including question marks in headings, but headings are sometimes appropriately phrased as questions, and question marks are appropriate in such cases.
This PR 
* Disables the rule
* Restores the heading to what it was previously but changes "use" to "choose"

Disable markdownlint rule

---

aspnetcore/signalr/dotnet-client.md

This warning is out-of-date and needed removal.

removed old xamarin warning

---

aspnetcore/performance/performance-best-practices.md

Changing the url for thread pool docs page to the correct one.

Typo in url for thread pool doc page

---

aspnetcore/mvc/views/tag-helpers/authoring.md

Description: missing spaces are breaking formatting on loc pages
@guardrex

C80832: Adding two spaces at the end of a line

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

You should import the Swashbuckle.AspNetCore.Swagger namespace _before_ adding the Swagger generator to the services collection or you get a red squiggly.

Should import the namespace first

---

aspnetcore/blazor/components.md

_italicsCheck in `bind` amended to `ItalicsCheck` which is referred to in the text above it

Fixed typo in binding example

---

aspnetcore/fundamentals/logging/index.md

https://github.com/serilog/serilog-extensions-logging specifies that ASP.NET Core 2.0+ should prefer https://github.com/serilog/serilog-aspnetcore instead.

Fix serilog link to newer repo

---

aspnetcore/tutorials/grpc/grpc-client.md

When adding gRPC packages the project to add them to should be GrpcGreeterClient.csproj.

Use correct gRPC client project name

---

aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker/samples/2.1/HelloDockerTools/Dockerfile.original

Switch .NET Core Images from the legacy location at Docker Hub Registry (`microsoft/*`) to a new location at Microsoft Container Registry (`mcr.microsoft.com/*`).

Update from microsoft/* to mcr.microsoft.com/*.

---

aspnetcore/mvc/controllers/areas.md

Description:  Missing spaces breaking loc content. Please add double space to reported lines at the end
@Rick-Anderson

C86836: Adding double spaces at the end of lines to avoid broken content

---

aspnetcore/web-api/index.md

How to log automatic 400 responses

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

The [proxies and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2) document had a code example that didn't line up with the [logging pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.2) in ASP.NET Core 2.2. This PR updates the code example and instructions.

Fix logging code example

---

aspnetcore/fundamentals/servers/kestrel.md

When Kestrel was moved into the AspNetCore monorepo this documentation was never updated. This small change updates the link to point to the correct folder in the AspNetCore repo.
Despite the change being quite minimal, I did verify that the page renders and functions correctly using DocFX.
If there is a desire to leave the link to the legacy implementation (and simply add a new link) then let me know and I will update the PR.
Thanks in advanced!

Updated link to Kestrel Source.

---

aspnetcore/mvc/views/dependency-injection.md

Fixes #10985
I've added a simpler example for injecting configuration into a view. Separated the two examples so the new example is for configuration-injection and the existing is for service-injection.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-2.2&branch=pr-en-us-12337#configuration-injection)

Adds a simpler example for view-injection

---

aspnetcore/blazor/hosting-models.md

Fixes #12358 
> We no longer need to load `blazor.server.js` from the client app project, because it's now served directly from an embedded resource in `.Components.Server` middleware.
https://github.com/aspnet/AspNetCore/pull/6562

Update source of the blazor.server.js script

---

aspnetcore/client-side/using-grunt.md

For example, this option:
Right-click the project and select Add > New Item. Select the Grunt Configuration file option, leave the default name, Gruntfile.js, and click the Add button.
Adding a "Grunt" or a "Gulp" configuration file hasn't existed in Visual Studio since around version 15.7.   You just add a javascript file and name it accordingly.
Also, this image "devdependencies-grunt.png" should be updated to show the current 1.x versions

Out of date documentation

---

aspnetcore/security/key-vault-configuration.md
aspnetcore/security/key-vault-configuration/sample/Program.cs
aspnetcore/security/key-vault-configuration/sample/Startup.cs
aspnetcore/security/key-vault-configuration/sample/appsettings.json
aspnetcore/security/key-vault-configuration/sample_snapshot/Program.cs

Fixes #12393
@anurse: Are you available for review? If not, who would be good to look at this one?
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&branch=pr-en-us-12396)
* Use certificate from the cert store as the main approach (over a cert in the root of the app, which would require a `SecureString` of the cert's password to work).
* Update instructions: Azure AD only allows CER, CRT, and PEM uploads now. Have the reader create and upload a CER from a PFX for their AAD-registered app. The PFX is in the cert store, and the CER goes to Azure.
Questions:
* Do we need to ask Azure AD engineers why a PFX can't be uploaded any longer?
* Does Azure AD engineering need to look into why a CER, CRT, or PEM can't be …

Update AKV config provider for new Azure process

---

aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/javascript-interop/samples_snapshot/_Host.cshtml
aspnetcore/blazor/routing.md
aspnetcore/host-and-deploy/blazor/client-side.md

Fixes #12188 
* Adds *\_Host.cshtml* coverage.
* Touch the app base path coverage in Blazor client-side host and deploy topic.
Thanks @patrickjlee! :rocket:
btw- I would've asked here about contacting Disqus about what we did on #12188 to get an example of a Disqus implementation in Blazor apps, but I think we'll need Blazor at RTM to approach them with the example. Maybe it's something we could do later this year.

Blazor _Host.cshtml coverage + base path touchup

---

aspnetcore/mvc/advanced/custom-model-binding/sample/CustomModelBindingSample/Controllers/ImageController.cs
aspnetcore/mvc/advanced/custom-model-binding/sample/CustomModelBindingSample/appsettings.json

Fixes #12292
* Mirrors the approach used in the [File Uploads PR (aspnet/AspNetCore.Docs #12344)](https://github.com/aspnet/AspNetCore.Docs/pull/12344).
* Specifically:
* Have the example save the file elsewhere, not to *wwwroot*.
* ~Cleanse the filename with `Path.GetInvalidFileNameChars` and Linq.~ Use `Path.GetRandomFileName` to get a fully trusted random file name.
* The topic makes no direct reference to any of this, so the topic doesn't require changes. Line highlights in the topic for the `regions` here don't require an update either.
Thanks @omerlh! :rocket:

File uploads in Custom Model Binding topic

---

aspnetcore/tutorials/build-your-first-blazor-app.md

Changed:
```cshtml
<input placeholder="Something todo" bind="@newTodo">
```
on line 185 to:
```cshtml
<input placeholder="Something todo" bind="@newTodo"/>
```
because it won't run otherwise / syntax mistake

Added missing slash in example code

---

aspnetcore/blazor/components.md
aspnetcore/blazor/javascript-interop.md

Fixes #12481 
Engineering resolved unclosed void elements on https://github.com/aspnet/Mvc/pull/2956.
Docs have moved in that direction (for example, [Unclosed void elements in topics (aspnet/AspNetCore.Docs #11881](https://github.com/aspnet/AspNetCore.Docs/pull/11881)).
Is this a point-in-time problem for Blazor, or will they always require closure?
btw - There are two spots where `<base>` tags are still unclosed. I think those don't suffer from this issue; but if I'm incorrect, I can add those two on another commit here before we merge this. :ear:

Close void elements in Razor components

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #11996 
Let's use a better link here: This install topic in the IIS docs speaks directly to the prereqs (e.g., the Management Service) issues for installing Web Deploy.
https://docs.microsoft.com/iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy-on-iis-80-or-later
Going with the IIS 8 or later (Windows Server 2012 and Windows 8) topic ... better than the IIS 7 version. The IIS 7 (WS 2008) topic is right next to this topic ... same node in their TOC ... a reader wouldn't miss it.

Change Web Deploy link in IIS topic

---

aspnetcore/fundamentals/choose-aspnet-framework.md
aspnetcore/includes/benefits.md

Updated this comparison doc to account for ASP.NET Core 3.0 Preview 4.    The compare doc uses an include called benefits.md which was also updated.  Minor updates overall.
Current published version of this doc:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-3.0

v3 preview 4 update to core vs 4.x compare

---

aspnetcore/blazor/get-started.md

Fixes #12549
We can go ahead with this: Engineering has said that preview VS is recommended for Blazor. It does work (I'm using 16.0.2 here) ... it *barely* works ... with lots of little tooling quirks. However, it isn't recommended, so let's drop this instruction.

Drop instruction for non-preview VS with Blazor

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/servers/kestrel/samples/2.x/KestrelSample/Startup.cs

Fixes #12101 
Fixes #12113 
* **Error confirmed here!**: `Store` is required or `WindowsCryptographicException: 'The parameter is incorrect'` is thrown.
* Similar to what we just did for config, call out the namespace for the section that pertains to Kestrel options.
* ... and that Logging namespace isn't needed ... probably a leftover from an earlier sample update that had some logging in there.

Kestrel topic updates

---

aspnetcore/client-side/spa-services.md
aspnetcore/release-notes/aspnetcore-2.0.md
aspnetcore/toc.yml

Fixes #12562 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.1&branch=pr-en-us-12571)
@scottaddie This is your :baby: ... do u want to review?
* The main callout on the issue is getting the engineering link addressed, and I just remove it here. Linking to source is either (eventually) a bad experience when the engineering version changes or going with `master` or it's a pain point for the reader having to figure out how to substitute a version into an engineering repo link that has something like `{X.Y}` in it. Therefore, I just drop it.
* Took the naming from "JavaScriptServices" to "JavaScript Services" and maintained it as a singular proper noun.
* ... then, just nit updates. I made a *quick* 🏃 and **_not …

JavaScript Services topic updates

---

aspnetcore/blazor/components.md

Fixes #12544
The remark came from the Gist ...
> ... split up your code into smaller pieces wrapped in `OpenRegion`/`CloseRegion` calls.
https://gist.github.com/SteveSandersonMS/ec232992c2446ab9a0059dd0fbc5d0c3#questions
... but those aren't `public` ...
https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/RenderTree/RenderTreeBuilder.cs#L537-L552
Thanks @limefrogyank! :rocket:

Remove OpenRegion/CloseRegion remark

---

aspnetcore/blazor/javascript-interop.md

Blazor JS interop: call void functions

---

aspnetcore/fundamentals/servers/httpsys.md
aspnetcore/security/authentication/windowsauth.md
aspnetcore/security/authentication/windowsauth/sample_snapshot/Program_GenericHost.cs
aspnetcore/security/authentication/windowsauth/sample_snapshot/Program_WebHost.cs
aspnetcore/security/authentication/windowsauth/sample_snapshot/launchSettings.json

Fixes #12102 
Fixes #12144 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&branch=pr-en-us-12554)
* Addresses content layout/organization problem. The changes here seek to adopt a *start-to-finish* section layout that should also clarify the difference between launch settings config and IIS/HTTP.sys host config.
* Added a bit for HTTP.sys to cover for 3.0 host building.
* Configure Windows Authentication in ASP.NET Core
* Launch settings (debugger)
* VS &ndash; *New project* and *Existing project* procedures
* VSC/CLI &ndash; *New project* and *Existing project* procedures
* Authentication services for IIS or HTTP.sys
* IIS
* Before publish with *web.config*
* After publish with IIS Manager
* HTTP.sys
* …

WinAuth topic updates

---

aspnetcore/fundamentals/websockets.md

Fixes #5466 
The bulk of #5466 was done in #12378, but this PR adds a few notes from #5466 that weren't included in the earlier PR. It also reorganizes a bit to promote H3s to H2s and removes 1.1 sections.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?branch=pr-en-us-12620)

Add WebSocket lifetime info

---

aspnetcore/host-and-deploy/azure-apps/troubleshoot.md
aspnetcore/host-and-deploy/iis/troubleshoot.md

This is a super rough draft for improvements we made for ANCM startup error pages. 
High level goals:
- Make ANCM startup pages have different error codes based on error condition
- Provided diagnostic information in the HTTP response in development
Right now, we have two troubleshooting guides, one for app services, and one for local IIS. We would like to have both of these have information (or ideally, consolidate these docs).
@guardrex I'll let you decide the best way to organize this information 😄

Update ANCM error pages and diagnostics

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/host-and-deploy/windows-service.md

Fixes #11791 
* Gets it into the hosted services and WS topics.
* I'll surface the hosted services VS4Mac instructions at 3.0 RTM. https://github.com/aspnet/AspNetCore.Docs/issues/12664
btw - In the WS topic, I tried a version of this where the IDE instructions are under item 1 in the two-item list. It renders with a full-width horizontal rule under the list item that I'm not happy about. Therefore, I list the two steps and then show the IDE instructions. We can play with it if you want, but I don't think it's worth 😅 *sweat'in* 😅 ... got other stuff that *I gots to get to*. :smile:

Surface Worker Service project template

---

aspnetcore/fundamentals/app-state.md
aspnetcore/security/gdpr.md
aspnetcore/security/gdpr/sample/RP/Startup.cs
aspnetcore/test/integration-tests.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/12688
**Summary of changes**
- Clarify how consent is provided in a template-generated project (by clicking the **Accept** button).
- Clarify what consent is provided (cookie storage).
- Move GDPR doc's non-essential cookies **Tempdata provider and session state cookies are not essential** section within the **Essential cookies** section. This makes linking easier from the Integration Tests doc.
- Replaced occurrences of *folder* with *directory* in the Integration Tests doc. Both terms were being used.

Add TestServer doc note about non-essential cookies

---

aspnetcore/security/authentication/windowsauth.md

Fixes #12618
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&branch=pr-en-us-12714)
* Re-org this a bit ... Let's try IIS/IIS Express first, then HTTP.sys separately.
* Should these sections say anything about in-proc vs. out-of-proc? Currently, we only address in-proc in the *Claims transformation* section at the bottom. It's also the only thing that pertains to WinAuth in the ANCM topic where in-proc/out-of-proc is covered.

WinAuth enhancements

---

aspnetcore/blazor/components.md

Fixes #12690 
From Dan on the issue ...
> Components are just classes. They really can go anywhere you want. I just figured we already had one random folder in the template for non-page components that there was no reason to create another one for this tutorial.
I hit this on a sample because I incorrectly assumed (and forgot) that these folders don't use the app's root namespace. Just a bit here surfaces the basic concepts, especially for newbies ... *like me!* :baby:

Namespace+location for components

---

aspnetcore/fundamentals/routing/samples/2.x/RoutingSample/Startup.cs

There is no open issue that this PR addresses. But it seems like bad form to have `detonate` as a package Action for a Microsoft sample.

'detonate' a package? Really?

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

Addresses https://github.com/aspnet/AspNetCore/issues/4135
Set for 2.1 and 2.2. Opened https://github.com/aspnet/AspNetCore.Docs/issues/12737 to revert the "Until new container images are provided in Azure" remark at 3.0 RTM.

Proxy/LB update for templates with Azure Linux

---

aspnetcore/fundamentals/configuration/index.md

Fixed https://github.com/aspnet/AspNetCore/issues/9700
Environment variables prefixed with `ASPNETCORE_` are loaded specifically for **host configuration**, not for app configuration. Added a link to the section on the difference in the environment variables section.

Clarify use of envvars for host config

---

aspnetcore/security/authentication/cookie.md

The anchor doesn't seem to add any value except for hiding the title of the page 😜.  The link is essentially to the top of the document.

Remove anchor link from using-data-protection

---

aspnetcore/host-and-deploy/windows-service/samples/2.x/AspNetCoreService/CustomWebHostService.cs

Because it inherits from `ServiceBase` (via `WebHostService`), VS treats this `CustomWebHostService` class like a "Component" and tries to open a design surface for it. This causes problems because the designer can't load properly over this type (it has a constructor). We are fixing `WebHostService` in 3.0 (and it's no longer recommended anyway, with Worker Service), but the 2.x sample should be updated to lead people down the happy path.
Addresses aspnet/AspNetCore#11114 for 2.1/2.2.

Workaround designer issue in VS

---

aspnetcore/security/authentication/windowsauth.md

Fixes #12420
[Doc preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&branch=pr-en-us-12793&tabs=visual-studio)

Docs for new Negotiate auth handler

---

aspnetcore/tutorials/grpc/grpc-start.md
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/GrpcGreeter.csproj
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/GrpcGreeterClient.csproj
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Program.cs

Addresses https://github.com/grpc/grpc-dotnet/issues/296
Should the client use TLS by default? The server template in preview 6 is not so we'd need to include instructions for adding TLS to the server.

Update gRPC tutorial for preview 6

---

aspnetcore/tutorials/first-mongo-app.md

Markdownlint changed the HTML regex and now flags some new elements.
These elements don't get swallowed like the others.

fix: MD033/no-inline-html

---

aspnetcore/data/ef-mvc/concurrency.md

Updated documentation to reflect the changed use of `SingleOrDefaultAsync` to now use `FirstOrDefaultAsync`

Updated Documentation to Reflect Changes in #11696

---

aspnetcore/blazor/class-libraries.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/routing.md
aspnetcore/host-and-deploy/blazor/client-side.md
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/host-and-deploy/blazor/index.md

Fixes #12865 
* Existed without "ASP.NET Core" because it was experimental and couldn't attach to the naming at that time.
* Three topics will have their titles updated on their existing PRs. This PR gets the rest of them.

Add tech name to Blazor topics

---

aspnetcore/security/gdpr.md

Cookie consent has been removed from the templates in ASP.NET Core 3.0
Fixes #12720

3.0 Cookie Consent updates

---

aspnetcore/client-side/bundling-and-minification.md

Fixes #12861 
Adding warning message to understanding gulp-uglify errors with es2015 syntax and newer.

Add warning to prevent es2015 minification errors

---

aspnetcore/tutorials/first-mvc-app/adding-view.md

When no name parameter is provided to a `View()` method, a view file with the same name of the caller action will be used, not an `Index.cshtml` view file by default.

Elaborate how view files are selected

---

aspnetcore/security/cookie-sharing/sample/CookieAuthWithIdentity.NETFramework/CookieAuthWithIdentity.NETFramework/CookieAuthWithIdentity.NETFramework.csproj
aspnetcore/security/cookie-sharing/sample/CookieAuthWithIdentity.NETFramework/CookieAuthWithIdentity.NETFramework/Web.config
aspnetcore/security/cookie-sharing/sample/CookieAuthWithIdentity.NETFramework/CookieAuthWithIdentity.NETFramework/packages.config

Fixes #12886
* System.Security.Cryptography.Xml taken to 4.4.2 per CVE-2018-0764 and CVE-2018-0765.
* Sample app confirmed running after this update.

Security vulnerabilities in sample app

---

aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/directory-structure.md

Fixes #10273
Version some language for when creating folders for a path to the debug log is necessary.
btw - Has the default location changed for the debug log, or is it still the app's deployment root?

ANCM log path updates

---

aspnetcore/fundamentals/middleware/index/snapshot/Culture/StartupCulture.cs
aspnetcore/fundamentals/middleware/write.md

Fixes #11443.
I made a few changes here:
* Changed the delegate example to use `async`/`await` to match the approach used in the middleware class.
* Switched the example URL to use https and the template-generated default 5001 port for that.
* Added an explanation of the requirements for a middleware class. All of these requirements are enforced by the hosting startup process, where exceptions are thrown if the requirements aren't met.
* Moved the dependencies section up to below the requirements explanation I added. I think this follows on naturally.
* Made the per-request dependencies section a child of the higher-level dependencies section.
**TODO**:
I don't know how to test the moniker ranges locally, so I couldn't update the note about `InvokeAsync` being available in ASP.NET Core …

Conventional middleware class requirements.

---

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
aspnetcore/razor-pages/sdk.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/12226

Document default Content globs for Web and Razor SDKs

---

aspnetcore/fundamentals/servers/kestrel.md

Endpoints should have a lower case 'p' as per: 
https://github.com/aspnet/AspNetCore/blob/c288baf967ddb615162e71ad924bd14526194908/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs#L16

Typo in json config prevented me from running my app on Linux

---

aspnetcore/fundamentals/servers/kestrel.md

This documents the change made in https://github.com/aspnet/AspNetCore/pull/10355

Document ability to disable request body data rate limits per HTTP/2 stream in Kestrel

---

aspnetcore/mvc/views/view-compilation.md

The RuntimeCompilation package does this on user's behalf. We had a bug in one of the earlier preview releases that required this, but it should be fixed now.

Remove PreserveCompilationContext requirement

---

aspnetcore/migration/1x-to-2x/identity-2x.md

* Give precise instructions for both HTTP.sys and IISIntegration
* Mention NuGet packages
* Add `using` statements
* Spell out the full exception that would be thrown if authentication is not properly setup to improve searchability
It's clear from [ASP.NET Core 2.0 HttpSys Windows Authentication fails with Authorize attribute][1] answer on Stack Overflow that this part of documentation needed improvements:
> I initially thought that this wouldn't apply to HttpSys, given the full name of the constant (especially the IISIntegration threw me off).
[1]: https://stackoverflow.com/questions/45818095/asp-net-core-2-0-httpsys-windows-authentication-fails-with-authorize-attribute/45818096#45818096

Improve the 1x to 2x migration guide about Windows Authentication

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md

Specify the latest preview version package to install.

Minor tweaks to API help pages PR

---

aspnetcore/release-notes/aspnetcore-2.2.md
aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/web-api-help-pages-using-swagger.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples.sln
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup2.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup1x.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup3.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup4.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.NSwag/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.NSwag/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Startup2.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/TodoApi.csproj
aspnetcore/web-api/action-return-types/samples/WebApiSample.Api.21/WebApiSample.Api.21.csproj
aspnetcore/web-api/action-return-types/samples/WebApiSample.Api.Pre21/WebApiSample.Api.Pre21.csproj

- part of #8462
- react to changes in these new packages
nits:
- update NSwag URLs to current GitHub location
- add solution for web-api-help-pages-using-swagger projects
- remove unused namespaces

Bump NSwag and Swashbuckle package versions

---

aspnetcore/signalr/version-differences.md

Shouldn't Redis Backplane listed as one of the option for ASP.NET Core SignalR scaleout?

Add Redis Backplane as scaleout option for ASP.NET Core SignalR

---

aspnetcore/blazor/components.md

Fixes #12548
Decided to flip my first-pass table so that the human-readable event names are the keys. The values are the classes. It's probably a bit more reader- and :eye:-friendly this way.

Blazor event argument coverage

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/HeadingComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/Index.razor
aspnetcore/blazor/components.md

Fixes #12892
**Skip these remarks and access the diff. My confusion was cleared in the discussion.**
**This PR has the final set of updates that we need.**
RE: [Update blazor docs to reflect directive attributes changes (aspnet/AspNetCore.Docs \#12756)](https://github.com/aspnet/AspNetCore.Docs/pull/12756)
1. WRT the temporary (Pre6) need to place an `@` on a field/property value of an `@bind` directive. I looked at [Implement directive attribute feature for components (aspnet/AspNetCore \#6364)](https://github.com/aspnet/AspNetCore/issues/6364), but none of the description discusses the scenario.
For example in the [Format strings section](https://docs.microsoft.com/aspnet/core/blazor/components?view=aspnetcore-3.0#data-binding) of the Components topic, updates didn't add the `@` to the …

Components topic code example updates

---

aspnetcore/host-and-deploy/iis/index.md

We don't support loading single-file deployments in-proc. We have a nice error but we should doc that too :).
I think this has a nested moniker, so I hope that works. I'll find out in the doc build! :)
[Internal Review Version](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0&branch=pr-en-us-12956)

Add note about single-file deployments for in-proc

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/common/samples/3.x/BlazorSample/App.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/BlazorSample.csproj
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/HTTPRequestTester.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/JsInteropClasses/ExampleJsInterop.cs
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/CallWebAPI.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/README.md
aspnetcore/blazor/common/samples/3.x/BlazorSample/Shared/NavMenu.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/wwwroot/css/site.css
aspnetcore/toc.yml

Fixes #10743
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0&branch=pr-en-us-12477)
* Not crazy about the title, but we can work on that.
* The sample app component (*Pages/CallWebAPI.razor*) is built in concert with our [web API tutorial](https://docs.microsoft.com/aspnet/core/tutorials/first-web-api). The examples in the topic and the sample app code are set up for a happy path by merely running the web API tutorial app and then running the code in the topic or the Razor component in sample against that service.
* I'm mostly concerned about the *HttpClient and HttpRequestMessage with Fetch API request options* section. It's the most challenging bit to organize and explain ... *lot's 'o concepts* there ... and there are …

Blazor call web API topic with sample

---

aspnetcore/fundamentals/choose-aspnet-framework.md

Hyperlinks to Visual Studio Code and Visual Studio for Mac are present but there was no hyperlink to Visual Studio IDE. So added that hyperlink.

Added missing link to Visual Studio IDE

---

aspnetcore/host-and-deploy/blazor/server-side.md

Fixes #12445
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server-side?view=aspnetcore-3.0&branch=pr-en-us-12732)
Improve cross-linking to content that pertains to hosing server-side Blazor.

Improve cross-links in Blazor server-side host doc

---

aspnetcore/signalr/configuration.md

`ClientTimeoutInterval` was added in 2.2 so should not be present in 2.1

Fix configuration across versions

---

aspnetcore/host-and-deploy/aspnet-core-module.md

**_QUICK_** 🐇 versioning patch. Opening the diff further on https://github.com/aspnet/AspNetCore.Docs/pull/13074 from earlier today would've revealed that the added 3.0 content dropped right into the middle of previously versioned 2.2+ content. This should patch it up.

Versioning patch

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/components.md
aspnetcore/blazor/components/samples_snapshot/3.x/FetchData.razor

Addresses #10717
... and I removed that old Preview 4 prerendering NOTE.
```
No "::: moniker-end" found for ">= aspnetcore-3.0", MonikerRange does not end explictly.
```
... was from earlier today and **_quick patched_** on https://github.com/aspnet/AspNetCore.Docs/pull/13076.
**No rush on this. It isn't going to block my _Blazor Sweep_ work on Tuesday.**

Blazor Pre6 Sweep 2

---

aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md

Follow-up PR to https://github.com/aspnet/AspNetCore.Docs/pull/13135. Global tools were supported as of 2.1. Adding the appropriate metadata, so this doc is only displayed for the appropriate versions.

Display code gen doc for 2.1+

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/razor-pages/razor-pages-conventions.md

Fixes #12734
[Internal Review Topic (*Service registration methods* section direct link)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1&branch=pr-en-us-13209#service-registration-methods)
@anurse We had an ask to clarify the service registration overloads. Do you have a couple of minutes to take a look at this new section? It's short and won't take long to :eyes:.
1. Is it sane thus far? 🙈
1. What's it missing? 🐄:bell:
1. Should it explicitly recommend the *concrete type that implements an interface* approach? 👩‍⚖

Enhance service registration scenario coverage

---

aspnetcore/fundamentals/configuration/index.md

Fixes #13182
The Azure docs content is very :+1: ... I recommend that we link out for the coverage.
https://docs.microsoft.com/azure/azure-app-configuration/quickstart-aspnet-core-app

Surface Azure App Configuration Provider

---

aspnetcore/fundamentals/logging/index.md

Fixes #12891 
* Turns out that there are only options for the Console provider ... Where's my *Easy Button*?
* Didn't touch the *old* (<2.1) versioning. I guesstimate that you plan to address that along with 3.0.
* I spotted two double-forward dashes for quick 🔪 work.

Surface link to console provider options

---

aspnetcore/mvc/controllers/filters.md

Make the description of IsReusable property of ServiceFilterAttribute and ServiceFilterAttribute consistent

Make description consistent

---

aspnetcore/security/ip-safelist.md
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/AdminSafeListMiddleware.cs
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Startup.cs

I was reading through [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-2.2) (uid: security/ip-safelist) and I noticed some minor errors:
* 3 approaches are listed and then the text explains how *both* approaches are in the sample.
* A line highlight for the second snippet is off.
* One of the code examples uses an enum for a 403, whereas the others use 401 and they use it directly.
You'll see that I collapsed the code that needed to be highlighted onto 1 line, as this works out to be exactly 80 characters, which I've read is the max for docs pages.
---
I think the page could do with some more work, which I'm happy to raise as an issue if this isn't already on the radar. Of course, I'd also be happy to PR something for …

Minor tweaks to "IP Safelist".

---

aspnetcore/host-and-deploy/azure-apps/index.md

Fixes #13013
Addresses #12965
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-2.1&branch=pr-en-us-13322)
* Clarifications for 64-bit.
* Re-organize for preview vs. non-preview deployments:
* The preview guidance in one section.
* The general guidance on deployment in another (new) section.
* Explicitly say *where* the published app is to be deployed when dragging to the Kudu console. I'll finish the updates for #12965 on a PR to follow our merging of the Azure Apps and IIS troubleshooting topics. For now, this takes care of that issue on the Azure Apps Overview topic side of things.

Azure Apps Overview updates

---

aspnetcore/fundamentals/middleware/index.md

Remove redundant character from the description

Fix typo in Map section

---

aspnetcore/grpc/authn-and-authz/sample/Ticketer/Protos/ticket.proto
aspnetcore/grpc/authn-and-authz/sample/TicketerClient/Protos/ticket.proto
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/Protos/greet.proto
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Protos/greet.proto

This is the most common syntax for declaring proto rpcs

Remove curly braces from proto rpcs

---

aspnetcore/blazor/get-started.md

Fixes #13402
* From the community report, this change just rolled out a couple of days ago for 16.2 Pre4.
* I don't have VS Preview (no HD space left here). I might have Aquent send me a laptop tho to address this *little problem* 😩 going forward.
* WRT any other spots that call out the VS UI template name, I'll square them away on my upcoming *doc sweep*.

Update client-side template name for VS Preview

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/BlazorSample.csproj
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/JSInterop.razor

Fixes #13454
@danroth27 One thing threw me off for a sec. We were using the Razor syntax for the `onclick` (as `@onclick`) with the JS interop example to call the FNs, like this ...
```cshtml
<button type="button" class="btn btn-primary"
@onclick="exampleJsFunctions.returnArrayAsyncJs()">
Trigger .NET static method ReturnArrayAsync
</button>
```
Now, that yields a big 'ole :boom: ...
> Pages\JSInterop.razor(51,19,51,37): error CS0103: The name 'exampleJsFunctions' does not exist in the current context
I resolved it by going with an old skool `onclick` ...
```cshtml
<button type="button" class="btn btn-primary"
onclick="exampleJsFunctions.returnArrayAsyncJs()">
Trigger .NET static method ReturnArrayAsync
</button>
```
Idk if that's by-design or a regression. I'm going to go ahead and merge …

Update Blazor common sample to Pre7

---

.markdownlint.json

These markdownlint rules cause too many false positives when tabs are used.  Tabs get flagged as duplicate headings and multiple h1s, and subsequent h3s get flagged as a jump in heading level even if there was an h2 before the tab.

Turn off md024, 25, 36

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #13450
* In this example (instructing the reader to avoid the service locator pattern), `MyClass` isn't a registered service ... it's just a class example ... so it's fine in its present form. However, @moikot correctly calls out that *IF* the pattern shown in the example were to be adopted by a singleton service that it won't work and probably isn't the best example.
* Let's inject `IOptionsMonitor<MyOptions>`, then pull the `CurrentValue` in the `MyMethod`. That will always work if this pattern were to become part of a singleton.
* This whole topic is coming up for a 3.0 update in a few weeks. I'll comb thru it (and take a look at the Options topic when it comes up) to see if any other little *gotchas* like this might be lurking.
Thanks @moikot for calling this out. 🎸

Update DI example

---

aspnetcore/fundamentals/servers/kestrel.md

This fixes the indentation in the Kestrel endpoint configuration example which was sometimes indented at the wrong level making it a bit difficult to read.

Fix indentation in Kestrel HTTPS config example

---

aspnetcore/razor-pages/ui-class.md

Path cleansing for RCL was reverted for preview 7.
This is creating confusion at 
Fixes https://github.com/aspnet/AspNetCore/issues/12561
Commit reference
https://github.com/aspnet/AspNetCore-Tooling/commit/98b168c8947d8c7f7b3f2beb3a0561fb89cadfb5

Update RCL static asset path

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/ChildComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/ListViewTemplate.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/Tab.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/TabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/TableTemplate.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/ParentComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/RouteParameter.razor
aspnetcore/blazor/components.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/get-started/samples_snapshot/3.x/Counter2.razor
aspnetcore/blazor/index.md
aspnetcore/blazor/routing/samples_snapshot/3.x/Constraint.razor
aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/Counter.razor

- A lot of the parameter documentation was already present (such as not setting parameters outside of their declaring class).
- Updated all `[Parameter]` locations to utilize `public` properties with `public` setters.
- Updated all the locations I could find where we were suggesting users to utilize non-public parameters.
Fixes #13453

Document public [Parameter] expectation in 3.0.0-preview8.

---

aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/host-and-deploy/iis/index.md

Fixes #13533 
An additional approach to surfacing the troubleshooting guidance is to place at link in or near the introductions of the IIS and Azure Apps topics. We already surface troubleshooting guidance in the *Additional Resources* sections, but this should aid readers when they're sent to these topics from a cross-link that we don't control (e.g., framework messages/links).
Close this PR if this doesn't look like it will be of any help. Just *spit-ball'in* here.

Surface troubleshooting overview in hosting topics

---

aspnetcore/blazor/debug.md

Fixes #13548 
We can revert this instruction pending the outcome of the engineering issue (https://github.com/aspnet/AspNetCore/issues/12779). I've opened https://github.com/aspnet/AspNetCore.Docs/issues/13596 to track the reversion, and that will be monitored on the Blazor.Docs project.

Pass Debug option to a Blazor app for debugging

---

aspnetcore/blazor/hosting-models.md
aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactoryConsoleSample/Program.cs
aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactoryConsoleSample/SampleApp.csproj
aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactoryConsoleSample/Program.cs
aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactoryConsoleSample/SampleApp.csproj

Fixes #7967 
[Internal Review Topic (*Use IHttpClientFactory in a console app* section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1&branch=pr-en-us-13434#use-ihttpclientfactory-in-a-console-app)
* Hack'in around 🙈 here. This is *one way* it could go. If u have a better i-dear, I'm all :ear::ear::ear:.
* I don't place this in with the other 'how to use IHttpClientFactory' list items because that's called out under **_ASP.NET Core_**, and this ain't that. :smile: Seems like the best spot is for this is down at the bottom.

Use IHttpClientFactory in a console app

---

aspnetcore/blazor/components.md

Fixes #13613
* Updating links to Pre8 ref source branch.
* Will open a Pre9 issue to react to https://github.com/aspnet/AspNetCore/pull/12660.
Thanks @Lurs! 🏍

Update EventArgs ref source links

---

aspnetcore/fundamentals/host/platform-specific-configuration.md

Fixes #12574 
**Start at LINE 316 here. There are some tiny nit updates on the lines leading up to that point that you can ignore.**
[Internal Review Topic (*Project bin folder* section direct link)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.1&branch=pr-en-us-13425#project-bin-folder)
* **Consume hosting startup assembly from load context or GAC when targeting .NET Framework**
I based the lingo on this PR from a convo between D.F. 🦆 and a community member (email chain). I can forward that convo to you, if needed.
* **Startup hook**
**[EDIT] No action taken on this point on this PR.**
* From a prior discussion, you said it should be documented in .NET Core docs, not here.
* Point of confusion tho: I was going to …

Hosting startup netfx bin+GAC

---

aspnetcore/security/key-vault-configuration.md

Fixes #13608 
The original remark was ...
> Disabled and expired secrets throw a `KeyVaultClientException` at runtime. Therefore, it's important that you update your application or replace or update a disabled or expried secret in the key vault before the provider attempts to load or reload a disabled or expired secret.
It was clearly mangled a bit on an ancient update back in 2017.
New remark on this PR ...
> Disabled and expired secrets throw a `KeyVaultClientException` at runtime. To prevent the app from throwing, provide the configuration using a different configuration provider or update the disabled or expired secret.
Thanks @ps-tb! :rocket:

Revise remark in AKV config provider topic

---

aspnetcore/tutorials/first-web-api.md

created new tab for mac and windows, updating the instructions to include mac.
fixes #13666

No instructions to disable ssl verification on mac

---

aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/handle-errors/samples_snapshot/3.x/person-example.razor
aspnetcore/blazor/handle-errors/samples_snapshot/3.x/product-details.razor
aspnetcore/fundamentals/middleware/index.md
aspnetcore/toc.yml

Fixes #13288 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.0&branch=pr-en-us-13407)
* Goes with "handle" over the participle ("handling"). More *verb-y-ish*:tm: (action based) this way. We gave this treatment to the ASP.NET Core "error handling" topic a while back as far as is permitted (e.g., title), not for its UID or URL. Here, we can start with the better option.

Blazor Handle Errors topic

---

aspnetcore/grpc/basics.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/13681
@Rick-Anderson I think this is a simple change to include all the packages required for the code sample to work.
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.0&branch=pr-en-us-13704

Display all the packages required for a gRPC client

---

aspnetcore/mvc/controllers/areas.md

The standard `asp-*` tag-helpers did not work when used from a view inside an area.
Could probably be written better, but this would at least save me some time, because I'd probably move `_ViewImports.cshtml` togheter with `_ViewStart.cshtml` when I started using Areas.
For current users it is good that `ctrl-f` `area` on [tag heplpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-3.0) would point directly to hints on what to do.

Add some hints on how to use tag helpers and areas together

---

aspnetcore/web-api/http-repl.md

Without this change, the list of instructions for making POST requests is ordered 1, 2, 1 instead of 1, 2, 3

Fix indentation in http-repl.md

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs

Fixes #13701
References same file as the InfoClassNamespace. I PR'd that file as well. /tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs

Adds Missing "using" statements

---

aspnetcore/grpc/aspnetcore.md
aspnetcore/tutorials/grpc/grpc-start.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/13544
Internal review URLs:
* https://review.docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&branch=pr-en-us-13568&tabs=visual-studio#grpc-and-aspnet-core-on-macos
* https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&branch=pr-en-us-13568&tabs=visual-studio#run-the-service

Add documentation for using gRPC on macOS

---

aspnetcore/blazor/handle-errors.md

Fixes #13694
For reverting "can be" back to "isn't," the original was correct (i.e., "isn't"). That's the point of what Steve is saying ... `person.Address` can throw, but `person` can't.
Thanks @tdykstra! 🏍

Clarify component instantiation remark

---

aspnetcore/performance/caching/middleware.md

Fixes #13750
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.1&branch=pr-en-us-13751)
* This adopts the approach discussed offline yesterday. Only the *Configuration* section requires versioning.
* Fix a miss 🤦‍♂ yesterday: Call out that the package is implictly added.

Update Resonse Caching Middleware version blocks

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

There are two index.html's in the project, so the right one one is now specified. Also changed http to https.

Made filepath more specific for index.html

---

aspnetcore/tutorials/grpc/readme.md

Adding new readme.md for gRPC sample
* Adds capability to add the gRPC sample Tutorial to https://docs.microsoft.com/samples
* Needed to create a Visual Studio specific version, tabs extension not supported in GitHub; which is linked to from the /samples page.
* additional readme files can be added potentially for additional versions with the proper metadata.
@dend

add gRPC Sample for docs sample browser

---

aspnetcore/blazor/class-libraries.md

Fixes #12888
This is bit *late to the party* 💃🕺 because the original engineering issue marked removal of the template for Pre9, but it was actually killed off at Pre8 and the docs issue wasn't aware. 
The docs issues were aware of the VS UI gesture changes to get an RCL. That update has already been made. However, you might want to take a look at that in this topic and confirm that the steps are correct.

Remove the Blazor Class Library template

---

aspnetcore/blazor/components.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/includes/blazor-prerendering.md

Fixes #13854
* Update current text+examples for **Preview 9**. This PR goes to the `release/3.0-preview9` branch.
* Drop some text that I held on to (it was commented out) from the release and patch at Preview 8.
* This seeks to follow the guidelines in the [Removing automatic backing field support for @ref in 3.0.0-preview9](https://github.com/aspnet/Announcements/issues/381) announcement.
cc: @rynowak @danroth27

Automatic backing field support update for Preview 9

---

aspnetcore/blazor/components.md

Since the API changed, it's no longer CaptureUnmatchedAttributes but CaptureUnmatchedValues

[Fix] CaptureUnmatchedAttributes => CaptureUnmatchedValues

---

aspnetcore/grpc/troubleshoot.md

Addresses https://github.com/grpc/grpc-dotnet/issues/460
Internal review URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0&branch=pr-en-us-13891#unable-to-start-aspnet-core-grpc-app-on-macos

Add paragraph that Http1AndHttp2 is not supported without TLS

---

aspnetcore/data/ef-rp/intro.md

Fixes #10771
Changes both 2.1 and 3.0 versions to drop db before the DbInitializer runs.

Drop db before seeding

---

aspnetcore/tutorials/grpc/grpc-start.md

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&branch=pr-en-us-13984)
Quick patch for a couple of nits and tab groups. A warning cropped up this morning on another PR ...
> | invalid-tab-group | aspnetcore/tutorials/grpc/grpc-start.md | Tab group with different tab id set. |
I think it was from a missing paren on https://github.com/aspnet/AspNetCore.Docs/pull/13954.

Fix and match tab groups in GRPC topic

---

aspnetcore/grpc/troubleshoot.md
aspnetcore/tutorials/grpc/grpc-start.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/13552
Addresses https://github.com/grpc/grpc-dotnet/issues/476
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0&branch=pr-en-us-14010)
[Note:The template uses the ASP.NET Core HTTPS development certificat](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&branch=pr-en-us-14010&tabs=visual-studio#next-steps)

Add troubleshooting docs on untrusted cert with gRPC client

---

aspnetcore/blazor/components.md

Fixes #14102
* Move coverage to the bottom of the section because the current content breaks right into the middle of the example without naming.
* Flesh out the code example with additional detail. For example, include both the ancestor and descendant components.
Thanks @Legends! :rocket:

Improve cascaded values/params content

---

aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/GrpcGreeterClient.csproj

Previous version numbers came from a private NuGet feed. Update sample to use publicly available versions.

Update gRPC sample package version to NuGet.org versions

---

aspnetcore/blazor/forms-validation.md

Validate nested sub-properties

---

aspnetcore/security/authentication/add-user-data/sample-2.2/ScaffoldingReadme.txt

The word "add" was missing from a sentence in the ScaffoldingReadme.txt file.

Added missing word in sentence

---

.vscode/settings.json

"files.trimTrailingWhitespace" already defaults to false in VS Code, but some people like me might have this configured to true in their user setting.
See https://github.com/aspnet/AspNetCore.Docs/pull/13844/files#r321423599

Ensure VS Code doesn't trim significant whitespace

---

aspnetcore/host-and-deploy/azure-apps/index.md

Fixes #13339
Fixes #11658
I don't see any obvious changes for 3.0, except ..........
For logging extension coverage, we have ...
> ASP.NET Core apps deployed to App Service automatically receive an App Service extension, **ASP.NET Core Logging Extensions**. The extension enables logging integration for ASP.NET Core apps on Azure App Service.
1. The name didn't change to **ASP.NET Core Logging Integration**. I guess we'll strip that here. If that's still in the works, what's the ETA on it?
1. We say that the extension is automatically added, but I just spun up an App Service and didn't get it automatically. Should we **_not_** say it's automatic here?

Deploy to Azure Apps update to 3.0

---

aspnetcore/includes/benefits.md

WRT https://github.com/aspnet/AspNetCore.Docs/pull/14204 ...
* There's a stray paren to remove.
* Also, clarification on my confusion: Wasn't the "or self-host in your own process" bit at the end supposed to be the bit that covered Kestrel? If so, I cut that here now that Kestrel is called out and cross-linked. If not, I'll add that phrase back to the end of the sentence. We still need this PR either way to 🔪 the stray paren.

Update benefits INCLUDE

---

aspnetcore/host-and-deploy/windows-service.md
aspnetcore/host-and-deploy/windows-service/samples/2.x/AspNetCoreService/README.md
aspnetcore/host-and-deploy/windows-service/samples/3.x/AspNetCoreService/README.md
aspnetcore/host-and-deploy/windows-service/samples/3.x/AspNetCoreService/appsettings.json

Fixes #14193
* Calls out the default URL (http://localhost:5000) in the sample apps' *README.md* files.
* Slight touch to *appsettings.json* to mirror what the `worker` template app does.
* I suppose that `AllowedHosts` in the settings file is ok given that this is a web app service and Host Filtering Middleware would work here if added. Let me know if you'd like that 🔪 out of here.

Call out the URL for Windows Service sample app

---

aspnetcore/web-api/http-repl.md

With https://github.com/dotnet/HttpRepl/pull/223, we changed the name of the tool from `dotnet-httprepl` to `httprepl`. This changes the way the tool is executed from `dotnet httprepl` (or `dotnet-httprepl`, though that wasn't used in the docs) to just `httprepl`.
This PR updates the docs to reflect that change.

Change how the tool is launched

---

aspnetcore/host-and-deploy/health-checks.md
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/BasicStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/CustomWriterStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/DBHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/DbContextHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/LivenessProbeStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/ManagementPortStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/BasicStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/CustomWriterStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/DBHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/Data/AppDbContext.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/Data/Blog.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/DbContextHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/LivenessProbeStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/ManagementPortStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/MemoryHealthCheck.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/Program.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/README.md
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/ReadinessPublisher.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/Services/StartupHostedService.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/appsettings.json

Fixes #13340
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2&branch=pr-en-us-13946)
* Sample update to 3.0. Confirmed working.
* Lot's 'o updates here. Plz review me carefully :eyes:. We're not in a major rush, so review can wait if too busy right now to look. 🏃🏃🏃🏃😅 
* Whole topic versioning. You only need to review the top-half of the markdown file (the >=3.0 section).
* Goes with endpoint routing.
* `RequireHost`, `RequireAuthorization`, and `RequireCors` added.
* Let me know if we aren't going to stick with `MapWhen` to limit the HTTP verb: Is there an endpoint routing way to do it? (See the *Restrict health checks with MapWhen* section.)

Health Checks topic+sample updates for 3.0

---

aspnetcore/web-api/advanced/custom-formatters.md

Explanation of built-in Input and Output formatters.

---

aspnetcore/blazor/components.md

Fixes #14144
[Internal Review Topic (direct link to the new *Chained bind* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0&branch=pr-en-us-14215#chained-bind)
The *chained bind concept* and *checking values with the property's setter concept* seem to me to be *two different things*. One doesn't need to perform any checking if they're just binding to an element and binding across nested components. Therefore, what I do here is cover chained bind first. Get that basic idea out of the way. Then, I expand upon chained bind with a check for spaces in the password value in a second example. This 🤠 *Texas Two-step* 🤠 makes sense to me because it avoids complexity when explaining the basic concept while not losing the great example of checking …

Blazor chained bind

---

aspnetcore/fundamentals/servers/index.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/servers/kestrel/samples-snapshot/2.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples-snapshot/3.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/2.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/KestrelSample.csproj
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/Startup.cs

Fixes #12842
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&branch=pr-en-us-13775)
**WRT HTTP/2: Additional updates (probably) will be made on https://github.com/aspnet/AspNetCore.Docs/issues/10141.**
* No giant rush on this. It's not a *quick review*. It needs a careful :eye: from engineering.
* Sample app
* Adding the 3.x version.
* Add `UseLibuv` to the `FileDescriptor` examples.
* We can't use our *whole topic* versioning here because there are *three* versions covered.
* Placing this back under TD's authorship now that he's back from *AzureLand*:tm:. :smile:
* The only obvious breaking change to react to is `NoDelay`, which was only in examples here. I remove it in favor of a nice, generic `// Configure …

Kestrel topic+sample 3.0 update

---

aspnetcore/security/authentication/identity.md
aspnetcore/security/authentication/identity/sample/WebApp1/Areas/Identity/Pages/Account/Logout.cshtml.cs

Fixes #14255.
The comment that comes in with the code update explains the need for a redirect, so I elected to remove the outdated line from the docs page.

Use RedirectToPage after SignOutAsync as per current Identity UI.

---

aspnetcore/security/enforcing-ssl.md
aspnetcore/toc.yml

Links to the OWASP cheatsheets should be to the published site (https://cheatsheetseries.owasp.org) rather than to the backend GitHub repo or the wiki (which has legacy versions).

Link to published OWASP cheatsheets rather than GitHub copies

---

aspnetcore/toc.yml

Add tutorial and samples links to gRPC TOC.
I'm not sure what the best title is for the gRPC tutorial. The current "Get started with gRPC service" doesn't read well to me.
Alternate ideas: "Get started with a gRPC service" or just "Get started with gRPC"
IDK

Add tutorials and samples to gRPC TOC

---

aspnetcore/blazor/components.md

Fixes #14277
Revert changes made on https://github.com/aspnet/AspNetCore.Docs/pull/12546, back when `OpenRegion`/`CloseRegion` were `private`.
https://github.com/aspnet/AspNetCore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L578-L597

Revert OpenRegion/CloseRegion remarks

---

aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/signalr/streaming.md

included all the stuff for signalr 3core 3.0. cc @BrennanConroy @anurse @halter73 @RickAndMSFT

added core 3.0 signalr

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14231

constructing AuthorizationPolicyBuilder without parameters leads to exceptions

---

aspnetcore/migration/22-to-30.md

Fixes #12923
[Internal Review Topic (direct link to Kestrel section)](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-1.0&branch=pr-en-us-14331#kestrel)
* Removing a lot of "Migrate" and "Update" verb-y-ish-ness in headings ... a bit silly imo ... the whole topic is about *migration* and *updates*. These just cloud the heading subjects imo.
* Miss anything?
* Any :poop: coverage?
* Keep an :eye: on my namespace/package references. They're easy to :bomb:.

Kestrel updates for 3.0 migration topic

---

aspnetcore/blazor/components.md
aspnetcore/mvc/views/razor.md

Fixes #14294
This directive *seems* to only apply to RC. If for all of Razor, let me know :ear:.

Add @typeparam

---

aspnetcore/razor-pages/ui-class.md
aspnetcore/razor-pages/ui-class/samples/cli/RazorUIClassLib/RazorUIClassLib.csproj
aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/WebApp1.csproj

Fixes #14408
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&branch=pr-en-us-14461)
* Whole-topic versioning.
* Add info on "Pages and Views" via VS and `-support-pages-and-views` option.&dagger;
* Update sample code for 2.x to 2.2 from 2.1.
&dagger;I won't get a look at the VS screens locally until RTM (I can't support preview VS).
Options:
* Let me know how to phrase the VS UI content ... How and where does VS show 'pages and views support'? Send me a screenshot perhaps.
* Let's hold this PR until RTM ... My VS will update that day ... I'll see and react to it myself. I'll just mark this PR with `[HOLD]` in the title for now.
Also note: I thought that I would arrive to find this topic+sample code addressed for 3.0. …

RCL topic update for 3.0

---

aspnetcore/performance/caching/memory.md

Description: extra space is breking formatting of code sample on LOC pages

C122717: removing extra space inside code snippet

---

aspnetcore/migration/22-to-30.md

There was a small typo in the Migrate from ASP.NET Core 2.2 to 3.0 documentation.

Fix Typo in 22-to-30 documentation

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/class-libraries.md
aspnetcore/blazor/components.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/index.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/routing.md
aspnetcore/blazor/state-management.md
aspnetcore/blazor/supported-platforms.md
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/host-and-deploy/blazor/index.md
aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/server.md

Because Blazor's first release is 3.0 GA, we can mark the Blazor docs date with the 3.0 GA date. In this way, readers know the docs are current as of the 3.0 GA release and don't merely apply to some prior Blazor preview release.

Set Blazor docs release date to GA date

---

aspnetcore/blazor/get-started.md

Fixes #14511
* Looks like the SDK step and template install step are still required (seems so here with a VS upgrade to 16.3).
* Do we still need to guide readers to get the preview for VS4Mac?

Update Blazor VS preview language

---

aspnetcore/migration/22-to-30.md

Hey @scottaddie,
When reading this doc, and upgrading my .NET Core 2.2 to .NET Core 3.0 bits I thought it would be nice to see the package names - so I'm adding them.

Added package names to migration doc

---

aspnetcore/security/authentication/2fa.md

Description: Missing hard break-line before snippet is preventing content to show properly. Please consider adding two spaces at the final of the line.

L124311: Adding two spaces to create hard break-line before snippet

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/DependencyInjectionSample.csproj
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Interfaces/IMyDependency.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Interfaces/IOperation.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Models/Operation.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/Error.cshtml
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/Error.cshtml.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/Index.cshtml
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/Index.cshtml.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/Shared/_Layout.cshtml
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/_ViewImports.cshtml
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Pages/_ViewStart.cshtml
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Program.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/README.md
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Services/MyDependency.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Services/OperationService.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/Startup.cs
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/appsettings.Development.json
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/appsettings.json
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/startup.md

Fixes #12839
[Internal Review Topic](#)
* New 3.0 sample confirmed working.
* Few content changes, so I used our standard versioning approach.
* Wording changes to the *Framework-provided services* section steering it away from saying or implying that *this is a full list* ... there are over 200 services registered by a typical template-based web app. I make it say that the table represents a small sample of them.
* *Call services from main* section updated to show:
* Generic Host and Web Host examples per version of doc.
* Converted over to async.
**Need guidance on alt container setup for 3.0 ...**
There's a section here on [default container replacement (this links to the live topic)](https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?#default-service-container-rep …

DI topic updates for 3.0

---

aspnetcore/performance/caching/memory.md

Hi @Rick-Anderson 
Description: Extra space inside code snippet is preventing correct display

L124348: Removing extra space inside code snippet

---

aspnetcore/razor-pages/index.md

Description: Missing break-line before snippet is preventing content to show properly.

L124355: Adding break-line before snippet

---

aspnetcore/includes/built-in-TH.md
aspnetcore/includes/cdn.md
aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/HtmlPage1.html
aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/HtmlPage2.html
aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/_Layout.cshtml
aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/index?view=aspnetcore-2.2&branch=pr-en-us-12270)
Fixes #12167
Fixes #12185
Fixes #10593

Link and Script TH

---

aspnetcore/signalr/client-features.md

A few updates:
* Added transports
* Added Azure SignalR support - every client supports it, but we do get questions like "can I use the service with Java?" so it's helpful to confirm that in the matrix, and technically the client has to do some (very minimal) work to support it. I put this at the top, because it's so awesome 😉, and that messed up the visual diff a bit (sorry!).
* Added note about issue tracking automatic reconnect

Update SignalR Client Features matrix

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes https://github.com/aspnet/AspNetCore/issues/8945
The customer in the linked issue had some confusion about why `ExecuteAsync` wasn't being called when they had overridden `StartAsync`, and it's because they didn't call the base class method. Added some content to clarify that.
Also, I rephrased some content here since I thought it was important to call out that `StartAsync` and `StopAsync` are *optional* methods that give you additional control over the lifetime of the service, if you want it.

Tidy up to hosted services doc

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

Swashbuckle.AspNetCore rc3 is released with aspnetcore 3 support. Updated the docs to instruct the user to install that version.

Updated nuget package to rc3

---

aspnetcore/host-and-deploy/health-checks.md

Fixes #14662 
The link to a "depreciated" package repo is a bit confusing. We don't need the link. We can just refer to the new package/repo. If users want to know more, they can reach that info from the `AspNetCore.Diagnostics.HealthChecks` repo.
Thanks @cshell-incomm! :rocket:

Remove links to BeatPulse from Health Checks topic

---

aspnetcore/tutorials/first-web-api.md

`TodoApi` is written as `TodoAPI` in three places as follows:
- Folder name (line: 81): `cd TodoAPI`
- Namespace (line: 269, 270): `TodoAPI.Models`
This will fix all.

[FIX] Fix minor typos

---

aspnetcore/data/ef-mvc/read-related-data.md
aspnetcore/data/ef-rp/read-related-data.md
aspnetcore/mvc/views/razor.md

Fixes #14681
Discussion in #14668.
Turns out that the loc version ends up with the correct destination heading (i.e., `<h3 id="explicit-line-transition-with-colon">`), which would have been easy to deal with in the source links by merely updating three bookmarks to this destination from `xref:mvc/views/razor#explicit-line-transition-with-` to `xref:mvc/views/razor#explicit-line-transition-with-colon`. The problem is on the English-side: The destination header is rendered as `<h3 id="explicit-line-transition-with-">`, and that's no good.
Best solution is to remove the colon: It's not necessary to describe this section, and removing it fixes the cross-topic bookmark issue everywhere.

Bookmark update

---

aspnetcore/tutorials/first-web-api.md

There are problems with spacing in a few different places as follows:
- Redundant white spaces in the line 226, 281, and 320.
- No space in the line 402 between the words "...in its" and "`id` parameter."
This will fix all.

[FIX] Fix spacing problems

---

aspnetcore/migration/22-to-30.md

Fixes #14695
* Clarify EFCore package by naming the package and linking out to NuGet.
* Disambiguate the providers remark by moving it down a line so that it's just implying that 'if you need this, go here.'
Thanks @sbsw! 🏍

Clarify EFCore package

---

aspnetcore/tutorials/publish-to-iis.md

While the current link is correct, this clarifies the specific version.
This page states the Update 3 is required: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore30

Clarify that Visual C++ 2015 Redistributable needs Update 3

---

aspnetcore/blazor/hosting-models.md

`components-reconnect-failed` is renamed to `components-reconnect-rejected` so just updating this

components reconnect status failed is renamed

---

aspnetcore/mvc/models/validation/sample/Models/User.cs

The AdditionalFields property of the [Remote] attribute is for the other fields that you want to relate but in the sample code, the field is referring to itself as an additional field.

Fix in AdditionalFields property sample

---

aspnetcore/tutorials/signalr-typescript-webpack.md

There was an extra `::: moniker-end` in the document that was casing the end of the document to appear regardless of the version, causing duplicate content to appear.
Fixes #14815

Remove extra moniker-end tag causing duplicate content

---

aspnetcore/fundamentals/host/web-host.md

Fixes #14857
`IHostApplicationLifetime` and `IWebHostEnvironment` work in an app targeting `netcoreapp3.0` and using the Web Host.

Web Host updates for 3.0

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/components.md

Fixes #14685
[Internal Review Topic (links to the *Import components* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0&branch=pr-en-us-14840#import-components)
* Ignore the date update for the web API topic. It's a quick fix to cover updates on a PR this morning that merged without the correct date.
* Let's make this section consistent with the rest of the topic and the common sample app by going with "BlazorSample" project naming.
* Check carefully on Bullet 3 ...
As a local test, I placed the common Blazor sample in a folder named *BlazorSampleFOLDER* and renamed the project `BlazorSampleFile` (*BlazorSampleFile.csproj*) to see how it resolved the namespaces (*obj* folder assets). This *seems* correct based on that behavior ... i.e. ... …

Add @namespace to components doc

---

aspnetcore/fundamentals/servers/httpsys.md

These cross-links fail and generate build warnings at this time. We'll add these back when they become available.
cc: @shirhatti

Temporarily remove API reference

---

aspnetcore/fundamentals/error-handling.md
aspnetcore/fundamentals/middleware/index.md

Comments in the markdown will help us catch these when these docs are revisited in the future and these API endpoints are available in the API docs.

Drop some API links that aren't available at this time

---

aspnetcore/fundamentals/middleware/index.md

The comment that I set up earlier to hold a note for future update didn't work with 'xref' on it.

Remove 'xref' from comment

---

aspnetcore/mvc/models/validation/sample/Controllers/UsersController.cs
aspnetcore/mvc/models/validation/sample/Views/Shared/_Layout.cshtml
aspnetcore/mvc/models/validation/sample/Views/Users/CheckName.cshtml

Fixes #14931.
There's a bit of a quirk in the UI with two fields being used for the same validation rule, in that the error message is only shown for the most recently changed input from the two. I don't think that's a big problem for the sample, which demonstrates a working `AdditionalFields` property and clears up any confusion re how the property should be used (see #13216).

Demo RemoteAttribute.AdditionalFields in Validation sample.

---

aspnetcore/migration/22-to-30.md
aspnetcore/performance/performance-best-practices.md
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/FireAndForgetSecondController.cs
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/MyFirstController.cs
aspnetcore/signalr/configuration.md

* SignalR now uses System.Text.Json
Starting in 3.0, SignalR no longer defaults to using Newtonsoft.Json
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#systemtextjson-is-the-default-protocol
* Address PR feedback
* Documentation -> documentation
* Apply suggestions from code review
Co-Authored-By: Scott Addie <10702007+scottaddie@users.noreply.github.com>
* Update configuration.md (#14958)
* Update configuration.md
* Update configuration.md

Merge to live part II 10-9

---

aspnetcore/tutorials/signalr.md
aspnetcore/tutorials/signalr/sample-snapshot/3.x/Index.cshtml

Fixes #14810
The location of signalr.js was incorrect according to Target Location set
up when Client-Side Library was added earlier in tutorial.

Updated signalr script tag (#14810)

---

aspnetcore/host-and-deploy/iis/development-time-iis-support.md

Fixes #14087
It's called the "**Start Debugging**" button actually. *Who knew?!!* :smile: lol
Thanks @abukres! :rocket: ... you're correct, and I found a place that we can link that to avoid having to put an image into the topic.

Rename and link the 'Run' (Start Debugging) button

---

aspnetcore/fundamentals/configuration/options.md

RequiredAttribute etc comes from the System.ComponentModel.DataAnnotations namespace.
Previously implied coming from Microsoft.Extensions.DependencyInjection

Add attribute namespace

---

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

Fixes #14178
* Temp workaround until https://github.com/aspnet/websdk/issues/888 is investigated/resolved.
* I leave the prior text in place in a comment ... easy to revert this on the next doc update.
* I go with `dotnet build` for all four examples (but I only tested the first one):
* Folder
* MSDeploy
* MSDeploy package
* Azure Kudu
... if it's known that the problem only pertains to folder publishing, let me know, and I'll make an update here. If it's not known on the others and you'd rather not show `dotnet build` for them for now, I can run an Azure publish and see what happens. :ear:
Thanks @Aszan for the report.

Use dotnet build with publish profiles for now

---

aspnetcore/security/key-vault-configuration.md

This is just a suggestion - and maybe it was just me, but when reading the section *Use Managed identities for Azure resources*, I didn't find it obvious that you still need the `KeyVaultName` setting specified. 
I thought the setting was only required if using the *Use Application ID and X.509 certificate for non-Azure-hosted apps* approach.
If the setting is not present, this leads to an error like the following during startup:
*Unhandled Exception: System.UriFormatException: Invalid URI: The hostname could not be parsed*
```
....
at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
...
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```
Feel free to …

Add KeyVaultName for Azure Managed Identities

---

aspnetcore/fundamentals/servers/httpsys.md

Fixes #15076
See :point_right: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/HttpSys/src/HttpSysOptions.cs#L95-L117
> \<summary>
> Gets or sets the maximum number of concurrent connections to accept, -1 for infinite, or null to
> use the machine wide setting from the registry. The default value is null.
> This settings does not apply when attaching to an existing queue.
> \</summary>
Thanks @SoeTien! 🏍

HTTP.sys options default max connections

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/MonitorLoop.cs
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/QueuedHostedService.cs
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/TimedHostedService.cs

Fixes #14746 
Fixes #12342
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&branch=pr-en-us-14765)
On stopping, the sample revision throws ...
```console
Unhandled exception. System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
at BackgroundTasksSample.Program.Main(String[] args) in C:\Users\guard\Desktop\BackgroundTasksSample\Program.cs:line 40
at BackgroundTasksSample.Program.<Main>(String[] args)
```
Even if that …

Hosted Services sample updates

---

aspnetcore/mvc/controllers/filters.md

Fixes #15090.
I think staying away from the *unless an exception was thrown* statement here might be the best option. It was just saying that the response might not have been written yet if an exception was thrown somewhere in the pipeline, but I think it ended up confusing things. If someone wants to write to the response in `OnResultExecuted`, they could check whether or not an exception was thrown (or even use [`HttpResponse.HasStarted`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse.hasstarted?view=aspnetcore-2.2#Microsoft_AspNetCore_Http_HttpResponse_HasStarted)), but that seems like a slightly more advanced scenario to me.

Address review note re Result Filters and exceptions.

---

aspnetcore/performance/caching/memory.md

Replaces instances of "[cache] memory size [limit]" with "cache size limit" where appropriate.  
Clarifies language to ensure that we're not referring to the cache's `SizeLimit` property as a "memory size limit".

[MemoryCache] Nit - Clarify cache size limit

---

aspnetcore/host-and-deploy/windows-service.md

Fixes  #14239
* The ask is to note in passing that HTTPS should be configured for a Windows Service that uses auth. I think we can all this out with a change in the existing coverage for endpoint configuration.
* I'm going to remove "(Kestrel)" and "(HTTP.sys)" in passing because those are called out in the topic titles that are rendered in the topic.
cc: @CeciAc @taori

Enhance Windows Service HTTPS coverage (auth note)

---

aspnetcore/test/integration-tests.md
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs

Fixes #14354
* I tested this with both an in-memory dB and SQL Server dB.
* Hoping that we can go with something simpler than the lower-level approach taken by the engineering sample (i.e., can't we just `services.AddDbContext<T>(...)` in the normal way after killing the existing service registration as I show here?).
* Interestingly, I didn't need to keep the `UseInternalServiceProvider`. I have no real confidence tho in this move outside of it ✨ *Just Works*:tm: ✨ in testing here. Do you want to ping an EF Core :cat2: to make sure that this approach is sound?

Integration Testing topic+sample dB replacement

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #15095
* Is it ok to go with `ConfigureKestrel` over `UseKestrel` here?
* While here, let me fix up something that's been bugging me for a while ... no need to show extra code around `webBuilder` in these examples. The overall layout of the `CreateHostBuilder` method is covered at the top of the doc.

CipherSuitesPolicy for Kestrel cipher suite filter

---

aspnetcore/blazor/components.md

Fixes #14260
[Internal Review Topic (links to *Lifecycle methods* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0&branch=pr-en-us-14844#lifecycle-methods)
* The issue ask (#14260) includes addressing this in the Razor syntax doc, but this doesn't seem to fit there because it's not really "Razor syntax." It seems to be an instruction for component authoring/behavior.
* There's an issue to create a [new Blazor component lifecycle doc page (aspnet/AspNetNet.Docs \#14253)](https://github.com/aspnet/AspNetCore.Docs/issues/14353), so I think what makes sense today is to add explicit NOTES to the *Lifecycle methods* section to clarify that these methods are where async is done. The guidance can be fleshed out by engineering when the new topic …

Blazor async work guidance

---

.ghal.rules.json

I ported the existing ruleset. I need to merge before I can deploy the tool update.
The new tool does not support the old v1 and v2 schemas anymore.

Update .ghal.rules.json for v3

---

aspnetcore/includes/blazor-prerendering.md

Changed `InvokeAsync<object>` to `InvokeVoidAsync` for functions that we don't need the result or don't return something.
I thought that is appropariate even if the specific function returns a value since we don't need it in the sample. This is also done to reflect the use of the code below where we explicitly specify the type that we actually want back `InvokeAsync<string>`

Changed InvokeAsync<object> to InvokeVoidAsync

---

aspnetcore/tutorials/first-web-api.md

Addresses https://github.com/aspnet/AspNetCore.Docs/issues/15087
The pre-3.0 version of the tutorial uses jQuery. This PR replaces Fetch references in the text with jQuery.

Replace Fetch API references in 2.x web API tutorial

---

aspnetcore/razor-pages/filter.md

Removed superflous `be', "... methods are be called." => "... methods are called." (It could also have been "...methods will be called." I guess)

Remove unnecessary word in filter.md

---

aspnetcore/migration/22-to-30.md

Fixes #15196
Doesn't seem necessary to show the "before" aspect. Let me know if you'd like that here.
We can't API-link `UseTestServer` yet ... 3.0 API isn't available yet.

TestServer with the Generic Host

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #14977 
[Internal Review Topic (direct link to *Service registration methods* section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1&branch=pr-en-us-15044#service-registration-methods)
Given that the table focuses on other info (e.g., signatures, automatic disposal, etc.), any objection to making all of the examples singletons?
Thanks @natenho 🏍 and @serpent5! 🎸

Registration examples in DI extentions table

---

aspnetcore/fundamentals/configuration/index.md

Fixes #15182
Indicate to the reader that `GetValue` is for single values with noncollection types.
Thanks @IanKemp! :rocket:

Configuration language enhancement

---

aspnetcore/grpc/migration.md

https://twitter.com/J0rgeSerran0/status/1185941180888080384

Fix typos on gRPC migration doc

---

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/Tab.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/Tab.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/components.md

Fixes #15206
* Calling `RemoveTab` in `Dispose` doesn't seem to be required. Is this update sane, or is there another approach that it should show?
* Engineering issues that touched on `StateHasChanged` and `Dispose` weren't *grokable*:tm: in this context. Do you want to say more in the NOTE?

Blazor StateHasChanged/TabSet example

---

aspnetcore/blazor/get-started.md

F5 is problematic with Blazor WebAssembly apps. Instead let's recommend Ctrl+F5

Run Blazor without debugging

---

aspnetcore/host-and-deploy/blazor/webassembly.md

[EDIT by guardrex to add issue number]
Fixes #14859
Adding Apache2 (httpd) example configuration to *Host and deploy* for Blazor webassembly.
Example is tested on CentOs7.

Apache configuration to Host Blazor webassembly

---

aspnetcore/razor-pages/index.md

Updated reference to customer model in the Validation section to the following reference: [!code-cs[](index/3.0sample/RazorPagesContacts/Models/Customer.cs)]. Customer model in "Write a basic form" section and the "Validation" section will now reference the same code.

Update reference to customer model

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Program.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Program.cs

Fixes #15300
Not tested given that ...
https://github.com/aspnet/Extensions/blob/d656c4f7e22d1c0b84cab1b453c50ce73c89a071/src/Hosting/Hosting/src/HostBuilder.cs#L191
https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/WebHostBuilder.cs#L269
... but let me know if I should run a round of testing on these updates.
Thanks @RehanSaeed! :rocket:

Remove SetBasePath from config examples

---

aspnetcore/blazor/routing.md
aspnetcore/docfx.json

Fixes #15172
This is a global scenario: "Blazor" shouldn't be localized in any repo doc (as opposed to sprinkling in the metadata prop on the individual Blazor topics).

No localization for "Blazor"

---

aspnetcore/razor-pages/ui-class.md

This fixes rendering of the configuration for TypeScript integration.
Thanks!
For context:
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#feedback

Fix TypeScript target snippet in Razor UI docs

---

aspnetcore/fundamentals/http-requests.md
aspnetcore/includes/not30.md

Fixes #15328
@serpent5  once this S&Ms, you can do the update in the 3.0 moniker section. You won't need to do any moniker juggling.
https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1&branch=pr-en-us-15329

Prepare IHttpClientFactory for 3.0 update

---

aspnetcore/fundamentals/configuration/options.md

Fixes #15348
I think the only salient point there is to inform the dev of the namespace. The package(s) are already addressed by the *Package* section of each doc version.
Thanks @IanKemp! :rocket: ... Hao will confirm on any namespace change. There were changes ... perhaps twice going all the way back to 1.0. We're only looking at 2.1+ now for the topic; and IIRC, it's `Microsoft.Extensions.Configuration`. I'll add a commit to cross-link that to the API browser.

Options GetSection updates

---

aspnetcore/security/authentication/social/google-logins.md

Related to fix for  #14855 , small additional edit.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-1.0&branch=pr-en-us-15361)
- Moved the instruction line for the google package out of its own H2.  
- Moved it into first line of  ## Create a Google API Console project and client ID

google-login: Moved package instruction out of H2

---

aspnetcore/fundamentals/configuration/index.md

Addresses #15370
Added an example that shows how to clear the default configuration sources provided by `Host.CreateDefaultBuilder` to the _Default configuration_ section.

Add an example for clearing default configuration sources

---

aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/social-code/3.x/StartupGoogle3x.cs

Fixes #15388
Referenced snippet was missing, given the size of the target file I've removed the reference rather than adding the snippet.
`StartupGoogle3x.cs` line 6 was a bit too long and wrapped halfway through a statement so I've dropped it down a line.

Fix google authentication main code fragment missing

---

aspnetcore/blazor/handle-errors.md

Fixes #14202
This is a small shift to the phrasing to move it away from "the circuit **_contains_** the components."
Thanks @Legends! 🎸

Blazor prerendering language update

---

aspnetcore/security/authentication/individual.md

Remove link the SMS 2FA, SMS 2FA is no longer recommended
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-3.0

Remove link the SMS 2FA, no longer recommended

---

aspnetcore/host-and-deploy/health-checks.md
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/SampleApp.csproj
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj

Fixes #15473
Minor text+sample change:
* In 3.x, the `Microsoft.AspNetCore.Diagnostics.HealthChecks` package is implicit from the shared framework.
* The 2.x text is fine as it is.
* The `Microsoft.Extensions.Diagnostics.HealthChecks` package comes in transitively via the `Microsoft.AspNetCore.Diagnostics.HealthChecks` package, so there's no need for the app to reference it.
Thanks @lol768! :rocket:

Health checks package reference updates

---

aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/MemoryHealthCheck.cs

Entirely possible I've missed something obvious, but when trying this sample as-is I noticed it seemed to always report the failure state (degraded) even when the memory threshold hadn't been hit.

Derive status from allocated < options.Threshold

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationProvider.cs
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Pages/Index.cshtml
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationProvider.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Pages/Index.cshtml

Fixes #15119
* Makes the `EFConfigurationProvider` example dict with case insensitive keys.
* Rolled right into the Index page display, too.
Nice one @tfabraham! :rocket::guitar::racing_car::beers: Would you like to review this before I ping engineering?

Configuration key (case) enhancement

---

aspnetcore/security/authentication/certauth.md

Per discussion with @HaoK, update the method referenced in the verbiage.

Replace invalid method name in cert authN doc

---

aspnetcore/fundamentals/logging/index.md

Fixes #15370
**_Highly prototyped_** for discussion/modification.

Surface Program class logging pattern

---

aspnetcore/fundamentals/index.md

Fixes #15556 
Surface control of *wwwroot* in the section that pertains to the web root. We cross-link this section from over a dozen places around the docs, so this should surface it generally.

Surface project item to control static asset publishing

---

aspnetcore/security/authentication/certauth.md

Fix incorrect text to match code. Thumbprint is used to validate certificate, and not subject or issuer. fix from @blowdart

fixing text to match code changes in certauth.md

---

aspnetcore/signalr/scale.md

Adding no-loc metadata to prevent the term "SignalR" from being over-localized.

Adding no-loc metadata

---

aspnetcore/mvc/models/file-uploads.md
aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Pages/Index.cshtml.cs
aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Pages/Index.cshtml.cs

Fixes #15337
Thanks @Legends. Given the workload, I don't recommend that we address the sample/topic directly at this time (except I spotted one that we can easily drop). Also, I note that we have chunking on the [File Uploads Tracking issue (aspnet/AspNetCore.Docs \#12285)](https://github.com/aspnet/AspNetCore.Docs/issues/12285) for future work. For now, let's call it out and see if additional community feedback comes in.
Pranav, can we do better than just saying, "use an alternative approach that doesn't rely upon a single `MemoryStream` for holding an uploaded file's content"? Can we offer more specific advice, or do you feel that merely calling this out is fine for the time being?

Stream was too long

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/class-libraries.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/index.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/routing.md
aspnetcore/blazor/state-management.md
aspnetcore/blazor/supported-platforms.md
aspnetcore/docfx.json
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/index.md
aspnetcore/razor-pages/sdk.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/server.md
aspnetcore/signalr/scale.md
aspnetcore/tutorials/build-your-first-blazor-app.md

Fixes #15614
* Opened a Blazor.Docs project issue to move back to global if/when supported. https://github.com/aspnet/AspNetCore.Docs/issues/15627
* Removes the entry from the *docfx.json* file.
* "Blazor" appears in a handful of ASP.NET Core topics (non-Blazor), so I add the metadata to those topics as well.
* In the SignalR topic, reposition the metadata entry to preserve **_alphabetical order_**. *ei ei ei* ... let's **_NOT_** go back to those messy days. :smile: lol
* I don't extend the "SignalR" entry out to other topics, not even in the Blazor topics. There are ... mmm 🤔 ... perhaps *40-ish topics* that would need a manual change. I'm 🏃 on a lot of priority Blazor issues this weekend; so if you want me to handle the SignalR work, let's work this PR in now and open an issue for …

Apply no-loc for "Blazor" to topics

---

aspnetcore/migration/22-to-30.md

I recently helped a customer migrate an ASP.NET Core 2.1 app to 3.0. Most of the breaks we ran into were documented, but a few were not. 
This PR adds some additional text around a few areas that were unclear to the customer based on current docs (changes to custom authorization handlers based on endpoint routing differences, URL.Link changes, and that AllowSynchronousIO settings must be made per-server (or per-request)).

Expand 2.2->3.0 migration guidance

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

Note: GetRequiredPolicy was removed/replaced in 3.0, but the docs were updated already to include the obsolete (now non existent method)
Fixes https://github.com/aspnet/AspNetCore/issues/13762
@Rick-Anderson @guardrex not sure who can help review/edit this update.

Update documentations for GetFallbackPolicy

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes #15649
* I think we can merely call out the package is added/present for the Worker SDK and implicit for the Web SDK.
* Strip out the bits on a Web Host and Generic Host pair of samples. Those went away recently (3.0 updates era), so those bits no longer apply.

Hosted services package reference

---

aspnetcore/host-and-deploy/health-checks.md

Fixes #12229
There aren't API notes on the purpose, so I *guessed* that it's to pass args (practically speaking).
Recommend in-text only at this time (not in the sample app) due to many high priority doc issues at this time. It's a candidate to roll into the sample app on a future doc+sample update.
Thanks @schummbo! :rocket: ... sorry that it took so long. We've been 🏃😅 for a while now.

AddTypeActivatedCheck coverage

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/security/authentication/certauth.md

As discussed in https://github.com/aspnet/AspNetCore/issues/15351, the behavior of the "Defaults" methods could be clarified a bit.
I had a few minutes so I took a stab at it.
Internal Render:
* [Kestrel web server implementation in ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&branch=pr-en-us-15697#endpoint-configuration-2)
* [Configure certificate authentication in ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0&branch=pr-en-us-15697#configure-your-host-to-require-certificates)

Add a clarifying note about Kestrel's ConfigureEndpointDefaults and ConfigureHttpDefaults methods

---

aspnetcore/includes/built-in-TH.md
aspnetcore/toc.yml

Fixes #15724
~Note to self: `[comment]: ` ... nice trick. I could'a used that a few times. :+1:~
The build is choking on that Options Tag Helper `[comment]:` placeholder. It's warning that the UID isn't there, which is true. Let's just add that topic when/if it becomes a thing.
Thanks @richardcox13! :rocket: ... do you spot any that I missed?

Tag Helper navigation

---

aspnetcore/fundamentals/configuration/options.md

Fixes #12121
* Much of the SO answer is already covered. An explicit contrast between `IOptionsMonitor` and `IOptionsSnapshot` is added here in the *Reload configuration data with IOptionsSnapshot* section. If you'd like to cover anything else from the SO answer, which additional points should be added?
* There another small touch up here in the (formerly named) *Options provided by a view model or with direct view injection* section. It's just a passing (hopefully good) improvement.

Difference between IOptionsMonitor/IOptionsSnapshot

---

aspnetcore/migration/22-to-30.md

The current link "Complete list of breaking changes in the ASP.NET Core 3.0 release" takes a user to the second page

Update page number (2->1) for "Complete list of breaking changes" link

---

aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs

In `AddDbContext<T>((options, context) => { … })`, that `options` is actually the service provider, and `context` is the context options builder.
So this changes that call to be just `AddDbContext<T>(options => { … })` which makes it a bit clearer since it also doesn’t need the service provider.

Rename parameters to avoid confusion

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes #15701
Set of updates seeking to:
* Generally improve layout and coverage (e.g., bullets to paragraphs, xref API cross-links).
* Surface that either `ExecuteAsync` must complete or yield for `StartupAsync` to complete. Trying to minimally capture the main point in [BackgroundService blocked the execution of whole host (aspnet/Extensions #2149)](https://github.com/aspnet/Extensions/issues/2149) and cross-link the engineering issue for the reader's further understanding.
❓ ... do you want it to specifically call out `await Task.Yield()` for the top of `ExecuteAsync` for scenarios where `StartupAsync` will be blocking? ... or should we let the cross-linked engineering issue capture that concept for the reader if they need to dig deeper? ... or even just wait until the engineering issue …

BackgroundService enhancements

---

aspnetcore/fundamentals/logging/index.md

Fixes  #3279
There's a sweet spot for a quick call out that will resolve this for readers. It can be done right where the **Level** is set for this provider.

Clarify log streaming level setting

---

aspnetcore/signalr/version-differences.md

Fixup for #15703 to clarify that SignalR auto reconnect is opt-in in SignalR Core, not legacy SignalR.

Clarify that SignalR auto reconnect is opt-in in Core

---

aspnetcore/mvc/views/layout.md

As noted in the issue #11860, the RenderSection example is confusing and may create a fallacious impression that RenderSection can be used only inside other section definition. It's overloaded with information that is unnecessary for RenderSection understanding.
Also more appropriate tilde (~) notation/operator is used for resources paths.

Fixes issue #11860 - confusing RenderSection example

---

aspnetcore/fundamentals/http-context.md

Controllers using `ActionResult` must inherit from the `Controller` class.

Inherit from Controller

---

aspnetcore/blazor/handle-errors.md

Fixes  #15624
*Only* Blazor Server, correct? Even if so, I wonder if we need a sister section for Blazor WebAssembly that merely states that the dev should look at the dev tools console. We do say in the live topic ...
> During development, Blazor usually sends the full details of exceptions to the browser's console to aid in debugging. 
... down in the *Log errors with a persistent provider* section.
I'm thinking 🤔 that we should add a short section on this PR at the top near this new section calling that guidance out for Blazor WebAssembly to balance the coverage up there. We can leave that existing line in place ... it's true for both hosting models. Should I do it?

Blazor Server detailed errors experience

---

aspnetcore/mvc/models/validation.md

Fixes #15822.
I mentioned in my previous PR for this topic that I thought the value here might be wrong. I've checked it in the source and in a sample project for both 2.2 (with different compat versions) and 3.0 to confirm it should be changed.

Corrected shown default for MaxValidationDepth.

---

aspnetcore/razor-pages/index.md

The Startup.cs example should also highlight line 36 where MapRazorPages() is called as it's essential to razor page routing.

Highlight MapRazorPages() in Startup.cs example

---

aspnetcore/host-and-deploy/azure-apps/index.md

Fixes #14000
The way this was originally written it said that the bitness setting only mattered for FDD apps. However, I think now the guidance is to set the platform bitness (in Azure) to match the app. Therefore, I made that part of this content generally apply to both FDD **_and SCD_**. Correct me if I'm mistaken on that point, and I'll revert that change back to *FDD only* for Azure's bitness setting. :ear:
On another point, The "A-series compute" level of Azure is the same as "Basic"? ... is that correct? I add "(Basic)" where mentioning when the Azure platform scenario becomes available to a dev in the portal (i.e., when the swtich is enabled so that they can select 64-bit apps). :ear:
Finally, I call out ...
> Confirm that the app's publish settings (for example, in the Visual …

Azure App Service bitness enhancements

---

aspnetcore/host-and-deploy/blazor/index.md

Fixes #15546
Getting a bit tricky, so check me carefully. :eyes:
* I think that the final guidance here for using `--pathbase` to run locally can just say to use the `dotnet run` option `--pathbase` with **Blazor WebAssembly** apps.
Let me know if you think I need to re-test both hosting models in a sub-app config.
* For `UsePathBase`, the engineering guidance from Javier is "it might be necessary," but that's not specific. Can we clarify the scenarios where `UsePathBase` must be used?
Currently, this is written as tho if you change the `<base>` tag to accomodate an explicit base path that you must also use `UsePathBase` (in a Blazor Server app). If that's right, then the content on this PR is good.

Blazor Server UsePathBase

---

aspnetcore/blazor/get-started.md
aspnetcore/blazor/templates.md
aspnetcore/toc.yml

Fixes #13757
Fixes #15863
Internal Review Topics:
* [Templates](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.0&branch=pr-en-us-15862)
* [Get Started](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&branch=pr-en-us-15862)
Notes:
* I'm floating a *templates* focus for this *project structure* topic (i.e., the title and URL) because it covers app structure **_and_** affords an opportunity to discuss further details about the templates as needed.
* Looks like :eyes: we can activate the VS4Mac instructions for Blazor Server. In spite of the `blazorwasm` template being installed (and a restart just for good measure), VS4Mac only shows **Blazor Server App** in the list.

Blazor templates topic

---

.openpublishing.redirection.json
aspnetcore/security/authentication/index.md
aspnetcore/toc.yml

In the ASP.NET Core docs, the security and authorization sections have 'overview' docs that give a high-level view of the topic's concepts.
Authentication docs just dive right into ASP.NET Core Identity, though, and I've worked with a couple customers recently who struggled to get started with ASP.NET Core auth because they didn't understand some of the concepts (what is a 'scheme' and how do you register one?, what does 'challenge' mean in an auth context?).
I've added a doc here meant to be a quick intro to authentication topics for folks who may not be familiar with some of the terms or how ASP.NET Core authentication works at a high level.

Add an authentication overview doc

---

aspnetcore/migration/22-to-30.md

Looks like an editing mistake. Perhaps intended to go under heading on Breaking API changes above?
Suggest it's removed as it is covered in [section](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#addauthorization-moved-to-a-different-assembly) earlier and in 2 of the 3 links under [Breaking API changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0).

AddAuthorization not related to Core 3.0 on Azure

---

aspnetcore/fundamentals/localization.md

This include:
- Fix Localization & Generic blog post link
- Remove my blog post link for Localization 3.0, coz the intend was to have it before we update the docs to 3.0

Fix Localization & Generics blog post link

---

aspnetcore/fundamentals/localization.md

@Rick-Anderson this is a reminder to merge this when ASP.NET Core 3.1 is shipped. A little bit history on this, I created a PR in localization long time ago, I supposed to be merged in 3.0, but the branch has been changed before merge this
After that I wrote a blog post about Localization 3.0, since then I got some feedback that this not working on 3.0, then I realize something goes wrong, until Ryan confirms
For that I pushed this PR, also I will change my blog post

Fix ASP.NET Core version for Content-Language header

---

aspnetcore/blazor/handle-errors.md

Fixes #15938
* Passing nit for this line ... adding "the following" composes the line better.
* This is written in the sense that they're *always* invoked in the framework because they all override when placed into developer code. Just confirming here that that's the case ... Blazor *always* invokes these *somewhere* ... dev code or framework code.

Blazor Handle Errors language improvement

---

aspnetcore/web-api/http-repl.md

The aspnet/HttpRepl repo was moved into the dotnet org. Update the HTTP REPL doc accordingly.

Update aspnet/HttpRepl to dotnet/HttpRepl

---

aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #15893
* Call out the need to restart apps for shared framework upgrades.
* This is a good time to update the stale instructions to match the latest download process.
* Update IIS ... <3.0 keeps "roll-forward" language ... >=3.0 provide "restart" language.
* Surface switches for SCD-only hosting.

Linux and IIS instruction updates

---

aspnetcore/release-notes/aspnetcore-3.1.md

Addresses #15958 
@scottaddie Do you want "Razor" or "razor" code language? "Razor" makes me think of Razor syntax. "razor" perhaps leans more toward Razor component (i.e., *.razor* file extension). This PR currently uses `razor`.

Blazor content for What's New 3.1 topic

---

.openpublishing.publish.config.json

In v2, `xrefservice` can be defined in `docfx.json` then the user can query `uid` universally, which will be removed during the migration to v3 and related tags should be added to `.openpublishing.publish.config.json`.
We created this pull request to make the repository ready to migrate to docfx v3. This PR will not change any published pages.

Add `xref_query_tags` to resolve xref in docfx v3 build

---

aspnetcore/fundamentals/http-context.md

Fixes #15967
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.1&branch=pr-en-us-15973)
Might be straightforward enough that we don't need engineering to look. There aren't any significant code changes here.
* Version whole topic to >=2.1.
* Revise in-text versioning for `ConfigureServices` example to >=3.0/<3.0.
* API docs xref cross-links.
* Remove in-code non-localized comment text to the localized text.
* Minor nits.
Thanks @Allann! :rocket:

Update Access HttpContext to 3.x

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/logging/index/samples_snapshot/3.x/TodoApiSample/Program.cs

Fixes #16005
[Internal Review Topic (links to *Create logs in the Program class* section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.1&branch=pr-en-us-16018#create-logs-in-the-program-class)
* I couldn't merely extend the snippet: The `CreateHostBuilder` method in the 3.x sample app is used as a snippet for another example and shows more than is needed to make the point. Therefore, I use a snapshot file for this.
* This update is for the 3.x content only. We're good on 2.x ... that example was able to wrap the `CreateWebHostBuilder` method into its snippet for display.
Thanks @MV10! :rocket: Your approach is fine for scenarios that don't want to use `CreateHostBuilder`, but we need to stick with it as much as possible due to (for …

Enhance logging in Program example

---

aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/lifecycle.md
aspnetcore/fundamentals/error-handling.md
aspnetcore/migration/webapi.md
aspnetcore/mobile/native-mobile-backend.md
aspnetcore/mvc/controllers/actions.md
aspnetcore/mvc/controllers/application-model.md
aspnetcore/mvc/controllers/areas.md
aspnetcore/mvc/controllers/routing.md
aspnetcore/mvc/views/overview.md
aspnetcore/mvc/views/tag-helpers/authoring.md
aspnetcore/mvc/views/working-with-forms.md
aspnetcore/razor-pages/index.md
aspnetcore/release-notes/aspnetcore-2.0.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/security/anti-request-forgery.md
aspnetcore/security/authentication/add-user-data.md
aspnetcore/security/authentication/azure-ad-b2c-webapi.md
aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/razor-pages/search.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/readme.md
aspnetcore/web-api/advanced/conventions.md

Dropping 'decorate'/'decorated' for attributes per guidance for MT.

Drop 'decorate'/'decorated' for attributes

---

aspnetcore/security/enforcing-ssl.md

Addresses #15249
Fixes #16053
This is a quick patch to correct an inaccuracy wrt default being 443. This sentence isn't necessary. Let's 🔪 it. The *Port configuration* section earlier is where the logic of port selection is handled.
I'll also paste the source cross-links into #15249 so that it will be fast 🏃 to get the latest framework logic for that issue when it's worked. [**EDIT ... _Done!_**]
Thanks @shoe788! 🎷

Remove 443 default line from Enforce HTTPS

---

aspnetcore/blazor/get-started.md

VS4Mac now defaults to 3.1 for new projects, and 3.1 is no longer in preview. The instruction should say to select the target framework.

Blazor VS4Mac Get Started instruction update

---

aspnetcore/signalr/configuration.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1&branch=pr-en-us-16060)
Fixes #15666 
Reorganized moniker sections and condensed where needed for file:
signalr/configuration.md

Cleaned up moniker versioning for ASP.NET Core SignalR configuration

---

aspnetcore/docfx.json

As mentioned in PR #15907 ,  the config is not needed now.
@scottaddie Please help to review and merge the PR

remove useless config `xrefservice`

---

aspnetcore/web-api/http-repl.md

Description: Three dashes in a row act similar to backticks (\`\`\`) and leave content un-localizable

C150960: Changing three dashes by three underscores to avoid issues on localized pages

---

aspnetcore/security/authentication/windowsauth.md

Fixed typo (`srever` => `server`) in the Windows Authentication page

Fixed typo in the Windows Authentication page

---

aspnetcore/host-and-deploy/health-checks.md
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/CustomWriterStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/BasicStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/CustomWriterStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/DBHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/DbContextHealthStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/LivenessProbeStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/ManagementPortStartup.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj

Addresses #5495 
Addresses #15473
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2&branch=pr-en-us-16204)
* 3.1 sample app confirmed running.
* Let's put the `System.Text.Json` approach in here but also retain the existing `Newtonsoft.Json` approach. A directive in the file makes it easy for the dev to switch back and forth.
* WRT the `System.Text.Json` approach: I couldn't get `WriteNumber` to work with a directly casted object (`(Decimal)item.Value`). I ended up performing the cast on a separate line with (`Convert.ToDecimal`) to make it happy.
cc: @lol768

Health Checks sample 3.1 updates

---

aspnetcore/mvc/views/view-components.md
aspnetcore/mvc/views/view-components/samples_snapshot/2.x/Startup.cs

Fixes #10385.
The topic itself needs some future work:
* 3.1 update.
* There are a few e.g. 1.1 monikers that need cleaning up.
* The current description of the view search path is incomplete. With RP, the page's path is also traversed segment by segment.
These are just points I've noted in passing. I won't address them as part of this PR.

Customizing the view search path for View Components.

---

aspnetcore/security/key-vault-configuration.md

Fixes #16117
* Unquoting the key vault name in Azure CLI command option values.
* Originally, it worked. It followed the Azure doc :point_right: https://docs.microsoft.com/en-us/azure/key-vault/tutorial-net-windows-virtual-machine#assign-permissions-to-the-vm-identity
* Unquoted (on this PR) follows a different Azure doc :point_right: https://docs.microsoft.com/en-us/azure/key-vault/quick-create-net#give-the-service-principal-access-to-your-key-vault
* I've alerted the Azure doc cats about the discrepancy in two Azure topics :point_right: https://github.com/MicrosoftDocs/azure-docs/issues/44749
Thanks @jeroenwo! 🎷

Update Azure CLI command syntax

---

aspnetcore/mvc/models/model-binding.md
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Controllers/CustomJsonController.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/JsonConverters/ObjectIdConverter.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/ModelWithObjectId.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/ObjectId.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Startup.cs

Fixes #15705.
[Customize model binding with input formatters](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1&branch=pr-en-us-16261#customize-model-binding-with-input-formatters)

Customizing the System.Text.Json-based Input Formatter

---

aspnetcore/tutorials/first-mvc-app/adding-controller.md

Contributor has reported source content issue. 
Description: Colin in link name is segmenting strings in Localized pages

CC170507: Escaping colon sign to avoid segmented strings in Loc pages

---

aspnetcore/security/authentication/certauth.md

A lot of cert auth errors are caused by incorrect DNS. Just added a note to the docs for this

Adding a note for a common configuration error in cert Auth

---

aspnetcore/mvc/advanced/custom-model-binding.md

Fixes #16374.
I've also changed the "View or download sample" link to match the style used in the other topics.

Remove line highlight and use standard sample code link.

---

aspnetcore/signalr/scale.md

The sticky session was a little bit vague so that one might think even if they use just WebSocket for all the clients and turn off negotiations on clients, and use Redis backplane they still might need "sticky sessions". There was a clarification by @davidfowl [here](https://twitter.com/davidfowl/status/1212068926676275202?s=20)

update(scale-out): docs for redis backplane

---

aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md

Fixes broken link to blog post about Azure publish. Link broken due to Xamarin blog migration.

Updated broken link for VS for Mac / Azure publish

---

aspnetcore/test/integration-tests.md

Fixes #16000
Call out that the execution order was a breaking change for 3.0. There is no announcement to link for this, per se. All we would have to link is the Generic Host announcement, so we may as well just cross-link the Generic Host topic here instead.
Thanks @SaebAmini! 🎸

Service config execution order breaking change

---

aspnetcore/fundamentals/configuration/options.md

Fixes #14158
The main focus is to call out that named options are case sensitive. I'm going to kill some `&num;` characters in passing.
Thanks @nickalbrecht! 🌴

Named options are case sensitive

---

aspnetcore/release-notes/aspnetcore-3.1.md

The Component Tag Helper will be used within a CSHTML file. Updating the devlang from `razor` to `cshtml`.

change component devlang to cshtml

---

aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Program.cs

In the sample snippet code in page [gRPC services with C#](https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.1):
```csharp
static async Task Main(string[] args)
{
// The port number(5001) must match the port of the gRPC server.
var channel = GrpcChannel.ForAddress("https://localhost:5001");
var client =  new Greeter.GreeterClient(channel);
var reply = await client.SayHelloAsync(
new HelloRequest { Name = "GreeterClient" });
Console.WriteLine("Greeting: " + reply.Message);
Console.WriteLine("Press any key to exit...");
Console.ReadKey();
}
```
the gRPC channel `channel` instance is not disposed of. It should be, as `Grpc.Net.Client.GrpcChannel` is a `IDisposable` resource.
This PR fixes this, adding a call to `Dispose()`:
```csharp
static async Task Main(string[] …
```

gRPC Channel is disposed of after use

---

aspnetcore/tutorials/signalr-typescript-webpack.md

Noticed this while doing a check over some SignalR docs :). If you go to https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack and toggle the version selector to a version below 3.0, the `Prerequisites` header just disappears :). It wasn't duplicated when the doc was duplicated across monikers.

fix missing header in pre-3.0 version of signalr tutorial

---

aspnetcore/getting-started/index.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/getting-started/index?view=aspnetcore-1.0&branch=pr-en-us-16453)
Fixes #16450 
Updated prereq section to use standard 3.1 install include link and retested the topic instructions with 3.1.

Updated prereq to standard 3.1 install include link.

---

aspnetcore/fundamentals/logging/index.md

Fixes #16445
For this approach (just calling out the example and cross-linking), I **_don't_** link to a specific sample version to harden the cross-link for future releases (but I do mention which file within the sample that the reader should look at).
Conversely, would you prefer that I add a console app example to the Generic Host topic and then cross-link to that? If so, I'll close this and create a new PR adopting that approach. :ear:

Cross-link to Generic Host console app example

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

OpenAPI package latest version for asp.net core is rc5. It's better to update article to latest version, because we all like to copy-paste code from documentation.

rc5 is latest pre-release version

---

aspnetcore/index.md

In Migration from the .NET Framework the link to ASP core migration was broken

aspnetcore update index migration link

---

aspnetcore/blazor/get-started.md

There is no need to switch to the preview channel on Mac as VS for Mac uses 8.4 as of 8th Jan 2020.

Removed preview channel note

---

aspnetcore/signalr/scale.md

Relax current wording that advises against using Azure SignalR Service in _all_ on-prem deployments.
/cc @sffamily

Update SignalR Service guidance

---

aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/iis/development-time-iis-support.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/iis/modules.md
aspnetcore/host-and-deploy/iis/transform-webconfig.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/web-farm.md

Fixes  #15323
Some touches to cross-linking in the *Host and deploy* node.
There are two old topics virtually defunct from a maintenance standpoint cross-linked in the *Transform web.config* topic that contain useful, valid content for our transform topic ...
* [Web.config Transformation Syntax for Web Application Project Deployment](https://docs.microsoft.com/en-us/previous-versions/dd465326(v=vs.100))
* [Web.config Transformation Syntax for Web Project Deployment Using Visual Studio](https://docs.microsoft.com/en-us/previous-versions/aspnet/dd465326(v=vs.110))
Would you like me to copy the relevant content from those topics that we need&dagger; into our doc and drop those foul cross-links? If so, I'll open an issue to address it. I think I'll have time in February to do the work.
**we …

Host and deploy crosslink updates

---

aspnetcore/security/authentication/azure-active-directory/index.md

Fixes #16545
When we touched this on https://github.com/aspnet/AspNetCore.Docs/pull/15141, we ended up pointing to the V2 sample. This PR follows the instructions in the README and points the link to the `master` branch of the prior link with "archived and unsupported" noted to the reader. Is that the best way to go, or is there a good V1 sample link for this?
Thanks @fowl2! ⭐️

Update AD sample link to point to AD V1 version

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/host-and-deploy/windows-service/samples_snapshot/CustomSettingsExample.cs

Fixes #16515
* Add an MVC controller injection example to the introductory remarks to go with the existing RP  example.
* Improve the default config content for app settings (JSON) files. Improve the example steps using the sample app to demonstrate the File Configuration Provider working with default config (`CreateDefaultBuilder`). Version the content because there's a delta for the *appsettings.json* file between 2.x and 3.x.
* Remove 'you' lingo throughout the Configuration topic.
* In the Windows Service topic, enhance the coverage on the content root. Explain how it's set by `UseWindowsService` to `AppContext.BaseDirectory` when the app runs as a service. Clarify that setting a base path isn't required for additional config files loaded in `ConfigureAppConfiguration`.
cc: @nicksav

Configuration and WS topic enhancements

---

aspnetcore/tutorials/first-mvc-app/adding-model.md
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/StartupDevProd.cs

Stopped using the include file in both Razor Pages and MVC tutorials, as the `DbContext` class names are different. Also performed a small amount of cleanup while I was in there.

Update the MVC tutorial's Startup class snippet for ASP.NET Core 3.x

---

aspnetcore/signalr/dotnet-client.md

[Internal Review of version 3.1](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&branch=pr-en-us-16554&tabs=visual-studio)
Fixes #16533 
Updated AspNetCore.Docs\aspnetcore\signalr\dotnet-client.md
Fixed _random.Next() * 10 to _random.NextDouble() * 10 so the retry timeout is in a correct range.

signalR\dotnet-client: corrected _random expression

---

aspnetcore/blazor/debug.md

Fixes #15983
Addresses #16270
Addresses #16273
DR: Most of the discussion below is TL;DR on the `no-loc` situation, which you can probably skip. There's one critical bit (https://github.com/aspnet/AspNetCore.Docs/pull/16123#issuecomment-570317743). Debugging doesn't work on Linux due to the setup in the framework: `Unable to find debuggable browser tab` instructions content always calls `GetLaunchEdgeInstructions` (i.e., on Linux), but `GetLaunchEdgeInstructions` throws for Linux at https://github.com/dotnet/aspnetcore/blob/e72223eaf58a3ee6660a922064d2449e47b78253/src/Components/Blazor/Server/src/MonoDebugProxy/BlazorMonoDebugProxyAppBuilderExtensions.cs#L288.
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0&branch=pr-en-us-16123) …

Blazor WebAssembly debugging update

---

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/StartupDevProd.cs

@scottaddie  normally we change the name of the startup class. In this case the snippet is showing that so need to change the NS so the download project compiles.
Fixes #16594

fix duplicate startup compile error

---

aspnetcore/includes/connectionid-signalr.md
aspnetcore/signalr/hubs.md
aspnetcore/signalr/security.md

Fixes: #11687 
[Internal Review of hubs.md](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.1&branch=pr-en-us-16573#handle-events-for-a-connection)
[Internal Review of security.md](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1&branch=pr-en-us-16573#connectionid)
Created a new include named: connectionid-signalr.md providing a short security warning against exposing ConnectionId.
Updated hubs.md so that it uses the connectionid-signalr.md security warning include where ConnectId is mentioned.

New include ConnectId security warning & applied to hubs.md for SignalR

---

aspnetcore/blazor/get-started.md

Install Visual Studio 2019 version 16.4 or later with the ASP.NET and web development workload should provide better information than 
Install Visual Studio 16.4 or later with the ASP.NET and web development workload.

Visual Studio 16.4  should be only in VS 2019

---

aspnetcore/web-api/http-repl.md

Description of the source issue: Lack of a backticks at the end of code-block is preventing following content to be localized

C150960: Adding missing backticks at end of code

---

aspnetcore/razor-pages/ui-class.md

Fixes #16600
The LIBRARY_NAME marker is a reference to the PackageId, which by default is the same as the Assembly Name.  If the PackageId is overridden in the csproj or nuspec file, that PackageId takes precedence

Added clarifying language for the LIBRARY_NAME

---

aspnetcore/migration/22-to-30.md

I added a note about `Microsoft.Extensions.Caching.Redis` being replaced as of ASP.NET Core 3.0 and added a cross-reference to the article about distributed caching.
Fixes #16476

Call out changes to Redis distributed caches

---

aspnetcore/signalr/messagepackhubprotocol.md

One of the anchor links was out of date. But really both links needed updating because they point people at the 2.1 documentation when for SignalR only the 1.x version is relevant. So I've updated the links to explicitly point at the v1.8 branch of the docs which fixes the broken link and points people at the docs relevant to the version they're using.

Update links to MessagePack-CSharp

---

aspnetcore/web-api/jsonpatch/samples/2.2/JSON/remove.json

Description: There is an extra comma which is causing the JSON file to have an invalid format

L166242: removing extra comma

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #16502
Update server version to 2012 R2 or later for >=3.0.
Per: https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows
Thanks @Nikita-T86! 🏍

Update server versioning

---

aspnetcore/fundamentals/configuration/index.md

Fixes dotnet/extensions#1795
This clarification was requested in an issue in the config area, and it seemed simple to knock out a quick PR.

Updates to clarify that fields are not bound in config

---

aspnetcore/security/authentication/identity-api-authorization.md

The description of the JSON snippet is in reversed order of the JSON items.
I propose reversing the description of items so that it matches the JSON snippet.
Fixes #16768

Re-order description of JSON snippet

---

aspnetcore/fundamentals/dependency-injection.md

Added convention based registration (e.g.: auto-registration of `ISomething` ->`Something`) to the list of reasons for "Default service container replacement", though this appears to be addressed by the [Scrutor project](https://andrewlock.net/using-scrutor-to-automatically-register-your-services-with-the-asp-net-core-di-container/)

Added convention based registration bullet

---

aspnetcore/signalr/streaming/samples/3.0/Hubs/AsyncEnumerableHub.cs
aspnetcore/signalr/streaming/samples/3.0/Hubs/StreamHub.cs

Adds the EnumeratorCancellationAttribute to the sample to prevent warnings when users add CancellationTokens. It also allows the server-side code to use `await foreach` with cancellation (i.e. in unit tests).
Fixes #16202
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.0)

[SignalR] Update to streaming sample

---

aspnetcore/client-side/libman/libman-cli.md
aspnetcore/data/ef-mvc/migrations.md
aspnetcore/data/ef-rp/migrations.md
aspnetcore/getting-started/index.md
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/includes/ef-cli.md
aspnetcore/security/key-vault-configuration.md
aspnetcore/toc.yml
aspnetcore/tutorials/first-mvc-app/adding-model.md

Also drop "tools" after CLI.  See https://github.com/dotnet/docs/pull/16880

Drop 'command-line interface' before 'CLI'

---

aspnetcore/blazor/routing.md

Just change link from `Microsoft.AspNetCore.Mvc.RouteAttribute` to `Microsoft.AspNetCore.Components.RouteAttribute` in Blazor routing

Fix RouteAttribute link

---

aspnetcore/signalr/messagepackhubprotocol.md

In response to [CVE-2020-5234](https://github.com/neuecc/MessagePack-CSharp/security/advisories/GHSA-7q36-4xx7-xcxf), we are updating our docs to recommend setting a new static property in their applications when using MessagePack.
cc @AArnott 
`@Rick-Anderson  edit:` [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.1&branch=pr-en-us-16799#configure-messagepack-on-the-server)

SignalR Docs update in response to CVE-2020-5234 in MessagePack library

---

aspnetcore/test/load-tests.md

Hi! 👋🏼
This commit adds k6 to the list of third-party performance testing tools.
Let me know if you need anything else for this PR to be merged.
Thanks,
Simon

Add k6 to the list of third party alternatives

---

aspnetcore/whats-new/2020-01.md
aspnetcore/whats-new/index.yml
aspnetcore/whats-new/toc.yml

Publish the generated page for January. Following the same format used over at https://github.com/dotnet/docs/pull/16931. New this month is a contribution count in the community contributors list.

Add what's new page for January 2020

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #16805 
I was going to just code fence `CreateDefaultBulder`; but in the *Fundamentals* node, new-to-Core/new-to-.NET readers consuming these topic linearly haven't reached the *Host* node yet. We'll need a cross-link here so that they can take a quick look 👀; therefore, we'll need to version Generic Host and Web Host for this change.
Thanks @serpent5! 🍕:beers:

Update scope validation condition in DI topic

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes #16579
I can't say if using the `StartupCommand` with `dotnet {ASSEMBLY}.dll` would work in an Azure Pipeline for an Azure App Service (regular) app, but I can add the Azure App Service WebJobs topic (first of a node in the Azure docs) to the additional resources section here.

Add WebJobs crosslink to Background Tasks topic

---

aspnetcore/grpc/diagnostics.md

PR of #16512
* Remove `you` when it's not needed and doesn't make the statement more clear. When `@davidfowl` 3rd cousin, an architect consultant, is consulting, it's never her app. 
* Minor clean up.
* added a few links
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1&branch=pr-en-us-16872)

gRPC diag edit

---

aspnetcore/host-and-deploy/windows-service.md

Fixes #16843
CR, would have handled this one with only docs review, but need to check something with you:
From the issue comment (pertaining to the Event Logging added automatically for a Windows Service app) ...
> the default event log source config is to log only messages with warning or higher
... but we've documented the log level as being set by `Logging:LogLevel:Default`, which should be *Information* or higher via a template-based app.
Is the guidance on this PR correct, or is the level actually defaulting to *Warning* or higher? If *Warning* or higher, where's that coming from?

Clarify log level and default for Windows Services

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #16759
To harden the text a bit, I'm deliberately vague in the NOTE due to in-progress/in-design work:
* [Read additional KestrelServerOptions from config #4765](https://github.com/dotnet/aspnetcore/issues/4765)
* [Setting the ClientCertificateMode Kestrel server option from an appsettings.json file. #18660](https://github.com/dotnet/aspnetcore/issues/18660)
* [ClientCertificateMode now read from config #18759](https://github.com/dotnet/aspnetcore/pull/18759)
The rest of the guidance seems correct.

Clarification on setting Kestrel options from config providers

---

aspnetcore/security/docker-https.md

Fixes #16900.
I checked the entire repo for references to the `dotnet-docker` repo, but this was the only one I found that was broken.

Fix link to dotnet-docker repo.

---

aspnetcore/fundamentals/middleware/request-response/samples/3.x/RequestResponseSample/Startup.cs
aspnetcore/razor-pages/index/sample/RazorPagesContacts2/Pages/Customers/CreateFATH.cshtml.cs
aspnetcore/razor-pages/index/sample/RazorPagesContacts2/Pages/Customers/CreateRoute.cshtml.cs

Fixes #16855.
This first commit shows the extent of the changes to code files. The only remaining calls/references to `ToLower` or `ToUpper` are in the following .md files:
* data/ef-mvc/sort-filter-page.md
* data/ef-rp/sort-filter-page.md
* mvc/controllers/routing.md
* razor-pages/razor-pages-conventions.md
I'll address those in another commit, excluding the `SlugifyParameterTransformer` stuff.
Note: The `SlugifyParameterTransformer` code is all inline in .md files, with no corresponding sample files.
cc @Rick-Anderson, @guardrex

Replace ToUpper/ToLower with ToUpperInvariant/ToLowerInvariant.

---

aspnetcore/fundamentals/http-requests.md

Fixes #16498.
I didn't think it was necessary to be explicit in warning against re-registering e.g. `GitHubService`, so I just went with a little more explanation of what happens behind the scenes, at a basic level.

Add more detail for AddHttpClient<TClient>().

---

aspnetcore/includes/signalr-typescript-webpack/npm-run-release.md

[Internal Review, see include in this topic section](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.1&branch=pr-en-us-16952&tabs=visual-studio#test-the-app)
Fixes #16945 
Updated some items in the npm-run-release.md include that will not machine translate.  Identified by Rick Anderson.

Updated to improve localization.

---

aspnetcore/security/authentication/social/social-code/3.x/StartupTwitter3x.cs
aspnetcore/security/authentication/social/twitter-logins.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.1&branch=pr-en-us-16809)
Fixes issue #16969
There are some additional permissions to be set to the Twitter app. The PR mentions them.
- App details: **Enable Sign in with Twitter** must be checked
- After creating the app: go to Permissions tab -> edit ->  **Request email address from users** must be checked
- `twitterOptions.RetrieveUserDetails = true;` is already mentioned
[topic link: Twitter external sign-in setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.1#configure-twitter-authentication)

Added missing instructions for sign in with Twitter.

---

aspnetcore/mvc/models/file-uploads.md

Fixes #16970
Let's not maintain links to their API unless we need to. They cross-link their API in the topic that we're suggesting, so the reader will have access to it easily enough once they get there.
Thanks @kaerm! 🎷

Drop unnecessary Azure API

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #16918
I have no direct experience with this configuration, so I need engineering to confirm the guidance.
DR, this bit about the Unix socket goes back to medieval Core times 🏰⚔️, where the example was ...
```
http://unix:/run/dan-live.sock  
```
`dan-live` 😀 ..... I assume that you had a hand in it. Can you sign-off or assign a reviewer to confirm the update?
**EDIT** Adding SS to look. :eyes:
~**EDIT** and please confirm that the `:/` at the end is required. The dropped `dan-live.sock` example didn't include it.~ Confirmed below :point_down:.
Thanks @gbjbaanb! ⛷

Improve bind to a Unix socket guidance

---

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/ChildComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/ParentComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/ChildComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/ParentComponent.razor
aspnetcore/blazor/components.md
aspnetcore/blazor/javascript-interop/samples_snapshot/component3.razor

Fixes #16693
* The ask is to make the chained bind example match the component param example (i.e., use the `Year`-`YearChanged` example instead of the password example). I don't think that's necessary ... I see a set of changes that *may* reduce confusion without sacrificing the password example, which is a nice real-world example:
* The chained bind section was outside of the bind section merely because it used an event handler (`onclick`). I move the chained bind section directly into the bind content area of the topic and add a line saying what `onclick` does with a cross-link to the *Event handling* section.
* Both of these sections (parent-to-child with component param and child-to-parent with chained bind) didn't make the scenario clear: I make them say "parent-to-child" and …

Blazor binding content and layout updates

---

.vscode/settings.json

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/16985
MVF1 of the extension has landed in the Docs Authoring Pack. Here it is in action with the config proposed in this PR. Type 3 backticks, and the auto-complete list appears. I've included all valid values used in our repo.
Adding @guardrex, @CamSoper, & @wadepickett for awareness.

Configure valid docset dev langs for docs-markdown extension

---

aspnetcore/security/blazor/index.md

Fixes #16999
Special thanks to @geersjake 🎷 for calling out this *embarrassing content!* 🙈 I only tested the first example locally, not the second example (auth state as a cascading param). I think I was very busy when we put this up and felt the code could be trusted as provided, but I should've waited a day until I could check it myself.
These updates fix a few problems:
* Errors are resolved with the service registrations that @geersjake recommends ...
* > System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Authorization.AuthorizationOptions]' while attempting to activate 'Microsoft.AspNetCore.Authorization.DefaultAuthorizationPolicyProvider'
* > System.InvalidOperationException: Cannot provide a value for …

Fix auth state as a cascading param guidance

---

aspnetcore/security/authentication/certauth.md

Added HttpClient examples, showing different ways to send the certificate in a HttpClient request
Fixes #15974

Adding HttpClient examples to send the certificate (cert_auth.md)

---

aspnetcore/security/anti-request-forgery.md

I replaced `services.AddMvc` with `services.AddControllersWithViews` as the way to apply filters globally was changed with the release of ASP.NET Core 3

Update global application example of AutoValidateAntiForgeryTokenAttribute

---

aspnetcore/mvc/models/file-uploads.md

`OnPostUploadAsync` contains a compilation error by trying to reference `filePath` outside the scope it was declared in.
Fixes #17114

File uploads example contains a compilation error

---

aspnetcore/data/ef-rp/update-related-data.md
aspnetcore/fundamentals/configuration/options.md
aspnetcore/fundamentals/environments.md
aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/localization.md
aspnetcore/fundamentals/middleware/index.md
aspnetcore/fundamentals/middleware/request-response.md
aspnetcore/fundamentals/static-files.md
aspnetcore/grpc/aspnetcore.md
aspnetcore/grpc/basics.md
aspnetcore/includes/code-comments-loc.md
aspnetcore/mvc/advanced/custom-model-binding.md
aspnetcore/security/data-protection/implementation/key-management.md
aspnetcore/security/data-protection/implementation/key-storage-providers.md

Part of work with loc to find out how important localized comments are.  If you know a doc with lots of code comments, please add the include.
The two routing docs have massive useful code comments, but those are in PR now so avoid that to prevent merge conflicts. I'll handle them.
See related PR https://github.com/dotnet/docs/pull/17129
cc @guardrex

Add include for localized comments

---

aspnetcore/grpc/configuration.md

Fixes #17124
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.0&branch=pr-en-us-17133#configure-services-options)
Is everyone cool with our HTML hack approach on this one? It 🤞 *should* 🍀 work. Applying this to the longest entry should set the column width to accommodate all entries in that column of the table. Can someone check the internal build topic to confirm?
... also wondering in passing if they chose the best style in this case. Perhaps, `<code>` in a table cell should have this style set everywhere. 🤔

Manage table 1st column width in gRPC topic

---

aspnetcore/fundamentals/localization.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/15412
The property was created in 5.0. so let's only show it there.
CC @Rick-Anderson

Only show property when it exists

---

aspnetcore/mvc/views/layout.md

Fix minor typo in the `Importing Shared Directives` section. The following:
> directives to importing namespaces
...should read:
> directives to import namespaces

Fix typo in "Importing Shared Directives" section.

---

aspnetcore/docfx.json

I've also submitted the metadata whitelisting request here: https://ceapex.visualstudio.com/Engineering/_workitems/edit/182170

Add ms.technology metadata for the What's New pages

---

.ghal.rules.json

I started the Blazor security topic work this morning and remembered that the "Blazor" label isn't applied to the ones that open from that neck of the woods. Is it ok to add that label to issues that come from those topics? We're about to have a whole slew of new reference topics there, which I think will generate a number of new issues in the future.
**Additional**: ~I added the upcoming Blazor Components TH topic to this in advance of that topic being set up. It will happen fairly soon-ish. That ok? If not, I can add it later when that topic goes up. :ear:~ **HELD** until that topic is created.

Add Blazor label to Blazor security topic issues

---

aspnetcore/blazor/data-binding.md

There were no H2 headings in this document and all headings were H3 (I suppose this was overlooked when the content was split out from the Razor Components Topic)
Due to the fact that there were no H2 headings, nothing was showing up in the "In this article" navigation

Change H3 headings to H2

---

aspnetcore/client-side/spa/react.md

The CRA github repo was probably restructured, which makes the CRA documentation link point to a "Learn about making a Progressive Web App" readme file.
This change will make it point to the official docs: https://create-react-app.dev/docs/getting-started/

Update CRA documentation link

---

aspnetcore/blazor/dependency-injection.md

This beefs up `OwningComponentBase` docs in *blazor/dependency-injection*, explaining the uses of `OwningComponentBase` and `OwningComponentBase<T>`, as well as commenting on the specific case of `DbContext` usage, which is a common case for DI woes in Blazor.
Fixes #14316

Expand `OwningComponentBase` docs

---

aspnetcore/fundamentals/middleware/index.md

Fixes dotnet/aspnetcore#19586
See https://github.com/dotnet/aspnetcore/issues/19586#issuecomment-595995998 for description as to why this appears to be a typo. This appears to have been a typo. There's a missing 'not' 😄.

Fix misleading typo in docs on UseWhen

---

aspnetcore/security/blazor/content-security-policy.md
aspnetcore/toc.yml

Fixes #12778
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/content-security-policy?view=aspnetcore-3.1&branch=pr-en-us-17147)
* I didn't see any reason to limit this to Blazor Server, so I provide guidance for Blazor WebAssembly, too. Testing CSP with Blazor WebAssembly went well, but I'll strip that out if there are technical reasons why it can't be supported.
* I qualify the security capability remarks for CSP by saying that CSP "**_helps_**" protect (i.e., no absolute guarantee). Let me know if I was too weak there (or not strong enough).
* Thank you Javier! ... *Your notes, remarks, and suggestions were excellent as usual!* 🎸

Blazor Content Security Policy topic

---

aspnetcore/blazor/get-started.md
aspnetcore/includes/net-core-prereqs-vsc-2.2.md
aspnetcore/includes/net-core-prereqs-vsc-3.0.md
aspnetcore/includes/net-core-prereqs-vsc-3.1.md
aspnetcore/tutorials/first-mongo-app.md
aspnetcore/tutorials/publish-to-azure-webapp-using-vscode.md
aspnetcore/tutorials/signalr-typescript-webpack.md

[C# for Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) has been renamed from `ms-vscode.csharp` to `ms-dotnettools.csharp`, this PR corrects to new correct uris.

ms-vscode.csharp to ms-dotnettools.csharp

---

aspnetcore/tutorials/first-mongo-app.md

The `AddMvc` method should be replaced with `AddControllers` in ASP.NET Core 3.0+.

Replace AddMvc method reference with AddControllers

---

aspnetcore/includes/blazor-security/app-component.md
aspnetcore/includes/blazor-security/authentication-component.md
aspnetcore/includes/blazor-security/fetchdata-component.md
aspnetcore/includes/blazor-security/index-page.md
aspnetcore/includes/blazor-security/logindisplay-component.md
aspnetcore/includes/blazor-security/redirecttologin-component.md
aspnetcore/includes/blazor-security/troubleshoot.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md
aspnetcore/security/blazor/webassembly/additional-scnearios.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/index.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md
aspnetcore/toc.yml
aspnetcore/whats-new/2020-02.md

Fixes  #17144
Internal Review Topics
* [Overview](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/index?view=aspnetcore-3.1&branch=pr-en-us-17260)
* [Standalone w/Auth Lib](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1&branch=pr-en-us-17260)
* [Standalone w/AAD](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1&branch=pr-en-us-17260)
* [Standalone w/AAD B2C](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1&branch=pr-en-us-17260)
* [Standalone w/MS …

Blazor WebAssembly auth documentation

---

aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo5.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo8.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/Todo4.razor

Fixes #17235 
@JMackey1 - The namespace for the app should have sufficed there. I think you may have accidentally created your `TodoItem` class in the *wwwroot* folder. There's no need to add a namespace if the class is created in the root of the project with either no namespace or a namespace that matches the app's namespace. Otherwise, I've reacted to your feedback on this PR. Thanks again for commenting on the topic.
@danroth27 @mkArtakMSFT Let me *beat a dead* 🐴 here for a sec (*poor horse!*). VS *correctly* uppercases the word "Component" when referring to a "Razor Component." I still cringe when I see it all across our docs as "Razor component" because the word "component" is part of the formal, specific, named entity ... part of the **_proper noun_**. I still suggest using "Razor …

Improve Blazor tutorial guidance

---

aspnetcore/blazor/components.md
aspnetcore/blazor/data-binding.md
aspnetcore/blazor/event-handling.md

Fixes #17119
* Nits on how we lead into binding and event handling.
* There's an out-of-place remark in the *Components* topic. I move it to the *Binding* topic.
* I kill off 🔪 the "to both components and DOM elements" phrase in the opening sentence of the *Binding* topic. There are **only** components and DOM elements under discussion, so it's not really explaining anything. Also, the concept is well covered down in the topic.
* We've been instructed to use the word *scenario* over *feature*. I don't fully understand it, but that's the word.

Blazor Razor syntax remark improvements

---

aspnetcore/azure/devops/tools-and-downloads.md
aspnetcore/data/ef-mvc/intro.md
aspnetcore/fundamentals/metapackage-app.md
aspnetcore/fundamentals/metapackage.md
aspnetcore/host-and-deploy/azure-iis-errors-reference.md
aspnetcore/host-and-deploy/docker/building-net-docker-images.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/includes/2.1-SDK.md
aspnetcore/includes/2.2-SDK.md
aspnetcore/includes/net-core-prereqs-mac-2.2.md
aspnetcore/includes/net-core-prereqs-vs2017-2.2.md
aspnetcore/includes/net-core-prereqs-vs2019-2.2.md
aspnetcore/includes/net-core-prereqs-vsc-2.2.md
aspnetcore/includes/net-core-prereqs-windows.md
aspnetcore/includes/net-core-sdk-download-link.md
aspnetcore/migration/proper-to-2x/index.md
aspnetcore/migration/proper-to-2x/mvc2.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/security/authentication/accconfirm.md
aspnetcore/security/authentication/samples.md
aspnetcore/security/docker-https.md
aspnetcore/test/troubleshoot.md
aspnetcore/tutorials/first-mongo-app.md
aspnetcore/tutorials/first-mongo-app/samples/3.x/SampleApp/readme.md
aspnetcore/tutorials/publish-to-iis.md
aspnetcore/tutorials/signalr-typescript-webpack.md

I'm looking at where we're getting the traffic from to the archives page given this issue (https://github.com/dotnet/website/issues/1070). This page was one of the sources.
While doing this, also noticed we had a couple of other links that could be updated. Let me know if you'd prefer a different target. For example, https://www.microsoft.com/net/download/all could go to the main download page instead of going to https://dotnet.microsoft.com/download/dotnet-core.

Replace www.microsoft.com/net links

---

aspnetcore/signalr/javascript-client/sample/wwwroot/js/chat.js

Turns out the JS version of the sample doesn't actually work because we don't call the `async function start()` we create.
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17358 (originally reported in dotnet/aspnetcore).

fix #17358 by calling 'start()' in the JS sample

---

aspnetcore/blazor/templated-components.md

Fixes #17348
I've opened [Blazor generic type constraints (dotnet/AspNetCore.Docs #17351)](https://github.com/dotnet/AspNetCore.Docs/issues/17351) on HOLD for 5.0 to revert this PR and supply feature coverage.
Thanks @ClaudioFriederich! 🚀

Surface plan for Blazor generic type constraints

---

aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md

Fixes #17349
Going ahead with that plan ... Given that the version is applied to all topics by two INCLUDES files, this is an easy way to signal the latest package version across the topics. It will be easy/fast to update each preview release.
Thanks @tomidix! 🌴

Add the Blazor WebAssembly version to INCLUDES

---

aspnetcore/blazor/class-libraries.md
aspnetcore/host-and-deploy/blazor/configure-linker.md

Fixes #17369
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&branch=pr-en-us-17425#add-an-xml-linker-configuration-file-to-a-library)
In passing, I'm moving the *Create a Razor components class library with static assets* section up because I want the *Build, pack, and ship to NuGet* section to appear last.

Add an XML linker config file to a library

---

aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/lifecycle.md
aspnetcore/blazor/lifecycle/samples_snapshot/3.x/event-handler-disposal-1.razor
aspnetcore/blazor/lifecycle/samples_snapshot/3.x/event-handler-disposal-2.razor
aspnetcore/blazor/routing.md

Fixes #17293
Internal Review Topics (links directly to sections) ...
* [Lifecycle](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1&branch=pr-en-us-17339#component-disposal-with-idisposable)
* [Routing](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1&branch=pr-en-us-17339#uri-and-navigation-state-helpers)
* [Forms](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1&branch=pr-en-us-17339#enable-the-submit-button-based-on-form-validation)
@scottaddie Encode hashes in xref links per our prior discussion (and following the linter's advice for these links), and it :boom: ...
&ndash; The Collector ([Henry Woolf](https://tardis.fandom.com/wiki/Henry_Woolf))
[Doctor …

Using Dispose to unhook Blazor event handlers

---

aspnetcore/security/blazor/webassembly/index.md

Fixes #17288
[Internal Review Topic (links directly to section)](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/index?view=aspnetcore-3.1&branch=pr-en-us-17295#options-for-hosted-apps-and-third-party-login-providers)
Check me here. :eyes: In an attempt to clarify some of the complex sentences, such as ...
> Create an endpoint in your API and use the access token generated by the server to retrieve the access token to talk to the third party API resource from Identity. 
... to ...
> Use the access token generated on the server to retrieve the third-party access token from a server API endpoint. From there, use the third-party access token to call third-party API resources directly from Identity on the client.
... *I may have gone right off the rails.* …

Blazor options for 3rd party login providers

---

aspnetcore/blazor/components.md

Fixes #17291
For now, let's link the engineering issue given that this scenario might get some framework ❤️ and devs may want to :+1: that engineering issue. The approach/workaround at the end of the issue shows how to pull it off.
Thanks @rrsit! :rocket: ... btw - I can't comment on your `RadzenGrid` component scenario. They're doing some ✨ *magical things* ✨ inside their components to deal with this that I haven't seen.

Surface workaround for referencing components in a loop

---

aspnetcore/blazor/get-started.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes #17427
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&branch=pr-en-us-17441)
We can get the ball roll'in now and see how this is starting to compose.
Let's clarify the VSC scenario ... VSC users, like CLI users, won't be able to install 3.1.300, thus a separate Blazor WebAssembly template install step should remain, correct?

Blazor updates for 3.2 Preview 3

---

aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/index.md

Fixes #17191
Breaking the blog content down by paragraph ...
> Blazor WebAssembly apps now integrate seamlessly with how ASP.NET Core handles static web assets. Blazor WebAssembly apps can use the standard ASP.NET Core convention for consuming static web assets from referenced projects and packages: *_content/{LIBRARY NAME}/{path}*. This allows you to easily pick up static assets from referenced component libraries and JavaScript interop libraries just like you can in a Blazor Server app or any other ASP.NET Core web app.
We already document static asset references in the Blazor RCL topic (*Create a Razor components class library with static assets* section) via cross link to Razor Class Libs topic.
wrt this passage ...
> pick up static assets from referenced ... JavaScript interop …

Surface Docker support for Blazor

---

aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Controllers/TodoItemsController.cs

Fixes #17528.
Really, this should just be `IActionResult`, because `TodoItemDTO` isn't returned from the method. I was gonna do that instead, but the scaffolded code sets things up like this. It really doesn't matter what type is used for the generic here, but using `TodoItemDTO` makes sense, at least.

Fix ActionResult<T> for consistency

---

aspnetcore/breadcrumb/toc.yml

[Internal Review - see breadcrumb at top](https://review.docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1&branch=pr-en-us-17559)
Updating the breadcrumb/toc.yml so it points to the new hub page instead of the old one.
- I will remove the old unused hub page in a separate PR once this last reference to it is updated.
- The ASP.NET 4.x breadcrumb that point to the old hub page will also have to be changed in a separate PR.

Update breadcrumb toc.yml to point to new hub page

---

aspnetcore/blazor/globalization-localization.md

Fixes #17513 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1&branch=pr-en-us-17569)
We'll be able to do more here later when there's more 🕐. For example, I think we should eventually add example code. For now 🏃😅, I recommend that we use this guidance with the linked engineering sample.

Localization for Blazor WASM

---

aspnetcore/breadcrumb/toc.yml

[Internal Review - See Breadcrumbs at top](https://review.docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1&branch=pr-en-us-17601)
Fixes #17562
Update the ASP.NET Core breadcrumbs/toc.yml to point to .NET in the following format:
Docs  / .NET / ASP.NET Core / 
instead of :
Docs  / ASP.NET / ASP.NET Core /
Where ".NET" will point to the .NET Hub page: https://docs.microsoft.com/en-us/dotnet/

Breadcrumb update to docs - .net at root - asp.net core

---

aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/host-and-deploy/blazor/webassembly.md

Fixes #17617
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1&branch=pr-en-us-17619#use-a-custom-webconfig)
Opened doc issue to react to engineering issue at https://github.com/dotnet/AspNetCore.Docs/issues/17620.
cc: @cornem

Use a copy target for Blazor WASM custom web.config

---

aspnetcore/includes/MTcomments.md
aspnetcore/performance/performance-best-practices.md
aspnetcore/release-notes/aspnetcore-2.2.md

This is a simple correction. There is no associated issue. Three markdown documents within the repository use the curly apostrophe character ( ’ ) instead of the straight apostrophe ( ' ). This was changed for the sake of consistency.

Straighten apostrophe character for consistency

---

aspnetcore/blazor/call-dotnet-from-javascript.md
aspnetcore/blazor/call-javascript-from-dotnet.md

Fixes #17626 
I've opened **Revert Blazor circular references content** #17651 on hold and tracking engineering issues to remove these sections when addressed.

Avoid circular references in Blazor JS interop

---

aspnetcore/includes/blazor-security/troubleshoot.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Addresses #17304
Fixes #17673
Improvements to the preview WASM security topics based on experience and feedback from readers.
cc: @mkArtakMSFT This is more a set of language improvements than technical guidance changes, so I'm going to go ahead and merge it. The bits for #17673 are just to surface the API setup in the standalone group of topics. Thanks again, @23min! 🌴
... btw, I still haven't worked out the delta between myself and Javier's scope URI experiences. In the AAD case, my test app *always* wants the scope URI without a scheme and host. I'll continue to work on that.

Blazor WASM preview security topic updates

---

aspnetcore/tutorials/grpc/grpc-start.md

Enable trust the HTTPS development certificate on some **Linux** distributions is not easy. 
Adding this instructions can make it easier to develop on Linux.

Update grpc-start: Call insecure gRPC services

---

aspnetcore/blazor/layouts/sample_snapshot/3.x/App2.razor

Fixes an error in the second layout code example of the docs under: https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0#default-layout

Fix missing @ before typeof(Startup)

---

aspnetcore/mvc/controllers/routing.md

Makes it more obvious you have to do something special, e.g. call MapControllers() to expose attribute only routes on regular (non-API) controllers. If you just comment out the default conventional route and add attribute routes to controllers, it won't work. And it is not immediately obvious why it doesn't work. This change makes those two lines more prominent.

Upgrade the info about exposing attribute routes to Warning

---

aspnetcore/blazor/integrate-components.md
aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md

Fixes #17210
[Internal Review Topic (Component TH topic)](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-1.0&branch=pr-en-us-17571)
Surfaces the guidance that we discussed on the issues. Thanks @mrlife! 🎷 ... and sorry for the delay, but I've been 🏃😅 lately.
WRT my problem on the issue: My problem was merely that I wasn't following the integration prereqs that we established earlier for the *Integrate components* topic. I was merely missing the *blazor.server.js* script. 👦🔫 Once I figured that out and dropped the script in there, it was :tada:. I've updated the text here to help others avoid my mistake.
One other thing to ask about here ... all of the `render-mode` guidance seems to be specifically angled toward the …

Rendering components in RP/MVC updates

---

aspnetcore/includes/blazor-security/wasm-aad-b2c-userflows.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md

Fixes #17522
Based on Javier's remark here :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17522#issuecomment-611406463
If we get feedback that devs are having trouble implementing something (and if the framework doesn't provide a thing for this), then we can add an example. I hacked around with it, and just getting the challenge and callback to work wasn't too bad :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17522#issuecomment-611643539
cc: @Alienroid ... would u like to take a look at this and add your feedback? I think we just need to say for now that it isn't supported OOB and here's some guidance on making a challenge.

Blazor WASM AAD B2C user flows

---

aspnetcore/mvc/views/view-compilation.md
aspnetcore/mvc/views/view-compilation/sample/Startup.cs

Fixes #16420
Fixes #15505 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&branch=pr-en-us-17709)
Prefer bullets to numbers unless customer is likely to do the steps out of order, and order is critical. That's a rare case. When order doesn't matter, as in this case, use bullets. For multi-step instructions that do need order, bullets are better anyway. Customer will naturally follow the bullets in order. Easier to write/maintain and it looks better.

Razor file compilation

---

aspnetcore/signalr/configuration.md

`MinimumProtocolVersion` was added in 3.1 but never added to the docs.
Had to copy the whole 3.0 section because we don't do monikers for subsections anymore. The only change was adding MinimumProtocolVersion to the table.

Add MinimumProtocolVersion

---

aspnetcore/signalr/messagepackhubprotocol.md

In 5.0 we updated the library to 2.x and we also changed how the options are set.
Main changes: fixed some links, changed options in 5.0, changed DateTime section in 5.0, changed warning in 5.0
Extra: this was using the old format of monikers for sub-sections. Updated it to copy paste the whole doc for each moniker.
[Internal review page](https://review.docs.microsoft.com/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-5.0&branch=pr-en-us-17736)

Update MessagePack docs for 5.0

---

aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/social-code/AccessDeniedPathInfo.cshtml
aspnetcore/security/authentication/social/social-code/StartupAccessDeniedPath.cs
aspnetcore/security/authentication/social/twitter-logins.md

Fixes #9603
Only FB seems to support this.
* [FB](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1&branch=pr-en-us-17679#react-to-cancel-authorize-external-sign-in)

AccessDeniedPath

---

aspnetcore/security/authentication/samples.md

Fixes #17757
Samples links for the range >= aspnetcore3-0 are not working anymore.
I updated it with links of ASP.NET Core 3.1 because it is the latest LTS release available.
(Hint: the ASP.NET Core 3.0 samples are available [here](https://github.com/dotnet/AspNetCore/tree/3.0/src/Security/samples). You can remove  "release/" from the paths and it will work. )

Fix broken links

---

aspnetcore/security/cors.md

Fixes #17803, again.
cc @Rick-Anderson 
It looks like it's just the one snippet where the highlighting went wrong. If you'd rather I put `UseAuthentication` in, just say the word.

Fix doubled-up UseAuthorization (part 2)

---

aspnetcore/mvc/views/view-compilation.md
aspnetcore/mvc/views/view-compilation/samples/3.1/Startup.cs

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17791
[Internal review page (ASP.NET Core 3.1+)](https://review.docs.microsoft.com/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&branch=pr-en-us-17792#enable-runtime-compilation-for-a-razor-class-library)

Explain how to enable Razor Class Library runtime compilation in ASP.NET Core 3.1+

---

aspnetcore/index.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1&branch=pr-en-us-17845)
Fixes #17554 
Updated link for Create your first data-driven MVC web app to point to first tutorial in the series rather than the "overview" page which just contains links.

Hub link update

---

aspnetcore/blazor/debug.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

[Preview 4] Blazor Preview 4 updates

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #17872
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1&branch=pr-en-us-17875)
* Best **_not_** to link any prior version explicitly because the bundle might rev and thus the link go stale.
* This removes the direct download link from prior versions because the 3.x runtime isn't backwards compat.
* I left a reminder note at the top of the topic about the changes needed for 5.0.
Thanks @willydavidjr! :rocket:

Hosting Bundle version clarification

---

aspnetcore/blazor/debug.md

We need this anchor for the VSCode debugging experience for Blazor WebAssembly.

Add vscode anchor to Blazor debugging page

---

aspnetcore/test/troubleshoot-azure-iis.md

Specifically, with details about the incompatibility between in-process hosting and single-file executables.
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1&branch=pr-en-us-17930#50038-ancm-application-dll-not-found)

Add note about ANCM 500.38 error

---

aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/host-and-deploy/blazor/webassembly/_samples/web.config

Fixes #17857
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1&branch=pr-en-us-17958#brotli-and-gzip-compression)
Looks good. Tested one file (*dotnet-wasm*) for all three and whole site for Gzip.
`http://localhost:8022/_framework/wasm/dotnet.wasm`
* No compression (`Accept-Encoding: identity`)
* Content-Type: application/wasm
* Content-Length: 1931045
* File size on disk: 1933312
* Gzip compression (`Accept-Encoding: gzip`)
* Content-Type: gzip
* Content-Length: 776068
* File size on disk: 778240
* Brotli compression (`Accept-Encoding: br`)
* Content-Type: br
* Content-Length: 619583
* File size on disk: 622592
Whole app came in at 2.04 MB without compression and 1.92 MB Gzipped.
@benaadams ... Thanks for …

Enhance Blazor WASM Brotli content

---

aspnetcore/toc.yml

Fixes #18009
@scottaddie ... This will place "Lifecycle" closer to the *Components* topic to make it a bit more noticeable. We're not going to have a node for *Components* ... at least not right now. I decided to keep going with just *Lifecycle* (short) over *Component lifecycle*, which would imply that we also change to *Component data-binding* and *Component event handling*. It's all a bit much, so I think let's just stick with *Lifecycle* here and keep an :ear: open for more feedback.
Thanks @behroozbc! :rocket:

Move Blazor Lifecycle topic UP in TOC

---

aspnetcore/index.yml
aspnetcore/whats-new/index.yml

[Internal Review - Hub page](https://review.docs.microsoft.com/en-us/aspnet/core/index?view=aspnetcore-3.1&branch=pr-en-us-18024)
[Internal Review - What's New page](https://review.docs.microsoft.com/en-us/aspnet/core/whats-new/index?view=aspnetcore-3.1&branch=pr-en-us-18024)
Fixes #17962 
Goal: Make sure ASP.NET developers can find the Download .NET and Community links in a somewhat prominent place since the L2 navigation that contains those links currently are being removed.
Updated the following to prep for L2 navigation bar removal:
- Hub page: Added a Download .NET card to the top highlights section at the top. Since the number of highlights cards were at the max, moved the video tutorial card to a more expanded card in the next section.  This also allowed for pointing to more than …

Update to Hub and What's new for L2 removal

---

.openpublishing.redirection.json
aspnetcore/blazor/call-javascript-from-dotnet.md
aspnetcore/blazor/components.md
aspnetcore/blazor/hosting-models.md
aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/server/additional-scenarios.md
aspnetcore/security/blazor/server/index.md
aspnetcore/security/blazor/server/threat-mitigation.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md
aspnetcore/toc.yml

Fixes #18027
We're splitting the Blazor Server security topic into a node that mirrors the TOC approach taken for WASM security topics.
We're still planning on hitting all of the topics with UE work later. It should happen after 3.2 is released. I'll ping you for review on those PRs when the time comes. Right now, the focus here is on the topic split, TOC changes, and the redirect file addition.
Also note a strange thing that's cropped up on my last few PRs here. I'm getting build warnings for an XREF in aspnetcore/blazor/integrate-components.md ...
> Cross reference not found: 'xref:mvc/views/tag-helpers/builtin-th/component-tag-helper'
... but that reference is correct, and it seems to generate the correct link in the live topic. See the 2nd bullet of the opening section at ... …

Create Blazor Server security node

---

aspnetcore/host-and-deploy/blazor/configure-linker.md

As of [PR#20878 in dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/tree/blazor-wasm), the option name has changed from MonoLinkerI18NAssemblies to BlazorWebAssemblyI18NAssemblies.

[3.2-RC] Rename MonoLinkerI18NAssemblies -> BlazorWebAssemblyI18NAssemblies

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Fixes #18031
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1&branch=pr-en-us-18049#custom-boot-resource-loading)
Safia, the draft text is a hybrid of what you and Steve provided. Also, I put you on the author byline for providing some of the text. Let me know if you prefer a different URL for the link.
cc: @Lupusa87 ... in case you would like to look this over and see if it gives you all of the information that you need for the scenario that you asked about on https://github.com/dotnet/aspnetcore/issues/21042.

[3.2-RC] Document Blazor `loadBootResource`

---

aspnetcore/index.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1&branch=pr-en-us-18099)
Fixes #17555 
Update the _Create your first web UI_ card to point to [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio) instead of the Blazor get started.

Update Hub - First web UI link point to Razor Pages instead of Blazor

---

aspnetcore/blazor/get-started.md

Fixes #18097
Fixes #18098
cc: @danroth27 @mkArtakMSFT 
Given that WASM requires an entire re-install of the app to get on the Preview Channel, I left our prior instructions here. The instructions tell the reader to use the guidance in the **.NET Core CLI** tab. Let me know if you prefer that I activate the Preview Channel instructions in a new WASM section of the tab (they're just commented out here) with the cross-link to the Preview Channel IDE instructions. :ear:
Thanks @leahtmsft ... This looks correct based on my *ancient* 👴 iMac (**2009!** ... *Good grief!* 🤦‍♂️). I'm going to go ahead and take this live now; but let me know if you think it needs a patch, and I can get that in today.

Update Blazor Get Started VS4Mac guidance

---

aspnetcore/host-and-deploy/blazor/configure-linker.md

Fixes #18096
Links directly to example XML files (data formats), not the landing for the entire `mono/linker` repo.

Directly link Blazor WASM linker data formats

---

aspnetcore/blazor/dependency-injection.md

Fixes #18130
cc: @mkArtakMSFT ... This isn't for the ask on https://github.com/dotnet/aspnetcore/issues/18077 because I don't see the problem described ...
> This page says that IJSInterop etc are scoped as singletons, which is incorrect in server-side apps.
It only says that `IJSRuntime` is ...
> Singleton (Blazor WebAssembly)
> Scoped (Blazor Server)
... and doesn't refer to `IJSInterop` or JS interop otherwise.
I did notice this change tho for `HttpClient` for WASM ... Transient now.

Blazor WASM HttpClient is Transient now

---

aspnetcore/blazor/call-web-api.md
aspnetcore/includes/blazor-security/fetchdata-component.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #18123
Thanks @carlblanchard! :rocket: This should answer your question about the approach with `HttpRequestMessage` and a token. I just tested this locally with a web API app that I have running on IIS, including with CORS. *It worked.* :tada: This PR will go into the live docs shortly, so you can just check the live docs later this evening if you prefer not to read the diff here. The text and examples will be continually improved over the next few weeks as we get to 3.2 GA. If you spot anything else, give me a *shout* 📣👦.
* A found a couple of things to fix here that didn't get in on Preview 5 (e.g., `ITokenAccessProvider` in some text and examples and some namespaces). I'll keep an :eye: out for 😈 *Sneaky Code*:tm: 😈 as I proceed with updates.
* I'm moving a section from the …

Blazor WASM security topic updates

---

aspnetcore/fundamentals/servers/kestrel.md

@aL3891 @guardrex After reading the final version of https://github.com/dotnet/AspNetCore.Docs/pull/18075 I wanted to clarify a few more things.
Preview: https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&branch=tratcher%2Frequest-draining

Clarify request draining comments

---

aspnetcore/fundamentals/routing.md
aspnetcore/includes/catchall.md
aspnetcore/migration/22-to-30.md
aspnetcore/mvc/controllers/routing.md

Address first part of #18072
Internal review URLS
* [Routing](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1&branch=pr-en-us-18121#rtr)
* [Controller routing](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1&branch=pr-en-us-18121#conventional-routing-order)
* [2.2 - 3.0 migration](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&branch=pr-en-us-18121&tabs=visual-studio#breaking-api-changes)

catch-all routing bug

---

aspnetcore/tutorials/grpc/grpc-start.md
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/GrpcGreeter.csproj
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/Program.cs
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/Services/GreeterService.cs
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/appsettings.json
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/GrpcGreeterClient.csproj

[Internal Review - Tutorial: Create a gRPC client and server in ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&branch=pr-en-us-18103&tabs=visual-studio)
Fixes #18104
Updated for ASP.NET Core 3.1:
- grpc-start.md tutorial
- GrpcGreeter sample app
- GrpcGreeterClient sample app
Completing this issue is a prerequisite to related issue #16467 which includes creating a new 3.1 version samples .zip for download and redirecting to this updated tutorial.

3.1 update for gRPC-start tutorial and its two sample apps

---

aspnetcore/blazor/call-web-api.md

Fixes #17634
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1&branch=pr-en-us-18187#handle-errors)
At this point, the draft language is for discussion. I used a vanilla example ... the exact scenario from a Hosted app with defaults and a bad URI. Would you like to do something else?

Surface handling errors in Blazor web API topic

---

aspnetcore/blazor/components.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&branch=pr-en-us-18192)
Review note: This is a meta data change work around to trigger the localization system to not localize the term "Razor".  There is no link to review until the localization has kicked off per this merged change in two days. This is a tiny change not warranting a review perhaps but since it is a temp work around which we normally avoid I'm asking for one.
Related to #18076 
Changing the title meta data so that "Razor" is lower case as "razor" as recommended by the localization team to test out as a near term solution.  There is currently an issue where no-loc: topic meta data terms are ignored if the same word in the same case exists in the title meta data. …

Temporary no-loc Razor term fix for high vis issue

---

.openpublishing.redirection.json
aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #18199
From the original issue ...
https://github.com/dotnet/AspNetCore.Docs/issues/17650#issue-595775463
The registration is shown as ...
```csharp
builder.Services.AddApiAuthorization<RemoteAuthenticationState, OidcAccount>()
.AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, OidcAccount, 
CustomAccountFactory>();
```
... but should that be on `AddMsalAuthentication`? ...
```csharp
builder.Services.AddMsalAuthentication<RemoteAuthenticationState, OidcAccount>()
.AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, OidcAccount, 
CustomAccountFactory>();
```
That's what actually worked in the AAD groups and roles scenario on the https://github.com/dotnet/AspNetCore.Docs/pull/18145 PR (i.e., adding it to `AddApiAuthorization` was a no-op for the scenario). Also, …

Update Blazor custom user account section

---

aspnetcore/includes/blazor-security/azuread-roles-groups.md
aspnetcore/mvc/models/file-uploads.md
aspnetcore/security/blazor/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md
aspnetcore/toc.yml
aspnetcore/whats-new/2020-04.md

Fixes #17660
Fixes #17927
Fixes #17928
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1&branch=pr-en-us-18145)
:tada::beers: I'm *very happy* to present how to use AAD groups, built-in Administrative Roles, and user-defined roles with Blazor WASM apps.
B2C for these approaches is going to require a bit more elbow grease given that it has to be done via Graph API. That's on [another issue](https://github.com/dotnet/AspNetCore.Docs/issues/17683) for another day.
This PR focuses on creating an INCLUDE that's used in the following WASM security topics:
* Standalone with Microsoft Accounts
* Standalone with AAD
* Hosted with AAD
You won't find the Object ID table **_anywhere on …

Blazor WASM with AAD groups and roles

---

aspnetcore/security/gdpr.md

The GDPR URL points to https://www.eugdpr.org/ which reports to be under construction.
I propose using this: https://ec.europa.eu/info/law/law-topic/data-protection/reform/what-does-general-data-protection-regulation-gdpr-govern_en
P.S.: I'm not a lawyer.

Change GDPR URL

---

aspnetcore/includes/IdentityServer4.md

Removes excessive `]` that shows up in the rendered markdown in the docs.
Docs: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio

Fix Azure AD B2C markdown link

---

aspnetcore/blazor/call-web-api.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Fixes #18230
* Important improvements to our Blazor WASM call web API coverage.
* Client coverage added and improved, including for named and typed clients.
* Naming consistency in code examples.
* The insecure approaches are in the *Call web API* topic with the rest of the insecure approaches.
* The secure approaches are in the Blazor WASM security node with the rest of the secure approaches.
* How to add an insecure client to an app with a default secure client is in an *Additional Scenarios* topic section and cross-linked from the rest of the Blazor WASM security topics.  
Thanks 🛸 **_@Alienroid_** 👽 for the suggestion and discussion on the issue.
There will be more improvements on the upcoming UE pass for all Blazor topics post 3.2 GA. For now, these changes surface and improve basic …

Blazor call web API enhancements

---

aspnetcore/toc.yml

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/18171
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-1.0&branch=pr-en-us-18279)
I also added ">>" to denote that the MS Learn links navigate away from our Table of Contents (ToC).

Move MS Learn ToC links to Tutorials

---

aspnetcore/tutorials/grpc/readme.md

Internal Review:  No actual build preview is generated since this is a sample readme pulled in by the samples system.
Minor link fix: Just updated 3 links at the bottom so they did not refer to a specific version of the docs and instead will point to whatever is latest.
Related to #16467

gRPC sample link fix

---

aspnetcore/performance/caching/memory.md

Fixes #18289
[Internal review 2.1 version](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1&branch=pr-en-us-18295#background-cache-update-1)

Update cache in background

---

aspnetcore/performance/caching/middleware.md

Related to #18298 
Some markdown was fixed in one version, but not the other.
This updates the other one.
(`[VaryByHeader](/aspnet/core/performance/caching/response#vary) property`)

fix markdown url

---

aspnetcore/security/blazor/webassembly/index.md

Fixes #18309
This should do the trick. Although we generally refrain from link lists in *Overview* topics, it isn't clear to readers what the next step is. The next step depends on their provider. General OIDC guidance for non-MS, non-Identity Server is in the first topic. The link text for that one should help readers find it.
Let's see how this goes. If readers report additional issues, we can try another approach, such as moving the basic OIDC coverage from the first topic into the *Overview* ... but let's not do that as a first step. That's the opposite of what I've been trying to do to simplify the TOC and remove duplication.
Thanks @yopez83!

Blazor Security Overview update

---

aspnetcore/test/integration-tests.md

The proposed override of `CreateHostBuilder` throws `NullReferenceException`s when the SUT provides an `IWebHostBuilder` rather than `IHostBuilder`.
Further, following the same environment variable approach does not work for `IWebHostBuilder`; however, `UseEnvironment()`  does work and is a single line.
@Rick-Anderson  edit:
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1&branch=pr-en-us-18313#set-the-environment)

Add info for setting environment on IWebHostBuilder

---

aspnetcore/signalr/client-features.md
aspnetcore/toc.yml

In reviewing https://github.com/dotnet/aspnetcore/issues/21618 and other issues about compatibility and versioning I figured this doc could use a quick update. Here's a first stab at it. I'm going to check the TOCs shortly and look at the internal review site, since I changed some titles.

SignalR Client Features doc -> SignalR Clients overview doc

---

aspnetcore/blazor/forms-validation.md

Using `@` in the `OnSubmit` is the old way of doing it

Removed `@` symbol in `OnSubmit`

---

aspnetcore/fundamentals/logging/index.md

There were a few broken links in the Built-in logging providers section.

Fixed Built-in logging providers links in index.md

---

aspnetcore/security/blazor/server/additional-scenarios.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #18045
Internal Review Topics (links to *Use Open ID Connect (OIDC) v2.0 endpoints* section of each) ...
* [Blazor Server Additional Scenarios](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/server/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-18308#use-open-id-connect-oidc-v20-endpoints)
* [Blazor WASM Additional Scenarios](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-18308#use-open-id-connect-oidc-v20-endpoints)
This PR seeks to surface https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8#updating-your-application-to-use-v20-endpoints coverage in the Server and WASM topics.
IIRC I tested this guidance on Blazor Server a while back and it worked …

Blazor with OIDC v2.0 endpoint coverage

---

aspnetcore/signalr/groups.md

Fixes #17217.
I also took the liberty of removing "you". I can roll it back to just the xref if that's preferred, of course.

Link from SignalR groups to authn/authz

---

aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md

Fixes #17317
Fixes #17649
Thanks @caleblloyd, @AlbertoPa, @hakenr, and @denmitchell.
[Internal Review Topic (links to *Name and role claim with API authorization* section)](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&branch=pr-en-us-18278#name-and-role-claim-with-api-authorization) ... and see the following new section here on *Profile Service*.
Some of the ask on #17317 was worked on prior PRs. The parts that pertain to Identity Server are on this PR.
The guidance on the PR **_only supports ONE role per authenticated user_**. I ran into a problem trying to use the factory pattern for multiple roles. If all you want to do is support one role per user right now, then the PR is fine for now, and we can …

Name and role for Blazor with Identity Server

---

aspnetcore/web-api/advanced/formatting.md

The NuGet package name within link text is getting over-localized, so suggest to make the link text as inline code to prevent this.

prevent over-localization in link text

---

aspnetcore/razor-pages/ui-class.md

Fixes #13951
I chased my tail for a while trying to find out why my static assets wouldn't serve from my Razor Class Library's NuGet package -- it was due to using `nuget pack` instead of `dotnet pack`.  This warning would've alerted me immediately to the issue.  Thankfully I found it via a comment at the bottom of the doc page.

Add warning about dotnet pack and static assets

---

aspnetcore/web-api/http-repl.md

Adds documentation for the `httpClient.useDefaultCredentials` preference in HttpRepl.
As always, @scottaddie feel free to wordsmith as necessary - but I think I got the bones right.

Add documentation for default credential use

---

aspnetcore/mvc/controllers/routing/samples/3.x/main/Controllers/MyDemo2Controller.cs

A very minor indent fix for the code sample that can be found here: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#reserved-routing-names

Fix indent in MVC routing code sample

---

aspnetcore/blazor/components.md

The **Component parameters** section contains a superfluous `xref` which gets rendered as text:
> with the [`[Parameter]`](xref:Microsoft.AspNetCore.Components.ParameterAttribute)](xref:Microsoft.AspNetCore.Components.ParameterAttribute) attribute.
The redundant second `xref` shall be removed:
> with the [`[Parameter]`](xref:Microsoft.AspNetCore.Components.ParameterAttribute) attribute.

Remove double xref reference to ParameterAttribute

---

aspnetcore/blazor/hosting-model-configuration.md

Addresses #18516
Let's make this example based on "Local" and a placeholder for authority and client id. We don't want to suggest Azure AD with `AddOidcAuthentication` here.
Also, check me on the statement ... `options.ProviderOptions`, not just `options`. That matches the *Standalone with Auth Lib* topic at ...
https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1#authentication-service-support
... where we show ...
```csharp
builder.Services.AddOidcAuthentication(options =>
{
builder.Configuration.Bind("Local", options.ProviderOptions);
});
```
I never tested this scenario because I don't have a non-Azure, non-Identity Server OIDC provider readily available.
This seems correct [a test app loaded config …

Patch Blazor config example

---

aspnetcore/host-and-deploy/blazor/webassembly/_samples/web.config

Blazor WebAssembly apps have a .dat file for the timezone data, but it's missing from the sample web.config.

Add .dat to sample web.config

---

aspnetcore/blazor/dependency-injection.md
aspnetcore/fundamentals/dependency-injection.md

Fixes #17766
Fixes #17775
[Internal Review Topic (links to new *IDisposable guidance for Transient and shared instances* section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1&branch=pr-en-us-18306#idisposable-guidance-for-transient-and-shared-instances)
The new section appears twice ... 2.x and 3.x parts of the doc ... so you only need to review the first instance of the section. See :point_right: **Lines 454-487**.
Thanks @brandondahler! 🎷

IDisposable guidance for Transient and shared instances

---

aspnetcore/index.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-1.0&branch=pr-en-us-18649)  
Partial fix for: #18647 
* Changed title to "ASP.NET Core documentation"
*  Added link to ASP.NET 4.x content in description.

Hub page title and description update

---

aspnetcore/fundamentals/localization.md

As the whole document refers to the sample code, the invalid URL should be fixed.
As the document targets .NET Core 3 or newer, I've changed the URL to the 3.x sample code instead of the parent directory including samples for .NET Core 2 as well.

Fix link to localization sample

---

aspnetcore/security/authentication/certauth.md

Clarification: client certificate settings are configured on servers like IIS and Kestrel, not hosts like WebHost. Admittedly the two blur when you get to places like Azure.
Preview: https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0&branch=tratcher%2Fhostserver

Certificates are managed by your server, not host

---

aspnetcore/index.yml

Fixes #18686 
Minor Change:
- Title to ASP.NET Documentation.
- Meta data title to ASP.NET Documentation
- Removed 4.x link from section summary since link are not supported there.

Hub title and metadata update

---

aspnetcore/release-notes/aspnetcore-3.1.md

Fixing what appears to be a typo, correcting RenderModel.ServerPrerendered to RenderMode.ServerPrerendered

Typo correction

---

aspnetcore/tutorials/first-mvc-app/adding-view.md

Before:
> The default view file has the same name as the method (`Index`), so in the */Views/HelloWorld/Index.cshtml* is used.
After:
> The default view file has the same name as the method (`Index`), so the view template in */Views/HelloWorld/Index.cshtml* is used.

adding-view.md: add missing words

---

aspnetcore/fundamentals/configuration/options.md

Fixes #18538.
Some of the wording around the NuGet package was shamelessly _borrowed_ from [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#package).

Add note for ValidateDataAnnotations NuGet package

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Models/MovieDateRatingDA.cs

Update Genre regular expression to match the intention as described in the tutorial text.
[This page](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md) says that Genre:
* Must only use letters
* The first letter is required to be uppercase. White space, numbers, and special characters are not allowed.
The original regular expression used:
`@"^[A-Z]+[a-zA-Z""'\s-]*$"`
says to allow double quotes, whitespace, and dashes after the first letter. This contradicts "must only use letters".

Genre regular expression

---

aspnetcore/tutorials/first-mvc-app/controller-methods-views.md

controller-methods-views.md: Remove extraneous dash.
Before:
> The - Label Tag Helper displays the name of
After:
> The Label Tag Helper displays the name of

Remove extraneous dash

---

aspnetcore/blazor/progressive-web-app.md

Fixes #18726
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&branch=pr-en-us-18729#interaction-with-authentication)
* The CarChecker app doesn't demonstrate the first bullet on serving a cached version of *_configuration/clientid* when the app is offline. What specific guidance can the topic provide?
* It's probably best if we refer to the factory and `LoginStatus` component in the CarChecker app. It's a slippery slope trying to put the code in ... one bit of code and text quickly leads to placing more code, which further leads to more text. It snowballs into a giant section. For now, readers can study the CarChecker sample app.

Enhance Blazor offline auth scenario content

---

aspnetcore/security/authentication/identity-custom-storage-providers.md

The View or download sample from GitHub link on this page currently points to a generic identity sample instead of the custom storage providers sample that actual contains the code shown in the article. This change fixes the link to point to the expected sample.

Fix link to point to correct sample

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Fixes #18752
I was curious to see if the word "consent" would work better with an alternate spelling. I just think it's good if we change the spelling of words occasionally to see if they look better on the screen or sound better when spoken. *Nah!* ... let's stick with "consent." I think that's best. 😁 
Seriously tho ... Azure portal UI screens threw me off for a sec on the other checks that I was making for potential updates this morning. I changed tenant directories from my default directory to the one that I've been using lately for Blazor apps, and the Azure portal matches the topics as written, so I think we're still good on the current instructions.
Will get back into this node on soon for [VS guidance in Blazor WASM security …

Misspelled word in Blazor WASM security topics

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/signalr/diagnostics.md

Fixes #18744
Note: I hope eventually to have `WebAssemblyConsoleLogger` in the API docs.

Blazor WASM SignalR client logging

---

aspnetcore/includes/net-core-prereqs-vs-5.0.md

Update per discussion with Sourabh

Change VS 2019 16.7 requirement to 16.6 for ASP.NET Core 5.0

---

aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/migration/22-to-30.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/signalr/authn-and-authz.md
aspnetcore/signalr/configuration.md
aspnetcore/signalr/dotnet-client.md
aspnetcore/signalr/groups/sample/wwwroot/ts/chat.ts
aspnetcore/signalr/hub-filters.md
aspnetcore/signalr/hubcontext.md
aspnetcore/signalr/hubs/sample/wwwroot/ts/chat.ts
aspnetcore/signalr/javascript-client.md
aspnetcore/signalr/javascript-client/sample/wwwroot/ts/chat.ts
aspnetcore/signalr/messagepackhubprotocol.md
aspnetcore/signalr/security.md
aspnetcore/signalr/security/sample/Startup.cs
aspnetcore/signalr/version-differences.md
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Pages/Index.razor
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/Startup.cs
aspnetcore/tutorials/signalr/sample-snapshot/2.x/Startup.cs
aspnetcore/tutorials/signalr/sample-snapshot/3.x/Startup.cs

Fixes #18758
* Went lowercase in URL endpoints everywhere (`chathub`).
* There was just one `var client =` to update.

SignalR naming consistency

---

aspnetcore/blazor/lifecycle.md

Addresses #16287
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1&branch=pr-en-us-18610)
I clarify lifecycle method ordering in two ways:
* I re-order the sections by *lifecycle method calling order*. To do so, I move the *Before parameters are set* section above the *Component initialization methods* section.
* I reword the explanations on when methods are called to clarify the order in each section.
Do you still want to produce a *lifecycle diagram* (a graphic) with additional goodness and/or address issue asks in other ways, e.g., "broadly how components work"?
If this is as far as you want to go right now, then I'll merge and close the issue. Otherwise, I'll leave that issue as a P1 assigned to you.

Blazor lifecycle ordering clarifications

---

aspnetcore/security/authentication/customize-identity-model.md

Usage of AddDefaultIdentity does not match the description here
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio#adddefaultidentity-and-addidentity
Changed to AddIdentity where subsequently chained calls are duplicating calls made inside AddDefaultIdentity

Don't duplicate calls made in AddDefaultIdentity

---

aspnetcore/web-api/advanced/formatting.md

Fixes #18804.
Fxed the link in question but also changed the first to point to `ContentResult`, which I think _might_ have been the original intent.

Fix up API links to ContentResult and Content

---

aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

Addresses  #18372
UI for reader interaction is normally set in bold. Templates and code examples aren't localized. Topics must occasionally call out unlocalized UI from templates and code. I'm trying a test with the two Blazor tutorials. For example, the ToDo List app code includes a button with "Add todo" text. I'll see how the following convention works ...
```
**`Add todo`**
```

Blazor localization updates

---

aspnetcore/blazor/call-web-api.md

Highlighting that the article doesn't apply to server side Blazor

Highlighting applicability to server side Blazor

---

aspnetcore/blazor/fundamentals/additional-scenarios.md

"IncludeRequestCredentialsMessagHandler" has a missing "e" in "Message".

Fix typo in class name of examples.

---

aspnetcore/blazor/components/event-handling.md

Ever since C# 5.0, the `foreach` variable can be captured in a lambda, and it works. [See the breaking changes section from the VS magazine back then.](https://visualstudiomagazine.com/articles/2012/11/01/more-than-just-async.aspx)
I tested it in Blazor, and `foreach` does not break like `for` does.

`foreach` variable can be captured.

---

aspnetcore/security/authorization/simple.md

@pranavkm can you help with the wording? This seems like the easiest approach to me. It's what I'd do if I needed mixed auth.
Now we have 2 very simple work arounds and one complex.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1&branch=pr-en-us-18879#authorize-attribute-and-razor-pages)

Use dedicated controllers for mixed attributes

---

aspnetcore/fundamentals/logging/index.md

Fixes #18997
Corrected typo regarding default log levels for EventLog.

Fix EventLog remark

---

aspnetcore/grpc/browser.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1&branch=pr-en-us-18995)
Fixes #18985 .   
Clarifying the Intro:
* Make it clear in the intro that this article assumes an existing gRPC service using ASP.NET Core
* Added links referring how to add gRPC to an existing ASP.NET app and one for getting started creating a gRPC service with ASP.NET Core.

Clarified gRPC Browser intro

---

aspnetcore/blazor/fundamentals/additional-scenarios.md
aspnetcore/fundamentals/url-rewriting.md

Addresses #19007
I'll just hit two of them in topics that I worked, a Blazor topic and the URL Rewriting topic.

Convert API link and code in table headers to text

---

aspnetcore/blazor/components/event-handling.md

Fixes #18827
Thanks @surenazatyan! :rocket:
The remark is confusing, and we generally don't need to document a **_non-conflict_**. All this means is that one can add these prevented actions per the guidance in this section **_in addition to_** a Blazor event handler that prevents the default action for whatever event the handler is handling. I think we'd only need to say something about this if there was a conflict or *gotcha* of some sort.

Remove confusing Blazor event handling remark

---

aspnetcore/blazor/components/data-binding.md
aspnetcore/blazor/forms-validation.md

Fixes #18900
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1&branch=pr-en-us-18930#binding-select-element-options-to-c-object-null-values)

Blazor select option binding

---

aspnetcore/blazor/components/index.md

Fixes #18713
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-19038#capture-references-to-components)
Per https://github.com/dotnet/aspnetcore/issues/22658#issuecomment-640731227 ...
> What you're trying to do is not supported. The reference variable may not be assigned by the time onclick is assigned. Doing through the lambda is the right thing to do.

Improve Blazor references to components

---

aspnetcore/blazor/security/webassembly/additional-scenarios.md

Fixes #19001
Thanks @gregorvilkner! :rocket:
The goal here is to use the generic `https://www.example.com/base` URL in the examples, which matches what we're showing for an `authorizedUrls` entry, **_BUT_** not leave devs in the dark when they're looking at a Blazor Hosted solution, where the base address can be set to `new Uri(builder.HostEnvironment.BaseAddress)`. That's what will match the default template experience.

Generic Blazor WASM base address

---

aspnetcore/blazor/components/index.md

Address https://github.com/dotnet/AspNetCore.Docs/pull/19102/files#r450232194 ...
The 2nd `Expander` component shouldn't have content in order to demo the behavior described by the text. If I had **_read the text_** during the update, I would've seen that. 🙈 ....... *I'll slow down when I get another 15 issues closed out.* 🏃😅 
Thank you @serpent5 🐢 for catching that.

Revert part of Expander update

---

aspnetcore/blazor/components/lifecycle.md

Fixes #17939
Thanks @mrlife ...
> in one place all ways the lifecycle comes into play
... isn't specifically actionable. We can cross-link the `StateHasChanged` behavior for `EventCallback` in the Lifecycle topic's `StateHasChanged` section (on this PR), but either I don't understand your ask or I don't think that what you're asking for can be done differently than the way that we already handle this using two topics, one on events and one on lifecycle.

StateHasChanged behavior for EventCallback

---

aspnetcore/blazor/debug.md
aspnetcore/blazor/tooling.md

Fixes  #19108
They will have very probably already installed the C# extension per our earlier guidance. Therefore, I think we can drop all of this lead-in content.

Drop JS Debugger extension guidance

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Looks like this was missed (by me probably 🙈) when we updated it in the IIS topic per https://github.com/dotnet/AspNetCore.Docs/pull/16506#pullrequestreview-346809599.

Update supported WS version

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
aspnetcore/blazor/tooling.md
aspnetcore/includes/blazor-security/azure-scope.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes #18379
Fixes #17913
Fixes #19143
Thanks @jlinstrum! :rocket:
Thanks @c0g1t8! :rocket:
* Tooling tabs can only be added for the *auth lib* and *Identity Server* topics because VS hasn't activated single and multi-organization auth options for Blazor WASM apps yet. We'll have to stick with the CLI for now for MS accounts, Azure AD, and Azure AD B2C topics.
* To improve translation of settings from the portal, I attempt to match how the portal names things to the placeholders in the `dotnet new` commands. I do this in the text, and I add a table of placeholders under each command. Combined with showing the app settings files from the apps (already in the topics today), it should be enough to keep devs *mostly* 🤞 on the right track for getting their apps configured.
* I think we'll …

Blazor WASM security topic enhancements

---

aspnetcore/grpc/basics.md
aspnetcore/grpc/troubleshoot.md

Addresses https://github.com/grpc/grpc-dotnet/issues/605
Move useful information from troubleshooting page to primary docs

Move docs to gRPC on C# page

---

aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/security/webassembly/index.md
aspnetcore/toc.yml
aspnetcore/tutorials/build-a-blazor-app.md

Fixes #19124
Fixes #18829
The issues explain the problems that I'm seeking to resolve, including with screenshots in #19124. AFAICT, the sidebar ToC doesn't have any capacity to short-circuit URL matching behavior (https://dotnet.github.io/docfx/tutorial/intro_toc.html). It selects links in ways that are detrimental to desirable navigation:
* The built-in components ToC entries are selected when following cross-links in other contexts.
* Following cross-links within the doc set, the *Security and Identity* node Blazor topics are selected when the reader should see the Blazor ToC node entry for the topics. Seems that the selection is made top-to-bottom and then based on indent level.
* Internal (MS doc search) and external (Google, etc.) referrals result in ToC node topic selection outside …

Blazor ToC improvements

---

aspnetcore/blazor/fundamentals/additional-scenarios.md

Fixes #19153
Addresses #14134
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-19172#configure-the-signalr-client-for-blazor-server-apps)
* The rubber 🦆 said, "*They all get `autostart="false"` for the `blazor.server.js` script.*" ... Is Mr. 🦆 correct?
* Can we address the first bullet point of https://github.com/dotnet/AspNetCore.Docs/issues/14134 here if ...
> Manually starting the blazor application
... means calling `Blazor.start`? If so, how do we phrase the coverage (e.g., just say 'set autostart to false and call Blazor.start when/where u want the app to start')? Do we need to show an example? If so, what? ... something simple like ...
```cshtml
...
<script …
```

Add Blazor SignalR client config

---

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md

Fixes #19208
Addresses #19151
Thanks @psiservices-mhart and @Ef0Dev! :rocket: ... Sorry again for my wrong (**_but logical_**) guess. I still don't know if the client config of the *Hosted with IdS* would ✨ *Just Work!*:tm: ✨ or not, but following the *Standalone with auth lib* topic is the supported/recommended approach for this scenario, even if my (incorrect) suggestion does work.
I think we only need to go one-way with the cross-link and not necessarily call out the external IdS scenario in the *Standalone with auth lib* topic. I may mention this there later if readers are still confused. Right now, let's get the scenario surfaced to move the reader to the right spot as soon as they land in the *Hosted with IdS* topic.

Cross-link Blazor WASM IdS to auth lib topic

---

aspnetcore/blazor/fundamentals/routing.md

Fixes  #18940
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1&branch=pr-en-us-19200#query-string-and-parse-parameters)
Avoiding a gerund in the section heading (i.e., "parse" over "parsing," which probably doesn't translate well).
Thanks @softchris! :rocket: ... would u like to review this?
cc: @mkArtakMSFT ... I'm going to go ahead with this, as it's fairly pedestrian stuff. If you spot anything, I'm :ear: to set up a patch.

Blazor query string parsing

---

aspnetcore/blazor/fundamentals/routing.md
aspnetcore/blazor/host-and-deploy/index.md

Fixes #13856
Addresses #14134
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?view=aspnetcore-3.1&branch=pr-en-us-19215#app-base-path)
Thanks @jerriep! :rocket: ... Sorry for the delay. We've been busy with a lot of high priority updates over the past several months.
* I add this to the *App base path* section in the *Host and deploy* overview.
* I cross-link to that section from the *Routing* topic.
* Based this on Artak's engineering remark at https://github.com/dotnet/aspnetcore/issues/13167#issuecomment-521710865.
I've only tested the Blazor WASM scenario, not the Blazor Server scenario. I haven't confirmed that it works ok. We'll see if the community sends me a 💀 *Rex Death Threat!* 💀😨

Blazor Server non-root URL hosting

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/fundamentals/routing.md

Fixes #19166 
* [Internal Review Topic (links to section in *Routing*)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1&branch=pr-en-us-19198#navlink-component)
* [Internal Review Topic (links to section in *Components* overview)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-19198#child-content)
I'd like to cover this in both *Routing* and *Components* because the *Routing* topic is considered more *fundamental* than the *Components* topic and will often be consumed first. I don't want the reader to *click forward* into the *Components* topic while reading about routing. Therefore, I cover it twice but using different language and examples.
I'm going with a forceful …

Closing over loop vars in child content

---

aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #18183
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-19158#nginx)
Thanks @OrihuelaConde! :rocket: Sorry for the delay. We've been busy with high priority doc updates. I'm digging out now ⛏️⛰️😅.
Sourabh, I'm not aware of a corollary for Apache's `mod_ratelimit`. There are no engineering repo issues for Blazor WASM and Apache pertaining to any problem in this area ...
https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+apache
... so perhaps there's no problem to address on Apache.

Blazor WASM Nginx burst rate limit

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Program.cs
aspnetcore/blazor/fundamentals/configuration.md
aspnetcore/blazor/fundamentals/dependency-injection.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Program.cs

Fixes #18359
Now that 3.1.6 is out, this updates service registrations from transient to scoped ...
* `HttpClient`
* `IHttpClientFactory`
* `CustomAuthorizationMessageHandler` (`AuthorizationMessageHandler`)

Blazor scoped service registrations

---

aspnetcore/security/authentication/accconfirm.md
aspnetcore/security/authentication/identity-configuration.md
aspnetcore/security/authentication/scaffold-identity.md

Fixes #18704
* Calls out the possibility that the dev will need to match the `[StringLength]` attribute in scaffolded pages to their `PasswordOptions` config in `Startup.ConfigureServices`.
* Update some versioning along the way.
* Fix up a table structure.

Password configuration

---

aspnetcore/mvc/models/file-uploads.md
aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Startup.cs
aspnetcore/razor-pages/index.md
aspnetcore/razor-pages/index/3.0sample/RazorPagesContacts/StartupRPoptions.cs
aspnetcore/razor-pages/index/3.0sample/RazorPagesContacts/StartupWithRazorPagesAtContentRoot.cs
aspnetcore/razor-pages/index/3.0sample/RazorPagesContacts/StartupWithRazorPagesRoot.cs
aspnetcore/razor-pages/razor-pages-conventions.md
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Startup.cs
aspnetcore/security/authentication/cookie/samples/3.x/CookieSample/Startup.cs
aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/Startup.cs
aspnetcore/security/authorization/razor-pages-authorization.md
aspnetcore/security/authorization/razor-pages-authorization/samples/3.x/AuthorizationSample/Startup.cs
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/src/RazorPagesProject/Startup.cs

Fixes #19245.
Created as a draft because:
1. I need to run through the changes I've made again tomorrow.
1. I can also replace all the `/dotnet/api` links with `xref:` links in the files I've touched. Let me know and I'll happily do so. There's a few unescaped `*`s in there, too.
cc @guardrex, @Rick-Anderson

Use AddRazorPages(options => ...) where appropriate

---

aspnetcore/web-api/index.md

Potential fix for inconsistency between automatic `[ApiController]` 400 response and `BadRequest()` result.
Fixes #19258

 Fix 400 responses inconsistency

---

aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs

Fixes #19263
Thanks @MatsyshynAnton! :rocket: ... we'll get a nice little update here based on your issue.
**_Confirmed_** ... a `null` descriptor doesn't break `Remove`. It returns `false` for `null` or a unmatched service descriptor.
Also, the content in the code comments is explained in localized topic text following the code example, so the code comments can be ...
**_Banished to the land of wind and ghosts._** - Ryan Nowak, 2019

Update integration tests sample app

---

aspnetcore/tutorials/first-web-api.md

I've updated the install instructions for what packages you need to install.
The reason I have added the second lot of instructions is because it wasn't clear you needed to run an install for Microsoft.EntityFrameworkCore.InMemory too. 
The heading only mentioned adding Microsoft.EntityFrameworkCore.SqlServer so once I had did that, I missed the second part of installing Microsoft.EntityFrameworkCore.InMemory.

Change to instructions for First Web API tutorial

---

aspnetcore/mvc/controllers/testing.md
aspnetcore/test/razor-pages-tests.md

Fixes #19223
As discussed in the issue, I am adding JustMockLite to links in the additional resources section.
Please have in mind that I also changed the "Razor Pages unit tests in ASP.NET Core" article to include the same link in the additional resources section.

Add JustMockLite to additional resources

---

aspnetcore/includes/requireAuth.md
aspnetcore/security/authentication/identity-configuration.md
aspnetcore/security/authentication/identity.md
aspnetcore/security/authentication/index.md
aspnetcore/security/authorization/policies.md
aspnetcore/security/authorization/secure-data.md
aspnetcore/security/authorization/secure-data/samples/final3/Startup2.cs
aspnetcore/security/authorization/simple.md

Fixes https://github.com/dotnet/aspnetcore/discussions/23008
Fixes #18843
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1&branch=pr-en-us-18825#rau)

Doc global require authenticated users

---

aspnetcore/fundamentals/routing.md

The current link points to the no longer existent 3.0 release. This changes it to 3.1.

Fix broken link to IAuthorizationPolicyProvider sample

---

aspnetcore/grpc/client.md

Use new `Metadata.GetValue(name)` to get trailer values.

Improve gRPC client trailers code

---

aspnetcore/security/authentication/samples.md

Fixes #19093
Most of the samples exist in `release/2.1`, but the changes in 15cae94e247f69c489c594a52730bf7fb3c1f75b show the two examples that don't exist for that branch. I changed them to the `2.1.3` branch, which has them, but there are also a number of `v2.1.x` tags that would work as well. 
Additionally, I wasn't sure if these should be excluded since they don't exist on the release branch or if the other examples should be changed as well so that all the samples are coming from the same branch (this might be desirable given the directions in the Run the Samples section).
I can make changes as needed.

Fix broken sample links pointing to release/2.2

---

aspnetcore/blazor/fundamentals/configuration.md
aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationContext.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationProvider.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationSource.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Extensions/EntityFrameworkExtensions.cs
aspnetcore/fundamentals/configuration/index/samples_snippets/3.x/ConfigurationSample/Program.cs

Fixes #18134
Internal Review Topics:
* [ASP.NET Core Configuration (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1&branch=pr-en-us-19293#custom-configuration-provider)
* [Blazor Configuration (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.1&branch=pr-en-us-19293#aspnet-core-blazor-configuration)
Notes:
* The EF Core config provider **_seems ok_**. `Load` is called once at startup. The example doesn't implement a reload-on-change feature, so it *might be* ok wrt the db context concurrency concern. Let me know if we need to totally warn off of this provider for some reason. :ear:
* I add the namespaces to the example in the ASP.NET Core …

Configuration updates

---

aspnetcore/razor-pages/index.md

Following the guide as written results in an error. UseInMemoryDatabase is provided by an additional package, and VS wasn't smart enough to be able to pull this down.

Add missing nuget reference for razor pages

---

aspnetcore/blazor/debug.md

Fixes #19377
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&branch=pr-en-us-19378)
* I prefer a compiler directive for this because a conditional check based on environment would run all the time. `DEBUG` is built-in. Idk if this will work in a Razor file like this. If there's any doubt on it, I'll run a test and confirm that the approach works. Let me know if I should run such a test. :ear:
* What do we show for the recommended delay line?
* Won't we need **_two examples_** of whatever the delay line is? ... one for synch and one for async.

Blazor WASM breakpoints in OnInitialized

---

aspnetcore/blazor/fundamentals/additional-scenarios.md
aspnetcore/toc.yml

Fixes #19265
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-19276#influence-html-head-tag-elements)
@MackinnonBuck, check carefully my translation of your "characteristics" notes. It's very easy for me to make a mistake when translating engineering notes. For example ...
> Only the `Value` parameter is valid in `Title`. For `Meta` and `Link`, all provided parameters will be reflected in the DOM.
... could mean a few different things depending on interpretation, so we might need to do a little more work here if I guessed wrong.
Sorry for the *update noise* 🙉 ... kept seeing little nits to touch.
I'll put this on draft until we get to Preview 8 and merge at that time. …

 [Preview 8] [READY] Blazor HTML <head> tag control

---

aspnetcore/blazor/components/class-libraries.md

Fixes #19317
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-3.1&branch=pr-en-us-19333)
* Adds the `Link` component to the Blazor RCL content.
* Explains how to get the stylesheet applied to components: 5.0+ with `Link` component or `<link>` tag and <5.0 with a `<link>` tag.
* Better naming: I've been leaning away from `My`-named things these days, so I name the lib `ComponentLibrary`. Also, I go with the project template-generated example component in the RCL named `Component1.razor`.
* I went ahead and cross-linked the `Link` component. There's no build warning on the premature link here, but the coverage won't be there until [[Preview 8] Blazor HTML <head> tag control (dotnet/AspNetCore.Docs …

[Preview 8] [READY] Blazor RCL stylesheet and Link component

---

aspnetcore/fundamentals/configuration/index.md

It was part of the "Configuration providers" section, but it should be part of the "File configuration provider" section, after the "INI configuration provider" section.

Move "JSON configuration provider" section to correct place

---

aspnetcore/blazor/components/integrate-components.md
aspnetcore/blazor/fundamentals/routing.md
aspnetcore/blazor/webassembly-lazy-load-assemblies.md
aspnetcore/blazor/webassembly-performance-best-practices.md
aspnetcore/toc.yml

Fixes #19149
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0&branch=pr-en-us-19211)
* This is the *hybrid* tutorial-like reference topic approach. We could just plop the complete example down and write thereafter about how it works, but I think there's merit to the approach on the PR that breaks it down into logical sections. This is the approach that you took with the design notes on the PR, and I think it works well here. However, let me know if you'd like to go the other way. I'm not opposed to a rewrite if you think it best.
* I originally pitched this for the *Host and deploy* node, but this is *really, REALLY* important perf that many devs are going to want to use. Therefore, I now recommend that …

Blazor WASM lazy load assemblies topic

---

aspnetcore/tutorials/dotnet-watch.md

Remove link to dotnet watch package now that it's included in the SDK

---

aspnetcore/blazor/fundamentals/additional-scenarios.md

Addresses #19434
Temporarily show this section (with a 5.0 note) until 5.0 because this section is linked directly from the Blazor ToC (*Built-in components*). The changes will be reverted when 5.0 ships later this year.
Thanks @augaldecr! :rocket:

Temporarily unversion Blazor doc section

---

aspnetcore/blazor/debug.md

Was working with a customer today who has v1.45 installed and we didn't see the "debug preview" option in settings.  We didn't know we had to upgrade to v1.47 and based on what was in the docs we were at a dead end.  Suggest telling user that either v1.47 or the extension is required.
azsdke2e

Add JavaScript extension message

---

.github/ISSUE_TEMPLATE/config.yml

Add a link to open an issue related to the docs.microsoft.com platform. The .NET docs team is already doing this. This option will be available to anyone clicking the **New issue** button:
See a live example at https://github.com/dotnet/docs/issues/new/choose.

Add link to open a general docs platform issue

---

aspnetcore/toc.yml

Rearrange the Learn section of the ToC to prepare for the microservices learning path. Also add a link to the new resiliency module (to be published on Monday, 8/10).
/cc: @CamSoper

Add ToC link to microservices resiliency Learn module

---

aspnetcore/azure/devops/cicd.md
aspnetcore/azure/devops/deploying-to-app-service.md
aspnetcore/azure/devops/index.md
aspnetcore/azure/devops/monitoring.md
aspnetcore/azure/devops/next-steps.md
aspnetcore/azure/devops/tools-and-downloads.md
aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md
aspnetcore/security/authentication/azure-ad-b2c.md
aspnetcore/signalr/diagnostics.md
aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md
aspnetcore/tutorials/publish-to-azure-webapp-using-vscode.md

Fixes #19467 19467
A temporary custom meta data value of "devx-track-csharp" is being used for identifying .NET + Azure topics (non-reference).
Added "devx-track-csharp" to ms.custom.

Updated metadata for C# .NET + Azure topic

---

aspnetcore/blazor/test.md
aspnetcore/toc.yml

Fixes #10747
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/test?view=aspnetcore-3.1&branch=pr-en-us-19474)
Assumes that we'll only keep **one** test Blazor topic (i.e., no node, no overview). When the time comes for E2E testing coverage, it would go into a section at the end of this topic.
cc: @egil

Blazor testing topic

---

aspnetcore/fundamentals/error-handling.md

Microsoft.AspNetCore.Diagnostics is now part of shared framework and not distributed separatedly via nuget

Remove ref to MS.AspNetCore.Diagnostics nuget

---

aspnetcore/security/authentication/customize-identity-model.md

Fixes #19531
Thanks @LiviuSosu! :rocket: ... I use placeholders quite a bit these days (e.g., `{...}`, `{VERSION}`, `{APP ASSEMBLY NAME}`, etc.), and they seem to work fairly well. Let's try that here.

Use placeholder for types remarks

---

aspnetcore/signalr/dotnet-client.md
aspnetcore/signalr/java-client.md
aspnetcore/signalr/javascript-client.md

Fixes #18710
I used ...
https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#what-is-the-meaning-of-service-mode-defaultserverlessclassic-how-can-i-choose
... for the additional information link because it seems like it has the most value. It explains out all three modes.
This PR modifies the existing NOTEs in the docs. If you want a section to call this out somewhere, I can add it (let me know where :ear:) and then cross-link to that. If what's on the PR is sufficient, we're good.

SignalR service mode guidance

---

aspnetcore/security/enforcing-ssl.md

@danroth27  can I change the target URL: 
https://docs.microsoft.com/aspnet/core/security/enforcing-ssl                  <-- Current
https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#ssl-linux   <-- Proposed

trust linux cert anchor

---

aspnetcore/migration/proper-to-2x/index.md

Fixes #19580
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-1.0&branch=pr-en-us-19581#bind-and-input-formatters)

Add [BIND] warning to migration guide

---

aspnetcore/blazor/forms-validation.md
aspnetcore/toc.yml

Fixes #19522
[Internal Review Topic (links to *Radio buttons* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1&branch=pr-en-us-19555#radio-buttons)
I'm not quite there locally for preview bits yet. I usually get on the new bits at RC1. This PR was derived from the engineering PR.
* `InputRadio` and `InputRadioGroup` component coverage.
* Standardizing the use of `@` on submit methods.

Blazor InputRadio/Group components

---

aspnetcore/data/entity-framework-6.md
aspnetcore/fundamentals/localization.md
aspnetcore/migration/http-modules.md
aspnetcore/migration/mvc.md
aspnetcore/migration/proper-to-2x/membership-to-core-identity.md
aspnetcore/mvc/views/tag-helpers/intro.md

Contributes towards resolving issue #19022 
Another round of MSDN Link fixes using an OPS pipeline. (Many more of these to come)
There was a blocking issue with running the scripts in the pipeline for a few weeks where it would not generate a branch.  It is back up and running now so I will be completing larger collections of these after this additional smaller trial run for this PR.
Links are verified.  Script has an issue where it will generate en-us/ local in links on occasion.  Had to remove those manually.
Zero warnings, including link warnings in test build.

MSDN Link migration - 2nd run

---

aspnetcore/migration/22-to-30.md

Reverts dotnet/AspNetCore.Docs#19596

Revert "RazorTemplateEngine removed/Migration doc"

---

aspnetcore/blazor/webassembly-lazy-load-assemblies.md

[HOLD, RC1] Blazor lazy load uses .dll extension

---

aspnetcore/blazor/forms-validation.md

Fixes #19633
It might be handy to foreshadow the proper section by adding a column to the built-in table. I think 🤔 that will be fine; but if it seems distracting, I'll kill that and we can just keep the section. :ear:

Blazor forms display name support

---

aspnetcore/blazor/debug.md

Fixes #19465
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&branch=pr-en-us-19659)
* Idk if we need to touch the [*Browser source maps* section](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#browser-source-maps). Do we need to qualify those remarks now that VS4Mac is in the topic?
* I couldn't get the **Debug in the browser** guidance to fully work. <kbd>Shift</kbd>+<kbd>&#8984;</kbd>+<kbd>d</kbd> gets the ball rolling with the **Unable to find debuggable browser tab** error page and the command seems to run. I can't get anywhere with it after that, and there is no `file://` node in **Sources**. I added a remark on this PR that says the guidance is only for Chrome or Edge on Windows.
* We'll have …

Blazor Debug WASM updates: VS4Mac guidance

---

aspnetcore/grpc/services.md
aspnetcore/toc.yml

Add a new doc: Create gRPC services
In the TOC I have grouped this with "gRPC services using C#". When the [Protobuf guide](https://github.com/dotnet/AspNetCore.Docs/pull/19623) is merged it will also be in this TOC group

Add Create gRPC services doc

---

aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md

Fixes #1737442
Addresses rebranding "Office 365" to "Microsoft 365".
I'll add a comment when the PR is ready for review. I'll leave the PR open for 48 hours and address any feedback. After that, I'll sign off for merge.
Thanks -

Rebrand Office 365 to Microsoft 365: User Story 1737442, Part 10

---

aspnetcore/test/middleware.md
aspnetcore/test/middleware/samples_snapshot/3.x/false-failure-check.cs
aspnetcore/test/middleware/samples_snapshot/3.x/final-test.cs
aspnetcore/test/middleware/samples_snapshot/3.x/request.cs

Fixes #19645.
I'm not sure that the original highlights are quite right. i.e. There's a highlight for the _CreateClient + Get_, then just the _CreateClient_, then the _Assert_. I'd say the first should be the (new) _CreateTestClient + Get_ line (there's no Assert), then the next should be the _Assert.NotEqual_ line, and then the _Assert.Equal_ line. Does that make sense?
cc @guardrex

Use GetTestClient() instead of GetTestServer().CreateClient()

---

aspnetcore/mvc/views/razor.md

The use of an HTML code section to display plain text rendered in the browser is misleading because browsers do not colour tags in plain text.

Escaped HTML code renders as plain text

---

.whatsnew.json

With Bill's changes in the following PR, the ".NET Platform" GitHub org. no longer has to be listed in the config file: https://dev.azure.com/mseng/TechnicalContent/_git/dotnet-docs-tools/pullrequest/571943

Remove .NET Platform org. from what's new config

---

aspnetcore/test/troubleshoot-azure-iis.md

There is a typo in the troubleshooting of IIS. This PR fixes this typo.

Fix typo in the troubleshooting of IIS

---

aspnetcore/blazor/components/index.md

Addresses #19789
@SteveSandersonMS ... This takes care of the second part of #19789. I'll knock out the first part (the password example) either after I hear back from you or after I've had a chance in the morning to see how it could be refactored to not write to itself but still be a chained bind example.

Blazor overwriting params

---

aspnetcore/blazor/fundamentals/additional-scenarios.md

Fixes #15373
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-19778#manual-start-of-the-blazor-app)
😕 ... I've run into a point of confusion that's even blocking this PR ...
Our content implies (and I was under the assumption) that when `autostart="false"` is placed on the script that calling `Blazor.start()` is absolutely required to get the app going. Testing here seems to indicate that that's not so. When I set the `_Host.cshtml` page up with **_only_** the following ...
```cshtml
<script autostart="false" src="_framework/blazor.server.js"></script>
```
and no call to `Blazor.start()`, the **_app still starts and runs normally_**, which I don't expect to happen. …

Enhance Blazor start content

---

aspnetcore/blazor/components/data-binding.md

Fixes #19789
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1&branch=pr-en-us-19799#child-to-parent-binding-with-chained-bind)
* The approaches now avoid writing to a component parameter and use a backing field instead.
* Using the *getter/setter* approach that [Ryan showed](https://github.com/dotnet/AspNetCore.Docs/issues/14144#issue-489386131) seems to only work when the component writes to the param per his original example. For this PR, I have the method that calls the binding delegate (`OnPasswordChanged`) make the checks. If that's not right, let me know how to handle that scenario. :ear: Even if that is the right spot, is calling `return Task.CompletedTask;` the right thing for a …

Blazor binding updates

---

aspnetcore/grpc/why-migrate-wcf-to-dotnet-grpc.md
aspnetcore/toc.yml
aspnetcore/tutorials/first-mvc-app/details.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/why-migrate-wcf-to-dotnet-grpc?view=aspnetcore-5.0&branch=pr-en-us-19768)
Fixes #19011 
This new topic is simply a short summary of the advantages of gRPC for WCF developers that also points them to the extensive eBook published for extensive guidance if the reader chooses to get started migrating.   The content here is the summary of advantages taken directly out of the book, and at the end of the summary it points to the eBook.
We generally really like to avoid copying content to put in two places, it affects SEO a bit for starters and they become out of sync. However the summary in the book is already short and to the point of what is needed here.  I put the eBook author in the "author" metadata.

New topic why migrate wcf to gRPC

---

aspnetcore/security/authentication/windowsauth.md

Fixes #19819
Thanks @aschuhardt! :rocket:
Capitalization in the Windows docs is *lowercase*, although I think they probably should have made these a proper nouns. They're named aspects of the product. Since they lowercase it tho, I lowercase them here. I'm :ear: for uppercase if you wish.
I cross-link twice. The NOTE might have the reader wishing to click at that point into the other topic. I don't think having them chase down the earlier link is best.

Cross-link Windows auth modes

---

aspnetcore/blazor/blazor-server-ef-core.md

Fixes  #19846
This is **_temporary_** until we can lay hands on **_version-by-file_**. At that point, I'll revert back to markdown-style headings.
cc: @Rick-Anderson @scottaddie @wadepickett ... The HTML tag headings approach bypasses the build system, but I did need to apply different tag ids. This approach provides stable text across sections without a visible version to readers. I'll just do this temporarily until hopefully 🤞 we get *version-by-file* and then revert back to plain markdown headings. 
This is the only Blazor topic with this problem right now, so it's trivial to revert later. I'll see how Blazor WASM security topics play out when I work the content for RC1. It might not be that bad. There might not be many changes, so whole-topic versioning might not be required. If so, I …

Drop markdown headings to solve dup headings

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/globalization-localization.md
aspnetcore/blazor/host-and-deploy/configure-linker.md
aspnetcore/blazor/host-and-deploy/configure-trimmer.md
aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/index.md
aspnetcore/blazor/webassembly-performance-best-practices.md
aspnetcore/toc.yml

Fixes #19848
[Internal Review Topic (Trimmer article)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-5.0&branch=pr-en-us-19849)
This looks good from a topic structure/ToC perspective.
We need to check the remarks in the other cross-linked topics on this PR to make sure that what they say about 'trimming' is still correct given that you said a lot of the linker content no longer applies.

Blazor WASM linker to trimmer

---

aspnetcore/blazor/security/server/additional-scenarios.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md
aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/blazor/security/webassembly/index.md

Fixes #19803
Thanks @taylorchasewhite! :rocket:
The enhancements include ...
* Flesh out a Graph API call from a component that's based on a named `HttpClient`. The existing content is *generic* for a named client and a custom `AuthorizationMessageHandler` class. This new example (AAD mobile phone number in component code) shows a specific implementation with those features that will work in a real app.
* Add a customize the user example (claims for users) based on Graph API. The existing customize the user coverage only deals with an access token claim (`amr`) that doesn't require a separate access token request. This new example (a claim for the AAD mobile phone number), similar to the example in the AAD groups and roles topic, shows a specific implementation with a separate Graph API …

Blazor WASM security updates

---

aspnetcore/blazor/forms-validation.md

Fixes #19850
Thanks @Paul-Dempsey! :rocket:
* I fixed the code languages.
* I decided to add a NOTE for the new radio button components to the current version content that instructs the reader that those two are new for 5.0 and to select a 5.0 or later version of the article for more info. I like that better than mucking up the ToC entries. I don't even think that I'll revert this NOTE at 5.0 GA. I think I'll just leave that there in case even after GA someone hits this topic at 3.x looking for those two components.
* I slept on the cross-links to the section with the table versus converting over to a section for each component. I changed my mind and think that *for the time being* we'll continue to link to the section. The purpose of the ToC entries is to get the reader to the right spot …

Blazor forms updates

---

aspnetcore/grpc/client.md
aspnetcore/toc.yml

Group topics under client and server to keep the top level menu clean.

Group gRPC client topics under a TOC parent

---

aspnetcore/blazor/components/component-virtualization.md
aspnetcore/blazor/webassembly-performance-best-practices.md
aspnetcore/toc.yml

Fixes #19871
Three concerns on this one:
* Consistency (I guess since it works either way) ... but there's still flexibility in how objects are assigned to component parameters in samples and examples. The blog post (and other assorted examples) assign **_without_** the `@` symbol, but we've been moving docs consistently to using `@` when the attribute isn't prefixed with `@`...
* `Items="@collection"` ... because what's in quotes isn't necessarily C# for a Blazor parameter. However, the framework seems to accept it without `@`. The examples in [the blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-component-virtualization) don't use `@` ... `<Virtualize Items="employees" Context="employee">`.
* `@bind="collection"` :+1:, **_NOT_** …

Blazor Virtualize component

---

aspnetcore/grpc/interprocess.md
aspnetcore/grpc/performance.md
aspnetcore/toc.yml

Use new `SocketsHttpHandler.ConnectCallback` in new inter-process docs.
The docs are unchanged apart from the client code sample.
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-5.0&branch=pr-en-us-19891

New gRPC inter-process doc

---

aspnetcore/grpc/protobuf.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19760
@jskeet

Protobuf scalar default values and ByteString detail

---

aspnetcore/toc.yml

@scottaddie ... No 🎲🎲 ... I tried both ...
* Using `topicHref`.
* Moving the node to the bottom.
It's not matching the first link to the landing page in the `toc.yml` file. It always matches the selected ToC entry.
I'm going to open a DocFX issue to ask them if the behavior I seek is possible.
If they say it isn't possible to achieve this behavior today, I'll ask them if they'll consider creating such a DocFX feature.
Thanks for your help.

Revert Blazor ToC back to original location

---

aspnetcore/toc.yml

Closes https://github.com/dotnet/AspNetCore.Docs/issues/19341
Add a link to the "Deploy a cloud-native ASP.NET Core microservice with GitHub Actions" MS Learn module.
The module is expected to publish on Tuesday, 9/22. Confirm module is live before merging this PR.

Add ToC link to DevOps with GitHub Actions Learn module

---

aspnetcore/security/authentication/social/microsoft-logins.md

Fixes #19795: common endpoint error
This pull request adds two sub-bullet points to App Registration setup on Azure dashboard:
- App Registration types supported by Microsoft Account NuGet package by default
- What to do if you would like to use other App Registration types
Without this information, developers will receive a cryptic error message, which is the scenario that prompted the creation of #19795.
I tried to make this really short: often a little goes a long way. Long help pages often force me to read too fast and miss details. More text can be added on request.

19795 microsoft account oauth options

---

aspnetcore/blazor/debug.md

Fixes #19970
Thanks @gfs ... I immortalize "OAT" (whatever that is :smile:) in the examples.
Safia, should we also address this for VS Code `url` and `webRoot` in `.vscode/launch.json`?
Also, we don't (*yet*) version anything here. I think if we don't version sections of the topic (if needed) that we should go ahead and version this whole topic for 5.0. Thoughts?

Debug WASM w/o changing base href

---

aspnetcore/blazor/host-and-deploy/webassembly.md

The engineering issue is closed, so it can't accept further feedback.

Remove engineering repo cross-link from Blazor doc

---

aspnetcore/security/authentication/certauth.md

Use GetRequiredService instead of GetService to better report DI errors like a missing service.

GetRequriedService

---

aspnetcore/tutorials/grpc/grpc-start.md

Fixed guide to remove compilation issue caused by incorrect namespace in greet.proto.

Added missing step causing compilation issue

---

aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/file-uploads/samples/5.x/Components/FilePreview.razor
aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor
aspnetcore/blazor/forms-validation.md

Fixes #20035
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&branch=pr-en-us-20046)
* Initial content of the [current live topic](https://docs.microsoft.com/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0) is based on DR's blog post ... it turned out to be a good start.
* Recommend that we keep the bare bones example in the topic and include your example **_and the framework's example_** as cross-linked sample code (this is all on this PR). This gives the reader immediate access to examples of various approaches/features without loading the topic down with code.
* Check the code carefully tho. I set this up quickly without local testing 🏃 so that I could get on to other issues that need to be addressed. I may have 💥😢 …

Blazor file uploads topic updates

---

aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/security/authorization/policies.md

Fixes #19573
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1&branch=pr-en-us-19774#authorize-server-api-access-for-user-defined-groups-and-administrator-roles)
Thanks @swannet! 🌴
The framework returns JWT bearer events using three code approaches:
* `Task.FromResult(0)`
* `Task.FromResult<object>(null);`
* `Task.CompletedTask`
Framework tests uses the first (and that's what's on the PR). However, the default assignment uses the last. Which is correct ... or merely preferred ... here? :ear:
cc: @blowdart ... Just as an **_FYI only_** that there's security guidance on this one.

Blazor *Server app* API authz for groups+roles

---

aspnetcore/fundamentals/middleware/index/snapshot/Chain/StartupUseWhen.cs

According to https://github.com/dotnet/extensions/issues/1096, in .NET Core 3+ you can no longer resolve ILogger when activating Startup and need to pass ILogger as parameter in Configure method.
This change is similar to this change to the docs - https://github.com/MicrosoftDocs/azure-docs/pull/33059

Update StartupUseWhen.cs (docs) for ILogger to work with .NET Core 3+

---

aspnetcore/blazor/security/server/additional-scenarios.md
aspnetcore/blazor/security/server/index.md

Addresses #19503
Internal Review Topics ...
* [Blazor Server security *Overview*](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/server/index?view=aspnetcore-3.1&branch=pr-en-us-20119)
* [Blazor Server security *Additional Resources*](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-20119)
Notes ...
* Whole topic versioning ... **_BUT_** ... let's try my fancy new hardcoded `<h2>` headings with `id`s to avoid the duplicate heading build warnings and preserve our bookmark anchors in the topic doing so in an HTML5-friendly way. It's probably the best of both worlds until we get *version-by-file*, when I'll revert these back to markdown H2s.
* Let's perform full topic UE passes while we're …

Blazor Server auth topic updates for 5.0

---

aspnetcore/fundamentals/logging/index.md

The docs state that "The order of placeholders, not their names, determines which parameters are used to provide their values" - and then provides an example that does the exact opposite. I have changed the example, hoping that the docs are correct. :)

Improve log template explanation

---

aspnetcore/tutorials/first-mvc-app/start-mvc.md

Added important instructional text "From the dropdown boxes, select .NET Core and ASP.NET Core 3.1". I missed this step in the tutorial because it was not instructed in the text. Later on I had to go back and recreate my project because I missed it.

Added missing step in text

---

aspnetcore/blazor/blazor-server-ef-core.md
aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Startup.cs
aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Startup.cs

Fixes #20101
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1&branch=pr-en-us-20169)
Thanks @CGuthrie72! :rocket:
* Given the [security concerns that you mentioned on the issue](https://github.com/dotnet/AspNetCore.Docs/issues/20101#issuecomment-705865479) with `EnableSensitiveDataLogging`, I recommend that we don't show it in the normal course of examples. We know that readers like to cut-'n-paste our examples right into their apps without a care in the world. 😨 I create a section dedicated to it and show the use of a compiler directive for a higher level of safe use over just using it by environment (cc: @blowdart courtesy ping given that this is Blazor Server).
* You said "call it out for identity server" ... …

Blazor Server-EF Core factory with Identity

---

aspnetcore/blazor/call-javascript-from-dotnet.md

I wanted to talk about tweaking JSInterop limits as well as having a minimal sample that does chunked uploads similar to Blazor's file upload. 
The sample https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1#perform-large-data-transfers-in-blazor-server-apps here should be removed now that we have InputFile but I'm open to copying some of the additonal notes surrounding it here.

Add some notes about JSInterop limits

---

aspnetcore/grpc/performance.md

Change link to point to new http2 specs repo. Old one is 404.

Update dead link to new HTTP2 specs repo

---

aspnetcore/grpc/troubleshoot.md

Fix is slightly different in .NET 5

Update unsecured gRPC call troubleshooting

---

aspnetcore/toc.yml

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19345
Associated with https://github.com/MicrosoftDocs/learn-pr/pull/12052
Add a link to the ASP.NET Core microservices instrumentation module on Learn.

Add ToC link for microservices logging and monitoring Learn module

---

aspnetcore/blazor/call-javascript-from-dotnet.md

Fixes #20195
Thanks @mrlife! ⛵
I think we can clarify that it's the *instance* being referred to by the remark and combine paragraphs. Those are the only changes that I can see making here at this time. The element ref shouldn't mutate **_within the same component_** and cause any problems. This section of text refers to trying something like passing an element ref as a parameter. The statement is clearer when reaching the next passage. Combining the paragraphs might help.

Clarify element reference remark

---

aspnetcore/signalr/configuration.md

I also added `transport` to the JS options table for consistency considering we also do that for the `accessTokenFactory` despite already demonstrating how to use it in an above section. I almost did the same for `logger` but decided against it considering `configureLogging()` is the right way to configure the `logger`.
@BrennanConroy

Demonstrate SignalR JS header option

---

aspnetcore/signalr/javascript-client.md
aspnetcore/signalr/troubleshoot.md
aspnetcore/toc.yml

https://github.com/dotnet/AspNetCore.Docs/issues/20063
Needs some cleanup.
This is definitely missing some common scenarios. Don't need to get them all in this first pass.
@Rick-Anderson  edit
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/troubleshoot?view=aspnetcore-3.1&branch=pr-en-us-20125)

Add troubleshooting page for SignalR

---

aspnetcore/blazor/call-javascript-from-dotnet.md
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/component1.razor
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/component2.razor
aspnetcore/blazor/components/event-handling.md

Blazor FocusAsync coverage

---

aspnetcore/blazor/components/css-isolation.md
aspnetcore/toc.yml

Here's the new article on Blazor CSS isolation. I'm looking forward to your feedback. 
I struggled a little with the CSS preprocessor section and how much in detail we should go into it. After all, CSS isolation works out of the box well, so don't want to overwhelm, but there's also a lot of folks that are interested in this. 
cc @guardrex @javiercn 
Fixes #19360

New article for Blazor CSS isolation

---

aspnetcore/toc.yml

The `Test` link in the `Blazor` section for the .NET 5 preview docs was misleading to me. At first, I wasn't sure if it was put there accidentally or what—looks like it links to the wonderful section on testing Blazor components. I think changing it to something like `Test components` is more clear.

Clarified "Test" link in TOC

---

aspnetcore/blazor/components/data-binding.md

Fixes #20263
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1&branch=pr-en-us-20267)
Thanks @mdekok! :rocket:
Let's work this further ...
* Do we want `Task`-`return` or `async Task`-`await` binding examples?
* I don't like the first sentence on Line 130. Can we do something to make it plainer/simpler?
> A common scenario is chaining a data-bound parameter to a page element in the component's output. This scenario is called a *chained bind* because multiple levels of binding occur simultaneously.
How about? ...
> A common scenario is chaining a data-bound parameter of a component to a property of field of another component. This scenario is called a *chained bind* because multiple levels of binding occur …

Update Blazor binding content

---

aspnetcore/fundamentals/routing.md
aspnetcore/includes/catchall.md

Fixes #19817
[internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0&branch=pr-en-us-20260#route-template-reference)

Remove warning about catch-all bug in 5.0 version

---

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/signalr/authn-and-authz.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes  #17751
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&branch=pr-en-us-20269#websockets-and-server-sent-events)
Brennan ... I'm winging this one even more than usual from the context on the issue. I need help with it ...
* Is this the best spot?
* Are these remarks sufficient/correct?
* Is Caleb's code good to provide?

IdS with WebSockets and Server-Sent Events

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md

The "Supported account types" field has changed the text of the option to the value above. This change updates the text to match the value in the Azure Portal "Register an application" screen.

Correct Label of Supported Account Type Option

---

aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config

Fixes #20205
Thanks @cornem! 🎷 and @glararan! :rocket:
* AFAICT, no need to version the updates. This should work with 3.x and 5.x.
* Decided in the DRAFT here **_NOT_** to serve double-compressed assets (in spite of the framework producing them), which I think would have unpredictable (and often not good) results. If a dev wants to change the file for things like PNG, WOFF, etc., they can do so on their own. The pattern here is easy to follow.
* For static and dynamic compression, I go off of what's in a typical (default) `applicationHost.config`. These removals look like the only ones that we need here.
* No need to remove and then add back existing MIME maps in the typical (default) scenario, so I take those out.
* Per Ben's original file, I retain the MIME change for DLLs. He goes …

Update Blazor WASM web.config

---

aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md

Fixes #20310 
Thanks @yuopolev! :rocket: ... Yes, the warning INCLUDES file for access token scopes is focused on the Azure-based scenarios. The INCLUDES file is here because there was a time that thought devs could use the *Auth Lib* topic guidance with AAD. However since then, the product unit has warned devs off of using this topic at all for AAD. Although it will work, it requires additional configuration. They want everyone to use the AAD-based topics (MSAL-based approaches, as you mentioned) in this node. Additionally, it's best to pull the INCLUDES for the reason that you just mentioned. Even if we kept it, it would require me to make a third file (there will be a 3.x and 5.x version of this INCLUDES file soon), and the third file would have the correct C# code examples. Indeed ... …

Remove token scope warning

---

aspnetcore/security/authentication/identity-api-authorization.md

It was confusing to be able to publish to other web hosting providers without using azure due to lack in documentations and enums(the StoreName enum does not contain webHosting option https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.storename?view=netcore-3.1)

publishing to other web hosting providers

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/fundamentals/additional-scenarios.md
aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/toc.yml

Drop Blazor section until 5.x

---

aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/host-and-deploy/azure-apps/index/sample/arm.json

Fixes #19388
[Internal Review Topic (links to section; scroll to the bottom of the section to see it)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-2.1&branch=pr-en-us-20298#install-the-preview-site-extension)
This is based on reverse engineering: I added the site extension to an Azure App in the portal and then exported the ARM template to see how it composed the resource (extension).
* I substituted `[resourceGroup().location]` for the string name of the datacenter, which is what my file contained ("Central US").
* I don't see a `properties` > `version` in what Azure produced; but since this is based on a live template from the portal, I assume what's on the PR is correct.

Azure Apps ARM template preview site extensions

---

aspnetcore/security/authentication/scaffold-identity.md

Fixes #20295
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&branch=pr-en-us-20361#standalone-or-hosted-blazor-webassembly-apps)
Thanks @dajma00! 🎷
IMO, this covers what we need. The 5.0 updates that have been made for Blazor WASM in the framework to correct problems with scaffolding Identity into the *Server* project of a hosted Blazor solution don't require calling out ... they're 🐞 fixes AFAICT. Since we have no coverage on this scenario (until now with this PR), there aren't existing workarounds that we need to version-out for 5.0.
The main things here to surface are ...
* One can't scaffold into a Blazor WASM project.
* Mention that **_Identity UI pages_** have no …

Scaffolding guidance on Blazor WASM

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md

Fixes #20381
Thanks @scdehmlow! :rocket: ... I'll keep an :eye: on that engineering issue. If they update the template for the 5.1 release (next year), I'll open an issue to react to the change later. If they don't change the template and keep the current behavior, then these two topics can keep this language and then I'll update the new guidance and strike the product unit issue cross-links from this.

Blazor WASM template behavior for App ID URI

---

aspnetcore/blazor/call-dotnet-from-javascript.md
aspnetcore/blazor/call-javascript-from-dotnet.md
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/call-js-example.razor
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/component1.razor
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/component2.razor
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/component3.razor
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/inject-abstraction-class.cs
aspnetcore/blazor/call-javascript-from-dotnet/samples_snapshot/inject-abstraction.razor
aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/fundamentals/configuration.md
aspnetcore/blazor/fundamentals/dependency-injection.md
aspnetcore/blazor/security/server/additional-scenarios.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md
aspnetcore/blazor/security/webassembly/graph-api.md

Fixes #20335
Thanks @ericsson007! :rocket: ... This fixes the example that you highlighted and addresses some inconsistency in variable naming elsewhere. The inconsistencies are expected to a certain extent because ...
* There are several product unit developers (and myself) submitting doc code examples with different favorite-naming schemes.
* The updates and new examples come in over a long span of time ... over years.
Even the same dev might submit code examples in one year using one naming approach and then change it up in a later year and use a different naming approach.
I'll keep working on this problem as I go with topic updates. I'll also keep working on calling out namespaces in examples ... another on-going pain point. Thanks again for calling this out in that example. It led to …

Blazor example consistency

---

aspnetcore/fundamentals/routing.md

Hi ASP .NET Core docs crew.
I think I found a little typo in this document; I'm assuming that what the original author wanted to say was "_This_ works..." but other options like "_It_ works..." could be also valid in this context.
Please let me know if this really is a typo.
Thanks in advance, have a great rest of the day.

Fix typo "The works because..."

---

aspnetcore/mvc/controllers/routing.md

Commit https://github.com/dotnet/AspNetCore.Docs/commit/fa4c1e7b6e2a0c2a0dd426405d56551d49395ffe changed this at the beginning of this document, but not this instance.

Correctly refer to MyDisplayRouteInfo location

---

aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/host-and-deploy/linux-nginx/nginx.conf

Fixes #20359
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&branch=pr-en-us-20360)
Cross-reference to discussion on initial PR by @tunggnu 🎷: https://github.com/dotnet/AspNetCore.Docs/pull/19972
There's one recommendation that that I'm not going to address on this PR ...
> Does not adhere to the **separation of concerns** principle. You created the `/etc/nginx/sites-available/default` file to contain HTTP configuration, but included HTTPS configuration settings in the `/etc/nginx/nginx.conf` file, which should only contain the general settings. In my opinion, the ideal solution is to move all the specific settings out of the `/etc/nginx/nginx.conf` file. They can be placed inside a new file or merged into the …

Improve HTTPS guidance

---

aspnetcore/blazor/components/index.md

Fixes  #20244
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-20452#overwritten-parameters)
Thanks @taori! 🌴 and @simonziegler! 🎷
Safia, I think we'll be able to close out that issue with what's on this PR.
I have some concerns about the specificity of Steve's remarks for the specific scenario on the engineering issue and some of the phrases ... perhaps pronouns ... that might make it a hair unclear.
However, we don't need to use Steve's text in the docs even in a modified form if the improvements here are enough to clarify the main problem and guide in the right direction. I still think we're wise **_to keep the SxS examples_** of **what not to do** and then **what to do**. I …

Improvements for Blazor overwritten params

---

aspnetcore/includes/http-repl/standard-options.md
aspnetcore/toc.yml
aspnetcore/web-api/http-repl-telemetry.md
aspnetcore/web-api/http-repl.md

Updates the HttpRepl documentation for the changes we've made in 5.0.
Additionally, adds a new HTTP REPL node in the table of contents with two children - the original docs and the new telemetry doc.
The telemetry page is taken directly from https://github.com/dotnet/HttpRepl/blob/master/TELEMETRY.md
@scottaddie I didn't add any of the metadata to the top of the telemetry page since I wasn't sure if that was autogenerated or not.

Update HttpRepl docs for 5.0 changes

---

aspnetcore/toc.yml
aspnetcore/web-api/http-repl/index.md
aspnetcore/web-api/http-repl/telemetry.md

Changing per a conversation with Brady & Tim.
Also document the `DOTNET_HTTPREPL_SKIP_FIRST_TIME_EXPERIENCE` environment variable.

Rebrand HTTP REPL to HttpRepl

---

aspnetcore/migration/31-to-50.md

This PR adds a note to inform that EF core packages should also be updated to 5.0.0.

Adding note to also upgrade Microsoft.EntityFrameworkCore packages

---

aspnetcore/tutorials/first-web-api.md

The highlighted line for DTO code should be on the new Secret field
right now it is on Name

Highlight is in the wrong place

---

aspnetcore/blazor/components/css-isolation.md

Small (probably incredibly pedantic!) change - the docs always refer to '.razor' files, so it would make sense for the 'razor.css' files to be written as '.razor.css' so idiots like me don't save a file as 'Indexrazor.css'. It would be consistent with [other .Net docs](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start#pages-folder).

Change 'razor.css' to '.razor.css'

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/components/css-isolation.md
aspnetcore/razor-pages/ui-class.md

Fixes #20480
Thanks @PoisnFang! :rocket:
Would u take a look @daveabrock? ...
* I'm a bit concerned about the 2nd `{ASSEMBLY NAME}` placeholder that I used (i.e., in the file name). See if I composed this correctly; otherwise if ur not available right now to look at this, I'll run a local test and confirm/update the behavior.
* Do I have the rest of it right (`.bundle.scp.css`) based on Javier's remark on the issue?

CSS isolation support in RCLs

---

aspnetcore/tutorials/first-web-api.md

Fixes #20540
When following along with the .NET Core 2.1 tutorial, the part that says to `Set the URI to https://localhost:<port>/api/TodoItem...` fails. However, if you look in the screenshot for that part, the URI does not say "TodoItem" but is instead "Todo". When you use the URI `https://localhost:<port>/api/Todo`, the test passes.

Error in Section "Test the PostTodoItem method 2.1"

---

aspnetcore/tutorials/build-a-blazor-app.md

Reverting the test on #20544 ...
```
[!code-csharp[TodoItem.cs](build-a-blazor-app/samples_snapshot/TodoItem.cs)]
```
It didn't work to render the file's name ...

Revert test if alt text renders file name cue

---

aspnetcore/release-notes/aspnetcore-5.0.md

Auto refresh is now available in VS with the 16.8 update. You just have to turn it on.

Update .NET 5 release notes to remove comment about VS support for auto refresh

---

aspnetcore/blazor/components/lifecycle.md

There are two typos in the lifecycle of Blazor. This PR fixes these typos.
"base.SetParametersAync" should be "base .SetParametersAsync"
"asychronously" should be "asynchronously"

Fix typos in the blazor-lifecycle doc

---

aspnetcore/data/ef-rp/intro.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&branch=pr-en-us-20615&tabs=visual-studio)
Fixes: #20612 
Minor correction, adding a line space before a code sample include so it will not be dropped in localization.

ef-rp intro: Fix code include line so it localizes

---

aspnetcore/grpc/authn-and-authz.md

Addresses https://github.com/grpc/grpc-dotnet/issues/1116
Make it clearer that CallCredentials require TLS.

Improve gRPC client authorization docs

---

aspnetcore/toc.yml

As part of the update for ASP.NET Core 5.0, the module link is changing slightly.
/cc: @CamSoper

Update link for ASP.NET Core web API module on Learn

---

aspnetcore/migration/31-to-50.md

The text says `id`, while the code consistently uses a `class`. I haven't tested, but I'm guessing the code is correct?

Corrected error in text

---

aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor

Fixes #20618
@DataJuggler ... Turns out that that's a namespace typically placed in the `_Imports.razor` file (it's provided by default from the project template these days). Therefore, I revert the sample app patch here, avoid adding it to the in-text example, and add a NOTE to the text that calls it out. This should clear it up. I'll work on namespaces further as I make update passes on each topic heading into the holidays. Thanks again for writing in on this.

Blazor File Uploads namespace update

---

aspnetcore/includes/run-the-app.md
aspnetcore/includes/trust-ff.md
aspnetcore/includes/trustCertVS.md
aspnetcore/includes/trustCertVSC.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/tutorials/razor-pages/razor-pages-start.md

Fixes #20567
* [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-1.0&branch=pr-en-us-20570&tabs=visual-studio#firefox-sec_error_inadequate_key_usage-certificate-error) 
* [example usage](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&branch=pr-en-us-20570&tabs=visual-studio#run-the-app)

FireFox cert instructions

---

aspnetcore/tutorials/web-api-javascript.md

The HTML file in the example references a site.css file, but the rest of the instructions did not include the CSS, which makes the finished code look weird since the edit form is not hidden at the beginning

CSS instructions were not included

---

aspnetcore/migration/31-to-50.md

Fixes #20654
Let's generalize the package versions for the Identity v2.0 packages because they're on a different release cadence and hardcoded versions will haunt us forever here 👻😨 if we don't. They **_just released_** new ones a few days ago, and there's no telling when they'll release again and thus break the doc again.

Generalize Blazor migration Identity package versions

---

aspnetcore/blazor/components/lifecycle.md

Be more explicit about the rendering that happens as soon as the first call is awaited. With the current description it sounds like it will only render after awaiting the `OnInitializedAsync` method.

Be more explicit about component lifecycle

---

aspnetcore/tutorials/signalr.md

Not adding "cd SignalRChat" causes the next command to copy files in wrong folder. The next command is this one: `libman install @microsoft/signalr -p unpkg -d wwwroot/lib/signalr --files dist/browser/signalr.js --files dist/browser/signalr.min.js`

Adds change directory to SignalRChat

---

aspnetcore/blazor/forms-validation.md

Fixes #20724
Thanks @VR-Architect! :rocket: ... this is the way that I've been composing examples lately.
Generally, there's no namespace for examples where objects are easily cut-'n-pasted into developer apps. The dev can add a namespace if they want to.
For examples that pertain to a specific hosting model scenario (e.g., the server API example in this topic where it's based on a hosted WASM app), I often leave the namespace but use a placeholder and then call out the placeholder in the text so that machine translation into other languages will describe it for everyone.
I'll continue my effort to make the docs consistent on these points as I perform the UE passes, and I hope to get them done ... *or mostly done* 🏃🏃🏃🏃 ... by the time I leave for ⛄ *holiday vacation* 🎁 this year 🤞.

Update code examples

---

aspnetcore/data/ef-mvc/migrations.md

The instruction to drop the database came before the instruction to install, which leads to confusing error messages

dotnet ef install instruction moved to beginning

---

aspnetcore/web-api/advanced/custom-formatters/samples/3.x/CustomFormattersSample/Controllers/ContactsController.cs

Addresses #20732.
Adding `ModelState` to the call to `BadRequest` ensures errors added by `VcardInputFormatter` are surfaced in the 400 response.

Include ModelState in BadRequest for vcard Input Formatter sample

---

aspnetcore/tutorials/build-a-blazor-app.md

Fixes #20728
... and fixes a few other nit things. I'll make a proper UE pass on this topic shortly to mop up remaining nits.
Thanks @papalanga! :rocket: ... *Great idea!* ... I just wish we had a `dotnet new class` CLI command to create the `TodoItem.cs` file. They **_are_** considering adding such a template, but they haven't built it into the SDK yet. https://github.com/dotnet/templating/issues/1713 ... For anyone seeing this and in agreement, please consider adding a :+1: to the opening comment of that issue. If it receives more :+1:s, it might get off of the backlog faster.

Use 'dotnet watch run' in Blazor tutorial

---

aspnetcore/blazor/call-javascript-from-dotnet.md

Fixes #20598
Thanks @sps014! :rocket:
There are big holes in my understanding here (*not surprising* 😄), so I need help.
* The [current example in the live topic](https://docs.microsoft.com/aspnet/core/blazor/call-javascript-from-dotnet#blazor-javascript-isolation-and-object-references) is broken and throws `There is no argument given that corresponds to the required formal parameter 'arg0'`.
* The new example on the PR is based on framework test code from [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/InteropComponent.razor#L198-L204) and [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/wwwroot/js/jsinteroptests.js#L222-L242) with …

Update and improve Blazor unmarshalled JS

---

aspnetcore/blazor/components/index.md
aspnetcore/mvc/views/razor.md

Fixes #20758
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-20761#whitespace-rendering-behavior)
Scott ... Is that your text? If so, can I place your name on this topic (it's on the PR) and 👮 **_steal ur stuff_** 🚓?
I'd like to cover this quickly and move on to get as much done prior to my 🏖️ *vacation* 😁 as possible. It's quick to base the coverage on your text and perhaps make additional updates on a UE pass for this topic later ...... you know ...... *the UE pass that I was going to make a year ago*. 🙈🏃😅 
I simplified a hair ... It's certainly OK to use the word "node" to refer to a group of whitespace characters in technical content (i.e., a DOM text **_node_**); but in its …

Razor component insignificant whitespace

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/environments.md
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/web-host.md
aspnetcore/fundamentals/index.md
aspnetcore/fundamentals/logging/index.md
aspnetcore/security/app-secrets.md
aspnetcore/security/app-secrets/samples/3.x/UserSecrets/Pages/Index.cshtml
aspnetcore/security/app-secrets/samples/3.x/UserSecrets/Pages/Index.cshtml.cs
aspnetcore/security/app-secrets/samples/3.x/UserSecrets/Program2.cs
aspnetcore/security/app-secrets/samples/3.x/UserSecrets/Startup2.cs
aspnetcore/security/app-secrets/samples/3.x/UserSecrets/Startup3.cs
aspnetcore/security/authentication/social/index.md
aspnetcore/security/key-vault-configuration.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20756
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/20168
**Summary of changes**
- Incorporate customer requests as part of the [Q2 content performance OKR](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1796311)
- Incorporate Acrolinx suggestions
- Rewrite the **Access a secret** section to include distinct steps and a Razor Pages example
- Replace incorrect usage of the term "Secret Manager" with "user secrets". Secret Manager is the tool. User secrets is the term to describe the configuration source read by the tool and the Configuration API. See https://github.com/dotnet/runtime/blob/fa367a397eaa518ec4c47c51f12d5994752d7321/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfig …

Show how to access user secrets in a Razor Page

---

aspnetcore/toc.yml

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19344
Link to the new feature flags module added in https://github.com/MicrosoftDocs/learn-pr/pull/12482.

Add ToC link to feature flags Learn module

---

aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/Program.cs

Updated: "SecretClient" should be "secretClient"
var secretClient = new SecretClient(new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
new DefaultAzureCredential());
config.AddAzureKeyVault(**SecretClient**, new KeyVaultSecretManager());

Fix Typo in key-vault-configuration/samples/3.x/SampleApp/Program.cs

---

.github/ISSUE_TEMPLATE/doc-issue.md

Can we 💪 **_strengthen_** 💪 the guidance on using the **This page** feedback button and form?
Even if we don't tho, let's at least take a look at the following ...
Although "**Content feedback** button" is for the "Feedback" section and does pertain to the "content," it really isn't the "**Content feedback** button." Using "**This page** button" is clear imo.
Just for list consistency, I put asterisks in for dashes below.

Strengthen the instruction and update button name

---

aspnetcore/blazor/call-javascript-from-dotnet.md

Fixes #17651
The [product unit issue](https://github.com/dotnet/aspnetcore/issues/20525) to work further on circular references is on the backlog. Given that it isn't clear if/when that work will take place, I think we should just remove the cross-link to the `dotnet/runtime` issue (closed as resolved) and keep the cross-link to `dotnet/aspnetcore` issue for now. We can open a new docs issue if the product unit issue is resolved or closed. I don't want to leave a lot of unactionable Blazor docs issue lying around.

Update Blazor circular references content

---

aspnetcore/blazor/components/index.md

That part should use `CustomLoginDialog` instead of `MyLoginDialog`, But since the rest of the section is using `MyLoginDialog` it's kind of confusing. It would be better to change the `CustomLoginDialog` Type in lines 442 & 445 to `MyLoginDialog` for the sake of integrity.

Change MyLoginDialog to CustomLoginDialog

---

aspnetcore/azure/devops/cicd.md
aspnetcore/azure/devops/deploying-to-app-service.md
aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #20895
Seeking to resolve these 'master branch' build suggestions. The build new seems 😁 with the approaches on this PR.
btw - The whole `git push origin master` command is throwing, so I seek to resolve it with a placeholder that calls out using `master` for `{BRANCH}`. It's a bit funky, but it's a decent workaround unless u have another idea.
..... but it isn't too *funky* because the `master` branch might not be the default branch, so a placeholder is perhaps ok there anyway.

Resolve 'master branch' build suggestions

---

aspnetcore/performance/caching/memory.md
aspnetcore/performance/caching/memory/3.0sample/WebCacheSample/Controllers/HomeController.cs

This adds an example without creating the `MemoryCacheEntryOptions` object.
Fixes #20849

Add example with set extension methods to memory cache usage

---

aspnetcore/mvc/controllers/filters.md

Fixes #20925
the missing code sample for ShortCircuitingResourceFilter

Fix the code sample for ShortCircuitingResourceFilter

---

aspnetcore/blazor/components/virtualization.md

Fixes #21026
We usually use warnings for security concerns, writing unstable code or code that produces strange/unexpected results, unsupported approaches that might break, and practices that might fall victim to a future breaking change.
This one seems less severe given that there's a clear exception when the params are set, but I place the guidance into its own paragraph to highlight it a bit more than just tacking it on at the end of the current paragraph.

Clarify Virtualize component item source

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md

Fixes #21034
Thanks @rameshkanjinghat! :rocket: ... I ultimately decided to keep the links but move them to the *Additional resources* section. They won't appear in the step-by-step guidance here now, and I think that will remove confusion. I checked on the *Create a tenant* Azure doc, and that seems fine/good to keep where it is. It's best if we not try to walk readers through all of that when the cross-link should take care of it without confusion. I do add a line here that says, '**_come right back_** when done.' I don't want readers lingering over there and getting into trouble with little 😈 in the remaining guidance between the two doc sets.
If you put up your solution in a GH repo (again, removing sensitive configuration), I'll take a look at it. Ping me back either here or on the …

Blazor WASM security-to-Azure cross-links

---

aspnetcore/blazor/tooling.md

On page `Tooling for ASP.NET Core Blazor` shows incorrect options

Fix template help options

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md

Addresses #21034
Turns out that moniker ranges break indentation in sub-bullet content when the bullet item isn't included in the versioned content ...
Therefore, the versioned content must include the bulleted item ... i.e. .... the bullet item must be repeated for each version.

Blazor WASM security versioned content

---

aspnetcore/blazor/fundamentals/dependency-injection.md
aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/DetectIncorrectUsagesOfTransientDisposables-server.cs
aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/DetectIncorrectUsagesOfTransientDisposables-wasm.cs

Fixes #20950
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-21002#detect-transient-disposables)
I recalled on a second look (after the UE pass on this topic last week) that the transient disposables code doesn't "**_detect_**" them until/unless they are resolved (constructed)&dagger;. I think when I was reading the topic and working on it that I incorrectly interpreted "detect" to mean on service registration. I add a bit to the bottom of the section here with an example to call it out.
&dagger;Resolve and construct: I say "resolve" first and then "construct" later. AFAIK, these mean the same thing in this context, and we can use both here. If it should use …

Enhance Blazor transient disposable content

---

aspnetcore/mvc/controllers/routing.md

Fixes #20988.
I'm not sure if you want this to auto-close the linked issue, so feel free to edit the above if you do.

Fix up token replacement characters for attribute routing

---

aspnetcore/signalr/version-differences.md

Fixes #21068
Thanks @chrisseed! :rocket:
Brennan ... I don't version this because we've always treated browser support as **_current only_** (unversioned in the *Supported Platforms* doc).

Update IE support for Core SignalR

---

aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/App.razor
aspnetcore/blazor/common/samples/5.x/BlazorServerSample/App.razor
aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/App.razor
aspnetcore/blazor/fundamentals/routing/samples_snapshot/3.x/App1.razor
aspnetcore/blazor/fundamentals/routing/samples_snapshot/3.x/App2.razor
aspnetcore/blazor/fundamentals/routing/samples_snapshot/5.x/App1.razor
aspnetcore/blazor/fundamentals/routing/samples_snapshot/5.x/App2.razor
aspnetcore/blazor/includes/prefer-exact-matches.md
aspnetcore/blazor/layouts/sample_snapshot/3.x/App1.razor
aspnetcore/blazor/layouts/sample_snapshot/3.x/App2.razor
aspnetcore/blazor/security/index.md
aspnetcore/blazor/state-management.md
aspnetcore/migration/31-to-50.md
aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Client/App.razor

Fixes  #21060
Thanks @RugerSR9 :rocket: and @carthell! 🎷
cc: @mkArtakMSFT ... I'll go ahead and shoot this into the docs now. If we need to provide different/additional info, I'm :ear: for your guidance and will modify/add content as soon as I hear back from you.
btw -- Just a reminder on how `PreferExactMatches` was added: I think where we have a `Router` components in the text, the INCLUDES file is positioned nearby to surface it. An INCLUDES file is used to avoid having many temporarily versioned code blocks all over the place. It will be easy later to drop the INCLUDES from the docs at 6.0.

Update Blazor PreferExactMatches

---

aspnetcore/mvc/controllers/areas.md

I believe this sentence:
> The fully qualified domain name must be used to specify the model...
Should refer to the "class name" rather than "domain name" and thus read:
> The fully qualified class name must be used to specify the model...

Fix typo in areas.md

---

aspnetcore/web-api/Microsoft.dotnet-openapi.md

`Add URL` example was using `Add File` and is now correct

Fix Add URL example

---

aspnetcore/migration/31-to-50.md

This is just a *nit* update to clarify that the setting would be `@false` to get a `false` value in C#. Setting to merely `false` will :boom: just like setting to `true`.

PreferExactMatches content update

---

aspnetcore/blazor/components/virtualization.md
aspnetcore/blazor/webassembly-performance-best-practices.md

Fixes #20965
* Combine sections into the Virtualization topic.
* Surface `@key` for these scenarios.
* Replace the example from the perf topic, which is more real-world than the existing example and includes the `@key` scenario.
* Fix a few minor spacing nits in lists in the perf topic.
Going to merge this one now, and we'll get PU feedback later on the UE pass on this topic for https://github.com/dotnet/AspNetCore.Docs/issues/19286.

Combine Virtualization sections and surface @key

---

aspnetcore/migration/22-to-30.md

Calling UseKestrel and UseIISIntegration is unnecessary with ConfigureWebHostDefaults

Demonstrate ConfigureWebHost in 22-to-30.md

---

aspnetcore/tutorials/razor-pages/sql.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-5.0&branch=pr-en-us-21142&tabs=visual-studio)
Fixes #21083
In sql.md, corrected which sample version of appsettings_SQLite.json is pointing to for versions 5.x-2.x of this topic.
The appsettings_SQLite.json example for versions 5.x - 2.x of this topic points to the non-versioned original app sample which originally used "MoviesContext". Instead those versions need to point to their own sample version:  razor-pages-start/sample/RazorPagesMovie50/appsettings_SQLite.json, razor-pages-start/sample/RazorPagesMovie30/appsettings_SQLite.json, etc.
Both the startup and the appsettings for the SQLite example should be using "RazorPagesMovieContext"

Point to versioned samples for appsettings_SQLite.json connection string

---

aspnetcore/signalr/client-features.md
aspnetcore/signalr/java-client.md
aspnetcore/signalr/java-client/sample/pom.xml
aspnetcore/signalr/messagepackhubprotocol.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-5.0&branch=pr-en-us-21090#java-client)
Resolves https://github.com/dotnet/aspnetcore/issues/26248

 Add docs for MessagePack

---

aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes #21114
Thanks @firewater! :rocket: ... I'm merely going to add the cross-link to *Additional resources* section because we don't want to get too deep into the weeds on debugging in a tutorial. We keep these tutorial articles **_lean_** ... minimal cross-links ... minimal distractions. The topic calls out the default config, which should be working for the default browser (Chrome). If you find a bug 🐞 in the template-based app with Chrome or a scenario with Edge that is breaking unexpectedly (outside of the additional guidance that we're cross-linking with this PR), open that directly with engineering at https://github.com/dotnet/aspnetcore/issues (and note to them that you're remarking on the project template code and default debugging configuration ... that's what the topic is …

Add Blazor debug topic cross-link

---

aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes #21112
Thanks again @firewater! 🎸
We'll kill this bit because it's been changing as the product unit makes improvements. It's not relevant to a successful tutorial experience, and the tutorial now cross-links to the Blazor WASM debugging topic.

Remove debugging info for VS Code

---

aspnetcore/fundamentals/static-files/samples/3.x/StaticFileAuth/Startup.cs

The following line:
>   // wwwroot css, JavaScrip, and images don't require authentication.
...is missing a "t" in the word "Javascrip" and should read:
>   // wwwroot css, JavaScript, and images don't require authentication.

Fix typo in source code comments for Startup.cs

---

aspnetcore/blazor/components/lifecycle.md

Fixes  #21139
Thanks @TheBigBirn! :rocket:
@captainsafia ... Instead of "stop," we can use virtually anything similar to that to kick this off. Does a different word capture the technical aspect better? Here are some synonyms that we can consider ...
* Stop further rendering operations on the component: (**_currently on the PR_**)
* Cease further rendering operations on the component:
* Discontinue further rendering operations on the component:
* Halt further rendering operations on the component:
* Terminate further rendering operations on the component:
* Avoid further rendering operations on the component:
... mmmmmm 🤔 ... Not sure if anything is better than just "stop," but I'll go with whatever you think best ... or something else if you have a word that isn't listed there.

Improve Blazor Lifecycle remark

---

aspnetcore/data/ef-mvc/update-related-data.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21152
Includes the closing tag in the selected lines displayed for the snippet.
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-5.0&branch=pr-en-us-21153#modify-the-course-views)

Display closing div tag in snippet

---

aspnetcore/mvc/views/view-components.md

Fixes #21106
Thanks @lukos! :rocket:
* Add cross-link to the integration coverage.
* DR wants a lowercase "components" for "Razor components" in docs. (I tried to talk him out of it ... *but failed*. :smile::cry::smile::cry:)

Add components integration cross-link

---

aspnetcore/data/ef-mvc/intro/samples/5cu-snap/Views/Instructors/Index.cshtml
aspnetcore/data/ef-mvc/intro/samples/cu/Views/Instructors/Index1.cshtml
aspnetcore/data/ef-mvc/read-related-data.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21128
**Summary of changes**
- Use the `table-success` class for ASP.NET Core 2.2 or later; use `success` for ASP.NET Core 2.1 or earlier. In ASP.NET Core 2.2, the project template was updated from Bootstrap 3.4.1 to 4.3.1. The `table-success` class doesn't exist in 3.4.1.
- Simplify a Razor code block loop in the Instructors index view
- Apply the correct devlang (HTML --> CSHTML)
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-1.0&branch=pr-en-us-21166#modify-the-instructor-index-view)

Update Bootstrap CSS class name in EF/MVC tutorial

---

aspnetcore/tutorials/first-mvc-app/search.md
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Startup.cs

When reading the docs for the ASP.NET Core 5.0 MvcMovie application, I noticed a code snippet on [Part 7 - Add search](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-5.0) containing code that is inconsistent with the rest of the tutorial. Specifically, it changes code in the Startup.cs file's `Configure()` method from `app.UseEndpoints()` to `app.UseMvc()`, which could be confusing to someone reading the code.
I'm not sure if this small change warrants a fix, but I thought I'd give it a go.
The snippets currently used in the documentation seem to come from an older version of the tutorial, but this is the only instance where the code blocks seem to differ compared to the 5.0 version. I changed the newer version to be the source of the snippet …

Changing MvcMovie documentation code snippet to show correct code

---

aspnetcore/blazor/progressive-web-app.md

Fixes  #20859
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&branch=pr-en-us-21190#convert-an-existing-blazor-webassembly-app-into-a-pwa)
I've successfully used the reference assets cross-linking approach you see here in the past. By linking over to the `wwwroot` folder assets, we'll avoid maintaining copies of these assets in the docs repo that tend to go stale in future releases. It does require the reader to select the right branch over there (and the added little NOTE here about the Blazor folder churn between 3.1 and 5.0), but I haven't seen readers having trouble following similar guidance in the past.
**_Did I miss anything?_** This looks complete, but PWAs are one of things that I …

Convert Blazor WASM into a PWA

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Fixes #18631
cc: @mkArtakMSFT ... I'm going to leave the nibblets of info on Docker that we have in the *Hosting models* topic and the *Introduction* topic, which are the only other places we address Docker in Blazor topics. We have this one line in each of the WASM and Server sections of the *Hosting models* topic ...
> The hosted Blazor app model supports \[Docker containers](/dotnet/standard/microservices-architecture/container-docker-introduction/index). For Docker support in Visual Studio, right-click on the \`Server\` project of a hosted Blazor WebAssembly solution and select \*\*Add\*\* > \*\*Docker Support\*\*.
That link goes to :point_right: https://docs.microsoft.com/dotnet/architecture/microservices/container-docker-introduction/
We also have this one line in the *Introduction* …

Drop Blazor-Docker section

---

aspnetcore/fundamentals/routing.md

The sentence:
> Once of set of candidates is found...
Should read:
> Once the set of candidates is found...

Fix typo in routing.md

---

aspnetcore/mvc/controllers/routing.md

The sentence:
> Routes templates:
Should read:
> Route templates:
The sentence:
> Conventionally routing...
Should read:
> Conventional routing...

Fix multiple typos in routing.md

---

aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md

Addresses #20175
cc: @billyjim ... This won't resolve your ask. However, the Blazor framework and existing examples (that I can find anyway) don't provide API or a recommended approach for a standalone WASM app with multiple IPs. Today, the developer can ...
* Write the code for a custom auth provider.
* Perhaps, find a third-party lib that will do it (but I didn't see one at Awesome Blazor).
* Go with a hosted solution and Identity Server, with IdS configured for the desired IPs.
* Go with Blazor Server and configure as an ASP.NET Core app for the desired IPs.
This PR tho can do a couple of quick things to improve the coverage ...
* In the *Auth Lib* topic, call out that the IP must be OIDC compliant and cross-link the *Overview* topic where that aspect is described.
* Show an example …

Improve WASM security coverage for external IPs

---

aspnetcore/mvc/controllers/routing.md

The section [`Specifying attribute route optional parameters, default values, and constraints`](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-5.0#specifying-attribute-route-optional-parameters-default-values-and-constraints) contains source code with `[HttpPost("product14/{id:int}")]` however the explanatory text that follows, says the code uses `[HttpPost("product/{id:int}")]` which is incorrect (`product` should read `product14`). I have changed the explanatory text, the example of a matching URL (`/product/3` should read `/product14/3`) and the name of controller class (`ProductsController.ShowProduct` should read `Products14Controller.ShowProduct`).
PS: routing.md is a MASSIVE document, it could really use decomposition into multiple smaller …

Fix mismatch between code and explanation in routing.md

---

aspnetcore/security/authentication/community.md

ASOS was merged into OpenIddict 3.0: https://kevinchalet.com/2020/12/23/openiddict-3-0-general-availability/
@Rick-Anderson could you PTAL? 😃

Remove ASOS from the community authentication providers and update OpenIddict's description

---

aspnetcore/blazor/progressive-web-app.md

Addresses #20859
We can show both like this.
I agree on `dotnet new`-ing up an app to get them. This looks good. Copying the files from a local folder is nice, too. I'm making this the first option.
I think we should keep the existing bit tho. A bit of developer training for GH is ok ... the proverbial *teachable moment* because **_they want those assets_** :smile: lol ... and if I keep these links up-to-date, they probably won't even have to fiddle with the branch selector.
btw - I'm going to temporarily change the folder/app name to `MyBlazorPwa` so that it will match what's shown in the images. Later on my UE pass for this topic, images really should come out of it. Keeping up with images are a real **_pain point_** around here 😬. Later, I'll use a different name because I'm getting …

Surface PWA conversion approach for static assets

---

aspnetcore/blazor/call-dotnet-from-javascript.md
aspnetcore/blazor/call-javascript-from-dotnet.md

Fixes #21208
Thanks @MarkStega! :rocket: ... We'll see when Javier looks :eyes: if I screwed it up 😜.
Internal Review Topics (link to sections):
* [Call .NET from JS](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1&branch=pr-en-us-21221#size-limits-on-js-interop-calls)
* [Call JS from .NET](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1&branch=pr-en-us-21221#size-limits-on-js-interop-calls)
Javier, I derived the coverage updates after testing with https://github.com/dotnet/AspNetCore.Docs/issues/21208#issuecomment-760217822. I'm careful with the text to highlight:
* Where the limit is imposed without the use of overloaded and confusing terms. 🤞
* How the error :boom: …

Size limits on JS interop calls

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/Pages/CallWebAPI.razor
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/web-host.md
aspnetcore/fundamentals/servers/index.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/servers/kestrel/endpoints.md
aspnetcore/fundamentals/servers/kestrel/host-filtering.md
aspnetcore/fundamentals/servers/kestrel/http2.md
aspnetcore/fundamentals/servers/kestrel/options.md
aspnetcore/fundamentals/servers/kestrel/request-draining.md
aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample/KestrelSample.csproj
aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample/Startup.cs
aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md
aspnetcore/grpc/aspnetcore.md
aspnetcore/grpc/migration.md
aspnetcore/grpc/security.md
aspnetcore/grpc/troubleshoot.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/mvc/models/file-uploads.md
aspnetcore/release-notes/aspnetcore-5.0.md
aspnetcore/security/authentication/certauth.md
aspnetcore/toc.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0&branch=pr-en-us-21091)
This is an attempt to see what it would look like to split Kestrel's docs into multiple pages so it doesn't feel so overwhelming to read and edit. This is inspired by the IIS documentation which is split up similarly. This only tries to update the aspnetcore-5.0 moniker.
I did my best to fix up the internal deep links referencing the aspnetcore5.0 version of kestrel.md. I also added `<a name="old-section-name"></a>` above the links to the new subpages to help with external deep links that may already be referencing aspnetcore-5.0.
Thoughts?

Split kestrel.md into multiple pages

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Fixes #19979
Made possible by https://github.com/google/brotli/pull/852 - Thanks @eustas! :rocket:
Thanks @mrpmorris! 🎷

Revert to minified Google Brotli script

---

aspnetcore/grpc/comparison.md

The following sentence:
> From this file gRPC frameworks will code generate a service base class...
Has the word "code" which is not required and should read:
> From this file gRPC frameworks will generate a service base class...

Remove unnecessary word in comparison.md

---

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md

Fixes #20699
Thanks @tesar-tech! :rocket:
I don't think we need a full, new section to cover this. I'd like to try further surfacing how the current section explains the configuration. It works the same way for a default Azure domain as it does for a custom domain. The cert creation and config is the same. I'll take further feedback on this :ear:; and if devs are confused by the coverage, we'll see about making further changes.

Blazor IdS HTTPS coverage update

---

aspnetcore/fundamentals/startup.md

The following sentence:
> IStartupFilter allows a different component call...
Is missing the word "to" and should read:
> IStartupFilter allows a different component to call...
PS: the diff view for this PR seems to indicate I made a change with the text `::: moniker-end` but I don't know how that happened or what it even means...just wanted to point it out here for the reviewers!

Fix typo in startup.md

---

aspnetcore/blazor/security/server/index.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/index.md
aspnetcore/security/authentication/identity-api-authorization.md

Fixes #21228
🤔 Guessing a bit on the best way to add/organize the coverage ...
* Main section that describes what to do: `security/authentication/identity-api-authorization.md`
* Cross-links to that section:
* `blazor/security/server/index.md`
* `blazor/security/webassembly/index.md`
* `blazor/security/webassembly/hosted-with-identity-server.md`

Specify the issuer explicitly App Service+IdS

---

aspnetcore/fundamentals/portable-object-localization.md
aspnetcore/razor-pages/index/sample/NuGet.config

Fixes #21021
@mmitche, these were the only files of "myget" in the repo.  `obj\MySharedApp.csproj.nuget.dgspec.json`, but `.gitignore` excludes the `obj` directory.

remove myget.org

---

.openpublishing.redirection.json
aspnetcore/toc.yml

[Internal Review - Verify TOC no longer includes overview for First MVC series](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/index?view=aspnetcore-5.0&branch=pr-en-us-21286&tabs=visual-studio)
[Internal Review - Test redirect of first-mvc-app/](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-5.0&branch=pr-en-us-21286&tabs=visual-studio)
[Internal Review - Test redirect of first-mvc-app/index](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/index?view=aspnetcore-5.0&branch=pr-en-us-21286&tabs=visual-studio)
Fixes #21283 
* Fixed redirect for First MVC series overview that has been removed.
* Removed First MVC series overview from TOC
Related to merged PR …

Fix redirect for First MVC index

---

aspnetcore/fundamentals/localization-extensibility.md

The sentence:
> By implementing `IStringLocalized`,
Should read:
> By implementing `IStringLocalizer`,

Fix type name in localization-extensibility.md

---

aspnetcore/blazor/components/lifecycle.md

Fixes #20921
Thanks @dumaisf! :rocket:
Safia, the example thus far on the PR might be a steaming pile of **_Rex dinosaur droppings_** 💩〰️👃😵, so the example might need work or replacement with something you think would be better. Whatever we do, I hope we flesh out the example and make it a complete *cut-'n-paste* experience. As we discussed offline, it's not an example of a workaround for doing anything specific with the parameters, just *how to work with them generally*.
@dumaisf ... Following our chat on the issue, you can interact with the parameters here ... try to parse one (or several) into your custom type(s) ... if they don't parse, do something else besides load the component ... throw ... redirect. That's a *workaround*/*hack* **_idea only_**, and Safia and I didn't discuss it …

Flesh out SetParametersAsync example

---

aspnetcore/blazor/fundamentals/handle-errors.md
aspnetcore/blazor/security/server/threat-mitigation.md

Fixes #17071
Thanks @mrlife! 🎸 
The coverage is currently in *Size limits on JS interop calls* of the *Call .NET from JS* topic (specifically for surfacing message size limit errors) and more generally in *Threat mitigation guidance for ASP.NET Core Blazor Server*. We don't have this coverage here in the newer *Handle errors* topic. I place it and update the threat mitigation guidance to cross-link.

Detailed circuit errors

---

aspnetcore/blazor/security/webassembly/index.md

Fixes #21323 
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?view=aspnetcore-3.1&branch=pr-en-us-21329#windows-authentication)
Do you want to add to or modify the bullet point above in the *Authentication library* section, which currently reads:
> \* Server endpoints don't require protection against \[Cross-Site Request Forgery (CSRF)](xref:security/anti-request-forgery) because the tokens are sent explicitly. This allows you to host Blazor WebAssembly apps alongside MVC or Razor pages apps.

Blazor Webassembly and Windows Auth

---

aspnetcore/security/cross-site-scripting.md

Insert missing back quote in the WARNING box that talks about `node.InnerText=`

Back quote missing in cross-site-scripting.md

---

aspnetcore/mvc/overview.md

The sentence:
> ...maps to a specific action method on given controller.
Should read:
> ...maps to a specific action method on a given controller.

Fix typo in overview.md

---

aspnetcore/security/data-protection/implementation/key-storage-providers.md

If not writable, sometimes you will suffer `UnauthorizedAccessException: Cannot write to the registry key.` I think a wide used docs should avoid that happen.

make Registry subkey writable

---

aspnetcore/fundamentals/servers/index.md

Fixes #21353
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&branch=pr-en-us-21354&tabs=windows)  ***PLEASE COMPARE SIDE BY SIDE WITH*** [current doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=windows)
Moved the misleading tabs to the top where it belongs. It was under Kestrel.
```
// Misleading tabs talking about Windows, IIS, HTTP.SYS, etc
```
cc @guardrex

Update web servers

---

aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/Startup.cs

Switched the cookies sample to use HttpClientHandler instead of SocketsHttpHandler. HttpClientHandler (the default) handles writing diagnostic events:
https://github.com/dotnet/runtime/blob/01116d4e145d17adefc1237d55b1e3574919b1c1/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L31-L34
So using SocketsHttpHandler directly as the snippet suggests actually breaks some of the default behaviors (besides impacting the cookie feature being discussed). For users using something like https://github.com/open-telemetry/opentelemetry-dotnet this leads to broken traces. Instead of going into that nuance, this seemed like a more fail-safe approach.
/cc @cijothomas

http-requests Cookies Sample HttpMessageHandler

---

aspnetcore/mvc/controllers/application-model.md

The sentence:
> ...application model INCLUDE both abstract interfaces and concrete implementation classes...
Should read:
> ...application model INCLUDES both abstract interfaces and concrete implementation classes...

Fix typo in application-model.md

---

aspnetcore/mvc/controllers/filters.md

Fix format for the WARNING box with the following sentence::
> Only configure IFilterFactory.IsReusable to return true if the source of the filters...
Hopefully this will fix the broken rendering on the [live site](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0#ifilterfactory):

Fix WARNING box format in filters.md

---

aspnetcore/blazor/security/index.md

There's a possible (definate?) conflict of text here - user will either see `You're not authorized` or `Authentication in progress` - one would expect both phrases to refer to "authentication" or both phrases to refer to "authorization".
I believe the latter is correct, hence this PR, but there are potentially other similar confusions of "authentication" / "authorization" in this markdown page, which aren't covered by this PR.

Minor (I think) confliction of "authentication" & "authorization" usage

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

Bumps version from 5.5.0 to 5.6.3 (latest as of today)

Update Swashbuckle NuGet package version

---

aspnetcore/blazor/components/css-isolation.md

[EDIT by guardrex to add the internal review topic link]
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0&branch=pr-en-us-21378)
This pull request addresses #21269, which answers the question: how do I achieve inheritance with Blazor CSS isolation? I added to the custom scopes section to address how to do this.
While in the file, I also did some cleanup:
- Addressed #21289, where it wasn't abundantly clear the `razor.css` files need to be in the same directory as the component it is associated with
- Noticed that, for the `razor.css` references in the project file, I didn't include the `Pages\` path before it. Oops! It's fixed now.
Fixes #21269
Fixes #21289
Fixes #29780

CSS isolation inheritance, minor cleanup

---

aspnetcore/signalr/background-services.md

The [sentence](https://docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-5.0#react-to-signalr-events-with-background-services):
> Like a Single Page App using the JavaScript client for SignalR or a .NET desktop **app can do using the using** the ASP.NET Core SignalR .NET Client...
Should not include the text "**app can do using the using**" and should therefore read:
> Like a Single Page App using the JavaScript client for SignalR, or a .NET desktop app using the ASP.NET Core SignalR .NET Client...

Fix typo in background-services.md

---

aspnetcore/mvc/models/validation.md

> Warning	User	riande	invalid-moniker-range	aspnetcore/mvc/models/validation.md	No "::: moniker-end" found for ">= aspnetcore-3.0", MonikerRange does not end explicitly.	79, 1	02/02/2021 13:02:29
... popped up this morning. This should fix it up.

Remove extra moniker-range

---

aspnetcore/fundamentals/configuration/index.md

The link points to an old location. The code has since been moved to a different repo.

Update link to configuration source code on GitHub

---

aspnetcore/blazor/components/lifecycle.md

Fixes #21416
Thanks @enetstudio! :rocket:
Safia, I found something else here that I think we need to address: Route param matching normally works in a case insensitive way, and we document that [in the Routing topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0#route-parameters). However, `TryGetValue` apparently returns `false` if there's a difference in casing. Therefore, this now calls out that the dev should match the case in the route template to the parameter name.

Before param set update

---

aspnetcore/blazor/host-and-deploy/configure-trimmer.md
aspnetcore/blazor/webassembly-performance-best-practices.md

[Internal Review Topic](#)
* Coalesce the coverage in the Trimmer topic. Only cross-link from the WASM Performance topic.
* There's either missing coverage or a misunderstanding on what the following line means ...
> The Trimmer is also unable to react to an app's dynamic behavior at runtime.
Does that only refer to **_reflection_**, or is that referring to **_other dynamic behavior_** that the topic doesn't describe? If it does refer to other dynamic behavior, should the topic list the behavior and provide guidance on dealing with it? If it's just referring to reflection, we can remove that line. :ear:
* My recommendation is to let the IL Trimming topic take care of the implementation details (i.e., this draft allows the external doc cover the `<PublishTrimmed>` …

Configure Trimmer UE pass

---

aspnetcore/blazor/index.md

Fixes  #21479
The WASM section earlier in the topic calls out that the runtime and code go to the client. Although we cover where the C# code executes for Blazor Server in the *Hosting Models* topic ...
> The app's .NET/C# code base, including the app's component code, isn't served to clients.
... the Introduction topic can call it out briefly with just a few nit changes drafted on this PR.

Clarify Blazor Server's C# execution location

---

aspnetcore/blazor/components/virtualization.md

This addresses an issue asking to clarify the behavior of `ItemSize` when using the `Virtualize` component.
Fixes #21314
cc/ @guardrex

Virtualize updates for ItemSize

---

aspnetcore/blazor/fundamentals/configuration.md

Fixes #21482
Thanks @Micteu! :rocket: ... If you want to do something like this, you should ... *in theory* ... be able to build your own based on (for Blazor Server) ... https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#custom-configuration-provider. For WASM, it's not a supported scenario because EF runs into problems with client sandbox restrictions on making a direct database connection on clients. I'm not saying that it can't be done. I'm just saying that we've been made aware that there are problems that may or may not be a blocker for making it work. It might work with an in-memory dB but not with a formal database on the client. If you need support for a custom approach, discuss it with the community. We recommend the usual community support forums ...
* [Stack …

Remove EF Core config provider
