aspnetcore/migration/22-to-30.md
aspnetcore/web-api/jsonpatch.md

Add instructions to JsonPatch document to use Newtonsoft.Json

---

aspnetcore/security/authorization/secure-data.md

Added instruction to create an Authorization folder

---

aspnetcore/data/ef-rp/intro.md

Fix highlighted lines

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/BlazorSample.csproj

Fixes #14335
I won't hold this up, but an error cropped up in a minor part of the sample app that will be addressed asap (within a couple of weeks due to 🏃 for 3.0 priority issues) on https://github.com/aspnet/AspNetCore.Docs/issues/14338.
cc: @danroth27

Update Blazor common sample app with 3.0-RC1 packages

---

aspnetcore/blazor/components.md

Unparsable values when databinding

---

aspnetcore/fundamentals/middleware/request-response.md

Add missing text to request and response operations.

---

aspnetcore/web-api/advanced/formatting.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/241

Add some notes about configuring Json formatters

---

aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/Startup.cs

Show Startup code for DI in Blazor Build Your First tutorial

---

aspnetcore/tutorials/razor-pages/index.md

I created a video series of this tutorial in Turkish. The link is placed in the additional resources.

Added a link to Youtube version

---

aspnetcore/includes/3.0-SDK.md
aspnetcore/includes/net-core-prereqs-mac-3.0.md
aspnetcore/includes/net-core-prereqs-vs-3.0.md
aspnetcore/includes/net-core-prereqs-vsc-2.2.md
aspnetcore/includes/net-core-prereqs-vsc-3.0.md
aspnetcore/migration/22-to-30.md

Updated Migration from 2.2 to 3.0.

---

aspnetcore/mvc/views/working-with-forms.md
aspnetcore/mvc/views/working-with-forms/sample/final/Controllers/HomeController.cs

Made changes specified by [User Story 1591104](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1591104) 
Replaced one code example with another, added an example, and fixed a typo in the example.

US1591104 Loc Fix - Replace and add examples

---

aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/signalr/streaming.md

PR of Bradys PR

---

aspnetcore/security/cors.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/11962

Endpoint routing + CORS

---

aspnetcore/migration/22-to-30.md
aspnetcore/security/authorization/iauthorizationpolicyprovider.md
aspnetcore/security/cors.md
aspnetcore/security/key-vault-configuration.md

 merge to live 9-18

---

aspnetcore/migration/22-to-30.md

Update migration guide

---

aspnetcore/fundamentals/startup/3.0_samples/StartupFilterSample/Program1.cs

Fixes #14420
Thanks @fitdev ... I was able to repro that. Engineering will let us know if there's another factor involved on review because it was approved when that update went in.
Fixing indentation here, too, but the important update is going from this ...
```csharp
Host.CreateDefaultBuilder(args)
...
.ConfigureServices(services =>
{
services.AddControllersWithViews();
})
...
```
... to ...
```csharp
...
webBuilder.ConfigureServices(services =>
{
services.AddControllersWithViews();
})
...
```

Update example for App Startup topic

---

aspnetcore/signalr/streaming/samples/3.0/Startup.cs

This sample doesn't have any controllers.
I should have done this originally in https://github.com/aspnet/AspNetCore.Docs/pull/14126.

Fix SignalR 3.0 Streaming Sample

---

aspnetcore/migration/22-to-30.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-1.0&branch=pr-en-us-14442&tabs=visual-studio)

Updates to the 2.2-3.0 migration docs

---

aspnetcore/blazor/components.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/javascript-interop/samples_snapshot/component1.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/inject-abstraction-class.cs
aspnetcore/blazor/javascript-interop/samples_snapshot/inject-abstraction.razor
aspnetcore/blazor/layouts.md
aspnetcore/blazor/routing.md
aspnetcore/blazor/state-management.md
aspnetcore/includes/blazor-prerendering.md

[EDIT by guardrex to crosslink issue]
Fixes #13787
@guardrex 
I did a full pass through **all** of the docs and samples. Yup. **all**. 
I didn't find too many things that needed updates. I also added a few things where it seemed like we were light on explanation.

Updates to Blazor docs from 3.0

---

aspnetcore/web-api/http-repl.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14441

Remove version option from HTTP REPL installation command

---

aspnetcore/fundamentals/middleware/extensibility.md
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Data/ApplicationDbContext.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/ConventionalMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/FactoryActivatedMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/MiddlewareExtensions.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/MiddlewareExtensibilitySample.csproj
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Models/Request.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/Error.cshtml
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/Error.cshtml.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/Index.cshtml
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/Index.cshtml.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/Shared/_Layout.cshtml
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/_ViewImports.cshtml
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Pages/_ViewStart.cshtml
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Program.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/README.md
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Startup.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/appsettings.Development.json
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/appsettings.json

Fixes  #13334
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.1&branch=pr-en-us-14472)
* @Tratcher ... any changes or new callouts for `IMiddleware`/`IMiddlewareFactory`?
* New 3.0 sample confirmed working.
* Whole-topic versioning given the number of sample links.

Middleware extensibility update to 3.0

---

aspnetcore/security/cors.md
aspnetcore/security/cors/sample/CorsExample4/Startup.cs

CORS update

---

aspnetcore/mvc/advanced/custom-model-binding.md
aspnetcore/mvc/advanced/custom-model-binding/3.0sample/PolymorphicModelBinding/ModelBinders/PolymorphicModelBinder.cs
aspnetcore/mvc/advanced/custom-model-binding/3.0sample/PolymorphicModelBinding/Pages/AddDevice.cshtml.cs
aspnetcore/mvc/advanced/custom-model-binding/3.0sample/PolymorphicModelBinding/Startup.cs

Fixes #14237
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.0&branch=pr-en-us-14423#polymorphic-model-binding)

Change polymorphic binding to use ComplexTypeModelBinder

---

aspnetcore/signalr/client-features.md
aspnetcore/signalr/clients.md
aspnetcore/toc.yml

not ready yet - working with @scottaddie on a TOC issue
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-3.0&branch=pr-en-us-14394)

add signalr client feature matrix

---

aspnetcore/data/ef-rp/intro.md
aspnetcore/data/ef-rp/migrations.md
aspnetcore/getting-started/index.md
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/includes/RP/model2.md
aspnetcore/includes/add-EF-NuGet-SQLite-CLI.md
aspnetcore/includes/azure-apps-preview-notice.md
aspnetcore/includes/mvc-intro/model2.md
aspnetcore/toc.yml
aspnetcore/tutorials/first-mvc-app/adding-model.md
aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/razor-pages/model.md
aspnetcore/web-api/Microsoft.dotnet-openapi.md
aspnetcore/web-api/http-repl.md

@scottaddie  look no merge conflicts. I did have to bring over a couple commits from aspnetcore/host-and-deploy/azure-apps/index.md
cc @guardrex

Merge Release/3.0 ga to master

---

aspnetcore/host-and-deploy/health-checks.md
aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/ReadinessPublisher.cs
aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/ReadinessPublisher.cs

Fixes #14459
Ignore the build warning ... that link was fixed on another PR.
Thanks @ThomasArdal

Health Checks ReadinessPublisher update

---

aspnetcore/grpc/configuration.md
aspnetcore/grpc/configuration/sample/Program.cs
aspnetcore/grpc/diagnostics.md
aspnetcore/grpc/diagnostics/logging-config-code.cs
aspnetcore/grpc/diagnostics/logging-config.json
aspnetcore/grpc/diagnostics/net-client-dependency-injection.cs
aspnetcore/grpc/diagnostics/net-client-loggerfactory-create.cs
aspnetcore/toc.yml

Addresses https://github.com/grpc/grpc-dotnet/issues/536
Plus minor clean up of configuration article.
Internal URL:
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0&branch=pr-en-us-14484

Add gRPC logging and diagnostics article

---

aspnetcore/web-api/advanced/formatting.md
aspnetcore/web-api/advanced/formatting/3.0sample/Controllers/ProductsController.cs
aspnetcore/web-api/advanced/formatting/sample/Controllers/ProductsController.cs

Fixes #11220.
Fixes #14109
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.0&branch=pr-en-us-14449)

Fixed FormatFilter example for ProductsController.

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/BlazorSample.csproj
aspnetcore/blazor/get-started.md

* Update packages in sample and *Get Started*.
* Sample app confirmed working.

Blazor packages update for 3.0 GA

---

aspnetcore/migration/22-to-30.md

Fixup Razor Class Library

---

aspnetcore/web-api/action-return-types.md
aspnetcore/web-api/action-return-types/samples/2x/WebApiSample.Api.21/Controllers/ProductsController.cs

Update return type | Fix highlited lines
Fixes #14432

Update code snippets

---

aspnetcore/mvc/advanced/app-parts.md
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/ViewComponents/SampleViewComponent.cs
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/Views/Features/Index.cshtml
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/Views/Shared/Components/Sample/Default.cshtml

Added output to docs page for Features sample.

---

aspnetcore/migration/22-to-30.md

The article title was already updated, but the page title was not. Fixes #14510

Update Page Title: Remove 'Preview'

---

aspnetcore/razor-pages/index.md

Updated intro to Razor Pages URL generation.

---

aspnetcore/signalr/scale.md

Fixes https://github.com/aspnet/AspNetCore/issues/13944
Added a note on the Sticky Session requirement in the hosting overview.
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-2.1&branch=pr-en-us-14392)

[SignalR] Add note on Sticky Sessions

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/class-libraries.md
aspnetcore/blazor/components.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/index.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/routing.md
aspnetcore/blazor/state-management.md
aspnetcore/blazor/supported-platforms.md
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/host-and-deploy/blazor/index.md
aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/migration/22-to-30.md
aspnetcore/mvc/advanced/app-parts.md
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/ViewComponents/SampleViewComponent.cs
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/Views/Features/Index.cshtml
aspnetcore/mvc/advanced/app-parts/sample2/AppPartsSample/Views/Shared/Components/Sample/Default.cshtml
aspnetcore/razor-pages/index.md
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/server.md
aspnetcore/signalr/scale.md

4th Merge to live on 9-23 GA day

---

aspnetcore/tutorials/signalr.md

Added additional resource section and link to youtube version.
Fixes #13467

Added link for YouTube version

---

aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/3.x/CurrentDirectoryHelpers.cs

Fixes  #12843
~[Internal Review Topic 2.1](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1&branch=pr-en-us-14462)~ **no or few changes**
[Internal 3.0 version](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0&branch=pr-en-us-14462)
* Whole-topic versioning.
* For 3.0 updates:
* A couple of link changes and an API reference update.
* Changes for the default hosting model.
@halter73, should `shirhatti` look?

Update ANCM doc for 3.0

---

aspnetcore/fundamentals/logging/index.md

Noticed this type while on the doc and it seemed incorrect, so I fixed it up :).

Update typo in logging doc

---

aspnetcore/tutorials/grpc/grpc-start.md
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/GrpcGreeter.csproj
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/GrpcGreeterClient.csproj

Fixes #14522 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&branch=pr-en-us-14521&tabs=visual-studio)

WIP: Update grpc-start.md

---

aspnetcore/migration/22-to-30.md

Fixes #14525
@khteh please review

MySql.Data.EntityFrameworkCore not supported in 3.0

---

aspnetcore/grpc/migration.md

Fix options.ReceiveMaxMessageSize example

---

aspnetcore/migration/22-to-30.md

Fixes #14595
Thanks @hudec117! :rocket:

Fix misspelled word

---

aspnetcore/security/enforcing-ssl.md

Fixes #13928
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&branch=pr-en-us-14568&tabs=visual-studio#troubleshoot-certificate-problems)

Cert troubleshooting

---

aspnetcore/security/data-protection/configuration/overview.md

Fixes #14065
@aKzenT  please review.

Redis warning on storing keys

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/RazorPagesMovie.csproj

Update sample code to use GA packages for RP intro

---

aspnetcore/migration/22-to-30.md

Fixes #14538
@jonstelly please review. This is just a draft on some of the issues you raised. Please suggest better wording.

Docker using Shared Lib

---

aspnetcore/blazor/get-started.md

Fixes #14600
Thanks @kdawg1406! :rocket:

Improve blazorwasm template install instruction

---

aspnetcore/tutorials/first-mvc-app/adding-model.md

remove prerelease

---

aspnetcore/data/ef-rp/intro.md

Added hyper link to ASP.NET Core Razor Pages

Added Hyperlink

---

aspnetcore/release-notes/aspnetcore-3.0.md

Fixes  #14567
@eriawan  please review
@leastprivilege @brockallen please review IdentityServer4. Guidance on securing web API's/SPAs has been our `#1` request the last 18 months. Please suggest better wording.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-1.0&branch=pr-en-us-14612)

IdentityServer4  and new event counters

---

aspnetcore/getting-started/index.md

Updated dotnet run instruction with dotnet watch run since changes in the project are made after the first run.  Also added instruction to refresh the page.
fixes #14636

Updated with dotnet watch run and browser refresh

---

aspnetcore/host-and-deploy/docker/building-net-docker-images.md

Make it version-agnostic so it doesn't need changing in the future

Remove SDK Version callout

---

aspnetcore/migration/22-to-30.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14385

Add Async suffix removal details to 3.0 migration guide

---

aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/BackgroundTasksSample.csproj
aspnetcore/fundamentals/middleware/extensibility-third-party-container/samples/3.x/SampleApp/MiddlewareExtensibilitySample.csproj
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/MiddlewareExtensibilitySample.csproj
aspnetcore/mvc/controllers/testing/samples/3.x/TestingControllersSample/src/TestingControllersSample/TestingControllersSample.csproj
aspnetcore/mvc/controllers/testing/samples/3.x/TestingControllersSample/tests/TestingControllersSample.Tests/TestingControllersSample.Tests.csproj

Fixes #14659
I didn't update three other samples that have versions of `3.0.0-*`. If you want me to update/add them here, 👂:ear::ear:.

Update sample package versions to 3.0.0

---

aspnetcore/web-api/handle-errors.md
aspnetcore/web-api/handle-errors/samples/3.x/Controllers/WeatherForecastController.cs

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14658
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.0&branch=pr-en-us-14670)

Add more detail to Developer Exception Page with web API

---

aspnetcore/web-api/advanced/formatting.md

fix misspelled word "Default" in DefautlContractResolver

---

aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Filters/ClientIdCheckFilter.cs
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Filters/ClientIdCheckPageFilter.cs

Update sample app code for ip-safelist

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/includes/worker-template-instructions.md

Fixes #14637
* Latest guidance for VS UI.
* Move instructions to an INCLUDES.
* VS4Mac instructions were added recently on another PR to one of these, so that's working good content.
Thanks @pwen090! :guitar:

Update worker template instructions

---

aspnetcore/tutorials/getting-started-with-NSwag.md

Fix link to NSwag.MSBuild

---

aspnetcore/release-notes/aspnetcore-3.0.md

Fix a grammar issue

---

aspnetcore/fundamentals/localization.md
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/migration/22-to-30.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/tutorials/razor-pages/index.md

Merge to live 9-30

---

aspnetcore/migration/22-to-30.md

Missing braces and semicolon

---

aspnetcore/fundamentals/logging/index.md

Fixes #14590 
This PR fixes a doc bug introduced by #14508 
cc @guardrex

Fix doc bug introduced by #14508

---

aspnetcore/getting-started/index.md

Removed line: 
Click Accept to accept the privacy and cookie policy. This app doesn't keep personal information.

Removed instruction to accept privacy policy

---

aspnetcore/toc.yml

Remove toc links to deleted articles

---

aspnetcore/grpc/aspnetcore.md
aspnetcore/grpc/basics.md
aspnetcore/grpc/configuration.md
aspnetcore/grpc/index.md
aspnetcore/grpc/troubleshoot.md
aspnetcore/includes/gRPCazure.md
aspnetcore/tutorials/grpc/grpc-start.md

Fixes #14684
@oising please review
Internal review URLs: - search for **warning**
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&branch=pr-en-us-14730
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.0&branch=pr-en-us-14730
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.0&branch=pr-en-us-14730
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/index?view=aspnetcore-3.0&branch=pr-en-us-14730
https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0&branch=pr-en-us-14730
https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&branch=pr-en-us-14730

gRPC not supported on Azure

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fixes #14757 
Swashbuckle.AspNetCore rc4 is released.

Updated nuget package to rc4

---

aspnetcore/razor-pages/index.md

Minor formatting improvements

---

aspnetcore/host-and-deploy/azure-apps/index.md

Fixes #14768
Thanks @timheuer! 🏍

Add --self-contained option to SCD publish command

---

aspnetcore/includes/gRPCazure.md

Fix gPRC to gRPC

---

aspnetcore/getting-started/index.md

For correct information -o directory_name

---

aspnetcore/blazor/hosting-models.md

Per https://github.com/aspnet/AspNetCore.Docs/pull/14759#issuecomment-537758148
cc: @MasihAkbari @rynowak

Update Blazor Server rejected state guidance

---

aspnetcore/blazor/index.md

Change title for consistency with https://docs.microsoft.com/en-us/aspnet/core/blazor/index?view=aspnetcore-3.0

Change title for consistency

---

aspnetcore/security/enforcing-ssl.md

Fix #14776 It is dev-certs, not devcerts

---

aspnetcore/signalr/client-features.md

Trying another format that includes version numbers.
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-3.0&branch=anurse%2Fmore-signalr-matrix)

[SignalR] Client feature matrix update

---

aspnetcore/tutorials/publish-to-iis.md

Fixes #14788
See :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/14788#issuecomment-538035293

Remove Microsoft Visual C++ guidance

---

aspnetcore/grpc/troubleshoot.md

Fixes https://github.com/grpc/grpc-dotnet/issues/574
Internal review URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0&branch=pr-en-us-14780

Add troubleshooting documentation for WPF

---

aspnetcore/grpc/authn-and-authz/sample/Ticketer/Protos/ticket.proto
aspnetcore/grpc/authn-and-authz/sample/TicketerClient/Protos/ticket.proto
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeter/Protos/greet.proto
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Protos/greet.proto

Addresses https://github.com/grpc/grpc-dotnet/issues/580

Update gRPC package case

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/common/samples/3.x/BlazorSample/Components/HTTPRequestTester.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/Pages/CallWebAPI.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/README.md

Fixes #14771
@guardrex please check it out :)

Update Blazor WebAssembly sample to go at pair with the new WebAPI sample

---

aspnetcore/security/authentication/identity.md

Use link to source code version 3.0

---

aspnetcore/fundamentals/host/generic-host.md

Fixes #14848
Thanks @Legends! :rocket:

Update to IHostApplicationLifetime

---

aspnetcore/fundamentals/host/generic-host/samples-snapshot/3.x/Program.cs

Fixes #14850
Thanks @Legends! :guitar:

Add namespace to Generic Host example

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/generic-host/samples-snapshot/3.x/Program.cs
aspnetcore/fundamentals/host/web-host.md
aspnetcore/security/authentication/identity.md

Merge to live Oct 5

---

aspnetcore/blazor/routing.md

Optinal parameters aren't allows in Blazor Server side 3.0 release.

Optional parameters aren't allowed in release

---

aspnetcore/security/authentication/social/social-without-identity.md
aspnetcore/security/authentication/social/social-without-identity/3.0sample/Pages/Index.cshtml.cs
aspnetcore/security/authentication/social/social-without-identity/3.0sample/Pages/Privacy.cshtml.cs
aspnetcore/security/authentication/social/social-without-identity/3.0sample/Startup.cs

Fixes #14578.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.0&branch=pr-en-us-14609)

3.0 version of "Social without Identity".

---

aspnetcore/blazor/class-libraries.md

It is dotnet nuget push + many arguments, not dotnet nuget publish

---

aspnetcore/migration/22-to-30.md

Changed preprocessor directives from `#else if` to the correct `#elif`

Fix preprocessor directives from #else if to #elif

---

aspnetcore/grpc/authn-and-authz.md
aspnetcore/grpc/authn-and-authz/sample/Ticketer/TicketRepository.cs
aspnetcore/grpc/authn-and-authz/sample/Ticketer/Ticketer.csproj
aspnetcore/grpc/authn-and-authz/sample/TicketerClient/Program.cs
aspnetcore/grpc/authn-and-authz/sample/TicketerClient/TicketerClient.csproj

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14837

Update gRPC authentication sample to latest packages

---

aspnetcore/migration/22-to-30.md

Add some extra notes about runtime compilation

---

aspnetcore/fundamentals/logging/index.md

Add Log4Net third-party logging provider

---

aspnetcore/fundamentals/change-tokens.md
aspnetcore/fundamentals/file-providers.md
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/web-host.md
aspnetcore/fundamentals/index.md
aspnetcore/fundamentals/static-files.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/iis/transform-webconfig.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/razor-pages/index.md
aspnetcore/security/data-protection/configuration/overview.md
aspnetcore/security/key-vault-configuration.md
aspnetcore/test/integration-tests.md

Fixes #14165
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/index?view=aspnetcore-2.1&branch=pr-en-us-14888)
* Clarify/clean-up/enhance the content root and web root definitions.
* We aren't treating these as proper nouns. Let's be consistent on that.
* Got all the good cross-links in here. Now when a dev is reading something that pertains to these terms and forgets what they are exactly, they can click right over for a reminder.
* The following language described in the issue wasn't found ... probably removed/updated on other PRs ... therefore, no action taken on them here.
> To fix that setup
> It is based on a set of granular and well factored NuGet packages.This allows you to optimize your app to include just the NuGet packages you need.

Content root & web root enhancements

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/web-host.md

Small update that I caught after merging https://github.com/aspnet/AspNetCore.Docs/pull/14888.

Small language update to Web Root section

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

Fixes #14887
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1&branch=pr-en-us-14892)
* I wasn't pinged/didn't review when that was added, which is why I didn't know it was there.
* Version for >=3.0. Thanks @samf1596.
* Let's move this up above *Troubleshooting*, which we usually place as the last section.
* Quick UE pass. Plz run an :eye: over the language.

Version and enhance certificate forwarding content

---

aspnetcore/security/blazor/index.md

Fixes #14792
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/index?view=aspnetcore-3.0&branch=pr-en-us-14847)
Thanks @patrickhacens! 🏍

Blazor package/namespace clarifications

---

aspnetcore/web-api/http-repl.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14677
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/http-repl?view=aspnetcore-3.0&branch=pr-en-us-14894&tabs=linux#test-secured-endpoints)

Document how to test secured endpoints with HTTP REPL

---

aspnetcore/mvc/controllers/filters.md

Updated description of always-run vs standard Result Filters.

---

aspnetcore/razor-pages/ui-class.md

Fixes #14906
Thanks tidyui! :rocket:

Update option syntax

---

aspnetcore/signalr/messagepackhubprotocol.md

Package name changed from .netcore2.x to .netcore3

Updated for .netcore3

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #14910
Thanks @Structed! :rocket:

Call out file names for examples

---

aspnetcore/fundamentals/logging/index.md

Fixes #14896
Thanks @Legends! 🏍

Clarify data store choice guidance

---

aspnetcore/host-and-deploy/docker/building-net-docker-images.md

Update docker images versions to coincide with the Dockerfile at https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile

Update docker images versions

---

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
aspnetcore/release-notes/aspnetcore-3.0.md

merge to live II on 10-8

---

aspnetcore/blazor/components.md

Fixes #14864
Perhaps, a few light touches here will clean the explanation up a bit. We've had two or three readers write in on this example, so I think we should improve it a hair.

Blazor component example/text touchups

---

aspnetcore/fundamentals/logging/index.md

It seems like it is capitalized other places.

Should Host be capitalized?

---

aspnetcore/blazor/routing.md

Fixes #14953
cc: @CeciAc @yomunsam

Apply code fencing to Router element in example

---

aspnetcore/performance/performance-best-practices.md
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/FireAndForgetSecondController.cs
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/MyFirstController.cs

Fixes #14966
https://review.docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.1&branch=pr-en-us-14965

replace Pokemon with Contoso

---

aspnetcore/performance/performance-best-practices.md

It's ReadFormAsync, not ReadAsFormAsync

---

.ghal.rules.json

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14959

Automate application of gRPC label

---

aspnetcore/fundamentals/middleware/index.md

We'll fix this when 3.0 API gets into the API docs.

Fix bad API ref

---

aspnetcore/performance/performance-best-practices.md
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/MyFirstController.cs

[EDIT by guardrex to add the issue link]
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.1&branch=pr-en-us-14978)
Fixes #14979

updating second snippet to call ReadToEndAsync

---

aspnetcore/toc.yml

Fixes #14641
* "Host in/on" removal
* *-ing* reversion per loc guidelines (we used to do this; reverting it back)

Node name update

---

aspnetcore/tutorials/grpc/grpc-start.md

Update VS4Mac instruction

---

aspnetcore/includes/benefits.md
aspnetcore/index.md

Updated Introduction for 3.0.

---

aspnetcore/fundamentals/localization-extensibility.md
aspnetcore/fundamentals/localization.md
aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md

React to Localization 3.0 changes

---

aspnetcore/performance/performance-best-practices.md
aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/AsyncBadVoidController.cs
aspnetcore/tutorials/razor-pages/sql.md

Attempt to address feedback I gave in https://twitter.com/danielmarbach/status/1182122914398773248
- Added a comment to the snippet for people who mostly focus on code. It might be hard to spot the subtle difference between the two controllers (at least it was for me when reading the article)
- Added more explanation to the intro text that mentions `async void` to be in line with the do this part
I know the explanation is a bit vague mentioning the `await` but I figured it is good enough. Happy to revise if you feel otherwise

Async void

---

aspnetcore/grpc/comparison.md

Fix comparison.md typo

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #15001
Thanks @spanevin! 🎸

Change app_offline file extension

---

aspnetcore/tutorials/first-mvc-app/adding-view.md

Unix delimiters -> Windows

---

aspnetcore/tutorials/publish-to-azure-webapp-using-vscode.md

Fixed a small typo within the `publish-to-azure-webapp-using-vscode document`.

Fixed typo in publish-to-azure-webapp-using-vscode

---

aspnetcore/web-api/advanced/formatting.md

Fixes #14996
@doggy8088  please review

Web API conneg correction

---

aspnetcore/tutorials/razor-pages/page.md

Changes for https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.0&tabs=visual-studio.
- minor grammar errors
- rewording to improve readability

Fixed minor grammar errors and other minor edits

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/servers/kestrel.md

Fixes #14566
Thanks @khteh! :rocket:
[Kestrel internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&branch=pr-en-us-14925#kestrel-options-2)
[generic host internal](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1&branch=pr-en-us-14925)

Kestrel configuration updates

---

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Program.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Startup.cs

Fix intro to MVC startup/program code for GA

---

aspnetcore/host-and-deploy/iis/index.md

Explicitly name 'module' in IIS topic

---

aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md

Fixes #15061
Thanks @matteocontrini! 🏍

Fix Anchor Tag Helper topic headings

---

aspnetcore/security/cors.md

Fixes #14276
Thanks @khteh! :rocket:

CORS 'Origin' header guidance

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #14714
* Is this the cross-link you would like to use? I felt it would be good to cross-link *something* for anyone reading and not knowing/recalling what this is.
* "single-file deployment" (apparently) isn't the MS name for this tech. It's a "web deployment package" or "web package" according to the docs.

Web Package (single-file) deployments support

---

aspnetcore/tutorials/razor-pages/da1.md

Added 'Add  route template'

---

aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/FetchData1.razor

Fixes #15083
* Fix the namespace in the `FetchData` component.
* Separate the hosting model coverage by adding section headings so that they don't drift into each other.
Thanks @aminm1364! 🎸

Blazor tutorial updates

---

aspnetcore/tutorials/razor-pages/model.md

Fixes #15084 
As per comments made in comment from @scottaddie in PR#15070.

Identified cmdlet as Powershell

---

aspnetcore/razor-pages/sdk.md

Remove a redundant "the"

---

aspnetcore/tutorials/razor-pages/sql.md

Typo and formatting improvements

---

aspnetcore/tutorials/razor-pages/new-field.md

Fixes #15067 
Suggestions only :)

Minor wording changes and corrections

---

aspnetcore/migration/22-to-30.md

Fixes #15102
Thanks @atmdevnet! :rocket:

Migration topic update

---

aspnetcore/fundamentals/configuration/options.md

Fixes #15005
* `IOptionsMonitor.Value` :point_right: `IOptionsMonitor.CurrentValue`
* Update for 3.0 package references
Thanks @jawn! 🏍

Update Options code and 3.0 package coverage

---

aspnetcore/host-and-deploy/blazor/server.md

Fixes #14652
[Internal Review Topic (links to *SignalR configuration* section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.0&branch=pr-en-us-14845#signalr-configuration)
Thanks @Alienroid! 🎸

Blazor Server provision/publish for Azure SignalR Service

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/migration/22-to-30.md
aspnetcore/performance/caching/response.md
aspnetcore/security/authentication/social/additional-claims.md

Fixes #15112
Although long, I recommend full refs. Helpful to find these things when u know *exactly* where they are.
cc: @Rick-Anderson @wadepickett

Code-fence cross-refs

---

aspnetcore/blazor/common/samples/3.x/BlazorSample/App.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample/BlazorSample.csproj

Fixes  #15115
Will refactor this into a Blazor Server app (3.0) tomorrow (10/16).

Blazor common sample 3.1 preview update

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/dependency-injection.md
aspnetcore/blazor/get-started.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/index.md
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/routing.md
aspnetcore/blazor/state-management.md
aspnetcore/blazor/supported-platforms.md
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/host-and-deploy/blazor/index.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/includes/blazorwasm-preview-notice.md
aspnetcore/security/blazor/index.md
aspnetcore/tutorials/build-your-first-blazor-app.md

Fixes #15110
* Get Started update.
* INCLUDE update.
* Updating dates on the topics that use the INCLUDE.

Blazor 3.1 Preview Updates

---

aspnetcore/web-api/advanced/formatting.md
aspnetcore/web-api/advanced/formatting/3.0sample/StartupStringOutputFormatter.cs
aspnetcore/web-api/advanced/formatting/sample/StartupStringOutputFormatter.cs

Fixed up explanation of "Special case formatters".

---

aspnetcore/grpc/troubleshoot.md

Fixing typo in section header

---

aspnetcore/mvc/controllers/routing.md

It's worth to mention the implication of using RouteAttribute.

Mention the behavior of RouteAttribute

---

aspnetcore/security/authorization/resourcebased.md

Fixes #6418
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-3.0&branch=pr-en-us-15176#challenge-and-forbid-with-an-operational-resource-handler)

Challenge and Forbid

---

aspnetcore/migration/proper-to-2x/index.md

Fixes #15197
For engineering approval, see :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/15197#issuecomment-542921463

Multi-value cookies unsupported

---

aspnetcore/security/authentication/windowsauth.md

Docs update suggested in https://github.com/aspnet/AspNetCore/issues/14951
Need @Tratcher to confirm that I've interpreted the thread right :).

Update windows auth docs re: NTLM on Kestrel

---

aspnetcore/migration/22-to-30.md

Fixes #15228
Thanks @sander1095! :rocket:

Surface App Service .NET Core rollout website

---

aspnetcore/razor-pages/razor-pages-conventions.md

Fixes #15203
Patch: `UseMvc` 👉 `UseRazorPages` for 3.0 in two examples.

RP conventions topic 3.0 text updates

---

aspnetcore/migration/22-to-30.md

2.2 => 3.0 migration notes for Identity UI.

---

aspnetcore/migration/22-to-30.md

Fixes #15257
https://github.com/aspnet/Announcements/issues/353
Thanks @IGx89! 🎸

IWebHostEnvironment for Startup ctor injection 3.0

---

aspnetcore/blazor/get-started.md
aspnetcore/migration/22-to-30.md
aspnetcore/performance/caching/memory.md
aspnetcore/razor-pages/razor-pages-conventions.md
aspnetcore/test/integration-tests.md

Merge to live 10-22

---

CODE_OF_CONDUCT.md

Merge to live 2nd  on 10-23

---

aspnetcore/tutorials/razor-pages/new-field.md

3rd Merge to live on 10-23

---

aspnetcore/tutorials/razor-pages/page.md

From https://github.com/aspnet/AspNetCore.Docs.zh-cn/pull/199

Remove extra parentheses

---

aspnetcore/security/ip-safelist.md
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Controllers/ValuesController.cs
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Filters/ClientIpCheckFilter.cs
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Filters/ClientIpCheckPageFilter.cs
aspnetcore/security/ip-safelist/samples/2.x/ClientIpAspNetCore/Startup.cs

Do changes below because they are doing ip-filtering
ClientIdCheckFilter -> ClientIpCheckFilter
ClientIdCheckPageFilter -> ClientIpCheckPageFilter

Improve naming

---

aspnetcore/security/authentication/scaffold-identity/consoleAddUser/Data/SeedData.cs
aspnetcore/security/authentication/scaffold-identity/consoleAddUser/Program.cs

Fixes #15286.
I think this is the lowest impact change to make this work, but I do think we can do better. I know I've already said that... :smiley: 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&branch=pr-en-us-15308&tabs=visual-studio#disable-register-page

Use foreach in consoleAddUser.

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #15080
* Enhancements to logging coverage from the discussion on #15080. Thanks @bdcoder2.
* We don't have linkable schema for *web.config* AFAIK. If it does exist, let me know, and I'll add it to these updates.
* I'm going to lowercase the `hostingModel` value because the Web SDK adds it that way. I'll also clarify the case insensitivity of the value throughout the topic.

ANCM topic logging content enhancements

---

aspnetcore/razor-pages/ui-class.md

Fixes #14946 
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&branch=pr-en-us-15310&tabs=visual-studio)
Updated VS instructions for new project to VS 2019.  
(Tested CLI new project instructions, they are good as is.)

Update ui-class.md new project instructions to VS 2019

---

aspnetcore/host-and-deploy/iis/index.md

Removed duplicate link to ASP.NET Core Module

---

aspnetcore/security/key-vault-configuration.md

Link managed identity topic for DevOps pipelines

---

aspnetcore/razor-pages/index.md

Code snippet should be identified as html.

Correct code snippet title to HTML

---

aspnetcore/razor-pages/index.md

Code snippet is titled with CSHTML. Should be HTML to be consistent with other sections.

Changed code snippet title to HTML

---

aspnetcore/security/authentication/community.md

Remove Cierge from OSS auth providers table

---

aspnetcore/test/integration-tests.md
aspnetcore/test/integration-tests/samples/2.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/AuthTests.cs
aspnetcore/test/integration-tests/samples/2.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/BasicTests.cs
aspnetcore/test/integration-tests/samples/2.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/IndexPageTests.cs
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/AuthTests.cs
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/BasicTests.cs

Fixes #12303
Fixes #14592
Fixes #3833
Fixes #6882
Fixes #13451
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1&branch=pr-en-us-15340)
Wonder if we should 🔪 out the `TestGithubClient : IGithubClient` bits?
Thanks @jvandertil ... *Yes!* ... your code sped this up! 🏎🏎🏎 Confirm that you're ok with going on the author byline with our thanks.

Mock authentication and set environment

---

aspnetcore/fundamentals/servers/kestrel.md

UseConnectionLogging

---

aspnetcore/mvc/controllers/filters.md
aspnetcore/mvc/controllers/filters/sample/FiltersSample/Controllers/FailingController.cs
aspnetcore/mvc/controllers/filters/sample/FiltersSample/Filters/CustomExceptionFilter.cs

Fixes #9713.
The direction for #9713 hasn't been decided yet. I've created this PR just to streamline things if this is the chosen outcome.
Edit by @Rick-Anderson 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.0&branch=pr-en-us-15318#exception-filters)
Ping `@dougbu ` after Nov 4th.

Implement the interface in Exception Filter sample.

---

aspnetcore/security/authentication/identity-api-authorization.md

Javier's instructions for customizing the IdentityServerJwt handler.

---

aspnetcore/mvc/models/validation/sample/Attributes/CustomValidationAttributeAdapterProvider.cs

Use is operator to check and cast attribute

Update CustomValidationAttributeAdapterProvider.cs - Use is and cast operator

---

aspnetcore/mvc/views/view-compilation.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15372

Add the supported file extension to view compilation doc

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Controllers/TodoController.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Controllers/TodoController.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.NSwag/Controllers/TodoController.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Controllers/TodoController.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Controllers/TodoController.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/readme.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15314

Replace hard-coded status codes with fields

---

aspnetcore/release-notes/aspnetcore-3.0.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15375

Explain IdentityServer integration added in 3.0

---

aspnetcore/tutorials/build-your-first-blazor-app.md

Fixes #14174
Let's just say that **one** language is better than **two** languages. We can amend as guided by engineering on review.
Thanks @LindaLawton! :rocket:

Explain what we mean by Blazor being "better"

---

aspnetcore/web-api/jsonpatch/samples/3.0/WebApp1/Startup.cs

Fixed Json Patch with NewtonsoftJson snippet.

---

aspnetcore/includes/IdentityServer4.md
aspnetcore/tutorials/first-mongo-app.md
aspnetcore/tutorials/first-web-api.md

Links to secure a Web API

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #15424 
Thanks @erichillah! :rocket:

Update how Kestrel is enabled at >=3.0

---

aspnetcore/blazor/index.md

Add Awesome Blazor cross-link

---

aspnetcore/signalr/supported-platforms.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/10568

Define what current means in the SignalR JS client table

---

aspnetcore/data/ef-rp/intro/samples/cu30snapshots/6-related/Pages/Instructors/IndexSingle.cshtml.cs

Update ef-rp intro IndexSingle snippet to be more in line with full sample

---

aspnetcore/web-api/jsonpatch.md

3.0 Microsoft.AspNetCore.App doesn't include Microsoft.AspNetCore.JsonPatch.

---

aspnetcore/tutorials/grpc/readme.md

Updated client code to match docs and current api
Fixes #14136

Update GrpcClient to client ctor on channel

---

aspnetcore/mvc/models/file-uploads.md

Roll in 3.0 changes to 2.2 portion of file uploads doc

---

aspnetcore/includes/azure-apps-preview-notice.md

Master to live 11-3 - Update azure-apps-preview-notice.md (#15479)

---

aspnetcore/index.md

Fixes #15482
Recommend that we have the migration guide surfaced right off the bat. @michaelbunney would probably have benefited from finding the *Configuration* topic in that node to explain the bits.
Thanks @michaelbunney! :rocket:

Surface the NetFX migration topic

---

aspnetcore/performance/caching/middleware.md
aspnetcore/performance/caching/response.md

Fixes #14643
* I think it's low cost to flesh it out using your language.
* A little more is done here to make sure that it's clear that clients and proxies are *supposed to follow the spec*.
* ... because I see a misspelled word in a doc that I wrote, the 👽 invasion is about to begin! *That's the embedded signal they use in preparation for an attack!* ... I'll head that off by fixing it. :smile:

Respnose caching enhancements

---

aspnetcore/performance/caching/memory.md
aspnetcore/performance/caching/memory/3.0sample/WebCacheSample/Controllers/HomeController.cs

Fixes #15187
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.0&branch=pr-en-us-15501#additional-notes)

add cancelAfter token sample

---

aspnetcore/index.md
aspnetcore/performance/caching/memory.md
aspnetcore/performance/caching/memory/3.0sample/WebCacheSample/Controllers/HomeController.cs
aspnetcore/performance/caching/middleware.md
aspnetcore/performance/caching/response.md

merge to live II on 11-4

---

aspnetcore/security/authentication/identity-api-authorization.md

[ApiAuthorization] Fix wrong code-snippet.

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #15282
We have a line in the *Design services for dependency injection* that might be a good spot for expansion.

DI and static classes/members

---

aspnetcore/grpc/migration.md

Fixes #14406 Fixes #15499 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-3.0&branch=pr-en-us-15500#grpc-interceptors-vs-middleware)

Interceptors vs middleware

---

aspnetcore/blazor/get-started.md
aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationProvider.cs
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Pages/Index.cshtml
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/EFConfigurationProvider/EFConfigurationProvider.cs
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Pages/Index.cshtml
aspnetcore/fundamentals/dependency-injection.md
aspnetcore/grpc/migration.md
aspnetcore/security/authentication/certauth.md
aspnetcore/tutorials/first-mvc-app/adding-model.md

merge to live 11-5

---

aspnetcore/performance/memory.md

This link tripped a loc warning on the Live merge.

Link update

---

aspnetcore/performance/memory.md
aspnetcore/security/authentication/certauth.md
aspnetcore/toc.yml

merge to live 2nd on 11-5

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #15009
Thanks @MaximeMarck! :rocket:

Long request headers enhancements

---

aspnetcore/blazor/forms-validation.md

Add docs for Blazor.DataAnnotations.Validation

---

aspnetcore/includes/RP/code/StartupDevProd.cs
aspnetcore/includes/RP/sqlitedev.md
aspnetcore/tutorials/first-mvc-app/adding-model.md
aspnetcore/tutorials/razor-pages/model.md

Use SQLite in dev, SQL Server in prod

---

aspnetcore/mvc/advanced/app-parts.md

App parts get ready for 3.0

---

aspnetcore/fundamentals/environments.md
aspnetcore/fundamentals/servers/index.md
aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

Fixes #15339
The config files on the issue (*launchSettings.json*, *.pubxml*, and *web.config*) are already covered, so I'm mostly drafting cross-links for this suggested update. We can surface that the publish profiles topic pertains to *.pubxml* files (and improve SEO) but including "(.pubxml)" in the title/H1.

Configuration file enhancements

---

aspnetcore/mvc/controllers/testing.md
aspnetcore/mvc/overview.md

Fixes #14541
There are two spots that make sense: Our *MVC Overview* and the *Test controllers* topic.
Rick, would you prefer one over the other or both?

Surface MyTested.AspNetCore.Mvc

---

aspnetcore/blazor/get-started.md

Related to https://github.com/aspnet/AspNetCore.Docs/pull/15527
/cc: @danroth27

Update Blazor wasm template version number

---

aspnetcore/host-and-deploy/web-farm.md

Fixes #14520
Probably the best that we can do/offer at this time. If you would like an issue to flesh this out later with explicit instructions for the hosting bundle, I can open that and work it later when there's less on my plate. However, their docs look good. :ear:

Azure Custom Script Extension for web farms

---

aspnetcore/fundamentals/file-providers.md
aspnetcore/fundamentals/file-providers/samples/2.x/FileProviderSample/Startup.cs
aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/Startup.cs

Fixes #12527
See the issue :point_up: for explanation.
Thanks @chrisdpratt! :rocket: ... and sorry for the delay getting to this. We've been 🏃😅 for a while now.

ManifestEmbeddedFileProvider assembly

---

aspnetcore/security/authorization/views.md

update aspnetcore/security/authorization/views.md to display the 3.x in the tab

Adding 3.x to the tabs display authorization-views.md

---

aspnetcore/security/authorization/limitingidentitybyscheme.md

update aspnetcore/security/authorization/limitingidentitybyscheme.md to display the 3.x in the tab

Adding 3.x to the tabs display limitingidentitybyscheme.md

---

aspnetcore/security/authentication/identity-api-authorization.md

Fixes #15572.
I wouldn't usually jump on an issue that's not been triaged, but this one was from `@javiercn` and it's a change to a section I've already worked on.

Identity with SPA JwtBearerEvents example.

---

aspnetcore/includes/blazor-prerendering.md

Fixes #15606
Thanks @Matthew-Bonner! :rocket:

Remove empty comment from example

---

aspnetcore/security/authentication/certauth.md

fix for https://github.com/aspnet/AspNetCore.Docs/issues/15601

Adding missing static StringToByteArray method to certauth.md

---

aspnetcore/fundamentals/file-providers.md
aspnetcore/fundamentals/file-providers/samples/2.x/FileProviderSample/Startup.cs
aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/Startup.cs
aspnetcore/fundamentals/localization.md
aspnetcore/includes/blazor-prerendering.md
aspnetcore/mvc/views/razor.md
aspnetcore/performance/memory.md
aspnetcore/security/authentication/certauth.md
aspnetcore/security/authentication/identity-api-authorization.md
aspnetcore/security/authorization/limitingidentitybyscheme.md
aspnetcore/security/authorization/views.md
aspnetcore/web-api/index.md

Merge to live 11-8

---

aspnetcore/blazor/forms-validation.md

Fixes #15631
Thanks @leftmostlane! :rocket:

Fix Blazor forms example

---

aspnetcore/mvc/advanced/app-parts.md

Fixes #15644 
Thanks @MisinformedDNA! :rocket:

Fix versioning of content

---

aspnetcore/blazor/forms-validation.md
aspnetcore/mvc/advanced/app-parts.md
aspnetcore/signalr/scale.md

Merge to live II on11-8

---

aspnetcore/fundamentals/localization.md
aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md

Add information about cause of loc problems

---

aspnetcore/security/data-protection/implementation/key-storage-providers.md
aspnetcore/security/data-protection/implementation/key-storage-providers/sample/Startup.cs

Fixes #15659
I just added code to configure the DbContext, as suggested by the original issue author.
Highlight marker might be messed up, I'll double check when the build finished and I can look at the preview.

fix #15659 by updating the dataprotection sample

---

aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/readme.md

Remove misplaced words in the code example

update readme removing wrong text

---

aspnetcore/mvc/models/validation.md

I've been stung by this 🐝 a few times myself! :smile:

Quick link fix

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/fundamentals/middleware/index/snapshot/Startup22.cs
aspnetcore/fundamentals/middleware/index/snapshot/StartupAll3.cs

Fixes #15353
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-3.0&branch=pr-en-us-15542#middleware-order)
cc @serpent5

Middleware order

---

aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/wwwroot/js/site.js

Fix error message in UpdateItem function in web-api-javascript tutorial

Fix error message in UpdateItem function

---

aspnetcore/performance/performance-best-practices.md

Fixes #15711 and #15710
@Rick-Anderson @paulomorgado

Warn against Task.Run

---

aspnetcore/migration/22-to-30.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15757

Add link to startup injection blog post

---

aspnetcore/test/troubleshoot-azure-iis.md

Fixes #15782
Thanks @wildcatgerry for spotting this! 🎸

Fix 500.35 error explanation

---

aspnetcore/migration/22-to-30.md

Addresses https://github.com/aspnet/AspNetCore.Docs/issues/15793
I worked with Chris to get this issue converted to the standard format. I then opened https://github.com/dotnet/docs/pull/15909 to have it added to the list in the .NET Core docs.

Move SameSite 3.0 breaking change to list in .NET Core docs

---

aspnetcore/signalr/redis-backplane.md

Fixes #15528
@Rick-Anderson  edit: 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.0&branch=pr-en-us-15763)

AddRedis when using Microsoft.AspNetCore.SignalR.Redis

---

aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/BlazorSample.csproj
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/wwwroot/css/site.css
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/wwwroot/index.html

Fixes #15530
Sample app confirmed working.
**EDIT** I repurposed this to move to Preview 3 (`3.1.0-preview3.19555.2`).

Blazor WebAssembly sample to 3.1 Pre3

---

aspnetcore/blazor/forms-validation.md

Blazor forms: nested models & custom attributes

---

aspnetcore/mvc/models/model-binding.md

Fixes #15704.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0&branch=pr-en-us-15820)

Explain relationship between FromBody and FromXXX.

---

aspnetcore/fundamentals/http-requests.md

Fixes: #15849
We frequently get requests for this kind of info, or for a "non-DI"
client factory story.

Add information about alternatives to client factory

---

aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/Startup.cs
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/includes/add-EF-NuGet-SQLite-CLI.md
aspnetcore/mvc/models/model-binding.md
aspnetcore/toc.yml

Merge master to live 11-25

---

aspnetcore/includes/3.1-SDK.md
aspnetcore/includes/net-core-prereqs-mac-3.1.md
aspnetcore/includes/net-core-prereqs-vs-3.1.md
aspnetcore/includes/net-core-prereqs-vsc-3.1.md
aspnetcore/migration/30-to-31.md
aspnetcore/toc.yml

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15678
[Internal review page](https://review.docs.microsoft.com/aspnet/core/migration/30-to-31?view=aspnetcore-1.0&branch=pr-en-us-15875&tabs=visual-studio)

Add 3.0-to-3.1 migration doc

---

aspnetcore/tutorials/web-api-javascript.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14620

Add a step to create a js folder

---

aspnetcore/security/authentication/add-user-data/sample-2.2/Areas/Identity/Pages/Account/Manage/Index.cshtml

Fix form-group divs nesting in "Add, download, and delete custom user data to Identity in an ASP.NET Core project" tutorial

Fix form-group divs nesting

---

aspnetcore/tutorials/build-your-first-blazor-app.md

Addresses #15903
This test PR didn't 💥 on us. Seems that we have approval now for "razor" as a code language. 
I can't locate the offline discussion on this subject (Aquent webmail search is 🤦‍♂). Our plan is to use this code language for Razor components, correct? If so, let's merge this one now, and I'll get to the other topics fairly soon.

Use 'razor' code language

---

aspnetcore/signalr/introduction.md

mentioned that SignalR communications techniques are in Order of gracefull fallback.

mentioned communications techniques are in Order

---

aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md

Script TH and defer attribute

---

aspnetcore/fundamentals/http-requests.md

Fix typos in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests

Fix typos in: Make HTTP requests

---

aspnetcore/fundamentals/host/generic-host.md

Caught out of the corner of the :eye: post merge of today's PR for this topic.

Small content updates to Generic Host topic

---

aspnetcore/fundamentals/localization.md
aspnetcore/mvc/models/model-binding.md
aspnetcore/mvc/models/model-binding/samples/StartupMB.cs

Fixes #15829
@newbienewbie  please review. I tried to make the H2's have SEO power so someone in your position could find it.

globalization behavior of value providers

---

aspnetcore/release-notes/aspnetcore-3.1.md
aspnetcore/release-notes/sample/Program.cs
aspnetcore/toc.yml

Fixes #15955
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.1?view=aspnetcore-3.1&branch=pr-en-us-15954)

What's new in 3.1

---

.openpublishing.publish.config.json
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/JsInteropClasses/ExampleJsInterop.cs
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/JsInteropClasses/ExampleJsInterop.cs
aspnetcore/blazor/javascript-interop.md
aspnetcore/blazor/javascript-interop/samples_snapshot/call-js-example.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/component3.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/inject-abstraction-class.cs
aspnetcore/migration/30-to-31.md
aspnetcore/release-notes/aspnetcore-3.1.md
aspnetcore/release-notes/sample/Program.cs
aspnetcore/toc.yml

Merge to live Dec 3

---

aspnetcore/fundamentals/http-context.md
aspnetcore/release-notes/aspnetcore-3.1.md

Merge to live 2nd time on 3 Dec

---

aspnetcore/security/anti-request-forgery.md

Fixes #13394 
Fixes #13369 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.0&branch=pr-en-us-15816#aspnet-core-antiforgery-configuration)

XSRF minor updates

---

aspnetcore/security/authentication/identity.md

Fixes #13697
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&branch=pr-en-us-15995&tabs=visual-studio)

Explain other Identity products

---

aspnetcore/security/authentication/index.md

Wording enhancement

---

aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/social-code/3.x/StartupMS3x.cs
aspnetcore/security/authentication/social/social-code/StartupMS.cs

[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-1.0&branch=pr-en-us-15985)
Updated the following topic and code example to 3.x and fixed some additional items.  Tested updates.
- microsoft-logins.md
- social-code/3.x/StartupMS3x.cs
Fixes #13299

Updated Microsoft OAuth topic and code to 3.x

---

aspnetcore/fundamentals/logging/index.md

Fixes #16021
[Internal Review Topic (*Windows Event Log provider* section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.1&branch=pr-en-us-16022#windows-eventlog-provider)
* https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.EventLog/src/EventLogSettings.cs
* The topic date was already updated from the PR earlier today.
Thanks @dcp12345678! 🎷

Add cross-links and EventLog setting details

---

aspnetcore/grpc/authn-and-authz.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15831

Clarify that gRPC CallCredentials requires TLS

---

aspnetcore/mvc/views/view-compilation.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/16028
[Internal review page](https://review.docs.microsoft.com/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&branch=pr-en-us-16034#conditionally-enable-runtime-compilation)

Add example of conditional Razor view compilation

---

aspnetcore/client-side/using-grunt.md
aspnetcore/release-notes/aspnetcore-2.1.md
aspnetcore/release-notes/aspnetcore-2.2.md
aspnetcore/release-notes/aspnetcore-3.0.md
aspnetcore/release-notes/aspnetcore-3.1.md
aspnetcore/security/authorization/iauthorizationpolicyprovider.md

I'm waiting on some Blazor things to happen, so this is a good time to do a quick pass and drop our yearly accumulation of 'dumb' smart quotes.

Dropping 'dumb' smart quotes

---

aspnetcore/security/authentication/social/social-code/3.x/StartupTwitter3x.cs
aspnetcore/security/authentication/social/twitter-logins.md

[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.0&branch=pr-en-us-16057)
Fixes #16052 
Updated the following to ASP.NET Core 3.0 / current twitter site UI / Microsoft.AspNetCore.Authentication.Twitter 3.0.0 package instruction:
- security/authentication/social/twitter-logins.md
- security/authentication/social/social-code/3.x/StartupTwitter3x.cs

Updated twitter-logins.md and code example to 3.0.

---

aspnetcore/fundamentals/environments.md

Fixes #16062
[Internal 3.0 review url](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.0&branch=pr-en-us-16061)
[Internal 2.2 review url](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2&branch=pr-en-us-16061)

refactor env

---

aspnetcore/tutorials/web-api-help-pages-using-swagger.md

Renaming GH Id ... this was throwing in a Blazor build this morning.

Update author GH Id

---

aspnetcore/security/authentication/windowsauth.md

Addresses #12833
I'll cross-link `AddNegotiate` to API docs later when it becomes available.

WinAuth Negotiate namespace content

---

aspnetcore/security/authentication/certauth.md

Fixes #16086
Cleaning up the spacing in code blocks here.

CertAuth topic code block improvements

---

aspnetcore/tutorials/razor-pages/razor-pages-start.md

Fixes #16105
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&branch=pr-en-us-16104&tabs=visual-studio)

RP update to 3.1

---

aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/RazorPagesMovie.csproj

update WebAPI intro to 3.1

---

aspnetcore/web-api/handle-errors.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/15670

Add callout about RFC compliance in 2.1

---

aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/Startup.cs

Update incorrect class name used in the cookie handling snippet

---

aspnetcore/grpc/configuration.md

Double check this is correct @JunTaoLuo

Add interceptors to configuration

---

aspnetcore/security/authentication/social/social-without-identity.md

Fixes #16131.
@Rick-Anderson I'm working on a couple of bigger issues I've signed up for, but I thought this would be a quick and useful addition in the meantime.

Xrefs to authn overview.

---

aspnetcore/includes/http-repl/requires-body-options.md
aspnetcore/web-api/http-repl.md
aspnetcore/web-api/http-repl/samples/SwaggerApp/Startup.cs
aspnetcore/web-api/http-repl/samples/SwaggerApp/SwaggerApp.csproj

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/14356
Also updates the sample web API from 2.2 to 3.1

Fix formatting of inline JSON request body content

---

aspnetcore/web-api/Microsoft.dotnet-openapi.md

Part of https://github.com/aspnet/AspNetCore/issues/17826

Remove references to verbose option which doens't exist

---

aspnetcore/signalr/javascript-client.md

Add missing curly brace in code sample

---

aspnetcore/tutorials/signalr-typescript-webpack.md

Replaces https://github.com/aspnet/AspNetCore.Docs/pull/16164

Rename SignalR JS client npm package for 2.x

---

aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/ChangeTokenSample.csproj
aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/ConfigurationSample.csproj
aspnetcore/fundamentals/configuration/options/samples/3.x/OptionsSample/SampleApp.csproj
aspnetcore/fundamentals/dependency-injection/samples/3.x/DependencyInjectionSample/DependencyInjectionSample.csproj
aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/FileProviderSample.csproj
aspnetcore/fundamentals/file-providers/samples/3.x/WatchConsole/WatchConsole.csproj
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/BackgroundTasksSample.csproj
aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactoryConsoleSample/SampleApp.csproj
aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactorySample/HttpClientFactorySample.csproj
aspnetcore/fundamentals/logging/loggermessage/samples/3.x/LoggerMessageSample/LoggerMessageSample.csproj
aspnetcore/fundamentals/middleware/extensibility-third-party-container/samples/3.x/SampleApp/MiddlewareExtensibilitySample.csproj
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/MiddlewareExtensibilitySample.csproj
aspnetcore/fundamentals/routing/samples/3.x/RoutingSample/RoutingSample.csproj
aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp/HttpSysSample.csproj
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/KestrelSample.csproj
aspnetcore/fundamentals/url-rewriting/samples/3.x/SampleApp/SampleApp.csproj
aspnetcore/host-and-deploy/windows-service/samples/3.x/BackgroundWorkerServiceSample/SampleApp.csproj
aspnetcore/host-and-deploy/windows-service/samples/3.x/WebAppServiceSample/SampleApp.csproj
aspnetcore/performance/caching/distributed/samples/3.x/DistCacheSample/SampleApp.csproj
aspnetcore/performance/caching/middleware/samples/3.x/ResponseCachingMiddleware/ResponseCachingMiddleware.csproj
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/SampleApp.csproj
aspnetcore/security/authentication/cookie/samples/3.x/CookieSample/CookieSample.csproj
aspnetcore/security/authentication/social/additional-claims/samples/3.x/ClaimsSample/ClaimsSample.csproj
aspnetcore/security/authorization/razor-pages-authorization/samples/3.x/AuthorizationSample/AuthorizationSample.csproj
aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/SampleApp.csproj

Addresses #5495
* The *low-hanging fruit* ones that can be updated without too much concern that they'll :boom: on us without testing.
* A handful of others will be put up on later PR(s) because they're complicated enough that they warrant a test run when updating to 3.1.

3.1 Sample Updates

---

aspnetcore/toc.yml

Fixes #16181
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.2&branch=pr-en-us-16194&tabs=visual-studio)

remove blazor samples from toc.yml

---

aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/SampleApp.csproj
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/src/RazorPagesProject/RazorPagesProject.csproj
aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/RazorPagesProject.Tests.csproj
aspnetcore/test/razor-pages-tests/samples/3.x/src/RazorPagesTestSample/RazorPagesTestSample.csproj
aspnetcore/test/razor-pages-tests/samples/3.x/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

Addresses #5495
Confirmed running for this group: two testing samples and the file uploads sample.

Sample updates to 3.1

---

aspnetcore/migration/22-to-30.md
aspnetcore/migration/22-to-30/samples/HomeController.cs
aspnetcore/migration/22-to-30/samples/Startup.cs
aspnetcore/migration/22-to-30/samples/Startup2.cs

Merge to #16092 when approved.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-1.0&branch=pr-en-us-16129&tabs=visual-studio#authorization-for-specific-endpoints)
External review:
* [Download 1.zip](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
* Unzip 1.zip file

Merge into Pranav's PR

---

aspnetcore/fundamentals/http-requests.md

Fixes #16213
Ok ... now we're cook'in. ☕️
Not that it matters really, but I'm going to set Line 660 for perfect harmony.

Surface JSON serialize content and version >=2.1

---

aspnetcore/migration/proper-to-2x/index.md

Fixes #10033
@shirhatti  can you edit this and complete the draft? Better to publish some help than to let the issue languish a few years.

Add Partial app migration to migration doc for IIS folks

---

aspnetcore/signalr/scale.md

Talk about avoiding IIS

---

aspnetcore/fundamentals/environments.md

Changed App Settings to Configuration

update Azure App Service set environment

---

aspnetcore/fundamentals/middleware/index.md

Just a refactor to make #16241 easier for PU to review

refactor middleware monikers

---

aspnetcore/security/authentication/scaffold-identity.md

refactor scaffold identity

---

aspnetcore/mvc/models/validation.md

broken link fixed

---

aspnetcore/security/authentication/azure-active-directory/index.md
aspnetcore/toc.yml

Fixes #16257
Thanks @freemstr! 🎷 Sorry for the misunderstanding. I searched the docs markdown files (*.md*) thinking it was in a topic, but our TOC (table of contents) file for the sidebar TOC is actually a YAML file (*.yml*), so I missed it. *Thanks for your persistence!*

Update links to Azure samples

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #16265
Thanks @Ricardoaraujo00! ⛄️ ... *We assume a little too much sometimes!* Thanks for calling this out, and we look forward to hearing if you run into additional troubles with any of the topics. Please feel free to use the **This page** feedback button+form at the bottom of any topic. It adds metadata to track the work and automatically pings the author when your docs issue is created.

Improve Kestrel startup example

---

aspnetcore/mvc/models/model-binding.md

Remove double TryUpdateModelAsync section from Model Binding.

---

aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg.md
aspnetcore/includes/scaffold-identity/migrations.md
aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupMVC.cs
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupRP.cs
aspnetcore/security/authentication/scaffold-identity/3.1sample/_Layout.cshtml

Fixes #10159 
No repo on #8440 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&branch=pr-en-us-16258&tabs=netcore-cli)

scaffold Identity 3.1 update

---

aspnetcore/razor-pages/filter.md

3.1 update of Filter methods for RP

---

aspnetcore/migration/22-to-30.md
aspnetcore/migration/22-to-30/samples/HomeController.cs
aspnetcore/migration/22-to-30/samples/Startup.cs
aspnetcore/migration/22-to-30/samples/Startup2.cs

@Rick-Anderson  edit: Moved to #16129

Add global auth filter + policy migration example

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/fundamentals/middleware/index/snapshot/Chain/StartupUseWhen.cs

Additional explanation of middleware pipeline configuration options.

---

aspnetcore/fundamentals/middleware/index.md

Fixes #16241
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-3.1&branch=pr-en-us-16252#built-in-middleware)
Note: This change is to the 3.x version of the doc only.
cc @guardrex  on how nice the diff is.

Add authorization to middleware table

---

aspnetcore/includes/notUpdated31.md
aspnetcore/mvc/controllers/filters.md

Filter refactor for 3.1

---

aspnetcore/includes/add-EF-NuGet-SQLite-CLI.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg.md
aspnetcore/includes/scaffoldTFM.md

Fixes #16329
Internal review URLs (search for  `a scaffolding error` )
* [Scaffold Identity](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&branch=pr-en-us-16332&tabs=netcore-cli)
* [Add a model to an ASP.NET Core MVC app ](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&branch=pr-en-us-16332&tabs=visual-studio-code)
* [Add a model to Razor Pages](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&branch=pr-en-us-16332&tabs=visual-studio-mac)

Scaffold warning TFM must match NuGet packages

---

aspnetcore/security/authentication/certauth.md

adding some defualt values for the certificate authentication options

Adding the default values for the certificate authentication options

---

aspnetcore/mvc/controllers/filters.md

Fixes #16377.
Just a very quick, high-level pass where I noticed a couple of things that might be worth merging before I can take a look at the live version and I have a bit more time. If this doesn't get merged before, I'll add extra commits to this PR if I find more.

A few updates to Filters.

---

aspnetcore/mvc/controllers/filters.md

merge to live 2nd on 2 Jan 2020

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #16393
Thanks @SgtSpamCan! ⭐️

Update IIS topic section to 3.0+

---

aspnetcore/security/authorization/introduction.md

Fixes #16413.
Just a small commit this time for a suggestion I made earlier today.

Add xref from authz to authn.

---

aspnetcore/host-and-deploy/azure-apps/index.md

Fixes #16025
Fixes #16114
[Internal Review Topic (*Override app configuration using the Azure Portal* section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?view=aspnetcore-2.1&branch=pr-en-us-16225#override-app-configuration-using-the-azure-portal)
Thanks @drdamour! 🏍
Thanks @jawn! 🎸

Clarify env var config in Azure Apps topic

---

aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md

Updating previous fix from blog post to official doc

Updated from macOS link from blog post to doc

---

aspnetcore/grpc/versioning.md
aspnetcore/grpc/versioning/sample/GreeterServiceV1.cs
aspnetcore/grpc/versioning/sample/greet.v1.proto
aspnetcore/toc.yml

~@Rick-Anderson  edit: Current work at #16417~ Merged
Fixes https://github.com/grpc/grpc-dotnet/issues/604
Internal preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-3.0&branch=pr-en-us-16404

Add gRPC versioning article

---

aspnetcore/fundamentals/http-requests.md

Fix typo 'dispostHandler' -> `disposeHandler`

---

aspnetcore/security/authentication/individual.md

Feedback for #16135

---

aspnetcore/getting-started/index.md
aspnetcore/grpc/versioning.md
aspnetcore/signalr/security.md
aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Program.cs
aspnetcore/tutorials/signalr-typescript-webpack.md

Merge to live Jan 7

---

aspnetcore/security/authentication/individual.md

Fixes #15142
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-3.1&branch=pr-en-us-16135)

LIst auth options

---

aspnetcore/tutorials/razor-pages/model.md

Minor fix to point to the correct image.

Correcting image url

---

aspnetcore/security/authentication/individual.md
aspnetcore/tutorials/razor-pages/model.md

merge to live 2nd time on Jan 7

---

aspnetcore/grpc/versioning.md

Move behavior info into its own section .

Update gRPC versioning doc

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/TimedHostedService.cs

Fixes #16358
Thanks again @thanuja89 and @huan086! :rocket:

Hosted service updates

---

aspnetcore/grpc/client.md

Update gRPC client doc with channel usage

---

aspnetcore/security/authentication/identity-api-authorization.md

This was bugging me when reading through the doc. Small change, but I think it's easier to read.

Fix grammatical error

---

aspnetcore/tutorials/razor-pages/model.md

Adding some missing instructions for scaffolding with Visual Studio for Mac.

minor update to add instruction to add dotnet ef tools

---

aspnetcore/mvc/controllers/routing.md

Fixed a grammatical error

---

aspnetcore/performance/caching/response.md

Added NCache as distributed cache and added link of microsoft IDistributedCache Nuget

NCache and redis links added

---

aspnetcore/host-and-deploy/windows-service.md
aspnetcore/host-and-deploy/windows-service/samples/scripts/DisableDumps.ps1
aspnetcore/host-and-deploy/windows-service/samples/scripts/EnableDumps.ps1
aspnetcore/test/troubleshoot-azure-iis.md

Fixes #16481
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&branch=pr-en-us-16504)
* Common errors content was derived from experience and prior issues opened by the community. Can you think of more *gotchas* to list there?
* WS entries show up in both System (SCM) and Application (dotnet) Event Logs, so I recommend the dev look at both.
* Let's roll in the usual *incoherent packages* advice when updating apps.
* Crash dump content: I tested locally with a service that had a C# line to cause a crash in a page handler. The crash dump file was produced following the approach here. Did I miss anything tho?
Thanks @mdddev! 🎸 ... Do you want to take a look and see if this new content would have saved you?

Windows Service topic troubleshooting

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Clarify User option in Linux .service files

---

aspnetcore/migration/22-to-30.md

See https://github.com/dotnet/aspnetcore/issues/13564#issuecomment-534627765
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-1.0&branch=pr-en-us-16529)

Link to JSON migration doc + clarify pkg requirements

---

aspnetcore/data/ef-mvc/intro.md

Remove moniker tags on tutorial

---

aspnetcore/fundamentals/index.md
aspnetcore/security/authentication/identity.md
aspnetcore/security/authentication/scaffold-identity.md

Fixes #16482
* Approved by https://github.com/dotnet/aspnetcore/issues/16862#issuecomment-550438934.
* Cross-links from the *Web root* section and the scaffolding topic might make this more discoverable, since a dev may hit either of those in a search result looking for something on this.
Thanks @mmarinchenko! 🌴

Prevent publish of static Identity assets

---

aspnetcore/security/samesite.md

Adding links to the shipped packages

Add samesite patch links

---

aspnetcore/blazor/lifecycle.md
aspnetcore/data/ef-mvc/intro.md
aspnetcore/fundamentals/index.md
aspnetcore/host-and-deploy/docker/building-net-docker-images.md
aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/migration/22-to-30.md
aspnetcore/security/authentication/identity.md
aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/security/blazor/server.md
aspnetcore/security/samesite.md
aspnetcore/signalr/dotnet-client.md
aspnetcore/signalr/supported-platforms.md

Merge to live 16 Jan

---

aspnetcore/blazor/dependency-injection.md

Fixes #16363
Thanks @drbldgtl! ⛄️
* https://github.com/dotnet/aspnetcore/blob/master/src/Components/Server/src/DependencyInjection/ComponentServiceCollectionExtensions.cs#L73-L74
* https://github.com/dotnet/aspnetcore/blob/5e575a3e64254932c1fd4937041a4e7426afcde4/src/Components/Blazor/Blazor/src/Hosting/WebAssemblyHostBuilder.cs#L93-L94

Update service lifetimes to include Blazor Server

---

aspnetcore/blazor/debug.md

This should fix it ... confirmed locally.

Blazor Debug topic list fix

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

Update version of Swashbuckle.AspNetCore to 5.0.0

---

aspnetcore/data/ef-mvc/intro.md
aspnetcore/migration/22-to-30.md
aspnetcore/mvc/models/validation.md
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/StartupDevProd.cs
aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/razor-pages/model.md

Merge master to live 17 Jan

---

aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/migration/1x-to-2x/samples/AspNetCoreDotNetFx2.0App/AspNetCoreDotNetFx2.0App/Controllers/ManageController.cs
aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Pages/StreamedSingleFileUploadPhysical.cshtml
aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Pages/StreamedSingleFileUploadPhysical.cshtml
aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo/Controllers/ManageController.cs
aspnetcore/security/authorization/resourcebased/samples/2_2/ResourceBasedAuthApp2/Controllers/ManageController.cs

Fixed some typos: 
- occured --> occurred
- Libary --> Library
- recieves --> receives

Contributing: Fixed some typos

---

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/CascadingValuesParametersTheme.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/ParentComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/RazorTemplates.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/TemplatedComponents.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Shared/CascadingValuesParametersLayout.razor
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Shared/NavMenu.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CascadingValuesParametersTabSet.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CascadingValuesParametersTheme.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/ParentComponent.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/RazorTemplates.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/TemplatedComponents.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Shared/CascadingValuesParametersLayout.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Shared/NavMenu.razor
aspnetcore/blazor/components.md
aspnetcore/blazor/dependency-injection/samples_snapshot/3.x/CustomerList.razor
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/get-started/samples_snapshot/3.x/Counter1.razor
aspnetcore/blazor/get-started/samples_snapshot/3.x/Counter2.razor
aspnetcore/blazor/handle-errors/samples_snapshot/3.x/product-details.razor
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/javascript-interop/samples_snapshot/call-js-example.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/component1.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/component2.razor
aspnetcore/blazor/javascript-interop/samples_snapshot/component3.razor
aspnetcore/blazor/lifecycle/samples_snapshot/3.x/FetchData.razor
aspnetcore/blazor/state-management.md

Fixes #15853
There are one or two template nits. I'll submit an engineering PR for those.

Make use of field underscores consistent

---

aspnetcore/test/troubleshoot-azure-iis.md

This 500.30 issue seems to pop up a lot, but doesn't show much information. When using Key Vault, this seems to be a common developer error.

Added 500.30 Key Vault note - a common issue

---

aspnetcore/razor-pages/index.md

Clearer explanation of RP handler URL customization.

---

aspnetcore/performance/caching/distributed.md

Added NCache info in Prereqs
added NCache distributed cache sub section in the Idistibutedcache section

Add NCache coverage to the Distributed Caching topic

---

aspnetcore/security/authentication/social/index.md

Update version to ASP.NET Core 3.1

---

aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md

Mentioning NCache as a third-party for Distributed Cache Tag Helper IDistributedCache implementations

NCache as IDistributedCache thirdparty implementation

---

aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper.md

This is to remove the duplication of the code for "asp-fallback-test-value" section.

Remove duplicated section

---

aspnetcore/blazor/handle-errors.md

Add a sample for circuit handler

---

aspnetcore/mvc/views/view-compilation.md
aspnetcore/razor-pages/sdk.md
aspnetcore/razor-pages/web-sdk.md
aspnetcore/toc.yml

* Adds missing details to RazorSDK
* Adds a Web SDK section (cc @vijayrkn)
* Re-organize TOC a bit

Fill in SDK gaps

---

aspnetcore/blazor/handle-errors.md
aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper.md
aspnetcore/mvc/views/view-compilation.md
aspnetcore/razor-pages/sdk.md
aspnetcore/razor-pages/web-sdk.md
aspnetcore/toc.yml

Merge to live 24 Jan

---

aspnetcore/grpc/browser.md
aspnetcore/grpc/browser/sample/AllServicesSupportExample_Startup.cs
aspnetcore/grpc/browser/sample/Handler.cs
aspnetcore/grpc/browser/sample/Startup.cs
aspnetcore/toc.yml

Edit by @wadepickett - all work moved to  #16676   for edit/move snippets to files, etc. **Do no edit, commit or provide feedback on this until #16676   merges into this**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-16613)
[EDIT by guardrex to add the fixes: We just had a community member (@cveld) ask for more info on this.]
Fixes #16598
Review but don't merge. This will be merged after gRPC-Web has been released on NuGet.
Preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-16613

Add gRPC-Web article

---

aspnetcore/web-api/index.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/16631

Restrict display of section link to ASP.NET Core 2.2 or later

---

aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/http-requests/samples/2.x/Startup21.cs
aspnetcore/fundamentals/http-requests/samples/3.x/Startup.cs

This is a PR of #16705
[Internal review URL 3.1](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1&branch=pr-en-us-16717#header-propagation-middleware)
[Internal review URL 2.1](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1&branch=pr-en-us-16717#header-propagation-middleware-1)

Header propagation middleware PR of PR

---

aspnetcore/tutorials/first-mvc-app/adding-view.md

Visual Studio for Mac documentation for Add a View is updated to match the screenshot

Update "Add a View" documentation for for Mac

---

aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/http-requests/samples/2.x/Startup21.cs
aspnetcore/fundamentals/http-requests/samples/3.x/Startup.cs

~All work moved to #16717~
[Internal review 2.1 Header propagation middleware](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1&branch=pr-en-us-16705#header-propagation-middleware-1)
[3.1 Internal review Header propagation middleware](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1&branch=pr-en-us-16705#header-propagation-middleware)

Add a snippet about header propogation

---

aspnetcore/blazor/javascript-interop.md

These are the current highlights pointing to wrong lines:

Fix highlighted lines in code sample

---

aspnetcore/security/authentication/add-user-data.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&branch=pr-en-us-16760&tabs=visual-studio)
Fixes #16757
Minor fix:
Replaced ADD with Add, add where appropriate.

Minor update to add-user-data.md

---

aspnetcore/blazor/components.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/routing.md
aspnetcore/client-side/libman/libman-cli.md
aspnetcore/data/ef-mvc/migrations.md
aspnetcore/data/ef-rp/migrations.md
aspnetcore/fundamentals/dependency-injection.md
aspnetcore/getting-started/index.md
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/includes/ef-cli.md
aspnetcore/security/authentication/identity-api-authorization.md
aspnetcore/security/authorization/limitingidentitybyscheme.md
aspnetcore/security/key-vault-configuration.md
aspnetcore/signalr/messagepackhubprotocol.md
aspnetcore/signalr/streaming/samples/3.0/Hubs/AsyncEnumerableHub.cs
aspnetcore/toc.yml
aspnetcore/tutorials/first-mvc-app/adding-model.md
aspnetcore/whats-new/2019-09.md

Merge to live Jan 31 

---

aspnetcore/performance/caching/memory.md

Incorrect word / fix (assumed) autocomplete

---

aspnetcore/mvc/controllers/filters.md

Clarify filters for Razor components

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #16858
Thanks @byroniac! ⛄️

Clarify namespaces in Linux topic examples

---

aspnetcore/razor-pages/razor-pages-conventions/samples/2.x/SampleApp/Pages/About.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/2.x/SampleApp/Pages/Contact.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/2.x/SampleApp/Pages/OtherPages/Page1.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/2.x/SampleApp/Pages/OtherPages/Page2.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/2.x/SampleApp/Pages/OtherPages/Page3.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Pages/About.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Pages/Contact.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Pages/OtherPages/Page1.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Pages/OtherPages/Page2.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions/samples/3.x/SampleApp/Pages/OtherPages/Page3.cshtml.cs

Fixes #16875
Thanks @davecanderson! 🏍

Fix sample apps for Razor Pages Conventions topic

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/web-api/index.md
aspnetcore/web-api/index/samples/3.x/Controllers/ConsumesController.cs

Merge to live Feb 6

---

aspnetcore/grpc/diagnostics.md

Fixes https://github.com/grpc/grpc-dotnet/issues/714
Fixes https://github.com/grpc/grpc-dotnet/issues/536
Internal preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0&branch=pr-en-us-16512

gRPC diagnostics content

---

aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp/Program.cs

Fixes #16910
Thanks @StevenTCramer! ⛄️

Update AllowSynchronousIO to false in 3.x sample

---

aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp/Program.cs
aspnetcore/grpc/diagnostics.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/security/samesite/sample/Startup.cs
aspnetcore/security/samesite/sample/Startup31.cs
aspnetcore/web-api/index.md

Merge to live 7 Feb

---

aspnetcore/web-api/action-return-types.md

Fix non-async ToListAsync example code.

---

aspnetcore/fundamentals/middleware/index.md

Fixes #16865.
It turns out this was _slightly_ more than just a space issue.

Fix xref to Angular SPA topic.

---

aspnetcore/grpc/browser.md
aspnetcore/grpc/browser/sample/AllServicesSupportExample_Startup.cs
aspnetcore/grpc/browser/sample/Startup.cs

Add "UseGrpcWeb should be added between UseRouting and UseEndpoints" comment to code to make it clear where the middleware must be added.
Also fix various other issues.

Fix various gRPC browser issues

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/servers/httpsys.md
aspnetcore/host-and-deploy/azure-iis-errors-reference.md
aspnetcore/host-and-deploy/directory-structure.md
aspnetcore/host-and-deploy/iis/development-time-iis-support.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/proxy-load-balancer.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/performance/caching/distributed.md
aspnetcore/performance/caching/middleware.md
aspnetcore/performance/response-compression.md
aspnetcore/razor-pages/razor-pages-conventions.md
aspnetcore/security/key-vault-configuration.md
aspnetcore/test/troubleshoot-azure-iis.md

Fixes  #16907
Versioning for the remaining fifteen that I'm `ms.author` on. No warnings/errors on the build report.
Break out the *EYE DROPS!* 👁

Whole-topic versioning

---

aspnetcore/mvc/models/validation.md

Fix inline SuppressImplicitRequiredAttributeForNonNullableReferenceTypes snippet.

---

aspnetcore/migration/30-to-31.md

Upgraded to latests sdk and nuget versions

---

aspnetcore/security/blazor/index.md

Fixes #16813
Helpful to those looking for custom authn/z solutions, such as authenticating from a component until something nice lands in the box for 5.0.
Thanks @idchlife! 🎸

Update Blazor Auth Additional Resources

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Program.cs

Fixes #16905
Thanks @KeeganFargher! 🏍

Show start of MonitorLoop in background tasks

---

aspnetcore/fundamentals/configuration/index.md

Fixes #16933
Thanks @MP7373! 🏍

Connection string example for env var config

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Program.cs
aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/middleware/request-response/samples/3.x/RequestResponseSample/Startup.cs
aspnetcore/fundamentals/servers/httpsys.md
aspnetcore/grpc/browser.md
aspnetcore/grpc/browser/sample/AllServicesSupportExample_Startup.cs
aspnetcore/grpc/browser/sample/Startup.cs
aspnetcore/host-and-deploy/azure-iis-errors-reference.md
aspnetcore/host-and-deploy/directory-structure.md
aspnetcore/host-and-deploy/iis/development-time-iis-support.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/proxy-load-balancer.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/migration/30-to-31.md
aspnetcore/mvc/models/validation.md
aspnetcore/performance/caching/distributed.md
aspnetcore/performance/caching/middleware.md
aspnetcore/performance/response-compression.md
aspnetcore/razor-pages/index/sample/RazorPagesContacts2/Pages/Customers/CreateFATH.cshtml.cs
aspnetcore/razor-pages/index/sample/RazorPagesContacts2/Pages/Customers/CreateRoute.cshtml.cs
aspnetcore/razor-pages/razor-pages-conventions.md
aspnetcore/security/blazor/index.md
aspnetcore/security/key-vault-configuration.md
aspnetcore/test/troubleshoot-azure-iis.md
aspnetcore/tutorials/web-api-javascript.md

Merge master to Live 10 Feb 

---

aspnetcore/fundamentals/environments/sample/EnvironmentsSample/Pages/About.cshtml

Fixes #16962
I had a minute here ... I'm waiting on a decision on the Blazor side of things to proceed with some more Blazor work. RA, if you want to address that yourself or close the issue as a `won't fix`, I'm good. :+1:

Enhance the display of which tag (environment) is effective

---

aspnetcore/security/authentication/cookie.md

Fixes #16960 
Thanks @ygoe! ⛄️
WRT ...
> how I should set the auth+cookie expiration time so that it works in current and future versions of ASP.NET Core
I don't think we can speak to **_future versions_** 🔮:smile: ...... *but* ... I think this will be stable going forward. If there's another passage that you think isn't correct, @ygoe, let us know here on the PR. It's not too late to address something else here, too.

Update cookie auth class/property

---

aspnetcore/grpc/browser.md
aspnetcore/grpc/browser/sample/Handler.cs

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1&branch=pr-en-us-16934)
Fixes https://github.com/grpc/grpc-dotnet/issues/764
Addresses https://github.com/grpc/grpc-dotnet/issues/759
Also fix some minor issues
Preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-16934

gRPC-Web documentation fixes

---

aspnetcore/fundamentals/owin.md

Add possible solution to make a code working.
Fixes #16698
Please review,
Thank you in advance

Fix error "Not all code paths return a value in lambda expression of type"

---

aspnetcore/blazor/components.md

Fixes #16887
Guessing this is a good compromise ... see my remarks at https://github.com/aspnet/AspNetCore.Docs/issues/16887#issuecomment-584776188.

Crosslink MDN event content for Blazor event args

---

aspnetcore/blazor/components.md

Update Blazor NotifierService example

---

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/wwwroot/exampleJsInterop.js
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/wwwroot/exampleJsInterop.js
aspnetcore/blazor/javascript-interop.md

Fixes #16627
Fixes #15517 
Fixes #16656
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1&branch=pr-en-us-16685#perform-large-data-transfers-in-blazor-server-apps)
* Condensed a bit from the source at https://gist.github.com/javiercn/f9c732b1d8e51634cbfd4cb0bce95b19.
* Minor code changes:
* `base64EncodedSegment` defined outside of the `try` (and `for`) due to use outside of the `try` below.
* Double quotes on JS function names ... compiler felt they were broken `char`s with the single quotes.
* I think `getFileSize` returns an `int` via `file.size` in JS code, not a `FileInfo`, so I changed that `InvokeAsync` return type to `int`.
* Then, the usual nits ... underscored fields ... spacing ... added …

Perform large data transfers in Blazor Server apps

---

aspnetcore/fundamentals/configuration/options.md

Fixes #16976
Thanks @ling1726! 🎸

Improve options validation guidance

---

aspnetcore/fundamentals/configuration/options.md

Nits followup to https://github.com/aspnet/AspNetCore.Docs/pull/16980 ...
* Small wording change.
* Duplicate the content for the 2.2 version.

Options followup update

---

aspnetcore/signalr/scale.md

Mentioning NCache as opensource thirdparty asp.net core signalR backplane
Added ncache-backplance image explaining the functionality , usage and benefits of ncache signalR

NCache SignalR backplane for asp.net core

---

aspnetcore/grpc/index.md

Fixes https://github.com/aspnet/AspNetCore.Docs/issues/16706

Fix gRPC typo

---

aspnetcore/blazor/advanced-scenarios.md
aspnetcore/blazor/event-handling.md
aspnetcore/blazor/globalization-localization.md
aspnetcore/blazor/integrate-components.md

You know ....... it helps quite a lot if after you commit locally **_YOU PUBLISH THE CHANGES!_** *Yikes!*

Split components followup

---

aspnetcore/client-side/spa/angular.md

Fixes https://github.com/aspnet/AspNetCore-ManualTests/issues/63.

Make warning an actual warning

---

aspnetcore/host-and-deploy/blazor/server.md

Fixes #16937
Thanks @3strategy! :rocket:

Surface enabling WebSockets for Blazor on IIS

---

aspnetcore/blazor/components.md

Fixes #17023
Thanks @c0g1t8! 🏎

Clarify static asset paths in Blazor apps

---

aspnetcore/blazor/components.md

Following https://github.com/aspnet/AspNetCore.Docs/pull/17024 and reacting to https://github.com/dotnet/aspnetcore/issues/19028#issuecomment-586625753.

Add cross-link to base path coverage

---

aspnetcore/blazor/advanced-scenarios.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/hosting-models.md

Fixes #12687
I considered placing this *IN* the *Hosting Models* topic, but we would be heading back down that road of loading advanced content into a topic that's more focused on overview concepts. I think the *Hosting Models* topic should remain light and accessible as devs read the first few Blazor topics.

Move Circuit Handler coverage

---

aspnetcore/blazor/advanced-scenarios.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/hosting-models.md
aspnetcore/fundamentals/middleware/request-response.md
aspnetcore/grpc/browser.md
aspnetcore/grpc/browser/sample/CORS_Startup.cs
aspnetcore/security/data-protection/compatibility/index.md
aspnetcore/web-api/index.md

Merge master to live 18 Feb

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Fixes #17060
Thanks @olabacker! 🎷

Fix misspelling

---

aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/Models/TodoItem.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Controllers/TodoItemsController.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Models/TodoContext.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Models/TodoItem.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Models/TodoItemDTO.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Program.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Startup.cs
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/TodoApiDTO.csproj
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/appsettings.Development.json
aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/appsettings.json

Fixes #15204
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&branch=pr-en-us-17074&tabs=visual-studio#prevent-over-posting)
cc @serpent5

Add DTO to prevent over-posting on API

---

aspnetcore/security/authentication/ws-federation.md
aspnetcore/security/authentication/ws-federation/samples/Startup21.cs
aspnetcore/security/authentication/ws-federation/samples/Startup31.cs
aspnetcore/security/authentication/ws-federation/samples/StartupNon21.cs
aspnetcore/security/authentication/ws-federation/samples/StartupNon31.cs

Identity Fed

---

aspnetcore/mvc/controllers/areas.md

Prepare areas for dual monikers

---

aspnetcore/security/authorization/razor-pages-authorization.md

Also tweaked wording before "than" -> "then" change.

Fixed "than" to "then"

---

aspnetcore/fundamentals/app-state.md

This PR adds monikers so the 3.1 version will be easy to diff.

App state prep

---

aspnetcore/blazor/components.md

Fixes #17109
[Internal Review Topic (links to Static Assets section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&branch=pr-en-us-17116#static-assets)

Clarify Blazor static asset location

---

aspnetcore/blazor/data-binding.md

Fixes #17040
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1&branch=pr-en-us-17108)
Thanks @curia-damiano! 🎷

Improve Blazor binding guidance

---

aspnetcore/security/authentication/windowsauth.md

Link AddNegotiate to API doc in WinAuth topic

---

aspnetcore/grpc/configuration.md

I'll revert if this doesn't work.

Test style for non-word-breaking code elements

---

aspnetcore/grpc/configuration.md

Test word-wrap with a span in gRPC topic

---

aspnetcore/grpc/configuration.md

Reverts dotnet/AspNetCore.Docs#17137

Revert "Test word-wrap with a span in gRPC topic"

---

aspnetcore/grpc/configuration.md

Reverts dotnet/AspNetCore.Docs#17138

Revert "Revert "Test word-wrap with a span in gRPC topic""

---

aspnetcore/fundamentals/localization.md
aspnetcore/web-api/jsonpatch/samples/2.2/JSON/copy.json

Merge to live 28 Feb

---

aspnetcore/tutorials/first-web-api/samples/3.0/TodoApiDTO/Controllers/TodoItemsController.cs

Fixes #17171.
Looking at this closer, I think `FindAsync` is a better option for both simplicity and consistency.

Use FindAsync in Overposting sample.

---

aspnetcore/security/authentication/index.md

Add links to HttpContext.[Verb]Async in authn overview

---

aspnetcore/fundamentals/app-state.md
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Startup3.cs
aspnetcore/host-and-deploy/web-farm.md
aspnetcore/toc.yml

Rename ToC entry for app state changes

---

aspnetcore/fundamentals/middleware/index.md

Fix line highlight for UseWhen sample

---

aspnetcore/tutorials/signalr-typescript-webpack.md

Fix Microsoft.TypeScript.MSBuild NuGet pkg link

---

aspnetcore/grpc/authn-and-authz.md

Fixes a typo at  the example of `Startup.Configure`
~~routes~~
endpoints

Fixes a typo at aspnetcore/grpc/authn-and-authz.md

---

aspnetcore/tutorials/first-mongo-app.md

Adjust code highlighting line numbers in web API / Mongo tutorial

---

aspnetcore/host-and-deploy/blazor/server.md

Updating to match nginx documentation (also linked in this page) which works. https://www.nginx.com/blog/websocket-nginx/

proxy_set_header Connection "Upgrade"

---

aspnetcore/host-and-deploy/blazor/server.md
aspnetcore/security/authentication/social/social-without-identity.md

Merge to live 10 March

---

aspnetcore/fundamentals/app-state.md
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Extensions/SessionExtensions.cs
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Startup4.cs

fIXES #17262
https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1&branch=pr-en-us-17269#configure-session-state

Add missing snippet to sesson doc

---

aspnetcore/fundamentals/app-state.md
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Extensions/SessionExtensions.cs
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Startup4.cs

* Add missing snippet to sesson doc
* Add missing snippet to sesson doc

Merge to live 2nd time on 10 March

---

aspnetcore/blazor/progressive-web-app.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/toc.yml

Fixes #17198
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&branch=pr-en-us-17261)
Not edited for style+grammar+UE. 🏃😅 Will return to do so asap.

Blazor WASM PWA support

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/get-started.md
aspnetcore/security/blazor/index.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

Fixes #17197
WRT the version of the template package: I'll update that package version here **_before_** shooting this in after release.

Blazor package renames

---

aspnetcore/host-and-deploy/blazor/configure-linker.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17196

Add preview2 Blazor linker changes

---

aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/BlazorSample.csproj
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/HTTPRequestTester.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Program.cs

cc: @mkArtakMSFT @danroth27 This takes care of the sample app, and the CSP topic doesn't require an update. I'll take this and the linker topic updates live now and call it a day. 🖖

Update Blazor WebAssembly sample to 3.2-Preview2

---

aspnetcore/fundamentals/index.md

Prep for #13877
[3.1](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&branch=pr-en-us-17272&tabs=linux)
[2.2](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&branch=pr-en-us-17272&tabs=linux)
[2.1](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.1&branch=pr-en-us-17272&tabs=linux)

fundamentals moniker prep for 3.0

---

aspnetcore/host-and-deploy/blazor/index.md
aspnetcore/host-and-deploy/blazor/webassembly.md

Fixes #17282
The IL Linker content was updated on **Add preview2 Blazor linker changes** #17236.
I'll take it live immediately after approval.

Update publish locations for Blazor apps

---

aspnetcore/fundamentals/index.md
aspnetcore/host-and-deploy/blazor/index.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/tutorials/build-your-first-blazor-app.md
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo5.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/ToDo8.razor
aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/Todo4.razor
aspnetcore/tutorials/first-mvc-app/adding-model.md

Merge to live March 13 or 14

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Fixes #17325
Follow-up to #17283.
Thanks @cornem! :rocket:

Additional Blazor WebAssembly path updates

---

aspnetcore/security/blazor/server.md

Update Blazor code example

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md

Addresses #17319
This will get the ball rolling with some obvious updates. I'll react further on the issue when we know more about why that app is failing.
Thanks @Alienroid 👽 ... keep me posted on that issue.

Additional Blazor WebAssembly security guidance

---

aspnetcore/blazor/components.md
aspnetcore/blazor/data-binding.md
aspnetcore/blazor/event-handling.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/security/authentication/index.md
aspnetcore/security/blazor/server.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md

Merge to live 3-16

---

aspnetcore/security/cors.md

Cors moniker  prep for 3.1

---

aspnetcore/security/blazor/webassembly/additional-scenarios.md

Addresses #17365
Per the fragments shown in :point_right: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs
Thanks @miri10134! :rocket:
@mkArtakMSFT GitHub is having some kind of problem here. When I try to call you for a review, the page throws a `Error: "element had interactions"` :boom: ... *whatever that means*. :smile:
**EDIT** *Ah!* … but Edge was able to do it. *Bad FF! Bad FF!*

Update Blazor RemoteAuthenticatorView fragments

---

aspnetcore/security/blazor/webassembly/index.md

Fixed a small typo (missing word)

---

aspnetcore/tutorials/build-your-first-blazor-app.md

Fixes #17389
Thanks @gomomohapi! 🌴

Fix an incorrect Blazor tutorial instruction

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md

Patch app settings file

---

aspnetcore/fundamentals/index.md

Fix typo (windows -> Windows)

---

aspnetcore/fundamentals/host/generic-host.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17373
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0&branch=pr-en-us-17386#disable-app-configuration-reload-on-change)

Explain how to disable app config reload in ASP.NET Core 5.0

---

aspnetcore/includes/blazor-security/index-page-authentication.md

Fixes #17418
Thanks @rdadkins! 🎸

Patch Blazor AuthenticationService.js file link

---

aspnetcore/blazor/call-dotnet-from-javascript.md
aspnetcore/blazor/common/samples/3.x/BlazorServerSample/JsInteropClasses/ExampleJsInterop.cs
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/JsInteropClasses/ExampleJsInterop.cs

Fixes #16682
Fixes #14972
Fixes #14879
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1&branch=pr-en-us-17075)
@shashikantx ... I really like the direction this is taking. Your example was an excellent basis for the multi-component scenario. I put you on here as an author. What URL do you want for the link? I can put your company, blog, etc. URL, or you can leave it pointed at your GH profile. You should review this first, then I'll call for an engineering review.

Enhance Blazor JS Interop coverage

---

aspnetcore/security/blazor/index.md

Fixes #16798
I think this is correct, but I haven't tested the first scenario (routeable components) myself. The second scenario (embedded) is obviously true.

Clarify RP conventions with Razor components

---

.ghal.rules.json
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/integrate-components.md
aspnetcore/blazor/state-management.md
aspnetcore/includes/built-in-TH.md
aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md

Fixes #17160
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-1.0&branch=pr-en-us-17343)

Component TH topic

---

aspnetcore/toc.yml

I missed this on **Component TH topic** #17343. The topic went up this morning ...... just need to give people a way to **_REACH IT!_** 🙈😄
I did manage to remember to get it into `aspnetcore/includes/built-in-TH.md`, so we're good there.
cc: @scottaddie

Add Component TH topic to TOC

---

aspnetcore/tutorials/first-mvc-app/validation.md

Fix typo (FireFox -> Firefox)

---

aspnetcore/migration/31-to-50.md

Uncomment the breaking changes section in the 5.0 migration doc.
[Internal review page](https://review.docs.microsoft.com/aspnet/core/migration/31-to-50?branch=pr-en-us-17445#review-breaking-changes)

Add breaking changes section to 5.0 migration doc

---

aspnetcore/migration/31-to-50.md

I think you meant it the other way right?

Switch + and - signs for PackageReference

---

aspnetcore/blazor/hosting-model-configuration.md

Fixes #17419
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1&branch=pr-en-us-17440)

Blazor WASM configuration

---

aspnetcore/blazor/.gitignore
aspnetcore/blazor/components.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/debug/launchSettings.json
aspnetcore/blazor/get-started.md
aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/fundamentals/dependency-injection.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md
aspnetcore/toc.yml
aspnetcore/tutorials/signalr-blazor-webassembly.md

Merge to live - 3/26

---

aspnetcore/blazor/templates.md

Fixes #17475
Nit fix ... just moving an list item to a better (logical) location.

Layout chnage in Blazor Templates topic

---

aspnetcore/blazor/data-binding.md

Fixes  #17479
Thanks @JonnyWaffles! 🎷

Repair broken Blazor example and fix typo

---

aspnetcore/fundamentals/routing.md
aspnetcore/fundamentals/routing/samples/3.x/RoutingSample/appsettings.Development.json
aspnetcore/fundamentals/routing/samples/3.x/RoutingSample/appsettings.json
aspnetcore/includes/dbg-route.md
aspnetcore/mvc/controllers/routing.md
aspnetcore/mvc/controllers/routing/samples/3.x/main/appsettings.Development.json

Add debug route info

---

aspnetcore/index.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1&branch=pr-en-us-17487)
Part 2 follow up to PR #17482 
In order to merge the new hub page that required a renaming of index.md and adding a new index.yml at the same time we had to take it in two steps.  This is the cleanup step to update a link the renamed index.md. Which as been reviewed with Scott Addie.

Update hub page to new overview link.

---

aspnetcore/includes/blazor-security/imports-file-hosted.md
aspnetcore/includes/blazor-security/imports-file-standalone.md
aspnetcore/includes/blazor-security/imports-hosted.razor
aspnetcore/includes/blazor-security/imports-standalone.razor
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Fixes  #17501
Thanks @IIStevowII! 🎷

Show imports file in WASM security topics

---

aspnetcore/blazor/handle-errors.md

Fixes #17485 
Thanks @Siphonophora! 🌴

Show Blazor error UI styles

---

aspnetcore/blazor/hosting-models.md

(AzureCXP) Fix typo

---

aspnetcore/web-api/handle-errors/samples/3.x/Startup.cs

[fix] Removed double using

---

aspnetcore/security/authentication/add-user-data.md

fixes https://github.com/dotnet/AspNetCore.Docs/issues/9244
@scottaddie @Rick-Anderson 
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-1.0&branch=pr-en-us-17394&tabs=visual-studio#add-claims-to-identity-using-iuserclaimsprincipalfactory)

Adding additional claims to Identity

---

aspnetcore/security/blazor/webassembly/index.md

See https://tools.ietf.org/html/rfc6749.
oAuth -> OAuth

Use standard casing for OAuth

---

aspnetcore/security/blazor/webassembly/index.md

@danroth27 ... found two more.
Searched the whole doc set ... these are the last two.

oAuth -> OAuth

---

aspnetcore/includes/net-core-prereqs-mac-5.0.md
aspnetcore/migration/31-to-50.md

[Internal review page](https://review.docs.microsoft.com/aspnet/core/migration/31-to-50?branch=pr-en-us-17591)

Update ASP.NET Core 3.1-to-5.0 migration doc for Preview 2 release

---

aspnetcore/fundamentals/app-state.md

Translator has reported possible content source issue.
Description> Adding missing parenthesis
Affected Line> 160

M48564 - Fixing Typo

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md

Fixes #17598
@IIStevowII ... see how this looks to you.

Blazor security guidance updates

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md

Nit patch on Blazor server guidance

---

aspnetcore/fundamentals/file-providers.md
aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/Pages/Index.cshtml.cs
aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/Startup.cs
aspnetcore/fundamentals/file-providers/samples/3.x/WatchConsole/Program.cs
aspnetcore/fundamentals/file-providers/samples/3.x/WatchConsole/TextFiles/quotes.txt
aspnetcore/fundamentals/file-providers/samples/3.x/WatchConsole/TextFiles/test.txt

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17547
Incorporates Acrolinx feedback and fixes other minor issues all throughout. Updated the *WatchConsole* sample app to demonstrate globbing.
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1&branch=pr-en-us-17600)

Improve file globbing explanations in File Providers doc

---

aspnetcore/performance/performance-best-practices.md

- Convert a comma to a period and add text for context
- Remove an unnecessary comma
- Add a comma

Correct punctuation and add text for clarity

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/target-aspnetcore.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/migration/22-to-30.md
aspnetcore/performance/performance-best-practices.md
aspnetcore/release-notes/aspnetcore-3.0.md

Correct the term IO to I/O

---

aspnetcore/blazor/globalization-localization.md

Fix Blazor culture code example

---

aspnetcore/security/data-protection/implementation/key-storage-format.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17672

Document the default key storage directory for macOS & Linux

---

aspnetcore/mvc/views/view-compilation.md

Razor compilation update

---

aspnetcore/signalr/javascript-client.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17403
[Internal review page](https://review.docs.microsoft.com/aspnet/core/signalr/javascript-client?branch=pr-en-us-17685#install-the-signalr-client-package)

Document non-npm approaches to installing SignalR JS client library

---

aspnetcore/data/ef-rp/intro/samples/cu/wwwroot/lib/jquery-validation/changelog.md

Description: Corrupted characters in article

L200052: Fixing corrupted characters

---

aspnetcore/blazor/get-started.md

Update Blazor Get Started VSC guidance

---

aspnetcore/blazor/get-started.md

cc: @danroth27 ... update is on this one.

Update Blazor Get Started

---

aspnetcore/blazor/get-started.md
aspnetcore/data/ef-rp/intro/samples/cu/wwwroot/lib/jquery-validation/changelog.md
aspnetcore/host-and-deploy/directory-structure.md

Master to live 2nd time on 9 April

---

aspnetcore/fundamentals/configuration/index.md

Clarify Hierarchal Key Configuration With Azure Key Vault

---

aspnetcore/security/cors.md

Merge to live again on 9 April

---

aspnetcore/blazor/hosting-model-configuration.md

Fixes #17567
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1&branch=pr-en-us-17584)
While we're at it here for environment, let's flesh out the configuration bit with the example from your blog post.

Surface additional Blazor environment content

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #17723
I have the day off ... so I turned this in. 😄😢😄😢 (I should be working on my Jeep right now. lol)
Thanks @carnadso! 🎸

Linux topics ForwardedHeaders middleware update

---

aspnetcore/signalr/configuration.md

Fixes #17753
Thanks @ EmpeRoar! :rocket:

Patch SignalR code example

---

aspnetcore/blazor/layouts/sample_snapshot/3.x/App2.razor

Follow-up to https://github.com/dotnet/AspNetCore.Docs/pull/17695.

Patch Blazor Layout topic example

---

aspnetcore/azure/devops/deploying-to-app-service.md
aspnetcore/security/key-vault-configuration.md

Fix invalid Azure CLI devlangs

---

aspnetcore/fundamentals/routing.md
aspnetcore/mvc/controllers/routing.md
aspnetcore/mvc/controllers/routing/samples/3.x/main/StartupSlugifyParamTransformer.cs
aspnetcore/razor-pages/razor-pages-conventions.md

Fixes #16956
@serpent5  please review and make suggestions I can commit.
I inspected all the builds and the include renders correctly.  You can see it live just above [Regular expressions in constraints](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#regular-expressions-in-constraints)

RegEx timeout warning

---

aspnetcore/fundamentals/host/generic-host.md

Fixes #17491
so next PR will have a clean diff.

Generic Host cleanup

---

aspnetcore/security/authentication/samples.md

Fix dead links on the documentation page

Fix dead links

---

aspnetcore/blazor/integrate-components.md

Fixes #17771
Thanks @besdsol! :rocket:
cc: @mkArtakMSFT ... just layout changes really. The ask is to introduce the component integration options clearly at the top of the topic. I'll go ahead and merge, but let me know if you want to do something different/better. [Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1&branch=pr-en-us-17793) :ear:

Enhance layout+content for component integration

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/index.md

Make ContentRoot and WebRoot coverage consistent

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/index.md
aspnetcore/security/authentication/social/microsoft-logins.md

Merge to live April 14

---

aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup2.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup3.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupAllowSubdomain.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupDefaultPolicy.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupEndPointBugTest.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupEndPt.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupTest2.cs
aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupTestMyPolicy.cs

Fix doubled-up UseAuthorization

---

aspnetcore/blazor/globalization-localization.md

Fixes #17808 
I'll open a new PR to activate the new content for P4 after this merges.

Revert P4 guidance

---

aspnetcore/mvc/views/overview.md

Remove [ViewData] example using @Model with a controller

---

aspnetcore/fundamentals/logging/index.md

https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1&branch=pr-en-us-17817

remove 80 monikers from logging

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

Fixup broken URL

---

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
aspnetcore/host-and-deploy/docker/index.md
aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md
aspnetcore/performance/memory.md

Fixes #17123
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-1.0&branch=pr-en-us-17606#gc-using-docker-and-small-containers)

GC with small containers

---

aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md

Fix broken bookmark

---

aspnetcore/grpc/browser.md

Compare Envoy vs Grpc.AspNetCore.Web

Add Envoy comparison

---

aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/BlazorSample.csproj
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CallWebAPI.razor
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Program.cs
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/_Imports.razor

Fixes #17830
cc: @mkArtakMSFT &ndash; Updated WASM common sample confirmed working. Merging as soon as the build completes.

Blazor WASM common sample update

---

aspnetcore/security/authorization/policies.md

Add some notes accessing controller action descriptor from auth handlers

---

aspnetcore/blazor/globalization-localization.md

Addresses #17808
cc: @pranavkm &ndash; I'll take that reversion live now and keep this one in my back pocket for the P4 release.

[Preview 4] Activate Blazor localization guidance

---

aspnetcore/index.yml

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1&branch=pr-en-us-17863)
Fixes #17556 
Update two links on Data-driven web apps section

Hub link update

---

aspnetcore/blazor/call-web-api.md
aspnetcore/toc.yml

[Preview 4] Update Blazor HttpClient coverage

---

aspnetcore/blazor/hosting-model-configuration.md

[Preview 4] Blazor WASM HostEnvironment

---

aspnetcore/fundamentals/environments/3.1sample/EnvironmentsSample/StartupMethodConventions.cs

code clean up

---

aspnetcore/includes/blazor-security/fetchdata-component.md

Fixes  #17760
Thanks @AlexSapple! :rocket:
cc: @mkArtakMSFT ... Surfacing the full set of directives for the `FetchData` component to make the namespaces clear. We already have a section to cover the package, and we also have a section to cover the addition to the *_Imports.razor* file.

Full directives for FetchData component INCLUDE

---

aspnetcore/introduction-to-aspnet-core.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17851
[Internal review page (ASP.NET Core 3.1+)](https://review.docs.microsoft.com/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1&branch=pr-en-us-17877)

Update the ASP.NET Core overview page for 3.x

---

aspnetcore/razor-pages/razor-pages-conventions.md

Fix reserved-routing-names xref from RP conventions

---

aspnetcore/security/cors.md

Add note re placement of UseCors

---

aspnetcore/web-api/advanced/formatting.md

Fix JsonOptions sample code

---

aspnetcore/blazor/templates.md

Provide commands to get Blazor template options

---

aspnetcore/includes/RP/model1b.md

Fix link to DataTypeAttribute

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

Fix link to sample on GitHub

---

aspnetcore/security/app-secrets.md

Preps for #17892
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&branch=pr-en-us-17923&tabs=windows)

remove moniker hell from Safe storage of app secrets

---

aspnetcore/tutorials/signalr-blazor-webassembly.md
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/BlazorSignalRApp.Client.csproj
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Pages/FetchData.razor
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Program.cs
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/_Imports.razor
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/BlazorSignalRApp.Server.csproj
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/Startup.cs

Fixes #17912
* Update tutorial steps
* Update sample app
Sample app confirmed working.

Blazor WASM-SignalR tutorial update

---

aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md

Blazor WebAssembly doesn't require server-side identity UI

---

aspnetcore/grpc/client.md

Preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.0&branch=pr-en-us-17946

Update gRPC client docs with trailer information

---

aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/fundamentals/logging/index.md

Fixes #17977
[Internal Review Topic (Fundamentals > Logging; links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.1&branch=pr-en-us-17980#create-logs-in-blazor)

Augment logging documentation for Blazor

---

aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/BlazorSample.csproj

Fixes #17972
Sample confirmed working.

[Preview 5] Blazor WASM common sample updates

---

aspnetcore/blazor/hosting-model-configuration.md

Fixes #17774
**HOLD FOR PREVIEW 5**
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1&branch=pr-en-us-17954)

[Preview 5] Blazor WASM configuration support

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/get-started.md
aspnetcore/host-and-deploy/blazor/webassembly.md
aspnetcore/includes/blazorwasm-3.2-template-article-notice.md
aspnetcore/includes/blazorwasm-3.2-template-section-notice.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/index.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md
aspnetcore/tutorials/signalr-blazor-webassembly.md

[Preview 5] Blazor Preview 5 updates

---

aspnetcore/includes/blazor-security/authentication-component.md
aspnetcore/includes/blazor-security/fetchdata-component.md
aspnetcore/includes/blazor-security/imports-hosted.razor
aspnetcore/includes/blazor-security/imports-standalone.razor
aspnetcore/includes/blazor-security/redirecttologin-component.md
aspnetcore/includes/blazor-security/troubleshoot.md
aspnetcore/includes/blazor-security/usermanager-signinmanager.md
aspnetcore/security/blazor/webassembly/additional-scenarios.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
aspnetcore/security/blazor/webassembly/index.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Fixes  #17973
Yeah, so there was no way this could've been accomplished yesterday. To update and verify all six test apps and make all of the doc changes required, it took **_seven hours_**. 😅
@mkArtakMSFT *Most* of this is going to be correct. 🤞🍀 I can mop up any lingering bits next week. I'd like to get this merged asap (now) given that it has all of the updated guidance for WASM Preview 5 security bits.

[Preview 5] Update Blazor WASM security topics

---

aspnetcore/includes/blazor-security/troubleshoot.md

Noticed there was some extraneous text in the header while looking at the docs.

Remove extraneous text in header

---

aspnetcore/includes/blazor-security/fetchdata-component.md
aspnetcore/includes/blazor-security/troubleshoot.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

[Preview 5] Blazor WASM security updates

---

aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/blazor/integrate-components.md

Fixes #18007
Thanks @NaserParhizkar! 🎸

Move and patch two Blazor sections

---

aspnetcore/tutorials/build-your-first-blazor-app/samples_snapshot/3.x/FetchData1_client.razor

Fixes #18019
Thanks @raisircl! :rocket:

Blazor Preview 4 tutorial update

---

aspnetcore/fundamentals/routing.md
aspnetcore/mvc/controllers/routing.md

Fix a couple of typos

---

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Views/Movies/IndexGet.cshtml

<input type="text" name="SearchString">
=>
<input type="text" name="SearchString" />

Add trailing slash for consistency

---

aspnetcore/fundamentals/configuration/index.md

Remove duplicated reference to the JSON provider

---

aspnetcore/mvc/models/validation.md

Fix link to DataAnnotations source

---

aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixed Constructor in CustomAccountFactory

---

aspnetcore/security/authentication/identity.md

Fixes https://github.com/dotnet/aspnetcore/issues/16979

Clarify username/email assumptions

---

aspnetcore/fundamentals/app-state.md
aspnetcore/fundamentals/app-state/samples/3.x/SessionSample/Startup4.cs

Fix line highlights for "Configure Session State"

---

aspnetcore/signalr/configuration.md
aspnetcore/signalr/security.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/15636
And adds a 5.0 setting that was commented out.

Update SignalR CORS for 5.0

---

aspnetcore/includes/benefits.md
aspnetcore/introduction-to-aspnet-core.md

Don't merge before dotnet/docs#18143 is live.

Update bookmark in dotnet repo

---

aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupRemove.cs

Fixes #8223
Fixes #18060
Fixes dotnet/Scaffolding#1275
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&branch=pr-en-us-18061&tabs=visual-studio)

remove dupicate Identity

---

aspnetcore/grpc/comparison.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/18083

Update gRPC comparison.md

---

aspnetcore/blazor/routing.md

"@implement IDisposable" is incorrect. It should be "@implements IDisposable".  Notice the "s".

Fix typo "@implement" => "@implements"

---

aspnetcore/security/blazor/server/index.md

Fixes #18105
Thanks @chriswhitts! ... and this won't be the last of it. There will probably be additional (detailed) guidance for Azure AD/B2C and edge case scenarios as we go forward.

Call out security config for Blazor Server apps

---

aspnetcore/fundamentals/routing.md

links to custom route constraints

---

aspnetcore/security/blazor/server/threat-mitigation.md

Fixes #18142
Thanks @vvgonline! :rocket:

Remove extra character

---

aspnetcore/blazor/get-started.md
aspnetcore/blazor/get-started/samples_snapshot/3.x/Counter1.razor
aspnetcore/blazor/get-started/samples_snapshot/3.x/Counter2.razor

Fixes #18148
kk ... it's ready now. It was inconsistent *even between the existing text and code*.

Match doc example to Blazor template code

---

aspnetcore/data/ef-mvc/update-related-data.md

Fix a teeny tiny typo

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md

Fixed AzureAdB2C appsetting

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Blazor WASM on Azure App Service for Linux

---

aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #17795
* Most of the cross-links in this node were addressed on prior issues/PRs.
* This PR adds namespaces to code examples.
Thanks @luisbecerril-ips! :rocket:

Add namespaces to Blazor Additional Scenarios topic

---

aspnetcore/blazor/components.md
aspnetcore/mvc/views/razor.md

[Internal Review - views/razor.md](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1&branch=pr-en-us-18213)
[Internal Review - revert of blazor/components.md](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1&branch=pr-en-us-18213)
fixes #18212
- Changing "Razor" to "razor" in the title metadata of https://github.com/dotnet/AspNetCore.Docs/blob/live/aspnetcore/mvc/views/razor.md
- Reverting a recent change of "razor" in the title meta data of  aspnetcore/blazor/components.md since it has turned out not to be the source of the translation issue, views/razor.md was instead, even though the issue appears in the translation of the Blazor topic.
Related to #18076

No-loc fix Razor translation source doc

---

aspnetcore/fundamentals/logging/index.md

Add reference to custom logging blog post

---

aspnetcore/mvc/models/validation.md

Add requirement for jQuery Validation's additional-methods

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #9078
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-18220#recommended-patterns-for-multi-tenancy-in-di)

recommended patterns for multi-tenancy in DI

---

aspnetcore/fundamentals/localization.md

Fixes #17720 and [Internal bug](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1702030)

CSAT title: Globalization and localization in ASP.NET Core

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/logging/index/samples/3.x/MyMain/Program.cs

Fix broken links and some code highlights in Logging

---

aspnetcore/blazor/components.md

Fixes #17371 
Lingo is approved on the issue.
Thanks @SQL-MisterMagoo 🍻 and @mrpmorris 🍻.

Blazor sync context updates

---

aspnetcore/blazor/components.md

Fixes #17148
Minor wording update.
Thanks @mrlife 🌴!

Component namespaces for custom folders

---

aspnetcore/security/data-protection/implementation/key-storage-providers.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/17759

Add Identity(1,1) to data protection doc

---

aspnetcore/host-and-deploy/docker/building-net-docker-images.md

Explain the Dockerfile distinct layers approach

---

aspnetcore/signalr/hubcontext.md

hubcontext.md: updates examples

---

aspnetcore/performance/caching/middleware.md

Fix custom middleware limitations

---

aspnetcore/performance/caching/middleware.md

Completes #18177.
We forgot to add the text to the netcore 3.x section.
This PR updates that section, and fixes a spelling mistake.

add to 3.x section , fix spelling

---

aspnetcore/blazor/components.md
aspnetcore/blazor/event-handling.md
aspnetcore/blazor/handle-errors.md
aspnetcore/blazor/layouts.md
aspnetcore/blazor/state-management.md
aspnetcore/mvc/views/razor.md

Fixes #17119
* Better cross-linking in the *Components* topic, focused on directives and directive attributes.
* Add a definition for "directive attributes" in the *Razor syntax* topic.
* Call out Razor early in a section and suggest reading the *Razor syntax* topic if not familiar with the language.
* Drop em dashes (for localization).
More updates in this vein coming on a big UE pass post 3.2 GA.

Blazor UE improvements

---

aspnetcore/test/middleware.md

Fixes #18259
Fixes #18255
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-1.0&branch=pr-en-us-18283#testserver-limitations)

Testserver limitations

---

aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Program.cs

Given this example is for .net core 3.x and C# 8 is supported, we're taking advantage of the simplified version of the using statement.

Simplify the using statement

---

aspnetcore/test/integration-tests.md

Fixes #18248
Thanks @AnthonyMastrean :rocket:
We'll need to hear from engineering on this. Although I tested 2.x, and these patterns seem to work, it's been a long time since I've worked this topic or with 2.x. I may have created a 💩. They'll let us know shortly.

Integration testing 2.x set env update

---

aspnetcore/razor-pages/index.md

Minor update for instructions on how to create a project with Visual Studio for Mac in the Introduction to Razor Pages doc.

minor update for vsmac content in Intro Razor Pages doc

---

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

Add xref to Web SDK in VS Publish Profiles

---

aspnetcore/blazor/lifecycle.md
aspnetcore/host-and-deploy/blazor/configure-linker.md
aspnetcore/performance/blazor/webassembly-best-practices.md
aspnetcore/toc.yml

Fixes #18277
Addresses #18218
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-2.1&branch=pr-en-us-18288)
Scott ... if you don't have 🕐 to review the whole thing, take a look at the TOC/UID bits. I avoid re-using the word "performance" in the UID/filename ... no need given that it's in the path.

Blazor WASM perf best practices topic

---

aspnetcore/blazor/forms-validation.md

Cross-link property binding in Blazor forms topic

---

aspnetcore/security/authentication/identity-api-authorization.md

Patch ... 'Azure Websites' to 'Azure App Service'.

Change 'Azure Websites' to 'Azure App Service'

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Blazor ext in service worker assets manifest

---

aspnetcore/includes/blazor-security/azure-scope.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Blazor WASM security NOTE update

---

aspnetcore/migration/22-to-30.md
aspnetcore/tutorials/first-mongo-app.md
aspnetcore/tutorials/first-mongo-app/samples/3.x/SampleApp/readme.md
aspnetcore/web-api/jsonpatch.md

Addresses #18369
cc: @JasonCard

Delocalize package name

---

aspnetcore/fundamentals/middleware/write.md

Fixes #17730.
I wouldn't typically include a [!NOTE] like this, but I think it's important to call out that this entire topic assumes convention-based middleware.

Link from basic middleware to middleware extensibility

---

aspnetcore/grpc/aspnetcore.md
aspnetcore/grpc/basics.md
aspnetcore/grpc/client.md
aspnetcore/grpc/index.md
aspnetcore/includes/gRPCazure.md

gRPC not supported on Azure/IIS

---

aspnetcore/fundamentals/logging/index.md

Fixes #18315
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0&branch=pr-en-us-18316#set-log-level-by-command-line-environment-variables-and-other-configuration)
Public review:
* Go to [this DropBox link](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
* In the upper right, select Download -> Direct download
* Click on HTML files.

Env sample for logging

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md

Fixes #18386
Thanks @marshallr12! :rocket:

Strike instruction in Blazor WASM security AAD topics

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md

Fixes #18389
Thanks again @marshallr12! 🌴

Blazor WASM security: Distinguish Kestrel & IIS ports

---

aspnetcore/mvc/models/file-uploads.md

Fixes #18423
Thanks @dwalleck! :rocket:

Update code example in File Upload topic

---

aspnetcore/tutorials/razor-pages/validation.md

Change of misspelling

---

aspnetcore/introduction-to-aspnet-core.md

Found &dagger; element in the tutorial for type of app table. Which is not required for this documentation.

Removed dagger Element

---

aspnetcore/introduction-to-aspnet-core.md

Reverts dotnet/AspNetCore.Docs#18441

Revert "Removed dagger Element"

---

aspnetcore/blazor/call-web-api.md

response.Content requires a capital C.

Incorrect capitalisation

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CallWebAPI.razor

Fixes #18464
Thanks @TNCodes! 🎷
I'll address this topic further on the two efforts that I mentioned: topic UE passes and the common sample app update. I'm still ⛏️ *digging myself out* ⛏️ on a pile of issues, and I'll get to it asap.

Fix Blazor code examples

---

aspnetcore/blazor/hosting-model-configuration.md

Just a small markdown correction

Format fix for IsEnvironment

---

aspnetcore/includes/IdentityServer4.md
aspnetcore/security/index.md

Minor improvements to Authentication docs

---

aspnetcore/migration/31-to-50.md

[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-1.0&branch=pr-en-us-18489&tabs=visual-studio)

Update ASP.NET Core 5.0 migration guide for Preview 4

---

aspnetcore/mvc/controllers/routing.md
aspnetcore/mvc/controllers/routing/samples/3.x/main/Controllers/HomeController.cs

Fix a couple of small MVC routing issues

---

aspnetcore/blazor/data-binding.md

Fixes #18500
Thanks @send2vinnie! :rocket:

Patch and update Blazor binding remark

---

aspnetcore/tutorials/signalr-blazor-webassembly.md
aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/Startup.cs

Fixes #18453
[Internal Review Topic (links to *Add services and an endpoint for the SignalR hub* section)](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&branch=pr-en-us-18520#add-services-and-an-endpoint-for-the-signalr-hub)
Thanks @pmathbliss! :rocket:

Show middleware config in Blazor-SignalR tutorial

---

aspnetcore/blazor/forms-validation.md

Fixes #14869
Thanks @donhuvy! :rocket:

Add a Troubleshoot section to Blazor forms topic

---

aspnetcore/migration/claimsprincipal-current.md

Thread.CurrentPrincipal is no longer thread-static

---

aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #18527
Thanks @mattruma! :rocket:
* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.remoteauthenticatorviewcore-1.onloginsucceeded?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_WebAssembly_Authentication_RemoteAuthenticatorViewCore_1_OnLogInSucceeded
* https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L81

Fix typo in Blazor code example

---

aspnetcore/blazor/debug.md

Fixes #18531
Thanks @Assassinbeast! :rocket:

'inspectUri' clarification in Blazor debug topic

---

aspnetcore/blazor/call-web-api.md

Fixes #18541
Thanks @mattruma! 🌴

Call out the package for IHttpClientFactory

---

aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Pages/Index.razor

https://github.com/dotnet/aspnetcore/issues/20932

Dispose SignalR connection in sample

---

aspnetcore/blazor/hosting-model-configuration.md
aspnetcore/fundamentals/logging/index.md

Fixes  #18444
[Internal Review Topic (links to the *Logging configuration* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1&branch=pr-en-us-18530#logging-configuration)
We had the bones for this come in on an earlier issue, so I enhance and crosslink here.

Enhance and crosslink Blazor WASM logging config

---

aspnetcore/host-and-deploy/blazor/webassembly.md

Add Gzip and prop to disable compression

---

aspnetcore/includes/net-core-prereqs-vsc-3.1.md

Link to VSC on macOS docs

---

aspnetcore/blazor/debug.md

Fixes #18554
Thanks @dselvan! :rocket:

Surface cert trust in Blazor debug topic

---

aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md
aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md

Addresses #18560
Yes, @bestcoder, I found a few more spots with similar lingo to update. *Thanks again!* 🎷

Improve Blazor WASM security setup steps

---

aspnetcore/host-and-deploy/linux-nginx/nginx.conf

Fixes #18566
Thanks @samgithub! :rocket:

Linux topic example consistency

---

aspnetcore/fundamentals/logging/index.md

Remove link to custom logger provider blog

---

aspnetcore/blazor/get-started.md

Fixes #18589
Thanks akunaatrium! :rocket:

Update dotnet command

---

aspnetcore/blazor/get-started.md

Fixes #18593
Thanks @Youssef1313! :rocket:

Mirror VSC instruction for CLI steps

---

aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/webassembly/index.md

Fixes #18602 
* Move a section that pertains solely to WASM to the WASM security overview topic.
* Call out refresh tokens in client-side WASM apps.
Thanks @TheMagnificent11! :rocket:

Blazor WASM security update

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes #18605
Thanks again @akempe! :rocket:

Drop cross-link to engineering issue

---

aspnetcore/toc.yml

Add microservices Learn module link to ToC

---

aspnetcore/fundamentals/localization.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/18608

Fix unreadable sentence in localization doc

---

aspnetcore/fundamentals/localization.md

Fix unreadable sentence in localization doc (#18611)

---

aspnetcore/security/blazor/webassembly/additional-scenarios.md

Fixes #18422
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-18616)
* I'm going to make the examples here generic (i.e., move away from the weather forecast case).
* The custom class is described first, and I add a "(*Recommended*)" text element.
:eyes: Watch out for *Rex Code Smells!*:tm: 💩👃😵

Add WASM custom auth handler example

---

aspnetcore/security/authentication/identity.md

- Updated links to the current branches of source code: 2.1 & 3.1
- Removed leftovers from previous versions of the document that
mentioned Controllers
- Removed mentions of DI that seemed out of place

Updates to Identity.md

---

aspnetcore/migration/Logging-nonaspnetcore.md
aspnetcore/security/authentication/identity.md
aspnetcore/security/enforcing-ssl.md

Merge to live

---

aspnetcore/blazor/hosting-model-configuration.md

Add end parentheses to the `AddOidcAuthentication` call

Missing end parentheses in Authentication sample

---

aspnetcore/blazor/event-handling.md

Fixes #17093
Thanks @bvirkler! :rocket:

Clarify Blazor loop vars in lambdas

---

aspnetcore/host-and-deploy/blazor/server.md

Fixes #14323
Thanks @rpc-scandinavia! :rocket: ... sorry for the delay. I've been 🏃 for months. I'm finally getting caught up on issues during this post-3.2-release quiet period.

Blazor Server with Apache on Linux

---

aspnetcore/blazor/globalization-localization.md

Fixes #15371
Thanks @PaloMraz! :rocket: ... sorry for the 🐌 *long* 🐌 delay in getting to this. I'm just now having the time to ⛏️ dig out from a ⛰️ of issues.
Artak, plz check the issue to see if there's anything else there that we need to do here. I think this covers the two main asks.

Enhance Blazor loc coverage

---

aspnetcore/includes/blazor-security/troubleshoot.md

Fixes #18669
:star: *Works like a charm!* ⭐
Thanks @captainsafia ... this was worked out from our discussion on the issue with debugging WASM.

Add Edge to Blazor WASM troubleshooting advice

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/includes/blazor-security/troubleshoot.md
aspnetcore/includes/scaffold-identity/hsts.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg.md
aspnetcore/security/authentication/certauth.md
aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupBlazor.cs
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupMVC.cs
aspnetcore/security/authentication/scaffold-identity/3.1sample/StartupRP.cs
aspnetcore/security/blazor/index.md
aspnetcore/security/blazor/server/index.md

Update live with master

---

aspnetcore/tutorials/build-your-first-blazor-app.md

The line after list all the things to be done in this tutorial reads. 
At the end of this tutorial, you'll have a working chat app.
So, I changed the "chat app" to "todo list app" as that is the aim of the tutorial

there is a typo "chat app"

---

aspnetcore/signalr/diagnostics.md

Inspired by https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1#metrics

Add SignalR counters

---

aspnetcore/fundamentals/middleware/request-response.md

Fix a couple of broken links

---

aspnetcore/includes/RP/model2.md

Move install of NuGet packages

---

aspnetcore/data/ef-mvc/complex-data-model.md
aspnetcore/data/ef-rp/complex-data-model.md
aspnetcore/includes/mvc-intro/validation.md
aspnetcore/tutorials/first-mvc-app-xplat/start-mvc/sample/MvcMovie/Models/Movie.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie21/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie21/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/first-mvc-app/validation.md
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie21/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie21/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Models/MovieDateRatingDAmult.cs

Fixes #18222.
This ended up affecting quite a few spots across the repo.
cc @scottaddie

Fix RegEx for Genre across the repo

---

aspnetcore/tutorials/first-mvc-app/new-field.md

At the end of the page, the following is mentioned:
> Add the Rating field to the Edit, Details, and Delete view templates.
However, we are already instructed to do so earlier in the tutorial:
> Update the remaining templates.
Also at the end of the page:
> Update the binding in the edit action method of the MoviesController.
Again, we are already instructed to do so earlier in the tutorial:
> update the [Bind] attribute for both the Create and Edit action methods to include the Rating property

Remove superfluous instructions

---

aspnetcore/signalr/authn-and-authz.md

cc @davidfowl 
Maybe we should check all the browsers listed in https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#javascript-client and put their status here?

Cleanup SignalR Windows Auth with browsers

---

aspnetcore/security/authentication/accconfirm.md

The SendGrid account may require

corrected spelling in the word

---

aspnetcore/blazor/components.md

Fixes  #18721
Approved by https://github.com/dotnet/AspNetCore.Docs/issues/18721#issuecomment-642819645.
Thanks @galaldev! :rocket:

Change Blazor example service registration

---

aspnetcore/security/authentication/cookie.md

RedirectUri

---

aspnetcore/includes/5.0-SDK.md
aspnetcore/includes/net-core-prereqs-mac-5.0.md
aspnetcore/includes/net-core-prereqs-vs-5.0.md
aspnetcore/migration/31-to-50.md

[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-1.0&branch=pr-en-us-18765)

Update migration guide for 5.0 Preview 5

---

aspnetcore/fundamentals/http-requests.md

Minor follow-up tweaks to HttpClient changes
