docs/getting-started/installing-on-mac.rst

It can be a little confusing if you had "aspnet/k" tapped and try to tap "aspnet/dnx" since they both provide the `kvm` formula. I added a small section to help with that situation.
(see https://github.com/aspnet/dnvm/issues/242)

Add some help for users who had old brew tap

---

docs/conceptual-overview/understanding-aspnet5-apps.rst

1. Removed an supposed to be unwanted & after config.json
2. Fixed an unwanted formatting where it appears that trying to have a link inside a code block causes a non-wrapping code paragraph, which looks like this: 
3. Added syntax highlighting around ConfigureServices() as it's clearly referencing a specific code method to make it more obvious.

Conceptual: Fixed IConfiguration formatting and removed unwanted '&'

---

docs/conceptual-overview/understanding-aspnet5-apps.rst

As per the [announcement](https://github.com/aspnet/Announcements/issues/18), `sources` has been renamed to `projects`. `sources` will be removed in beta5.

Update global.config section sources to projects

---

docs/fundamentals/application-insights.rst

There was a space between opening `` and "services.AddApplicationInsightsTelemetry(Configuration);" which resulted in `` pair being displayed and special formatting being ignored.

Correct typo which damages display

---

docs/dnx/console.rst

Fixed a missing space on article dnx\console that prevented rST to properly display the note block

Fixed missing space in `.. note` block to properly display it

---

docs/security/sociallogins.rst

Other notes:
1. There is a mix of "Create" and "Creating" (+ "Running" etc.) for the section titles, which could maybe be made more consistent.
2. "Add your Site URL" is mentioned twice. The second time "Add" is also incorrectly capitalized.
3. You might want to mention hitting "Save Changes" on FB.
4. "Set the Facebook AppSecret" shows using the AppId again – maybe use placeholder text like YOUR_APP_SECRET_HERE.

Corrections to sociallogins.rst

---

aspnet/index.rst

To be able to link to the core ASP.NET 5 documentation on RTD via
intersphinx we need to a label in the index.rst file. Added that.
/cc @danroth27

Adding index label to aspnet index.rst

---

CONTRIBUTING.md

The docs state that `make` can be started from the `\docs` directory, but make files only exist in the sub dirs `\aspnet` and `\mvc` (with thanks to @dpaquette for helping out this Python/Sphinx rookie).

Clarify the getting started - incorrect path

---

aspnet/getting-started/installing-on-mac.rst

We're removing the Homebrew formula since it messes with `dnvm update-self`. Given that, here are the updated instructions for Mac.
/cc @glennc @danroth27 @ardalis

Update Mac Instructions for Beta6

---

aspnet/getting-started/installing-on-linux.rst

The case of the `NuGet.Config` file in the Linux instructions is incorrect, and Linux file systems are generally case-sensitive, so it doesn't work as cased in the instructions.
/cc @danroth27 @glennc

Update casing of NuGet.Config

---

aspnet/conceptual-overview/dotnetcore.rst

Link reference for .NET Core 5 on dotnetfoundation.org was broken - fixed URL reference.

Link reference for .NET Core 5 on DNF fixed

---

mvc/tutorials/mvc-with-entity-framework.rst

"Entity Framework 7 Code" doesn't make sense. Should be either "Entity Framework 7 Code _First_" or just "Entity Framework 7".
Prefer just "Entity Framework 7", as the phrase "Code First" only makes sense to people who already know EF.

Title change

---

mvc/controllers/dependency-injection.rst

This should hopefully fix the build, and remove a stub icon reference that doesn't belong there.

Fixing Stub Icon Issue in DI for Controllers

---

aspnet/security/authentication/cookie.rst

I know it's minor, but this little typo initially threw me for a small loop.
If you want to provide your **on** login screens   => If you want to provide your **own** login screens

Fix typo in CookieAuthentication article

---

aspnet/index.rst

I just updated the title in the docs to the new "aspnet core".
+Info: https://github.com/aspnet/Docs/pull/938

Rename aspnet5 to aspnet core

---

aspnet/conceptual-overview/aspnet.rst

Added line containing static 'Main' method which is now needed as a suitable entry point
This is based on the newest ASP.NET 5 Visual Studio 2015 project templates for Empty, Web API and Web Application options

Updated ASP.NET 5 application definition

---

aspnet/tutorials/nano-server.rst

The previous statement copied the application to the destination in an incorrect way and so the destination wouldn't contain the approot folder.

Fix statement to copy application to nano server

---

aspnet/security/authorization/views.rst

The wrong method name `AuthorizeSync` is specified in the code explanation, instead of `AuthorizeAsync`.

Fixed typo.

---

aspnet/security/authorization/limitingidentitybyscheme.rst

Probably a typo from copy and pasting from other example. We are already in the context of the lambda.

Fix a typo in "Limiting identity by scheme" page

---

aspnet/tutorials/first-web-api.rst

The old link points to a 404 page

Fix "First web API" sample app url

---

aspnet/mvc/models/validation.rst

As discussed in https://github.com/aspnet/Mvc/issues/4475, validation `span` tag helpers shouldn't be self closed.
Updating the code snippets in Model Validation docs to avoid confusion.

Fix validation tag helpers Span tags

---

aspnet/client-side/yeoman.rst

Previously, the command line was escaped twice: both with spaces and <code>\`\`</code>, which meant that the <code>\`\`</code> showed.
This change fixes that.

Removed `` in Yeoman

---

aspnet/security/authentication/accconfirm.rst

Fixed file name to the correct user secrets file, not project.json
@Rick-Anderson @blowdart @rachelappel

project => secrets.json

---

aspnet/publishing/iis.rst

Using the abbreviated table formatting in the update, it was nothing but :cry: tears :cry: ... https://docs.asp.net/en/latest/publishing/iis.html#application-configuration
This PR fixes the broken table format.

Fix broken table in Publishing to IIS

---

.travis.yml

@danroth27  We have a similar setup in all of our repos to reduce the amount of churn on travis and I'm wondering if we should do the same for the Docs repo. The idea is to restrict building branches to PRs, main branches (master, release and dev) and branches specifically tagged with <alias>/ci-<branch name>.

Limit the branches that build on travis

---

aspnet/tutorials/dotnet-watch.rst
aspnet/tutorials/dotnet-watch/sample/WebApp/Controllers/MathController.cs
aspnet/tutorials/dotnet-watch/sample/WebApp/Program.cs
aspnet/tutorials/dotnet-watch/sample/WebApp/Startup.cs
aspnet/tutorials/dotnet-watch/sample/WebApp/project.json
aspnet/tutorials/dotnet-watch/sample/WebApp/web.config
aspnet/tutorials/dotnet-watch/sample/WebAppTests/CalculatorTests.cs
aspnet/tutorials/dotnet-watch/sample/WebAppTests/project.json
aspnet/tutorials/index.rst
common/authors.txt

Fixes https://github.com/aspnet/Docs/issues/696
A tutorial on using `dotnet watch`
Please review @Rick-Anderson @rachelappel @danroth27

dotnet-watch tutorial

---

aspnet/tutorials/first-mvc-app/start-mvc/sample/src/MvcMovie/Controllers/HelloWorldController.cs

Fixed #1560.
Uses the `ID` parameter instead of the incorrect `numTimes` value.

Fix non-compiling code sample

---

aspnet/tutorials/nano-server.rst

@shirhatti The following text was taken from https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/Documentation/known-issues.md#running-net-core-cli-on-nano-server
@Rick-Anderson

Document .Net CLI issue workaround on Nano

---

aspnet/fundamentals/startup.rst

See https://docs.asp.net/en/latest/migration/rc1-to-rtm.html#hosting-service-changes

IApplicationEnvironment is now longer available in Startup

---

aspnet/security/authorization/limitingidentitybyscheme.rst

Replace lambda argument to `app.UseCookieAuthentication()` with instantiation of a `new CookieAuthenticationOptions()` object.

Fix incorrect UseCookieAuthentication code snippet

---

aspnet/fundamentals/startup.rst
aspnet/tutorials/first-mvc-app/validation.rst

The line of code to configure `AppSettings` is removed in the commit [Updating WebApplication1 sample to beta5](https://github.com/aspnet/Docs/commit/8080f1b325413c39e011a8623d4a80ae0d623120#diff-931fae37c82f38008d5a4cde9c977604L52)

the sample does not configure AppSettings any more

---

aspnet/mvc/views/partial.rst

The HtmlHelperPartialExtensions methods are named 'Partial' and 'PartialAsync', not 'Render' and 'RenderAsync'

fix HtmlHelperPartialExtensions method name references

---

aspnet/fundamentals/configuration.rst
aspnet/fundamentals/configuration/sample/src/UsingOptions/Startup.cs

The doc states that:
> the value of Option1 is overridden by the configured delegate with the value “value1_from_action”
In order to make this statement true, the configurd delegate should be put last.
This issue is introducted by PR #1331

fix the issue that the code doesn't do as stated in the doc

---

aspnet/publishing/iis.rst

The application is required to inject the IISIntegration module. This was not obvious to me.
Added the error to the troubleshooting guide.
@GuardRex PTAL

Adding reference to IISIntegration in the IIS docs

---

aspnet/publishing/iis.rst

This adds the "`.UseUrls()` after `.UseIISIntegration()`" condition to the new common error for "IISIntegration middleware not implemented"
I also figured out in yesterday's PR that it's best (shorter) to just roll the portable and self-contained language of an Application Log error into one line and just designate which part of the error language pertains to each app type.

Update common error

---

aspnet/migration/http-modules.rst

@mperdeck Please review, thank you!
I think the intended content for 
> HTTP modules are typically added to the request pipeline using Web.config
is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.webServer>
<modules>
<add name="MyModule" type="MyApp.Modules.MyModule"/>
</modules>
</system.webServer>
</configuration>
```
and the intended content for
> Configuring an HTTP handler is done in Web.config and looks something like this
is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.webServer>
<handlers>
<add name="MyHandler" verb="*" path="*.report" type="MyApp.HttpHandlers.MyHandler" resourceType="Unspecified" preCondition="integratedMode"/>
</handlers>
</system.webServer>
</configuration>
```

correct the code line numbers in http-modules.rst

---

aspnet/getting-started.rst

Default dotnet new on Mac has ConsoleApplication as namespace. This PR highlights the `Program.cs` namespace line as a change. Resolves Issue #1652

Added namespace change line emphasis to docs.

---

aspnet/publishing/iis.rst

The modifications that are needed for the `tools` and `scripts` sections of *project.json* no longer has a stray `}` to make it easier for folks who are copy and pasting.

Fixing typo in project.json settings

---

aspnet/fundamentals/servers.rst

Eventually we will have a complete discussion of Kestrel and ASP.NET hosting (#929), but adding a warning to the Servers doc for now.

Clarify guidance for using Kestrel

---

aspnet/fundamentals/logging.rst

Hello, I just noticed that the documentation for available providers is still pre-RTM:
> The ASP.NET Core team is still working with third party logging providers to publish support for this logging model. Once these ship, we will include links to them here.
I have replaced this note with an alphabetized copy of the list found in: https://github.com/aspnet/Logging#providers
Cheers,
Nick

Update note on available logging providers

---

aspnet/intro.rst

In order to use a middleware it is important to take a dependency on a specific and dedicated NuGet package and then use the extension method against IApplicationBuilder interface.
I think it is important piece and was missing.
Lets include this change.

middleware fix

---

aspnet/fundamentals/routing.rst

MapRoute was listed twice and MapDelete wasn't listed

fix MapDelete typo in method listing

---

aspnet/fundamentals/routing.rst

"present during during URL generation" -> "present during URL generation"

Removed duplicate "during"

---

aspnet/publishing/iis.rst

A dev on Slack said that "application’s assets" didn't translate well into their language. This change modifies the expression and includes a link to the Directory Structure doc.

Minor language update

---

common/authors.txt

This PR simply replaces my HTTP author link with the HTTPS version.

Convert Scott Addie author link from HTTP to HTTPS

---

aspnet/migration/webapi.rst

This PR removes an extra colon in the "Sections" heading of the Web API migration doc.

Remove extra colon from Sections heading in Web API doc

---

aspnet/security/authentication/accconfirm/sample/WebApplication3/src/WebApplication3/Services/MessageServices.cs

`new SendGrid.Web(credentials)` can throw an exception, but it can't evaluate to null.

Removed unreachable code for sending with SendGrid

---

common/_templates/layout.html

Fixes #1822 
Provide appropriate headers so that browsers/RSSreaders can find the ASP.NET Core docs RSS feed #1822

Add rss link to layout template 

---

aspnet/publishing/linuxproduction.rst

It is necessary to set the `HOME` environment variable when running a dotnet
core site through supervisor. If it is not set, the following exception is
thrown:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
at System.IO.Path.Combine(String path1, String path2, String path3)
at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
at …
```

Set HOME environment variable

---

aspnet/publishing/linuxproduction.rst

When running `dotnet` two processes are started: one started by the user,
and one spawned as a child process. Example after running `dotnet run -p
/var/www/HelloWorld/src/HelloWorld`:
```
root     27452  0.5  5.6 3070112 57064 ?       SLl  16:50   0:01 /usr/bin/dotnet run -p /var/www/HelloWorld/src/HelloWorld
root     27470  0.1  3.5 7014752 36028 ?       SLl  16:50   0:00 /usr/share/dotnet/dotnet exec --additionalprobingpath /var/www/.nuget/packages /var/www/HelloWorld/src/HelloWorld/bin/Debug/netcoreapp1.0/HelloWorld.dll
```
When starting a site with supervisor, the same thing happens. When trying to
stop a site through `supervisorctl` with (in this case) `stop helloworld` the
original process is stopped (the one with id `27452`) but that process doesn't
pass on the `SIGINT` to its …

Stop and kill as group

---

aspnet/fundamentals/dependency-injection.rst

More obvious when you look at the doc itself - two spaces are needed after the "*\" in order to get a space between the words "Service" and "extension".

missing space in text

---

aspnet/tutorials/web-api-help-pages-using-swagger.rst

Using the index.html at the current to customize UI is not working. The current swagger ui for .net core should be 
https://github.com/domaindrivendev/Ahoy/tree/master/test/WebSites/CustomizedUi/wwwroot/swagger/ui

Outdated git repo link for swagger ui customization

---

aspnet/fundamentals/logging.rst

The link to the elmah.io package pointed to the old package from before the rename from framework.logging to extensions.logging.

Fixed link to elmah.io

---

aspnet/migration/identity.rst

Updated references in Identity Migration to use the final namespaces of components:
"Microsoft.AspNetCore.Identity.EntityFrameworkCore":  "1.0.0",
"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
Removed workaround to assure that database is created in Entity Framework Core

Updated references in Identity Migration Doc

---

aspnet/hosting/aspnet-core-module.rst

Fixes #1931
... also updated capitalization of "h" of `applicationhost.config` to `applicationHost.config`.
Adds ANCM module, schema, and `applicationHost.config` locations to the doc for easy dev reference.
All credit to @jhkimnew for excellent post at https://github.com/aspnet/Home/issues/1583#issuecomment-249754022.

Add location information to ANCM hosting doc

---

aspnet/performance/caching/index.rst
aspnet/performance/caching/output.rst

I believe this topic is covered by the response caching topic.

Remove output caching from TOC

---

aspnet/security/app-secrets.rst

Updated Library references to not bound with a specific version.
When tools/references are updated (like Microsoft.Extensions.Configuration.UserSecrets was updated to 1.0.0) the documentation turns outdated

Update lib references

---

aspnet/security/authentication/identity.rst
aspnet/security/authentication/identity/sample/src/ASPNET-IdentityDemo/Startup.cs

By default, identity doesn't  require unique emails for user. 
Add an example of how configure ASP.NET Identity to have unique user emails, which is the need in a lot of projects.

Add user's unique email policy configuration

---

aspnet/client-side/using-gulp.rst

Fixes #1751 
- Removed references to rc1 versions of templates
- Re-worded sections to make relevant to using Gulp

Update for gulp document

---

aspnet/publishing/vsts-continuous-deployment.rst

Making a note to improve restore times when using Hosted build agents and restoring packages for ASP.NET Core by setting an environment variable.
Credit to @DarqueWarrior and his article at http://donovanbrown.com/post/2016/08/28/Stop-wasting-time-during-NET-Core-builds

Noting to skip first time package restore on hosted servers for vsts CI Build

---

aspnetcore/data/ef-mvc/crud.md

Fix typo in CRUD tutorial for Entity Framework

---

aspnetcore/fundamentals/error-handling.md

For someone not familiar with the pipeline and just arriving from a google search it's not clear that this needs to be run before the rest of the middleware that actually produces the error, and adding it later will appear to have no effect.

Add tip to add error handler before others

---

aspnetcore/getting-started.md

I followed this documentation and found several steps unnecessary.   
The new command: "dotnet new -t web" will create the asp.net core web application leaving the user to restore and run only.
This simplifies the steps need for a user to get up and running, from 8 steps to 5.

Updated document to reflect new cli command

---

aspnetcore/publishing/iis-with-msdeploy.md
aspnetcore/publishing/iis.md

(Preamble: This is my first asp.net Docs pull requests. Apologies in advance for any errors.)
I noticed these two articles had the correct headings but the title tags were back to front.

title of iis.md and iis-with-msdeploy were back-to-front.

---

aspnetcore/intro/index.md
aspnetcore/mvc/views/tag-helpers/toc.md

There are links to docs.microsoft.com/en-us/aspnet/aspnetcore/intro which does not exist.  Duped page from /aspnetcore/index.md to fix for now. Breadcrumbs also links to above link.  Doing hotfix for Connect().
@wpickett
@danroth27

intro.md fix

---

aspnetcore/mvc/views/tag-helpers/intro.md

An asterisk was not escaped in the "wildcard" section which was causing some text to become italicized.

Escape asterisk in tag helper introduction

---

aspnetcore/fundamentals/routing.md

The route templates/behavior template didn't have a proper column marker, and the minlength example in the route constraints table was inconsistent with the note.

Fix typos in tables

---

aspnetcore/data/ef-mvc/crud.md

Correct the destinations for two links from the old to the current Entity Framework documentation

Correct link destinations

---

aspnetcore/fundamentals/servers/kestrel.md

Should this be link to the api reference at https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.hosting.kestrelserveroptionshttpsextensions too?

Correct reference to UseHttps extension method

---

aspnetcore/mvc/models/formatting.md

Per [ObjectResultExecutor](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/Internal/ObjectResultExecutor.cs#L265) the `RespectBrowserAcceptHeader` option controls the behaviour when the Accept header includes the `*/*` media type.

Fix wildcard accept header

---

aspnetcore/data/ef-mvc/advanced.md

Fix link to point to current EF documentation

Fix link to documentation

---

aspnetcore/data/ef-mvc/intro/samples/cu/Controllers/DepartmentsController.cs

Line 146 runs inside of a block for which departmentToUpdate == null. Therefore, the attempt to read departmentToUpdate.InstructorID leads to a null reference exception.
The code is re-displaying the properties of the deletedDepartment, so the selected member of the select list should be deletedDepartment.InstructorID

Fix null reference exception

---

CONTRIBUTING.md

Add the CLA completion link in contributing.md, with others details about complex PR.
I had to complete the CLA and it was difficult to know what the procedure is. On google, you'll find multiple links and posts, all wrong or obsolete : https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=CLA+microsoft+github&start=0
The only one good information I found was here : https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md

Add CLA completion link in contributing doc

---

aspnetcore/data/ef-mvc/update-related-data.md

Code snippet is pointing to the wrong range of lines. Showing "Title" field when it is supped to show "CourseID" field.

Fix range for code snippet

---

aspnetcore/client-side/using-gulp.md

The instructions for setting up Gulp referenced "project.json" as the location to add the "devDependencies" section, rather than "package.json".

change "project.json" to "package.json"

---

aspnetcore/security/authentication/sociallogins.md

Social Logins page should have a note about calling order according to https://github.com/aspnet/Identity/issues/1036
@Rick-Anderson

add a note about UseIdentity() being first in order

---

aspnetcore/security/data-protection/configuration/default-settings.md

Fixes #2334 
cc/ @blowdart @tmm360

Add slot details to behavioral defaults for Azure Apps

---

aspnetcore/tutorials/first-mvc-app/start-mvc/sample2/src/MvcMovie/Views/Movies/IndexOriginal.cshtml

Remove unused comments to display the correct lines that need to be highlighted.
BEFORE:
-
AFTER:
-

Correct the highlighted line

---

aspnetcore/performance/caching/toc.md

I've taken care of this in my branch `middleware.md` doc. I won't sweat the placeholder middeware doc, since that will go away soon.

Update TOC caching middleware link to title casing

---

aspnetcore/fundamentals/middleware.md

Fixes #2358 
Opted for approach #3 ... just link the dedicated docs. It's the :lips: KISS :lips: approach here.
It's such a downer to click a link all excited to hear about the topic and hit a doc stub :cry:; therefore, I'll keep :eyes: on when the new docs land and create PR to add links for Response Caching, Response Compression, and URL Rewriting.

Add middlewares to list in Middleware doc

---

aspnetcore/data/ef-mvc/crud.md

The markup wasn't correct so the /span tag wasn't being displayed in the tutorial.  There may be a better markup, but this solution works.

Fix markup so /span end tag is displayed

---

aspnetcore/fundamentals/configuration/sample/src/CommandLine/Program.cs

To use .AddCommandLine the Microsoft.Extensions.Configuration.CommandLine package needs to be added to dependencies.

add CommandLine package id comment

---

aspnetcore/data/ef-mvc/sort-filter-page.md

Highlight the LastName and EnrollmentDate lines that are swapped.  These lines aren't changed, but they are swapped and it took me a second to realize that because they weren't highlighted.  Not sure is you have a policy on lines moving vs. changing and what is highlighted.

Highlight the LastName and EnrollmentDate lines

---

aspnetcore/security/authorization/policies.md

code snippet had either 1 too many brace closure (if was just the beginning of the method and remainder was removed for brevity) or the close parenthesis was misplaced.

AddPolicy over21 incorrect brace closer

---

aspnetcore/data/ef-mvc/update-related-data.md

Fixed highlighting in Updating related data Instructors controller.
Update the Delete Page - First three lines are all changed - variable declaration style changed and lambda input parameter name changed (could also leave highlighting as is and change the other two).

Fixed code highlighting in Instructor Controller

---

aspnetcore/fundamentals/routing.md
aspnetcore/mvc/controllers/routing.md

Also fixed some broken/inaccurate links, typos, etc.
cc @Rick-Anderson @rynowak @danroth27

Improved routing info on regex constraints, plus more

---

aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/TestingControllersSample.sln
aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/global.json
aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/src/TestingControllersSample/project.json
aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/tests/TestingControllersSample.Tests/project.json

Upgraded the [Testing Controller Logic](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) sample solution to .NET Core 1.1. See issue #2453

Upgraded Testing Controllers sample solution to .NET Core 1.1

---

aspnetcore/fundamentals/middleware.md
aspnetcore/fundamentals/url-rewriting.md
aspnetcore/toc.md

Renames *URL Rewriting* to *URL Rewriting Middleware* in TOC and `middleware.md` doc.
Also seeks to fix text links that load as clickable links, since DocFX doesn't seem to have a capacity to make text (unclickable) links.

URL Rewriting title update and text links fix

---

aspnetcore/data/ef-mvc/concurrency.md

Link in summary is to old docs site. updated to point to the new doc site for core.

Fix Bad Link in summary

---

aspnetcore/mvc/controllers/routing.md

In sample code, it's 
public IActionResult GetProduct(int id) { ... }
But next line, it says The ProductsApi.GetProducts(int) , 
So update it to ProductsApi.GetProduct(int)

Update routing.md to change one typo

---

aspnetcore/security/authentication/accconfirm.md

For the Code block relating to Configure startup to use AuthMessageSenderOptions the referenced line numbers have changed since this page was updated. Edited the line numbers to properly reference the correct lines

Reference for code in file incorrect

---

aspnetcore/security/authentication/accconfirm.md

When following the guide and adding the service.configure for mvcoptions a compile error occurs using a base .netcore mvc project.
The startup.cs file by default does not include the declaration for the namespace microsoft.aspnetcore.mvc which resolves the compile error.
Added a note section below the code block stating if you recieve an error you may need to add the delcaration

error occurs when using MvcOptions

---

aspnetcore/fundamentals/dependency-injection.md

Fix codeblocks:
* Indentation
* Some line references
There's a `literal_block` at Line 232 ...
```
```
... that doesn't seem to be affecting the text of the doc. Should that line be removed?

Fix codeblocks in Dependency Injection doc

---

aspnetcore/fundamentals/middleware.md

Fixes #2516 (also adds a link to the Response Caching Middleware doc)
There's a NOTE in the doc that touches on the ordering concept. What I try to do here is move that note content down to this new *Middleware ordering* section, then show the examples. 
cc/ @JunTaoLuo

Add Middleware ordering content to Middleware doc

---

aspnetcore/mvc/models/file-uploads.md
aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/StreamingController.cs
aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/UploadFilesController.cs
aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Filters/DisableFormValueModelBindingAttribute.cs
aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Filters/GenerateAntiforgeryTokenCookieForAjaxAttribute.cs
aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Startup.cs

Fixes #2553 
... and with the usual updates:
* Codeblocks (formatting fixed and in-text code is swapped for sample snippets)
* Description + keywords
* Code filenames to italics
* Title and header casing
* Minor grammatical changes
* Links converted to `xref` format
* Took `en-us` out of external links
Let me know how you handle line breaks in code to format the code for doc webpage presentation: Do you want code lines broken for a manual word-wrap where feasible, or you do want to just let them break naturally?

File uploads doc update

---

aspnetcore/mvc/views/tag-helpers/intro.md

Add a missing space before the word "icon", and properly escape two asterisks.

Minor fixes to Tag Helpers intro doc

---

aspnetcore/publishing/iis.md

Fixes #1017 
Short and sweet. I don't call out the various config providers. They'll hear all about them in the *Configuration* doc.

Documenting ineffective web.config sections in Pub to IIS doc

---

aspnetcore/mvc/views/razor.md

If you're interested in this one ...
This one comes from https://github.com/aspnet/MvcPrecompilation/issues/37. I just hit it when I had a misnamed view file and setup precompiled views for an app.

Add note on case sensitive view lookups to Razor doc

---

aspnetcore/publishing/linuxproduction.md

Since the ASP.NET Core application is run from /etc/systemd/system directory, the working directory is no longer /var/aspnetcore/hellomvc. Update the service file to set WorkingDirectory=/var/aspnetcore/hellomvc so that the program will run. Otherwise, users will get System.IO.FileNotFoundException when using systemd to monitor and run ASP.NET Core application.

Update service file to set WorkingDirectory

---

aspnetcore/performance/response-compression/sample/ResponseCompressionSample.csproj

@tdykstra This one can go in now. It merely removes the bit that creates a `Logs` folder in published output. It isn't in the templates, so I shouldn't have had it in there in the first place (except it is awfully handy for when you need to flip on stdout logging).

Update Response Compression Sample

---

aspnetcore/security/data-protection/consumer-apis/overview.md

The `Microsoft.AspNetCore.DataProtection.Abstractions` package contains the interfaces. There is no such package as `Microsoft.AspNetCore.DataProtection.Interfaces`.

Refer to correct abstractions package

---

aspnet/.gitignore
aspnet/docfx.json
aspnetcore/docfx.json

@Rick-Anderson please review and merge
I also added _site and _build to the empty aspnet folder .gitignore.  However, when we have an opportunity we should delete this file and find out what it is in the main .gitignore that was causing problems and fix it there.

enable local builds in aspnet folder

---

aspnetcore/getting-started.md

dotnet new -t web is no longer valid, using dotnet new web instead.

Update getting-started.md for a .NET tooling change

---

aspnetcore/mvc/controllers/areas.md

The MVC Areas doc is displaying _http:///products_ instead of _http://\<yourApp\>/products_. This PR addresses the problem by escaping the less than and greater than characters.

Properly escape special characters in MVC Areas doc

---

aspnetcore/fundamentals/servers/aspnet-core-module.md
aspnetcore/publishing/iis.md
aspnetcore/tutorials/nano-server.md

Addresses: https://github.com/aspnet/Home/issues/694
This is waiting on response from @shirhatti as to whether or not the `https://go.microsoft.com/fwlink/?linkid=837808` link should be used for the hosting bundle installer. If @shirhatti is :+1: on using this link instead of an `aka.ms` link, then this can go in now.

Update hosting bundle installer link

---

aspnetcore/security/data-protection/compatibility/replacing-machinekey.md

The \<machineKey\> tag wasn't escaped and therefore considered as a tag by Markdown and not displayed.

Fix display for machineKey tag

---

aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/twitter-logins.md

It looks like the latest dotnet cli syntax for adding packages is "dotnet add package <packagename>" (http://ardalis.com/how-to-add-a-nuget-package-using-dotnet-add).

Update dotnet CLI syntax for adding packages

---

aspnetcore/publishing/iis.md

Addresses: https://github.com/aspnet/IISIntegration/issues/325
We have the Common Error for this problem, but that's too late in the doc to catch an offline install of the hosting bundle and the :boom: that results. Adding one line should save a few broken hearts 💔 .
Thanks to @salmankhann for pointing this out.
This also makes a minor change and removes the "(x64)" from the name of the redist installer package. Following the language in ANCM issues where the x86 and x64 of the ANCM are discussed, we probably shouldn't guess and instruct which bitness of the redist to install. cc/ @shirhatti - Let me know if we **should** state to **install the x64 version of the VC++ redist explicitly** and I'll make a modification to this PR to point that out.

Add in-text note for offline VC++ redist install to Publishing to IIS

---

aspnetcore/client-side/bower.md

Fix a backtick usage issue in the **Manual installation in bower.json** section of the Bower doc.

Remove extraneous backtick from Bower doc

---

aspnetcore/client-side/bower.md

Fix an issue which was causing the doc to display _*.bowerrc_, which is an invalid file name.

Remove extraneous asterisk from Bower doc

---

aspnet/web-api/overview/web-api-routing-and-actions/create-a-rest-api-with-attribute-routing/samples/sample17.cs

// its better to use {authorId:int} instead of just {authorId}
// wrong {authorId} will produce a 400 error with error message
// wrong {authorId:int} will produce a 404 error
Since the publish date route is limited to a couple of formats, I assume you're of the type to prefer to control what type of error is shown to the resource user.

{authorId:int} instead of {authorId}

---

aspnetcore/mvc/controllers/areas.md

Add the missing _id_ placeholder to the _default_ MVC route. Also, change the verbiage above the code snippet slightly, since there is no highlighting.

Fix area routes code sample

---

aspnetcore/tutorials/first-web-api.md

The source code had been updated to use the EF Core InMemory provider but the tutorial did not reflect these changes. To help get people up and running, I have:
Added the following new sections:
* Add support for Entity Framework Core
* Create the database context
Updated the following section:
* Add a repository class

Updated tutorial to include support EF Core

---

aspnetcore/tutorials/web-api-help-pages-using-swagger.md

Fix typo where UseSwaggerUI was written with lowercase 'i' in 'UI'

doc(tutorials): fix typo

---

aspnetcore/aspnetcore-1.1.md
aspnetcore/toc.md

New direction as of 28 Feb:
From the Release Notes TOC, link to a page similar to [Release Notes History](http://docs.servicestack.net/release-notes-history) 
I think we'll want to add a link to [ASP.NET Core 1.1 RTM blog](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/)
[Internal review ULR](https://review.docs.microsoft.com/en-us/aspnet/core/aspnetcore-1.1?branch=ra%2Fwhats-new-in-1.1) **Note**: some of the in page anchors don't work in this branch such as Cookie-based TempData provider and VC's as TH

WIP: What's new in ASP.NET Core 1.1

---

aspnetcore/fundamentals/configuration/sample/src/UsingOptions/Controllers/HomeController.cs

The constructor receives an optionsAccessor, but by the time it is stored in the field, its value has been accessed, so the field name should not be suffixed with Accessor.

Rename _optionsAccessor field to represent value

---

aspnetcore/fundamentals/hosting.md

As it was treated as formatting, so it made the rest of the paragraph not legible

Escape literal asterisk

---

aspnetcore/client-side/index.md

@Rick-Anderson Renaming link to AngularJS like in the article.
Greetings Damien

renaming to AngularJS like in page

---

aspnetcore/hosting/aspnet-core-module.md

Update ANCM ref doc for tooling RTM.
* Set default for `forwardWindowsAuthToken` to `true` per https://github.com/aspnet/AspNetCoreModule/issues/53
* Update language that pertains to loss of `publish-iis` tooling
* Change spacing of *web.config* to 2-space indents
* Change `aspnetcore-stdout` to `stdout` to match what the SDK produces
* Reference and link the two deployment types, which are represented by the example *web.config* files
cc/ @shirhatti

Update ANCM ref doc for tooling RTM

---

aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events/samples/sample7.cs

The PR contains an update to an example on the server-side.
The base object does not have a method with no parameters in SignalR version 2.2.1. The change in the code changed the call to the base class to include a mandatory parameter.

Added parameter in the call to the base function

---

aspnet/web-api/overview/advanced/http-cookies/samples/sample11.cs
aspnetcore/fundamentals/configuration/sample/ConfigInMemory/Program.cs
aspnetcore/fundamentals/configuration/sample/src/CommandLine/Program.cs
aspnetcore/fundamentals/configuration/sample/src/ConfigJson/Program.cs
aspnetcore/fundamentals/configuration/sample/src/InMemory/Program.cs
aspnetcore/fundamentals/configuration/sample/src/InMemoryGetValue/Program.cs

Replaced several uses of `static public` with the more appropriate `public static` to fall in line with the [coding guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), which state that the visibility modifier should always be the first modifier present.

Updated Coding Style in Examples

---

.github/PULL_REQUEST_TEMPLATE.md

@Rick-Anderson People tend to leave the template text in the PRs, and the title vs summary guidance seems unnecessary so I'm thinking a lighter-weight template would be better.

PR template changes

---

aspnetcore/fundamentals/localization.md

This is an attempt to clarify resource naming (which we get a lot of issues about at aspnet/Localization). Firstly by moving the relevant section higher up in the document where it's more likely to be seen and has relevance to the section about generating resource files. Secondly by emphasizing that what matters in the end is the name of the assembly your project generates.

Move resource naming section up and clarify

---

aspnetcore/publishing/iis.md

Several minor updates, including making the doc more hosting system agnostic by removing "server" in a number of places in favor of "hosting system" and "system," per discussion with @Rick-Anderson that IIS Local will often not be on a server ... could be a desktop or laptop.
* Daggars (&#8224;) for asterisk (\*) on note references ... much cooler. 😎 
* Formatting of code and italics removed from headings
* A sentence merged into a paragraph to avoid the dreaded *one-sentence paragraph* (yuck).
* Relative links converted to `xref` links
* Reference the :balloon: :tada: **NEW IIS Modules** :tada: :balloon: doc. *Booyeah!*
Reacts to
* Runtime not installed on host: https://github.com/aspnet/Tooling/issues/886, http://github.com/aspnet/IISIntegration/issues/307
* WebListener is not supported …

Update Publishing to IIS

---

aspnetcore/tutorials/first-web-api.md

The deleted line is supposed to "make the class complete" by adding the two closing brackets for namespace and class. [The way it is rendered](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) however does more harm than good in my opinion because it can not be copied at once anyway and looks like bug.
```cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using TodoApi.Models;
namespace TodoApi.Controllers
{
[Route("api/[controller]")]
public class TodoController : Controller
{
private readonly ITodoRepository _todoRepository;
public TodoController(ITodoRepository todoRepository)
{
_todoRepository = todoRepository;
}
```
```cs 
}
}
```
I think users who got far enough to do this tutorial should be able to add the closing brackets without copying the …

Remove closing brackets

---

aspnetcore/security/key-vault-configuration.md

When running AspNet Core 1.1 on top of .NET 4.6.2 and trying to use the Azure Key Vault configuration extensions, I was encountering an exception that was being thrown for `System.TypeLoadException`. I discovered this originated from the use of the Azure Key Vault API and how it interacted with an older (built-in) version of `System.Net.HTTP`. I ended up installing the updated NuGet package for `System.Net.Http` and that fixed the issue. Hopefully this proposed tip will help someone in the future. Or at least until the packages get more aligned.
Addresses #2968

Add troubleshooting tip for `System.TypeLoadException`

---

aspnetcore/fundamentals/environments.md

A minor amendment but could be confusing for people unfamiliar with the cmd line.
The text describes setting it for the current current command window, however setx actually only explicitly changes the environment variable, it doesn't change the current window either, so a user would have potentially noticed no change.

Change environments.md to use set as opposed to setx

---

aspnet/mvc/overview/getting-started/introduction/adding-search.md
aspnet/mvc/overview/getting-started/introduction/adding-search/samples/sample17.cshtml

The current doc treats the second parameter of `@Html.DropDownList()` as a way to set the default selected option. It gives an example of choosing "Comedy" by default. In fact, the given example creates a second entry that says "Comedy" but has an empty value. I provided a correct example.
Feedback is welcome! :-)

Fix explanation: setting a default selected option

---

aspnetcore/tutorials/first-mvc-app/controller-methods-views.md

* I believe that the 'Attribute' suffix at then end of the attributes is misleading as they do not exist in the code:
- The `HttpPostAttribute` attribute -> The `HttpPost` attribute
- The `ValidateAntiForgeryTokenAttribute` attribute  -> The `ValidateAntiForgeryToken` attribute 
Kind regards

Remove the unnecessary 'Attribute' suffix

---

aspnetcore/tutorials/first-mvc-app/start-mvc.md

Unless there's a version of Visual Studio that has a different dialog, I think Authentication only comes up in the second "create a project" dialog. The screenshots that are already in the article confirm this. Thanks!

Remove too-early reference to authentication

---

aspnetcore/client-side/angular/sample/AngularJSSample/src/AngularJSSample/AngularJSSample.csproj

Remove 2 unused references to the `BundlerMinifier.Core` NuGet package in the `*.csproj` file.

Angular doc: Remove unused BundlerMinifier.Core package references

---

aspnetcore/security/app-secrets/sample/UserSecrets/Startup.cs

As the non-generic version is deprecated.

Updated to use generic method of `AddUserSecrets`

---

aspnetcore/client-side/bundling-and-minification.md

The following note in the **Bundling and minification** doc is inaccurate:
> Conversion option only available in Visual Studio 2017.
This PR adds instructions for accomplishing the same Gulp conversion in VS 2015.

Add VS 2015 instructions for bundle & minify Gulp conversion

---

aspnetcore/client-side/bundling-and-minification.md

Change the `gulpfile.js` code snippet content type from JSON to JavaScript to improve syntax highlighting.

Change gulpfile.js snippet content type to JavaScript

---

aspnetcore/fundamentals/logging.md

the current link doesn't work.  It redirects to https://docs.microsoft.com/en-us/aspnet/core/api/

Fix Bad Link for LogLevel

---

aspnetcore/mvc/views/view-components.md

Cleanup several minor issues in the [View components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) doc, such as extraneous space, spelling & punctuation mistakes, and code highlighting problems.

Fix minor mistakes in view components doc

---

aspnetcore/tutorials/web-api-vsc.md

* Spelling fix naviage -> navigate
* Removed Fiddler link : not relevant for Mac or Linux
* Added `Ctrl+Shift+P` key stroke for command pallete and for Linux, `⌘` doesn't exist for Linux and shortcut is different 
* F5 is Debug keystroke, first mention of Debug instruction did not define this.
* Although not documenting VS Code, adding links to Debugging in VS Code: https://code.visualstudio.com/docs/editor/debugging
* Visual Studio Code users would tend to take advantage of CLI commands for adding/modifying EF component items.  See: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
* Show integrated terminal or more terminal based commands
@Rick-Anderson @danroth27

Minor changes for First API on Mac/Linux

---

aspnetcore/security/authentication/cookie.md

Just a very simple little change to some markdown formatting. The triple backtick being indented meant the next few paragraphs were being included in the code snippet.

Fix markdown formatting around code snippet

---

aspnetcore/tutorials/first-web-api.md

'Use Postman to send a Create request' section has a markdown mismatch. Below the 'In the key-value editor, enter a Todo item such as', the text formatting is broken.

Markdown mismatch

---

aspnet/web-pages/overview/getting-started/introducing-razor-syntax-c.md

The backslash character does not appear when the document is rendered in the browser

Backslash character does not render in browser

---

aspnetcore/mvc/views/view-components.md

There was a reference to the `InvokeAsync` method in the [View Components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) doc which was unnecessarily italicized. This PR removes the italics to make it consistent with all other occurrences in the doc.

Make InvokeAsync styling consistent with other occurrences

---

aspnetcore/tutorials/first-mvc-app/adding-model.md

Added clarification about the current Add > Controller process, which takes two steps and may create confusion about the outcome of the first step, and makes the reader question why the controller itself is not created.

Add clarification about the current Add > Controller

---

aspnetcore/tutorials/first-web-api.md

Line 12 refers to the Microsoft.AspNetCore.Mvc package, I believe the documentation intended to highlight the Microsoft.EntityFrameworkCore.InMemory line 14.

Highlight the EntityFrameworkCore.InMemory line

---

aspnetcore/tutorials/first-web-api.md

To match the earlier code snippet ```string``` should be ```long```

Fix parameter type typo

---

aspnetcore/tutorials/first-mvc-app/details.md

Simply changed from "a" to "an" in two places for fluidity and consistency. I also added the filename extension for `Startup` and made it italic.

Fix typo and filename

---

aspnetcore/mvc/views/tag-helpers/intro.md

Addresses the spacing issues which cause many of the code samples in the [Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro) to display incorrectly.

Fix display issues in Tag Helpers doc code samples

---

aspnetcore/getting-started.md

`macOC` -> `macOS`
Well, the change is next to nothing but still...

Fixes typo

---

aspnet/mvc/overview/deployment/docker-aspnetmvc.md

Fix dockerfile example to work with latest microsoft/aspnet version.
This is the minimal change. There are other ways to get the content in the correct place. The latest aspnet docs use a `site_root` argument when creating the image. See https://github.com/Microsoft/aspnet-docker/blob/master/4.6.2/sample/Dockerfile

Update dockerfile in aspmvc deployment

---

aspnetcore/migration/mvc.md

The snippet range for `PrepareForPublish` is incorrect.
It currently shows:
and it should show:
```xml
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
<Exec Command="bower install" />
</Target>
```

Updated PrepareForPublish snippet range

---

aspnetcore/tutorials/web-api-vsc.md

changed from ´public IActionResult GetById(string id)´ to ´public IActionResult GetById(long id)´ in line 189.

updated the id type from string to long

---

aspnetcore/fundamentals/routing.md

Just under "Routing basics" there was text that had an opening '(' but no closing ')' (probably occurred when the link to IRouter was created). @ardalis

Fixed typo in copy: Missing closing ')'

---

aspnetcore/fundamentals/environments.md

With the change from setx to set, quotation marks are invalid and get set as part of the environment variable, this actually leads to a bad path exception upon dotnet run.
This was introduced actually by last PR #2958 which although did fix that issue, introduced a new one, it's annoying there is such a difference in syntax between setx and set, but that's the way it goes.
A minor change again but the exception if following along would be confusing.

Remove usage of quotations with set command

---

aspnetcore/tutorials/web-api-help-pages-using-swagger.md

So we don't need to include preleases (or do -Pre) when installing the package.

Swashbuckle.AspNetCore is now v1.0

---

aspnetcore/security/authentication/identity.md

Changed the "LogOff" action name into "LogOut".Changed the "LogOff" action name into "LogOut".By default ASP Net core provides Logoff action in "LogOut" ActionResult Only.Also raised PR for changed the action name in account controller .

Changed the "LogOff" action name into "LogOut"

---

aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client.md

There is not reference to a issue number.
I think that there is a typo in the text.

missing space character between `Main` `RunAsync`

---

aspnetcore/fundamentals/localization.md

In French, a space is required both before and after all two- (or more) part punctuation marks and symbols, including the exclamation mark "!". See https://www.thoughtco.com/how-to-use-french-punctuation-4086509 for more information.
*This pull request was suggested by @RickAndMSFT.*

Updating line 78: Correcting French punctuation.

---

aspnetcore/data/ef-mvc/update-related-data.md

Also implement customer suggestion to link back to note about using notepad to avoid VS ruining view code indentation.

remove instructions left over from 1.0

---

aspnetcore/fundamentals/localization.md

Extend Localization middleware code sample to display the declaration of the variable 'supportedCultures'
There are some comments about that.

Extend middleware code sample to display var decla

---

aspnetcore/security/authorization/claims.md

Fixes missing ending parentheses in AddAuthorization example code.

Missing ending parentheses in AddAuthorization example code

---

aspnet/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages.md

Corrected markup for `@Html.AntiForgeryToken` link.

Corrected link markup

---

aspnetcore/fundamentals/localization.md

I made this PR according to the issue that created in the localization repo https://github.com/aspnet/Localization/issues/370, according localization cookie format
It seems someone confused with this line of code https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L81, because there's no quotation at all in the actual cookie format
/cc @RickAndMSFT

Remove unnecessary quotations from localization cookie format

---

aspnet/web-api/overview/advanced/httpclient-message-handlers/samples/sample2.cs

MSDN description of DelegatingHandler Class says:
"Any instance members are not guaranteed to be thread safe"
https://msdn.microsoft.com/en-us/library/system.net.http.delegatinghandler(v=vs.118).aspx

Mitigate possible race condition in MessageHandler1

---

aspnetcore/fundamentals/logging.md

To stop the ETW tracing session, the Remove-EtwTracingSession command doesn't work. Used Stop-EtwTraceSession instead.

To stop tracing session use Stop-EtwTraceSession

---

aspnetcore/publishing/iis.md

Related documentation from @blowdart in an issue from 2015: https://github.com/aspnet/DataProtection/issues/107
The option of having the app pool user load the profile was by far the easiest route, and is not part of the docs. Is there a reason for it missing?

Update docs with load user profile option

---

aspnetcore/security/authentication/accconfirm/sample/WebApp1/Services/MessageServices.cs

Fixed async/await usage to not call .Wait() on the task and to not await the Task that is never used.

Correct async/await usage

---

aspnetcore/mvc/views/view-components.md

This adds some docs to clarify that in order to use a View Component as a Tag Helper, you need to register the assembly containing the View Component using `@addTagHelper`
fixes #3435

document registering View Component Tag Helpers

---

aspnetcore/security/authorization/policies.md

As suggested by VS2017 I've substituted the 2 line code by an inline temporary variable in the last code example of the doc page.

modified mvc example to use c#7

---

aspnetcore/index.md

[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/?branch=pr-en-us-3497)
Given this is our #1 article we should put some effort into it. After we agree, let's run it by Dan.
Fixes  #3496

Update our Intro page - #1 article 

---

aspnetcore/security/key-vault-configuration.md

Without the handling of "--" the keys never get turned into sections seperated by the ConfigurationPath delimiter.

Add KeyDelimiter replacement to GetKey function.

---

aspnet/signalr/overview/getting-started/introduction-to-signalr.md

Hi @Rick-Anderson, appreciate if you can review. Thanks!

Minor: Typo fix "Communcation" => "Communication"

---

aspnetcore/mvc/controllers/filters.md

The Action filters sample was previously at the end of the Exceptions filter section. 
Moved it to the end of the Action filters section instead.

Move Action filter example to correct section

---

aspnetcore/client-side/angular/sample/AngularJSSample/src/AngularJSSample/Views/_ViewImports.cshtml
aspnetcore/mvc/models/validation/sample/Views/_ViewImports.cshtml
aspnetcore/mvc/razor-pages/index.md
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/TagHelpers/z1AutoLinkerCopy.cs
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/TagHelpers/z2AutoLinkerCopy.cs
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/Views/_ViewImports.cshtml
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/Views/_ViewImportsCopy.cshtml
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/Views/_ViewImportsCopyEmail.cshtml
aspnetcore/mvc/views/tag-helpers/intro.md
aspnetcore/mvc/views/view-components.md

Remove the optional double quotes used in the `@addTagHelper` directives. This aligns with what's used in the VS project templates.

Remove double quotes used in addTagHelper directives

---

aspnetcore/security/authentication/accconfirm.md
aspnetcore/security/authentication/accconfirm/sample/WebApp1/Views/Account/ForgotPassword.cshtml

The text in the ForgotPassword.cshtml file is incorrect as it leaves the paragraph linking back to the article https://go.microsoft.com/fwlink/?LinkID=532713 intact.

Update ForgotPassword.cshtml file

---

aspnetcore/security/cross-site-scripting.md

Typo: `attacher` -> `attacker`

Fix typo in cross-site-scripting.md

---

aspnetcore/mvc/views/tag-helpers/built-in/index.md

Simple UE edit of the native Tag Helpers landing page. Changes include use of xref links, clarifications in wording, and standardization/cleanup of terminology & grammar.

UE Edit of native Tag Helpers landing page

---

aspnetcore/includes/webApi/next.md

Fixed the Swagger link syntax in the Next Steps section of the ASP.net Core Web API tutorial.

Fixed broken link syntax

---

aspnetcore/mvc/views/view-compilation/sample/MvcRazorCompileOnPublish.csproj

The .csproj file's `ToolsVersion` attribute is implied. Removing it to simplify the code sample.
@Rick-Anderson Please review.

Remove implied ToolsVersion property

---

aspnetcore/mvc/controllers/testing.md

The source listing of the GetTestSessions method of [Testing Controller Logic](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) included an end bracket due to an offset error in the line numbers:
```cs
[Fact]
public async Task Index_ReturnsAViewResult_WithAListOfBrainstormSessions()
{
// Arrange
var mockRepo = new Mock<IBrainstormSessionRepository>();
mockRepo.Setup(repo => repo.ListAsync()).Returns(Task.FromResult(GetTestSessions()));
var controller = new HomeController(mockRepo.Object);
// Act
var result = await controller.Index();
// Assert
var viewResult = Assert.IsType<ViewResult>(result);
var model = Assert.IsAssignableFrom<IEnumerable<StormSessionViewModel>>(
viewResult.ViewData.Model);
Assert.Equal(2, model.Count());
}
}
private List<BrainstormSession> …
```

Fixed an extra bracket in test method

---

aspnetcore/tutorials/first-mvc-app/adding-model.md

The last *list item* above [Add EF tooling and perform initial migration](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model#add-ef-tooling-and-perform-initial-migration) is shown as:
* Razor view files for Create, Delete, Details, Edit and Index pages (Views/Movies/\.cshtml*)
which I believe should be rendered as ... (*Views/Movies/\*.cshtml*) based on its source `*Views/Movies/\*.cshtml*`
I think this is an issue with docfx! and I didn't test this change locally because I couldn't get docfx to work on Ubuntu!

escape asterisk to look properly on ms-docs

---

aspnet/mvc/mvc3.md

Install links broken for 3 MVC pages, because they had been JavaScript popups on the original www.asp.net website. We still do not have the ability to add these links, so removing them and leaving the standalone installer links.

Removing broken install link

---

aspnetcore/fundamentals/servers/weblistener.md

Fix an invalid "Windows Authentication" link in the WebListener doc.

Fixes #3821

---

aspnet/mvc/mvc4.md
aspnet/mvc/overview/older-versions/mvc-music-store/mvc-music-store-part-1.md

Install links broken for 3 MVC pages, because they had been JavaScript
popups on the original www.asp.net website. We still do not have the
ability to add these links, so removing them and leaving the standalone
installer links.

Removing broken install links

---

aspnet/aspnet/overview/owin-and-katana/owin-startup-class-detection/samples/sample6.xml

The redundant space there makes the option inoperative.
I just spent some time to debug the issue in my application that was caused by the documentation copy-pasted into `Web.config`, and I'd like to help all the other folks around by fixing that typo.

Fix a sample for OWIN Startup Class Detection

---

aspnetcore/security/data-protection/compatibility/cookie-sharing.md

Match the ASP.NET 4.x cookie name with the AuthenticationScheme created at first section

Match the ASP.NET 4.x cookie name with the AuthenticationScheme created at first section

---

aspnetcore/mvc/views/tag-helpers/built-in/AnchorTagHelper.md
aspnetcore/mvc/views/tag-helpers/built-in/CacheTagHelper.md
aspnetcore/mvc/views/tag-helpers/built-in/DistributedCacheTagHelper.md
aspnetcore/mvc/views/tag-helpers/built-in/EnvironmentTagHelper.md
aspnetcore/mvc/views/tag-helpers/built-in/ImageTagHelper.md

The built-in Tag Helper docs were missing snippet content types, and in some cases the types were incorrect. This PR cleans up that issue and addresses a few other minor formatting issues.

Fix snippet content type issues

---

aspnetcore/publishing/linuxproduction.md

There was a semicolon missing in a line for nginx:
should be: `add_header X-Content-Type-Options nosniff;`

Add semicolon to nginx config line

---

aspnetcore/migration/webapi.md
aspnetcore/mvc/models/file-uploads.md
aspnetcore/mvc/razor-pages/index.md
aspnetcore/mvc/views/tag-helpers/built-in/CacheTagHelper.md
aspnetcore/publishing/apache-proxy.md

Remove doubled-up occurrences of "the" which I stumbled upon while writing another doc.

Remove duplicated instances of 'the'

---

aspnetcore/tutorials/first-web-api/sample/TodoApi/Controllers/TodoController.cs

By using First(), there's the opportunity for an uncaught exception when the endpoint is called with an ID not present in the database.

Fix DELETE operation in TodoController

---

aspnetcore/fundamentals/hosting.md

@Rick-Anderson ... let's make that "section names" :point_right: "section name" (singular, as it's the same name across the keys of the filtered section)
From ...
> The presence of the section names on the keys prevents ...
... to ...
> The presence of the section name on the keys prevents ...

Patch a plural term making it singular

---

aspnetcore/data/ef-mvc/intro/samples/cu-final/Views/Home/Index.cshtml
aspnetcore/data/ef-mvc/intro/samples/cu/Views/Home/Index.cshtml

The final source code and a snippet referenced in "EF Core with ASP.NET Core MVC" tutorial needs correct url,
currently:  "https://github.com/aspnet/Docs/tree/master/aspnet/data/ef-mvc/intro/samples/cu-final"
should be:
"https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final"

use correct github url in link to project source code

---

aspnetcore/publishing/iis.md
aspnetcore/publishing/web-publishing-vs.md
aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md

Fixes #3301
Adds a blurb to three:
* *aspnetcore/publishing/iis.md* - There's also a bad section heading that I fix in passing.
* *aspnetcore/publishing/web-publishing-vs.md*
* *aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md* - Azure peeps might not look at either of the other two topics, so I surface the info here at the top of the deployment step.
cc/ @danroth27 @Rick-Anderson @tdykstra

Document that deployment requires stopping the app

---

aspnetcore/aspnetcore-2.0.md
aspnetcore/toc.md

[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0?branch=td-whatsnew)
@Rick-Anderson @scottaddie Ready for review but wait on merging

2.0 RTM changes for whatsnew

---

aspnetcore/mvc/views/view-compilation.md

[Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?branch=scottaddie%2Fscd-view-compilation)
The view compilation tool doesn't work for Self-Contained Deployment scenarios in ASP.NET Core 2.0. Update the doc to account for that. Also, include detail on ASP.NET Core 2.0 projects targeting .NET Framework.

2.0 updates to Razor view compilation doc

---

aspnetcore/security/authentication/identity-enable-qrcodes.md

This reverts commit adb98d23559b19043b308b74208ca9c17bd36db6.
@blowdart was right all along
I added to the wrong page but that page's having model the `AuthenicatorUriFormat` reinforced it was the correct page https://github.com/dotnet/templating/pull/1214

Revert "Fix QRCode generation data source"

---

aspnet/web-api/overview/web-api-routing-and-actions/routing-and-action-selection.md

I was reading this doc and the "JavaScript" label on a code sample threw me for a second. I noticed an earlier sample was labeled "PowerShell", too. Both are C# and would be contained in the same .cs file.

Re-label programming language for two code samples

---

aspnetcore/mvc/razor-pages/index.md

@jaliyaudagedara 
@scottaddie 
@ardalis 
@halter73 
The original sentence makes it sound like the `Async` suffix is a naming convention for the new Page handlers, but it's not; it's a naming convention for functions that are declared `async`.  I think this change makes that more clear.

Clarified some wording over the "Async" naming convention

---

aspnetcore/fundamentals/middleware.md

1. The method and its description do not match.
2. To be good structure, the contents of the paragraph should be in order to match the order of the items listed at the beginning of the paragraph. I think this is a good rule to read paragraphs predictably.

Correct the contents of middleware.md

---

aspnetcore/migration/1x-to-2x/index.md
aspnetcore/migration/1x-to-2x/samples/AspNetCoreDotNetCore1.1App/AspNetCoreDotNetCore1.1App/Program.cs
aspnetcore/migration/1x-to-2x/samples/AspNetCoreDotNetCore2.0App/global.json

- Change a `global.json` sdk version number to 2.0.0
- Remove the region displayed in the `Program.cs` code snippet

Fix version number and region issue in 2.0 migration doc

---

aspnetcore/publishing/iis.md

There is no space between the Sid and the permission in the ICACLS console expression according to the specs over at https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls
Here is the main syntax snip: icacls <FileName> [/grant[:r] <Sid>:<Perm>
Tested this on Windows 10 and Windows 2008 R2.

Correct the ICACLS console example

---

aspnetcore/fundamentals/url-rewriting/samples/2.x/UrlRewritingSample.csproj

URL Rewriting Middleware topic: Updates sample to target only `netcoreapp2.0`.
@Rick-Anderson, this is the last one of the group.

Update 2.0 sample TFM+packages

---

aspnetcore/data/ef-mvc/complex-data-model.md

A separate semi-related issue:
There is a sentence that uses `{` insted of `<` in this file: (inside [this section](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model#add-a-migration))
> Open the {timestamp}_ComplexDataModel.cs file.
Should it be changed to use <...>_... or left as is?

Escape another <

---

aspnetcore/migration/1x-to-2x/identity-2x.md

The 2.0 version of AddEntityFrameworkStores still needs the DbContext type

Added generic param on AddEntityFrameworkStores

---

aspnetcore/data/ef-mvc/read-related-data.md

The previous code was:
```
if (courseID != null)
{
ViewData["CourseID"] = courseID.Value;
viewModel.Enrollments = viewModel.Courses.Where(
x => x.CourseID == courseID).Single().Enrollments;
}
```
and it has changed to:
```
if (courseID != null)
{
ViewData["CourseID"] = courseID.Value;
var selectedCourse = viewModel.Courses.Where(x => x.CourseID == courseID).Single();
await _context.Entry(selectedCourse).Collection(x => x.Enrollments).LoadAsync();
foreach (Enrollment enrollment in selectedCourse.Enrollments)
{
await _context.Entry(enrollment).Reference(x => x.Student).LoadAsync();
}
viewModel.Enrollments = selectedCourse.Enrollments;
}
```
So I think the highlighted portions should change!

Change highlighted code

---

aspnetcore/data/ef-mvc/update-related-data.md

It was changed from `[HttpPost, ActionName("Edit")]` to `[HttpPost]` but was not highlighted

Highlight modified line

---

aspnetcore/fundamentals/file-providers/sample/src/WatchConsole/WatchConsole.csproj
aspnetcore/fundamentals/url-rewriting/samples/1.x/URLRewritingSample.csproj
aspnetcore/fundamentals/url-rewriting/samples/2.x/UrlRewritingSample.csproj
aspnetcore/mvc/models/formatting/sample/ResponseFormattingSample.csproj
aspnetcore/mvc/models/validation/sample/ValidationSample.csproj
aspnetcore/performance/caching/middleware/samples/1.x/ResponseCachingSample.csproj
aspnetcore/performance/caching/middleware/samples/2.x/ResponseCachingSample.csproj
aspnetcore/performance/response-compression/samples/1.x/ResponseCompressionSample.csproj
aspnetcore/performance/response-compression/samples/2.x/ResponseCompressionSample.csproj

Removing \<OutputType> from updated projects, as it's specified by `Sdk.Web`, and we're (generally) not showing defaults in the files.
There's a chance that we'll need to make an additional  update for *wwwroot* to match the templates. I'm checking on that now and will provide a new PR if an additional update is needed on a couple that have a *wwwroot* folder.

Remove OutputType from project files

---

aspnetcore/tutorials/web-api-help-pages-using-swagger/sample/TodoApi/Startup2.cs

app.UseMvcWithDefaultRoute() neither used in the previous Todo Api nor in the swagger tutorial

Call `UseMvc()` instead of `UseMvcWithDefaultRoute()`

---

aspnetcore/data/ef-mvc/concurrency.md

The code in 2nd snippet changed from:
```
[HttpPost, ActionName("Delete")]
[ValidateAntiForgeryToken]
public async Task<IActionResult> DeleteConfirmed(int id)
{
var department = await _context.Departments.SingleOrDefaultAsync(m => m.DepartmentID == id);
_context.Departments.Remove(department);
await _context.SaveChangesAsync();
return RedirectToAction(nameof(Index));
}
```
to
```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Delete(Department department)
{
try
{
if (await _context.Departments.AnyAsync(m => m.DepartmentID == department.DepartmentID))
{
_context.Departments.Remove(department);
await _context.SaveChangesAsync();
}
return RedirectToAction(nameof(Index));
}
catch (DbUpdateConcurrencyException /* ex */)
{
//Log the error (uncomment ex variable name and …
```

Highlight modified code

---

aspnetcore/data/ef-mvc/advanced.md

I believe I saw some code doing the same! I'm not sure about it and couldn't find info about this in DocFX docs. Is there any place to read about this? because the `id="dynamic-linq"` is changed to `id="use-dynamic-linq-to-simplify-sort-selection-code"` when I use docfx to preview changes locally!

Add a missing closing tag `<\a>`

---

aspnetcore/fundamentals/logging.md

as per configuration JSON example in  "Create filter rules in configuration" section, "How filtering rules are applied" table rule # 6 should  at Debug log level instead of Warring log level.
* Suggest reviewers if you know who should review the PR, using the GitHub **Reviewers** UI.

correct small typo in logging.md  for How filtering rules are applied" table

---

aspnetcore/data/ef-mvc/concurrency.md

I used `dotnet aspnet-codegenerator controller -name DepartmentsController -m ContosoUniversity.Models.Department -udl -scripts -dc ContosoUniversity.Data.SchoolContext -outDir Controllers` on Ubuntu 17 and the scaffolded *Edit* view doesn't have this div!
Maybe older version of `dotnet aspnet-codegenerator` adds this `div` or when using VS on Windows?! I'm not sure...
Edit: I'm using SQL Server on Ubuntu and the tutorial uses LocalDB if this matters to `aspnet-codegenerator`!

Remove extra instruction in ef-mvc tutorial

---

aspnetcore/security/authentication/accconfirm/sample/WebPW/WebPW.csproj

Resolve project warnings by upgrading the *.csproj* package references to 2.0.0.

Upgrade NuGet packages to 2.0 RTM

---

aspnetcore/migration/proper-to-2x/index.md

With .NET Core now being cross-platform and IDE agnostic, listing Visual Studio 2017 as a prerequisite (thus *required*) is misleading and confusing to newcomers to the platform using one of the many alternative editors.
As a .NET developer using a Macbook with VS Code, Visual Studio for Mac and/or JetBrains' Rider, this prerequisite implies that I'm unable to upgrade to .NET Core 2.0 because I don't have Visual Studio 2017.
An alternative approach could be to reword it to something similar to 
> Visual Studio 2017, Visual Studio for Mac, Visual Studio Code or an alternative .NET Core compatible IDE
If this is preferred then let me know and I'll update my PR.
Fixes …

Remove Visual Studio as a prerequisite

---

aspnetcore/toc.md

@scottaddie In the original TOC (prior to moving the tutorials), this topic doesn't look like it was in the right spot ...
This PR just puts the *Backend Services for Native Mobile Applications* topic under the *Mobile* node. The index seems to indicate it should reside there ...

Small TOC patch

---

aspnetcore/fundamentals/configuration.md
aspnetcore/security/authentication/accconfirm.md

Since the anchor appears at the top of the doc, it serves no purpose and can safely be removed.

Remove unnecessary section anchor from Configuration doc

---

aspnetcore/mvc/razor-pages/index.md

The same code snippet is displayed twice. I'm certain that I won't be the only one analysing the two code samples to try to find a difference only to realise that they're identical and thus redundant to be shown twice.
"preceding code" in the following sentence is fine to refer to both of the blocks of sample code (view and backing code for the Razor Page) and still makes sense.

Remove duplicated code display

---

aspnetcore/tutorials/first-web-api-mac.md

The "uid" metadata field was removed in https://github.com/aspnet/Docs/commit/42a48de471aaa42526dfa3f37415f7b43aa3afa2. This PR adds it back to fix a build warning.

Add missing uid to metadata

---

aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client/samples/sample27.js

Small contribution to remove an extra }); found within "Define method on client (with the generated proxy)" JavaScript code snippet found after the .fail method.

Updating "Define method on client (with the generated proxy)" code snippet

---

aspnetcore/fundamentals/servers/weblistener.md

Two more patches.
I don't see `UseWebListener` in the API content.

Link patches

---

CONTRIBUTING.md

There's no need to pass the default template ... it *IS* the default template used.

Contribution guidelines update

---

aspnetcore/fundamentals/metapackage.md

Delete the "todo" comment and include a link to the Runtime Store doc. Also, fix Gauntlet warnings related to description and keywords.

Add link to Runtime Store

---

aspnetcore/migration/1x-to-2x/index.md

Remove the leading space before the 2nd line of the App Insights code snippet in the 1.x to 2.0 migration doc.

Dedent App Insights code snippet

---

aspnetcore/mvc/views/view-compilation.md

This needed a small touch. View precomp for SCDs worked in 1.1, broke in 2.0, and will be back for 2.1.

Patch note for view precomp for SCDs

---

aspnetcore/security/authentication/social/microsoft-logins.md

Discussed with @blowdart and @HaoK and it sounds like this warning isn't actually needed.

Remove note about calling AddAuthentcation multiple times

---

aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/twitter-logins.md

Applying the same change as https://github.com/aspnet/Docs/pull/4377 to the Twitter, Google, & Facebook social auth docs.

Remove unnecessary warnings from social auth docs

---

.gitignore

- Remove duplicate *node_modules/* entry
- Make the *Thumbs.db* file exclusion more generic

.gitignore file cleanup

---

aspnetcore/includes/make-ssl-cert.md

Fixes #4373 
@scottaddie @mairaw Looks like there's a bad 🐁 in the redirect 🕰️. The link:
> https://technet.microsoft.com/itpro/powershell/windows/pki/new-selfsignedcertificate
... redirects to ...
> https://docs.microsoft.com/powershell/module/pki/new-selfsignedcertificate
... but should go to ...
> https://docs.microsoft.com/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps
... perhaps because it changed modules without an update to their redirect file.

Update tooling links

---

aspnetcore/fundamentals/configuration.md
aspnetcore/fundamentals/configuration/sample_snapshot/CommandLine/Program.cs
aspnetcore/fundamentals/configuration/sample_snapshot/CommandLine/Program2.cs
aspnetcore/fundamentals/configuration/sample_snapshot/Program.cs
aspnetcore/fundamentals/configuration/sample_snapshot/readme.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?branch=pr-en-us-4307&tabs=basicconfiguration#commandline-configuration-provider)
Fixes #2409 
Fixes #1382
[Review site topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?branch=pr-en-us-4307#commandline-configuration-provider)
This turned out to be a considerable overhaul of the CommandLine config provider section:
* The whole topic (big IMHO here) is *toooooo console app-ish*. We want to maintain the basic config explanations. What's a :boy: to do? 💡 :zap: **3RD TAB!** :zap: :bulb: The "Basic Configuration" is a tab with the basics (as the topic currently embraces in each of its samples). We can have the 2.x and 1.x bits in tabs 2 and 3 showing how the …

CommandLine config provider overhaul

---

aspnetcore/security/authentication/identity-enable-qrcodes.md

The existing code without the tilde results in a warning in VS.

Use tilde syntax for QR code script reference

---

aspnetcore/tutorials/web-api-help-pages-using-swagger.md

React to Livefyre comment for the [Swagger tutorial](https://docs.microsoft.com/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio). The tutorial wasn't explicitly asking the reader to create the *wwwroot/swagger/ui* folder.

Add instruction to create Swagger UI assets folder

---

aspnet/identity/overview/getting-started/aspnet-identity-using-mysql-storage-with-an-entityframework-mysql-provider/samples/sample6.cs

Fixes #3260
[Review topic (internal only)](https://review.docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/aspnet-identity-using-mysql-storage-with-an-entityframework-mysql-provider?branch=pr-en-us-4366)
@Kyoraku I've only very rarely ever used MySQL, but is this correct? Does this clarify the value?
```
"SELECT COUNT(*) 
FROM information_schema.tables 
WHERE table_schema = 'IdentityMySQLDatabase' AND table_name = '__MigrationHistory'"
```
In spite of the topic showing a MySQL Workbench screenshot with the name in lowercase, I think the guidance is that it should be provided the way it was created in the Azure portal. Although Windows is case insensitive, other systems (Unix) or certain Mac scenarios are case sensitive.
Original (unfixed) topic: …

Clarify MySQL schema in topic example

---

aspnetcore/security/authentication/cookie.md

In .Net Core 2.0 using the code as supplied results in an exception, the fix is to pass the scheme name when calling AddCookie.
Fails:
services.AddAuthentication("MyCookieAuthenticationScheme")
.AddCookie
Works:
Fix demo code for services.AddAuthentication.AddCookie
services.AddAuthentication("MyCookieAuthenticationScheme")
.AddCookie("MyCookieAuthenticationScheme",

Fix demo code for AddAuthentication.AddCookie

---

aspnetcore/security/authentication/cookie.md

Adding a missing parameter to the `AddCookie` call, per Chris' request in https://github.com/aspnet/Docs/pull/4422.

Add missing param to AddCookie call

---

aspnet/breadcrumb/toc.yml

I've noticed that if I'm on a localized version of the docs and click on the breadcrumb link to ASP.NET Core (e.g. https://docs.microsoft.com/ru-ru/aspnet/core/migration/), the site jumps to the English version somehow. It might be a bug with the redirection mechanism but I thought I'd put the right link on the breadcrumb to avoid that.

fix breadcrumb link to core

---

aspnetcore/toc.md
aspnetcore/tutorials/razor-pages/index.md
aspnetcore/tutorials/razor-pages/model.md
aspnetcore/tutorials/razor-pages/page.md
aspnetcore/tutorials/razor-pages/razor-pages-start.md

A trailing "z" was added in the following commit: https://github.com/aspnet/Docs/commit/d9ec19e5452af83648074db5d96c0a0f4f9e7f9a#diff-fd72d6004b543ea4d6849242cb8b45ea. Reverting, as there are references in the docset that still reference the old value without the "z".

Fix inadvertent uid change (typo)

---

aspnetcore/security/authentication/identity/sample/src/ASPNET-IdentityDemo-PrimaryKeysConfig/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNETv2-IdentityDemo-Configuration/Startup.cs

- Shorten the 1.x `AuthenticationScheme` and `ReturnUrlParameter` setter lines to improve display
- Add missing `ReturnUrlParameter` setter line to 2.x sample. This makes it clear that the property still exists in 2.x.

Alter app cookie configuration code samples

---

aspnetcore/migration/1x-to-2x/samples/AspNetCoreDotNetFx2.0App/AspNetCoreDotNetFx2.0App/Views/Account/AccessDenied.cshtml

In line 6 an @ symbol was forgotten. This made ViewData["Title"] render in HTML instead of being parsed as C#.

Added @ symbol to make C# code work (typo fix)

---

aspnetcore/security/authentication/2fa/sample/Web2FA/Services/MessageServices_twilio.cs

Removes a `var` declaration that would not compile.
Also changes the call to Twilio to use the async version and return the resulting Task.

2fa twilio sample

---

aspnetcore/fundamentals/metapackage.md

Fixes https://github.com/aspnet/Docs/issues/4486

Explicitly state .NET Core 2.x is a metapackage requirement

---

aspnetcore/fundamentals/environments.md

As already noted by users IhorShnaider and Mike_DePouw_CEI in the comments on the actual Microsoft Docs page, this link just goes back to the wiki homepage, which isn't very helpful.  The proper fix would probably be to link to an article somewhere about environment variables, such as [Wikipedia's](https://en.wikipedia.org/wiki/Environment_variable), but I wasn't sure if there was some Microsoft-specific article that the author had in mind, so I just deleted the link.
Suggested reviewers:
@ardalis

Removed a link from the Working With Multiple Environments Article

---

aspnetcore/fundamentals/localization.md

Given the presence of APIs like [`RequestLocalizationOptions.FallBackToParentCultures`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.requestlocalizationoptions.fallbacktoparentcultures?view=aspnetcore-2.0), it seemed appropriate to mention that specific cultures have "parent" neutral cultures.
Suggested reviewers:
* @Rick-Anderson 
* @damienbod 
* @hishamco

Added "Parent culture" to the list of terms on the Globalization and Localization article

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/RazorPagesMovie.csproj

Due to being an old skool Gulp dude, I wasn't aware that the light-up feature for `BundlerMinifier.Core` with `dotnet build` is to include the `BuildBundlerMinifier` package. This composes the project file better.
@Rick-Anderson @scottaddie In my spare time (i.e., not working on contract items), I'd like to run thru existing 2.0 samps and make sure that the ones with Bower and BundlerMinifier configuration (*bower.json*, *bundleconfig.json*) have the right bits to work properly x-tooling if that's ok with you. I'd propose to look at it this weekend, since some of the samples are broken for these features when not using VS, especially if you consider that the *.gitignore* locks out *lib* folders from samples.
[EDIT] ... and I'm a bit concerned that topics/samples don't call out the prereqs …

Add BuildBundlerMinifier to drop the Target

---

aspnetcore/migration/1x-to-2x/index.md

Fixes https://github.com/aspnet/Docs/issues/4493
[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/migration/1x-to-2x/index?branch=pr-en-us-4494#rely-on-application-insights-light-up-features)
/cc: @mrbullwinkle

Add 2.0 App Insights migration instructions for .NET Framework

---

aspnetcore/getting-started.md

xref resolution should end with a white space. 
This fix also fixed the broken localized content [here](https://docs.microsoft.com/zh-cn/aspnet/core/getting-started) due to bad xref resolution.

Fix @DateTime.Now reference not resolving

---

.gitignore

Due to the changes coming along for https://github.com/aspnet/templating/issues/48, samples will get *lib* folder static assets that Bower would have normally provided when the app is built/published.
Side Note: We'll also include bundled+minified styles and scripts that `BundlerMinifier.Core` would have produced for the app.
Therefore, new samples and existing sample updates should contain all of the static assets they need to run (*lib* folder and *.min.* CSS and JS files) and Bower+`BunderMinifier.Core` shouldn't be part of the app (no configuration files for these features and no targets and package+tooling references in the project file for these features).
cc/ @Rick-Anderson

Allow lib folder contents for samples

---

aspnetcore/fundamentals/app-state.md

In ASP.NET Core 2.0 the Cookie TempData provider is the default, not session state.
Fixes https://github.com/aspnet/Docs/issues/3767
[review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?branch=pr-en-us-4350)

Update doc to state that CookieTempData is the default

---

aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/twitter-logins.md

The anchors are unused and are rendering as raw HTML at the top of each doc.

Remove unnecessary anchors from social auth docs

---

aspnetcore/security/authorization/policies.md

[From build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r):
aspnetcore/security/authorization/policies.md
•	Line 19: [Warning] Illegal link: `[role authorization](roles.md#security-authorization-role-based)` -- missing bookmark. The file security/authorization/roles.md doesn't contain a bookmark named security-authorization-role-based. 
•	Line 19: [Warning] Illegal link: `[claims authorization](claims.md#security-authorization-claims-based)` -- missing bookmark. The file security/authorization/claims.md doesn't contain a …

fix illegal links

---

aspnetcore/mvc/views/razor.md

Most of the necessary background on this PR is provided in an Issue that I created, linked below:
Fixes #4575
I wasn't quite sure on the syntax for relative links to sections within the same topic, so someone will want to review those.
- @Rick-Anderson 
- @guardrex 
- @NTaylorMullen

Added info about calling generic methods to the Razor syntax topic

---

aspnetcore/tutorials/razor-pages/uploading-files.md

`FileUpload` is needed prior to running the migration, so this moves it to the top. Thanks to @jd_kimber and @sevdanski for suggesting this change.

Move FileUpload step to the top

---

aspnetcore/security/authentication/index.md

The the link to "Securing ASP.NET Core apps with IdentityServer4" was broken. The link was replaced with a working one.

Broken link fixed.

---

aspnetcore/mvc/razor-pages/razor-pages-convention-features.md
aspnetcore/mvc/razor-pages/razor-pages-convention-features/sample/Pages/Index.cshtml

Moving from a table to an ordered list, I didn't 🥊 knock out the `<td>` elements. I also add a one line note there to confirm the matching of handler method to handler name from the POST request is correct in the example shown.

Patch sample and add a note on handler name matching

---

aspnetcore/fundamentals/dependency-injection.md

Fixes 
Illegal link: `[Options Model](configuration.md#options-config-objects)` -- missing bookmark. The file fundamentals/configuration.md doesn't contain a bookmark named options-config-objects.
--

Fix link: dependency-injection.md

---

aspnetcore/fundamentals/configuration.md

Fix typo in configuration.md

---

aspnetcore/security/authorization/limitingidentitybyscheme.md

reference: [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r)
Fixes one issue in #4649

fix bad anchor link

---

aspnetcore/security/authorization/policies.md

This will allow for an anchor link (I think, I know ## does, hoping ### does too).  This will help to fix "Illegal link: `[Authorization handlers must be registered](policies.md#security-authorization-policies-based-handler-registration)` -- missing bookmark." on `aspnetcore/security/authorization/dependencyinjection.md`
Reference: [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r)
Reference: #4649

add heading for handler registration

---

aspnetcore/fundamentals/logging.md

Addresses #4093 
Addresses https://github.com/aspnet/Logging/issues/694
The topic already addressed the main misunderstanding that log message text is really a log message *template* with some particular requirements for the sequence of parameters.
What I do here is beef it up a hair 🐄🔔 by referencing the string passed as a "template" in most places. I call out that it can be a string but go with "template" elsewhere in the section.
cc/ @davidfowl @pakrym

Beef up log message template language in logging.md

---

aspnetcore/security/authorization/dependencyinjection.md

Fixes one issue in #4649 
>Illegal link: `[Authorization handlers must be registered](policies.md#security-authorization-policies-based-handler-registration)` -- missing bookmark. The file security/authorization/policies.md doesn't contain a bookmark named security-authorization-policies-based-handler-registration.
Reference [Build Report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r)

fix anchor link to handler registration

---

aspnetcore/security/data-protection/implementation/index.md
aspnetcore/security/data-protection/index.md
aspnetcore/security/index.md
aspnetcore/toc.md

Remove the period from the "Authenticated encryption details" doc's TOC links.

Remove period from TOC link title

---

aspnetcore/security/authorization/resourcebased.md

[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/security/authorization/resourcebased?branch=pr-en-us-4712)
`AuthorizeAsync` method returns `Task<AuthorizationResult>` instead of `Task<bool>` in 2.0.

Changes to resourcebased.md to match Core 2.0

---

aspnetcore/fundamentals/dependency-injection.md

Explains two things:
- Services implementation that implements `IDisposable`, but not their interfaces are correctly disposed.
- Services instances created by a factory function gets disposed

Added examples in Disposing of services

---

aspnetcore/publishing/linuxproduction.md

I followed the [Host on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x) guide and the service did not start due to a permission error similar to one described [here](https://stackoverflow.com/q/47082358/280778
).
I looked into the source code and found that the problem can be avoided by not displaying the telemetry message. So I added the corresponding environment variable to the example to make the service work on a default nginx installation.

Updated example kestrel-hellomvc.service

---

aspnetcore/fundamentals/servers/aspnet-core-module.md
aspnetcore/publishing/iis.md

We have a better, more stable link to the hosting bundle installer now. We'll still need to keep an eye out for major version updates, but this will help us with the patch releases:
https://aka.ms/dotnetcore-2-windowshosting
Thanks @leecow! :rocket:

Hosting Bundle Link 2 ... The Sequel!

---

aspnetcore/security/authentication/social/google-logins.md

Update that dotnet Add Package is required only in ASPNET Core 1.x and not in 2.x

Update dotnet package version

---

aspnetcore/performance/response-compression.md

Updates the list of when to use Response Compression Middleware to avoid confusion on HTTP.sys and Kestrel supporting built-in compression features (i.e., they don't).

Update Response Compression Middleware topic

---

aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/tests/TestingControllersSample.Tests/TestingControllersSample.Tests.csproj
aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/tests/TestingControllersSample.Tests/xunit.runner.json

* Re-introduces the workaround for moving the `.deps.json` file from the tested project to the test project. Re-introduces disabling shadow copying.
* May as well update the package references while we're here.

Fix and update Testing Controllers sample

---

aspnetcore/mvc/models/validation.md

The section on using IValidatableObject was missing the Validate method signature and included an extra closing } 
The range was off by 1 on both sides.
Question: The first snippet sample for "Custom validation" looks weird because it contains the class name but not the closing } , not sure how to fix that though with the ?range syntax.

Adjust sample range to show method signature

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Utilities/FileHelpers.cs

RE: File Uploads section of RP tutorial (*FileHelper.cs*)
When the `StreamReader` chokes on bytes for a Unicode conversion, it throws a `DecoderFallbackException`:
> DecoderFallbackException: Unable to translate bytes \[97] at index 301 from specified code page to Unicode.
I recommend we catch a more general exception and then just report the error `Message` back to the user.
The result of this will look like this in the UI ...

Catch a more general exception and report it

---

aspnet/web-api/overview/getting-started-with-aspnet-web-api/using-web-api-with-aspnet-web-forms.md

[Internal Review Page](https://review.docs.microsoft.com/aspnet/web-api/overview/getting-started-with-aspnet-web-api/using-web-api-with-aspnet-web-forms?branch=pr-en-us-4899#add-client-side-ajax)

Missing  ContentPlaceHolder in master page

---

aspnetcore/fundamentals/logging/index.md

Came here for something else and noticed some double-spaces to 🔪.
I also 🌹 *beautified a table* 🌷 while I was here.

Remove double-spaces from logging topic

---

aspnetcore/hosting/directory-structure.md

Addresses https://github.com/aspnet/websdk/issues/152#issuecomment-348569871
Related: https://github.com/aspnet/AspNetCoreModule/issues/30
Based on the latest guidance for creating and deploying the *Logs* folder :sparkles: auto-magically :sparkles: that covers all manner of deployment strategies.
cc/ @vijayrkn @dasmulli
Thanks to @DaleMckeown and @gpcaretti.

Update guidance on creating the Logs folder

---

aspnetcore/fundamentals/servers/aspnet-core-module.md

Use the aka.ms url for downloading the .NET Core Windows Server Hosting bundle. This is the same link as on https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#install-the-net-core-windows-server-hosting-bundle

Windows Server Hosting bundle link : use aka.ms

---

aspnetcore/fundamentals/configuration/options/sample/Pages/Index.cshtml

Came here for something else and noticed that the `<form>` elements were leftover from a previous sample. This just deletes those elements (nothing POSTs here) and adjusts the indenting.

Sample update

---

aspnetcore/testing/integration-testing/sample/test/PrimeWeb.IntegrationTests/PrimeWeb.IntegrationTests.csproj
aspnetcore/testing/integration-testing/sample/test/PrimeWeb.IntegrationTests/xunit.runner.json
aspnetcore/testing/integration-testing/sample/test/PrimeWeb.UnitTests/PrimeWeb.UnitTests.csproj
aspnetcore/testing/integration-testing/sample/test/PrimeWeb.UnitTests/xunit.runner.json

Addresses #4943 
This fixes up the project files in the tests projects of the PrimeWeb sample:
* Provide for `shadowCopy: false`
* Copy the deps file per https://github.com/NuGet/Home/issues/4412.

PrimeWeb sample fix

---

aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Views/Todo/IndexFirst.cshtml

Remove an extra space from a div tag which appears in a code snippet in the View Components doc.

Remove extra space from div tag

---

aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md

'expires-after' example is fixed.

Incorrect 'expires-on' is changed to 'expires-after'

---

aspnetcore/data/ef-rp/crud.md

In the highlighted portion of new code to be added for the section "Display related enrollments on the Details page", the previous 3 lines (32-34) are not highlighted but they are new lines of code that the user should add.

Correct highlighted new code that needs to be added

---

aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md

Fixes https://github.com/aspnet/Docs/issues/4983
Also, fix the first example which is missing a slash in the closing tag.
[Internal Review Page](https://review.docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/built-in/cache-tag-helper?branch=pr-en-us-4984)

Convert Cache tags to lowercase

---

.openpublishing.publish.config.json

This is to fix the build error due to overlapping output path.

fix publish config due to overlapping output path

---

aspnetcore/tutorials/dotnet-watch.md

The doc here seems accurate, but the README install directions in the dotnet-watch repo looks incorrect. I don't see anywhere the notion of installing tools via `dotnet install tool dotnet-watch`. Perhaps unreleased feature? Or dead?

fixed broken links to dotnet-watch repo

---

aspnetcore/data/ef-rp/concurrency.md
aspnetcore/data/ef-rp/intro/samples/StageSnapShots/cu-part8/Pages/Departments/Edit.cshtml.cs
aspnetcore/data/ef-rp/intro/samples/cu/Pages/Departments/Edit.cshtml.cs

In the razorpages CU-8 there is misleading code that does not do anything in the handleDelete method. Deleted the method because the values displayed come from the ModelState not the Department instance.

Fixed confusing but harmless code that had no effect on the Page() display

---

aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Filters/DisableFormValueModelBindingAttribute.cs

Why don't we use the [`ValueProviderFactoryExtensions`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ValueProviderFactoryExtensions.cs) to cut the chatter?

Making use of the ValueProviderFactoryExtensions

---

aspnetcore/client-side/index.md
aspnetcore/spa/angular.md
aspnetcore/spa/index.md
aspnetcore/spa/react-with-redux.md
aspnetcore/spa/react.md
aspnetcore/spa/sample/AngularServerSideRendering/AngularServerSideRendering.csproj
aspnetcore/toc.md

We've now published version `2.0.0-rc1-final` of the SPA templates.
The final release should be soon (pending feedback) but this PR is to update the docs to reference the rc1 version in the meantime so people know they can try it.

Update SPA templates references to 2.0.0-rc1-final

---

aspnetcore/publishing/linuxproduction.md

Using `$host` only in HTTP header in Nginx config causes that Kestrel only knows that the host name is *hostname.com* **without any port**. That causes a problem in **redirecting** (e.g. to login page). The user will be directed to the hostname without any port (i.e. to 80 or 443 according to the schema HTTP or HTTPS respectively).
I added `$server_port` to HTTP request header in Nginx config, so the host name will become *hostname.com:8080*. That solves any related redirecting problems.
I am not sure if this is related to any opened issue.

Add port to to the header in Nginx config

---

aspnetcore/tutorials/web-api-help-pages-using-swagger.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/sample/TodoApi/Startup.cs

Enabling the XML documentation will throw __Missing XML comment for publicly visible type or member__ so I thought it's important to give a heads up in the documentation regarding that. Not sure if referencing this [stack overflow thread](https://stackoverflow.com/questions/203863/missing-xml-comment-for-publicly-visible-type-or-member) is something that could be done in the documentation (or maybe create tab style information area on how to ignore them per editor?)
Also I've updated the reading code to be explicit regarding Path.Combine (so you can just copy paste the code) and also replaced the directory path code PlatformServices.Default.Application.ApplicationBasePath using System.AppContext.BaseDirectory since [according to](http://michaco.net/blog/EnvironmentVariablesAndConfiguration …

add notice regarding undocumented methods notices and updated code

---

aspnetcore/fundamentals/hosting.md

Reacting to a reader comment:
> I can't figure out what "injecting IStartup directly into the dependency injection container" means.
Adding this inline code example should clarify what is meant there.

Add example to ArgumentException remark

---

aspnetcore/security/authorization/roles.md

On line 43 the 'Administrator' gets called a 'role' while at line 25 the 'Administrator' gets called a 'group'

Inconsistent usage of the 'role' word

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDAmult.cs

Fixes #5140
* Double double-quotes to escape double quotes in verbatim strings. (*Say that ten times fast.* lol)
* Move dash to end of the class.
Please close if DOA, as these expressions might be by-design.

Use double double-quotes for verbatim string literals in RP tutorial?

---

aspnetcore/mvc/views/razor.md

Because there is no VBHTML in ASP.NET Core.

Remove unneeded references to VB

---

aspnetcore/includes/RP/model4Win.md
aspnetcore/includes/RP/model4x.md

While going through the tutorial on Mac, I was confused by this wording. I assumed that "command window" was something that was part of Visual Studio.
It may be clearer (especially to newcomers) to be consistent with the wording that's only a few lines above "From the command line, run the following .NET Core CLI commands:".
This is just a suggestion, now I realize that the words "Open a command window" appear in many parts of the documentation.
Motivated by my conversation [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model#scaffold-the-movie-model) (click the livefyre comment icon).

Suggestion for better wording.

---

aspnet/visual-studio/overview/2012/index.md

SEO fix to disambiguate Visual Studio docs from ASP.NET docs

---

aspnetcore/fundamentals/url-rewriting.md

In the original, the character class will negate individual characters in brackets, but not the extension as desired. Fixed and tested regex using negative look ahead and negative look behind variations.

fix regex in url-rewriting.md

---

aspnetcore/data/ef-mvc/advanced.md

Standard case - "Some sentence referencing the [the link]".  
I left the link alone and removed the "the" from the sentence.

Removed a duplicate "the"

---

aspnetcore/fundamentals/configuration/index.md

:boom: Spotted a 404 in passing ... it's just missing a link segment.

Fix 404 link missing the "dotnet" segment

---

aspnet/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline.md

Typo fix 'pp.' to `app.` in Owin IIS Pipeline doc

---

aspnetcore/data/ef-rp/crud.md
aspnetcore/data/ef-rp/sort-filter-page.md
aspnetcore/fundamentals/logging/loggermessage.md
aspnetcore/includes/RP/page1.md
aspnetcore/mvc/razor-pages/index.md
aspnetcore/mvc/razor-pages/razor-pages-convention-features.md
aspnetcore/tutorials/razor-pages/uploading-files.md

I avoid using "page model file" in many spots where it was "code-behind file." It seems sufficient to just state "page model."

Remove code-behind from RP terminology

---

aspnet/signalr/overview/getting-started/supported-platforms.md

_Windows 10_ has not been mentioned in the _Supported Platforms_ for SignalR. That has been added.

Added missing operating system

---

aspnetcore/fundamentals/url-rewriting/samples/1.x/README.md
aspnetcore/fundamentals/url-rewriting/samples/2.x/README.md

Based on the actual code, the following README documentation needs to be consistent.

Fix minor readme typos for AddRedirect function sample.

---

aspnetcore/fundamentals/environments.md

Code block was labeled as XML instead of JSON, and added the type to another code block for consistency

Change label from XML to JSON

---

aspnetcore/security/authentication/cookie.md
aspnetcore/security/authentication/cookie/sample/Pages/Account/Login.cshtml.cs

John Hargrove remarked on the topic that the establishment of a ClaimsPrincipal wasn't adequately addressed by the topic. I took a closer look, and there's an inline code snippet that doesn't do ClaimsPrincipal/ClaimsIdentity justice. This brings the sample's code into the topic to showcase that setup better.
cc/ @HaoK :point_right: [Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?branch=pr-en-us-5307&tabs=aspnetcore2x#creating-an-authentication-cookie)

Cookie auth w/o Identity: Tie sample code (sign in) into the topic

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Utilities/FileHelpers.cs
aspnetcore/tutorials/razor-pages/uploading-files.md

Fixes #5160 
[Internal Review Topic (Security considerations)](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?branch=pr-en-us-5244#security-considerations)
[Save the file to disk](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?branch=pr-en-us-5244#save-the-file-to-disk)
Save file to Azure Blob Storage: Immediately under the *Save the file to disk* section. :point_up:
Decided we should try a general security section with this update.
@blowdart Need ur wisdom here sir. :beer:

Add content for saving to disk and Azure blob storage

---

aspnetcore/fundamentals/logging/loggermessage.md

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?branch=pr-en-us-5329)
@syscall implies that the implementation details of `Define` and `DefineScope` should appear next to their definitions (and API links).
The reason the topic has its current layout is that the message template applies to both methods and is worthy of highlighting immediately after the concept of a message template is introduced. To avoid duplication of that text, the topic was created with this structure:
1. Define the methods
1. Describe the message template
1. Describe the implementations
**This PR is is test.**
Let's see how it looks if I group the implementations with the definitions and go ahead and duplicate the message template information. I'm not …

Restructuring of the LoggerMessage topic

---

aspnetcore/mvc/models/validation.md

The code samples added while fixing #4752 attempted to use the jQuery [`removeData()`](https://api.jquery.com/removeData/) function on a vanilla FormElement.  As pointed out in a comment by user Allen_Wang1 on the [Add Validation to Dynamic Controls](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation#add-validation-to-dynamic-controls) section of the Model Validation docs page, this results in an `Uncaught TypeError`.  This PR fixes that error.

Fixed a jQuery error on the Model validation page

---

aspnetcore/spa/index.md
aspnetcore/spa/sample/AngularServerSideRendering/AngularServerSideRendering.csproj

Hopefully the final release will be in the next week, but in the meantime it's useful to update the docs so people try out the new RC2 build.

Update SPA templates references to 2.0.0-rc2-final

---

aspnetcore/performance/caching/middleware.md

The source indicates that using `*` as a single value in VaryByQueryKeys is also valid.
See https://github.com/aspnet/ResponseCaching/blob/release/2.0/src/Microsoft.AspNetCore.ResponseCaching/Internal/ResponseCachingKeyProvider.cs#L165

Update caching documentation for VaryByQueryKeys

---

aspnetcore/data/ef-rp/read-related-data.md

For collections it uses... : add comma
Does 'Eager loading for the `Course` entities and their related `Department` entities is used' means 'Eager loading is used for the `Course` entities and their related `Department` entities'?
'related data from the `Enrollments` entity is displayed' => may be 'are displayed' ?
'clicking on the **Select** link for an instructor when the page directive produces a URL like the following': There must be some missing words.

Typos in ef-rp/read-related-data.md

---

aspnetcore/security/authorization/policies.md
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Handlers/PermissionHandler.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Requirements/DeletePermission.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Requirements/EditPermission.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Requirements/ReadPermission.cs

Fixes https://github.com/aspnet/Docs/issues/5017
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?branch=pr-en-us-5445#what-should-a-handler-return)

Mention InvokeHandlersAfterFailure property in policy auth doc

---

aspnetcore/security/authorization/secure-data.md
aspnetcore/security/authorization/secure-data/samples/final2/Startup.cs
aspnetcore/security/authorization/secure-data/samples/final2/appsettings.Development.json

Fixes #5452 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?branch=pr-en-us-5451#require-authenticated-users)

remove AuthorizeFolder in secure user data

---

aspnetcore/fundamentals/hosting.md

This surfaces `StopApplication` with a quick RP example. Feels like this method won't be very useful outside of debugging scenarios, but it might be good to show how it can be used to gracefully shutdown an app from a web app UI. Because this probably releases locked files, it might be useful in some deployment scenarios.

Add example IApplicationLifetime.StopApplication

---

CONTRIBUTING.md

Suggestion: Placed into its own section here because it goes beyond "voice and tone."
Note that the voice and tone doc pushes conversational tone and 2nd person more than I think we're actually embracing here. It might be best to carve out active voice, reading level, future tense, and the note at the end for this doc and drop the link to the voice and tone doc ... let me know.
[Voice and tone doc](https://github.com/dotnet/docs/blob/master/styleguide/voice-tone.md)

Surface the new public style manual

---

aspnetcore/fundamentals/logging/loggermessage.md
aspnetcore/fundamentals/logging/loggermessage/sample/Program.cs

Per @davidfowl ... devs might start doing something like this all the time. It was here to clean up the output so that the messages are super-easy to see; but if it shows a foul pattern, then it should go.

Remove log filtering from Logger Message samp

---

aspnetcore/fundamentals/servers/aspnet-core-module.md

We need a good link point in the topic for the hosting bundle installer that clearly describes what's in the bundle.
I've also opened [Servers > ANCM UE pass (\#5490)](https://github.com/aspnet/Docs/issues/5490) ... this topic needs a pass.

Add hosting bundle installer desc to ANCM topic

---

aspnetcore/includes/mvc-intro/adding_view2.md

Mvc Movie changed to Movie App, since anchor text on layout was change from MvcMovie to Movie App on Index.cshtml file

Typo error updated

---

aspnetcore/mvc/razor-pages/razor-pages-convention-features.md

@Syscall asked about the use of the word "conventions" in the topic. This PR links it over to :point_right: https://docs.microsoft.com/aspnet/core/mvc/controllers/application-model#conventions
@pranavkm Is it safe to do this, since the *Conventions* section might not take into account differences between MVC and RP?
This also:
* Changes the sample app link to our standard format.
* Surfaces where the conventions are established on the first example shown with a link to the sample app.

Link "conventions" language to the app model topic

---

aspnetcore/fundamentals/configuration/index.md

React to https://github.com/aspnet/Configuration/issues/770
@HaoK Would u like to address that in the topic? It's true that if one tries to do this ...
```csharp
Configuration["wizard:1:age"]
```
... it won't work with XML.

Surface XML array indexing for Configuration

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/hosting.md

Fixes #3660 
[Internal Review Topic (DI)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-5507#scope-validation)
[Internal Review Topic (Hosting)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?branch=pr-en-us-5507#scope-validation)
@pakrym The docs don't describe the "root provider" anywhere. I don't think we can put this up without briefly describing it and why scoped services shouldn't be resolved from it. If you'll provide a few notes, I'll wordsmith them in here.

DI scope validation enabled by default

---

aspnetcore/host-and-deploy/iis/index.md

Fixes #5454 
I checked using a fresh VM, `OPT_INSTALL_LTS=0` no-ops (the runtime and store are installed). The only working switch at the moment (apparently) is `OPT_INSTALL_X86`.

Add hosting bundle installer switch note

---

aspnetcore/fundamentals/hosting.md

Per reader feedback, add detail on `shutdownTimeoutSeconds` to *Hosting in ASP.NET Core*.
[Reference Source (`StopAsync`)](https://github.com/aspnet/Hosting/blob/4f3fdaebeebbe4481ec00e4790da1758a6aa02ea/src/Microsoft.Extensions.Hosting/Internal/Host.cs#L60-L103)
Thanks to @DrSensor for reporting.

Add detail on shutdownTimeoutSeconds in Hosting

---

aspnetcore/index.md

[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/index?branch=pr-en-us-5571)

Landing page - explain full .NET Framework.

---

CONTRIBUTING.md

The link to Microsoft Writing Style Guide was pointing to `/style-guide/welcome/` path that does not exist in this project's repository. As I have not found the GitHub project that contains the source for Microsoft Writing Style Guide, I modify the link to point to the published version at Microsoft website.

Fix link to writing style guide in CONTRIBUTING.md

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Pages/Movies/Index.cshtml.cs

This PR tries to ensure consistent use of `IList` interface for declaring collection of `Movie` in tutorial about Razor Pages.
The code snippet displayed in ["Adding search to ..."](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search) was using `List` class instead of `IList` interface when declaring `Movie` collection in Movie's page model. It was different from previous step of the tutorial (i.e. ["Scaffolded Razor Pages ..."](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page) where `Movie` collection was declared using `IList` interface. 
Additionally, `Schedule` page model already using `IList` for declaring the collection of schedule in the index page.

Make consistent use of IList in Movie page model

---

CONTRIBUTING.md

cla2.dotnetfoundation.org link is returning a 404.  Changing this to cla.dotnetfoundation.org takes it to a page about the CLA.  Found this while trying to figure out how to commit to this repo.  Figured this probably should be fixed.

Updating CLA link from cla2 to cla

---

aspnetcore/signalr/get-started-signalr-core.md

Fixes https://github.com/aspnet/Docs/issues/5620

Convert SignalR Prereqs section's h1 heading to h2

---

aspnetcore/mvc/razor-pages/razor-pages-convention-features.md
aspnetcore/mvc/razor-pages/razor-pages-convention-features/sample/Conventions/GlobalTemplatePageRouteModelConvention.cs

The current route order (0) causes that generating links (ie. using tag helpers) does not work. Proposing fix after consultation with @pranavkm.

Changed route order

---

aspnetcore/mvc/controllers/actions.md
aspnetcore/mvc/razor-pages/index.md
aspnetcore/tutorials/first-mvc-app/start-mvc.md

Addresses #5649 
This topic is the landing page for a reader arriving along the chain of links starting with `https://dot.net` (`https://www.microsoft.com/net`). In addition to the current link allowing a reader to get out to the *Get started with RP* page, I suggest we provide an additional circuit breaker that will allow the reader to get out to the doc set's main landing page.

Surface the intro topic in the RP tutorial

---

aspnetcore/security/authentication/community.md

This may or may not be desired, but this link used to go to this page: https://identityserver4.readthedocs.io/en/release/, but now goes to the Identity Server 4 home page. You have to make extra clicks to get to the tutorial.

Identity Server Link to Original Tutorial

---

aspnet/ajax/cdn/overview.md

Do not know if there is an issue yet, but bootstrap 4.0.0 has js on the aspnet cdn. No CSS yet though. Do not know who to contact for the CSS but the docs should list the js because it is available.
edit: my bad, 4.0.0 css is there too. It's the theme which is not there. http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap-theme.css

added bootstrap 4.0.0 js but no css yet?

---

aspnetcore/signalr/get-started-signalr-core/sample/Hubs/ChatHub.cs
aspnetcore/signalr/get-started-signalr-core/sample/wwwroot/js/chat.js

I followed this example today and was getting this error:
I realized that this example omits the method name `Send`, and it is passing `timestamp` as the method name instead (when that should be the first argument)
Here is the function deceleration, it requires method name:
```
/// <summary>
/// Invokes a method on the connection(s) represented by the <see cref="T:Microsoft.AspNetCore.SignalR.IClientProxy" /> instance.
/// Does not wait for a response from the receiver.
/// </summary>
/// <param name="clientProxy">The <see cref="T:Microsoft.AspNetCore.SignalR.IClientProxy" /></param>
/// <param name="method">name of the method to invoke</param>
/// <param name="arg1">The first argument</param>
/// <param name="arg2">The second argument</param>
/// <returns>A task that represents when the …
```

SignalR Example: add method to ChatHub broadcast

---

aspnetcore/security/authentication/identity.md
aspnetcore/security/authentication/identity/sample/src/ASPNET-IdentityDemo-PrimaryKeysConfig/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNET-IdentityDemo/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNETv2-IdentityDemo-Configuration/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNETv2-IdentityDemo-PrimaryKeysConfig/Startup.cs
aspnetcore/security/authentication/identity/sample/src/ASPNETv2-IdentityDemo/Startup.cs

Fixes #5615 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?branch=pr-en-us-5666)
The engineers decided not to change the template ([2.1 ref source](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Controllers/AccountController.cs#L104) and [comment \#5615](https://github.com/aspnet/templating/issues/88#issuecomment-370969013)). In effect, the template is set up so that the `LogOff` method performs a hard `RedirectToAction` to the Home controller `Index` method. Therefore, setting the `LogoutPath` option no-ops, which might be unexpected behavior given that the doc is showing how to set it.
I added the note on this to the code, and I think it should stay with the …

Remove LogoutPath from cookie options in Identity topic

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fix the metadata in the 2 Web API help pages docs.

Fix metadata in Web API help pages docs

---

aspnetcore/fundamentals/logging/index.md

There was a link in the document pointing towards the documentation for CreateDefaultBuilder but it was broken so I updated it with the right one.

Fixed link for CreateDefaultBuilder docs

---

aspnetcore/fundamentals/configuration/index.md

Fixes #5731 
It takes considerably more lines of code to show full examples of each. It could be shown quickly in one code block. However, *Fundamentals* is above MVC/RP topics. It's nice for new devs to see explicit examples in fundamentals topics if they skip *Tutorials* and just start reading.
Alternatively, we could show one block of:
```cshtml
// Add directives to the top of the page or view
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
// Access the value with Razor syntax
<p>Configuration[&quot;key&quot;]: @Configuration["key"]</p>
```
[EDIT] Thought it over 🤔 ... I'd be happy with it either way. Let me know which way you want to go. @rachelappel plz TAL, too.

Demonstrate how to access config in a RP page and MVC view

---

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

... and I fixed a couple of section headings.
[Internal Review Topic (links directly to new section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?branch=pr-en-us-5733#publish-to-a-server-using-an-untrusted-certificate)

Surface AllowUntrustedCertificate for MSDeploy

---

aspnetcore/mvc/views/dependency-injection.md

Currently the highlight is mapping the operation of GetAveragePriority on the incorrect line:
The correction is to highlight the previous line.
*** Files no issue since its a minor correction, apologies.

Update highlight on dependency-injection.md

---

aspnet/web-forms/overview/older-versions-getting-started/master-pages/specifying-the-master-page-programmatically-cs.md

Corrected the typo error on line #137 (Alternate.master)
No Issue is related to this fix.

Typo fix on specifying-the-master-page-programmatically-cs.md

---

aspnetcore/fundamentals/dependency-injection.md

@rynowak Catching up on standups and caught your and @jongalloway's remarks. We use this approach today to init dBs. However, I made this generic in light of https://docs.microsoft.com/ef/core/modeling/data-seeding. Our samples might be heading that way, and I suspect it will be the suggested approach in the future for dB init.

Get a scoped service within the app scope

---

aspnet/web-api/overview/web-api-routing-and-actions/create-a-rest-api-with-attribute-routing.md

Typo fix in REST API Attribute routing guide

---

aspnetcore/fundamentals/configuration/options.md

Reader feedback from @Baharestani ...
> The first line is referring to something called "option classes" which doesn't make any sense to a reader who is not familiar with Options Pattern.
The use of "options class" now first appears on line 29 where it's defined.
Thank you @Baharestani for pointing this out. :rocket:

Update first two lines of Options pattern topic

---

aspnetcore/tutorials/razor-pages/model.md

[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?branch=pr-en-us-5886#add-scaffold-tooling-and-perform-initial-migration)

Updated with NET Core SDK 2.0  commands

---

aspnetcore/signalr/get-started/sample/Hubs/ChatHub.cs
aspnetcore/signalr/get-started/sample/Pages/About.cshtml.cs
aspnetcore/signalr/get-started/sample/Pages/Contact.cshtml.cs
aspnetcore/signalr/get-started/sample/Pages/Error.cshtml.cs
aspnetcore/signalr/get-started/sample/SignalRChat.csproj
aspnetcore/signalr/get-started/sample/Startup.cs
aspnetcore/signalr/get-started/sample/wwwroot/js/chat.js

Great tutorial! The sample embeds user content directly into the page which allows for clicked javascript to take over the browser. (send message `<a href="javascript:document.write("rooted");">here</a>`). I propose a quick fix by using the textContent or innerText instead of innerHtml to set the message. Also following the tutorial the app runs great but the example download has a namespace error and dependency errors. (It wouldn't run without the update. 
Also, just out of curiosity why are folders like the lib folder excluded? Are you trying to save space on github?

Prevent javascript injection.

---

aspnetcore/toc.md

Convert the **JavaScript Client** TOC node to sentence case for consistency

Convert TOC title to sentence case

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #5264 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-1.0&branch=pr-en-us-5949)
In the <=2.0 and >=2.1 rendered table content, you only need to look at the `requestTimeout` row *Description* column content.

React to ANCM requestTimeout change for 2.1

---

aspnetcore/web-api/action-return-types.md

Eliminates the awkward line break before the 3rd list item in the following doc:
https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1

Fix unordered list formatting with monikers

---

aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md

Adds the 2.1 preview note to the Partial Tag Helper doc

Add 2.1 note to Partial Tag Helper doc

---

aspnetcore/fundamentals/servers/aspnet-core-module.md
aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/iis/index.md

Fixes #5891 
* Add a bit more info to the IIS config topic
- The path must exist
- The app pool must have permission to write to the location
* Add a bit of content with an explicit example of the user identity to the linked ANCM ref topic (and re-organize a bit)
Thanks to @Scott_Moses for the heads-up.

stdout log instructions enhancement

---

aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/TagHelpersBuiltIn.csproj

Removes a deprecated DotNetCliToolReference from the CSPROJ file. It has been replaced by a .NET Core CLI global tool.

Remove deprecated DotNetCliToolReference node

---

aspnetcore/host-and-deploy/iis/modules.md

Fixes #5844 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules?branch=pr-en-us-5873)
* Adds notes on two modules that aren't strictly speaking "required" for an ASP.NET Core app to run in reverse proxy with IIS but whose perf is affected when the module isn't active.
* Refactors the managed modules table to remove a column (and adds a line of text).
* Renames a column (and adds a line of text) for the native modules column.
* Corrects a mistake with a module name.
* Remove the config code to disable "default" IIS modules because that's too variable really to be effective given how variable module config will be server-to-server and organization-to-organization.
Thanks to @bangbingsyb :rocket: for highlighting the problems with the …

Update IIS Modules topic

---

aspnetcore/client-side/spa-services.md

Running the command in the project root complains that no package.json can be found. You have to run the command from the ClientApp directory where the package.json is located also indicated in the instructions on the splash page "The ClientApp subdirectory is a standard Angular CLI application. If you open a command prompt in that directory, you can run any ng command (e.g., ng test), or use npm to install extra packages into it."

npm test directory wrong

---

aspnetcore/mvc/razor-pages/razor-pages-convention-features.md
aspnetcore/mvc/razor-pages/razor-pages-convention-features/sample/README.md

Fixes #5520 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/razor-pages-convention-features?view=aspnetcore-2.0&branch=pr-en-us-5961)
* I can't see the built topic, please check rendering on review.
* I've added a note to the [Sample Update Tracking Issue](https://github.com/aspnet/Docs/issues/5495) to add `IPageHandlerModelConvention` to the sample when it's upgraded to 2.1.
To speed up review of the table, the major change there (in the *Model Conventions* row) is
\<= 2.0
* IPageRouteModelConvention
* IPageApplicationModelConvention
\>= 2.1
* IPageRouteModelConvention
* IPageApplicationModelConvention
* IPageHandlerModelConvention

RP conventions topic update

---

aspnetcore/fundamentals/primitives/change-tokens/sample/Utilities/Utilities.cs

The original would loop infinitely if the file doesn't exist. (bug).
Now, private void InvokeChanged(IHostingEnvironment env) should invoke computenhash() in a try catch... I could add that if desired

fixed infinite loop error

---

aspnetcore/mvc/views/razor.md

There's a broken link here.
There's a rendering problem with the `@`-prefixed link text in the table. https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#tag-helpers
We can try an HTML entity code for the `@` symbol as a workaround. I won't be able to see it on the built site, so someone will need to look and say if it worked. If that doesn't work, we can also try the HTML code (`&#64;`).
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-1.0&branch=pr-en-us-5992)

Broken and malformed links

---

aspnetcore/fundamentals/primitives/change-tokens/sample/Utilities/Utilities.cs

Same infinite loop error in 2nd example. Also, three links titled reference source linking to core 2.0.1 are now dead. The first on the page works.

Utilities.cs infinite loop

---

aspnetcore/data/ef-rp/migrations.md

Fix a typo: 'the DB exits' -> 'the DB exists'

---

aspnetcore/signalr/get-started.md

Resolves: [Signalr.js not found](https://stackoverflow.com/q/50053462/8601760)

Add step for vscode to signalr get started doc

---

aspnetcore/tutorials/first-web-api-mac.md
aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/web-api-vsc.md

Add the ASP.NET Core 2.1 Preview banner to the top of each Web API tutorial (only when v2.1 is selected). This makes it even clearer to the reader that v2.1 is selected in the version selector.
**Internal Preview Pages**
* [VS Code](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1&branch=pr-en-us-6156)
* [VS for Mac](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac?view=aspnetcore-2.1&branch=pr-en-us-6156)
* [VS](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1&branch=pr-en-us-6156)

Add 2.1 preview notice to Web API tutorials

---

aspnetcore/fundamentals/http-requests.md

The code sample and explaining text appear to be out of sync. This is a correction of the reference made to a function name in the surrounding text of the sample.

Correct Code Sample Method Reference

---

aspnetcore/fundamentals/configuration/options.md

The extension method in the sample app is different from the linked api page. I was trying to figure something unrelated out, and got confused. Strangely, the same thing occurs in another above link (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.iconfigureoptions-1) which is the wrong api but I didn't fix it because the autogenerated api doesn't have the correct extension method where it should [be] (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.configure?view=aspnetcore-2.0&viewFallbackFrom=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_OptionsServiceCollectionExtensions_Configure__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Action___0__)

wrong api link

---

aspnetcore/security/authentication/identity-custom-storage-providers.md

Fixes #6207
`Microsoft.AspNet.Identity.CoreCompat` API is [in the `/aspnet/core` API browser](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnet.identity.corecompat). Did these move to the [Microsoft.AspNetCore.Identity namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity?view=aspnetcore-2.0)? The `.CoreCompat` namespace is present in the Identity repo: https://github.com/aspnet/Identity/tree/dev/src/AspNetCoreCompat
@HaoK @dend - These links changed when a [recent batch were updated (\#6149)](https://github.com/aspnet/Docs/pull/6149) to use the `/dotnet` API browser. Let me know if these reversions back to their prior URLs should be taken another way. Perhaps unrelated, but I see ["legacy API" in …

Broken CoreCompat API links

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md
aspnetcore/security/authorization/index.md

Adds a page to ASP.NET Core Security/Authorization docs covering how to use `IAuthorizationPolicyProvider` to dynamically generate authorization policies.
Fixes #6111 
`[rick edit]` [Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-1.0&branch=pr-en-us-6185)

IAuthorizationPolicyProvider documentation

---

aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/includes/2.1.md
aspnetcore/mvc/razor-pages/razor-pages-conventions.md
aspnetcore/mvc/razor-pages/sdk.md
aspnetcore/mvc/razor-pages/ui-class.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/tutorials/first-web-api-mac.md
aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/web-api-vsc.md

2.1 RC1 has a run live licence
remove
-> [!NOTE]
-> ASP.NET Core 2.1 is in preview and not recommended for production use.

remove not for production

---

aspnetcore/signalr/hubs.md

Ref to the wrong line in the code example, required is
line 38 => services.AddSignalR();
https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md
page
https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1
@rachelappel

Code ref incorrect, use line 38 instead => services.AddSignalR();

---

aspnetcore/signalr/index.md

The **Publish to Azure** link, which is present in the ToC, was missing from the index page.

Add Publish to Azure link to SignalR index page

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fixes https://github.com/aspnet/Docs/issues/6310
**Internal Review Pages**
* [Swashbuckle](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.0&branch=pr-en-us-6319&tabs=visual-studio%2Cvisual-studio-xml)
* [NSwag](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.0&branch=pr-en-us-6319&tabs=visual-studio%2Cvisual-studio-xml)

Add sample app download links to help page tutorials

---

aspnetcore/tutorials/first-web-api/samples/2.1/TodoApi/TodoApi.csproj

Remove the `Version` attribute from the ASP.NET Core 2.1 metapackage reference element. This is the sample app used by the 3 web API tutorials.

Simplify 2.1 metapackage reference

---

aspnetcore/mvc/controllers/routing/sample/main/NamespaceRoutingConvention.cs
aspnetcore/mvc/controllers/routing/sample/main/WebMvcRouting.csproj

Some of the controllers don't have a namespace so this allows the project to run.

fix null ptr in routing

---

aspnetcore/fundamentals/servers/weblistener.md

As per commit - Fix a missing quote from an example command.

Add missing quotation mark to ssl binding command

---

aspnetcore/signalr/hubs.md

The methods below aren't defined at the `Hub` class but accessible through `Clients` property like the first three properties (`All`, `Caller`, `Others`) :
| `AllExcept` | Calls a method on all connected clients except for the specified connections |
| `Client` | Calls a method on a specific connected client |
| `Clients` | Calls a method on specific connected clients |
| `Group` | Sends a message to all connections in the specified group  |
| `GroupExcept` | Sends a message to all connections in the specified group, except the specified connections |
| `Groups` | Sends a message to multiple groups of connections  |
| `OthersInGroup` | Sends a message to a group of connections, excluding the client that invoked the hub method  |
| `User` | Sends a message to all connections associated …

Those methods are not defined at the Hub class

---

aspnetcore/tutorials/razor-pages/search.md

Since the searching method in SQLite is case-sensative, the example should pass the search string in the correct case.

Capitalize search string 'Ghost' in URL segment

---

aspnetcore/fundamentals/metapackage-app.md
aspnetcore/fundamentals/metapackage.md

Fixes  #5884 
[M.A.App review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1&branch=pr-en-us-6069)
[M.A.ALL review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.0&branch=pr-en-us-6069)

Microsoft.AspNetCore.App metapackage

---

aspnetcore/testing/troubleshoot.md

partial warning

---

aspnet/mvc/overview/older-versions/hands-on-labs/aspnet-mvc-4-entity-framework-scaffolding-and-migrations.md
aspnet/mvc/overview/older-versions/hands-on-labs/aspnet-mvc-4-fundamentals.md
aspnet/mvc/overview/older-versions/hands-on-labs/aspnet-mvc-4-models-and-data-access.md
aspnet/mvc/overview/older-versions/hands-on-labs/whats-new-in-aspnet-mvc-4.md
aspnet/web-api/overview/older-versions/build-restful-apis-with-aspnet-web-api.md
aspnet/web-forms/overview/getting-started/creating-a-basic-web-forms-page.md
aspnet/web-forms/overview/getting-started/hands-on-labs/whats-new-in-aspnet-and-web-development-in-visual-studio-2012.md
aspnet/web-forms/overview/getting-started/hands-on-labs/whats-new-in-web-forms-in-aspnet-45.md

Follow-up to https://github.com/aspnet/Docs/pull/6426. This PR removes them.
Yes, there were 20 that wrapped `[!NOTE]` blocks and text with a code block, which I imagine would also break localization.

Remove triple-tildes from aspnet topics

---

aspnetcore/fundamentals/metapackage.md
aspnetcore/fundamentals/metapackage/samples/Metapackage.All.Example.csproj
aspnetcore/mvc/views/view-compilation.md
aspnetcore/mvc/views/view-compilation/sample/DotNetFrameworkProject.csproj
aspnetcore/mvc/views/view-compilation/sample/MvcRazorCompileOnPublish.csproj

Fixes #5408
**Changes**
- Make the doc unavailable for ASP.NET Core 1.0, where precompilation isn't supported
- Replace tabs with versioning monikers
- Move an unused *.csproj* file from the *sample* folder to a *samples* folder for the metapackage doc using it
- Address Acrolinx suggestions, Gauntlet warnings, and Markdownlint warnings
- Add headings to improve readability
- Add an **Additional resources** section
**Internal Review Pages**
* [ASP.NET Core 1.1](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-1.1&branch=pr-en-us-6464)
* [ASP.NET Core 2.0](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.0&branch=pr-en-us-6464)
* [ASP.NET Core …

UE edit of Razor file compilation doc

---

aspnetcore/security/app-secrets.md

Per a discussion with a customer, it wasn't clear that the `AddUserSecrets` call is unnecessary in 2.x.
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/security/app-secrets?branch=pr-en-us-6488&view=aspnetcore-2.0#access-a-secret)

Add note about AddUserSecrets in 2.x

---

aspnetcore/host-and-deploy/linux-nginx.md

`[Edit by @rick-anderson]`
added:
**Note:** Linux has a case-sensitive file system. Setting ASPNETCORE_ENVIRONMENT to "Production" results in searching for the configuration file *appsettings.Production.json*, not *appsettings.production.json*.

Fix format

---

aspnetcore/fundamentals/logging/index.md

While other 3rd party providers supplied with their github source, to keep it consistent, I suggest to change JSNLog ones as well.

JSNLog url changed to github link

---

aspnet/web-forms/overview/deployment/configuring-server-environments-for-web-deployment/configuring-a-web-server-for-web-deploy-publishing-remote-agent.md

Hello, @jrjlee,
Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  

C19395: Missing hyperlink due to incorrect format

---

aspnetcore/host-and-deploy/iis/index.md

Surface that the preview runtime may have "rc" (Release Candidate) in its link text.

Update Hosting Bundle instruction

---

aspnetcore/security/app-secrets.md

Fixes https://github.com/aspnet/Docs/issues/6523
**Changes**
- Display the **Install the Secret Manager tool** section for all versions of ASP.NET Core, since it's not safe to assume the .NET Core SDK version being used.
- Include the specific SDK version number which includes the Secret Manager tool
- Add note about tool warning
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/security/app-secrets?branch=pr-en-us-6564&view=aspnetcore-2.0&tabs=windows#install-the-secret-manager-tool)

Clarify SDK version containing Secret Manager tool

---

aspnetcore/spa/angular.md
aspnetcore/spa/index.md
aspnetcore/spa/react-with-redux.md
aspnetcore/spa/react.md

Fixes https://github.com/aspnet/Docs/issues/6603
**Changes**:
- Make the SPA template docs available for ASP.NET Core 2.0+ only
- Display the template inclusion banner in each doc for 2.0 only
**Internal Review Pages**:
- [ASP.NET Core 2.0](https://review.docs.microsoft.com/en-us/aspnet/core/spa/?branch=pr-en-us-6604&view=aspnetcore-2.0)
- [ASP.NET Core 2.1](https://review.docs.microsoft.com/en-us/aspnet/core/spa/?branch=pr-en-us-6604&view=aspnetcore-2.1)

Display SPA docs for 2.0+ and display banners for 2.0 ONLY

---

aspnetcore/security/authorization/secure-data/samples/final2/Pages/Account/ForgotPassword.cshtml.cs
aspnetcore/security/authorization/secure-data/samples/final2/Pages/Account/ForgotPasswordConfirmation.cshtml.cs

Previously it was impossible to navigate to these pages unless logged in which makes no sense if you are trying to reset your password.

Added missing AllowAnonymous to ForgotPassword and ForgotPasswordConfirmation

---

aspnetcore/host-and-deploy/iis/index.md

UseIISIntegration is not mentioned in the preceding code snippet, but is actually called by CreateDefaultBuilder. Reworded slightly to clarify.

Made it clear that UseIISIntegration is called by CreateDefaultBuilder

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/host-and-deploy/proxy-load-balancer.md

Fixes #5806 
Addresses #6538
The Apache config for setting the `X-Forwarded-Proto` header is based on general Net sources. Their official docs are weak on the point, referring only to the `RequestHeader` directive.

Forwarded headers updates for Nginx/Apache topics

---

aspnetcore/fundamentals/error-handling.md

Add RP page example to Error Handling topic

---

aspnetcore/client-side/using-browserlink.md

Upgrading an ASP.NET Core project from 2.0 to 2.1 requires one to manually add the BrowserLink package.

Update BrowserLink instructions for 2.0 to 2.1

---

aspnetcore/aspnetcore-2.0.md
aspnetcore/aspnetcore-2.1.md
aspnetcore/toc.md

Per Dan, create a top-level "What's new" ToC node. This node will ONLY display when version 2.1 is selected. Also, convert the release notes links into "What's new" links. The two external release notes links can be removed.
**Internal Review Pages**
[2.1](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1&branch=pr-en-us-6690)
[2.0](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.0&branch=pr-en-us-6690)
[1.1](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-1.1&branch=pr-en-us-6690)

Create a "What's new" ToC node

---

aspnetcore/includes/2.1-SDK.md

Addresses https://github.com/aspnet/Docs/issues/6700
Now that 2.1 has released, the RC1 text should be removed from the download link.

Remove RC1 text from 2.1 SDK download link

---

aspnetcore/mvc/razor-pages/ui-class.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/signalr/get-started.md

The original changes for these three topics were safe because the `dotnet new` commands were either already inside a moniker-range for 2.1+ or the whole topic was set for 2.1+.

Repair Enforcing SSL topic moniker range

---

aspnetcore/getting-started.md

Fixes https://github.com/aspnet/Docs/issues/6700
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/getting-started?branch=pr-en-us-6748&view=aspnetcore-2.1)

Change .NET Core SDK version text when 2.1 is selected

---

aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample12.cs

With this sample for strongly typed hub, we get the error "All client proxy methods must return 'System.Threading.Tasks.Task'"
This PR fixes that error.

Fixing client method return type

---

aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/Program.cs

Fixes #6765 
Cross-ref: https://github.com/aspnet/Hosting/issues/1440#issuecomment-393698716
More closely matches `CreateDefaultBuilder` for the Web Host, where settings files go first, then env vars, followed by command line args.
cc/ @chrisckc

Move env var config down in Generic Host sample

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup1x.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/TodoApi.csproj

Addresses https://github.com/aspnet/Docs/issues/6686 (still need to address deployment concerns)
Addresses https://github.com/aspnet/Docs/issues/5495
**Changes**
- Update 2.1 sample app from RC1 to RTM
- Simplify sample app download link markup
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-1.1&branch=pr-en-us-6761#add-and-configure-swagger-middleware)

Fix Swashbuckle tutorial for 1.x apps

---

aspnetcore/fundamentals/metapackage.md

The link in the note that was supposed to be to the new metapackage was instead to the same page that contained the note.

Fix link to metapackage

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/security/enforcing-ssl.md

Fixes #6792 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-1.0&branch=pr-en-us-6793)
One thing right off the bat. The third entry is *terribad* ...
> To specify an HTTPS port:
>
> * Set [HttpsRedirectionOptions.HttpsPort](/dotnet/api/microsoft.aspnetcore.httpspolicy.httpsredirectionoptions.httpsport). See the preceding example that shows how to set the port to 5001.
> * Set the `HTTPS_PORT` environment variable.
> * The middleware uses the port or ports defined by [IServerAddressesFeature.Addresses](/dotnet/api/microsoft.aspnetcore.hosting.server.features.iserveraddressesfeature.addresses).
What should it say about port discovery from the `IServerAddressesFeature.Addresses`?
cc/ @k3davis

Enforce HTTPS update

---

aspnetcore/fundamentals/configuration/options.md
aspnetcore/fundamentals/configuration/platform-specific-configuration.md
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/primitives/change-tokens.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/performance/response-compression.md

A set of package language updates (and a few other nits) to the prior sample+topic updates.
I have a pattern going for the "App" package mentions:
If the link goes to the package on NuGet, I use ...
> \[Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App/)
If the link goes to our topic, I use ...
> \[Microsoft.AspNetCore.App metapackage](xref:fundamentals/metapackage-app) (ASP.NET Core 2.1 or later)
I won't be using the "All" package or mentioning it.

Package language updates

---

aspnetcore/mvc/razor-pages/ui-class.md

RCL projects should not end in ".Views"

---

aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on.md

Hello, @Rick-Anderson,
Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  
From the context of this source string, we can assume that writer did not intend this example URL to be rendered as hyperlink, and that text "App Namespace" within brackets {} is expected to be translated.
We found out that OPS is using a Markdig flavor called "Markdig (DocFX)" which does render URL surrounded by space to be rendered as hyperlink. 
To avoid this, suggested fix to source string is add an escape char (\) to part of the URL.
Many thanks in …

C19396: Missing hyperlink due to incorrect redenring

---

aspnetcore/getting-started.md
aspnetcore/includes/webapp-alias-notice.md
aspnetcore/mvc/razor-pages/index.md
aspnetcore/mvc/razor-pages/ui-class.md
aspnetcore/security/authentication/accconfirm.md
aspnetcore/security/authentication/add-user-data.md
aspnetcore/security/authentication/individual.md
aspnetcore/security/authentication/scaffold-identity.md
aspnetcore/security/authorization/secure-data.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/signalr/get-started.md
aspnetcore/tutorials/publish-to-azure-webapp-using-cli.md
aspnetcore/tutorials/razor-pages-mac/razor-pages-start.md
aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md

Fixes #6937 
We may need to work with the note language, but I propose something like this temporarily (until 2.2?).
In spite of `webapp`'s alias status, I chose "replaces" in the wording to push the idea that this is what we recommend for everyone going forward.

Add webapp alias notice

---

aspnetcore/mvc/razor-pages/index.md

"Whatever's there's appended to" sounds odd and, more importantly, take longer to understand than "whatever's there is appended to".
When first reading this page, I had to stop and re-read several times before I understood what was trying to be said. Dropping the contraction on "there's" helped a lot, while leaving the contraction on "whatever's" keeps the tone conversational.

Remove difficult consecutive contractions

---

aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/LifetimeEventsHostedService.cs

Going  through the docs for the new .NET Core 2.1 IHostService examples. 
Found a small bug (most likely a copy/paste issue) where ILogger type was incorrect.

Fix logger type in LifetimeEventsHostedService example

---

aspnetcore/performance/caching/middleware.md

Changes the corresponding package for the `UseResponseCaching` middleware, which was incorrectly linking to the `Microsoft.AspNetCore.ResponseCompression` package, instead of the correct `Microsoft.AspNetCore.ResponseCaching`.

Fixes ResponseCaching package name and link

---

aspnetcore/security/anti-request-forgery.md

Clarify that there are alternative scenarios a malicious site could implement, in addition to the example of a basic CSRF attack. The original content conveys the impression that the user is required to interact with the malicious site, which is presumably almost never the case when the user has JavaScript enabled.

Add clarification to scenario in anti-request-forgery.md

---

aspnetcore/fundamentals/configuration/platform-specific-configuration.md

Fixes #6951 
This doesn't address *Split dynamic loading section into separate document* #6896 and the new exclusion bits provided by https://github.com/aspnet/Hosting/pull/1243. I'll hit those on #6896.

Order of IHostingStartup Configure calls

---

aspnetcore/mvc/views/tag-helpers/intro.md

I just tested and it does not matter whether the project in vs2017 is created with or without authentication regarding the _viewimports file. Seems odd it mentions that making the reader think that there is a difference or why would it be mentioned.  Second ,and not sure if this should be addressed because it might be the tip of the iceberg, the files are no longer in views/ but are now in pages/

Update intro.md for views->pages and removing mention of auth

---

aspnetcore/security/authentication/social/facebook-logins.md

I believe the current document conveys that developers have to use /signin-facebook as their callback URI. However, almost in every scenario, we need to set a different callback URI and this is easily possible via authentication middleware.
`Edit:` [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-1.0&branch=pr-en-us-6964&tabs=aspnetcore2x)

Introducing CallbackPath Property

---

aspnetcore/security/cookie-sharing.md

Fixes #6639 
* Calls out that it's ok to use `UseCookieAuthentication` with netfx/Katana apps.
* Removes prior code example from the previous round of samples for this topic. The tabs would work to match the examples to the version of the topic, but they also make this section confusing because it pertains to netfx app config ... not ASP.NET Core app config. These are subject to change anyway after *Update cookie sharing topic for new samples* (#5238) goes in.
* Let's remove the NOTE and TIP and just let the reader read the content in this section.

Clarify UseCookieAuthentication

---

aspnetcore/fundamentals/url-rewriting.md
aspnetcore/security/enforcing-ssl.md

Fixes #7059 
Killed the mention of 443 in the URL Rewriting Middleware topic NOTE because HTTPS Redirection Middleware options permit setting that. Using the redirection middleware is the recommendation if additional redirect rules aren't needed.
@Tratcher Side ❓ ... Why 307 for this middleware ... why not 308? It seems like you wouldn't want the insecure endpoint requested every time. It seems like you take a *forever perf hit* by issuing 307s for these redirects.

Link to URL Rewriting Middleware

---

aspnetcore/host-and-deploy/linux-apache.md

The URI captured was not re-added in the regex replacement. See [example](https://wiki.apache.org/httpd/RewriteHTTPToHTTPS). I also tested this in Apache to confirm.

missing capture group in regex

---

aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application.md

Removed some manually inserted linebreaks in creating-an-entity-framework-data-model-for-an-asp-net-mvc-application.md to fix how the content displays on docs.microsoft.com

Fix line breaks in entity framework tutorial

---

aspnetcore/signalr/hubcontext.md
aspnetcore/signalr/index.md

Add an entry to the SignalR ToC for the new HubContext doc.

Add HubContext doc to SignalR ToC

---

aspnetcore/fundamentals/environments.md
aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/generic-host/samples-snapshot/2.x/GenericHostSample/Program.cs
aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/Program.cs

Fixes #6760 
The goals are ...
* Surface that env vars aren't added by default with the Generic Host.
* Describe `AddEnvironmentVariables`.
* Deal with env var prefix issue.
* Explain how to set env vars for dev (shoot reader to *Multiple environments* topic for more info). Mention VS, command-line, and VSC config.
* Add VSC example to the *Multiple environments* topic.
* Update the sample app and snippets for the topic.

Improve environment variable coverage

---

aspnetcore/fundamentals/host/web-host.md

Fixes #6576 
I'm using the word "fixes" lightly at the moment. We might need to restructure the layout to accommodate host and app config descriptions ... along the lines of the way we handled it in the Generic Host topic.
We do have host configuration via `UseConfiguration` in this topic with an example. It's down in the *Override configuration* section. I added the bit about `reloadOnChange` not working. If there are any additional gotchas, we can list them in the NOTE that describes `UseConfiguration` limitations for host configuration.
Any chance we can get the Generic Host to take over in a **_2.1 patch release??!_** :smile:

Improve web host configuration content

---

aspnetcore/data/ef-mvc/intro.md

Removes the PDF version of the VS 2015 tutorial from https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1. Since this is an unsupported scenario, the PDF shouldn't be made available (per Dan).

Remove VS2015 PDF link from tutorial

---

aspnetcore/razor-pages/index.md

The statement at the end of this paragraph added a level of confusion around the `@namespace` directive. Some on stackoverflow took the meaning to be they didn't need to ever include `using` statements. I felt that we were clear enough in the article already in regards to what the `namespace` directive accomplished and therefore didn't need this extra tid bit.
aspnet/Mvc#7932

Remove confusing statement about namespace directive.

---

aspnetcore/client-side/bower.md

Fixes #7135 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-1.0&branch=pr-en-us-7151)
I couldn't find the exact version of VS that dropped Bower in the VS Release Notes. From online sources, it looks like it might have been 15.5.
@justcla Can you confirm the VS version that dropped Bower?

Add Bower VS details

---

.openpublishing.publish.config.json

The "aspnetmigration" branch doesn't exist, so this section of the publish config should be deleted.

Remove nonexistent branch from publish config

---

aspnetcore/signalr/streaming.md
aspnetcore/signalr/streaming/sample/Hubs/StreamHub.cs

- Fixed sample for SignalR stream usage.
- Link to this code sample updated as well, because of 404 error when opening it from aspnetcore/signalr/streaming.md

SignalR stream sample fix. Link to sample updated in related article.

---

aspnet/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks.md

Hello, @MikeWasson  ,
"Example URL at line 24 is displayed as a link, it must be escaped in order to be displayed as text"
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

C26453: escaping URL to display it as text

---

aspnet/web-forms/overview/deployment/configuring-team-foundation-server-for-web-deployment/creating-a-team-project-in-tfs.md

Hello, @jrjlee ,
"Example URL at line 109 is displayed as a link, it must be escaped in order to be displayed as text"
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

C26449: escaping URL to display it as text

---

aspnet/web-api/overview/releases/whats-new-in-aspnet-web-api-22.md

Hello, @tdykstra  ,
"Example URL at line 128 is displayed as a link, it must be escaped in order to be displayed as text"

C26454: escaping URL to display it as text

---

aspnetcore/host-and-deploy/directory-structure.md

The directory structure table and text mentions a lower case *logs* directory. 
After the XML code snippet the spelling changes to *Logs* (upper case).
Changed every mention of the *logs* directory to be lower case.

Changes "logs" to be lower-case everywhere

---

aspnet/mvc/overview/getting-started/introduction/adding-validation.md

Removed an extra verb so that sentence now reads "The `Genre` field is no longer nullable" instead of "The `Genre` field is are no longer nullable"

Simple grammar fix

---

aspnetcore/getting-started/index.md

Hello, @rick-anderson,
"INCLUDE syntax is incorrect. There should be a space before title bracket."

L25985: Adding space between !INCLUDE and []

---

aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint/samples/sample4.xml

connectionString currently leads to a SQL error 50: "Local Database Runtime error occurred. Cannot create an automatic instance" when trying to access the local database. Proposed fix taken from accepted StackOverflow answer here:
https://stackoverflow.com/a/26267373/8133586

Update connectionString for SQL 2014 or later

---

aspnetcore/fundamentals/host/generic-host/samples-snapshot/2.x/GenericHostSample/Program.cs

Snippet `ConfigureAppConfiguration` in the generic host fundamental page was referencing an invalid variable name in the context of the scope. Updated to use the correct variable name.

Fixed invalid variable name in generic host snippet

---

aspnetcore/host-and-deploy/windows-service.md

Fixes #7373 
@scottaddie In this case, I'm making an exception to our general rule about not specifying the TF explicitly because I want it to be utterly clear what the path will look like. For the example prereqs, I've added a bullet to say that the project is published for `netcoreapp2.1`. [EDIT] The TF will be updated at each sample update, so I'm not worried about it for the future of the topic.
Also, I want to reinforce the `binPath` argument space requirement, so I repeat the following line on purpose for this new example ...
> **Make sure the space is present between the `binPath=` argument and its value.**
It's an easily overlooked instruction that turns into a big 'ole :bomb: if it isn't seen by the reader.
Thanks to @mmaguirehub for reporting! :rocket:

Enhance service creation content

---

aspnetcore/tutorials/signalr.md
aspnetcore/tutorials/signalr/sample/Hubs/ChatHub.cs
aspnetcore/tutorials/signalr/sample/Startup.cs

* Fixed whitespace and capitalization
* Clarified that `UseSignalR` adds to the middleware pipeline (`AddSignalR` just adds services to DI)

Minor corrections to SignalR tutorial

---

aspnetcore/fundamentals/index.md

`Microsoft.AspNetCore.App` metapackage is recommend for applications targeting ASP.NET Core 2.1.

Introduce Microsoft.AspNetCore.App metapackage instead of All in fundamentals/index.md

---

aspnet/ajax/cdn/overview.md

As discussed in #7382 the Bootstrap 4 CDN section should not contain reference to Glyphicons library as:
- this is no longer part of Bootstrap itself, it ships without icon/web font dependency now
Thanks!

Remove links to Glyphicons library. Closes #7382

---

aspnet/ajax/cdn/overview.md

This add missing links to resources already hosted on CDN for Bootstrap 4, but missing in docs.
The resources linked can be used standalone by developers without using main `bootstrap.css` resource:
- to just reset the default browsers styling and built upon this own solution
- to just use the grid layout from Bootstrap without a need to use the fully fledged components.
Reference:
http://getbootstrap.com/docs/4.1/getting-started/contents/
Thanks!

Add missing links to Bootstrap 4 CDN resources

---

aspnetcore/security/authentication/social/index.md

Fixes https://github.com/aspnet/Docs/issues/7409
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.1&branch=pr-en-us-7421#use-secretmanager-to-store-tokens-assigned-by-login-providers)

Add note about using Secret Manager in development only

---

aspnetcore/includes/net-core-prereqs-windows.md

Fixes #7453 
In addition to the link going stale, shouldn't this also instruct to take the **.NET Core cross-platform development** workload?

Update prereq include

---

aspnetcore/tutorials/signalr-typescript-webpack.md
aspnetcore/tutorials/signalr.md

The SignalR tutorials only display when 2.1 or later is selected in the version picker. VS 2017 15.7.3 or later is required for 2.1+. This PR fixes that prereq version number, which should take care of the related issues we've been seeing.

Specify VS 2017 version required for .NET Core 2.1

---

aspnetcore/web-api/define-controller/samples/WebApiSample.Api/Startup.cs
aspnetcore/web-api/index.md

Fixes https://github.com/aspnet/Docs/issues/7407
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1&branch=pr-en-us-7491#annotate-class-with-apicontrollerattribute)

Mention 2.1 compat flag requirement for [ApiController]

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/web-host.md

Fixes #7283
[Internal Review Topic (Web Host)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-1.0&branch=pr-en-us-7493)
[Internal Review Topic (Generic Host)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1&branch=pr-en-us-7493)
@Tratcher, you only need to eyeball the *Application Key (Name)* sections on these. The rest are just doc structure updates.
Did I just make up `ASPNETCORE_APPLICATIONKEY`? Is that a thing?

App key/name enhancements to host topics

---

aspnet/ajax/cdn/jquery-cycle/cdnjquerycycle288.md

Hello, @Rick-Anderson , 
"Links are not inside the MD link structure"

C26452: Converting links to markdown code

---

aspnetcore/security/authorization/iauthorizationpolicyprovider.md

As per the "contributing" instructions, because this is a simple change, there is no issue raised for this change. 
There is a broken link in this file (to a source code repo in GitHub). I've corrected the link, pointing it to what is (I hope) the correct location.

Correct broken link to source code sample

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

Fixes #7515 
I also:
* Conform to a convention we're using where the latest content (>=2.1) is above the prior versions (<2.1). In the table, the only content actually changing is `ForwardedForHeaderName` and `ForwardedProtoHeaderName`.
* Update some links formats.
cc/ @dasMulli :beer:

Enhance forwarded headers content

---

aspnetcore/fundamentals/metapackage-app.md

cref aspnet/Home#3292
Per customer feedback, we have decided to restore the Version attribute on the PackageReference for .App/.All in our new project templates. Users are still struggling with the implicit package version if they have not updated to the 2.1.301 SDK, so let's change the docs to show 2.1.1 as the recommended minimum version.

Remove instructions about using the implicit PackageReference feature for AspNetCore.App/All

---

aspnetcore/migration/20_21.md
aspnetcore/migration/20_21/sample/WebApp21.csproj

Follow up to https://github.com/aspnet/Docs/pull/7540
I found one more reference to versionless packages. I've updated the migration guide to remove this recommendation, and also briefly mentioned the most common issues users have encountered so far.

Update the migration docs to remove instructions for versionless package references

---

aspnetcore/fundamentals/configuration/options.md

Fixes #7504 
@HaoK I'm applying versioning (moniker ranges) in place of text references to versions. It's probably a good time for you to double-check and see if the versions mentioned are correct.

Apply versioning to Options topic

---

aspnet/ajax/cdn/overview.md

This commit adds information about 4.1.1 being added to the CDN.
The original tip-off:
https://github.com/aspnet/Templating/pull/595#discussion_r201817830
Thanks!

Update information about hosted Bootstrap 4 versions

---

aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2/samples/sample14.cs

Added missing parenthesis in RouteAttribute

Update sample14.cs added missing parenthesis in RouteAttribute

---

aspnetcore/fundamentals/startup.md

I noticed that some links point to https://github.com/aspnet/Mvc/blob/dev/src/ but since that one doesn't exist (anymore?). I fixed them to point to master.

Fix urls linking to non-existing dev branch

---

aspnetcore/docfx.json
aspnetcore/security/authentication/social/index.md
aspnetcore/tutorials/dotnet-watch.md

Found some more links pointing to non-existing dev branches. Also found a link in docfx.json which was non-existent.

Fix links pointing to dev branch to point to master branch

---

aspnetcore/tutorials/signalr.md

I think this should be added for those who do not know that `lib` is in `wwwroot`.

Mention `wwwroot` when copying over signalr.js

---

aspnetcore/fundamentals/metapackage.md

Remove the "and later" portion of the title from the metadata, since the .App metapackage should be used instead.
@Rick-Anderson Should this doc only display for 2.0? I was just talking to a customer who was confused about which metapackage to use.

Remove confusing verbiage from .All metapackage title metadata

---

aspnetcore/signalr/authn-and-authz.md

https://github.com/aspnet/Docs/issues/7586 revealed a gap in the new authentication docs. Added a small blurb about configuring clients for Windows Auth.

SignalR - .NET Client Windows Auth

---

aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/ui_and_navigation.md

It is well known that if you use a Bootstrap 4 template on an ASP.NET template it will break the layout. This is a convenience change to prevent confusion as it will send people to the correct versioned URL as it was back when this article was written.

Changed Bootswatch URL to point to Bootswatch 3.

---

aspnet/mvc/pluralsight.md

The "Start Free Trial" and "Subscribe Now" links pointed to a 404 page at Pluralsight. I have updated the URLs with destinations that make sense to the average user. The free trial URL remains focused on Scott Allen's ASP.NET MVC 5 course for promotional purposes.
**If Microsoft has updated affiliated links, that might be a better option for the future.**

Corrected broken URLs to point to updated content.

---

aspnetcore/data/ef-rp/read-related-data.md

This line originally generated is `public IList<Instructor> Instructor { get;set; }` and gets changed to `public InstructorIndexData Instructor { get; set; }` so it's worth highlighting, I feel

Highlight one more line

---

aspnetcore/data/ef-rp/concurrency.md

It seems that the missing blank line between the paragraph and the list is causing an error in the display style. I've made a screenshot below that shows the problem. However, I'm not able to test if the blank lines are really causing this error. In this case, however, I assume the same from my previous experience with Markdown renderings.

Add spacing for unordered lists

---

aspnetcore/data/ef-rp/sort-filter-page.md

The text removed references an old issue before EF Core 2.1 was released. Now that EF Core 2.1 is released, this text is no longer current.

Removed out of date text

---

aspnetcore/data/ef-rp/complex-data-model.md

EF Core 2.1 is out and already supports data seeding, so this note is no longer relevant.

Removed EF Core 2.1 note

---

aspnetcore/data/ef-rp/intro/samples/cu/Pages/Instructors/IndexRRD.cshtml

`<td>@Html.ActionLink("Select", "OnGetAsync", new { courseId = item.CourseID })</td>` throws an error saying:
> Cannot resolve action 'OnGetAsync'
I also fixed a spacing issue
<hr />
I see a now closed issue: #6230 that seems to also have trouble with this link, but does not mention this specific error.
The only similarity I have with that issue is that I also created the project with[ Individual User Accounts as the security](https://github.com/aspnet/Docs/issues/6230#issuecomment-390510927), though as Rick-Anderson [mentioned ](https://github.com/aspnet/Docs/issues/6230#issuecomment-390786825) it's likely not the problem.

Update Select HTML.ActionLink to use asp tag helpers

---

aspnetcore/tutorials/razor-pages/validation.md

The current follow-up tutorial link takes users to an MVC tutorial based on ASP.NET Core 2.0. This tutorial is based on Razor Pages and ASP.NET Core 2.1. I think it makes more sense for the recommended follow-up tutorial to continue building on the knowledge learned here about Razor Pages, so I updated the link to take users to [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro) instead.

Updated link to follow-up tutorial

---

aspnet/mvc/overview/older-versions/working-with-the-dropdownlist-box-and-jquery/using-the-dropdownlist-helper-with-aspnet-mvc.md

Hello, @Rick-Anderson ,
"The unescaped '@' sign is breaking the code"
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

C30172: Escaping '@' character to avoid broken content in localization

---

aspnetcore/mvc/views/working-with-forms.md

Hello, @rick-anderson ,
"The unescaped '@' sign is breaking the code"

C30171: Escaping '@' character to avoid broken content in localization

---

aspnet/signalr/overview/older-versions/introduction-to-security.md

Hello, @pfletcher ,
"Escaping URL that must not be shown as link"

C28229: Escaping URL that must not be shown as link

---

aspnetcore/security/cookie-sharing.md
aspnetcore/security/cookie-sharing/sample/README.md

Add subdomain config in cookie sharing topic

---

aspnetcore/web-api/define-controller/samples/WebApiSample.Api.Pre21/Controllers/PetsController.cs
aspnetcore/web-api/index.md

The line numbers being used were no longer the correct ones. Replace that delicate range with a newly created region name to prevent this from happening again.
Shout out to @DavidCBerry13 for spotting this mistake.

Replace line numbers range with snippet name

---

aspnetcore/fundamentals/servers/kestrel.md

@Tratcher Don't we need type args here? ... my compiler wasn't too happy about the code sample as-is.

Supply type args in Kestrel example

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fixes #7795 - Add recommendation for ignoring XML doc warnings for certain classes in Swagger documentation
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&branch=pr-en-us-7849&tabs=visual-studio%2Cvisual-studio-xml#xml-comments)

Add recommendation and example for ignoring XML doc warnings per class

---

aspnetcore/tutorials/first-web-api/samples/2.1/TodoApi/TodoApi.csproj
aspnetcore/tutorials/web-api-vsc.md

Addresses https://github.com/aspnet/Docs/issues/7866
The 2.1 project template doesn't add the `Version` attribute, but the sample app includes it (as it should). This PR tells the reader to add the attribute.

Add instruction to add Version attribute

---

aspnetcore/fundamentals/host/web-host.md
aspnetcore/security/enforcing-ssl.md

Fixes #7659 
More to come on remarks about env vars across the repo when I get to the *Configuration coverage* issue (#7102).
I think we're going to have to go in this direction wherever we mention env vars explicitly because we probably won't be able to rely on prior knowledge when they're mentioned outside of config/hosting. I'll analyze the situation further later this week or early next week. For now, this will fix this *one spot*.

Enforcing SSL topic: HTTPS_PORT env var details

---

aspnetcore/signalr/configuration.md

Had a question about default values for the config values and I figured it would be faster to answer by updating the docs ;).
Not committed to the formatting. I thought a new column could work well but I could also do this as sentences in the Description column (some of the options already had this, I think I moved them all)
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1&branch=pr-en-us-7906)

Add default values to SignalR config doc

---

aspnetcore/host-and-deploy/windows-service.md

Fixes #7842 
I didn't need to change anything other than setting `StoreLocation.LocalMachine`. I'm under the impression that a cert install by a user in the `My` store will be available to a WS running under the LocalSystem account *if only this one change is made to the `LoadFromStoreCert` call.* I need engineering confirmation on that point.
cc: @Hugh-walsh

Windows Service with HTTPS

---

aspnetcore/security/enforcing-ssl.md

Add a line explaining once you're confident in HSTS you should increase the value from the default, and expanding out the click through prevention.
Fixes #7940

Expanding out HSTS values

---

aspnetcore/fundamentals/configuration/options.md

[`PostConfigureAll` does not actually take a string parameter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsservicecollectionextensions.postconfigureall?view=aspnetcore-2.1) since it post-configures *all* named options, instead of just the supplied name.

Fix PostConfigureAll example

---

aspnet/web-forms/overview/older-versions-getting-started/aspnet-ajax/understanding-asp-net-ajax-debugging-capabilities.md

Hello, @scottcate,
"There's an extra asterisk that's breaking the Note code. In case the italics must be conserved, we suggest to start them on line 53."

C32681: Changing position of Italic Marker (asterisk)

---

aspnetcore/mvc/models/validation/sample/ClassicMovieAttribute.cs

The parameter should be camelCase.

Paramater naming convention fix

---

aspnetcore/toc.md

Somehow some of the SignalR docs got moved to the "Client-side development" hive. This should move them back, if I understand how the TOC file works properly :)
[Internal Review Site](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1&branch=anurse%2Ffix-signalr-toc&viewFallbackFrom=aspnetcore-1.0&tabs=visual-studio)

Re-transplant SignalR docs to the correct TOC tree

---

aspnet/web-api/overview/testing-and-debugging/mocking-entity-framework-when-unit-testing-aspnet-web-api-2.md
aspnet/web-api/overview/testing-and-debugging/unit-testing-with-aspnet-web-api.md

Synchronize the link to sample code at the top description to be the same link to sample code that use VS 2017.
* Refers to #4308 because looks like the link from the top description isn't the same as the "Download the complete code" link. The top description still points to the old VS 2013 sample code, therefore I update the link to be the same link as I have submitted before 🙂 
cc @scottaddie

synchronize link to updated sample code that use VS 2017

---

aspnetcore/security/app-secrets.md

Docs: Code hightlighted in snippet is NOT the code that the section is
referring to. Prior 5-8 is not the AddUserSecret call - line 12 of the snippet is
Fixes #8123

fix the highlighting for AddUserSecrets

---

aspnetcore/docfx.json
aspnetcore/web-api/index.md

Fixes https://github.com/aspnet/Docs/issues/7064
Modified 1 doc to demonstrate the new syntax. See http://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services for more context around the *docfx.json* file change.
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?branch=pr-en-us-8112&view=aspnetcore-2.1#additional-resources)
/cc: @mairaw I took a different approach than how it's done in the dotnet/docs repo. Copying you in case you're interested in this solution.

Support .NET API xref links in ASP.NET Core docs

---

aspnetcore/host-and-deploy/windows-service.md
aspnetcore/host-and-deploy/windows-service/samples/2.x/AspNetCoreService/Program.cs
aspnetcore/host-and-deploy/windows-service/samples/2.x/AspNetCoreService/Startup.cs
aspnetcore/host-and-deploy/windows-service/samples_snapshot/1.x/AspNetCoreService/Startup.cs

Fixes #8131 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-1.0&branch=pr-en-us-8136)
* Provide a hint for `ConfigureAppConfiguration`.
* Drop the `ConfigurationBuilder` in `Startup` (not needed with `CreateDefaultBuilder` and we don't want 2.1+ devs going that way).
I'm retaining (but not wiring up) the original `Startup` as a snapshot file in case I need to show the 1.x/2.0 approach in the future.
cc: @Eldorian

Reorganize Windows Service samp app config

---

aspnetcore/mvc/controllers/testing.md

Fixes #8156 
* Removes the integration testing coverage from the testing controllers topic. This info has been superseded by the new testing approach, which is outlined in the integration testing topic. A cross-link to the integration testing topic has been added here.
* Leaves the sample as it is for now. The sample is due for upgrade on #5495. We'll either support the new `WebApplicationFactory` approach here (less likely) or move some or all of the examples over to the integration testing topic sample app to keep all of our integration testing coverage in one spot (more likely).
* This isn't a UE pass. I'll do that when I get to this on #5495.

Remove integration testing

---

aspnetcore/signalr/version-differences.md

Adds a section to the ASP.NET Core SignalR Differences document to help identify the version you are using. This can be a helpful resource when customers aren't sure which version is which.
We're also adding a link to this doc (through an `aka.ms` forwarder) to some new version detection logic we're adding to the client (see https://github.com/aspnet/SignalR/pull/2820). I'm not 100% confident in putting a link in an exception message but I think it really needs more explanation than an exception message can provide. We're using a forwarder though so we can re-target it if things move around.
Also cleared up some references to make sure they use the more canonical "ASP.NET Core SignalR" and "ASP.NET SignalR" phrases
[Internal Review …

SignalR: Add table to help identify version

---

aspnetcore/security/authentication/windowsauth.md

Fixes #7789 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-1.0&branch=pr-en-us-8159)
* The main thing is to surface that the Windows Authentication role service must be configured in IIS. This also mentions in passing that the IIS option for the middleware is defaulted to work and that the ANCM is defaulted to pass on the token. It's accomplished with a couple of cross-links in a new *IIS configuration* section.
* The other thing is that "Windows Authentication" is a proper noun, so I update that throughout the topic.

Surface IIS config in Windows Auth topic

---

aspnetcore/mvc/views/tag-helpers/authoring.md
aspnetcore/mvc/views/tag-helpers/authoring/sample/AuthoringTagHelpers/src/AuthoringTagHelpers/Views/Home/Index.cshtml

Related to https://github.com/aspnet/Docs/pull/4599.
Removed unnecessary `@` symbols, added missing double quotes, and replaced inline code snippet with code import.

Remove unnecessary @ symbols in Tag Helper example

---

aspnetcore/tutorials/signalr.md

Addresses discussion in https://github.com/aspnet/Docs/pull/8145 and a few minor problems.

Specify target framework of .NET Core in SignalR tutorial

---

aspnetcore/signalr/version-differences.md

Fixes #8182 
Surfaces the .NET Framework package from https://github.com/aspnet/Docs/pull/8145
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?branch=pr-en-us-8183&view=aspnetcore-2.1#how-to-identify-the-signalr-version)

Corrections in SignalR version support table

---

aspnetcore/test/integration-tests/samples/2.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/IndexPageTests.cs

Changed code from 
_client = factory.CreateClient(new WebApplicationFactoryClientOptions
{
AllowAutoRedirect = false
});
_factory = factory;
To
_factory = factory;
_client = factory.CreateClient(new WebApplicationFactoryClientOptions
{
AllowAutoRedirect = false
});

Assign CustomWebApplicationFactory value before using it

---

aspnetcore/fundamentals/startup.md
aspnetcore/migration/20_21.md
aspnetcore/mvc/compatibility-version.md
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/CompatibilityVersionSample.csproj
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/Program.cs
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/Startup.cs
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/Startup2.cs
aspnetcore/mvc/overview.md
aspnetcore/razor-pages/index.md
aspnetcore/release-notes/aspnetcore-2.1.md
aspnetcore/toc.md
aspnetcore/tutorials/razor-pages/sql.md
aspnetcore/web-api/index.md

Fixes #8170 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-2.1&branch=pr-en-us-8196)
* Other than an API link, there are no changes to the original text. Just moving the content and sample app here.
* The new topic preserves the original date of the content from #5948.
Please check [20-21.md (Internal Review Topic)](https://review.docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-1.0&branch=pr-en-us-8196), as I escaped several underscores in an attempt to make GH rendering good.

Move SetCompatibilityVersion into an MVC subtopic

---

aspnetcore/fundamentals/middleware/index.md

Fixes #8274 
A quick fix that surfaces two concepts:
* The extension methods are exposed directly on the `IApplicationBuilder`.
* The namespace that exposes them is `Microsoft.AspNetCore.Builder`.
These concepts appear much later in the topic (*Write middleware*), but we probably need to surface them earlier, where extension methods for pipeline processing middleware are first mentioned.
Thanks to @NicolasDorier for discussion in #8118 leading to this enhancement.

Middleware ext method namespace clarification

---

aspnetcore/fundamentals/error-handling.md
aspnetcore/fundamentals/error-handling/samples/2.x/ErrorHandlingSample/Startup.cs
aspnetcore/host-and-deploy/iis/modules.md
aspnetcore/security/authentication/windowsauth.md

Addresses #8118 
This is a quick patch based on @NicolasDorier's feedback on the issue. The issue requires more extensive changes, but we can knock this clarification out quickly.
This exposes:
* The Diagnostics package requirement for Status Code Pages Middleware. A reader may skip the Developer Exception Page content and jump right to this section and then not be aware that they need the package reference.
* The need for the members of the `Microsoft.AspNetCore.Http` namespace in the example code, which is required to enable the [Microsoft.AspNetCore.Diagnostics.StatusCodeContext.HttpContext](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.diagnostics.statuscodecontext.httpcontext) property.
@scottaddie A nit update here, too ... It seems to me that "Developer Exception Page" …

Clarify package for Status Code Pages Middleware

---

aspnetcore/client-side/libman/libman-cli.md

Adds an example of using a relative path with `libman install --files`.

Add note about LibMan install relative path support

---

aspnetcore/fundamentals/servers/kestrel.md

The line break in the markdown seems to break the link to further docs

Fix link to metapackage docs

---

aspnetcore/fundamentals/error-handling.md

You can see the correct name is already used the the code sample two sentences down

the default model class is `ErrorViewModel`, not `ErrorModel`

---

aspnetcore/performance/caching/middleware.md
aspnetcore/performance/caching/middleware/samples/2.x/ResponseCachingMiddleware/Startup.cs

Fixes #8409 
* Surface the namespace for `GetTypedHeaders`.
* Quick touch on the package section.
* Not assessing for more than these two quick updates. 🏃😅

Response caching middleware: Surface a namespace in example

---

aspnetcore/fundamentals/configuration/index.md
aspnetcore/fundamentals/configuration/index/samples/1.x/ConfigurationSample/Extensions/EntityFrameworkExtensions.cs
aspnetcore/fundamentals/configuration/index/samples/1.x/ConfigurationSample/Startup.cs
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Extensions/EntityFrameworkExtensions.cs
aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Program.cs

Fixes #8413 
* Let's go with an *Extensions* folder and make the file name match the class name of `EntityFrameworkExtensions`.
* I confirmed that both samps build with these updates.

Update EF extensions file name+location

---

aspnetcore/fundamentals/startup.md
aspnetcore/fundamentals/startup/sample/Program.cs
aspnetcore/fundamentals/startup/sample/Startup.cs

Fixes #8407 
* The update of the 2.0 sample here is tracked by #5495.
* Placed the snippet region just around the `CreateDefaultBuilder` call so that the 2.0-era `BuildWebHost` call isn't seen in the topic.

App startup topic updates

---

aspnetcore/fundamentals/host/generic-host.md

Fixes #8393 
* Swaps RabbitMQ for the `TimedHostedService` example, which is an example over in the background tasks/hosted services topic.
* It's a bit silly, but I think this was all that David was trying to show ... it's easy to extend on the host builder.

Change extensibility example

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

Update IP address format with note

---

aspnetcore/signalr/version-differences.md

Addresses https://github.com/aspnet/Docs/issues/7814
Saw this in one of the comments. So thought of adding it.
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1&branch=pr-en-us-8469#scaleout-differences)

Added 'Scaleout differences' section

---

aspnetcore/signalr/hubs.md

Fixes #7629
@BrennanConroy -  added Context object section similar to Clients object section as suggested.
A few questions:
* How do things get into the `Items` collection?
* Any additional useful information we should add to the property and method descriptions?
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1&branch=pr-en-us-8486)

Add Context section to signalr/hubs.md

---

aspnetcore/security/data-protection/consumer-apis/password-hashing.md

A non standard parenthesis was inserted on the left parenthesis of the link I added likely due to one of the foreign keyboards I use being activated when I entered it.

fixed link not rendered

---

aspnetcore/mvc/controllers/routing.md
aspnetcore/razor-pages/razor-pages-conventions.md
aspnetcore/razor-pages/razor-pages-conventions/sample/Conventions/GlobalTemplatePageRouteModelConvention.cs
aspnetcore/razor-pages/razor-pages-conventions/sample/Startup.cs

Fixes #6173 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.0&branch=pr-en-us-8523)
@rynowak This follows our discussion on https://github.com/aspnet/Mvc/issues/8385.
Thanks again to @user135711 for surfacing the issues.

RP conventions topic+sample updates

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #8442 
Fixes #7641 
Fixes #8385
* `sudo` on `systemctl` calls.
* Drop text out of notes: IMO devs should just read these passages in the the normal flow of the text.
* Doc `TimeoutStopSec`.
* Add `KillSignal=SIGINT` to config file.
@shirhatti @Praveen-Rai @harrison314 Consider this a draft ... it needs a touch more work.
@shirhatti, you said ...
> systemd defaults to sending SIGTERM
Does setting `KillSignal=SIGINT` override the default `SIGITERM` for `KillSignal`, or are both eligible to act as a kill signal for the app after this setting is made? I think we'd want to relay that info here. If it's a replacement of the default, I'll also specify which one where this says "initial terminate/interrupt signal." It will either remain as "initial terminate/interrupt signal" or go to …

Address KillSignal/exiting & sudo in Linux topics

---

aspnetcore/mvc/views/tag-helpers/built-in/index.md
aspnetcore/mvc/views/tag-helpers/th-components.md
aspnetcore/toc.md

Fixes #4033 
Fixes https://github.com/aspnet/Docs/issues/5475
Fixes https://github.com/aspnet/Docs/issues/5476

Add Tag Helper Components doc to ToC

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/security/gdpr.md
aspnetcore/security/gdpr/sample/Startup.cs

Fixes #8041 
[Internal Review Topic (Middleware)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-1.0&branch=pr-en-us-8382)
[Internal Review Topic (GDPR)](https://review.docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1&branch=pr-en-us-8382)
* Surfaces Cookie Policy Middleware in Middleware topic.
* Remarks on Cookie Policy Middleware ordering in Middleware and GDPR topics.
* Cleans up a few small content issues.
@kichalla Follows your remarks on https://github.com/aspnet/Mvc/issues/8233.

Additional content on Cookie Policy Middleware

---

aspnetcore/signalr/java-client.md
aspnetcore/signalr/java-client/sample/pom.xml

This updates the current preview 1 SignalR Java client docs to preview 2. 
It removes the second where we call out that the Azure SignalR Service is not supported. Should we add a section calling out that it works?
@scottaddie Can you help with changing the drop down from preview 1 branding to preview 2? Thanks!

Update SignalR Java Docs to Preview2

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/web-api-help-pages-using-swagger.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup2.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.NSwag/Startup.cs
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.NSwag/TodoApi.csproj

- Upgrade NSwag (samples) and use new API Explorer based generators (the reflection based generators are deprecated soon)
- Some text improvements
- Change "Open API" to "OpenAPI" (correct name)
- Use new Swagger UI 3 in samples
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&branch=pr-en-us-8572&tabs=visual-studio%2Cvisual-studio-xml)

Use API Explorer based NSwag generator and middlewares

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/host-and-deploy/proxy-load-balancer.md

Fixes #8632 
[Internal Review Topic (Nginx; Apache topic has the same text)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-1.0&branch=pr-en-us-8634#use-a-reverse-proxy-server)
[Internal Review Topic (Forwarded Headers topic)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-1.0&branch=pr-en-us-8634#troubleshoot)
* Enhances `KnownProxies`/`KnownNetworks` line in Nginx and Apache topics.
* Enhances troubleshooting content in Forwarded Headers topic.
cc: @michaelkrog @LindaLawton - You'll need to look at the diff to see the changes. The internal review topics are only available to MS folks.

Enhance KnownProxies/Networks content

---

aspnetcore/tutorials/getting-started-with-NSwag.md

Fixes the used snippets in the NSwag tutorial (currently the imports are missing and the configure snippet is used twice).

Fix snippets in NSwag tutorial

---

aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md
aspnetcore/performance/caching/index.md
aspnetcore/performance/index.md
aspnetcore/performance/response-compression.md
aspnetcore/performance/response-compression/samples/1.x/README.md
aspnetcore/performance/response-compression/samples/1.x/Startup.cs
aspnetcore/performance/response-compression/samples/2.x/README.md
aspnetcore/performance/response-compression/samples/2.x/Startup.cs
aspnetcore/toc.md

Fixes #7715 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-1.1&branch=pr-en-us-8560)
* A number of topic UE updates are provided.
* Brotli content is added to the topic.
* I use inline code examples over snapshot files because this will only in need of a quick sample update + some sample link changes when 2.2 RTMs, and that's right around the corner.
* Opened **Add Brotli compression to the sample app** #8559 to deal with sample app update later.
cc: @khellang ... do u want to take a look at the Brotli bits before I call for engineering to take a look?

Response Compression updates (+Brotli)

---

aspnetcore/mvc/views/view-components.md

Surface synchronous approach for view components

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #8496 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-1.0&branch=pr-en-us-8689)
This PR hoists sections from **bold text** into level 3 section headers. This improves the navigation sidebar and makes it easier for readers to locate sections.
In passing tho ........ I think we're coming back here later. Because Kestrel config is so flexible with so many knobs and switches, I'd like to take a look at the possibility of splitting the config into subtopics. We might not go there, but it's worthy of consideration. I'll look at that option later if it seems to have merit.

Improve Kestrel topic section support

---

aspnetcore/fundamentals/dependency-injection.md

Fixes #8592 
* We have a few link destinations in the Architectural Principles topic that we can use here.
* This isn't a UE pass ... just a link replacement PR.
* We perform link updates on UE passes. It isn't feasible for us to perform a sweep of the entire repo for this type of update. I suggest we continue to do this work on a topic-by-topic basis.

Use MS architectural principles link in DI topic

---

aspnetcore/performance/caching/distributed/sample/src/DistCacheSample/StartTimeHeader.cs
aspnetcore/performance/caching/distributed/sample/src/DistCacheSample/Startup.cs

Fixes #8514 
* Convert use of local time to UTC.
* I went for some naming upgrades and consistency.
* I prefer not to post-fix types on variable names (i.e., "String" here).
* I add "UTC" here and there tho to clarify what's held in vars and the cache key.
* Opened **Distributed cache topic UE pass** #8702 to do a pass on the topic later.

Distributed caching topic sample update

---

aspnetcore/migration/20_21.md
aspnetcore/migration/20_21/sample/WebApp21.csproj

Reverts https://github.com/aspnet/Docs/pull/7543
See https://github.com/aspnet/Home/issues/3292#issuecomment-424146341 for context

Update the 2.1 migration doc to instruct users to remove the version on Microsoft.AspNetCore.App

---

aspnetcore/mvc/controllers/filters.md

Add separate section using h3 title to separate out the IFilterFactory description from that of the TypeFilterAttribute when discussing dependency injection.

Separate IFilterFactory from TypeFilterAttribute

---

aspnetcore/security/data-protection/implementation/key-storage-providers.md
aspnetcore/security/data-protection/implementation/key-storage-providers/sample/MyKeysContext.cs
aspnetcore/security/data-protection/implementation/key-storage-providers/sample/Startup.cs

Adding documentation about a new feature coming in 2.2. https://github.com/aspnet/DataProtection/pull/323
cref https://github.com/aspnet/Home/issues/2505
@rick-anderson edit below:
[Internal review url](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.2&branch=pr-en-us-8328#entity-framework-core)
~Do not merge until preview-2 ships.~

Add a section about storing data protection keys using the EF Core provider

---

aspnetcore/tutorials/signalr.md

I don't have a way of testing this on Windows atm, but most of the other examples use forward slashes, so I assume this is correct on all platforms.  Backslashes fail on MacOS, creating a directory called "wwwrootlibsignalr".

Use forward slashes for destination path

---

aspnetcore/tutorials/razor-pages/search.md

Visual Studio does not recognize the query without using the `Microsoft.Linq` namespace, which isn't specified in the document.
Interestingly, without it - you get an error saying `Could not find an implementation of the query pattern for source type 'DbSet<Movie>.' 'Select' not found.` You can't even have VS easily import the namespace using `Ctrl` + `.` or similar methods.

Added using for clarity

---

aspnetcore/fundamentals/environments.md

The text says that the code is using the UseBrowserLink function while it is actually not using it

Remove UseBrowserLink

---

aspnetcore/getting-started/index.md

Indenting the code block with 4 spaces causes the Markdown parser to think that the lines with the backticks are also part of the code block, [as per the Markdown specifications](https://daringfireball.net/projects/markdown/syntax#precode). I reduced the indentation to 2 spaces to get around this problem.
Fixes #8563 
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&branch=pr-en-us-8772)

Fix code block showing backticks

---

aspnet/webhooks/receiving/receivers.md

The description of the webhook uri contains the following:
```
"The component is the name of the receiver, for example github or slack"
```
It should read:
```
"The <receiver> component is the name of the receiver, for example github or slack"
```
This PR code fences &lt;receiver&gt; so it displays correctly.

Code fence <receiver> uri component

---

.github/ISSUE_TEMPLATE/doc-issue.md

Noticed that in the template for creating a Doc Issue, the link navigating you to the page to choose which type of issue applies is not valid and returns a 404 error instead. this is due to the fact that in the url itself, "Issues" should not be capitalized -- Changing to lowercase fixes the problem.
**Live:** https://github.com/MicrosoftDocs/Feedback/Issues/new/choose
**PR Change:** https://github.com/MicrosoftDocs/Feedback/issues/new/choose

Fixed hyperlink so user routed to the correct page to create a new issue

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/host-and-deploy/iis/modules.md

Adding link to [Sentry](https://github.com/getsentry/sentry) integration with ASP.NET Core and `Microsoft.Extensions.Logging`.

Add Sentry, FOSS error monitoring tool

---

aspnetcore/fundamentals/environments.md

Fixes #8635 
Let me know if you'd prefer to see it just changed to something along the lines of ...
> Restart an app's app pool. This approach only works if the environment variable is set on the app pool. This approach doesn't work for a system-wide environment variable.
If we were to go that way, should it address the user env var case? (restart of app pool tied to a specific user account and the env var is set for that user)?
However, I removed the item on this PR because it's easier for a general audience to follow the simpler instructions for `net stop`/`net start` or restarting the server.

Update instruction on picking up env var change

---

aspnetcore/fundamentals/websockets.md

The doc mentions 1.1+ support, yet the moniker range indicated 2.1+.

Correct the moniker range in WebSockets doc

---

aspnetcore/signalr/supported-platforms.md

Fixes #2996
@anurse -- what versions of Node and Java do the SignalR clients support?

Add available clients to SignalR supported platforms

---

aspnetcore/includes/net-core-prereqs-windows.md

The download link for Visual Studio only takes you to the .NET/.NET Core downloads page like the second link. This page has no links to download Visual Studio.
Corrected to take you to the Visual Studio download page just like this page [https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio.md] does.

Corrected download link for Visual Studio

---

aspnetcore/mvc/views/working-with-forms.md

The first `IndexOption` reference in the article is changed to `Index.` The second reference stays intact and is correct.
Fixes #7309

Update `IndexOption` to `Index`

---

aspnetcore/fundamentals/configuration/options.md

`ConfigureAll` configures _all_ instances, not just explicitly named instances. The "Note" section sort explains this later by mentioning that that "All options are named instances". But I think it makes the behaviour clearer to remove the "named" qualifier in this case?

Clarifications around ConfigureAll and named options

---

aspnetcore/fundamentals/localization.md

This PR address:
- Fix Localization.StarterWeb project link
- Change "Resource Files in Visual Studio" link because it seems talking about C++ specific resources

Fix localization resources links

---

aspnetcore/razor-pages/index.md

I added a quick description of HEAD requests. It seems many developers don't know the difference between that and a GET, and a quick sentence to put it in context might help.

Added context around HEAD requests

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #8710 
1. Fix the `./<app_executable>` bit ... refer to the DLL.
1. Drop "mvc" from naming and go with "app."
1. Path to `/var/www/helloapp`.

Linux topic updates

---

aspnetcore/host-and-deploy/iis/index.md

Reconstitute installer flags

---

aspnetcore/fundamentals/metapackage.md
aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/environment-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/index.md
aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md
aspnetcore/toc.md

Fixes #8771 
* Add cross-links back out to the main TH topic early in these built-in TH topics. This helps a dev who has landed directly into a built-in TH topic from an external link get back out to the basic overview.
* Hit some of these with a UE pass.

Tag Helpers: Enhance cross-links and UE pass

---

aspnetcore/fundamentals/configuration/index.md

Fixes #8795 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-1.0&branch=pr-en-us-8918)
Although the topic does call out `ConfigureAppConfiguration` early in the coverage (for 2.1), it didn't show provider examples using it down through the topic.
It was relying too heavily on devs *remembering* what they read and **not showing up from an external link directly to a provider section**.
This PR seeks to enhance the examples in every provider section.
I can't see the internal review topic, so plz put an :eye: on that and confirm the versioning is all :+1:.

Configuration enhancements

---

aspnetcore/fundamentals/host/web-host.md

Fixes #8920 
Clarify that the order that the configuration providers are listed is the order that they are read.

Language enhancement to the Web Host topic

---

aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-security-guidance.md

The reference to the mdash entity is missing a semicolon in the documentation.  This renders incorrectly on the documentation website.

Fix broken xhtml named entity reference (mdash)

---

aspnetcore/mvc/views/view-components.md

Hello, @rick-anderson,
Description: Some of the "folder names" inside \<\> are not displaying well in localized pages, and also those terms are not blocked for localization.

CC71738: Escaping components names to avoid broken format in translation pages

---

.ghal.rules.json

Add config file to support automatic labeling for "Source - Docs.ms".

Add GitHub auto labeler config file

---

aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2.md

Correct property name for route ordering in RouteAttribute is Order, not RouteOrder. Replace incorrect RouteOrder property name with correct name Order
source references:
https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/RouteAttribute.cs#L40
https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/RouteAttribute.cs#L40

attribute-routing-in-web-api-2, RouteOrder=>Order

---

aspnetcore/data/ef-rp/crud.md

Found a typo in the `FindAsync` section where "they" was used instead of "that".
Currently: "Can have perf benefits in some situations, but **they** rarely happens for typical web apps."

Update crud.md with fixed typo

---

aspnetcore/data/ef-rp/sort-filter-page.md

Sections in the document where "**Student**/Index.cshtml" was used instead of the correct, plural form like so: **Students**/Index.cshtml

Update sort-filter-page.md with proper path names

---

aspnetcore/fundamentals/websockets.md

Fixes https://github.com/aspnet/Docs/issues/8618
We still need to call out that IIS Express does not support WebSockets in Windows 7, so we still need the section.
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1&branch=pr-en-us-8621)

Add note about WebSockets in IIS Express

---

aspnetcore/tutorials/web-api-vsc.md

I was reviewing an issue - to me, it looks like the VS Code help reference was a bit out of place. Having it up front right under the prerequisites might be a better spot.

Updated help reference

---

aspnetcore/security/key-vault-configuration.md

Fixes #8750 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-1.1&branch=pr-en-us-9064)
Uses the explain-by-example strategy based on the issue discussion with @Jaffacakes82. JSON is familiar to devs, so a SxS show-and-tell with the AKV keys might make sense.
@Jaffacakes82, would this have worked for you?

Array support with the AKV configuration provider

---

aspnetcore/signalr/security.md

Added some notes on WebSocket Origin validation to ASP.NET Core SignalR documentation.
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1&branch=pr-en-us-9080)

Documentation on WebSocket Origin validation

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/generic-host/samples-snapshot/2.x/GenericHostSample/Program.cs
aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/Program.cs

Fixes #8893 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1&branch=pr-en-us-9061)
* Remove Logging from service config (given it's a default service).
* List the default services (too literal here? ... trimming needed??? :hocho:)

List default services for Generic Host

---

aspnetcore/mvc/views/partial.md

Fixes https://github.com/aspnet/Docs/issues/9073
@pranavkm I tried to make it very clear what behavior to expect in which version of ASP.NET Core.
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.2&branch=pr-en-us-9087#declare-partial-views)

Add detail about serving partial views named with underscores

---

aspnetcore/data/ef-rp/complex-data-model.md

A link to the FK section is actually provided, but it is easy to gloss over. Moving the section up in the document prevents users reading it too late to do anything about it, as said in the issue.
Fixes #7728

Moved section earlier in this tutorial

---

aspnetcore/signalr/security.md
aspnetcore/signalr/security/sample/Startup.cs

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1&branch=pr-en-us-9088)
- Kill long sentences. Long sentences are difficult for native speakers and impossible for MT (machine translation)
- Format code to prevent horizontal scroll bar on tablets 85 characters wide. You can simulate tablets by viewing in a browser of the maximum width that doesn't have left or right panes (TOC's).
- Prune dead wood. Avoid unnecessary words that don't add meaning to the text.
- Avoid "you" except when it make the statement more clear. 
- For example, the following CORS policy allows a SignalR browser client hosted on `http://example.com` to access **your** SignalR app:
-For example, the following CORS policy allows a SignalR browser client hosted …

UE edit of Security considerations in ASP.NET Core SignalR

---

aspnetcore/tutorials/razor-pages/da1.md

I noticed the "Next" button in this tutorial was not prefaced with `Next:` like the rest of the tutorials. This massive pull request resolves this.

Added "Next" to "Search" button

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/security/enforcing-ssl.md
aspnetcore/security/enforcing-ssl/sample-snapshot/Program.cs
aspnetcore/security/enforcing-ssl/sample/Startup.cs

Addresses #6538 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-1.0&branch=pr-en-us-9044)
Organize and enhance the coverage. I've marked this "addresses" for now, but we might find out that other issues cover the remaining parts of #6538 and this PR can close the issue.
Numbering the items from #6538 for reference ...
1. Setting up HTTPS
a. Cross-link to existing server specific guidance on enabling HTTPS
b. Cross-link to the proxy guidance especially around validating forwarded headers Addressed by #6644.
1. Enforcing HTTPS in Azure App Service
1. Enforcing HTTPS behind other proxies
1. Surface IIS hosting issues in the IIS topic pertaining to use of the middleware when the site isn't configured for HTTPS in IIS
There …

Enforcing HTTPS enhancements

---

aspnetcore/toc.md

Adding a line to the table of contents. We need a reference to the .NET Client API reference link here.

Update TOC to have the .NET Client API reference.

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #9141 
Carrying over the question on ...
> Debug level (`debugLevel`) values:
>
> \* ERROR
> \* WARNING
> \* INFO
> \* TRACE
> \* CONSOLE
> \* FILE
> \* EVENTLOG
The first four look like logging levels, and the last three look like locations. How do I fix the coverage?

ANCM: Detect client disconnects and logging

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/appsettings_SQLite.json

While going through [this topic](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1), I noticed that the *appsettings.json* file that is shipped with the template is different now. I updated it. With the change, the highlighted lines do not change - a nice surprise.

Changed to reflect default json file

---

aspnetcore/signalr/java-client.md

Updating the link on the main Java docs page

Update Java API reference link

---

aspnetcore/toc.md

The current link 404s because we've updated the package name from `com.microsoft.aspnet.signalr` to `com.microsoft.signalr`

Update TOC to reflect new SignalR Java client package name

---

aspnetcore/signalr/security/sample/Startup.cs

fixes https://github.com/aspnet/Docs/issues/9246
The spec does mention that we should use `403 Forbidden` when validating the Origin. I missed that when writing the original sample :) https://tools.ietf.org/html/rfc6455#section-10.2

Fix status code for WebSocket origin validation

---

aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md

Instead of "comma-delimited list of header values" it should be "... query string keys"

Updated vary-by-query

---

.github/PULL_REQUEST_TEMPLATE.md

Since GitHub supports comments in pull request templates, I thought this might be a nice way to provide the text without causing anyone to have to delete it afterward. We used it on another project of mine with success, so contributing the idea back.

Use comment in pull request template

---

aspnetcore/includes/mvc-intro/adding_view2.md
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Views/Shared/_Layout21.cshtml

Fixes #8558.
If I'm correct, I think the issue here is that the .NET Core 2.1 OOTB `_Layout.cshtml` is a little bit different now, and ApplicationInsights is not included out of the box. Therefore, the error was received after copying/pasting.
* I ran through the steps in the tutorial using .NET Core 2.1 on my local until I hit that step.
* I copied the `_Layout.cshtml` file that my .NET Core 2.1 app came out with.
* I pasted that into the example file, overwriting it.
* I updated the title line and the line referring to the movies controller
* I updated the highlights

Update sample to reflect .NET Core 2.1 out of the box

---

aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v3/working-with-entity-relations.md

Hello, @MikeWasson,
Description of the source issue: Missing semicolon at the end of the numeric entity is preventing  code to be displayed as a dash  "—"

C47281: Missing semicolon

---

aspnet/single-page-application/overview/introduction/knockoutjs-template.md

Hello, @MikeWasson,
Description of the source issue: Missing semicolon at the end of the numeric entity is preventing  code to be displayed as a dash  "—"

C47280: Missing semicolon

---

aspnetcore/razor-pages/index.md

Add 'as' in 'Mark page properties **as** required' to be clearer and avoid mistakes when translated.

Update Razor Pages

---

aspnet/web-api/overview/web-api-routing-and-actions/routing-in-aspnet-web-api.md

Fixes #8208 
This is in relation to and hopefully fixes #8208. I have added the additional supported HTTP Action verbs, HEAD, OPTION and PATCH to those listed as convention.

Added additional verbs to routing convention text

---

aspnet/mvc/overview/older-versions/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc-part-1.md

Hello, @Rick-Anderson,
Description of the source issue: There are two links in source code next to each other, causing they appear broken on LOC site.
Proposed fix: Only one link should be in the () brackets, but neither of them is working. This will at least fix the issue that is causing a code to be shown in LOC sites

C47282: Broken links

---

aspnetcore/tutorials/razor-pages-vsc/model.md
aspnetcore/tutorials/razor-pages/razor-pages-start.md

Change "MacOS" to the official casing of "macOS".

Address casing of MacOS

---

aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server.md
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample13.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample23.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample25.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample41.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample42.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample46.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample58.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample59.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample60.vb
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample63.cs
aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample7.cs

Related: https://github.com/SignalR/SignalR/issues/4144
FYI: This is for **ASP.NET** SignalR, *not* ASP.NET Core SignalR. (The concepts are relative to both but the newer docs are better at showing the right pattern ;))
When SignalR fails to send a message (possibly due to an error in the backplane), the exception bubbles all the way up to the Client proxy (e.g. `Clients.All.foo()`). However, all our docs tell users to simply invoke these methods without `await`ing the task or otherwise observing it. This means that these errors can end up triggering the [`TaskScheduler.UnobservedTaskException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception?view=netframework-4.7.2) event.
This updates our docs on the Hubs API to show `await`ing …

update ASP.NET SignalR docs to show observing send errors

---

aspnetcore/security/authentication/accconfirm/sample/WebPWrecover21/Services/EmailSender.cs

use `SetClickTracking` method instead of directly accessing the public property `TrackingSettings`.
Reference #9235 
Related to #6268

use "SetClickTracking" method to disable clicktracking

---

aspnetcore/includes/RP/page1.md

Some of the links was fixed before. This should be the last one.

Fix path for _Layout.cshtml

---

aspnet/web-api/overview/formats-and-model-binding/media-formatters/samples/sample4.cs

namespace ProductStore.Formatters was declared 2 times; 1 time in the first line and 1 time in line 9.

Remove an erroneous namespace declaration

---

aspnetcore/client-side/bundling-and-minification/samples/BuildBundlerMinifierApp/wwwroot/js/site.min.js

To resolve a recent build warning showing up on PRs:
> Cannot  resolve  '../client-side/bundling-and-minification/samples/BuildBundlerMinifierApp/wwwroot/js/site.min.js'  relative to 'client-side/bundling-and-minification.md'.

Replace missing JS file in sample app

---

aspnetcore/fundamentals/host/web-host.md
aspnetcore/fundamentals/servers/aspnet-core-module.md
aspnetcore/fundamentals/servers/index.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/servers/weblistener.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fixes #6091 
@Rick-Anderson @scottaddie I found some minor errors in some of the topics while working on this issue. They mostly pertain to the 2.0 release, which probably explains why they haven't been flagged by anyone. We have a 😵 number of versioning sections required to address the framework churn in a few topics. This situation makes working on these topics difficult. Version 3.0 may even overlap with 1.x, adding to the totals shown in the table.
| Topic | moniker range instance count |
| --- | :---: |
| Host > web-host.md | 36 |
| Servers > kestrel.md | 52 |
| Configuration | 86 |
[EDIT] Build warning ... need a tip ...
> Tab group with different tab id set.
[EDIT] Moved the bit about Swashbuckle 1.x versioning to a new issue: https://github.com/aspnet/Docs/issues/9270

Update BuildWebHost to CreateWebHostBuilder (MD topics)

---

aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45.md

Fix the formatting on the Formatting on ".NET framework is listed as v4.0" section list.

Formatting on ".NET framework is listed as v4.0" section list

---

aspnetcore/fundamentals/websockets.md
aspnetcore/signalr/security.md

Fixes https://github.com/aspnet/Docs/issues/9363
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.2&branch=pr-en-us-9447)
There are some moniker ranges, so switch the versions to verify they're working

WebSocket Origin Restriction

---

aspnetcore/host-and-deploy/iis/index.md

More for #9441 with a bit of refactoring.
- IISServerOptions (inproc) are unique from IISOptions (out of proc)
- Move HTTP/2 topic lower in the document (flow felt off by having it before how to enable IISIntegration)
- Remove stop/starting app pool in favor of dropping app_offline (@shirhatti for thoughts)
- Generalize addressing AspNetCore behind IIS (remove reverse proxy stuff).

Update IIS index.md

---

aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/GenericHostSample.csproj

The code to move JSON files to the output directory causes build failures after multiple builds - at least in .NetCore 2.1. The reason being that for each build the Include="**\*.json" syntax will pick up JSON files that exist in both the Bin and Obj folders - and maintain their file structure - but appending them to the root bin folders causing a recursive file structure problem. This eventually triggers a path to long exception in MSBuild.
After adding the current code to the project file (without the exclude condition)
`<ItemGroup>
<Content Include="**\*.json"  CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>`
The following happens to the Bin folder:
Build1:
\bin\Debug\netcoreapp2.1\*.json
\bin\Debug\netcoreapp2.1\obj\*.json
Build2:
\bin\Debug\netcoreapp2.1\*.json …

Exclude Bin and Obj from CopyToOutputDirectory

---

aspnetcore/fundamentals/configuration/options.md

Fixes https://github.com/aspnet/Docs/issues/9443
Fixes https://github.com/aspnet/Docs/issues/9232

Update options for 2.2

---

aspnetcore/includes/webApi/getTodoItems.md

Making it a bit clearer that the [controller] name replacement of MyNameController is by naming convention.

Docs: Mentioned that the Controller name replacement is by convention

---

aspnetcore/index.md

Fixes #9470 
[Internal Review Topic (How to download a sample section)](https://review.docs.microsoft.com/en-us/aspnet/core/index?view=aspnetcore-1.0&branch=pr-en-us-9544#how-to-download-a-sample)
I'm not very trusting of ✨ *Magic Build Systems* ✨. I usually encode reserved DocFX characters outside of code-fenced content ... *they'll **never** break this way no matter what the build system thinks about them*.
If you prefer that I go with either a backslash (safe) or roll the 🎲🎲 and use unencoded chars with build system processing trust, let me know which alternate way you would like to go. Again, my approach is **_bulletproof_**.
Thanks @rswetnam! :rocket:

Clarify use of preprocessor directives with samps

---

aspnetcore/signalr/supported-platforms.md

fixes #9460, by limiting the "server side" language in the .net client segment and by adding a brief discussion on Xamarin, which links off to the issue we created to help Xamarin developers get going.

added .net client discussion

---

aspnetcore/security/data-protection/configuration/overview.md

Fixes #9354 
[Internal Review Topic (SetApplicationName section)](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-1.0&branch=pr-en-us-9546#setapplicationname)
Engineering only needs to look at Lines 132-139 ... the rest of this is just dropping tabs.
Thanks @Sigvaard! :rocket:

Clarify shared DP version for shared DP payloads

---

aspnet/web-forms/overview/data-access/caching-data/caching-data-at-application-startup-cs.md

All the apostrophes were missing for some reason -- added them back in.

Added missing apostrophes

---

aspnetcore/signalr/hubs.md
aspnetcore/signalr/streaming.md
aspnetcore/signalr/streaming/sample/Hubs/StreamHub.aspnetcore21.cs
aspnetcore/signalr/streaming/sample/Hubs/StreamHub.cs

fixes aspnet/SignalR#3190
ASP.NET Core SignalR now has support for a CancellationToken in Hub methods. This updates our docs to show that support in the ASP.NET Core 2.2 version of the docs
My first time using `:::moniker range`, and I think it's appropriate here. We'll see if I did it right :)
| Review Links | 2.1 | 2.2 |
| ------------ | --- | --- |
| ~~Hubs API~~ | ~~[Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1&branch=pr-en-us-9346)~~ | ~~[Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2&branch=pr-en-us-9346)~~ |
| Streaming | [Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.1&branch=pr-en-us-9346) | …

fix aspnet/SignalR#3190 by adding docs on cancellation in 2.2

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/security/authentication/social/additional-claims.md
aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/includes/chain-auth-providers.md
aspnetcore/security/authentication/social/includes/forwarded-headers-middleware.md
aspnetcore/security/authentication/social/index.md
aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/other-logins.md
aspnetcore/security/authentication/social/twitter-logins.md
aspnetcore/toc.md

Fixes #9549 
* Not a full UE pass on the group of external provider topics ... don't quite have time for that right now. However, I do hit a number of small UE-type updates.
* Engineering: You only need to look at one thing here: See the *forwarded-headers-middleware.md* file. The content of the file is below. The INCLUDE is linked into the external auth provider topics to surface Forwarded Headers Middleware (proxy/LB topic).
> \#\# Forward request information with a proxy or load balancer
>
> If the app is deployed behind a proxy server or load balancer, some of the original request information might be forwarded to the app in request headers. This information usually includes the secure request scheme (\`https\`), host, and client IP address. Apps don't automatically read these request …

Surface Forward Headers in ext auth provider topics

---

aspnetcore/fundamentals/configuration/index.md

Fixes #9597 
I think this makes it a bit more clear where the prefixed vars come in and that they're used for host config. I add a line to the list for `CreateDefaultBuilder`'s app config.
@Tratcher ... am I making things better? .......... *or should I have stayed in bed this morning?!!* :smile:
Thanks @penenkel! :rocket:

Clarify env vars in Web Host building remarks

---

aspnetcore/client-side/bundling-and-minification.md

Fixes https://github.com/aspnet/Docs/issues/8758
Also replaced ASP.NET Core version tabs with moniker ranges.
**Internal Review Pages**
* [2.1](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&branch=pr-en-us-9655&tabs=visual-studio#configure-bundling-and-minification)
* [2.0](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.0&branch=pr-en-us-9655&tabs=visual-studio#configure-bundling-and-minification)

Update bundleconfig.json guidance for 2.1+ projects

---

aspnetcore/toc.md

Fixes #9668 
Tom, do you prefer this approach: Nix the duplicate content by dropping the App Service tutorial link, or how would you like to handle this? The Azure doc set doesn't include a publish-to-Azure tutorial based on the CLI AFAICT. They have [script samples](https://docs.microsoft.com/azure/app-service/app-service-cli-samples?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest) that might do it but not a tutorial.
* Ours: https://docs.microsoft.com/aspnet/core/tutorials/publish-to-azure-webapp-using-vs
* Theirs: https://docs.microsoft.com/azure/app-service/app-service-web-get-started-dotnet
Thanks @henrikrxn for reporting. :rocket:
WRT to the question on publishing with CLI and publish profiles, I think we're ok with the publish profiles …

Change URL of link to Azure deploy with CLI tutorial

---

aspnet/web-pages/overview/ui-layouts-and-themes/twitter-helper.md

Fixes #6578
* A quick fix: I'm not going to probably ever have time to rewrite the topic.
* We can link the reader over to Twitter's latest approaches with this update.
* Note that their link appears localized (`en`). Removing that segment breaks the link.

Inform readers on depreciated Twitter Helpers

---

aspnetcore/includes/net-core-prereqs-macos.md

The current link redirects to the .NET Downloads page. Should we have this go to the VS for Mac page?

Repoint VS for Mac link?

---

aspnetcore/test/integration-tests.md

Fixes #6292 
[Internal Review Topic (Disposal of objects section)](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1&branch=pr-en-us-9691#disposal-of-objects)
I'll deal with the non-xref API links that run throughout the topic on a future PR.

Surface test object cleanup content

---

aspnetcore/fundamentals/servers/httpsys.md
aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/host-and-deploy/iis/index.md
aspnetcore/host-and-deploy/iis/troubleshoot.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md
aspnetcore/host-and-deploy/web-farm.md
aspnetcore/host-and-deploy/windows-service.md
aspnetcore/test/troubleshoot.md

Fixes #6083 
[Internal Review Topic (Troubleshoot ASP.NET Core projects)](https://review.docs.microsoft.com/en-us/aspnet/core/test/troubleshoot?view=aspnetcore-1.0&branch=pr-en-us-9689)
* The app code from IIS Integration that reports request, connection, env vars is so useful, including outside of IIS scenarios, that imo it should be surfaced to readers. I've used it several times, and the community has enjoyed using it.
* Engineering: The main update to review here is at the bottom of the diff (updates to the last file): *test/troubleshoot.md*.
* In most spots, adding a link to the *test/troublshoot.md* topic is enough. In a few spots, I add a short section.
* UE is not a thrust of this, but I did fix up a few things as I went along.

Surface troubleshooting code from IIS Int repo

---

aspnetcore/tutorials/signalr.md

When I run through the tutorial after executing `code -r SignalRChat`, a new VSCode window opens that is in the signalRChat directory.  (Ex. C:\SignalRChat).  When I execute `dotnet run -p SignalRChat` from there I get an error
"MSBUILD : error MSB1009: Project file does not exist.
Switch: SignalRChat
The build failed. Please fix the build errors and run again."
However, if I change the command to `dotnet run -p SignalRChat.csproj` it works.

VS Code `dotnet run -p` command update

---

aspnetcore/tutorials/first-mvc-app/start-mvc.md
aspnetcore/tutorials/first-mvc-app/working-with-sql.md

Two of the tutorials still had tabs being used for versions. The only purpose was to include 1.x text in the tutorial, so the tabs and 1.x content were removed.

Remove version tabs from intro to MVC

---

aspnetcore/security/authentication/identity/sample/src/ASPNETCore-IdentityDemoComplete/IdentityDemo/IdentityDemo.csproj

Demo\IdentityDemo.csproj : error NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Tools from 2.0.3 to 2.0.0. Reference the package directly from the project to select a different version.
Demo\IdentityDemo.csproj : error NU1605:  IdentityDemo -> Microsoft.AspNetCore.All 2.0.9 -> Microsoft.EntityFrameworkCore.Tools (>= 2.0.3)
Demo\IdentityDemo.csproj : error NU1605:  IdentityDemo -> Microsoft.EntityFrameworkCore.Tools (>= 2.0.0)
The build failed. Please fix the build errors and run again.

Error NU1605: Detected package downgrade.

---

aspnetcore/tutorials/signalr-typescript-webpack.md

To avoid confusion, I added a clarifying statement in case developers are getting project.json errors because they are in the wrong directory, like in the issue this fixes.
Fixes #9754

Clarify where to execute npm

---

aspnetcore/host-and-deploy/health-checks.md

cc @glennc @rynowak @unaizorrilla @guardrex @Rick-Anderson 
I actually wouldn't mind too much if we want to refer to the DbContext as "database context", but we need to be consistent for the links to work :trollface:

Tweaks to the EF Core-based health checks

---

.openpublishing.redirection.json

Fixes https://github.com/dotnet/docs/issues/9386
The tutorials index page was deleted as part of the ToC reorganization. This PR redirects to the Razor Pages tutorial.

Add redirect entry for tutorials index page

---

.openpublishing.redirection.json

Fixes https://github.com/dotnet/docs/issues/9386
The tutorials index page was deleted as part of the ToC reorganization. This PR redirects to the Razor Pages tutorial.

Merge to live 12-4 Part 2

---

aspnet/web-pages/overview/getting-started/introducing-aspnet-web-pages-2/publishing.md

Hello, @Rick-Anderson,
Description: contoso.com is a mock URL and should not be linked. The proposed fix for this is either write the URL within code box, meaning between grave accents (`) or using backslashes.

C53605: Escaping mock URL

---

aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs
aspnetcore/host-and-deploy/iis/troubleshoot.md

Fixes #9865 
I'm also making a quick "InProcess" casing change here to match the templates.
See Lines 48-50 of the first file on the diff for the `CurrentDirectoryHelpers` bit.

Workaround for base dir when hosting in-process

---

aspnetcore/mvc/views/razor.md

Removed leading space so that the two bullet points are not formatted as a code block.

Fix formatting in razor.md

---

aspnetcore/client-side/spa-services.md
aspnetcore/client-side/spa-services/sample/SpaServicesSampleApp/Startup.cs

Fixes #9889
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-1.0&branch=pr-en-us-9891)
mmmm ... Looks like this fixes those `can't find the startTag` build warnings I've been getting locally lately. Looks like underscores are *IN* this year and dashes are *OUT*. :smile:
cc: Thanks @dliabenow! :rocket:

Update snippet names

---

aspnetcore/migration/21-to-22.md

Fixes #9901
* I don't say *why* ... is it relevant? It makes the doc shorter to not get into it.
* It also made sense to move *Update .NET Core SDK version in global.json* down because currently it appears in the middle of changes made to the project file.

Use ConfigureKestrel over UseKestrel

---

aspnetcore/mvc/compatibility-version.md
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/Startup.cs
aspnetcore/mvc/compatibility-version/samples/2.x/CompatibilityVersionSample/Startup2.cs

Quick update of compatibility version docs to mention 2.2 as the latest version.
Also updated code samples to use the recommended `CompatibilityVersion.Version_2_2`.

Updated Compatibility version docs to mention version 2.2

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #9920 
**OLD**: `MSAspNetCoreToken`
**NEW**: `MS-ASPNETCORE-TOKEN`
https://github.com/aspnet/AspNetCore/blob/2.2.0/src/IISIntegration/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L21
No versioning on this change given the proximity to 1.x EOL.
Thanks @Julian89757! :rocket:

Name of IIS Middleware pairing token header

---

aspnetcore/tutorials/first-web-api/samples/2.2/TodoApi/wwwroot/index.html

Minor change but it seems a little confusing to call the button "Edit" when you use it to "Save" your changed todo item.
Slight sense of deja vu. #9602

Update title of button in HTML code for clarity

---

aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md
aspnetcore/host-and-deploy/index.md
aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md

Fixes #9716 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-1.0&branch=pr-en-us-9871)
* Cross-link to surface this content better ... it's viable for Azure App Service.
* Update the versioning in examples (1.1 content is in the PDF).
* Enhance the instructions in the *Publish to an MSDeploy endpoint from the command line* section.
* Call out that `dotnet msbuild` of the CLI toolchain works on Windows with this approach.
cc: @madmox

Publish profiles enhancements + cross-links

---

aspnetcore/host-and-deploy/health-checks.md

In version 2.2.0, `HealthCheckStatus` was renamed to `HealthStatus`

 Fix HealthCheckStatus → HealthStatus in Health checks documentation

---

aspnetcore/signalr/redis-backplane.md

Add text to clarify that StackExchangeRedis is for 2.2, non-SO Redis is for 2.1.
Fixes #9919

Clarify Redis package vs SignalR version

---

aspnetcore/host-and-deploy/directory-structure.md

Fixes #9965 
The dir structure has experienced considerable churn release-to-release. I recommend we version latest. Otherwise, we're going to have to get into the time machine to figure out when the dir structure changed in order to version this content currently.

Update and improve the Directory Structure topic

---

aspnetcore/performance/diagnostic-tools.md
aspnetcore/toc.md

This short document lists useful ASP.NET Core perf diagnostic tools.
There's not much 'meat' since the tools are all well-documented elsewhere, but I think it's valuable to have this sort of list so that ASP.NET Core devs can discover the tools (especially PerfView and PerfCollect, which can be hard to find without links from official docs).
Fixes #9525

Document ASP.NET Core perf tools

---

aspnetcore/mvc/models/validation/sample/Program.cs
aspnetcore/mvc/models/validation/sample/Startup.cs
aspnetcore/mvc/models/validation/sample/ValidationSample.csproj

Addresses #8622
- Target 2.2
- Switching from using deprecated logging setup

ASP.NET Core MVC: Updating validation sample to 2.2

---

aspnetcore/fundamentals/configuration/options.md

This page in the docs states that `Microsoft.Extensions.Options.DataAnnotations` is available as part of the metapackage in Core 2.1, when actually it's only available in 2.2.

Replace reference to ASP.NET Core 2.1 with 2.2

---

aspnetcore/security/authentication/social/facebook-logins.md

This pull request clarifies that the `Microsoft.AspNetCore.Authentication.Facebook` NuGet package is not required. I have removed that statement, and added a bullet to the end of the document saying it can be used if preferred for advanced scenarios.
Fixes #9014

Make Microsoft.AspNetCore.Authentication.Facebook optional

---

aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/Areas/Sessions/Pages/Index.cshtml
aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/Areas/Sessions/Pages/Index.cshtml.cs
aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/Areas/Sessions/Pages/_ViewStart.cshtml
aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/Startup.cs
aspnetcore/mvc/views/tag-helpers/built-in/samples/TagHelpersBuiltIn/Views/Home/Index.cshtml

Fixes https://github.com/aspnet/Docs/issues/9834
Also converted API ref links to the xref style.
[Internal Review Page](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?branch=pr-en-us-10048&view=aspnetcore-2.2#asp-area)

Add example of asp-area with a Razor Pages area

---

aspnetcore/tutorials/getting-started-with-NSwag.md
aspnetcore/tutorials/getting-started-with-swashbuckle.md

Fixes https://github.com/aspnet/Docs/issues/9134
Also changes "Web API" references to "web API".

Add blurb about web API conventions in Swashbuckle doc

---

aspnetcore/security/authentication/social/facebook-logins.md
aspnetcore/security/authentication/social/google-logins.md
aspnetcore/security/authentication/social/index.md
aspnetcore/security/authentication/social/microsoft-logins.md
aspnetcore/security/authentication/social/twitter-logins.md

Review and update code samples for setting up social providers on asp.net core 2.
* Turns out they already had notes about default service settings being overridden when setting up social providers, so no change necessary - please sanity check. I ended up just updating the sample code to match the latest result from WebApp generator.
Remove bad repo link in social index.

Fixes #10015 Update code samples

---

aspnetcore/security/data-protection/implementation/key-storage-providers.md

Fixes #9864 
@chrizy Take a look ... I think this would've helped. We're not going to show the CREATE TABLE statement on the grounds that this is for EF Core, so showing the migration for EF Core makes the most sense. I do think we should have the class/schema there tho. IMO, that's a nice touch.

Table migration for PersistKeysToDbContext

---

aspnetcore/host-and-deploy/linux-apache.md
aspnetcore/host-and-deploy/linux-nginx.md

Fixes #8679 
Fixes #9997 
* No examples, since we're not pitching specific values.
* Didn't link DoS or buffer overrun. We don't have particularly good options on the MS end. We have [this topic for DoS](https://docs.microsoft.com/windows-hardware/drivers/ifs/denial-of-service), but that's not very satisfying as provided by Windows drivers docs. Same for buffer overrun. We have [this topic](https://docs.microsoft.com/windows/desktop/secbp/avoiding-buffer-overruns) via Windows Desktop docs. It was supposed to be in [this security glossary](https://docs.microsoft.com/security-updates/Glossary/glossary), but they removed it at some point (I sent them a note about that). If you want buffer overrun and DoS links here, we may need to ping Barry for a tip. There are *lots 'o options*.
* Nginx …

Linux topics: Long request headers content

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Pages/Movies/Index.cshtml.cs

In [coding-style.md](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md ) NO 11, we use language keywords instead of BCL types

Using keywords 

---

aspnetcore/fundamentals/configuration/options.md

Fixes #10136 
Small update to improve the link text in the `IConfigureNamedOptions` content of the Options topic.
[Internal Review Topic (links directly to the section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-1.0&branch=pr-en-us-10137#named-options-support-with-iconfigurenamedoptions)

Improve IConfigureNamedOptions API link text

---

aspnetcore/security/authentication/identity.md

Fixes #10081 (again).
The project's folder structure changed from `src/UI` to `UI/src`, so I've addressed that and pinned the link to the 2.2 branch to try and limit future issues.

Updated link to 2.2 AddDefaultIdentity source.

---

aspnetcore/performance/caching/response.md

Fixes #10095 
* A small introduction enhancement to clarify the `ResponseCache` attribute and Response Caching Middleware.
* Fix a link to the issue that discusses providing a purely server-side caching scenario to the middleware.

Enhance response caching introduction

---

aspnetcore/fundamentals/environments/sample-snapshot/EnvironmentsSample/Pages/About.cshtml

Fixes #10228 
Quick patch for the *About.cshtml* snapshot that the topic states will show how the Environment Tag Helper works. One way to fix this would be to use a snippet block in the non-snapshot *About.cshtml* file. However since the snapshot exists, the fastest way to fix this is just to place the TH code into the snapshot file. The next author to perform a major update on the topic can take further steps.
The code appears for the 2nd code block of :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/environments#environments
Thanks @serpent5 :rocket: for reporting this.

Update snapshot to show Tag Helper

---

aspnetcore/migration/proper-to-2x/membership-to-core-identity.md

Fixes https://github.com/aspnet/Docs/issues/8022
- Added UPPER function calls in the SQL script for the 2 Normalized columns used in Identity
- Improved readability of the SQL script
- Improved Markdown formatting of tables
- Added a missing step for viewing the local Identity DB

Convert Normalized Identity column values to upper case

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/migration/21-to-22.md

Fixes #10343
Including a code sample should help, so I add one to the migration and Kestrel topics. Let me know if you would like to add more detail. This doesn't get into the weeds on **_why_**, which might be ok.

Update Kestrel configuration sections

---

aspnet/web-api/overview/advanced/dependency-injection.md

The link to StructureMaps' home page was pointing to a shady site. Update it to http://structuremap.github.io/documentation/

Update link to StructureMap

---

aspnetcore/fundamentals/routing.md

Fixes #10365
The link is rendered for 2.2, so I'll try relative to see if that fixes it.

Convert xref link to relative

---

aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api/samples/sample2.cshtml

The current version of default scaffolding jQuery library in ASP.NET MVC is v3.3.1. 
And the jqXHR.error() method has been replaced with jqXHR.fail() after jQuery 3.0.
You can see this on this page: http://api.jquery.com/jQuery.ajax/#jqXHR
```
Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.
```

Update jqXHR.error() method into jqXHR.fail() method after jQuery 3.0

---

aspnetcore/host-and-deploy/azure-apps/troubleshoot.md
aspnetcore/host-and-deploy/azure-iis-errors-reference.md
aspnetcore/toc.md

Fixes #5297 
Always a **_"fun"_** one to work. 😅 lol
* Updated common errors for ANCM v2/2.2 scenarios. Includes:
* *Missing .NET Core shared framework* section
* Direct download for the hosting bundle
* Azure Apps *Troubleshoot* topic
* The portal changed. This re-aligns the topic to the portal.
* We should remove "startup errors" from the Azure Apps *Troubleshoot* title. It's for more than that.
* Add the ASP.NET Core Module debug log.
* TOC
* You moved the ANCM topic out of the *host-and-deploy* node, but that was placed there by-design so as not to hide it from Azure Apps users who might not look inside the IIS node. The content is *highly relevant* to Azure Apps scenarios. However, it isn't much more useful than that, so I figure what we can do is add the same link in the Azure Apps …

Common errors topic update

---

aspnetcore/toc.md

"Backend for mobile apps" tutorial was in the wrong place, move it to Web API section.

Move a toc node

---

CONTRIBUTING.md

I worked out some updated (better imo) instructions for building docs with Mono on macOS [for the Blazor docs](https://github.com/aspnet/Blazor.Docs/pull/319). Moving those instructions over to this doc set following an ask on Slack.

Update Mono instructions for building the docs

---

.ghal.rules.json

Automatically apply the **SignalR** label to issues for docs residing in the following paths of the **master** branch:
1. aspnetcore/signalr
1. aspnetcore/tutorials/signalr*

Configure automatic labeling of SignalR issues

---

aspnetcore/tutorials/first-mongo-app.md

For some reason the \ is acting like an escape character in the md. Alternatively adding \\ between Server and version number <version_number> fixed it in the preview. "Server\\<version_number>

escape character in md

---

aspnetcore/mvc/views/view-compilation.md

Fixes #10108
* Taken just about verbatim from the [API reference](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptions.cs#L198-L243) ... don't think we need engineering for this one.
* Note that I can't link 2.2 API until that issue is fixed, so I code fence the bits here. I'm noting on my 2.2 tracking issue to hit this up with proper API links later.

Document AllowRecompilingViewsOnFileChange

---

aspnetcore/data/ef-rp/intro/samples/cu21/Pages/About.cshtml.cs

Fixes #10676
This pull request will fix the below issue:
In section "Update the About page model", in the About.cshtml.cs code, the reference to ContosoUniversity.Data isn't mandatory as the 2 classes in the Data folder (Dbinitializer.cs and Schollcontext.cs) are in the ContosoUniversity.Models namespace.

removed unused using statement

---

aspnetcore/migration/21-to-22.md

Encountered a typo while browsing the migration guide from ASP.NET Core 2.1 to 2.2.

Fix casing of configuration property

---

aspnetcore/toc.yml

Fixes #10699 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-1.0&branch=pr-en-us-10698) (goes to an article in the deployment section of the TOC.  Note that the new links 404 from staging -- when you get the 404, remove "review." from the link and you'll get the doc it's linking to.)

Add VS for Mac deploy articles to TOC

---

aspnetcore/migration/22-to-30.md
aspnetcore/migration/22-to-30/samples/Program.cs
aspnetcore/migration/22-to-30/samples/Program2.2.cs

Fixes #10618, Fixes  #10711 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&branch=pr-en-us-10718&tabs=visual-studio#generic-host-replaces-webhostbuilder)

Add HostBuilder to 3.0 migration docs

---

aspnetcore/toc.yml

Fixed a parent node that was linked to a URL.
@Rick-Anderson Also changed name of RP Intro article node from Overview to Introduction, thinking that may better reflect the extent of the content in this article (Overview implies something more superficial). Feel free to change it back if you don't think the change will have the desired effect.

Changes to RP node of TOC

---

aspnetcore/fundamentals/url-rewriting/samples/2.x/SampleApp/SampleApp.csproj

Using the plural TargetFrameworks element will cause an 'unable to run your project' error on 'dotnet run' command. Switching to use singular TargetFramework can fix it and also avoid confusing beginners.

Use singular TargetFramework element

---

aspnetcore/includes/net-core-prereqs-mac-3.0.md

From Matt Ward ...
> Unfortunately Visual Studio for Mac 7.7 does not support .NET Core 3.0. The bug here is that the New Project dialog shows 3.0 as a target framework - it should not be listed.
> More recent Visual Studio for Mac 8.0 versions should have support for .NET Core 3.0.
> New project templates need to be enabled in Visual Studio for Mac. New project templates available in the installed .NET Core sdk are not automatically available in the IDE. Right now Visual Studio on Windows has more project templates enabled than Visual Studio for Mac, such as the angular and react templates.
This came about because I attempted to use the 3.0 Preview 2 SDK with VS for Mac 7.7.4 and it :boom:.
Not sure if the last point will require another line in the prereqs here. I suspect that 8.0 with …

Change VS version for 3.0 on macOS

---

aspnetcore/razor-components/get-started.md
aspnetcore/razor-components/get-started/samples_snapshot/3.x/Counter1.cshtml
aspnetcore/razor-components/get-started/samples_snapshot/3.x/Counter2.cshtml
aspnetcore/razor-components/get-started/samples_snapshot/3.x/Index1.cshtml
aspnetcore/razor-components/get-started/samples_snapshot/3.x/Index2.cshtml
aspnetcore/razor-components/get-started/samples_snapshot/3.x/launch.json
aspnetcore/razor-components/get-started/samples_snapshot/3.x/tasks.json

Fixes #10765 
Updates the *Get started* topic to go with the RC model.
The only prob is VS for Mac. I have the SDK on the iMac working now. :tada:
References:
* https://github.com/aspnet/AspNetCore/issues/5490
* https://developercommunity.visualstudio.com/content/problem/444024/create-button-doesnt-create-new-project-for-30-pre.html
* https://github.com/dotnet/core/issues/2263#issuecomment-460054012
**Note on VSC**: We can't count on VSC producing the *tasks.json* and *launch.json* files for us given that the template is a solution with two project inside of it. VSC won't do that for us in this scenario. Therefore, I instruct the dev on how to create those two files in the right spot. Providing the files has the added advantage of explicitly setting the TFM+assembly in the file ... …

Razor Components: Get started topic update

---

aspnetcore/toc.yml

Point to the 2.2 APIs now that they're published.

Update API ref ToC link to ASP.NET Core 2.2

---

aspnetcore/host-and-deploy/windows-service.md

Fixes #10836
* Call out use of admin command shell when running commands.
* Explicitly grant `Log on as a service` privilege to the user account.
* Call out MSA as an alternative approach with AD. Confirm that I chose a good link for that scenario.
* Call out default password expiry of six weeks.

Windows Service topic enhancements

---

aspnetcore/docfx.json

I doubt we'll be nesting folders below *blazor*, so it should be ok without `/**/` in the path.

Update razor-components in docfx.json

---

aspnetcore/mvc/compatibility-version.md

Fixed the link to MvcOptions in Compatibility Version documentation
[Link to current docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-2.2)

Fixed broken link to MvcOptions source file

---

aspnetcore/client-side/spa/blazor/get-started.md

The Blazor template package now has a preview moniker, so you need to specify the version explicitly.

Update step for installing Blazor CLI templates

---

aspnetcore/fundamentals/dependency-injection.md

Updating the link to readme in the "Default service container replacement" section to point to the readme in the new extension repo.

Updating a URL to point to the correct extensions repo

---

aspnet/mvc/mvc5.md

https://attributerouting.net/ doesn't go to Tim McCall's website anymore so I don't think it's what you want to link to. I updated the route to point to the code for AttributeRouting on Github.

Change link for AttributeRouting library

---

aspnetcore/security/authorization/policies.md

Corrected "has succeed" to "has succeeded"
Updated description to reflect the provided code sample: code used "is", description incorrectly suggested to use "as".

Corrected typos

---

aspnetcore/mvc/compatibility-version.md

Because it's much easier to read and navigate a rendered html page than comments on GitHub.

Link to MvcOptions doc instead of source code

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/performance/caching/middleware.md

**Apologies for the length of these remarks :point_down:, but there be 🐉 here.**
Addresses #10987 
@shapeh and I deliberated a bit further: Turns out that we aren't covering "terminal middleware" very well. The last PR didn't go far enough.
"Terminal middleware" only appears in the *Built-in middleware* table of the Middleware topic and assumes that the reader will define it correctly.
* I've elaborated on it in the Middleware topic ... both early where "short-circuiting" is described and later where it's used in the table.
* The Response Caching topic now has a spot that we can link directly for *terminal middleware* (and then links to the whole topic as 'for more info, see'). I link to the table because the caching topic is saying that 'a terminal middleware' must not process the …

"Terminal middleware" enhancements

---

aspnetcore/fundamentals/servers/httpsys.md

Fixes #11025
* Clarify that there are two locations here: VM/server firewall **_AND_** (in Azure VM case), NSG for the VM. Best to split them in the list, which calls it out better.
* Link the firewall remark.
* Better link for the PS cmdlet.
* Better link for the NSG remark.

Clarify Azure NSG+VM/server firewall config

---

aspnetcore/host-and-deploy/azure-iis-errors-reference.md

Fixes #10940
@shirhatti This is a bit detailed in terms of providing a solution that would allow an earlier hosting bundle install to work.
The alternative is to describe the problem generally and don't give the dev an option on using the latest hosting bundle ... just guide them to use the latest if uninstalling and installing an earlier version isn't supported by engineering. Let me know if you prefer that approach.

Surface hosting bundle downgrade common error

---

aspnet/web-api/overview/security/working-with-ssl-in-web-api.md

MakeCert.exe is pointing to an old link which now says:
This topic is no longer available
The information in this topic is now moved to the following topic: https://msdn.microsoft.com/library/windows/desktop/aa386968.aspx.
Hence updating the link.

Update MakeCert.exe link in the Working with SSL in Web API doc

---

aspnetcore/security/key-vault-configuration.md

Clarified that Managed Identity does not require secrets since the resource calling Key Vault will be authorized by Azure AD.

Managed Identity does NOT require secrets in app

---

aspnetcore/host-and-deploy/aspnet-core-module.md

Fixes #9985
Related to the fix provided by: [Backport the current directory fix to 2.2.x (aspnet/AspNetCore 4599)](https://github.com/aspnet/AspNetCore/issues/4599)
Original PR: [Workaround for base dir when hosting in-process (aspnet/Docs 9873)](https://github.com/aspnet/Docs/pull/9873)

Revert workaround for base dir when in-process

---

aspnetcore/fundamentals/host/hosted-services.md
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-GenericHost/BackgroundTasksSample.csproj
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-GenericHost/Program.cs
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/BackgroundTasksSample.csproj
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Data/AppDbContext.cs
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Data/Message.cs
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Pages/Error.cshtml
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Pages/Error.cshtml.cs
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Pages/Index.cshtml
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Pages/Index.cshtml.cs
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Pages/Shared/_Layout.cshtml
aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-WebHost/Startup.cs

Fixes #10381 
[Internal Review Topic (Queued background tasks section)](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&branch=pr-en-us-11035#queued-background-tasks)
* Have the queued background task write status messages to a database.
* Take both of the hosted services samples to 2.2.

dB scope in a hosted service example + 2.2 updates

---

aspnetcore/tutorials/first-mvc-app/adding-model.md

Ran through the tutorial today and this warning didn't occur on my machine (running MacOS and dotnet SDK 2.2.104).

Remove obsolete warning reference

---

aspnetcore/razor-components/components.md

The @ symbol was causing the Directive column values to not render. Added `\` to have the values render properly on the final output.

Fixed Directive name does not render in column

---

aspnetcore/mvc/views/layout.md

Fixes #11110
I'm not super happy with the oversimplification here ...
> The folder where the handler method (or controller) exists is searched first, followed by the *Shared* folder.
... but for the algorithm that searches, it's not really inaccurate, just oversimplified. We could pull this sentence here and let the link *do the talk'in*.

Directly link partial view discovery in Layouts

---

.gitignore
.vscode/extensions.json

Fixes https://github.com/aspnet/Docs/issues/11115
Altered the *.gitignore* file to allow check-in of the *extensions.json* file. Suggests the Docs Authoring Pack extension for VS Code.

Add suggested extensions file for aspnet/Docs repo

---

aspnetcore/client-side/spa/angular.md

Fixes #10501 and #8139.
This PR removes the Angular SSR documentation from the docs. When the Angular template initially shipped it included SSR as a built-in feature. Since we've moved the Angular template to be based on the Angular CLI, SSR is no longer included. Instead of trying to maintain our own instructions in the ASP.NET Core docs for enabling Angular SSR we recommend referring to the [Angular docs directly](https://angular.io/guide/universal).

Remove Angular SSR documentation

---

aspnetcore/test/load-tests.md

Added a note that the web performance and load testing tools in Visual Studio is deprecated and will be removed after VS 2019 as was announced here: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#test-tools
In the same note, a line was added about the load testing service in Azure DevOps closing in 2020 from the announcement here: https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

Added note about deprecated features

---

.gitignore

Related to https://github.com/aspnet/Docs/pull/11116. Restores the original *.vscode* pattern.

Fix glob pattern in .gitignore

---

aspnetcore/razor-components/hosting-models.md

`blazor.server|webassembly.js` are now `components.server|webassembly.js` as of ASP.NET Core 3.0 preview 2

updated referenced JS files

---

aspnetcore/razor-components/javascript-interop.md

`using Microsoft.AspNetCore.Blazor;` is now `using Microsoft.AspNetCore.Components;` as of ASP.NET Core 3.0 preivew 2

Updated namespace usage

---

aspnetcore/razor-components/components.md

`BlazorLayoutComponent` became `LayoutComponentBase` in ASP.NET Core preview 2 when Razor Components was extracted from Blazor.

Update BlazorLayoutComponent > LayoutComponentBase

---

aspnetcore/razor-components/layouts.md

`BlazorLayoutComponent ` was changed to `LayoutComponentBase` in ASP.NET Core 3.0 preview 2 when Razor Components were extracted from Blazor.

Update BlazorLayoutComponent LayoutComponentBase

---

aspnetcore/fundamentals/startup.md

`Startup` class constructor actually receives `Microsoft.Extensions.Configuration.IConfiguration` instead of `Microsoft.Extensions.Configuration.IConfigurationBuilder`

Update startup.md for startup class constructor params

---

aspnetcore/mvc/views/tag-helpers/built-in/index.md
aspnetcore/mvc/views/working-with-forms.md

- Utilized the `AnchorTagHelper` docs to consistenly describe the `asp-` attributes used to control how links get generated.
- Updated the built in TagHelper list doc to include the FormAction TagHelper.
#10593 
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.2&branch=pr-en-us-11192#the-form-action-tag-helper)

Add Form Action Tag Helper docs

---

aspnetcore/host-and-deploy/azure-iis-errors-reference.md

Fixes #10725 
> Confirm that the app's **Platform** in **Application Settings** matches the bitness of the app.
~I still haven't figured out how to recover a 32-bit app set to 64-bit in the portal and then set back to 32-bit. It doesn't seem to recover on its own by merely flipping the switch in the portal back to 32-bit and restarting the app. I show the errors from logging back over on the issue for this scenario.~
~It does recover if the x86 + x64 site extensions are present and then the x64 site extension is deleted (or the site extension is just added and then deleted and added back) ... of course, following a restart of the site.~
Checked with a fresh service this morning, and I can't repro the failure behavior. I think there is **_some combo_** of adding and subtracting site …

Add more ANCM startup failures

---

aspnetcore/performance/caching/distributed.md

Addresses #11118 
Thanks @marekkar
@natemcmaster Need a tip .... I couldn't get API Browser links for: 
* `AddStackExchangeRedisCache`
* `RedisCache` (in the `Microsoft.Extensions.Caching.StackExchangeRedis` namespace)
They live for 2.2 ...
https://github.com/aspnet/Extensions/blob/release/2.2/src/Caching/StackExchangeRedis/src/StackExchangeRedisCacheServiceCollectionExtensions.cs#L23
https://github.com/aspnet/Extensions/blob/release/2.2/src/Caching/StackExchangeRedis/src/RedisCache.cs#L13
... and here's the 2.2 package ...
https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis/2.2.0
... but no :heart: from the API Browser ...
Is that something that someone needs to know?
I've code-fenced them into the topic, so we can proceed here without the API pages if that's …

Update Redis section of dist caching

---

aspnetcore/signalr/configuration.md

Fixes #11125 
Adds guidance on how to configure the various options on the SignalR Java client. 
[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1&branch=pr-en-us-11143)

Update config doc with Java client

---

aspnetcore/signalr/streaming.md

Fixes: #9771 
Adding a section on the `hubConnection.stream` api for the java client
[Internal review link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.1&branch=pr-en-us-11227)

Java server to client streaming

---

aspnetcore/tutorials/razor-pages/model.md

Moved the PMC commands warning "The preceding commands generate the following warning..." to align with the section it is referring to.  It was presented too early in the topic.

Moved PMC commands warning

---

aspnetcore/migration/22-to-30.md
aspnetcore/mvc/views/view-compilation.md

Fixes #11232
This heading ...
> \#\# Moving from WebHostBuilder to HostBuilder
... didn't seem to make sense because the prior section is addressing the same migration aspect. These two sections were probably added at different times (guessing), which would explain the (accidental) appearance of both.
I see a handful of little super-nits in the view comp file beyond the few that I touch here (mostly punctuation on this PR), but I'll leave those unless you want me to edit the file.

Migration section on runtime comp

---

aspnetcore/fundamentals/routing.md

Fix typo: wrong placement of a back-tick character

Fix typo: wrong placement of a back-tick character

---

aspnetcore/fundamentals/app-state.md

Fixes #11269 
Bit of a *nit PR*. The original text is good. This just clarifies a bit further by explicitly stating that the site visitor must permit tracking under GDPR for sessions to work.

Session state/GDPR clarification

---

aspnetcore/signalr/messagepackhubprotocol.md

There are some known issues/quirks in the MessagePack Hub Protocol for SignalR. We should call them out in our docs instead of making users search GitHub for these answers :).
[Internal Review Version](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.1&branch=pr-en-us-11170)

Add section on SignalR MessagePack "known issues"

---

aspnetcore/fundamentals/servers/kestrel.md

Fixes #11263
Moves the URL-setting approaches up in the *Endpoint configuration* section prior to their first mention in the section (provides context for the following remarks).
Thanks @gaziqbal.

Update Kestrel topic endpoint config section

---

aspnetcore/host-and-deploy/azure-apps/troubleshoot.md

Added info on how you can start a 64-bit app using the 64-bit version of dotnet.exe.

Update for 64-bit

---

aspnetcore/security/authorization/policies.md

In #10976, @blowdart pointed out that `IAuthorizationHandler` implementations don't have to be registered as singletons.

Reference Service Lifetimes from Policies for Handler registration.

---

aspnetcore/security/gdpr.md
aspnetcore/security/gdpr/sample/RP/Startup.cs

Fixes #11088 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1&branch=pr-en-us-11306#tempdata-provider-and-session-state-cookies-are-not-essential)

How to make session cookies essential/GDPR

---

aspnetcore/toc.yml

Fixes #10207
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&branch=pr-en-us-11293&tabs=visual-studio)
@Rick-Anderson @scottaddie @wadepickett I've implemented this for one series -- all tutorials in the RP Intro series are duplicated under the Tutorials top-level node and the subject area top-level node (Web apps).  When you click on a link in the ToC, only the node you clicked on is highlighted, but when you get to one of these tutorials some other way, like clicking Next or Previous buttons, the same tutorial in both places in the ToC is highlighted.  Since you'd normally be using Next/Previous in a series, most of the time you'd see two nodes highlighted, which is not ideal.  Is it worth putting up …

Duplicate ToC  nodes for tutorial series

---

aspnetcore/toc.yml

Fixes #8855
This fixes the problem of switching ToC's.  I'll add breadcrumb handling in a separate PR, since I have to test that after the breadcrumb/toc.yml file goes to live.

Add toc query string to external link toc nodes
