dotnet/AspNetCore.Docs

aspnetcore/security/authentication/scaffold-identity.md
=> Disable pages in Identity UI

aspnetcore/security/authentication/certauth.md
Fixes #18681
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0&branch=pr-en-us-18684#optional-client-certificates)
=> Optional client certs

aspnetcore/mvc/views/razor.md
Fixes #18771
cc @JasonCard  : I'll get this merged to live in the next hour
=> fence reserved keywords

aspnetcore/fundamentals/http-requests.md, aspnetcore/mvc/views/razor.md, aspnetcore/security/authentication/certauth.md, aspnetcore/security/authentication/scaffold-identity.md
=> Merge master to Live 6-11 2nd for loc fixes

aspnetcore/security/authorization/iauthorizationpolicyprovider.md
=> make clear custom policy requirements

aspnetcore/security/blazor/webassembly/azure-active-directory-groups-and-roles.md
Find-'n-replace ... gotta :heart: it ... *when used correctly!* 🙈
=> Fix two bad API doc crosslinks

aspnetcore/mvc/views/razor.md
=> fence folders

aspnetcore/includes/catchall.md
=> CatchAll bug fix released

aspnetcore/blazor/hosting-model-configuration.md, aspnetcore/fundamentals/logging/index.md, aspnetcore/includes/catchall.md, aspnetcore/includes/net-core-prereqs-vs-5.0.md, aspnetcore/migration/22-to-30.md, aspnetcore/mvc/views/razor.md, aspnetcore/release-notes/aspnetcore-3.0.md, aspnetcore/security/authorization/iauthorizationpolicyprovider.md, aspnetcore/security/blazor/webassembly/azure-active-directory-groups-and-roles.md, aspnetcore/signalr/authn-and-authz.md, aspnetcore/signalr/configuration.md, aspnetcore/signalr/diagnostics.md, aspnetcore/signalr/dotnet-client.md, aspnetcore/signalr/groups/sample/wwwroot/ts/chat.ts, aspnetcore/signalr/hub-filters.md, aspnetcore/signalr/hubcontext.md, aspnetcore/signalr/hubs/sample/wwwroot/ts/chat.ts, aspnetcore/signalr/javascript-client.md, aspnetcore/signalr/javascript-client/sample/wwwroot/ts/chat.ts, aspnetcore/signalr/messagepackhubprotocol.md, aspnetcore/signalr/security.md, aspnetcore/signalr/security/sample/Startup.cs, aspnetcore/signalr/version-differences.md, aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Pages/Index.razor, aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/Startup.cs, aspnetcore/tutorials/signalr/sample-snapshot/2.x/Startup.cs, aspnetcore/tutorials/signalr/sample-snapshot/3.x/Startup.cs
=> Merge main to live 6-12

aspnetcore/fundamentals/configuration/index.md
=> fixed link to the command-line config provider

aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md, aspnetcore/security/blazor/webassembly/additional-scenarios.md, aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md, aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md
Fixes #18799
Thanks @dajma00! :rocket: ... I clarified the placeholder in every Blazor topic where it appears.
=> Clarify Blazor placeholder "{APP ASSEMBLY}"

aspnetcore/blazor/event-handling.md
Fixes #18461
Thanks @ndc! :rocket:
=> Update Blazor EventCallback example

aspnetcore/blazor/progressive-web-app.md
Fixes #18436
Thanks @Ponant! :rocket:
=> Clarify Blazor topic PWA-SPA remark

aspnetcore/security/authentication/identity-api-authorization.md
=> Add reference for ApiAuthorization nuget package

aspnetcore/signalr/configuration.md
New option in 5.0 and old option we never documented.
=> Add 'headers' option to docs

aspnetcore/fundamentals/configuration/index.md, aspnetcore/host-and-deploy/azure-apps/index.md, aspnetcore/host-and-deploy/health-checks.md, aspnetcore/host-and-deploy/linux-apache.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/migration/http-modules.md
Fixes #18785.
Fixes #18811.
cc @Rick-Anderson, @guardrex
=> Patch up a few broken anchor references

aspnetcore/fundamentals/routing.md, aspnetcore/migration/22-to-30.md, aspnetcore/security/authorization/claims.md, aspnetcore/security/authorization/policies.md
Fixes #18737.
I broke the work into multiple commits for visibility. I can revert the last one if it's out-of-scope, but I know "ing"s aren't popular around here.
=> Cover how to access HttpContext in an authz handler

aspnetcore/host-and-deploy/linux-nginx.md
=> Clarify OR when describing HSTS for Linux+nginx

aspnetcore/migration/22-to-30.md
=> Add a note about output formatter buffering

aspnetcore/blazor/index.md
Fixes #18867
I'll go ahead and say "or later" to future-proof it a bit.
Thanks @operationslazlo326! :rocket:
=> Update Blazor .NET Standard content

aspnetcore/tutorials/razor-pages/validation.md
Fixing minor grammatical and formatting issues.
=> fixing minor errors in validation.md

aspnetcore/mvc/controllers/filters.md
Fixes #17216.
It still surprises me how long it can take to decide exactly how to word something like this. I hope it's OK as a note - I want to draw attention to it to frame the rest of the section.
=> Mention and link to auto-400s for [ApiController]

aspnetcore/blazor/components/event-handling.md
Fixes #18856 
Thanks @pstricks-fans! :rocket:
=> Improve Blazor event arg types content

aspnetcore/blazor/fundamentals/logging.md
Fixes #18888
Thanks @serpent5! 🎷
=> Fix cross-link

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/Tab.razor, aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/TabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/CascadingValuesParametersTabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/Tab.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/TabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CascadingValuesParametersTabSet.razor
Fixes #18865
The user triggers `ActivateTab`, and `SetActiveTab` is used to set the tab.
Thanks @serpent5! 🐢 ..... Do u want to 👀 this to make sure that I didn't create a PR :poop:? :smile:
=> Update Blazor common sample example

aspnetcore/fundamentals/dependency-injection.md
Fixes #17052
Thanks @Orwel! :rocket: ... sorry for the delay. We've been 🏃😅 working thru a lot of issues. We'll see how engineering wants to tweak this on review.
=> DI service lifetime disposal relative to requests

aspnetcore/fundamentals/logging/index/samples/3.x/TodoApiDTO/appsettings.Prod2.json
Fixes #18880 
Move "EventSource" from under "Debug" section to "Logging" section
=> Fix worng configuration example for logging

aspnetcore/data/ef-rp/read-related-data.md
Adding bold to `Note:` prefix and correcting punctuation in paragraph about the `Where` method returning a collection and using `Single`.
=> updating formatting and fixing grammatical error

aspnetcore/blazor/security/server/index.md
=> Address Blazor Server heading

aspnetcore/tutorials/build-your-first-blazor-app.md
=> Clarify component file name casing

aspnetcore/host-and-deploy/health-checks.md
Fixes #18857
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2&branch=pr-en-us-18873#separate-readiness-and-liveness-probes)
Thanks @OldrichDlouhy! :rocket:
cc: @unaizorrilla
=> Health checks liveness and readiness

aspnetcore/security/authentication/add-user-data.md
=> Note that sub-topic isn't an extension of tutorial

aspnetcore/blazor/components/data-binding.md
=> Fix typo in chained bind explanation.

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #18863
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-18937#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client)
We already had a section for anonymous access, so I enhance the remarks in that section.
=> Enhance Blazor WASM unauth endpoint access

aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/DetectIncorrectUsagesOfTransientDisposables-server.cs, aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/DetectIncorrectUsagesOfTransientDisposables-wasm.cs, aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/server-program.cs, aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/server-startup.cs, aspnetcore/blazor/fundamentals/dependency-injection/samples_snapshot/3.x/transient-disposables/wasm-program.cs
Fixes #18786
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-18956#detect-transient-disposables)
=> Blazor transient disposables

aspnetcore/blazor/debug.md
Fixes #18434
Thanks #TPJ11! :rocket:
=> Add Blazor VS debugging troubleshoot entry

aspnetcore/blazor/components/index.md
Fixes #18036
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-18958#synchronization-context)
Are there more methods to list here? :ear:
I *stole* 👮‍♂️🚓 the list from our friend, @StephenCleary, who wrote a [best practices for async/await MSDN Magazine article](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming) several years ago with this list. *Hopefully, he won't press charges!* :smile:
=> Blazor async guidance

aspnetcore/blazor/webassembly-performance-best-practices.md
Fixes #18420
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-2.1&branch=pr-en-us-18957#avoid-unnecessary-component-renders)
Thanks @SQL-MisterMagoo! 🌴 ... I'm glad it didn't take six months to get to this one. 😅
=> Blazor WASM perf ShouldRender updates

aspnetcore/test/middleware.md
Fixes #18948
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-3.1&branch=pr-en-us-18969#set-up-the-testserver)
=> TestServer comes in a package

aspnetcore/security/authorization/simple.md
* Use dedicated controllers for mixed attributes
* Update aspnetcore/security/authorization/simple.md
Co-authored-by: Pranav K <prkrishn@hotmail.com>
Co-authored-by: Pranav K <prkrishn@hotmail.com>
=> Merge Main to live.

aspnetcore/tutorials/getting-started-with-swashbuckle.md, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Startup2.cs, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Startup2.cs, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Startup3.cs
Closes #16195 
cc: @bradygaster
=> Swashbuckle update

aspnetcore/performance/caching/response.md, aspnetcore/performance/caching/response/samples/2.x/ResponseCacheSample/README.md, aspnetcore/performance/caching/response/samples/3.x/Startup.cs
Fixes #18193
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-3.1&branch=pr-en-us-18971#cache-profiles)
=> Update Response caching

aspnetcore/data/entity-framework-6.md, aspnetcore/performance/ObjectPool/ObjectPoolSample/BirthdayMiddleware.cs, aspnetcore/performance/ObjectPool/ObjectPoolSample/Startup.cs, aspnetcore/performance/caching/response.md, aspnetcore/performance/caching/response/samples/2.x/ResponseCacheSample/README.md, aspnetcore/performance/caching/response/samples/3.x/Startup.cs, aspnetcore/tutorials/getting-started-with-swashbuckle.md, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Startup2.cs, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Startup3.cs
=> Merge main to live

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #18984
Thanks @zequential! :rocket:
=> Fix code block

aspnetcore/fundamentals/host/generic-host.md
Fixes #18996
Thanks @atykhyy! :rocket:
=> Clarify remark on IHostedService startup

aspnetcore/fundamentals/localization.md, aspnetcore/includes/dbg-route.md
Updates from the build report on https://github.com/dotnet/AspNetCore.Docs/pull/18999.
=> Build report patches and formatting nits

aspnetcore/fundamentals/error-handling.md
=> Db error page/ra

aspnetcore/performance/ObjectPool.md
Fixes #16747
/cc: @Rick-Anderson
=> ObjectPool notes about IDisposable support

aspnetcore/includes/RP/model3.md, aspnetcore/includes/ef-cli.md, aspnetcore/security/authentication/identity.md, aspnetcore/tutorials/first-mvc-app/adding-model.md
=> instructions for adding global EF command

aspnetcore/fundamentals/dependency-injection.md
Fixes #16323
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-19008#request-services)
@mkArtakMSFT  please review or suggest a reviewer.
=> Explain Request services/DI

aspnetcore/fundamentals/static-files/samples/3x/sample/Program.cs, aspnetcore/fundamentals/static-files/samples/3x/sample/StartupBrowse.cs, aspnetcore/fundamentals/static-files/samples/3x/sample/StartupFileExtensionContentTypeProvider.cs, aspnetcore/fundamentals/static-files/samples/3x/sample/StartupRose.cs, aspnetcore/fundamentals/static-files/samples/3x/sample/StartupUseFileServer.cs
Fixes #16657
@halter73  please review or recommend a reviewer.
@BWCutters-DBirch please review.
=> Replace Directory.GetCurrentDirectory() with xplat env versions

aspnetcore/grpc/browser.md
Fixes https://github.com/grpc/grpc-dotnet/issues/963
=> gRPC-Web with bidirectional streaming on IIS/Azure

aspnetcore/blazor/fundamentals/configuration.md
Fixes https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/287
谢谢 @gtools! :rocket:
=> Patch Blazor cofiguration example

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
Fixes #19025
Thanks @rleath82! :rocket:
=> Fix incorrect UI text

aspnetcore/blazor/forms-validation.md
Fixes #18973
Thanks @lfrancke! :rocket: ... I'll pick up with additional updates for server validation (hopefully including an `OnFieldChanged` approach) on the existing issue https://github.com/dotnet/AspNetCore.Docs/issues/17377.
=> Blazor forms validation and service injection

aspnetcore/blazor/fundamentals/routing.md
Fixes #19033
Thanks @serpent5! 🐢
=> Blazor routing updates

aspnetcore/fundamentals/environments.md
=> Clarify dotnet run launch profile limitation

aspnetcore/fundamentals/configuration/index.md
=> values set in launchSettings.json override values set in the system

aspnetcore/includes/SameSiteIdentity.md, aspnetcore/security/samesite.md, aspnetcore/security/samesite/mvc21.md, aspnetcore/security/samesite/rp21.md, aspnetcore/security/samesite/rp31.md
Fixes #18057
Internal review URLs:
* [SameSite and Identity](https://review.docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-1.0&branch=pr-en-us-19024#samesite--and-identity)
* [ASP.NET Core 2.1 MVC SameSite cookie sample](https://review.docs.microsoft.com/en-us/aspnet/core/security/samesite/mvc21?view=aspnetcore-2.1&branch=pr-en-us-19024)
* The rest look the same.
=> Identity and SameSite

aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #17189
Thanks @adam000! :rocket: ... Sorry for the delay. We've been very busy 🏃😅. I'm finally digging out ⛏️⛰️.
=> Add usings to examples in Blazor DI topic

aspnetcore/fundamentals/portable-object-localization.md
Link for "View or download sample code" returns a 404.
=> Fix of broken link

aspnetcore/blazor/components/index.md
Fixes #19080
Thanks @serpent5! :turtle:
Yeah ... the find-'n-replace was a bit too aggressive and broke this link. I didn't see it on the review pass. 🙈
=> Fix Blazor common sample link

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/TabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/CascadingValuesParametersTabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/TabSet.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CascadingValuesParametersTabSet.razor, aspnetcore/blazor/components/cascading-values-and-parameters.md, aspnetcore/blazor/components/index.md
Fixes #19090
Fixes #19092
Thanks @serpent5! 🎷
I'm going to leave the basic `RenderFragment` (child content) section alone at this time and not cross-link it down to templated components. It's early in the reader's learning curve, and they'll get to templated components soon in the Components ToC node. I'll take another look :eyes: at this when I edit this topic later.
=> Blazor topic feedback

aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/fundamentals/handle-errors.md
Fixes  #17955
Thanks @pekspro! :rocket: ... sorry for the delay. We've been 🏃 on high priority issues for quite a while. WRT class replacement, they're still working on that in engineering. There will be another update for .NET 5 if they implement a solution. For now, we can cover the stylesheet class.
=> Surface Blazor validation message styling

aspnetcore/blazor/debug.md
Fixes #18439
Thanks @snerks :rocket: ... sorry for the delay. We've been working a lot of high priority issues recently.
=> Improve Blazor Debug in the browser guidance

aspnetcore/security/authentication/identity-api-authorization.md
https://github.com/aspnet/Announcements/issues/380
=> UIFramework.Bootstrap4 is not supported anymore

aspnetcore/blazor/components/event-handling.md
Fixes #18977
Thanks @pstricks-fans  and @serpent5! 🌴
I'll go ahead and put this in, and Artak can let me know later if I need to patch it.
=> Clarify InvokeAsync argument types

aspnetcore/blazor/call-dotnet-from-javascript.md, aspnetcore/blazor/call-javascript-from-dotnet.md
Fixes #17966
Thanks @CliffConway! :rocket: ... Sorry for the delay. We've been busy with high priority updates for several months. 🏃😅
=> Component JS invoking app assembly placeholder

aspnetcore/blazor/fundamentals/additional-scenarios.md
Fixes #12569
Thanks @sowsan! :rocket: ... Sorry for the delay. It's taken a while to work thru the backlog of high priority issues.
=> Update SignalR reconnect modal guidance

aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Components/TableTemplate.razor, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/TableTemplate.razor
Fixes #19128
Thanks @serpent5! 🎷 ... bonus on this one ... it saves some space vertically to slightly reduce scrolling. :+1:
=> Drop TableFooter from Blazor sample app

aspnetcore/blazor/tooling.md
=> Add and improve dev cert trust

aspnetcore/data/ef-rp/concurrency.md, aspnetcore/fundamentals/routing.md
=> Sweep up a few typos

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes #19151
Thanks @Ef0Dev! :rocket:
=> HttpClient config in Blazor IdS topic

aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/StartupGF.cs
=> Fix indentation

aspnetcore/web-api/handle-errors.md
Fixes #19192
Thanks @heemskerkerik! :rocket:
=> Fix namespace/API docs cross-link

aspnetcore/fundamentals/app-state.md
=> Add line highlight and use xrefs

aspnetcore/data/entity-framework-6.md
=> Fix link to EF6 docs

aspnetcore/blazor/debug.md
Fixes #19204
I don't think we need to say more than what the config options explain. The bits work OOB as described (with the touch-ups on this PR).
=> Update Blazor debug for hosted config and Edge

aspnetcore/fundamentals/middleware/index.md
Encode asterisks in existing links and add a few new links.
=> Add links and apply link encoding in Middleware doc

aspnetcore/security/authentication/certauth.md
See https://github.com/dotnet/aspnetcore/issues/23948
Review link: https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0&branch=tratcher%2Fno-renegotiate
=> Explain why not to use renegotation

aspnetcore/test/integration-tests.md
Clarification to help with issues like https://stackoverflow.com/questions/61769497/skip-jwt-auth-during-tests-asp-net-core-3-1-web-api
=> Clarify that authentication scheme needs to match

aspnetcore/security/authentication/certauth.md
Doc perf fixes for https://github.com/dotnet/aspnetcore/issues/12324
cc @blowdart @Tratcher @JamesNK
=> Add section on cert caching

aspnetcore/blazor/components/index.md
Fixes #19232
Per https://github.com/dotnet/aspnetcore/issues/23955#issuecomment-659542806
=> Blazor imports only apply to .razor files

aspnetcore/blazor/security/index.md
=> Changed "element" to "tag" to match other usages

aspnetcore/test/troubleshoot-azure-iis.md
Fixes #19202
cc @rhamlett
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1&branch=pr-en-us-19238#aspnet-core-module-stdout-log-azure-app-service)
=> update azure debug log

aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Program.cs, aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Client/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/19231#discussion_r456414705
Thanks @serpent5! 🐢
=> Patch Blazor samples

aspnetcore/blazor/components/index.md
Fixes #19249
Thanks @codertimu! :rocket:
=> Fix example

aspnetcore/blazor/security/webassembly/index.md
Fixes #18181
Thanks @aherrick! :rocket: Sorry for the delay. I've been backed up for a bit. I'm digging out now ⛏️⛰️😅.
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?view=aspnetcore-3.1&branch=pr-en-us-19162#require-authorization-for-the-entire-app)
> Apply the \[`[Authorize]` attribute](xref:blazor/security/index#authorize-attribute) (\[API documentation](xref:System.Web.Mvc.AuthorizeAttribute)) to each Razor component in the `Pages` folder of the app.
:+1: **_Works!_** :+1:
Add to `_Imports.razor` file ...
```razor
...
@using Microsoft.AspNetCore.Authorization
@attribute [Authorize]
```
:+1: **_Works!_** :+1:
```csharp
using Microsoft.AspNetCore.Authorization;
... …
```
=> Secure the entire Blazor WASM app

aspnetcore/security/authentication/certauth.md
This feature was added in preview 7, not preview 4.
https://github.com/dotnet/aspnetcore/pull/21484
=> Fix cert auth preview version

aspnetcore/mvc/controllers/filters.md, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Controllers/Test2Controller.cs, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Controllers/Test3Controller.cs, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Controllers/TestController.cs, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/FiltersSample.csproj, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Helper/MyDebug.cs
=> Filters explain debug code

aspnetcore/blazor/components/data-binding.md
Fixes #19268
Thanks @pstricks-fans! :rocket:
=> Blazor component param binding naming

aspnetcore/migration/31-to-50.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19285
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-1.0&branch=pr-en-us-19288&tabs=visual-studio)
=> Update 3.1-to-5.0 migration guide for Preview 7

aspnetcore/blazor/debug.md
Fixes #19291
Thanks @rollandjb! :rocket:
=> Drop VSC installer line

aspnetcore/web-api/handle-errors.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19281
=> Add verbiage about magic number 10

aspnetcore/client-side/bundling-and-minification.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19283
=> Document required NuGet package for bundling MSBuild target

aspnetcore/fundamentals/routing/samples/3.x/RoutingSample/StartupRegex2.cs
=> Fix Routing sample code for regex-constrained route template

aspnetcore/includes/blazor-security/blazor-shared-state.md
=> Un-transposed words

aspnetcore/grpc/client.md
Add detail to gRPC client docs about TLS
Preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.0&branch=pr-en-us-19329
=> gRPC client TLS

aspnetcore/blazor/debug.md
Fixes #19312
Thanks @lonpalmer! :rocket:
=> Clarify VSC debug Blazor WASM guidance

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19303
=> Update link to Web SDK README file

aspnetcore/tutorials/build-a-blazor-app.md
Fixes #19363
Thanks @KettuJKL! :rocket:
=> Add prereqs to Blazor todo list tutorial

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #19302
Thanks @HillPhelmuth! :rocket:
=> Clarify Blazor Brotli JS decoder guidance

aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md
=> Fix up link, use xrefs, and format tables

aspnetcore/tutorials/first-web-api.md
=> Emphasize NuGet requirements and use xrefs

aspnetcore/includes/RP/code/StartupDevProd.cs
[EDIT by guardrex to update the 'fixes' line]
Fixes #19305 #17986
But https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/includes/RP/code/Models/Movie.cs is still `Movie`, I didn't change it. If you think it needs more updates, close this PR then.
=> MovieContext -> RazorPagesMovieContext

aspnetcore/tutorials/build-a-blazor-app.md
Fixes #19379
Thanks @DarkChocoholicDev! :rocket:
=> Remove DI remark in Blazor tutorial

aspnetcore/mvc/controllers/routing.md
=> Fix up typo and a little xref encoding

aspnetcore/fundamentals/error-handling.md
=> Note required order for UseStatusCodePagesWithReExecute

aspnetcore/blazor/components/lifecycle.md
Fixes #19396
I'm going to move this section down so that it's immediately above the the *Cancelable background work* section, too.
Thanks @JvanderStad! :rocket:
=> Razor component disposal

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #19370
Thanks @wilsoncg! :rocket: ... I've floated a PR to Steve on those package versions in his repo. I haven't used GH pages since the original content was put up; and as you said, that was several years ago. Do you think anything else needs to be called out here?
=> Update Blazor GitHub pages external example

aspnetcore/blazor/templates.md
Fixes #19411
Thanks @DarkChocoholicDev! :rocket:
=> Update Blazor templates content

aspnetcore/blazor/templates.md
Fixes #19414
Thanks again @DarkChocoholicDev! :rocket:
=> Blazor templates content updates

aspnetcore/fundamentals/configuration/index.md
It got accidentally moved in PR #19373.
=> Move fcp name tag to the correct location

aspnetcore/blazor/debug.md
Fixes #19440
Is this just for the Blazor WASM debug topic? It's a little hard to tell from the issue how far this should be taken.
Also, you said "on VS" ... is it only VS? ... or VS and VSC (as the current update on this PR goes)?
=> Blazor WASM debug note

aspnetcore/toc.yml
Link to a new event counters doc based on an ASP.NET Core sample project.
=> Add ToC link to event counters doc

aspnetcore/blazor/hosting-models.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
Fixes #19470
Thanks @peereflits ... Thanks for calling this out. I cross-linked the Hosting Model topic in the WASM security topics, and I added a little more text there to make the distinction clearer.
=> Fix typo and enhance definition of standalone vs. hosted WASM apps

aspnetcore/blazor/call-dotnet-from-javascript.md
=> Improve Blazor call instance method guidance

aspnetcore/blazor/fundamentals/additional-scenarios.md, aspnetcore/fundamentals/static-files.md
Fixes #19340
Per engineering remarks :point_right: https://github.com/dotnet/aspnetcore/issues/9588#issuecomment-505465169
Thanks @Paul-Dempsey! 🎸 ... Do you want to review this to confirm that it would have surfaced the guidance for you?
=> File content type provider in Blazor Server

aspnetcore/blazor/call-dotnet-from-javascript.md
Fixes #19318
Thanks @AlbertoPa! 🌴
=> Blazor JS interop: Params for C# methods

aspnetcore/blazor/call-dotnet-from-javascript.md
Fixes  #18705
Thanks @glacasa! 🚀
=> Blazor instance method helper class guidance

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md, aspnetcore/includes/blazor-security/msal-login-mode.md
=> Blazor WASM security MSAL login mode

aspnetcore/docfx.json
Depends on https://github.com/MicrosoftDocs/DocsRoot/pull/696 getting merged first
=> Re-add L2 header

aspnetcore/blazor/debug.md
Fixes #19476
Draft wording for sure ... we might need to play with it a bit on review.
=> Clarify perf implication in WASM debug note

aspnetcore/blazor/host-and-deploy/server.md
Fixes #19504
Fixes #16615
Thanks @marin-bratanov! 🎸
Thanks @miaoxue! 🎷
=> Fix Blazor network latency example code

aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #19051
I'll leave the cross-link in a section to hopefully make it more discoverable.
cc: @JeremyLikness
=> Drop EF Core from Blazor DI topic

aspnetcore/tutorials/first-web-api.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&branch=pr-en-us-19500&tabs=visual-studio)
Fixes #16901 , #16997 
- Added URI examples in Postman tests plus link to verb attributes.
- Fixed dotnet-aspnet-codegenerator commands.
=> Updated: Added URI examples in Postman tests.

aspnetcore/blazor/debug.md
=> Blazor WASM debug VS timeout configuration

aspnetcore/mvc/advanced/app-parts/3.0sample1/MySharedApp/MySharedApp.csproj, aspnetcore/mvc/advanced/app-parts/3.0sample1/WebAppParts/Startup.cs, aspnetcore/mvc/advanced/app-parts/3.0sample1/WebAppParts/WebAppParts.csproj
Fixes #18487
Here is a fix for using views from another RCL in WebAppParts
=> fix using view in WebAppParts

aspnetcore/blazor/host-and-deploy/webassembly.md
=> Add Blazor enable compression property

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
Fixes #19526
Thanks @StevenTCramer! :rocket:
=> Blazor package references and links

aspnetcore/blazor/blazor-server-ef-core.md, aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Data/DbContextFactory.cs, aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/EditContact.razor, aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/Index.razor, aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Startup.cs, aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/EditContact.razor, aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/Index.razor, aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Startup.cs
=> Blazor EF Core topic updates

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
Fixes #19539
Thanks @StevenTCramer! :rocket:
=> Blazor WASM guidance clarification

aspnetcore/blazor/debug.md
Fixes #19518
Thanks @groogiam! :rocket:
=> Clarify Blazor WASM debug remark

aspnetcore/grpc/client.md
Fixes https://github.com/grpc/grpc-dotnet/issues/1021
=> Gracefully end bi-directional gRPC calls

aspnetcore/toc.yml
=> Add XSS acronym to ToC entry

aspnetcore/data/ef-mvc/crud.md, aspnetcore/fundamentals/app-state.md, aspnetcore/includes/mvc-intro/controller-methods-views.md, aspnetcore/release-notes/aspnetcore-2.0.md, aspnetcore/security/index.md, aspnetcore/toc.yml, aspnetcore/tutorials/first-mvc-app/controller-methods-views.md
=> Refer to XSRF/CSRF instead of anti-request forgeries

aspnetcore/data/ef-rp/intro.md, aspnetcore/data/ef-rp/intro/samples/cu30/Program.cs
=> Class Name Renaming #19513

aspnetcore/mvc/models/model-binding.md
Fixes #19567
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1&branch=pr-en-us-19568#attributes-for-complex-type-targets)
Changed from  ***NOTE*** to ***WARNING***
=> clarify BIND on input formatters

aspnetcore/security/authentication/azure-ad-b2c.md
Fixes #19520
Thanks @anuraj! :rocket: ... Cam will confirm that this is the correct cross-link when he reviews this.
=> Link to new Azure tutorial

aspnetcore/performance/caching/distributed.md
=> redis cache

aspnetcore/blazor/components/lifecycle.md
Fixes #19597
Thanks @pstricks-fans! :rocket:
=> Clarify Blazor ParameterView remark

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
Where did my descriptions go??????!
🤔 
I know ...... I figured it out ........ 👽 ..... gotta be. *They are among us!*
=> MIA Blazor WASM security topic descriptions

aspnetcore/blazor/blazor-server-ef-core.md
Fixes #19607
Thanks @mrlife! 🌴
=> Surface "Wrapper" in Blazor EF Core topic

aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Blazor lazy loading renamed assemblies

aspnetcore/blazor/components/index.md, aspnetcore/blazor/fundamentals/routing.md
Fixes #19632
Based on:
* https://github.com/dotnet/aspnetcore/issues/25199#issuecomment-679321134
* https://github.com/dotnet/aspnetcore/pull/24038#issuecomment-660154330
=> Blazor catch-all parameters

aspnetcore/grpc/performance.md, aspnetcore/toc.yml
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.0&branch=pr-en-us-19624
Collection of best practices for good performance with gRPC.
=> gRPC performance best practices

aspnetcore/tutorials/first-web-api.md
=> dotnet-aspnet-codegenerator command

aspnetcore/security/authentication/cookie.md
=> use JavaScript to sign out when browser is closed

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md
=> Move Blazor section for greater visibility

aspnetcore/security/authentication/accconfirm.md
@mkArtakMSFT  is this change OK or should I merge this into the RC1 branch which won't be published until RC1 is on https://dotnet.microsoft.com/download/dotnet/5.0 ?
=> 5.0 updates to resend email confirmation

aspnetcore/includes/net-core-prereqs-vs-5.0.md, aspnetcore/migration/31-to-50.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19661
=> Update 3.1-to-5.0 migration guide for Preview 8

aspnetcore/security/authentication/cookie.md
=> update tab closing/cookie delete

aspnetcore/grpc/interprocess.md, aspnetcore/toc.yml
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-5.0&branch=pr-en-us-19626
Note: Uses features new in .NET 5 RC1. Don't merge until RC1 is released.
=> gRPC and inter-process communication

aspnetcore/grpc/basics.md, aspnetcore/grpc/protobuf.md, aspnetcore/grpc/versioning.md, aspnetcore/toc.yml
Fixes https://github.com/grpc/grpc-dotnet/issues/1020
Preview - https://review.docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-3.0&branch=pr-en-us-19623
gRPC users are often asking questions about defining Protobuf types. This page summarizes the content from https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protocol-buffers
=> Add Protobuf guide for .NET

aspnetcore/grpc/performance.md
Add more sections to gRPC perf page
=> Add load balancing and IPC to gRPC performance

aspnetcore/fundamentals/owin.md
=> remove nowin code

aspnetcore/fundamentals/dependency-injection.md
=> Remove point re injecting transients into singletons/scopeds

aspnetcore/blazor/host-and-deploy/server.md
Fixes #19649
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1&branch=pr-en-us-19663#azure-signalr-service)
=> Blazor with WebSockets on Azure guidance

aspnetcore/grpc/browser.md, aspnetcore/grpc/httpapi.md, aspnetcore/toc.yml
Discuss gRPC HTTP API project.
=> Add Create JSON Web APIs from gRPC doc

aspnetcore/blazor/call-dotnet-from-javascript.md
Fixes #19709
Thanks @swijnands! :rocket:
=> Fix Blazor code example

aspnetcore/blazor/call-dotnet-from-javascript.md
Fixes #19712
Thanks again @swijnands! :rocket:
=> Remove attribute identifier

aspnetcore/fundamentals/dependency-injection.md
=> Fix up recommendation re scope validation

aspnetcore/blazor/call-dotnet-from-javascript.md
Fixes #19732
Thanks @mrlife! 🎷 
It was better **_BEFORE_** I touched it this weekend. 🙈
I'll work on this topic further when I have more time, which will be after .NET 5 releases. The holiday period between Thanksgiving 🦃 and mid-December looks good for a major update with improved organization and with better and more examples.
=> Update Blazor Call .NET from JS + fix a regression

aspnetcore/blazor/forms-validation.md
Fixes #19685
Thanks @Assassinbeast! :rocket:
=> Blazor code example update

aspnetcore/blazor/hosting-models.md
Fixes #19728
We already have coverage in the last section, so how about we place this strategic IMPORTANT remark with **bold** text in the initial Blazor Server remarks?
=> Enhance Blazor Server sticky sessions requirement

aspnetcore/blazor/components/data-binding.md
Address #19721
We'll temporarily drop the content until the product unit comments on the scenario at https://github.com/dotnet/aspnetcore/discussions/25490. A follow-up PR will fix the issue.
cc: @CincySteve
=> Temporarily drop Blazor content

aspnetcore/tutorials/first-mvc-app/details.md
Fixes #19705.
cc @Rick-Anderson.
=> Fix link to Azure App Service tutorial

aspnetcore/grpc/performance.md
=> Link to gRPC client factory from performance doc

aspnetcore/grpc/browser.md
Fixes https://github.com/grpc/grpc-dotnet/issues/749
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-19754#use-grpc-client-factory-with-grpc-web
=> Add client factory section to gRPC-Web doc

aspnetcore/client-side/bundling-and-minification.md
fixes https://github.com/dotnet/AspNetCore.Docs/issues/19729
=> Note about BuildBundlerMinifier Nuget package required

aspnetcore/blazor/fundamentals/routing.md
Fixes #19664
Thanks @kdubau! :rocket:
=> Blazor routing fallbacks for dots in params

aspnetcore/blazor/hosting-models.md
Fixes #19784
Thanks @em-jones! :rocket:
=> Clarify ambiguous Blazor Server language

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Manually register LazyAssemblyLoader

aspnetcore/blazor/blazor-server-ef-core.md
=> Fix typo ("contact" should be "context")

aspnetcore/fundamentals/localization/sample/3.x/Localization/Startup.cs
=> Fix localization sample

aspnetcore/tutorials/first-web-api.md
=> Add "Models" to no-loc for First Web API

aspnetcore/migration/31-to-50.md
[EDIT by guardrex to add Dan's Blazor issue]
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19852
Fixes #19780
[Internal review page](https://review.docs.microsoft.com/aspnet/core/migration/31-to-50?branch=pr-en-us-19853)
=> Update 5.0 migration guide for RC1 release

aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Blazor RC1 updates

aspnetcore/grpc/client.md, aspnetcore/grpc/deadlines-cancellation.md, aspnetcore/grpc/deadlines-cancellation/cancellation-client.cs, aspnetcore/grpc/deadlines-cancellation/clientfactory-propagate.cs, aspnetcore/grpc/deadlines-cancellation/deadline-client.cs, aspnetcore/grpc/deadlines-cancellation/deadline-propagate.cs, aspnetcore/grpc/deadlines-cancellation/deadline-server.cs, aspnetcore/toc.yml
Fixes https://github.com/grpc/grpc-dotnet/issues/535
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/deadlines-cancellation?view=aspnetcore-3.0&branch=pr-en-us-19787
=> Add gRPC deadlines and cancellation

aspnetcore/fundamentals/logging/index.md, aspnetcore/fundamentals/logging/index/samples/3.x/LoggingConsoleApp/Program.cs
=> Small improvements to logging docs

aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/BlazorServerDbContextExample.csproj
Fixes #19883
Thanks @justSteve! :rocket: ... I had a few minutes here to knock it out as a I wrap up prior *to getting blown away by a hurricane!* 😨 ... *Yes!* ... Sally is trying to **_GET ME!_** 😨
=> Update Blazor-EF Core sample to .NET 5 RC1

aspnetcore/data/ef-rp/intro.md
Add monikers for a productive review on changes.
=> 5.0 monikkers for EF/RP

aspnetcore/blazor/host-and-deploy/configure-trimmer.md
=> Make the trimming options link be more prominent.

aspnetcore/blazor/components/class-libraries.md
=> Blazor WASM browser compatibility analyzer

aspnetcore/blazor/call-javascript-from-dotnet.md, aspnetcore/blazor/components/class-libraries.md
=> Blazor JavaScript isolation

aspnetcore/blazor/components/event-handling.md
=> Blazor support for ontoggle event

aspnetcore/blazor/forms-validation.md
=> Blazor custom validation class attributes

aspnetcore/blazor/components/lifecycle.md
Fixes #19948
Thanks @wbuck! :rocket:
=> Enhance Blazor OnAfterRender[Async] content

aspnetcore/blazor/components/virtualization.md
=> Blazor virtualization state changes

aspnetcore/azure/devops/deploying-to-app-service.md
=> added azurecli devx-track tag to ms.custom

aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/ConsumeScopedServiceHostedService.cs
=> Fix up ConsumeScopedServiceHostedService.StopAsync impl to call base

aspnetcore/blazor/components/virtualization.md
=> Convert Blazor Virtualize examples

aspnetcore/signalr/configuration.md
=> Add new SignalR server option

aspnetcore/mvc/models/model-binding.md
=> Add a note about model binding record types

aspnetcore/mvc/views/partial.md
Fixes #19973
Thanks @FredHan001! :rocket:
=> Enhance partial page description

aspnetcore/migration/31-to-50.md
=> Add notes about behavior changes to model binding in 5.0

aspnetcore/blazor/security/server/additional-scenarios.md
The end of code block was not working due to indentation and was causing some unlocalized strings.
=> Fixing end of code block

aspnetcore/fundamentals/static-files.md
=> Fixing bookmark links

aspnetcore/signalr/streaming.md, aspnetcore/signalr/streaming/samples/2.1/Hubs/StreamHub.cs, aspnetcore/signalr/streaming/samples/2.2/Hubs/StreamHub.cs, aspnetcore/signalr/streaming/samples/3.0/Hubs/StreamHub.cs
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/15408
=> Fix streaming wording and example

aspnetcore/signalr/messagepackhubprotocol.md
Addresses feedback in https://github.com/dotnet/AspNetCore.Docs/issues/19937
=> Add some info to MessagePack page

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #19938
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-19978#compression)
Thanks @mrpmorris! 🎸
I opened https://github.com/dotnet/AspNetCore.Docs/issues/19979 to revert this change later.
=> Unminified Google Brotli script (temporary)

aspnetcore/fundamentals/logging/index.md
=> Note absence of built-in file logging provider

aspnetcore/blazor/components/templated-components.md
Fixes #20002
Thanks @chanmmn! :rocket:
=> Cross-link sample app and enhance examples

aspnetcore/mvc/models/model-binding.md
cc: @pranavkm ... It looks like you were going for **>=** 5.0 (to include 5.0) instead of > 5.0. If the change on that here is incorrect, I'm :ear: and will change it back to > 5.0.
=> Fix moniker range + nits

aspnetcore/tutorials/first-mvc-app/new-field.md
[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-3.1&branch=pr-en-us-20019&tabs=visual-studio)
Replaced the sensitive term "white list" with standard term "allow list".  Very minor.
=> Removed sensitive term in new-field.md

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #20020
Thanks @GisliSig! :rocket:
Approved per https://github.com/dotnet/AspNetCore.Docs/issues/20020#issuecomment-700072878.
=> Update lazy loading WASM guidance

aspnetcore/blazor/fundamentals/additional-scenarios.md
Fixes https://github.com/dotnet/aspnetcore/issues/26383.
=> [.NET 5 RC1] Add content on customizing client-side disconnect

aspnetcore/blazor/call-javascript-from-dotnet.md
Fixes https://github.com/dotnet/aspnetcore/issues/24492.
=> Add clarification on invoking Promise-based functions via JS interop

aspnetcore/blazor/blazor-server-ef-core.md
Fixes #19989
Thanks @EddyHaigh! :rocket:
Because we're close to 5.0 GA and I'd like to harden this against having to come back later for another update, I'll go ahead and write the line in the present tense (i.e., "available in" 5.0 instead of "will be available in").
=> IDbContextFactory in 3.x sample app

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #20040
Thanks @emmerel37! :rocket:
=> Update Blazor lazy loading guidance

aspnetcore/fundamentals/localization.md
=> Fix Localization external link

aspnetcore/security/authentication/mfa.md
fixes https://github.com/dotnet/AspNetCore.Docs/issues/20039
=>  Add a link to the src at the top MFA doc

aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Details.cshtml, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Details.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/appsettings.json
=> Fix App settings

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/state-management.md, aspnetcore/includes/blazor-state-management/state-container.md, aspnetcore/tutorials/first-mvc-app/new-field.md
Fixes #17921
Internal Review Topics ...
* [Data Binding topic (links to *Bind across more than two components* section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1&branch=pr-en-us-20047#bind-across-more-than-two-components)
* [State Management topic (links to *In-memory state container service* section)](#in-memory-state-container-service)
Thanks @timcromarty! :rocket: ... sorry for the delay. I've been 🏃😅 on a lot of doc updates over the past several months. Fortunately, I've almost dug myself out thank goodness ⛰️⛏️😄. 
Thanks Steve :pray: for sorting out my nested chained bind problems 😖 ...
* I place the multi-level chained bind content in a new section at the bottom of the Blazor *Data Binding* topic.
* I place the state …
=> Blazor multiple chained bind and state containers

aspnetcore/data/ef-rp/crud.md, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Create.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/CreateVM.cshtml, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/CreateVM.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Delete.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Students/Edit.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/ViewModels/StudentVM.cs
Fixes #20052
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-1.0&branch=pr-en-us-20061)
=> 5.0 update EF/RP part 2

aspnetcore/migration/22-to-30.md, aspnetcore/web-api/advanced/formatting.md
=> Detail effects of AddNewtonsoftJson

aspnetcore/signalr/javascript-client.md
According to [this github issue](https://github.com/dotnet/AspNetCore.Docs/issues/19570), I'd like to submit this troubleshooting guidance for common Signalr WebSocket handshake issues.
=> new topic about troubleshooting

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes #19572
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&branch=pr-en-us-19749#host-in-azure-app-service-with-a-custom-domain)
Thanks @donquijotedelamancha! 🎸
As is often the case here, the options are to:
* Link out for everything possible.
* Make it dead simple to set up and configure.
I opted for the **_dead simple_** coverage. We have new-to-Blazor and new-to-.NET 🐈🐈 coming in for these topics. With the interplay of Azure Apps, Azure Key Vault, Identity Server, Visual Studio, and Blazor, I thought it best to go in this direction.
cc: @blowdart ... Just as an **_FYI only_** that there's security guidance on this one.
=> Blazor WASM IdS custom domain App Service

aspnetcore/whats-new/2020-09.md, aspnetcore/whats-new/index.yml, aspnetcore/whats-new/toc.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19746
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/whats-new/2020-09?view=aspnetcore-1.0&branch=pr-en-us-20072)
=> Add what's new page for September 2020

aspnetcore/blazor/components/data-binding.md
=> Adds missing line of code.

aspnetcore/blazor/components/virtualization.md, aspnetcore/data/ef-rp/sort-filter-page.md
Fixes #20081
Thanks @ShahJe! :rocket:
=> Add Virtualize component example to Blazor doc

aspnetcore/web-api/handle-errors/samples/3.x/Filters/HttpResponseExceptionFilter.cs
=> Remove set from interface impl

aspnetcore/security/authentication/cookie.md
=> Remove reference to old package in 3.0 section

aspnetcore/mvc/controllers/filters.md
=> Fixes filter order

aspnetcore/host-and-deploy/proxy-load-balancer.md
=> Remove reference to the NuGet package

aspnetcore/blazor/supported-platforms.md, aspnetcore/signalr/supported-platforms.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1&branch=pr-en-us-20006)
Recommendations on this PR:
* We have a pointless heading level here ... let's drop it. 🔪
* Alphabetize the tables.
* We call out browsers by manufacturer and name for all but Safari, so let's display that entry as "Apple Safari ..." to match.
=> Blazor Supported Platforms topic UE pass

aspnetcore/fundamentals/host/generic-host.md
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1&branch=pr-en-us-20098)
=> Move 5.0 moniker to the top

aspnetcore/data/ef-mvc/inheritance.md, aspnetcore/tutorials/signalr-blazor-webassembly.md
@Rick-Anderson Monthly FQDN link script run for this repo.
=> Links: AspNetCore (2020-10)

aspnetcore/fundamentals/configuration/index.md, aspnetcore/fundamentals/configuration/options.md, aspnetcore/fundamentals/dependency-injection.md, aspnetcore/fundamentals/host/generic-host.md, aspnetcore/fundamentals/logging/index.md
=> Point extensions docs to .NET content

aspnetcore/blazor/tooling.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-3.1&branch=pr-en-us-20026)
**Recommendation on this PR:** For the SDK install in the Linux pivot, let's *please* make that SDK link generic and just point to the downloads page. This hardens the entire topic for future releases (i.e., we won't need to version the topic further than the existing metadata version entry), thus it results in *one less thing* 😅 to break/require updates as we go. :+1:.
Note that links in the topic with a trailing slash avoid a redirect. Links without a trailing slash land at the destination without a redirect. I checked all of them for this PR.
=> Blazor Tooling topic UE pass

aspnetcore/blazor/debug.md
Fixes #20127 
Thanks @AdrianSanguineti! :rocket: ... For some reason, the PR didn't submit against the master branch. No worries ... I put your remarks on this PR.
=> Call out NO_PROXY environment variable

aspnetcore/blazor/components/lifecycle.md
Reverts dotnet/AspNetCore.Docs#20133
=> Revert "Image size update"

aspnetcore/blazor/blazor-server-ef-core.md
Fixes #20150
Thanks @kinetiq! :rocket:
=> Cross-link sample app code

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes https://github.com/dotnet/aspnetcore/issues/22470
This applies equally to .NET Core 3.x and 5.0+.
=> Add info about integrity checking

aspnetcore/blazor/webassembly-performance-best-practices.md
Implements https://github.com/dotnet/aspnetcore/issues/25356
Note: I have added `xref` and `::: moniker` markers in various places - hope I got that right.
=> Extend docs about Blazor WebAssembly perf

aspnetcore/host-and-deploy/windows-service.md
Without the quotes the command won't work
=> Added quotes around parameters

aspnetcore/blazor/globalization-localization.md
=> Add a note about BlazorWebAssemblyLoadAllGlobalizationData

aspnetcore/grpc/services.md
=> Update services.md -- wrong method name in example code

aspnetcore/blazor/components/lifecycle.md
=> Blazor lifecycle images update

aspnetcore/blazor/components/lifecycle.md
=> Blazor lifecycle topic image update

aspnetcore/migration/31-to-50.md
=> Update ASP.NET Core 3.1-to-5.0 migration guide for RC2

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
Clear up confusion about switching to windows containers. I initially got stuck on this step.
=> add link about switching container types

aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse.md, aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse/sample/AuthorizationMiddlewareResultHandlerSample/MyAuthorizationMiddlewareResultHandler.cs, aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse/sample/AuthorizationMiddlewareResultHandlerSample/Startup.cs, aspnetcore/toc.yml
=> Add a snippet that shows wo to use AuthorizationMiddlewareResultHandler

aspnetcore/security/authentication/windowsauth.md
Add LDAP lookup config examples for RC2
=> Add LDAP lookup config examples

aspnetcore/blazor/globalization-localization.md
=> Add a note about configuring Blazor Wasm culture using JavaScript

aspnetcore/migration/31-to-50.md
Fixes  #20143
Thanks @dajma00! 🌴
I'm not going to address tooling with this update: These migration topics are largely tooling agnostic AFAIK.
=> Clarification in Blazor WASM section

aspnetcore/blazor/fundamentals/additional-scenarios.md
=> Additional Blazor static files config content

aspnetcore/blazor/host-and-deploy/webassembly.md
=> PublishIISAssets must be set to publish custom web.config

aspnetcore/fundamentals/request-features.md
Fixes https://github.com/dotnet/aspnetcore/issues/26249
=> Request feature updates

aspnetcore/web-api/route-to-code.md, aspnetcore/web-api/route-to-code/sample/Program.cs, aspnetcore/web-api/route-to-code/sample/Startup.cs, aspnetcore/web-api/route-to-code/sample/Startup2.cs, aspnetcore/web-api/route-to-code/sample/Startup3.cs, aspnetcore/web-api/route-to-code/sample/WebR2C.csproj, aspnetcore/web-api/route-to-code/sample/appsettings.Development.json, aspnetcore/web-api/route-to-code/sample/appsettings.json
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-5.0&branch=pr-en-us-20276)
=> Add snippets to R2C

aspnetcore/security/key-vault-configuration.md, aspnetcore/web-api/http-repl.md
Bulk addition of azurecli mscustom metadata for @dbradish-microsoft
=> Bulk addition of azurecli mscustom metadata

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
=> Blazor code example enhancements

aspnetcore/fundamentals/servers/kestrel.md
Fix versioning from https://github.com/dotnet/AspNetCore.Docs/pull/20261.
=> Fix versioning

aspnetcore/fundamentals/dependency-injection.md
=> Add more IEnumerable<TService> documentation

aspnetcore/fundamentals/dependency-injection.md
Fixes #19702
@serpent5  please review.
=> add warning about indirectly resolving scoped

aspnetcore/fundamentals/websockets.md, aspnetcore/fundamentals/websockets/samples/2.x/WebSocketsSample/Startup.cs, aspnetcore/fundamentals/websockets/samples/2.x/WebSocketsSample/Startup2.cs
Fixes #19788
[Internal review URL](#19788)
=> add using to sockets sample

aspnetcore/blazor/call-dotnet-from-javascript.md, aspnetcore/blazor/call-javascript-from-dotnet.md, aspnetcore/blazor/index.md, aspnetcore/blazor/webassembly-performance-best-practices.md, aspnetcore/client-side/spa-services.md, aspnetcore/security/anti-request-forgery.md, aspnetcore/signalr/diagnostics.md, aspnetcore/signalr/javascript-client.md, aspnetcore/signalr/streaming.md, aspnetcore/signalr/supported-platforms.md, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/web-api-javascript.md
=> JS Dev Center - bulk metadata change

aspnetcore/security/authorization/dependencyinjection.md
=> Auth handlers - any lifetime

aspnetcore/blazor/file-uploads.md
=> Tweaks to file upload

aspnetcore/host-and-deploy/azure-apps/index.md
=> Self-contained deployments to Azure

aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/signalr/scale.md
Progress on https://github.com/dotnet/AspNetCore.Docs/issues/10827
=> Improve SignalR Nginx settings

aspnetcore/tutorials/grpc/grpc-start.md
Updated document date
Changed "click" to "select" as better wording for accessibility (from team review)
=> Update document date

aspnetcore/signalr/hubcontext.md, aspnetcore/signalr/hubs/sample/Hubs/ChatHub.cs, aspnetcore/signalr/hubs/sample/Hubs/IChatClient.cs, aspnetcore/signalr/hubs/sample/Hubs/StronglyTypedChatHub.cs
Closes https://github.com/dotnet/AspNetCore.Docs/issues/15238
@Rick-Anderson  edit
Fixes #15238
=> Fix Strongly type hubs docs

aspnetcore/blazor/state-management.md
Fixes #20350
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&branch=pr-en-us-20351&view=aspnetcore-5.0&pivots=server#aspnet-core-protected-browser-storage)
=> Update protected browser storage for 5.0

aspnetcore/fundamentals/environments.md
Fixed a typo within a sentence.
=> Fixed Typo in environments.md

aspnetcore/signalr/streaming.md
https://github.com/dotnet/AspNetCore.Docs/issues/14308
=> Add client->server streaming in Java

aspnetcore/security/authentication/social/additional-claims.md
Updated [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.1)
see [source](https://github.com/dotnet/aspnetcore/blob/e3fd7471db53a559e37ba03dd76408053a80535e/src/Security/Authentication/Google/src/GoogleOptions.cs#L24) for reference
=> At authentication/social/additional-claims fixes google scope

aspnetcore/fundamentals/host/generic-host.md
=> Cross-link sections in Generic Host topic

aspnetcore/security/data-protection/configuration/overview.md
Update Microsoft.AspNetCore.DataProtection.AzureStorage and Microsoft.AspNetCore.DataProtection.AzureKeyVault sdk to track2 in secure-data_protection-configuration-overview.md.
=> Updates overview.md

aspnetcore/host-and-deploy/iis/hosting-bundle.md
Helping people with https://github.com/dotnet/aspnetcore/issues/24512 a bit more. Still need to try to do some installer work here as well.
=> Add documentation for VS C++ Redist

aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md, aspnetcore/migration/31-to-50.md
Fixes #20400
... includes further work on introductory remarks in the WASM security topics.
=> Migration for standalone Blazor WASM security 

aspnetcore/blazor/debug.md
Fixes #20411
Not sure about the language ... u might need to suggest alternate text.
* Is there a specific port that we can say to open?
* Are there one or several ports?
=> Cover Blazor debug with firewall config

aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config
Fixes #20405
@cornem, would you like to review this one?
@robertmclaws ... Open a new issue from the bottom of [the topic](https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly) if you discover what the problem is with your app/file and still feel that we need a doc update to cover it. If this PR doesn't address it, your situation might become actionable after we know what the cause of the problem is. Let's treat it as a separate (new) issue if that turns out to be the case.
=> Improve Blazor standalone web.config file remarks

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Migrations/20201109212940_Rating.Designer.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Migrations/20201109212940_Rating.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Views/Movies/Index.cshtml
* 5.0 update of intro to MVC
* 5.0 update of intro to MVC
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* work
* update files
=> merge to live 2

aspnetcore/blazor/security/server/threat-mitigation.md
Fixes #20417
Thanks @jraadt! :rocket:
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-3.1&branch=pr-en-us-20454#client-connections)
btw- They have it up as a UserVoice at :point_right: https://feedback.azure.com/forums/217313-networking/suggestions/37346371-support-websocket-connections-on-azure-front-door
=> Blazor Azure Front Door clarification

aspnetcore/host-and-deploy/app-offline.md
I'm not really sure, but the described PowerShell commands didn't work as expected.
The first line would result in:
```
C:\Users\muehsig> New-Item -Path c:\temp app_offline.htm
New-Item : A positional parameter cannot be found that accepts argument 'app_offline.htm'.
At line:1 char:1
+ New-Item -Path c:\temp app_offline.htm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindingException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.NewItemCommand
```
The `Remove-Item` would result in this:
```
:\Users\muehsig> Remove-Item -Path \\d331\oostage\361\HealthMonitor app_offline.htm
Remove-Item : A positional parameter cannot be found that accepts argument 'app_offline.htm'.
At line:1 char:1
+ …
```
=> Fix powershell errors

aspnetcore/includes/blazor-security/troubleshoot.md, aspnetcore/migration/31-to-50.md
Fixes #20447
Thanks @mattruma! 🎷 You probably saved many devs for this migration. *The 🙏 server gods 🙏 will smile on u for this!* :+1:
I decided to leave additional cross-links to the hosted scenarios off of this PR. I'll take additional reader feedback over the next days and weeks to see if that will be necessary.
=> Cover a Blazor security migration scenario

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/data/ef-mvc/intro.md, aspnetcore/includes/add-EF-NuGet-SQLite-CLI-5.md, aspnetcore/migration/31-to-50.md
=> Update from RC2 to RTM

aspnetcore/security/authentication/index.md, aspnetcore/security/authorization/limitingidentitybyscheme.md
=> multiple authentication schemes

aspnetcore/blazor/components/data-binding.md
Fixes #20479
Thanks @gregoryagu! :rocket: ... Would you like to review this before I merge it?
=> Change naming in Blazor binding example 

aspnetcore/migration/31-to-50.md
=> Add RCL migration to 5.0 migration topic

aspnetcore/blazor/debug.md
=> Blazor WASM debugging only for local scenarios

aspnetcore/migration/31-to-50.md
Per https://github.com/dotnet/aspnetcore/issues/27738#issuecomment-725645942
=> Strategic NOTEs for hosted Blazor migrations

aspnetcore/tutorials/first-web-api.md
=> update MacOS WebAPI tutorial

aspnetcore/blazor/state-management.md
Fixes #20529
Thanks @dsychin! :rocket:
=> Refactor section headings for stable bookmarks

aspnetcore/blazor/security/content-security-policy.md
=> Update Blazor Content Security Policy doc for 5.0

aspnetcore/blazor/components/css-isolation.md
Nit update following https://github.com/dotnet/AspNetCore.Docs/pull/20539 ... I'm going a wee bit too 🏃🏃🏃🏃🏃🏃🏃🏃 this AM.
=> Update Blazor CSS isolation-RCL support section

aspnetcore/blazor/call-dotnet-from-javascript.md, aspnetcore/blazor/call-javascript-from-dotnet.md
Fixes #20461
Thanks @GeorgeS2019! :rocket:
=> Blazor JS module support 

aspnetcore/tutorials/build-a-blazor-app.md
Addresses #20499
@gregoryagu ... In the ancient days of docs (a few years ago 👴), this didn't have an effect that produced a rendered file name cue. However, this will be a little test to see if that has changed since then. I'll take this live immediately, and we'll see what renders. I'll revert it after the test.
I'll place a screenshot of the result on #20499 shortly.
=> Test if alt text renders file name cue

aspnetcore/blazor/security/index.md
Fixes #20462 
Thanks @shanemikel! :rocket: ... sorry it took so long to reach the answer on this one.
=> AuthorizeView authorized event handlers

aspnetcore/blazor/host-and-deploy/server.md
Fixes  #20491
Thanks @gregoryagu! :rocket:
=> Azure SignalR Service and sticky session config

aspnetcore/blazor/fundamentals/additional-scenarios.md, aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md
=> Update Blazor Render mode coverage

aspnetcore/blazor/security/webassembly/graph-api.md
Fixes #20572
Thanks @taylorchasewhite! :rocket:
=> Fix code example

aspnetcore/blazor/components/index.md
Fixes #20565
Thanks @mrlife! 🎷 ... This is an excellent addition.
=> Surface C# assignment to component params

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/fundamentals/additional-scenarios.md
Fixes #20441
Thanks @akovac35! :rocket:
=> Blazor reconnection and component lifecycle events

aspnetcore/tutorials/signalr-blazor-webassembly.md
Fixes #20581
Thanks @NibblyPig! :rocket:
=> Change title of SignalR-Blazor tutorial

aspnetcore/migration/31-to-50.md
Fixes  #20587
Thanks @smjltd! ⛄
=> Add Blazor WASM migration steps

aspnetcore/blazor/common/samples/5.x/BlazorServerSample/Pages/RouteParameter.razor, aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/Pages/RouteParameter.razor, aspnetcore/blazor/fundamentals/routing.md
Fixes #20591
Thanks @gregoryagu! 🎸 ... that one slipped under the radar.
=> Blazor optional params support in 5.0

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Migrations/20190805165915_InitialCreate.Designer.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Migrations/20190805165915_InitialCreate.cs
Small Typo Fix
Matches the code to the tutorial at `~aspnetcore/tutorials/first-mvc-app/adding-model.md`
Tutorial expects class to be named `InitialCreate`
=> Update Migrations class to match documentation

aspnetcore/razor-pages/index/3.0sample/RazorPagesContacts/Pages/Customers/Index.cshtml
=> Missing th element in thead

aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor
Fixes #20613
Thanks @moonolgerd! :rocket:
=> Fix Blazor Uploads code sample

aspnetcore/data/ef-mvc/migrations.md
Fixes  #20568
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-5.0&branch=pr-en-us-20569)
=> Address click through rate

aspnetcore/security/samesite.md
Fixes #20608
Update moniker on section "Supporting older browsers" to work with .NET Core 5+
=> Fix moniker on samesite.md

aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor
Fixes #20618
Thanks @DataJuggler! :rocket:
=> Add namespace to Blazor File Uploads sample

aspnetcore/migration/31-to-50.md
Fixes #20627
Thanks @jskop! :rocket: ... It required more work. I was overly focused on WASM this release and found out that the stylesheet changes extended into Blazor Server. Thanks for writing in.
=> Update Blazor migration guidance

aspnetcore/migration/31-to-50.md
Fixes #20618
Thanks @DataJuggler! ⛄
=> Show Blazor namespaces

aspnetcore/blazor/templates.md
=> Add new stylesheet files to Blazor Templates

aspnetcore/blazor/fundamentals/routing.md
Fixes #20602
Thanks @gregoryagu! :rocket:
=> Use OnParametersSet instead of OnIntialized

aspnetcore/data/ef-mvc/intro.md
=> typos in ef-mvc intro tutorial

aspnetcore/tutorials/first-web-api.md
* Fix typo in package name `Dotnet-aspnet-codegenerator`
* Use `-g` instead of `--global` to be consistent with `update` command
=> Make install and update command more consistent

aspnetcore/tutorials/first-mvc-app/new-field.md, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Views/Movies/IndexGenreRating.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Views/Movies/Index.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5/Views/Movies/IndexGenreRating.cshtml
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-5.0&branch=pr-en-us-20646&tabs=visual-studio#add-a-rating-property-to-the-movie-model)
Fixes #20586 
On section "Add a Rating Property to the Movie Model" of new-field.md:
The version 3.x and 5 app samples needed their own IndexGenreRating.cshtml example:  The 5.0 version was pointing to Index.cshtml which is also used for an example before the rating property is is added.  The 3.x version was pointing to v2.2
=> First-mvc: Fix new-field.md cshtml examples

aspnetcore/migration/31-to-50.md
Fixes  #20659
Thanks @qwertie! :rocket: ... Let's give this a shot. The updates include ...
* Cross-link the sections to make it clear that upgrade guidance is in more than one section.
* Add a *Clean and rebuild* section. Include info on nuking the package cache in case that causes anyone grief.
* Add a *Troubleshoot* section that reminds readers to hit up the individual *Troubleshoot* section of the topic that applies to their app.
=> Enhance Blazor migration guidance

aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md
Fixes #20623
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-2.1&branch=pr-en-us-20647#uninstall-aspnet-codegenerator)
=> uninstall scaffolding engine

aspnetcore/mvc/models/model-binding.md
=> Expand CancellationToken notes

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/index.md
Fixes #20675
Thanks @vborovikov! :rocket:
=> Surface Blazor complex parameter support

aspnetcore/release-notes/aspnetcore-5.0.md
Fixes #20686
Thanks @xiety! :rocket:
=> Fix link destination

aspnetcore/blazor/fundamentals/routing.md
Changed "the app to use **other** controllers and pages without..." to "the app to use **other** controllers and pages without...".
=> Fixed a typo in routing.md

aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
Will be reverted on next week's (planned 🤞) PR to update the topic for 5.0. I have a working prototype, and we're working out the final details for the updated approaches.
=> NOTE for Blazor AAD groups+roles update to 5.0

aspnetcore/security/key-vault-configuration.md, aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/Program.cs, aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/SampleApp.csproj, aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/appsettings.json, aspnetcore/security/key-vault-configuration/samples_snapshot/Startup.cs
Updated : key-vault-configuration.md, key-vault-configuration\samples\3.x\SampleApp\SampleApp
1. `Microsoft.Extensions.Configuration.AzureKeyVault` to `Azure.Extensions.AspNetCore.Configuration.Secrets`.
2. `KeyVaultClient ` to `SecretClient`.
There is no new API reference Documentation about AddAzureKeyVault(), so its link is not added in this PR.
@pakrym, @jongio please help review
=> Updated KeyVaultConfiguration

aspnetcore/security/key-vault-configuration.md
=> Fix bad xref

aspnetcore/razor-pages/index.md
=> 5.0 update RP - adv

aspnetcore/blazor/webassembly-performance-best-practices.md
=> Fixed Typo in Blazor WebAssembly performance best practices docs

aspnetcore/tutorials/first-web-api.md
=> Demo URL format error

aspnetcore/release-notes/aspnetcore-5.0.md
Fixed a reference to Active Directory that says "Activity Directory."
=> Activity Directory -> Active Directory

aspnetcore/grpc/httpapi.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20730
=> Fix grpc-gateway docs link

aspnetcore/fundamentals/configuration/index.md
The documentation doesn't currently explain how to handle more complex structures, such as arrays.  This change adds an explanation and example.
=> Add info on arrays with AddEnvironmentVariables

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Addresses #20696
Thanks @ChristianWeyer ... I'll leave this as a DRAFT for now. We'll start with this and then see if it requires more work. Your issue will remain open until it's fully resolved.
=> Update Blazor prerender with auth for 5.0

aspnetcore/blazor/security/webassembly/additional-scenarios.md
=> Additional Blazor prerendering text updates

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
=> Update VS NOTEs for Blazor WASM AAD topics

aspnetcore/migration/31-to-50.md
Fixes #20684
Thanks @josekpaul! :rocket:
=> PWA: Service worker registration 5.0

aspnetcore/blazor/forms-validation.md
=> CompareAttribute works now

aspnetcore/tutorials/first-web-api.md
=> Fix "copy and past" typo

aspnetcore/blazor/blazor-server-ef-core.md
Fixes #20801
Thanks @DarkMonkDev! :rocket:
=> Fix Blazor-EF Core topic code example

aspnetcore/migration/31-to-50.md
=> Blazor client-side routing migration

aspnetcore/blazor/forms-validation.md
=> Update Blazor forms event binding example

aspnetcore/security/docker-https.md
Adding some notes around using the sample ASP.NET app with certificates.
@RickAndMSFT Let me know what you think.
=> testing with openssl certificates with sample app

aspnetcore/toc.yml, aspnetcore/web-api/route-to-code.md, aspnetcore/web-api/route-to-code/sample/Program.cs, aspnetcore/web-api/route-to-code/sample/Startup.cs, aspnetcore/web-api/route-to-code/sample/Startup2.cs, aspnetcore/web-api/route-to-code/sample/Startup3.cs, aspnetcore/web-api/route-to-code/sample/Startup4.cs, aspnetcore/web-api/route-to-code/sample/Startup5.cs, aspnetcore/web-api/route-to-code/sample/Startup6.cs, aspnetcore/web-api/route-to-code/sample/UserApi.cs, aspnetcore/web-api/route-to-code/sample/WebR2C.csproj, aspnetcore/web-api/route-to-code/sample/appsettings.Development.json, aspnetcore/web-api/route-to-code/sample/appsettings.json
Fixes https://github.com/dotnet/aspnetcore/issues/26250
Preview: https://review.docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-5.0&branch=pr-en-us-20259
***EDIT*** by @Rick-Anderson ~work moved to #20276~
=> Add doc for new ASP.NET Core JSON extension methods

aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/model.md, aspnetcore/tutorials/razor-pages/new-field.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/razor-pages/search.md, aspnetcore/tutorials/razor-pages/sql.md, aspnetcore/tutorials/razor-pages/validation.md
=> remove Create and Delete from no:loc

aspnetcore/tutorials/signalr-blazor-webassembly.md, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Client/Program.cs, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Client/wwwroot/index.html, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Server/Program.cs, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Server/Startup.cs, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Server/appsettings.json
Fixes #20752
Doc sample updates were put in during 5.0 preview (and the sample ran at that time), but this PR applies final updates based on the GA 5.0 project template.
Thanks @pmready! 🚀
=> Blazor SignalR tutorial sample update for 5.0

aspnetcore/fundamentals/middleware/index.md, aspnetcore/fundamentals/middleware/index/snapshot/StartupAll3.cs, aspnetcore/performance/response-compression.md
=> app.UseResponseCompression(); to middleware ordering

aspnetcore/migration/31-to-50.md
=> Hold PreferExactMatches from migration content

aspnetcore/migration/31-to-50.md
Fixes #20831
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-1.0&branch=pr-en-us-20833&tabs=visual-studio#usedatabaseerrorpage-obsolete)
=> doc Auth template changes

aspnetcore/web-api/route-to-code.md
=> Update route-to-code doc with API links

aspnetcore/host-and-deploy/index.md
=> how to pub xml files

aspnetcore/fundamentals/middleware/index.md
=> Fix snapshot code and line highlights

aspnetcore/blazor/components/index.md
=> Mention that Blazor component parameters are optional and can have a default value

aspnetcore/blazor/layouts.md
Amended the text on how to convert a component to layout for improved readability.
=> Update to layouts documentation

aspnetcore/blazor/state-management.md
=> Add NOTE for Blazor Protected Browser Storage

aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/host-and-deploy/webassembly/_samples/integrity.ps1, aspnetcore/blazor/progressive-web-app.md
Fixes #20852
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-20861#troubleshoot-integrity-powershell-script)
=> Troubleshoot integrity PowerShell script

aspnetcore/blazor/fundamentals/routing.md
=> Updates to Routing

aspnetcore/blazor/security/webassembly/graph-api.md
Fixes #20883
Thanks @petersgiles! :rocket:
=> Remove part of an example

aspnetcore/tutorials/first-mvc-app/adding-model.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&branch=pr-en-us-20783&tabs=visual-studio)
--
Incorrect highlights for json snippets
Missing key step for steps on Macs
=> Updating highlights and Mac instructions

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #20917
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-20918#troubleshoot-integrity-powershell-script)
btw --- It's not related to the issue; but while I'm here, I want to make that code-based string for dev console into a **_blockquote_**, which will render better.
=> Blazor WASM integrity script Bitdefender exception

aspnetcore/blazor/fundamentals/additional-scenarios.md
=> Fix syntax error in code snippet

aspnetcore/migration/31-to-50.md
Addresses #20838
Reverts #20839
=> Redisplay Blazor PreferExactMatches content

aspnetcore/blazor/fundamentals/configuration.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1&branch=pr-en-us-20908)
=> Blazor Configuration UE pass

aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/index.md, aspnetcore/tutorials/razor-pages/model.md, aspnetcore/tutorials/razor-pages/new-field.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/razor-pages/search.md, aspnetcore/tutorials/razor-pages/sql.md, aspnetcore/tutorials/razor-pages/validation.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&branch=pr-en-us-20933&tabs=visual-studio)
Very minor update of metadata:
- Added ms.custom: contperfq2 used for tracking content improvements.
Fixes #20932
=> Razor Pages tutorial series: Add metadata for tracking improvements

aspnetcore/blazor/templates.md
Corrected the reference to the root component app in Blazor
=> Correction to the root element in Blazor

aspnetcore/data/ef-mvc/migrations.md, aspnetcore/security/app-secrets.md, aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/index.md, aspnetcore/tutorials/razor-pages/model.md, aspnetcore/tutorials/razor-pages/new-field.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/razor-pages/search.md, aspnetcore/tutorials/razor-pages/sql.md, aspnetcore/tutorials/razor-pages/validation.md
Applied updates per Mark's request.
=> Update FY21 Q2 content performance metadata tag

aspnetcore/blazor/fundamentals/environments.md, aspnetcore/blazor/fundamentals/environments/samples_snapshot/ReadEnvironment.razor, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/logging/samples_snapshot/Counter1.razor, aspnetcore/blazor/fundamentals/logging/samples_snapshot/Counter2.razor
Internal Review Topics:
* [Environments](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-3.1&branch=pr-en-us-20929)
* [Logging](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-3.1&branch=pr-en-us-20929)
Notes:
* Check me on the Logging one in particular. It seems like `CustomLoggingProvider` signifies just that ... a **custom** logging provider.
* I don't see [`WebAssemblyConsoleLogger`](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly/src/Services/WebAssemblyConsoleLogger.cs) in https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.AspNetCore.Components.WebAssembly.Services. Looks like that API didn't get marked for API docs. …
=> Blazor Environments & Logging topics UE pass

aspnetcore/tutorials/build-a-blazor-app.md, aspnetcore/tutorials/build-a-blazor-app/samples_snapshot/NavMenu.razor, aspnetcore/tutorials/build-a-blazor-app/samples_snapshot/ToDo0.razor, aspnetcore/tutorials/build-a-blazor-app/samples_snapshot/ToDo5.razor
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.0&branch=pr-en-us-20941)
=> Blazor tutorial UE pass

aspnetcore/blazor/fundamentals/logging.md
Per https://github.com/dotnet/AspNetCore.Docs/pull/20929#issuecomment-745748090.
I considered just placing "(internal)" after the first reference, but we have a lot of new devs and new-to-.NET devs to cover. It's probably safest to quickly explain it.
=> Blazor WebAssemblyConsoleLogger NOTE

aspnetcore/blazor/fundamentals/environments.md
Fixes #20989
Thanks @francescocristallo! :rocket:
=> Fix double word

aspnetcore/security/ip-safelist/samples/Shared/ClientIpSafelistComponents/Filters/ClientIpCheckPageFilter.cs, aspnetcore/security/ip-safelist/samples/Shared/ClientIpSafelistComponents/Middlewares/AdminSafeListMiddleware.cs
=> fix bad performing code example

aspnetcore/grpc/client.md
=> Access response headers from gRPC calls

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #21006
Thanks @AlbertoPa! :rocket: ... I'll work on this a bit more when I reach this topic again within a few months on general document passes.
=> Enhance multiple hosted Blazor client app guidance

aspnetcore/fundamentals/error-handling.md
Fixes #20958.
I think this also addresses the comment I removed from the topic. Let me know if you disagree.
cc @Rick-Anderson.
=> Note that StatusCodePages doesn't handle exceptions

aspnetcore/security/key-vault-configuration.md
Fixes #21047
Thanks @slimechips! :rocket:
=> Add Azure.Identity package

aspnetcore/migration/31-to-50.md
A semicolon was missing in newly added line
=> Missing semicolon

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
Fixes  #21034
Thanks @rameshkanjinghat! :rocket:
=> Blazor Hosted WASM B2C User.Identity.Name 5.0

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
=>  Blazor Hosted WASM AAD User.Identity.Name 5.0

aspnetcore/tutorials/signalr-blazor-webassembly.md
Fixes #21054
Thanks @rob-github! :rocket:
I opened an issue to 🔪 this later ...
**[5.0.2] Remove Blazor-SignalR tutorial encodings package content** #21056
cc: @BrennanConroy ... ~I'll wing it on the language given that we're still on the ⛄ *holiday break* :gift:. If you want to review and send suggestions for improvement, note them here. I'll patch the topic.~ **UPDATE**: Actually, best to wait for a sec to see if you have time for a quick :eyes: now. I'll merge if you're not free right now. :ear:
I'm going to hit a few other quick content layout nits while I'm here. This topic will receive further updates of that ilk on a UE pass in January.
=> Blazor-SignalR tutorial web encodings package

aspnetcore/tutorials/build-a-blazor-app.md
Fixes #21064
Thanks @joebowbeer! :rocket: ... Although the filenames aren't seen, I'll make those consistent, too.
=> Blazor Todo naming consistency

aspnetcore/host-and-deploy/iis/transform-webconfig.md
Change 'a environment' to 'an environment' to meet indefinite article rules.
=> Correct Grammar on Transform web.config Doc

aspnetcore/web-api/http-repl/index.md
=> removed mscustom tag

aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
Fixes #21078
Thanks @MrSethT! :rocket:
=> Fix CLI command

aspnetcore/blazor/security/webassembly/graph-api.md
Added new [] to the scope to match the instructions.
=> updated scope to match instructions

aspnetcore/fundamentals/servers/kestrel.md, aspnetcore/migration/20_21.md, aspnetcore/release-notes/aspnetcore-2.1.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0&branch=pr-en-us-21081#libuv-transport-configuration)
Fixes https://github.com/dotnet/aspnetcore/issues/26245
=> Obsolete Kestrel's Libuv transport

aspnetcore/security/authorization/simple.md
The following sentence:
> **Moved** shared content into one or more partial views...
Should read:
> **Move** shared content into one or more partial views...
=> Fix typo in simple.md

aspnetcore/grpc/code-first.md, aspnetcore/grpc/code-first/Contracts.cs, aspnetcore/grpc/code-first/GreeterService.cs, aspnetcore/grpc/code-first/Program.cs, aspnetcore/grpc/code-first/Startup.cs, aspnetcore/toc.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19825
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/code-first?view=aspnetcore-3.0&branch=pr-en-us-20882
@mgravell
=> Add code-first gRPC doc

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0&branch=pr-en-us-20957#prerequisites)
Fixes #20805 
- Updated for 5.0
- Little bit of clean up.
=> Update 5.0 building net docker images

aspnetcore/whats-new/2020-12.md
See https://github.com/dotnet/docs/pull/22219#discussion_r552147341
=>  Add link to Blazor breaking change.

aspnetcore/blazor/components/virtualization.md
Fixes #20823
Thanks @maloo! :rocket: ... I'll get the rest dealing with setting the height when I reach this topic again for it's UE pass, where I'll also take a look at the content, layout, examples, etc. For example, I notice that we don't broach the subject of **_disposal_**, and that should probably have a brief call-out and a quick example, too. We'll also have one of the product unit engineers look it over and see if they think it's missing anything or has any other technical problems.
=> Surface new API for Virtualization component

.whatsnew.json
Update the config file for the global tool's 1.0.0 NuGet package release.
=> Update what's new config file for 1.0.0 package release

aspnetcore/blazor/security/server/index.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
Fixes #20930
Thanks @AlbertoPa! :rocket:
=> Proxy config link for WASM security topics

aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/App.razor, aspnetcore/blazor/common/samples/5.x/BlazorServerSample/App.razor, aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/App.razor, aspnetcore/blazor/includes/prefer-exact-matches.md, aspnetcore/migration/31-to-50.md, aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Client/App.razor
=> Remove '@' from PreferExactMatches

aspnetcore/blazor/layouts.md
=> Surface Blazor layouts limitation

aspnetcore/web-api/handle-errors.md
=> clean up handle web API errors

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Views/Movies/Index.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Views/Movies/IndexForm1.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Views/Movies/IndexFormGenre.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Views/Movies/IndexGenreRating.cshtml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20845
The same inconsistency existed elsewhere in the same project, so I fixed all occurrences.
=> Enforce consistency with self-closing input elements

aspnetcore/fundamentals/websockets.md, aspnetcore/fundamentals/websockets/samples/2.x/WebSocketsSample/Startup.cs
=> remove ReceiveBufferSize

aspnetcore/mvc/views/razor.md
=> Surface Blazor layout limitation

aspnetcore/data/ef-mvc/update-related-data.md, aspnetcore/fundamentals/websockets.md
cc: @Rick-Anderson ... I'll perform a quick pair of updates here to resolve dup alt text problems from the build report when we merge to live. You might want to change the way that I did the first one: I'm just trying to 🏃 *quickly* 🏃 resolve these here, even if only temporarily in the first case.
=> Resolve dup alt text build suggestions

aspnetcore/host-and-deploy/iis/index.md
Fixes #20992
@jkotalik  90 second review please.
=> Add Overlapped recycle comment to IIS deployment doc

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #21176
Thanks @ejhg! :rocket:
Dan, this orginially came from your remarks here ...
https://github.com/dotnet/aspnetcore/issues/5477#issuecomment-599148931
=> Update Linux/macOS command

aspnetcore/blazor/debug.md
Fixes #20934
This update is discussed on the issue at https://github.com/dotnet/AspNetCore.Docs/issues/20934#issuecomment-758415194.
Thanks @matthewcorven! :rocket:
=> Note on dotnet watch run

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/virtualization.md, aspnetcore/blazor/index.md, aspnetcore/mvc/views/partial.md, aspnetcore/razor-pages/index.md
Fixes #21189
cc: @wadepickett ... Plz let me know if that title metadata change was a temporary/testing thing. I'll revert these updates if the title ever goes back to sentence case.
=> Use explicit link text

aspnetcore/blazor/components/class-libraries.md
Fixes #20726
Thanks @srpeirce! :rocket: ... Sorry for the delay getting to this. I was 🏃😅 and then the holidays hit. I'm digging out now.
I decided to do this ... I'll fix the main problem that you raised on this PR. When I circle back around to this topic on my UE ("user experience") pass on https://github.com/dotnet/AspNetCore.Docs/issues/19286, I'll revisit the content on static assets from RCLs. I've already made a note on the tracking issue so that I don't forget. Thanks again for writing in on this topic.
=> RCL styles for components update

aspnetcore/blazor/tooling.md
=> Links: AspNetCore (2021-01)

aspnetcore/mvc/views/tag-helpers/built-in/environment-tag-helper.md
IHostingEnvironment is obsolete.
=> Update IHostingEnvironment to IWebHostEnvironment

aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/components/virtualization.md, aspnetcore/blazor/includes/prerendering.md, aspnetcore/toc.yml
Fixes #16119
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-3.1&branch=pr-en-us-21199)
Thanks @kevingates! :rocket: ... I'll review+update on Wednesday morning before merging, which provides Steve some time to answer your last question on the issue with perhaps additional content for this PR.
=> Blazor component rendering topic

aspnetcore/host-and-deploy/azure-apps/index.md
Fixes #20372
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-5.0&branch=pr-en-us-20830&tabs=visual-studio#deploy-the-app-framework-dependent)
=> Update pub to Azure

aspnetcore/blazor/components/lifecycle.md
Addresses #21139
cc: @captainsafia
=> Word change

aspnetcore/blazor/call-javascript-from-dotnet.md
Fixes #21206
Thanks @stefanloerwald! :rocket:
Safia, this isn't super specific, but at least it gets the text remark in line with the code example.
**UPDATE**: Safia, I'm going to go ahead and get this in given that it's a slight doc bug 🐞. Let me know if you spot a needed change.
=> Update asset path description and example

aspnetcore/razor-pages/ui-class.md
Adds some extra info to the ui-class.md
https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class
@Rick-Anderson @scottaddie 
Let me know if I should create an issue? 
Greetings Damien
=> Added info about using the host layout for a shared razor page library

aspnetcore/blazor/project-structure.md
Fixes #21241
Fixes #21240
Thanks @hugh-maaskant! :rocket:
=> Blazor Project structure topic UE pass

aspnetcore/blazor/project-structure.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/21247#issuecomment-762946170
cc: @hugh-maaskant
=> Blazor Project Structure topic improvements

aspnetcore/blazor/forms-validation.md
=> Removed extra `@` to match all other uses

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19113
Fixes https://github.com/dotnet/aspnetcore/issues/26240
Replaces https://github.com/dotnet/AspNetCore.Docs/pull/20913
**[Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0&branch=pr-en-us-21235)**
=> Add PEM config info to Kestrel doc

aspnetcore/blazor/progressive-web-app.md
Fixes #20742
Thanks @Ricardoaraujo00! :rocket:
Per https://github.com/dotnet/aspnetcore/issues/20888#issuecomment-615207876.
=> Surface URL exclusion for PWA cached content

aspnetcore/signalr/supported-platforms.md
Fixes https://github.com/dotnet/aspnetcore/issues/29424
@BrennanConroy
=> SignalR update supported-platforms.md

aspnetcore/tutorials/signalr.md
=> bullet clean up signalr.md

aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
Fixes #21230
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1&branch=pr-en-us-21236#build-a-custom-version-of-the-authenticationmsal-javascript-library)
* Placed into the *Additional Scenarios* topic and cross-linked from the others.
* I didn't realize at the time we discussed this that it requires developer SDK bits, and I don't know what "this project" is in "Building the project ..." I think what's on the PR is incorrect.
* I start with a *'drop the built script into published assets'* approach, but I have a feeling that's not right ... that's not going to allow the smoothest debug build testing experience.
=> Custom Authentication.MSAL library

aspnetcore/blazor/components/lifecycle.md
Fixes #21096
Thanks @firewater! 🔥💧
=> Blazor component disposal improvements

aspnetcore/blazor/components/index.md
Fixes #21290
.... maybe 🤞.
This time, I'll check the *dog'gone live bleed'in topic!!!!* 😝.
Thanks @AndrewTriesToCode! :rocket:
=> Fix broken link list approach

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/project-structure.md, aspnetcore/blazor/security/index.md, aspnetcore/toc.yml
Fixes #21294
@AndrewTriesToCode ... I had a better idea ... something that could be done quickly to solve it. I'll just surface it in the section heading. This section can continue to cover both. I'll leave them separate in the ToC component list tho. I don't think that matters much either way.
=> Surface NavMenu component

aspnetcore/blazor/fundamentals/routing.md
Fixes #21291
Not a 🐞 the way it is, but the other examples use `NavigationManager`, so let's do that here, too.
Thanks @AndrewTriesToCode! :rocket:
=> Change service property

aspnetcore/fundamentals/error-handling.md
=> Explain how the HTTP method affects the exception handler page

aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/App.razor, aspnetcore/blazor/common/samples/5.x/BlazorServerSample/App.razor, aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/App.razor, aspnetcore/blazor/includes/prefer-exact-matches.md, aspnetcore/migration/31-to-50.md
Fixes #21227
Thanks @pinoli! :rocket:
There's one update left to make in the SignalR-Blazor Server tutorial sample app, but that's a new sample appearing on the open PR https://github.com/dotnet/AspNetCore.Docs/pull/21271. I'll go update that PR right now.
=> Update PreferExactMatches value

aspnetcore/security/authentication/index.md, aspnetcore/security/authorization/limitingidentitybyscheme.md
Fixes #20414
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0&branch=pr-en-us-21296#authentication-concepts)
=> Explain no default auth

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes https://github.com/dotnet/aspnetcore/issues/26244.
Also moved Configure before ConfigureHttpsDefaults.
=> Add ssl protocols default doc

aspnetcore/grpc/index.md, aspnetcore/grpc/supported-platforms.md, aspnetcore/includes/gRPCazure.md, aspnetcore/toc.yml
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-3.0&branch=pr-en-us-21276
=> Add gRPC supported platforms doc

aspnetcore/fundamentals/http-requests.md, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Handlers/OperationHandler.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Handlers/OperationResponseHandler.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Models/OperationScoped.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Pages/Operation.cshtml, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Pages/Operation.cshtml.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Startup.cs
Fixes #20401. Moved from #20458
@serpent5  put together an example and added a TODO into the topic for explanation. I'll do that in the next commit, but I'm offering this up here as a draft for some feedback on the approach.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0&branch=pr-en-us-21275#use-di-in-outgoing-request-middleware)
Public review of doc build 
- download https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0
- unzip
- view HTML file in FF (Fire Fox). It best to view the doc with the widest window that has no left or right TOC (Table  of contents)
=> Serpent5 scoped di/ra

aspnetcore/web-api/advanced/formatting.md, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/Controllers/WeatherForecastController.cs, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/Program.cs, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/Startup.cs, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/WeatherForecast.cs, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/WebAPI5PascalCase.csproj, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/appsettings.Development.json, aspnetcore/web-api/advanced/formatting/5.0samples/WebAPI5PascalCase/appsettings.json
Fixes #21318
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0&branch=pr-en-us-21328#configure-systemtextjson-based-formatters)
=> Error message always camelCase

aspnetcore/security/anti-request-forgery.md
Fixes #21316
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0&branch=pr-en-us-21319#windows-authentication-and-antiforgery-cookies)
=> Add details about windows auth/CSRF

aspnetcore/web-api/advanced/formatting.md
=> Specify MvcOptions.ReturnHttpNotAcceptable for 406

aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/supported-platforms.md, aspnetcore/toc.yml
Fixes https://github.com/dotnet/aspnetcore/issues/27284
Internal preview https://review.docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-5.0&branch=pr-en-us-21357&tabs=visual-studio
=> Add IIS and HTTP.sys to grpc asp.net core page

aspnetcore/fundamentals/servers/index.md
Fixes  #21369
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&branch=pr-en-us-21370&tabs=windows#kestrel-vs-httpsys)
Once this is published, create new SO Q/A and link to https://stackoverflow.com/questions/54641919/
=> Update web servers

aspnetcore/tutorials/build-a-blazor-app.md
Fixes #21381
Thanks @XzipbitA! :rocket:
=> Clarify no namespace in tutorial step

aspnetcore/mvc/models/validation.md
=> Expand nullable reference types

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/templated-components.md, aspnetcore/blazor/webassembly-performance-best-practices.md
Fixes #21266
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-3.1&branch=pr-en-us-21326#define-reusable-renderfragments-in-code)
Thanks @musictopia2! 🎸 and @stefanloerwald! 🎷
There's a few other nits on here, too. I'll look closer at the whole WASM perf topic when I reach it on the UE pass later.
=> RenderFragment property scenario

aspnetcore/host-and-deploy/proxy-load-balancer.md
=> remove config IPv4 addresss rep by IPv6

aspnetcore/blazor/call-javascript-from-dotnet.md
Fixes #21384
Per https://github.com/dotnet/aspnetcore/issues/29808#issuecomment-770848970.
Thanks @braidenstiller! :rocket:
=> Dynamic module import must be async

aspnetcore/blazor/components/virtualization.md
Fixes #21414
Thanks @bsHobbit! :rocket:
We have more work coming up for `ItemSize` on https://github.com/dotnet/AspNetCore.Docs/issues/21314.
=> Specify 'height' for item size

aspnetcore/mobile/native-mobile-backend.md
Added updated links for Xamarin developers to consume REST and authenticate. Also add links to Microsoft Learn
=> [Mobile REST] Update additional resources

aspnetcore/migration/31-to-50.md
Fixes #21428
Thanks @sterneric! :rocket: ... Sorry that I missed this one 😈.
=> Blazor WASM migration update

aspnetcore/tutorials/first-web-api.md
Apply updates to 3.1 version of tutorial
=> remove unnecessary NuGet Pkg from WebAPI

aspnetcore/blazor/host-and-deploy/webassembly.md
Addresses #21465
Thanks @stefanloerwald! :rocket: ... I'll leave your issue open on HOLD until they resolve your issue, then I'll revert the content back.
=> Use the unmifified Google Brotli script (again)

aspnetcore/security/authentication/identity.md
=> identity.md: Update link to Identity source code

aspnetcore/fundamentals/owin.md
Fixes #21406
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-6.0&branch=pr-en-us-21484)
=> OWIN Katana

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/includes/state-container.md
Fixes #21355
Thanks @aaronhudon! :rocket:
The main thing to check is the added text to the *Lifecycle* topic in the *Component disposal with `IDisposable`* section. That section (internal review topic) is at: 
https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1&branch=pr-en-us-21410#component-disposal-with-idisposable
=> Blazor event delegates

aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
Fixes  #21510
Thanks @esamk! :rocket: ... This doesn't encompass all of the improvements that can be made here. This is what I can do quickly 🏃😅 under a heavy workload ⛰️⛏️ at this time. I'll return to this topic for more work on https://github.com/dotnet/AspNetCore.Docs/issues/19286, including full testing and including working on the companion topic for the hosted scenario. If your product unit issue leads to the need for additional work, either you or I can open a new issue for that when we get their feedback.
=> Blazor Standalone WASM OIDC update

aspnetcore/blazor/host-and-deploy/webassembly.md
=> Cross-link BuildBundlerMinifier

aspnetcore/blazor/call-javascript-from-dotnet.md
=> Fixed the line number for code highlight

aspnetcore/blazor/security/index.md
=> Surface LoginDisplay in AuthorizeView content

aspnetcore/grpc/protobuf.md
Fixes https://github.com/grpc/grpc-dotnet/issues/1184
=> Protobuf field names info

aspnetcore/signalr/scale.md
=> Add Rebus to Third-party SignalR backplane providers

aspnetcore/test/troubleshoot-azure-iis.md
=> fix broken link caused by heading name change

aspnetcore/index.yml, aspnetcore/security/data-protection/implementation/key-storage-providers.md, aspnetcore/tutorials/build-a-blazor-app.md, aspnetcore/tutorials/razor-pages/new-field.md, aspnetcore/tutorials/razor-pages/sql.md
=> Links: ASP .NET Core (2021-02)

aspnetcore/fundamentals/app-state.md, aspnetcore/includes/cookies-not-compressed.md, aspnetcore/migration/proper-to-2x/index.md, aspnetcore/security/cookie-sharing.md
Fixes #21455
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-1.0&branch=pr-en-us-21571#cookies-are-not-compressed-in-aspnet-core)
[2nd review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-6.0&branch=pr-en-us-21571#cookies)
=> cookies not compressed

aspnetcore/tutorials/first-web-api.md
=> Add Learn link to resources

aspnetcore/security/samesite.md, aspnetcore/security/samesite/mvc21.md, aspnetcore/security/samesite/rp21.md, aspnetcore/security/samesite/rp31.md
=> Fix invalid C# dev langs in code snippets

aspnetcore/web-api/advanced/custom-formatters/samples/2.x/CustomFormattersSample/Formatters/VcardOutputFormatter.cs, aspnetcore/web-api/advanced/custom-formatters/samples/3.x/CustomFormattersSample/Formatters/VcardOutputFormatter.cs
=> Use selected encoding when writing the response

aspnetcore/test/load-tests.md
Hi,
Please add NBomber to the list of load-testing tools
> Very simple load testing framework for Pull and Push scenarios. It's 100% written in F# and targeting .NET Core and full .NET Framework.
Github: https://github.com/PragmaticFlow/NBomber
Docs: https://nbomber.com/docs/index.html
=> Add NBomber to list of load-testing tools

aspnetcore/tutorials/first-mongo-app.md
=> Add Learn Link

aspnetcore/security/authentication/samples.md
Fixes #21597
These updates make the topic version agnostic. The only activities that should require further updates are ...
* Moving samples.
* New or dropped samples.
=> Authentication samples article updates

aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #21613
Thanks @stefanloerwald! 🎸
=> Improve integration guidance instruction

aspnetcore/blazor/forms-validation.md
Fixes #21626
Thanks @TanvirArjel! :rocket: ...
More work will be performed on the whole topic when I reach it on my [UE ("user experience," i.e., topic overhaul) tracking issue (dotnet/AspNetCore.Docs #19286)](https://github.com/dotnet/AspNetCore.Docs/issues/19286). I might provide a fully working example for this section at that time. Devs like to cut-'n-paste complete examples into test apps for their own experimentation and app development. This scenario is a good candidate for that type of experience.
I'll also continue to track on your engineering issue. You asked a follow-up question, and I'll keep an :eye: on it for additional updates to this section either on this PR or another PR later if we need to surface more content.
=> Improve custom validation classes section

aspnetcore/blazor/call-javascript-from-dotnet.md, aspnetcore/blazor/common/samples/3.x/BlazorServerSample/Pages/_Host.cshtml, aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/wwwroot/index.html, aspnetcore/blazor/common/samples/5.x/BlazorServerSample/Pages/_Host.cshtml, aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/wwwroot/index.html
Fixes  #21652
Thanks @AnkitSharma-007! 🎷
=> Move script call locations in samples

aspnetcore/tutorials/first-mvc-app/adding-controller.md
Fixes some malformed URLs in the "Add controller" step of the MVC tutorial
=> Fix invalid URLs in the MVC tutorial

aspnetcore/blazor/components/virtualization.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0&branch=pr-en-us-21623)
=> Blazor Virtualize topic UE pass

aspnetcore/toc.yml
=> Link to LayoutView component in ToC

aspnetcore/includes/6.0-SDK.md, aspnetcore/includes/net-prereqs-mac-6.0.md, aspnetcore/includes/net-prereqs-vs-6.0.md, aspnetcore/includes/net-prereqs-vsc-6.0.md, aspnetcore/migration/50-to-60.md, aspnetcore/toc.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21580
=> Add migration guide for updating ASP.NET Core 5.0 to 6.0

aspnetcore/blazor/includes/security/troubleshoot.md
Fixes #21679
Thanks @jaredrakoff! :rocket: ... I'm not quite sure if this addresses your scenario exactly, but it's worth having as general troubleshooting guidance for app upgrades.
=> Blazor WASM security troubleshoot upgrades

aspnetcore/blazor/includes/security/troubleshoot.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
=> Add WASM security updates

aspnetcore/blazor/call-web-api.md
Just noticed a missing quotation mark, so I added it.
=> Added closing quotation mark to call-web-api.md

aspnetcore/introduction-to-aspnet-core.md
=> Fix link to repository zip file

aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #21717
Thanks @pallu! :rocket:
=> Cross-link section

aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/templated-components/Pets1.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/templated-components/Pets2.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/templated-components/Pets3.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/templated-components/Pets4.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Shared/templated-components/TableTemplate.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/_Imports.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/templated-components/Pets1.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/templated-components/Pets2.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/templated-components/Pets3.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/templated-components/Pets4.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Shared/templated-components/TableTemplate.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/_Imports.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/templated-components/Pets1.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/templated-components/Pets2.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/templated-components/Pets3.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/templated-components/Pets4.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Shared/templated-components/TableTemplate.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/_Imports.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/templated-components/Pets1.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/templated-components/Pets2.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/templated-components/Pets3.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/templated-components/Pets4.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Shared/templated-components/TableTemplate.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/_Imports.razor, aspnetcore/blazor/components/templated-components.md, aspnetcore/mvc/views/razor.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1&branch=pr-en-us-21666)
=> Blazor Templated Components topic UE pass

aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Protos/greet.proto
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/14170
=> Fix gRPC tutorial sample code

aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/GitHub/GitHubService.cs, aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/Pages/BasicUsage.cshtml.cs, aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactorySample/Pages/NamedClient.cshtml.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactorySample/GitHub/GitHubService.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactorySample/Pages/BasicUsage.cshtml.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactorySample/Pages/NamedClient.cshtml.cs, aspnetcore/fundamentals/middleware/index.md, aspnetcore/host-and-deploy/aspnet-core-module.md, aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md, aspnetcore/includes/MTcomments.md, aspnetcore/mvc/models/validation.md, aspnetcore/release-notes/aspnetcore-2.0.md, aspnetcore/release-notes/aspnetcore-3.0.md, aspnetcore/security/authentication/social/additional-claims.md, aspnetcore/security/data-protection/implementation/key-storage-providers.md, aspnetcore/whats-new/index.yml
**Summary of changes**
- Replacing some *master* branch references with *main*.
- The repo was migrated from the aspnet org. to the dotnet org. Updating the repo references accordingly.
=> Update master branch references to main and update repo org.

aspnetcore/tutorials/razor-pages/model.md
[Internal Review - model.md](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&branch=pr-en-us-21747&tabs=visual-studio-code#add-a-data-model)
Fixes #21738
=> RP Series - Removed sections scaffold provides in VS Code section

aspnetcore/blazor/fundamentals/configuration.md
Fixes #21756
Thanks @KevinBurton! 🎸
=> Enhance Blazor logging instruction

aspnetcore/fundamentals/static-files.md, aspnetcore/performance/caching/middleware.md, aspnetcore/security/cors.md
=> fix warnings

aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/fundamentals/static-files.md, aspnetcore/grpc/netstandard.md, aspnetcore/grpc/supported-platforms.md, aspnetcore/host-and-deploy/docker/building-net-docker-images.md, aspnetcore/migration/proper-to-2x/index.md, aspnetcore/performance/caching/middleware.md, aspnetcore/security/cors.md, aspnetcore/test/integration-tests.md, aspnetcore/toc.yml, aspnetcore/tutorials/razor-pages/model.md
=> Merge live from main

aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/rendering/CounterState1.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/rendering/CounterState2.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/rendering/CounterState1.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/rendering/CounterState2.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/rendering/CounterState1.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/rendering/CounterState2.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/rendering/CounterState1.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/rendering/CounterState2.razor, aspnetcore/blazor/components/rendering.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-3.1&branch=pr-en-us-21766)
=> Blazor Rendering topic UE pass

aspnetcore/blazor/advanced-scenarios.md, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/advanced-scenarios/BuiltContent.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Shared/advanced-scenarios/PetDetails.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/TrackingCircuitHandler.cs, aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/_Imports.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/advanced-scenarios/BuiltContent.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Shared/advanced-scenarios/PetDetails.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/_Imports.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/advanced-scenarios/BuiltContent.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Shared/advanced-scenarios/PetDetails.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/TrackingCircuitHandler.cs, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/_Imports.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/advanced-scenarios/BuiltContent.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Shared/advanced-scenarios/PetDetails.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/_Imports.razor, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/hosting-models.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1&branch=pr-en-us-21768)
=> Blazor Advanced Scenarios topic UE pass

aspnetcore/blazor/includes/state-container.md
Fixes #21808
Thanks @gregoryagu! 🎷
=> Improve State Container example

aspnetcore/blazor/components/index.md, aspnetcore/blazor/index.md, aspnetcore/mvc/views/partial.md, aspnetcore/razor-pages/index.md
=> Revert addition of Razor syntax topic link text

aspnetcore/fundamentals/target-aspnetcore.md
Addresses #21725
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-1.0&branch=pr-en-us-21727)
* I'm not sure if I've composed the scenarios exactly right given my lack of experience with multitargeting and Blazor Server-only targeting.
* This PR only focuses on the Blazor aspects. I suspect that you, Scott, will want to circle around for a comprehensive 5.0 update later. I've marked the PR as 'addresses' the issue and will re-assign after we get this bit merged.
* I don't seek to use snippets at this time given that ...
* The 🤖 *Cyberdyne Systems Snippet Builder 5000*&trade; 🤖 will just crush the existing snippet files and thus blow up :boom: the whole PR.
* The topic's snippets will change extensively when they go …
=> Razor components class library 5.0 updates

aspnetcore/host-and-deploy/linux-apache.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/host-and-deploy/linux-nginx/nginx.conf
Fixes #21743
Thanks @NavitaireSecurity! :rocket:
Internal Review Topics (link to section):
* [Nginx](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&branch=pr-en-us-21753#https-configuration)
* [Apache](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&branch=pr-en-us-21753#https-configuration)
Notes:
* I think we need a WARNING for this pair of sections. IMO, MS shouldn't take on responsibility for accurate, one-size-fits-all security config of third-party products.
* ⚠️ Due to my lack of familiarity with Linux security scenarios, I can't really say if this is exactly right, even in the general sense. This is the best that I can piece together from Nginx and Apache docs. I haven't …
=> Linux TLS security updates

aspnetcore/includes/RP/sqlitedev.md, aspnetcore/tutorials/first-mvc-app/adding-model.md, aspnetcore/tutorials/razor-pages/model.md
Fixes #21609
Test all links once we have a build.
=> SQLite in dev, SS in production links

aspnetcore/grpc/clientfactory.md
=> gRPC client factory page improvements

aspnetcore/grpc/retries.md
https://twitter.com/tech_fellow/status/1372910651333545987
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-3.0&branch=pr-en-us-21833#when-retries-are-valid
=> Add validity and streaming info to gRPC retries

aspnetcore/tutorials/dotnet-watch.md
=> Add a note about excluding content files

aspnetcore/tutorials/first-mongo-app.md
* [MongoClient](https://api.mongodb.com/csharp/current/html/T_MongoDB_Driver_MongoClient.htm): Reads the server instance for performing database operations. The constructor of this class is provided the MongoDB connection string:
Should be:
* [MongoClient](https://api.mongodb.com/csharp/current/html/T_MongoDB_Driver_MongoClient.htm): Reads the server instance for performing database operations. The constructor of this class is provided with the MongoDB connection string:
=> Sentence Correction at Line 620.

aspnetcore/security/anti-request-forgery.md, aspnetcore/security/app-secrets/samples/2.x/UserSecrets/appsettings-unsecure.json, aspnetcore/security/data-protection/configuration/overview.md
Fixes the aspnetcore.docs issues for  #21834 
The aspnet issues will be in a seperate pr for that repo of course.
=> Doc sweep fixes

aspnetcore/security/key-vault-configuration.md
Apply the metadata value required to track work done for the FY21 Q3 content performance work on this Key Vault doc.
=> Apply ms.custom contperf-fy21q3 metadata to Key Vault doc

aspnetcore/data/ef-mvc/inheritance.md
Hi,
Last one from me on this tutorial! I have tried to improve the readability of the "Inheritance" tutorial.
Poornima
=> Inheritance - Improving readability and consistency

aspnetcore/data/ef-mvc/concurrency.md
Hi,
I have tried to make the "Handle Concurrency Conflicts" more consistent :-)
Poornima
=> Handle Concurrency Conflicts - Amends for consistency

aspnetcore/data/ef-mvc/update-related-data.md
Hi,
I have made amends to bring more consistency to the Update related data page.
Poornima
=> Consistency updates to the Update related data page

aspnetcore/data/ef-mvc/read-related-data.md
Hi,
Another one! I have improved the readability and made it more consistent. I have added an extra link to the "Include multiple levels" on the eager loading page and increased the range of code as well (both in the Create Instructors page section)
Poornima
=> Improved consistency and readability

aspnetcore/host-and-deploy/aspnet-core-module.md, aspnetcore/host-and-deploy/iis/hosting-bundle.md, aspnetcore/includes/announcements.md, aspnetcore/introduction-to-aspnet-core.md
Fixes #21910
[Internal Review Topic (links to section in the 5.0 content)](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1&branch=pr-en-us-21914#install-aspnet-core-module)
Thanks @avendel! :rocket:
No cross-link to *Announcements* here. I'll note here in passing that there is no main *to keep up with Announcements, see ...* cross-link outside of mentions in *Migration* topics (cc: @Rick-Anderson on that in case it should be called out in the [ASP.NET Core Introduction article](https://docs.microsoft.com/aspnet/core/introduction-to-aspnet-core) ... I can add it to this PR if you want ... it's just a one-liner or an *Additional resources* cross-link there I think 🤔).
=> ASP.NET Core Module compatibility

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/debug.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-3.1&branch=pr-en-us-21881)
=> Blazor Prerendering and Integration UE pass

aspnetcore/client-side/spa/react.md
Updated the ASP.NET Core version to reflect that it works for ASP.NET Core 2.1 and above versions.
=> Updated the ASP.NET Core version

aspnetcore/security/docker-https.md
Fixes #21622
@RehanSaeed please review
=> Add VS instructions link to docker

aspnetcore/blazor/host-and-deploy/webassembly.md
=> Cross-link Azure static web app tutorial

aspnetcore/blazor/includes/state-container.md
Fixes #21948
Thanks @kjhf! :rocket: ... Would u like to review this?
=> Blazor state container example fix

aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/host-and-deploy/linux-nginx/nginx.conf
Modify nginx proxy_pass address Fixes #21944
=> Modify nginx proxy_pass address

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes https://github.com/dotnet/aspnetcore/issues/26242
@halter73 Is there important information I missed? On the surface it seems quite simple to explain (that's good)
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0&branch=pr-en-us-21941
=> Add SNI configuration docs

aspnetcore/grpc/authn-and-authz.md, aspnetcore/grpc/clientfactory.md
Addresses https://github.com/grpc/grpc-dotnet/issues/1255
=> How to configure auth using gRPC client factory

aspnetcore/test/razor-pages-tests.md
=> xunit.github.io not found

aspnetcore/grpc/basics.md
Fixes #21974
Thanks @gopkumr! :rocket:
=> Show full package reference in doc snippet

aspnetcore/client-side/bundling-and-minification.md, aspnetcore/client-side/libman/index.md, aspnetcore/client-side/libman/libman-cli.md, aspnetcore/client-side/libman/libman-vs.md, aspnetcore/client-side/spa-services.md, aspnetcore/fundamentals/target-aspnetcore.md, aspnetcore/migration/1x-to-2x/identity-2x.md, aspnetcore/migration/1x-to-2x/index.md, aspnetcore/migration/21-to-22.md, aspnetcore/migration/30-to-31.md, aspnetcore/migration/31-to-50.md, aspnetcore/migration/50-to-60.md, aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md, aspnetcore/mvc/views/tag-helpers/th-components.md, aspnetcore/security/authentication/windowsauth.md, aspnetcore/security/authorization/resourcebased.md, aspnetcore/web-api/action-return-types.md, aspnetcore/web-api/http-repl/index.md, aspnetcore/web-api/http-repl/telemetry.md, aspnetcore/web-api/index.md
=> Author scott change to rick

aspnetcore/grpc/troubleshoot.md
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0&branch=pr-en-us-21962
=> Add troubleshooting section for gRPC calls and subdirectories

aspnetcore/fundamentals/dependency-injection.md, aspnetcore/fundamentals/http-requests.md, aspnetcore/fundamentals/http-requests/samples/2.x/HttpClientFactoryConsoleSample/Program.cs, aspnetcore/fundamentals/http-requests/samples/3.x/HttpClientFactoryConsoleSample/Program.cs
Fixes #21958
Thanks @Gladskih! :rocket:
cc: @stevejgordon
=> Cross-link and enhance scoping in a console app

aspnetcore/grpc/performance.md
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.0&branch=pr-en-us-22001
=> Add gRPC performance section about reading data

aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Program.cs, aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/BackgroundTaskQueue.cs, aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/MonitorLoop.cs, aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/appsettings.json
=> refactored to use Threading.Channel instead of ConcurrentQueue

aspnetcore/data/entity-framework-6.md
Fixes #22022
Thanks @jordantvincent! :rocket:
=> Fix spelling

aspnetcore/fundamentals/error-handling.md
=> Be more explicit about "unhandled" exceptions

aspnetcore/blazor/debug.md
Fixes #22055
Thanks @BMarques! :rocket:
=> Code example fix

aspnetcore/mvc/views/view-compilation.md, aspnetcore/razor-pages/ui-class.md
Contributes to https://github.com/aspnet/Announcements/issues/459.
=> Update Razor output for version 6

aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample3/RazorPagesMovie30/Pages/Movies/Index.cshtml.cs
Fix for https://github.com/dotnet/AspNetCore.Docs/issues/22033
=> stop showing #regin in code snippet

aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Controllers/StreamingController.cs, aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Utilities/FileHelpers.cs, aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Controllers/StreamingController.cs, aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Utilities/FileHelpers.cs
=> Use Array.Empty instead of instantiating a new empty array

aspnetcore/security/authorization/secure-data.md
The link to the "Build a .NET Core and SQL Database web app in Azure App Service" was broken and now points to the new URL where the article is stored.
=> Update to broken link

aspnetcore/security/authentication/identity.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21789
=> added missing instruction for scaffolding uisng SQLite

aspnetcore/blazor/webassembly-performance-best-practices.md
Addresses https://github.com/dotnet/aspnetcore/issues/18919.
=> Add docs on preventing rendering after event handling

aspnetcore/migration/31-to-50.md
Fixes #22108
@DenmarkG, how's this look?
@daveabrock, do you want to run an :eye: over this? ... will only take a sec. I don't recall the scenario where this file appeared in build output. I'm going off of the PU issue.
=> Add a Blazor migration scenario

aspnetcore/fundamentals/file-providers.md
Fixes #22110
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.1&branch=pr-en-us-22112)
Thanks @danjagnow! :rocket:
* I touched up a few other bits, but I left the 2.x section alone ... not worth the trouble given that we're so close now to dropping 2.x coverage.
* I placed some spaces in the three type-name headings because I think those will MT ok and become more valuable for navigation.
=> File Providers topic updates

aspnetcore/security/authentication/index.md
Fixes #22099
Thanks @martijnhoekstra! :rocket:
Rick, how about we just link that first bullet to the next section (on the PR)? It's reached quickly and has an doc cross-link (`security/authorization/limitingidentitybyscheme`) in place in its first sentence.
=> Authentication Overview updates

aspnetcore/blazor/components/index.md
Fixes #22123
Thanks @EKanadily! :rocket:
=> Cross-link component integration

aspnetcore/security/data-protection/configuration/overview.md
UnprotectKeysWithAnyCertificate sample code.
=> Fixed build in "Configure ASP.NET Core Data Protection"

aspnetcore/tutorials/first-mvc-app/adding-model.md
Fixes #22129
Thanks @AmulyaReddy99! :rocket:
=> Highlight line

aspnetcore/blazor/components/index.md
Changed "concatination" to "concatenation" and added reference link to "global::"
=> Fix typo and add link

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #22122
Thanks @taylorchasewhite! :rocket: ... I'll work further on this section (and the whole topic) on my upcoming UE ("user experience") (i.e., total overhaul) pass later.
=> Update Blazor WASM security Additional scenarios

aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/Startup3.cs
There were two Startup2 classes in the same namespace
=> Fixed Swashbuckle ToDo Example

aspnetcore/security/authorization/simple.md
Adds an example on how to do authorization using Razor Pages.
***Edit by @Rick-Anderson***
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-5.0&branch=pr-en-us-22037)
=> Add Razor Pages authorization example

aspnetcore/includes/RP-MVC/validation.md, aspnetcore/tutorials/first-mvc-app-xplat/start-mvc/sample/MvcMovie/Models/Movie.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie21/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie21/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie21/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie21/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/validation.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22137
=> space in genre is now allowed, description is changed as appropiate

aspnetcore/blazor/globalization-localization.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/22146#issuecomment-827802596
Thanks @beppemarazzi! :rocket:
=> Update path in Blazor culture example

aspnetcore/toc.yml
=> HTTP Logging to TOC

aspnetcore/data/ef-rp/intro/samples/cu50/StartupMaxMBsize.cs
=> Idiomatic C# variable naming

aspnetcore/razor-pages/sdk.md
=> prep Razor SDK doc for efficient 6.0 PR/compare

aspnetcore/performance/performance-best-practices.md
Rearranging the section on IAsyncEnumerable to discuss the return of large collections.
=> Updating performance-best-practices.md

aspnetcore/mvc/advanced/custom-model-binding/samples/3.x/PolymorphicModelBindingSample/ModelBinders/PolymorphicModelBinder.cs
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22198
=> Fixup bug in implementation

aspnetcore/host-and-deploy/directory-structure.md, aspnetcore/mvc/views/view-compilation.md
=> prep to monikers to remove views.dll

aspnetcore/security/authentication/community.md
Fixes #22203 Fixes #22212
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/community?view=aspnetcore-1.0&branch=pr-en-us-22223)
=> add aspnet-contrib to commuity page

aspnetcore/fundamentals/servers/kestrel.md
=> forward headers, not host filtering

aspnetcore/grpc/netstandard.md
Fixes https://github.com/grpc/grpc-dotnet/issues/1290
=> Include minimum .NET Framework version for gRPC

aspnetcore/fundamentals/logging/index.md
Fixes #21306
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0&branch=pr-en-us-22260#apply-log-filter-rules-in-code)
@svdHero please review
=> Add LoggerFactoryOptions.ActivityTrackingOptions

aspnetcore/grpc/migration.md, aspnetcore/grpc/netstandard.md
=> Add detail about Grpc.Core deprecation

aspnetcore/razor-pages/ui-class.md
=> prep Razor UI class lib for .NET 5 version

aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md, aspnetcore/includes/aspnet-codegenerator-args-md.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22227
@Rick-Anderson please review
=> added section for code-generator view command

aspnetcore/security/authentication/certauth.md
=> Replace `that` with `at` in the sentence describing certificate exchange

aspnetcore/signalr/streaming.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20562
=> Update SignalR streaming code sample

aspnetcore/signalr/hub-filters.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21243
=> Fix hub filter sample code

aspnetcore/signalr/hubcontext.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20871
=> Update incorrect statements about IHubContext

aspnetcore/signalr/scale.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20451
=> Update vague text about Azure SignalR service and backplans

aspnetcore/performance/caching/distributed.md, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/Error.cshtml, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/Error.cshtml.cs, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/Index.cshtml, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/Index.cshtml.cs, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/Shared/_Layout.cshtml, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/_ViewImports.cshtml, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Pages/_ViewStart.cshtml, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Program.cs, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/README.md, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/SampleApp.csproj, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/Startup.cs, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/StartupRedis.cs, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/appsettings.Development.json, aspnetcore/performance/caching/distributed/samples/5.x/DistCacheSample/appsettings.json
Fixes #19680
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-5.0&branch=pr-en-us-22301#distributed-redis-cache)
=> Add Redis instructions

aspnetcore/razor-pages/ui-class/samples/cli/RazorUIClassLib/RazorUIClassLib.csproj, aspnetcore/razor-pages/ui-class/samples/cli/RazorUIClassLib/wwwroot/lib.css, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Pages/About.cshtml, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Pages/Contact.cshtml, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Pages/Shared/_Layout.cshtml, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Program.cs, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Startup.cs, aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/WebApp1.csproj
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22302
=> rcl project update  3.1

aspnetcore/blazor/fundamentals/startup.md
⚠️ **_Sarcasm Alert!_** ⚠️ *Thanks a lot build system for the note on these when the original PR was built!* :smile:
* https://github.com/dotnet/AspNetCore.Docs/pull/22279/files#diff-1b771961172b2d6288544f88ec6e30169dcd3d59e635a3da6084da8737cb94cf
* https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C332f35cd-658d-4914-0f85-907e40ee89f0%5CPullRequest%5C202105141044310572-22279%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=06ZWG%2Fajj%2BCz8d%2Fhd%2BwxXQuOxKdZzI2f1jQS8p%2FuabE%3D&st=2021-05-14T10%3A42%3A01Z&se=2021-06-14T10%3A47%3A01Z&sp=r
=> Cross-link updates

aspnetcore/mvc/controllers/filters.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22297
=> highlighting index fix

aspnetcore/grpc/security.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/19183
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/14821
=> Discuss TLS termination proxy in gRPC security doc

aspnetcore/grpc/troubleshoot.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20332
=> Improve gRPC WPF workaround instructions

aspnetcore/grpc/interprocess.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21459
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20290
Added explicit protocol to sample in case it isn't the default
=> Update gRPC UDS example

aspnetcore/grpc/configuration.md, aspnetcore/grpc/security.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20743
=> Add package links to gRPC configuration docs

aspnetcore/security/enforcing-ssl.md
Fixes #19410
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&branch=pr-en-us-22298&tabs=visual-studio)
=> Show how to disable HTTP

aspnetcore/tutorials/razor-pages/da1.md
=> Fix incorrect link

aspnetcore/mvc/models/model-binding.md
=> Binding C#9 record types /a

aspnetcore/tutorials/signalr/sample-snapshot/3.x/chat.js
Fixes #22337
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-5.0&branch=pr-en-us-22346&tabs=visual-studio)
=> Fix chat.js in SignalR /a

aspnetcore/blazor/host-and-deploy/webassembly.md
Courtesy ping for @blowdart 🎯 ... *I'm working with Blazor security subject matter here.* 😨😄 
[Internal Review Topic (links to section, **See NOTE**)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-22338#troubleshoot-integrity-powershell-script)
* Multiple users have hit this problem where a heuristic scanner throws a false positive.
* Not going to go with an INCLUDE for now. This is the only spot in Blazor docs that we need to cover this at this time. [Note tho that this is a wider problem across the repo, i.e. ... non-Blazor scenarios.]
* Explains that an exception is required for the file, **_BUT_** calls out a strong warning on file security when creating exceptions **_AND_** briefly covers …
=> Blazor 'integrity.ps1' script security

.openpublishing.redirection.json
=> Blazor topic redirection updates

.openpublishing.redirection.json, aspnetcore/blazor/components/cascading-values-and-parameters.md, aspnetcore/blazor/components/layouts.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/project-structure.md, aspnetcore/mvc/views/razor.md, aspnetcore/toc.yml
* Improved location for *Layouts* guidance consumption 🍽️😋. 
* Approved offline by PU management.
=> Move Blazor Layouts topic to Components ToC node

aspnetcore/fundamentals/servers/kestrel.md, aspnetcore/host-and-deploy/iis/index.md
=> Update kestrel.md /path-4

aspnetcore/data/ef-rp/complex-data-model.md
=> Remove extra comma

aspnetcore/data/ef-rp/read-related-data.md
=> Correct property reference

aspnetcore/data/ef-rp/read-related-data.md
=> Update css reference mention in versions >= 3.0

aspnetcore/data/ef-rp/migrations.md
=> Add missing directory separator

aspnetcore/migration/22-to-30.md, aspnetcore/security/authorization/dependencyinjection.md, aspnetcore/security/authorization/iauthorizationpolicyprovider.md, aspnetcore/security/authorization/policies.md
=> Show that AuthorizationHandlerContext.Resource is HttpContext for >= 5.0

aspnetcore/data/ef-rp/update-related-data.md
=> Update description for 5.0

aspnetcore/blazor/components/event-handling.md
Addresses  #22370
Thanks @darraghjones! :rocket:
This will be permanently addressed when the issue is reached after [UE passes are complete](https://github.com/dotnet/AspNetCore.Docs/issues/19286).
=> Temporarily surface perf issue with cross-link

aspnetcore/data/ef-rp/concurrency.md
=> Fix wording

aspnetcore/data/ef-mvc/intro.md, aspnetcore/data/ef-rp/intro.md, aspnetcore/includes/sql-log.md, aspnetcore/includes/sql-log/appsettings.json, aspnetcore/tutorials/first-mvc-app/adding-model.md, aspnetcore/tutorials/razor-pages/model.md
=> SHow how to log SQL

aspnetcore/mvc/controllers/filters.md
Fixes #21997
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0&branch=pr-en-us-22296#next-actions)
=> filters thread safety /7

.github/workflows/build-validation.yml, aspnetcore/fundamentals/http-logging/samples/6.x/Startup.cs
s/AppHttpLogging/AddHttpLogging
=> Fix typo in HttpLogging doc

.github/workflows/build-validation.yml
Fixes #22393 . If you want to "comment it out", this would probably work. If you want to remove it completely, then we should just remove the 4 files added in https://github.com/dotnet/AspNetCore.Docs/pull/21396.
=> Turn off snippets 5000

aspnetcore/index.yml
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-5.0&branch=pr-en-us-22404)
Fixes #21710
=> Hub page - Fixing EF MVC link

.github/workflows/build-validation.yml
Let's try this instead since #22400 didn't take.
=> Comment out file paths for snippets 5000

aspnetcore/grpc/clientfactory.md
=> Named clients with gRPC client factory

aspnetcore/fundamentals/host/hosted-services.md
Fixes #22347
@huan086  please review.
=> Update hosted-services.md 

aspnetcore/security/authorization/policies.md
=> Fix monikers for Policy-Based Authz

aspnetcore/fundamentals/http-logging/index.md
Fixes #22431
Fix AddText() and AddBinary() methods documentation
=> Fix MediaTypeOptions methods typo

aspnetcore/razor-pages/ui-class.md
=> Fixed sentence.

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
=> Update Blazor WASM AAD NOTE

aspnetcore/includes/RP/code/StartupDevProd.cs, aspnetcore/includes/RP/code/StartupDevProdV5.cs, aspnetcore/includes/RP/sqlitedev.md, aspnetcore/includes/add-EF-NuGet-SQLite-CLI-5.md, aspnetcore/tutorials/razor-pages/model.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21917
@Rick-Anderson please review. I don't know why but I can't add you as a reviewer from Github
=> Rp tutorial model doc update

aspnetcore/blazor/file-uploads.md
Fixes #22452
Thanks @CaiusJard! :rocket:
=> Improve phrasing of warning remark on uploaded files

aspnetcore/blazor/javascript-interoperability/index.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/22489#pullrequestreview-675522921
Well ... I guess I went a little **_tooooo fast_** 🏃😅 on that one. Try this revision to those lines.
I'll hold here Pranav until you can take a look at this.
=> Patch Blazor interaction with the DOM

aspnetcore/fundamentals/http-logging/index.md
=> Updated minor mistake

aspnetcore/grpc/index.md, aspnetcore/tutorials/grpc/grpc-start.md
=> Update some gRPC doc links

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
[EDIT by guardrex to add the issue]
Fixes #22507
According to this comment: https://github.com/dotnet/aspnetcore/issues/24237#issuecomment-663085021
=> Fix CustomUserFactory code

aspnetcore/mvc/views/partial/sample/PartialViewsSample/PartialViewsSample.csproj, aspnetcore/mvc/views/partial/sample/PartialViewsSample/Startup.cs
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22089
@wadepickett @Rick-Anderson please review
=> partial views sample update to target .net 5

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/fundamentals/routing.md, aspnetcore/includes/reservedRouting.md, aspnetcore/mvc/controllers/routing.md
[EDIT by @guardrex to add the 'addresses' and add a 'fixes']
Fixes #18636
Addresses #21501
Against the Issue [#18636](https://github.com/dotnet/AspNetCore.Docs/issues/18636).
Added the file `https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/includes/reservedRouting.md`.
Included the same in the routing docs.
*aspnetcore/mvc/controllers/routing.md
*aspnetcore/fundamentals/routing.md
*aspnetcore/blazor/fundamentals/routing.md
=> Changes against Issue #18636

aspnetcore/security/enforcing-ssl.md
Removed unnecessary white space that was making copying the command invalid.
=> Update Chrome section for Linux.

aspnetcore/mvc/views/view-components.md, aspnetcore/mvc/views/view-components/sample/StarterViewComp/StarterViewComp.csproj, aspnetcore/mvc/views/view-components/sample/StarterViewComp/Startup.cs, aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Controllers/ToDoController.cs, aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Startup.cs, aspnetcore/mvc/views/view-components/sample/ViewCompFinal/ViewCompFinal.csproj, aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Views/ToDo/IndexTypeof.cshtml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/14443
=> sample and documentation update for using component with type

aspnetcore/fundamentals/error-handling.md
=> Add error handling warning

aspnetcore/security/authentication/claims.md, aspnetcore/toc.yml
fixes https://github.com/dotnet/AspNetCore.Docs/issues/18191
**EDIT BY @Rick-Anderson** [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-3.1&branch=pr-en-us-22456)
=> Authentication claims mapping and claims transformation

aspnetcore/blazor/components/cascading-values-and-parameters.md
Such a great article! Couldn't help but fixing the typos 😺
=> minor typos fix

aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Views/ToDo/IndexTypeof.cshtml
section name should be typeof
[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-5.0&branch=pr-en-us-22531)
=> section header should be typeof instaed of nameof

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes #22534
Thanks @julioalfredo! :rocket: ... Versioning not needed given that it was apparently a change that they made back in a late preview release. I did find a few more spots to update tho.
=> Blazor WASM security named client

aspnetcore/grpc/clientfactory.md
Fixes  #22543
[Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-5.0&branch=pr-en-us-22544)
=> Fix Typo, use GrpcClientFactory.CreateClient

aspnetcore/data/ef-mvc/intro/samples/cu/Controllers/HomeController.cs, aspnetcore/data/ef-mvc/sort-filter-page.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20624
@Rick-Anderson while fixing this, I find out that the [version 5](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-mvc/intro/samples/5cu) sample is unfinished.
In, [Set up the site style](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0#set-up-the-site-style) section, the second code snippet prompts to download a sample from this URL which is not available,
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-mvc/intro/samples/5cu-final
I guess the project/folder never got pushed to the repo?
=> sample and doc update

aspnetcore/mvc/models/validation.md, aspnetcore/mvc/models/validation/samples/3.x/ValidationSample/Pages/Movies/Create.cshtml.cs
Fixes #22233
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0&branch=pr-en-us-22239#rerun-validation)
=> Update validation.md patch1
