aspnetcore/fundamentals/servers/httpsys.md
Fixes #21422
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0&branch=pr-en-us-21488#when-to-use-httpsys)
=> More on Kestrel vs. HTTP.sys

aspnetcore/blazor/includes/state-container.md
Addresses #21501
@JasonCard ...
* This will be our test to confirm that adding the metadata to an INCLUDES file **_doesn't_** work.
* When this (likely) fails, I'll revert these changes and go with the inline approach for these files. I have an algorithmic approach to make the changes in an automated way.
* Given that there's a delay on the localized version going live, I'll track on a couple of colons in the code blocks ...
```csharp
StateContainer.SetProperty($"New value set in Component 1: {DateTime.Now}");
```
```csharp
StateContainer.SetProperty($"New value set in Component 2: {DateTime.Now}");
```
... then compare the following content against "(Blazor WebAssembly)" and "(Blazor Server)" ...
Cross-reference: https://docs.microsoft.com/fr-fr/aspnet/core/blazor/state-management
=> no-loc metadata test in INCLUDES files

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md, aspnetcore/tutorials/signalr-blazor.md
Fixes #21524
Thanks @nosnetrom! :rocket:
Brennan, if you're too 🏃😅 to look, I'll ask Safia if she's free. :ear: 
[Internal Review Topic (*Tooling*)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-3.1&branch=pr-en-us-21526)
I'm making this dead simple to follow .... **_wordy_** 📘 *yeah* ... **_but_** dead simple ...
* Let's show with placeholders because there is flexibility in the folder and app naming.
* Let's follow that with an explicit example using the SignalR-Blazor tutorial example.
* Let's call out Edge config while we're at it. I use Edge for a lot of testing, especially my WASM security testing.
Outside of the *Debug WASM* topic and *SignalR-Blazor* tutorial, I didn't look further for hosted WASM VSC tooling cross-link opportunities because we …
=> Hosted Blazor VSC tasks/launch guidance

aspnetcore/blazor/components/index.md
Fixes #21552
Fixes #21553
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-21555#component-parameters)
This is a little rough. If you don't get a chance to look today (Monday), I plan to give it another polish pass on Tuesday AM. It will probably improve tomorrow morning.
I'm addressing sour guidance on the UE passes on https://github.com/dotnet/AspNetCore.Docs/issues/19286. I haven't reached this topic yet. Given the amount of hack'in on these topics over a long period of time, all bets are off on quality until I reach and overhaul them. This one tho ... for sure ... let's immediately address ...
* The main bug of missing the `()` for a method result assignment.
* Other problems in …
=> Component parameter assignment guidance

aspnetcore/mvc/controllers/filters.md
`IFilterFactory` is unrelated to **Result filters** so this PR moves it up in the heading structure to be its own heading in the TOC.
It might be the case that this section should actually be under **Dependency injection** instead though, and that it's located in the wrong part of the page currently.
=> Fix IFilterFactory heading level in filters.md

aspnetcore/blazor/host-and-deploy/webassembly.md
Addresses #21659
The whole NOTE will be removed as soon as Google fixes their script, so I don't need to really get into the weeds on a specific suggestion. I think the important thing to do is to drop the reference to B&M.
=> Drop BuildBundlerMinifier from a Blazor topic

aspnetcore/blazor/security/server/index.md, aspnetcore/security/authentication/social/additional-claims.md, aspnetcore/security/authentication/social/google-logins.md
Fixes #15445
Fixes #21560
Let's consider this again. 😄
Hao, we left this off over a year ago on the closed PR https://github.com/dotnet/AspNetCore.Docs/pull/15491.
The scenario is that there's an app in production. New external provider claims are needed. The dev updates the app according to the guidance for adding claims following the topic and on top of existing external claims that were put into the app when it was first built (i.e., just following the same pattern that they used when they built the app). The dev deploys the app to production with the new claims code in place. There are two user scenarios at this point:
* New claims aren't added to users on sign in, they're added on registration.
* New claims aren't updated for users who are currently signed into the app.
From the PR …
=> User claims added or updated

aspnetcore/blazor/debug.md
Fixes #21627
I place the guidance in both in the Prereqs section and in the VSC guidance tab. It shouldn't be missed this way.
=> Add VSC Blazor WASM Debugging Extension

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/includes/handle-errors/global-exception-handling.md, aspnetcore/blazor/security/server/threat-mitigation.md
\[Internal Review Topic]()
Notes ...
* I slept on the problem with MIA global exception handling. I still think that we should do something about it. Going all the way to November seems like a looooong wait.
I did scale back the section+example here. What I like about what I'm pitching here relative how devs have worked around this (e.g., logger implementations and other complicated approaches) is that the cascading component approach ...
* Is simple to reason about and can be shown/used quickly because it's based on a garden variety component with cascading values and parameters. Besides the approach's value for this use case, it cross-teaches the cascading concept, which is a powerful approach for component coordination anyway.
* Is easy to customize, including for ... …
=> Blazor Handle Errors topic UE pass

aspnetcore/blazor/fundamentals/signalr.md
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-3.1&branch=pr-en-us-21620)
The primary review request is to confirm that the sections and content for each of the WASM and Server pivots are correct. However, I did touch-up quite a bit here ... probably best to run an :eye: over everything.
=> Blazor SignalR UE pass

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
Microsoft.Identity.Web.UI is not required for Web APIs in doc hosted-with-azure-active-directory.md
PR removes this from the doc.
https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory
=> Refactor WASM security package text

aspnetcore/fundamentals/websockets.md
See https://github.com/dotnet/aspnetcore/issues/30646 - you won't be able to accept WebSocket connections in a controller if the UseWebSockets() middleware is below the UseEndpoints() middleware. In my opinion, whether or not the root issue is a bug is irrelevant (and I don't know if it is or not yet). This little note would benefit documentation readers. :)
=> Add information about the location of app.UseWebsockets()

aspnetcore/grpc/troubleshoot.md
Minor reorder of docs to explain .NET 5 requirements before .NET Core 3.x
=> Update gRPC troubleshooting

aspnetcore/tutorials/dotnet-watch.md
The code for dotnet watch no longer lives in the dotnet/aspnetcore github repo. It was moved to the dotnet/sdk repo: https://github.com/dotnet/sdk/tree/master/src/BuiltInTools/dotnet-watch. Having this link in the docs seems unnecessary.
=> Remove dotnet watch GitHub repo link

aspnetcore/fundamentals/servers/kestrel/options.md
`KeepAlivePingInterval` property has been renamed to `KeepAlivePingDelay` property. (https://github.com/dotnet/aspnetcore/pull/24308)
=> Rename KeepAlivePingInterval to KeepAlivePingDelay

aspnetcore/tutorials/signalr/sample-snapshot/3.x/Startup.cs
The `chat.js` file uses the URL "/chatHub" when connecting to the hub rather than lowercase "/chathub". I was receiving a 404 until changing it to align with the endpoint set in Startup.js.
=> Use correct endpoint to avoid 401

aspnetcore/blazor/call-web-api.md
The example line to call ReadFromJsonAsync: `var content = response.Content.ReadFromJsonAsync<WeatherForecast>();`, shouldn't it use await?
=> Missing await in ReadFromJsonAsync

aspnetcore/includes/net-prereqs-vs-6.0.md, aspnetcore/migration/50-to-60.md
Incorporates details from https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/
[Internal review page](https://review.docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-1.0&branch=pr-en-us-21804&tabs=visual-studio)
=> Update ASP.NET Core 5.0-to-6.0 migration guide for Preview 2

aspnetcore/fundamentals/logging/index.md
dotnet-trace has a ps command that can be used to determine the PID of all running dotnet processes on the machine, so all these instructions are outdated/unnecessary.
=> Update dotnet-trace instructions to use dotnet-trace ps command

aspnetcore/index.yml
Changing the querystring value to default select ASP.NET Core 5.0
=> Update API ref page link for 5.0 default selection

aspnetcore/data/ef-mvc/intro.md
Hi,
I have corrected a typo in the `Getting Started ` for EF MVC. I also think it can be helpful if there can be a deep link to the performance considerations from the MVC page. I have done both in a single PR as they are on the same page. 
Poornima
=> Fixed typo and added deep link

aspnetcore/grpc/browser.md, aspnetcore/grpc/netstandard.md
How to use gRPC client factory on .NET Standard 2.0 implementations.
=> Configure gRPC client factory on .NET Standard 2.0

aspnetcore/data/ef-mvc/migrations.md
Hi,
I have made a small correction to the migrations tutorial. The tutorial says to drop the database where as the tutorial said you changed the connection string earlier.
Regards,
Poornima
=> Corrected documentation for migrations

aspnetcore/blazor/components/data-binding.md
cc: @scottaddie (in your final days pinging u probably one last time :smile:) @Rick-Anderson @wadepickett 
I detect a rendering problem that might be due to an out-of-sequence highlight list. The original line is ...
```
[!code-razor[](~/blazor/common/samples/3.x/BlazorSample_WebAssembly/Shared/data-binding/PasswordEntry.razor?highlight=7-10,23-24,26-27,13,36-39)]
```
... with a highlight of `7-10,23-24,26-27,13,36-39` (the "13" is out of sequence) producing ...
I'm updating the line here to ...
```
[!code-razor[](~/blazor/common/samples/3.x/BlazorSample_WebAssembly/Shared/data-binding/PasswordEntry.razor?highlight=7-10,13,23-24,26-27,36-39)]
```
... with a highlight of `7-10,13,23-24,26-27,36-39` ("13" in sequence).
This PR is an attempt to see if the sequence is producing the rendering …
=> Fix Blazor Data Binding code snippet

aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
Fixes #21877
Thanks @dkboon01! :rocket: ... Let's start with cross-links to more info for Microsoft APIs. This is the most general and generic of the AAD-based Blazor auth topics, so the section on access token scopes will be a bit more vague than the other topics in this node. However, these enhanced cross-links should help. If you need general advice and product support, try the community on the usual public support places ...
* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
If you have topic feedback, such as for the issue that you opened, you did the right thing to open an issue using the **This page** feedback button+form at …
=> Add access token scope cross-links

aspnetcore/host-and-deploy/health-checks.md, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/BasicStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/CustomWriterStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/DBHealthStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/Data/AppDbContext.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/Data/Blog.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/DbContextHealthStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/LivenessProbeStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/ManagementPortStartup.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/MemoryHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/Program.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/README.md, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/ReadinessPublisher.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/SampleApp.csproj, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/Services/StartupHostedService.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/5.x/HealthChecksSample/appsettings.json
Fixes #21848
Per https://github.com/dotnet/aspnetcore/pull/21175.
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2&branch=pr-en-us-21854)
Thanks @mfkl! :rocket: ... You can see by this PR how involved it is. There's ...
* A new 5.0 sample app.
* A new 5.0 section with the content updates.
* Versioning, updated sample cross-links, localization improvements, and improved XREF link formats.
Just need to double-check with you, @mfkl: The updates on your product unit PR were for >=5.0, correct? They pertain to >=5.0 and not <5.0, right? If so, we're good here. That's the way that this PR is set up. Alternatively if for 5.x and 3.x, then I'll roll the updates into the 3.x content and the 3.x sample app. :ear:
=> Health Checks topic+sample updates for 5.0

aspnetcore/blazor/components/templated-components.md
Fixes #21769
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1&branch=pr-en-us-21846#infer-generic-types-based-on-ancestor-components)
Steve ... If it's easier/quicker to just fix it, please feel free to edit the PR directly. It starts at Line 97.
=> Blazor generic type cascading feature

aspnetcore/fundamentals/host/web-host.md
Fixes #21931
Thanks @oreze! :rocket:
@Rick-Anderson ... Chatted with ... er ... I think it was Scott ... at some point about this. We have double-spaces here and there to get `<br>`s in for this scenario. We spoke about just having true `<br>`s in these spots, which are instantly visible over markdown double-spaces. If we did switch over to `<br>`, it should be fine for inline markup ...
https://github.com/dotnet/AspNetCore.Docs/blob/main/.markdownlint.json#L35
Let me know if you prefer the switch, and I'll start go forward with `<br>` and revise as docs come up in the normal course of work. Otherwise, I'll keep going with markdown double-spaces. :ear:
=> Patch line breaks problem

aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorServerSignalRApp/BlazorServerSignalRApp.csproj, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorServerSignalRApp/Hubs/ChatHub.cs, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorServerSignalRApp/Pages/Index.razor, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorWebAssemblySignalRApp/Client/BlazorWebAssemblySignalRApp.Client.csproj, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorWebAssemblySignalRApp/Client/Pages/Index.razor, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorWebAssemblySignalRApp/Server/BlazorWebAssemblySignalRApp.Server.csproj, aspnetcore/tutorials/signalr-blazor/samples/3.x/BlazorWebAssemblySignalRApp/Server/Hubs/ChatHub.cs, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorServerSignalRApp/BlazorServerSignalRApp.csproj, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorServerSignalRApp/Hubs/ChatHub.cs, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorServerSignalRApp/Pages/Index.razor, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorWebAssemblySignalRApp/Client/BlazorWebAssemblySignalRApp.Client.csproj, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorWebAssemblySignalRApp/Client/Pages/Index.razor, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorWebAssemblySignalRApp/Server/BlazorWebAssemblySignalRApp.Server.csproj, aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorWebAssemblySignalRApp/Server/Hubs/ChatHub.cs
Fixes #21938
Brennan ...
* I found one totally *wrong* 🙈 sample package version. I don't think anyone pulled that sample down because I think I would've received the usual 💀 **_death threat_** 💀 from the community when I screw something up. :smile:
* I changed the name of `SendMessage` to `SendMessageAsync` for consistency, but I'll revert if that's a bad idea. :ear:
* In spite of roll-forward patch package version behavior, one of these apps was flaking out for no obvious reason on the presence of `PreferExactMatches` (a 5.0.1 thing) until I made package references point to the latest patch versions. It might have just been that I didn't clean the app. Anyway ... I went ahead and made all packages in all samples latest. *All apps work normally now.* :+1:
* There's no …
=> Blazor-SignalR tutorial updates

aspnetcore/tutorials/razor-pages/model.md
Removing an extra '-' when explaining how to call aspnet-generator. The correct way of calling it doesn't need the '-' between the dotnet and the aspnet-generator option. You can also see this as a way of unify how the asp-generator is being used in other tutorials like the first-mvc-app adding-model page here: https://github.com/iamnicoj/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md
Other related open issue caused by this extra hyphen: dotnet/Scaffolding#1404
=> Removing extra '-' when calling aspnet-generator

.github/workflows/check-for-build-warnings.yml
This adds a status check that fails if there are build warnings. This status check is not required to pass before the PR can be merged.
=> Add build warning status check

aspnetcore/grpc/netstandard.md
[Internal Review:  Use gRPC client with .NET Standard 2.0](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-5.0&branch=pr-en-us-22015)
=> Update gRPC WinHttpHandler required version

aspnetcore/toc.yml
The link at the end of the 'build your first' tutorial brings the reader back to the doc set at the 'build a todo list' tutorial, so they'll go away for it to `/learn/aspnet/blazor-tutorial/intro` but come back here and pick up where they left off.
Also, I add the Blazor-SignalR tutorial to the main *Tutorials* list.
=> Add the Blazor first tutorial to the ToC

aspnetcore/toc.yml
The original change hasn't gone live, so this fix is in under the wire 😅.
=> Fix Blazor tutorial cross-link

aspnetcore/blazor/call-web-api.md
Fixes #22063
Thanks @ToiWright! :rocket: ... The `HttpResponseMessage` is called out immediately under the example. This topic is due for an overhaul soon on https://github.com/dotnet/AspNetCore.Docs/issues/19286, and I'll take another look and make further updates when I reach it on that issue. Thanks again.
=> Update API description

aspnetcore/includes/aspnet-codegenerator-args-md.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/21475
=> duplicate instruction for --dataContext removed and added command instruction for --useSqlite

aspnetcore/security/authentication/community.md
[Community OSS authentication options for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community?view=aspnetcore-5.0) contains an additional link to edit the page. Since ASP.NET's GitHub repo structure has changed since then, the link has to be either updated or removed.
=> Update "edit this page" link to new repo

aspnetcore/security/enforcing-ssl.md
Fixes #22020
Fixes #22021
Fixes #22019
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&branch=pr-en-us-22064&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
=> FF trust cert

aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/netstandard.md, aspnetcore/grpc/supported-platforms.md, aspnetcore/host-and-deploy/iis/protocols.md
Fixes #22107
Thanks @richardbartley! :rocket:
Where the &dagger; and &Dagger; are stacked, I remove the intervening line and place two spaces at the end of the first line. This markdown creates a `<br>` there so that they'll be on separate lines. This is better than paragraphs imo.
From ...
> * Kestrel
> * TestServer
> * IIS&dagger;
> * HTTP.sys&Dagger;
>
> &dagger;IIS requires .NET 5 and Windows 10 Build 20300.1000 or later.
>
> &Dagger;HTTP.sys requires .NET 5 and Windows 10 Build 19529 or later.
>
> The preceding Windows 10 Build versions may require the use of a [Windows Insider](https://insider.windows.com) build.
To ....
> * Kestrel
> * TestServer
> * IIS&dagger;
> * HTTP.sys&Dagger;
>
> &dagger;IIS requires .NET 5 and Windows 10 Build 20300.1000 or later.
> &Dagger;HTTP.sys …
=> Windows version updates

aspnetcore/fundamentals/target-aspnetcore/samples/middleware.cs
Replaces hardcoded status code value with the usage of HttpStatusCode enum casted to int.
=> Use HttpStatusCode enum instead of hardcoded status code

aspnetcore/fundamentals/error-handling/samples/2.x/ErrorHandlingSample/Startup.cs, aspnetcore/fundamentals/error-handling/samples/5.x/ErrorHandlingSample/StartupLambda.cs, aspnetcore/fundamentals/url-rewriting/samples/2.x/SampleApp/RewriteRules.cs, aspnetcore/fundamentals/url-rewriting/samples/3.x/SampleApp/RewriteRules.cs, aspnetcore/fundamentals/websockets/samples/1.x/WebSocketsSample/Startup.cs, aspnetcore/fundamentals/websockets/samples/2.x/WebSocketsSample/Startup.cs, aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Filters/UnprocessableResultFilter.cs, aspnetcore/mvc/controllers/filters/sample/FiltersSample/Filters/UnprocessableResultFilter.cs, aspnetcore/security/anti-request-forgery/sample/AngularSample/Startup.cs, aspnetcore/security/anti-request-forgery/sample/Javascript/Startup.cs, aspnetcore/security/enforcing-ssl.md, aspnetcore/security/enforcing-ssl/sample-snapshot/2.x/Startup.cs, aspnetcore/security/enforcing-ssl/sample-snapshot/3.x/Startup.cs, aspnetcore/security/ip-safelist/samples/Shared/ClientIpSafelistComponents/Middlewares/AdminSafeListMiddleware.cs, aspnetcore/signalr/security/sample/Startup.cs, aspnetcore/web-api/route-to-code/sample/Startup2.cs
Fixes #22115.
Created on @Rick-Anderson suggestion in #22114.
I have also replaced all `StatusCodes` references to `HttpStatusCode` so the code is consistent in the documentation. If this is not right just comment and I will revert the last commit and remove only hardcoded status codes.
=> Replace status code with status code enum

aspnetcore/blazor/globalization-localization.md
In the code snippet provided as example of doing redirection for user selected culture, there was a NavigateTo with absolute path. This doesn't work if the app is behind a reverse proxy in some virtual subfolder.
=> Use relative path in NavigateTo

aspnetcore/host-and-deploy/iis/hosting-bundle.md, aspnetcore/host-and-deploy/iis/index.md
Fixes #22127
Thanks @ManojPrasad1984! :rocket:
Let's call out some additional details on stopping/restarting WAS/W3SVC.
I'm updating docs for >2.x, given that 2.x will go out of support and be dropped from the doc set fairly soon.
=> Clarify Hosting Bundle install WS restart guidance

aspnetcore/performance/caching/memory.md
Fixes #22142
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0&branch=pr-en-us-22145#use-imemorycache)
=> Remove EF warning on cache

aspnetcore/tutorials/first-web-api.md
Adding direction to run `dotnet aspnet-codegenerator controller` on a Mac from within the `TodoApi` subfolder.
=> Adding path to Mac directions

aspnetcore/blazor/components/css-isolation.md
This PR corrects an issue where the CSS reference should be `AssemblyName.styles.css` and not `ProjectName.styles.css`.
Fixes #22163
=> CSS isolation styles static file placeholder name

aspnetcore/security/data-protection/configuration/overview.md
Fixes #21996
Updated documentation to cover for PersistKeysToDbContext functionality in aspnetcore > security > data-protection > configuration > overview
=> Updated documentation to include PersistKeysToDbContext

aspnetcore/blazor/components/css-isolation.md
Fixed missing instruction that rose to issue #22177 and this SO post: https://stackoverflow.com/questions/65057537/why-blazor-css-isolation-not-adding-the-link-tag-to-load-the-bundled-css-file
=> Blazor CSS isolation stylesheet link clarification

aspnetcore/performance/caching/response.md, aspnetcore/security/authentication/customize-identity-model.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22179
@Rick-Anderson I did a lot of modifications. I do think that at this point we don't even need the `moniker range=">= aspnetcore-2.1 <= aspnetcore-5.0"` since I removed everything for `1.1` and `2.0`. And from 2.1 to 5.0 the snippets are all same. 
Please review.
=> modified documentation for customize identity model

aspnetcore/mvc/controllers/application-model.md
This PR is the result of running a Link Repair script on the included content. This script is primarily being run to cleanup links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes:
- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- This also includes cleanup of the appended query string for MSDN …
=> Links: ASP.NET Core (2021-05)

aspnetcore/security/authentication/social/microsoft-logins.md
Fixes #22206
App Registration in Azure Dashboard displays multiple values that could be understood as "Client ID": in particular the "ID" field of the "Client Secret" which is actually the Secret ID. This change edits the text to make the description more detailed (although this is somewhat at the expense of becoming outdated quicker when Azure Dashboard UX changes).
The "perfect" fix would have been to make both "Client ID" and "Client Secret" into hyperlinks that go to Azure documentation for the App Registration (with corresponding anchors) and explain what those values are, where they are on the dashboard, and show screenshots. This kind of documentation doesn't exist as far as I know, so it can't be linked to.
I bolded field names and tab names as is common in most product …
=> #22206 Reference Client ID and Secret detail from Azure Dashboard

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Result of .ToArray() is always not null.
=> refactor: remove always true condition

aspnetcore/grpc/aspnetcore.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/16959
(I think some conditional sections might be needed here because the Kestrel page was restructured in .NET 5)
=> Link to Kestrel endpoints HTTPS from gRPC docs

aspnetcore/tutorials/razor-pages/model.md
A simple fix from "dotnet aspnet-codegenerator" to "dotnet-aspnet-codegenerator".
#No Issue_Number.
=> from "dotnet aspnet-codegenerator" to "dotnet-aspnet-codegenerator"

aspnetcore/data/ef-rp/complex-data-model.md
This section:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio-code#create-a-migration
contains the following
After running the commands shown, I did not get the SQLite error message shown.
The docs mention `AlterColumnOperation`. Note that the migration file in my case uses `AlterColumn`:
Note that column is now called `FirstName`:
So the instructions now seem to work without issue on SQLite.
=> Remove outdated instructions

aspnetcore/data/entity-framework-6.md, aspnetcore/fundamentals/localization.md, aspnetcore/migration/http-modules.md, aspnetcore/migration/mvc.md, aspnetcore/migration/proper-to-2x/membership-to-core-identity.md, aspnetcore/mvc/views/tag-helpers/intro.md, aspnetcore/razor-pages/sdk.md
Fixes #22376
I only had a few minutes left this week, so this seemed like a good thing to squeeze in here. This should clean up the build report. In a couple of spots the cross-linked coverage was legacy without a suitable, current replacement, and I think it was fine to just mention the name of the thing without a cross-link in those few cases. In other spots, the current API docs have the information.
=> Build report bug fixes

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #22007
Thanks @carsten-moos ... If you figure out what's going on with the `New-BlazorFile` function and you'd like to suggest an update, please open a new issue with the update from the bottom of the topic. Otherwise, this update calls out that this is a PS6 script with the known good version that it was developed under.
=> Specify version of Blazor integrity.ps1 script

aspnetcore/blazor/security/index.md
Fixes #22405
@HaoK ... This will be safe because we're only cross-linking to existing guidance. I'll address further on the UE pass later with improvements to the Blazor Server *Overview* topic.
Thanks @Alienroid ... u can try to hack a component that calls Identity controller endpoints if you wish ... *at your own risk 😨, of course!* :smile: lol The only guidance I have from the PU is to use the ordinary Identity infrastructure and then customize on that basis. They permitted (I think) me to say in the scaffolding topic that hitting Identity controller endpoints should work. However, I want to review that with them later to see just how sound that is ... if it's completely safe and stable. Your issue is cross-linked to my UE pass tracking issue, so I won't lose our discussion.
=> Improve Blazor security NOTE

aspnetcore/performance/response-compression.md, aspnetcore/performance/response-compression/samples/2.x/SampleApp/README.md, aspnetcore/performance/response-compression/samples/3.x/SampleApp/README.md
Fixes #22424
Replaces cross-links to the defunct FireBug 🐞 with a *Firefox Browser Developer* cross-link.
btw - The trailing slash is required; otherwise, it leads to a double 301: one for the `/` and one for the localization.
=> Squash the Firebugs

aspnetcore/blazor/host-and-deploy/configure-linker.md, aspnetcore/data/ef-rp/intro.md, aspnetcore/fundamentals/logging/index.md, aspnetcore/fundamentals/servers/index.md, aspnetcore/host-and-deploy/visual-studio-publish-profiles.md, aspnetcore/migration/22-to-30.md
Fixes #22461
Found two 'master' branch cross-links in Blazor docs. Repo-wide search turned up a handful more that can be updated.
=> Swap 'main' for 'master' branch in cross-links

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/signalr-blazor.md
Fixes #22234
Thanks @samcarey! #22325 
Notes:
* It's challenging to cover cleanly because there are permutations of hosting (standalone vs. hosted), some sort of 🐞 *bug* in VSC `launch.json`/`task.json` automatic config, stock launch/task setup (non-debugging) vs. launch/task setup with debugging.
* I think what I've worked out covers things, and we can take feedback on this to see if further confusion 😵 ensues.
* Because I favor adding the `.vscode` assets to a hosted WASM app's **_solution folder_**, I don't think we should keep the old *Launch and debug a hosted Blazor WebAssembly app with Microsoft Edge* section, so I delete it here. That's now covered by the new content added on this PR. By opening at the solution level, all of the solutions folders/projects (`Client`, `Server`, and …
=> Blazor VSC launch/tasks/debug guidance updates

aspnetcore/blazor/includes/prerendering.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md
Thanks @angelotrivelli! :rocket: ... We just discussed the use of Bootstrap JS offline, and the PU ("product unit") confirmed that it's just like any other JS lib/framework. If the JS interop use of Bootstrap interacts with the same DOM objects that Blazor is tracking, bad results can ensue. If the Bootstrap JS is touching something that Blazor isn't tracking, then it's fine.
I'm improving the coverage on this subject ...
* I add a section to the new JS interop *Overview* topic on this.
* I mention Bootstrap JS and jQuery as examples.
* I mention that a few doc examples do violate the general guidance purely for demonstration purposes as part of an example, and I mention that the text calls out when the docs do this.
* I cross-link to the new section from relevant spots. …
=> Blazor interaction with the DOM

aspnetcore/blazor/state-management.md
There was a typo on `CurrentCount` lower case, should be upper case.
=> Typo on CurrentCount upper/lower case

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #21465
@stefanloerwald ... I'm going to close the issue out with these updates. I don't want an issue lying around here **_forever_**. If they ever fix the script minification and close your issue, would you open a new docs issue from the topic to update the content?
=> Google JS Brotli decompression script for Blazor

aspnetcore/blazor/fundamentals/routing.md
Fixes #22477
Thanks @ErikApption! :rocket:
Pranav: Optional parameters are covered in the *Route parameters* section, so that's why the bookmark link is set up the way that it is.
=> Blazor route constraints with optional params

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Without this, role-based backend API authorization won't work, the API will just return 403.
=> Fix ProfileService registration sample

aspnetcore/blazor/forms-validation.md
Fixes #22515
Thanks @mxmissile! :rocket:
Let's call it out generically. The dev can check the API to see which `Input{X}` components support it. This way, the doc is hardened against future engineering churn (e.g., new `Input{X}` components).
=> Cover Blazor InputX DisplayName property generically

aspnetcore/fundamentals/localization-extensibility.md, aspnetcore/fundamentals/localization.md, aspnetcore/fundamentals/localization/sample/3.x/Localization/Startup.cs, aspnetcore/fundamentals/middleware/index.md
Fixes #22512
@hishamco ...
* Places Routing Middleware first with an added bit for `RouteDataRequestCultureProvider`, which isn't covered in docs AFAICT. I cross-link it to its API doc.
* Scoping down the loc topic code sample to just show the pipeline add. The text explains two key ordering concepts and cross-links to the Middleware topic for more info. This has the Middleware topic deal with the broader aspects and show the full example.
* Minor touches to Loc Extensibility doc.
NOTE: In the loc sample app at ...
> aspnetcore\fundamentals\localization\sample\3.x\Localization\Startup.cs
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization/sample/3.x/Localization/Startup.cs#L98
... there was a 2nd `app.UseRequestLocalization()` that appeared at the very …
=> Loc Middleware ordering

aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor, aspnetcore/mvc/models/validation.md
Fixes #22503
Sorry for the trouble @kenjohnson03 and @renner2 ... Since my local test (hosted WASM) app does **_NOT_** have the `using` and the topic's Blazor Server example does **_NOT_** have it, it seems that I missed the update when working on this for the **_pivot_**. On https://github.com/dotnet/AspNetCore.Docs/pull/22161, I made an update to this topic to pivot the text and example between WASM and Server approaches because the text and example code are different. There are **two** examples of the component, one for WASM and one for Server. The WASM one didn't get this change. These 😈 *rotten gremlins* 😈 get in sometimes, and I appreciate your help and patience getting them **_OUT_** 😠 of the docs!
=> Fix broken Blazor file upload component

aspnetcore/security/authorization/policies.md
Adding a description of why mixing a handler and policy in the same class removes the need for DI registration.
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/18695
=> Update to include PassThroughAuthorizationHandler

aspnetcore/security/data-protection/configuration/overview.md
Correct that its blob storage that stores the keys, not keyvault.
=> Tweak the docker instructions

aspnetcore/blazor/components/data-binding.md
Fixes #22593
cc: @peterbozso ... **_Baaaaack again!_** 🏃
* Let's see if the additions here to the text explain that this is one-way and that the purpose of the `password` in the parent is to demonstrate an initial value *there* and that it updates from the child.
* I call out the 💀 **_don't write to a component param_** 💀 bit with cross-links to that coverage.
* This links *down* a section for the two-way bit (that includes across a component hierarchy, too).
* The new text on this PR probably needs a little more work ... just a draft at this point. I'll work it a bit more in the morning ☕🍩. Let me know if you have additional feedback here on the PR.
=> Clarify Blazor chained bind example

aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/mvc/views/razor.md
Fixes #21619
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1&branch=pr-en-us-22525)
=> Blazor Global/Loc UE pass

aspnetcore/security/authentication/social/additional-claims.md
Fixes #22613
Thanks @KurtP20! :rocket:
I think we can keep this only in the additional claims topic. It looks like a good spot to mention it is immediately after we list the registration topics. This is a general aspect of provider config on the provider side, so it generally applies. We can use AAD as an example and have a quick cross-link to the AAD topic that covers it, then we tell the reader to consult the external docs for the other providers for similar guidance.
=> Call out optional claims for tokens

aspnetcore/test/integration-tests.md
This PR fixes broken links to xUnit website and documentation in integration tests documentation.
There is no issue to be linked to this PR.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0&branch=pr-en-us-22637)
=> Update links to xUnit website and documentation for integration tests docs

aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/index/People.razor, aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/index/People.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/index/People.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/index/People.razor
Addresses #22644 
@konstantinovaleksej ... I'm going to put in a quick 🏃 patch fix to make it correct. However, this only *addresses* the issue and won't close it out. I need to hear from Steve on why this behavior occurs. After I hear back from him, I'll make another update that probably will include a new example+paragraph with the `Details` component in a list with the keyed `<li>` tag.
=> Update Blazor @key example

aspnetcore/signalr/hubs.md
Fix typo on example Hub method name in order to fit with sample method name.
public Task SendMessageToGroup(string user, string message)
{
return Clients.Group("SignalR Users").SendAsync("ReceiveMessage", user, message);
}
=> Fix typo on example Hub method name

aspnetcore/signalr/javascript-client/samples/3.x/SignalRChat/wwwroot/chat.js
> **Warning**: This code snippet is used as a [Sample](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#connect-to-a-hub).
I am not sure, if the behavior stays the same after this change. For me it looks like the intent should be the same though.
=> Use the automatic SignalR reconnect feature

aspnetcore/client-side/spa/angular.md, aspnetcore/client-side/spa/react.md
This patch renames the environment variable `ASPNETCORE_Environment` to `ASPNETCORE_ENVIRONMENT`.
=> docs: Fix typo in environment variable.

aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
Fixes #22703
Thanks @dustout! :rocket: ... Good news is that the topic already had the text to cover it ...
> The `maxAllowedSize` parameter of `OpenReadStream` can be used to specify a larger size if required.
I just didn't implement **_what I wrote in the topic in the sample app!_** 🙈 Did I have too much 🍺???? ... **_Or, not enough!??_** 😆
Thanks again for the catch. I'll merge this to the live doc immediately.
=> Refactor approach on max file size

aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/includes/handle-errors/error-boundaries.md, aspnetcore/blazor/includes/handle-errors/global-exception-handling.md, aspnetcore/toc.yml
Fixes #22446
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/22045
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-3.1&branch=pr-en-us-22688#error-boundaries)
* Add the coverage for error boundaries.
* While here, I want to move the *Global exception handling* heading into its INCLUDE file. It's just a nit update.
=> Blazor error boundaries

aspnetcore/blazor/components/index.md
Fixes #22450
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-22717#scalable-vector-graphics-svg-images)
=> Blazor SVG

aspnetcore/blazor/host-and-deploy/server.md
There is no `blazorserverside` template. I changed it to the proper name, `blazorserver`.
=> Change "blazorserverside" to "blazorserver"

aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample10.razor, aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample10.razor, aspnetcore/blazor/includes/js-interop/size-limits.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
=> Blazor byte array support

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/toc.yml
Fixes #22734 
\[Internal Review Topic (links to section)](#focus-an-element-on-navigation)
=> FocusOnNavigate for Blazor Router

aspnetcore/blazor/components/index.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22445
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/22045
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-3.1&branch=pr-en-us-22696#component-parameters)
=> Required Blazor parameters

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md, aspnetcore/mvc/views/tag-helpers/built-in/index.md, aspnetcore/mvc/views/tag-helpers/built-in/preserve-component-state.md, aspnetcore/toc.yml
Fixes #21771
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-3.1&branch=pr-en-us-22732#preserve-prerendered-state)
This one will remain in DRAFT state until the PU either provides additional details/API naming updates/usage patterns **_or_** they say go ahead based on the blog post content here (perhaps with some feedback) and we circle back around to this content later on another PR.
=> Blazor preserve state during prerendering

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/templated-components.md, aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/webassembly-performance-best-practices.md, aspnetcore/mvc/views/razor.md
Fixes #17351
* We're currently lacking some basic coverage in the *Components* overview for generic type params. This PR fixes that.
* The new 6.0 feature that allows `where` constraints with standard C# syntax is included.
* Improve cross-linking and lingo.
=> Generic type support updates (including 6.0 updates)

aspnetcore/mvc/views/razor.md
I corrected some code-fencing on `.razor` file extensions on an unrelated Blazor PR earlier this morning but noticed after merging that there were more file extensions and file/folder names/paths that need the treatment.
=> Additional code-fencing in Razor syntax topic

aspnetcore/signalr/redis-backplane.md
Comment in prior to this edit implied that Redis would be only good for development and test, when in fact, Redis is great for production usage and we want to make sure we don't imply anything to the contrary.
=> removed implied comment

aspnetcore/signalr/javascript-client.md, aspnetcore/signalr/javascript-client/samples/3.x/SignalRChat/wwwroot/chat.js
There are some cut-off snippets for version 3.1 of [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1) i.e. in [connect-to-a-hub](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#connect-to-a-hub) and [manually-reconnect](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#manually-reconnect) section. Fixed on my basic understanding. @Rick-Anderson please review
=> cutoff snippets fixed

aspnetcore/mvc/views/razor.md
Fixes #22848 per https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-5/
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0&branch=pr-en-us-22853#scalable-vector-graphics-svg)
=> Add SVG to Razor syntax /3

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/forms-validation.md
Fixes #22448
Addresses #22448
🛑 ~**HOLD FOR RELEASE OF PREVIEW 7**~ 🛑 We're going to go ahead with the coverage **_BUT_** with a NOTE that it applies to Preview 7. This is blocking other work. I'll revert the NOTE when Preview 7 releases.
* [Internal Review Topic (Data Binding, links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1&branch=pr-en-us-22770#multiple-option-selection-with-input-elements)
* [Internal Review Topic (Forms and Validation, links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1&branch=pr-en-us-22770#multiple-option-selection-with-the-inputselect-component)
On the PR:
* The multiple select feature for Preview 7 release. *I'll hold this PR …
=> Binding select multiple

aspnetcore/security/enforcing-ssl.md
Adds more detail to the security implications of having the ASP.NET Core dev cert generated in an environment that could be redistributed and how to disable it from being generated.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&branch=pr-en-us-22878&tabs=visual-studio)
=> Add info on security risk of redistribution of dev cert

aspnetcore/fundamentals/logging/index.md
Make the example `setx` command consistent with the corresponding `appsettings.json` configuration above (the `"Console"` part was missing).
Also fix a few typos.
=> Fix incorrect sample code and typos in aspnetcore/fundamentals/logging/index.md

aspnetcore/3.1/blazor/components/built-in-components.md, aspnetcore/5.0/blazor/components/built-in-components.md, aspnetcore/6.0/blazor/components/built-in-components.md, aspnetcore/toc.yml
Fixes #22897
**UPDATE**: Dan, Artak ... I'm going to go ahead and merge this because I'm going to give the `toc.yml`-per-group (version) test a shot. I'd like this topic in place for the test. The test PR becomes a live merge PR if the test works. Ping me for feedback on this ... concerns ... complaints ... 💀 **_death threats_** 💀😄. I'll mod it separately later on your feedback.
The *Built-in components* ToC node is a **_stinker_** 💩👃😵. The link highlight cues have never worked perfectly well. For example, the highlight cue is applied to the last URL that matches the loaded page, which isn't necessarily the component that the reader selected. Also, the whole node has to reside at the end of the Blazor ToC to get any of the highlighting not to interfere with the regular topics listed in …
=> Blazor built-in Razor components topic

aspnetcore/fundamentals/host/hosted-services.md
Fix the incorrect link anchor in order to point to the ShutdownTimeout section in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host#shutdowntimeout
=> Fix link anchor

aspnetcore/razor-pages/ui-class/samples/cli/WebApp1/Pages/Error.cshtml.cs
building the rcl sample was giving a warning. required a minor fix. @Rick-Anderson, please review
tag:  @chengyanbing https://github.com/dotnet/AspNetCore.Docs/pull/22808#issuecomment-890428061
=> response cache attribute should be set on page model

aspnetcore/6.0/blazor/components/class-libraries.md, aspnetcore/6.0/blazor/components/css-isolation.md, aspnetcore/6.0/blazor/components/event-handling.md, aspnetcore/6.0/blazor/components/prerendering-and-integration.md, aspnetcore/6.0/blazor/fundamentals/handle-errors.md, aspnetcore/6.0/blazor/fundamentals/routing.md, aspnetcore/6.0/blazor/fundamentals/signalr.md, aspnetcore/6.0/blazor/fundamentals/startup.md, aspnetcore/6.0/blazor/globalization-localization.md, aspnetcore/6.0/blazor/host-and-deploy/index.md, aspnetcore/6.0/blazor/includes/prerendering.md, aspnetcore/6.0/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/6.0/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/6.0/blazor/javascript-interoperability/index.md, aspnetcore/6.0/blazor/project-structure.md, aspnetcore/6.0/blazor/security/content-security-policy.md, aspnetcore/6.0/blazor/security/server/additional-scenarios.md, aspnetcore/6.0/blazor/state-management.md
Addresses #20319
This is step one of what will be a three step process:
1. `_Layout.cshtml` coverage generally across 6.0 topics. **This PR.**
2. Control of `<head>` content. Can be worked immediately after this goes in.
3. Prerendering and integration updates. The setup is so complex that it will need to be tested locally using prerelease bits, so the last step will be on hold until RC1 releases.
=> Blazor _Host to _Layout updates

aspnetcore/grpc/configuration.md, aspnetcore/security/authentication/add-user-data.md
Per Jason Card, these are fine to code-fence, and they don't break cross-links to headings. This will resolve a build suggestion that's popping up on unrelated PRs.
Adding a few tweaks for GRPC config. This will resolve a few additional build suggestions.
=> Resolve suggestion on heading

aspnetcore/6.0/blazor/components/class-libraries.md, aspnetcore/6.0/blazor/components/control-head-content.md, aspnetcore/6.0/blazor/components/css-isolation.md, aspnetcore/6.0/blazor/components/event-handling.md, aspnetcore/6.0/blazor/components/prerendering-and-integration.md, aspnetcore/6.0/blazor/fundamentals/handle-errors.md, aspnetcore/6.0/blazor/fundamentals/routing.md, aspnetcore/6.0/blazor/fundamentals/signalr.md, aspnetcore/6.0/blazor/fundamentals/startup.md, aspnetcore/6.0/blazor/globalization-localization.md, aspnetcore/6.0/blazor/host-and-deploy/index.md, aspnetcore/6.0/blazor/includes/layout-page-preview-7.md, aspnetcore/6.0/blazor/includes/prerendering.md, aspnetcore/6.0/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/6.0/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/6.0/blazor/javascript-interoperability/index.md, aspnetcore/6.0/blazor/project-structure.md, aspnetcore/6.0/blazor/security/content-security-policy.md, aspnetcore/6.0/blazor/state-management.md, aspnetcore/6.0/blazor/toc.yml
Addresses #20319
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-6.0&branch=pr-en-us-22931)
* This will be the 2nd step of a 🤠 **_Texas Three-step_**&trade; 💃🕺 (a dance that I just made up). This PR can be merged after revision and approval. The 3rd step will need to wait until RC1 to flesh out prerendering and integration guidance with local testing.
* To move forward with the upcoming Preview 7 release coverage, I call out the upcoming release in an INCLUDE for `_Layout.cshtml` and have a one-liner at the top of the new topic on controlling `<head>` content. I'll back these out as soon as Preview 7 is available.
=> Blazor control head content

aspnetcore/security/authorization/secure-data.md
Highlight call to `AddRoles<IdentityRole>()` instead of `AddEntityFrameworkStores<ApplicationDbContext>()` in the **Add Role services to Identity** section
=> Highlight the correct line of code

aspnetcore/security/authorization/secure-data.md
Replace "Return `context.Success`" and "Return `context.Fail`" phrases in text to "Call ...", these are void functions. And also add some details to the description of returning `Task.CompletedTask` in `AuthorizationHandler<>.HandleRequirementAsync`
=> Replace mixed up words and add some details

aspnetcore/blazor/components/built-in-components.md, aspnetcore/blazor/components/control-head-content.md, aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/dynamiccomponent.md, aspnetcore/blazor/forms-validation.md, aspnetcore/toc.yml
Fixes #22005 
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-6.0&branch=pr-en-us-22984)
@daveabrock ... See how this is shaping up thus far.
* Follows your general blog post layout.
* Loosely follows your examples. However, I wasn't clear on why you had the types in the metadata for the passing parameters piece. You don't have the full implementation shown in your post, so I'm not sure how you use your metadata dictionary. I just keep the parameters and the name (for display) in the metadata and generate the options from it. Also, the naming might still be a bit dodgy ... I'm still working on that a bit.
* I'm not on the new bits yet. I tend to adopt preview releases starting with RC1 (for …
=> Blazor DynamicComponent coverage

aspnetcore/blazor/hosting-models.md
Blazor has multiple hosting models that are appropriate for different scenarios. There really isn't a primary hosting model. This language incorrectly discourages users from building with Blazor Server.
=> Remove language stating that Blazor WebAssembly is the primary hosting model

aspnetcore/blazor/fundamentals/routing.md
Fixes #22689
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1&branch=pr-en-us-23000#uri-and-navigation-state-helpers) (links directly to the NavManager table section; the *Query strings* section immediately follows)
Mackinnon ...
* I'd normally 🛌😴 one more night, but let's get this in quickly 🏃. It will be reviewed again at RC.
* Most of this PR pertains to the query string bits, but I do add the `replace` guidance for `NavigateTo` while I'm here.
* URI vs. URL: The API rightly uses "URI" ... but for practical purposes around the doc set, we use URL because that's specifically and usually what the dev is working with. Here, "URI" is used in text *near* API remarks, and "URL" is generally used …
=> Blazor 6.0 query string enhancements

aspnetcore/blazor/globalization-localization.md
Fixes #23010
Thanks @craigbrown! 🎷
@hishamco ... Do you want to review this?
~I can't tell from the PU history if they backported to 3.1. I'll need to test and see what happened. The change that introduced the `BlazorWebAssemblyLoadAllGlobalizationData` property came in for >=5.0. However, I see a reference by the PU that it might have been backported to a 3.1 release to fix some bugs on iOS. I'll take a look ASAP 🏃 ... probably Friday morning.~ **_Answered below._**
=> Add Blazor WASM globalization requirement

aspnetcore/data/ef-mvc/complex-data-model.md
Implicit join tables are supported since EF Core 5.0, but the documentation for EF Core + MVC was outdated
=> Update EF Core MVC implicit join

aspnetcore/blazor/file-uploads.md
Fixes #22444 
~Await confirmation on https://github.com/dotnet/aspnetcore/pull/35373.~ :+1: **_Confirmed!_**
=> Update API cross-reference

aspnetcore/data/ef-rp/migrations.md, aspnetcore/data/ef-rp/sort-filter-page.md, aspnetcore/fundamentals/host/platform-specific-configuration.md, aspnetcore/fundamentals/localization.md, aspnetcore/fundamentals/logging/index.md, aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/host-and-deploy/visual-studio-publish-profiles.md, aspnetcore/host-and-deploy/windows-service.md, aspnetcore/mvc/controllers/filters.md, aspnetcore/mvc/models/validation.md, aspnetcore/release-notes/aspnetcore-2.1.md, aspnetcore/security/authentication/azure-active-directory/index.md, aspnetcore/security/authentication/certauth.md, aspnetcore/security/authentication/social/index.md, aspnetcore/security/samesite/mvc21.md, aspnetcore/security/samesite/rp21.md, aspnetcore/security/samesite/rp31.md, aspnetcore/signalr/redis-backplane.md, aspnetcore/test/razor-pages-tests.md, aspnetcore/test/troubleshoot-azure-iis.md
Contributes to fixing #21751
This PR fixes all 5.0 to 2.0 version broken links in the repo, except for a few where the link is still good but the issue was that the ssl cert expired, link technically works, plus no alternative.
=> Broken links sweep

aspnetcore/blazor/components/index.md
Fixes #23056 
Thanks @leotsarev! :rocket: ... **_Indeed!_** ... I'm acquainted with this **_sneaky devil_** 😈 ... this happens when the doc author (**_ME!_** 🙈) isn't aware of the location of the cursor and has a backspace ... er ... **_incident_** 😆😢😆😢. The build report catches some of these types of problems, so I'm a bit surprised when they come in as an issue ... but they sneak by. In this case, it probably just treated that as normal text and didn't flag it. I'll get this merged and live immediately. Thanks again for the report.
=> Fix broken cross-links

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #23039
I also made some improvements to the earlier text/example that we added for streaming to .NET.
btw -- need review of https://github.com/dotnet/AspNetCore.Docs/pull/23033.
=> Blazor .NET to JS Streaming Interop

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/includes/DuendeIdentityServer.md, aspnetcore/migration/50-to-60.md, aspnetcore/security/authentication/identity-api-authorization.md, aspnetcore/security/authentication/mfa.md, aspnetcore/toc.yml, aspnetcore/tutorials/first-mongo-app.md
Fixes #22355
Addresses https://github.com/dotnet/aspnetcore/issues/32881
This at least gets the ball rolling ... but there are potentially a few little devils 😈 in the details ...
* Not sure on the presence and phrasing of `public DbSet<Key> Keys { get; set; }` in the migration topic.
* I added Duende to the ToC with a cross-link to their docs. This PR keeps the existing ToC cross-link to IdentityServer4 docs. Do u want to keep that cross-link in the ToC?
* Hao, your PU PR didn't include the license text AFAICT ... it might have been a different project template PR tho. I took a shot at wording lingo here for docs.
* I can't quite test all of the Blazor guidance **_YET_**. I do plan to do so tho ... either in the RC period or after GA (possibly as late as January) as …
=> Guidance and migration for Duende IdS

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/security/server/threat-mitigation.md
Fixes #22863
* Is `(function start() { ... })()` necessary in this scenario? AFAIK, we document calling `Blazor.XXX` directly in the `<script>` everywhere else.
@danroth27 ... I cross-link to the Azure Feedback item ...
[Support WebSocket connections on Azure Front Door](https://feedback.azure.com/forums/217313-networking/suggestions/37346371-support-websocket-connections-on-azure-front-door)
... is that a good :+1: bikeshedding scenario (they **_should be aware of it and vote_**) or bad :-1: bikeshedding scenario (they'll need to find that on their own and let's chop 🔪 the cross-link here)?
=> Long Polling disabled update

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md, aspnetcore/razor-pages/ui-class.md
Fixes #23070
Let's see :eye: how this looks. We had some coverage for it, but it was rather weak. Many spots didn't mention it.
I also perform some code-fencing of mostly filenames here.
=> Library naming behavior

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/components/css-isolation.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md, aspnetcore/razor-pages/ui-class.md
Fixes #23070
Addresses dotnet/aspnetcore#35587
Rick, #23077 was kind'a headed in the right direction but didn't really fix the problem.
Javier just remarked on the latest PU issue (a different discussion from the earlier one at https://github.com/dotnet/aspnetcore/issues/26055), "... it's always the package Id that is used." Looking at his earlier doc issue, he stated in the title, "Indicate that [Library Name] = MSBuild $(PackageId)". Steve also remarked ...
> Just to capture context, this is by design (since we want package and project references to behave the same, as it's more convenient not to force developers to switch between two different reference formats.
I think that the PR #23077 for Issue #23070 was moving in the right direction, but it looks like it would be better to recast …
=> Package ID updates (Redux)

aspnetcore/host-and-deploy/iis/development-time-iis-support.md
The sentence:
> ... a binding to **post** 80...
Should read
> ... a binding to **port** 80...
=> Fix typo in development-time-iis-support.md

aspnetcore/includes/run-the-app.md, aspnetcore/includes/trustCertVS.md, aspnetcore/includes/trustCertVSC.md, aspnetcore/tutorials/grpc/grpc-start.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&branch=pr-en-us-23061&tabs=visual-studio)
Fixes #21657
- Updated the topic for version 5.0.  Moved existing 3.1 content into its own 3.1 moniker section.
- Clarified the instruction for the SSL security popups. You will not get those if they were set previously, but the instruction assumes you always would and I recall several customers pointing out the confusion around this in other topics using the same instructions.
- I verified the 3.1 instructions work with the latest grpc packages.  So no need to specify an earlier version.
- I verified the sample service and client porjects build and run properly so I am leaving them as is.
=> Update gRPC Client and Server tutorial and app sample

aspnetcore/mvc/views/tag-helpers/intro.md
These three sections should either have proper markdown line breaks or be converted to headings (or a bullet list?). Currently the "headings" run into the text content without a line break, which looks weird:
Live page: https://docs.microsoft.com/en-US/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-5.0#what-tag-helpers-provide
=> Add proper markdown line breaks

aspnetcore/blazor/hosting-models.md
* Dropping versions because so little of this is versioned content and it's easier to maintain this one versionless.
* Favoring Blazor Server first in phrasing and order of coverage.
=> Blazor Hosting Models topic updates

aspnetcore/security/authentication/certauth.md
Fixes https://github.com/dotnet/aspnetcore/issues/34006, adds descriptions for delayed client certificate negotiation.
The xref warnings are for new .NET 6 APIs that don't seem to be available yet in the API docs.
=> Update optional client cert doc for 6.0 features

aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/performance.md
Fixes  #23075
cc: @hishamco ... Do you want to put an 👁️ on this one? I'm just calling out the additional ways to configure invariant globalization and moving the content into a section higher in the Blazor doc. Plus, I add a cross-link to the .NET doc. btw -- That .NET doc content claims that this has been around since 2.0, so I add it to the <5.0 content of the performance topic here. AFAIK, it did work back then on that basis.
=> Additional invariant globalization config

aspnetcore/blazor/security/index.md
Fixes #19807
Looking the issue over (and I'll consider this further on upcoming UE "user experience" updates on #19286), I'd like to improve cross-links to MS identity platform docs for the basics on OAuth 2.0, OIDC, auth code flow, and tokens.
> doc about the mapping between the registered default schemas and extension methods like AddAzureADBearer and AddAzureAD
API docs cover these, and the extension methods can be found in reference source. Some of the differences are point-in-time ... ADAL to MSAL and implicit grant to auth code. We try to avoid covering migration in the reference docs. Transitions are covered by MS security docs.
> JwtBearerOptions, OpenIdConnectOptions and CookiePolicyOptions. It would be also appreciated that those connections would be illustrated
These are …
=> MS identity platform cross-links

aspnetcore/host-and-deploy/windows-service.md, aspnetcore/security/authentication/certauth.md
fixes some references to 'hang' that were flagged by policheck
=> Update to policheck-flagged text

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes https://github.com/dotnet/aspnetcore/issues/26246
These were 5.0 features that were only partially covered by the SNI docs.
***@Rick-Anderson EDIT:*** [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0&branch=pr-en-us-23241#ssltls-protocols)
=> Doc "SslProtocols" and "ClientCertificateMode" settable via config

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes https://github.com/dotnet/aspnetcore/issues/26241. This was a 5.0 feature.
=> Doc kestrel config reload support

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes #23180
@niem94 ... Here's the direction that I'm headed **_thus far_** 🚧⛏️👷. I might ultimately decide not to go this way, but this shows one way to compose coverage for these features.
* Split token signing from custom domains. These are independent concepts.
* Place the new App Service setup in the two new token signing sections (... but I might decide to take all of the new App Service coverage bits out because other docs exist for it in our doc set and in the Azure docs already. That way, all of this IdS coverage can just focus on the token signing and custom domain config.)
* We'll keep the IdS app token signing configuration for Windows as a gesture in the `appsettings.json` file, where it uses the Windows cert store.
* Let's consider **NOT** using the more complicated Azure …
=> Blazor IdS custom domains and token signing

aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/performance.md
Fixes #22370
Thanks @darraghjones! :rocket: ... **_but_** I'll need to have engineering remark on this given that it stretches my understanding of the relevant factors for this scenario. I do want to try and keep the new `Action`-delegate-based example close to what we're showing in the [*Lambda expression* section of the *Event handling* article](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#lambda-expressions-1) ...
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample5.razor
The content is TBD based on what engineering has to say about this. Even if I did create a 💩👃 *RexStinker*&trade; 😄 here, this PR at least gets the ball rolling on the …
=> Blazor event delegate performance

aspnetcore/blazor/security/server/threat-mitigation.md
For one thing, the feedback site has been dropped, so the link is a dead end for info on this ...
https://feedback.azure.com/forums/217313-networking/suggestions/37346371-support-websocket-connections-on-azure-front-door
There are indications from dev feedback that if Azure SignalR Service is used, all will be well with a Blazor Server app and Azure Front Door ...
https://docs.microsoft.com/en-us/answers/questions/146868/if-websockets-are-not-supported-in-azure-front-doo.html
I think we can drop the Azure Front Door remark. We'll take more feedback on it. They said that it was a priority feature request; so even if there are lingering problems today, I expect that they'll have them sorted out soon 🤞🍀.
=> Remove Blazor Server with Azure Front Door remarks

aspnetcore/fundamentals/servers/kestrel/http3.md
@Tratcher @JamesNK Not sure if this was intentional, but this linked to a specific section of the preview features doc before.
=> Link to full doc on preview features instead of a subsection.

aspnetcore/fundamentals/servers/httpsys.md
=> RC1 httpsys by chris/4 (#23257)

aspnetcore/fundamentals/servers/kestrel/http3.md, aspnetcore/fundamentals/servers/kestrel/samples/6.x/Http3Sample/Program.cs
Reflects the more streamlined behavior. We should publish this when RC1 is shipped on the 14th, and reference it from https://github.com/aspnet/specs/pull/602 (CC @danroth27).
Fixes https://github.com/dotnet/aspnetcore/issues/34488
=> publish when RC1 is shipped on the 14th: Update HTTP3 Sample for RC1

aspnetcore/blazor/components/index.md
Fixes #23295
... but ... I see ...
> warning NU1603: Microsoft.AspNetCore.Components.CustomElements 0.1.0-alpha.21402.1 depends on Microsoft.AspNetCore.Components.Web (>= 6.0.0-rc.1.21381.3) but Microsoft.AspNetCore.Components.Web 6.0.0-rc.1.21381.3 was not found. An approximate best match of Microsoft.AspNetCore.Components.Web 6.0.0-rc.1.21452.15 was resolved.
=> Blazor custom elements

aspnetcore/blazor/components/index.md
=> Generate Angular and React components

aspnetcore/security/authentication/identity-enable-qrcodes.md
In-line JavaScript is insecure and breaks script-src 'unsafe-inline' in Content Security Policy.
Note: I think the part about locating the Scripts section in EnableAuthenticator.cshtml should probably go after bit I've added about creating the js file (qr.js), and before updating the scripts section. I haven't moved it as I wasn't sure how the "moniker" directives worked and didn't want to break anything. (my first ever documentation proposal)
=> Move the creation of the QR code to a js file.

aspnetcore/tutorials/razor-pages/page.md
`@` symbol is followed by a Razor reserved keyword, it transitions into Razor-specific markup, otherwise it transitions into HTML. --NOT '...into C#."
=> Fixed '@' symbol work definition

aspnetcore/introduction-to-aspnet-core.md
Customer reported to us that we had a dead external link; updated to last known good.
=> Update dead external link

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes #26243 (5.0): ServerOptionsSelectionCallback 
Also adds (6.0): TlsHandshakeCallbackOptions
The overall document needs reorganizing, but at least this adds the new APIs.
***@Rick-Anderson EDIT:*** [Internal review URL - V6](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0&branch=pr-en-us-23302#sni-with-servercertificateselector)
=> ServerOptionsSelectionCallback and TlsHandshakeCallbackOptions

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/javascript-interoperability/index.md, aspnetcore/includes/js-collocation.md
Fixes #23299
* https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/#collocate-javascript-files-with-pages-views-and-components
* Probably should be covered in a few spots because ...
* This feature works with script files collocated with pages/views/components in the app and from RCLs.
* There's separate general RCL coverage for RP/MVC and Blazor.
I think the best way to go is via an INCLUDES file that can be placed in a few strategic spots ... as long as such a file covers all of the scenarios (app model and script locations).
Notes on the INCLUDES file:
* I'm only going to work this into the Blazor topics on this PR. The RP/MVC topics need a little work ... e.g., they're like 2.0-era (literally 2.0, not 2.1) and don't use whole-topic versioning ... and I'm not sure …
=> JS file collocation with Razor components

aspnetcore/blazor/fundamentals/signalr.md
btw -- I add the API doc cross-links (e.g., `HTTPTransportTypes`) after GA. They aren't available yet to cross-link.
=> Update Long Polling content

aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/includes/js-initializers.md, aspnetcore/blazor/javascript-interoperability/index.md, aspnetcore/blazor/performance.md
=> Blazor JS initializers

aspnetcore/fundamentals/servers/kestrel/diagnostics.md, aspnetcore/toc.yml
**@Rick-Anderson  edit:** [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/diagnostics?view=aspnetcore-6.0&branch=pr-en-us-23319)
=> Kestrel diagnostics doc

aspnetcore/mvc/models/validation.md
Fixes #23034 by making it clear to the end-user that the `[Required]` attribute used for non-nullable context is not the default one, but one that only checks for null values.
=> Improve [Required] attribute description

aspnetcore/blazor/tooling.md, aspnetcore/fundamentals/servers/kestrel/endpoints.md
This PR is the result of running a Link Repair script on the included content. This script is primarily being run to clean up links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes:
- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- This also includes cleanup of the appended query string for MSDN …
=> Linkfix: ASP.NET (2021-09)

aspnetcore/security/authentication/certauth.md
Fixes #63530
There has some extra setup needed for Azure Web Apps, the validation will fail with the "The system cannot find the file specified" error if they're not supplied.
=> Cross-link certificate use patterns for App Service

aspnetcore/mvc/models/validation.md
Clarifies to the end-user that for non-nullable reference types a `[Required(AllowEmptyStrings = true)]` attribute is used, that only checks for null values.
=> Improve [Required] attribute usage

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md
Fixes #23373
We'll go ahead with these updates for now and circle around after RC2 release/after code review.
=> Update hosted WASM debug guidance

aspnetcore/grpc/basics.md
[Internal Review: Moniker v6 added only](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-6.0&branch=pr-en-us-23415)
Adding just the new .NET 6 moniker section to merge first, so pr for the actual content update for .NET 6.0/VS 2022 can be easily differentiated. 
Contributes to #23403
=> v6 Update: gRPC Services with CSharp: Add 6.0version Moniker section only

aspnetcore/grpc/diagnostics.md
[Internal Review: New moniker sections only are the only change.](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0&branch=pr-en-us-23433)
Update gRPC Diagnostics topic moniker version section for .NET 6.0 only, no content updates.   
Then once this is merged, use this v6 monikered version to make v6 updates in the content so it is easier to diff to the original for reviews.
=> v6 Update: gRPC Diagnostics: Moniker versioning only

aspnetcore/grpc/index.md
Update for .NET 6.0
- Create new 6.0 version moniker section.
- Change code reference from Startup.cs to Program.cs
- Update template name.
- Verify there isn't anything else to change.
=> gRPC Intro v6 update

aspnetcore/mvc/models/validation.md
We really don't want a sample that shows this (particularly when the doc is also incorrect)
=> Remove section that demonstrates disabling validation

aspnetcore/tutorials/razor-pages/model.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/razor-pages/sql.md
Fixes #23682.
For consistency with the other pages, I've changed the relevant monikers to show content for all versions rather than excluding the lower versions. I concluded that this is the quickest/easiest approach for now, but we can come back and use a topic-level `monikerRange` later.
=> Fix empty RP tutorial pages

aspnetcore/blazor/security/includes/app-component.md
Fixes #23696
Thanks @johndhunter! :rocket: ... This will be the best way to go for now. I'll revisit when I reach the security node on UE passes in 2022 and perhaps make it so that versioned code is loaded. The problem with doing that now is that:
* It's a change that will require similar work in other areas. I might even decide in the end to use this "see the ref source" approach for everything. The framework churn is challenging to keep up with, and that's a guaranteed winner for churn **_as long as the dev selects the right release in the PU repo (per the INCLUDE here)._**
* Or, we might be dropping this coverage entirely in 2022 in favor of the Azure docs coverage. If so, then we don't want to spend a lot of time making changes to this at this time. That's a waste of ⏱️ ... thus a …
=> Version-agnostic App component

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
@guardrex this is for your consideration. Given how the docs are broken up into _from dotnet_ and _from javascript_, I think it may make sense to split up the streaming sections appropriately as well. I've added cross-links to ensure this remains navigable.
=> Refactor Blazor Streaming Docs

aspnetcore/blazor/fundamentals/static-files.md
Move the branch configuration from the `StartsWithSegments` method to the `MapWhen` method.
=> Correct an error in the use of `MapWhen`

aspnetcore/signalr/scale.md
Adding a link to the SqlServer backplane that I've created. https://github.com/IntelliTect/IntelliTect.AspNetCore.SignalR.SqlServer
=> Add link to SQL Server backplane for SignalR

aspnetcore/blazor/host-and-deploy/index.md
Addresses #23695
**_Draft-ish_** coverage at this point. I'm marking it off on the [tracking item check off list](https://github.com/dotnet/AspNetCore.Docs/issues/19286), but the topic is still up for a UE pass there. This will be improved when it's reached, probably in 22H1.
@cmedianu ... This is just an FYI that I worked out the coverage for this fallback path scenario *that makes sense now* 🙈 for Blazor apps. This use case is for a separate area of components and resources within the app that uses `MapFallbackToPage` with a separate area root page. The use case doesn't pertain to your original ask, but I just wanted to thank you again for the issue. It resulted in several important improvements to the coverage for sub-apps and this use case.
=> Activate new/working MapFallbackToPage coverage

aspnetcore/blazor/includes/js-interop/size-limits.md
Fixes: https://github.com/dotnet/AspNetCore.Docs/issues/23738
=> Update Blazor JSInterop Size Limits Docs

aspnetcore/blazor/components/css-isolation.md, aspnetcore/blazor/fundamentals/static-files.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #23729
* Static file topic organization.
* Static File Middleware callout and cross-link to main doc set for details.
* `<StaticWebAssetBasePath>` property description and examples.
* Cross-links relevant scenarios, including API docs and ref source.
* Nit improvements to hosted multiple WASM app scenario.
=> Blazor static files guidance improvements

aspnetcore/release-notes/aspnetcore-6.0.md
Addresses #22852
cc: @Rick-Anderson @serpent5 @wadepickett 
Just a few nits at the moment. I'll have a few more updates on Monday morning for the Error Handling topic. The heading in the topic will change to match what's here, so the link here will ✨ *Just Work!*&trade; ✨ when my Monday morning update goes live. As for the rest of the MIA Blazor stuff, that's still being worked out internally. I'll flesh out the commented-out bits as soon as I have guidance from DR on the final Blazor coverage.
Side-note on the `view` qs param: It only works when non-6.0 docs load if that "preserve view" param is also supplied. I don't recall the exact param at the moment. I think all of the `view=aspnetcore-6.0` links should get it here. It's a confusing UE if we don't add that param to these links 😵.
=> Blazor updates for What's New 6.0

aspnetcore/host-and-deploy/health-checks.md
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks#separate-readiness-and-liveness-probes
In the second snippet of this section, "Separate readiness and liveness probes", the original highlight was like this:
```diff
+        // Simulate the effect of a long-running startup task.
+        Task.Run(async () =>
+        {
await Task.Delay(_delaySeconds * 1000);
_startupHostedServiceHealthCheck.StartupTaskCompleted = true;
_logger.LogInformation("Startup Background Service has started.");
});
```
I changed the highlighted lines to 4 lines below, that is, like:
```diff
// Simulate the effect of a long-running startup task.
Task.Run(async () =>
{
await Task.Delay(_delaySeconds * 1000);
+
+            _startupHostedServiceHealthCheck.StartupTaskCompleted = true;
+ …
```
=> Update highlighted lines in code snippet in "Health checks in ASP.NET Core"

aspnetcore/blazor/supported-platforms.md
Fixes #23784
Thanks @anranruye! :rocket: ... Part of the doc wasn't updated properly on a recent round of updates when I was trying to implement a new type of doc content versioning (*that didn't work out* 😢). This PR restores the original 3.1 content before that failed attempt took place. Thanks for your report on this.
=> Blazor platforms update for 3.1

aspnetcore/includes/net-prereqs-vs-6.0.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&branch=pr-en-us-23794&tabs=visual-studio)
Updated the v6 prereq include to point to VS 2022 rather than preview.
Contributes towards #23771.  Doing this item in a separate PR to get it live quickly since it is used in several topics.
=> v6 vs2022 update for prereq include

aspnetcore/blazor/security/content-security-policy.md
Reflects changes in https://github.com/dotnet/aspnetcore/pull/36771 / https://github.com/dotnet/aspnetcore/issues/34428.
Created https://github.com/dotnet/aspnetcore/issues/36805 to track removal of the inline script which requires the `sha256-v8v3RKRPmN4odZ1CWM5gw80QKPCCWMcpNeOmimNL2AA=` hash.
=> Update Blazor CSP Guidance

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md, aspnetcore/release-notes/aspnetcore-6.0.md, aspnetcore/toc.yml, aspnetcore/whats-new/21-07.md
Fixes #23810
Thanks @JulienM28! :rocket:
cc: @shirhatti ... I was too literal copying DR's blog post on this from ...
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-2/#preserve-prerendered-state-in-blazor-apps
... and the coverage ended up mangling the name (and markup) of the Tag Helper. This PR should fix things up. It will break the link to the TH doc, and the section in the Blazor *Prerendering and integration* topic gets a new name. If you cross-linked in the blog post to ...
https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#preserve-prerendered-state
... change that to ...
https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=se …
=> Persist component state updates

aspnetcore/security/enforcing-ssl.md, aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program.cs, aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program2.cs, aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program3.cs, aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/appsettings.json
Fixes #23761
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&branch=pr-en-us-23773&tabs=visual-studio)
=> .NET 6 update enforce HTTPS /4

aspnetcore/docfx.json
cc @Rick-Anderson, @guardrex, @wadepickett.
This should mean we no longer need to provide the `--xrefService` argument for DocFx. I'm just running it through the build-system to make sure I haven't missed anything. Please let me know if you see any issues before I consider merging.
=> Configure xrefService in docxfx.json

aspnetcore/grpc/troubleshoot.md
Preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0&branch=pr-en-us-23857#configure-grpc-client-to-use-http3
Fixes https://github.com/grpc/grpc-dotnet/issues/1478
=> Troubleshoot doc on using gRPC client with HTTP/3

aspnetcore/blazor/fundamentals/signalr.md
`Blazor.defaultReconnectionHandler._reconnectionDisplay` is a framework internal API. I believe we may want to avoid officially documenting it as its subject to change without notice.
=> Blazor remove documentation of `_reconnectionDisplay`

aspnetcore/migration/50-to-60-samples.md, aspnetcore/toc.yml
While I work on the 3.1 to 6.0 migration guide, let's not rule out the 3.1 folks to look at these samples, most of which apply to 3.1 for folks that want to make the big jump to the new minimal hosting model.
=> Make the migration samples not exclude the LTS train, 3.1 folks aren't excluded

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/components/css-isolation.md
Fixes  #23849
Thanks @liangpeihui! :rocket:
Javier, you approved the RCL section at https://github.com/dotnet/AspNetCore.Docs/pull/20539. Looks like we need some additional detail on it:
* Updates seek to clarify the RCL scenario in both this topic and in the RCL topic. I took @liangpeihui's suggestion to expand the remark in the CSS Isolation topic that the bundled file "references the styles using CSS imports" remark to include more detail (and an example) on the CSS import statement. The RCL topic is also updated on this PR with these expanded remarks.
* The updated *build time* remark now points to the `obj` path for the bundle file. This is a bit detailed for docs to cover, but the updated path seems to be where the file is in the project and updates how it's named. I guess we're …
=> Blazor CSS isolation updates

aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #23911
Thanks @dotnetshadow! :rocket:
* Looks like we can drop the property for 6.0 or later based on local testing.
* Let's make this guidance about publishing from the **`Server`** project for hosted WASM more prominent with a callout in the *Host and Deploy* overview NOTE.
=> Update Blazor custom web.config guidance

aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md, aspnetcore/security/authentication/scaffold-identity.md
=> prep monikers for scaffold identity

aspnetcore/fundamentals/host/generic-host.md
Fixes #23984
Thanks @yecril71pl! :rocket:
From identifying the `ParseBool`-calling options in `WebHostOptions` and given that `ParseBool` is a `true`/`1` **string** for `true` (**bool**) and `false`/`0`/anything **string** for `false` (**bool**), this PR sets the potential and recommended&dagger; values.
&dagger;Recommended in the sense that a nonsensical/nonstandard value is interpreted as `false`. We don't need to call it out, but ...
```csharp
webBuilder.UseSetting(WebHostDefaults.DetailedErrorsKey, 
"Spare me the details, man! It's FRIDAY for crying out loud! 🎉🍻");
```
😆 Technically, that's ok. Then, it would reach code review, and you'd have to go find a new dev role. 🙈
* https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Abstractions/src/WebHostDefaults.cs
* …
=> Update bool value entries for host config

aspnetcore/mvc/controllers/actions.md
I understand that from the library POV a non-public class is non-instantiable.  However, when I look at my code, I can instantiate the controller class all right, so I cannot see the problem.  Also, there is no warning from the library when a controller class is non-public, so there is no way to discover the problem at run time.  I hope this small amendment will do no harm.
=> A controller is an instantiable public class

aspnetcore/mvc/views/working-with-forms.md
The page already has a link to the `<form />` html tag. Users reading this document are probably more interested in the API docs, I know I am.
=> Reference to FormTagHelper API docs

aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md, aspnetcore/security/authentication/scaffold-identity.md
Fixes #23993
Rick ... I'll number these so that you can easily respond to each .......
1. Let's eliminate the unnecessary division between existing/new scaffolding Blazor Server section ... for now anyway until I perform additional testing+validation. It's the same dialog, and we weren't describing anything in particular about apps that already have Identity in place and just need to add some Identity pages via the scaffolder.
1. Let's eliminate the `Program.cs` (formerly `Startup.cs`) aspect for Blazor Server. It doesn't seem helpful because the scaffolder adds the required services (it did here in testing), and there's nothing to add for an Identity-enabled Blazor Server app that's scaffolding in pages for custom dev markup/code. It simplifies the coverage, thus cuts maintenance …
=> Blazor Identity scaffolding

aspnetcore/migration/50-to-60-samples/samples/Web6Samples/Program.cs
Fixes typo: `implemenation` => `implementation`
=> Fix typo: implemenation => implementation

aspnetcore/blazor/components/control-head-content.md, aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #24034
Internal Review Topics:
* [*Control \<head> Content* article (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-6.0&branch=pr-en-us-24035#control-head-content-during-prerendering)
* [*Prerendering and Integration* article (the NOTE with cross-link is in multiple sections)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-3.1&branch=pr-en-us-24035)
I recommend **_very careful review_** 😨. These overlapping cases and permutations of scenarios are tricky to describe.
I assume that a RP/MVC app that's integrating Razor components into pages and views from a hosted WASM app **_can have the component set \<head> content_**. That might be …
=> Layout and prerendered head content

aspnetcore/web-api/handle-errors.md, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Controllers/ErrorsController.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/HandleErrorsSample.csproj, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Program.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Snippets/HttpResponseException.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Snippets/HttpResponseExceptionFilter.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Snippets/Program.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/Snippets/SampleProblemDetailsFactory.cs, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/appsettings.Development.json, aspnetcore/web-api/handle-errors/samples/6.x/HandleErrorsSample/appsettings.json
Fixes #23537.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0&branch=pr-en-us-24066).
=> Update Handle Web API Errors to 6.0

aspnetcore/fundamentals/configuration/index.md
Current state wrong line highlighted. Change highlights the following correct line in code. 
builder.Configuration.AddEnvironmentVariables(prefix: "MyCustomPrefix_");
=> Fix for correct code highlighting in doc

.vscode/settings.json, aspnetcore/blazor/security/index.md
Fixes #24052
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/index?view=aspnetcore-3.1&branch=pr-en-us-24113#resource-authorization)
Javier ... Best if you put an 👁️ on this. I've hacked up a simple, fully-working example.
**UPDATE (12/1)**: Javier ... I'm going ahead with this. I'll take community feedback on it. 
Delta from [your recommendation](https://github.com/dotnet/aspnetcore/issues/33958#issuecomment-977910725) for `Resource="@(routeData)"`. Seems like `Resource="@routeData"` works, so that's what's on the PR. I'm 👂 if I made a mistake there 🙈.
Setting this up only for 5.0 or later, as [`Resource`](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.components.authorization.authorizerouteview.resource) …
=> Resource authorization

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md, aspnetcore/fundamentals/host/generic-host.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/tutorials/build-a-blazor-app.md, aspnetcore/tutorials/signalr-blazor.md
Fixes #23662
I found two main docs with **Ctrl** keys in them, and I make the updates in them along with the Blazor doc updates.
=> macOS Command key

aspnetcore/fundamentals/middleware/index.md
Fixes #23527
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0&branch=pr-en-us-24164#middleware-code-analysis)
=> add link to code analysis to middleware /3

.github/workflows/merge-live.yml
This adds a manual GitHub Actions workflow to create a PR that merges from main to live.
I've [tested this in a fork](https://github.com/serpent5/dotnet-AspNetCore.Docs/actions/runs/1531727795), where it [works well](https://github.com/serpent5/dotnet-AspNetCore.Docs/pull/3), so I'd like to bring it in here. I've deliberately kept this as simple as it can be for now, with scope for more automation, etc, going forward.
=> Add GitHub Workflow for Merge to Live

.github/workflows/merge-live.yml
This repo is more restrictive than the fork I created, so we need to add explicit permissions for writing PRs.
=> Add permissions for merge-live GitHub Workflow

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/toc.yml
Fixes #24185
We'll decide later if we want to update the filename and UID to match. It's actually more likely that we'll split out the Navigation Manager and NavLink component bits into a *Navigation* topic to appear immediately after the *Routing* topic ... and then the *Routing* topic will get its old name back. Therefore, the update on this PR is merely cosmetic for the time being (title and ToC entry text).
=> Cosmetic rename of Blazor Routing topic

aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md
Explain that if the [page referenced by an anchor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.anchortaghelper.page) does not exist, a link to the main page will be generated.  No warning will be produced.
=> Anchor: What if asp-page does not exist

aspnetcore/fundamentals/environments/6.0sample/EnvironmentsSample/Properties/launchSettings.json
Fixes wrong environment name in multi environment launch settings documentation sample.
The launch profile is named `EnvironmentsSample-Production` so i guess the environment should also be `Production` and not `Development`
=> Fixes wrong environment name

aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/performance.md
Fixes #24220
* Compression is already covered in the perf topic, as is invariant globalization.
* Let's use sections over additional-resource links but cross-link as much as possible to avoid duplicate coverage.
* Let's clean up one point along the way: Runtime relinking requires the installation of the build tools, so I clarify that point by placing that sentence on its own line (new paragraph) before describing automatic runtime relinking on publish and the glob/loc aspect.
=> Blazor performance/AOT/RR updates

aspnetcore/fundamentals/middleware/index.md
Fixes #24262.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0&branch=pr-en-us-24263#branch-the-middleware-pipeline).
=> Fix link to 6.0 MapWhen snippet

aspnetcore/tutorials/signalr.md
SignalRChat instead of RazorPagesMovie
=> fix folder name error

aspnetcore/host-and-deploy/health-checks.md, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/Extensions/SampleHealthCheckBuilderExtensions.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/HealthCheckPublishers/SampleHealthCheckPublisher.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/HealthChecks/SampleHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/HealthChecks/SampleHealthCheckWithArgs.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/HealthChecks/StartupHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/HealthChecksSample.csproj, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/Program.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/Services/StartupBackgroundService.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/Snippets/Program.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/Snippets/SampleDbContext.cs, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/appsettings.Development.json, aspnetcore/host-and-deploy/health-checks/samples/6.x/HealthChecksSample/appsettings.json
Fixes #24092.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0&branch=pr-en-us-24261).
Working notes on changes:
- Removed two sections:
- [Metric-based probe with a custom response writer](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#metric-based-probe-with-a-custom-response-writer): I don't think this offers anything in the context of health checks that's not already covered elsewhere in the topic.
- [Restrict health checks with MapWhen](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#restrict-health-checks-with-mapwhen): This looks like it would have never compiled, so I don't think it's serving any value.
- Removed …
=> Update Health Checks to 6.0

aspnetcore/blazor/index.md, aspnetcore/toc.yml
Fixes #24296
* Let's go ahead with this. I'd like to try and close out the new, little issues before taking a ⛄ *break* 🎁. WRT to addl reviews: I recommend **not** sweating it, as these are minimal updates and obtaining reviews is getting harder and harder these days.
* Swap the WASM and Server sections. We favor Server now and order doc content that way.
* Move the *Tutorials* node directly under the *Overview*.
* I'd like to place this NOTE **_under the opening paragraphs_** (but in the opening section). I think it would be disruptive to see it immediately under the title of the doc and above the *Welcome* remark. Let's at least welcome the reader and make these opening remarks before potentially having them depart for a tutorial.
=> Blazor quick start tutorial link

aspnetcore/fundamentals/servers/kestrel/http3.md
Fixes #23432.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-6.0&branch=pr-en-us-24304#limitations).
=> Link to specific UseHttps overloads

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md, aspnetcore/blazor/includes/package-reference.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md, aspnetcore/includes/package-reference.md, aspnetcore/test/middleware.md
Fixes #24265 
* Move the Blazor INCLUDE file to the main `includes` folder.
* Update Blazor links to the file.
* Add the INCLUDE to the Middleware Test doc that was updated earlier.
* Add a *quick* 🏃 remark on package versioning.
The Blazor docs have already shed all of their crappy `<PackageReference>` guidance in favor of this (much better imo) approach.
I deliberately kept ...
> \> [!NOTE]
> \> For guidance on adding packages to .NET apps, see the articles under *Install and manage packages* at \[Package consumption workflow (NuGet documentation)](/nuget/consume-packages/overview-and-workflow). Confirm correct package versions at \[NuGet.org](https://www.nuget.org).
... **_short-'n-sweet_** because this INCLUDE is injected around the docs in spots where we don't want to distract …
=> Add package INCLUDE

.github/workflows/merge-live.yml
Adds a scheduled trigger to open a merge-live PR [At 08:00 on every day-of-week from Monday through Friday](https://crontab.guru/#0_8_*_*_1-5). The time is UTC, so I think 8AM is a good starter, and I don't think it needs to run at weekends. We can still do it manually [here](https://github.com/dotnet/AspNetCore.Docs/actions/workflows/merge-live.yml):
Very much open to feedback on all of this. The next step is automated merge of the PR, but I have some investigation around status checks to do first.
=> Schedule automatic runs of merge-live

aspnetcore/web-api/handle-errors.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/23248
@Rick-Anderson, I think a simple warning messege will suffice. 
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0&branch=pr-en-us-24305).
=> Explicit http verbs are needed when OpenAPI support is enabled

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #24325
cc: @TanayParikh ... I'm going to go ahead with this and get it merged, as it's very *garden variety stuff* 🏡 that we can't get too deep into the weeds on ... deployment corruption could be caused by any number of things. Fortunately, this is much less common these days AFAICT. I angle the text along the lines of the concepts that I listed on the issue at #24325. If you have a concern with the guidance, ping me here for discussion and perhaps a patch PR later. 👂
=> Prior deployment corruption guidance

aspnetcore/blazor/components/control-head-content.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/security/content-security-policy.md
Fixes  #24237
Thanks @christianAtSuddath :rocket: and @damienbod 🚀!
I think we'll go ahead with this and get it merged on Friday. I want to sleep on it 🛌💤 and make a few more updates on Friday morning.
@damienbod ... I'd ***very much*** like to just go with a ✨ **_'use middleware'_** ✨ bit of guidance 😄 for the Blazor Server/hosted WASM scenario. I don't want to get into the weeds on how far a dev might want to take that (a la what you cross-linked). It's really just middleware under-the-covers. I do have a remark here tho that they can create a class and use an extension method to call middleware and cross-link the appropriate doc in the main doc set. We can't link 3rd party for this. If the blog or the GH repo is something that you/Andrew want to surface, we recommend Awesome Blazor. We …
=> Header control in Blazor apps

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/fundamentals/servers/kestrel/diagnostics.md
Fixes #21939
cc: @Rick-Anderson ... For the Kestrel diagnostics doc (`fundamentals/servers/kestrel/diagnostics.md`), a build suggestion popped up ...
> Invalid value for 'ms.author', 'soshir' is not a valid Microsoft alias.
I change it here to `riande`.
=> Surface error for lack of sticky sessions

.github/workflows/merge-live.yml
Instead of running merge-live on a schedule, we could have it open a PR anytime we push to `main`. We can check first to make sure one doesn't exist, so that we don't end up with loads of failed workflow runs.
cc @guardrex
=> Update merge-live to ensure a PR is always available

aspnetcore/fundamentals/minimal-apis/samples/todo/Program.cs
Utilize Microsoft.AspNetCore.Http.StatusCodes instead of integers for Produces() method of a endpoint mapping to utilize available convention within the AspNetCore framework.
Fixes #24360
=> Update Program.cs example for minimal-apis documentation

.repoman.yml
There's a new TH doc (Persist Component State TH) that can auto-map to me for ...
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md
=> GH repoman rules: Persist Component State TH doc

aspnetcore/blazor/file-uploads.md
* Duplicate the controller into each of the hosted WASM and Server pivots because an additional namespace is required for the controller to access the `UploadResult` class in the **`Shared`** project.
* Call out that the **`Client`** project needs the import for the **`Shared`** project as a dedicated paragraph because the current sentence that describes it is too easy to miss buried in the middle of a paragraph.
=> Blazor file uploads example update

aspnetcore/blazor/debug.md
Fixes: https://github.com/dotnet/aspnetcore/issues/38382
=> Blazor Debugging Launch.json `url` property documentation

aspnetcore/grpc/performance.md
Note that the gRPC example that is linked to hasn't been merged yet - https://github.com/grpc/grpc-dotnet/pull/1529
=> Add streaming examples to gRPC perf docs

aspnetcore/fundamentals/configuration/index.md
setx command does not use equal operator for assignment. Attempting this will result in an error. Instead you simply use a space.
=> Fix setx examples

aspnetcore/tutorials/first-web-api.md
Update dotnet-aspnet-codegenerator version to stable 6.0.1
Fixes #24418 
dotnet-aspnet-codegenerator --version 6.0.0-preview.7.21413.1 causes issue when scaffolding. Using Latest stable version of dotnet-aspnet-codegenerator will fix the issue.
=> Update dotnet-aspnet-codegenerator version to 6.0.1

aspnetcore/blazor/file-uploads.md
Fixes #24381
These updates are only in the 5.x versioned content of the topic.
cc: @TanayParikh
=> Blazor framework file size limit for 5.x

aspnetcore/fundamentals/middleware/write.md, aspnetcore/fundamentals/middleware/write/6sample/WebMiddleware/MyCustomMiddleware.cs
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/24434
@Rick-Anderson, did some rearrangements. I think it will better explain to the user which `Use` overload should be used for performance.
please add your suggestions also :)
=> review and clean up write middleware

aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs
Current code fails building because of breaking change in .NET 6. This changes the code sample to a correct .NET 6 variant. See #24452
=> Fixes #24452 Minimal API webroot change sample

aspnetcore/release-notes/aspnetcore-6.0.md
=> .NET MAUI release notes entry

aspnetcore/blazor/host-and-deploy/configure-linker.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/index.md, aspnetcore/blazor/security/content-security-policy.md, aspnetcore/blazor/webassembly-native-dependencies.md
Fixes #24443
@markarnolditpro ...
* It seems that runtime relinking is a **_publish-in-Release config_** gesture based on the size of compiled output in testing here. I've made a note on a tracking issue to confirm this with the PU ("product unit") later when they're all back from vacation. For now, I feel good enough about it to clarify it in the doc.
* This will cross-link the MSBuild properties and targets file *temporarily* until we get .NET Core doc set article updates. Also, it calls out the open issue to provide that coverage in order to ward off additional requests here. I think you're the third person to ask.
* I don't think we need to say anything specific at this time about `WasmBuildNative`. If you were to get that error regularly and could describe exact repro steps, it would …
=> Mono/WASM MSBuild property guidance

aspnetcore/web-api/index.md, aspnetcore/web-api/index/samples/3.x/Startup.cs
Add automatic 400 response logging code samples, instead of pointing the end-user to our issue tracking website, as proposed in https://github.com/dotnet/AspNetCore.Docs/issues/12157
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0&branch=pr-en-us-24463).
=> Add automatic 400 response logging code samples

aspnetcore/blazor/debug.md
Fixes #24479
Previously, a project created by "dotnet new" and opened in VS Code was unable to debug.  Specifically, when the debugger was started, a new browser window would open "about:blank, wait for 30 seconds, and then close.  The issue was that:
- The launchSettings.json generated by the "dotnet new" command uses a random port number.
- The launch.json file generated by VS Code omits the "url" parameter (the default value is "https://localhost:5001").
The fix is to add the "url" parameter to launch.json.
Also, I merged the "Example launch configurations" section with the relevant steps above.  This makes it easier for users to find the appropriate config, as well as simplifying long-term maintenance of the documentation.
=> Improve launch.json examples

aspnetcore/performance/caching/memory.md
Fixes #24464
@JunTaoLuo I know you don't own this doc now, but was this your intention?
=> Don't use external input as cache keys.

aspnetcore/tutorials/razor-pages/model.md
[Internal review - link to edited section](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&branch=pr-en-us-24532&tabs=visual-studio-mac#create-the-initial-database-schema-using-efs-migration-feature)
Summary changes:
VS for Mac 2022 Preview for .NET 6.0 has recently changed so EF CLI Tools are not included, but rather need to be added. Updated the Model topic to reflect this.
Fixes #23414
=> Razor tutorial update for additional .NET 6.0 VS for Mac EF changes - 23414

aspnetcore/security/authentication/certauth.md, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/CertAuthSample.csproj, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Program.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/ICertificateValidationService.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/Program.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/SampleCertificateThumbprintsValidationService.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/SampleCertificateValidationService.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/SampleHttpService.cs, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/appsettings.Development.json, aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/appsettings.json
Fixes #23229.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0&branch=pr-en-us-24550).
I've created a 6.0 sample project and moved all inline code into there. I've left the content alone as much as I can, changing only references to `Startup` and updating the code for 6.0. I've also dropped the first section that discusses using `HttpClient` directly, as I think the section that follows covers the same details without having to worry about the lifetime of `HttpClient` et al.
=> Update Certificate Authentication to 6.0

aspnetcore/mvc/views/tag-helpers/intro.md
Fixes formatting issues. The [current version](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0#tag-helper-initializers) is a bit broken.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0&branch=pr-en-us-24566#tag-helper-initializers).
=> Fix formatting in Tag Helper Initializers

aspnetcore/test/integration-tests.md
In aspnetcore 6, both of the code snippets mentioned are needed in order to get the Program class imported in a test project.
Initially I only added the changes shown for `.csproj`, but after following along to the BasicTests example I still got this error when writing the constructor: `Inconsistent accessibility: parameter type 'WebApplicationFactory<Program>' is less accessible than method 'MyControllerTest.MyControllerTest(WebApplicationFactory<Program>)'`.
Adding the `public partial class Program { }` change fixed that error.
***EDIT by @Rick-Anderson*** [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0&branch=pr-en-us-24274#basic-tests-with-the-default-webapplicationfactory)
=> fix instructions for referencing internal classes

aspnetcore/fundamentals/static-files.md, aspnetcore/fundamentals/static-files/samples/6.x/StaticFilesSample/Program.cs
Fixes #24559.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0&branch=pr-en-us-24576#serve-files-from-multiple-locations).
=> Show example of multiple UseStaticFiles

aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
Blazor WebAssembly apps still require the DLLs even when AOT compiled.
This security statement also seems to indicate that Blazor WebAssembly's use of DLLs is a security risk, when there are really multiple mitigations in place, like the browser security sandbox. So I've toned down the warning accordingly to instead focus on collaborating with the network admin.
=> Clarifying security warning and removing statement about AOT and DLLs.

aspnetcore/blazor/components/cascading-values-and-parameters.md
CascadingValue causes components to be re-rendered if the value changes. We don't currently document this.
=> Add a note about subscriptions triggered thru CascadingValue

aspnetcore/security/anti-request-forgery.md
Fixes #24592
the page contains a `&dagger;` ==> &dagger; <== which is probably not render as it should (or at least it's not using a valid emoji if that was intended)
Repro:
* Ctrl+F
* look for In this context
* the characted on the left:
=> remove &dagger; from anti-request-forgery.md

aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/signalr/scale.md, aspnetcore/toc.yml
=> Blazor Linux hosting

aspnetcore/fundamentals/dependency-injection.md
Scoped services can be injected into the middleware's InvokeAsync method (as the previous point mentions) even if the middleware is NOT Factory-based.  Injection into the constructor, on the other hand, throws exception.  So it is the scoped service's injection into constructor -- without throwing exception -- that is allowed by Factory-based middleware. This is also explicitly mentioned in the detailed topic on Factory-based middleware here: 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-6.0#:~:text=IMiddleware%20is%20activated%20per%20client%20request%20(connection)%2C%20so%20scoped%20services%20can%20be%20injected%20into%20the%20middleware%27s%20constructor.
=> Injection into constructor allowed by Factory-based middleware

aspnetcore/migration/1x-to-2x/index.md
The package `Microsoft.Extensions.CommandLineUtils` has been [retired](https://github.com/dotnet/extensions/blob/release/2.1/README.md).
=> 1x-to-2x: about CommandLineUtils

aspnetcore/test/hot-reload.md
Using .NET 6 on macOS, we can see that `dotnet watch` uses Ctrl+R, not Cmd+R:
```
$ dotnet watch
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
```
=> hot-reload: macOS also uses Ctrl+R

aspnetcore/security/authentication/identity.md
The wrong application name WebAppAuth is used twice in CLI commands instead of correct name WebApp1, this puts the correct name.
=> fix wrong application name WebAppAuth with WebApp1

aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program3.cs
The text leading into the example is ...
> If you prefer to send a permanent redirect status code when the app is in a non-Development environment, wrap the middleware options configuration in a conditional check for a non-Development environment.
The earlier version (5.x) is correct.
=> Code patch

aspnetcore/blazor/file-downloads.md, aspnetcore/tutorials/razor-pages/model.md
Fixes #24521
Thanks @ylr-research! :rocket:
* Recommend that we show the procedure for opening a new tab.
* To cover security aspects for older browsers, I include a bit on the Referrer Policy, but I need verification on the sanity of the remarks and example.
* There are a few other *NITs* on the PR, and I'll be back for a broader UE pass on this topic later.
For the following remark ...
> At this point, the file download is triggered, and it's generally safe to revoke the temporary object URL by calling \[\`revokeObjectURL\`](https://developer.mozilla.org/docs/Web/API/URL/revokeObjectURL) on the URL.
I'm not keen on the "generally" part without further explanation. What does "generally" mean in this context? I think we should say **_when_**/**_how_** it might be unsafe ... or strike the …
=> Blazor file download updates

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/includes/js-collocation.md
Fixes #24637
Thanks @Ricardoaraujo00! :rocket: ... It's best to cross-link for the fully working example with a quick description of the changes for the example. This clarifies the points that we discussed on the issue, and I found that the two Blazor JS interop topics need a cross-link to the new colocation coverage. We'll take further feedback on this and update it again if needed. Thanks for your feedback on this.
=> Improve JavaScript colocation guidance

aspnetcore/host-and-deploy/linux-apache.md, aspnetcore/host-and-deploy/linux-nginx.md
Fixes #24618
Thanks @nachiketrss! :rocket:
For this PR ...
* The guidance remains focused on local execution ("If the app is run locally ...") with the improvement that it's for the "Development environment" with a cross-link.
* Maintains the guidance on the insecure URL config for `launchSettings.json`.
* Fleshes out the guidance on removing the redirection middleware. Since the cross-linked content isn't explicit for this scenario, I place it here in the articles.
* Cross-links the *Environment* topic for additional information.
* Linux-Apache and Linux-Nginx articles receive the updates.
Thanks for your issue and discussion on this.
=> Improve Linux deployment guidance

aspnetcore/includes/RP-MVC/validation-net6.md
Added the highlight query when displaying the first code block or snippet in [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-6.0) section of docs.
IDK how the highlight query works so I added the line numbers of the line to highlight relative to that region, `i.e FinalSnippet`, please correct me if that's wrong.
And if someone could please also _explain how to highlight line(s) in different regions_ since it's not mentioned in the [Contributing Guidelines](https://github.com/dotnet/AspNetCore.Docs/blob/main/CONTRIBUTING.md#code-snippets) so that I could add some more similar changes 'cuz those _highlights are really required for some one like me who is following along the tutorial in the docs_.
=> Highlighted code snippets

aspnetcore/fundamentals/servers/kestrel/endpoints.md, aspnetcore/fundamentals/servers/kestrel/samples/6.x/KestrelSample/Snippets/Program.cs
Fixes #24604.
Fixes #21799.
Fixes #23244.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0&branch=pr-en-us-24640).
Updated sample code for 6.0, explained random ports as described [here](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#tgp), and fixed outstanding issues as linked above.
=> Update Kestrel Endpoints to 6.0

aspnetcore/blazor/fundamentals/dependency-injection.md
Per https://github.com/dotnet/aspnetcore/pull/39445#discussion_r787781819 ...
Pranav, *keep/update this? ... or close the PR (e.g., it's too weedy ... too rare)?* 👂 
Currently, this is only for the 6.0 or later versions due to NRT enforcement for C# 8.0 or later. If we keep/modify this, let me know if you feel that 3.1/5.0 should have this guidance as well. 👂
=> Injected properties are expected to be available

aspnetcore/fundamentals/servers/kestrel/options.md, aspnetcore/fundamentals/servers/kestrel/samples/6.x/KestrelSample/Snippets/Controllers/SampleController.cs, aspnetcore/fundamentals/servers/kestrel/samples/6.x/KestrelSample/Snippets/Program.cs
Fixes #23653.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-6.0&branch=pr-en-us-24688).
Updated all code samples to 6.0, and moved inline snippets out to code references. As a couple of the defaults we call out don't match the latest defaults in the code, I decided to drop specifying defaults in general. I concluded that these are all shown and accurate in the API references for each property, so they're very easy to find out for the curious reader, but I can add them back in with the latest correct values if that's preferred.
=> Update Kestrel Options to 6.0

aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md
If the referenced page does not exist, a link to the current page is generated.
This is a self-correction; the previous wording was correct only if the current page was in fact the main page.
=> Anchor link: what if page does not exist

aspnetcore/blazor/globalization-localization.md
In Blazor Server, it is not a requirement that the `CurrentCulture` and `CurrentUICulture` are set to the same value for resource based localizations to work, but in Blazor WebAssembly they must be set to the same culture or the `SatelliteResourcesLoader` will not load the resources that Localizers are expected to read.
A quick note to this effect for the Blazor WebAssembly section of this doc could save someone else the trouble of figuring this out.
=> Clarify requirement for localization

aspnetcore/tutorials/razor-pages/validation.md
The section talks about what the DataAnnotations namespace provides. It makes sense to make it a link to the DataAnnotations reference page so it's easy to take a look at what else it provides.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-6.0&branch=pr-en-us-24762&tabs=visual-studio).
=> Add Link to DataAnnotations Reference Where It's Mentioned

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #24790
Thanks @olivertrampenau! :rocket: ... All of the topics in the security node of docs are due for a major overhaul. All of these examples will probably change to use placeholders instead of actual examples. Instead of `example.read` and `example.write`, these will probably become "`{SCOPE 1}, {SCOPE 2}, ..., {SCOPE X}`" ... or something like that ... with a line underneath them that says what the placeholders are ...
> In the preceding code example, the placeholder list `{SCOPE 1}, {SCOPE 2}, ..., {SCOPE X}` is one or more scope strings separated by commas. ... *AND ADD THE AAD EXAMPLES TO THAT*.
... something like that. Anyway ... the bit here on the PR is good for the time being. Thanks again for commenting on the article.
=> Clarify generic scopes and include AAD examples

aspnetcore/fundamentals/http-context.md
Addresses #7721.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0&branch=pr-en-us-24806).
This adds sections for the supported scenarios described in https://github.com/dotnet/aspnetcore/issues/27392#issuecomment-900756212. There's more work needed to explain discouragement of `IHttpContextAccessor`, which I think is for a follow-up PR.
=> Add scenarios for accessing HttpContext

aspnetcore/security/authorization/secure-data.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0&branch=pr-en-us-24830).
=> Replace /dotnet/api with xrefs in Secure Data

aspnetcore/mvc/views/working-with-forms.md
Explain how to override the default caption in the [Label tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms#the-label-tag-helper)
=> Label tag helper: override the default caption

aspnetcore/razor-pages/filter.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-6.0&branch=pr-en-us-24843).
=> Replace /dotnet/api with xrefs in Razor Pages Filters

aspnetcore/host-and-deploy/docker/building-net-docker-images.md, aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md
Fix some (deep) links against docker docs.
One of them is still invalid (`Docker for Windows: What to know before you install`) as it seems that it has been removed in the latest docs.
I don't know how everything is structured (working) on their end regarding the docs but I could find those (old?) resources over here:
https://docs.docker.com.xy2401.com/docker-for-windows/install/#what-to-know-before-you-install
=> Fix docker docs (deep) links

aspnetcore/blazor/components/cascading-values-and-parameters.md, aspnetcore/blazor/components/index.md, aspnetcore/blazor/forms-validation.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/performance.md, aspnetcore/blazor/samples/3.1/BlazorSample_WebAssembly/Shared/MainLayout.razor, aspnetcore/blazor/samples/3.1/BlazorServerEFCoreSample/BlazorServerDbContextExample/Shared/GridWrapper.razor, aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Shared/MainLayout.razor, aspnetcore/blazor/samples/5.0/BlazorServerEFCoreSample/BlazorServerDbContextExample/Shared/GridWrapper.razor, aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Shared/MainLayout.razor, aspnetcore/blazor/samples/6.0/BlazorServerEFCoreSample/BlazorServerDbContextExample/Shared/GridWrapper.razor
Fixes #24769
Years ago, I performed a similar set of updates to make how we assign to parameters consistent in code examples. While I was working on something else today, I noticed that *a few sneaky devils* 😈 *are back!* This PR seeks to fix them up.
Included here is an effort to fix `this` keyword assignments, which I don't think are fundamentally different to anything else. Let me know if I'm mistaken on that. We've had (and I've seen outside of the doc set) any of the following. The last one is consistent with the earlier decision to quote and `@`-prefix these, and that's what's on this PR ...
* `<Something Value=this />`
* `<Something Value="this" />`
* `<Something Value="@this" />`
What about a boolean tho? Razor seems happy with `@true`. Doesn't the **_second one_** 👇 lend itself …
=> Param attribute value @-prefix convention

aspnetcore/signalr/configuration.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&branch=pr-en-us-24859&tabs=dotnet).
=> Replace /dotnet/api with xrefs in SignalR Configuration

aspnetcore/fundamentals/host/web-host.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0&branch=pr-en-us-24885).
=> Replace /dotnet/api with xrefs in WebHost

aspnetcore/toc.yml
Thanks @serpent5 for catching these.
It seems like these were here earlier and that an update ... moving content, perhaps ... knocked them out.
OH! Wait! NO! I know what ... or **_WHO_** ... did this. **_This is IT!_** It's the coded signal to their operatives!
*They are among us!* 😆 
Seriously tho ... These have been **_well cross-linked_** into Blazor docs where needed. The major downside to my missing them is when readers strictly read topics in order top-to-bottom from the ToC. Thanks again, @serpent5 ... *great catch!*
=> Surface two Blazor topics in the ToC

aspnetcore/mvc/models/validation.md, aspnetcore/mvc/models/validation/samples/6.x/ValidationSample/Snippets/Controllers/MoviesController.cs
Fixes #24579.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0&branch=pr-en-us-24909).
=> Add MVC example for ModelState.IsValid

aspnetcore/test/integration-tests.md
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0&branch=pr-en-us-24938).
=> Replace /dotnet/api with xrefs in Integration Tests

aspnetcore/mvc/models/file-uploads.md
The following sentence:
> ...`FileHelpers` class demonstrates **a** several checks for...
Should read:
> ...`FileHelpers` class demonstrates several checks for...
=> Fix typo in file-uploads.md

aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config
I had to remove the `.wasm` file extension because IIS was complaining about duplicate entries in order to make it work with `br` and `https`.
Others also reported this issue on stackoverflow:
https://stackoverflow.com/a/69888016
https://stackoverflow.com/a/70967738
=> Remove .wasm file extension before redefining it

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #24926 
Thanks @jerrevds! :rocket: ... I'll ping Tanay to look, too, but see if the additional update here makes sense to you. There's a duplication of guidance for the `Pages/_Host.cshtml` page that I'm striking in the process.
Tanay ... This is Javier's original code for the scenario and then updated from https://github.com/dotnet/aspnetcore/issues/37713#issuecomment-961838175 and his following answer to my question there.
However, this looks correct. In the *Prerender and Integrate* topic, we guide adding the Component TH to `Pages/_Host.cshtml` ...
```razor
<component type="typeof(App)" render-mode="WebAssemblyPrerendered" />
```
... in the **_NON-auth case_**. Then, the WASM security doc should just pick up from there.
Cross-reference: **Step 4 of** …
=> Fix code example

aspnetcore/blazor/security/webassembly/index.md, aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/routing.md, aspnetcore/mvc/advanced/app-parts.md, aspnetcore/mvc/controllers/filters.md, aspnetcore/release-notes/aspnetcore-6.0.md, aspnetcore/tutorials/first-mongo-app.md, aspnetcore/tutorials/getting-started-with-NSwag.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/web-api/index.md
We have a few references to `System.Web.` that should be `Microsoft.AspNetCore.`. This PR addresses that, but excludes one I found in Blazor. I've emailed @guardrex about the Blazor issue, but I can add that fix in here, so let me know.
=> Replace errant references to System.Web.

aspnetcore/blazor/host-and-deploy/index.md
Fixes #25069
Thanks @DrLeh! 🚀 ... This should prompt developers to place it early in the request processing pipeline. I won't be too specific on it because it really only needs to be set for downstream middlewares that interact with the request path. I think this will prompt devs to just get it before the most important one ... *Routing Middleware*.
=> UseBasePath placement in processing pipeline

aspnetcore/blazor/tutorials/signalr-blazor.md, aspnetcore/blazor/tutorials/signalr-blazor/samples/6.0/BlazorServerSignalRApp/Hubs/ChatHub.cs, aspnetcore/blazor/tutorials/signalr-blazor/samples/6.0/BlazorServerSignalRApp/Program.cs
Fixes #25074
Thanks @smiller7812! :rocket: ... This renames that namespace in the Blazor Server tutorial+sample to drop the "**`Server`**" segment that's present in the hosted WASM version of the tutorial+sample. I won't bother fixing the earlier versions. I'm just going to patch the present release on this one. The earlier versions still work ... devs just copy-'n-paste the code out of the topic instead of using the VS features to set the namespace for them. Most of our readers use the latest version of the SDK and doc. If more feedback comes in later, I'll reach back into the older 5.0 tutorial+sample and make similar updates. I'll take these updates live immediately after this PR merges, so the updates will appear in the live topic generally within 20 minutes (for English-US, localized …
=> Update Blazor-SignalR tutorial

aspnetcore/grpc/code-first.md, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/GrpcGreeter.csproj, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/Program.cs, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/Services/GreeterService.cs, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/Startup.cs, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/appsettings.Development.json, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeter/appsettings.json, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeterClient/GrpcGreeterClient.csproj, aspnetcore/grpc/code-first/samples/6.x/GrpcGreeterClient/Program.cs, aspnetcore/grpc/code-first/samples/6.x/Shared/Contracts.cs, aspnetcore/grpc/code-first/samples/6.x/Shared/Shared.Contracts.csproj
Prep for #25071 by creating a new moniker range in the content for 6.x.
[Internal review, verify versions intact](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/code-first?view=aspnetcore-6.0&branch=pr-en-us-25073).
=> v6 prep code-first gRPC Services

aspnetcore/tutorials/first-web-api.md
Fixes #25088.
Adds guidance for NuGet package references and removes `--prerelease` from .NET 6 instructions.
=> Add Package Reference guidance to First Web API

aspnetcore/mvc/models/model-binding.md
=> Adding additional comment about FromServices optionality

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
The Dockerfile examples uses .NET 5.0 image when viewing docs for .NET 6.0.
This PR adds the correct image versions for version 6.0.
=> Bump framework version number in Dockerfile examples

aspnetcore/blazor/file-downloads.md
Fixes #24887
Thanks @bisaacson100! :rocket:
Tanay ... I think we'll need to do more than what I currently have on the PR. A couple of things cropped up as I was adding a simple *"watch out for CORS ... and see this"* remarks ...
1. Did this topic (on downloads) inadvertently receive a copy of the *File streams* section in the uploads topic? Even if the remarks should be here, can that first sentence ... perhaps the second sentence, too ... be more specific as to what it's explaining in this context (i.e., downloads)?
> \#\# File streams
>
> In Blazor WebAssembly apps, file data is streamed directly from .NET code into the browser. In Blazor Server apps, file data is streamed over the SignalR connection from .NET code into the browser.
1. I think we need to scope the whole topic better. …
=> Add File Downloads topic CORS guidance

aspnetcore/blazor/hybrid/routing.md, aspnetcore/toc.yml
Addresses #24956
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-6.0&branch=pr-en-us-25130)
Notes
* These will be *rough* at first. I'll circle around later for niceties like API doc cross-links (when available), enhanced descriptions, fully-working, cut-'n-paste code examples, etc.
* Although this PR doesn't include routing coverage, I think we'll probably be adding at least a brief remark that component routing (in a `BlazorWebView`) conforms to the coverage in the Blazor *Fundamentals* node topic on the subject with any caveats or *gotchas* 😈 that you want to call out. [*Fundamentals* topic on routing/nav](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/routing) ... **_Does it all apply to Hybrid scenarios …
=> Blazor Hybrid routing and nav topic

aspnetcore/host-and-deploy/iis/in-process-hosting.md, aspnetcore/host-and-deploy/iis/index.md, aspnetcore/includes/hosting-bundle.md, aspnetcore/migration/20_21.md, aspnetcore/migration/21-to-22.md, aspnetcore/migration/22-to-30.md, aspnetcore/migration/30-to-31.md, aspnetcore/migration/31-to-50.md, aspnetcore/migration/31-to-60.md, aspnetcore/migration/50-to-60.md
Fixes #24974
Fixes #24385
Per the PU issue discussion, call out for each migration topic (via an INCLUDE) that the dev should obtain and run the .NET Core Hosting Bundle Installer ...
* If the ANCM wasn't installed via a component install when the VS installer was run.
* If a prior version of the ANCM was installed. It perhaps hasn't changed (and won't change) every release, but this is wise guidance given that VS installer and the SDK installer don't check/auto-update the ANCM each release. It's a manual update.
WRT to the configuration guidance for ANCM being somewhat buried back in the *Advanced* topic, this adds a cross-link to the IIS *Overview* to surface it to readers.
=> ANCM migration

aspnetcore/fundamentals/host/web-host.md
Fixes #24890.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0&branch=pr-en-us-25092).
@Rick-Anderson How should we frame this article for 6.0? I've made minor tweaks to explain that `WebApplication` is recommended for web apps. Should I go through and update all the code to .NET 6/C# 10, or is this enough? I think it might be odd to show `WebHost` with a top-level program, if it's not an approach that we recommend now.
=> Update Web Host to 6.0

aspnetcore/signalr/javascript-client.md
=> Fix signalR reference links

aspnetcore/blazor/fundamentals/logging.md, aspnetcore/fundamentals/logging/index.md
Fixes #25172
cc: @qJake ...
* There's already coverage in the topic for using an `ILogger` to obtain dev tools console output, it's just too low in the topic's layout. Among other things on this PR, the organization is revised to move it UP to make it more apparent. I also flesh the content out a bit further.
* WRT the custom logger provider, the example that .NET docs show isn't good for us for Blazor WASM. It's a **_color console logger_** and thus isn't available as a demo in a dev tools console log. It correctly even blocks API per the "`browser`" OS platform. Therefore, I'm hatching up a full custom logger provider here on the PR that will work in a Blazor WASM scenario. I'm going to sleep on this one 🛌💤 and make some further improvements on Friday morning. In the meantime, you can …
=> Blazor logging topic enhancements

aspnetcore/blazor/components/lifecycle.md
Fixes #24863
Thanks @jkdba! :rocket: ... Looks like Pranav isn't on the PU team any longer. This should be fine tho given that it comes directly from reference source.
Ref source code comment:
> Components shouldn't need to implement IAsyncDisposable and IDisposable simultaneously,
> but in case they do, we prefer the async overload since we understand the sync overload
> is implemented for more "constrained" scenarios.
> Component authors are responsible for their IAsyncDisposable implementations not taking
> forever.
Cross-reference: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs#L1009-L1013
=> Clarify component disposal async+sync

aspnetcore/blazor/samples/3.1/BlazorSample_Server/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/3.1/BlazorSample_Server/Shared/index/Expander.razor, aspnetcore/blazor/samples/3.1/BlazorSample_WebAssembly/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/3.1/BlazorSample_WebAssembly/Shared/index/Expander.razor, aspnetcore/blazor/samples/5.0/BlazorSample_Server/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/5.0/BlazorSample_Server/Shared/index/Expander.razor, aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Shared/index/Expander.razor, aspnetcore/blazor/samples/6.0/BlazorSample_Server/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/6.0/BlazorSample_Server/Shared/index/Expander.razor, aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Shared/index/BadExpander.razor, aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Shared/index/Expander.razor
Fixes #23715
Thanks @omuleanu! 🚀
I haven't forgotten about #23704, but I'll have to get back to that one later. I'd like Steve to answer it, but I still can't ping him on that one at the moment given the workload of high priority issues. It's tracked, and we'll get to it *ASAP* 🏃.
WRT this update: You originally only called out the revised `Expander` (the "good" one) for the update mentioning that it's only used once in `OnInitialized` (as far as parent/children would be concerned). There's no problem applying the update to the "bad"-behaving one, too, so I do that here as well.
Also, I'd like to ask Tanay about this. We don't really sweat private getters. It's when the setter must be restricted that the access modification is particularly relevant. We might not want to make this change …
=> Update overwritten param examples

aspnetcore/grpc/protobuf.md
I was pleasantly surprised to see that Microsoft provides guidance on how to encode `decimal` in protobuf but I quickly realized that this encoding only supports a limited range of values with a limited precision. While this limitation probably is fine in most cases I think it should be mentioned so I added a warning and placed it after the note that hints at the superiority of this encoding to contextualize it a bit and also help the "copy-paste developer" to better understand the encoding at a glance.
=> Add warning about limited range of decimal encoding

aspnetcore/web-api/index.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0&branch=pr-en-us-25302)
It seems like the word "request" was used instead of "response" in these two places.
=> Fix request-response mixup

aspnetcore/security/data-protection/introduction.md
Fixes the DPAPI broken link  
Correct link: https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection
=> Fix DPAPI's docs link

aspnetcore/blazor/javascript-interoperability/index.md
Fixes #24646
Thanks @pm100! :rocket:
Notes ...
* I prefer **_not_** to demo a JSON converter in code given that the cross-linked doc for JSON converters looks good and includes such examples, including the factory approach.
* I'm interpreting remarks from PU discussions, so Tanay please check my remarks carefully ... *I might be making up my own .NET or Blazor features here!* 🙈😆 
* Don't sweat removal of the point-in-time remark+cross-link on `DateOnly`/`TimeOnly` for 7.0. Removal of that remark is tracked, so the task won't get lost.
* After we sort out the technical remarks and improve the guidance, I'll create the 5.0 and 3.1 versions of this at the end right before merging the PR.
* ❓ ... The main points from pm100's issue are covered by the PR (and including the extra bits of info …
=> Blazor JS intorop serialization section

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #25319
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-3.1&branch=pr-en-us-25346#abort-a-long-running-javascript-function)
Let's hope that we don't have another **_:t-rex: HackMess_**&trade; 🙈 here 😆.
=> Abort a long-running JavaScript function

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/forms-validation.md
... due to no longer being a free tool.
Rick, close this if you've already started a branch that includes this handful of Blazor doc references.
=> Drop Fiddler from Blazor docs

aspnetcore/test/hot-reload.md
This is just showing a blank bullet since the content is commented out. Since it's not linkable in the release notes, I suggest just removing the list item.
=> Remove commented out bullet

aspnetcore/tutorials/first-mongo-app.md
Fixes #25379
Deprecates PR #25390 
This commit updates all the references and hyperlinks from `mongo` to `mongosh` which is recommend by MongoDB version 5.x or newer.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&branch=pr-en-us-25399&tabs=visual-studio).
=> Update tutorial to use MongoDB Shell

aspnetcore/signalr/groups.md, aspnetcore/signalr/hubcontext.md, aspnetcore/signalr/hubs.md, aspnetcore/signalr/messagepackhubprotocol.md
We have a few "Related Resources" headers that should be "Additional Resources".
Internal Reviews:
- [Manage users and groups in SignalR](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-6.0&branch=pr-en-us-25419)
- [Send messages from outside a hub](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-6.0&branch=pr-en-us-25419)
- [Use hubs in SignalR for ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0&branch=pr-en-us-25419)
- [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-6.0&branch=pr-en-us-25419)
=> Replace "Related Resources" with "Additional Resources"

aspnetcore/blazor/hosting-models.md
Fixes #25454
Thanks @DrEsteban! :rocket:
The language used to describe the result of trimming the runtime can be removed from the *Hosting Models* topic, mostly because AOT is going to make the overall app larger ... much larger in most cases. The product unit claims that production apps will be around twice the size with AOT.
When runtime relinking is performed **_with disabling globalization_**, the *runtime size reduction* is probably significant for small apps. For large apps, I expect the size increase due to AOT to swamp any savings from runtime relinking. As you said, devs should test their apps to see what sort of size gains/reductions occur, taking into account if they can get away with dropping globalization and how much performance they gain on the client with AOT. The good …
=> Clarify build tool effect on size

aspnetcore/grpc/test-tools.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/test-tools?view=aspnetcore-6.0&branch=pr-en-us-25472)
Version prep, adding .NET 6 moniker copy.
Contributes to #25072
=> v6 Update Prep: Test gRPC Tools

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #25450
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-3.1&branch=pr-en-us-25465#call-net-generic-class-methods)
We don't currently carry coverage on this. This is a subject on the UE tracking issue that I've been hoping to reach for over a year now ... *and here it is!* 🎉👏 ... hopefully, it isn't another **_Rex Stinker_**&trade; 💩👃😆. 
The framework's `BasicTestApp` bits were used as a basis for this and can be found at ...
* [`InteropComponent.razor`](https://github.com/dotnet/AspNetCore/blob/main/src/Components/test/testassets/BasicTestApp/InteropComponent.razor)
* [`jsinteroptests.js`](https://github.com/dotnet/aspnetcore/blob/main/src/Comp …
=> Blazor JS interop with generic methods

aspnetcore/host-and-deploy/iis/in-process-hosting.md, aspnetcore/host-and-deploy/iis/in-process-hosting/6.0samples/Program.cs
Fixes #25325
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-6.0&branch=pr-en-us-25489) and [bottom of page here](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-6.0&branch=pr-en-us-25489#differences-between-in-process-and-out-of-process-hosting)
Replaced `ClaimsTransformer` with [`MyClaimsTransformation `](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0#extend-or-add-custom-claims-using-iclaimstransformation) because there is a .NET 1.1 class called [ `ClaimsTransformer` ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.claimstransformer?view=aspnetcore-1.1) and I don't …
=> .NET 6 in-proc-hosting /2

aspnetcore/grpc/test-tools.md, aspnetcore/grpc/test-tools/samples/5.x/Startup.cs, aspnetcore/grpc/test-tools/samples/6.x/GrpcGreeter.csproj, aspnetcore/grpc/test-tools/samples/6.x/Program.cs, aspnetcore/grpc/test-tools/samples/6.x/Protos/greet.proto, aspnetcore/grpc/test-tools/samples/6.x/Services/GreeterService.cs, aspnetcore/grpc/test-tools/samples/6.x/appsettings.Development.json, aspnetcore/grpc/test-tools/samples/6.x/appsettings.json
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/test-tools?view=aspnetcore-6.0&branch=pr-en-us-25480)
Fixes #25072 
Doc updated to .NET 6 
New app sample added for .NET 6 / VS 2022 + Latest packages
=> v6 udpate: Test gRPC services with gRPCurl: doc and samples

aspnetcore/release-notes/aspnetcore-6.0.md
Fixes  #22441
The tracking aspect of #22441 has been superseded by https://github.com/dotnet/AspNetCore.Docs/issues/24956, but we do need this update for the 6.0 release notes on the subject. I'll close out the issue with this update.
Along the way here, let's split out this Blazor Hybrid bit to an H2 section.
WRT the placeholders that I'm 🔪 out here ...
* Blazor WebAssembly packaging: Already covered in the *WebAssembly deployment layout* section. It was named kind'a funky on the PU roadmap, so it ended up as a dup for coverage here.
* Dynamically added root components: Also from the roadmap. There's a Blazor tracking issue for coverage. I'm dropping the placeholder here. If the tracked issue is addressed by the PU, then I'll circle back here and add something on it.
=> Update Blazor Hybrid section

aspnetcore/security/authentication/social/social-without-identity.md, aspnetcore/security/authentication/social/social-without-identity/samples/6.x/SocialWithoutIdentitySample/Snippets/Pages/Privacy.cshtml.cs, aspnetcore/security/authentication/social/social-without-identity/samples/6.x/SocialWithoutIdentitySample/Snippets/Program.cs
Fixes #10504.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-6.0&branch=pr-en-us-25509#save-the-access-token).
=> Show usage of SaveTokens

aspnetcore/security/cors/6.0sample/Cors/WebAPI/Program.cs
I see this a lot and I always think it's a bad practice. Not sure "b" is the right choice,but "builder" is definitely one of the few wrong choices.
=> confusing overriding of variables

aspnetcore/fundamentals/middleware/index/snapshot/Chain60/Program.cs
The referenced code sample had the same comment both before and after the call to await next.Invoke();
However, you CAN write to the response before you call next.invoke, so I updated the comment to reflect the proper control flow.
I did not create an issue for this, but can if needed.
=> Corrected Code Execution Reference

aspnetcore/security/cors.md, aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup2.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/Startup3.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupAllowSubdomain.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupDefaultPolicy.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupEndPointBugTest.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupEndPt.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupTest2.cs, aspnetcore/security/cors/3.1sample/Cors/WebAPI/StartupTestMyPolicy.cs, aspnetcore/security/cors/6.0sample/Cors/WebAPI/Program.cs, aspnetcore/security/cors/6.0sample/Cors/WebAPI/ProgramTest.cs, aspnetcore/security/cors/sample/Cors/WebAPI/Startup.cs, aspnetcore/security/cors/sample/Cors/WebAPI/Startup2.cs, aspnetcore/security/cors/sample/Cors/WebAPI/StartupMultiPolicy.cs, aspnetcore/security/cors/sample/Cors/WebAPI/StartupTest.cs, aspnetcore/security/cors/sample/Cors/WebAPI/StartupTestMultiPolicy.cs, aspnetcore/security/cors/sample/CorsExample4/Startup.cs
Follow-up for #25496.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0&branch=pr-en-us-25529).
=> Replace "builder" with "policy" for CORS snippets

aspnetcore/docfx.json, aspnetcore/migration/no-loc-test.md
Addresses #25187
Test 2:
* See if `globalMetadata` works as well as `fileMetadata` did in the first test.
* Confirm that `globalMetadata` merges with a topic-specific `no-loc` array. We'll just use our normal `no-loc` for the topic-specific array here.
The words used in the `globalMetadata` array aren't found anywhere in the doc set, so they won't interfere with normal topic localization ... 🤔 *well* ... unless the whole loc system **_blows up in my face and all loc goes out the window!_** 💣💥😨
=> Localization Test 2

aspnetcore/host-and-deploy/iis/development-time-iis-support.md
Fixes #23975
Removes 
from VS6+
@adityamandaleeka please assign a reviewer.
=> remove IIS Dev time support in VS /3

aspnetcore/docfx.json, aspnetcore/migration/no-loc-test.md
Addresses #25187
Test 3:
* See if a wildcard `fileMetadata` merges with a topic-specific `no-loc` array. We'll just use our normal `no-loc` for the topic-specific array here.
* The words used in the `fileMetadata` array aren't found anywhere in the doc set, so they won't interfere with normal topic localization.
=> Localization Test 3

aspnetcore/data/ef-rp/complex-data-model.md
Incorrect code block indentation has been fixed:
```diff
-         public ICollection<Instructor> Instructors { get; set; }
+ public ICollection<Instructor> Instructors { get; set; }
```
=> Fix indentation in complex-data-model.md

aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Error.cshtml.cs, aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Program.cs
@tothalexlaszlo please review
1. Get rid of nullable warning.
2. Use standard API.
=> Minor cleanup of using Minimal API as a Windows Service code /2

aspnetcore/mvc/controllers/routing.md
Fixes #25580.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0&branch=pr-en-us-25581).
=> Remove obsolete references to UseEndpoints

aspnetcore/fundamentals/configuration/options.md
Fixes #25579.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0&branch=pr-en-us-25596#ivalidateoptionstoptions-and-ivalidatableobject).
=> Note support in Options Validation for IValidatableObject

aspnetcore/blazor/debug.md
Fixes #25512
Are the problems that ...
* Debugger support introduces security risk?
* Copying output symbols introduces perf risk (of deployment ... larger app, slower deployment)?
I think it's good if we say why these should be disabled for published, production apps.
=> Blazor debug published, non-production, hosted WASM

aspnetcore/migration/50-to-60.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&branch=pr-en-us-25606&tabs=visual-studio)
Fixes #25550 
Clarified the changes made in the default appsettings for logging.
=> Migration topic fix: Logging defaults

aspnetcore/fundamentals/routing.md, aspnetcore/fundamentals/routing/samples/6.x/RoutingSample/Snippets/Controllers/HostsController.cs, aspnetcore/fundamentals/routing/samples/6.x/RoutingSample/Snippets/Controllers/ProductsController.cs
Fixes #16913.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0&branch=pr-en-us-25600#parse-url-paths-with-linkparser).
=> Document LinkParser.ParsePathByEndpointName

aspnetcore/blazor/hybrid/routing.md, aspnetcore/blazor/hybrid/security/index.md, aspnetcore/blazor/hybrid/tutorials/maui.md, aspnetcore/blazor/includes/net-maui-release-candidate-notice.md
Fixes #25432
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-6.0&branch=pr-en-us-25631)
* There were commits and additional discussion after your remarks at https://github.com/dotnet/maui/pull/5313#issuecomment-1078511479 on the PU PR, and I don't know if your remarks were updated for those followup commits/new design.
* Also, the remarks and discussion are kind'a cryptic in a few spots, such as for permutations for any scheme-based behaviors, static files in the app, and platform/OS behaviors.
* I recommend that you edit the PR directly to get the technical remarks right, then I'll circle around and sprinkle in a few commas and what-nots. You can see where I'm going with this: I suggest laying out the default behaviors …
=> Blazor Hybrid link handling behaviors

aspnetcore/test/hot-reload.md
Fixes #23864
cc: @Rick-Anderson ... We added a remark quite a while ago (with Pranav's approval) about Hot Reload not working with a WASM app with the debugger. Whatever the problem was, they seem to have fixed it in the intervening time ... it works fine here AFAICT, so I'm removing the condition ...
> In Visual Studio 2022 GA (17.0), Hot Reload is only supported when running without the debugger.
=> Remove Blazor WASM non-debug condition

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #24889
Thanks @abdollahkahne! 🚀 ... This will surface the common service registration approach the Blazor DI topic and cross-link it from the prerendering topic with a new step in the section that explains how to add prerendering support to a hosted WASM app.
As for RCL-based services and registration, there's no built-in feature for registration from the RCL AFAIK. You can open an issue with the product unit if you wish for Q&A/discussion with them on it ...
https://github.com/dotnet/aspnetcore/issues
If you open an issue with them, please CC: me. I'll re-open your original docs issue if they remark on anything worth describing the docs. You can CC: me on such an issue by adding the following to your opening comment ...
```
cc: @guardrex …
```
=> Hosted Blazor WASM common services

aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #25517
Thanks @sykesbPragmatics! :rocket:
> the example path has "_bin" as the final folder
IIRC, the paths changed between 3.1 and 5.0. IIRC, I tested this when it first came over from the engineers. I was able to make these updates and copy the new 6.0 or later guidance back to 5.0.
WRT 3.1 ... **_I'm going to_** 🔪 **_that._** That's too old to sweat maintaining for a few reasons, not the least of which is that I've dropped that framework locally. We're moving into .NET 7 territory now! 🏃 I tend to shed the oldest framework around the time that it's going to lose primary support.
One high-level reason not to get too deep into the weeds with this further (e.g., showing how to recompress the `blazor.boot.json` file via PS) is simply that this low-hanging fruit approach of changing …
=> Change published assembly extensions update

aspnetcore/security/authorization/secure-data.md
Page improperly uses AuthN terminology instead of AuthZ
=> AuthZ instead of AuthN

aspnetcore/toc.yml
Pointing this to the MS Learn landing page for Blazor. This endpoint is the one that I've already used in the Blazor Tutorials topic, so I think this is the only spot that requires an update. IIRC, this path (and endpoint in Learn pages) didn't exist when the first Learn module went up, so this pointed to that one tutorial. It's best for us to use the path endpoint because they have several experiences now.
=> Update MS Learn cross-link

aspnetcore/security/authentication/social/microsoft-logins.md
In the documentation about [Microsoft authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-6.0), there is a wrong punctuation at the end of the following sentence:
`You are now logged in using your Microsoft credentials:`
It should be:
`You are now logged in using your Microsoft credentials.`
=> Changed end-of-sentence punctuation from : to .

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
Update port mapping in Windows Container, I run the instruction on my Windows 10 machine and it works
***@Rick-Anderson  EDIT*** 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-6.0&branch=pr-en-us-25687#run-in-a-windows-container)
Fixes #25708
=> Update building-net-docker-images.md port mapping in Windows Container

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/rendering.md
Fixes #23084 
Thanks @szalapski! 🚀 ... Sorry for the delay. We tend to work through the backlog in H1 of each year following a hectic end-of-year release cycle and the holidays.
For the *Binding* topic, I'm adding a cross-link to the *Rendering* topic, where the subject is covered. I think it could go either way ... it could be an INCLUDES file shared in both spots; however, this subject is bit more in-the-weeds ... more implementation-ish ... than perhaps binding needs to cover directly. For most devs in most scenarios, the change detection should ✨ **_Just Work!_**&trade; ✨. The *Rendering* topic comes up fairly fast in the reading list down the ToC, so they'll get there PDQ anyway. Let's try this. If more feedback comes in on the *Binding* topic asking for more detail earlier, then …
=> Clarify change detection

aspnetcore/grpc/troubleshoot.md
Add new code snippet for aspnetcore-6.0 and later to relate to the default template with top-level statements.
Fixes #25783
=> Update gRPC troubleshooting for macOS 

aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/host-and-deploy/proxy-load-balancer.md
We plan to fix `UsePathBase()` in .NET 7 so it's unnecessary to call `UseRouting()` afterwards like we did for `UseExceptionHandler()`, `UseStatusCodePagesWithReExecute()` and `UseRewriter()` in .NET 6. https://github.com/dotnet/aspnetcore/pull/35426
For now, we want to document that explicitly calling `UseRouting()` is necessary for `UsePathBase()` to work with `WebApplication`.
Partially addresses: https://github.com/dotnet/aspnetcore/issues/38448
=> Add note to call UseRouting after UsePathBase

aspnetcore/blazor/fundamentals/handle-errors.md
there seem to be a change between the section names used in the .net 5 and .net 6 version of this doc.
this caused a broken link, fixed in this patch
=> Fixed broken link in aspnetcore/blazor/fundamentals/handle-errors.md

aspnetcore/blazor/security/index.md
I haven't reached UE passes on the security node of topics, but these underscores 😈 were troubling me this morning 😆.
=> Drop underscores from code examples

aspnetcore/blazor/fundamentals/environments.md
Fixes #24041
Thanks @buzzluck68! :rocket:
I'm labeling this as 'fixes' to close the issue, but the core of the issue is actually a `won't-fix` scenario for docs **_at the moment_** because there's a framework bug/feature that hasn't been addressed yet by the PU **_&mdash;OR&mdash;_** approaches described by the community on the [PU issue (dotnet/aspnetcore #25152)](https://github.com/dotnet/aspnetcore/issues/25152) are perhaps valid to address the scenario and the PU won't bless **one** of them as a recommendation.
This bug/feature is under investigation (or in design) over there for .NET 7, and I can't do much over here at the moment. It is OK to close the issue and pick it back up if they work the PU issue for .NET 7. We maintain dedicated doc tracking issues for .NET releases, so it …
=> Environments guidance updates

aspnetcore/grpc/troubleshoot.md
[Internal Review - Link to MacOS workaround section](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0&branch=pr-en-us-25798#unable-to-start-aspnet-core-grpc-app-on-macos)
Fixes #25742
Added clarification on the TLS workaround for MacOS
Cleaned up the moniker ranges so there are distinct copies of the topic that reflect each version rather than scattered ranges inline.
=> Troubleshoot gRPC - Clarified MacOS TLS workaround for 6.0

aspnetcore/fundamentals/host/platform-specific-configuration/samples/2.x/RuntimeStore/deploy.ps1, aspnetcore/fundamentals/host/platform-specific-configuration/samples/3.x/RuntimeStore/deployment/deploy.ps1
The `AppendToEnvironmentVariable` function in `Deploy.ps1` is incorrectly setting environment variables to `StartupDiagnostics` instead of the supplied value when setting instead of appending.
=> Fix Powershell script in /fundamentals/host/platform-specific-configuration sample

aspnetcore/fundamentals/logging/index.md, aspnetcore/fundamentals/logging/index/samples/6.x/TodoApiDTO/Pages/About.cshtml.cs
Fixes #25790
btw -- The PU (finally) settled on dropping underscores from fields in dev code in favor of the `this` keyword. However, that's beyond the scope here and will require a lot of repo-wide work to adjust.
Also, let me know if you prefer a different structured template var from `DT` ... that's nice because it's short and most will get what it means.
One more edit to this ... the message template should be stable.
=> Update logging example

aspnetcore/blazor/components/index.md
Fixes #25817
Thanks @LordScree! :rocket: ... I looked things over this morning ☕, and let's go with this as a general concept in the most general area that speaks to Razor syntax in components: Let's place a line in the *Components* overview topic in its *Markup* section. I use `@Body` as the example of an uppercase property. As you pointed out on the issue, the *Layouts* topic already indicates and cross-links the `LayoutComponentBase.Body` property, and I think that's all that that topic must cover given that this is a general Razor point.
=> Clarify Razor syntax casing

aspnetcore/fundamentals/configuration/index.md
Fixes #25626
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0&branch=pr-en-us-25686)
@Hoffs @chertby  please review.
=> host and app config, appsettings Urls takes precedence over ASPNETCORE /2

aspnetcore/fundamentals/static-files.md
Fixes #25848 . The image was showing the wrong value of max-age. As recommended, I am removing the image itself.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0&branch=pr-en-us-25850)
=> Removed the image from max-age example

aspnetcore/signalr/client-features.md, aspnetcore/signalr/hubs.md
Documenting new feature in SignalR added in https://github.com/dotnet/aspnetcore/pull/40811
[Review Url](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0&branch=pr-en-us-25796#client-results)
=> [SignalR] Document client results

aspnetcore/mvc/models/model-binding.md
[Internal Review - 5.x-3.x version](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0&branch=pr-en-us-25858)
Fixes #25856
Minor: Fixed H2 link for 5.0-3.1
=> Link fix in model-binding.md

aspnetcore/blazor/tutorials/build-a-blazor-app.md
Fixes #25877
Thanks @MichaelBrooks-Informatyx ... This briefly calls out that the automatic Blazor rerender triggers the Razor expression re-evaluation. I don't want to get into more detail on rendering behaviors than this (along with the other remarks here about the button that does have an event handler). The Razor syntax topic gets into the details and is cross-linked liberally from the Blazor node in various spots.
https://docs.microsoft.com/aspnet/core/mvc/views/razor
=> Clarify automatic Razor evaluation

aspnetcore/security/authorization/roles.md
Fixes #25906
The config is way down at the bottom. This PR moves it to the top, similar to the way that the policy-based auth topic does it ...
https://docs.microsoft.com/aspnet/core/security/authorization/policies
... but I do leave it as a section, just in case that the section is cross-linked from anywhere.
Also, this full fledged startup code example is overkill and not applicable to all app types. I recommend that we just shoot in a generic **_Code Nibblet&trade;_** 😆 ... with just the bit that they need to implement, the `AddRoles` call.
cc: @gregoryagu ... In addition to the Blazor doc cross-link improvement, this hopefully will help avoid your experience. *Future generations will thank us!* 😄
=> Promote and revise role auth config

aspnetcore/test/middleware.md
[Internal Review: Section: TestServer Limitations](https://review.docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-6.0&branch=pr-en-us-25896#testserver-limitations)
Fixes #22618
=> Add to TestServer limitations: TestServer ignores stream positioning

aspnetcore/grpc/httpapi.md
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-7.0&branch=pr-en-us-25920)
Fixes: #25837 
Adding a note on gRPC HTTP API and linking out to its gitHub readme.
=> gRPC JSON transcoding: Move openAPIto gRPC HTTP API doc and link out

aspnetcore/blazor/fundamentals/logging.md
Note to @Rick-Anderson and @wadepickett on this subject in passing:
I have several spots where I show console output in block quotes. I thought that in the the olden days of docs 👴, one could just CRLF at the ends of the lines for bare returns in the output (`<br>`) ...
```
> Blah blah blah.
> Blah blah blah 2.
> Blah blah blah 3.
```
... would render as ...
> Blah blah blah.
> Blah blah blah 2.
> Blah blah blah 3.
Whether or not I'm recalling that correctly, it certainly isn't working today. The rendered output is ...
> Blah blah blah.Blah blah blah 2.Blah blah blah 3.
Soooo ... we're back to our usual rock-and-hard-place choice: Use HTML bare returns (`<br>`) (which are strictly required in table cells) or use markdown's double-space at the end of the line. I'm going with the …
=> Update block quote bare returns

aspnetcore/blazor/hybrid/routing.md, aspnetcore/blazor/hybrid/security/index.md, aspnetcore/blazor/hybrid/tutorials/index.md
Addresses #24956
Best I can do for the moment. Lots of API is MIA from the API docs at the moment. I'm following up internally on it.
=> Blazor Hybrid API cross-refs

aspnetcore/fundamentals/index.md
Minimum Host and Generic House are proper nouns in the document like Jim Smith and Bob Smith are proper nouns. 
You would not say "Jim and Bob smiths" -- you'd say "Jim and Bob Smith" it should be "Minimal and Generic Host" not "Minimal and Generic hosts"
=> Fixed incorrect lower case letter, and incorrect plural

aspnetcore/fundamentals/host/hosted-services/samples/6.0/BackgroundTasksSample/Services/TimedHostedService.cs
The `_timer` field should be nullable in this sample instead of using the null-forgiving operator.
=> Fix nullability annotation in TimedHostedService

aspnetcore/tutorials/min-web-api.md
The table under Examine the GET endpoints was supposed to enumerate all GET endpoints in the example, but `todoitems/complete` was missing for some reason.
=> Update table in Examine the GET endpoints section

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/rendering.md
Fixes #23704
Thanks @omuleanu! :rocket:
Referenced content:
https://docs.microsoft.com/aspnet/core/blazor/components/rendering#rendering-conventions-for-componentbase
The updates to the *Overwritten parameters* section doesn't try to list the explicit parameters that are checked because that's subject to change over time. I think it best to refer to the reference source to harden the doc. Devs can then 👀 the exact list of param types checked for any given release, and the PU is free to change the list at any time without breaking the doc.
I'm moving the *Overwritten parameters* one section lower, below the *Child content* section. The *Child content* section introduces the `RenderFragment`, so that should appear first.
I'm also improving cross-links.
I considered moving the whole example …
=> Improve overwritten parameter guidance

aspnetcore/blazor/fundamentals/routing.md
The article description shows twice when the selected moniker is < .net 6.
This moves all instances of the article description within moniker range selections, so there is only ever one description displayed.
Example incorrect behaviour:
Also fix a typo in the article description to read "create navigation links in Blazor apps" rather than "create **a** navigation links in Blazor apps".
=> Fix article description showing twice

aspnetcore/performance/caching/memory.md
The sentence fragment and the next sentence are combined because they're probably meant to be together.
=> Fix sentence fragment

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/6.0-completed/Views/Shared/_Layout.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/6.0-completed/Views/Shared/_ValidationScriptsPartial.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie60/Views/Shared/_Layout.cshtml, aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie60/Views/Shared/_ValidationScriptsPartial.cshtml
Fixes #26041
Update .NET 6 Bootstrap and jQuery static references since .NET 6 no longer ships min versions of libs.
=> Update MvcMovie static references for .NET 6

aspnetcore/fundamentals/index.md
The original section said: 
There are three different hosts:
.NET WebApplication Host
.NET Generic Host
ASP.NET Core Web Host
The .NET Minimal Host is recommended and used in all the ASP.NET Core templates. 
----
Notice a 4th host, ".NET Minimal Host" is discussed under the list. I added it to the bulleted list.
The strart setence said "There are three different hosts:" but the number three is wrong (the correct number is four) but I made the setence agnostic to the number of hosts in case a 5ht, 6th or 7th host is added. The new setence is "The different hosts include:" which works for 50 or 100 or 1000 hosts.
=> Add missing host & fixed number of hosts available

aspnetcore/includes/appname6.md, aspnetcore/migration/31-to-60.md, aspnetcore/migration/50-to-60.md
=> links to workaround for app name change in .NET 6 /1

aspnetcore/security/cookie-sharing.md, aspnetcore/security/cookie-sharing/samples/WebCookieShare/Program.cs
Fixes #26066
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-6.0&branch=pr-en-us-26068)
Changes:
1. Created .NET 6 version
2. Replaced non working HTML `.PersistKeysToFileSystem("{PATH TO COMMON KEY RING FOLDER}")` with working code snippet `.PersistKeysToFileSystem(new DirectoryInfo(@"c:\PATH TO COMMON KEY RING FOLDER"))`
3. Added [In .NET 6, **Application name change** xref:Microsoft.AspNetCore.Builder.WebApplicationBuilder normalizes the content root path to end with a xref:System.IO.Path.DirectorySeparatorChar.](https://review.docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-6.0&branch=pr-en-us-26068#application-name-change)
=> .net 6 update of sharer app cookies /1

aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/hybrid/reuse-razor-components.md, aspnetcore/blazor/includes/js-interop/synchronous-js-interop-call-dotnet.md, aspnetcore/blazor/includes/js-interop/synchronous-js-interop-call-js.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md, aspnetcore/blazor/performance.md
* Surface `IJSInProcessObjectReference` better. It was primarily covered way back in the *Performance* topic. This will centralize its coverage with the rest of JS interop in the JS interop node.
* Both the JS interop coverage and the performance articles use INCLUDE files to call out the synchronous options for WASM coverage. Because in the performance topic these sections sit SxS, there's a bit of duplicate text. Each section starts by explaining that WASM can use sync calls, not Server. Still tho, that language should stay in each INCLUDE because the files are used separately in the JS interop node topics on *calling JS* or *calling .NET* ... they aren't SxS in the JS node topics ... the dup text won't be seen by readers there. This is a reasonable compromise. I …
=> Sync JS interop updates

aspnetcore/whats-new/dotnet-AspNetCore.Docs-2022-02-01.md
**Global effort to fix broken links**
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!
=> [BrokenLinksH2] Fix path in link

aspnetcore/fundamentals/index.md
The bullet list contains .NET WebApplication Host but the paragraph below uses the terms .NET Minimal Host and Minimal Host. .NET WebApplication Host is the primary name used in .NET 6. The paragraph should match bullet list.
=> Standardized on .NET 6 Host naming

aspnetcore/toc.yml
Fixes #26128
It looks like this link for web API with B2C should be ...
**How to secure a Web API built with ASP.NET Core using the Azure AD B2C**
https://docs.microsoft.com/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/how-to-secure-a-web-api-built-with-aspnet-core-using-the-azure-ad-b2c/
=> Repair broken link

aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/includes/js-location.md, aspnetcore/blazor/includes/prerendering.md
=> Cross-link JS location guidance

aspnetcore/blazor/file-downloads.md, aspnetcore/blazor/images.md, aspnetcore/blazor/includes/js-location.md
* Split the small file (< 250 MB) approach from the large file (> 250 MB) approach into a pair of sections.
* Phrasing updates.
* Cross-link improvements.
* Fully-working, cut-'n-paste examples.
* Reference snippet sample app code in the `dotnet/blazor-samples` repo.
=> Blazor file downloads UE pass

aspnetcore/blazor/host-and-deploy/index.md
Fixes #26170
Thanks @engineerTrooper! 🚀 ... *Great idea to add this!* Thanks again for the suggestion. I'd like to merge this quickly, but I'll leave it here for a few hours to give you a chance to look it over for any possible feedback.
Note that `launchBrowser` is already present in a profile config of an app created from a Blazor project template and set to `true`, so we don't need to call that property out.
=> Add launch profile config for setting pathbase

aspnetcore/host-and-deploy/health-checks.md
Everywhere in the document, the _/health**z**_ endpoint is used (which, as I understand it, is the name by convention), and in the example for Kubernetes, just _/health_. I made changes to unify endpoints and get rid of misleadings.
=> docs: Fix Kubernetes example

aspnetcore/tutorials/first-mvc-app/search.md
[Internal Review of topic build](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0&branch=pr-en-us-26226)
Removed redundant highlight in the code snippet example.
Furthermore, on the docs, line 43 isn't highlighted but should be according to the context of the docs and the URL provided for the code snippet.
link to documentation in question: [https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0)
Code snippet URL before:
`~/tutorials/first-mvc-app/start-mvc/sample/MvcMovie22/Views/Movies/IndexFormGenreNoRating.cshtml?highlight=1,15,16,17,19,28,31,34,37,43)`
Code snippet URL after: …
=> Removed redundant highlight for code example

aspnetcore/performance/caching/response.md, aspnetcore/performance/caching/response/samples/6.x/WebRC/Controllers/TimeController.cs
Fixes #26235
Thanks @xenophilios! :rocket:
Rick, a few points on this one ...
* If I've gone off the rails here, close this and take it over for a *better* PR than what I've set up here 🙈😄.
* The `Duration = 0` setting I think 🤔 is just a no-op in the scenario and can be removed/avoided.
* The RP approach is messy compared to the MVC approach ... *apparently*. It looks like something might be worked for 7.0 on [Make ResponseCacheMiddleware endpoint aware (dotnet/aspnetcore #37995)](https://github.com/dotnet/aspnetcore/issues/37995), so it might be good to have a follow-up 7.0 docs issue to make sure that this bit gets a 7.0 update if they make a change for MVC/RP/both.
* Although the "Razor Pages page responses" lingo isn't what I normally use, I think we must clarify that it's the page …
=> Global no-store/no-cache guidance

aspnetcore/security/data-protection/consumer-apis/password-hashing.md, aspnetcore/security/data-protection/consumer-apis/password-hashing/samples/5.x/passwordhasher.cs, aspnetcore/security/data-protection/consumer-apis/password-hashing/samples/6.x/passwordhasher.cs, aspnetcore/security/data-protection/consumer-apis/password-hashing/samples/passwordhasher.cs
Updates the salt hashing example in passwordhasher.cs for dotnet 6 using RandomNumberGenerator instead RNGCryptoServiceProvider (outdated).
=> Updates the salt hashing example in passwordhasher.cs for dotnet 6

aspnetcore/security/anti-request-forgery.md
The following xref link `xref:razor-pages/index#xsrf` points to the invalid link below:
> https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio#xsrf
The xref link should be `xref:razor-pages/index#xsrfcsrf-and-razor-pages-1` in order to point to the valid link below:
> https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio#xsrfcsrf-and-razor-pages-1
I've noticed that the xref link seems broken only for the ASP.NET Core 5.0 docs, so this fix may need tweaking to target just those docs (not sure how to do that at the moment).
=> Fix xref link in anti-request-forgery.md

aspnetcore/security/key-vault-configuration.md
This documentation page still refers to the `Microsoft.Extensions.Configuration.AzureKeyVault` APIs even though it recommends the newer `Azure.Extensions.AspNetCore.Configuration.Secrets` package.
`IKeyVaultSecretManager` interface isn't supported by `AddAzureKeyVault` now, and the link to inspect `AzureKeyVaultConfigurationOptions` (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azurekeyvault.azurekeyvaultconfigurationoptions?view=dotnet-plat-ext-3.1) lists multiple options which aren't supported either.
=> Update API references to KeyVault secrets package

aspnetcore/fundamentals/minimal-apis/min-api-filters.md
Slightly reword  a sentence in [_Filters in Minimal API apps_](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters) and make the value a string.
Relates to #26188.
=> Minor reword in "Filters in Minimal API apps"

aspnetcore/grpc/protobuf.md
Missing semicolon at the end of the import statement causes build error like this.
=> Add missing semicolon at the end of the import statement

aspnetcore/signalr/configuration.md, aspnetcore/signalr/configuration/6.0-samples/Program.cs
Fixes #26293
**Internal review URLs**
* [6.0 ](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&branch=pr-en-us-26294&tabs=dotnet)
* [7.0 ](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-7.0&branch=pr-en-us-26294&tabs=dotnet)
=> SignalR config to .NET 6 /2

aspnetcore/blazor/security/includes/index-page-authentication.md
The existing script has a line break which prevents the script from working if copying directly. My change removed the spaces so the script is usable without editing.
=> Removed spaces to make command one line

aspnetcore/blazor/file-downloads.md
Fixes #26377
Thanks @frankleib! :rocket:
btw ... We're working on a build problem at the moment, which is why you see the 💥 down there :point_down:. We should have that cleared up shortly, then I'll merge this.
cc: @Rick-Anderson @wadepickett ... Here's another example of the 💥 ...
> File aspnetcore/blazor/file-downloads.md was deleted without redirection. To avoid broken links, add a redirection.
This topic has no versioned content. It's just for `monikerRange: '>= aspnetcore-6.0'`. It loads fine on the live doc set for the version selector ...
* https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-7.0
* https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0
... and displays the correct banner earlier than that (e.g., …
=> Improve download from stream example

aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/samples/5.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor, aspnetcore/blazor/samples/5.0/BlazorSample_Server/Pages/file-uploads/FileUpload3.razor, aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
Fixes #26405
Thanks @mo2eharrington! :rocket:
Changes for 6.0 were performed separately at the `dotnet/blazor-samples` repo, which can be see here ...
https://github.com/dotnet/blazor-samples/commits/main
=> Make max file size consistent across examples

aspnetcore/signalr/hubs.md
https://github.com/dotnet/aspnetcore/pull/42236 changed the API for client results, updating doc to reflect the changes.
=> Update SignalR client results

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/release-notes/aspnetcore-7.0.md
=> Bind arrays in What's new

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #26381
Fixes #26383
Javier ... It's best if you look this over. There are some deltas from your "provider options" issue on the PR ...
* I can't find a `WebAssemblyHostBuilder.BaseUri` property, but I think 🤔 that the redirect URIs can be built with `builder.HostEnvironment.BaseAddress`. It's probably also worth it to call out supplying the URIs via configuration.
* I can't find `Uri.Create`, so I placed a `Uri.TryCreate` approach on the PR.
=> Provide additional Blazor WASM security guidance

aspnetcore/signalr/hubs.md, aspnetcore/signalr/hubs/samples/2.x/SignalRChat/Hubs/ChatHub.cs, aspnetcore/signalr/hubs/samples/2.x/SignalRChat/Hubs/StronglyTypedChatHub.cs
[Internal Review - Handle events for a connection section of Use hubs in SignalR for ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0&branch=pr-en-us-26394#handle-events-for-a-connection)
The sample added this explicit `RemoveFromGroupAsync` call when the connection disconnects, however, it is a redundant call since when the connection disconnects, it is automatically removed from the group. 
We have customers using Azure SignalR followed this sample and invokes `RemoveFromGroupAsync` for every client disconnect, this increases unnecessary burdon to the Azure SignalR service when the client connection closes burst.
=> No need to explicitly call RemoveFromGroupAsync

aspnetcore/security/anti-request-forgery.md, aspnetcore/security/anti-request-forgery/samples/6.x/AntiRequestForgerySample/Snippets/Index.js, aspnetcore/security/anti-request-forgery/samples/6.x/AntiRequestForgerySample/Snippets/Program.cs, aspnetcore/security/anti-request-forgery/samples/7.x/AntiRequestForgeryMinimalSample/AntiRequestForgeryMinimalSample.csproj, aspnetcore/security/anti-request-forgery/samples/7.x/AntiRequestForgeryMinimalSample/Program.cs, aspnetcore/security/anti-request-forgery/samples/7.x/AntiRequestForgeryMinimalSample/appsettings.Development.json, aspnetcore/security/anti-request-forgery/samples/7.x/AntiRequestForgeryMinimalSample/appsettings.json
Closes #26350 
Part of https://github.com/dotnet/aspnetcore/pull/42586
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0&branch=pr-en-us-26386)
EDIT by @Rick-Anderson  [Internal Preview URL `JavaScript H2` where the changes start](https://review.docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0&branch=pr-en-us-26386#javascript)
=> Antiforgery doc updates

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Controllers/WeatherForecastController.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Models/Culture.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Models/DateRange.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/Culture.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRange.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Views/WeatherForecast/Error.cshtml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26434
@Rick-Anderson I've modified the sample to make the snippets more meaningful and compact.
* `/WeatherForecast?culture=en-GB` can be called with or without the `culture=en-GB`
* `/WeatherForecast/Range?range=07/12/2022-07/14/2022`, here dateRange is a required field
* `/WeatherForecast/GetByRangeWithCulture?culture=en-GB&range=07/12/2022-07/14/2022`, both culture and range is required (but the range is in a string format, we make the call `DateRange.TryParse(range, new CultureInfo(culture?.DisplayName ?? "en-US"), out var dateRange)` inside the controller to validate the parameter based on the culture privided by the client
These three examples should suffice for using both,
`public static bool TryParse(string value, T out …
=> Tryparse with dynamic format provider supplied from client

aspnetcore/security/data-protection/consumer-apis/password-hashing.md, aspnetcore/security/data-protection/consumer-apis/password-hashing/samples/6.x/passwordhasher.cs, aspnetcore/security/data-protection/consumer-apis/password-hashing/samples/6.x/pwHash.csproj
Completes PR #26233 which added [this pw hasher file](https://github.com/dotnet/AspNetCore.Docs/pull/26233/files#diff-1e2c12b88507dbd85457afb6e3edabb07e29a6e6f4ec918d794d1bc57b0a4b84)
Fixes #25786 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-7.0&branch=pr-en-us-26253)
=> Updates the salt hashing example for .NET 6 /4

aspnetcore/release-notes/aspnetcore-7.0.md
=> what's new top level option

aspnetcore/mvc/views/razor.md
Shouldn't it be `T` instead of `dynamic` here?
=> `@model T` will generate a class that inherits from `RazorPage<T>`

aspnetcore/blazor/components/dynamiccomponent.md
Fixes #26555
Thanks @adver501! :rocket: ... and I'm going to make a note to myself to chat with Tanay of the product unit about this approach (and the others here). There might be a *better* way to showcase the parameter dictionary approach generally ... or specifically for event callbacks. At least this implies how different event callbacks can be present in the parent component parameter dictionary for different dynamically-rendered components.
I'll merge this into the *LIVE* doc set right after I build it. It should show up in the live topic shortly. Thanks again for your issue!
=> Update event callback approach

aspnetcore/blazor/components/index.md, aspnetcore/blazor/globalization-localization.md
Will only cover at this point via cross-link because ...
* Javier didn't call for explicit coverage and remarked that ...
> This is not a common pattern that we see often ...
* The discussion on the PU issue covers the scenario and supported approach well.
=> Preserve context for external events

aspnetcore/blazor/project-structure.md, aspnetcore/blazor/tooling.md
=> Blazor empty templates

aspnetcore/blazor/tooling.md
=> Update Blazor tooling empty templates

aspnetcore/tutorials/razor-pages/model.md
Updated the SQL Lite+Development / SQL Server+Production switching code to use Program.cs per the new .NET 6 minimal hosting model
Fixes #26582
=> Dev/Prod SQL code for VS Mac to .NET 6

aspnetcore/blazor/components/index.md, aspnetcore/mvc/models/validation.md
=> Custom elements support

aspnetcore/release-notes/aspnetcore-2.1.md
Hello,
I was just browsing through our docs and came upon this statement:
"SignalR has been rewritten for ASP.NET Core 2.1. ASP.NET Core SignalR includes a number of improvements:"
It took me some time to parse and understand why we have the "ASP.NET Core" syntax mentioned consecutively.
I would propose a line break after the first phrase - it makes the content easier to understand and read.
Please let me know if you have any issues with this PR.
You can also reach out to me on Teams (aolariu).
Thanks!
=> improve text readability.

aspnetcore/blazor/forms-validation.md
=> Custom validation attribute with DI

aspnetcore/release-notes/aspnetcore-7.0.md
=> JSON prop names for validation in What's new /6

aspnetcore/security/authentication/identity.md
While Duende does use Identity to manage users that is unrelated to explaining is at it's core. 
We already have an external link to the Dueude identity server, this doc shouldn't mention it when explaining what identity is.
=> Remove duende from the core identity docs

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md
=> WASM debug default browser is going to Edge

aspnetcore/blazor/components/built-in-components.md, aspnetcore/blazor/components/index.md
=> Blazor QuickGrid Razor component

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #26619
@yugabe ... Are you free to take a look 👀 at this?
btw -- You'll see three copies of the section. You only need to look at the first because they're identical. We duplicate them to cover different release versions in the same article.
The new section for the WASM deployment doc seeks to address both the general scenario for any given MSBuild property that's applied to both projects of a hosted WASM solution and specifically for your use case scenario (framework-dependent executable for a specific platform), which I show as the example.
You (and Javier) didn't state that there was a limitation on the self-contained deployment option (as `false`) to the project file. You did state that ...
> Disabling SCD from the CLI breaks the build altogether.
... but you may have meant by …
=> MSBuild properties for hosted deployment options

aspnetcore/security/authentication/social/additional-claims.md, aspnetcore/security/authentication/social/additional-claims/samples/6.x/ClaimsSample/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
The `props` variable which holds the authentication tokens from the external provider, is initialized in line 247 but never actually used. Changed line 269 to use it.
Fixes #26651
=> fix: `props` is initialized but never used

aspnetcore/tutorials/first-web-api.md
Fixes #26652
`dotnet aspnet-codegenerator` --> `dotnet-aspnet-codegenerator`
=> Fix dotnet-aspnet-codegenerator command by removing spaces

aspnetcore/test/troubleshoot-azure-iis.md
FYI @Rick-Anderson ... This came up on a build report for a Blazor code example that I was fixing on another PR ...
> aspnetcore/test/troubleshoot-azure-iis.md
>
> Absolute link 'https://docs.microsoft.com/azure/app-service/troubleshoot-performance-degradation' will be broken in isolated environments. Replace with a relative link.
Patching it up here. 🏃
=> Use relative cross-link to Azure doc

aspnetcore/host-and-deploy/health-checks.md
This PR doesn't resolve an issue, but it addresses a small mistake in the docs.
As shown in the image below, `RequireCors` requires us to pass a builder, or a policy name.
The method gives a compile error when no arguments are provided, but the docs mention that it should be possible.
[Link](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/CORS/src/Infrastructure/CorsEndpointConventionBuilderExtensions.cs#L12) to the source code with the allowed signatures.
=> fix(health-checks): cors origin doesn't accept empty args

aspnetcore/blazor/fundamentals/startup.md
=> Blazor WASM loading progress indicator

aspnetcore/fundamentals/w3c-logger/index.md, aspnetcore/fundamentals/w3c-logger/samples/7.x/Program.cs, aspnetcore/fundamentals/w3c-logger/samples/7.x/W3CLoggerSample.csproj, aspnetcore/release-notes/aspnetcore-7.0.md
=> AdditionalRequestHeaders

aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/graph-api.md
Fixes #26528
Thanks @Zhiyuan-Amos :rocket: and @oatsoda! :rocket: ... I'll leave this up for a couple of hours for you to take a look if you want. I need to get it merged rather quickly. I'm 🏃😅 on a lot of issues right now for .NET 7 and want to avoid 💥 **_merge conflicts_** 💥😢 among PRs.
=> Transient registration for HTTP message handlers

aspnetcore/fundamentals/websockets.md
[Internal Review - Verify 7.0 version added, and previous versions still showing](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0&branch=pr-en-us-26766)
Contributes to #26366 
Just prep, adding a moniker copy for >= 7.0 so in my following PR the changes easy to compare.
=> Prep: Added moniker range for 7.0: WebSockets support in ASP.NET Core

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/security/webassembly/graph-api.md
This mostly addresses:
* `@bind:after`
* MDN doc cross-link updates, as they moved the 🧀 for some of their content.
I'll circle around after the RC1 blog post to provide further guidance on `@bind:get`/`@bind:set`.
=> Blazor bind get/set/after

aspnetcore/blazor/security/content-security-policy.md
Fixes #26483
Thanks @yugabe! 🚀 
`block-all-mixed-content` is deprecated and obsolete.
> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
>
> Warning: This directive is marked as obsolete in the specification: all mixed content is now blocked if it can't be autoupgraded. …
=> Remove deprecated/obsolete CSP directive

aspnetcore/blazor/fundamentals/environments.md, aspnetcore/blazor/fundamentals/static-files.md
Fixes #26751
[Internal Review Topic (links to 7.0 section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-7.0&branch=pr-en-us-26759#static-files-in-non-development-environments-for-blazor-server-apps)
cc: @captainsafia ... Idk if you want to look 👀 at this given your participation in the PU discussion. I'll ping Halter for review; but of course, you're very welcome to help me with this. I didn't see a final summary set of suggestions for *all versions*, including 3.1 (which I think is the same as 5.0), at the end of the PU discussions **_from the PU engineers_**.
Thanks @KurtP20! 🚀 
cc: @voroninp ... I see that you asked about documenting this on [another PU issue](https://github.com/dotnet/aspnetcore/issues/43110). It's being worked …
=> Non-Development static files for Blazor Server

aspnetcore/fundamentals/middleware/request-decompression.md
Contributes to #26541
- Fixes minor formatting issue.
- List the places where `MaxRequestBodySize` is configured for each web server implementation.
- Link to doc page for `KestrelServerLimits.MaxRequestBodySize` instead of source.
=> Request decompression improvements

aspnetcore/release-notes/aspnetcore-7.0.md
=> .NET 7: customize cookie consent value

aspnetcore/fundamentals/middleware/request-decompression.md
Contributes to #26541
- Clarifies the order of precedence for max request size limits
=> Request decompression: clarify order of precedence for size limits

aspnetcore/release-notes/aspnetcore-7.0.md
Fixes #26291
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26792#provide-endpoint-descriptions-and-summaries)
=> .NET 7 what's new - endpoint descriptions and summaries

aspnetcore/blazor/components/index.md, aspnetcore/blazor/debug.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Remove default Kestrel HTTPS binding

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #26798
@mayur-ekbote ... Would you like to take a look at this?
See if this lays out the approach and would've helped with the editable `<div>`s scenario. I never did find out why Javier said "JSObjectReference." I don't see how `IJSObjectReference` is relevant. Perhaps, he meant to say `DotNetObjectReference`. The code for the `ListItem2` and `CallDotNetExample7` components can be reached via the links below. They're in the `dotnet/blazor-samples` repo, and the code is pulled into the article from there.
I made the example almost exactly like the preceding list item example, so readers can see these approaches in a SxS format. Because I'm using another list item component named "ListItem," you'll see that I'm renaming the one in the *Component instance .NET method helper class* …
=> Add JS interop example

aspnetcore/fundamentals/startup.md, aspnetcore/release-notes/aspnetcore-7.0.md
Fixes #26846
* [What's new](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26847#serverready-event-to-measure-startup-time)
* [Startup](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-7.0&branch=pr-en-us-26847)
=> ServerReady event /8

aspnetcore/blazor/host-and-deploy/index.md
Fixes #26667
Follow-up to #26733.
Thanks @LarsOutzen! :rocket: ... I wasn't able to repro a problem with our current app base path guidance. I tested with both the base path tag (`<base>`) and the `UsePathBase` call, and they both worked for a Blazor Server sub-app. Other than the earlier PR to move the call for adding `UsePathBase` **_first_**, I don't have further changes at this time on the app base path piece.
Idk if you ever got it working in your Umbraco CMS scenario or other IIS config scenario. Perhaps, Umbraco has/had an influence or perhaps your IIS config or steps didn't work out. I also linked the [PU issue remarks that Javier made](https://github.com/dotnet/aspnetcore/issues/43191#issuecomment-1212156106) on that other issue at the bottom of the *App base path* section …
=> Blazor IIS and subapp hosting

aspnetcore/fundamentals/static-files.md, aspnetcore/fundamentals/static-files/samples/6.x/StaticFilesSample/Program.cs
This PR updated two things about static files in ASP.NET Core:
1. Update code sample about `enableDirectoryBrowsing` parameter of `UseFileServer`. `AddDirectoryBrowser` is supposed to be called when the `EnableDirectoryBrowsing` property value is true.
2. According to [this issue](https://github.com/dotnet/aspnetcore/issues/2449), trailing `/` redirect could be disable with `RedirectToAppendTrailingSlash`.
=> Update static-files.md & its code samples.

aspnetcore/grpc/services.md
=> gRPC multithreading example

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/includes/prerendering.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #26862
Thanks @JefSchraag! :rocket: ... Those are great suggestions. A few notes on the update here ...
* The section can be renamed to merely "Prerendering." This content comes from an INCLUDE file to appear in two spots, the *Lifecycle* topic and the *Call JS from .NET* topic. I think that will work in both spots. I ran through the docs and updated the references everywhere for this section heading change.
* It's ok to use the word "server" (lowercase) because that's where prerendering happens in either a Blazor Server app or hosted Blazor WebAssembly (solution). "Server" isn't used in the docs to mean "Blazor Server." I do use it in spots with special formatting [**`Server`** project (or app)] when referring to that project/app in a hosted WASM solution.
* When I have the two …
=> JS interop with prerendering updates

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/routing.md
=> Update Blazor sample app references

aspnetcore/security/anti-request-forgery.md
The link to bad-crook-site is very unsafe. Nobody should click that ever. Not sure why you are linking to there, but it's an actual scam site with explicit porn ads on it.
=> remove very unsafe link to bad-crook-site

aspnetcore/whats-new/index.yml
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
=> [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 3)

aspnetcore/security/samesite.md, aspnetcore/signalr/introduction.md, aspnetcore/test/debug-aspnetcore-source.md, aspnetcore/toc.yml, aspnetcore/tutorials/first-mongo-app.md, aspnetcore/tutorials/first-mvc-app/start-mvc.md, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/getting-started-with-swashbuckle.md, aspnetcore/web-api/index.md
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
=> [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 2)

aspnetcore/release-notes/aspnetcore-7.0.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26515
=> what's new update rate limiting

aspnetcore/blazor/hybrid/routing.md
=> Blazor Hybrid routing (external nav, pivots)

aspnetcore/security/data-protection/consumer-apis/purpose-strings.md
The warning about user input and using nested purposes to provide isolation uses a constant string instead of the actual user input.
Fixes #26930
=> Fix example for nested purposes with user input

aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs
Fixes #26937
This test fails to build when using Visual Studio Code or a CodeSpace. This change makes use of xUnit's exception assertions that are already included in the .csproj to conduct the same test.
=> use xunit exception assertions in grpc integration test sample

aspnetcore/mvc/views/tag-helpers/intro.md
If `Model` or `LicenseId` is null, the expression evaluates to true, not false.
=> Fix logic error in the explanation

aspnetcore/fundamentals/localization.md
The code on line 355 lacks an awaiter despite being part of an async method, and triggers a warning for not being awaited in .NET 6. I settled on this implementation which eliminates the warning and functions properly. It seems like there should be some more code here to help with the async method, hence my proposed change. However, please let me know if I am incorrect or misunderstanding this code.
=> update custom provider code snippet

aspnetcore/release-notes/aspnetcore-7.0.md
Fixes #26540
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26985#minimal-apis-and-api-controllers)
@martincostello this works for API controllers too, right?
=> param binding /1

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/release-notes/aspnetcore-7.0.md
Fixes #26683
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26988#file-uploads-using-iformfile-and-iformfilecollection) and [What's new](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26988#file-uploads-using-iformfile-and-iformfilecollection)
=> IForm uploads /1

aspnetcore/blazor/file-uploads.md
Fixes #26923
I'll make it utterly clear in the text to create the folder. I'm **_too scared_** 😨 to automate the folder creation step given that we know devs copy-'n-paste our code directly into their **_production apps_** 🙈. On production systems, upload folders ...
* Shouldn't be part of the app's folder/file structure.
* Should have execute permissions disabled.
* Should have a virus/malware scanner in play.
Let's keep it manual for the local demo, but I do call out the folder creation step with **BOLD** text on its own line leading into the demo code.
I also improve the existing WARNING note at that spot (and add it to a prior version of the topic) on the dangers here. It includes a cross-link to our main security best practices content on file uploads over in the MVC file uploads …
=> Clarify folder creation and add addl warning

aspnetcore/tutorials/min-web-api.md, aspnetcore/tutorials/min-web-api/samples/7.x/WebMinJson/Program.cs, aspnetcore/tutorials/min-web-api/samples/7.x/WebMinJson/WebMinJson.csproj, aspnetcore/tutorials/min-web-api/samples/7.x/WebMinJson/appsettings.Development.json, aspnetcore/tutorials/min-web-api/samples/7.x/WebMinJson/appsettings.json, aspnetcore/tutorials/min-web-api/samples/7.x/stub.txt
Fixes #26445 
***@Rick-Anderson EDIT:***
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&branch=pr-en-us-26996&tabs=visual-studio)
=> Update JSON options examples

aspnetcore/blazor/fundamentals/signalr.md
The notes [were not rendered correctly](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#reflect-the-connection-state-in-the-ui-blazor-server) due to incorrect syntax of `[!NOTE]`.
=> Fix `[!NOTE]` syntax

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #27010
Thanks @jorgearana! :rocket: ... This will surface the API doc and the reference source for that class.
=> Cross-link class to example code

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/security/includes/fetchdata-component.md, aspnetcore/blazor/security/includes/logindisplay-component.md, aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
**_Reminder to anyone else looking: Open the files on the diff for the "compare" links to show the code changes._**
* IMO, it's best to split the coverage between the *WASM Overview* to explain basic concepts and the *WASM Additional scenarios* topic for the coding recipes. These sections are in the following files/locations:
* `aspnetcore/blazor/security/webassembly/index.md`: https://github.com/dotnet/AspNetCore.Docs/compare/guardrex/blazor-auth-updates?expand=1#diff-f141178902970237a98cb3c67364e38902db1ddefbb66a29db4f77683d25347cR537-R567
* `aspnetcore/blazor/security/webassembly/additional-scenarios.md`: https://github.com/dotnet/AspNetCore.Docs/compare/guardrex/blazor-auth-updates?expand=1#diff-21d675281d3bd37692b5325cb748c4d3c368112058b62184137bf32e795a8fd8R3753-R385 …
=> [7.0] Blazor auth updates

aspnetcore/includes/combine-di6.md
The .NET docs formally recommend _not_ using the `Microsoft.Extensions.DependencyInjection` namespace, [.NET docs: Options pattern guidance for .NET library authors — Namespace guidance](https://docs.microsoft.com/dotnet/core/extensions/options-library-authors#namespace-guidance). The sentence being removed in this PR are a contradiction to the .NET docs recommendation.
This PR removes the recommendation to use namespaces owned by Microsoft. Otherwise, doing so has a good chance of colliding with our future additions in these namespaces.
Fixes dotnet/docs#31084
=> Address dotnet/docs #31084 - contradicting recommendations

aspnetcore/fundamentals/http-logging/index.md
Can't hurt to be explicit. Someone on an internal mailing list thought this applied to outgoing requests from HttpClient.
=> Clarify HTTP logging middleware only logs incoming requests

aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes  #27052
Thanks @d4shm1r! :rocket: This will use line highlights, so the text part can avoid individual code lines.
and btw ... There's a number difference of line 16 vs. line 17. That's because I removed a comment line from the `Program.cs` file that's normally in the project template. It moves up that highlight to line 16 in the 7.0 example.
=> Clean up "In Program.cs" step

aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigSample/Options/MyConfigServiceCollectionExtensions.cs, aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Options/MyConfigServiceCollectionExtensions.cs
Fixes #27095
The code in `snippet3` of [Program.cs](https://github.com/dotnet/AspNetCore.Docs/blob/3057fe3e950d41d39d55b45d7545acdba63defed/aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Program.cs#L99) in the configuration fundamentals section makes a call to a non-existent extension method called `AddMyDependencyGroup`, this PR adds that extension method.
=> Add an AddMyDependencyGroup extension method

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/security/server/threat-mitigation.md, aspnetcore/signalr/configuration.md
=> Warn on MaximumReceiveMessageSize

aspnetcore/security/authorization/policies.md
For https://github.com/dotnet/aspnetcore/issues/18961
Clarify that authZ requirement handlers are not guaranteed to execute in any order
=> Clarify authZ handler ordering behavior

aspnetcore/security/authentication/customize-identity-model.md
Fixes https://github.com/dotnet/aspnetcore/issues/12511
Clarify AddEntityFrameworkStores behavior and workaround when not using a derived IdentityDbContext
=> Clarify AddEntityFrameworkStores behavior

aspnetcore/blazor/hybrid/tutorials/maui.md, aspnetcore/blazor/hybrid/tutorials/windows-forms.md, aspnetcore/blazor/hybrid/tutorials/wpf.md
Fixes  #27131
~This PR only updates the MAUI tutorial. The Windows Forms and WPF tutorials still call for preview. I'm 👂 if they need to change in the same way.~
Nevermind ... I just picked up on the "**for Blazor Hybrid**" part of your issue title. I'll update the other two now. **_Done!_** 👍
I've set up ...
**Remove VS4Mac prerelease remark at 17.4 release**
https://github.com/dotnet/AspNetCore.Docs/issues/27133
... to track the VS4Mac update at 17.4.
=> Update Blazor Hybrid prereq

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #27036
This *should* 🤞 wrap up the series of JS interop disposal update PRs in the *Call .NET* article and in the examples for the article in the `dotnet/blazor-samples` repo. There's one more PR to place on the samples repo for the *Call JS* article: Two classes don't implement `IDisposable`. I'll take care of that over there next.
Thanks again @omuleanu! 🎷 ... I'm sorry that it took so long to adopt the correct approaches for disposal. I wasn't aware that the additional instances were created, and *multiple reviews across multiple doc PRs by different PU engineers* didn't catch these problems. **_I'm glad you called it out!_** Thanks @MackinnonBuck, too, who reminded me of the usefulness of `using var` syntax for these scenarios.
=> Update JS interop examples (Part 4)

aspnetcore/mvc/views/razor.md
Updates the section 'Inspect the Razor C# class generated for a view' to reflect the behavior of recent versions that by default omit the generated source files. Adds information on how to re-enable it.
Since the directory structure that was shown in the previous version of the section has changed (in fact, all generated files now get dumped in one single directory instead of mirroring the original structure), I took the liberty of removing it.
(Fixes #26804)
=> Updates note for emitting Razor generated files

aspnetcore/blazor/hosting-models.md, aspnetcore/blazor/tooling.md, aspnetcore/blazor/webassembly-native-dependencies.md
=> Build tools for .NET 6 projects under .NET 7 SDK

aspnetcore/blazor/fundamentals/logging.md
=> Update Blazor auth logging 7.0

aspnetcore/fundamentals/minimal-apis/test-min-api.md, aspnetcore/toc.yml, aspnetcore/web-api/index.md
Internal review URLs, link is under the following doc's. See the TOC
* [Handle errors in ASP.NET Core web APIs](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0&branch=pr-en-us-27193)
* [OpenAPI support in minimal APIs - ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0&branch=pr-en-us-27193)
* [test node](https://review.learn.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-7.0&branch=pr-en-us-27193)
=> Add links to port tunneling in VS

aspnetcore/security/docker-https.md
The document had references to the `mcr.microsoft.com/dotnet/core/samples` repo. The use of `core` in the repo name is not recommended since the repo names were updated to remove "core" from the name (see https://github.com/dotnet/dotnet-docker/discussions/3674). The old "core" repos are still maintained and up-to-date but no longer documented at https://hub.docker.com/_/microsoft-dotnet-samples/. We should use the officially documented repo names instead.
=> Remove references to legacy .NET container repo

aspnetcore/security/docker-https.md
Add in Container User flag for docker run usage per https://github.com/dotnet/dotnet-docker/blob/main/samples/host-aspnetcore-https.md#windows-using-windows-containers from per chat with @mthalman. this change will allow IIS in the container to pick up the certificate.
=> Add container user note

aspnetcore/security/data-protection/configuration/overview.md
Fixes #27196
Thanks @Cybrosys! :rocket:
* Cross-link the concept sections, *Per-application isolation* and *Data Protection and app isolation*, both ways to the *SetApplicationName* section, and explain the connection between the discriminator and the app name setting.
* Add the discriminator property `ApplicationDiscriminator` (via API doc link) in the three relevant sections.
* For 6.0 or later, show a 🙈 **_RexHak_**&trade; 🙈 that will allow the dev to quickly log out the value of the discriminator for troubleshooting purposes. I think this would've helped you, @Cybrosys, quickly see that your VM instances have different physical paths yielding different discriminators assigned by the framework (🤔 *guessing*).
* I had to add "later in this article" to the line ...
> For more information …
=> Clarify ApplicationDiscriminator property

aspnetcore/release-notes/aspnetcore-7.0.md
=> Add PDS to What's new

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #26465
Brennan, this is a bit *drafty* at the moment, but it's probably worth sorting out the SignalR settings for this before I copy content for multiple versions of the content ... and even across docs, since we probably need these updates for the hosted WASM case, too.
This PR is mostly about addressing Javier's ask at ...
**Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.**
https://github.com/dotnet/aspnetcore/issues/42778#issuecomment-1188852129
There are several **permutations** of the configuration. Ultimately, I'm trying to cover both hosting models, WebSockets (primary) and Long Polling (fallback), and server/client config for when latency is spawning the reconnection UI.
The critical piece is Lines 754-828 in …
=> Blazor-SignalR configuration updates

aspnetcore/mvc/advanced/custom-model-binding/samples/2.x/CustomModelBindingSample/Controllers/BoundAuthorsController.cs, aspnetcore/mvc/advanced/custom-model-binding/samples/3.x/CustomModelBindingSample/Controllers/BoundAuthorsController.cs
Related #10341
Updating the `route parameter name` to make the sample code functional, however, this code produces a bad OpenAPI documentation, and we should review it later.
=> Changing route parameter name

aspnetcore/blazor/fundamentals/routing.md, aspnetcore/mvc/views/razor.md
Fixes #27262
Thanks @cdomino! :rocket: ... Let's see how this composes. I add it to the Blazor *Routing and Navigation* topic right near the top where route templates are first called out. I also add it to the `@attribute` directive coverage in the Razor syntax doc. I think the use of the `diff` (the minus line first will be red ... i.e., representing removal/replacement ... and the plus line second in green ... i.e., representing the replacement line) will work well as a SxS presentation reinforcing that this is an **_alternative_** to `@page` directive/string literal routing. I'll hold here for a bit to give you a chance to look ... *but don't take too long!* We're rapidly getting .NET 7 coverage in and don't want PRs to linger and generate merge conflicts 👹😨😄🏃🏃🏃🏃.
=> Constant-based route templates

aspnetcore/fundamentals/minimal-apis/test-min-api.md, aspnetcore/release-notes/aspnetcore-7.0.md
Fixes #26352
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/test-min-api?view=aspnetcore-7.0&branch=pr-en-us-27267#iit7)
=> update testing with IResult types

aspnetcore/blazor/fundamentals/logging.md
=> Update WASM auth logging section

aspnetcore/fundamentals/minimal-apis.md
In the example for [optional parameters](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#optional-parameters), the route registered is `app.MapGet("/products", (int? pageNumber) => $"Requesting page {pageNumber ?? 1}");`.
If you call the API with `/products/two` it will return a `404` and not throw an exception as the documentation indicates.
See the attached screenshots.
=> Minimal APIS Optional Parameters example /products/two will return a 404 and not throw

aspnetcore/tutorials/razor-pages/model.md
Using dotnet-aspnet-codegenerator was producing the result zsh: command not found: dotnet-aspnet-codegenerator using the .NET CLI on mac.  The alternative dotnet aspnet-codegenerator worked as intended. Updated docs here to use dotnet aspnet-codegenerator  command instead.
=> update dotnet-aspnet-codegenerator command

aspnetcore/blazor/tooling.md
=> WASM build tools additional coverage

aspnetcore/blazor/components/data-binding.md, aspnetcore/migration/60-70.md, aspnetcore/release-notes/aspnetcore-7.0.md
**_Ready!_** ... but let me try to reach ⚔️ *Sir Artak* 🛡️ and ⚔️ *Sir Dan* 🛡️ of *.NETtingham* 🏰 to see if they'd like to look before merging. ~If I don't get a response soon (1pm CST), I'll merge and circle around later with them.~
Dan, Artak ...
* Some of the commented-out content is IN PROGRESS stuff. I'll activate it later.
* Some of it is on HOLD because I'm not sure we would call them out. I'm 👂 if you see some of them that I should activate. If not, I'm going to 🔪 the HOLD ones later.
Review in progress. We should have this merged this merged in a few hours.
=> Blazor What's New and Migration guidance

aspnetcore/release-notes/aspnetcore-7.0.md
=> What's new HTTP/2 perf

aspnetcore/blazor/progressive-web-app.md
Fixes #27247
... ~**_BUT_** ... this needs to go ON HOLD until the PU resolves what's going on. There might have been a PU fix for the underlying problem, so they'll need to tell me what the workaround is supposed to solve in light of the PR that may have fixed it. Discussion is taking place on https://github.com/dotnet/aspnetcore/issues/39252.~
This coverage seems fine for now. There's a new PU issue to consider the change (`updateViaCache: 'none'`) ... among other things ... for the project template for .NET 8. I'll refactor the language here for .NET 8 docs if this becomes the default.
Cross-ref: https://github.com/dotnet/aspnetcore/issues/44635
=> Prevent disk caching of service-worker-assets.js

aspnetcore/security/authentication/index.md
Contributes to #26682
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-7.0&branch=pr-en-us-27310#authentication-concepts)
=> default scheme

aspnetcore/fundamentals/minimal-apis.md
- Add new "special types" introduced in ASP.NET Core 7.
- Add links to special types in the 6 and 7 versions of minimal-apis.md\
- Add missing backtick after `[AsParameters]`.
[Internal Review link](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-27319#binding-precedence-1)
=> Fix and improve minimal APIs binding precedence section

aspnetcore/fundamentals/minimal-apis.md
This PR moves the [Bind the request body as a Stream or PipeReader](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#bind-the-request-body-as-a-stream-or-pipereader), [Parameter binding for argument lists with [AsParameters]](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#parameter-binding-for-argument-lists-with-asparameters), [File uploads using IFormFile and IFormFileCollection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection) from the top of the TOC to under "[Request Handling](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#request-handling-1) > …
=> Fix minimal-apis.md's TOC

aspnetcore/toc.yml
The sub-node title for this group of topics is "JavaScript interop," and I've already merged the new JS interop article PR to use the name "JS [JSImport]/[JSExport] interop," so let's go with "JS" over "JavaScript" for each entry in this sub-node.
mmmmmmmmmm ...
Let's just go with "[JSImport]/[JSExport] interop" for that article.
=> Thin the Blazor "JavaScript" names to "JS"

aspnetcore/toc.yml
Without an escape ...
```yaml
- name: [JSImport]/[JSExport] interop
```
... it breaks the build. With an escape (`\`), it shows it ...
I'll strip the brackets off of the name. That's fine for this entry.
No giant rush to merge this to live. The presence of the backslash is trivial at the moment.
=> Escape didn't work in name

aspnetcore/fundamentals/minimal-apis/openapi.md
Fixes #26818 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0&branch=pr-en-us-27348#multiple-response-types)
=> Add information about multiple return types

aspnetcore/fundamentals/minimal-apis.md
=> Add route groups section

.repoman.yml, aspnetcore/client-side/dotnet-interop.md, aspnetcore/client-side/import-export-interop.md, aspnetcore/toc.yml
Fixes #27016
[Internal Review Topic](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/import-export-interop?view=aspnetcore-7.0&branch=pr-en-us-27311)
=> Run .NET from JS article

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #27320
* I assume that a connection failure can also occur because the `ClientTimeoutInterval` isn't long enough on the server. I apply the same guidance to this as for the `ServerTimeout` on the client, namely that it should be at least double the keep-alive. I also say that when changing any of these on one side (server or client) that matching them on the other side (server or client) is sensible.
* When creating a new hub connection in a component, the `serverTimeoutInMilliseconds` / `keepAliveIntervalInMilliseconds` aren't reflected in `Microsoft.AspNetCore.SignalR.Client.HubConnection.ServerTimeout` / `Microsoft.AspNetCore.SignalR.Client.HubConnection.KeepAliveInterval`. AFAICT, they must be changed manually by the dev in the component where the hub connection is created. …
=> Blazor SignalR configuration updates

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Addresses #27374
* Add two headings and a line of text to each to clarify the hosting model scenarios.
* Strike the `Blazor.start` example from the hosted WASM scenario. That code never runs AFAICT, so it looks like there either is no app-level hub analogous to the Blazor Server app hub or the hub created in a hosted WASM scenario doesn't call `configureSignalR`.
=> Follow-up SignalR-Blazor updates

aspnetcore/blazor/fundamentals/routing.md
This PR changes the wording of the `NavigationLock` description to make it a little more obvious what "lock" refers to.
cc @mkArtakMSFT
=> Update 'NavigationLock' description

aspnetcore/release-notes/aspnetcore-7.0.md
=> What's new Kestrel full certificate chain improvements

aspnetcore/blazor/state-management.md
Fixes #27296
cc: @lonix1 @ShaunCurtis
Along with what I added on #27455, let's cross-link the issue discussion. That will surface that discussion and example approaches better than just relying on the **View all page feedback** link, which is probably rarely seen by devs reading topics ... well ... rarely seen by ***ME!*** 🙈🤣
=> Add an additional cross-link

aspnetcore/release-notes/aspnetcore-7.0.md
[Internal Review - New Section - Http/2 WebSockets support](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-27466#http2-websockets-support)
Fixes #27442
=> Add HTTP/2 WebSockets to What's New in 7

aspnetcore/release-notes/aspnetcore-7.0.md
This API has existed since net6.0 so it doesn't need to be included in the release notes. `WithOpenApi` and the package are the new APIs we want to document.
=> Remove net6.0 API from net7.0 release notes

aspnetcore/fundamentals/minimal-apis/min-api-filters.md, aspnetcore/fundamentals/minimal-apis/openapi.md, aspnetcore/fundamentals/minimal-apis/parameter-binding.md, aspnetcore/fundamentals/minimal-apis/route-handlers.md, aspnetcore/fundamentals/minimal-apis/security.md, aspnetcore/fundamentals/minimal-apis/test-min-api.md, aspnetcore/fundamentals/minimal-apis/webapplication.md, aspnetcore/toc.yml
This PR switches minimal TOC titles and page titles for Minimal API apps. It also replaces references to "minimal applications" with "minimal apps".
=> Switch minimal TOC titles and page titles

.github/workflows/quest-bulk.yml, .github/workflows/quest.yml, quest-config.json
This PR adds the configuration for the Quest import GitHub action.
Before merging this PR, follow the instructions [here](https://github.com/dotnet/docs-tools/tree/main/actions/sequester#installation-and-use) to create the API KEY secrets. Then, once this is installed, it will start updating work items.
Note: To import items in bulk, when those have already been labeled, you can run the `quest-bulk` action via the GitHub UI to import all issues already labeled.
=> Add config for Quest import

aspnetcore/grpc/interceptors.md
Using ServerLoggerInterceptor everywhere in the document, because that is the type name also used by the samples, ie. when registering the interceptor to the services.
Fixes #27375
=> Matching type names of the sample server interceptors

aspnetcore/release-notes/aspnetcore-7.0.md, aspnetcore/security/authentication/index.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26682
=> What's new defaut scheme

aspnetcore/fundamentals/middleware/index/snapshot/Chain/StartupMap.cs, aspnetcore/fundamentals/middleware/index/snapshot/Chain/StartupMapWhen.cs, aspnetcore/fundamentals/middleware/index/snapshot/Chain60/ProgramMap.cs, aspnetcore/fundamentals/middleware/index/snapshot/Chain60/ProgramMapWhen.cs, aspnetcore/fundamentals/middleware/index/snapshot/Chain60/ProgramMultiSeg.cs, aspnetcore/fundamentals/middleware/index/snapshot/Chain60/ProgramUseWhen.cs
I noticed a typo in an article on learn.microsoft.com. The tag was open, but not closed. I think it was supposed to use "Hello from non-Map delegate." inside the p tag.
If so, I suggest using this quick fix. Thanks!
=> Corrected a typo at StartupMap.cs

aspnetcore/blazor/components/cascading-values-and-parameters.md, aspnetcore/blazor/components/layouts.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/globalization-localization.md
Fixes #27515
Thanks @nicholasyin! :rocket:
* I updated the snippet sample apps from which the `MainLayout.razor` files are drawn for display. I think I see what went wrong with them: During preview of each release, I create new snippet sample apps so that I can link them into new content for the upcoming release. The product unit made a mistake in the 6.0 timeframe and missed an update that they had to go back in and fix for the laytouts, ***but it was too late for me*** 😨 ... I had already created the snippet sample apps from the incorrect templates. I didn't catch their later fix, so I didn't update them in the `blazor-samples` repo. Anyway, it's fixed now and for the future .NET 7 release.
* Flexbox is mentioned and cross-linked now.
* I found a few more 😈 to squash for the `<main>` …
=> MainLayout content updates

aspnetcore/blazor/javascript-interoperability/index.md
Addresses #26364 
Per merge of https://github.com/dotnet/runtime/issues/53539 and per https://github.com/dotnet/AspNetCore.Docs/pull/25283, remove the remark on `DateOnly`/`TimeOnly` and PU cross-link. It's resolved for 7.0, and I'm going to 🔪 it a few days early here just to get it out of the way.
=> Remove point-in-time remark for 7.0

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md
Fixes #27531
Thanks @Bouke! :rocket: ... I'll remain 👂 on your PU issue in case there's more to address. If so, I'll do that on a follow-up PR. This is ***NOT*** a good time to leave PRs lying around with the .NET 7 release and all of the docs work needed to activate the new release docs ... 😈 ***merge conflicts!*** 😈
I added the coverage both to the *Prendering* doc ***and*** in the *Persist component state* TH doc. That should surface it well.
I also included the exact client-side message about the circuit not initializing, which can help devs find this content via a string-based docs search.
Since most apps won't hit the limit  ... we hope 🤞🍀 and is consistent with the lack of issues generated on this particular error, here on the docs repo anyway, I'll hold off on placing this info …
=> Message size limit and prerendering state size

aspnetcore/client-side/dotnet-interop.md
=> Update JS module code for release

aspnetcore/blazor/javascript-interoperability/import-export-interop.md, aspnetcore/client-side/dotnet-interop.md
Fixes #27554
Thanks @yugabe! 🚀 
@pavelsavara ... It's not my intention here to use an example that's an already-imported global FN by the framework, but I only see `console.log` in a helper class for testing ...
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.InteropServices.JavaScript/tests/System.Runtime.InteropServices.JavaScript.UnitTests/System/Runtime/InteropServices/JavaScript/JavaScriptTestHelper.cs#L17-L18
If it's only in test code there, the example on this PR should be fine unless you want to change it to something else. It would be easy for devs to play with this `Log` method they want to drop this into a local test app because `console.log` is already there.
***ALSO***, I modified the signature from `public` to `internal` ... head-check the 🦖 on that …
=> [JSImport] global FN guidance

aspnetcore/fundamentals/minimal-apis/openapi.md
Swashbuckle.AspNetCore does not support the endpoint summary attributes yet so we'll have to do this for now.
See https://github.com/dotnet/aspnetcore/issues/45082.
=> Remove invalid summary setting strategies

.github/workflows/holiday-blazor-comment.yml
As you know, I've had great success thus far with ✨ ***auto-magical*** ✨ new Blazor issue management with automatic labels, project assignment, and assignees ( 🦖 ***ME!*** 😄) per Andy's bits 🥇.
Now, I'd like to see if I can have ***automatic comments*** when a new Blazor issue is opened. *May the* 🙏***server gods*** 🙏 *bless me with this feature!* 😆
A problem that I always hit during the holidays is that I manually need to apply my *'I'm out for the holiday ... I'll get back to you ASAP here when I get back'* message to new issues. It would be super cool to have that message automatically applied along with the rest of the automatic issue config. If this works 🍀🤞 ... *and I think it will* ... I should be able to focus on my 🏖️ vacation with only one daily check-in for emergency bugs, …
=> Test holiday Blazor automatic commenting

aspnetcore/blazor/hybrid/tutorials/maui.md
=> Blazor MAUI tutorial followup updates

.github/workflows/holiday-blazor-comment.yml
@Rick-Anderson ... I'm changing from pinning via the SHA to the version number, which I think is how **create-pull-request** is managed. I'm leaving the `token` in place just in case that's required. It's probably harmless if it isn't required. I'll monitor for a 💥 on that just in case.
=> Change SHA to version number

aspnetcore/blazor/globalization-localization.md
Fixes #27594
Thanks @AlessandroMartinelli! :rocket:
@hishamco, I think we should have a tidbit on this in the Blazor loc doc. If we merely cross-link to the main doc set for this, it's just a bit too cryptic for a typical dev and certainly too cryptic for ***new-to-Blazor/new-to-loc/new-to-.NET devs***. This section makes it 💀 ***dead simple*** 💀 to set up with the existing examples in the topic.
@AlessandroMartinelli ... WRT ...
> * Localization keys (the terms to be translated) taken from a constants file. This would help guarantee uniqueness of keys but would introduce a little overhead since all terms have to be inserted in the constants file first.
> * Localization keys sparsed among the .razor files. This would allow to avoid the constants file overhead, but it would be harder to …
=> Blazor loc shared resource approach

aspnetcore/client-side/bundling-and-minification.md
Fixes #27508
Thanks @pluraltouch! 🚀 
Rick, I had a couple of minutes this morning to touch-up a few bits (downloading and installing Xcode on the MacBook ⏳😠) ...
* The impacts section with the right calcs (% reduction).
* I took out the word "significant," which has specific meaning in scientific contexts. I admit that we're only weakly within the bounds of "computer ***science***" here as a formal science because we aren't reporting the results of empirical investigation. However, I'd feel better if we don't use the word "significant" when referring directly to ***data***. That's kind'a 😨 if we ever have researchers looking at our docs. I checked the whole doc set on the use of the word. Of the ~30-40 times "significant" is used, this is the only spot where it's used to directly address …
=> Bundling and minification updates

aspnetcore/blazor/file-uploads.md
Looks like a pesky CR/LF 😈 got in there and fouled up the `no-loc` markdown.
=> Patch a no-loc blockquote

aspnetcore/blazor/components/index.md
Fixes #27703
Thanks @gregoryagu! 🎸 ... I'm going to (***super quickly*** 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️) change the component name/path to fix this. I figured that would be a bit faster than changing the `people` object, and I'm in a real rush this week to wrap up as much as I can before the 🦃 weekend 😄. I have a ***heavy schedule*** ⛰️⛏️😅 right thru the EOY. The related changes to the snippet sample app are at https://github.com/dotnet/blazor-samples/pull/59, and I guess it didn't break on snippet build. It ***WAS*** catching those because I fixed a few of these. Oh, well. No worries. It will be fixed ***NOW*** 😆. Thanks for the report.
=> Rename People component

aspnetcore/tutorials/razor-pages/model.md
[Internal review - Add Scaffold section - for VSC](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&branch=pr-en-us-27700&tabs=visual-studio-code)
Fixes #27614 
- Added namespace for -dc class for windows/Linux on VSC tab.
- Noted that class with namespace is used for -dc for VSC tab.
Per workaround suggested by dev team until scaffold tool is updated.
=> Add namepace for datacontext as workaround for CLI scaffolding

aspnetcore/fundamentals/configuration/index.md
- The order between `WebApplicationBuilder` and the other hosts are different
- `ASPNETCORE_`-prefixed environment variables have the lowest precedence with `WebApplicationBuilder`
I reponed https://github.com/dotnet/aspnetcore/issues/17963 to track aligning this behavior in .NET 8.
I also made a breaking change announcement about this at https://github.com/aspnet/Announcements/issues/498. At first, I thought https://github.com/dotnet/runtime/issues/78583 was an issue related to this intentional breaking change, but it appears to have been caused by an unintended behavioral change specific to the content root. So, I'm still not sure if anyone has really been broken by this change, but I still think it's probably worth putting in the list of breaking changes between .NET 6 and 7.
=> Update default host configuration sources list

aspnetcore/blazor/hybrid/index.md
Fixes #25679
I can't find API coverage on `System.AppDomain.CurrentDomain.UnhandledException`. I've added it to a list of temporarily-MIA API on #26044.
There's one more thing we can knock out here ... 
**Blazor Desktop tenets: Global readiness**
https://github.com/dotnet/maui/issues/2532
... and I'll add that right now 🏃‍♂️.
I had to make several phrasing guesses to get Pranav's remarks in here from ...
https://github.com/dotnet/maui/issues/2532#issuecomment-1026378294
It probably needs some work on review.
WRT ...
> There are some instances of users trying this in their [Xamarin.Forms apps](https://stackoverflow.com/a/44417380) which relies on triggering an event causing their app to re-render. A determined user could do something similar to re-render the root component …
=> Exception handling and Glob/Loc in Blazor Hybrid

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Per https://github.com/dotnet/aspnetcore/issues/29342#issuecomment-1317311677, this looks like it was fixed. It isn't repro-ing in .NET 7. I'm going to remove the NOTE from the 7.0 or later coverage and leave it for earlier versions ***just in case*** 😈.
=> Remove NOTE

aspnetcore/security/docker-compose-https.md
The file had references to the `mcr.microsoft.com/dotnet/core/samples` tag which is [no longer a supported tag](https://github.com/dotnet/dotnet-docker/blob/9eb203c4890d3d0122d3939614ff25d68fc46d6e/README.samples.md?plain=1#L93), and no longer exists.
This updates it to the supported tag: `mcr.microsoft.com/dotnet/samples:aspnetapp`
Related:
- https://github.com/dotnet/AspNetCore.Docs/pull/27202
- https://github.com/dotnet/dotnet-docker/discussions/3674
- https://github.com/dotnet/AspNetCore.Docs/issues/27194
=> Update container reference to supported tag

aspnetcore/fundamentals/environments/samples/6.x/EnvironmentsSample/Pages/About.cshtml
Fixed broken code render when embedded in documation on:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-7.0#environments
(ASP.NET Core 3.1 to 7.0 variations uses the same code sample)
The environment tag helper code  &lt; was rendered as actual HTML tags in the embedded code example, creating invalid  code.
=> Simplified the code so it renders correct HTML when embedded

aspnetcore/blazor/fundamentals/signalr.md
This PR adds an example showing how to configure a Blazor Server app to automatically refresh the browser if reconnection to the server fails.
Customers have been asking for a way to keep the existing Blazor Server reconnection logic and UI, but modified slightly so that refreshing the browser happens automatically rather than requiring direct user action. We don't have an extensibility point in our current JavaScript API that allows this do be done without reimplementing the full reconnection logic and UI. That said, it's not _that_ much code, so it could be sufficient to provide an example in the docs showing how to achieve this.
I'm opening this initially as a draft PR because there are a few open questions:
1. How complete should the example code be?
* Should we make the example more …
=> Example on how to automatically refresh the browser when Blazor Server reconnection fails

aspnetcore/diagnostics/asp0015.md, aspnetcore/diagnostics/asp0016.md, aspnetcore/diagnostics/asp0017.md, aspnetcore/diagnostics/asp0018.md, aspnetcore/diagnostics/asp0019.md, aspnetcore/diagnostics/code-analysis.md, aspnetcore/toc.yml
Fixes #27366 
Internal review URLs:
File Type | File Name | Published Url
-- | -- | --
content | aspnetcore/diagnostics/code-analysis.md | https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?view=aspnetcore-7.0&branch=pr-en-us-27727
content | aspnetcore/diagnostics/asp0015.md | https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0015?view=aspnetcore-7.0&branch=pr-en-us-27727
content | aspnetcore/diagnostics/asp0016.md | https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0016?view=aspnetcore-7.0&branch=pr-en-us-27727
content | aspnetcore/diagnostics/asp0017.md | https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0017?view=aspnetcore-7.0&branch=pr-en-us-27727
content | aspnetcore/diagnostics/asp0018.md | …
=> Add documentation for new analyzers

aspnetcore/blazor/components/event-handling.md
- Fix typo in JS code
- Mark `EventHandlers` class as public, otherwise Razor compiler will not find it
=> Fix typos in event-handling.md

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #27556
Mackinnion ...
* Today, there's a chasm between mentioning the purpose of the `App` component in the *Project Structure* topic and all of the juicy details in the *Prerendering and Integration* topic. I think we need a short section in the *Components Overview* topic to address static root components ... nothing too detailed or long ... just the basic idea with the cross-links to the *Component Tag Helper* doc and the *Prerendering and Integration* doc. Also, it makes sense to have such a section just above the new section for dynamically-rendered components from JS that was added back at 6.0. Now, we can cover both scenarios back-to-back/SxS ... static via C#/CSHTML root component registration/Tag Helper and dynamic via JS. 
* Javier asked me to flesh out dynamic root …
=> Clarify root component disposal

aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/graph-api.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/zone-pivot-groups.yml
Thanks @hanslai and @damienbod. I'm going to sleep on these updates overnight and make some final touches on Saturday morning. Because of the number of updates here, you might want to wait until after tomorrow morning and inspect the live topic after these updates merge.
=> Blazor MS Graph article updates

aspnetcore/security/authentication/jwt-authn.md
This PR fixes the wrong reference to the `delete` command instead of `remove` in the `user-jwts` tool documentation.
Fixes #27870
=> Fix reference to `delete` command

aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #27908
[Internal Review Topic (links to section)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0&branch=pr-en-us-27909#access-blazor-services-from-a-different-di-scope)
Mackinnon:
The Blazor DI topic is probably the best spot for this.
Questions ❓ ...
1. Is `IJSInterop` a thing? I can't find that API. Did you mean `IJSRuntime`?
1. Is the "Blazor `IServiceProvider`" a `System.IServiceProvider`? I ask to make sure that I have the API cross-links correct.
1. I removed the `_` from `hasCalledOnAfterRender`. I was told that for developer code not to sweat it ... that it was more for framework purposes. I might be a bit off on that tho because the discussion surrounding using the underscore on fields was focused on how we …
=> Access services from a different DI scope

aspnetcore/security/authentication/scaffold-identity.md
Fixes #27921
cc: @fgalarraga
Thanks for the issue, @mattbeasley96. I've reviewed the cross-links, and I want to leave them in this section for a few reasons:
* Javier explains in full detail ***why*** they don't want to build such components into the framework, and we try not to get into design decisions in the docs. We prefer to link to the product unit discussions that explain the reasoning behind framework design decisions.
* Although MS doesn't support the approach, there are helpful tidbits in the discussions, including community sample code that might be helpful to some devs. Also, there are links to sample code in non-MS repos for custom Identity components that are worth taking a look at. 
* If we don't have the links to these discussions, devs are left trying to find these …
=> Update custom Identity component guidance

aspnetcore/web-api/handle-errors.md
Previously this was highlighting some code that wasn't super relevant (unless I'm missing something). Now this will highlight the line mentioned above the snippet.
Current state:
=> Highlight code for suppress map client errors

aspnetcore/host-and-deploy/windows-service.md
Fixes #23847 
This article was updated to 6.0 in https://github.com/dotnet/AspNetCore.Docs/pull/26844, and to 7.0 in https://github.com/dotnet/AspNetCore.Docs/pull/26913
In both cases a reference to .NET Core 3.1 remained in a project file example; that is what this PR corrects.
=> Correct target framework

.openpublishing.redirection.json, aspnetcore/blazor/security/server/threat-mitigation.md, aspnetcore/fundamentals/best-practices.md, aspnetcore/fundamentals/environments.md, aspnetcore/fundamentals/middleware/index.md, aspnetcore/fundamentals/use-http-context.md, aspnetcore/performance/overview.md, aspnetcore/toc.yml
Fixes #26643 
Moving this doc to Fundamentals left us with no overview article for the Performance TOC section, so this PR creates a simple one with a list of links.
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?view=aspnetcore-8.0&branch=pr-en-us-27940)
=> Move and rename "ASP.NET Core Performance Best Practices" doc

aspnetcore/tutorials/signalr/sample-snapshot/3.x/Index.cshtml, aspnetcore/tutorials/signalr/samples/SignalRChat/Pages/Index.cshtml
Fixes #27952
Thanks @smiller7812! 🚀 
🦖 did the following here ...
* Span these rows to 6 columns.
* Use one container.
* Drop the blank (`&nbsp;`) rows.
* Pad a pixel.
* Fill the message box to the cell size.
* Adjust the columns.
* Move the button.
* Have a 🍺😆.
I just tested it locally, and it renders like this ...
=> Restructure container div in example

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/includes/js-interop/circuit-disconnection.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #27974
Thanks @lonix1! 🚀 
The current section is fine for what it covers (`JSDisconnectedException` in Blazor Server apps), so I add a SxS section for the other scenarios. I place this in three spots: It will appear in both JS interop articles. It will also appear in the *Lifecycle* topic.
WRT adding a code example of the `MutationObserver` pattern, I would like to consider it, but I'm buried in work for a while. I added it to a tracking issue that I keep at https://github.com/dotnet/AspNetCore.Docs/issues/24615. I'll consider it in 23H1.
=> Disposal cleanup code pattern

aspnetcore/fundamentals/configuration/index.md
There is a typographical mistake in the Default host configuration sources where the word '**_the_**' is repeated multiple times.
Doc Link -> [Link](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#default-host-configuration-sources)
=> Fixed typo mistake in Default host configuration sources Section.

aspnetcore/fundamentals/configuration/index.md
The **Configure options with a delegate** section has a typo in the link to the `Test2.cshtml.cs` code sample (`optionssamples` in path should be `options/samples`).
=> Fix Options Delegate link

aspnetcore/signalr/hubs.md
As of 7.0-rc1, this is no longer necessary due to https://github.com/dotnet/aspnetcore/pull/42796.
Should we add a caveat for this "con" mentioned int the PR description?
> * `IHubContext` injected and used in Hubs for `InvokeAsync` can still block
I think injecting an `IHubContext` into a hub might be too contrived of a scenario to be worth mentioning. Lengthening the docs to cover every edge case can make things overwhelming. On the other hand, it'd probably be pretty difficult to diagnose if you did happen to run into it.
=> Remove note about increasing MaximumParallelInvocationsPerClient

aspnetcore/blazor/file-uploads.md
Fixes #27893
Thanks @jorgearana! 🚀 ... I'll add a line that states that the fully working implementations are coming up later in the article. This bit is only to address the correct and incorrect ways of accessing the stream data, and it will continue to say what `browserFile` is.
=> Clarify lead-in to examples

aspnetcore/blazor/forms-and-input-components.md
Per #27490 ...
> The paragraph below should not jump into data annotations yet. The reader may have zero knowledge of those concepts at this point and they came here to learn about forms. So let's start from forms.
I add a non-DA example (but maintain the model) prior to the DA-based example.
An early, simple DA example is present for the following reasons ...
* Data annotations are perhaps 15 years old now, integral to most real-world scenarios, conceptually simple, and cross-linked at first mention to our main doc set for those who aren't familiar with them.
* It doesn't go farther than just a `[Required]` and `[StringLength(...)]` at that point. The topic uses DA extensively in the latter example at ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view …
=> Forms and input components updates

aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md
Fixes #28044
Thanks @plastovicka! :rocket:
I'm adding a bit to explain how the Blazor JS engine ***should be blocked*** until the scripts are loaded.
If you take Steve's advice and open an issue for the product unit on [their GH repo](https://github.com/dotnet/aspnetcore/issues) with steps to reproduce and a sample app hosted in GH, please add the following to your opening comment there so that I can follow along ...
```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28044
```
If something comes out of that investigation/discussion that we can add to the documentation, I'll take care of re-opening your original issue and working on it further. Thanks for your issue. This was an important bit to add.
WRT my mention about manually starting the Blazor JS engine, I'm adding …
=> JS interop script location

aspnetcore/mvc/models/file-uploads.md
Fixes #28042
Thanks @Taylor365! 🚀 
Rick, I think we can harden this and still help readers by just giving them the search result because there are dozens of file signature databases out there. I don't think we need to pick a winner.
I left the word "and" in there for 'use a dB' ***AND*** 'consult official file specs.' I add a sentence to this to clarify the "and" recommendation. I only say that official file specs ***may*** confirm a valid selection. I checked on a few official specs to support this remark, and it's true. Some number of official specs *do mention* the "magic number" file sig for their file type in their official guidance. I think we can go with this remark.
I don't have further changes. Please merge when you've reviewed or made additional mods to this.
=> Update broken link

aspnetcore/fundamentals/request-features.md, aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/fundamentals/servers/kestrel.md, aspnetcore/fundamentals/servers/kestrel/options.md, aspnetcore/fundamentals/url-rewriting.md, aspnetcore/host-and-deploy/iis/advanced.md, aspnetcore/host-and-deploy/iis/index.md, aspnetcore/host-and-deploy/linux-apache.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/performance/caching/middleware.md, aspnetcore/performance/caching/response.md, aspnetcore/performance/response-compression.md, aspnetcore/tutorials/first-mongo-app.md, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/getting-started-with-NSwag.md, aspnetcore/tutorials/min-web-api.md, aspnetcore/tutorials/publish-to-iis.md, aspnetcore/web-api/advanced/formatting.md
Replace all references to obsolete HTTP specifications such as RFC 2616 and RFC 7230-7234 with references to the latest (as of now) HTTP specifications; RFC 9110-9112.
=> Replace references to obsolete HTTP specifications

aspnetcore/blazor/fundamentals/index.md, aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/security/includes/3.1/troubleshoot.md, aspnetcore/blazor/security/includes/5.0/troubleshoot.md, aspnetcore/blazor/security/includes/6.0/troubleshoot.md, aspnetcore/blazor/security/includes/7.0/troubleshoot.md, aspnetcore/security/authentication/scaffold-identity.md
Fixes #28066
@Rick-Anderson ... AFAICT, this gets them all updated. There was one outside of the Blazor node after all ... in the Scaffolding doc.
Since the live link is broken, I'll merge to live now 🏃.
=> Slack Team link update

aspnetcore/host-and-deploy/linux-nginx.md
[Internal Review  - Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0&branch=pr-en-us-27774&tabs=linux-ubuntu)
Fixes #27604
Adding instruction/tabs specific to RHEL and SLES distros.
=> Host-Linux Nginx: Add RHEL and SLES distros

aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Program.cs
As described in the diagnostic [ASP0013](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0013?view=aspnetcore-7.0#rule-description):
> To fix a violation of this rule, use the `Configuration` property on the `WebApplicationBuilder` to modify application configuration directly without the need for an additional `ConfigureAppConfiguration` call.
=> fix ASP0013 violation in snippet_json

aspnetcore/blazor/hybrid/static-files.md
Fixes #27862
[Internal Review Topic](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/static-files?view=aspnetcore-8.0&branch=pr-en-us-28052)
Notes ...
* Adds a JS static file example to the existing examples.
* Shows it via a script file ***and*** via a collocated JS file as a modification to the preceding example at the end.
* Seems like we can remove my earlier remark on setting the **Copy to Output Directory** and go with the default **Do not copy** everywhere. IIRC, it 💥 on me before with the text file, but I'm not seeing a problem now with guiding on the default property value.
=> Add static JS file example

aspnetcore/fundamentals/app-state.md
Fixes #28093
Thanks @baktay! 🚀 
Rick ... I'm playing with some ideas here that I hope will help surface additional concepts surrounding HTTP context-based state management and SignalR apps, including Blazor Server ...
* The section title probably should include "Blazor Server" somehow. The PR uses a slash, but parentheses or a conjunction probably work, too. A conjunction is a bit trickier, since "and" is already there.
* It's not merely "session state" but any HTTP context-based strategy, so I make wording changes along those lines. I don't get into an explicit list tho. For example, use of QS in Blazor Server apps works and is covered in the Blazor docs. I just say here that the "HTTP context-based approaches" aren't going to work.
* The prior heading isn't cross-linked anywhere …
=> SignalR-based (Blazor Server) stage mgmt

aspnetcore/fundamentals/dependency-injection.md
Looks like Orchard Core documentation's URL changed. This PR updates the URL to the latest version of the documentation. Which I think is the same as `dev` in the old URL.
=> Update Orchard Core Documentation URL

aspnetcore/blazor/hybrid/routing.md
Fixes #28131
Thanks @DanielEggers! :rocket: ... It looks like I'll just need to drop the versioned content for >=7.0, since the PU changes occurred for the 6.0 release.
[**Internal Review Topic**](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0&branch=pr-en-us-28132)
Mackinnion or Tanay: Could either of you take a look at the [internal review topic](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0&branch=pr-en-us-28132) and confirm that this is all we need? Also note that there's a separate issue that I haven't quite reached yet, but I'm getting there ...
**Missing basics of navigation for hybrid app**
https://github.com/dotnet/AspNetCore.Docs/issues/25872
It looks like …
=> Repair versioning

aspnetcore/blazor/components/index.md
Fixes #28135
[Internal Review Topic (links to section)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-8.0&branch=pr-en-us-28140#render-razor-components-from-javascript)
Mackinnon: @SQL-MisterMagoo [asked in 2021 about coverage for javaScriptInitializer in a PU issue](https://github.com/dotnet/aspnetcore/issues/37181#issuecomment-940567797) that I didn't see until yesterday. I'm going to work on that here ***and*** use the opportunity to knock up a quick example of the whole feature, along the lines of my usual ***fully-working, cut-'n-paste demos*** 👍 that makes it easy for devs to see how features compose.
In addition to just checking the basic technical aspects, I've hit a knowledge gap (not surprising for the 🦖🙈) on part of the coverage. …
=> Document javaScriptInitializer

aspnetcore/fundamentals/servers/httpsys.md
=> Remove the redundant entries here and link to the API docs instead

aspnetcore/blazor/images.md
=> Images article versioning

aspnetcore/blazor/hybrid/routing.md
Fixes #25872
Thanks @Christoph1972! 🚀 ... Sorry for the delay. We had a busy .NET 7 release cycle for docs late last year. I'm just now wrapping up last year's lower-priority issues ⛰️⛏️😅.
[Internal Review Topic](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0&branch=pr-en-us-28216)
David ...
* I blatantly ***stole*** 🚓👮 some of your language from the issue 😄. Thanks for those remarks.
* Thanks again for the `MainPage` tip. I felt there was ***one silly thing*** 😈 that I was doing wrong. I've placed that change here to head off anyone else from missing it. It also plays into my ***fully-working, cut-'n-paste examples*** effort across the Blazor docs node. Since I started providing these a few years ago, the number of docs issues has dropped …
=> Blazor Hybrid (MAUI) page-component navigation

aspnetcore/migration/proper-to-2x/index.md
Currently we link to a blog post on how to do ASP.NET to ASP.NET Core migration. But we now have a docs [section](https://learn.microsoft.com/aspnet/core/migration/inc/overview) for this that we should link to instead.
=> Update links to incremental ASP.NET migration

aspnetcore/fundamentals/servers/kestrel.md, aspnetcore/fundamentals/servers/kestrel/diagnostics.md, aspnetcore/fundamentals/servers/kestrel/options.md
Fixes #23945
* [Internal review URL - Kestrel](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?branch=pr-en-us-28212)
* [Internal review URL - Kestrel options](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?branch=pr-en-us-28212)
* [Internal review URL - Kestrel diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/diagnostics?branch=pr-en-us-28212)
=> Timeouts disabled when debugger is attached

aspnetcore/fundamentals/minimal-apis/security/7.0-samples/MinApiAuth/MinApiAuth/Program.cs
Move the comment about requiring the JwtBearer package to the sample that actually uses JwtBearer.
=> Fix comment in minimal APIs AuthN sample

aspnetcore/fundamentals/servers/index.md, aspnetcore/fundamentals/servers/kestrel.md, aspnetcore/fundamentals/servers/kestrel/http2.md, aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/supported-platforms.md, aspnetcore/grpc/troubleshoot.md, aspnetcore/tutorials/grpc/grpc-start.md
Fixes https://github.com/dotnet/aspnetcore/issues/45569
On some pages, I've left a note that macOS + TLS doesn't work before .NET 8, rather than removing mentioning it completely. I did that because I think there could be people using older versions of .NET who visit those pages to get troubleshooting advice.
=> Update docs for macOS + TLS on .NET 8

aspnetcore/blazor/components/data-binding.md
Fixes  #28254
Thanks again, @lonix1! ⛵ 
This is the ***one*** reason that Javier gave rewritten into 🦖-speak 😄. Let's go with it, as I'm not aware of any other reasons than the one that he provided. If you want to inquire further with him/them, open an issue on the PU's repo and add my ping line so that I can see what he/they say ...
Please add ...
```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28254
```
=> Enhance remark on motivation for bind:get/set

aspnetcore/fundamentals/environments.md
Now `DOTNET_` variables have higher precedence then  `ASPNETCORE_` ones which affects the `ASPNETCORE_ENVIRONMENT` too. See [this breaking change arrticle](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/environment-variable-precedence)
FIxes #28242
=> Reflecting ASPNETCORE_ and DOTNET_ breaking change in .NET 7

aspnetcore/fundamentals/minimal-apis/security.md
Currently the lines highlighted aren't relevant to the section (see image below). This change should highlight the lines associated with creating and using the authorization policy.
=> Fix highlighted lines in authz policies example

aspnetcore/fundamentals/routing.md, aspnetcore/includes/routeSlash.md, aspnetcore/mvc/controllers/routing.md
Fixes #27900
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0&branch=pr-en-us-28213#routing-with-special-characters)
- unzip
=> Warn about routing with special chars /6

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/includes/js-interop/synchronous-js-interop-call-js.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #27536
Thanks @lonix1! 🎸 
There are two side updates that I think must be accomplished and are on this PR:
* As part of the work for this PR, I found an example that doesn't show the proper disposal pattern.
* I think it's a good idea to call out that trying to perform any kind of DOM cleanup on location changes is a BAD idea. I add an IMPORTANT note to the *Routing* article.
This PR adds new section to the *Lifecycle* topic and the two JS interop topics that ***reiterates to reinforce*** all of the existing demonstrations and written content on disposal of JS interop objects.
We exclusively show `IJSObjectReference`/`IJSInProcessObjectReference` created and disposed ***on the .NET side***. If there was something to say about disposal of that on the JS side, I'm not sure what to say …
=> JS interop disposal guidance updates

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #26980
Thanks @contractcooker! 🚀 ...
* I finally reached your issue. Sorry for the delay. It was a busy .NET 7 release season late last year, and I'm just now wrapping up last year's backlog issues.
* Two things that I found out improving the JS interop coverage:
* I found a bug in one of the examples that didn't prevent it from running ... the example just wasn't composed correctly. I found one line in the article's disposal example for instance methods that required an update. (I wish that I had known about this because I would've marked your issue as a 🪲 and worked it last year.)
* Also, I found a blasted ***spelling error*** 😈 in one of the code examples 🙈 ... that HEX array byte array support example that writes out a Serenity movie quote via JS interop ... that code example …
=> JS interop updates

aspnetcore/tutorials/razor-pages/model.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&branch=pr-en-us-28290&tabs=visual-studio-code#scaffold-the-movie-model)
Fixes #28299 
The page currently instructs you to run an ASP.NET Code Generator command using the relative output folder "Pages\Movies" if you're using Windows and "Pages/Movies" otherwise. However, I was going through this tutorial on a Windows machine using VS Code and found that these instructions generate a PagesMovies folder, rather than a Pages/Movies folder. I resolved the issue by using the non-Windows command, which is why I suggest this change.
=> Change ASP.NET Core Code Generator command

aspnetcore/blazor/debug.md
Blazor WebAssembly apps used to launch by default with an HTTPS address, but users kept hitting issues with that so we switch back to HTTP by default. I copied the url property from the doc and it didn't work because the app was listening on an HTTP address, not HTTPS.
=> Switch VS Code launch.json URL to be http instead of https

aspnetcore/signalr/redis-backplane.md
SignalR Redis backplane documentation informs about the trade-off that increasing the number of nodes in a Redis Cluster decreases the message throughput of the backplane ([source video](https://www.youtube.com/watch?v=6G22a5Iooqk), and [source slides](https://www.slideshare.net/RedisLabs/redis-day-tlv-2018-scaling-redis-pubsub)).
Also mention that in the SignalR app, all the Redis nodes should be included in the Redis connection string or added as `EndPoints` in the `ConfigurationOptions` object.
Reference issue: https://github.com/dotnet/aspnetcore/issues/46408
=> Improve SignalR Redis Cluster section

aspnetcore/grpc/authn-and-authz.md
It's not necessary to have UseEndpoints for Authentication/Authorization. You can just use MapGrpcService instead.
There is no issue associated with this doc, so I didn't referenced any.
=> Removed UseEndpoints

aspnetcore/blazor/hybrid/security/index.md
It took me a while to figure out there was a typo in the case of the letter i instead of upper case I.
=> Fixed typo in code sample

aspnetcore/blazor/globalization-localization.md
Fixes #28367
Updating this remark for .NET 8 is tracked by the [.NET 8 tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/28161).
=> Update WASM reduced locale support remarks

aspnetcore/blazor/debug.md, aspnetcore/blazor/tooling.md
Fixes #28382
Thanks @ScottPeabody! 🚀 ... This should help clear up the confusion about the `launchSettings.json` file in the **Client** project when the hosted app is run from the **Server** project. The remark(s) shouldn't appear in the *Host and deploy* node because this file is for local, debug/`dotnet run` runs of the app. Therefore, I only place it in the *Debug* and *Tooling* topic content where they speak to how to run a hosted WASM app (i.e., from the **Server** project).
WRT Kestrel settings at play with anything in Blazor, you'd need to call out the specifics that might be missing. The host app (the **Server** project) is just an ASP.NET Core app, so all of the main doc set guidance for configuring Kestrel applies. The only rub is that the app is serving the Blazor WASM app. I'm …
=> Launch settings file for hosted WASM apps

aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/forms-and-input-components.md
=> Update cross-link/content for image preview

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
=> Change placeholder

aspnetcore/grpc/json-transcoding.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-8.0&branch=pr-en-us-28454#usage)
Fixes #27206
Clarifying where to add google/api/http.proto and google/api/annotations proto files in an ASP.NET Core gRPC project
=> gRPC json transcoding - Clarify proto path

aspnetcore/blazor/file-downloads.md, aspnetcore/blazor/images.md, aspnetcore/includes/js-collocation.md
Patch needed that I noticed in passing on https://github.com/dotnet/AspNetCore.Docs/issues/28456. The example in this file is no longer the exact example in the cross-linked content, so I'm just going to 🔪💀 that line. 
I'll also take Tanay off of the `ms.author` metadata, which I see flagged on the build report.
=> Patch JS collocation content

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/security/server/threat-mitigation.md
=> Threat mitigation article updates

aspnetcore/tutorials/signalr.md
Fixes #26776 
[Review URL -  Both VSC and VS for Mac tabs](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0&branch=pr-en-us-28475&tabs=visual-studio-code#add-the-signalr-client-library)
=> SignalR: libman: command not found

aspnetcore/mvc/views/razor.md
The only two most prominent places I could find this docummented are:
* [Conditional Attributes in Razor View Engine and ASP.NET MVC 4](https://www.davidhayden.me/blog/conditional-attributes-in-razor-view-engine-and-asp.net-mvc-4)
* [Jon Galloway - ASP.NET MVC 4 Beta Released!](https://weblogs.asp.net/jongalloway/asp-net-4-beta-released)
As well as these two Stack Overflow posts:
* [Conditional HTML Attributes using Razor](https://stackoverflow.com/questions/8061647/1366033)
* [ASP.NET MVC razor - Conditional attribute in HTML](https://stackoverflow.com/questions/9399531/1366033)
But couldn't find anything about this behavior in the official docs.  
Since it's more likely that people will use these attributes with variables, instead of inlined hard coded values, the example might be more …
=> document conditional attribute rendering in razor

aspnetcore/fundamentals/index.md, aspnetcore/toc.yml
Given we document 3 hosts in the overview, I think there should be three listed in the TOC as well.
[Internal Review Link](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-7.0&branch=halter73%2Fwebapplication-host-toc&tabs=macos#host).
=> Add WebApplication under "Host" in TOC

aspnetcore/fundamentals/localization.md, aspnetcore/fundamentals/localization/make-content-localizable.md, aspnetcore/fundamentals/localization/provide-resources.md, aspnetcore/fundamentals/localization/select-language-culture.md
Fixes #17167 
* The goal of this PR is just to split up the long doc, without addressing the doc's update-and-improve needs; issues and PRs for updating and improving the content can then focus on individual articles.
* The split follows the original article's structure of 3 main sections following the intro. Each of the three main sections becomes a separate article.
* The current article says it's for .NET 5.0 but the code examples all come from the 3.x sample; I left all of that unchanged in this PR. There was a .NET 6 stub which was never used; I deleted it and will add .NET 7 stubs after this PR is merged. The .NET 6 stub deletion is in a separate commit from everything else.
File Type | File Name | Published Url
-- | -- | --
content | aspnetcore/fundamentals/localization.md | …
=> Split localization article into multiple articles

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/js-spa-frameworks.md, aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/hybrid/class-libraries.md, aspnetcore/toc.yml
* Break out the JS apps/SPA frameworks sections into a new topic.
* Move the component class remarks to the "namespaces" section and rename the section "Class name and namespaces."
=> Breakout sections and updates

aspnetcore/blazor/security/includes/3.1/troubleshoot.md, aspnetcore/blazor/security/includes/5.0/troubleshoot.md, aspnetcore/blazor/security/includes/6.0/troubleshoot.md, aspnetcore/blazor/security/includes/7.0/troubleshoot.md, aspnetcore/blazor/security/includes/azure-scope.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
Addresses #28001 
cc: @mrpmorris ... I did find two small-ish problems to fix. The `appsettings.json` file for the server API didn't have the right config in the part of the file that *wasn't being described by the text in that part of the article*. I'm not sure if that confused anyone. No one wrote in to me about it. Second, the `Scopes` entry for the file wasn't included in earlier updates since the release of 6.0. I'm fixing these two problems on this PR, and I will take this live immediately.
I'm also making additional changes here to clarify the guidance. It's always been tricky in this node of articles to lay out this ***very complex*** 😰 guidance. I plan to do more work on this article (and INCLUDES files in use) later today and tomorrow morning. The round of updates will be less …
=> Blazor hosted WASM security updates

aspnetcore/mvc/models/validation.md
Fixes #27861
code from https://github.com/dotnet/AspNetCore.Docs.Samples/pull/115
https://github.com/dotnet/AspNetCore.Docs.Samples/issues/92
https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/RazorPages/models/ModelStateError/Pages/Contacts/Create.cshtml.cs#L26
=> Draft-WIP: ModelState.AddModelError /2

aspnetcore/host-and-deploy/linux-apache.md
Paths were saved to:
/var/log/apache2helloapp-error.log
/var/log/apache2helloapp-access.log
Instead, it should be:
/var/log/apache2/helloapp-error.log
/var/log/apache2/helloapp-access.log
=> Fixing paths for apache error and access logs

aspnetcore/tutorials/first-mvc-app/adding-model.md
Removed a ```(``` that broke the links to the previous/next pages and added a colon so that the links are consistent with other pages.
=> Fixing typo in links to previous/next pages

aspnetcore/migration/inc/adapters.md, aspnetcore/migration/inc/overview.md, aspnetcore/migration/inc/session.md, aspnetcore/migration/inc/start.md, aspnetcore/migration/proper-to-2x/index.md
***TL:DR***
1. Replace experimental VS extension with the .NET Upgrade Assistant VS extension. This is a stop gap, in another PR I'll add full instructions on using .NET Upgrade Assistant VS extension.
2. Replace `migrate` with `update`.  There are a couple instances of  `migrate` left where it sounded better, but I replaced most.
Fixes #28448
Fixes #28447
Fixes #28562
Fixes #28611
[Internal review URL 1](https://review.learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/index?view=aspnetcore-8.0&branch=pr-en-us-28592)
=> upgrade not migrate /1

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #28619
The line number for the `CallDotNetExample4` example is correct, but it didn't pull in the file to highlight the correct line in the published topic. I'm trying an article date update to fix it.
=> Update the article date

aspnetcore/blazor/components/built-in-components.md, aspnetcore/blazor/components/index.md
=> QuickGrid productization

.github/workflows/quest-bulk.yml, .github/workflows/quest.yml
Quest runs nightly, rather than on each label update.
The following changes make that happen:
- The bulk action runs once a day, at a hopefully convenient time.
- The single item workflow runs only in response to a workflow dispatch event (user started)
- For security reasons, limit the permissions to write *issues*, not *contents*
=> Run quest nightly

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #28630
Thanks @ScarletKuro! 🚀 ... This might be a bit *rough*, but I couldn't wait until next Tuesday. See what you think of this. After we get the lingo hammered out sufficiently, I'll ping for engineering review.
You'll see some repeats of text here. It's just due to a type of versioning that we use. Ignore the duplicate sections/text.
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/0e11d66277d5a6cd6a9bb46fdc11e32df7351a12/aspnetcore/blazor/components/class-libraries.md) | [aspnetcore/blazor/components/class-libraries](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-28631) |
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://githu …
=> Protect class instance invokable methods

aspnetcore/blazor/components/data-binding.md
Fixes #27848
Thanks for the issue, @MisinformedDNA! 🚀 ... This should be resolved now 🤞🍀 with the latest update to VS.
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/9230d1733c9b0419865790f1b0bc0f6c0cd6005e/aspnetcore/blazor/components/data-binding.md) | [aspnetcore/blazor/components/data-binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-28683) |
=> Remove @bind:{get|set|after} feature NOTEs

aspnetcore/fundamentals/minimal-apis/includes/webapplication.md, aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/fundamentals/servers/kestrel/endpoints.md, aspnetcore/includes/http-ports.md
Fixes #27156 
The *http-ports.md* include file was added in an earlier PR, so to see all of it expand the diff manually or use the Kestrel endpoints internal preview or HTTP.sys internal preview.
@Tratcher 
> This would also work with Http.Sys though we have a warning there not to use wildcards.
It looks awkward to have text explaining how to conveniently specify ports-only right next to a warning not to use wildcards for URLs. Is there something we should say to make it look less like we're contradicting ourselves?
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/d4f9d1b491e631b4b216fed2f9fcab826c2fe24a/aspnetcore/fundamentals/servers/httpsys.md) | …
=> Doc HTTP_PORTS, HTTPS_PORTS

aspnetcore/fundamentals/configuration/index.md, aspnetcore/fundamentals/configuration/index/includes/index6.md, aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Program.cs
We should avoid calling `builder.Host` where we can. See https://github.com/dotnet/aspnetcore/issues/40681#issuecomment-1470017165
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3ccc33f0ffe92a366b3b3932da97e3cc6700ea7f/aspnetcore/fundamentals/configuration/index.md) | [aspnetcore/fundamentals/configuration/index](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-28697) |
=> Remove ConfigureAppConfiguration usages

aspnetcore/blazor/components/index.md
Fixes #28694
This topic is one of the handful that hasn't been reached to drop the *Whole-topic Versioning*, so there are four copies of the text here. Resolving topics down to ***one copy*** 👍 is an on-going task this year, and I'll get to this topic soon enough! 😄
The `ParameterParent2` component is in the Blazor sample app. Steve, I kept it the way that it was with separate `Title` assignments to plainly demonstrate that they all work to the reader. This is the first time that a new-to-Blazor dev is seeing this. I understand that from the framework's perspective that there's no difference in these assignments.
https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorSample_WebAssembly/Pages/index/ParameterParent2.razor
|:--|:--|
| …
=> Component parameter value guidance updates

aspnetcore/blazor/call-web-api.md
`System.Net.Http.HttpClient`/`System.Net.Http.HttpContent` aren't packages ... the API is merely in the `System.Net.Http` package.
This was just added yesterday to `main` and ***has NOT merged to `live`***, so I'm fixing this ***before*** it hits the live site 😅.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/b0191895da0719003984a9325424d93b51324b08/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-28729) |
=> Correct bad package references

aspnetcore/blazor/security/webassembly/graph-api.md, aspnetcore/zone-pivot-groups.yml
Addresses #28001 
Fixes #28573
Thanks @cloudhal! 🚀 ... I'm still working on this. It's just a *draft* at the moment, while I work on a service registration problem with the custom account factory approach. I'll call for one of the product unit engineers to help if I can't figure it out.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/3408e4f35526925fd1277072f258b1d91a084f04/aspnetcore/blazor/security/webassembly/graph-api.md) | [aspnetcore/blazor/security/webassembly/graph-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?branch=pr-en-us-28706) |
=> Add MS Graph SDK v5 guidance

aspnetcore/blazor/hybrid/security/index.md
Use the correct filename that contains the static `CreateMauiApp` method.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/62d4ee4c510c6bc8f6f2244abb80772d05c6275a/aspnetcore/blazor/hybrid/security/index.md) | [aspnetcore/blazor/hybrid/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/index?branch=pr-en-us-28751) |
=> Change MainWindow.cs to MauiProgram.cs

aspnetcore/razor-pages/index.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/28456
---
|:--|:--|
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/d6b35419e31af292625235fea4b7531d5c7f90fa/aspnetcore/razor-pages/index.md) | [aspnetcore/razor-pages/index](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-28772) |
=> JS collocation /3

aspnetcore/blazor/blazor-server-ef-core.md
Fixes #28804
Thanks @rafael-f! 🚀 
I went ahead and moved all of the versions of the sample app prior to 7.0 on the `dotnet/blazor-samples` repo to match the 7.0 location on https://github.com/dotnet/blazor-samples/pull/72. Here in the article, the foul link segments 😈  are removed. The build (finally 😅) is clean now, and I'll take this live in the next few minutes.
---
|:--|:--|
| [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/ab588b7f45797589869e9dfc3ebbc0871a403694/aspnetcore/blazor/blazor-server-ef-core.md) | [aspnetcore/blazor/blazor-server-ef-core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?branch=pr-en-us-28806) |
---
|:--|:--|
| …
=> Update sample app links

.github/workflows/quest-bulk.yml
This action fails when run on forks due to permissions issues. So, run it only on the dotnet org.
=> Run only on the .NET org

aspnetcore/tutorials/razor-pages/model.md
Running with -sqlite will produce the following error. `--useSqlite|-sqlite option is obsolete now. Use --databaseProvider|-dbProvider instead in the future.` This fixes that.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/c33f1364961ca3010cfcc90ee4fd8ce91bc9bdf7/aspnetcore/tutorials/razor-pages/model.md) | [aspnetcore/tutorials/razor-pages/model](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?branch=pr-en-us-28808) |
Added by wpickett;
Fixes #28813
=> Fix scaffolding command

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/minimal-apis/includes/route-handlers.md, aspnetcore/fundamentals/minimal-apis/includes/webapplication.md, aspnetcore/fundamentals/minimal-apis/responses.md, aspnetcore/fundamentals/minimal-apis/route-handlers.md, aspnetcore/includes/route-groups.md
Fixes #27480
Promoting most H3 headings to H2 (#27709) didn't work out well - the flat internal toc got to be too long and the heading levels got too far removed from the content structure. This PR just replaces one of the H2s with two of them: it divides up Request handling into Routing and Parameter binding. H2s are appropriate for those two major sections, which are also separate articles. The PR also contains some general cleanup.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf07a36ee3f0a17421bd4827079bb650cc9b3865/aspnetcore/fundamentals/minimal-apis.md) | [aspnetcore/fundamentals/minimal-apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-28820) | …
=> Some H3s to H2s and H5s to H4s

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #28783
Thanks @NightProgramming! 🚀 ... Per Steve's suggestion, we're just going to state in passing that reading the DOM or triggering events isn't a concern. I'll make a minor change to one line to make it utterly clear that it's modifying the content via JS interop with the element reference that's the concern here for where Blazor is interacting with the content. 
WRT the "empty element" aspects, we'll stick with what we have and tell (imply anyway) that it literally should be read as "***empty***" in these contexts. That's all that the product unit is guaranteeing ... "***so far it works***" could very easily turn into a 💥😢😄 per Steve's remarks. 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://gith …
=> Additional element reference guidance

aspnetcore/blazor/debug.md
Blazor WASM Debug extension for VSCode is no longer needed for debugging Blazor WASM applications.
This PR removes that recommendation.
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a5b6f03834183f40c3493a5a916f5664825f110/aspnetcore/blazor/debug.md) | [aspnetcore/blazor/debug](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-28841) |
=> Do not recommend Blazor WASM extension for debugging in VSCode

aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md
Document the script tag helper attribute "src" instead of the non-existent attribute "asp-src". Move description of said attribute to the top, similar to link tag helper's "href" attribute.
Fixes #28818
---
|:--|:--|
| [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/9c97679221b65da183bd31bce0b2984d77638432/aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md) | [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?branch=pr-en-us-28802) |
=> Remove prefix from script tag helper attribute "src"

aspnetcore/fundamentals/configuration/index.md
The sentence:
> ...in more than one configuration **providers**
Should read:
> ...in more than one configuration **provider**
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/7729840b1e2bf19be9c6c1e3a23ee015bcd2e667/aspnetcore/fundamentals/configuration/index.md) | [aspnetcore/fundamentals/configuration/index](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-28854) |
=> Fix typo in index.md

aspnetcore/blazor/security/webassembly/graph-api.md
Addresses #28859
cc: @danieltharris ... This is just temporary until we get more info from Javier on how to address/cover this. At least with this update, we have a working approach for users who haven't already granted permission for Graph.
=> Update code example

aspnetcore/grpc/native-aot.md, aspnetcore/grpc/native-aot/Program.cs, aspnetcore/grpc/native-aot/Server.csproj, aspnetcore/toc.yml
Add gRPC specific page for native AOT. Will add links to it from the fundamentals AOT page later.
---
|:--|:--|
| [aspnetcore/grpc/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/121040d72cdb98708c785da4c4374407542be30d/aspnetcore/grpc/native-aot.md) | [aspnetcore/grpc/native-aot](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/native-aot?branch=pr-en-us-28899) |
=> Add gRPC native AOT page

aspnetcore/fundamentals/native-aot.md
Two changes:
* Split out discussion about AOT publishing into its own section, and include information about what actually enables native AOT.
* Add link to native AOT gRPC page
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/750ddb10933bc1cccd24ae323c6b093d070bda54/aspnetcore/fundamentals/native-aot.md) | [aspnetcore/fundamentals/native-aot](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-28902) |
=> Add link to native AOT gRPC from fundamentals native AOT

aspnetcore/grpc/native-aot.md
I forgot the gRPC template has an aot flag.
---
|:--|:--|
| [aspnetcore/grpc/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/71dce5ae4ff7a615292f03a53af34e0e679f54f3/aspnetcore/grpc/native-aot.md) | [aspnetcore/grpc/native-aot](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/native-aot?branch=pr-en-us-28904) |
=> Mention the aot flag in gRPC template

aspnetcore/fundamentals/apis.md
Removing limitation "No support for binding from forms. This includes binding IFormFile"
According to [What's new in ASP.NET Core 7.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?source=recommendations&view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection) 
> Minimal APIs now support file upload with IFormFile and IFormFileCollection.
---
|:--|:--|
| [aspnetcore/fundamentals/apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/48b0251bfa55d313b3f37ddd8676418b817d609f/aspnetcore/fundamentals/apis.md) | [aspnetcore/fundamentals/apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/apis?branch=pr-en-us-28908) |
=> APIs overview: Remove IFormFile support from minimal APIs limitations list

aspnetcore/blazor/host-and-deploy/server.md
StickyServerMode -> ServerStickyMode
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/b896ea43ac6d222181f11d55ec3cb2ea1c9b86e5/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy Blazor Server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-28939) |
=> Fix Azure SignalR config key

aspnetcore/migration/inc/remote-app-setup.md
Use indexer rather than method syntax for `builder.Configuration`
---
|:--|:--|
| [aspnetcore/migration/inc/remote-app-setup.md](https://github.com/dotnet/AspNetCore.Docs/blob/02e25ec4e92b1a31b28f90239c856d674e34d192/aspnetcore/migration/inc/remote-app-setup.md) | [Remote app setup](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-app-setup?branch=pr-en-us-28967) |
=> Fix syntax error in remote app setup sample code

aspnetcore/mvc/models/validation.md
If I am reading this correctly, it looks like this is a typo.
---
|:--|:--|
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/6e590bafe38059545383479c12bc7f603563124b/aspnetcore/mvc/models/validation.md) | [Model validation in ASP.NET Core MVC and Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?branch=pr-en-us-29000) |
=> Model validation non-nullable reference types typo

aspnetcore/blazor/hybrid/routing.md
Fixes #28965
cc: @mkArtakMSFT ... I can see that Surayya did the PR ... I'll ping for review.
Notes:
* Do we want to use this language to describe the default start path? ...
> The default start path is the relative root URL path (`/`).
... because I'm not aware if it's possible for these apps to have a different base path. I'll modify to your best choice of language there.
* Just FYI ... Across the Hybrid docs, we use the approach for setting properties on a `BlazorWebView` that the tutorials adopt. In the case where the dev is looking at the XAML markup code, we show the setting on the element, not via the designer property tools. In the WinForms case, we set those properties in C#, so that's what we place here. We assume the reader used our tutorials, so we assume they'll work with the …
=> Initial URL for BlazorWebView

aspnetcore/security/authentication/identity.md
Fixes #23048
I was globally addressing some issue labels and turned up this old-ish issue that needed a final push over the finish line. The change is just to use the new Duende IdS INCLUDE over the prior IdS 4 INCLUDE (which we keep b/c it's used in pre-6.0 content versions). This is the only spot to update AFAICT. The newer one just has the added bit about the possible license fee that they instituted at that time ...
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/DuendeIdentityServer.md
I won't have further updates to this ... it can be merged immediately after approval.
---
|:--|:--|
| [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/f70b8e94f6b269bca44fa54a2947d2f71aed9372/aspnetcore/se …
=> Update Duende IdS INCLUDE reference

aspnetcore/migration/inc/remote-app-setup.md
I can't find anywhere in the current docs where it says to install this package. Just using the sample code will yield `The name 'SystemWebAdapterConfiguration' does not exist in the current context`
Fixes #28976
---
|:--|:--|
| [aspnetcore/migration/inc/remote-app-setup.md](https://github.com/dotnet/AspNetCore.Docs/blob/33f0ba20b98e21e56508f7e606b673e22a103f31/aspnetcore/migration/inc/remote-app-setup.md) | [Remote app setup](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-app-setup?branch=pr-en-us-28966) |
=> Mention required nuget package in remote app doc

aspnetcore/fundamentals/configuration/index.md
The existing links are pointing at File Configuration Provider rather than JSON Configuration Provider. This pull request updates the links
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a8f3f0271dc63ae18ea7961bf1bce4f6cea0f03/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-29028) |
=> Fix links for JSON configuration provider

aspnetcore/blazor/hybrid/root-component-parameters.md
Fixes #29009
Thanks @UnusualJustin! 🚀 
Let's look at this carefully because it's (obviously) a bit tricky. I think my app turned out a bit different than your suggestion, @UnusualJustin, in that you suggested a change in `MainLayout.razor` that I don't need to cascade this param. In a nutshell on the PR, the new guidance is ***only to*** ...
In the `Main` component (`Main.razor`):
* Add a parameter matching the type of the object passed to the root component:
```razor
@code {
[Parameter]
public KeypadViewModel KeypadViewModel { get; set; }
}
```
* Cascade the `KeypadViewModel` with the [`CascadingValue` component](xref:blazor/components/cascading-values-and-parameters#cascadingvalue-component). Update the `<Found>` XAML content to the following markup:
```xaml
<Found Context="routeData"> …
```
=> Repair bad root component param guidance

aspnetcore/blazor/fundamentals/routing.md
Fixes #29027
Thanks @OnSive! 🚀 ... I'll leave this up for a couple of hours for you to take a look. I digest what Steve said down to just enough basic info that I think readers will get it without getting into the weeds. The important final point is that devs can define their own cascading or regular params as needed, so I close the added paragraph on that point. If I do go ahead and merge this before you see it, you can leave feedback here if you feel I left something important out or wrote something confusing in the paragraph. If changes are needed, I'll patch this paragraph on a new PR.
Also, I'll note that *sometimes* we cross-link the PU repo issue/PR remarks. I don't think that we need to do that in this case. I think the simplified remark on this docs PR for the reasoning is …
=> Non-routable components query param processing

aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md, aspnetcore/toc.yml
Fixes #28980
Notes:
* The content doesn't really fit into Blazor-specific docs, so I create an article for it in the *Components* node. I also didn't want to try and tack this on to the *Components* node overview article because that article is already *toooo looong* 😩. I'm actually going to be looking for ways to shorten it further, not make it longer. We can move the content of this new article later easily enough. The nice thing here is to have the content work done (or mostly done).
* Code tested working locally here.
* I have a tracking item in my 8.0 tracking issue to strip out the `--prerelease` options at RTM.
---
|:--|:--|
| [aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/7e92944b7 …
=> Render components outside of ASPNETCORE

aspnetcore/security/enforcing-ssl.md
The text made it appear as one should put the bash script into the policies.json file
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/f7ddc2a9725a7b573343c0ef888f8d5852d538ee/aspnetcore/security/enforcing-ssl.md) | [[.NET Core CLI](#tab/netcore-cli) ](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-29037) |
=> Fix confusing statement

aspnetcore/performance/ObjectPool.md, aspnetcore/performance/ObjectPool/ObjectPoolSample8/Program.cs, aspnetcore/performance/ObjectPool/includes/ObjectPool1-5.md, aspnetcore/performance/ObjectPool/includes/ObjectPool6.md
Fixes #29036
---
|:--|:--|
| [aspnetcore/performance/ObjectPool.md](https://github.com/dotnet/AspNetCore.Docs/blob/0454c15cff2c79f547ed59e6110a3f2ef9e007ca/aspnetcore/performance/ObjectPool.md) | [Object reuse with ObjectPool in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?branch=pr-en-us-29054) |
=> Better comments in object pool /5

aspnetcore/blazor/components/layouts.md, aspnetcore/blazor/components/sections.md, aspnetcore/toc.yml
Fixes #28617
Surayya ... Note that I don't get access to the bits until the preview releases, so I can't check/test anything locally at this time. I had to guess a little on a few of the finer points, but you'll likely spot anywhere I went wrong 🙈 quickly.
***UPDATE***: I reacted to the latest design changes coming for Preview 3. Given that I did that here, it seems like we should hold this until the Preview 3 release. However, I think we can go ahead and get it reviewed and updated.
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/ed4959588bea8c20baf071900fc2f474cfb72e58/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/comp …
=> Blazor layout sections

aspnetcore/blazor/tooling.md
Fixes #28996
I left the remark about Apple Safari in the 7.0 version of this content. Was 7.0 ever patched to support SIMD for Safari with `<WasmEnableSIMD>` enabled?
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/4193ea6793fa539ea51bc556f8b6044c40122e7f/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-28997) |
=> Blazor WASM SIMD support

aspnetcore/grpc/troubleshoot.md, aspnetcore/grpc/troubleshoot/includes/troubleshoot3-7.md
Fixes #28597
Fixes #2867 with one added detail but mostly addressed through pr #28876
Minor updates.
- Update version 6-7 to remove reference to "preview" reference and clarify HTTP/3 needs to be enabled for .NET 6 & 7 while it is enabled by default for .NET 8.
- - Moved include for version 3-7 to its own troubleshooting folder and updated reference in version 8.
---
|:--|:--|
| [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/9366c9617e36449434031a0944ff25aa4fe166b7/aspnetcore/grpc/troubleshoot.md) | [Troubleshoot gRPC on .NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?branch=pr-en-us-29095) |
=> gPRC Troublehsooting Update version 6-7 HTTP/3 support statement and fix include

aspnetcore/host-and-deploy/aspnet-core-module.md, aspnetcore/host-and-deploy/iis/hosting-bundle.md
Fixes #29019
Thanks @jovton! 🚀 
The main update is to the ANCM doc, but I also added the remark to the WARNING note in the hosting models doc. I suppose it can be a warning given that if either or both the ANCM and framework apps are mixed and matched ***out of LTS support***, there could be some 🐉🐉🐉 lurking in production 😨.
---
|:--|:--|
| [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/02f2d08bf46b74ed4f80fe34d0c1a31abc738765/aspnetcore/host-and-deploy/aspnet-core-module.md) | [ASP.NET Core Module (ANCM) for IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?branch=pr-en-us-29021) |
| [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCor …
=> Clarify ANCM .NET version support

aspnetcore/blazor/components/built-in-components.md
Addresses #28001 
Adds `SectionContent`/`SectionOutlet` components (8.0) for the new [Blazor Sections article](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/sections?view=aspnetcore-8.0).
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/70234187cf3c6335dfe02445f4312a69a81d1961/aspnetcore/blazor/components/built-in-components.md) | [ASP.NET Core built-in Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-29103) |
=> Blazor built-in components article versioning

aspnetcore/fundamentals/configuration/index.md
Code snippet was instead showing the broken markdown, and I think this change fixes it.
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf67399937e7fc1219e7eda77812588e7e9d2606/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-29107) |
=> Bugfix code section not displaying

aspnetcore/blazor/fundamentals/routing.md
Fixes #29105
Surayya ... I didn't guess about what general rules or *gotchas* 😈 that you want to call out. Let me know what you'd like to add in a comment, or you can `suggestion` them into the text.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/598a3718a3a34a773dc30e9a585d5276f5146fbb/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-29106) |
=> Hashed routing to named elements

aspnetcore/security/authentication/community.md
Keeping the ASP.NET Core versions list up-to-date in OpenIddict's description depends on community contributions and proved to be a painful process. Mentions of ASP.NET Core and Microsoft.Owin are also problematic as OpenIddict now includes a client stack that aims at being a universal .NET client (that can be used in ASP.NET Core and OWIN web apps and but also in console/WPF/WinUI/UWP and Linux desktop apps): listing all the supported environments would make the description messy, so `Flexible and versatile OAuth 2.0/OpenID Connect stack for .NET` seems to be a simpler option.
On a related note, it's not clear at all why non-.NET projects like Gluu Server (built on top of the Janssen Project, which is Java-based) and Authentik (Python-based, AFAICT) are included in this list. This …
=> Simplify OpenIddict's description

aspnetcore/host-and-deploy/linux-apache.md
Fixes #29079
See [Config Apache](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?branch=pr-en-us-29081&view=aspnetcore-7.0#configure-apache)
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/61c9058f6ad028c440b52f0167b94e778f09fe91/aspnetcore/host-and-deploy/linux-apache.md) | [The default value is 90 seconds for most distributions.](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?branch=pr-en-us-29081) |
=> RequestHeader set "X-Forwarded-Proto"

aspnetcore/migration/inc/remote-app-setup.md
It seems that the .Net Upgrade Assistant no longer automatically adds the HttpModule. Regardless, this article doesn't seem to assume the use of that tool, so it should describe all the required pieces.
***@Rick-Anderson edit: Fixes #29151***
---
|:--|:--|
| [aspnetcore/migration/inc/remote-app-setup.md](https://github.com/dotnet/AspNetCore.Docs/blob/e1973edb8d5691cc9561f7d9306d00fc65180f41/aspnetcore/migration/inc/remote-app-setup.md) | [Remote app setup](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-app-setup?branch=pr-en-us-29020) |
=> Fix Remote App Setup method name and HttpModule

aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md, aspnetcore/zone-pivot-groups.yml
Fixes #29043
**UPDATE**: Javier, I think you'll be too busy to look at all of the updates in detail. TL;DR the main points are that: (1) I can't get your approach to work, but my approach works here, so I'll go with my approach for now. Perhaps, I should ping you after .NET 8 releases to discuss it further and see if the 🦖 approach is *sane enough* 😵 to keep 😄. (2) I'm adding your hosting concept (hosting at subpaths) to the existing domain/port coverage, which is still working 🎉. I think using pivots for the coverage is best.
Notes
* I can't get the [sample app](https://github.com/javiercn/BlazorMultipleApps/tree/main/BlazorMultipleApps) to run locally for the 2nd client. It 💥404s 💥 ... https://github.com/dotnet/AspNetCore.Docs/issues/29043#issuecomment-1530035513.
* I've 🙈 …
=> Subpath scenario for multiple hosted WASM apps

aspnetcore/blazor/components/index.md, aspnetcore/blazor/fundamentals/handle-errors.md
Fixes #28933
Notes ...
* I felt building off of the prior example makes sense. Presumably, many readers will have just tested out the prior section's example, so they can just build on that experience to see this API in action.
Here's what this new example builds off of ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#invoke-component-methods-externally-to-update-state
* There's one thing in Steve's remarks that I don't understand ...
> ... the premise that you have an exception already implies you caught it. If you don't catch an external exception, then you have an unhandled exception which has nothing to do with Blazor.
Cross-ref: https://github.com/dotnet/aspnetcore/issues/46068#issuecomment-1398207040
***... but*** error boundaries (getting …
=> Dispatch exceptions to the sync context

aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md, aspnetcore/blazor/hybrid/security/security-considerations.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/57f51c6fa03641e0fc653e22939b2805a90a6bb7/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md) | [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?branch=pr-en-us-29210) |
| [aspnetcore/blazor/hybrid/security/security-considerations.md](https://github.com/dotnet/AspNetCore.Docs/blob/57f51c6fa03641e0fc653e22939b2805a90a6bb7/aspnetcore/blazor/hybrid/security/security-considerations.md) | [aspnetcore/blazor/hybrid/security/security-considerations](https://review.learn.microsoft.com/en-us/aspnet/core/bl …
=> Code language updates

aspnetcore/tutorials/min-web-api/samples/6.x/todo/Program.cs
When adding public class TodoItemDTO, this message may display in Visual Studio: Inconsistent accessibility: parameter type: 'Todo' is less accessible than the method 'TodoItemDTO.TodoItemDTO (todo).
Adding public to class makes this message go away.
=> Add public to class Todo

aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md
Fixes #29228
Thanks @sulmar! 🚀 ... How about we just expand the existing example, as I have on this PR, to show it? I add a NOTE at the end about passing an empty `ParameterView` for the no params case.
... and btw ... I didn't think the `EditorRequired` attribute was required ... is that what you're seeing there?
---
|:--|:--|
| [aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/74dafd7edf55f493cbfbe158ce8499828aff4e4d/aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md) | [Render Razor components outside of ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?branch=pr-en-us-29231) |
=> Expand example to show passing parameters

aspnetcore/toc.yml
Fixes #28988 
>No page summarizes the different servers. We can add an `Overview` page if there is a dedicated `Servers` section. 
We have an overview of the servers in `Fundamentals` - I moved that to the `Overview` node of the new top-level `Servers` section. This overview article already [compares Kestrel to HTTP.sys](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-8.0&branch=pr-en-us-29008&tabs=windows#kestrel-vs-httpsys), and we can add comparison section(s) to address #28948.
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-8.0&branch=pr-en-us-29008&tabs=windows)
=> Move Servers to a top-level TOC section

aspnetcore/fundamentals/error-handling.md
Fixes #29152
Bruno, can't we get an [ASPnnnn](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?view=aspnetcore-8.0) code analysis to detect this?
[Review URL internal only](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29221&view=aspnetcore-8.0#customize-problem-details)
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/74a8ff4f110e6a21a8b6d194ed1a8ef26ffba339/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29221) |
=> warn about registering customer service /5

aspnetcore/index.yml
Fixes #29256 
On the landing page there's no need to try to avoid duplicating links in multiple places as in the TOC, so I put Kestrel, IIS, and HTTP.sys links in both the Servers card and the Host and Deploy card.
=> Add Servers card to landing page

aspnetcore/diagnostics/asp0025.md, aspnetcore/diagnostics/code-analysis.md, aspnetcore/toc.yml
Fixes #29229 
---
|:--|:--|
| [aspnetcore/diagnostics/asp0025.md](https://github.com/dotnet/AspNetCore.Docs/blob/c827dcab40f8957a3a3acc001a90942a8a7d3fb0/aspnetcore/diagnostics/asp0025.md) | [aspnetcore/diagnostics/asp0025](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0025?branch=pr-en-us-29252) |
| [aspnetcore/diagnostics/code-analysis.md](https://github.com/dotnet/AspNetCore.Docs/blob/c827dcab40f8957a3a3acc001a90942a8a7d3fb0/aspnetcore/diagnostics/code-analysis.md) | [Code analysis in ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?branch=pr-en-us-29252) |
=> Document ASP0025 code analyzer

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/eead844f3c903799ff314560a989f7574f49d9b8/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-29282) |
=> Remove sample line highlights

aspnetcore/tutorials/first-web-api.md
Fixes #29190 
This leaves the testing in Swagger and links to the .http files documentation and the minimal API tutorial for info about and examples of testing with .http files.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/161fcf949ec470ca4e75eafa50811a62379e6c40/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-29300) |
=> Link to info about Endpoints Explorer and .http files

aspnetcore/security/authentication/azure-active-directory/index.md
The old link goes to:
Welcome! This probably isn't the page you were expecting. 
I am just making a guess as to where this is supposed to go: https://learn.microsoft.com/en-us/azure/active-directory/develop/web-app-quickstart?pivots=devlang-aspnet&tabs=windows
Fixes #29304
---
|:--|:--|
| [aspnetcore/security/authentication/azure-active-directory/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/47f3a5424a0748847bc8fe57a0b2556e2f4f20fd/aspnetcore/security/authentication/azure-active-directory/index.md) | [Azure Active Directory with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/index?branch=pr-en-us-29301) |
=> Fixing bad link

aspnetcore/tutorials/first-web-api.md
Some minor cleanup changes that accidentally got left out of #29300
* Remove a duplicated h2
* Text in all Mac tabs should say go to .NET 7 version.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/9cd15112a755151955c5bb5a8b70e5c0034136b3/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-29305) |
=> Follow-up to #29300

aspnetcore/blazor/security/content-security-policy.md
Fixes #29293
Mackinnon ... I see that Pavel is still working on runtime bits, but it is ok to knock this out for preview coverage now?
It's not easy to see from the diff because it's adding versioned content. The changes here are to ...
* Remove the following line ...
> \* Specify \`unsafe-eval\` to permit the Blazor WebAssembly Mono runtime to function.
* Change part of the WASM policy from ...
> ```html
> script-src 'self'
>            'unsafe-eval';
> ```
... to ...
> ```html
> script-src 'self';
> ```
---
|:--|:--|
| [aspnetcore/blazor/security/content-security-policy.md](https://github.com/dotnet/AspNetCore.Docs/blob/810b3158f9a8eb750ddc092b88131a7697d04bc6/aspnetcore/blazor/security/content-security-policy.md) | [Enforce a Content Security Policy for …
=> Remove 'unsafe-eval' in CSP guidance

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
The configuration change in `appsettings.json` (Server) is no longer related to the "audience" but the paragraph describes general configuration change needed.
Relates to #29032, cc @guardrex.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf737e30f90005d1e18fbc1d8ce8960e0f572465/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?branch=pr-en-us-29315) |
=> Blazor - hosted-with-azure-active-directory.md - No audience

aspnetcore/blazor/globalization-localization.md
Fixes #29317
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/143436a2574ae0836612342438222e9db601c385/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-29318) |
=> Custom ICU loading

aspnetcore/grpc/troubleshoot.md, aspnetcore/grpc/troubleshoot/includes/troubleshoot3-7.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2048
FYI @tonydnewell
---
|:--|:--|
| [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/bceca0cb2b415e434a6ebba83abcbcd45f8963b1/aspnetcore/grpc/troubleshoot.md) | [Troubleshoot gRPC on .NET](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?branch=pr-en-us-29314) |
=> Add docs for using Grpc.Tools on unsupport platforms

aspnetcore/test/dev-tunnels.md
dev tunnels has GAed in 17.6, the Preview Feature option has been removed and it's enabled by default. Updated the doc to reflect that.
cc @tdykstra 
---
|:--|:--|
| [aspnetcore/test/dev-tunnels.md](https://github.com/dotnet/AspNetCore.Docs/blob/6eefdb89458c1786b41e759594f24dea9ec45dbc/aspnetcore/test/dev-tunnels.md) | [How to use dev tunnels in Visual Studio 2022 with ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?branch=pr-en-us-29334) |
=> Removing Preview Feature from dev tunnels, it is no longer required

aspnetcore/includes/scaffold-identity/migrations.md
It doesn't read well with "either" when only one command is shown by a single tab control.
---
|:--|:--|
=> NIT Migrations INCLUDE lingo change

aspnetcore/blazor/components/index.md
Fixes #29410
We don't want to turn this into *Programming 101*, but let's add just a *wee bit* of the reason why one would want to take these approaches with their components. *We have plenty of new-to-programming folks coming into the industry!* 😄
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/93fbcb661027bb56074e15507083bc55f1b4aadd/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-29411) |
=> Remark on the reasons for using partial classes and base classes

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
Fix a little indent error in a linux code example.
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/42bfee49dadcdf5df33e972ae210a835597c758e/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [Docker images for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-29425) |
=> Update building-net-docker-images.md - Indent Error

aspnetcore/blazor/components/element-component-model-relationships.md, aspnetcore/blazor/components/overwriting-parameters.md, aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md, aspnetcore/blazor/components/synchronization-context.md
---
|:--|:--|
| [aspnetcore/blazor/components/element-component-model-relationships.md](https://github.com/dotnet/AspNetCore.Docs/blob/3fa368cbb73ce0ac48f829582ca7edd05bfe9ce5/aspnetcore/blazor/components/element-component-model-relationships.md) | [Retain element, component, and model relationships in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?branch=pr-en-us-29437) |
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/3fa368cbb73ce0ac48f829582ca7edd05bfe9ce5/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core …
=> Move code example cross-links in new articles

aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md
Addresses #29399
Thanks @hacst! 🚀 ... I don't know how it will play out in the framework or for the rest of the docs, but this addresses use of the Host header in one Blazor example ... the only Blazor example AFAIK.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/1dfd994c70cdd184cf0bdc00d1f45356c9fd5c5c/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md) | [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?branch=pr-en-us-29445) |
=> Warn on port spoofing via the Host header

aspnetcore/blazor/security/server/index.md
Fixes #29448
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/7111dd777579900c7f972d702d950e6de59271b0/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core Blazor Server apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-29449) |
=> Provide examples of recommendations

aspnetcore/performance/timeouts.md, aspnetcore/performance/timeouts/samples/8.x/Program.cs
Fixes #29436 
---
|:--|:--|
| [aspnetcore/performance/timeouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/f9c6c534e609038e91427afdeb4eab2b50b98e16/aspnetcore/performance/timeouts.md) | [Request timeouts middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/timeouts?branch=pr-en-us-29443) |
=> Pass the RequestAborted token to async APIs like Task.Delay

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ae52efa84ded187d460d601117c7909a0c45dfc/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md) | [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?branch=pr-en-us-29472) |
=> Call .NET from JS article versioning

aspnetcore/blazor/file-downloads.md, aspnetcore/blazor/images.md, aspnetcore/blazor/includes/js-location.md, aspnetcore/blazor/includes/prerendering.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a23fd3861b4c90116275447340e2ccd97df3677/aspnetcore/blazor/file-downloads.md) | [ASP.NET Core Blazor file downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-29481) |
| [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a23fd3861b4c90116275447340e2ccd97df3677/aspnetcore/blazor/images.md) | [Work with images in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/images?branch=pr-en-us-29481) |
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a23fd3861b4c90116275447 …
=> Call JS from .NET article versioning

.github/workflows/oof-blazor-comment.yml
cc: @Rick-Anderson ... I'll run with this for the few days each of the next two weeks and for the full last week of the month. I'll be checking in periodically, and I'll squash 🪲 and react to any PU issues immediately. There's no need for the team to take any action on Blazor issues while I'm out. This will be a typical ***staycation*** type of break. 😆
=> Create a Blazor OOF vacation issue comment workflow

aspnetcore/fundamentals/request-features/samples/8.x/IHttpSysRequestTimingFeature/IHttpSysRequestTimingFeature.csproj, aspnetcore/fundamentals/request-features/samples/8.x/IHttpSysRequestTimingFeature/Program.cs, aspnetcore/fundamentals/request-features/samples/removeMe.txt
Adds a minimal API sample using the new `IHttpSysRequestTimingFeature` API added in .NET 8 Preview 2. 
Includes examples for each of the available members on the feature (`Timestamps`, `TryGetTimestamp`, `TryGetElapsedTime`).
Fixes: #29537
=> Add sample for IHttpSysRequestTimingFeature

aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/progressive-web-app.md
Fixes #28964
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/e59372de91703fdcad5dd9896460355bbb7904fc/aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md) | [Deployment layout for ASP.NET Core Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-deployment-layout?branch=pr-en-us-29542) |
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/e59372de91703fdcad5dd9896460355bbb7904fc/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webas …
=> .NET assembly packaging (Webcil)

aspnetcore/web-api/action-return-types.md
Fixes #29538
---
|:--|:--|
| [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/054380c132fd172dfc4c47c8d8e0c5ba694507a3/aspnetcore/web-api/action-return-types.md) | [Controller action return types in ASP.NET Core web API](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?branch=pr-en-us-29578) |
=> API generic return types /2

aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/29594
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/a4cd3290785e733620ad3ec1603777049623508a/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?branch=pr-en-us-29596) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/a4cd3290785e733620ad3ec1603777049623508a/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29596) |
=> What's new update

aspnetcore/fundamentals/servers/kestrel/connection-middleware.md, aspnetcore/fundamentals/servers/kestrel/endpoints.md, aspnetcore/fundamentals/servers/kestrel/samples/6.x/KestrelSample/Snippets/Program.cs, aspnetcore/includes/credentials-warning.md, aspnetcore/toc.yml
Based on https://github.com/dotnet/AspNetCore.Docs/pull/29501
Fixes #21117 
[The issue](https://github.com/dotnet/AspNetCore.Docs/issues/21117) initially proposed grouping topics by ways to configure (e.g. code, appsettings.json). Then under each way to configure, there would be subjects (e.g. HTTPS, HTTP protocol)
That layout didn't work well because subjects couldn't be introduced once (e.g. here are all the HTTP protocols and what is needed to support them) because the instructions to configure the subject was in 2-3 different places. The layout is now by subject, with an introduction to that subject, then ways to configure it as subheadings.
I've liberally added links between different sections, so people can jump directly to the content they want.
**Use this link to preview …
=> Improve Kestrel endpoints

aspnetcore/blazor/tooling.md
Fixes #29567
VS4Mac can't create a Blazor Web App yet via its UI, so I've temporarily placed an instruction to create the app with the CLI. Next, I tell the reader to open the app in VS4Mac via its project file.
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/0bf6547963a7c3f2e99789684a1f9a641dbff6b5/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29568) |
=> Tooling article updates

aspnetcore/blazor/tooling.md
Lists don't render with correct number increments where there's separation present for versioning.
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/ad39e997e6e205bb7757e495fe8ea7aaf983b83a/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29609) |
=> Drop lists in Tooling article

aspnetcore/fundamentals/aot/native-aot-tutorial.md, aspnetcore/fundamentals/native-aot.md
Fixes #29112 
The instructions work the same using CLI for MacOS and Windows, so no MacOS tab is needed.  I clarified a bit on the cli vs VS template description.
Tested with VS 2022 Preview/.NET 8 and project generation on MacOS with CLI.  Thanks Andy for testing on MacOS for compile/publish.  
Verified diff in the launchSettings.json were correct.  They are on both Win and MacOS and VS and CLI.
Note: VS for Mac 2022 preview is not working with .NET 8 preview yet so there is no VS for Mac specific instruction.  
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/8a97c5ae5a73e09a07ae70ae8ff508230b9460b4/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native …
=> Correct AOT instructions MacOS and Win

aspnetcore/release-notes/aspnetcore-8.0.md
1 H3 section was accidentally left under the wrong H2 section.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/3afe7f2217c30d98573329eafae3ad249c69cd31/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29635) |
=> Move an h3 section to misc h2 section

aspnetcore/security/cross-site-scripting.md
---
|:--|:--|
| [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/1f492cc616815ffdae4f9c9bb7ba7004fe573aa7/aspnetcore/security/cross-site-scripting.md) | [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?branch=pr-en-us-29641) |
=> Added a missing word to "Prevent Cross-Site Scripting (XSS) in ASP.NET Core" article

aspnetcore/tutorials/grpc/grpc-start/sample/sample3-5/readme.md, aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/readme.md
We're trying to remove the .NET Core label from the site experience. It's not the main technology focus for these samples (neither is VS), so I removed that metadata.
Contributes to https://github.com/dotnet/docs/issues/35970
---
|:--|:--|
| [aspnetcore/tutorials/grpc/grpc-start/sample/sample3-5/readme.md](https://github.com/dotnet/AspNetCore.Docs/blob/6c36bbe6878dcdfb51334b5d54bacfc57bf179bb/aspnetcore/tutorials/grpc/grpc-start/sample/sample3-5/readme.md) | [Create a gRPC client and server in ASP.NET Core 3.1](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start/sample/sample3-5/readme?branch=pr-en-us-29647) |
| [aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/readme.md](https://github.com/dotnet/A …
=> Clean up product metadata for 2 samples

aspnetcore/security/identity-management-solutions.md
@kevinchalet ... `https://www.openiddict.com/` yields a 404 💥. Is the GH address the correct replacement URL?
https://github.com/openiddict/openiddict-core
---
|:--|:--|
| [aspnetcore/security/identity-management-solutions.md](https://github.com/dotnet/AspNetCore.Docs/blob/bad527388b33120b3400f6d130cac807d6a9ecf1/aspnetcore/security/identity-management-solutions.md) | [Identity management solutions for .NET web apps](https://review.learn.microsoft.com/en-us/aspnet/core/security/identity-management-solutions?branch=pr-en-us-29660) |
=> Update OpenIddict link

aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo0.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo2.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo3.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo4.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo6.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo7.razor
Fixes #29668
A tracking item has been created to return for further updates to this article later. For now, an IMPORTANT note warns readers that the content work isn't complete and to select the .NET 7 version of the article to use it with the current release.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/e5be616ee51cb50620f819dccbf12f7746f35689/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-29669) |
=> Blazor ToDo tutorial updates

aspnetcore/blazor/tooling.md, aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/signalr-blazor-preview.md, aspnetcore/blazor/tutorials/signalr-blazor.md, aspnetcore/toc.yml
Fixes #29679
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/da0829ae53c5d5c788b18309402152722dca124a/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29681) |
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/da0829ae53c5d5c788b18309402152722dca124a/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-29681) |
| [aspnetcore/blazor/tutorials/signalr-blazor-preview.md](https://github.com/dotnet/AspNetCore.Docs/blob/da0829ae53c5d5c788b1 …
=> Blazor SignalR tutorial for .NET 8

aspnetcore/test/integration-tests.md
Add a note how to avoid HTTPS redirection warnings when using HTTPS Redirection Middleware
---
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/0436563c8ae86e9fabb9c621c886779110a09658/aspnetcore/test/integration-tests.md) | [Integration tests in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-29589) |
=> Add note concerning HTTPS redirection warnings

aspnetcore/fundamentals/error-handling.md, aspnetcore/fundamentals/error-handling/samples/8.x/ErrorHandlingSample/CustomExceptionHandler.cs, aspnetcore/fundamentals/error-handling/samples/8.x/ErrorHandlingSample/Program.cs
Fixes #29520 
Best location for the new H2 section seems to be after the sections on Developer exception page and Exception handler page, and before the UseStatusCodePages section.
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0&branch=pr-en-us-29674#iexceptionhandler) (goes to .NET 8 version and the new section)
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/078e223bdbe69e841383671f3f4f6c094d6643b5/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29674) |
=> Document IExceptionHandler

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29690 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/152c61560d60f7b232b5ba0e60125cb180bcc584/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29691) |
=> Iexceptionhandler3

aspnetcore/signalr/configuration/includes/configuration2.1.md, aspnetcore/signalr/configuration/includes/configuration2.2.md, aspnetcore/signalr/configuration/includes/configuration3.1.md, aspnetcore/signalr/configuration/includes/configuration3.md, aspnetcore/signalr/configuration/includes/configuration5.md, aspnetcore/signalr/configuration/includes/configuration6.md, aspnetcore/signalr/configuration/includes/configuration7.md
Fixes #29719
Moving versions 2.1 through 8.0 to version by include and update any links.
This is prep to doing an 8.0 update to reflect a few changes.
---
|:--|:--|
| [aspnetcore/signalr/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/05fa8924813f6c66902694f476e282c2407e5c4f/aspnetcore/signalr/configuration.md) | [ASP.NET Core SignalR configuration](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/configuration?branch=pr-en-us-29720) |
=> SignalR Config version by include prep

aspnetcore/blazor/fundamentals/routing.md
Fixes #29547
Mackinnon ...
* We never documented `[SupplyParameterFromForm]` for any release. I thought it was an internal framework API bit that devs wouldn't directly use, but I'm prepared to hear what we need to cover it if that's not the case. 👂
* This is the only spot in the Blazor docs that we cover the `[SupplyParameterFromQuery]` attribute. If there are no other places around the Blazor docs that need to refer to the attribute, then we'll be good to go after we get this spot updated.
* Although Pre6 isn't out yet, I'm going to merge this after you sign off. I'm already working on the major updates for full-stack Blazor, and I don't want to get bogged down in a 😈 ***nasty merge conflict*** 😈 situation 😆.
---
|:--|:--|
| …
=> SupplyParameterFromQuery 8.0 updates

aspnetcore/mvc/views/working-with-forms.md
Noticed in passing while [chatting with a dev](https://github.com/dotnet/AspNetCore.Docs/pull/29750) on the subject ...
* "an" HTML: 99 cases
* "a" HTML: 1 case 😈
---
|:--|:--|
| [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/b3dbc77b5b124d4df81ec25e6f0daa704a3e9e39/aspnetcore/mvc/views/working-with-forms.md) | [Tag Helpers in forms in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?branch=pr-en-us-29751) |
=> Update indefinite article

aspnetcore/host-and-deploy/health-checks.md
Fixes #29421
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/c6ef09865ab6c35694cbcde34cc26841272f702b/aspnetcore/host-and-deploy/health-checks.md) | [Health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-29439) |
=> UseHealthChecks vs. MapHealthChecks /5

aspnetcore/blazor/components/index.md
Fixes #28572
Thanks @LuohuaRain! :rocket:
Now that 17.6 is out, named tuples support can be added to the doc, and I created an example of it to demonstrate how it composes. Also, I think naming the "Tuple" type isn't so good. One nice thing about this is how compact the code is when just placing parentheses around the types (and names).
I'll leave this up until Wednesday morning to give you a chance to take a look, but I need to get it merged ***quickly*** 🏃, as we have a ***TON*** 🐘 of work going on right now for .NET 8. I don't want this to get mired in a nasty 😈 ***merge conflict*** 😈😆. 
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/eb09bb7ed55e6e3e813d4ce69945f07a647d65d4/aspnetcore/blazor/components/i …
=> Named Tuple support

aspnetcore/blazor/components/control-head-content.md, aspnetcore/blazor/state-management.md
Fixes #29792
---
|:--|:--|
| [aspnetcore/blazor/components/control-head-content.md](https://github.com/dotnet/AspNetCore.Docs/blob/2807a11b1bcf6f085db5d51612a7f2adaf8756ef/aspnetcore/blazor/components/control-head-content.md) | [Control `<head>` content in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?branch=pr-en-us-29793) |
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/2807a11b1bcf6f085db5d51612a7f2adaf8756ef/aspnetcore/blazor/state-management.md) | [ASP.NET Core Blazor state management](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/state-management?branch=pr-en-us-29793) |
=> HeadOutlet component 8.0 updates

aspnetcore/blazor/components/sections.md
Addresses #28617
---
|:--|:--|
| [aspnetcore/blazor/components/sections.md](https://github.com/dotnet/AspNetCore.Docs/blob/3477d23957132fc62287b5542c0226f482bcb8aa/aspnetcore/blazor/components/sections.md) | [ASP.NET Core Blazor sections](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/sections?branch=pr-en-us-29795) |
=> Sections Pre6 updates

aspnetcore/blazor/tooling.md, aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/signalr-blazor-preview.md
Addresses #29567
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4b0443295260fcb46e20c7eee995e8058827f75/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29796) |
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4b0443295260fcb46e20c7eee995e8058827f75/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-29796) |
| [aspnetcore/blazor/tutorials/signalr-blazor-preview.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4b0443295260fcb …
=> Tooling Pre6 updates

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/includes/js-interop/circuit-disconnection.md, aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md, aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md, aspnetcore/blazor/javascript-interoperability/index.md
Fixes #29726
Mackinnon ...
* Most of the file changes on the PR are to improve content organization, so you can ignore those pieces. The main thing that I need help with is the new `MutationObserver` example. We talk about it around the docs now in several spots, so I think an example would be helpful over just mentioning it and cross-linking to Mozilla API docs. I'll show it below, so you don't even need to look at the diff unless you want to (or wish to indicate line suggestions to the PR).
* The example is cobbled together from several examples around the Net ... another classic 🙈 ***RexHaq!***&trade; 🙈 that needs to be checked by a *REAL* programmer ... *YOU!* 😆.
* Whatever we do with the example, I recommend keeping it simple and something that a dev can cut-'n-paste as a …
=> DOM cleanup with MutationObserver updates

aspnetcore/blazor/components/quickgrid.md
Fixes #29816
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/fce82075870847a7a0e218a588075200fa4ed61e/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-29817) |
=> QuickGrid 8.0 updates

aspnetcore/fundamentals/logging/index.md
The "Log level" section describes an example scenario that says "`Trace` and `Information`" and "`Trace` or `Information`", suggesting that `Debug` levels are excluded from that example.  This seemed unexpected to me, and I wondered if it may have been reflecting an older version of the defined log levels.  I changed those phrases to instead say "`Trace` through `Information`" to be harmonious with the existing verbiage that says "`Warning` through `Critical`".
Fixes #29822
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/0857ef7eae9e76ef60ee87d60cd1eccffec0040b/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundament …
=> Changing "Trace and/or Information" verbiage to include "Debug"

aspnetcore/mvc/views/razor.md
Addresses #29854
Rick, I'm not sure if this fixes the whole issue.  I noticed the quick copy of the whole section, when I really only needed to version the added bit on generic type params. This PR fixes that bit.
---
|:--|:--|
| [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/af14b230410a5c5ee59b06cb63e68e4696059a68/aspnetcore/mvc/views/razor.md) | [Razor syntax reference for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?branch=pr-en-us-29857) |
=> Update @typeparam versioning

.repoman.yml
@Rick-Anderson @tdykstra @wadepickett 
We'll need an additional bit of issue processing for Blazor Hybrid issues, including adding @BethMassi to the assignees so that she can track what comes in and probably react directly to community feedback.
I considered setting up a new `ms.technology` for this, but that's probably overkill. I should be able to make this work with a path check, where I ...
* Swap the label ("Blazor Hybrid" for "Blazor").
* Swap the project ([106](https://github.com/dotnet/AspNetCore.Docs/projects/106) for [35](https://github.com/dotnet/AspNetCore.Docs/projects/35)). We've never tried `projects-remove` before on this repo. If this breaks, then I'll revert this in favor of a new `ms.technology`. 🤞 and 🍀 on this PR's changes working out.
* Assign @BethMassi ... and I'll …
=> Blazor Hybrid issue management

aspnetcore/blazor/hybrid/security/security-considerations.md
Fixes #26089
btw -- We use contractions across the docs, but we often avoid it to highlight a "not" (... ***not*** ...), such as in a case like this support remark.
~I don't think we need very specific guidance on use of the Google Play Store here for a Chrome update, but let me know if you want something for it. I can probably scare up a cross-link.~ **UPDATE:** I rephrased it and added a link.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/security-considerations.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d35ff9c1619f748cb322e1e8acdb45f30ba69ae/aspnetcore/blazor/hybrid/security/security-considerations.md) | [ASP.NET Core Blazor Hybrid security considerations](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/security-cons …
=> Android Web View with emulated device

aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/fundamentals/index.md
Fixes #29917
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/a91043ff309b4cdd81e77504dc7aaa1d3d079402/aspnetcore/blazor/fundamentals/configuration.md) | [ASP.NET Core Blazor configuration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?branch=pr-en-us-29918) |
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/a91043ff309b4cdd81e77504dc7aaa1d3d079402/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-29918) |
| …
=> Move code samples and BWA handle errors 8.0

aspnetcore/fundamentals/minimal-apis/handle-errrors.md, aspnetcore/fundamentals/minimal-apis/handle-errrors/sample8/Program.cs
Fixes #28756
Some changes that I made while copy-pasting the existing snippets into the program file:
- Made sure each snippet compiles (e.g. `User` was sometimes not declared within the snippet)
- Consistency: I added the `/` endpoint in each snippet where it wasn't added before
- Consistency: used `MapGet` in each snippet to create an endpoint (before `Map` and `MapGet` was used)
- Added some code highlighting where I thought it was needed
If you don't mind, I also got the following questions:
- I noticed two ways of referring to snippets `:::code` vs `[!code-csharp[]`, is there a difference and/or preference?
- In this PR I created a section for each snippet, is that the way to go, or is that a better way? I mainly did this otherwise I couldn't hide some parts, but this ends up with …
=> handle-errors: use project file code snippets

aspnetcore/performance/caching/distributed.md, aspnetcore/performance/caching/output.md, aspnetcore/performance/caching/output/includes/output7.md, aspnetcore/performance/caching/output/samples/8.x/Gravatar.cs, aspnetcore/performance/caching/output/samples/8.x/OCMinimal.csproj, aspnetcore/performance/caching/output/samples/8.x/Program.cs, aspnetcore/performance/caching/output/samples/8.x/appsettings.Development.json, aspnetcore/performance/caching/output/samples/8.x/appsettings.json
Fixes #29833 
|:--|:--|
| [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/30832bf2b45bd5f63cd7bfae69f54317af2c7fd9/aspnetcore/performance/caching/distributed.md) | [Distributed caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-8.0&branch=pr-en-us-29941) |
| [aspnetcore/performance/caching/output.md](https://github.com/dotnet/AspNetCore.Docs/blob/30832bf2b45bd5f63cd7bfae69f54317af2c7fd9/aspnetcore/performance/caching/output.md) | [Output caching middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0&branch=pr-en-us-29941) |
---
|:--|:--|
| …
=> .NET 8 Redis-based output caching

aspnetcore/docfx.json
We can't have Blazor/Blazor Hybrid alphabetically in the list because sub-paths of Blazor node articles include at least one of the segments that apply a different technology to the document, namely a path segment of "security" for a Blazor security article led to the assignment of the `aspnetcore-security` technology 😈. This was avoided in the past by a different rule that relied on the path of the article, but that rule had to be removed so that Blazor Hybrid articles receive the Blazor Hybrid technology (note that the Blazor Hybrid node/folder is within the Blazor node/folder). Because these tech assignments are made on a ***last-assignment-wins strategy***, we need the Blazor tech assignments last in order to get Blazor issue labelling, etc. applied.
cc: @wadepickett @Rick-Anderson …
=> Move Blazor technology assignment down

aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/first-web-api/includes/first-web-api3-7.md
Fixes #28715
Changed the instruction on VS Code to specify the HTTPS profile for `dotnet run` on the command line.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/5aa54dea1716eaeac547e1b93d05b61a7eda6609/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-29952) |
=> Create Web API: HTTPS profile instructions

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
Change `T out` to `out T` in 4 places
=> Out and type order in code sample

aspnetcore/client-side/dotnet-interop.md
Addresses #29985
Pavel, I think it's ok if we tell devs to see that content making it clear that I plan to circle around and incorporate guidance from it later this year or early next year. The remark elevates the importance of that content in hopes that devs are less likely to skip looking at it.
On Line 17, the NIT change is just to make it say ".NET 7 or later" where it currently only says ".NET 7".
This PR won't close the issue, so the work item won't get lost. It's tracked by the Blazor GH project.
---
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/67bd00cad2783d229832730db09967e6c49832a9/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from …
=> Surface new guidance

aspnetcore/migration/50-to-60.md
@tdykstra @wadepickett @Rick-Anderson ... I'm adding a cross-link to our NRT coverage in the 5.0-6.0 migration topic for ...
https://learn.microsoft.com/dotnet/csharp/language-reference/operators/null-forgiving
... because I have some Blazor implementations that use it. I cross-link to this content for NRT coverage.
---
|:--|:--|
| [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/378c2a0ca768dcbf834829a3aae9e48c4a8b83bd/aspnetcore/migration/50-to-60.md) | [Migrate from ASP.NET Core 5.0 to 6.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?branch=pr-en-us-29990) |
=> Add a cross-link

aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/project-structure.md, aspnetcore/blazor/tooling.md, aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/index.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/ede129cc2e9b730bd6a11c2bd5bec28199c0c09d/aspnetcore/blazor/fundamentals/configuration.md) | [ASP.NET Core Blazor configuration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?branch=pr-en-us-29996) |
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/ede129cc2e9b730bd6a11c2bd5bec28199c0c09d/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependen …
=> Full-stack UI updates (Fundamentals/Components nodes)

aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/includes/location-client-and-server.md, aspnetcore/blazor/includes/location-client.md, aspnetcore/blazor/includes/location-server.md
Fixes #30003
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/e7eda522c94db44ceea62c31ed07d0a3e58e4ccf/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-30004) |
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/e7eda522c94db44ceea62c31ed07d0a3e58e4ccf/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-30004) |
=> Glob & loc full-stack UI updates

aspnetcore/grpc/troubleshoot.md, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/GrpcGreeter.csproj, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/Program.cs, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/Protos/greet.proto, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/Services/GreeterService.cs, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/appsettings.Development.json, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeter/appsettings.json, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeterClient/GrpcGreeterClient.csproj, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeterClient/Program.cs, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeterClient/Protos/aggregate.proto, aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeterClient/Protos/greet.proto
Fixes #29224
Moved 8.0 gRPC Troubleshoot topic code snippets to client and server app samples.
---
|:--|:--|
| [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/7ee689d4ee3df03b71ed045499ced05d047c3d68/aspnetcore/grpc/troubleshoot.md) | [Troubleshoot gRPC on .NET](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?branch=pr-en-us-30008) |
=> 8.0: gRPC Troubleshoot: Move code snippets to app samples

aspnetcore/fundamentals/minimal-apis/7.0-samples/todo/Program.cs, aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/todo/Program.cs, aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/todo/Program.cs, aspnetcore/fundamentals/minimal-apis/samples/todo/Program.cs, aspnetcore/tutorials/min-web-api.md, aspnetcore/tutorials/min-web-api/samples/6.x/todo/Program.cs, aspnetcore/tutorials/min-web-api/samples/6.x/todoDTO/Program.cs, aspnetcore/tutorials/min-web-api/samples/7.x/todo/Program.cs, aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs, aspnetcore/tutorials/min-web-api/samples/7.x/todoGroup/Program.cs, aspnetcore/tutorials/min-web-api/samples/7.x/todoTypedResults/Program.cs
Fixes #30026
Within the page I also found more delete endpoints/handlers that could be updated.
If this is not desired I can revert these changes.
Side note: I like the new "Examine and test the endpoint" sections for the v8 docs! 
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ad32df620cd96fcae710f1a5c3fc18c4fc3aab2/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-30036) |
=> update delete handlers in the minimal API tutorial

aspnetcore/grpc/netstandard.md, aspnetcore/grpc/supported-platforms.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2197
@jtattermusch Is this what you're looking for?
---
|:--|:--|
| [aspnetcore/grpc/netstandard.md](https://github.com/dotnet/AspNetCore.Docs/blob/32e76a58222347e7dd61c9b5f93277275adc9ecd/aspnetcore/grpc/netstandard.md) | [Use gRPC client with .NET Standard 2.0](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?branch=pr-en-us-30033) |
| [aspnetcore/grpc/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/32e76a58222347e7dd61c9b5f93277275adc9ecd/aspnetcore/grpc/supported-platforms.md) | [gRPC on .NET supported platforms](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?branch=pr-en-us-30033) |
=> Improve documentation around .NET Framework and gRPC-Web in the client

aspnetcore/tutorials/first-mvc-app/new-field.md, aspnetcore/tutorials/first-mvc-app/new-field/includes/new-field7.md
Fixes #29949 
Link to code for adding a new field section was pointing to v6 rather than v8 code for .NET 8 or v7 code for .NET 7 version of the topic.
Issue corrected in both version 7 and 8 of this topic.
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/a34a0b2ce400b3a3fcde0c2f12c4992af9b8ba77/aspnetcore/tutorials/first-mvc-app/new-field.md) | [Part 8, add a new field to an ASP.NET Core MVC app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-8.0&branch=pr-en-us-30050&tabs=visual-studio#add-a-rating-property-to-the-movie-model) |
=> First MVC correct new field code link

aspnetcore/includes/net-prereqs-mac-8.0.md
Fixes #30063 
Correcting the include for .NET 8 VS Mac prereq to indicate VS for Mac (Latest) and point out the pref setting to allow .NET 8 to be used.  
Previously it indicated VS for Mac Preview, but the VS for Mac Preview does not yet have the option to use .NET 8.
=> Correct include for .NET 8 VS Mac prereq

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/components/built-in-components.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/server/additional-scenarios.md, aspnetcore/blazor/security/server/index.md, aspnetcore/security/anti-request-forgery.md, cspell.json
Fixes #29728
Rick, Tom, Wade ... The antiforgery topic only has two changes ...
> \* \<xref:Microsoft.AspNetCore.Builder.ComponentEndpointRouteBuilderExtensions.MapBlazorHub%2A>
... is changed to ...
> \* \<xref:Microsoft.Extensions.DependencyInjection.RazorComponentsServiceCollectionExtensions.AddRazorComponents%2A>
... and this is added ...
> \#\#\# Blazor
> 
> For more information, see \<xref:blazor/security/index#antiforgery-support>.
Thanks in advance for helping later with the INCLUDES work on the versioning, which I'm not completely familiar with on folder/filenaming. I need to get this PR done and merged *ASAP*. I'm 🏃🏃🏃🏃😅 and need to get on with a large set of further Blazor updates.
---
|:--|:--|
| …
=> Blazor forms and antiforgery 8.0

aspnetcore/log-mon/metrics/metrics.md
Addresses https://github.com/dotnet/aspnetcore/issues/33387
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f316bac779ec0f3db0044e6c4d615930b81446c/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30068) |
=> Add metrics unit testing

aspnetcore/blazor/forms-and-input-components.md
Addresses #29728
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/877c4d5579557c5167bb0b97e885ed452f6b1c1b/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30081) |
=> Blazor forms and antiforgery 8.0 updates (2)

aspnetcore/tutorials/getting-started-with-NSwag.md
Fixes #30072
This was an accidental copy-paste of the swashbuckle instructions that I added with #29993
These can be removed because NSwag renders these comments by default, without additional configuration.
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/40a098d737cbd1e8e7b9814617c14176503d57c6/aspnetcore/tutorials/getting-started-with-NSwag.md) | [Get started with NSwag and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-NSwag?branch=pr-en-us-30085) |
=> Remove IncludeXmlComments instructions for NSwag sample

aspnetcore/blazor/components/virtualization.md
Fixes #30094
@etemi ... Would you like to review the documentation for the feature?
---
|:--|:--|
| [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/29a633f5fd73fca216c3e05cc847f3256a538464/aspnetcore/blazor/components/virtualization.md) | [ASP.NET Core Razor component virtualization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?branch=pr-en-us-30096) |
=> Virtualize empty content 8.0

aspnetcore/tutorials/first-web-api.md
Fixes #29827 
Update Visual Studio for Mac instruction for .NET 8 and test both VS Code and VS for Mac where they overlap using the same tab.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/6a2b38e08edd83ad553ff9561f6e4fb3ecb00cfc/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-30104) |
=> v8 macOS Update Create a web API

aspnetcore/blazor/components/cascading-values-and-parameters.md
Fixes #30093
***Steve***, for ...
> something like a global “weather forecast” service that is defined in Program.cs, has some way of getting state changes from an external source of information, and exposes the current forecast as a cascaded value (which may change over time).
Do you want me to draft up something like that now, table it for later (like 24Q1), or not place coverage for that at all?
If you want me to take a 🔪 at it, I'll need some info on triggering `NotifyChangedAsync` from a service because the tests at ...
https://github.com/dotnet/aspnetcore/blob/f902a5b27cf2d89e555a1cf67ae796d11dab039e/src/Components/Components/test/CascadingParameterTest.cs#L571-L635
... new up the `CascadingValueSource` in the method. How is `NotifyChangedAsync` called in a service? What am I …
=> Root-level cascading values 8.0

aspnetcore/blazor/performance.md
Addresses #30118
Confirmed that the newer approach works for ***all releases*** >=3.1. Therefore, this removes the versioned content that was placed when the original updates were made at 6.0.
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/d38a342f118954fa7a8c5c524ff668dfd0f222ea/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-30121) |
=> Remove prior reusable RenderFragment approach

aspnetcore/security/anti-request-forgery.md
Clarifying the behavior of antiforgery validation when a token is provided in both the header and form payload.
---
|:--|:--|
| [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/730cbc5a1a9f8da0e3c54b7072414510b8e6b32d/aspnetcore/security/anti-request-forgery.md) | [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?branch=pr-en-us-30090) |
=> Add note about processing of anti-forgery tokens in header and form

aspnetcore/blazor/fundamentals/handle-errors.md
Fixes #30127
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/dbdf668b919bc1d47f3920ff3cbdf529f9b9b336/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-30128) |
=> Error boundary updates 8.0

aspnetcore/fundamentals/servers/kestrel/endpoints/includes/endpoints5-7.md
This information is not version specific - certificates should always be protected.
=> Add a note about restricting access to certificate files

aspnetcore/blazor/tooling.md
Fixes #30151
I'm glad you said something in spite of my working on it. This is looking much better.
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/a9e78de3573eeca7b9d1886bcab7efe7489a207e/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-30152) |
=> Update WASM AOT guidance 8.0

aspnetcore/blazor/test.md
Fixes #30165 
Following changes were made:
* Showcasing `.razor` file based tests
* Showcasing that `TestContext` should not be created in each test
* Moved wording from "selecting" a button to "clicking"
CC @egil
---
|:--|:--|
| [aspnetcore/blazor/test.md](https://github.com/dotnet/AspNetCore.Docs/blob/ae58f0f09fd568ee7f23f286a8f767c6c17558cc/aspnetcore/blazor/test.md) | [Test Razor components in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/test?branch=pr-en-us-30166) |
=> Update bUnit docs
