dotnet/AspNetCore.Docs

.repoman.yml

Reverts dotnet/AspNetCore.Docs#22567

Revert "Update .repoman.yml"

---

aspnetcore/blazor/security/webassembly/additional-scenarios.md

Clarify prerender with authorized content

---

aspnetcore/blazor/file-uploads.md

Fixes #22590
@Rick-Anderson ... If you would like something similar added to the main doc set's file uploads topic, let me know. :ear:

Call out PS for dummy test files

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Fixes #22607
Thanks @stefanloerwald! 🎷

Blazor WASM Brotli update

---

aspnetcore/security/authentication/certauth.md

Add sample code in docs to handle URL-encoded client certs, eg. on NGINX / Kubernetes NGINX Ingress

---

aspnetcore/fundamentals/routing.md

Per the build report on https://github.com/dotnet/AspNetCore.Docs/pull/22611.

Update internal routing topic links

---

aspnetcore/blazor/globalization-localization.md

I'll make some of the code more cut-'n-paste-capable out of the topic by focusing the code blocks on the exact lines that the dev needs. This should *speed them UP!* 🏃

Blazor glob/loc code layout patch

---

aspnetcore/tutorials/first-mvc-app/adding-model.md

* Correct spacing 
* Format unformatted code elements 
* Change "`@model` keyword" to "`@model` directive"
* Format buttons with `<kbd>`

Improve formatting

---

aspnetcore/web-api/handle-errors.md

Documentation for https://github.com/dotnet/aspnetcore/issues/4953.

Add docs on generating ProblemDetails payload

---

aspnetcore/security/enforcing-ssl.md

Cert trust info for more linux distros

---

aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/blazor/fundamentals/logging.md

Logging for prerendered hosted WASM

---

aspnetcore/blazor/fundamentals/configuration.md

Client security and Blazor paths

---

aspnetcore/blazor/fundamentals/signalr.md
aspnetcore/blazor/host-and-deploy/server.md

Fixes #21723
Thanks @ErikApption! :rocket:
Brennan ... Do you want to cover anything WRT ...
> It looks like you can grab `IOptions<RouteOptions>` from DI after `UseEndpoint` to get all the routing information, including the endpoints.

Blazor SignalR enhancements

---

aspnetcore/tutorials/build-a-blazor-app.md
aspnetcore/zone-pivot-groups.yml

Fixes #22676
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.0&branch=pr-en-us-22675)

Pivot the Blazor ToDo List tutorial

---

aspnetcore/tutorials/razor-pages/new-field.md

fixed Mac OS migration command for Add a migration for rating session ( line 119, 120)

fixed MacOS migration command

---

aspnetcore/signalr/messagepackhubprotocol.md

Add .NET 6 monikers for productive diff file 
eventually will address #22008

prep MessagePack for .NET 6

---

aspnetcore/signalr/messagepackhubprotocol.md

Fixes #22008
@fiyazbinhasan please review
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-6.0&branch=pr-en-us-22738#javascript-client)

Remove msgpack5 for .NET 6 /3

---

aspnetcore/security/cross-site-scripting.md

Code style fixes cross-site-scripting

---

aspnetcore/fundamentals/websockets.md

API docs don't have the APIs yet, so can't link to them

Add WebSocket Compression

---

aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/event-handling/EventHandlerExample8.razor
aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample8.razor

Null-check ElementReferences

---

aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample11.razor
aspnetcore/blazor/common/samples/3.x/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample11.razor
aspnetcore/blazor/common/samples/5.x/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample11.razor
aspnetcore/blazor/common/samples/5.x/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample11.razor
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-3.1&branch=pr-en-us-22772#catch-javascript-exceptions)

Catch JS interop exceptions

---

aspnetcore/web-api/index.md

Remove 25 moniker pairs hell in WebAPI /a

---

aspnetcore/toc.yml

Add Kestrel displayname to TOC /4

---

aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/first-web-api/samples/5.x/TodoApi/Startup.cs

show removed Swagger calls /3

---

aspnetcore/data/ef-rp/intro.md
aspnetcore/data/ef-rp/intro/samples/cu50/Startup.cs
aspnetcore/data/ef-rp/intro/samples/cu50/StartupSQLite.cs

Fixes #21131 and #20870
@JonPSmith please review

add DB exception filter /6

---

aspnetcore/security/authentication/claims.md

Small text fixes to doc:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims

small text fixes to security-authentication-claims doc

---

aspnetcore/mvc/views/razor.md
aspnetcore/tutorials/first-web-api.md

clean up monikers in Razor syntax /3

---

aspnetcore/security/authentication/azure-ad-b2c.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-5.0&branch=pr-en-us-22838)

B2C article typo fixes

---

aspnetcore/3.1/blazor/components/class-libraries.md
aspnetcore/5.0/blazor/components/class-libraries.md
aspnetcore/6.0/blazor/components/class-libraries.md
aspnetcore/toc.yml

Reverts dotnet/AspNetCore.Docs#22870

Revert "Test potential 'is-selected' style fix for ToC"

---

aspnetcore/includes/combine-di.md

Fixes #22862
@serpent5  please review

DI extenstion convention /3

---

aspnetcore/toc.yml

Blazor file versioning

---

aspnetcore/security/authentication/azure-ad-b2c.md
aspnetcore/security/authentication/azure-ad-b2c/sample/Startup.cs
aspnetcore/security/authentication/azure-ad-b2c/sample/appsettings-b2c-userflow.json
aspnetcore/security/authentication/azure-ad-b2c/sample/appsettings.json

Small addition to the doc, added a note about the Azure B2C user flow configuration which requires different app.settings
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c

Damienbod-security-authentication-azure-ad-b2c-add-userflow-note

---

aspnetcore/web-api/advanced/conventions.md
aspnetcore/web-api/advanced/conventions/ValuesController.cs

Fixes  #21655
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-5.0&branch=pr-en-us-22793)

Add valuesController to Web API conventions article /a

---

aspnetcore/fundamentals/websockets.md
aspnetcore/fundamentals/websockets/samples/6.x/WebSocketsSample/Controllers/WebSocketController.cs
aspnetcore/fundamentals/websockets/samples/6.x/WebSocketsSample/Program.cs
aspnetcore/fundamentals/websockets/samples/6.x/WebSocketsSample/WebSocketsSample.csproj
aspnetcore/fundamentals/websockets/samples/6.x/WebSocketsSample/wwwroot/index.html

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/22747
@Rick-Anderson added a sample for .net 6 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-5.0&branch=pr-en-us-22760#accept-websocket-requests)

ws in controller sample

---

aspnetcore/3.1/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/3.1/blazor/tooling.md
aspnetcore/5.0/blazor/components/prerendering-and-integration.md
aspnetcore/5.0/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/5.0/blazor/tooling.md
aspnetcore/6.0/blazor/components/prerendering-and-integration.md
aspnetcore/6.0/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/6.0/blazor/tooling.md
aspnetcore/tutorials/signalr-blazor.md

Blazor VS 16.10 new project guidance

---

aspnetcore/3.1/blazor/blazor-server-ef-core.md
aspnetcore/5.0/blazor/blazor-server-ef-core.md
aspnetcore/6.0/blazor/blazor-server-ef-core.md

Fixes #22905
Thanks @jimmybbb! :rocket: ... I'll take this change to the live doc set immediately, and it should update on the live site within 15 minutes.

Sample link updates

---

aspnetcore/3.1/tutorials/signalr-blazor.md
aspnetcore/5.0/tutorials/signalr-blazor.md
aspnetcore/6.0/tutorials/signalr-blazor.md

Blazor-SignalR sample links update

---

aspnetcore/3.1/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/AddContact.razor
aspnetcore/3.1/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/EditContact.razor
aspnetcore/5.0/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/AddContact.razor
aspnetcore/6.0/blazor/samples/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/AddContact.razor

The previous error message was about updating the Contact however this page was only used for adding new ones so now the message reflects that.
Follow the guidelines [here](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) as this seems more like a documentation change than a code change.

Updated error message on AddContact.razor

---

aspnetcore/fundamentals/static-files.md

Fixes #22926
Thanks @Dillion132! :rocket:

Fix incorrect bookmark destination

---

cspell.json

Here it is. 🎉
The file is picked up ✨ *auto-magically* ✨ by VSC locally.
I'll add more words shortly/later 🏃 ... I just put a few words in here to get the ball rolling. Feel free to edit directly if you want to add your own.

Add cSpell config to repo

---

aspnetcore/mvc/models/validation/samples/3.x/ValidationSample/Pages/Movies/Create.cshtml.cs

Fix validation sample /4

---

aspnetcore/5.0/blazor/components/built-in-components.md

A patch ... best to say "ASP.NET Core" here.

Content update (Blazor -> ASP.NET Core)

---

aspnetcore/toc.yml

[Internal Review of TOC](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-5.0&branch=pr-en-us-22956)
Related to new topic PR #22635

Update TOC to include new Choose ASP.NET Core UI topic

---

aspnetcore/grpc/loadbalancing.md
aspnetcore/toc.yml

Work in progress.
Internal preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-3.0&branch=pr-en-us-22348

Add gRPC client-side load balancing doc

---

aspnetcore/signalr/hubcontext.md

Another preview7 feature
[Internal Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?branch=pr-en-us-22943&view=aspnetcore-6.0#use-ihubcontext-in-generic-code)

Using IHubContext in hub agnostic code

---

aspnetcore/fundamentals/servers/kestrel/http3.md
aspnetcore/fundamentals/servers/kestrel/samples/6.x/Http3Sample/Program.cs
aspnetcore/toc.yml

Tell people why HTTP/3 is good.
Minor updates and improvements.

HTTP/3: Improve Kestrel doc

---

aspnetcore/performance/caching/memory/3.0sample/WebCacheSample/CacheKeys.cs
aspnetcore/performance/caching/memory/sample/WebCache/CacheKeys.cs

Use Expression-bodied members

---

aspnetcore/6.0/blazor/includes/prerendering.md
aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/components/control-head-content.md
aspnetcore/blazor/components/css-isolation.md
aspnetcore/blazor/components/data-binding.md
aspnetcore/blazor/components/event-handling.md
aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/fundamentals/handle-errors.md
aspnetcore/blazor/fundamentals/signalr.md
aspnetcore/blazor/fundamentals/startup.md
aspnetcore/blazor/globalization-localization.md
aspnetcore/blazor/host-and-deploy/index.md
aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
aspnetcore/blazor/javascript-interoperability/index.md
aspnetcore/blazor/project-structure.md
aspnetcore/blazor/security/content-security-policy.md
aspnetcore/blazor/state-management.md

Blazor Preview 7 updates

---

aspnetcore/blazor/hosting-models.md

Language update

---

aspnetcore/6.0/blazor/includes/layout-page-preview-7.md
aspnetcore/blazor/components/dynamiccomponent.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

Blazor 6.0 Preview 7 final updates

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/fundamentals/signalr.md
aspnetcore/blazor/host-and-deploy/server.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
aspnetcore/blazor/test.md

Blazor link updates

---

aspnetcore/signalr/authn-and-authz.md
aspnetcore/signalr/configuration.md

New in preview7, so probably shouldn't merge until that's released.
[Internal review link](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?branch=pr-en-us-22932)

Add new auth config option for SignalR

---

aspnetcore/grpc/client.md

Update gRPC client unsecured docs

---

aspnetcore/blazor/components/dynamiccomponent.md

Addresses https://github.com/dotnet/aspnetcore/issues/35355

Update DynamicComponent instance example

---

aspnetcore/blazor/file-uploads.md

Address https://github.com/dotnet/AspNetCore.Docs/issues/22444#issuecomment-899693489
cc: @TanayParikh

Remove API configurability remark

---

aspnetcore/blazor/file-uploads.md

Addresses https://github.com/dotnet/AspNetCore.Docs/pull/23040#discussion_r689735714

Blazor Server file upload remark update

---

aspnetcore/host-and-deploy/azure-iis-errors-reference.md

I'll be removing the archives page so updating the topic to no longer use it

Updating link

---

aspnetcore/fundamentals/localization.md

Prepare for #23062
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0&branch=pr-en-us-23067)

prepare loc doc for V6 /4

---

aspnetcore/security/data-protection/configuration/overview.md

Applies @GrabYourPitchforks  non-suggestion suggestions to #23068

Apply Pitch fork guys suggestions

---

.openpublishing.publish.config.json

https://review.docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-5.0&branch=pr-en-us-23095

Rename ref branch to xamarin /7

---

cspell.json

* Adding some common words for Blazor topics.
* Alphabetize and collapse the list, which I hope will make it easier to manage as it grows.

cSpell word list update

---

aspnetcore/includes/net-prereqs-vs-6.0.md
aspnetcore/includes/net-prereqs-vs19-vs22-6.0.md

VS19 or VS2022 for prerequisites /7

---

aspnetcore/security/data-protection/configuration/overview.md

Fixes #23080
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0&branch=pr-en-us-23081#logging-dataprotection)

Add logging to dataProtection /4

---

aspnetcore/blazor/fundamentals/logging.md

Fixes #23147
Thanks @Orange23333! :rocket:

Update heading for loc

---

aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/tooling.md

Fixes #22442
Fixes #22440
Fixes #23102
Internal Review Topics (links to sections):
* [Hosting models](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1&branch=pr-en-us-23065#blazor-webassembly) &mdash; Passing remarks on the new features.
* [Host and deploy: WebAssembly](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-23065#ahead-of-time-aot-compilation) &mdash; Config details ... AOT section is followed by the runtime relinking section.
* [Tooling](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1&branch=pr-en-us-23065#net-hot-reload) &mdash; Hot Reload
Preview remarks are here, and I'll remove …

Blazor AoT, runtime relinking, hot reload

---

aspnetcore/blazor/hosting-models.md

Tooling maturity text removal

---

aspnetcore/data/ef-rp/concurrency.md

Improved info about where the Utility.cs class should be created. Similar to the PaginatedList.cs example from previous sections.

Utility path info

---

aspnetcore/mvc/controllers/filters.md

The article links to controller (!) methods, but it is actually talking about ActionFilter (!) methods!!!

Fixed links to wrong methods

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60/Models/MovieDateRatingDA.cs
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60/Models/MovieDateRatingDAmult.cs
aspnetcore/tutorials/razor-pages/validation.md

fix validation snippets /6/ra

---

aspnetcore/blazor/security/webassembly/index.md

Fixes #20689
Thanks @hanslai! :rocket:
Thanks @m-gug! :rocket:

Blazor WASM secure app via Imports update

---

aspnetcore/data/ef-rp/intro/samples/cu50/PaginatedList.cs

Use expression bodied properties.

Use expression body

---

aspnetcore/fundamentals/configuration/index/samples/6.x/EFconfigSample/TODO.txt

stub folder

---

aspnetcore/security/cors.md

prep CORS for V6 monikers /6

---

aspnetcore/blazor/debug.md
aspnetcore/blazor/tooling.md

Hosted WASM app start update

---

aspnetcore/security/authentication/accconfirm.md
aspnetcore/security/authentication/accconfirm/sample/WebPWrecover30/Services/AuthMessageSenderOptions.cs
aspnetcore/security/authentication/accconfirm/sample/WebPWrecover30/Services/EmailSender.cs

Fixes #23096.
- Removed the SendGridUser field. The Sendgrid key will suffice.

Update SendGrid Implementation

---

aspnetcore/blazor/javascript-interoperability/index.md

Fixes #21278
Thanks @neil-rubens! :rocket: ... I *might* do a little more with this subject later. We have a current Blazor *Static files* topic that could be expanded to receive this guidance. Currently, that's focused on one or a few Blazor Server concepts, but it could be made to cover both hosting models and could discuss Blazor static asset caching and how to control/manage it. I've marked this subject for discussion with management on a [Blazor tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286). We'll discuss it either later this year after 6.0 releases or in early 2022. For now, what's on this PR should be ok.

Blazor JS file cache/no-cache guidance

---

aspnetcore/mvc/controllers/routing/samples/3.x/main/Controllers/ProductsController.cs

fixes #23222 
Updated routing comment to include action name

update routing comment

---

aspnetcore/mvc/controllers/routing.md

routing V6 /3x moniker prep /3x

---

aspnetcore/fundamentals/servers/httpsys.md

moniker fix for V6 on httpsys/4

---

aspnetcore/security/authentication/identity.md

prep identity for V6 monikers

---

aspnetcore/fundamentals/servers/httpsys.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-6.0&branch=pr-en-us-23257#http3-support)
@Tratcher  writes:
> Fixes [dotnet/aspnetcore#35204](https://github.com/dotnet/aspnetcore/issues/35204)
> 
> Consider holding this update until RC1 releases.
Yes, this will merge into the RC1 branch
~~@Tratcher  this is just your work. Once you approve this version, I'll do the edit and you can check my commit for changes.~~

RC1 httpsys by chris/4

---

aspnetcore/blazor/javascript-interoperability/index.md

Fixes #17595
Thanks @LaughingJohn! :rocket: ... We have (somewhat buried) coverage on this subject back in the *Performance* (WASM pivot) guidance. This little blurb and cross-link in the JS interop *Overview* topic will help surface it. Sorry for the delay getting to your issue. I've been 🏃😅 for quite a while and finally have a tiny break here prior to 6.0 RC1's release to look at and address some of the older issues.

Cross-link async/sync perf guidance

---

aspnetcore/host-and-deploy/iis/http3.md
aspnetcore/toc.yml

Contributes to https://github.com/dotnet/aspnetcore/issues/26415
***@Rick-Anderson  edit:***
~Much of this content is the same as Http.Sys (#23252)~
Much of this content is the same as Http.Sys (#23257)
Note this feature work is available in rc2. https://github.com/dotnet/aspnetcore/pull/36054

Don't merge until RC1: Docs for HTTP/3 on IIS

---

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

RC1 remark removal

---

aspnetcore/blazor/components/index.md

Render components from JS

---

aspnetcore/blazor/samples/5.0/BlazorSample_Server/Pages/event-handling/EventHandlerExample8.razor
aspnetcore/blazor/samples/5.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample8.razor
aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/event-handling/EventHandlerExample8.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample8.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor

Fixes #23305
Thanks @Continuitis! :rocket: ... I'll roll with it here and take further feedback.

Blazor file uploads example update

---

aspnetcore/mvc/views/razor.md

it transitions into Razor-specific markup. Otherwise, it transitions into plain HTML.
-- NOT "plain C#"

Fixed @ symbol work definition

---

aspnetcore/blazor/blazor-server-ef-core.md

Fixes #22985
Thanks @TheRealDuckboy! :rocket: ... The blog post will become an official MS document. For now, we'll cross-link the blog post. Later, we'll cross-link to the official doc. ~I'll open a follow-up issue on hold to make that link update.~ **_Done!_** :+1:

Update Blazor-EFCore factory remarks

---

aspnetcore/grpc/services.md

Added a line about ServerCallContext

Updated gRPC services.

---

aspnetcore/tutorials/razor-pages/model.md

Addresses #23346
Addresses #23360
cc: @chpong

Remove extra words

---

aspnetcore/introduction-to-aspnet-core.md

Fixes #23363
Thanks @Johnvan! 🦘

Download a sample guidance updates

---

aspnetcore/blazor/components/prerendering-and-integration.md

Blazor prerendering and integration updates

---

aspnetcore/grpc/loadbalancing.md

Update code snippets to the correct API.
https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.Net.Client/GrpcChannelOptions.cs

Update code snippets to the correct API - loadbalancing.md

---

aspnetcore/blazor/components/prerendering-and-integration.md

Addresses https://github.com/dotnet/aspnetcore/issues/37118
Thanks @Swimburger! :rocket:

Update WASM prerendering 6.0 guidance

---

aspnetcore/whats-new/21-09.md
aspnetcore/whats-new/index.yml
aspnetcore/whats-new/toc.yml

What's new for Sept 2021

---

aspnetcore/signalr/configuration.md

[Internal review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&branch=pr-en-us-23413)

Update SignalR configuration for RC1

---

aspnetcore/grpc/basics.md
aspnetcore/tutorials/grpc/grpc-start/sample6/GrpcGreeter/Services/GreeterService.cs

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-6.0&branch=pr-en-us-23419)
.NET 6 update for gRPC services with C#
Fixes #23403

gRPC service with CSharp v6 udpate

---

CONTRIBUTING.md
aspnetcore/blazor/state-management.md
aspnetcore/security/data-protection/introduction.md

Rick, this is per a side discussion with Artak offline while we were chatt'in about the upcoming WASM deployment layout topic. "Unsuitable" isn't a good choice for localization, and he recommends going with 'not intended for'/'isn't intended for' (or similar) language.
Please merge if ur good ... I'm going to be OOF for a bit 🏃 ... *Friday errands!* 🎉 ... e.g., ... Nice to have some 🍕🍺 food to eat!

Wording change ("unsuitable")

---

aspnetcore/fundamentals/servers/kestrel/http3.md

Fixes https://github.com/dotnet/aspnetcore/issues/26415

Document UseHttps limitations for Http/3 in Kestrel

---

aspnetcore/blazor/components/index.md

Fixes #23431
Thanks @DarkStarDS9! :rocket: ... I'm going to let the Data Binding topic cover that concept with the existing examples, in particular the password binding example for this scenario. The section here can cross-link to that. This way, the section here can remain focused with the simpler example of how writing directly to component params can lead to a poor implementation with bad behavior.
State management should remain the focus of its own topic. If you have further feedback on binding with state management, open an issue from that topic.

Cross-link databinding

---

aspnetcore/blazor/security/webassembly/index.md

Add cross-link

---

aspnetcore/grpc/test-tools.md

Fixes #22974
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/test-tools?view=aspnetcore-5.0&branch=pr-en-us-23094#call-grpc-services)
@clarkezone please review

grpcurl syntax on MacOS /8

---

aspnetcore/grpc/diagnostics.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0&branch=pr-en-us-23434)
Updates to reflect .NET 6, project templates and top level statements for: 
- Content 
- Server and Client diagnostic app samples

v6 update: gRPC Diagnostics

---

aspnetcore/security/authentication/identity-enable-qrcodes.md

Path should be "\~/js/qr.js" not "\~/js/qs.js"

Correct typo in example filepath

---

aspnetcore/blazor/security/webassembly/additional-scenarios.md

Fix modifier declaration order

---

aspnetcore/blazor/host-and-deploy/server.md

For: https://github.com/dotnet/aspnetcore/issues/37014
TODO: Need to update https://aka.ms/blazor-server-using-fallback-long-polling to point towards this.

Add Details for Configuring Azure App Service For Blazor Deployment

---

aspnetcore/blazor/components/virtualization.md

Fixes #23692
Thanks @omuleanu! :rocket:

Change word

---

aspnetcore/blazor/file-downloads.md
aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
aspnetcore/toc.yml

Fixes: https://github.com/dotnet/aspnetcore/issues/30736

Blazor File Downloads Documentation

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/toc.yml
aspnetcore/tutorials/min-web-api.md

Fixes #23677
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0&branch=pr-en-us-23679)

Add minimal APIs to TOC /4

---

aspnetcore/fundamentals/routing.md

Fixes #23684
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0&branch=pr-en-us-23687#guidance-for-large-route-tables)
@javiercn  once this is approved I'll add it to the previous versions. Does https://github.com/dotnet/aspnetcore/issues/30092 only mitigate the problem?

Guidance for large route tables /2

---

aspnetcore/signalr/api-design.md
aspnetcore/signalr/security.md

cc: @Rick-Anderson @serpent5 @wadepickett ... These are the last ones that I see. They popped up on a build report for a PR that I'm working.

Update author in metadata

---

aspnetcore/blazor/debug.md

Fixes #23709
Thanks @Ruoruni! :rocket:

Remove Blazor debugging step

---

aspnetcore/blazor/fundamentals/routing.md
aspnetcore/blazor/host-and-deploy/index.md
aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/security/includes/troubleshoot.md

Fixes #23695
Thanks @cmedianu ... This mirrors our discussion on the issue. I'll wait until I hear back from you before publishing this 🤞. Later, I'll get with Javier on the fallback mapping that doesn't seem to pertain to a basic sub-app hosting scenario. I've temporarily placed that coverage in a comment here. When I find out what it applies to, I'll open a new issue and address it (or remove it). It will be tracked by https://github.com/dotnet/AspNetCore.Docs/issues/19286.

App base path/sub-app hosting updates

---

aspnetcore/toc.yml

Remove .NET Core from TOC

---

aspnetcore/blazor/components/event-handling.md

Fixes: https://github.com/dotnet/aspnetcore/issues/30199

Update `stopPropagation` Blazor Delegated Events Docs

---

aspnetcore/security/app-secrets.md

moniker prep for secrets

---

aspnetcore/blazor/file-downloads.md
aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/images.md
aspnetcore/toc.yml

Fixes: https://github.com/dotnet/aspnetcore/issues/36991
Fixes: https://github.com/dotnet/aspnetcore/issues/37016

Blazor Working With Images Docs

---

aspnetcore/blazor/includes/js-interop/3.1/size-limits.md
aspnetcore/blazor/includes/js-interop/5.0/size-limits.md
aspnetcore/blazor/includes/js-interop/6.0/size-limits.md
aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

Addresses #23738
cc: @TanayParikh

Blazor JS interop SignalR size limits (Part 2)

---

aspnetcore/fundamentals/configuration/options.md
aspnetcore/fundamentals/configuration/options/samples/6.x/OptionsSample/Program.cs
aspnetcore/fundamentals/configuration/options/samples/6.x/OptionsSample/SampleApp.csproj

prep monikers for Options

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/performance.md

Blazor hosting model pivot updates

---

aspnetcore/blazor/call-web-api.md

Blazor pivot updates (2)

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md

Fixes #23780 
Thanks @bizframe! :rocket:

Call out included trailing slash

---

aspnetcore/blazor/fundamentals/handle-errors.md

Patch section location

---

aspnetcore/tutorials/first-mvc-app/start-mvc.md
aspnetcore/tutorials/first-web-api.md
aspnetcore/tutorials/grpc/grpc-start.md
aspnetcore/tutorials/min-web-api.md
aspnetcore/tutorials/razor-pages/razor-pages-start.md

remove Preview from tutorials /3

---

aspnetcore/data/ef-rp/crud.md
aspnetcore/data/ef-rp/intro.md

pre EF/RP monikers /3

---

aspnetcore/migration/50-to-60.md

Fixes : https://github.com/dotnet/AspNetCore.Docs/issues/23806

replace .net6 rc with .net 6

---

aspnetcore/tutorials/min-web-api.md
aspnetcore/tutorials/min-web-api/samples/6.x/todoDTO/Program.cs

fix min web API todo /2

---

aspnetcore/migration/50-to-60-samples.md

Reference the correct code snippet when changing the HTTP server implementation to be HTTP.sys based.

Reference the correct code snippet in "Customize IWebHostBuilder" section

---

aspnetcore/release-notes/aspnetcore-6.0.md
aspnetcore/release-notes/aspnetcore-6.0/samples/HomeController.cs

fix snippet /2

---

aspnetcore/performance/caching/memory.md

Prepare Cache In-Memory for 6.0

---

aspnetcore/index.yml

[Internal Review: ASP.NET hub page](https://review.docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-6.0&branch=pr-en-us-23804)
Fixes #22599 
- Reviewed hub topic data to see if any highlighted links need to move. (Data made available on Teams)
- Updated to .NET 6 / VS 2022
- Verified Hub uses latest required template.

v6 Update ASP.Net Hub

---

aspnetcore/blazor/host-and-deploy/index.md

Fixes #23856
Thanks @gbthakkar! :rocket: ... I tested this scenario locally, and the guidance worked. If you have trouble implementing it, we recommend obtaining product support on public support forums, such as ...
* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Fix file extension

---

aspnetcore/tutorials/getting-started-with-swashbuckle.md
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/TodoApi.csproj
aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/6.0/SwashbuckleSample/SwashbuckleSample.csproj

Update Swashbuckle tutorial syntax and 6.0 RTM

---

aspnetcore/migration/50-to-60-samples.md
aspnetcore/migration/50-to-60-samples/samples/Web6Samples/Program.cs

Fixes #23873.
cc @Rick-Anderson.

Fix UseWebRoot example in Minimal APIs

---

aspnetcore/mvc/models/model-binding.md
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Controllers/PetsController.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/JsonConverters/ObjectIdConverter.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/Instructor.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/InstructorWithCollection.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/InstructorWithDictionary.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/ModelWithObjectId.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Models/ObjectId.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Pages/Instructors/Create.cshtml.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Pages/Instructors/Edit.cshtml.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Pages/Instructors/Index.cshtml.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Pages/InstructorsWithCollection/Create.cshtml.cs
aspnetcore/mvc/models/model-binding/samples/3.x/ModelBindingSample/Startup.cs
aspnetcore/mvc/models/model-binding/samples_snapshot/3.x/Startup.cs

Prepare Model-Binding for 6.0

---

aspnetcore/migration/50-to-60-samples/samples/Web6Samples/IHelloService.cs
aspnetcore/migration/50-to-60-samples/samples/Web6Samples/Program.cs

Fixes #23839.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0&branch=pr-en-us-23884#aspnet-core-6-9).

Remove nullability from IHelloService sample

---

aspnetcore/release-notes/aspnetcore-6.0.md

fix snippets in what's new

---

aspnetcore/fundamentals/minimal-apis.md

Update minimal-apis.md - fix url link for autofac

---

aspnetcore/fundamentals/host/hosted-services.md

Update hosted-services.md - Remove typo `}`

---

aspnetcore/razor-pages/index.md

Moniker prep for into to RP /4

---

aspnetcore/blazor/components/control-head-content.md
aspnetcore/migration/50-to-60.md

Fixes #23920
Thanks @fingers10! :rocket:

Ad hoc feature adoption and HeadOutlet updates

---

aspnetcore/blazor/components/css-isolation.md

Surface how to disable CSS isolation

---

aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs

remove snippet /2

---

aspnetcore/tutorials/signalr.md

signalR moniker prep /2

---

aspnetcore/fundamentals/middleware/write.md

Fixes #23950.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0&branch=pr-en-us-23951).

Use InvokeAsync in all Write Middleware examples

---

aspnetcore/blazor/samples/3.1/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor
aspnetcore/blazor/samples/3.1/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor
aspnetcore/blazor/samples/5.0/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor
aspnetcore/blazor/samples/5.0/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor

Fixes #23943
Thanks @liangpeihui! 🎸

Make example classes public

---

aspnetcore/security/authentication/social/microsoft-logins.md

Prepare Microsoft Logins for 6.0

---

aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md

Fixes #23948
Thanks @dlyltm! :rocket:

Clarify Component TH cross-linked content

---

aspnetcore/blazor/fundamentals/handle-errors.md

Fixes #23942
Thanks @liangpeihui! 🎸 
Javier ... for reference to an example that @liangpeihui was working with, see the issue :point_right: #23942.

Razor component instantiation update

---

aspnetcore/mvc/views/partial/sample/PartialViewsSample/Views/Articles/Read.cshtml

in MVC partial view example, added `@` to actually render the article section partial view

added @ to render partial view _ArticleSection in mvc example

---

aspnetcore/fundamentals/dependency-injection.md

Corrects the language of this snippet to C# instead of json

fix snippet language in dependency-injection

---

aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/blazor/fundamentals/logging.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md
aspnetcore/blazor/security/webassembly/index.md
aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/http-requests.md
aspnetcore/fundamentals/minimal-apis.md
aspnetcore/includes/scaffold-identity/id-scaffold-dlg-auth.md
aspnetcore/security/authentication/scaffold-identity.md

This ***Merge to Live*** is brought to you by ☕ [***Starbucks***&trade; *Holiday Blend*](https://www.starbucks.com/menu/product/295/whole-bean?parent=%2Fat-home-coffee%2Fwhole-bean%2Fmedium-roast) ☕. 😆
"Starbucks" is a registered trademark of [Starbucks Coffee Company](https://www.starbucks.com/).

Merge to Live - 11/18

---

aspnetcore/blazor/fundamentals/static-files.md

Fixes #23981
Thanks @knilecrack! :rocket:

Correct path in example

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/dependency-injection/samples/6.x/DIsample2/DIsample2/Program.cs

Fixes #23986
@mahidulalvi this is the correct snippet

fix sample

---

aspnetcore/data/ef-mvc/intro.md

warn tutorial is not updated to 6.0 yet

---

aspnetcore/security/authentication/windowsauth.md

Update monikers for Win auth /3

---

aspnetcore/includes/make-x509-cert.md

Fixes #23999
Thanks @FerdousR! :rocket:
btw Rick ... I searched the whole repo for the segment "`/pkiclient/`", and this is the only link that turned up.

Update broken link

---

aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md

Fixes #24012
Thanks @Bouke! :rocket:

Persist component state updates

---

aspnetcore/fundamentals/routing.md
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Program.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Routing/ICoolMetadata.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Routing/NoZeroesRouteConstraint.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Routing/SlugifyParameterTransformer.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/RoutingSample.csproj
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/AutoStopwatch.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Controllers/BetterNoZeroesController.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Controllers/GadgetController.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Controllers/NoZeroesController.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Controllers/ProductsController.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Controllers/WidgetController.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Middleware/ProductsMiddleware.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Pages/Index.cshtml.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/Program.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/Snippets/RequiresAuditAttribute.cs
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/appsettings.Development.json
aspnetcore/fundamentals/routing/samples/6.0/RoutingSample/appsettings.json

Fixes #23170.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0&branch=pr-en-us-23932).

Update Routing to 6.0

---

aspnetcore/grpc/loadbalancing.md

Fixes https://github.com/grpc/grpc-dotnet/issues/1499
It is supported with the latest release: https://github.com/grpc/grpc-dotnet/releases/tag/v2.41.0-pre1

Update client-side load balancing with client factory support

---

aspnetcore/fundamentals/app-state.md

moniker prep session

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs

Fixes #23921.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0&branch=pr-en-us-23998#access-the-dependency-injection-di-container).

[Minimal API docs] Adding an example of how to resolve dependencies just like in configure method

---

aspnetcore/security/authentication/identity.md

Fix casing of Identity's --useSqLite

---

aspnetcore/blazor/security/index.md

The slash shouldn't be in the output, but I don't know if there was any reason it was there.

Remove slash

---

aspnetcore/blazor/file-uploads.md

Explain GetRandomFileName /2

---

aspnetcore/fundamentals/servers/kestrel.md
aspnetcore/fundamentals/servers/kestrel/samples-snapshot/2.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/Program.cs
aspnetcore/fundamentals/servers/kestrel/samples/3.x/KestrelSample/Startup.cs
aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample/Program.cs

Addresses #24046.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0&branch=pr-en-us-24070).

Prepare Kestrel Overview for 6.0

---

aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md

Fixes #24067
Thanks @SzymonSel! :rocket: ... I can't repro what you're seeing there, but double-check all of your configuration and access the relevant Azure docs on KV and App Service. If you're still having trouble, reach out to the community for assistance. We recommend the usual public support forums, such as ...
* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
When you discover the problem there and if you think it would be helpful to other readers of this section on Blazor with IdS and Azure, please either leave a comment on your original issue or open a new issue using the **This page** feedback button and form from the …

Blazor IdS AKV updates

---

aspnetcore/blazor/globalization-localization.md

Fixes #24071
Thanks @rswetnam! :rocket: ... I'll hold this in a DRAFT state until I hear back from you that this works.

Update Blazor loc 6.0 example

---

aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/tooling.md

Include WASM build tools in Tooling topic

---

aspnetcore/grpc/loadbalancing.md

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/24099

gRPC DNS resolver refreshing

---

aspnetcore/blazor/tutorials.md

Fixes #24103
Thanks @SogoGolf! :rocket:

Indicate hosting model of Blazor tutorials

---

aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/ResultsExtensions.cs

Remove the second parameter as the compiler will do that for you automatically in C# 10.

Simplify code example

---

aspnetcore/fundamentals/minimal-apis.md

min API overview /1

---

aspnetcore/blazor/globalization-localization.md

Fixes #24089
Thanks @rswetnam for your comments on the issue. I've updated the topic to address some of your points ...
1. I prefer not to split the topic at this time, but I'll continue to take feedback on it 👂. This topic will receive an overhaul at some point, and the subject of content organization will be assessed again at that time.
2. The hosting model selector at the top ("doc pivots") is a relatively new doc content feature. It's in use here because having to look at a large amount of unrelated coverage for the hosting model that the dev isn't using is a poor user experience. These doc pivots are only in use in about six topics where there's a lot of hosting model-specific coverage. We'll continue to take feedback on the use of doc pivots, and we may drop them if they generate a …

Blazor glob/loc updates

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/security/index.md

Drop NavLink boilerplate examples

---

aspnetcore/fundamentals/http-context.md

Addresses #24120.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0&branch=pr-en-us-24133).

Prepare HttpContext for 6.0

---

aspnetcore/test/troubleshoot-azure-iis.md

Fixes https://github.com/dotnet/aspnetcore/issues/25862

Mention hosting bundle for 500 internals

---

aspnetcore/razor-pages/index.md

Fix missing code highlight

---

aspnetcore/security/authorization/secure-data.md
aspnetcore/security/authorization/secure-data/samples/final6/Pages/Contacts/Details.cshtml

fix snippets

---

aspnetcore/host-and-deploy/health-checks.md

Moniker prep for Heath checks

---

aspnetcore/security/anti-request-forgery.md

Moniker prep for XSRF

---

aspnetcore/security/authorization/policies.md
aspnetcore/security/authorization/policies/samples/6.0/AuthorizationPoliciesSample/Program.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Controllers/AlcoholPurchaseController.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Handlers/BadgeEntryHandler.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Handlers/MinimumAgeHandler.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Handlers/PermissionHandler.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Handlers/TemporaryStickerHandler.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Requirements/BuildingEntryRequirement.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Services/Requirements/MinimumAgeRequirement.cs
aspnetcore/security/authorization/policies/samples/PoliciesAuthApp2/Pages/AlcoholPurchase.cshtml.cs
aspnetcore/security/authorization/policies/samples/stubs/copy_of_IAuthorizationService.cs

Addresses #23658.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0&branch=pr-en-us-24148).

Clean-up policy-based authz

---

aspnetcore/host-and-deploy/linux-nginx.md

fix monikers Nginx

---

aspnetcore/fundamentals/http-context.md

Fixes #24120.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0&branch=pr-en-us-24134).

Update HttpContext to 6.0

---

.github/workflows/whats-new.yml

The whats new action needs to have additional permissions in order to create the new branch and create a new PR.

fix permissions to create PR

---

aspnetcore/fundamentals/static-files.md

moniker prep for static files

---

aspnetcore/blazor/performance.md

Fixes #23642
Thanks @omuleanu! :rocket:

Add event args to non-rendering example

---

aspnetcore/host-and-deploy/linux-nginx.md

Fixes #24090
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0&branch=pr-en-us-24161#use-a-reverse-proxy-server)

V6 update to Linux proxy Nginx /1

---

aspnetcore/mvc/views/view-compilation.md

Update runtime compilation docs for 6.0

---

aspnetcore/blazor/fundamentals/handle-errors.md

Blazor Handle Errors content reorganization

---

aspnetcore/fundamentals/startup.md

Fixed capitalization of Program.cs on line 18

---

aspnetcore/fundamentals/localization-extensibility.md

Fix a typo in Localization Extensibility article

---

aspnetcore/blazor/components/virtualization.md

Fixes https://github.com/dotnet/aspnetcore/issues/29123 and https://github.com/dotnet/aspnetcore/issues/38020

Virtualization doc updates (keyboard support, guidance on correct use)

---

aspnetcore/mvc/models/model-binding.md

Fixes dotnet/aspnetcore#28603
Preview URL: https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1&branch=pr-en-us-24175

Collections model binding "index" parameter warning

---

aspnetcore/blazor/fundamentals/handle-errors.md

Hosting model-agnostic Prerender section

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/fundamentals/configuration.md
aspnetcore/blazor/globalization-localization.md
aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
aspnetcore/blazor/includes/package-reference.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
aspnetcore/blazor/webassembly-lazy-load-assemblies.md

Add package guidance INCLUDE

---

aspnetcore/grpc/deadlines-cancellation.md
aspnetcore/grpc/retries.md

How deadlines and transient retries interact

---

aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/StartupJavaScript.cs
aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/wwwroot/css/site.css
aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/wwwroot/index.html
aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/wwwroot/js/site.js
aspnetcore/tutorials/web-api-javascript.md

Prep Call Web API with JavaScrip for .NET 6/3

---

aspnetcore/blazor/host-and-deploy/index.md
aspnetcore/host-and-deploy/iis/web-config.md

Justin ... Firming up that for Blazor apps the general guidance on app pools is still in effect. Outside of accuracy, is there anything else that you'd like me to address here?
Also, I found an IIS area cross-link that was broken to fix on this PR.

Blazor app pool guidance

---

aspnetcore/fundamentals/host/generic-host.md
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/GenericHostSample.csproj
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/Program.cs
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/Services/HostApplicationLifetimeEventsHostedService.cs
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/Services/SampleHostedService.cs
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/Snippets/Program.cs
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/appsettings.Development.json
aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/appsettings.json

Fixes #24091.
Fixes #21637.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0&branch=pr-en-us-24189).

Update Generic Host to 6.0

---

aspnetcore/security/index.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-1.0&branch=pr-en-us-24238)
Add extra links to doc. Add links at the end so the **Build secure web apps** section of https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps can link to this page.

Add security links /3

---

aspnetcore/fundamentals/static-files.md
aspnetcore/fundamentals/static-files/samples/6.x/StaticFilesSample/Program.cs

Fixes #24239
[Internal review URL Dir browsing](
[V5 dir browsing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#directory-browsing-1)

Static files enable display /3

---

aspnetcore/performance/caching/distributed.md

prep monikers for distributed caching /3

---

aspnetcore/grpc/performance.md

Preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.0&branch=pr-en-us-24250#binary-payloads

gRPC large binary performance best practices

---

aspnetcore/performance/response-compression.md

Prep rc 4 monikers/3/ra

---

aspnetcore/fundamentals/index.md
aspnetcore/performance/caching/middleware.md

Prep monikers for V6

---

aspnetcore/test/middleware.md

Update middleware.md package necessary to the extension method Configure

---

aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/ConfigSample.csproj
aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Pages/Test22.cshtml.cs

update project with ImplicitUsings

---

aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/host-and-deploy/webassembly/_samples/integrity.ps1

Fixes #24260 
Tanay and Javier, the engineering issue is at https://github.com/dotnet/aspnetcore/issues/38668.
Nevermind on my earlier bug report ... I inadvertently tried the script with a running Blazor Server app.
> No error founds. Application is consistent.
I fix the sentence "No error founds." on the next update.

Update Blazor WASM integrity PS script

---

aspnetcore/security/cors.md
aspnetcore/security/enforcing-ssl.md

HTTP and CORS /1

---

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60/Program.cs

Remove app.UseDeveloperExceptionPage(); from RP tutorial.

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/logging/index/samples/6.x/WebApp/Program.cs

Fixes #24322.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0&branch=pr-en-us-24323).

Prefer WebApplicationBuilder properties over ConfigureLogging, ConfigureServices, etc

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs

Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0&branch=pr-en-us-24327#read-the-request-body

Add minimal API sample of reading the request stream

---

aspnetcore/security/anti-request-forgery.md

Improve Antiforgery section titles

---

aspnetcore/blazor/webassembly-native-dependencies.md

Updated closing tag for paragraph

---

aspnetcore/toc.yml

Whenever I view toc.yml in VS Code, I'm presented with a sea of red errors.
The schema validation fails because of the following:
* There's no `items` root key.
* `display` should be `displayName`.
It also complains about `uid`, but changing that to `topicUid` doesn't work in the published files. I think the two changes here are still useful just to soften the eye-bleed.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-6.0&branch=pr-en-us-24334).

Update ToC to conform to schema

---

aspnetcore/toc.yml

Fixes #23710.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?view=aspnetcore-6.0&branch=pr-en-us-24336).

Add remaining diagnostics to the ToC

---

aspnetcore/grpc/configuration.md
aspnetcore/grpc/configuration/sample/Program2.cs

Related to https://github.com/grpc/grpc-dotnet/issues/1528
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.0&branch=pr-en-us-24339

gRPC config - client interceptors

---

aspnetcore/diagnostics/code-analysis.md

Add missing diagnostics to overview table

---

aspnetcore/mvc/views/working-with-forms.md

Remove ValidationSummary prefix from tag-helper attribute values

---

aspnetcore/fundamentals/host/hosted-services.md

Fixes #24038.
Fixes #24349.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&branch=pr-en-us-24355&tabs=visual-studio).

Update coverage of IHostedService.StartAsync

---

aspnetcore/blazor/security/server/additional-scenarios.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md

Fixes #24366
Thanks @dreibelt! :rocket: ... these are all the ones that I found in >3.1 docs.

Blazor auth schemes

---

aspnetcore/security/authentication/social/index.md

@smandia remember to add the following
Fixes #24365
Thanks for doing this.

fixes #24365 for facebook case study link(issue 24365)

---

aspnetcore/fundamentals/configuration/index.md

Fixes the words to match the example code above this description.

Fix a not updated description

---

aspnetcore/fundamentals/localization.md

Add a section for order request culture providers

---

aspnetcore/includes/add-EF-NuGet-SQLite-CLI-6.md

Update add-EF-NuGet-SQLite-CLI-6.md (Fixed Issue #24401)

---

aspnetcore/host-and-deploy/linux-apache.md

I felt like there is one or two things that can be added to the documentation which i did add.

Apache configuration process update on linux

---

aspnetcore/blazor/javascript-interoperability/index.md

typo correct

---

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
aspnetcore/blazor/javascript-interoperability/index.md

Addresses #24427
Thanks again @thiennn! :rocket: ... This fixes the other spots for *this one* 😈.

Fix heading and cross-links

---

aspnetcore/client-side/spa/angular.md
aspnetcore/client-side/spa/react-with-redux.md
aspnetcore/client-side/spa/react.md
aspnetcore/includes/spa-proxy.md

Fixes #23382
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&branch=pr-en-us-24315&tabs=visual-studio#configure-proxy-middleware-for-signalr) 
@YakupIpek please review. You won't be able to see the [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&branch=pr-en-us-24315&tabs=visual-studio#configure-proxy-middleware-for-signalr)

how to config proxy middleware in spa app

---

aspnetcore/tutorials/min-web-api.md

update no loc

---

aspnetcore/performance/caching/distributed.md
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/Pages/Index.cshtml.cs
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/Program.cs
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/SampleApp.csproj
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/client.ncconf
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/config.ncconf

Fixes #24121
***EDIT by @Rick-Anderson**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0&branch=pr-en-us-24400)

fixes #24121 , documentation update distributed caching

---

aspnetcore/migration/31-to-60.md

Fixing typo in code sample for Update package references.

Adjust the syntax for Update package references

---

aspnetcore/tutorials/razor-pages/razor-pages-start.md
aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60/Program1Snip.cs

fix RP tutorial snippets

---

aspnetcore/performance/caching/distributed.md
aspnetcore/performance/caching/distributed/samples/6.x/DistCacheSample/Program.cs

clean up distributed caching /1

---

aspnetcore/host-and-deploy/proxy-load-balancer.md

moniker clean up

---

aspnetcore/mvc/views/view-components.md

Fixes #23963
This is a documentation for the use of the NonViewComponent Attribute([NonViewComponent]). 
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0&branch=pr-en-us-24424#the-view-component-class).

NonViewComponent attribute documentation

---

aspnetcore/grpc/supported-platforms.md

Add Azure Container Apps to supported gRPC platforms

---

aspnetcore/tutorials/grpc/grpc-start.md
aspnetcore/tutorials/grpc/grpc-start/sample6/GrpcGreeter/appsettings.Development.json

fixes #24386 grpc service logging in console.

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/performance.md

Fixes #24490
Thanks @omuleanu! :rocket: ... We won't be able to say anything about what the product unit **_might do_** at this point. I'll certainly keep an 👂 open for them telling me that they worked out something for it as a language feature for .NET 7 later this year. I'll hold off on merging this until you have a chance to look at the updates. If I do merge it later today before you have a chance to look and respond, I can open a patch PR if needed to address it further.

Blazor render fragment support remark

---

aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md

Fixes #24523
Thanks @genifycom! :rocket: ... I'll see if the others require an update as well. If so, I'll add them to this PR.
**UPDATE**: This is the only doc that has it.

Update VS guidance

---

aspnetcore/tutorials/razor-pages/model.md

there is no issue no.
just for fixing a small localization issue

updated localization

---

aspnetcore/blazor/fundamentals/dependency-injection.md
aspnetcore/blazor/fundamentals/signalr.md

Fixes  #24534
Thanks @abdollahkahne! :rocket:

Add a cross-link

---

aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md

Fixes #24545
Thanks @elslush! :rocket:

Update Blazor code guidance

---

aspnetcore/grpc/test-client.md

Mock gRPC client clean up

---

aspnetcore/fundamentals/routing.md

Typo in documentation

---

aspnetcore/security/key-vault-configuration.md
aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample/KeyVaultConfigurationSample.csproj
aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample/Program.cs
aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample/Snippets/Program.cs
aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample/Snippets/SamplePrefixKeyVaultSecretManager.cs
aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample/appsettings.json

Fixes #24123.
Fixes #17234.
Fixes #18946.
Fixes #13484.
Fixes #23004.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0&branch=pr-en-us-24510).
There's a lot of "you" and parenthetical clauses in this one, but I've chosen to leave those as-is, in the interest of just getting this updated to 6.0, fixing the article's outstanding GitHub issues, and testing all the Azure stuff.

Update KV configuration to 6.0

---

aspnetcore/host-and-deploy/health-checks.md

Fixes #24341.
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0&branch=pr-en-us-24577#docker-healthcheck).

Add note re curl being missing from Docker images

---

aspnetcore/blazor/components/index.md

Fixes #24450
~Safia, do you have a sec to advise on this one? *I'm pinging Tanay too much these days!* 😄~ It's *probably* ok ... I'll go ahead. Readers will call for my 👦 on a 🍽️ if I've fouled it up.
I see some folks on the interwebs doing fancier things with `Tuple` than this (e.g., `RenderFragment<{TUPLE}>` with component types for various iterating scenarios), but I think we should keep this simple and accessible for basic use cases. For now, I suggest we put this up (or something like this) and take reader feedback on it.

Tuple component param example

---

aspnetcore/host-and-deploy/proxy-load-balancer.md
aspnetcore/host-and-deploy/proxy-load-balancer/6.1samples/WebPS/Program.cs
aspnetcore/host-and-deploy/proxy-load-balancer/6.1samples/WebPS/appsettings.Development.json

Fixes #24530
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0&branch=pr-en-us-24558#troubleshoot)  -- [Current Troubleshoot section](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0&branch=pr-en-us-24558#troubleshoot)

Use AddHttpLogging API in sample code /1

---

aspnetcore/security/authentication/social/includes/chain-auth-providers6.md
aspnetcore/security/authentication/social/index.md
aspnetcore/security/authentication/social/index/Program.cs

FB/Gooog/auth providers .NET 6 /8

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/logging/index/samples/6.x/TodoApiDTO/appsettings.Development.json

Corrected some issues at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging to correctly bridge the content and the preceding JSON.
Took reference from https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#configure-logging
[Internal Preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0&branch=pr-en-us-24595#configure-logging).

Fix explanation of logging configuration

---

aspnetcore/security/authorization/limitingidentitybyscheme.md

prep monikers for Auth with scheme

---

aspnetcore/data/ef-rp/intro.md
aspnetcore/data/ef-rp/intro/samples/cu50snapshots/Index.cshtml.cs

Remove MaxModelBindingCollectionSize from EF RP tutorial

---

aspnetcore/fundamentals/servers/kestrel/endpoints.md
aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample/Startup.cs

Prepare Kestrel Endpoints for 6.0

---

aspnetcore/tutorials/getting-started-with-NSwag.md

Prep NSwag monikers

---

aspnetcore/toc.yml

Remove gRPCs from toc

---

aspnetcore/grpc/migration.md
aspnetcore/toc.yml

Fixes https://github.com/grpc/grpc-dotnet/issues/588

Make migration page include client details

---

aspnetcore/tutorials/signalr.md

Updating argument to avoid deprecation warning

---

aspnetcore/tutorials/dotnet-watch.md

Add a note about emojis

---

aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/tooling.md
aspnetcore/tutorials/signalr-blazor.md

Addresses #24615 
In good shape generally ... I just see a few spots where an additional remark (or reinforcing remark when present earlier) is needed.

Hosted WASM execution startup project

---

aspnetcore/blazor/components/prerendering-and-integration.md

Fix confusing language

---

aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/images.md
aspnetcore/blazor/includes/inputfile-preview-images.md

InputFile image preview INCLUDE

---

aspnetcore/grpc/health-checks.md
aspnetcore/grpc/health-checks/Startup.cs
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/GrpcServiceHC.csproj
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/Program.cs
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/Protos/greet.proto
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/Services/GreeterService.cs
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/appsettings.Development.json
aspnetcore/grpc/health-checks/samples-6/GrpcServiceHC/appsettings.json

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0&branch=pr-en-us-24660) 
Merges into #24638

Rick's update of JamesNK Add gRPC health checks doc /8

---

aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs

It occurs on: Allow unauthenticated users to access an endpoint

Update Auth4 snippet to be more accurate

---

aspnetcore/fundamentals/servers/kestrel/endpoints.md
aspnetcore/tutorials/signalr-blazor.md

@wadepickett @serpent5 **_Ah, HA!_** 😈 *Sneaky devil* 😈  got past u guys! 😆 lol ... I'm fixing it on this PR, which will go in now.
> Url 'xfef:security/app-secrets' references a disallowed domain 'xfef:'.

Clarifications on the sample app

---

aspnetcore/fundamentals/w3c-logger/index.md
aspnetcore/fundamentals/w3c-logger/samples/6.x/Program.cs

Fixes #23422.
Fixes #23421.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/w3c-logger/?view=aspnetcore-6.0&branch=pr-en-us-24700).

Link to W3CLoggerOptions.LoggingFields

---

aspnetcore/tutorials/first-web-api.md

Use lowercase for API URLs

---

aspnetcore/security/authentication/identity-enable-qrcodes.md

Fix monikers for Identity QR

---

aspnetcore/blazor/fundamentals/dependency-injection.md

Addresses https://github.com/dotnet/AspNetCore.Docs/pull/24685#discussion_r792141506
Thanks @jessegood! :rocket:

Patch DI text and example

---

aspnetcore/web-api/advanced/custom-formatters.md
aspnetcore/web-api/advanced/custom-formatters/samples/3.x/CustomFormattersSample/Formatters/VcardInputFormatter.cs
aspnetcore/web-api/advanced/custom-formatters/samples/3.x/CustomFormattersSample/Formatters/VcardOutputFormatter.cs
aspnetcore/web-api/advanced/custom-formatters/samples/3.x/CustomFormattersSample/Startup.cs

Prepare Custom Formatters for 6.0

---

aspnetcore/web-api/advanced/custom-formatters.md
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/Controllers/ContactsController.cs
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/CustomFormattersSample.csproj
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/Formatters/VcardInputFormatter.cs
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/Formatters/VcardOutputFormatter.cs
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/Models/Contact.cs
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/Program.cs
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/appsettings.Development.json
aspnetcore/web-api/advanced/custom-formatters/samples/6.x/CustomFormattersSample/appsettings.json

Fixes #24743.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-6.0&branch=pr-en-us-24746).

Update Custom Formatters to 6.0

---

aspnetcore/grpc/migration.md

Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-3.0&branch=pr-en-us-24749

Improve gRPC migration doc

---

aspnetcore/fundamentals/minimal-apis.md

Fixes #24747.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0&branch=pr-en-us-24767#special-types).

Add examples for Minimal web API special types

---

aspnetcore/tutorials/min-web-api/samples/6.x/WebMinJson/Program.cs
aspnetcore/tutorials/min-web-api/samples/6.x/WebMinJson/WebMinJson.csproj

Fixes #24669.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&branch=pr-en-us-24772&tabs=visual-studio#use-jsonoptions).

Add JsonOptions configuration example

---

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

JavaScript API restricted to user gestures

---

aspnetcore/includes/bind6.md

[ The title is self descriptive , can't think of any more description ]

'Position' is a field, not property

---

aspnetcore/tutorials/grpc/grpc-start.md

Correct wrong client namespace

---

aspnetcore/web-api/index.md

In the "ApiController attribute" chapter the first four link are duplicated below, pointing to the same resources (e.g. the sixth is a duplicate of the first and so on. Only the fifth one is not repeated.)

Delete duplicated content

---

aspnetcore/grpc/loadbalancing.md

Docs updated for new API.
PR is waiting for next gRPC package to be published with the new API.

Update gRPC load balancing sample

---

aspnetcore/security/authentication/social/twitter-logins.md

Fixes https://github.com/dotnet/aspnetcore/issues/39664

Add note about twitter OAuth2

---

aspnetcore/test/integration-tests.md

Recommend SQLite for DB testing /1

---

aspnetcore/blazor/host-and-deploy/webassembly.md
aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/performance.md

Per ...
* https://github.com/dotnet/aspnetcore/issues/35302#issuecomment-898018584 (first comment in discussion)
* https://github.com/dotnet/aspnetcore/issues/35302#issuecomment-898523284 (follow-up comment in discussion)
* https://github.com/dotnet/aspnetcore/issues/35302#issuecomment-900683673 (@Andrzej-W specified an exact reason during the discussion ... we'll have the PU confirm shortly, since they didn't respond to the comment)
* https://github.com/dotnet/aspnetcore/issues/37092#issuecomment-930323496
cc: @ChristianWeyer ... "get to that in due course over the next couple of weeks" **_translated into real world time_** is actually "next couple of months/years" 🙈😆 lol *Sorry about that. I got to it as soon as I could!* ⛰️⛏️😅

Enhance AOT WASM load-time/runtime perf remarks

---

aspnetcore/blazor/security/server/index.md

Fixes #24845
Javier ... a bit *draft-ish* at the moment. Normally, I'd sleep on it, but see how we're doing here. This might just about do the trick.
~**_Don't forget to duplicate the section for 5.0 and 3.1 before merging!_**~ 🏃 **_Done!_** :+1:
This should appear at the following URL after it goes live ...
https://docs.microsoft.com/aspnet/core/blazor/security/server/#blazor-server-uses-aspnet-core-identity

Blazor UI for Identity

---

aspnetcore/blazor/components/class-libraries.md

Fixes #24867
Thanks @abdollahkahne! 🎷 ... This will take care of the **_rotten little gremlin!_** 😈 
Let me know (perhaps in a new issue because the one you opened will close) ... let me know if you hit a problem with the approach. I do need to check it, but perhaps I don't need to implement it myself if I don't hear back from you. I'll know that the new guidance is ok. I'm going to merge this to the live doc set right after it builds, so this will go live in the article within perhaps 20 or 30 minutes.

Update RCL control of <head> content guidance

---

aspnetcore/blazor/fundamentals/logging.md

Fixes #24856
Thanks @johndhunter! :rocket:

Add namespace for Microsoft.Extensions.Logging

---

aspnetcore/signalr/authn-and-authz.md

fix monikers in Auth and Authz in SignalR /1

---

aspnetcore/mvc/views/working-with-forms.md

The attribute `asp-for="@Name"` is not what you would normally write.

Fix asp-for sample (a genuine mistake?)

---

aspnetcore/data/ef-rp/crud.md

[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-6.0&branch=pr-en-us-24877).

Replace /dotnet/api with xrefs in RP-EF CRUD

---

aspnetcore/migration/30-to-31.md

Update the docker pull path based on the new .net docker repo change. https://github.com/dotnet/dotnet-docker/issues/2375

Update 30 to 31.md

---

aspnetcore/security/authentication/identity-configuration.md

Replace /dotnet/api with xrefs in Identity Configuration

---

aspnetcore/security/authentication/identity-custom-storage-providers.md

[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-6.0&branch=pr-en-us-24908).

Replace /dotnet/api with xrefs in Identity Custom Providers

---

aspnetcore/blazor/hosting-models.md

Fixes #24864
Let's go "*all hands on deck*" with this one. I'll ping widely for review so that we can tap into the wide experience.
* Improve the description. This likely will have little direct effect, but longterm it should:
* Identify to readers that this topic has information on selection of the hosting model.
* Lead to more search result clicks and more time spent on the page.
* Ultimately result in higher search rankings.
* Increase relevant keywords and phrases (examples: select, should use, decide, versus, which, choose).
* Add "WASM" to help capture that search term.
* Improve the section heading with the table comparison.
* We don't use "Blazor WASM" in the docs. However, let's add "WASM" to this topic in a few strategic spots to help capture it as a search term.
* Among …

Improve Blazor Hosting Models article SEO

---

aspnetcore/blazor/components/prerendering-and-integration.md

Prerendering helps with SEO

---

aspnetcore/security/data-protection/configuration/overview.md

Addresses #23083.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0&branch=pr-en-us-24914).

Prepare Data Protection Configuration for 6.0

---

aspnetcore/blazor/hosting-models.md

Addresses https://github.com/dotnet/AspNetCore.Docs/pull/24878#issuecomment-1031997644

Patch for better first line

---

aspnetcore/grpc/clientfactory.md

Update gRPC client factory with interceptor scope information

---

aspnetcore/grpc/authn-and-authz.md

I haven't written docs before where the example starts off with "imagine a scenario...". Let me know if there is a better way to do this.

Update gRPC auth with interceptor scope example

---

aspnetcore/fundamentals/localization.md

correct spelling error

---

aspnetcore/data/ef-rp/intro.md

fix download link

---

aspnetcore/security/authentication/accconfirm.md

Prep account confirmation monikers

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/index.md

Call out "Blazor components" terminology

---

aspnetcore/blazor/hosting-models.md

Addresses #24923
@v-mepa ... We can adjust that right now. Is this what you had in mind?
**UPDATE**: Approved on the issue. We'll do this now and perhaps make some additional tweaks in a bit.

Update Blazor hosting models topic title

---

aspnetcore/data/ef-rp/complex-data-model.md
aspnetcore/data/ef-rp/concurrency.md
aspnetcore/data/ef-rp/intro.md
aspnetcore/data/ef-rp/migrations.md
aspnetcore/data/ef-rp/update-related-data.md

[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&branch=pr-en-us-24959&tabs=visual-studio).
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-6.0&branch=pr-en-us-24959&tabs=visual-studio).
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-6.0&branch=pr-en-us-24959&tabs=visual-studio).
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-6.0&branch=pr-en-us-24959).
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-6.0&branch=pr-en-us-24959&tabs=visual-studio).

Replace /dotnet/api with xrefs in RP w/ EF

---

aspnetcore/blazor/hosting-models.md

server goes off - line not the client

server goes off - line not the client

---

aspnetcore/includes/localization/unsupported-culture-log-level.md

extra unneeded word "is" removed

---

aspnetcore/mvc/advanced/app-parts.md
aspnetcore/mvc/controllers/actions.md
aspnetcore/mvc/models/model-binding.md
aspnetcore/mvc/views/dependency-injection.md
aspnetcore/mvc/views/partial.md
aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md
aspnetcore/mvc/views/tag-helpers/intro.md
aspnetcore/mvc/views/view-components.md
aspnetcore/mvc/views/working-with-forms.md
aspnetcore/performance/memory.md

Replace /dotnet/api with xrefs in MVC

---

aspnetcore/blazor/security/index.md

Addresses #24992
This section will move to the dedicated Blazor Server topic later today. For now, let's just fix the 🐛 here.

Section only applies to Blazor Server

---

aspnetcore/blazor/components/control-head-content.md

Fixes #24996
Thanks @chinmay-trivedi! 🚀 ... I'll check the live topic to confirm that this worked out ok. Thanks for the issue.

Tag "head" without angle brackets

---

aspnetcore/security/data-protection/configuration/overview.md
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/DataProtectionConfigurationSample.csproj
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/Program.cs
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/Snippets/Program.cs
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/Snippets/SampleDbContext.cs
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/appsettings.Development.json
aspnetcore/security/data-protection/configuration/samples/6.x/DataProtectionConfigurationSample/appsettings.json

Fixes #23083.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0&branch=pr-en-us-24991).

Update Data Protection Configuration to 6.0

---

aspnetcore/blazor/tutorials/signalr-blazor.md

Fixes #24999
Thanks again, @reminvestor! 🚀

Update sample code link

---

aspnetcore/blazor/components/control-head-content.md

Patch title and description

---

aspnetcore/security/cross-site-scripting.md

XSS doc to .NET 6

---

aspnetcore/security/authentication/identity-configuration.md

moniker prep for Identity

---

aspnetcore/mvc/controllers/filters.md

Exception Filter - fix docs regarding how the exceptions are propagated in the exception filter.
Fixes #24987

Exception Filter exception propagation

---

aspnetcore/security/data-protection/configuration/overview.md

Update ms.date for Data Protection Configuration

---

aspnetcore/blazor/security/index.md
aspnetcore/blazor/security/server/index.md

Fixes #24992
Follow-up to #24993, which was just a quick patch while working on other things 🏃😅.

Finish custom auth state provider update

---

aspnetcore/blazor/components/virtualization.md

Describes an additional requirement that was omitted before. This additional requirement will stop being required (and hence this doc change can be reverted) in future versions if we implement the enhancement https://github.com/dotnet/aspnetcore/issues/40262

Add note about flex-shrink on Virtualize docs

---

aspnetcore/mvc/views/tag-helpers/intro.md

C# in Tag Helpers: explain false attribute values

---

aspnetcore/security/authentication/claims.md

mon prep for claims

---

aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Error.cshtml
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Error.cshtml.cs
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Index.cshtml
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Index.cshtml.cs
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/Shared/_Layout.cshtml
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/_ViewImports.cshtml
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Pages/_ViewStart.cshtml
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Program.cs
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/README.md
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/SampleApp.csproj
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Services/ServiceA.cs
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Services/ServiceB.cs
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/appsettings.Development.json
aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/appsettings.json

The sample shows how to host an ASP.NET Core app using Minimal API as a Windows Service .

Minimal API windows service sample

---

aspnetcore/blazor/host-and-deploy/server.md
aspnetcore/diagnostics/bl0001.md
aspnetcore/diagnostics/bl0004.md
aspnetcore/diagnostics/mvc1002.md
aspnetcore/diagnostics/mvc1003.md
aspnetcore/fundamentals/host/web-host.md
aspnetcore/fundamentals/localization.md
aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/routing.md
aspnetcore/fundamentals/servers/kestrel/diagnostics.md
aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md
aspnetcore/grpc/authn-and-authz.md
aspnetcore/grpc/diagnostics.md
aspnetcore/grpc/troubleshoot.md
aspnetcore/host-and-deploy/azure-apps/index.md
aspnetcore/host-and-deploy/web-farm.md
aspnetcore/migration/1x-to-2x/identity-2x.md
aspnetcore/migration/20_21.md
aspnetcore/migration/22-to-30.md
aspnetcore/migration/claimsprincipal-current.md
aspnetcore/migration/http-modules.md
aspnetcore/mvc/controllers/routing.md
aspnetcore/performance/performance-best-practices.md
aspnetcore/release-notes/aspnetcore-2.1.md
aspnetcore/signalr/authn-and-authz.md
aspnetcore/web-api/handle-errors.md
aspnetcore/web-api/index.md

Replace remaining /dotnet/api references with xrefs

---

aspnetcore/blazor/security/includes/troubleshoot.md

Make the test User component available

---

aspnetcore/signalr/javascript-client.md
aspnetcore/signalr/javascript-client/samples/6.x/SignalRChat/Pages/Index.cshtml
aspnetcore/signalr/javascript-client/samples/6.x/SignalRChat/Pages/Shared/_Layout.cshtml
aspnetcore/signalr/javascript-client/samples/6.x/SignalRChat/Pages/Shared/_ValidationScriptsPartial.cshtml
aspnetcore/signalr/javascript-client/samples/6.x/SignalRChat/wwwroot/chat.js

Use consistent DOM IDs between inline snippets & sample

---

aspnetcore/blazor/components/index.md
aspnetcore/blazor/samples/6.0/BlazorSample_Server/TimerService.cs
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/TimerService.cs
aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md

Calling async void + PeriodicTimer updates

---

aspnetcore/blazor/hybrid/index.md

Just noticed a broken sentence in the Blazor Hybrid overview page.

Fixed broken sentence

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Fixes #25032
Thanks @rmencia-isv! 🚀 
This addresses the specific ask on integrity checks by including Javier's remarks from the PU issue.
WRT ...
> A lot of times the settings don't explain the scenarios in where they can be applied, only what it does.
... and I think the additional bit on your PU issue about not having "real world" examples of things. We avoid making examples **_more complicated_**/**_more confusing_** 😵 for devs merely to match something that an arbitrary production app might do. Also, we can't conceive of every use case for every setting. We do scope to some degree for most settings; and what we don't scope in the article, the API docs often scope. We favor the simplest case that demonstrates the concept. For settings with API coverage, we seek to cross-link the API …

Disable integrity checks enhancements

---

aspnetcore/fundamentals/host/web-host.md

Addresses #24890.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-6.0&branch=pr-en-us-25068).

Prepare Web Host for 6.0

---

aspnetcore/data/ef-mvc/intro/samples/cu-final/PaginatedList.cs
aspnetcore/data/ef-mvc/intro/samples/cu/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part4/ContosoUniversity/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part5/ContosoUniversity/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part6/ContosoUniversity/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part7/ContosoUniversity/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part3-sorting/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part4-migrations/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part5-complex/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part6-related/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part7/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu20snapshots/cu-part8/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu21/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu21snapshots/Part-3-Sorting/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu21snapshots/Part-4-Migrations/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu21snapshots/Part-5/PaginatedList.cs
aspnetcore/data/ef-rp/intro/samples/cu30/PaginatedList.cs

This uses modern expression-bodied properties.

Use expression-bodied property

---

aspnetcore/fundamentals/logging/index.md

Follow-up for #25087.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0&branch=pr-en-us-25089).

Simplify moniker versioning

---

aspnetcore/client-side/spa/angular.md

Addresses #25028.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-6.0&branch=pr-en-us-25093&tabs=visual-studio).

Prepare Angular for 6.0

---

aspnetcore/client-side/spa/react.md

Addresses #24874.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-6.0&branch=pr-en-us-25094&tabs=visual-studio).

Prepare React for 6.0

---

aspnetcore/data/ef-rp/crud.md

Fix moniker versions for EF RP Part 2

---

aspnetcore/migration/31-to-60.md
aspnetcore/migration/50-to-60.md

Fixes #25045
Internal Review URLs
* [3.1 to 6](https://review.docs.microsoft.com/en-us/aspnet/core/migration/31-to-60?view=aspnetcore-3.1&branch=pr-en-us-25055&tabs=visual-studio#review-breaking-changes)
* [5.0 to 6](https://review.docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&branch=pr-en-us-25055&tabs=visual-studio#review-breaking-changes)

Add bootStrap breaking change to migration docs /1

---

aspnetcore/blazor/components/index.md

Without this javascript in place the "custom element" will not render and silently fail. I found out after inspecting Blazor's websocket traffic:
```
ù•€ÀµEndInvokeJSFromDotNet“ÂÚÙ[
2,
false,
"Could not find 'registerBlazorCustomElement' ('registerBlazorCustomElement' was undefined).
findFunction/<@https://localhost:5001/_framework/blazor.server.js:1:497
findFunction@https://localhost:5001/_framework/blazor.server.js:1:465
E@https://localhost:5001/_framework/blazor.server.js:1:2606
attachWebRendererInterop/<@https://localhost:5001/_framework/blazor.server.js:1:33097
attachWebRendererInterop@https://localhost:5001/_framework/blazor.server.js:1:33145
beginInvokeJSFromDotNet/s<@https://localhost:5001/_framework/blazor.server.js:1:3501 …
```

Additional javascript required for custom elements

---

aspnetcore/blazor/components/index.md

Patch code example

---

aspnetcore/web-api/jsonpatch.md

Mon prep for JsonPatch

---

aspnetcore/getting-started/index.md

Fixes #25113.
.NET 6 SDK for asp.net core 6

Update Get started with ASP.NET Core to 6.0

---

aspnetcore/client-side/spa/react.md

Add comment to show 6.0 version needs update

---

aspnetcore/blazor/components/rendering.md
aspnetcore/blazor/components/virtualization.md
aspnetcore/blazor/fundamentals/handle-errors.md
aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
aspnetcore/blazor/test.md
aspnetcore/release-notes/aspnetcore-3.1.md
aspnetcore/release-notes/aspnetcore-5.0.md

Update 'Blazor component' naming

---

aspnetcore/mvc/models/model-binding.md

Wrap >= 7.0 content in a moniker range

---

aspnetcore/blazor/hybrid/routing.md

Addresses https://github.com/dotnet/AspNetCore.Docs/pull/25130#discussion_r814367350
I'll do a bit more work on this on the next pass. Eventually, it will say what API requires it.
cc: @TanayParikh

Move namespace remarks

---

aspnetcore/security/authorization/limitingidentitybyscheme/samples/AuthScheme/Controllers/WeatherForecastController.cs

Hello 👋 
I saw that indentation is not observed. So I fixed that.

Clean up indentation

---

aspnetcore/grpc/clientfactory.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0&branch=pr-en-us-25148)
Contributes to #25147
v6 prep only.  Moving content into moniker sections per versions.  >= 6.0 and < 6.0

v6 Update Prep: gRPC client factory integration in .NET

---

aspnetcore/web-api/jsonpatch.md
aspnetcore/web-api/jsonpatch/samples/3.x/api/JsonPatchSample.csproj
aspnetcore/web-api/jsonpatch/samples/6.x/api/Controllers/HomeController.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/JsonPatchSample.csproj
aspnetcore/web-api/jsonpatch/samples/6.x/api/Models/Category.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/Models/Customer.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/Models/Order.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/Models/Product.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/MyJPIF.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/Program.cs
aspnetcore/web-api/jsonpatch/samples/6.x/api/appsettings.Development.json
aspnetcore/web-api/jsonpatch/samples/6.x/api/appsettings.json

Fixes #24422 Fixes  #25099 Fixes 
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0&branch=pr-en-us-25146)

JsonPatch .NET 6 /1

---

aspnetcore/blazor/file-uploads.md

Standalone WASM file upload enhancements

---

aspnetcore/blazor/components/class-libraries.md

Discussed and approved by SS on 2/28.

Update guidance on global RCL stylesheet use

---

aspnetcore/grpc/interceptors.md
aspnetcore/toc.yml

Fixes #24720 
New topic covers the basics of gRPC interceptors on .NET, how to create and configure them.
Since this is my first bigger contribution to ASP.NET Core documentation I appreciate any kind of hint.
@JamesNK @wadepickett 
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-3.0&branch=pr-en-us-25150#interceptor-type

New topic - gRPC interceptors on .NET

---

aspnetcore/security/authentication/social/google-logins.md

clean up instructions on Google sign-in/3

---

aspnetcore/grpc/interceptors.md
aspnetcore/grpc/migration.md

* Add example of client interceptor that awaits the result
* Remove duplicate content and link to interceptor page
cc @erni27

Await response in client interceptor

---

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
aspnetcore/blazor/samples/6.0/BlazorSample_Server/JsInteropClasses3.cs
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample2.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample3.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample5.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample2.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample3.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample5.razor

Fixes #24902
cc: @bar10dr ... There will be a little more work to do on the next topic overhaul, but this is a good start. For example, the new example will be rolled into the snippet sample apps. Thanks again for your feedback.

Improve Call .NET guidance

---

aspnetcore/blazor/hosting-models.md

Fixes  #24923
Adds a paragraph for each row of the 'Which hosting model ...' table.

Blazor Hosting Models SEO

---

aspnetcore/web-api/index.md
aspnetcore/web-api/index/samples/2.x/2.1/Controllers/MyControllerBase.cs
aspnetcore/web-api/index/samples/2.x/2.1/Controllers/PetsController.cs
aspnetcore/web-api/index/samples/2.x/2.1/Controllers/ProductsController.cs
aspnetcore/web-api/index/samples/2.x/2.1/Controllers/ValuesController.cs
aspnetcore/web-api/index/samples/2.x/2.1/Models/Pet.cs
aspnetcore/web-api/index/samples/2.x/2.1/Models/Product.cs
aspnetcore/web-api/index/samples/2.x/2.1/Program.cs
aspnetcore/web-api/index/samples/2.x/2.1/Startup.cs
aspnetcore/web-api/index/samples/2.x/2.1/WebApiSample.csproj
aspnetcore/web-api/index/samples/2.x/2.1/appsettings.Development.json
aspnetcore/web-api/index/samples/2.x/2.1/appsettings.json
aspnetcore/web-api/index/samples/2.x/2.2/Controllers/MyControllerBase.cs
aspnetcore/web-api/index/samples/2.x/2.2/Controllers/PetsController.cs
aspnetcore/web-api/index/samples/2.x/2.2/Controllers/ProductsController.cs
aspnetcore/web-api/index/samples/2.x/2.2/Controllers/ValuesController.cs
aspnetcore/web-api/index/samples/2.x/2.2/Models/Pet.cs
aspnetcore/web-api/index/samples/2.x/2.2/Models/Product.cs
aspnetcore/web-api/index/samples/2.x/2.2/Program.cs
aspnetcore/web-api/index/samples/2.x/2.2/Startup.cs
aspnetcore/web-api/index/samples/2.x/2.2/WebApiSample.csproj
aspnetcore/web-api/index/samples/2.x/2.2/appsettings.Development.json
aspnetcore/web-api/index/samples/2.x/2.2/appsettings.json

restore 2.2 Web API /1

---

aspnetcore/introduction-to-aspnet-core.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-6.0&branch=pr-en-us-25191)
Fixes #25190 which details why changes are being made and tracks just this topic fix.
Changes to:
- Meta Description
- Title
- H1
- First paragraph

SEO: Introduction to ASP.NET Core

---

aspnetcore/fundamentals/servers/kestrel.md

Follow-up for #25201.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0&branch=pr-en-us-25206).

Emphasize relationship between WebApplicationBuilder and UseKestrel

---

aspnetcore/blazor/components/lifecycle.md

Fixes #25185
Thanks @TheAtomicOption! :rocket:

Event handler disposal update

---

aspnetcore/mvc/views/working-with-forms.md

Fixes [#40156](https://github.com/dotnet/aspnetcore/issues/40156)
What cannot be fixed should at least be documented.

INPUT tag helper: How to prevent duplicate ids

---

aspnetcore/tutorials/choose-web-ui.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-6.0&branch=pr-en-us-25202)
Fixes #25200.  Go here to view audit research details for this topic.
Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/25126
Address SEO improvements needed after reviewing the data and topic.
Changes to:
- Meta Description
- A fix for a list missing a return

SEO audit: Choose ASP.NET Core web UI

---

aspnetcore/host-and-deploy/aspnet-core-module.md
aspnetcore/toc.yml

Fixes #25210.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-7.0&branch=pr-en-us-25211).

Optimize for ASP.NET Core Module for better SEO

---

aspnetcore/blazor/hybrid/tutorials/wpf.md

Fixes  #25231
Thanks @workaholic! :rocket:

Fix namespace in example code

---

aspnetcore/blazor/security/includes/authorize-client-app.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md

Fixes #25026
cc: @tomreich ... I don't think we need Javier to look. This seems reasonable, and I'll take further feedback from the community on it. I'll leave this up until this afternoon to give you a chance to look at it before I merge it.

AAD tenant can't be authorized

---

aspnetcore/security/authentication/social/index.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&branch=pr-en-us-25230&tabs=visual-studio)  Note: Just Meta Title and description changed, so not viewable.
Fixes #25228 which details why changes are being made and tracks just this topic fix.
Changes to the following meta items:
- Title
- Description

SEO: Facebook, Google, and external provider auth

---

aspnetcore/signalr/introduction.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-6.0&branch=pr-en-us-25227)
Fixes #25199 which details why changes are being made and tracks just this topic fix.
Changes to:
- Title
- H1

SEO audit: Introduction to ASP.NET Core SignalR

---

aspnetcore/security/data-protection/introduction.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0&branch=pr-en-us-25233)
Fixes #25232  which details why changes are being made and tracks just this topic fix.
Changes to:
- Meta Title
- H1
- First Paragraph
- Next Steps

SEO audit: ASP.NET Core Data Protection

---

aspnetcore/getting-started/index.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-6.0&branch=pr-en-us-25225&tabs=windows)
Fixes #25219 which details why changes are being made and tracks just this topic fix.
Changes to:
- Meta Description
- Next Steps

SEO audit: Get started with ASP.NET Core

---

aspnetcore/blazor/hybrid/index.md
aspnetcore/blazor/index.md

Addresses #25243
Wade, I use "Overview" everywhere, including all of the ToC entries, except these two spots on the PR. AFAICT, these are the only Blazor spots to touch for your issue.

Blazor "Introduction" to "Overview"

---

aspnetcore/tutorials/signalr-typescript-webpack.md

Fixes #25239.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-6.0&branch=pr-en-us-25240&tabs=visual-studio).

Optimize SignalR + TypeScript/Webpack for better SEO

---

aspnetcore/blazor/blazor-server-ef-core.md

Fixes #23342
Thanks @JeremyLikness! 🎷

Update external link

---

aspnetcore/blazor/call-web-api.md
aspnetcore/blazor/security/index.md
aspnetcore/blazor/security/server/additional-scenarios.md
aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/blazor/security/webassembly/graph-api.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
aspnetcore/blazor/state-management.md
aspnetcore/blazor/webassembly-native-dependencies.md

Improve add package ref guidance

---

aspnetcore/host-and-deploy/azure-iis-errors-reference.md

This topic gets flagged every OKR round. Everyone with an Azure problem comes to this topic and it only what we guess are the most common errors. 
Fixes and #25248
Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/25126

SEO Azure errors /2

---

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md

Addresses #25265
Thanks @abdollahkahne! ... I wouldn't have noticed that little sneaky 😈 if you hadn't opened your issue. It's there ... it just needs to be code-fenced for code to show up in the live topic! 🙈

Code-fence an HTML tag

---

aspnetcore/fundamentals/index.md

Fixes #25238.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-6.0&branch=pr-en-us-25261&tabs=windows).

Optimize ASP.NET Core fundamentals for better SEO

---

aspnetcore/tutorials/signalr-typescript-webpack.md
aspnetcore/tutorials/signalr-typescript-webpack/sample/2.x/Startup.cs
aspnetcore/tutorials/signalr-typescript-webpack/sample/2.x/snippets/ChatHub.cs
aspnetcore/tutorials/signalr-typescript-webpack/sample/3.x/Startup.cs
aspnetcore/tutorials/signalr-typescript-webpack/sample/3.x/snippets/ChatHub.cs

Addresses #24650.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-6.0&branch=pr-en-us-25273&tabs=visual-studio).

Prepare SignalR, TS, and Webpack for 6.0

---

aspnetcore/fundamentals/logging/index.md

Reference WebApplication.CreateBuilder instead of CreateDefaultBuilder

---

aspnetcore/docfx.json
aspnetcore/migration/no-loc-test.md

Move no-loc test doc

---

aspnetcore/security/enforcing-ssl.md

Fixes #25272.
[Internal Preview](https://review.docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&branch=pr-en-us-25280&tabs=visual-studio).

Link to Kestrel Endpoints from Enforce HTTPS

---

aspnetcore/web-api/jsonpatch.md

Fix line highlight in JSON Patch

---

aspnetcore/security/authentication/add-user-data.md

Remove commented-out content and fix versions

---

aspnetcore/signalr/background-services.md

Fix moniker Hell in background services for SignalR /1

---

aspnetcore/client-side/spa/react.md
aspnetcore/includes/spa-proxy.md

Fixes #24874.
This is a fairly minimal upgrade to 6.0, that covers the basics but doesn't go into detail on the new proxy approach. The work for that is being tracked in #25028.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-6.0&branch=pr-en-us-25331&tabs=visual-studio).

Update React to 6.0

---

aspnetcore/client-side/spa/angular.md

Fixes #25332.
This is a fairly minimal upgrade to 6.0, that covers the basics but doesn't go into detail on the new proxy approach. The work for that is being tracked in #25028.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-6.0&branch=pr-en-us-25333&tabs=visual-studio).

Update Angular to 6.0

---

aspnetcore/migration/31-to-60.md

Update markdown syntax to follow the pattern for file names

Update markdown syntax

---

aspnetcore/mvc/models/file-uploads.md

Fixes #25290
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0&branch=pr-en-us-25323#file-upload-scenarios)
In https://github.com/dotnet/aspnetcore/issues/3704#issuecomment-812301385, fowler asks this be better documented.

File uploads buffers in temp directory /2

---

aspnetcore/blazor/hybrid/tutorials/windows-forms.md

Per https://github.com/dotnet/AspNetCore.Docs/pull/25322#discussion_r828404885

Update Blazor Hybrid WinForms tutorial

---

aspnetcore/performance/response-compression.md
aspnetcore/performance/response-compression/samples/6.x/SampleApp/Program.cs
aspnetcore/performance/response-compression/samples/6.x/SampleApp/ResponseCompressionSample.csproj
aspnetcore/performance/response-compression/samples/6.x/SampleApp/appsettings.Development.json
aspnetcore/performance/response-compression/samples/6.x/SampleApp/appsettings.json

Prep source for updating response compression /1

---

aspnetcore/grpc/configuration.md

Information about configuration for client and server that isn't gRPC specific

gRPC server and client config detail

---

aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs

Fix Minimal APIs nullable parameter example

---

aspnetcore/security/authentication/index.md

Addresses #25359.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0&branch=pr-en-us-25366).

Prepare Authentication for 6.0

---

aspnetcore/security/authentication/index.md

Fixes #25359.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0&branch=pr-en-us-25367).

Update Authentication to 6.0

---

aspnetcore/security/authentication/identity.md

Fix reference to missing UseEndpoints

---

aspnetcore/signalr/background-service/samples/6.0/Clients.ConsoleOne/Clients.ConsoleOne.csproj
aspnetcore/signalr/background-service/samples/6.0/Clients.ConsoleOne/Program.cs
aspnetcore/signalr/background-service/samples/6.0/Clients.ConsoleTwo/Clients.ConsoleTwo.csproj
aspnetcore/signalr/background-service/samples/6.0/Clients.ConsoleTwo/ClockHubClient.cs
aspnetcore/signalr/background-service/samples/6.0/Clients.ConsoleTwo/Program.cs
aspnetcore/signalr/background-service/samples/6.0/HubServiceInterfaces/HubServiceInterfaces.csproj
aspnetcore/signalr/background-service/samples/6.0/HubServiceInterfaces/IClock.cs
aspnetcore/signalr/background-service/samples/6.0/HubServiceInterfaces/Strings.cs
aspnetcore/signalr/background-service/samples/6.0/Server/ClockHub.cs
aspnetcore/signalr/background-service/samples/6.0/Server/Program.cs
aspnetcore/signalr/background-service/samples/6.0/Server/Server.csproj
aspnetcore/signalr/background-service/samples/6.0/Server/Worker.cs
aspnetcore/signalr/background-service/samples/6.0/Server/appsettings.Development.json
aspnetcore/signalr/background-service/samples/6.0/Server/appsettings.json
aspnetcore/signalr/background-service/samples/6.0/SignalRBackgroundServiceSample6.sln
aspnetcore/signalr/background-service/samples/6.0/global.json
aspnetcore/signalr/background-service/samples/6.0/readme.md
aspnetcore/signalr/background-services.md

Fixes #25155.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-6.0&branch=pr-en-us-25361).

Add SignalR background service 6.0 sample

---

aspnetcore/blazor/index.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0&branch=pr-en-us-25372)

Removed Linux as Visual Studio is not supported on Linux.

---

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md

Fixes #25386
Thanks @purplemon! 🚀

Blazor security topic wording change

---

aspnetcore/fundamentals/app-state.md

Expand on string vs object for HttpContext.Items

---

aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse.md
aspnetcore/web-api/advanced/analyzers.md
aspnetcore/web-api/handle-errors.md

Authors showed up for Pranav on a PR build report ... changing to you, Rick, if that's ok.

Change topic author

---

aspnetcore/migration/31-to-60.md

Fixes typo with the correct version of the upgrade path.

Fix Incorrect Version Typo

---

aspnetcore/host-and-deploy/health-checks.md

fix text error

---

aspnetcore/grpc/clientfactory.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0&branch=pr-en-us-25180)
Fixes #25147 
ASP.NET Core 6.0 update for topic and code samples.

v6 update: gRPC client factory integration in .NET

---

aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Options/ArrayExample.cs
aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Pages/Array.cshtml.cs

I had to make the conditional statement come immediately after initializing the _array variable with the config values.
I also removed the early setting of array values in the ArrayExample class for proper indexing of config values

Solved little error in configuration code

---

aspnetcore/tutorials/first-mongo-app.md

Follow-up for #25399.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&branch=pr-en-us-25407&tabs=visual-studio).

Use includes for Mongo prerequisites

---

aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse.md
aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse/samples_snapshot/6.x/Program.cs
aspnetcore/security/authorization/customizingauthorizationmiddlewareresponse/samples_snapshot/6.x/SampleAuthorizationMiddlewareResultHandler.cs

Fixes #25410.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authorization/customizingauthorizationmiddlewareresponse?view=aspnetcore-6.0&branch=pr-en-us-25413).

Update IAuthorizationMiddlewareResultHandler to 6.0

---

aspnetcore/performance/response-compression/samples/6.x/SampleApp/Program.cs

Follow-up for #25352.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-6.0&branch=pr-en-us-25408#azure-deployed-sample).

Use minimal APIs for Response Compression endpoints

---

aspnetcore/security/authorization/dependencyinjection.md

Update Authz Handlers DI to 6.0

---

aspnetcore/fundamentals/middleware/extensibility.md
aspnetcore/fundamentals/middleware/extensibility/samples/2.x/MiddlewareExtensibilitySample/Middleware/ConventionalMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/2.x/MiddlewareExtensibilitySample/Middleware/FactoryActivatedMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/2.x/MiddlewareExtensibilitySample/Middleware/MiddlewareExtensions.cs
aspnetcore/fundamentals/middleware/extensibility/samples/2.x/MiddlewareExtensibilitySample/Startup.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/ConventionalMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/FactoryActivatedMiddleware.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Middleware/MiddlewareExtensions.cs
aspnetcore/fundamentals/middleware/extensibility/samples/3.x/MiddlewareExtensibilitySample/Startup.cs

Addresses #24346.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-6.0&branch=pr-en-us-25424).

Prepare IMiddleware for 6.0

---

aspnetcore/toc.yml

Fix broken link for JavaScript API Reference

---

aspnetcore/docfx.json
aspnetcore/migration/no-loc-test.md

New no-loc test

---

aspnetcore/host-and-deploy/iis/modules.md

Update to indicate WebDav isn't supported, as requested in https://github.com/dotnet/aspnetcore/issues/40903

Update to indicate webdav isn't supported

---

aspnetcore/host-and-deploy/iis/in-process-hosting.md

moniker prep for In proc hosting

---

.openpublishing.publish.config.json
aspnetcore/signalr/hubs.md

Fixes #24574.
Fixes #18081.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0&branch=pr-en-us-25449).

Update SignalR Hubs to 6.0

---

aspnetcore/fundamentals/middleware/index.md
aspnetcore/security/cors.md

Fixes #25264
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-7.0&branch=pr-en-us-25471#serve-files-outside-wwwroot-by-updating-iwebhostenvironmentwebrootpath)
@rabidkitten please review

Cors and UseStaicFiles order /3

---

aspnetcore/tutorials/min-web-api.md
aspnetcore/tutorials/razor-pages/model.md

remove prerelease /1

---

aspnetcore/fundamentals/configuration/options.md

Doc IOptionsSnapshot perf cost /1

---

aspnetcore/blazor/fundamentals/routing.md

Fixes #23385
Thanks @cantSleepNow! :rocket: ... Sorry it took so long for the update. I didn't mark your issue for my tracking project, so it was lost for a bit.

Nullable variants update (string? is supported)

---

aspnetcore/security/authentication/certauth.md
aspnetcore/security/authentication/certauth/samples/6.x/CertAuthSample/Snippets/Program.cs

Fixes #25516
* [3.1](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1&branch=pr-en-us-25524#implement-an-httpclient-using-a-certificate-and-a-named-httpclient-from-ihttpclientfactory-1)
* [5.0](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-5.0&branch=pr-en-us-25524#implement-an-httpclient-using-a-certificate-and-a-named-httpclient-from-ihttpclientfactory)
* [6.0](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0&branch=pr-en-us-25524#implement-an-httpclient-using-a-certificate-and-ihttpclientfactory)

Fix ConfigurePrimaryHttpMessageHandler /2

---

aspnetcore/web-api/advanced/formatting.md
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Controllers/TodoItemsController.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Models/TodoItem.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Models/TodoItemStore.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Program.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/ResponseFormattingSample.csproj
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Controllers/FormatFilter/TodoItemsController.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Controllers/TodoItemsController.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Program.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/appsettings.Development.json
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/appsettings.json

Addresses #24529.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-7.0&branch=pr-en-us-25552).

Add 7.0 version of Response Formatting

---

aspnetcore/host-and-deploy/iis/advanced.md

Fixes  #25499
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0&branch=pr-en-us-25547#shadow-copy)

Shadow deployment /2

---

aspnetcore/fundamentals/configuration/index.md

SEO boost for configuration

---

aspnetcore/blazor/hybrid/tutorials/wpf.md

Add step to Blazor-WPF tutorial

---

aspnetcore/host-and-deploy/windows-service.md

Windows service .net6 moniker prep

---

aspnetcore/fundamentals/middleware/write.md

fix formatting for api reference

---

aspnetcore/web-api/advanced/formatting.md
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Controllers/SampleController.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Models/TodoItem.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Models/Formatted/SampleModel.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Models/SampleModel.cs
aspnetcore/web-api/advanced/formatting/samples/7.x/ResponseFormattingSample/Snippets/Program.cs
aspnetcore/web-api/advanced/formatting/samples_snapshot/7.x/ValidationProblemDetailsCustom.json
aspnetcore/web-api/advanced/formatting/samples_snapshot/7.x/ValidationProblemDetailsDefault.json

Fixes #24529.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-7.0&branch=pr-en-us-25554#format-problemdetails-and-validationproblemdetails-responses).

Document new ModelMetadataDetailsProviders for 7.0

---

aspnetcore/migration/no-loc-test.md

Localization Test 4

---

aspnetcore/fundamentals/configuration/options.md
aspnetcore/fundamentals/configuration/options/samples/6.x/OptionsValidationSample/Snippets/Program.cs

Document ValidateOnStart Options Validation

---

aspnetcore/web-api/index.md

Fixes #24293.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0&branch=pr-en-us-25608#multipartform-data-request-inference).

Correct explanation of multipart/form-data request inference

---

aspnetcore/fundamentals/configuration/index.md

Clarify cmdline configuration examples

---

aspnetcore/fundamentals/http-requests.md

Replace HttpRequestMessage.Properties recommendation with HttpRequestMessage.Options

---

aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/EmailService.cs
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/HttpContextInBackgroundThread.csproj
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/IEmailService.cs
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/NewsletterService.cs
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/Program.cs
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/appsettings.Development.json
aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/appsettings.json
aspnetcore/fundamentals/http-context/samples/6.x/readmd.txt

Addresses #7721.
@Rick-Anderson please have a look :)

Http context caveats

---

aspnetcore/grpc/authn-and-authz.md
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/Program.cs
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/Protos/ticket.proto
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/Services/TicketerService.cs
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/TicketRepository.cs
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/Ticketer.csproj
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/appsettings.Development.json
aspnetcore/grpc/authn-and-authz/sample/6.x/Ticketer/appsettings.json
aspnetcore/grpc/authn-and-authz/sample/6.x/TicketerClient/Program.cs
aspnetcore/grpc/authn-and-authz/sample/6.x/TicketerClient/Protos/ticket.proto
aspnetcore/grpc/authn-and-authz/sample/6.x/TicketerClient/TicketerClient.csproj

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-6.0&branch=pr-en-us-25628)
Fixes #25137 
- Added a 6.0 version app samples for Ticketer Service and TicketerClient apps. (See download link at top of  doc)
- Updated content and code snippets to reflect .NET 6.0.

gRPC Authentication & Authorization Version 6.0 update

---

aspnetcore/razor-pages/index.md
aspnetcore/razor-pages/index/3.0sample/RazorPagesContacts/Pages/Customers/Index.cshtml
aspnetcore/razor-pages/index/sample/RazorPagesContacts2/Pages/Customers/CreateFATH.cshtml

Follow-up for #25627.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&branch=pr-en-us-25630&tabs=visual-studio).

Prefer name over range for snippets

---

aspnetcore/fundamentals/servers/kestrel/http3.md

version compatibility needed to be included

Update http3 docs for libmsquic version compatibility

---

aspnetcore/blazor/file-uploads.md

InputFile selection not cumulative

---

aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/hybrid/index.md
aspnetcore/blazor/index.md
aspnetcore/blazor/supported-platforms.md

Prevent 'Web View' loc

---

aspnetcore/blazor/hybrid/tutorials/windows-forms.md

Fixes  #25647
Thanks @rod-mac! 🎸

Update for RC1

---

aspnetcore/blazor/tutorials/signalr-blazor.md

Fixes #25650
Thanks @smadgerano! :rocket: ... Let's see if this helps head folks off from this happening again.

Add hosted WASM confirmation step

---

aspnetcore/blazor/hybrid/tutorials/wpf.md

WPF-Blazor tutorial updates

---

aspnetcore/blazor/security/server/index.md

Register auth provider after AddServerSideBlazor

---

aspnetcore/blazor/hybrid/tutorials/windows-forms.md
aspnetcore/blazor/hybrid/tutorials/wpf.md

Fixes #25661
Thanks @JerryMVC! :rocket:
I made changes yesterday for churn from the last preview to RC1. These changes didn't appear in the blog post, nor was I informed of the updates by the product unit. I missed a spot tho further down in the topic when I made the updates. This takes care of that for both the WinForms and the WPF tutorials.

Additional Blazor Hybrid tutorial update

---

aspnetcore/security/authentication/mfa.md

Fixes #7326.
As the linked issue has sat for almost 4 years, I decided to keep it minimal and just explain what's required rather than giving example code.
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-6.0&branch=pr-en-us-25669).

Explain how to enable/disable 2FA and TOTP

---

aspnetcore/mvc/views/view-components.md

Fix typo and remove "ing"s

---

aspnetcore/blazor/fundamentals/configuration.md
aspnetcore/blazor/fundamentals/environments.md
aspnetcore/blazor/fundamentals/logging.md
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/logging/Counter1.razor
aspnetcore/blazor/samples/6.0/BlazorSample_Server/Pages/logging/Counter2.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/logging/Counter1.razor
aspnetcore/blazor/samples/6.0/BlazorSample_WebAssembly/Pages/logging/Counter2.razor

*Note to self*: ~Don't forget a companion `dotnet/blazor-samples` repo update.~ **_Done!_** 👍 https://github.com/dotnet/blazor-samples/pull/9

Blazor WASM logging coverage enhancements

---

aspnetcore/security/docker-https.md

dotnet dev-certs https command example clearer

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Fixes #25723
Thanks @lonix1! :rocket: ... The addition of a cross-link to the doc for integrating RP/MVC into a hosted Blazor WASM solution doesn't directly address your ask for actually showing exactly how to compose it, but guidance should work together for the two scenarios. This subject will remain on my tracking issue for another look later when I have more time.

Cross-link additional scenarios

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Additional cross-link improvements

---

aspnetcore/migration/22-to-30.md

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&branch=pr-en-us-25736&tabs=visual-studio)

Fixed namespace for IWebHostEnvironment

---

aspnetcore/signalr/configuration.md
aspnetcore/signalr/hubs.md

Documenting feature from https://github.com/dotnet/aspnetcore/pull/34047

Add DI to SignalR hub methods

---

aspnetcore/razor-pages/index.md
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Data/CustomerDbContext.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Models/Customer.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Create.cshtml
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Create.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Delete.cshtml
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Delete.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Details.cshtml
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Details.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Edit.cshtml
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Edit.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Index.cshtml
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Customers/Index.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Index.cshtml.cs
aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Privacy.cshtml.cs

Addresses https://github.com/dotnet/AspNetCore.Docs/issues/25694
@Rick-Anderson @serpent5 please review. I've removed the `#pragma warning disable CS8618` statements from the code and updated them accordingly

Update razor pages sample and doc for ASP.NET Core 6

---

aspnetcore/host-and-deploy/linux-nginx.md

Update Ubuntu version

---

aspnetcore/blazor/project-structure.md

Fixes #12572
* The *Hosting Models* topic isn't the best spot for this, based on chats with DR about the purpose and focus of the hosting models coverage there. The *Project Structure* topic is probably better for this, so that's where I'm drafting the content on the PR.
* **_DEFINITELY_** avoiding the word "hybrid" here 😨. Let's see how it composes with the word "dual."
* I started with only using the word "solution" in the section heading, but I'm going to change that to just "app." In fact, I need to assess the choice to use the word "solution" at all around Blazor docs, as it's probably only formally a VS concept. I know that I've favored it over the years for hosted WASM (a "solution" of three projects). That might change. Anyway, let's avoid "solution" here for sure.

Dual WASM/Server project structure

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/file-uploads.md
aspnetcore/blazor/forms-validation.md
aspnetcore/blazor/fundamentals/dependency-injection.md
aspnetcore/blazor/fundamentals/environments.md
aspnetcore/blazor/fundamentals/routing.md
aspnetcore/blazor/fundamentals/static-files.md
aspnetcore/blazor/host-and-deploy/index.md
aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
aspnetcore/blazor/security/includes/troubleshoot.md
aspnetcore/blazor/security/webassembly/additional-scenarios.md
aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
aspnetcore/blazor/security/webassembly/graph-api.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/index.md
aspnetcore/blazor/tooling.md
aspnetcore/blazor/tutorials/signalr-blazor.md
aspnetcore/blazor/webassembly-lazy-load-assemblies.md

Role of the solution file with Blazor

---

aspnetcore/blazor/components/rendering.md

Improve Blazor change detection description

---

aspnetcore/blazor/components/rendering.md

Fixes #25776
Thanks to Bill Wagner and Tom Dykstra for their help.

Change detection remark update

---

aspnetcore/grpc/loadbalancing.md

Fixed gRPC load balancing docs based on the current APIs.

fix grpc loadbalancing doc based on current APIs

---

aspnetcore/blazor/components/rendering.md

Addresses #25776
cc: @szalapski
This text is plagued with a nasty **_gremlin_** 😈! 😄 I'll ping Steve on Monday to discuss this further and review the PR.
If we can just say 'set of known types' and 'see the ref source' for them, that's really the best. I've been around here five years now, and I'm telling u that it will all end in **_tears_** 😢 if we try to explicitly list these types ... devs will get 😠 after they churn ... I'll forever need to be looking over my shoulder everywhere I go for the rest of my life! 😨😆

Update parameter change detection remarks

---

aspnetcore/test/load-tests.md

Added reference to Azure Load Testing

---

aspnetcore/blazor/hybrid/index.md

BlazorWebView configuration

---

aspnetcore/blazor/hybrid/security/index.md

Fixes #25453
**_HOLD for RC2 release._**

[RC2] Keep WebViews current

---

aspnetcore/fundamentals/dependency-injection.md
aspnetcore/fundamentals/dependency-injection/samples/6.x/DependencyInjectionSample/DependencyInjectionSample.csproj
aspnetcore/fundamentals/dependency-injection/samples/6.x/DependencyInjectionSample/Middleware/MyMiddleware.cs
aspnetcore/fundamentals/dependency-injection/samples/6.x/DependencyInjectionSample/Program.cs

Fix trans middleware DI sample/1

---

aspnetcore/security/authentication/identity.md

I found it challenging to understand the relationship of ASP.NET Identity, Duende IdentityServer4 and Microsoft identity platform. I hope this change can make it easier for others.

Clarify the relationship of ASP.NET Identity, IdentityServer4 and Microsoft identity platform

---

aspnetcore/tutorials/first-web-api.md

[Internal Review 5.0 & 6.0](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&branch=pr-en-us-25812&tabs=visual-studio-mac#install-postman)
Fixes #21967 
Verified latest Postman for Windows and macOS.
I didn't put the OS specific Postman menu instructions in tabs for VS vs Visual Studio Code vs VS for Mac.  That didn't really make sense here since it was strictly the Postman UI and a sub section of it at that. So I just specified the Postman OS specific menu instruction inline.

Web API tutorial - Update Postman for Mac menu instruction

---

aspnetcore/mvc/models/validation.md
aspnetcore/mvc/models/validation/samples/6.x/WeatherForecastG.cs

Fixes #25840
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0&branch=pr-en-us-25841#non-nullable-reference-types-and-required-attribute)

non-nullable generic requied /1

---

aspnetcore/mvc/models/validation.md

Fixes #25842
[Internal review URL 6](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0&branch=pr-en-us-25844)
[Internal review URL 7](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0&branch=pr-en-us-25844)

.NET 7 validation /1

---

aspnetcore/fundamentals/routing.md

The statement I made changes to was due to the fact that explicit values were used in the link generator method but no ambient value was used

made changes to a statement

---

aspnetcore/data/ef-mvc/intro/samples/cu-final/Data/SchoolContext.cs

Fixes #25167 - Typos in the table assignment

Fixed typos in the table assignment

---

aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Departments/Delete.cshtml

Fixes #24722 - Added the missing id details in the page directive

#24722 - Updated the page directive

---

aspnetcore/blazor/fundamentals/handle-errors.md

Fixes #25873
Thanks @lcichanowicz! 🚀

Language patch

---

aspnetcore/data/ef-mvc/intro/samples/cu-final/Data/SchoolContext.cs

Reverts dotnet/AspNetCore.Docs#25865
Closer to the inheritance solution.

Revert "Fixed typos in the table assignment"

---

aspnetcore/signalr/client-features.md

Reverts dotnet/AspNetCore.Docs#25884

Revert "Update links"

---

aspnetcore/host-and-deploy/windows-service.md

Fixes #25880 
Fixes #23387 
addresses https://github.com/dotnet/runtime/issues/69212

Added --contentRoot to PowerShell New-Service command

---

aspnetcore/grpc/performance.md

From internal performance investigation.
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.0&branch=pr-en-us-25901

Add gRPC performance section on flow control

---

aspnetcore/blazor/security/index.md

Fixes #25895
Thanks @gregoryagu! 🚀 ... This will hopefully catch the reader's 👁️ before they fail with the Razor code alone.

Improve cross-link

---

aspnetcore/grpc/performance.md

Follow up feedback on https://github.com/dotnet/AspNetCore.Docs/pull/25901

Flow control feedback

---

aspnetcore/blazor/tooling.md

Fixes #25912
Thanks @gaazkam! :rocket:

Update Linux cert trust guidance

---

aspnetcore/blazor/tooling.md

Fixes #25913
Thanks again, @gaazkam! 🎸

Silence VSC remarks for Windows & macOS

---

aspnetcore/blazor/fundamentals/logging.md

Fix highlighting

---

aspnetcore/security/authentication/index.md

Like Orchard Core, ABP Framework is also a popular web application framework for ASP.NET Core. I believe Microsoft can recommend such frameworks to encourage successful open source projects.
***@Rick-Anderson edit:***
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0&branch=pr-en-us-25892#authentication-providers-per-tenant)

Added ABP Framework as a recommended project

---

aspnetcore/security/authorization/secure-data/samples/final6/Pages/Contacts/Details.cshtml

"Preceding" instead of "Precedng"

Correct typo error

---

aspnetcore/blazor/hosting-models.md
aspnetcore/blazor/hybrid/developer-tools.md
aspnetcore/blazor/hybrid/index.md
aspnetcore/blazor/hybrid/reuse-razor-components.md
aspnetcore/blazor/hybrid/routing.md
aspnetcore/blazor/hybrid/security/index.md
aspnetcore/blazor/hybrid/security/security-considerations.md
aspnetcore/blazor/hybrid/static-files.md
aspnetcore/blazor/hybrid/tutorials/index.md
aspnetcore/blazor/hybrid/tutorials/maui.md
aspnetcore/blazor/hybrid/tutorials/windows-forms.md
aspnetcore/blazor/hybrid/tutorials/wpf.md
aspnetcore/blazor/includes/blazor-hybrid-preview-notice.md
aspnetcore/blazor/includes/net-maui-release-candidate-notice.md
aspnetcore/blazor/index.md

Blazor Hybrid doc updates

---

aspnetcore/blazor/supported-platforms.md

Fixes #25640
Thanks @kgkayak! :rocket: ... As Dan said on the issue, trouble on a given platform may warrant opening a product unit issue at https://github.com/dotnet/aspnetcore/issues. Provide as much detail as you can ... code ... screenshots ... a repro app placed on GH for them to download and run. As far as this PR is concerned, I think this will clear up the ambiguity that you asked about.

Update Blazor supported platforms article

---

aspnetcore/web-api/advanced/formatting.md

**Global effort to fix broken links**
@rick-anderson
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

[BrokenLinksH2] fixing broken links

---

aspnetcore/web-api/advanced/formatting.md

Polymorphic deserialization

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/components/prerendering-and-integration.md
aspnetcore/blazor/globalization-localization.md

Blazor diff code fixups

---

aspnetcore/includes/th_version.md
aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md
aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md
aspnetcore/mvc/views/tag-helpers/intro.md

Add TH version gen outside wwwroot

---

aspnetcore/security/authorization/resourcebased.md

Moniker hell fix resource auth

---

aspnetcore/blazor/fundamentals/logging.md

The filtering section example logs Information instead of warning.

Correction of a possible typo

---

aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md

Fixed invalid attribute name.

---

aspnetcore/fundamentals/servers/kestrel.md

Remove duplicate words

---

aspnetcore/blazor/fundamentals/logging.md

WASM Scopes Logger sample

---

aspnetcore/blazor/components/lifecycle.md

Cross-link rendering conventions

---

aspnetcore/security/authentication/certauth.md

We want to make this clear. Context https://github.com/dotnet/aspnetcore/issues/41653
@BrennanConroy

You MUST configure your server for cert auth to work

---

aspnetcore/security/authentication/identity-custom-storage-providers.md

Fixes 16925 Fixes #17188 Fixes #26007
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-6.0&branch=pr-en-us-26008#reconfigure-app-to-use-a-new-storage-provider)

.NET 6 Custom storage providers for Identity /1

---

aspnetcore/security/data-protection/configuration/overview.md

TODO: Update migration docs too
This will close https://github.com/dotnet/aspnetcore/issues/38274

Provide workaround for regression in AddDataProtection

---

aspnetcore/performance/caching/memory.md

Addresses #26022
Thanks @greyhillman! :rocket:

Update cached item sliding expiration guidance

---

aspnetcore/blazor/security/index.md
aspnetcore/blazor/security/server/index.md

Fixes #26014
[Internal Review Topic (links to section)](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/security/index?view=aspnetcore-3.1&branch=pr-en-us-26015#blazor-server-authentication)
The PR ...
* Moves the section to the *Security and Identity* overview.
* Because the overview is meant to primarily address *common* guidance, I felt it best to integrate the content into the topic's existing section on *Blazor Server authentication*.
* Seeks to extend and clarify prior remarks in the section. This is purely *first-cup* ☕ language ideas to get us started. I expect it to change, perhaps quite a bit.👂
I defer on pinging any of the others from the discussion.

Blazor default ASP.NET Core Identity UI updates

---

aspnetcore/blazor/hosting-models.md

Fixes #25855
Fixes #25910
[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1&branch=pr-en-us-25948)
Notes ...
* *DRAFT-y-ish* for sure. This text likely needs some technical wording/marketing lingo help.
* To some degree, the content provided in the table from Javier is already covered here. I tried to identity new feature concepts for the coverage and concentrate on those for potential additions.
* I recommend that we try to expand the existing table. I think the existing table hasn't become overloaded ... *yet*.

Blazor hosting models topic updates

---

aspnetcore/tutorials/min-web-api.md

Use lowercase for consistency

---

aspnetcore/fundamentals/environments.md
aspnetcore/fundamentals/environments/samples/6.x/EnvironmentsSample/Pages/About.cshtml
aspnetcore/fundamentals/environments/samples/6.x/EnvironmentsSample/Pages/About.cshtml.cs
aspnetcore/fundamentals/environments/samples/6.x/EnvironmentsSample/Pages/Shared/_Layout.cshtml
aspnetcore/fundamentals/environments/samples/6.x/EnvironmentsSample/Program.cs
aspnetcore/fundamentals/environments/samples/6.x/dnr-prod.txt
aspnetcore/fundamentals/environments/samples/6.x/dnr-verbose.txt

Env updates /1

---

aspnetcore/blazor/fundamentals/routing.md

Fix redundant equal sign

---

aspnetcore/blazor/components/links-test-2.md
aspnetcore/blazor/links-test-1.md

Blazor sample cross-link test

---

aspnetcore/mvc/views/dependency-injection.md
aspnetcore/mvc/views/dependency-injection/6.0sample/WebViewInject/Controllers/ProfileController.cs
aspnetcore/mvc/views/dependency-injection/6.0sample/WebViewInject/Models/Services/ProfileOptionsService.cs
aspnetcore/mvc/views/dependency-injection/6.0sample/WebViewInject/Pages/Privacy.cshtml
aspnetcore/mvc/views/dependency-injection/6.0sample/WebViewInject/Pages/RPprofile.cshtml
aspnetcore/mvc/views/dependency-injection/6.0sample/WebViewInject/Pages/RPprofile.cshtml.cs

Fixes #26071
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-6.0&branch=pr-en-us-26084)

.NET 6: DI in views /4

---

aspnetcore/fundamentals/servers/kestrel/endpoints.md

moniker prep for Kestrel endpoints

---

aspnetcore/blazor/tutorials/signalr-blazor.md
aspnetcore/blazor/tutorials/signalr-blazor/samples/3.1/BlazorWebAssemblySignalRApp/Server/Startup.cs
aspnetcore/blazor/tutorials/signalr-blazor/samples/5.0/BlazorWebAssemblySignalRApp/Server/Startup.cs
aspnetcore/blazor/tutorials/signalr-blazor/samples/6.0/BlazorWebAssemblySignalRApp/Server/Program.cs

Fixes  #26105
Thanks @Ricardoaraujo00! 🎸 ... I place the lines SxS and only show those two lines in the topic. In addition to clearing up confusion about what to add, this will accomplish my general goal of having the doc's snippet copy button just grab those two lines for pasting into the dev's sample app.

Improve step in Blazor-SignalR tutorial

---

aspnetcore/fundamentals/index.md

Actually, I caused that typo with a change I made. I fixed it.

Minimum Host was used but it is Minimal Host

---

aspnetcore/blazor/fundamentals/handle-errors.md

Update error UI message

---

aspnetcore/fundamentals/logging/index.md
aspnetcore/fundamentals/logging/index/samples/6.x/WebLog/Program.cs
aspnetcore/fundamentals/logging/index/samples/6.x/WebLog/WebLog.csproj
aspnetcore/fundamentals/logging/index/samples/6.x/WebLog/appsettings.Development.json
aspnetcore/fundamentals/logging/index/samples/6.x/WebLog/appsettings.json

Fixes #26143
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0&branch=pr-en-us-26149#log-in-programcs)

show how to log in Program.cs /3

---

aspnetcore/fundamentals/configuration/index.md

Moniker prep for .NET 7 configuration

---

aspnetcore/blazor/hybrid/tutorials/maui.md

Call out preview template install workaround

---

aspnetcore/security/authorization/secure-data/samples/starter6/Pages/Shared/_Layout.cshtml

Layout for sample is referring to minimized JavaScript and CSS files which aren't present in the project.
Apologies if I've missed a step and they should be created, but I removed the .min part of the filename and everything then looked right.

Update _Layout.cshtml to correct missing files

---

aspnetcore/performance/response-compression.md

Response Compression moniiker prep /2

---

aspnetcore/blazor/components/prerendering-and-integration.md

Fix code diff

---

aspnetcore/security/authorization/simple.md

Minor grammar edit

---

aspnetcore/data/ef-rp/intro.md

Rather than to old EF6 perf docs
/cc @ajcvickers

Point to the EF Core performance docs

---

aspnetcore/grpc/authn-and-authz.md
aspnetcore/grpc/interceptors.md

[Internal Review - Interceptor Link added to Additional Resources](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-6.0&branch=pr-en-us-26220#additional-resources)
[Internal Review - Interceptor Link added to Additional Resources](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-6.0&branch=pr-en-us-26220#additional-resources)
Fixes #25724

gRPC Authentication: add Interceptor links

---

aspnetcore/grpc/health-checks.md

Fixes https://github.com/grpc/grpc-dotnet/issues/1790

Add publisher configuration to gRPC health checks doc

---

aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/Filters/Program.cs

Fix Invo context

---

aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/Filters/Program.cs

Hi @Rick-Anderson the indentation in the minimal API filters doc was looking a bit weird. I did a fix, please have a look

Minimal api identation fix

---

aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/readme.md

Fix broken links: Update readme.md

---

aspnetcore/security/authentication/identity-api-authorization.md
aspnetcore/toc.yml

What's new to TOC

---

aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/ReadMe.md
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/ReadMe.md

preps 7.0 sample folders

---

aspnetcore/signalr/hub-filters.md

Had to define the **arguments** variable

added the implicit type declarator using var

---

aspnetcore/blazor/file-downloads.md

Fixes #26298
Thanks @frankleib! :rocket:

Update JS in file downloads example

---

aspnetcore/release-notes/aspnetcore-6.0.md

Note Blazor project template changes for 6.0

---

aspnetcore/signalr/streaming.md

I think the extra code wasn't necessary. Since it was already present

removed some redundant piece

---

aspnetcore/migration/31-to-50.md

Fixes #26305
Thanks @cocoa-dev008! :rocket:

Package reference changes section

---

aspnetcore/migration/31-to-50.md
aspnetcore/release-notes/aspnetcore-7.0.md

SignalR hubs to what's new

---

aspnetcore/blazor/security/includes/index-page-msal.md

Remove spaces from an RCL asset link

---

aspnetcore/fundamentals/minimal-apis/bindStreamPipeReader/7.0-samples/readme.txt
aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/readme.txt

Folders fo IFormFile and Stream/PipeReade samples

---

aspnetcore/blazor/fundamentals/signalr.md

Fixes #26301
Thanks @pradeep-w! :rocket:
~Brennan, thx for looking given that this isn't really a complicated SignalR concept.~ Sorry about that ... I should've guessed! 😄

Clarifications on reconnect UI rendering

---

aspnetcore/test/minimal-api-tests/7.0-samples/readme.txt

Minimal API unit tests folder

---

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/readme.txt

Bind TryParse

---

aspnetcore/fundamentals/minimal-apis/resultsStream/7.0-samples/readme.txt

results stream

---

aspnetcore/release-notes/aspnetcore-7.0.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-1.0&branch=pr-en-us-26359#server)

ServerReady and HTTP/2

---

aspnetcore/fundamentals/minimal-apis/misc-samples/typedResults/readme.txt

TypedResults code folder

---

aspnetcore/blazor/fundamentals/index.md

Fixes #26398
Thanks @Loophole62ndFF! :rocket: ... I think removing it will be fine.

Remove sentence

---

aspnetcore/client-side/using-browserlink.md

Fixes #16949
[Internal Review - Intro section](https://review.docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-6.0&branch=pr-en-us-26399)
Included more information on what Browser Link is for in the intro.

Improve Browser Link intro

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/todo/Program.cs

Fixes #26396
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26397#bind-arrays-and-string-values-from-headers-and-query-strings)

Bind arrays with Min APIs /2

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/release-notes/aspnetcore-7.0.md

Add Streams to What's new

---

aspnetcore/blazor/fundamentals/dependency-injection.md

Fixes #26330
Thanks @nkatz01! :rocket: ... Except for an explicit recommendation to read the main doc set's DI topic first, I'm happy with the current language on the service behaviors. The content is accurate, but one can't read too far into these remarks, either. They must be taken at face value. The thrust of the paragraph on Blazor Server is that circuit-based communication doesn't reconstruct scoped services, while HTTP-based communication does (at it normally does in ASP.NET Core apps). I'll continue to take feedback on these points.

Recommend reading main DI topic

---

aspnetcore/blazor/components/dynamiccomponent.md

Fixes #26324
Thanks @jwu-dharmo! :rocket: ... I'm going to base this on the existing example but not roll it into the sample app at this time. This topic is on a tracking item for further work at https://github.com/dotnet/AspNetCore.Docs/issues/24615, so I'll circle around later to add the example to snippet sample apps later. For now, this will surface the approach. The product unit is too busy 🏃 right now to review this, so I'm going to go ahead and get it in. I'll take reader feedback on it as we go forward.

Event callbacks with DynamicComponent

---

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Controllers/WeatherForecastController.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Models/Culture.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseAPI/Models/DateRange.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/Culture.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRange.cs

Clean up TryParse samples

---

aspnetcore/mvc/models/model-binding.md

moniker prep for model binding

---

aspnetcore/blazor/fundamentals/logging.md

WASM logging in Program.cs

---

aspnetcore/release-notes/aspnetcore-7.0.md

What's new Typed results

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/7.0-samples/todo/Program.cs
aspnetcore/release-notes/aspnetcore-7.0.md

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-1.0&branch=pr-en-us-26478#openapinuget)

What's new OpenAPI /2

---

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Program.cs

Fix datetime culture

---

aspnetcore/migration/proper-to-2x/index.md

Fixes #26495
Thanks @Simon-Miller! :rocket:

Remove duplicated words

---

aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/MinimalApi/MinimalApi.csproj
aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/MinimalApi/Program.cs
aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/MinimalApi/appsettings.Development.json
aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/MinimalApi/appsettings.json
aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/readme.txt

Adding IFormFile samples

---

aspnetcore/data/ef-rp/intro/samples/cu70/appsettings.Development2.json

Sample folder for EF/RP 7.0

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/bindStreamPipeReader/7.0-samples/PipeStreamToBackgroundQueue/BackgroundQueueService.cs
aspnetcore/fundamentals/minimal-apis/bindStreamPipeReader/7.0-samples/PipeStreamToBackgroundQueue/Program.cs

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26510#bind-the-request-body-as-a-stream-or-pipereader)

Bind request boday as stream /6

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/release-notes/aspnetcore-7.0.md

Wn request body stream

---

aspnetcore/fundamentals/minimal-apis/samples/todo/Program.cs

Fix snippet syntax

---

aspnetcore/grpc/health-checks.md
aspnetcore/grpc/httpapi.md

* Add streaming information
* Shorten "JSON transcoding" to just "transcoding" in the doc

Add streaming information to gRPC transcoding doc

---

aspnetcore/mvc/models/validation.md

moniker prep for model validation

---

aspnetcore/grpc/browser.md
aspnetcore/grpc/httpapi.md

React to customer issue https://github.com/grpc/grpc-dotnet/issues/1830

Add HTTP protocols section to gRPC-Web and transcoding docs

---

aspnetcore/grpc/browser.md
aspnetcore/grpc/httpapi.md

@guardrex I decided I prefered the other option 😄

Change sentence order

---

aspnetcore/mvc/models/model-binding.md

Fixes #26580 
Preview URL: 
https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1&branch=pr-en-us-26581#collections-2
https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0&branch=pr-en-us-26581#collections-1
https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0&branch=pr-en-us-26581#collections

Adding back Form Data only statement

---

aspnetcore/blazor/fundamentals/index.md

Add a ref source Basic Test App cross-link

---

aspnetcore/migration/http-modules.md
aspnetcore/security/authorization/secure-data.md

Fix Some Broken Bookmarks

---

aspnetcore/blazor/globalization-localization.md

Fixes #26599
Thanks @genifycom! :rocket:

Remove oversimplified JS interop modules remark

---

aspnetcore/blazor/file-uploads.md

Fixes #26602
Thanks @Olby2000! :rocket:

SignalR message size limit

---

aspnetcore/blazor/host-and-deploy/index.md

Fixes #26604
Thanks @BlanketFortGames! :rocket:

Add cross-link to launchSettings.json guidance

---

aspnetcore/whats-new/dotnet-AspNetCore.Docs-2022-07-01.md
aspnetcore/whats-new/index.yml
aspnetcore/whats-new/toc.yml

What's new for July

---

aspnetcore/fundamentals/servers/kestrel/endpoints.md

Addresses https://github.com/dotnet/aspnetcore/issues/42982

Document dynamic port binding limitations

---

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/LDR.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRange.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRangeTP.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/Locale.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Program.cs
aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Views/Shared/_Layout.cshtml
aspnetcore/mvc/models/model-binding.md

Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/26423
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0&branch=pr-en-us-26608#bind-with-tryparse)
Moved from #26488

TryParse /6

---

aspnetcore/release-notes/aspnetcore-7.0.md

TryParse in What's new

---

aspnetcore/blazor/file-downloads.md

Clarify scenarios for Blazor file downloads article

---

aspnetcore/grpc/browser.md

Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-7.0&branch=pr-en-us-26625

Improve gRPC browser topic

---

aspnetcore/blazor/components/virtualization.md

Virtualization enhancements and updates

---

aspnetcore/blazor/fundamentals/signalr.md
aspnetcore/blazor/security/webassembly/index.md
aspnetcore/blazor/tutorials/signalr-blazor.md

Add cross-link to SignalR auth guidance

---

aspnetcore/release-notes/aspnetcore-7.0.md

[Internal Review- Client results section](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26675#client-results)
Fixes #26673
Contributes to #26477

Added Client Results for SignalR sub-section

---

aspnetcore/release-notes/aspnetcore-7.0.md

[Internal review: gPRC section of What's new](https://review.docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-26679#grpc)
Fixes #26677 
Contributes to #26477 
Adding gRPC > gRPC JSON transcoding section to .NET 7.0 What's new

7.0 What's new: Adding gRPC JSON transcoding section

---

aspnetcore/release-notes/aspnetcore-7.0.md

What's new react and angular

---

aspnetcore/blazor/images.md

Fix Issue 26680 in blazor image documentation  

---

aspnetcore/test/troubleshoot-azure-iis.md

Fixes #26664
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-7.0&branch=pr-en-us-26666#troubleshoot-on-azure-app-service)

Azure streaming logs /5

---

aspnetcore/security/authentication/jwt-authn.md

Fixes description section in jwt-authn.md

---

aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Instructors/Index.cshtml.cs

Simplify code for Instructors page

---

aspnetcore/fundamentals/minimal-apis/min-api-filters.md

Ra filters

---

aspnetcore/fundamentals/minimal-apis/min-api-filters.md

Rename IRouteHandlerFilter => IEndpointFilter

---

aspnetcore/blazor/components/class-libraries.md
aspnetcore/blazor/debug.md
aspnetcore/blazor/host-and-deploy/index.md
aspnetcore/blazor/hybrid/developer-tools.md
aspnetcore/blazor/hybrid/static-files.md
aspnetcore/blazor/hybrid/tutorials/windows-forms.md
aspnetcore/blazor/progressive-web-app.md
aspnetcore/blazor/security/server/index.md
aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
aspnetcore/blazor/tooling.md
aspnetcore/blazor/tutorials/signalr-blazor.md

Update Blazor-macOS guidance

---

aspnetcore/grpc/test-services/sample/Server/Startup.cs
aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/Helpers/GrpcTestContext.cs
aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs

Changes from https://github.com/grpc/grpc-dotnet/pull/1841

Sync test app with changes in grpc-dotnet repo

---

aspnetcore/blazor/host-and-deploy/index.md

Revise guidance on UsePathBase

---

aspnetcore/blazor/host-and-deploy/webassembly.md

Removed typo

---

aspnetcore/fundamentals/middleware/request-decompression.md
aspnetcore/release-notes/aspnetcore-7.0.md
aspnetcore/toc.yml

Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/26541

What's new Request decompresssion /8

---

aspnetcore/blazor/security/server/additional-scenarios.md

This 😈 *gremlin* 😈 got under the radar when the node was addressed for NRTs earlier.

Update token provider example for NRTs

---

aspnetcore/security/anti-request-forgery.md

Prevent Cross-Site Request Forgery: Minor very quick fix on code sample type.
Fixes #26783
[Internal review - link to edited section](https://review.docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0&branch=pr-en-us-26786#javascript)

Update anti-request-forgery.md: Fix code sample type

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/OpenAPISummary/OpenAPISummary.csproj
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/OpenAPISummary/Program.cs
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/OpenAPISummary/appsettings.Development.json
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/OpenAPISummary/appsettings.json
aspnetcore/fundamentals/minimal-apis/endpoint-description-summary/7.0-samples/ReadMe.md

Contributes to #26291
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26791#add-endpoint-summary-or-description)

.NET 7 - Provide OpenAPI endpoint summary and description

---

aspnetcore/grpc/services.md

Fixes https://github.com/grpc/grpc-dotnet/issues/1845
[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/services?view=aspnetcore-7.0&branch=pr-en-us-26767)

Add section on multi-threading to gRPC services doc

---

aspnetcore/blazor/blazor-server-ef-core.md

Fixes #26813
Thanks @bxjg1987! :rocket:

Loading logic enhancement

---

aspnetcore/fundamentals/minimal-apis.md
aspnetcore/toc.yml

Add links to OpenAPI doc 

---

aspnetcore/tutorials/first-mvc-app/start-mvc/sample/6.0-completed/appsettings_SQLite.json
aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie60/appsettings_SQLite.json

[Internal Review](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&branch=pr-en-us-26808&tabs=visual-studio-code#examine-the-generated-database-connection-string)

Fix appsettings_SQLite.json syntax

---

aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples/MinimalApi/Program.cs

IFormFile code update

---

aspnetcore/blazor/tutorials/build-a-blazor-app.md
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo0.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo2.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo3.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo4.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo5.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo6.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/3.1/Todo7.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo0.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo2.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo3.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo4.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo5.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo6.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/5.0/Todo7.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo0.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo2.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo3.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo4.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo6.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/6.0/Todo7.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo0.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo2.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo3.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo4.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo6.razor
aspnetcore/blazor/tutorials/build-a-blazor-app/7.0/Todo7.razor

Move example code to repo

---

aspnetcore/release-notes/aspnetcore-7.0.md

what's new update

---

aspnetcore/blazor/hosting-models.md

Fixes #26833
Thanks @BernhardHofmannAtDwellant! :rocket:

Fix word and a stray space

---

aspnetcore/blazor/components/virtualization.md

Collection type approaches for virtualization

---

aspnetcore/fundamentals/url-rewriting.md

show where user defined class comes from

---

aspnetcore/blazor/host-and-deploy/index.md

Add WASM guidance to Blazor Host & Deploy overview

---

aspnetcore/release-notes/aspnetcore-6.0/samples/WebApp1/Program.cs

- Used the value of the variable directly

feat: use variable value directly

---

aspnetcore/blazor/file-uploads.md

Cancel a file upload section

---

aspnetcore/toc.yml

Contributes to #26515
* [Rate limit](https://review.docs.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0&branch=pr-en-us-26880)

Rate limit middleware to TOC /1

---

aspnetcore/release-notes/aspnetcore-7.0.md

link in What's new
