aspnetcore/blazor/blazor-server-ef-core.md
Fixes #26873
Thanks @KurtP20! 🚀 ... I think this section was the content that you were seeking, not per the guidance in the main doc set. However, I think we can make an improvement here with this PR that will help clarify the example a bit further. Of course, the whole sample app is quite great 🎉 ... built by a guru dB engineer and product manager 🙏, Jeremy Likness.
If you plan to look this over, please do so quickly 🏃, as I'm trying to avoid 😈 **_merge conflicts_** 😈 under a rapid .NET 7 content rollout.
=> Improve dB factory/context section

aspnetcore/blazor/hybrid/tutorials/maui.md
Fixes #26164
This has been resolved in the time between VS Preview 1 and Preview 4 according to the MAUI folks.
=> Drop workaround NOTE

aspnetcore/host-and-deploy/windows-service.md, aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Program.cs
Fixes #26843
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-7.0&branch=pr-en-us-26844&tabs=visual-studio#app-configuration)
=> Win service needs to set ContentRootPath

aspnetcore/blazor/fundamentals/routing.md
Fixes #26903
Thanks @Michael-Ziluck! :rocket:
=> Update example code

aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/Error.cshtml, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/Error.cshtml.cs, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/Index.cshtml, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/Index.cshtml.cs, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/Shared/_Layout.cshtml, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/_ViewImports.cshtml, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Pages/_ViewStart.cshtml, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Program.cs, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/README.md, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/SampleApp.csproj, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Services/ServiceA.cs, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/Services/ServiceB.cs, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/appsettings.Development.json, aspnetcore/host-and-deploy/windows-service/samples/7.x/WebAppServiceSample/appsettings.json
=> prep for 7.0 changes in Windows Service

aspnetcore/blazor/performance.md
Fixes #25822
Thanks @SQL-MisterMagoo! :rocket: ... If you would like to review these updates, please don't delay. I'm trying to keep the PRs rolling in to avoid **_merge conflicts_** 💥😈 while preview .NET 7 content is rolling out quickly. We'll make this update for 6.0 or later, so you'll see two sections updated the same way.
=> Update render fragment guidance

.repoman.yml
🤔 ... If it doesn't work out and the whole repo crashes, I could always go back and play for the Celtics again! 🤣
=> Test automatic assignment for new Blazor issues

.repoman.yml
@Rick-Anderson ... Since we know it works now, I expand it to the other entries for Blazor articles.
Wow! This works better than the ... *cough cough* ... **Artemis 🚀** ... *cough*. 🤣
**_GO Rocket Lab!_**
=> Include assignment for addl Blazor entries

aspnetcore/blazor/forms-and-input-components.md
Fixes #26939
Thanks @Michael-Ziluck! :rocket:
=> Add namespace

aspnetcore/blazor/fundamentals/routing.md
=> Routing features (loc changes, NavigationLock)

aspnetcore/fundamentals/error-handling.md, aspnetcore/web-api/handle-errors.md
=> moniker prep

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/tutorials/signalr-blazor.md
=> Disable response compression for Hot Reload

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/web-api/index.md
Contributes to #26540
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26897#parameter-binding-for-argument-lists)
=> Min API param binding with record /1

aspnetcore/blazor/file-uploads.md
=> Controller purpose/location clarification

aspnetcore/blazor/call-web-api.md
Fixes #26995
Thanks @Michael-Ziluck! 🚀 ... I had a few minutes to work on this right now. This will preserve the H2s because I'd like to keep these sections showing up in the sidebar ToC. H3s don't appear there.
=> Named and typed HttpClient improvements

aspnetcore/fundamentals/error-handling.md
Fixes https://github.com/dotnet/aspnetcore/issues/43870
=> Clarify behaviour of developer exception page

aspnetcore/blazor/hybrid/security/index.md, aspnetcore/blazor/security/server/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md
=> Auth State Provider registration change

aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/aspnetcore/sample-6/Program.cs
Internal preview: https://review.docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&branch=pr-en-us-27022
=> Update grpc/aspnetcore with modern startup code

aspnetcore/grpc/grpcweb.md
=> "RequiresCors" method should be "RequireCord"

aspnetcore/toc.yml
=> add scaling Azure to TOC

aspnetcore/blazor/components/index.md
Fixes  #27055
Thanks @SQL-MisterMagoo! 🎷 ... I'll hold here for your feedback on the updates. I tried to steer it a bit more in the 'it may be required for you to control it' direction.
Also note that this is kind'a *draft-y-ish* at the moment. I need to run out for a couple of hours. I'll give it another 👁️ when I get back to perhaps provide further polish.
=> Improve section leading paragraphs

aspnetcore/toc.yml
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-7.0&branch=pr-en-us-27074)
Just moved one test and added a TOC entry to the other so you could see all the unit/int testing together.
=> unifiy testing in TOC /1

aspnetcore/includes/integrationTests.md, aspnetcore/test/integration-tests.md
=> Refactor integration tests /4

aspnetcore/blazor/host-and-deploy/server.md
Fixes #27087
Initial draft to generate a preview
=> Scalable blazor updates

aspnetcore/diagnostics/asp0008.md, aspnetcore/diagnostics/asp0009.md, aspnetcore/diagnostics/asp0010.md, aspnetcore/diagnostics/code-analysis.md
Add documentation for analyzers in ASP.NET.
Part of #27020
=> Add documentation for ASP0008-10

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Addresses #27036
@omuleanu ... I'm going to work on this in three steps. I had a few minutes here to knock out the easy cases for example components 2 and 3 ... and one here that's inlined into the topic's content.  I've already made updates to the `dotnet/blazor-samples` repo on https://github.com/dotnet/blazor-samples/pull/42. Components 4 and 5 still need to be addressed, and I'll work on updating those tomorrow. After that, I'll put the line highlights back on the code links. It was best to knock those out here while I update a lot of code. It's not so many components ... just four ... it's that there are also **_4 release versions_** and **_2 hosting models_** of snippet sample apps. It's a bit of work 😅 to get them all updated.
=> Update JS interop examples (Part 1)

aspnetcore/diagnostics/asp0003.md, aspnetcore/diagnostics/asp0004.md, aspnetcore/diagnostics/asp0005.md, aspnetcore/diagnostics/asp0006.md, aspnetcore/diagnostics/asp0007.md, aspnetcore/diagnostics/asp0008.md, aspnetcore/diagnostics/asp0009.md, aspnetcore/diagnostics/asp0010.md, aspnetcore/diagnostics/asp0011.md, aspnetcore/diagnostics/asp0012.md, aspnetcore/diagnostics/asp0013.md, aspnetcore/diagnostics/asp0014.md, aspnetcore/diagnostics/code-analysis.md
=> Add docs for analyzers ASP0011-14

aspnetcore/fundamentals/minimal-apis/min-api-filters.md, aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/todo/Program.cs
Review link: https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-7.0&branch=pr-en-us-27106
=> Update minimal API filter docs to reflect latest changes

aspnetcore/includes/net-prereqs-mac-7.0.md, aspnetcore/includes/net-prereqs-vs-7.0.md, aspnetcore/includes/net-prereqs-vsc-7.0.md, aspnetcore/migration/60-70.md, aspnetcore/toc.yml
~Fixes~ contributes to #26800 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&branch=pr-en-us-27102)
=> WIP: Migrate 6 to 7

aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #27069
Thanks @mrpmorris! ... This has a chance to cover ALL of the bases that could interfere with a custom `web.config` ... either not generating the file in the first place (standalone WASM), not placing a custom file where they want it, or messing with the dev's custom file. If you want to look 👀, please look *quickly* 🏃 because I need to get this in 🏎️ *FAST* 🏎️. I'm ⛰️⛏️😅 on a number of issues right now 🏃 🏃🏃🏃🏃🏃😅.
=> Beef up custom web.config content

aspnetcore/host-and-deploy/proxy-load-balancer.md
Fixes #27129
Thanks @Otto404! :rocket:
Rick ... I have a little time here while I wait on the PU to provide some Blazor feedback elsewhere, so I tossed this up in case this is the right way to go. If not, please close.
btw -- The YARP docs have everything AFAICT ... ASP.NET Core+.NET config guidance all covered. I think we only need a cross-link and can let their docs cover their scenarios.
=> Add a YARP additional resource cross-link

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
=> Update JS interop examples (Part 2)

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
=> Update JS interop examples (Part 3)

aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/graph-api.md, aspnetcore/blazor/security/webassembly/index.md
=> Update Navigation Manager naming

aspnetcore/fundamentals/app-state.md
For https://github.com/dotnet/aspnetcore/issues/37978
=> Clarify that cookieless session is insecure

aspnetcore/fundamentals/minimal-apis/test-min-api.md
Contributes to #26352
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/test-min-api?view=aspnetcore-7.0&branch=pr-en-us-27116)
[test project](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample)
=> Min API unit and integration testing

aspnetcore/toc.yml
=> min api tests toc

aspnetcore/blazor/components/lifecycle.md
=> Cross-link reference source

aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/security/includes/troubleshoot-60-or-earlier.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
=> Blazor auth logging 7.0

aspnetcore/grpc/troubleshoot.md
[EDIT by guardrex to add the "fixes" ... note @lucasmaj that this will auto-close the issue when the PR merges.]
Fixes #27140
[Internal doc build review](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0&branch=pr-en-us-27174)
=> Third-party tools with subdomain hosting

aspnetcore/whats-new/dotnet-AspNetCore.Docs-2022-09-01.md, aspnetcore/whats-new/index.yml, aspnetcore/whats-new/toc.yml
=> What's new for Oct 22

aspnetcore/security/key-vault-configuration.md
=> Update Key Vault configuration provider docs

aspnetcore/security/data-protection/extensibility/core-crypto.md, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md
=> [Bulk]MS-09-04-AspNetCore-fixes

aspnetcore/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps.md
Technically, this is KQL. And it doesn't look like it's getting syntax highlighted as SQL anyway.
=> SQL -> KQL

aspnetcore/fundamentals/http-context.md, aspnetcore/fundamentals/use-http-context.md, aspnetcore/fundamentals/use-http-context/samples/Program.cs, aspnetcore/toc.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/27184
Fixes https://github.com/dotnet/aspnetcore/issues/26509
Internal preview: https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-7.0&branch=pr-en-us-27183
=> HttpContext fundamentals documentation

aspnetcore/fundamentals/use-http-context/samples/Program.cs
=> Fix snippets to keep @blowDart not red faced

aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md
=> .net6 and vs2022 fixes as per #25341

aspnetcore/test/integration-tests.md
=> update monikers for integration tests

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/virtualization.md
Fixed some typo and word spelling.
=> Fix typo and spelling

README.md
=> Broken link update

aspnetcore/index.yml
Fixes broken link i found on the main ASP.NET documentation
=> Fix broken link in index page on ASP.NET documentation

aspnetcore/blazor/fundamentals/index.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/host-and-deploy/configure-trimmer.md
Fixed word spelling and typos.
=> Spelling correction.

aspnetcore/grpc/retries.md
Fixes https://github.com/grpc/grpc-dotnet/issues/1904
=> gRPC retry metadata

aspnetcore/security/authorization/simple.md
=> Fixed plural typo

aspnetcore/security/docker-https.md
=> Full path to certificate for windows container

aspnetcore/fundamentals/minimal-apis/openapi.md
Part of https://github.com/dotnet/aspnetcore/issues/44257.
Review: https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0&branch=pr-en-us-27181
=> Update documentation for OpenAPI in minimal APIs

aspnetcore/web-api/handle-errors.md
=> IProblemDetailsWriter

aspnetcore/fundamentals/use-http-context/samples/Program.cs
=> Fix property name: User.Identify > User.Identity

aspnetcore/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps.md
=> initial commit

aspnetcore/blazor/fundamentals/logging.md
=> Blazor WASM auth logging updates

aspnetcore/blazor/fundamentals/logging.md
*Oooops!* ... going a bit too fast here! 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️
=> Spelling error

aspnetcore/blazor/fundamentals/configuration.md
=> Clarify WASM logging configuration

aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/basics.md, aspnetcore/grpc/configuration.md, aspnetcore/grpc/index.md, aspnetcore/grpc/troubleshoot.md, aspnetcore/includes/gRPCazure.md, aspnetcore/tutorials/grpc/grpc-start.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/27270
=> Remove gRPC Azure warnings

aspnetcore/performance/rate-limit.md
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0&branch=pr-en-us-27294#enableratelimiting-and-disableratelimiting-attributes)
=> update rate limiting /1

aspnetcore/host-and-deploy/health-checks.md, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Extensions/SampleHealthCheckBuilderExtensions.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthCheckPublishers/SampleHealthCheckPublisher.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthChecks/SampleHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthChecks/SampleHealthCheckWithArgs.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthChecks/SampleHealthCheckWithDI.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthChecks/StartupHealthCheck.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/HealthChecksSample.csproj, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Program.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Services/StartupBackgroundService.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Snippets/Program.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Snippets/SampleDbContext.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/Snippets/SampleHealthCheckOptions.cs, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/appsettings.Development.json, aspnetcore/host-and-deploy/health-checks/samples/7.x/HealthChecksSample/appsettings.json
Fixes #24571 and adds a DI sample to the samples project.
I copied the 6.x samples project to 7.x, updated the project to .NET 7, and added the new sample snippets.
@Rick-Anderson I also added a small section to the docs markdown to explain the usage of D. I Hope I did that right.
=> Health Check sample using Dependency Injection

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Addresses #27320
Let's comment-out the offending guidance until we work out what to say on the issue.
=> Temporarily address Blazor SignalR guidance

aspnetcore/fundamentals/middleware/index.md, aspnetcore/fundamentals/minimal-apis/middleware.md
Part of https://github.com/dotnet/aspnetcore/issues/44259
Not linked to anywhere yet since it's not clear how all the new docs will be stitched together yet.
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-7.0&branch=pr-en-us-27283)
=> Document middlware with minimal APIs

aspnetcore/tutorials/first-web-api.md
=> moniker prep for Web API

aspnetcore/release-notes/aspnetcore-7.0.md
[Internal Review - gRPC Transcoding section](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-27331#json-transcoding)
Contributes to #26477 
Added mention of OpenAPI support as sub item to gRPC JSON Transcoding section.
=> Added mention of OpenAPI support for gRPC JSON Transcoding

aspnetcore/toc.yml
* [first](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-7.0&branch=pr-en-us-27328)
=> Middleware API to TOC

aspnetcore/blazor/security/server/threat-mitigation.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixed some spelling in documentation.
=> Spelling Correction

.repoman.yml
@pavelsavara ... This *should* 🤞 fix that assignment problem. I forgot that we ***both*** need to be listed here.
After this merges and merges to live, I'll run a test by opening a new issue from the topic to see if we both get assigned to it.
=> Add Pavel to the Client-side JS interop article

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/SeedData.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Program.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/ProgramSeed.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/RazorPagesMovie.csproj, aspnetcore/tutorials/razor-pages/sql.md
=> RP part 4 for .NET 7 /2

aspnetcore/blazor/hybrid/security/index.md
Fixes #27404
Thanks @hgirma! 🚀
=> Cross-link MAUI resources

aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/todo/Program.cs
It appears the wrong variable was used here. `tdparam` is declared elsewhere in the code. I believe IsValid should be using `todoParam` that is mentioned in the line above it.
=> Fix variable name typo

aspnetcore/security/authentication/add-user-data.md
Adds missing highlighting from sample code for section `Update the Account/Register.cshtml page`
=> Update add-user-data.md fixes highlighting

aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample7/Pages/Movies/Edit.cshtml.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample7/Pages/Movies/IndexClean.cshtml.cs
Contributes to #27365
https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0&branch=pr-en-us-27409
=> Update RP part 5 for .NET 7 /2

aspnetcore/mvc/models/validation.md
Add the missing "the" to the link
=> Fix invalid anchor link

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Pages/Movies/Index.cshtml, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Pages/Movies/Index.cshtml.cs, aspnetcore/tutorials/razor-pages/search.md
Contributes to #27365
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-7.0&branch=pr-en-us-27426)
=> Part 6 RP .NET 7 refresh /2

aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md
=> SignalR-Blazor client logging enhancements

aspnetcore/diagnostics/asp0006.md
=> Fix string literals

aspnetcore/mvc/advanced/custom-model-binding.md, aspnetcore/mvc/models/model-binding.md
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-7.0&branch=pr-en-us-27415#model-binding-simple-and-complex-types)
Replaces PR #26975
=> Define simple and complex types

aspnetcore/security/authentication/2fa.md, aspnetcore/security/authentication/certauth.md, aspnetcore/security/authentication/claims.md, aspnetcore/security/authentication/mfa.md
Extra spacing removed and "negotiation" spelling correction
=> removed extra spacing

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Migrations/20221031235618_New_DataAnnotations.Designer.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Migrations/20221031235618_New_DataAnnotations.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateRating.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateRatingDAmult.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Pages/Movies/Create.cshtml.cs, aspnetcore/tutorials/razor-pages/validation.md
=> .NET 7 RP intro part 8 /2

aspnetcore/fundamentals/logging/index/samples/3.x/TodoApiDTO/Controllers/TestController.cs
Similar to:
https://github.com/dotnet/docs/pull/32076
=> Update scope example to use KVP instead of string

aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateFixed.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateRatingDA.cs, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie70/Models/MovieDateRatingDAmult.cs
=> clean up snippet

aspnetcore/blazor/state-management.md
Fixes #27296
Thanks @lonix1! :rocket:
We'll do this for now. If Steve, another PU member, or management comes along to say that the PU is receiving multiple requests for more information/examples on browser storage for WASM, then they'll probably write something up for it and provide it to me for publication.
=> Cross-link cascading values/params topic

aspnetcore/blazor/includes/state-container.md, aspnetcore/blazor/state-management.md
Addresses #27296
@lonix1 @ShaunCurtis ... I thought about this a bit more at the gym 🏋️🏃, and I'm touching it again for some further enhancements ...
* The in-memory state provider INCLUDE should mention that the approach is generalized without a persistent state storage solution.
* I create an *Additional approaches* section in the *State management (WASM)" topic for the bit on using cascading values/params with the link to the issue.
This should tie things over to 2023 when I speak with Dan and Artak about it further. It will remain tracked by my issue so that I don't forget.
=> Further updates for state management

aspnetcore/whats-new/dotnet-AspNetCore.Docs-2022-10-01.md, aspnetcore/whats-new/index.yml, aspnetcore/whats-new/toc.yml
=> What's new Oct 22

aspnetcore/tutorials/razor-pages/new-field.md
=> Minor snip fix

aspnetcore/release-notes/aspnetcore-7.0.md
I'd like to start including features added to grpc-dotnet to release notes. This PR has the two areas I think should be highlighted in the release notes.
Internal preview: https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-27454#grpc
=> Add extra gRPC features to .NET 7 release notes

aspnetcore/blazor/javascript-interoperability/import-export-interop.md
=> Change title

aspnetcore/security/authorization/limitingidentitybyscheme/samples/AuthScheme/Program.cs
=> Code cleanup: remove duplicated semicolons.

aspnetcore/tutorials/first-web-api.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&branch=pr-en-us-27363&tabs=visual-studio-mac)
Fixes #27334
=> .NET 7 MacOS: Tutorial: Create a web API

aspnetcore/fundamentals/minimal-apis/security.md
[Preview View](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0&branch=pr-en-us-27356)
=> Add authentication and authorization docs for minimal APIs

aspnetcore/fundamentals/minimal-apis/min-api-filters.md, aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/Filters/Program.cs, aspnetcore/mvc/controllers/filters.md
Preview 1: https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-7.0&branch=pr-en-us-27481
Preview 2: https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?branch=pr-en-us-27481&view=aspnetcore-7.0#register-a-filter-on-controller-actions
=> Add reference to endpoint filters from MVC filters

aspnetcore/release-notes/aspnetcore-7.0.md, aspnetcore/release-notes/sample/Program7.cs
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-27482#http3-improvements)
=> What's new HTTP/3

aspnetcore/blazor/hybrid/security/index.md, aspnetcore/blazor/hybrid/static-files.md
=> Add Blazor Hybrid API doc links

aspnetcore/fundamentals/routing/samples/6.x/RoutingSample/Snippets/Controllers/WidgetController.cs
=> Ra widget/anton

aspnetcore/blazor/components/index.md
Fixes #27337
I'm drafting some kind of content here for this ... *crappy content*??! 🙈😄. This is just to get the ball rolling with some ideas.
=> Document IComponent

aspnetcore/fundamentals/minimal-apis/handle-errrors.md, aspnetcore/fundamentals/minimal-apis/min-api-filters.md, aspnetcore/fundamentals/minimal-apis/openapi.md, aspnetcore/fundamentals/minimal-apis/responses.md, aspnetcore/fundamentals/minimal-apis/security.md, aspnetcore/fundamentals/minimal-apis/test-min-api.md, aspnetcore/toc.yml
Fixes #27379
[Internal review URL](https://buildapi.docs.microsoft.com/Output/PullRequest/332f35cd-658d-4914-0f85-907e40ee89f0/202211040233047417-27496/BuildReport?accessString=0c960d6c1567ab36bc48d70dc422c1097c81fda88b1397a3f7359ada661389c6)
=> Add min API auth to TOC /1

aspnetcore/fundamentals/servers/kestrel/http3.md
=> moniker prep HTTP/3

aspnetcore/razor-pages/ui-class.md
Fixes #27509
Thanks @StevenTCramer! 🚀
=> Add instruction to TS integration guidance

aspnetcore/release-notes/aspnetcore-7.0.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26687
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0&branch=pr-en-us-27522#new-httpresult-interfaces)
=> New HttpResult interfaces in What's new

aspnetcore/fundamentals/minimal-apis/responses.md
Fixes https://github.com/dotnet/AspNetCore.Docs/pull/27520#discussion_r1015873406
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-7.0&branch=pr-en-us-27525#httpresult-interfaces)
=> Add link to filters doc

aspnetcore/performance/caching/overview.md
=> Add .NET 6 and earlier moniker block

aspnetcore/blazor/components/virtualization.md
Fixes #27537
Thanks @richward1! :rocket: ... The full overhaul of this article with ***fully-working, cut-'n-paste examples*** should occur in 23Q1 🤞🍀.
=> Improve example

aspnetcore/blazor/fundamentals/startup.md
=> Add a load progress example

aspnetcore/security/authentication/accconfirm.md
Fixes a small typo "marked a spam" to "marked as spam"
=> Fix typo "marked a spam" to "marked as spam"

aspnetcore/fundamentals/servers/kestrel/http3.md, aspnetcore/host-and-deploy/iis/http3.md
Fixes #27004 Fixes #27504
[Kestrel Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-7.0&branch=pr-en-us-27503)
[IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/http3?view=aspnetcore-7.0&branch=pr-en-us-27503)
=> HTTP/3 on Kestrel and IIS /1

aspnetcore/toc.yml
contributes to #27550
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-7.0&branch=pr-en-us-27549)
=> Test Debug Trouble TOC /1

aspnetcore/toc.yml
Fixes #27550 
Also contributes to #27477 (adds displayName for caching articles)
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-7.0&branch=pr-en-us-27561)
=> Rearrange testing section of toc

aspnetcore/blazor/security/includes/redirecttologin-component.md
Follow up to https://github.com/dotnet/aspnetcore/issues/44973#issuecomment-1309211993.
=> Update for ASP.NET Core 7.0

aspnetcore/signalr/hubs.md
Client result is supported in Azure SignalR SDK v1.19.0.
=> Update content about Azure SignalR

aspnetcore/tutorials/razor-pages/razor-pages-start.md
Corrected single letter typo in word Authentication
=> Single typo fix on razor-pages-start.md

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #27552
Thanks @JinShil! 🚀 .... This the content that Steve approved at this time. We'll expand it if devs run into problems from here and require more explanation and a more complete example.
=> JS object and data refs passed to .NET

aspnetcore/blazor/globalization-localization.md
=> Improve cross-links

aspnetcore/test/hot-reload.md
Fixes #27560
This includes some lingo improvements.
* Are the lists correct?
* Is the phrasing good?
=> Blazor Hot Reload 7.0 improvements

aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/Migrations/20221025210428_Initial.cs, aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/MinApiRouteGroupSample.csproj, aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/Program.cs, aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/Todo.cs, aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/TodoDb.cs, aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group/TodoEndpoints.cs, aspnetcore/includes/route-groups.md
[EDIT by guardrex to update the issue link: @sammychinedu2ky, use the format "Fixes {ISSUE NUMBER}" to cross-link an issue for a PR.]
Fixes #27609
`Fix to this issue  -> https://github.com/dotnet/AspNetCore.Docs/issues/27609`
@Rick-Anderson
=> Changetoembed

aspnetcore/blazor/fundamentals/routing.md
Fixes #27635
Thanks @yogyogi! :rocket:
This was the very first .NET 7 bit that I added this year, and I really blew it 🙈😄. Well, things are rough during the preview, and my guessing based on PU PRs doesn't always work out. I'll merge this into the live doc set immediately 🚓🚑🚒.
=> Update navigation loc changing example

aspnetcore/toc.yml
Fixes #27649 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-7.0&branch=pr-en-us-27650)
=> Move What's new in docs to What's new section of toc

aspnetcore/host-and-deploy/index.md
=> Add h3 section "Run the published app locally"

aspnetcore/security/authentication/jwt-authn.md
Updates the correct location of the user-jwts.json file, Fixes #27663
=> Update jwt token data location

.github/workflows/holiday-blazor-comment.yml
I'll disable it until 🦃 Day weekend gets here.
=> Disable Blazor holiday message

aspnetcore/release-notes/aspnetcore-7.0.md
=> Removed not needed with

aspnetcore/performance/caching/output.md
Fixes #27559 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-7.0&branch=pr-en-us-27675)
=> Add info about limits to output caching article

aspnetcore/performance/diagnostic-tools.md
=> Windows and Linux confused, fixes #27710

aspnetcore/test/integration-tests.md
Aligns the name of the scheme in the text with the scheme name in the code
=> Align scheme name with code snippet

aspnetcore/blazor/hybrid/index.md
=> Call out platform-dependent style rendering

aspnetcore/blazor/security/webassembly/index.md
Fixes #27717
Javier, I'm going to put this in and will patch it if needed on your feedback. I'm going for a clean backlog in order to focus on the *Security* node in the holiday period 🦃 to 🎅🎆.
=> Refresh token guidance enhancements

aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs, aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRangeTP.cs, aspnetcore/mvc/models/model-binding.md
=> Update DateRangeTP in [ Bind with TryParse ]

aspnetcore/data/ef-rp/intro.md
See https://github.com/dotnet/EntityFramework.Docs/issues/4109
=> Add note on SqlClient async issues

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #27741
Thanks @edgett! 🚀 
I'm going to go ahead and merge this because I'm trying to clear out the 🦃 holiday backlog quickly to reach a high priority set of security updates for EOY. You can certainly hit me up here with any concerns that you have about the content update. I can apply a patch PR to this if things have gone badly due to my going too *FAST* here 🏃🏃🏃🏃😅.
**UPDATE**: I was going to add the content to the existing NOTE, but there's so much content with all of my add-ons and this is probably a required step in most cases that I feel it should be promoted to regular content at the end of the section.
=> Note file ext change for server static assets

aspnetcore/toc.yml
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?view=aspnetcore-8.0&branch=pr-en-us-27775)
=> Hook up TOC to incremental migration /1

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #27752
Thanks @AlfredBr! 🚀 ... Note in passing that we try to maintain good coverage on Nginx and Apache static file server configuration, but additional configuration might be required. These aren't Microsoft-owned technologies. We recommend consulting their doc sets for full coverage on static file server configuration in addition to what we maintain. That includes [Docker documentation](https://docs.docker.com/) for this scenario.
=> Standalone Blazor WASM with Docker

aspnetcore/security/authentication/identity.md
This article is excellently written. 
It is important to bear in mind that auth is one of the most challenging concepts for developers, particularly with the multitude of technologies and terms. As this is the first time Microsoft Identity Platform is mentioned in this article, I was confused as to whether Microsoft Identity Platform is the same thing as ASP.NET Core Identity. I would suggest that the proposed change makes this much clearer.
=> Rearrange text for clarity

aspnetcore/fundamentals/minimal-apis.md
=> abs path fix

aspnetcore/mvc/models/validation.md, aspnetcore/mvc/models/validation/includes/validation6.md
=> fix monikers /1

aspnetcore/client-side/spa/angular.md
Fixes #27796 
Thanks @AdamJonsson! :rocket:
Rick, you can merge this immediately ... or update directly and merge.
... and btw ... the change of the section heading to drop "etc." doesn't break any bookmarks on the repo.
=> Launch standalone with URLs/HTTPS port

aspnetcore/fundamentals/configuration/index.md
=> json comments /1

aspnetcore/fundamentals/servers/kestrel/endpoints.md
=> Add HTTP/3 to endpoint protocols documentation

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/server.md
Fixes #27768
[Internal Review Topic (links to section)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-8.0&branch=pr-en-us-27781#blazor-server-memory-model)
Javier ...
* It's best if you review this one to correct any inadvertent loss or butchering of concepts during editing 🙈.
* I opened #27780 to track on the memory analyzer tool and will ping you mid-'23 to see about covering it.
🎗️ ~***Duplicate content across versions before merging.***~ 🎗️
***Done!*** 👍
=> Blazor Server memory model

aspnetcore/fundamentals/minimal-apis/overview.md, aspnetcore/toc.yml
Fixes #27600 
Draft of minimal API overview.
***Edit by @Rick-Anderson :***
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/overview?view=aspnetcore-7.0&branch=pr-en-us-27724)
=> Jeremy likness minapi overview

aspnetcore/performance/caching/output.md
=> Add note about IDistributedCache

aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part5/ContosoUniversity/Data/DbInitializer.cs, aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part6/ContosoUniversity/Data/DbInitializer.cs, aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part7/ContosoUniversity/Data/DbInitializer.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Data/DbInitializer.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Data/DbInitializer2.cs
Fix #27743
Fixing not only Part 5 of the [Razor Pages with EF Core Tutorial](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-7.0&tabs=visual-studio#seed-the-database), but also 4 other files using the same code.
=> Database initialization

aspnetcore/security/authentication/claims/sample6/WebRPmapClaims/Program.cs
spacing in code demo fix
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims
=> Fix spacing in code demo Name claim and role claim mapping

aspnetcore/blazor/components/index.md
=> Limitations of Blazor custom elements

aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md, aspnetcore/tutorials/first-mvc-app/adding-model.md, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/razor-pages/model.md
=> Prefer dotnet aspcodegen over dotnet-aspnetcodegen

aspnetcore/migration/inc/overview.md
This is some additional content that should be included in the docs to help customers understand which packages they should use
=> Add information about System.Web adapter packages

aspnetcore/blazor/security/webassembly/graph-api.md
=> Blazor Graph code NIT

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/security/includes/msal-login-mode.md, aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes  #27886
Thanks @gregoryagu! 🎸 ... I think this covers them all, but I'll catch any other ***sneaky gremlins*** 😈 on further sweeps through the security docs. Thanks again for the issue! 🍻
=> Role and policy name conventions

aspnetcore/blazor/security/webassembly/graph-api.md
=> Add a MS Graph sample app cross-link

aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md
Fixes #27118 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?view=aspnetcore-8.0&branch=pr-en-us-27895)
=> Add to the list of attributes for script tag helper

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/migration/60-70.md, aspnetcore/release-notes/aspnetcore-7.0.md
Addresses #27848
I think I'll go with 🎲 ***Javier's Gambit***&trade; 🎲 and just drop in the sample app code. It really does make all of the scenarios dead simple.
=> Blazor bind get/set/after NOTE

aspnetcore/blazor/components/data-binding.md
=> Additional Bind get/set/after updates

aspnetcore/blazor/components/index.md
Fixes #27911
[Internal Review Topic (links to section)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?view=aspnetcore-8.0&branch=pr-en-us-27912#blazor-custom-elements)
=> Update custom elements guidance

aspnetcore/blazor/components/index.md
=> Custom elements updates

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #27891
[Internal Review Topic (links to section)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0&branch=pr-en-us-27897#custom-authentication-request-scenarios)
Updates to the current coverage:
* Adding a full `LoginDisplay` component for ***one example*** here. It helps get the overall impression of how this type of code is organized in a common use case.
* Adding a mention of `TryGetAdditionalParameter`, and I re-organize the three methods at the tops of the subsections.
* I think a *NIT* 😈 came over from the PU (or the 🧀 moved at some point): It's not `login_hint`. I think it should be `loginHint`.
* Move the *Logout with a custom return URL* subsection down under these redirect param subsections.
Looks …
=> Additional guidance on custom parameters

aspnetcore/mvc/views/view-compilation.md
=> Runtime Razor compilation doesn't support implicit usings

aspnetcore/blazor/file-uploads.md
Fixes: https://github.com/dotnet/aspnetcore/issues/27983
Fixes #26276
=> [Blazor] Add image upload preview guidance

aspnetcore/mvc/models/file-uploads.md
=> Small VS Large /2

aspnetcore/includes/IdentityServer4.md
=> Duende IdentityServer  /1

aspnetcore/blazor/components/index.md
=> Custom elements kebab case

aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/security/includes/7.0/troubleshoot.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/index.md
=> Security Overview updates

aspnetcore/security/authentication/scaffold-identity.md
Fixes  #27970
Thanks @gregoryagu! 🚀 ... This cross-link is already here in the preceding sentence, but I'll add it to the class mentions, too, to make sure devs can find these classes.
=> Improve cross-linking

aspnetcore/blazor/index.md
Noticed in passing while working on an unrelated issue.
=> Add link and improve WASM description

aspnetcore/security/docker-compose-https.md
=> Add powershell command /1

aspnetcore/blazor/debug.md
=> [vscode] Clarify that "cwd" property is required when project is not in workspace root

aspnetcore/tutorials/choose-web-ui.md
Fixes #27981
[Internal Review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-8.0&branch=pr-en-us-27985)
Thanks @StingyJack! 🎃 ... but note that the "downsides" that you're asking about in your issue are just the ones for the server-rendered and client-rendered UI sections early in the article, applying to either Blazor Server (server-side UI rendering) or Blazor WebAssembly (client-side UI rendering/SPA). We don't have further "downsides" to call out beyond the ones that are already explained. What I would like to address is the Blazor content, so thanks for your issue on that front. It's been a *loooooong time* 👴 since we worked on the Blazor bit of this doc 😄.
Wade ...
* I focus on Blazor updates using Dan's approved descriptions from the …
=> Improve Blazor coverage

aspnetcore/blazor/fundamentals/signalr.md
Fixes  #27949
Thanks @VorTechS! 🚀
=> Add connection state elements

aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Courses/DepartmentNamePageModel.cs
Fixes #26725 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?branch=pr-en-us-28009#create-a-base-class-for-course-create-and-edit)
=> Replace string arguments with typed parameters

aspnetcore/migration/31-to-50.md, aspnetcore/toc.yml
=> Add Microsoft Identity Web to TOC

aspnetcore/signalr/hubs.md, aspnetcore/signalr/introduction.md, aspnetcore/signalr/troubleshoot.md
=> Link to SIGNALR ON THE WIRE – AN INFORMAL DESCRIPTION OF THE SIGNALR PROTOCOL

aspnetcore/security/enforcing-ssl.md
Fixes #23686 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&branch=pr-en-us-28012&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communication)
=> Warn about some Linux steps not working

aspnetcore/migration/50-to-60.md
=> Migrating SPA apps

aspnetcore/web-api/action-return-types.md
=> update link fragment

aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/SampleApp.csproj
=> Remove dup package ref

aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #27833
Thanks @smiller7812! 🚀 ... I'm going to call out that the dev can check the console to confirm that the solution was started from the **Server** project, and I mention that they should try to refresh their browser.
=> Add troubleshooting guidance

aspnetcore/signalr/redis-backplane.md
Testing for reference: https://github.com/dotnet/aspnetcore/issues/27583#issuecomment-1310746715
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26271
=> Update redis for clustering

aspnetcore/signalr/java-client.md
Closes https://github.com/dotnet/aspnetcore/issues/45315
=> Update Java package version reference

aspnetcore/data/ef-rp/intro/samples/cu50/PaginatedList.cs.txt, aspnetcore/data/ef-rp/intro/samples/cu80/PaginatedList.cs
See #28077
@vanillajonathan we don't have time to test this and update the tutorial with the changes, but we'll consider it when we update this series for .NET 8
cc @tdykstra
=> Proposed new PaginatedList.cs

aspnetcore/blazor/components/data-binding.md
Fixes #28098
Thanks @toddlucas! 🚀 ... I put your fix in, ***and*** I have it update the value of `text` to reflect it in the elements. The component will show the value in the element but not update the underlying value of `text` unless the value is assigned.
I think this is a better example. If you have more feedback on it, please open a new issue for me to work on it further.
=> Fix data binding example

aspnetcore/blazor/components/data-binding.md
=> @bind:{get|set|after} feature NOTE updates

aspnetcore/grpc/configuration/sample/GrcpService/Startup3.cs
fixes #28110 
Typo in Startup3.cs
aspnetcore/grpc/configuration/sample/GrcpService/Startup3.cs
=> gPRC config sample3 fix

aspnetcore/performance/caching/output.md
=> Fix method name

aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/images.md
Fixes #27539
Thanks @WayneAASPLLC! 🚀 ... I think the guidance is located in the right spots. I enhance it a bit here.
=> Lambda expression and loop vars

aspnetcore/web-api/index.md
=> Put 7.0 moniker block first

aspnetcore/performance/response-compression.md
=> Really small typo in update response-compression.md

aspnetcore/fundamentals/error-handling.md
Fixes #22598 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-28141)
=> UseExceptionHandler and UseStatusCodePagesWithReExecute re-execution

aspnetcore/blazor/components/rendering.md
=> Rendering article internal versioning

aspnetcore/blazor/components/control-head-content.md
=> Head content article versioning

aspnetcore/blazor/components/dynamiccomponent.md
=> Dynamic component article versioning

aspnetcore/fundamentals/apis.md, aspnetcore/fundamentals/apis/APIWithControllers/APIWithControllers.csproj, aspnetcore/fundamentals/apis/APIWithControllers/Controllers/WeatherForecastController.cs, aspnetcore/fundamentals/apis/APIWithControllers/Program.cs, aspnetcore/fundamentals/apis/APIWithControllers/WeatherForecast.cs, aspnetcore/fundamentals/apis/APIWithControllers/appsettings.Development.json, aspnetcore/fundamentals/apis/APIWithControllers/appsettings.json, aspnetcore/fundamentals/apis/MinimalAPI/MinimalAPI.csproj, aspnetcore/fundamentals/apis/MinimalAPI/Program.cs, aspnetcore/fundamentals/apis/MinimalAPI/WeatherForecast.cs, aspnetcore/fundamentals/apis/MinimalAPI/appsettings.Development.json, aspnetcore/fundamentals/apis/MinimalAPI/appsettings.json, aspnetcore/toc.yml, aspnetcore/tutorials/first-web-api.md, aspnetcore/tutorials/min-web-api.md
Fixes #28058 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/apis?branch=pr-en-us-28113)
=> APIs TOC work

aspnetcore/blazor/components/index.md
=> Fix for broken no-loc rendering

aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md, aspnetcore/blazor/includes/js-interop/7.0/import-export-interop-mappings.md, aspnetcore/blazor/security/includes/3.1/troubleshoot.md, aspnetcore/blazor/security/includes/5.0/troubleshoot.md, aspnetcore/blazor/security/includes/6.0/troubleshoot.md, aspnetcore/blazor/security/includes/7.0/troubleshoot.md, aspnetcore/blazor/security/includes/authorize-client-app.md, aspnetcore/blazor/security/includes/azure-scope.md, aspnetcore/blazor/security/includes/fetchdata-component.md, aspnetcore/blazor/security/includes/usermanager-signinmanager.md
=> Remove no-loc markdown

aspnetcore/blazor/fundamentals/environments.md
=> Environments article versioning

aspnetcore/performance/ObjectPool.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/26981
=> Object Reuse thread safe /1

aspnetcore/fundamentals/dependency-injection.md
Corrected the links for the following
- (generic) open types
- (generic) constructed type.
=> corrected links to other documentation

aspnetcore/razor-pages/web-sdk.md
=> Update SDK.Web doc with monikers

aspnetcore/blazor/file-uploads.md
=> File uploads article versioning

aspnetcore/blazor/file-downloads.md
=> File downloads article versioning

aspnetcore/blazor/hosting-models.md
=> Hosting models article versioning

aspnetcore/blazor/project-structure.md
=> Project structure article versioning

aspnetcore/migration/inc/adapters.md
=> Fix trivial typo in adapters.md

aspnetcore/migration/proper-to-2x/includes/index.md, aspnetcore/migration/proper-to-2x/includes/index5.md, aspnetcore/migration/proper-to-2x/index.md
=> Update Migration /8

aspnetcore/blazor/fundamentals/dependency-injection.md
=> DI article versioning

aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/security/server/threat-mitigation.md
=> Handle errors article versioning

aspnetcore/grpc/interprocess-namedpipes.md, aspnetcore/grpc/interprocess-uds.md, aspnetcore/grpc/interprocess.md, aspnetcore/grpc/interprocess/Server-web.csproj, aspnetcore/toc.yml
Internal preview: https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-8.0&branch=pr-en-us-28129
=> Add gRPC IPC named pipes documentation

aspnetcore/includes/http-repl/requires-body-options.md
=> Escape quotes in --content example

aspnetcore/web-api/action-return-types.md
=> Perf of async link

aspnetcore/blazor/fundamentals/logging.md
=> Logging article versioning

aspnetcore/blazor/fundamentals/routing.md
=> Routing article versioning

aspnetcore/blazor/fundamentals/startup.md
=> Startup article versioning

aspnetcore/blazor/hybrid/root-component-parameters.md, aspnetcore/toc.yml
Fixes #28219
[Internal Review Topic](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/root-component-parameters?view=aspnetcore-8.0&branch=pr-en-us-28237)
Thanks @Daeer-Projects! 🚀 ... I'm going to sleep on this 🛌💤 and perform an edit/update pass on Tuesday morning. Since I figured out while writing this up that we don't have a great spot for it in existing docs, I decided to go with a new topic for it. I will ask Dan and Artak tomorrow if they would like to look at it on those grounds ... but also because they may have some ideas to improve the coverage or even ask Tanay/Mackinnion to suggest improvements. There might be some additional angles to cover and ***gotchas*** 😈 to call out.
=> Pass params to the root component article

aspnetcore/blazor/hybrid/root-component-parameters.md
=> Update API doc cross-link layout

aspnetcore/tutorials/min-web-api/samples/7.x/todoGroup/Todo.cs
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&branch=pr-en-us-28264)
Fixes #27898 
Todo class needed to be public to match TodoDTO, so setting it to public to begin with to keep things simple.  Tested it.
=> Create Min API tutorial: Updated Todo class to public since DTO will be public

aspnetcore/blazor/forms-and-input-components.md
=> Blazor forms article versioning

aspnetcore/fundamentals/http-logging/index.md
Address https://github.com/dotnet/aspnetcore/issues/45161
=> Add note about another use case for MediaTypeOptions

aspnetcore/blazor/fundamentals/startup.md
=> Cross-link JS initializer coverage

aspnetcore/razor-pages/web-sdk.md
=> Ref props in Web-SDK /1

aspnetcore/blazor/supported-platforms.md
=> Supported platforms article versioning

aspnetcore/blazor/file-uploads.md
Fixes #28287
Thanks @aldefrawy! 🚀
=> Update upload image preview example

aspnetcore/grpc/interprocess-uds.md, aspnetcore/grpc/interprocess.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-8.0&branch=pr-en-us-28282)
=> Improve guidance for IPC transports, discuss using multiple

aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Addresses #26980
Mackinnon ... thanks (*again!*) for the help. I think this is right ... ***or close to right*** 🙈😄.
=> Patch JS interop article

aspnetcore/tutorials/razor-pages/model.md
Forgot to update the metada date and custom in last merged PR a few minutes ago, so fixing.
=> Fix metadata item in RP series, model.md

aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs
=> Updated GetCompleteTodos to hide secret

aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs
Fixes #28303 
I have just realized that I coded the GetCompleteTodos method and haven't tested it, that explains the endpoint missing. But that will fix it. Thanks for your attention.
=> Added endpoint for complete todos

aspnetcore/blazor/tooling.md
=> Tooling article versioning

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Lazy loading article versioning

aspnetcore/performance/rate-limit.md
Fixes #27443
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0&branch=pr-en-us-28326#create-chained-limiters)
=> Add chained limiter /8

aspnetcore/blazor/globalization-localization.md
=> Cross-link supported WASM API/locales

aspnetcore/host-and-deploy/azure-apps/index.md, aspnetcore/toc.yml
=> Link to Azure SQL tutorial

aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/webassembly-lazy-load-assemblies.md
=> Blazor Security overview updates

aspnetcore/blazor/security/server/index.md, aspnetcore/blazor/tooling.md
=> Blazor Server security overview versioning

aspnetcore/blazor/security/server/additional-scenarios.md
=> Blazor Server security addl scenarios versioning

aspnetcore/includes/SignalR/es6.md, aspnetcore/signalr/client-features.md, aspnetcore/signalr/introduction.md, aspnetcore/signalr/supported-platforms.md
Fixes #24673
**Internal review URLs**
* [client features](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-8.0&branch=pr-en-us-28325#es6)
* [Intro](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-8.0&branch=pr-en-us-28325#es6)
=> ES5 support in SIgnalR /6

aspnetcore/client-side/spa/intro.md
Fixes #28344
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?view=aspnetcore-8.0&branch=pr-en-us-28345#supported-spa-framework-version-in-aspnet-core-spa-templates)
=> SPA updates /8

aspnetcore/tutorials/first-mvc-app/start-mvc.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md
=> Remind to use non minified CSS /8

aspnetcore/fundamentals/localization/sample/6.x/POLocalization/POLocalization.csproj
@hishamco  use the following to auto close on merge
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/18559
=> Update OrchardCore.Localization.Core to 1.5.0

aspnetcore/tutorials/razor-pages/model.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&branch=pr-en-us-28346&tabs=visual-studio-code#add-a-data-model)
fixes #28079 
fixes #27246  (Verifying fixed in the same section I am editing here.)
Verified on VSC and VS for Mac.
=> RazorPages Get Started: Correct Solution Tool reference

aspnetcore/includes/built-in-TH.md
Fixes #14583 
Update the include file to make it consistent with the TOC. The other tasks mentioned in #14583 were addressed by #15725.
=> Add missing tag helper to the list

aspnetcore/test/integration-tests.md
Fixes #28375
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0&branch=pr-en-us-28377)
=> add snippet tag

aspnetcore/host-and-deploy/iis/advanced.md
Fixes #25893 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-8.0&branch=pr-en-us-28374)
=> Document disableRotationOnConfigChange

aspnetcore/blazor/hybrid/routing.md
=> Cross-link PU issue on deep linking support

aspnetcore/fundamentals/portable-object-localization.md
Fix tiny issues in #28376
Fixes #28409
=> Fix hightlight selection in PO localization docs

aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/SampleApp.csproj
Thanks @X-Celcius! 🚀 ... I'll take this to the live doc set very quickly. I'm just waiting on two more PRs to merge so that I can get them live, too.
Package references roll forward for patch releases, but I'll go ahead and call for the latest versions.
=> Return package reference

aspnetcore/security/enforcing-ssl.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/28278
Fixes [#16974](https://github.com/dotnet/AspNetCore.Docs/issues/16974)
<html>
<body>
[aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/ra-RHEL/djgalvan/aspnetcore/security/enforcing-ssl.md)	Succeeded	[Internal View](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&branch=pr-en-us-28428)
- unzip
=> Ra rhel/djgalvan

aspnetcore/security/cors.md, aspnetcore/security/cors/includes/cors56.md
=> Moniker Prep for CORS

aspnetcore/fundamentals/minimal-apis/security.md
=> Update security.md: policy name

aspnetcore/blazor/performance.md
=> Peformance article versioning

aspnetcore/signalr/hubcontext.md
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-8.0&branch=pr-en-us-28343#get-an-instance-of-ihubcontext-in-middleware)
Fixes #28081
=> SignalR clarify connectionID access options

aspnetcore/blazor/components/prerendering-and-integration.md
Addresses #28443
Thanks @Krangth! 🚀 ... We'll just make this an "addresses" PR so that your issue will remain open. I suspect that we'll have a follow-up "fixes" PR later based on what the PU ("product unit") comes up with on the PU issue that I opened.
=> Call out a check on the article's version

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #28457
Thanks @timschwallie! 🚀 ... The content was written a long time ago and isn't very helpful in most cases. The Multipart Bundle approach is better, and I cross-link it now. There's more coming on that, too. This has been a hot topic of conversation. The product unit is working on something for .NET 8. See the discussion and community remarks at https://github.com/dotnet/aspnetcore/issues/36978.
WRT disabling compression, I don't think the document necessarily must call out reasons. I suspect one of the few reasons for disabling it is if for some reason it's failing, perhaps temporarily due to factors out of the dev's control, and they need to shut it off. I think the doc just needs to cover how to do it.
=> Update DLL extension change section

aspnetcore/diagnostics/asp0014.md
Close https://github.com/dotnet/AspNetCore.Docs/issues/28364.
=> Update suppression guidance on ASP0014

aspnetcore/blazor/project-structure.md, aspnetcore/blazor/security/content-security-policy.md
=> CSP article versioning and updates

aspnetcore/toc.yml
Followup to #28488 
File Type | File Name | Published Url
-- | -- | --
content | aspnetcore/fundamentals/localization.md | https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-8.0&branch=pr-en-us-28496
=> Split localization followup -- add new articles to toc

aspnetcore/blazor/fundamentals/logging.md
=> Location of SignalR client builder

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
... followup update for #28505.
=> Update WeatherForecast controller

aspnetcore/fundamentals/http-logging/index.md, aspnetcore/fundamentals/middleware/request-response.md
@Rick-Anderson ... These popped up on the `live` build report this morning, and I guessed that I should I rotate you in for Justin.
=> Change author in metadata

aspnetcore/test/dev-tunnels.md
=> Dev tunnels in VS GA

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
=> Hosted Blazor WASM AAD updates

aspnetcore/blazor/security/webassembly/index.md
=> WASM security overview updates

aspnetcore/migration/inc/remote-authentication.md
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?view=aspnetcore-8.0&branch=pr-en-us-28545)
Fixes https://github.com/dotnet/systemweb-adapters/issues/302
Fixes #28547
=> Fix a couple of incorrect APIs for the incremental migration docs

aspnetcore/data/ef-rp/intro/samples/cu/Pages/Departments/Edit.cshtml.cs, aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Departments/Edit.cshtml.cs
=> Fix code style issues

aspnetcore/migration/inc/abtesting.md, aspnetcore/toc.yml
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/abtesting?view=aspnetcore-8.0&branch=pr-en-us-28551)
Fixes #28536
=> A/B Test edit pass /1

aspnetcore/blazor/security/index.md
Fixes  #28530
Thanks @carlsixsmith! 🚀 ... and sorry again for the delay. This cross-state move in Florida has been a killer. I'm finally getting stabilized in my new house here and getting through the backlog from earlier in the week now.
Actually, I don't think we need Mackinnon on this one. This fix seems fairly straightforward to me. How do you like the update on this PR? Is that clear as to what's going on?
=> Fix broken example and add an explanation

aspnetcore/blazor/components/virtualization.md
`ForcecastUpdated` -> `ForecastUpdated`
=> Fix some typos

aspnetcore/blazor/fundamentals/routing.md
Fixes #28587
Thanks @yv989c! 🚀 ... IIRC, that was sent over like that, but shame on me for not spotting it! 🙈 Oh, well! It will be fixed now. Thanks for the shout-out!!!!!
=> Fix example code

aspnetcore/blazor/security/webassembly/index.md, aspnetcore/mvc/views/working-with-forms.md
Add missing property accessor: Change `model.Insert(..)` to `model.Countries.Insert(..)`
Add jump link to section **HTML Helper alternatives to Input Tag Helper**.
Fixes #28525
=> Fix missing property accessor in code and add jump link to section

aspnetcore/tutorials/first-mvc-app/adding-model.md
Fixes #27381
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-8.0&branch=pr-en-us-28636)
=> Remove manual package installations from VS tab

aspnetcore/migration/mvc.md, aspnetcore/migration/mvc/includes/mvc6.md
Fixes #28608
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-8.0&branch=pr-en-us-28625)
I've avoided massive screen shots because the steps are easy to follow and the UI will almost certainly be changing. The UI has multiple changes since your [Dec 2022 blog](https://devblogs.microsoft.com/dotnet/migrating-from-asp-net-to-asp-net-core-part-5/).
=> update how to update MVC legacy to Core

aspnetcore/tutorials/getting-started-with-swashbuckle.md
Fixes #25685
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&branch=pr-en-us-28645)
=> Add note about AddEndpointsApiExplorer

aspnetcore/blazor/components/data-binding.md, aspnetcore/blazor/components/layouts.md, aspnetcore/blazor/debug.md, aspnetcore/blazor/hybrid/security/security-considerations.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/migration/60-70.md, aspnetcore/release-notes/aspnetcore-7.0.md
=> Layouts versioning

aspnetcore/performance/caching/response.md
=> Remove outdated note about output caching

aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
|:--|:--|
| _aspnetcore/blazor/security/webassembly/additional-scenarios.md_ | [Preview: aspnetcore/blazor/security/webassembly/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-28672) |
| _aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md_ | [Preview: aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?branch=pr-en-us-28672) |
| _aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md_ | [Preview: …
=> Blazor WASM MS accts updates

aspnetcore/test/integration-tests.md
Fixes #28676 
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/c6d84c6661c6ff5e8a04c3f6c9d4786776948f3d/aspnetcore/test/integration-tests.md) | [aspnetcore/test/integration-tests](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-28689) |
=> Remove duplicate snippet

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/c35551c53d1c1b386574fa42fa934b380c2bf0c6/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-28684) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/c35551c53d1c1b386574fa42fa934b380c2bf0c6/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md) | …
=> Blazor standalone WASM auth updates

aspnetcore/host-and-deploy/windows-service.md
Fixes #28638 
|:--|:--|
| [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/75f13cc5e88a3c5fa2fe1ed4e62ad6353f979965/aspnetcore/host-and-deploy/windows-service.md) | [aspnetcore/host-and-deploy/windows-service](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?branch=pr-en-us-28686) |
=> Install Microsoft.Extensions.Hosting.WindowsServices NuGet package

aspnetcore/includes/kerberos.md
Adding references to other Microsoft articles on gMSA.
Fixes #28365
=> review mid March: Update kerberos.md

aspnetcore/performance/caching/distributed.md, aspnetcore/performance/caching/distributed/includes/distributed5.md
Fixes #28698
|:--|:--|
| [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a07010ffdeb1e7ac389eabaa551a7fa78c0073c/aspnetcore/performance/caching/distributed.md) | [aspnetcore/performance/caching/distributed](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?branch=pr-en-us-28700) |
=> REddis best /1

aspnetcore/razor-pages/sdk.md
Fixes #22939 
---
|:--|:--|
| [aspnetcore/razor-pages/sdk.md](https://github.com/dotnet/AspNetCore.Docs/blob/24fb58e5c8fe3cc57d4c6268486ad1818d358859/aspnetcore/razor-pages/sdk.md) | [aspnetcore/razor-pages/sdk](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?branch=pr-en-us-28707) |
=> Document UseRazorSourceGenerator

aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/fundamentals/servers/httpsys/includes/httpsys5-7.md
Fixes #28709 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/a8b27bba2201725d9408aa4e622fdb1dc95be3ef/aspnetcore/fundamentals/servers/httpsys.md) | [aspnetcore/fundamentals/servers/httpsys](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?branch=pr-en-us-28712) |
=> Fix snippet links

aspnetcore/blazor/call-web-api.md
Fixes #28724
The project template included the package reference for 3.1/5.0, so I'll go with 'confirm or add' for 3.1 and 5.0.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/d7e9ce3d68a1e01883ec6aa96290c66029147cd9/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-28727) |
=> Update System.Net.Http.Json package info

aspnetcore/security/authentication/windowsauth.md, aspnetcore/security/authentication/windowsauth/6.0samples/WebRPwinAuth/Program.cs
Fixes #28365
The PR explains how to determine if Kerberos or NTLM is being used.
- unzip
[Internal URL](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-8.0&branch=pr-en-us-28713&tabs=visual-studio#kerberos-vs-ntlm)
2nd pass review `@wfurt | @ShreyasJejurkar | ` 
---
|:--|:--|
| [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/8ee6cf9133566cc1ca082be5d00866d90cff3b5a/aspnetcore/security/authentication/windowsauth.md) | …
=> Kerberos /8

aspnetcore/fundamentals/host/hosted-services.md, aspnetcore/fundamentals/host/hosted-services/includes/hosted-services5.md
Contributes to #28533
---
|:--|:--|
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/910aa74e2bebee9209a3867035480c5cbb050891/aspnetcore/fundamentals/host/hosted-services.md) | [aspnetcore/fundamentals/host/hosted-services](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-28734) |
=> prep for async background task

aspnetcore/fundamentals/host/hosted-services.md
Fixes #28533
---
|:--|:--|
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/0866f8ac035e45faf290f70cffadbcb1fb601286/aspnetcore/fundamentals/host/hosted-services.md) | [aspnetcore/fundamentals/host/hosted-services](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-28738) |
=> add sample

aspnetcore/fundamentals/routing.md
Fix some minor typos
---
|:--|:--|
| [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a10586573b9a653983446f3a0783475dce55095/aspnetcore/fundamentals/routing.md) | [aspnetcore/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-28748) |
=> Fix minor typos

aspnetcore/blazor/security/includes/imports-hosted.razor, aspnetcore/blazor/security/includes/logindisplay-component.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/0d29ddabdbd2059dc0a31c3b567639b54269304b/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-28718) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/0d29ddabdbd2059dc0a31c3b567639b54269304b/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md) | …
=> Blazor hosted WASM with IdS updates

aspnetcore/security/cors.md, aspnetcore/security/cors/includes/cors7.md
Contributes to #28420
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a13aa747b043bd880024ea6665c78a042f0c11f/aspnetcore/security/cors.md) | [aspnetcore/security/cors](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-28761) |
=> prep for CORS .NET 8

aspnetcore/fundamentals/routing.md, aspnetcore/mvc/controllers/routing.md
This replicates the changes from https://github.com/dotnet/AspNetCore.Docs/pull/28750 and https://github.com/dotnet/AspNetCore.Docs/pull/28748 to older version of the doc. 
---
|:--|:--|
| [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/9c5d7a5853dfd6c917a46d588513747c1d86d24a/aspnetcore/fundamentals/routing.md) | [aspnetcore/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-28760) |
| [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/9c5d7a5853dfd6c917a46d588513747c1d86d24a/aspnetcore/mvc/controllers/routing.md) | [aspnetcore/mvc/controllers/routing](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?br …
=> Fix typos and formatting (for older version of the doc)

aspnetcore/security/cors.md, aspnetcore/security/cors/8.0sample/Cors/Web2API/Controllers/TodoItems2Controller.cs, aspnetcore/security/cors/8.0sample/Cors/Web2API/Program.cs, aspnetcore/security/cors/includes/cors7.md
Fixes #28420
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/6429f016b5966da58380a5598f360a063a786457/aspnetcore/security/cors.md) | [aspnetcore/security/cors](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-28763) |
=> CORs in 7.0 preflight /3

aspnetcore/razor-pages/index.md, aspnetcore/razor-pages/index/includes/index35.md
Contributes to  #28456
---
|:--|:--|
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9c4eeec73f1bce28008d2aab81fa65e38d8c19ab/aspnetcore/razor-pages/index.md) | [aspnetcore/razor-pages/index](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-28770) |
=> JS colocation /3

aspnetcore/security/authentication/accconfirm.md
---
|:--|:--|
| [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/d396988ee2cbc0f10d3132a12f009a78d41e0fda/aspnetcore/security/authentication/accconfirm.md) | [aspnetcore/security/authentication/accconfirm](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?branch=pr-en-us-28773) |
=> Fix typo in Account confirmation docs

aspnetcore/blazor/globalization-localization.md
Fixes #28777
Thanks @Flachdachs! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/843c7c37db155e58a57125673e3405ea82091d38/aspnetcore/blazor/globalization-localization.md) | [aspnetcore/blazor/globalization-localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-28778) |
=> Clarify article pivots to readers

aspnetcore/tutorials/first-mongo-app.md
Fixes #28372 
- Corrected the version 6.0 instructions to run with the currently available version of MongoDB and MongoDB Shell.
- Clarified which commands were to be run at the OS command line and which ones were to be run on the MongoDB Shell.
- Specified the version of MongoDB required by the tutorial
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/02476ba5831ebb48dcbd3bc90c38245b2b00c3f1/aspnetcore/tutorials/first-mongo-app.md) | [aspnetcore/tutorials/first-mongo-app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-28781) |
=> Web API with MongoDB: Corrected instructions for MongoDB and database creation

aspnetcore/diagnostics/asp0020.md, aspnetcore/diagnostics/asp0021.md, aspnetcore/diagnostics/asp0022.md, aspnetcore/toc.yml
Fixes #28742 
Fixes #28744 
Fixes #28745 
---
|:--|:--|
| [aspnetcore/diagnostics/asp0020.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4ed018d5a35b70daa704463cb5a5718a1d5d4af/aspnetcore/diagnostics/asp0020.md) | [aspnetcore/diagnostics/asp0020](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0020?branch=pr-en-us-28791) |
| [aspnetcore/diagnostics/asp0021.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4ed018d5a35b70daa704463cb5a5718a1d5d4af/aspnetcore/diagnostics/asp0021.md) | [aspnetcore/diagnostics/asp0021](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0021?branch=pr-en-us-28791) |
| [aspnetcore/diagnostics/asp0022.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4ed018d5a35b70daa704463cb5a5718a1d5d4af/as …
=> Document ASP0020, ASP0021, ASP0022

aspnetcore/includes/add-EF-NuGet-SQLite-CLI-7.md
Without this tool, the command in part 2 for code generation will fail with the message below
```
To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Tools
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```
---
|:--|:--|
=> Add missing required code generation package

aspnetcore/migration/60-70.md
get rid of shadowing inject property name per https://github.com/dotnet/AspNetCore.Docs/issues/28831
Fixes #28831
---
|:--|:--|
| [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/524cdbf9ae747921dab946a3747567054705568a/aspnetcore/migration/60-70.md) | [aspnetcore/migration/60-70](https://review.learn.microsoft.com/en-us/aspnet/core/migration/60-70?branch=pr-en-us-28834) |
=> get rid of shadowing inject property name per issue #28831

aspnetcore/index.yml
Adding ASP.NET survey to landing page 
@BillWagner
=> add_aspnet_survey

aspnetcore/release-notes/aspnetcore-8.0.md
contributes to #28596
Fixes #28757
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/73beec20aa76c8c8fe8758b9ba6534543a255a81/aspnetcore/release-notes/aspnetcore-8.0.md) | [aspnetcore/release-notes/aspnetcore-8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-28824) |
=> what's new in 8.0  /3

aspnetcore/fundamentals/servers/kestrel/endpoints.md
Fixes #28842 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/c4ebc4b5b452252161469b8ee0ad0406ff54c7ba/aspnetcore/fundamentals/servers/kestrel/endpoints.md) | [aspnetcore/fundamentals/servers/kestrel/endpoints](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?branch=pr-en-us-28843) |
=> Remove false statement about UseUrls method

aspnetcore/mvc/views/view-compilation.md
Fixes #24944 
---
|:--|:--|
| [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/582017a16a531c8dc56d65bda625a52d072fe5fb/aspnetcore/mvc/views/view-compilation.md) | [aspnetcore/mvc/views/view-compilation](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?branch=pr-en-us-28708) |
=> Advise when to use runtime compilation

aspnetcore/tutorials/signalr.md, aspnetcore/tutorials/signalr/includes/signalr3-5.md, aspnetcore/tutorials/signalr/includes/signalr6.md
Fixes #18740 
Added sections:
* Next steps
* Additional resources
I added them in all the earlier versions as well since the issue was originally filed on an early version of the doc.
---
|:--|:--|
| [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdd63a055b4df613f88a086a94b64ae61761df67/aspnetcore/tutorials/signalr.md) | [aspnetcore/tutorials/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?branch=pr-en-us-28849) |
=> SignalR Getting Started: Add next steps & resources

aspnetcore/security/gdpr/includes/gdpr2.md, aspnetcore/security/gdpr/includes/gdpr35.md, aspnetcore/security/gdpr/includes/gdpr6.md
Fixes #28864
---
|:--|:--|
| [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/459f16a322e1a6b9c8f96271cfd088d25f61cf93/aspnetcore/security/gdpr.md) | [aspnetcore/security/gdpr](https://review.learn.microsoft.com/en-us/aspnet/core/security/gdpr?branch=pr-en-us-28870) |
=> fix monikers /3

aspnetcore/blazor/security/webassembly/additional-scenarios.md
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a8231f1309fd9333bf11d9ddc446a1b87c58636/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [aspnetcore/blazor/security/webassembly/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-28857) |
=> Additional scenarios article updates

aspnetcore/fundamentals/static-files.md, aspnetcore/fundamentals/static-files/includes/static-files6.md, aspnetcore/fundamentals/static-files/samples/8.x/StaticFileAuth/appsettings.Development.json
Contributes to #28863
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8edaecaba2fb8e86d473ffea3c4488399896957/aspnetcore/fundamentals/static-files.md) | [aspnetcore/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-28882) |
=> Static files auth path /3

aspnetcore/fundamentals/native-aot.md
After some testing it looks like localization is working fine in ASP.NET Core under AOT.
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/ae1e1fd17b6e171623c87d985519ec8364b0fc5a/aspnetcore/fundamentals/native-aot.md) | [aspnetcore/fundamentals/native-aot](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-28905) |
=> Mark localization as supported in AOT.

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #28906
Thanks @Flachdachs! 🚀 ... As soon as this builds, I'll take the update live. It will appear on the live site within perhaps 20 minutes or so.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/b31d3d238e36e6b1a9f6bfda543956e575dae312/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-28907) |
=> Return missing file to article example

aspnetcore/fundamentals/app-state.md
---
|:--|:--|
| [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/ade0307cfcda4238dec7c07ecada94df424545ff/aspnetcore/fundamentals/app-state.md) | [aspnetcore/fundamentals/app-state](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?branch=pr-en-us-28909) |
=> Fix a typo or two

aspnetcore/fundamentals/static-files.md, aspnetcore/fundamentals/static-files/samples/8.x/StaticFileAuth/Program.cs
Fixes #28863
- unzip
@fiyazbinhasan  please review.
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/b81c0684a5915bf5a2045455689ac546c1fdf0ab/aspnetcore/fundamentals/static-files.md) | [aspnetcore/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-28900&view=aspnetcore-8.0#static-file-authorization) |
=> Static file auth sample /3

aspnetcore/fundamentals/apis.md, aspnetcore/fundamentals/includes/apis6.md
Fixes #28913
See [Minimal APIs now support file upload with IFormFile and IFormFileCollection](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?source=recommendations&view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection)
---
|:--|:--|
| [aspnetcore/fundamentals/apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/4bd1b1a626ec6cf9bce304679a1317ac84a69c02/aspnetcore/fundamentals/apis.md) | [aspnetcore/fundamentals/apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/apis?branch=pr-en-us-28915) |
=> update api limits /3

aspnetcore/getting-started/index.md
Fixes #28943
---
|:--|:--|
| [aspnetcore/getting-started/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/df8902279e49eba5b55017a201cc481804b56894/aspnetcore/getting-started/index.md) | [[Linux](#tab/linux)](https://review.learn.microsoft.com/en-us/aspnet/core/getting-started/index?branch=pr-en-us-28942) |
=> Update the getting started with sdk-7 reference

aspnetcore/fundamentals/minimal-apis/responses.md
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/d25eb6ca881ef9dd5ea4d0b1081db5d0946db0e0/aspnetcore/fundamentals/minimal-apis/responses.md) | [How to create responses in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-28956) |
=> Grammar fixes

aspnetcore/toc.yml
Kestrel is the recommended server. Moved it above IIS in TOC to help hint that it should be considered first.
=> Move Kestrel above IIS in TOC

aspnetcore/fundamentals/best-practices.md, aspnetcore/host-and-deploy/azure-apps/index.md, aspnetcore/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps.md, aspnetcore/includes/reliableWAP.md, aspnetcore/includes/reliableWAP_H2.md, aspnetcore/migration/proper-to-2x/index.md
Fixes #28946
---
|:--|:--|
| [aspnetcore/fundamentals/best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/fc8c1a2cd8924802bf11e2e68a55ba0db4d6499b/aspnetcore/fundamentals/best-practices.md) | [ASP.NET Core Best Practices](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?branch=pr-en-us-28947) |
| [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fc8c1a2cd8924802bf11e2e68a55ba0db4d6499b/aspnetcore/host-and-deploy/azure-apps/index.md) | [[.NET Core CLI](#tab/netcore-cli/)](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?branch=pr-en-us-28947) |
| [aspnetcore/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps.md](https://github.com/ …
=> Reliable web app pattern 3

aspnetcore/blazor/fundamentals/startup.md
Fixes #28903 
Thanks @jan-johansson-mr! :rocket:
I'll ask Mackinnon to review because I'd like to make sure that my explanation in the text is sound.
*Sorry for the churn!* I think it's ready now. ............................ *maybe* 😆.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/41ddfab38c92ccfc5787cd19054d5a89a5db4623/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-28920) |
=> Latest framework approach for boot resource example

aspnetcore/web-api/http-repl/index.md
Fixes #28990 
---
|:--|:--|
| [aspnetcore/web-api/http-repl/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/407368d05bc34a37d5933f8e55ccb6c7b3ea9e5d/aspnetcore/web-api/http-repl/index.md) | [[Windows](#tab/windows)](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/http-repl/index?branch=pr-en-us-28998) |
=> Update path on macOS

aspnetcore/release-notes/aspnetcore-8.0.md, aspnetcore/toc.yml
Fixes #28986
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/1cb5072a3e0608d1d6f4ad5745f9bae8832e278c/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-28987) |
=> What's new in 8.0

aspnetcore/blazor/components/lifecycle.md
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/230ccabb4356cad9b3d5e561c3b337756787e850/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-29022) |
=> Move remark to opening content of article

aspnetcore/fundamentals/native-aot.md
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/a881809f76a420632da676da6acc42388f414502/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29029) |
=> Grammar and typo fixes

aspnetcore/performance/ObjectPool.md, aspnetcore/performance/ObjectPool/ObjectPoolSample8/stub.txt, aspnetcore/performance/ObjectPool/includes/ObjectPool6.md
contributes to #28656
---
|:--|:--|
| [aspnetcore/performance/ObjectPool.md](https://github.com/dotnet/AspNetCore.Docs/blob/482054cc632ce7eb007ce57a96e19a40b6d47004/aspnetcore/performance/ObjectPool.md) | [Object reuse with ObjectPool in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?branch=pr-en-us-29018) |
=> mon prep for objectpool

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
Addresses #29032
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/1951dad344b895f03e727439322990a218a687d8/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-29057) |
=> Remove audience remark

aspnetcore/mvc/controllers/dependency-injection.md
The previous profile link is no longer valid.
---
|:--|:--|
| [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e4076aefa2939e2cc9f89831ddb9bd841abf38a/aspnetcore/mvc/controllers/dependency-injection.md) | [Dependency injection into controllers in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?branch=pr-en-us-29066) |
=> Author profile link renewed

aspnetcore/security/authentication/community.md
Adds [Authentik](https://goauthentik.io) to open source identity providers list. While it is not written in C#, I did not see anything indicating that providers in the list have to be a .net project.
---
|:--|:--|
| [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/243edb317e8e4ab81b91b9c9d21c3074fa1a6255/aspnetcore/security/authentication/community.md) | [Community OSS authentication options for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/community?branch=pr-en-us-29065) |
=> Add Authentik to OSS providers list.

aspnetcore/mvc/controllers/actions.md, aspnetcore/web-api/index.md
Fixes #29069
---
|:--|:--|
| [aspnetcore/mvc/controllers/actions.md](https://github.com/dotnet/AspNetCore.Docs/blob/763316553bd2b64bad550241360cc8a83f57d5f1/aspnetcore/mvc/controllers/actions.md) | [Handle requests with controllers in ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?branch=pr-en-us-29071) |
| [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/763316553bd2b64bad550241360cc8a83f57d5f1/aspnetcore/web-api/index.md) | [Create web APIs with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/index?branch=pr-en-us-29071) |
=> Controller lifetime

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Addresses #29032
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/a5a64486244415b95f6184539e33b51605754704/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [ASP.NET Core Blazor WebAssembly additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-29087) |
=> Followup Blazor security updates

aspnetcore/mvc/advanced/app-parts/3.0sample1/WebAppParts/Startup2.cs
No need to call GetTypeInfo() as Assembly is accessible from the result of typeof(MySharedController)
=> Sample code can be simplified

aspnetcore/mvc/models/validation.md
Fixes #19282
---
|:--|:--|
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/6163d2735699b685dee1a28e4ba1b1c580851765/aspnetcore/mvc/models/validation.md) | [Model validation in ASP.NET Core MVC and Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?branch=pr-en-us-29096) |
=> Add problem details to validation

aspnetcore/blazor/javascript-interoperability/index.md
Fixes #28923
Thanks @Flachdachs! 🚀 
This is just *DRAFT* content at this point for what we'll say. I'm going to ping Dan and Artak to look, and they might have PU engineers remark as well.
I'm not sure if we want to push WebPack or not. That's more of an Artak/Dan/PU call. I defer to them to let me know what additional cross-links to add here.
btw @Flachdachs ... The reason that the content is duplicated in the topic like this is because we were using this form of content management whereby each release the entire document was copied and updated. That was supposed to be a short-term fix until we put a better approach to versioning in place. However, that effort to adopt the new versioning failed. I'm going back to the original form of versioning that doesn't have all of this content …
=> JS interop NPM package and TS for JS interop

aspnetcore/blazor/javascript-interoperability/index.md
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/aebe1032007722833aca556a52f053fb28e4b904/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-29100) |
=> Blazor JS interop overview versioning

aspnetcore/blazor/components/cascading-values-and-parameters.md
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/25950d5e4c4d55df85078ce28777b4ce263787cd/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-29104) |
=> Cascading values and params versioning

aspnetcore/performance/timeouts.md
Contributes to #28934 
---
|:--|:--|
| [aspnetcore/performance/timeouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4af30c1e3d76744636d5e1a34fb60bfa53b2caa/aspnetcore/performance/timeouts.md) | [Request timeouts middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/timeouts?branch=pr-en-us-29114) |
=> Add API ref links

aspnetcore/fundamentals/middleware/index/includes/midpipe-request.md, aspnetcore/fundamentals/minimal-apis/handle-errrors.md, aspnetcore/fundamentals/minimal-apis/handle-errrors/includes/handle-errrors7.md
Fixes #29138
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/handle-errrors.md](https://github.com/dotnet/AspNetCore.Docs/blob/88d844000357fc11153fdd9317bcc032193e9c40/aspnetcore/fundamentals/minimal-apis/handle-errrors.md) | [How to handle errors in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errrors?branch=pr-en-us-29139) |
=> Problem details monikers /8

aspnetcore/fundamentals/error-handling.md, aspnetcore/fundamentals/minimal-apis/handle-errrors.md, aspnetcore/fundamentals/minimal-apis/handle-errrors/sample8/Program.cs
Fixes #28755
[ProblemDetailsService fallback](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errrors?branch=pr-en-us-29140&view=aspnetcore-8.0#problemdetailsservice-fallback)
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/1173d1203d39d2d9c769b1197553145e0dcbcba9/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29140) |
| [aspnetcore/fundamentals/minimal-apis/handle-errrors.md](https://github.com/dotnet/AspNetCore.Docs/blob/1173d1203d39d2d9c769b1197553145e0dcbcba9/aspnetcore/fundamentals/minimal-apis/handle-errrors.md) | [How to handle errors …
=> PD .NET 8 sample /8

aspnetcore/blazor/tutorials/signalr-blazor.md
Addresses #29154
Thanks @weedylan1! 🚀 ... This will simplify the addition of those two lines by referring to their preceding lines in the file and permit the reader to use the built-in code copy button to transfer each of the lines that they need for their sample app experience (if they're building it out while reading down the article).
---
|:--|:--|
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/a044881cdb18089de8650833a4c42d6402600e7a/aspnetcore/blazor/tutorials/signalr-blazor.md) | [Use ASP.NET Core SignalR with Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-29160) |
=> Simplify line addition guidance

aspnetcore/fundamentals/native-aot.md
Fixes #29063
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/ee55aaa2a213dec593cd80d91dedb23a42c0c826/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29162) |
=> API links to AOT /8

aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/ContactsController.cs, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Program.cs, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Views/Shared/_Layout.cshtml
=> Easy test Problem /8

aspnetcore/host-and-deploy/iis/advanced.md
Fixes #29168
Thanks @jguett! :rocket: ... AFAICT, this mirrors what the preceding manual process produces. Thanks for writing in on this doc 🪲.
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/978e5068b2714419cc43a57fa354e6d5c865ad90/aspnetcore/host-and-deploy/iis/advanced.md) | [Advanced configuration of the ASP.NET Core Module and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-29172) |
=> Update ICACLS command

aspnetcore/blazor/security/server/index.md
Should be `AddScoped`
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/61e49372c7529c82d10ed7e285d4f208d6288715/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core Blazor Server apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-29184) |
=> Update index.md for blazor server security

aspnetcore/tutorials/min-web-api.md, aspnetcore/tutorials/min-web-api/includes/min-web-api6-7.md
Fixes #29191 
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/2504297a3e99de4043f5be089f85ddff932c88d4/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-29192) |
=> Set up for 8.0 content

aspnetcore/fundamentals/localization.md
Fixes #29060
@replaysMike please review
[Globalization and localization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?branch=pr-en-us-29178#additional-resources)
---
|:--|:--|
| [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/d7577232e1732b1bed00790dfa720cfd7380649e/aspnetcore/fundamentals/localization.md) | [Globalization and localization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?branch=pr-en-us-29178) |
=> Mini TOC in loc /5

aspnetcore/fundamentals/startup.md, aspnetcore/migration/50-to-60.md
Fixes #29157
cc @ohads-MSFT 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?branch=pr-en-us-29173&view=aspnetcore-7.0#startup-configureservices-and-configure)
---
|:--|:--|
| [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/e67f5f04a0f81d4ee75fa6e89adb9def95d351ce/aspnetcore/fundamentals/startup.md) | [App startup in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?branch=pr-en-us-29173) |
| [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/e67f5f04a0f81d4ee75fa6e89adb9def95d351ce/aspnetcore/migration/50-to-60.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/migr …
=> Add links to Startup.cs /8

aspnetcore/fundamentals/dependency-injection.md, aspnetcore/fundamentals/dependency-injection/samples/6.x/DIsample2/DIsample2/appsettings.Development.json
Fixes #27917 
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/43daa0d80496870da4b665d7bbd677cb94b95b1f/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-29182) |
=> fix: #27917

aspnetcore/fundamentals/localization/make-content-localizable.md, aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/AboutController.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/BookController.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/InfoController.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/ManageController.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/TestController.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/Program.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/SharedResource.cs, aspnetcore/fundamentals/localization/sample/6.x/Localization/ViewModels/Account/RegisterViewModel.cs
Fixes #29179
---
|:--|:--|
| [aspnetcore/fundamentals/localization/make-content-localizable.md](https://github.com/dotnet/AspNetCore.Docs/blob/54bba8a38f7a49889511837b27d41c6401060d8d/aspnetcore/fundamentals/localization/make-content-localizable.md) | [Make an ASP.NET Core app's content localizable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?branch=pr-en-us-29180) |
=> Remove Startup from Loc /2

aspnetcore/mvc/models/validation.md, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Controllers/ContactsController.cs, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Models/Contact.cs
Fixes #29136
---
|:--|:--|
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/112466b3b6e52c76f1639025c170fa6bb4fd4178/aspnetcore/mvc/models/validation.md) | [Model validation in ASP.NET Core MVC and Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?branch=pr-en-us-29202) |
=> Validation Result /2

aspnetcore/mvc/models/validation.md, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Controllers/ContactsController.cs, aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Models/Contact.cs
---
|:--|:--|
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/4d406581c66ab69f29e78551304ad4c8518c5352/aspnetcore/mvc/models/validation.md) | [Model validation in ASP.NET Core MVC and Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?branch=pr-en-us-29203) |
=> Validation result

aspnetcore/blazor/components/index.md
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f73c65fd610cc8ac1b7b4e07782209cedb0fc56/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-29206) |
=> Components overview versioning

aspnetcore/blazor/blazor-server-ef-core.md
---
|:--|:--|
| [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/f83902ce514c79eb7bcd63860cfd6bc582bb9b41/aspnetcore/blazor/blazor-server-ef-core.md) | [ASP.NET Core Blazor Server with Entity Framework Core (EF Core)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?branch=pr-en-us-29207) |
=> Blazor Server EF Core article versioning

aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #28743
This is temporary coverage to tide us over until the SWA docs receive a tutorial. We'll cross-link to that after it appears and shed this detailed coverage, which is ***bound to break at some point*** 💥😈😄.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/f4f7011a7492d511e3bd6829cd852f08c49a0a6e/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-29130) |
=> Add Azure SWA VS deployment

aspnetcore/blazor/fundamentals/signalr.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/52716f72249fdaf1efd683c281cc3cd6927c7937/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-29216) |
=> Remove list formatting (and 🪲)

aspnetcore/tutorials/min-web-api.md, aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs
Fixes #29198 
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/8b6dcc976320f823abfad8b6a139ef44807f44b3/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-29205) |
=> returned a DTO instead of Todo

aspnetcore/fundamentals/servers/index.md
Fixes #29050 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/f283795259dbd9e2c7a32e8af666abde8ff3335a/aspnetcore/fundamentals/servers/index.md) | [Hosting Models](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/index?branch=pr-en-us-29053#hosting-models) |
=> Update Hosting Models section

aspnetcore/toc.yml
Make servers slightly more prominent in TOC by moving it higher.
=> Move Servers TOC item higher

aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/0b43a15fd094c90e1f9da51593b98cd0fa271162/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md) | [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?branch=pr-en-us-29254) |
=> Small language NIT fix

aspnetcore/tutorials/signalr.md
Fixes #29261
Thanks, @aglee! :rocket: ... The team will figure out the best way to address your other issue separately. Let's go ahead and get this NIT 😈 update in now.
---
|:--|:--|
| [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/611a513a59ef9007c6db58c3c98fa9d8e818df6a/aspnetcore/tutorials/signalr.md) | [Customer intent: As a developer, I want to get a quick proof-of-concept app running, so I can get a practical introduction to ASP.NET Core SignalR.](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?branch=pr-en-us-29263) |
=> Update app running instructions

aspnetcore/host-and-deploy/docker/building-net-docker-images.md
Fixes #29276
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/4e673e0b1b7faf9c83b67981b956ce1fd6711f2c/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [Docker images for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-29227) |
=> Add reference to build docker image using dotnet publish

aspnetcore/fundamentals/error-handling.md
Fixes #29259
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/02205ba6f3a3b3cb3da7066b4f2b98d102a45bff/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29306) |
=> Problem details program.cs /5

aspnetcore/blazor/host-and-deploy/index.md
Addresses #28001 
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/a79cebdd996da0ea7563ef3bf7c97af74801af9c/aspnetcore/blazor/host-and-deploy/index.md) | [Host and deploy ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-29271) |
=> Expand lead-in coverage on app base path

aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/host-and-deploy/index.md
* Repair a malfunctioning pivot zone.
* Update a sentence.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/ec515fc4aeccb6dde3440c16a3841b82afdaba2c/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-29319) |
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ec515fc4aeccb6dde3440c16a3841b82afdaba2c/aspnetcore/blazor/host-and-deploy/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-29319) |
=> Follow-up updates

aspnetcore/fundamentals/routing.md, aspnetcore/fundamentals/routing/includes/routing3-7.md, aspnetcore/fundamentals/routing/samples/8.x/OptionalParams/Controllers/MyController.cs, aspnetcore/fundamentals/routing/samples/8.x/OptionalParams/Program.cs, aspnetcore/fundamentals/routing/samples/8.x/OptionalParams/WebApplication1.csproj
Fixes #29313
[Review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-29322&view=aspnetcore-7.0#optional-route-parameter-order)
---
|:--|:--|
| [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/84d3dcaaa8a38f7610a5ac7e5c84b33c682f55c4/aspnetcore/fundamentals/routing.md) | [Routing in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-29322) |
=> Optional route params 2

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md, aspnetcore/fundamentals/minimal-apis/parameter-binding.md, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Iform.csproj, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/appsettings.Development.json, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29286
Fixes #29287
[Review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0&branch=pr-en-us-29312#binding-to-forms-with-iformcollection-iformfile-and-iformfilecollection)
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/ad377a5d318f22b1ced64c4a9846ea0ff6a3cf26/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-29312) |
| [aspnetcore/fundamentals/minimal-apis/parameter-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/ad377a5d318f22b1ced64c4a9846ea0ff6a3cf26/aspnetcore/fundamentals/minimal-apis/parameter- …
=> IForm binding /5

aspnetcore/migration/web_forms.md
Fixing the title and the reference to MVC instead of Web Forms.
There should also be some text in this article about how the .NET Upgrade Assistant isn't going to help you rewrite your web forms pages into MVC views or Razor Pages. The user will have to do that manually.
---
|:--|:--|
| [aspnetcore/migration/web_forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/7cdcc463961234faa6f98a0e4da0ae29943d3df2/aspnetcore/migration/web_forms.md) | [Upgrade an ASP.NET Framework Web Forms app to ASP.NET Core ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/migration/web_forms?branch=pr-en-us-29337) |
=> Fix duplicate text in title

aspnetcore/blazor/debug.md
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/e558dd850a52fda25e16d8deff55e7d94cb2a6f9/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-29342) |
=> Blazor debug versioning update

aspnetcore/blazor/state-management.md
---
|:--|:--|
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/295eedc8a4d1f45085c0267b37944c94f7fc0922/aspnetcore/blazor/state-management.md) | [ASP.NET Core Blazor state management](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/state-management?branch=pr-en-us-29345) |
=> State management article versioning

aspnetcore/blazor/components/element-component-model-relationships.md
Fixes #29350
Thanks, @wenhx! ... I'll have this updated on the live site in just a few minutes! 🚑🚓🚒 
---
|:--|:--|
| [aspnetcore/blazor/components/element-component-model-relationships.md](https://github.com/dotnet/AspNetCore.Docs/blob/a37f7bbcf53c848a917e579734cc9132596fb4f7/aspnetcore/blazor/components/element-component-model-relationships.md) | [Retain element, component, and model relationships in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?branch=pr-en-us-29351) |
=> Update topic links

aspnetcore/blazor/components/layouts.md
Fixes #29354
Thanks again, @wenhx! :rocket:
Two items here:
* Because the updates from 'master' to 'main' are in the samples repo, this will need at least a date update to trigger a rebuild with the new code over there.
* I won't bother with the date because I want to make a 2nd NIT change in an `href` naming for consistency from `episode-main-list` to `main-episode-list`. These aren't really destinations, but I'd like to update them in the samples repo and here in this one line where it appears in the example's rendered markup.
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ff3366d4f8295eff75b532c6354e2ac929be6a5/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor …
=> Update layouts for 'master' switch

aspnetcore/fundamentals/host/hosted-services.md, aspnetcore/fundamentals/host/hosted-services/includes/hosted-services67.md
Fixes #29289
See https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-29349&view=aspnetcore-8.0&tabs=netcore-cli#native-aot
---
|:--|:--|
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/0530c8e13d2c943346fd4badf442fb44e6bd840f/aspnetcore/fundamentals/host/hosted-services.md) | [Background tasks with hosted services in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-29349) |
=> Worker aot /2

aspnetcore/fundamentals/native-aot.md
Fixes #29290
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29348&view=aspnetcore-8.0&tabs=netcore-cli#csb)
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/a9f348e9c353933159f32f3d6add876ab79361bd/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29348) |
=> Reduced size AOT /5

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29365 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/fb276fd4eafefa960e750ef7dc988ae35736eb55/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29368) |
=> Update What's new for HTTP/3 enabled by default

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29371 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf935ec97edb129f24c523c99463df133b063468/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29372) |
=> Add some preview 1 features to what's new

aspnetcore/blazor/hybrid/tutorials/index.md, aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/index.md, aspnetcore/blazor/tutorials/signalr-blazor.md, aspnetcore/toc.yml
Fixes #29380
Thanks @Sudo-Ale! :rocket: ... This isn't what you asked for, but it should clarify the purpose of the tutorials (i.e., 'basic working experience') and call out that the detailed guidance for the technology is in the reference topics.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d61fb5a1cb89ff77712f5004c736bd99ee53ccb/aspnetcore/blazor/hybrid/tutorials/index.md) | [ASP.NET Core Blazor Hybrid tutorials](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/index?branch=pr-en-us-29382) |
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d61fb5a1cb89ff77712f5004c736bd99ee53ccb/aspnetcore/blazor/tutorials/build-a-bl …
=> Improve tutorial lead-in remarks

aspnetcore/blazor/components/templated-components.md
Moving over from #29376.
Thanks @DesuNinshu! :rocket:
---
|:--|:--|
| [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/d59e33e5b9d0fd73652df9b80911a5b5a07637dd/aspnetcore/blazor/components/templated-components.md) | [ASP.NET Core Blazor templated components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?branch=pr-en-us-29385) |
=> Improved the clarity of the description of the article

aspnetcore/blazor/components/class-libraries.md
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/4fcac4c61dea709c96fb214b3257937f8acd17f2/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-29394) |
=> Class libs article versioning

aspnetcore/fundamentals/minimal-apis/8.0-samples/MinAPISeparateFile/MinAPISeparateFile.csproj, aspnetcore/fundamentals/minimal-apis/8.0-samples/MinAPISeparateFile/Program.cs, aspnetcore/fundamentals/minimal-apis/8.0-samples/MinAPISeparateFile/TodoEndpoints.cs, aspnetcore/fundamentals/minimal-apis/8.0-samples/MinAPISeparateFile/appsettings.Development.json, aspnetcore/fundamentals/minimal-apis/8.0-samples/MinAPISeparateFile/appsettings.json, aspnetcore/fundamentals/minimal-apis/includes/route-handlers.md
Fixes #28680 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/route-handlers?view=aspnetcore-8.0&branch=pr-en-us-29387#endpoint-defined-outside-of-programcs)
---
|:--|:--|
=> Salvage project structure section from route-to-code doc

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md, aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
Fixes #29401
Parsing the remarks in external doc sets, it looks like Implicit flow hasn't been completely disabled ... it's just very strongly recommended to devs that they should use auth code flow with PKCE. I'll cross-link their remarks in our coverage, so devs can see for themselves what they recommend. We'll just say that it 'isn't recommended' in our docs, but I'll bold it to make it a strong recommendation.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/fda49feab3aff2dcd38549a939186a24508c00cd/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory …
=> Highly recommend avoiding Implicit grant

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/forms-and-input-components.md
Fixes #29403
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/317441da2ede0d5bab2e1afdf0872f10660d7168/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-29404) |
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/317441da2ede0d5bab2e1afdf0872f10660d7168/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-29404) |
=> Forms/input components article NRT updates

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
Fixes #28167 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0&branch=pr-en-us-29405#explicit-binding-from-form-values)
---
|:--|:--|
=> Document support for FromForm attribute

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #29413
Thanks @Kevin-Andrew! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/123fb3fae1975d58e7d2208921063251192cb98d/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [ASP.NET Core Blazor WebAssembly additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-29414) |
=> Fix broken example code

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
Fixes #29416 
[Quick reference URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0&branch=pr-en-us-29417#parameter-binding)
[Parameter Binding URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0&branch=pr-en-us-29417)
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/4159bbf1b16f03ec607f0099ef6cb7dcea627b2a/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-29417) |
=> Fix Parameter Binding section

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
Follow-up to #29417 
---
|:--|:--|
=> Add FromForm and IFormCollection to precedence list

aspnetcore/blazor/security/server/index.md
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/f6bb3cfccb3975b37adb0e5edd890594ece09d0f/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core Blazor Server apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-29424) |
=> Example code fix

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
Fixes #29423
Thanks @martillodecampo! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/fd1b797ba3d63c5bd6ee16715c98fa61ca360a4d/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-29430) |
| [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/fd1b797ba3d63c5bd6ee16715c98fa61ca360a4d/aspnetcore/blazor/security/webassembly/standalone-wi …
=> Improve a step in Blazor B2C tutorials

aspnetcore/blazor/components/data-binding.md
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/53b6c123dc631870b614a27fd7f28fdcf8e8af21/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-29433) |
=> Data binding article versioning

aspnetcore/release-notes/aspnetcore-8.0.md
Follow-up to #29405 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/28194389eb043a346bfd301126c9d2b8a84b6242/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29434) |
=> Add form binding to whats new

aspnetcore/blazor/components/event-handling.md, aspnetcore/blazor/components/lifecycle.md
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/ecd5b4218bfa63550215b2dff1208dc887ce181f/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-29442) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/ecd5b4218bfa63550215b2dff1208dc887ce181f/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-29442) |
=> Event handling/Lifecycle article versioning

aspnetcore/blazor/security/server/index.md
Fixes #29446
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e9f5c4a446b543424de040babf9d034096314300/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core Blazor Server apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-29447) |
=> Generic identifier for example

aspnetcore/blazor/security/index.md, aspnetcore/blazor/security/server/index.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
Fixes #29451
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d32c9700b4653a9add61cbd9e41243a534ee3cd/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-29454) |
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d32c9700b4653a9add61cbd9e41243a534ee3cd/aspnetcore/blazor/security/server/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-29454) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://gith …
=> NRT updates

aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Pages/Item.cshtml
=> Fixes 27414

aspnetcore/security/cors/includes/cors56.md, aspnetcore/security/cors/includes/cors7.md
Updated the docs for including UseCors after UseRouting but before UseAuthorization
=> Updated Cors middleware pages

aspnetcore/blazor/tutorials/signalr-blazor.md
---
|:--|:--|
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/77ade5e6e066a0ad7e2c45ee2db94416a73d37fe/aspnetcore/blazor/tutorials/signalr-blazor.md) | [Use ASP.NET Core SignalR with Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-29471) |
=> SignalR-Blazor tutorial versioning

aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md, aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/c7ea814f5d5d5ece84ed973b3ab1b2bdcf7be0b8/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-29473) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/c7ea814f5d5d5ece84ed973b3ab1b2bdcf7be0b8/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md) | …
=> Restore API cross-links

aspnetcore/blazor/tutorials/signalr-blazor.md
---
|:--|:--|
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/29d3bb579967ccc9af212be8f9e682795ed3727b/aspnetcore/blazor/tutorials/signalr-blazor.md) | [Use ASP.NET Core SignalR with Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-29474) |
=> Patch code blocks

aspnetcore/fundamentals/host/hosted-services.md
Fixes #29511 
---
|:--|:--|
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa9a9f86d323ab80182994d163ee12aec6811cbe/aspnetcore/fundamentals/host/hosted-services.md) | [Background tasks with hosted services in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-29513) |
=> Fix default shutdown timeout

aspnetcore/fundamentals/host/hosted-services/includes/hosted-services67.md
Follow-up to #29513 
The same fix for .NET 6 and 7
=> Update default timeout in hosted-services67.md

aspnetcore/security/authorization/iard.md
Fixes #29291
---
|:--|:--|
| [aspnetcore/security/authorization/iard.md](https://github.com/dotnet/AspNetCore.Docs/blob/4c2bb233e9576e08e02bc7297e445127b1606430/aspnetcore/security/authorization/iard.md) | [aspnetcore/security/authorization/iard](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/iard?branch=pr-en-us-29374) |
=> IAuthRequirementsData 

aspnetcore/blazor/javascript-interoperability/import-export-interop.md
Fixes #29544
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/5997c0d337befe68126da2e1b6c7b56ac4ee703f/aspnetcore/blazor/javascript-interoperability/import-export-interop.md) | [JavaScript `[JSImport]`/`[JSExport]` interop with ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?branch=pr-en-us-29545) |
=> Update module import approach

aspnetcore/security/authentication/add-user-data/samples/6.x/SampleApp/Areas/Identity/Pages/Account/Manage/Index.cshtml
=> Fixes issue 27414

aspnetcore/mvc/controllers/filters/samples/8.x/FiltersSample/Controllers/FilterMiddlewareController.cs
Fixes #29558
Moniker prep in https://github.com/dotnet/AspNetCore.Docs/pull/29559
=> Add generic type middleware filter /2

aspnetcore/blazor/blazor-server-ef-core.md, aspnetcore/blazor/components/js-spa-frameworks.md, aspnetcore/data/ef-rp/migrations.md, aspnetcore/fundamentals/routing/includes/routing3-7.md, aspnetcore/migration/inc/remote-authentication.md, aspnetcore/mvc/controllers/dependency-injection.md, aspnetcore/razor-pages/sdk.md, aspnetcore/security/enforcing-ssl.md, aspnetcore/security/samesite.md, aspnetcore/tutorials/grpc/grpc-start/includes/grpc-start6.md, aspnetcore/tutorials/grpc/grpc-start/includes/grpc-start7.md
For User Story https://dev.azure.com/msft-skilling/Content/_workitems/edit/98992: VALIDATION: AspNetDocs/AspNetCore
Addresses all broken links reported for AspNetCore.Docs on the Broken Link Dashboard https://aka.ms/brokenlinkdashboard as of 6/19/2023 (21 links)
---
|:--|:--|
| [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/60e5c70c56804db10128f8c6fa42c3b6bef63646/aspnetcore/blazor/blazor-server-ef-core.md) | [ASP.NET Core Blazor Server with Entity Framework Core (EF Core)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?branch=pr-en-us-29569) |
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/60e5c70c56804db10128f8c6fa42c3b6bef63646 …
=> [BULK] Fix 21 broken links in AspNetCore.Docs as of 6/19/2023

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29576
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3dbe2a79667e033280adcdc102f6ebffca3605e/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29580) |
=> generics in What's new /2

aspnetcore/release-notes/aspnetcore-8.0.md, aspnetcore/release-notes/sample/ProgramAsParameters.cs
Fixes #29581
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/fcc928b756611913956d3337957a34fa740ddcf1/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29585) |
=> Support for AsParameters /2

aspnetcore/grpc/authn-and-authz.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2108
Ready for review. Shouldn't be merged until gRPC 2.54.0 is released.
---
|:--|:--|
| [aspnetcore/grpc/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b58b4cdc85cded886dd5c36f3865d14f0b8d62f/aspnetcore/grpc/authn-and-authz.md) | [Authentication and authorization in gRPC for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?branch=pr-en-us-29185) |
=> Document CallCredentials CancellationToken

.gitignore
=> fix typo in .gitignore

aspnetcore/mvc/views/view-components.md
Added paths for views search about Areas for View Components
---
|:--|:--|
| [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/050be73a37fd8ff6753482bf1f6f0816de73f8e8/aspnetcore/mvc/views/view-components.md) | [View components in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?branch=pr-en-us-29587) |
=> Added Areas paths for View Components

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29592 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0fe302e30c229b0d612ee5da1c1c39f5871018a/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29591) |
=> Add preview 1 what's-new-only sections

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29602 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa291002f8b274c702614c11857188828d1f22cc/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29601) |
=> Add content from preview 3 to what's new

aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #29606
Thanks @jdh148! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/b1b79c9b8285a381a9a28eb50ece9ad939c1dff4/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [ASP.NET Core Blazor WebAssembly additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-29607) |
=> Explicitly instruct on adding package

aspnetcore/blazor/project-structure.md
Fixes #29565
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/e5ec568c40db003291fa057def0cb99117c3e1e5/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-29566) |
=> Project structure article updates

aspnetcore/blazor/tooling.md
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/716ebfcb890177800e3ea02c7c0ca656fd5820e3/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29611) |
=> Update Tooling article lists

aspnetcore/blazor/tooling.md
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/cbb79a8ae3295a1f5c3bc4eea6ecf0ccd028755e/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-29613) |
=> Tooling article updates

aspnetcore/mvc/controllers/filters/samples/8.x/FiltersSample/Controllers/ExceptionController.cs, aspnetcore/mvc/controllers/filters/samples/8.x/FiltersSample/Controllers/FilterDependenciesController.cs, aspnetcore/mvc/controllers/filters/samples/8.x/FiltersSample/Controllers/FilterFactoryController.cs, aspnetcore/mvc/models/model-binding.md, aspnetcore/mvc/models/model-binding/samples/8.x/ModelBindingSample/ModelBindingSample.csproj
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/29571
---
|:--|:--|
| [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b2c49632ba8c7f7e743ab1db90bedcd994a4f4e/aspnetcore/mvc/models/model-binding.md) | [Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=pr-en-us-29573) |
=> Model binding with generic types /7

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/minimal-apis/7.0-samples/WebMinAPIs/Program.cs, aspnetcore/fundamentals/minimal-apis/includes/webapplication7.md
Fixes #29497
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/99865f59ee9653e60965c34d046eab957c4341d6/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-29604) |
=> Fix snippet tag /2

aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/HttpSysSample.csproj, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/Error.cshtml, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/Error.cshtml.cs, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/Index.cshtml, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/Index.cshtml.cs, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/Shared/_Layout.cshtml, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/_ViewImports.cshtml, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Pages/_ViewStart.cshtml, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Program.cs, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/README.md, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/appsettings.Development.json, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/appsettings.Production.json, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/appsettings.json
Updates the HTTP.sys sample project to 8.0
Fixes #29562
=> Update HTTP.sys sample to 8.0

aspnetcore/fundamentals/servers/httpsys.md, aspnetcore/fundamentals/servers/httpsys/samples/8.x/SampleApp/Program.cs
Fixes #29631
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/a3dbd88ab85e21b289f8ca2871e91d093d838bc6/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?branch=pr-en-us-29632) |
=> Update snippet ref to 8.x /2

aspnetcore/fundamentals/servers/kestrel/endpoints.md, aspnetcore/fundamentals/servers/kestrel/samples/6.x/KestrelSample/Snippets/Program.cs
Feedback from https://github.com/dotnet/AspNetCore.Docs/pull/29564
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/b6268b3677b7b172dac8d6e8dca615b2bc7d5d81/aspnetcore/fundamentals/servers/kestrel/endpoints.md) | [Configure endpoints for the ASP.NET Core Kestrel web server](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?branch=pr-en-us-29605) |
=> Kestrel endpoints follow up changes

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29619 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/59284a412f5170d1444f7f2b54664156a30ec405/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29648) |
=> Add EnableKernelResponseBuffering option to what's new

aspnetcore/fundamentals/servers/httpsys.md
Contributes to #29619 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/46154bac814039700cdb37941584a1c366bb083e/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?branch=pr-en-us-29649) |
=> Doc http.sys response buffering option

aspnetcore/blazor/components/dynamiccomponent.md, aspnetcore/blazor/security/webassembly/index.md
Fixes #29652
Thanks @AlanFitzgeraldVSolvit! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/bc8fd84b6c00d69ec32effe19b5e4381f0fe23bd/aspnetcore/blazor/components/dynamiccomponent.md) | [Dynamically-rendered ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-29653) |
| [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bc8fd84b6c00d69ec32effe19b5e4381f0fe23bd/aspnetcore/blazor/security/webassembly/index.md) | [Secure ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?branch=pr-en-us-29653) |
=> Improve namespace instructions

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29582 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/57d69b6fec01192c6ae6736e41777e1cea862ba0/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29654) |
=> Add an auth section to what's new

aspnetcore/grpc/aspnetcore.md
ITNOA
Fixes #29628 
---
|:--|:--|
| [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/add580ee74c8416a9e08d3f20a879cdc3f1aaff2/aspnetcore/grpc/aspnetcore.md) | [gRPC services with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?branch=pr-en-us-29629) |
=> Remove extra and inconsistent sentences for windows insider.

aspnetcore/blazor/supported-platforms.md
Fixes #29664
---
|:--|:--|
| [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/78ebc13d2564a850dafc29e8028fc9a974705b3e/aspnetcore/blazor/supported-platforms.md) | [ASP.NET Core Blazor supported platforms](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?branch=pr-en-us-29665) |
=> Supported platform updates

aspnetcore/blazor/tutorials/index.md
Fixes #29666
---
|:--|:--|
| [aspnetcore/blazor/tutorials/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3791b6e4a2b72353bc2f87fb96f2ef4e754d7112/aspnetcore/blazor/tutorials/index.md) | [ASP.NET Core Blazor tutorials](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/index?branch=pr-en-us-29667) |
=> Tutorials overview updates

aspnetcore/blazor/tutorials/index.md
---
|:--|:--|
| [aspnetcore/blazor/tutorials/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/05bbafe459952c26767cb2ed3a8c1c8090d651c8/aspnetcore/blazor/tutorials/index.md) | [ASP.NET Core Blazor tutorials](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/index?branch=pr-en-us-29682) |
=> Update tutorials overview

aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo0.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo2.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo3.razor, aspnetcore/blazor/tutorials/build-a-blazor-app/8.0/Todo6.razor
---
|:--|:--|
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/d2a49ad87202db092894f52a5805fc95ab93b8e3/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-29683) |
=> Update ToDo List tutorial

aspnetcore/blazor/debug.md
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/5348e5f96ca99f6d9477a1a3d4313cd664825f12/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-29685) |
=> Added missing comma.

aspnetcore/blazor/components/class-libraries.md
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/75c4455e2be8f7e5bb083a54c27437a8012a9460/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-29697) |
=> Cross-link content

aspnetcore/blazor/components/index.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/blazor/host-and-deploy/configure-linker.md, aspnetcore/blazor/host-and-deploy/configure-trimmer.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/performance.md
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/44834f210491174f2cd4d6f0844cc23a01212edc/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-29699) |
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/44834f210491174f2cd4d6f0844cc23a01212edc/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-29699) |
| [aspnetcore/blazor/host-and-deploy/configure-linker.md](https://github.com/dotnet/ …
=> Crosslink 'reflection' to C# Guide

aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #29737
Thanks @speschka! :rocket: ... I'm clarifying the target audience for this in the opening remarks and cross-linking the framework doc sets, given that this particular tutorial is mostly for those who already know SignalR and are trying to understand how to integrate it with Blazor.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d74d6321f86e065b618b8ce47d44b6c2c2cb902/aspnetcore/blazor/tutorials/signalr-blazor.md) | [Use ASP.NET Core SignalR with Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-29740) |
=> Clarify target audience

aspnetcore/toc.yml
Fixes #29645 
Don't merge until #29646 is merged.
=> Logging and monitoring TOC section

aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/state-management.md
Fixes #29763
Addresses #29749
---
|:--|:--|
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/64b1a4c82f14b62bb171376d5c6ff92eb96debfc/aspnetcore/blazor/components/rendering.md) | [ASP.NET Core Razor component rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?branch=pr-en-us-29764) |
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/64b1a4c82f14b62bb171376d5c6ff92eb96debfc/aspnetcore/blazor/state-management.md) | [ASP.NET Core Blazor state management](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/state-management?branch=pr-en-us-29764) |
=> Cross-link sync context content

aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #29450
---
|:--|:--|
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/51f85663ad9f6563165226b62996ef71eb560048/aspnetcore/blazor/components/prerendering-and-integration.md) | [Prerender and integrate ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?branch=pr-en-us-29769) |
=> Update prerendering resource lists

aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/performance.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/768b4670b9305b0fec016208144e84f1716ebdb2/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-29770) |
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/768b4670b9305b0fec016208144e84f1716ebdb2/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy ASP.NET Core Blazor Server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-29770) |
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/bl …
=> Memory management updates

aspnetcore/host-and-deploy/health-checks/includes/health-checks6-7.md
Fixes #29775 
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/b2ac8dfc8a234c37c62f36a9590a397bf34e93ce/aspnetcore/host-and-deploy/health-checks.md) | [Health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-29776) |
=> Moniker prep for .NET 8

aspnetcore/fundamentals/error-handling.md
Follow-up to #29674 -- see https://github.com/dotnet/AspNetCore.Docs/pull/29674#discussion_r1249302217
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/3603cbd9f30becb23763a797788421f1466ed0a1/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29730) |
=> IExceptionHandler is singleton

aspnetcore/host-and-deploy/health-checks.md
Fixes #29709 
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/733c2f9edd065ec3f0d4c74d39cd110dc91c0b26/aspnetcore/host-and-deploy/health-checks.md) | [Health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-29778) |
=> Add note about calling ShortCircuit

aspnetcore/blazor/call-web-api.md
Fixes #29783
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/f723f4c93abcaa0add087ec36f4505e404953829/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-29784) |
=> Call web API PATCH section improvements

aspnetcore/security/authorization/claims.md, aspnetcore/security/authorization/policies.md, aspnetcore/security/authorization/policies/samples/6.0/AuthorizationPoliciesSample/Controllers/AtLeast21Controller2.cs, aspnetcore/security/authorization/roles.md, aspnetcore/security/authorization/roles/samples/6_0/WebAll/Controllers/ControlAllPanelController2.cs
Fixes #29802
Thanks @david-acker! 🚀 
Rick, I had a few minutes while I wait for DR to get back to me on a few Blazory things, so I took a quick stab 🔪 at this. Please close if it's a `won't-fix` or should be handled differently.
---
|:--|:--|
| [aspnetcore/security/authorization/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/eee45f0620f1307cd0b0bbc923c655c345e36a68/aspnetcore/security/authorization/claims.md) | [Claims-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/claims?branch=pr-en-us-29803) |
| [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/eee45f0620f1307cd0b0bbc923c655c345e36a68/aspnetcore/security/authorization/policies.md) | …
=> Enhance multiple policy/attribute coverage

aspnetcore/blazor/security/includes/usermanager-signinmanager.md, aspnetcore/fundamentals/configuration/index.md, aspnetcore/fundamentals/configuration/index/includes/index6.md, aspnetcore/fundamentals/logging/index.md, aspnetcore/fundamentals/minimal-apis/includes/webapplication7.md, aspnetcore/grpc/interceptors.md, aspnetcore/migration/50-to-60-samples.md, aspnetcore/security/data-protection/configuration/overview.md
Fixes #29799
Thanks @sliekens and @Ducki! 🚀
Rick, I have a few minutes to toss a quick one up for this. I'm waiting on some DR feedback on Blazorish thing-a-ma-bobs and what-nots.
I took the "*Read the environment*" heading out and left that content under the *Read configuration* section. There are no bookmark instances of "#read-the-environment" in the doc set, so nothing breaks with the change in the doc set.
Also, I went through the doc set and placed message templates into the logging code examples.
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/5cc0665b0bfe002f399bcebcbef7b26c4f56bbd1/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET …
=> Enhance config access in Program.cs

aspnetcore/fundamentals/error-handling.md, aspnetcore/fundamentals/error-handling/includes/error-handling3-7.md
Fixes #29747
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/c728c24f7946bc8ba76db6e47a2748fc37271f7b/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29807) |
=> Include AddMvc in IProblemDetailsWriter registration warning

aspnetcore/includes/preview-notice.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29838 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/a57ddba149a64624a668db51969306d93c2b2e89/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29839) |
=> Add preview notice to What's new

aspnetcore/fundamentals/error-handling.md, aspnetcore/fundamentals/minimal-apis/handle-errrors.md, aspnetcore/fundamentals/servers/kestrel/endpoints.md, aspnetcore/includes/not-latest-version.md, aspnetcore/mvc/controllers/routing.md
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/f313a20b253ae1cd0e6b287b4b7f0e5a4ed2f84e/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29844) |
| [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/f313a20b253ae1cd0e6b287b4b7f0e5a4ed2f84e/aspnetcore/fundamentals/servers/kestrel/endpoints.md) | [Configure endpoints for the ASP.NET Core Kestrel web server](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?branch=pr-en-us-29844) |
| …
=> Extend preview notice to .NET 8 doc versions

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md, aspnetcore/fundamentals/minimal-apis/parameter-binding.md, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/ComplexBinding/ComplexBinding.csproj, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/ComplexBinding/Program.cs, aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/ComplexBinding/appsettings.json
Fixes #29831
[Internal: Bind to collections and complex types](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0&branch=pr-en-us-29834#bind-to-collections-and-complex-types)
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/parameter-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/147e1dcc210a08815e0be4020e9dd023066844a1/aspnetcore/fundamentals/minimal-apis/parameter-binding.md) | [Parameter Binding in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?branch=pr-en-us-29834) |
=> Complex binding /5

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29848
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/67ef3f78d352a7f0366dc3d67b76ed7a2581e3f0/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29849) |
=> What's new

aspnetcore/blazor/tutorials/build-a-blazor-app.md
Addresses #29668
---
|:--|:--|
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/4cac435fbcab3a79864227a746a502224fc07d81/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-29862) |
=> Todo tutorial 8.0 updates

aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md
Fixes #29897 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md](https://github.com/dotnet/AspNetCore.Docs/blob/3b309fb2dee8386dbae799aa8d74145c258e710e/aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md) | [When to use Kestrel with a reverse proxy](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy?branch=pr-en-us-29898) |
=> Clarify pros and cons of internal HTTPS

aspnetcore/fundamentals/error-handling.md, aspnetcore/fundamentals/error-handling/includes/error-handling3-7.md, aspnetcore/fundamentals/error-handling/samples/7.x/ErrorHandlingSample/Snippets/Program.cs, aspnetcore/fundamentals/error-handling/samples/8.x/ErrorHandlingSample/Snippets/Program.cs
Fixes #29902
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/59911e251a604e3243fa49aab52c03a2fee891c0/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29903) |
=> Prob details in the right place /5

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29889 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/1935af84c80ce480581997af1c4ba1aab6f1581b/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29905) |
=> Add IPNetwork.Parse and TryParse to WN

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/components/index.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/hybrid/root-component-parameters.md, aspnetcore/blazor/hybrid/security/security-considerations.md, aspnetcore/blazor/progressive-web-app.md, aspnetcore/blazor/security/webassembly/index.md, aspnetcore/blazor/state-management.md
Fixes #29910
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/a8f03752e64be872e4637030de45fbeb5986e1f1/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-29911) |
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/a8f03752e64be872e4637030de45fbeb5986e1f1/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-29911) |
| [aspnetcore/blazor/components/rendering.md](https://github.com …
=> Language cleanup and additional updates

aspnetcore/blazor/components/dynamiccomponent.md, aspnetcore/blazor/components/index.md
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/45caacc7821379abf2291fbf8331bb6f2e8cba2a/aspnetcore/blazor/components/dynamiccomponent.md) | [Dynamically-rendered ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-29912) |
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/45caacc7821379abf2291fbf8331bb6f2e8cba2a/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-29912) |
=> Move sample code

aspnetcore/release-notes/aspnetcore-8.0.md
Follow-up to #29905
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/cfc40c7ee2e76fcf8793ea45afbccb51dd2dc894/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29919) |
=> Put examples in separate code blocks

aspnetcore/blazor/fundamentals/handle-errors.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/19bdb9c0965d30ef559e92f17d267931c55a9b96/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-29920) |
=> Handle errors followup 8.0

aspnetcore/includes/not-current-version.md, aspnetcore/performance/caching/output.md, aspnetcore/performance/caching/output/includes/output7.md
Fixes #29921 
---
|:--|:--|
| [aspnetcore/performance/caching/output.md](https://github.com/dotnet/AspNetCore.Docs/blob/908d69732ca7e9332a11fd35b7e70440f2d5ae86/aspnetcore/performance/caching/output.md) | [Output caching middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/output?branch=pr-en-us-29922) |
=> Moniker prep for 8.0

.repoman.yml, aspnetcore/docfx.json
Thx, @tdykstra! 🎸
cc: @BethMassi ... This will handle labels, assignments, and placing issues on the Blazor Hybrid project when a new issue arrives. Next, you can assign a priority label (Pri0-Pri3); add a label for `doc-bug`, `doc-idea` (a new doc), or `doc-enhancement`; and set the correct column on the project based on its priority.
=> Blazor Hybrid issue management

aspnetcore/fundamentals/aot/includes/aot_lib.md, aspnetcore/fundamentals/aot/native-aot-tutorial.md, aspnetcore/fundamentals/native-aot.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29924
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/aac2fad4998842a1ff9142b28ca31771af3df7dd/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-29925) |
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/aac2fad4998842a1ff9142b28ca31771af3df7dd/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29925) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com …
=> AOT for libs /5

aspnetcore/fundamentals/aot/native-aot-tutorial.md
Fixes #29937
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/b1b514c3ee6ef850e4019666ec0cd12990ef8343/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-29938) |
=> Linux AOT /4

aspnetcore/fundamentals/use-http-context.md, aspnetcore/fundamentals/use-http-context/samples/Program.cs
Fixes #29533
---
|:--|:--|
| [aspnetcore/fundamentals/use-http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca628c4c7ecdbcf23a0e41e4c3ab7c3be5709272/aspnetcore/fundamentals/use-http-context.md) | [Use HttpContext in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?branch=pr-en-us-29927) |
=> docs: fix feature snippet

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29960
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/5cf1d5417df638ac87cad96e262b0627b8369dde/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29961) |
=> Output cache Redis to WN

aspnetcore/blazor/hosting-models.md, aspnetcore/blazor/security/webassembly/index.md
Fixes #29955
---
|:--|:--|
| [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/50a198eeefdb7630b371be08c8c879519b604d4d/aspnetcore/blazor/hosting-models.md) | [ASP.NET Core Blazor hosting models](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?branch=pr-en-us-29962) |
| [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/50a198eeefdb7630b371be08c8c879519b604d4d/aspnetcore/blazor/security/webassembly/index.md) | [Secure ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/index?branch=pr-en-us-29962) |
=> Client-side security remarks

aspnetcore/migration/inc/remote-session.md, aspnetcore/migration/inc/samples/remote-session/Global.asax.cs, aspnetcore/migration/inc/samples/remote-session/Program.cs, aspnetcore/migration/inc/samples/remote-session/SomeController.cs, aspnetcore/migration/inc/samples/remote/stub.text, aspnetcore/migration/inc/samples/session/Program.cs, aspnetcore/migration/inc/samples/wrapped/Program.cs, aspnetcore/migration/inc/session.md, aspnetcore/migration/inc/wrapped.md
Fixes #28549
Because the changes are small this PR contains the changes for each task in the linked issue.
---
|:--|:--|
| [aspnetcore/migration/inc/remote-session.md](https://github.com/dotnet/AspNetCore.Docs/blob/d1b375edaed5e168a64c52a2647e42eaf3dfb8e2/aspnetcore/migration/inc/remote-session.md) | [Remote app session state](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-session?branch=pr-en-us-29948) |
| [aspnetcore/migration/inc/session.md](https://github.com/dotnet/AspNetCore.Docs/blob/d1b375edaed5e168a64c52a2647e42eaf3dfb8e2/aspnetcore/migration/inc/session.md) | [ASP.NET to ASP.NET Core incremental session state migration](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/session?branch=pr-en-us-29948) |
| …
=> Move Remote app session state snippets to project in samples folder

aspnetcore/test/http-files.md
Fixes #29976 
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c36beaee75c1c243f2c45b44005089f62f5ac93/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-29977) |
=> .http files, Endpoint Explorer GA

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29940 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d209f8dc9504ff01fdf3d5858ac4efc4b0a7cd6e/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-29979) |
=> Add short-circuit to WN

aspnetcore/migration/inc/remote-authentication.md, aspnetcore/migration/inc/samples/remote-authentication/AspNetApp.cs, aspnetcore/migration/inc/samples/remote-authentication/AspNetCore.cs
Closes #28548
Side note: I hope it's OK that I'm picking up these issues 😅
---
|:--|:--|
| [aspnetcore/migration/inc/remote-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/f12e6239b201e6c0b43e33f91e579d72839cbf7b/aspnetcore/migration/inc/remote-authentication.md) | [Remote Authentication](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-authentication?branch=pr-en-us-29975) |
=> move remote authentication snippets into project file

aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/prerendering-and-integration.md, aspnetcore/blazor/components/quickgrid.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/fundamentals/dependency-injection.md, aspnetcore/blazor/fundamentals/environments.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/fundamentals/index.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/fundamentals/routing.md, aspnetcore/blazor/fundamentals/signalr.md, aspnetcore/blazor/fundamentals/startup.md, aspnetcore/blazor/fundamentals/static-files.md, aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md, aspnetcore/blazor/includes/location-client-and-server.md, aspnetcore/blazor/includes/location-client.md, aspnetcore/blazor/includes/location-server.md, aspnetcore/blazor/progressive-web-app.md, aspnetcore/blazor/project-structure.md, aspnetcore/blazor/security/server/additional-scenarios.md, aspnetcore/blazor/security/webassembly/additional-scenarios.md, aspnetcore/blazor/security/webassembly/graph-api.md, aspnetcore/blazor/tooling.md, aspnetcore/blazor/tutorials/build-a-blazor-app.md, aspnetcore/blazor/tutorials/index.md, aspnetcore/blazor/tutorials/signalr-blazor-preview.md, aspnetcore/blazor/tutorials/signalr-blazor.md
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/d032ffe31144af858e9d43e511270b4eb7880651/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-29928) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/d032ffe31144af858e9d43e511270b4eb7880651/aspnetcore/blazor/components/prerendering-and-integration.md) | [Prerender and integrate ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/component …
=> Full-stack UI updates (Fundamentals node) 8.0

aspnetcore/fundamentals/aot/samples/Todo.cs, aspnetcore/fundamentals/native-aot.md
Fixes #29915
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0&branch=pr-en-us-29967#minimal-apis-and-json-payloads)
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/ba5fa32465a28ad330f21a317d5fa208fbbf4c9f/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29967) |
=> Minimal APIs and native AOT /4

aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md
Fixes #30005
Thanks @TDroogers! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/e2f21f496c17017c3f15bb4caa3572216ad19af4/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md) | [Azure Active Directory (AAD) groups, Administrator Roles, and App Roles](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?branch=pr-en-us-30006) |
=> Update AuthorizeView example

aspnetcore/fundamentals/aot/native-aot-tutorial.md
Fixes #29944
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/4e0656280059a14b1f498c8a91101ab7e8e746dc/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-30014) |
=> CLI requires VC++ /4

aspnetcore/fundamentals/aot/native-aot-tutorial.md
Fixes #29978
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/d526160f14a25d5b486f210d8d4d2ea7d0972bd5/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-30024) |
=> Use new webapiaot project template

aspnetcore/fundamentals/native-aot.md
Fixes #29984 
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/5944ed7e14c42e29c28727a197844f17dcfab736/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-30027) |
=> Change api template to webapiaot template

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29986 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/bc4b3f65acdc3f65198fb39c25955c02ad87b94f/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30029) |
=> Change api template to webapiaot

aspnetcore/tutorials/first-web-api.md
Fixes #30037 
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/6adf307b3bef966854a0c137e735131d57d084cb/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-30038) |
=> Add --use-controllers

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29366 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/92f1b122a320e131270edd50914d894c6e36645d/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30046) |
=> Add ProblemDetails fallback API to WN

aspnetcore/fundamentals/localization/select-language-culture.md
Addresses #30009
---
|:--|:--|
| [aspnetcore/fundamentals/localization/select-language-culture.md](https://github.com/dotnet/AspNetCore.Docs/blob/d17f3583e602206f06092e1eff8a11acea92771b/aspnetcore/fundamentals/localization/select-language-culture.md) | [Implement a strategy to select the language/culture for each request in a localized ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?branch=pr-en-us-30021) |
=> Add docs for localization 8

aspnetcore/fundamentals/localization/includes/select-language-culture67.md, aspnetcore/fundamentals/localization/select-language-culture.md
Fixes #30051
---
|:--|:--|
| [aspnetcore/fundamentals/localization/select-language-culture.md](https://github.com/dotnet/AspNetCore.Docs/blob/225ea3a3593f08522820cfc5aa37f283f3745aff/aspnetcore/fundamentals/localization/select-language-culture.md) | [Implement a strategy to select the language/culture for each request in a localized ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?branch=pr-en-us-30049) |
=> culture /4

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30047
Related to #30021
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d665bada76cdcd7f5db7487fb2e993ab99343368/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30069) |
=> Add User override culture in ASP.NET Core 8.0 release notes

aspnetcore/blazor/forms-and-input-components.md
Addresses #29728
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/78fee1ca5578a375a009cf019d4745fe04b177ed/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30078) |
=> Blazor forms and antiforgery 8.0 updates

aspnetcore/tutorials/razor-pages/da1.md, aspnetcore/tutorials/razor-pages/model.md, aspnetcore/tutorials/razor-pages/new-field.md, aspnetcore/tutorials/razor-pages/page.md, aspnetcore/tutorials/razor-pages/razor-pages-start.md, aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie80/Migrations/20230606012811_New_DataAnnotations.cs, aspnetcore/tutorials/razor-pages/search.md, aspnetcore/tutorials/razor-pages/sql.md, aspnetcore/tutorials/razor-pages/validation.md
Fixes #29478 
Fixes #29477 
Updated and tested this series for .NET 8 for macOS and cleaned up a few items.
Tested and verified SQLite package issue for 29477
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d6ee303d3c1fb1e19705b05f6f456ca505e55cb/aspnetcore/tutorials/razor-pages/da1.md) | [Part 5, update the generated pages in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?branch=pr-en-us-30075) |
| [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d6ee303d3c1fb1e19705b05f6f456ca505e55cb/aspnetcore/tutorials/razor-pages/model.md) | [Part 2, add a model to a Razor Pages app in ASP.NET …
=> 8.0 Update MacOS: Razor Pages Get Started Series

aspnetcore/fundamentals/change-tokens.md, aspnetcore/fundamentals/change-tokens/samples/2.x/SampleApp/Utilities/Utilities.cs, aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Utilities/Utilities.cs
Fixes #30080
Thanks @fdcastel! 🚀 
---
|:--|:--|
| [aspnetcore/fundamentals/change-tokens.md](https://github.com/dotnet/AspNetCore.Docs/blob/a343e4fff94b4068473845ae9bb4139caaa6cf43/aspnetcore/fundamentals/change-tokens.md) | [Detect changes with change tokens in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?branch=pr-en-us-30086) |
=> Improve code example

aspnetcore/mvc/models/validation/samples/ValidationResultErrorMessage/Models/Contact.cs
Remove superfluous whitespace in Contact.cs
=> Remove superfluous whitespace in Contact.cs

aspnetcore/blazor/components/lifecycle.md
Fixes #30097
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/7597b2cafc027a70ebd752fd4e81e0034bc07ef5/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-30098) |
=> OnAfterRender lifecycle updates 8.0

aspnetcore/grpc/services.md, aspnetcore/grpc/services/DownloadResults.cs, aspnetcore/grpc/services/ExampleService.cs, aspnetcore/grpc/services/GreeterBase.cs, aspnetcore/grpc/services/GreeterService.cs, aspnetcore/grpc/services/PerformLongRunningWorkAsync.cs, aspnetcore/grpc/services/Program.cs, aspnetcore/grpc/services/Protos/example.proto, aspnetcore/grpc/services/Protos/greeter.proto
Fixes #28555
---
|:--|:--|
| [aspnetcore/grpc/services.md](https://github.com/dotnet/AspNetCore.Docs/blob/73beb9261695012d4c1a339e67451f110e15c560/aspnetcore/grpc/services.md) | [Create gRPC services and methods](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/services?branch=pr-en-us-30077) |
=> move grpc embedded snippets to projects files

aspnetcore/security/authentication/mfa.md
Updated the MFA text to include passkeys and mention other phishing resistant authentication methods.
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa
***EDIT BY @Rick-Anderson***
Fixes #30089
---
|:--|:--|
| [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/0b83688a15a0e4936fca82b582e482c1fe8b7685/aspnetcore/security/authentication/mfa.md) | [Multi-factor authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?branch=pr-en-us-30084) |
=> Update text MFA passkeys/FIDO2 or passwordless

aspnetcore/security/authentication/mfa.md
I updated the example and this PR updates the docs to match. 
- Using ASP.NET Core Identity Razor Pages
- Updated IdentityServer4 to Duende IdentityServer
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa
Fixes #30108
---
|:--|:--|
| [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/12874ac86c28d97077b10eb520a106ed731daf92/aspnetcore/security/authentication/mfa.md) | [Multi-factor authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?branch=pr-en-us-30105) |
=> damienbod/mfa/updated ASP.NET Core Identity to Razor Pages and OpenID Connect Duende IdentityServer

aspnetcore/fundamentals/native-aot.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30052
Fixes #30053
* [C# 12 Interceptors](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0&branch=pr-en-us-30054#c-12-interceptors)
*  [Increased performance using Interceptors](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0&branch=pr-en-us-30054#increased-performance-using-interceptors)
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a6bbe9e4273f5445be91244069ba4c2c4735593/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-30054) |
| …
=> Interceptors in AoT /4

aspnetcore/fundamentals/native-aot.md, aspnetcore/release-notes/aspnetcore-8.0.md, aspnetcore/release-notes/aspnetcore-8.0/samples/EmptyBuilderExample/EmptyBuilderExample.csproj, aspnetcore/release-notes/aspnetcore-8.0/samples/EmptyBuilderExample/Program.cs
Fixes #30099 
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/96cd43c3f9b5f6f95ae9082e3167f7397bd80011/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-30113) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/96cd43c3f9b5f6f95ae9082e3167f7397bd80011/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30113) |
=> Add CreateEmptyBuilder to What's new

aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie80/Models/MovieDateRatingDA.cs
While looking at a case in the documentation I saw that the Display attribute remains as a comment. It's not a big problem but I wanted to open pr.
Related link -> https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-7.0&tabs=visual-studio#add-validation-rules-to-the-movie-model
=> Editing Asp.Net documents

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/file-uploads.md
Fixes #30111
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/8f790f35a57b8858f46b8bd742d99a6779c609e3/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-30117) |
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/8f790f35a57b8858f46b8bd742d99a6779c609e3/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30117) |
=> Blazor File Uploads article updates 8.0

aspnetcore/performance/rate-limit.md
---
|:--|:--|
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/c653d01bdc5c368ba0712cf8f35258ad63246130/aspnetcore/performance/rate-limit.md) | [Rate limiting middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?branch=pr-en-us-30126) |
=> Correctly format example

aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/fundamentals/logging.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/tooling.md
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/46273c35f269e8d170a05e1cb5026ca026f31d0d/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30179) |
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/46273c35f269e8d170a05e1cb5026ca026f31d0d/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?branch=pr-en-us-30179) |
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/46273c35f269e8d170a05e1cb5026ca …
=> Full-stack UI updates

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/zone-pivot-groups.yml
Fixes #30172
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/591e3232e7d9783043aa6f13aac5a3af241142a1/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-30180) |
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/591e3232e7d9783043aa6f13aac5a3af241142a1/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30180) |
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/591e3232e7d9783043aa6f13aac5a3 …
=> Call web API article updates 8.0

aspnetcore/blazor/host-and-deploy/server.md, aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #30207
Thanks @kevingolding2001! 🚀 ... I'll merge this change into the live documentation immediately. It will be live in about 10-15 minutes. I searched the whole doc set, and I had commented out other code where it appeared earlier, so this was the only live instance of it in the published docs.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/1b2a23472d0b43c9f303646e337d7661c4359974/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy Blazor Server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-30208) |
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/1b2a23472d0b43c9f303646e337d76 …
=> Remove ProxyRequests in Apache guidance

aspnetcore/grpc/interprocess.md
@blowdart @GrabYourPitchforks Security guidance for named pipes IPC (and IPC in general)
---
|:--|:--|
| [aspnetcore/grpc/interprocess.md](https://github.com/dotnet/AspNetCore.Docs/blob/ac40eebc2ca99d8eb173151c88ea6791c4a05dd3/aspnetcore/grpc/interprocess.md) | [Inter-process communication with gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?branch=pr-en-us-29973) |
=> Add IPC security section

aspnetcore/blazor/components/class-libraries.md, aspnetcore/blazor/debug.md, aspnetcore/blazor/fundamentals/index.md, aspnetcore/blazor/host-and-deploy/index.md, aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md, aspnetcore/blazor/hybrid/tutorials/maui.md, aspnetcore/blazor/progressive-web-app.md, aspnetcore/blazor/security/server/index.md, aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md, aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md, aspnetcore/blazor/tooling.md, aspnetcore/blazor/tutorials/signalr-blazor-preview.md, aspnetcore/blazor/tutorials/signalr-blazor.md, aspnetcore/zone-pivot-groups.yml
Fixes #30219
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/d0ef39b023e19da7028a1664b68d20d797518f83/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-30225) |
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/d0ef39b023e19da7028a1664b68d20d797518f83/aspnetcore/blazor/debug.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-30225) |
| …
=> Remove VS4Mac from the Blazor node

aspnetcore/security/authentication/azure-ad-b2c.md
Fixes #30186
See [New name for Azure Active Directory](https://learn.microsoft.com/azure/active-directory/fundamentals/new-name)
---
|:--|:--|
| [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/94529f2e7c9ccea63630fa88438fb3785178281a/aspnetcore/security/authentication/azure-ad-b2c.md) | [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?branch=pr-en-us-30188) |
=> AD rename /4

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md, aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30159
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/420f95b3aafec9c1eab6a8fe45b4eab6f2db9565/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30205) |
=> anti forgery to WN /1

aspnetcore/fundamentals/servers/kestrel/endpoints/includes/endpoints5-7.md
=> Shorten some H2 headings

aspnetcore/fundamentals/host/generic-host.md
Fixes #30070 
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/aa0bc279fd48673e9d02ef3e2a144d66c9998675/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-30238) |
=> Explain difference between Start vs. Run

aspnetcore/host-and-deploy/linux-apache.md, aspnetcore/host-and-deploy/linux-nginx.md, aspnetcore/security/authentication/social/additional-claims.md, aspnetcore/security/authentication/ws-federation.md, aspnetcore/security/authorization/policies.md
Fixes #30200
Fixes #30242
Fixes #30244
Fixes #30246
Fixes #30245
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c04a823ea8daeb93965d288daa22db1f7084b46/aspnetcore/host-and-deploy/linux-apache.md) | [Host ASP.NET Core on Linux with Apache](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?branch=pr-en-us-30247) |
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c04a823ea8daeb93965d288daa22db1f7084b46/aspnetcore/host-and-deploy/linux-nginx.md) | [[Ubuntu](#tab/linux-ubuntu)](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-30247) |
| …
=> Rename Azure AD /1

aspnetcore/log-mon/metrics/metrics.md
Add enrichment section to ASP.NET Core metrics docs.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/bfab1827f874fbb91c5dbc6b38cddfe7a79ceb0d/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30222) |
=> Add HTTP request metrics enrichment docs

aspnetcore/blazor/performance.md
Fixes #30228
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/7c73acb93d5c0ffe7e1f4430410b599c89c62959/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-30262) |
=> Performance article updates 8.0

aspnetcore/blazor/advanced-scenarios.md
Fixes #30263
---
|:--|:--|
| [aspnetcore/blazor/advanced-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/189893980a64ffa4ce1b9f5d566a66ccecef2f05/aspnetcore/blazor/advanced-scenarios.md) | [ASP.NET Core Blazor advanced scenarios (render tree construction)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?branch=pr-en-us-30264) |
=> Advanced Scenarios article updates 8.0

aspnetcore/performance/memory.md
Improving the section about `GC.Collect` usage in "Memory management and garbage collection (GC) in ASP.NET Core".
---
|:--|:--|
| [aspnetcore/performance/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b6ef1d391f7b567d007ad3a14ed1e0393fb8884/aspnetcore/performance/memory.md) | [Memory management and garbage collection (GC) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/memory?branch=pr-en-us-30202) |
=> Clarify GC.Collect guidance in memory management doc

aspnetcore/log-mon/metrics/metrics.md, aspnetcore/log-mon/metrics/metrics/samples/EnrichMetrics/EnrichMetrics.csproj, aspnetcore/log-mon/metrics/metrics/samples/EnrichMetrics/Program.cs, aspnetcore/log-mon/metrics/metrics/samples/EnrichMetrics/appsettings.json
Fixes #30230
cc @JamesNK  copy/paste of your code.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/f6164edac18dbde88bbdd95834574727bcd60e39/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30272) |
=> enrich metrics snippet to project file

aspnetcore/test/troubleshoot-azure-iis.md
Document https://github.com/dotnet/aspnetcore/issues/46544
---
|:--|:--|
| [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/e1cdb578704d304f502125c5ad03694729f4e2ca/aspnetcore/test/troubleshoot-azure-iis.md) | [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?branch=pr-en-us-30237) |
=> IIS null service

aspnetcore/tutorials/web-api-help-pages-using-swagger.md, aspnetcore/tutorials/web-api-help-pages-using-swagger/includes/web-api-help-pages-using-swagger7.md
contributes to #30067
---
|:--|:--|
| [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/dotnet/AspNetCore.Docs/blob/88081c55b4f91539f124778e3f227b6a50d1955d/aspnetcore/tutorials/web-api-help-pages-using-swagger.md) | [ASP.NET Core web API documentation with Swagger / OpenAPI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?branch=pr-en-us-30290) |
=> secure swag prep

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30297
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/91ea6855922c4850bcf25fecc6c17678d91df8db/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30299) |
=> secure swag

aspnetcore/fundamentals/logging/index.md
Fixes #30294
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/d1d65e8595b5f589d7b403a67cd16469130fa508/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-30298) |
=> logging with dot on linux /7

aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/38afc5e9c90b2f38934e5dfbcf312363cbed2f54/aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md) | [Deployment layout for ASP.NET Core hosted Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-deployment-layout?branch=pr-en-us-30313) |
=> Add NOTE on upcoming BWA coverage

aspnetcore/blazor/call-web-api.md, aspnetcore/blazor/components/lifecycle.md, aspnetcore/blazor/components/quickgrid.md, aspnetcore/blazor/components/render-modes.md, aspnetcore/blazor/components/rendering.md, aspnetcore/blazor/components/synchronization-context.md, aspnetcore/blazor/file-uploads.md, aspnetcore/blazor/forms-and-input-components.md, aspnetcore/blazor/fundamentals/configuration.md, aspnetcore/blazor/fundamentals/handle-errors.md, aspnetcore/blazor/globalization-localization.md, aspnetcore/blazor/includes/location-client-and-server-net31-or-later.md, aspnetcore/blazor/includes/location-client-and-server-net6-or-later.md, aspnetcore/blazor/includes/location-client-and-server-net7-or-later.md, aspnetcore/blazor/includes/location-client-and-server-net8-or-later.md, aspnetcore/blazor/includes/location-client.md, aspnetcore/blazor/includes/location-server.md, aspnetcore/blazor/index.md, aspnetcore/blazor/project-structure.md
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/960069cf0729ad29ba03245166edb76cc6da20b2/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-30314) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/960069cf0729ad29ba03245166edb76cc6da20b2/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-30314) |
| …
=> Render mode content changes

aspnetcore/fundamentals/logging/index.md
This reverts commit fbc35fcb6801102dabd14c1637fda1809d53c77c.
@Rick-Anderson ... Just to unblock the *Merge to Live* build, I'd like to revert that Logging doc change. GH isn't allowing a quick conflict resolution with the online tools. I'll put a PR in to update that line after I unblock and merge to live, which is a high priority merge this morning for Blazor docs.
Hopefully, this will clear it ...... and not make things ***worse.*** 🤞🍀 
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/740073390b52eda3ea498869600bc919be91bf87/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-3 …
=> Revert "Update index.md (#30306)"

aspnetcore/blazor/forms-and-input-components.md
Fixes #30323
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d8ee9762195666a51da6979bedf0b7b4767d8cb/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30324) |
=> Remove suppress-error attr NOTE

aspnetcore/blazor/project-structure.md
Per https://github.com/dotnet/aspnetcore/pull/49801/commits/4269d5db284f08a7b409c7fa438a73334b23e28b.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/4420774d52743616dd824b259cb4231102916047/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-30327) |
=> Drop launchSettings.json for BWA

aspnetcore/release-notes/aspnetcore-8.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/72572fa3fd053282be8ce85839e5518cf1624a20/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30330) |
=> Move Blazor entry

aspnetcore/migration/70-80.md
Fixes #30303
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/074ac8c5ed39d6fa0e5c91d5fbc9ae36fe19d704/aspnetcore/migration/70-80.md) | [aspnetcore/migration/70-80](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30304) |
=> MIgrate to 8 /1

aspnetcore/migration/70-80.md, aspnetcore/toc.yml
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/47326c0ef26fd368cdedd7a885487eca8f94a550/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30335) |
=> MIgration TOC

aspnetcore/blazor/project-structure.md
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/ea95eda58c6dca541698b4497f61dd129a704fe7/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-30359) |
=> Project structure article updates 8.0

aspnetcore/blazor/tooling.md
Addresses  #28161
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/5498ba542ebb41eb2d1b0705ab4abb7640f75c76/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-30365) |
=> Add manual debug/build assets guidance for VSC

aspnetcore/log-mon/metrics/metrics/samples/metric-tests/BasicTests.cs
=> update WebMetric test for RC1

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
Part of https://github.com/dotnet/aspnetcore/issues/50275.
=> Update form mapping docs

aspnetcore/blazor/security/server/index.md
Fixes #30385
Thanks again, @tolubewaji! 🎸
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e0094f17822467470482d598428ca9d29a4f556f/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-30386) |
=> Fix bad example

aspnetcore/fundamentals/routing.md
Fixes #30410
---
|:--|:--|
| [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/67beb6397ade5e0cbe7663659e70d71447481483/aspnetcore/fundamentals/routing.md) | [Routing in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-30409) |
=> routing.md: fixed lazy matching definition

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md, aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
=> antiforger is available in .NET 8 /1

aspnetcore/diagnostics/rdg001.md, aspnetcore/diagnostics/rdg002.md, aspnetcore/diagnostics/rdg003.md, aspnetcore/diagnostics/rdg004.md, aspnetcore/diagnostics/rdg005.md, aspnetcore/diagnostics/rdg006.md, aspnetcore/diagnostics/rdg007.md, aspnetcore/diagnostics/rdg008.md, aspnetcore/diagnostics/rdg009.md, aspnetcore/diagnostics/rdg010.md, aspnetcore/diagnostics/rdg011.md, aspnetcore/diagnostics/rdg012.md, aspnetcore/diagnostics/rdg013.md
Fixes #30423
---
|:--|:--|
| [aspnetcore/diagnostics/rdg001.md](https://github.com/dotnet/AspNetCore.Docs/blob/65cb8fea57329b1b72afc1f4674a771f0dcf5975/aspnetcore/diagnostics/rdg001.md) | [aspnetcore/diagnostics/rdg001](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/rdg001?branch=pr-en-us-30446) |
| [aspnetcore/diagnostics/rdg002.md](https://github.com/dotnet/AspNetCore.Docs/blob/65cb8fea57329b1b72afc1f4674a771f0dcf5975/aspnetcore/diagnostics/rdg002.md) | [aspnetcore/diagnostics/rdg002](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/rdg002?branch=pr-en-us-30446) |
| [aspnetcore/diagnostics/rdg003.md](https://github.com/dotnet/AspNetCore.Docs/blob/65cb8fea …
=> Dump some content

aspnetcore/log-mon/metrics/metrics.md
Fixes #30184
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/659b9a240fd7582d3a7b05e1b6827a7de3953f5a/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30453) |
=> add dotnet-counters example for custom meter

aspnetcore/grpc/aspnetcore.md, aspnetcore/grpc/aspnetcore/includes/aspnetcore3.md, aspnetcore/grpc/aspnetcore/includes/aspnetcore3_1.md, aspnetcore/grpc/aspnetcore/includes/aspnetcore5.md, aspnetcore/grpc/aspnetcore/includes/aspnetcore6.md, aspnetcore/grpc/aspnetcore/includes/aspnetcore7.md, aspnetcore/includes/net-core-prereqs-vs-3.1.md, aspnetcore/includes/net-prereqs-vs-6.0.md
Fixes #30120 
Fixes #30459
- Fixed prereqs for versions 3.0 through 8.0
- Moved topic to versioning by include organization.
---
|:--|:--|
| [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/b7b53159f3caf7fccd8a9acc663ed5a665bb0fee/aspnetcore/grpc/aspnetcore.md) | [gRPC services with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?branch=pr-en-us-30445) |
=> gRPC services Prereq update plus versioning by include

aspnetcore/migration/70-80.md
Fixes #30451 
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/3f66ac9257fc350ce16ae3c7d34246e2d5b8fa99/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30461) |
=> Update migration 7.0-8.0

aspnetcore/performance/timeouts.md
Fixes #30431 
---
|:--|:--|
| [aspnetcore/performance/timeouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdbd261b37021869ca01b99ef0b4b4f686667a14/aspnetcore/performance/timeouts.md) | [Request timeouts middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/timeouts?branch=pr-en-us-30456) |
=> Note timeout behavior when debugging

aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md, aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md, aspnetcore/toc.yml
Fixes #30462
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a1719d103350bc32f66737591eb2c538cf53b45/aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md) | [Turn Map methods into request delegates with the ASP.NET Core Request Delegate Generator](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg?branch=pr-en-us-30465) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a1719d103350bc32f66737591eb2c538cf53b45/aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md) | [ASP.NET Core Request Delegate Generator (RDG) …
=> add RGD to TOC /8

aspnetcore/security/authentication/mfa.md
Updated the OpenID Connect flow to use Code flow with PKCE
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/mfa.md
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa
Fixes #30467
---
|:--|:--|
| [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/979ad2274070aacd581c05a08d30c7011abb04c4/aspnetcore/security/authentication/mfa.md) | [Multi-factor authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?branch=pr-en-us-30435) |
=> MFA authentication switched  OIDC flow to code flow using PKCE

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md
Fixes #30475
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md](https://github.com/dotnet/AspNetCore.Docs/blob/ae41b25d08a689b211fec200e6265539d3d13ab5/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md) | [RDG002: Unable to resolve endpoint handler](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg002?branch=pr-en-us-30490) |
=> Move snippets to project file /5

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md, aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md, aspnetcore/fundamentals/aot/request-delegate-generator/rgd_ids.md, aspnetcore/toc.yml
Fixes #30487
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md](https://github.com/dotnet/AspNetCore.Docs/blob/69ce12f92b2ce45d0ec044ccc766040ba31aa9ab/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md) | [RDG001: Unable to resolve route pattern](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg001?branch=pr-en-us-30488) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md](https://github.com/dotnet/AspNetCore.Docs/blob/69ce12f92b2ce45d0ec044ccc766040ba31aa9ab/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md) | ["RDG003: Unable to resolve …
=> Remove RDG001 and 03 /8

aspnetcore/migration/webapi.md
Changed `ProductController` to `ProductsController` to match the rest of the document and the example code.
---
|:--|:--|
| [aspnetcore/migration/webapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/a95fb6efb6e2dfba145f586239eaecce2869ef9d/aspnetcore/migration/webapi.md) | [Migrate from ASP.NET Web API to ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/migration/webapi?branch=pr-en-us-30505) |
=> typo: webapi.md

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md
Fixes #30477
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md](https://github.com/dotnet/AspNetCore.Docs/blob/a1af54a2a866d81cc3ad65bca39ef80d78f63cf3/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md) | [RDG004: Unable to resolve anonymous type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg004?branch=pr-en-us-30509) |
=> Rdg004 update /8

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md
Fixes #30478
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md](https://github.com/dotnet/AspNetCore.Docs/blob/2ac229165d7530e228aa133e5dcd970c5caa241d/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md) | [RDG005: Invalid abstract type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg005?branch=pr-en-us-30511) |
=> Add Rg005 sample

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md, aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md
Fixes #30515
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md](https://github.com/dotnet/AspNetCore.Docs/blob/d4f1c0c9b5e6e7a68c1ddf3bca4b571caa536c9d/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md) | [RDG005: Invalid abstract type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg005?branch=pr-en-us-30519) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md](https://github.com/dotnet/AspNetCore.Docs/blob/d4f1c0c9b5e6e7a68c1ddf3bca4b571caa536c9d/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md) | ["RDG006: Invalid constructor …
=> RDG006 error update /8

aspnetcore/migration/inc/blazor.md
Fixes #30524
---
|:--|:--|
| [aspnetcore/migration/inc/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/549f7720b153dedc293c46846aebf44ba91ffbf3/aspnetcore/migration/inc/blazor.md) | [Enable ASP.NET Core Blazor support with Yarp in incremental migration](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?branch=pr-en-us-30525) |
=> Update blazor.md to note it's for Blazor Server

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md
Fixes #30479
Needs to be merged after https://github.com/dotnet/AspNetCore.Docs.Samples/pull/200
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md](https://github.com/dotnet/AspNetCore.Docs/blob/c2e84c39ef01024cb9dc06759e47f7065da9181f/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md) | [RDG007: No valid constructor found](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg007?branch=pr-en-us-30527) |
=> move rdg7 example to samples

aspnetcore/blazor/components/rendering.md
Fixes #30504
---
|:--|:--|
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/656b333a55eae11070fa3cbb90ff1b1f686c1111/aspnetcore/blazor/components/rendering.md) | [ASP.NET Core Razor component rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?branch=pr-en-us-30538) |
=> Streaming rendering and buffering

aspnetcore/blazor/forms-and-input-components.md
Fixes #30436
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/faae88ae29df0b1a05e268784b5fd2a00eba85f4/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30540) |
=> Submit an SSR plain form with JS

aspnetcore/blazor/javascript-interoperability/index.md
Fixes #30437
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/110f7ddfd0a3da997852cec110009ee24e867d74/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-30541) |
=> Add IsBrowser for JS interop scenarios

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md
Fixes #30485
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md](https://github.com/dotnet/AspNetCore.Docs/blob/377471fde2d02474deb3660b02e4626505d02013/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md) | [RDG013: Invalid source attributes](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg013?branch=pr-en-us-30522) |
=> Update RDG013 sampe /8

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md, aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md
Fixes #30483
Needs to me merged after https://github.com/dotnet/AspNetCore.Docs.Samples/pull/202
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md](https://github.com/dotnet/AspNetCore.Docs/blob/7afa62e2499c0867e92993167014bdd3137ac7c0/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md) | [RDG007: No valid constructor found](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg007?branch=pr-en-us-30531) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md](https://github.com/dotnet/AspNetCore.Docs/blob/7afa62e2499c0867e92993167014bdd3137ac7c0/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostic …
=> add rdg011 code examples

aspnetcore/blazor/hybrid/routing.md
Addresses #28401
---
|:--|:--|
| [aspnetcore/blazor/hybrid/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/0be1a2902f4d78a8f1fd7b293caa816d483bc1ca/aspnetcore/blazor/hybrid/routing.md) | [ASP.NET Core Blazor Hybrid routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?branch=pr-en-us-30551) |
=> Update deep linking remark

aspnetcore/migration/inc/adapters.md, aspnetcore/migration/inc/overview.md, aspnetcore/migration/inc/samples/unit-testing/Program.cs, aspnetcore/migration/inc/unit-testing.md, aspnetcore/toc.yml
Fixes #30549 
---
|:--|:--|
| [aspnetcore/migration/inc/adapters.md](https://github.com/dotnet/AspNetCore.Docs/blob/72dcf6dbd601f056e50c61a6ecc416d9e2ecffc2/aspnetcore/migration/inc/adapters.md) | [System.Web adapters](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/adapters?branch=pr-en-us-30560) |
| [aspnetcore/migration/inc/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/72dcf6dbd601f056e50c61a6ecc416d9e2ecffc2/aspnetcore/migration/inc/overview.md) | [Incremental ASP.NET to ASP.NET Core update](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?branch=pr-en-us-30560) |
| [aspnetcore/migration/inc/unit-testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/72dcf6dbd601f056e50c61a6ecc416d9e2ecffc2/aspn …
=> Add to toc and edit pass

aspnetcore/security/authentication/community.md
- Added some good OSS identity provider solutions to the community oss authentication options page.
- Small formatting fixes
- Renamed IdentityServer to Duende IdentityServer
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/community
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/community.md
---
|:--|:--|
| [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/e01cd42b6bd49185cc59aaf65643b6fc105170be/aspnetcore/security/authentication/community.md) | [Community OSS authentication options for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/community?branch=pr-en-us-30557) |
=> Updated community oss authentication options

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md, aspnetcore/toc.yml
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md](https://github.com/dotnet/AspNetCore.Docs/blob/02f289a36f3eaba228c541e77dd7301cc2272745/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md) | [RDG009: Invalid nested AsParameters](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg009?branch=pr-en-us-30568) |
=> Fix Rdg009

.github/ISSUE_TEMPLATE/customer-feedback.yml
=> Create template for unified feedback control

aspnetcore/docfx.json
Add the labels "Source - Docs.ms" and ":watch: Not Triaged" to issues created by the feedback control
=> Add labels to issues created by the feedback control

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md
Fixes #30484
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/207 needs to be merged first
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md](https://github.com/dotnet/AspNetCore.Docs/blob/3caa5d1ec80e0cc9ade3d1af2d44fe605cf8f924/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md) | [RDG012: Unable to resolve inaccessible type](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg012?branch=pr-en-us-30579) |
=> add RDG012 example

aspnetcore/security/identity-management-solutions.md
Small product naming fix
---
|:--|:--|
| [aspnetcore/security/identity-management-solutions.md](https://github.com/dotnet/AspNetCore.Docs/blob/b0d88c744512f1f53babb879e7e07a6783db7699/aspnetcore/security/identity-management-solutions.md) | [Identity management solutions for .NET web apps](https://review.learn.microsoft.com/en-us/aspnet/core/security/identity-management-solutions?branch=pr-en-us-30598) |
=> Rename Microsoft Entra to Microsoft Entra ID

aspnetcore/tutorials/choose-web-ui.md
[Internal review: Choose an ASP.NET Core web UI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-8.0&branch=pr-en-us-30569)
Fixes #30497
- Revised the Choose a web UI topic to lead with Blazor as the recommend web UI approach.
- Added mentions that MVC & Razor Pages as mature and supported alternatives to Blazor.
- Removed the server-render vs client render content since you no longer must choose. With Blazor in .NET 8 you get both from the same app (and more).
- Verified we still mention that Blazor can be integrated with existing MVC & Razor Pages apps if desired. We do, see last section _Choose a hybrid solution: ASP.NET Core MVC or Razor Pages plus Blazor_,
I am reusing some key Blazor introductions already approved and published for .NET 8 …
=> 8.0 Update for Choose a web UI

.github/ISSUE_TEMPLATE/customer-feedback.yml
Clarify Article information section intro text, explain usage of doc id, correct doc id field label.
=> Clarify Article information section intro text

aspnetcore/toc.yml
part of https://github.com/dotnet/AspNetCore.Docs/issues/30559
=> update identity menus => ASP.NET Core Identity

aspnetcore/mvc/models/file-uploads/samples/5.x/LargeFilesSample/Controllers/FileUploadController.cs
Fixes #30474
Addresses #30473
Thanks @mulei2023! 🚀
=> Remove the quotes from boundary

aspnetcore/toc.yml
fixes https://github.com/dotnet/AspNetCore.Docs/issues/30609
=> Add a link to Microsoft Identity Web wiki

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md
Fixes #30596
Needs to be merged after https://github.com/dotnet/AspNetCore.Docs.Samples/pull/214
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md](https://github.com/dotnet/AspNetCore.Docs/blob/f52ea73fb5e444c7af6039ba2bc60d6ed0703001/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md) | [RDG010: InvalidAsParameters Nullable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg010?branch=pr-en-us-30613) |
=> add RDG010 example

aspnetcore/toc.yml
This should make it better to find authn solutions
=> Re-organize and rename some authentication menus

aspnetcore/host-and-deploy/iis/advanced.md
Fixes #30603 
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/d2d71ec478287fb4cbb23a7054c47048a246d6b1/aspnetcore/host-and-deploy/iis/advanced.md) | [Advanced configuration of the ASP.NET Core Module and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-30621) |
=> Remove outdated link

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md, aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md
Contributes to #30480
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md](https://github.com/dotnet/AspNetCore.Docs/blob/f304913a9367beb48974a0642e91056b940b39ea/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md) | [RDG007: No valid constructor found](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg007?branch=pr-en-us-30625) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md](https://github.com/dotnet/AspNetCore.Docs/blob/f304913a9367beb48974a0642e91056b940b39ea/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md) | ["RDG008: Multiple public …
=> Fix RDG8 /8

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md](https://github.com/dotnet/AspNetCore.Docs/blob/271cc40e45bf4c68bd8b6780653e92e7c043e0d5/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md) | [RDG008: Multiple public constructors](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg008?branch=pr-en-us-30627) |
=> New snippet /8

aspnetcore/toc.yml
fixes https://github.com/dotnet/AspNetCore.Docs/issues/30630
=> index link is missing in security authentication menu

aspnetcore/client-side/spa/intro.md, aspnetcore/includes/spa-templates-recommend-vs.md
Fixes #30634 
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?view=aspnetcore-8.0&branch=pr-en-us-30635)
---
|:--|:--|
| [aspnetcore/client-side/spa/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/5437755d444a0d9c3de6ad1aa5cfc328f798bd0e/aspnetcore/client-side/spa/intro.md) | [Overview of Single Page Applications (SPA) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?branch=pr-en-us-30635) |
=> Run SPA projects by using CLI

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md](https://github.com/dotnet/AspNetCore.Docs/blob/965131a0467ae70ba7aa3953db8ad2aa0f91048e/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md) | [RDG010: InvalidAsParameters Nullable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg010?branch=pr-en-us-30638) |
=> Fix RDG010 content

aspnetcore/toc.yml
improve security authentication menus
=> Move identity social providers into Identity

.github/ISSUE_TEMPLATE/customer-feedback.yml
=> Remove issue type field

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30349
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/72294df02c6b8a241329b7c9c2ed20bcc1a5e8b8/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30677) |
=> Keyed services to What's new /7

aspnetcore/toc.yml
fixes https://github.com/dotnet/AspNetCore.Docs/issues/30648
=> Security menu: Choose an identity solution

aspnetcore/fundamentals/minimal-apis/includes/webapplication.md, aspnetcore/mvc/controllers/dependency-injection.md
Fixes #30345
Fixes #30679
* [Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0&branch=pr-en-us-30678#access-the-dependency-injection-di-container)
* [Internal review URL2](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-8.0&branch=pr-en-us-30678#action-injection-with-fromkeyedservices)
---
|:--|:--|
| [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/a97314b02b9a31ad9047829dbb3cf319237dce61/aspnetcore/mvc/controllers/dependency-injection.md) | [Dependency injection into controllers in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection? …
=> Key Services DI /8

aspnetcore/fundamentals/dependency-injection.md
Fixes #30682
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/4345d66b6d192543f807a7208d4a739c942a12c8/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-30683) |
=> Add keyed services

aspnetcore/test/troubleshoot-azure-iis.md
This error causes everything until the following code block to appear as code rather than rendered Markdown.
---
|:--|:--|
| [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/f89f26d8d28d4950405e6b9b36dec5142fe9b9e7/aspnetcore/test/troubleshoot-azure-iis.md) | [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?branch=pr-en-us-30685) |
=> Fix Markdown syntax error

aspnetcore/blazor/fundamentals/routing.md
Fixes #30687
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/127111bfc8466e6320a71150984682f1bb99ac94/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-30688) |
=> Fix section name in link

.repoman.yml
@tdykstra 
I need someone to ping me on Teams so that I can share the new endpoint with them
=> Update .repoman.yml to latest github issue system

.github/workflows/new-blazor-issue.yml
cc: @Rick-Anderson @wadepickett @tdykstra ... Let's see if I have any luck 🤞🍀 with this workflow approach. If this runs, and I think it will, at least I'll get the pings back. Further, I'd hope to expand it to assign me, modify the labels, and add the Blazor project. I have a bit of time right now to work on this, and perhaps we'll get something cook'in here!
=> Create a Blazor issue workflow

.github/workflows/new-blazor-issue.yml
=> Add Blazor label

.github/workflows/new-blazor-issue.yml
=> Update Blazor workflow

aspnetcore/fundamentals/native-aot.md
Fixes #30730 
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/91a2ccc058a8214f34777253d1c78c2c9966b32c/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-30731) |
=> Update link, remove old link

aspnetcore/signalr/hubs.md
Fixes #30348
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/228 shows PU review and approval.
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-8.0&branch=pr-en-us-30744#keyed-services-support-in-dependency-injection)
---
|:--|:--|
| [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/4ab40415279539139f695e14a5c1f63e5e675c6d/aspnetcore/signalr/hubs.md) | [Use hubs in SignalR for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/hubs?branch=pr-en-us-30744) |
=> Hub key svc

aspnetcore/log-mon/metrics/metrics.md, aspnetcore/toc.yml
Fixes #29731
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0&branch=pr-en-us-30745)
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/5377b8ddb2a591554b8d026885bb1f6d06211454/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30745) |
=> metrics /7

.github/workflows/issue-processing.yml
=> Workflow updates

.github/workflows/issue-processing.yml
=> Update issue workflow

aspnetcore/security/authentication/index.md
Fixes #30472
---
|:--|:--|
| [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/326c4b3109c5837a3d83576799082f30ef99f24d/aspnetcore/security/authentication/index.md) | [Overview of ASP.NET Core authentication](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/index?branch=pr-en-us-30486) |
=> Add Finbuckle.MultiTenant

.github/workflows/issue-processing.yml
=> Issue workflow update

aspnetcore/fundamentals/http-logging/index.md, aspnetcore/fundamentals/http-logging/samples/8.x/HttpLoggingSample.csproj, aspnetcore/fundamentals/http-logging/samples/8.x/Program.cs, aspnetcore/fundamentals/http-logging/samples/8.x/appsettings.Development.json, aspnetcore/fundamentals/http-logging/samples/8.x/appsettings.json
Contributes to #30642 
---
|:--|:--|
| [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ee6a00bfaf6ce810526608106be151b6878f1692/aspnetcore/fundamentals/http-logging/index.md) | [HTTP Logging in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/index?branch=pr-en-us-30784) |
=> make 8.x copy of sample

aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30813
Changing `UseStatefulReconnect` to `WithStatefulReconnect`.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/21d7229a9e478febabad813440ec80f8e55584cc/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30815) |
=> What's New: SignalR typo fix

aspnetcore/blazor/file-uploads.md
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/59cb791c7437b2e2f6c110bb52791f36c7c5d547/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30818) |
=> Add PU PR tracking link

aspnetcore/tutorials/first-web-api/samples/7.0/TodoApi/Controllers/WeatherForecastController.cs
Indenting the first elements in the generated example of a new project ASP.NET Core Web API.
=> Indent first elements in WeatherForecastExample

aspnetcore/fundamentals/minimal-apis.md, aspnetcore/fundamentals/minimal-apis/includes/minimal-apis7.md, aspnetcore/fundamentals/minimal-apis/includes/webapplication.md
Contributes to #30644
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/b3e36c3c4f8ae021c3a2f7d2803409d36be6080e/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-30830) |
=> Mon prep /7

aspnetcore/fundamentals/minimal-apis/security.md
Adding the nuget package that is being used in the main text.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/2ddef46e9512ebcd9c8dc8915cf1df7827b63395/aspnetcore/fundamentals/minimal-apis/security.md) | [Authentication and authorization in minimal APIs](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?branch=pr-en-us-30793) |
=> Clarifying the Minimal API Authentication example.

aspnetcore/migration/70-80.md
Fix "Replace" spelling error.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf92e3fc4cf8481411772d823721afd3e0bf85c7/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30835) |
=> Fix "Replace" spelling error.

aspnetcore/release-notes/aspnetcore-8.0.md
Contributes to #30642
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/432216db7acb90d433c244339f695ec6eccb480d/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30838) |
=> WN: HTTP Logging and Acrolinx

aspnetcore/blazor/fundamentals/signalr.md
Addresses #30843
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/3c5018a1a9c6e004d84e7973ad664eb211b5f8fc/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-30846) |
=> Update option location guidance

aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0&branch=pr-en-us-30832#secure-binding-from-iformfile-and-iformfilecollection)
Fixes #30644
=> IForm binding /7

aspnetcore/blazor/fundamentals/signalr.md
Addresses #30843
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/c7a5bce58e19903570944895de9ba3f4bd6482d0/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-30856) |
=> Version API list

aspnetcore/blazor/webassembly-lazy-load-assemblies.md
---
|:--|:--|
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/e55dca1d3c59edb42d5aebf52693ba599bde484e/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?branch=pr-en-us-30858) |
=> Drop Blazor Server language 8.0

aspnetcore/blazor/globalization-localization.md
Addresses #30002
cc: @mkArtakMSFT @danroth27 ... This finishes the second of three Glob/Loc article updates for 8.0. The third is an approach for BWAs that spans both server-side and client-side (i.e., `Auto` render mode). I'll get back to look at it as soon as I can.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b816ed1c3d8b3e9e6d691a239c69fda88287734/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-30860) |
=> Dynamic server-side culture selection (BWA) 8.0

aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Pulling updated code from the snippet sample repo.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/69af823c82b7cf1c433313e1e9a3c17d32c41bcf/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-30861) |
=> Pull updated code examples

aspnetcore/fundamentals/servers/httpsys.md
Fixes #30518 
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/c5b09a9f6c8a76dc804770475d55627c17459428/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-8.0&branch=pr-en-us-30879) |
=> Note wildcard options, link to tracing info

aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/ConfigSample.csproj, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Options/ArrayExample.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Options/MyConfigServiceCollectionExtensions.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Options/NameTitleOptions.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Options/PositionOptions.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/Array.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/Index2.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/Test21.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/Test33.cshtml, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/Test33.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/TestNum.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/TestSection.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/TestSection2.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/TestSection4.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Pages/XML/Index.cshtml.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/Program.cs, aspnetcore/fundamentals/configuration/index/samples/8.x/ConfigSample/appsettings.Development.json, aspnetcore/includes/bind7.md
=> Add new bind sample /8

aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md, aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md, aspnetcore/toc.yml
Fixes #30641
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md](https://github.com/dotnet/AspNetCore.Docs/blob/e58b5f0a448e490cc6a24544364b8988a9c5d277/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md) | [RDG009: Invalid nested AsParameters](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg009?branch=pr-en-us-30906) |
=> fix RDG9 /8

aspnetcore/blazor/host-and-deploy/index.md
Fixes #30901
Thanks @istoyneva! 🚀
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/5af84fd3a9ca403c27a8939634a88c9ead9ad1f1/aspnetcore/blazor/host-and-deploy/index.md) | [Host and deploy ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-30913) |
=> Improve description and add XREF

aspnetcore/blazor/file-uploads.md
Fixes #30914
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/da59f14635eaf939ce53dce89b9fa4a27564b84d/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30915) |
=> CSR/BWA/web API updates 8.0
