dotnet/AspNetCore.Docs

- aspnetcore/introduction-to-aspnet-core.md
- aspnetcore/migration/proper-to-2x/mvc2.md
- aspnetcore/toc.yml
Fixes #30161
See [New Visual Studio templates](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-7/#new-visual-studio-templates)
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-8.0&branch=pr-en-us-30162)
---
|:--|:--|
| [aspnetcore/migration/proper-to-2x/mvc2.md](https://github.com/dotnet/AspNetCore.Docs/blob/eaec76c15c26e6e156e09bbf7fcc308d1545c584/aspnetcore/migration/proper-to-2x/mvc2.md) | [Migrate from ASP.NET to ASP.NET Core 2.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/mvc2?branch=pr-en-us-30162) |
> add external link to Vue

- aspnetcore/log-mon/metrics/metrics.md
ASP.NET Core has built-in support for `IMeterFactory`. We want to encourage people to write metrics that integrates with DI.
This PR expands the section on writing custom metrics to include a sample of DI-integrated metrics.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/c71b0eff02f646d9bb86fd38ecb103dfd2f39ce0/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30073) |
> Add IMeterFactory best practice to ASP.NET Core metrics

- aspnetcore/blazor/file-downloads.md
- aspnetcore/blazor/images.md
- aspnetcore/blazor/includes/location-client-and-server-net6-or-later.md
- aspnetcore/blazor/includes/location-client-and-server-net7-or-later.md
- aspnetcore/blazor/includes/location-client-and-server-net8-or-later.md
Fixes #30181
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9c040649a2b9872918f965ba53e74ac0991b898/aspnetcore/blazor/file-downloads.md) | [ASP.NET Core Blazor file downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-30196) |
| [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9c040649a2b9872918f965ba53e74ac0991b898/aspnetcore/blazor/images.md) | [Work with images in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/images?branch=pr-en-us-30196) |
> Images article updates 8.0

- aspnetcore/blazor/host-and-deploy/webassembly.md
Corrected documentation to reflect the compression flag name change from BlazorEnableCompression to CompressionEnabled as described here https://github.com/dotnet/aspnetcore/issues/50451#issuecomment-1702809005
Fixes #30213
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/6011ee846f30c6f135c6b6c07c0e8d37647d7c98/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-30214) |
> Change Blazor WASM compression flag

- aspnetcore/fundamentals/best-practices.md
The LOH threshold is 85,000 bytes, it's a little confusing whether the `85 KB` means 85000 bytes or 85 * 1024 bytes
---
|:--|:--|
| [aspnetcore/fundamentals/best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/fbe44087532735c9276061373cbe96847af7308a/aspnetcore/fundamentals/best-practices.md) | [ASP.NET Core Best Practices](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?branch=pr-en-us-30252) |
> update LOH threshold

- aspnetcore/blazor/index.md
Fixes #29657
Dan, do you have an image for Blazor Web Apps?
The current images are ...
* Blazor Server (will only appear for <8.0 because the *Blazor Server* section only appears for <8.0): https://learn.microsoft.com/en-us/aspnet/core/blazor/index/_static/blazor-server.png
* Blazor WebAssembly: https://learn.microsoft.com/en-us/aspnet/core/blazor/index/_static/blazor-webassembly.png
---
|:--|:--|
| [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/596e277e96b3c6bfd1dd62e9f792a49ac3cd13d0/aspnetcore/blazor/index.md) | [ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/index?branch=pr-en-us-29659) |
> Blazor Overview updates

- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model3.md
- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model5.md
- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model6.md
Fixes @30266
Next and previous page links for versions 3-5 had an extra bracket, removed it.
[Internal review](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&branch=pr-en-us-30267&tabs=visual-studio#additional-resources)
> MVC Get Started - Add Model - Link Fix

- aspnetcore/fundamentals/logging/index.md
- aspnetcore/fundamentals/logging/index/samples/6.x/WebLog/Program.cs
Fixes #30239
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/7245cc3cc6339240a4015c55ab06c81092b5a651/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-30249) |
> Remove problematic factory.create.logger /7

- aspnetcore/blazor/index.md
A patch to an earlier PR where I missed adding the render mode for >=8.0.
---
|:--|:--|
| [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/d7048df0a117e3ef349063371e81ad3208dd9c11/aspnetcore/blazor/index.md) | [ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/index?branch=pr-en-us-30283) |
> Apply render mode to example

- aspnetcore/fundamentals/logging/index.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/30281
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4914aff9b2c7bebad7ab2753d9bb04c41c9a5fac/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-30288) |
> fix logger /7

- aspnetcore/mvc/models/validation.md
I [misinterpreted expected behavior](https://github.com/dotnet/AspNetCore.Docs/pull/29000#issuecomment-1712026290) from the docs. Added a sentence to hopefully help clarify the expected behavior.
Also, I can't tell if the xref link will resolve correctly since the preview doesn't generate the link. Copied the xref from [here](https://github.com/dotnet/dotnet-api-docs/blob/6eadf345b36fbfd7b6b3ddd30f7ab717c8239382/xml/System.ComponentModel.DataAnnotations/DisplayFormatAttribute.xml#L225C73-L225C73).
---
|:--|:--|
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/3fd066b609903e1709784a6746f4796f04c309e8/aspnetcore/mvc/models/validation.md) | [Model validation in ASP.NET Core MVC and Razor …
> Clarify expected behavior of validation for non-nullable props/params in nullable contexts

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/fundamentals/render-modes.md
- aspnetcore/blazor/hosting-models.md
- aspnetcore/mvc/views/razor.md
- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/toc.yml
Fixes #29861
Fixes #30270
* This has a *brain dump* 🧠💩 feeling cranking it out so quickly. *Future passes can polish up this turd!* 😆 
* Because I don't have RC1 yet, I had to guess on a few behaviors/scenarios.
* I recommend accessing the *Hosting Models* updates first. New content for render modes flows from it.
* I placed the *Render modes* article in the *Fundamentals* node immediately under the overview because ...
* Render modes makes the most sense with examples, but we don't even show a component or explain anything about them until the *Fundamentals* node overview is reached. **UPDATE**: I meant beyond the example in the landing page. The first place we get into a fuller explanation is in the *Fundamentals* overview.
* Render modes activate at the component level …
> Hosting models/render modes & What's New 8.0

- aspnetcore/release-notes/aspnetcore-8.0.md
We removed Open Iconic from the Blazor templates and initially used the Bootstrap icons, but we've switched to using custom SVG instead.
@guardrex 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a3152cc5a5c036ab4fc2fee492a0c2069fd558a/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30308) |
> Clarify that the Blazor templates don't depend on Bootstrap icons

- aspnetcore/blazor/tooling.md
- aspnetcore/blazor/tutorials/build-a-blazor-app.md
- aspnetcore/blazor/tutorials/signalr-blazor-preview.md
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/a31bd7d5562dc07ce0ff46613e85a1250a606b6c/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-30296) |
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/a31bd7d5562dc07ce0ff46613e85a1250a606b6c/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-30296) |
| [aspnetcore/blazor/tutorials/signalr-blazor-preview.md](https://github.com/dotnet/AspNetCore.Docs/blob/a31bd7d5562dc07c …
> Blazor RC1 updates

- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes  #30320
Confirm what I called these in case I'm making up my own 🦖 Blazor framework .... ***again!*** 😆
> To configure the .NET WebAssembly runtime, use the `configureRuntime` property with the `dotnet` runtime host builder.
* `configureRuntime` ... a "***property***"?
* `dotnet` ... the "***runtime host builder***"?
@maraf ... I took your test example for the doc coverage. If either you or Pavel have something better for the example, I'm 👂.
Finally, this is used to configure quite a few runtime-y things. I see what looks like an incomplete list at ...
https://github.com/dotnet/aspnetcore/issues/49264#issuecomment-1628483544
What do we want to say about that (or cross-link for it)?
---
|:--|:--|
| …
> Configure the Blazor WASM runtime

- aspnetcore/razor-pages/index.md
This PR fixes the Create.cshtml.cs page model code snippet which is currently broken on https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio&source=docs:
---
|:--|:--|
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/06729221460d7fa5a51659e938600b1cccad9f0b/aspnetcore/razor-pages/index.md) | [Introduction to Razor Pages in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-30316) |
> Fix broken Create.cshtml.cs page model reference

- aspnetcore/blazor/components/control-head-content.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/index.md
Fixes #30328
---
|:--|:--|
| [aspnetcore/blazor/components/control-head-content.md](https://github.com/dotnet/AspNetCore.Docs/blob/3ef753ed5459dafe8d02f871fe370b81e9ce890b/aspnetcore/blazor/components/control-head-content.md) | [Control `<head>` content in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?branch=pr-en-us-30329) |
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/3ef753ed5459dafe8d02f871fe370b81e9ce890b/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-30329) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.co …
> Blazor router NotFound updates

- aspnetcore/blazor/project-structure.md
This reverts commit 6da4e2fe272ebee81abd0bc26cc73cd95edc7cd2.
***Ooooooops!*** 😵😆 ... It was removed for the ***CLIENT*** project and didn't appear in the client part of the doc in the first place. This PR was just unnecessary. The docs were correct at the outset, and the PU was just fixing a framework problem where the client project had it and should've have had it.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b535bd3a35f243bed3467b2df60535d44bd241b/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-30331) |
> Revert "Drop launchSettings.json for BWA (#30327)"

- aspnetcore/fundamentals/servers/kestrel/http3.md
HTTP/3 standard has been approved.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/http3.md](https://github.com/dotnet/AspNetCore.Docs/blob/37eb22ced444a6e33b83780bbc0e7148c38a468f/aspnetcore/fundamentals/servers/kestrel/http3.md) | [Use HTTP/3 with the ASP.NET Core Kestrel web server](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?branch=pr-en-us-30305) |
> Update HTTP/3 docs with latest state

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/forms-and-input-components.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/tooling.md
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/84c04ee1bc7edcc9bb0e8b2f247f7a44549d4715/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-30339) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/84c04ee1bc7edcc9bb0e8b2f247f7a44549d4715/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-30339) |
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNe …
> Blazor RC1 wrap-up 8.0

- aspnetcore/blazor/hosting-models.md
---
|:--|:--|
| [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/c1f7b4de0d7757a98ba4b1380919d1ec2b8102db/aspnetcore/blazor/hosting-models.md) | [ASP.NET Core Blazor hosting models](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?branch=pr-en-us-30373) |
> Swap 'standalone' for 'static'

- aspnetcore/blazor/forms-and-input-components.md
Fixes #30338
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e8d1d75a042af40fd1ae9bf7476bf35048f5455/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30374) |
> EditContext with IsValid examples update

- aspnetcore/includes/net-prereqs-mac-6.0.md
- aspnetcore/includes/net-prereqs-mac-7.0.md
- aspnetcore/includes/net-prereqs-mac-8.0.md
- aspnetcore/includes/vs-mac-eol.md
- aspnetcore/security/enforcing-ssl.md
- aspnetcore/test/razor-pages-tests.md
- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md
- aspnetcore/tutorials/publish-to-iis.md
Fixes #30217 
This is mainly about getting the notice into tutorials, which it does by adding an include to the VS Mac prerequisites includes.
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/b81dfafa9726c785159ca0758ff3be7e341b11a7/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-30382) |
| [aspnetcore/test/razor-pages-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/b81dfafa9726c785159ca0758ff3be7e341b11a7/aspnetcore/test/razor-pages-tests.md) | [Razor Pages unit tests in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?branch=pr-en-us-30382) |
| …
> Note VS for Mac EOL

- aspnetcore/includes/signalr-typescript-webpack/npm-run-release.md
- aspnetcore/tutorials/signalr-typescript-webpack.md
- aspnetcore/tutorials/signalr-typescript-webpack/includes/signalr-typescript-webpack6.md
- aspnetcore/tutorials/signalr-typescript-webpack/includes/signalr-typescript-webpack7.md
There is a little error in the sample: if you follow the tutorial, the `npm run release` fails because it looks for html/css/ts files in the src folder but the tutorial says to create these files in the project root.
My favourite solution is to create the _src_ folder and then put these files into this folder. I modified the tutorial to follow this solution.
Thanks!
Samuele
---
|:--|:--|
| [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/dotnet/AspNetCore.Docs/blob/7adf0ef7219ac7d78e49d5a9d553a119a9fb3827/aspnetcore/tutorials/signalr-typescript-webpack.md) | [Tutorial: Get started with ASP.NET Core SignalR using TypeScript and Webpack](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?branch=pr-en-us …
> Fix client side files position

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/state-management.md
Fixes #30391
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/93d0aea88741fb1831094711649dee6347960e21/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-30397) |
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/93d0aea88741fb1831094711649dee6347960e21/aspnetcore/blazor/security/server/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-30397) |
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNe …
> Disable prerendering update 8.0

- .openpublishing.redirection.json
- aspnetcore/blazor/blazor-ef-core.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/toc.yml
- aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod5.md
Fixes #30398
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe5ef89142bce50dfae2604ea026c38570546411/aspnetcore/blazor/blazor-ef-core.md) | [aspnetcore/blazor/blazor-ef-core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-30405) |
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe5ef89142bce50dfae2604ea026c38570546411/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-30405) |
| [aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod5.md](https://github.com/d …
> Blazor with EF Core article updates 8.0

- aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
Fixes #30416
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/43fd738aa2c77a4f95d04025ba59bc3757c6ddc1/aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md) | [Deployment layout for ASP.NET Core hosted Blazor WebAssembly apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-deployment-layout?branch=pr-en-us-30419) |
> Mulitpart bundling package support 8.0

- aspnetcore/grpc/aspnetcore.md
- aspnetcore/grpc/migrate/Server-web.csproj
- aspnetcore/grpc/migration.md
This is useful information for the migration page.
---
|:--|:--|
| [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/6024cd7f84c8e477b613b5cf4eb3d27916f571fc/aspnetcore/grpc/aspnetcore.md) | [gRPC services with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?branch=pr-en-us-30415) |
| [aspnetcore/grpc/migration.md](https://github.com/dotnet/AspNetCore.Docs/blob/6024cd7f84c8e477b613b5cf4eb3d27916f571fc/aspnetcore/grpc/migration.md) | [Migrate gRPC from C-core to gRPC for .NET](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/migration?branch=pr-en-us-30415) |
> Add note to C-core migration about non-ASP.NET Core SDKs

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/prerendering-and-integration.md
- aspnetcore/blazor/components/prerendering.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md
- aspnetcore/blazor/includes/prerendering.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/fundamentals/url-rewriting.md
- aspnetcore/migration/30-to-31.md
- aspnetcore/migration/70-80.md
- aspnetcore/mvc/overview.md
- aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md
- aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md
- aspnetcore/mvc/views/view-components.md
- aspnetcore/razor-pages/index.md
- aspnetcore/razor-pages/index/includes/index35.md
- aspnetcore/release-notes/aspnetcore-3.1.md
- aspnetcore/toc.yml
- aspnetcore/tutorials/choose-web-ui.md
Addresses #30341
This will be at least a two-step process. I'm going to merge this one quickly to get out of the way on non-Blazor node updates (e.g., the ToC changes needed).
I'm just going to use the *old skool* Whole-topic Versioning approach without the INCLUDE because I'm not clear on naming/location for the extra content (in the INCLUDE) and slammed with work right now. I need to keep rolling with the Blazor updates 🏃😅.  I'll leave it to others to structure this article later for the new Whole-topic approach, if desired.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bf213e4b228412f3ec48c7bbf199f65fb5f72cb/aspne …
> Prerender and Integrate work (Round 1)

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/hosting-models.md
- aspnetcore/blazor/index.md
- aspnetcore/release-notes/aspnetcore-3.0.md
- aspnetcore/tutorials/choose-web-ui.md
Fixes #30285
* When 🔪 here, I made sure that the *Hosting Models* and *Components* overview received a couple of items that they didn't have to ensure that we don't lose any coverage. The entire *Components* section of the Blazor overview can be 🔪 because we have all of that coverage back in the *Components* overview article. Assuming that you like the cut, I dropped the content for all versions, but do you want to keep the components coverage for <8.0 coverage?
* I merged the prior *Blazor Web Apps* and *Blazor WebAssembly* content with an emphasis on the former.
* For >=8.0, we don't have a BWA image, and I didn't keep the Blazor WASM image for >=8.0 coverage. Do you want any images in >=8.0 coverage?
---
|:--|:--|
| …
> Blazor overview updates 8.0

- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/prerendering-and-integration.md
- aspnetcore/blazor/components/prerendering.md
- aspnetcore/blazor/file-downloads.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/includes/prerendering.md
- aspnetcore/blazor/security/server/threat-mitigation.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md
- aspnetcore/mvc/views/tag-helpers/built-in/persist-component-state.md
Fixes #30341
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e4f88391f07806994ed1f4ae01a774b3063029b/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30514) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e4f88391f07806994ed1f4ae01a774b3063029b/aspnetcore/blazor/components/prerendering-and-integration.md) | [Prerender and integrate ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration …
> Prerender and Integrate work (Round 2)

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #30535
Thanks @AceHack! :rocket:
BTW ... I still need to know on the other issue that you opened if the original (published) code was still working under .NET 7.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/9039d501212759b82f736890d0195b92ee7cfd0d/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-30542) |
> GitHub page hosting without WasmStripILAfterAOT

- aspnetcore/blazor/host-and-deploy/webassembly.md
~HOLDING this for a bit while we see what investigation turns up on https://github.com/dotnet/aspnetcore/issues/51057.~
**UPDATE**: ***Removing content***, since this now looks like a bug.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/c660d5fd110afd05d698456a29a50e6acf53f0cc/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-30544) |
> Remove guidance

- aspnetcore/performance/rate-limit.md
Fixed grammar mistake in rate limiting documentation
---
|:--|:--|
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/752e39f42f7bd150bbc3fbb3dfbbf2c62504992b/aspnetcore/performance/rate-limit.md) | [Rate limiting middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?branch=pr-en-us-30548) |
> fix: grammar mistake in rate limiting documentation

- aspnetcore/migration/inc/samples/unit-testing/Program.cs
- aspnetcore/migration/inc/unit-testing.md
As discussed in this issue https://github.com/dotnet/systemweb-adapters/issues/401, there are some additional steps that must be followed if the subject under test make use of `HttpRuntime`. 
This PR adds a new subpage **Unit Testing** to [ASP.NET to ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-7.0) and explains how that particular issue can be resolved.
---
|:--|:--|
| [aspnetcore/migration/inc/unit-testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/15be33f0cf3e51aa66fd68df5b20f33205a568b9/aspnetcore/migration/inc/unit-testing.md) | [aspnetcore/migration/inc/unit-testing](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/unit-testing?branch=pr-en-us-30537) |
> Add "Unit Testing" page to .NET Core Incremental Migration

- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/prerendering.md
- aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/components/sections.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/hybrid/troubleshoot.md
- aspnetcore/toc.yml
Fixes #30553
David, I **stole** 🚓👮 a good bit of what you put up. Let me know if you want to add anything or cross-link anything else.
There's a few NIT updates here to the "latest version" INCLUDE that you can ignore. 
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/66d892f3dcabeeac48981460be84eef6a65e1376/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30554) |
| [aspnetcore/blazor/components/prerendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/66d892f3dcabeeac48981460be84eef6a65e1376/aspnetcore/blazor/components …
> Blazor Hybrid troubleshoot article 8.0

- aspnetcore/toc.yml
The links are removed and now part of the community links like all other OSS providers
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/community
> Removed IdentityServer direct links

- aspnetcore/includes/DuendeIdentityServer.md
- aspnetcore/includes/IdentityServer4.md
Fixes #30592
Searched through entire aspnetcore\tutorials node and for anything in aspnetcore/ that has wadepickett in the metadata.
Topics were clean (beyond the gRPC and SignalR nodes which are taken care of in other PR's)
However, I had topics that used includes that needed renaming, so that is what I am updating in this PR.
Found and fixed AAD references here:
aspnetcore/includes/DuendeldentityServer.md  (used in the MongoDB tutorial for example).
aspnetcore/includes/IdentityServer4.md
Checked for:
"Azure Active"
"Azure AD"
"Azure-active"
"Azure-ad"
"AAD" (which brings up 20 random doc ID's that had "aad" in the sequence but no legit AAD hits).
> AAD rename for all content owned by wp

- aspnetcore/grpc/authn-and-authz.md
Fixes #30590
Azure Active Directory rename update for all gRPC topics in the gRPC node.
Criteria: replace "Azure Active Directory," "Azure AD," and "AAD" and looked for any links to docs with those names in the filename or title.
There was just one topic that needed an update in that gRPC node:  authn-and-authz.md
See related issues #30591 and #30592
---
|:--|:--|
| [aspnetcore/grpc/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/210f27d2f27e488dea2452b55084f0da4e8e2556/aspnetcore/grpc/authn-and-authz.md) | [Authentication and authorization in gRPC for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?branch=pr-en-us-30593) |
> AAD rename - gRPC node topics

- aspnetcore/razor-pages/index.md
Code snippet wasn't showing any code, also highlighting the wrong part of the code.
---
|:--|:--|
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e85110d6a0720095a7eea6ccac8ed8b2dcc8a96d/aspnetcore/razor-pages/index.md) | [Introduction to Razor Pages in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-30606) |
> Fix index.md code snippet

- aspnetcore/host-and-deploy/linux-nginx.md
Part of https://github.com/dotnet/aspnetcore/issues/45522, users aren't necessarily noticing/following the SignalR link after the nginx snippet. So we should just add the small bit needed to support websockets to the main snippet.
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/1b7bdb8dae7d2be0e3e6a78d9503a5705088a337/aspnetcore/host-and-deploy/linux-nginx.md) | [Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-30605) |
> Add websocket support to generic nginx docs

- aspnetcore/blazor/forms-and-input-components.md
An example is showing outside of the rest of this section's >=6.0-only content in <6.0 content 😈.
---
|:--|:--|
| [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/d36174811eca12773245dcb7fc66bd665b8c4292/aspnetcore/blazor/forms-and-input-components.md) | [ASP.NET Core Blazor forms and input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?branch=pr-en-us-30650) |
> Versioning repair

- aspnetcore/host-and-deploy/iis/advanced.md
The old docs were confusing because they seemed to indicate that `~/` should work with just Blazor. See https://github.com/dotnet/aspnetcore/issues/51027.
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/44cbb6c3109f4363d1ea205782445e6ce53c674e/aspnetcore/host-and-deploy/iis/advanced.md) | [Advanced configuration of the ASP.NET Core Module and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-30632) |
> Link to Blazor docs in IIS sub-application section

- aspnetcore/fundamentals/minimal-apis/route-handlers.md
According the usual naming convention within .NET `MapGet`, etc. is Pascal-cased, so the term camel-cased is most likely a typo.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/route-handlers.md](https://github.com/dotnet/AspNetCore.Docs/blob/f841052db92cc801f858fb7b1970c8df80f1a468/aspnetcore/fundamentals/minimal-apis/route-handlers.md) | [Route Handlers in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/route-handlers?branch=pr-en-us-30649) |
> Http methods in route-handlers.md are Pascal-cased

- aspnetcore/log-mon/metrics/metrics.md
- aspnetcore/release-notes/aspnetcore-8.0.md
@Rick-Anderson ... In the Metrics article, the absolute links where throwing. Even when I tried to visit them in the browser they 404'ed on me 💥. Therefore, I'm just code-fencing the API in the doc to clear the build. I left the XREF and the absolute links in the article commented out.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/e0557a093b7d7ba73d8fb4a64f5a5c7224f6cd46/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-30668) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/e0557a093b7d7ba73d8fb4a64f5a5c7224f6cd46/aspnetcore/release-note …
> Cross-link updates

- aspnetcore/includes/built-in-TH.md
The listing of built-in tag helpers (included in e.g. https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-7.0#built-in-aspnet-cores) is using the heading "Built-in ASP.NET Cores", which doesn't make sense. This PR updates that heading to "Built-in ASP.NET Core Tag Helpers"
> Clarity heading of Tag Helper list

- aspnetcore/grpc/test-services.md
Use correct variable to access UserState collection in code snip
---
|:--|:--|
| [aspnetcore/grpc/test-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/8649deeff6cf278b3bf082f09c4c6b4f7b305c19/aspnetcore/grpc/test-services.md) | [Test gRPC services in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/test-services?branch=pr-en-us-30705) |
> Fix code snip for unit test HttpContext

- aspnetcore/fundamentals/dependency-injection.md
Fixes #30741
Restore the keyed services section only for .NET 8.
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/bab007a3325efb1748bed6ae7c2fb55d8889eb1e/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-30743) |
> Restore keyed services section

- aspnetcore/performance/ObjectPool.md
The sentence:
> an object pool that is **construct** directly
Should read:
> an object pool that is **constructed** directly
---
|:--|:--|
| [aspnetcore/performance/ObjectPool.md](https://github.com/dotnet/AspNetCore.Docs/blob/966706ec02bbbbf1b215cb15c5287e3c5df204d2/aspnetcore/performance/ObjectPool.md) | [Object reuse with ObjectPool in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?branch=pr-en-us-30754) |
> Fix typo in ObjectPool.md

- aspnetcore/blazor/components/integration.md
- aspnetcore/migration/70-80.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #29505
Fixes #30471
Fixes #29522
***Ready*** for review!
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/20ae3176ee1c3c74088cf0ae6e2cac9da4230577/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30671) |
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/20ae3176ee1c3c74088cf0ae6e2cac9da4230577/aspnetcore/migration/70-80.md) | [[Visual Studio Code](#tab/visual-studio-code)](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30671) |
| …
> Blazor migration guidance 8.0

- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
- aspnetcore/zone-pivot-groups.yml
Fixes  #30789
Thanks @philip-reed! ... I'm literally just typing this straight in. Do you want to try it and let me know if it compiles and runs, or do you want me to do it instead and let you know how it turns out? I'm still focused on .NET 8 work; and if you were working with it anyway, I'd just trust that if it works for you that it will work for others. The transition from v4 to v5 is fairly straightforward. I trust the updates if the code will run for you ... and I'll publish this on that basis. It's not your fault tho if it 💥 later for someone else. I'd just need to work further with it in that case.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e23ec183afc53c33a9d562d278061e1b20acbaa/ …
> Graph SDK v5 update

- aspnetcore/security/data-protection/configuration/overview.md
Microsoft.AspNetCore.DataProtection.AzureDataProtectionBuilderExtensions is in the https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.AzureKeyVault package, which as been deprecated as legacy. We shouldn't reference these APIs in our docs.
See https://github.com/aspnet/Announcements/issues/408
---
|:--|:--|
| [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/0fbb2995a74a4a4ba8269a8101478b23645f895d/aspnetcore/security/data-protection/configuration/overview.md) | [Configure ASP.NET Core Data Protection](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=pr-en-us-30796) |
> Remove references to deprecated package

- aspnetcore/blazor/components/integration.md
Fixes #30471
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f363e192d4a6347e3c8b0f1809bb60f03af33d9/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30791) |
> Add Blazor support to an ASP.NET Core app

- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30675 
Updates the SignalR stateful reconnect section of the What's New for 8.0.
- SignalR seamless reconnect is renamed to _SignalR stateful reconnect_.
- Code example updated.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe9ee39273a92a44a8c44ec0c622e690d9f7640b/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30804) |
> 8.0: Update What's New: SignalR stateful reconnect

- aspnetcore/migration/70-80.md
I didn't care for the shortened DIFF-CODE block pairs without an intervening line. It's better in the long form with the added line.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ba53a48edaf26a2dd659640ea39dae38dbb74c9/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30817) |
> Content structure updates

- aspnetcore/blazor/components/integration.md
Fixes #30471
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/668c5126dc5d9c50e73a1ad1f40864187d7ebb12/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-30799) |
> Blazor support to an ASP.NET Core app (Part 2)

- aspnetcore/docfx.json
This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation
> Fix breadcrumbs

- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/migration/70-80.md
Fixes #30843
cc: @shrayasr ... A 🏅 for opening an issue. This will help others in a similar situation.
Cross-linking a few existing options config sections for migration guidance ... ➕ ***PLUS*** ➕ adding a couple of missing options.
I also see that we never had good `MapBlazorHub` guidance. It was part of the tutorial but not in a reference doc section. This PR will fix that 😈.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/55724858406b6d9dd2244a37f4322cf9bf39468e/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-30845) |
| …
> Blazor options configuration 8.0

- aspnetcore/log-mon/metrics/metrics/samples/web-metrics/Program.cs
As [documented elsewhere](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#instrument-httpserveractive_requests) (and [implemented](https://github.com/dotnet/aspnetcore/blob/6c1b3dfb66a1b66cc32ee26bbc23f6472f1dc985/src/Hosting/Hosting/src/Internal/HostingMetrics.cs#L30)) the instrument name uses dots rather than slashes: 
It seems that slashes were used in the [initial proposal](https://github.com/dotnet/aspnetcore/issues/47536).
> Fix ASP.NET metric instrument name in example

- aspnetcore/tutorials/signalr/includes/signalr7.md
Contributes to #30565
Prep for 8.0 update to [Tutorial: Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0&tabs=visual-studio).
Moved version 7 of doc to an include file.
---
|:--|:--|
| [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/fedb043fd292764f64b94d228ddcc18e03ed2cce/aspnetcore/tutorials/signalr.md) | [Customer intent: As a developer, I want to get a quick proof-of-concept app running, so I can get a practical introduction to ASP.NET Core SignalR.](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?branch=pr-en-us-30851) |
> Versioning prep for 8.0 update: SignalR JS Getting Started

- aspnetcore/blazor/host-and-deploy/webassembly.md
Updates the example to exclude assets with the type `manifest` (usually `blazor.boot.json`).
This prevents headers like `Blazor-Environment` from getting lost when generating a decompressed response.
Fixes https://github.com/dotnet/aspnetcore/issues/51552
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/5ecd97fb3016b2cb3dfb6aaeaff91c88d677570d/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-30867) |
> [Blazor] Update WebAssembly docs for handling compressed static assets

- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/host-and-deploy/server.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/migration/70-80.md
- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/tutorials/signalr-typescript-webpack.md
Fixes #30812
Fixes #30580
Fixes #30862
Mackinnon ... You might want to expand the entire *Startup* doc on the diff to confirm that nothing else needs to change.
Also, confirm if the brace blocks (`{...}`) passed to `ssr`, `circuit`, and `webAssembly` are called "functions" in this context. If not, what should they be called? You'll see on the DIFF (Lines 51-53) where we need to change the word if I made a poor choice.
The bit that I added on an earlier PR for `disableDomPreservation` is versioned for 8.0+ at the end of the doc.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/8f276487f810668cdc21283d4bde7b375ecd20bb/aspnetcore/b …
> Manual Blazor start updates 8.0

- aspnetcore/signalr/diagnostics.md
Spent a couple hours stuck on this until I found the github issue. Might be appropriate to mention it here as well?
---
|:--|:--|
| [aspnetcore/signalr/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/55e0509513347b19cba0910d32a1f210534189e6/aspnetcore/signalr/diagnostics.md) | [Logging and diagnostics in ASP.NET Core SignalR](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/diagnostics?branch=pr-en-us-30874) |
> SignalR loglevel nuance in javascript

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #30535
Thanks @AceHack! 🚀 ... For now, we'll go with this. I'll keep an 👂 open on the `dotnet/runtime` issue for additional information and perhaps some firm guidance from that team on what to say (e.g., known, specific cases where it will fail that we can call out).
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e1602912acfdb6792dfe63d57178b84664a1047/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-30886) |
> Update .NET IL trimming remarks 8.0

- aspnetcore/migration/70-80.md
- aspnetcore/migration/inc/blazor.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30528
* Capping the version of the Blazor Server with Yarp migration article for <8.0.
* Indicating to readers that they can drop the workaround ...
* In the *Migration* guidance for Blazor.
* As a *What's new* article entry.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/dba3c307f0efebab69029e9b0b084f34f1e0c33a/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30885) |
| [aspnetcore/migration/inc/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/dba3c307f0efebab69029e9b0b084f34f1e0c33a/aspnetcore/migration/inc/blazor.md) | [Enable ASP.NET Core Blazor Server support with Yarp in incremental …
> Drop Yarp-Blazor workaround 8.0

- aspnetcore/migration/70-80.md
Addresses #30528
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/8bd23803fc3db505530329233b7240f41d3b5537/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30889) |
> Update Blazor Server with Yarp 8.0

- aspnetcore/migration/70-80.md
since we're upgrading from .NET 7 to .NET 8
update the previous SDK version from 6 to 7
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/f20d9449970955d715f529d0fd341d07f839751f/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30910) |
> update global json sdk version

- aspnetcore/blazor/tooling.md
Fixes  #30923
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/48af0d117977494d25a44b357b700ad6344da16f/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-30924) |
> Update SIMD disable guidance 8.0

- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
Fixes #30918
Javier, Mackinnon ... Guessing on a couple of aspects, particularly the arguments (`options`, `extensions`, and `blazor` of the legacy initializers for the new ones). Also, I'm sure you'll want to update/add remarks on behaviors.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/12a8f9b5480c9d7df780d8df2d4825ef290cfc75/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-30920) |
| [aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/12a8f9b5480c9d7df780d8df2d4825ef290cfc75/aspnetcore/blazor/host-a …
> JS initializers 8.0

- aspnetcore/blazor/debug.md
Fixes  #30824
For ***adding a note about how to debug exceptions***, is the guidance what Thays provided at ...
* https://github.com/dotnet/aspnetcore/issues/42510#issuecomment-1171706250
* https://github.com/dotnet/aspnetcore/issues/42510#issuecomment-1171716418 
... what we're passing on? ~My plan is to place a section on it, which I've started but haven't finished yet.~ **UPDATE**: I've made the PR say what I think it's supposed to say.
~BTW, I'm not sure what Thays took a screenshot of for that. Where is that "All Exceptions" setting? ... and note that her text remark doesn't exactly match what's shown in the screenshot.~ ***Nevermind!*** I found it. I haven't looked at that UI in several years ... **Debug** > **Windows** > **Exception Settings**. I thought it would be in **Options**. …
> WASM debug scenario update

- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/forms/validation.md
Fixes #30055
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/100d414d58905d96a5525dfcc9cdc886e3e36595/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-30925) |
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/100d414d58905d96a5525dfcc9cdc886e3e36595/aspnetcore/blazor/forms/validation.md) | [ASP.NET Core Blazor forms validation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?branch=pr-en-us-30925) |
> Server validation with a validator component 8.0

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/javascript-interoperability/static-server-rendering.md
- aspnetcore/toc.yml
Fixes #30921
Mackinnon ... Check everything because I made a few guesses along the way ... *and we know how that goes* 🦖🙈😆. 
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/6b94e61cd5dc244598e1da70a8128a6998834e73/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-30922) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/6b94e61cd5dc244598e1da70a8128a6998834e73/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fun …
> JavaScript with Blazor static server rendering

- aspnetcore/grpc/interprocess.md
- aspnetcore/grpc/interprocess/includes/interprocess5-7.md
Internal review:
[.NET 8 version: Interprocess](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-8.0&branch=pr-en-us-30981)
[.NET 5-7 versions: Interprocess](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-7.0&branch=pr-en-us-30981)
Fixes #30823 
Goal:  Move all Named pipes support information to the .NET 8 topic only so it is not in previous versions.
**Added file include versioning:**
- Moved to file include type versioning.  There was previously only one version of this topic.  Now there is a .NET 5-7 version and .NET 8 version.
**For the .NET 8 version of the Interprocess topic:**
- Added at the top that Named pipe support requires .NET 8 or later.
**For .NET versions 5-7 of the Interprocess topic:**
- …
> gRPC  interprocess: Move Named pipes content to 8.0 topic

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
- aspnetcore/toc.yml
Fixes #30944
I'm going *VERY fast* 🏃‍♂️ right now to get this in. I'm just about out-of-🕦 on getting everything into place 😰. This should be enough to get us started. I'll take another look for improvements in 24Q1.
The sample is at ...
https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyStandaloneWithIdentity
The reason you were having trouble getting the Bootstrap icons in place via only a stylesheet class on the `<span>` elements is that the classes must be manually placed in (usually collocated) stylesheets ([`MainLayout.razor.css`](https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Layout/MainLayout.razor.css#L49-L59)). I changed the icons to the opening door (login), …
> Blazor WASM w/Identity article 8.0

- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/security/authentication/scaffold-identity.md
Fixes #30976
We can add more 🍖 if you wish (e.g., is there additional configuration to call out?), but the most important changes look merely to be ...
* Update the **Authentication Types** to just **None** and **Individual Accounts**.
* Version ***out*** the scaffolding guidance and remarks on Identity components and `SignInManager`/`UserManager` in the Blazor security overview article.
* Version ***out*** the scaffolding guidance in the Blazor server security doc.
* Version ***out*** the scaffolding guidance in the main doc set's *Scaffolding* article. **NOTE**: The article uses **Whole-topic Versioning**, so it's versioned out by making a copy of the entire 6.0 content block and deleting the bits to drop for >=8.0. They have a new INCLUDE file add-on process, but I'm …
> Blazor security BWA with Identity components 8.0

- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/input-components.md
- aspnetcore/blazor/forms/validation.md
Fixes #30996
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/96400c58c97c48f8e027ba218f6971d06e0fead7/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-30997) |
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/96400c58c97c48f8e027ba218f6971d06e0fead7/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-30997) |
| [aspnetcore/blazor/forms/input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/96400c58c97c48f8e027ba218f6971d06e0fead7/aspnetcore/bla …
> EditForm examples update

- aspnetcore/security/key-vault-configuration.md
Resolves #26714 
While disabled secrets are listed, values cannot be retrieved. Also updated text to use the Key Vault product name correctly, or just "vault" where it's mentioned as a resource. Sections for >= net6.0 and < net6.0 were also made mostly congruent, sans sample code / references.
---
|:--|:--|
| [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/4cdab733121cbedf7c4187df738d6d1b8ee241f0/aspnetcore/security/key-vault-configuration.md) | [Azure Key Vault configuration provider in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?branch=pr-en-us-30964) |
> Correct KeyVaultSecretManager documentation

- aspnetcore/tutorials/min-web-api.md
- aspnetcore/tutorials/min-web-api/includes/min-web-api6-7.md
Fixes #30588
Made the code samples for this tutorial discoverable at bottom of the topic.
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/eae06ccaefe22508a8854c6421726608efbce57b/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-30999) |
> Create Min Web API: Link to code sample

- aspnetcore/release-notes/aspnetcore-8.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/85a6c961a0c0c85540aab09870b707cda1763ee3/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31019) |
> Blazor What's New updates 8.0

- aspnetcore/blazor/globalization-localization.md
Fixes #31053
Thanks @stancoffyn! :rocket: ... I found two 😈 in the doc. Blazor WASM requires the Localization Middleware services added to the app (i.e., `builder.Services.AddLocalization();`, which I think you did add based on your remarks. A step appeared in other sections of the doc for client-side app, but it wasn't in this section, so I updated the section to cover it. Also, I see that the section you were referring to didn't mention adding the Localization package itself.
I think if you just add a package reference for [`Microsoft.Extensions.Localization`](https://www.nuget.org/packages/Microsoft.Extensions.Localization) to your app, it will work. I just tested the revised guidance here, and it looks good.
---
|:--|:--|
| …
> Fix dynamic localization guidance

- aspnetcore/blazor/security/includes/app-component.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/migration/70-80.md
Fixes  #31056
Thanks @xunmeng2002! 🚀 ... I'm sorry that we didn't have these updates! It didn't make some of the product unit lists that I received, so it slipped through the cracks and didn't get covered for release.
This PR should cover it now everywhere that we had guidance on the `CascadingAuthenticationState` component, ***AND*** I added a section to the 8.0 Migration article to highlight it.
I'm going to merge this quickly 🏃 and take it live immediately. It should appear in the live articles within 20 minutes.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdd4f4327f676751882fcb65a6fdae2b8c13821f/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and …
> Migrate to cascading auth state services

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/configuration.md
- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/state-management.md
Fixes #31025 
Mackinnon ... I decided to draft this with a full explanation and examples for what's going on with client-side services in a BWA. It's a little long. However, I can understand it this way, so we have a good bet on not losing anyone.
In the *Render Modes* article, the *Set the render mode for the entire app* section was too far down the article. I moved the section up and changed the heading name to *Apply a render mode to the entire app*. The new section on *Client-side services fail to resolve during prerendering* makes reference to globally setting the render mode. I want to reader to have already seen that section.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/76f68fd99e5 …
> Environments + client services w/prerendering

- aspnetcore/blazor/performance.md
Fix typo (EventUntil -> EventUtil).
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/6e1ea6cbe22f98415760ec9a4c7b7120caf6535f/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-31069) |
> Fix typo (EventUntil -> EventUtil)

- aspnetcore/blazor/caching-issues.md
- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/sections.md
- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/security/includes/troubleshoot.md
- aspnetcore/blazor/security/server/static-server-side-rendering.md
- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
- aspnetcore/migration/70-80.md
- aspnetcore/toc.yml
Fixes #31058
---
|:--|:--|
| [aspnetcore/blazor/caching-issues.md](https://github.com/dotnet/AspNetCore.Docs/blob/a6de0006a305ebc5f4785cbc44c33937fc12d320/aspnetcore/blazor/caching-issues.md) | [aspnetcore/blazor/caching-issues](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/caching-issues?branch=pr-en-us-31073) |
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/a6de0006a305ebc5f4785cbc44c33937fc12d320/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-31073 …
> Add HTTP caching issues article

- aspnetcore/blazor/components/render-modes.md
Fixes #31078
Thanks @TheCakeMonster! 🚀 ... I'll leave this up for an hour to give you a chance to look before merging.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/bfd7842a53c402d860ca44196ddfc466c2ce1238/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31079) |
> Clarify global interactive WASM/Auto folders/files

- aspnetcore/fundamentals/middleware/index.md
Fixes https://github.com/dotnet/aspnetcore/issues/52295
All three of these middleware can handle an exception and not re-throw it, the most specific middleware (timeouts) needs to be last so it can handle them first.
---
|:--|:--|
| [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4c52cf71e26455278a284467a6094ac66dc44620/aspnetcore/fundamentals/middleware/index.md) | [ASP.NET Core Middleware](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?branch=pr-en-us-31110) |
> Clarify timeout middleware ordering

- aspnetcore/blazor/security/content-security-policy.md
Fixes #31105
Mackinnon ...
* Our CSP guidance seems ok. We addressed it during an early preview.
* I wanted to confirm all is well anyway and was reminded that we never had guidance on how to only apply CSPs in non-Development environments. It's always been a PITA 😠 during development just plopping a CSP into `<head>` content. I add a new section (just picking up with 8.0+, I won't sweat prior releases) that will assist devs with this problem.
* ***Section order change***: When you look at the DIFF, the first thing that you'll see is the *Server-side Blazor apps* section, which isn't being added as new content. It's just moving from below the *Client-side Blazor apps* section to above it. We're generally ordering our server-side coverage above our client-side coverage these days. Scroll …
> Apply a CSP in non-Development environments

- aspnetcore/blazor/tutorials/build-a-blazor-app.md
Fixes #31163
Thanks @vjojic-dev! 🚀 ... I'll patch it quickly. The reason this happened is because I haven't created the Blazor Web App snippet sample yet. The article is pulling code from the Blazor WebAssembly sample app, where the render mode wouldn't be applied. What I'll do here is just drop some code in place temporarily with the `@rendermode` line present.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/2c468e734f8f537fdc192ae8e44760f58d2babf8/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [Build a Blazor todo list app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-31164) |
> Fix example code

- aspnetcore/blazor/components/lifecycle.md
Fixes #31171
Thanks @QueryCoordinator! 🚀 ... Indeed! A missing backtick is the cause 😈.
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/9a3d24f84be91b622a92643caa76c86cf7b1de43/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-31172) |
> Fix broken code-fencing

- aspnetcore/blazor/components/layouts.md
Fixes #31170
Thanks @bmeenehan! 🚀 ... This will fix up the article in a general way. I'm adding a section on namespaces, and I'm tailoring the article for the churn across .NET 8 on layouts. For example, they're no longer set app-wide in the `App` component (Blazor Server) because the `Router` component moved to the `Routes` component in Blazor Web Apps.
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/595512394287370b11a76f659b73e8d36096d7b7/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-31173) |
> Address layout namespaces

- aspnetcore/tutorials/first-web-api.md
Fixes #30737
Very minor update: Removed mention of preview and preview versions for required packages and re-tested.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/34ce7c510e8f8b63d61be78a09c4a2fcbd9a102e/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-31198) |
> First Web API: Remove preview specific packages

- aspnetcore/tutorials/web-api-javascript.md
- aspnetcore/tutorials/web-api-javascript/includes/web-api-javascript3-5.md
- aspnetcore/tutorials/web-api-javascript/includes/web-api-javascript6-7.md
Fixes #31033 
Minor change: Just moving topic to version by include files.
---
|:--|:--|
| [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/1910bb0b0fbd603d8f39216e979a450baf58958f/aspnetcore/tutorials/web-api-javascript.md) | [Tutorial: Call an ASP.NET Core web API with JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?branch=pr-en-us-31210) |
> Web API with JavaScript: Move to version by include

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31194
Thanks @SandroRiz.
Stephen, Jeremy ... These changes take into account that the dev will need to write custom code. I have a feeling that this is going to generate doc issues from devs asking for a complete implementation. I presume that you want me to tell them that we're not going to support it in our docs and that they should research it on the Net and use public support channels for assistance.
Also, @halter73 ... You didn't mention in your PU issue remarks the piece on `AddBearerToken`. I left that in the section, so let me know if it gets the 🔪 *chop* ... or a change to something else.
**UPDATE**: I see what you and Tom did in the main article. That's better, but it still isn't a complete, fully working implementation. The text over there is below. I'll make cross-link …
> Token authentication updates

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/element-component-model-relationships.md
- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/file-uploads.md
- aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Pages/Index.cshtml
- aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/tvshow.xml
- aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/Pages/Index.cshtml
- aspnetcore/fundamentals/configuration/index/samples/3.x/ConfigurationSample/tvshow.xml
Addresses #31029
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/43113949daf894f2f481364545227758b6b14cd8/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31236) |
| [aspnetcore/blazor/components/element-component-model-relationships.md](https://github.com/dotnet/AspNetCore.Docs/blob/43113949daf894f2f481364545227758b6b14cd8/aspnetcore/blazor/components/element-component-model-relationships.md) | [Retain element, component, and model relationships in ASP.NET Core …
> Sample snippet updates

- aspnetcore/blazor/hybrid/routing.md
Fixes #28401
* I made a couple of guesses at wording for tech that I'm not very familiar with. Check carefully to correct any 💥 in meaning that I introduced 🙈.
* You could update the README of the sample app to just point to this article/section. The link is ...
`https://learn.microsoft.com/aspnet/core/blazor/hybrid/routing?pivots=maui#deep-linking`
* Not sure what's going on with the original PU issue ... if this content just provides a workaround approach until the framework has formal API at .NET 9. Adjust the lead-in wording accordingly. If something is coming for .NET 9, I recommend leaving something in the opening remarks like what I have. Devs may schedule a revisit on deep linking in 2024 on that basis.
---
|:--|:--|
| …
> MAUI deep linking guidance

- aspnetcore/blazor/tooling.md
The new section just went live in their article.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#blazor
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/eb07d7cf38045be157a5deac4cc469fcce2d97c0/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-31244) |
> Add .NET docs crosslink

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #31250
Thanks @sam-wheat! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/9e60986e26d637c1ae94db46278c1689116dad9e/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-31251) |
> Cross-link to app base path guidance

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/control-head-content.md
- aspnetcore/blazor/components/data-binding.md
- aspnetcore/blazor/components/dynamiccomponent.md
- aspnetcore/blazor/components/element-component-model-relationships.md
- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/generic-type-support.md
- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/components/rendering.md
- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
- aspnetcore/blazor/components/synchronization-context.md
- aspnetcore/blazor/components/templated-components.md
Addresses #31029
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/e031beb621575f69daeedda39e02cec7e5ad9ba2/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31268) |
| [aspnetcore/blazor/components/control-head-content.md](https://github.com/dotnet/AspNetCore.Docs/blob/e031beb621575f69daeedda39e02cec7e5ad9ba2/aspnetcore/blazor/components/control-head-content.md) | [Control head content in ASP.NET Core Blazor …
> Snippet cross-links 8.0

- aspnetcore/blazor/project-structure.md
Hello. This PR fixes two simple typos that I noticed in the `Blazor/Project Structure` article.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/1ad83cd3bf858d89e04848309d9cb3cfb52d8dcb/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-31272) |
> Fix two typos in blazor/project-structure.md

- aspnetcore/tutorials/first-mongo-app.md
Fix a typographical error under Add a CRUD operation service
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/4adf324e29c31cdffcb44e662dd83312b7c34430/aspnetcore/tutorials/first-mongo-app.md) | [Create a web API with ASP.NET Core and MongoDB](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-31279) |
> Fix typo in first-mongo-app.md

- aspnetcore/security/authentication/scaffold-identity.md
Addresses #31271
---
|:--|:--|
| [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/38355b38ff2575433d9c65e140fd7542516c0378/aspnetcore/security/authentication/scaffold-identity.md) | [Scaffold Identity in ASP.NET Core projects](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?branch=pr-en-us-31282) |
> Blazor scaffold Identity remarks

- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/javascript-interoperability/index.md
Addresses #31029
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/0be3dc3b659ebab6e0078dad405d013fd2e823aa/aspnetcore/blazor/fundamentals/index.md) | [ASP.NET Core Blazor fundamentals](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/index?branch=pr-en-us-31286) |
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/0be3dc3b659ebab6e0078dad405d013fd2e823aa/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md) | [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call …
> Snippet cross-links 8.0 (4)

- aspnetcore/blazor/forms/validation.md
Fixes #31311
Thanks @MorneZaayman! 🚀 ... This will at least get the topic fixed for the time being. I might continue to work on the issue next week because the sample app should use the `IsValid` approach. Also, the topic has this code inlined into the article, I'm in the process now (on another issue) of using the sample apps to provide code for the new 8.0 examples. I'll get that squared away, too. Thanks for the report. This will go live shortly after I merge it.
---
|:--|:--|
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/340c18ad45e2d39367eeaf3481e1e97c8b73426e/aspnetcore/blazor/forms/validation.md) | [ASP.NET Core Blazor forms validation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation? …
> Fix casing of "isValid" in form code examples

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #31317
Thanks @ericbrunner! 🚀 ... This will help everyone spot and understand that the placeholder must have a value, and it must match the correct script path.
This is a change that I'll make everywhere across the Blazor docs on a future PR. It's tracked for work now.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/846beb30691ab3644641d314c6dd14a33aae9f72/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-31318) |
> Highlight placeholder line

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Addresses https://github.com/dotnet/blazor-samples/pull/152
cc: @Rahul-K-Saini ... Here is the article update to go with that set of sample changes.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/697b3e92b9c38af60b6fbaeac7a8c0310a688fe3/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-31328) |
> Remove console logging

- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/first-web-api/includes/first-web-api3-7.md
Fixes #31620
- Added EF tools package in scaffolding step for version 7 specifying version 7.0.0, and then added same package for version 8 but allowing it to use the very latest version.
- Designated to use .NET 7.0 SDK in project creation for version 7 topic since using a later SDK simply targeting 7 will result in an 8.0 openAPI package loaded which will error at build when targeting .NET 7 for build.
- Specified v7.0.0 for InMemory package for version 7 of the doc.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/388e61e642499c76ce0031ba7c98785a7fde4011/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/fir …
> Web API tutorial - Add EF tools package

- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/input-components.md
- aspnetcore/blazor/forms/troubleshoot.md
- aspnetcore/blazor/forms/validation.md
Fixes #31029
....... for now anyway.
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/3db14979fa8fa59e194a570e589c97294f51c751/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-31364) |
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3db14979fa8fa59e194a570e589c97294f51c751/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-31364) |
| [aspnetcore/blazor/forms/input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/3db14979fa8fa5 …
> Move example code to sample apps

- aspnetcore/security/app-secrets.md
Fixes #31370 
Adds documentation for explicitly using the dotnet user-secrets in projects that target `Microsoft.NET.Sdk` and not the web SDK `Microsoft.NET.Sdk`.
See issue.
---
|:--|:--|
| [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/5a41051b6917251882dca7eef92066b714730ff6/aspnetcore/security/app-secrets.md) | [Safe storage of app secrets in development in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/app-secrets?branch=pr-en-us-31371) |
> Updated app-secrets.md to show how to use user secrets in a console app

- aspnetcore/blazor/components/rendering.md
- aspnetcore/blazor/fundamentals/startup.md
Fixes #31048
I built something that doesn't match what Javier described at https://github.com/dotnet/aspnetcore/issues/52076#issuecomment-1812541641. The 🦖 ***RexHax!***&trade; approach on the PR seems to work, but I suspect it has some 🐉🐉🐉. It at least doesn't seem to be right for WASM components that don't prerender.
---
|:--|:--|
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d02c3358740da57251f2f2b1fdda65d222bdf30/aspnetcore/blazor/components/rendering.md) | [ASP.NET Core Razor component rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?branch=pr-en-us-31145) |
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/ …
> Custom Blazor WASM loading progress indicator

- aspnetcore/blazor/security/server/index.md
Fixes #31271
Thanks @kevon-vems! 🚀 ... but note that I didn't find the KB links that you were referring to. I need the URL(s) to search for in the reference source or the link(s) to the project template files where the links exist in order to alert the product unit. Conversely, you can open an issue directly for them with that information on their repo at ...
https://github.com/dotnet/aspnetcore/issues
If you open an issue for them to update template link(s), you can tell them to cross-link instead to ...
https://learn.microsoft.com/aspnet/core/blazor/security/server/#blazor-identity-ui-individual-accounts
... and please add ...
```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31271
```
... to the bottom of your opening comment so that I can follow along …
> Add Identity BWA template cross-links

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes  #31267
Thanks @BrettSandham! 🚀 ... I think this expansion of the existing coverage will help devs avoid (and resolve) this situation.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/364818a6fcb86892fb3a9664d9150060a88996dd/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31382) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/364818a6fcb86892fb3a9664d9150060a88996dd/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rende …
> Client services during prerendering

- aspnetcore/performance/ObjectPool/ObjectPoolSample8/Program.cs
Minor typo fix in the object pooling documentation
> Minor typo in object pool documentations

- aspnetcore/blazor/host-and-deploy/index.md
Fixes #30043
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d9eb921af4f47c447fc2f0c2c156c3c8e0ade9f/aspnetcore/blazor/host-and-deploy/index.md) | [Host and deploy ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-31390) |
> App base path enhancements

- aspnetcore/fundamentals/native-aot.md
Fixes #31222
[internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0&branch=pr-en-us-31396#createslimbuilder-vs-createbuilder)
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/ba753264b3d8f224da0d59d11849b2d46e7ca7b9/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-31396) |
> CreateSimBuilder is missing /7

- aspnetcore/blazor/components/render-modes.md
Fixes #31403
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/358cfd37a995c9f4d59b9ff55ddae63034f50dc5/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31404) |
> Apply a render mode programatically section

- aspnetcore/host-and-deploy/health-checks.md
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecksSample.csproj
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Snippets/Program.cs
Fixes #31143
Error	CS0122	'DelegateHealthCheck' is inaccessible due to its protection level
cc @francedot @JuergenGutsch @JoshKeegan @tdykstra @viktorpeacock
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/556e757800c37d2c3b88425e1cb55c8d1f6088b6/aspnetcore/host-and-deploy/health-checks.md) | [Health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-31357) |
> DelegateHealthCheck /8

- aspnetcore/docfx.json
Addresses #31413
Ok ... last one ... I hope 🤞🍀.
I think the Blazor Hybrid one works as long as it's after the Blazor entry because this works on a ***last one wins*** basis when it comes to folder paths. The Blazor one is assigned, then it's replaced by Blazor Hybrid.
> Metadata update

- aspnetcore/blazor/components/integration.md
Fixes #31393
Thanks @nfplee! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/64bec0f91cc6ca3b7da7714f3ebdbb6d774a3b4d/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-31425) |
> RazorComponentResult rendering behavior

- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #31394
Artak ... Can I say ***why***? The line I added to the opening remarks is ...
> Lazy loading shouldn't be used for core runtime assemblies, which might be trimmed on publish and unavailable on the client when the app loads.
**UPDATE**: I'm going to go ahead and get this in. I'm 🏃 to get things closed out to slim my backlog ⛰️⛏️😅.
---
|:--|:--|
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/293557e804f8444d4c9b461f3991df4229bbae65/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?branch=pr-en-us-31407) |
> Clarify lazy loading is only for dev assemblies

- aspnetcore/client-side/libman/libman-cli.md
Fixes #31294
---
|:--|:--|
| [aspnetcore/client-side/libman/libman-cli.md](https://github.com/dotnet/AspNetCore.Docs/blob/8ca8503eaad92a771dbe4b7e25e403ad9ce6462e/aspnetcore/client-side/libman/libman-cli.md) | [Use the LibMan CLI with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?branch=pr-en-us-31419) |
> libMan limitations /8

- aspnetcore/test/middleware.md
I spent a lot of time noodling for how to do this for building some middleware tests so thought it would be good to contribute an example back here.
Fixes #31337
---
|:--|:--|
| [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/ede5f67776c3093c4f10f2ae42aa14fa7048ebc7/aspnetcore/test/middleware.md) | [Test ASP.NET Core middleware](https://review.learn.microsoft.com/en-us/aspnet/core/test/middleware?branch=pr-en-us-31323) |
> Add example with endpoints to middleware testing doc

- aspnetcore/tutorials/getting-started-with-NSwag.md
Remove reference to Swashbuckle from NSwag documentation.
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/fce2e9dc846426ece5832ea6d66768c98116efae/aspnetcore/tutorials/getting-started-with-NSwag.md) | [Get started with NSwag and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-NSwag?branch=pr-en-us-31447) |
> Remove reference to Swashbuckle

- aspnetcore/blazor/components/data-binding.md
- aspnetcore/blazor/components/event-handling.md
- aspnetcore/toc.yml
Fixes #30960
Thanks @voroninp! 🚀 ...
* I updated three event handling article examples in the `dotnet/blazor-samples` repo to avoid binding data (i.e., using `@bind`) on https://github.com/dotnet/blazor-samples/pull/166.
* That permitted me to swap the order of the event handling and binding articles in the ToC so that the event handling doc comes first.
* In the binding article, I added a link to the remark on `@bind:after` back to the `EventCallback`/`EventCallback<T>` section of the event handling article, where the reader can review the content.
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc7922cd6d0fb700c9701a4b4c4cbbc62e0e7fde/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core …
> Event handling/data binding article order swap

- aspnetcore/blazor/components/render-modes.md
Fixes #31228
Thanks @ghost! :rocket: ... I think the remarks that Mackinnon stated on general Auto mode rendering logic should be included. I'm not too keen at the moment on getting very deep into implementation details. After all, devs can't control those behaviors, and the timing of behaviors is somewhat arbitrary. Let's go with this for now, and we'll continue to work on the coverage as we go. Note that I can't use the `<head>` content control example that he used because that coverage ***comes later in the doc set***. That wouldn't make sense to include here and would confuse readers. It's best to just state the reason and not have an example.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/245458 …
> Clarify Auto render mode behavior

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/state-management.md
Fixes #31316
Thanks @vconfrence! 🚀 ... Getting close to where we need to be here. According to Steve, it should work if you adopt the ***Wrap the `<Router>` Approach***&trade;. As you can see, I trademarked it, so I get a nickel every time a dev uses it 💰😆.
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/e12543fb9e044d0a980391ccd136429faf976203/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31488) |
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCor …
> Cascading values updates

- aspnetcore/blazor/fundamentals/routing.md
Fixes #31513
Thanks @Masoud-Sal! 🚀 ... I'll make it generic since the earlier samples probably do set the text in an `<h1>`.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/75a686868c377a57ea9ed998c86401fe5ee5fd49/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-31514) |
> Patch text for sample change

- aspnetcore/blazor/security/server/index.md
Fixes #31496
@surayya-MS ... Ignore my ping. I just found out that you joined a different team.
Thanks @PMcVries! :rocket: ... This isn't the end of the story. There's a lot more work to do on BWA security. This at least calls out Surayya's suggestion to take an approach similar to what the BWA template does. I have a tracking work item separate from your issue to work further on this node of docs, and I'll get to it as soon as I can 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️.
Mackinnon, I stole 🚓👮 Surayya's remarks from https://github.com/dotnet/aspnetcore/issues/52317#issuecomment-1824624057 to get this coverage going. I don't have the workaround described at https://github.com/dotnet/aspnetcore/issues/52317#issuecomment-1830673284 because it sounds like it isn't the best way to manage the …
> Improve auth state provider guidance

- aspnetcore/security/enforcing-ssl.md
Fixed incorrect ASPNETCORE_HTTPS_PORT variable name (correct is ASPNETCORE_HTTPS_PORTS)
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/e60efe350696e5828fb999bec8e260d95136729c/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-31533) |
> Update enforcing-ssl.md - Fixing invalid environment variable name

- aspnetcore/security/authorization/claims/samples/6.x/WebAll/Pages/Index.cshtml.cs
- aspnetcore/security/authorization/roles/samples/6_0/WebAll/Pages/Index.cshtml.cs
There is a single space character missing before the OnGet method access modifier:
> Resolve minor typo on authorization roles/claims documentation page

- aspnetcore/blazor/components/integration.md
Fixes #31429
Thanks @nitrospaz! 🚀 ... and sorry that you ran into trouble with the guidance.
I made a few light touch-ups to where setting the namespace for components are called out. These didn't really need to be changed, but I made improvements that show an example of the `using`/`@using` statement(s) with a placeholder (`{APP NAMESPACE}`) and then an example of an actual statement with `BlazorSample` as the app's namespace (e.g., `using BlazorSample.Components`).
In order to use the shortened syntax for render modes, such as ...
```razor
@rendermode InteractiveServer
```
... the `_Imports.razor` file needs an additional `@using` ...
```razor
@using static Microsoft.AspNetCore.Components.Web.RenderMode
```
Right at the time of release of the 8.0 framework, they tossed that `@using` …
> Integration article updates

- aspnetcore/blazor/components/render-modes.md
Fixes #31543
Thanks @DavidThielen! 🚀 ...
> can't be disabled directly by the `App` component
... meant '***with an `@rendermode` at the top of the root component's definition file***,' so I've explained that out fully here.
I'm also going to change this from a passing NOTE to ordinary content. I'll also position this after the correct approach is described.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9560555db7ed2208fa3c62b799b6e05965e09fe/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31544) |
> Clarification on prerendering and root components

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31552
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/5cd713831f97be861416d5eb96a1435f42bef4a0/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-31553) |
> Drop Swashbuckle/OpenAPI from WASM+Identity article

- aspnetcore/fundamentals/minimal-apis/includes/route-handlers.md
The sentence:
> When a request is **made a route** with parameters...
Should read:
> When a request is made **to** a route with parameters...
> Fix typo in route-handlers.md

- aspnetcore/fundamentals/minimal-apis/min-api-filters.md
The sentence:
> The **follow** code shows...
Should read:
> The **following** code shows...
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/min-api-filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/806a68c64e6ddff43bd024251f1027695d262264/aspnetcore/fundamentals/minimal-apis/min-api-filters.md) | [Filters in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?branch=pr-en-us-31558) |
> Fix typo in min-api-filters.md

- aspnetcore/blazor/progressive-web-app.md
- aspnetcore/blazor/security/webassembly/graph-api.md
Fixes #31561
Thanks @michaelm7456! 🚀 ... Sorry for the trouble, but they didn't tell me that these changes were being made, nor did I spot them in the large sweeps of updates that I had to make. This one got by 😈. There might be others as well. I have a tracking item for one of their engineers to review this article for 8.0, but that still hasn't happened. I'll make sure that eventually one of them takes a look at it. In the meantime, this will deal with the problem that you discovered.
---
|:--|:--|
| [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/43ad9d371cb696d791b2e58f0eefa3a5db38a752/aspnetcore/blazor/progressive-web-app.md) | [ASP.NET Core Blazor Progressive Web Application …
> Update PWA guidance

- aspnetcore/blazor/project-structure.md
Fixes #31562
Thanks @MarcoGaribaldi! 🚀 ... This should explain why the folder layouts are different and clarify that you can use the main project folder structure if you wish.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/bba6f6759ca688f52f3de79cdbf7276bfcc8caaf/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-31566) |
> Terminology updates

- aspnetcore/migration/70-80.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #31554
Thanks @JZO001! 🚀 
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/a42253168e84f1df53d3f9af18124e1c82cc0cbd/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-31569) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/a42253168e84f1df53d3f9af18124e1c82cc0cbd/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31569) |
> Drop `[Parameter]` for query string params

- aspnetcore/tutorials/min-web-api/samples/7.x/todo/Message.cs
Hello,
When building the current version of [this example for .NET 7](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/min-web-api/samples/7.x/todo) there is an error:
```log
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Message.cs(6,12): warning CS8618: Non-nullable pro
perty 'Text' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [G:\A
spNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\TodoApi.csproj]
G:\AspNetCore.Docs\aspnetcore\tutorials\min-web-api\samples\7.x\todo\Program.cs(120,43): error CS0246: The type or name
space name 'Message' could not be found (are you missing a using directive or an assembly reference?) [G:\AspNetCore.Do …
```
> Fix aspnetcore\tutorials\min-web-api\samples\7.x\todo\ build

- aspnetcore/fundamentals/minimal-apis.md
The sentence:
> ...because the **services** is retained...
Should read:
> ...because the **service** is retained...
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/e296852c670a1fcf2a89f415af88b1d1b3b5dabc/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-31579) |
> Fix typo in minimal-apis.md

- aspnetcore/fundamentals/minimal-apis/responses.md
The sentence:
> ...adds an annotation to the preceding `HtmlResult` type that **describe** the response...
Should read:
> ...adds an annotation to the preceding `HtmlResult` type that **describes** the response...
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/3e79c7a5dd586e5e84635214a1a9767f8bc484e5/aspnetcore/fundamentals/minimal-apis/responses.md) | [How to create responses in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-31585) |
> Fix typo in responses.md

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/server/index.md
Addresses #31403
* Now we're cook'in with ***gas*** 🔥.
* There's a section here named *Client-side services fail to resolve during prerendering* that you can ignore. That section is merely moving down in the article, and there are no changes to it.
* The two sections for review are:
* ***Apply a render mode in code*** and its two subsections
* ***Fine control of render modes*** and its two subsections
* We might want to change the section heading name, *Fine control of render modes*, but I'm not sure yet what would be better. I'll 🤔 about it.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/d005f79d64c26e4541fc704c300a054afb66928e/aspnetcore/blazor/components/render-modes.md) | …
> Fine control of static SSR

- aspnetcore/release-notes/aspnetcore-8.0.md
Add a note about certificate file watching in Kestrel.
Fixes #30404
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/046b993f426f6d10c72d25ac03bc5d5bfeda1a71/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31588) |
> Add a note about certificate file watching

- aspnetcore/blazor/components/built-in-components.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/host-and-deploy/webassembly-deployment-layout.md
- aspnetcore/blazor/hybrid/security/index.md
- aspnetcore/blazor/security/includes/authorize-client-app.md
- aspnetcore/blazor/security/includes/troubleshoot.md
- aspnetcore/blazor/security/includes/wasm-aad-b2c-custom-policies.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
- aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
- aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-entra-id.md
Fixes #31620
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/3b2ee979a08a6cd21b4c619e939e177fb818fd42/aspnetcore/blazor/components/built-in-components.md) | [ASP.NET Core built-in Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-31622) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/3b2ee979a08a6cd21b4c619e939e177fb818fd42/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-m …
> Content follow-up updates (8.0)

- aspnetcore/fundamentals/servers/kestrel/options.md
Presently, they can't conveniently be configured from appsettings.json.  There are [workarounds](https://github.com/dotnet/aspnetcore/issues/4765), but none that seem worth recommending.
Fixes #31108
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/49d9d1fcbbe0b588305458266a8d46b32baea8a4/aspnetcore/fundamentals/servers/kestrel/options.md) | [Configure options for the ASP.NET Core Kestrel web server](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?branch=pr-en-us-31633) |
> Remove incorrect comments about kestrel limits

- aspnetcore/blazor/debug.md
- aspnetcore/blazor/tooling.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
Addresses #31638
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d1ede52db0ee24f98324a0fe9ea68f52d7d5ee8/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-31639) |
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d1ede52db0ee24f98324a0fe9ea68f52d7d5ee8/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-31639) |
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d1ede52db0ee24f98324a0fe9ea68f52d7d5ee8/aspnetcore/blazor/tutorials/signalr-blaz …
> Debug article follow-up 8.0

- aspnetcore/includes/RP-MVC/validation.md
- aspnetcore/tutorials/razor-pages/validation.md
https://github.com/dotnet/AspNetCore.Docs/commit/bff9fa8741e8e10f95df9c5f930297b22307f917 permit whitespace characters in the Genre field.
That commit changed
```
The first letter is required to be uppercase. White space, numbers, and special characters are not allowed.
```
to 
```
The first letter is required to be uppercase. White spaces are allowed while numbers, and special characters are not allowed.
```
After that edit the comma after 'numbers' is stray.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/75c0b5c8d368a63cfeb7d2dbe62083b00559450f/aspnetcore/tutorials/razor-pages/validation.md) | [Part 8 of tutorial series on Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorial …
> edit validation.md: remove stray comma

- aspnetcore/tutorials/razor-pages/search.md
Before this change:
^ Links are outside purple box.
After this change (what I intend):
^ Links are inside purple box.
Because the links are part of the note's message, I claim the links should be inside the note's box (if possible).
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/04a3ab9636d73a3825c229dd44e8b311152a6cb0/aspnetcore/tutorials/razor-pages/search.md) | [Part 6, add search to ASP.NET Core Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?branch=pr-en-us-31641) |
> edit search.md: in Note that describes LINQ Contains and SQLite case (in)sensitivity, include links in the Note instead of outside

- aspnetcore/tutorials/razor-pages/validation.md
^ When the reader selects the 'Visual Studio Code' toggle, the reader sees `dotnet ef database update` then a use of `Update-Database` rather than `dotnet ef database update`.
This commit puts the use of `Update-Database` in the Visual Studio tab and a corresponding use of `dotnet ef database update` in the Visual Studio Code tab.
Separately, this commit changes '`Up` methods' to '`Up` method` because I see only one method in the code block that follows. 
[A previous page ](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio-code) uses `dotnet-ef` rather than `dotnet ef`.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/02a948a0548ca193 …
> edit validation.md: use `dotnet ef database update` in Visual Studio Code section. Use `Update-Database` in Visual Studio section

- aspnetcore/tutorials/razor-pages/search.md
Ooooops, @zipperer 🙈 ... I missed code-fencing the repo names. In these cases, it's good because it prevents the machine translation from localizing any of the text in the repo names.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/1ec3998c52cc556c87d04735c125153feaf114d6/aspnetcore/tutorials/razor-pages/search.md) | [Part 6, add search to ASP.NET Core Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?branch=pr-en-us-31655) |
> Code-fence repo names

- aspnetcore/tutorials/razor-pages/validation.md
- aspnetcore/tutorials/razor-pages/validation/includes/validation6.md
- aspnetcore/tutorials/razor-pages/validation/includes/validation7.md
Fixes #31650 
Explanation for what runs `Up` in Razor Pages Get Started - Validation tutorial was used for both VS and VS Code/MacOS tabs but should have been separate and different for the latter.
Fix already added by community member for v8.  Adding it to versions 6-7 and a space correction on version 8.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/180ff75839e86f0503dbfe4bf41c83102d2001f1/aspnetcore/tutorials/razor-pages/validation.md) | [Part 8 of tutorial series on Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?branch=pr-en-us-31653) |
> Razor Pages Get Started: Fix VS Code and MacOS explanation for Up

- aspnetcore/performance/performance-best-practices/samples/3.0/Controllers/FireAndForgetSecondController.cs
I think the usage of `AsyncServiceScope` should be encouraged in this example, given that the example shows usage of resolving a service that implements `IAsyncDisposable`.
I realize there is some documentation elsewhere in this repository referencing `IServiceScope` and I don't think there are other places referencing `AsyncServiceScope`, so this could be a little misleading/incohesive.
> Suggestion: Update best practice Fire-And-Forget example to use AsyncScope

- aspnetcore/blazor/components/class-libraries.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/security/index.md
I recommend not referring to RenderFragment parameters and components as "tags".
In other parts of the documentation, the term "template" is commonly used for RenderFragment parameters, and "content" is also an appropriate choice. Although "parameter" might be the most precise term, it could be considered too technical for some contexts.
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/76a70966921f0318e2b438ec5fc145e54257068e/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-31662) |
| …
> Avoid referring to components or RenderFragment parameters as "tags"

- aspnetcore/blazor/components/built-in-components.md
The list of Razor components includes both built-in components provided by the Blazor framework and those that come with Blazor project templates.
It's important to note this distinction on the page to prevent confusion, especially when working on projects not based on the official Blazor project templates.
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/8282bac47d68247d3c6c6a1e5cc5d6a5660f0232/aspnetcore/blazor/components/built-in-components.md) | [ASP.NET Core built-in Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-31663) |
> Blazor built-in components include components from project templates

- aspnetcore/blazor/debug.md
Fixes #30443
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/cee885a65ec3e239454f3f656213c804d237f203/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-31671) |
> Final round of debugging updates

- aspnetcore/migration/70-80.md
Fixes #31709
Thanks @Stra1ghter ... This will at least get readers to the *Environments* article to consume the new content for the `.Client` project's use of the environment, especially in light of prerendering, where `IWebAssemblyHostEnvironment` isn't on the server by default. Of course, I can't say if the guidance resolves any particular problem that you're reporting in your product unit issue, but I'll keep an 👁️ on it over there for further work here.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/911cfd4c4b3699492394d3bd83ebe0f4fb60d5ff/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-31710) |
> Add cross-link

- aspnetcore/blazor/http-caching-issues.md
This PR corrects a grammatical error in the documentation for DNS cache flushing. The original text, "Try to flushing the DNS cache", has been changed to "Try to flush the DNS cache" for clarity and correctness.
---
|:--|:--|
| [aspnetcore/blazor/http-caching-issues.md](https://github.com/dotnet/AspNetCore.Docs/blob/5e3bb3d1d12024bbcba78060702fab07f083eb36/aspnetcore/blazor/http-caching-issues.md) | [Avoid HTTP caching issues when upgrading ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/http-caching-issues?branch=pr-en-us-31711) |
> Fix grammar in DNS cache flushing instruction

- aspnetcore/blazor/fundamentals/handle-errors.md
Fixes #31707
Thanks @chulla! 🚀 ... Looks like the guidance that I added also should've been added in a second spot higher up in the article.
I'm going to sit on this overnight for more updates on Wednesday morning. I think the *Error Boundaries* section might appear earlier in the article's content. I also want to double-check the updated guidance setting the render mode on the `HeadOutlet` and `Routes` components to confirm the behaviors are good.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/ba97adb9089ad86cf09d3e558fb98557fbabff47/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamenta …
> Update render mode guidance for error boundaries

- aspnetcore/blazor/fundamentals/dependency-injection.md
The Note box caught my attention because the two links placed next to each other seemed cluttered. For comparison, I found similar Note boxes elsewhere where this is handled with bullets (e.g., `tooling.md`).
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/09a2c4692a6d41183d39138c6538002cf9e3e742/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-31718) |
> Dependency Injection - formatting fix (missing bullets)

- aspnetcore/blazor/globalization-localization.md
Fixes #31694
Thanks @MartinNr5! 🚀 ... This was very educational for me, and I'm glad it worked out. I think Tim's extension is the way to go, and I have no problem recommending it to users. Although, I did need to say here that it isn't maintained or supported by MS.
@hishamco ... Here it is. I added some additional updates to make it clear that these files need to be SxS with the component in the `Pages` folder.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/f5f00df87b499de3206ea999ecc62b7373ed1cad/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr- …
> Include a VSC path for resource files

- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #31724
@hakenr ... 
* I couldn't fully integrate the "detector" sections with the `OwningComponentBase` section because there's still too much code and too many remarks. However, I did re-organize the presentation to make these sections into sub-sections of the *Utility base component classes to manage a DI scope* section. That should be fine.
* WRT your other remark about the lead-in paragraph. The earlier work from yesterday hasn't merged to the live branch yet. That's stale content on the live site at this time. Let me finish this up first, then I'll take the new content live. We can see if a new issue should be opened to talk to Mackinnon about it. I'll ping you back in a bit.
---
|:--|:--|
| …
> Cross-link (don't show) example code

- aspnetcore/blazor/fundamentals/startup.md
It appears that the _Standalone Blazor WebAssembly_ is missing here, unlike in many subsequent sections where the _Blazor Web App_ is typically presented first, followed by WASM/Server code snippets.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/6eecbe366adfa0cfd908f0c00b69d52c8d7ebd13/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-31746) |
> Startup - manually start Standalone Blazor WebAssembly

- aspnetcore/blazor/fundamentals/handle-errors.md
In the linked example, the component name is now `Notifications.razor` (used to be `ReceiveNotification.razor` pre-net8)
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/371b7103681d44b578acffdaec7726f50611dfde/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-31763) |
> [Blazor] Handle errors - Example component name correction

- aspnetcore/blazor/file-uploads.md
Although the code snippet in this commit is representing a non-recommended practice, the `async` call should be awaited.
The problem being highlighted in the code snippet is the practice of loading the file into the `MemoryStream`. Having an non-awaited `async` call in the same example confuses the example because it is unclear if the problem is the lack of `await` or the overall approach.
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/8b1076f7a93b155ec6d91c2d012198cd8822962e/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-31779) |
> Add missing await call

- aspnetcore/release-notes/aspnetcore-9/includes/debugger.md
This fixes the "before" image being used twice.
Before/Before:
Before/After:
> Use correct after image for ASPNetCore 9 Debugger release notes section

- aspnetcore/grpc/netstandard.md
Ready for review, **not ready for merge**. A new release is required before merging the documentation.
---
|:--|:--|
| [aspnetcore/grpc/netstandard.md](https://github.com/dotnet/AspNetCore.Docs/blob/62cde09a63d4acb157ee850d13c5246fc88c6e91/aspnetcore/grpc/netstandard.md) | [Use gRPC client with .NET Standard 2.0](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?branch=pr-en-us-31482) |
> Update required Windows version for WinHttpHandler to include WS2019

- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #31688
* ~[Transient disposable section updates](https://github.com/dotnet/AspNetCore.Docs/issues/31689): I have everything I need to resolve this, and I should reach it on Tuesday 🤞🍀.~ **UPDATE**: This is resolved now.
* [PU review of *Pass tokens to a server-side Blazor app* section](https://github.com/dotnet/AspNetCore.Docs/issues/31691): Currently assigned to both Stephen and Jeremy, but perhaps only one pass by one PU 🐱 will suffice.
Dan ... You said you'd provide a code example, but it 🤔 ***seems like*** the current code is ok. The updates to the section are on the DIFF, so you can see the current code there. The focus of the updates thus far is just to 🔪 OUT the little bits of text that pertain to hosted WASM and updating the versioning to return the content …
> Offline discussion updates for 8.0

- aspnetcore/blazor/fundamentals/signalr.md
It seems inappropriate and somewhat unnecessary to remind everyone to include `using System;` for every demo. The topic of SignalR, especially the demos that involve configuring specific options, is quite advanced, and it's reasonable to assume that the audience is already familiar with such details.
(By the way, the Blazor templates use `<ImplicitUsings>enable</ImplicitUsings>`.)
I've noticed this reminder in other topics, but this time, it really felt superfluous.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/96a203748e942016e6369ff828d05ab2ecd79e84/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/bl …
> [Blazor] SignalR - remove "using System" reminder

- aspnetcore/blazor/components/layouts.md
Fixes #31814
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/4eba51805ed93cb46e1694dbd72aaf0e226753f0/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-31815) |
> fix: #31814 wrong hyperlink

- aspnetcore/fundamentals/dependency-injection.md
- aspnetcore/fundamentals/dependency-injection/includes/dependency-injection-5-7.md
Fixes #31786
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/89963cac71ad488a01ffd8b603b7ac4c509a5585/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-31807) |
> fix: #31786 correct url to sample project in DI pages

- aspnetcore/grpc/error-handling.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2368
---
|:--|:--|
| [aspnetcore/grpc/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/8d8b027e526db563bdb801c8acae9ca4006fcbe3/aspnetcore/grpc/error-handling.md) | [Error handling with gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/error-handling?branch=pr-en-us-31809) |
> Link to Grpc.StatusProto package

- aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts/Pages/Privacy.cshtml.cs
Fixes #31825
The snippet wasn't included in the .NET 6 sample.
> Copy snippet to .NET 6 sample

- aspnetcore/performance/response-compression.md
Since [.Net 6](https://github.com/dotnet/runtime/commit/7d527c33681d0f844639249012f4e16e22fc1192) there has been an additional option: `CompressionLevel.SmallestSize`. And since .Net 7 `CompressionLevel.Optimal` was [also changed for brotli](https://github.com/dotnet/runtime/commit/f281393412758b1345a8dc5073b91f9e950e683d)  to not mean smallest size anymore but rather a balanced value.
This change is also documents what these abstracted `CompressionLevel` values means for underlying Gzip and Brotli compression libraries, given those are enabled by default. In my case I came to this page wanting to get an Idea of balancing CPU use vs size of the response, as there are plenty of pages online benchmarking zlib vs brotli at all possible levels and cpu types.
Fixes #31836
---
| 📄 File | 🔗 …
> Add CompressionLevel.SmallestSize and actual Gzip/Brotli compression levels

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31045
cc: @julioct ... My guesses on dealing with roles/role claims were good. The approach of ***NOT*** trying to fight the JSON serializer/deserializer to work with `Claim` arrays turns out to be the right way to go. Use of an anonymous type on the `/roles` endpoint side (backend server API) is fine, and using a custom `RoleClaim` type on the frontend is also good. These are the low-hanging-fruit ***happy paths*** 😄.
WRT other claim types, we're going to leave that to the devs to work out from this example. It's a straightforward update to this code to send all of the claims. The frontend code will take whatever is sent back and make user claims out of it. We might do more in this area down the road, but I need to get on with other work for now 🏃‍♂️😅. I'll take feedback from the …
> Add roles and test user guidance

- aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md
Fixes #31840
---
|:--|:--|
| [aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/566c9d80155e23972df379254a588a17929ced0e/aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?branch=pr-en-us-31841) |
> Redirect to the home page

- aspnetcore/blazor/components/index.md
Addresses #31845
@hakenr ... I'm going to condense this and revise the cross-linking a bit. This will solve part of the problem by avoiding getting into the weeds on the subject here in the *Components* node overview. All I really want here is an explanation of the existence of route params with cross-links back to the *Route parameters* section. Then, that section (and possibly something done with the *Lifecycle* article that pertains to setting params) can take over with the full explanation.
This is going to lead to killing off 🔪 the `OptionalParameter` component in the sample apps and only using `RouteParameter1` and `RouteParameter2` components in the sample apps and in the *Routing* article.
---
|:--|:--|
| …
> Update Route params section

- aspnetcore/blazor/fundamentals/startup.md
Fixes #31811
Marek ...
* Along with correcting any mistakes that a 🦖  made 🙈😄, is there any additional info that should appear?
* Was the bit of text you stated for `onRuntimeReady` ... "*and passed in the .NET runtime API*" ... important to keep? I 🔪 it, but I'll add it back if it's important to call that out.
* Is the sample code that you cross-linked OK to show here with these?
* Are there any gotchas 😈 that devs should be aware of?
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/4cea4de517e8ac7498c8575adbc9029b758a3381/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-31852) |
> Add WebAssembly (runtime) startup callbacks

- aspnetcore/fundamentals/minimal-apis/includes/middleware7.md
- aspnetcore/fundamentals/minimal-apis/includes/middleware8.md
- aspnetcore/fundamentals/minimal-apis/middleware.md
Fixes #31502
Clarified first paragraph and added links for WebApplication and Minimal APIs Overview.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce95704df012f545f5166ccde696505a388684be/aspnetcore/fundamentals/minimal-apis/middleware.md) | [Middleware in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?branch=pr-en-us-31857) |
> Middleware in Minimal API: Add links

- aspnetcore/blazor/components/render-modes.md
Current Visual Studio New Blazor Web App project wizzard no longer uses checkboxes for render-mode related options.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/ec26dd79afc972b1819ed7094e75897e9985e2b7/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31864) |
> Blazor Render Modes - Visual Studio project template options

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #31740
Thanks @mrlife! 🌴 ...
* This has a unique and narrow scope, so I thought it best to cover it in a section at the bottom of the *Render Modes* article.
* I rejected it for the DI topic because not enough has been covered by that point in the readings to make full sense of it. I placed a cross-link at the bottom of the DI topic to this section.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ab4f53b456e850c26a25b4b01b87c31b2581847/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31867) |
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://gith …
> Services via the top-level imports file

- aspnetcore/blazor/fundamentals/handle-errors.md
Fixes  #31765
@hakenr ... I'd like to try and fix what's here. It seems faster to just adopt Steve's pattern ... ***the correct approach*** 🙈 ... by merely ...
* 🔪 out the `OnNotify` piece.
* Call `DispatchExceptionAsync` for the timer in the component in the way that Steve proposed calling it.
This only requires a few small changes to what's here, which makes this a quick 🏃‍♂️ update.
WRT a component example for this in the sample apps, I placed a tracking item for it on my long-range tracking issue. I also cross-linked the example that you provided. It might be a good idea to include your example. The text could receive a cross-link and quick description of the alternative approach. I'll consider it further when I reach that item on my long-range tracking issue.
Sorry about the churn …
> Update DispatchExceptionAsync example

- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Improves readability.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/36db048b89d62b71aa0c953525f26d026f519d04/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-31883) |
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/36db048b89d62b71aa0c953525f26d026f519d04/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?branch=pr-en-us-31883) |
> Use generic Enum.GetValues<T>() method instead of (T[])Enum.GetValues(typeof(T)) (net5+)

- aspnetcore/test/integration-tests/includes/integration-tests7.md
This PR removes the deprecated `ISystemClock` in the 8.x docs
Fixes #31484
The samples should be merged first at https://github.com/dotnet/AspNetCore.Docs.Samples/pull/249
Steps:
- copy pasted the existing docs page to `integration-tests7.md`
- update moniker range in 7.x docs, and update references within the sample (add the 7.x folder into the path reference), e.g. `test/integration-tests/IntegrationTestsSample/src/RazorPagesProject/Program.cs` becomes `test/integration-tests/7.x/IntegrationTestsSample/src/RazorPagesProject/Program.cs`
- updated references to v8 sample in existing docs, e.g. `test/integration-tests/IntegrationTestsSample/src/RazorPagesProject/Program.cs` becomes `test/integration-tests/8.x/IntegrationTestsSample/src/RazorPagesProject/Program.cs`
- update moniker range …
> remove deprecated ISystemClock

- aspnetcore/tutorials/min-web-api.md
Fixes #31882 
- Instruction and commands for adding prerelease packages were removed.
- Made a few corrections in some list punctuation for consistency and a couple of quick grammar improvements.
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/838e3badcdd7de5c4634e0f2fecfcf6e4838d2d2/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-31892) |
> Min Web API tutorial: Remove prerelease for packages

- aspnetcore/migration/70-80.md
Fixes #31907
Thanks @Stra1ghter! 🚀 ... I think this should leave the "`.Client`" segment out because that's part of the client project's assembly name, and assembly name is what is used in the placeholder for what to change.
... but I just added a description of the placeholders with examples.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/345b973391a0b5020342b8138471c03d390eaa30/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core in .NET 7 to .NET 8](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-31908) |
> Add step to hosted Blazor WASM migration guidance

- aspnetcore/index.yml
[Internal review: Hub page for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/?branch=pr-en-us-31913&view=aspnetcore-9.0)
Fixes #31578 
The ASP.NET Core hub page was specified as one of the Hub pages that could use some changes per hub OKR.  It had some high traffic links below the fold that needed to move up, some low traffic links above the fold where we provided too many doc choices per app type, and too many duplicate links.
- I reviewed traffic, clickthrough, exit rate, bounce, heatmap, and general report data available.
- Verified what should move above the fold per that data.
- Reviewed current published HUB with OKR stakeholders for suggestions per site wide initiative for Hub pages.
- Removed some duplicate links where it made sense.
**Top section:**
Summary: …
> Hub page update per data and OKR

- aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program2.cs
- aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program3.cs
The previous paragraph says
> Use the fields of the [StatusCodes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes) class for assignments to `RedirectStatusCode`.
But the sample code then uses the status code defined in `System.Net` and a cast to `int`.
> Enforce HTTPS in ASP.NET Core: Use Status308PermanentRedirect

- aspnetcore/blazor/components/synchronization-context.md
I believe the emulation of a single-threaded environment in Blazor server-side is scoped only to an individual circuit (or a request for static SSR).
(It seems the multi-threading will be part of net9, but for now...)
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/synchronization-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/589bfabbe2f14181cac69bd931ac390ed7c301cd/aspnetcore/blazor/components/synchronization-context.md) | [ASP.NET Core Blazor synchronization context](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/synchronization-context?branch=pr-en-us-31910) |
> Blazor - Synchronization context - circuit-scoped emulation of single threaded environment

- aspnetcore/blazor/components/layouts.md
`_Imports.razor` is not a component.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/d9a4ed1561514b2832ab022fab04fe9c322ea2f4/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-31930) |
> Blazor - layouts.md - _Imports.razor file

- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #31926
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d08550d0e5605c8b86d2889e024d987581ff25d/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-31927) |
> Ctor service injection

- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31389
Addresses #31205
FIRST ... before reviewing the article DIFF on this PR ... let's sort out the sample updates at ...
https://github.com/dotnet/blazor-samples/pull/210
* NIT updates on the PR
* Move CORS in the pipeline above the logout endpoint.
* Lowercase the logout endpoint from `/Logout` to `/logout`.
* Change conditional check `empty != null` to `empty is not null`.
* Place a line of spacing above `return`s ... that's by convention for Blazor example code.
* Remove null-forgiving ops from `email` and `password`, as they can't be null.
* Remove the `UserBasic` class, as it isn't used.
* Same-site/secure policy settings: Add commented-out default-setting code for it.
* Add a quick-'n-dirty data processing experience.
* Form in a page that uses the `Auth` …
> WASM+Identity same-site & antiforgery updates

- .vscode/settings.json
- aspnetcore/blazor/performance.md
> It's rare that too many parameters severely restricts performance, but it can be a factor. For a `TableCell` component that renders 1,000 times within a grid, each extra parameter passed to the component could add around 15 ms to the total rendering cost. If each cell accepted 10 parameters, parameter passing would take around 150 ms per component for a total rendering cost of 150 ms (0.15 seconds) and cause a UI rendering lag.
I believe the original information from benchmarks was "when rendering 1,000 `TableCells`, adding one more parameter adds 15 ms to the total rendering cost". With 10 parameters, it's 150 ms in total (still with the original 1,000 `TableCells` involved), not 150,000 ms (150 sec). The 150-sec number is too high to believe. ;-)
cc @guardrex 
---
| 📄 File | 🔗 Preview …
> [Blazor] Performance - Too many parameters timing calculations correction

- aspnetcore/fundamentals/logging/index.md
- aspnetcore/fundamentals/logging/index/samples/3.x/TodoApiDTO/Pages/Contact.cshtml.cs
This is a follow up to https://github.com/open-telemetry/opentelemetry-dotnet/pull/5405#discussion_r1508527541 based on discussion with @noahfalk and @tarekgh.
Related to https://github.com/dotnet/docs/pull/39777.
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a402ddca98bb99fa2fb6a6046d2016001f3e0d1/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-31963) |
> Refine the log category convention

- .vscode/settings.json
- aspnetcore/blazor/components/data-binding.md
The current text doesn't accurately represent how the original _Forms_ page was split into separate pages: _Input components_ and _Forms validation_.
It seems the intention was to express that both input components and form validation components will be used together.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/15bf22d291054f8dca0af66c4442b6798dec7c1d/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-31968) |
> [Blazor] Data Binding - fix for input components and forms validation xref

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/prerender.md
- aspnetcore/fundamentals/minimal-apis.md
Fixes #31887
I haven't reached security updates yet. Security updates will be handled by a separate issue/PR shortly.
This is going in ***NOW*** 🚑🚒🚓 to surface better coverage and the sample apps quickly. I'll be circling around for more updates and to address security guidance for calling web APIs shortly ... by the EOW hopefully 🤞🍀.  
The sample apps are here ...
* Blazor WASM with a separate backend web API for todo list web API
https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyCallWebApi
* Blazor Web App with the separate backend todo list web API (uses `HttpClient` server and client to interact with it) ***AND*** a separate movie list web API that resides in the server project of the BWA. For movie list interaction, the components use either the client-based …
> Call web API article updates

- aspnetcore/mvc/views/tag-helpers/intro.md
Surfaced on the build report. Let's have the reader Google it if they aren't familiar with HTML Helpers.
---
|:--|:--|
| [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/73d0956a7aaf733bf1313849bea7aa9d5249d111/aspnetcore/mvc/views/tag-helpers/intro.md) | [Tag Helpers in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?branch=pr-en-us-31974) |
> Remove broken links

- aspnetcore/blazor/components/data-binding.md
Fixes #31969
@hakenr ... Let's start with something simple to avoid confusion that Line 558 is merely a lead-in remark to the next paragraph ... ***by 🔪 it!*** 😄 Let's try allowing the first sentence of the next paragraph to state that `@bind` is insufficient.
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/45d1840e1f3ec1cacf4524e559668f8a4350cae6/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-31971) |
> Improve chained bind section

- aspnetcore/blazor/globalization-localization.md
Fixes #30002
@hishamco ... I have another 🙈 ***RexHacks!***&trade; 🦖 approach here. It ***SEEMS*** to work, but IDK if there are some 🐉🐉🐉 with what I did or some lurking 😈😈😈 in here.
Because of the complexity of this, I thought you might want to pull it down and run it locally, so I placed my test app at ...
https://github.com/guardrex/BlazorCulturePerComponentInteractivity
There is one thing here that I don't understand. When changing the culture from a CSR component (in the sample app, changing it from the `CultureClient` component), it does seem to update the localization cookie and carryover to the server-rendered component (in the sample app if you then navigate to the `CultureServer` component). It's not clear to me where/how the localization cookie is being updated …
> Add BWA global Auto approach

- aspnetcore/blazor/hybrid/tutorials/windows-forms.md
- aspnetcore/blazor/hybrid/tutorials/wpf.md
Fixes #31995
Thanks @alvinashcraft! 🚀 ... I added it to the WinForms tutorial as well. I don't have time to test it there, but I'm sure a reader will come after me if it fails 💀😨😄. One sad thing in this ... Bootstrap versions ***ALL*** of their content at their website, including their download page, so I can't add a direct link here. I must tell readers in the text how to navigate at their site. They might have a permalink system, but IDK if they have it or how to get a hard (versionless) link to their download page. I think that's kind'a silly, but whatever ... anyway ... we have the coverage now. Thanks for the issue! 
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/25f727474f954242ce27e91af …
> Add Bootstrap to Blazor Hybrid tutorials

- aspnetcore/blazor/components/overwriting-parameters.md
No PageTitle prior to net6
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/c2540b290d0ed764fc7c41e0cf7c79dd7eed0713/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-32012) |
> [Blazor] overwriting-parameters - suck updated samples

- aspnetcore/blazor/components/data-binding.md
>Using an event callback parameter with `@bind:set` (`[Parameter] public EventCallback<string> ValueChanged { get; set; }`) isn't supported. Instead, pass a method that returns an [Action](https://learn.microsoft.com/en-us/dotnet/api/system.action) or [Task](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) to `@bind:set`.
I think the `@bind-Value:set` actually supports the `EventCallback<T>`.
The paragraph probably clones the similar statement which is correct:
>Using an [event callback parameter (`EventCallback/EventCallback<T>`)](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0#eventcallback) with `@bind:after` isn't supported. Instead, pass a method that returns an …
> [Blazor] Data binding - @bind-Value:set - EventCallback<T> support

- aspnetcore/blazor/fundamentals/signalr.md
Fixes  #32021
Thanks @gerektoolhy! 🚀 ... This will log the ID ***and*** fix a few other NITs.
@MackinnonBuck ... The updates ***seem*** reasonable 🤔, but I'll wait for you to look because I don't think you saw the original content when it went in. This will give you a chance to look over the entire section in case there are additional remarks to make (e.g., ***gotchas*** 😈).
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/237fc677446c2dd06321e9deec0cfb61c284dc28/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32027) |
> Improve SignalR idle timeout example

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/httpsysextendedauth.md
- aspnetcore/release-notes/aspnetcore-9/includes/oidccustomparms.md
contributes to #31770 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/e853c018c2a062e1215dd9047e81b450f7ada3c9/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32034) |
> Add preview 2 features

- aspnetcore/tutorials/first-mvc-app/start-mvc.md
- aspnetcore/tutorials/first-mvc-app/start-mvc/includes/start-mvc7.md
Fixes #32045 
Should have been Control (^) key for macOS not Command to run without debugging.  Fixed.
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/cbb7b72592898d4043fa2017ccb6e300054fea66/aspnetcore/tutorials/first-mvc-app/start-mvc.md) | [Get started with ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?branch=pr-en-us-32052) |
> First MVC: Correct macOS command

- aspnetcore/migration/70-80.md
Fixes #31931
Thank you @CoskunSunali for that great write-up 🥇. I've combined your remarks with Stephen's response to address this subject in the *Migration* article. It's here for review if you would like to provide feedback 👂.
Stephen said on the issue ...
> It looks like the documentation at https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md ought to be updated to reflect that Blazor static files no longer rely on UseStaticFiles and instead are mapped using endpoint routing.
... but I think I need a more specific change set to update the article. I'm also not generally clear what "Blazor static files" means ... I don't think he meant that Static File Middleware no-ops in BWAs. I think he means that static assets managed by Blazor (the …
> Blazor Server script fallback policy authorization

- aspnetcore/blazor/components/cascading-values-and-parameters.md
Noticed in passing that using a custom class isn't the best example (at least not without showing the class in the explanation), so I'm changing it to use a built-in Bootstrap class that will work well for a "dark" UI theme example, which is `btn-secondary`.
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce2c5a28949e7961f98df9980c7e9e4330f0c72e/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-32058) |
> Patch button class in example

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #32026
Missing release changes on these has happened ***multiple times*** 😢 over the years because options changes usually don't rise to the level of a roadmap or blog post entry. Some changes even seem to occur outside of release labeling. The changes here harden the options for future PU updates by relying on the API docs for the options and reference source for the default values. We only have to hope 🤞🍀 that the option class names/locations don't change, which would break ref source links.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/82e566558cbbad5c8362f448327d0a8ba7bfc51f/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR …
> Harden API options

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
GitHub permissions are ANDed, not ORed. So, even though the sequester app was given permission to read and write pull requests, the configuration in YAML prevented it.
This ensures that if a PR is tagged as a work item, it will be imported correctly.
> Add permissions to write pull requests

- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/security/index.md
Fixes #31402
Thanks @FengRuikai! 🚀
I'm mostly going off of Javier's sentiment expressed here ...
https://github.com/dotnet/aspnetcore/issues/52176#issuecomment-1825677291
... and I'm cleaning up the approach for how we can convey this information:
* Add the guidance to the static SSR section of the *Render Modes* article. Include how devs should deal with these scenarios server-side.
* Clean up and cross-link that from the `<NotAuthorized>` content in the *Security* article.
* Clean up and cross-link that from the `<NotFound>` content in the *Routing* and *Layouts* articles.
Also, are there any other scenarios that fall into this bucket outside of `<NotFound>` and `<NotAuthorized>` content that we should add to the list here (and cross-link from outside the article)?
... and btw ... …
> Server-side behaviors during static SSR

- aspnetcore/fundamentals/host/generic-host.md
Fixes #32069
Update the default value for ShutdownTimeout according to https://github.com/dotnet/runtime/blob/v8.0.3/src/libraries/Microsoft.Extensions.Hosting/src/HostOptions.cs#L24
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/9f42265f7cdc28686e7871ab20ec53c8a6b23ac0/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-32070) |
> ShutdownTimeout default value in documentation

- aspnetcore/blazor/components/event-handling.md
This is the very first example for `eventCallback.InvokeAsync()` in the whole article and I think we should show that the `InvokeAsync` method accepts the argument to be passed within the callback.
We might also use a placeholder:
```csharp
await OnClickCallback.InvokeAsync({ARG});
```
where we descibe the `{ARG}` as optional argument.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/c99e7904feae7eda85db7b50bc21632ed69bf811/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-32085) |
> [Blazor] Event handling - first InvokeAsync example with args

- aspnetcore/blazor/components/lifecycle.md
Such changes, typically breaking, are now uncommon, and the potential for these changes is inherent in the definition of a "major release." I believe there's no need to intimidate developers in the documentation by explicitly mentioning this.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/2bf246e565d58cc4c207d9bc5222e3322f0253d3/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32090) |
> [Blazor] Lifecycle - remove breaking-changes notice

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #32008
Jeremy ... Three things on this one ...
* Do you want to say more than this in the *Call web API* article? I figure that this along with the *Standalone with Identity* article (+sample), which is cross-linked here, should be enough. Are there any :smiling_imp: ***gotchas*** to call out or anything else?
* AFAIK, the only versioning that this needs is for the *Standalone with Identity* article (>=8.0). I think the rest of this always worked. AFAIK, we just didn't have it because we were pushing token auth for just about everything. We have a bit of this in the next section, which is generalized for Fetch API options. We just didn't have it in a dedicated cookie auth section. Anyway, any concerns about showing this for all versions?
* The API engineering comment for the handler …
> Blazor WASM cookie security for web APIs

- aspnetcore/blazor/components/lifecycle.md
The original explanation could have been misunderstood, implying that `OnAfterRender[Async]` is not called for any of the server rendering scenarios (including _interactive SSR_).
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/79f87fc00deefb14b90a5ae527929345a2760ac5/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32116) |
> [Blazor] Lifecycle - When is OnAfterRender not invoked

- aspnetcore/blazor/components/lifecycle.md
The `if (firstRender)` is demonstrated in the `AfterRender.razor` sample. It seems unnecessary to complicate the `OnAfterRenderAsync` sample, which is meant to illustrate asynchronous usage, by making users wonder why `await` is used inside `if (firstRender)`.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/f97d6fd0ad07181317ce2fec0664f8a94dd0693d/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32121) |
> [Blazor] Lifecycle - remove if (firstRender) from OnAfterRenderAsync sample

- aspnetcore/blazor/includes/prerendering.md
There's no such thing as a "JS element" (in this context).
I believe the term intended here is "HTML DOM element" (which can be abbreviated to "HTML element," but we can retain "HTML DOM element" to emphasize the meaning).
cc @guardrex
> [Blazor] include/prerendering.md - JS element => HTML DOM element

- aspnetcore/blazor/project-structure.md
Fixes #32133
Thanks @Maintenance-Partnership-Systems! 🚀 ... This should clarify that the Blazor WASM section, named *Standalone Blazor WebAssembly* going forward, isn't part of the *Blazor Web App* section. WRT MudBlazor (or any other external docs that we don't control), you'd need to let them know that their guidance for BWAs is incorrect. I assume that they'd update their docs to indicate that the HTML markup they're seeking to have you add to a BWA would be for the `App` component of the server project.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/bceb991593577f5f2d6ac75448838035dfdfb20f/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project …
> Improved Project Structure article WASM headings

- aspnetcore/blazor/components/lifecycle.md
In the context of Blazor, `IDisposable` and `IAsyncDisposable` enable components to perform cleanup logic. However, it's important to note that this still involves managed logic. Components are generally not designed to directly use unmanaged resources, like file handles, which would necessitate the use of finalizers (destructors).
Therefore, we should avoid using the term _unmanaged_ in the context of Blazor.
(I'll propose adding an explanation about why we don't use destructors in Blazor in a separate issue.)
cc @guardrex
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/d625fce4a143322515385fcad264e7964d4fd178/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component …
> [Blazor] - Lifecycle - Incorrect usage of "unmanaged" term

- aspnetcore/blazor/components/event-handling.md
I believe the `await Task.Yield()` in the `ParentChild2.razor` example no longer makes sense. It probably remained from an earlier era of Blazor when these in-line lambdas had to be asynchronous.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/e692389396709bbe8bee0398aa98ac0dcc7ae3c3/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-32086) |
> [Blazor] Event handling - ParentChild2.razor without Task.Yield()

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32146
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/91e2aae55af725a05b302dd42af9f3d7da5013f9/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32149) |
> Update scope/authority guidance in BWA+OIDC article

- aspnetcore/blazor/components/control-head-content.md
- aspnetcore/migration/70-80.md
Addresses #32138
This just resolves the page title aspects of the issue. An upcoming PR will address the security aspects.
---
|:--|:--|
| [aspnetcore/blazor/components/control-head-content.md](https://github.com/dotnet/AspNetCore.Docs/blob/b804297c61df806f4425ca3a641b2335c43b819a/aspnetcore/blazor/components/control-head-content.md) | [Control `<head>` content in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?branch=pr-en-us-32144) |
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/b804297c61df806f4425ca3a641b2335c43b819a/aspnetcore/migration/70-80.md) | [[Visual Studio Code](#tab/visual-studio-code)](https://review.learn.microsoft.com/en-us/aspnet/core/migrat …
> Control <head> content and migration updates

- aspnetcore/fundamentals/configuration/index.md
Fixes #32114 
Url corrected
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/676a418463deabb38761fa4c0a73dbfffbc466d6/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-32178) |
> Fix url pointing to Configuration-binding source generator

- aspnetcore/blazor/security/index.md
Fixes #32053
Thanks @cosmic-tiger! 🚀 ... I'm not going to list every authorization check, as they all appear in later sections of the article. I add a remark stating that if authorization must be guaranteed that the dev should avoid building a client-side app.
> why bother implementing authentication if it can be by-passed? Might as well use server side
*Yes!* ... That's exactly right. That's exactly what a dev should do if they want guaranteed authz checks and to secure data/code from prying eyes 👮😄.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3377aed7f644b07b03bfc63375962e7d51a2f8e9/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and …
> Improve authorization opening remarks

- aspnetcore/fundamentals/minimal-apis/7.0-samples/WebMinAPIs/Program.cs
- aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
- aspnetcore/fundamentals/minimal-apis/parameter-binding.md
This PR updates the code highlighting and removes some unneeded blank lines (see screenshots).
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32046#issuecomment-2003656101
The second commit unifies the way code snippets are included in the article to use the moniker(?) syntax. If needed I can revert this commit.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/parameter-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/8bd7cfb9289ec2105c213fd9985c50b8c396bd4b/aspnetcore/fundamentals/minimal-apis/parameter-binding.md) | [Parameter Binding in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?branch=pr-en-us-32214) |
> update line highlighting and spacing

- aspnetcore/blazor/components/rendering.md
I believe that when presenting a bullet list of approaches to manage state in Blazor, we should list the built-in approaches first.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/69a2851358882494c3abee9a18cbcc7a161e33d0/aspnetcore/blazor/components/rendering.md) | [ASP.NET Core Razor component rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?branch=pr-en-us-32227) |
> [Blazor] Rendering - order of approaches to manage state

- aspnetcore/blazor/components/rendering.md
Minor adjustment to the `ShouldRender`-related condition on when rendering is skipped (to improve clarity).
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/a7b94c6ff001964d2147df6434e479807aec7547/aspnetcore/blazor/components/rendering.md) | [ASP.NET Core Razor component rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/rendering?branch=pr-en-us-32226) |
> [Blazor] Rendering - ShouldRender explanation

- aspnetcore/blazor/components/virtualization.md
My original concern was that this bullet
> * Only fetches the slice of records from an external API that correspond to the current visible region, instead of downloading all of the data from the collection.
does not specify that this happens only when `ItemsProvider` is used.
I've attempted to rearrange the text, though I'm uncertain if I've achieved the best possible result. @guardrex, I'll defer to your expertise to determine if this is usable or if a better solution can be found.
(Technically, one could envision a setup with an `ICollection Items` where `.Skip().Take()` in `Virtualize.DefaultItemsProvider` might achieve a similar effect, but that's not how the Virtualize component was meant to work.)
---
|:--|:--|
| …
> [Blazor] Virtualization - data slicing clarification

- aspnetcore/blazor/components/dynamiccomponent.md
@guardrex, this draws the new samples from https://github.com/dotnet/blazor-samples/pull/256 and includes related adjustments
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/0538fadd32792fb47d0ede5ab9f86aac6e96eb5a/aspnetcore/blazor/components/dynamiccomponent.md) | [Dynamically-rendered ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-32251) |
> [Blazor] DynamicComponents - fixes samples vulnerability + related adjustments

- aspnetcore/blazor/fundamentals/environments.md
In the example, IWebAssemblyHostEnvironment is injected as `Env`, but referenced in the code as `@HostEnvironment`. Modified the `@HostEnvironment` to be `@Env`.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/6c83b6129bbc3ad14a2264fc20a8307d790b84d0/aspnetcore/blazor/fundamentals/environments.md) | [ASP.NET Core Blazor environments](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-32256) |
> Update @HostEnvironment to @Env

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32243
Thanks @nwoolls! 🚀 ... I'm adding a NOTE to clarify that `IHttpContextAccessor`/`HttpContext` isn't used for interactively-rendered components with a cross-link to that guidance.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/c2138cbc1c9acd3d6bc8186200bb836d645c329c/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32260) |
> Clarify use of IHttpContextAccessor/HttpContext

- aspnetcore/signalr/groups.md
Fixes: #29736
Clarifying:
- Group data is kept in-memory and do not persist.
- You are allowed to add users multiple times to a group, it will not throw an exception.
Also a little bit of cleanup.
---
|:--|:--|
| [aspnetcore/signalr/groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/faf6cffea9e0b97634a63aa3027efa0b69194eb1/aspnetcore/signalr/groups.md) | [Manage users and groups in SignalR](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/groups?branch=pr-en-us-32261) |
> SignalR: Clarify groups

- aspnetcore/blazor/components/dynamiccomponent.md
Looks like they moved the 🧀 on this one!
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/76c37f7742ebb7dbd6b316f156577b66ec578cf2/aspnetcore/blazor/components/dynamiccomponent.md) | [Dynamically-rendered ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-32267) |
> Link update

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #30278
Marek ... I'm confused on the setting you provided ... 256 MiB (BTW, they won't allow us to use MiB, so I'm just going to show bytes and write "bytes" for this guidance) ... anyway ... 256 MiB ... or 268,435,456 bytes.
According to https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/WasmApp.Common.targets, the default is listed a lot higher ...
> - $(EmccMaximumHeapSize) - Maximum heap size specified with `emcc`. Default value: 2147483648 or size of the DLLs, whichever is larger. Corresponds to `-s MAXIMUM_MEMORY=...` emcc arg.
... **2,147,483,648** bytes ... 2 gigs.
So ... is the remark in that file incorrect on the default? If so, what's the actual default value?
Otherwise, the PR is ready for review.
---
|:--|:--|
| …
> WASM runtime max heap size

- aspnetcore/blazor/components/js-spa-frameworks.md
***Arrrrrgh!*** 😡 Looks like one of these snuck in here from content that arrived for the article. 
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/25748d51eefa433102701f1dddc59bb5a65f3e76/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-32275) |
> Remove sneaky component reference

- aspnetcore/blazor/fundamentals/configuration.md
Fixes #31152
Thanks @HaraldSchmitt! 🚀 ... I'm resolving this by ...
* Noting that it's ***PUBLIC*** security config that goes into the file ... public data that's required for the security implementation to work properly by-design. I both **bold** and *italicize* the word "public" in the security section to highlight that fact.
* Further, I place a copy of that warning in that section with a modification to clarify that it's the web root-served (`wwwroot` folder) app settings file that's of concern. A server-side app settings fine remains secure on the server, so that's not a concern here.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a81bbe98963f46054af9aa1858d9c9a12114d38/aspnetcore/blazor/fun …
> Improve guidance on security config with app settings files

- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
Fixes #30788
Thanks @philip-reed! 🚀 ... This is an important improvement to the coverage.
Since we discussed this, there was a considerable overhaul to the Graph API article, which included updates to the remarks on scopes. Those updates also ensure that devs can get over to the Azure docs for more info.
Here, I think the article should merely indicate delegated scope(s) for the client and application scope(s) for the server app with a bit of explanation on why one is delegated and the other is for the application. Beyond that, devs should access the Identity platform/Azure docs for more info, as they have extensive coverage. I'm improving the cross-linking by adding a second cross-link to helpful information over there.
---
|:--|:--|
| …
> Add additional scope guidance

- aspnetcore/blazor/components/generic-type-support.md
Fixes #31905
Thanks @hakenr! 🎸 ... This won't address all of your suggestions, but it will improve the state of the doc with the following updates ...
* `ListDisplay1` and `ListDisplay2`/`ListDisplay3` and `ListDisplay4` component pairs, which only distinguished by color as an additional helpful way to see the different collections in rendered output, are condensed into a single component each, passing the color as a param. This helps a little ... just a little bit ... with your concern about simplifying the guidance.
* Makes some component name changes, but it doesn't go as far as you suggest because numbering helps me maintain the examples and lists the components together in a sample app for devs to find them easily.
* Moves all examples into the sample apps. However, these are only …
> Generic type article improvements

- aspnetcore/blazor/debug.md
Fixes #31281
Thanks @Bradtus! 🚀 ... Let me know when you get the title of the `dotnet/runtime` PU issue changed.
@maraf ... Given how hard it is to understand the <8.0 behavior and the fact that use of <8.0 will recede in coming years, I think we should only document this for >=8.0. Let me know if you disagree and please suggest text. What you said on the PU issue is very challenging to comprehend for <8.0. The cross-link is here, so devs can get into the weeds of your complete answer if they want to. At this point, I don't think the article has to cover that level of detail.
BTW @maraf ... In case @Bradtus doesn't see this, could you change the name of that PU issue at https://github.com/dotnet/runtime/issues/96239?
Go from its current title of ...
> Blazor WASM Custom debug configs need …
> Add Debugger support section

- aspnetcore/blazor/components/integration.md
The original text could be misinterpreted in a way that Blazor switches from interactive-SSR to WASM immediately after the  Blazor bundle has been downloaded (within first visit).
I reused the wording from https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#automatic-auto-rendering
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/f008fc35632a018cf11f590afa5493c12cb56a93/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-32313) |
> [Blazor] Integration - Autor render mode explanation

- aspnetcore/blazor/components/quickgrid.md
Fixes #32312
Thanks @johndhunter! 🚀 ... In addition to fixing the line about EF Core and adding a formal EF Core section to contain that guidance, I'm also adding the *Remote data* section from the QuickGrid sample (the one that makes an OpenFDA database call).
Do you want to look at this before I merge it? I leave it open for a few hours for you to look.
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/8914b7bae2332558f79afaec6aa5ea4379e18483/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-32317) |
> Update QuickGrid guidance

- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/first-web-api/samples/7.0/TodoApi/Controllers/TodoItemsController.cs
The DOCS has wrong references for the PostTodoItem on the first-web-api tutorial.
Fixes #32320
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/86226e52d76f0610723b96e62cf1068eefdfa224/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-32321) |
> [WebAPI Tutorial] - Wrong references for PostTodoItem

- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/first-web-api/includes/first-web-api3-7.md
- aspnetcore/tutorials/first-web-api/samples/2.2/TodoApi/Controllers/TodoController.cs
- aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/5.x/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/7.0/TodoApi/Controllers/TodoItemsController.cs
Adjust places where GetTodosItem is referenced wrong, when needed to be PostTodosItem
Fixes #32326
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/ee66486fc50403721c3973cb3102a49fd22e6d03/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-32328) |
> First Web API: Test PostTodoItem section: GET rather than POST used in return

- aspnetcore/blazor/components/index.md
Fixes #31042
We'll call this out because it's valid, but we'll recommend not adopting the approach.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/aef92c6bf106c33cdd31344ba937131291e4df4b/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32333) |
> Optional (but not recommened) Razor directive attribute syntax

- aspnetcore/blazor/includes/js-interop/js-collocation.md
`Pages` is part of the `{Path}` in specification of the target folder.
(If the source component is not placed inside `Pages` folder, there is no such folder present in destination path.)
cc @guardrex
> [Blazor] js-collocation - remove `Pages` from destination folder

- aspnetcore/blazor/includes/js-interop/js-collocation.md
The only possible value of `{EXTENSION}` placeholder is `razor`.
(Removing the placeholder also better aligns with the next paragraph.)
cc @guardrex
> [Blazor] js-collocation - remove {EXTENSION} placeholder

- aspnetcore/tutorials/getting-started-with-swashbuckle.md
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup1x.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup2.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup3.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.Swashbuckle/Startup4.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Startup.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.1/TodoApi.Swashbuckle/Startup2.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/Startup.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/Startup2.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/Startup3.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/readme.md
Fixes #32327
See app sample changes and Readme changes in **Files Changed**.
[Internal Review: cod highlight changes in Get started tutorial](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&branch=pr-en-us-32330&tabs=visual-studio)
Versions 2.2 though 3.0 had 10 different variations on Startup.cs examples using swagger that needed to be fixed so that swagger endpoints are only available in a development environment.
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8f2d340c9375e2f41fc759a9e6f72a5b4d52921/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET …
> Doc With Swagger: Enable only in dev env

- aspnetcore/blazor/components/templated-components.md
Fixes #32229
dependent on https://github.com/dotnet/blazor-samples/pull/266
@guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/20a73dbb80ae85486f00e16994207f74b1e827a7/aspnetcore/blazor/components/templated-components.md) | [ASP.NET Core Blazor templated components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?branch=pr-en-us-32360) |
> [Blazor] Templated components - TemplatedNavBar + keyed TableTemplate

- aspnetcore/tutorials/first-mongo-app.md
Fixes #30010 
Tested on VS and macOS scenarios.
- The original path setting instruction was confusing and not organized to clearly separate Windows from macOS/Linux. Rewrote to clarify.
- The instruction for the Open API test pages did not include selecting **Try it out** > **Execute**.  Added that.
- Updated VS for Mac instruction to remove Preview settings steps.
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/7bb4ebeb8b9699b8b171945fc2801d4045d87206/aspnetcore/tutorials/first-mongo-app.md) | [Create a web API with ASP.NET Core and MongoDB](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-32353) |
> WebAPI MongoDB: Clarify steps

- aspnetcore/tutorials/getting-started-with-swashbuckle.md
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/6.x/SwashbuckleSample/Snippets/Program.cs
Fixes #32414
UseSwaggerUI() moved to within dev env only.
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/5bb9e5d5e5b354f3bea55690143c74768b420da0/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?branch=pr-en-us-32416) |
> Swagger Update: web-api-help-pages: Sample fix

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #30136
@garrettlondon1 ... This is my best guess thus far based on PU discussion and framework behavior. We'll see what Mackinnon thinks when he gets back. I think he's out for some R&R 🏖️ at the moment.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/090436182d616d8e3c82ce0be1982c1748c95bd2/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32331) |
> Improve reconnection UI guidance

- aspnetcore/blazor/fundamentals/logging.md
Log level string replaced with its corresponding integer value (as Example2 is about integers)
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/ac456a3d40504ea54e3bb2fdbcecd7465d14c413/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?branch=pr-en-us-32429) |
> Fix typo in logging.md

- aspnetcore/blazor/globalization-localization.md
fixes #32365
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/1f2d640b10ff19558dc458122ad5eb497c3a203e/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-32433) |
> [Blazor] Globalization & localization - correct async JS interop

- aspnetcore/blazor/fundamentals/logging.md
The code, although intended to demonstrate function calls using integers, should avoid containing magic numbers. I've added a comment typical for such cases, similar to what you can find here:
https://github.com/dotnet/aspnetcore/blob/333629e6c3d4ee301bb5985f0de66f447f6226ba/src/Components/test/testassets/ComponentsApp.Server/Pages/_Host.cshtml#L20-L24
(In production code, we might want to minify the script, but here in the demo code, including a comment seems appropriate.)
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/de488369d2ae03544ca18b62fbcb32027ed23e2b/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/bla …
> [Blazor] Logging - comments for "magic numbers"

- .github/workflows/merge-live.yml
- .github/workflows/whats-new.yml
Hey! 🙂
I want to contribute the following changes to your workflow:
- Avoid executing  scheduled workflows on forks
- Stop running workflows when there is a newer commit in branch
(These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html))
> Fix potential github action smells

- aspnetcore/blazor/components/lifecycle.md
Addresses #32209
Thanks @kjkrum! 🚀 ... This only "addresses" part of your issue, and your issue will remain ***open***. The product unit is swamped with .NET 9 work at the moment, so I'm just going to fix up the one line to reflect a more specific statement about implementing the disposal methods ...
* Don't count on when they'll execute. Clarify with the example that Javier and imtrobin were discussing.
* Don't count on the existence of objects when disposing.
WRT the text that you provided in the issue ... I'll ask one of the engineers in a few months to look at that and see if we can place it into the guidance, perhaps with some modifications to their liking.
I'll leave this open for a few hours for you to look and merge it later today.
---
|:--|:--|
| …
> Improve remark on component disposal code

- aspnetcore/fundamentals/servers/httpsys.md
See https://github.com/dotnet/aspnetcore/issues/55334#issuecomment-2085772934
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/d5bffbc8dd162529323f2a57f11676cf66df6cf6/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?branch=pr-en-us-32469) |
> Add min Windows version for IHttpSysRequestTimingFeature

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
- .github/workflows/whats-new.yml
Copied from https://github.com/dotnet/docs/pull/40674
> Use OIDC keys for the OSPO API

- aspnetcore/blazor/forms/binding.md
The referred class name is `ComponentEnums` not `enums`.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/bae10315e901485399e22d11c60788b9b3661481/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-32496) |
> [Blazor] Binding - class name fix

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/host-and-deploy/server.md
Fixes #32493
Thanks @troubleshootdoc! 🚀 ... I'll check back later and remove these remarks when it's supported.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/19ccbd19467f31cc9b9a14e9495a5923405b74b5/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32500) |
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/19ccbd19467f31cc9b9a14e9495a5923405b74b5/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-u …
> Inform readers on support status of stateful reconnect

- aspnetcore/tutorials/min-web-api.md
Fixes #32239
Minor change.
Two items were mentioned in the issue, only one turned out to need a fix which was to remove the id from the PUT data in the body.  This fix was not needed for previous versions, just the current v 8.0.
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/a89bbc5b71292a4baa001b8bdb27af0b10e37d3d/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-32498) |
> Min Web API: Corrected Put data in body

- aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md
Contributes to dotnet/docs#38555
The DiagnosticDescriptors class is internal, so those APIs will never be published in the .NET API browser.
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md](https://github.com/dotnet/AspNetCore.Docs/blob/c70b4540dea72027cae6d0b3f8f71a93b83fc84f/aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md) | [Turn Map methods into request delegates with the ASP.NET Core Request Delegate Generator](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg?branch=pr-en-us-32503) |
> Add publishtrimmed note

- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/signalr/configuration.md
Fixes #32284
Update to withServerTimeout and withKeepAlive for two 8.0 topics where the old JS versions of withServerTimeoutInMilliseconds and withKeepAliveIntervalInMilliseconds exist, which turned out to be the two topics addressed here after seraching the repo.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/a4256485a46a720984dfd4be8467288f5504775c/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-32504) |
| [aspnetcore/signalr/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/a4256485a46a720984dfd4be8467288f5504775c/aspnetcore/signalr/configuration.md) | …
> SignalR:H ubConnectionBuild: Update to withServerTimeout and withKeepAlive

- aspnetcore/signalr/api-design/sample/Samples.cs
Page: https://learn.microsoft.com/en-us/aspnet/core/signalr/api-design?view=aspnetcore-8.0
- A lot of functions were async and returned `Task` without awaiting anything which is 
- Some functions had a 'void' `Task` as return type but actually returned a value
- Some functions returned `string` while that should be `int`
Fixes #32505
> Fix return type issues in "SignalR API design considerations"

- aspnetcore/blazor/globalization-localization.md
- aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md
Fixes #32463
@hishamco ... I performed a NIT 😈 edit pass on the article, mostly just hitting styles that we use today in articles and per the MS Style Manual. Indeed! It is old. I see some versioning for <3.0 here! 😄
I ended up adding a short section on it at the end of each article, and I cross-link to the PU issue. If you think we shouldn't bother with the PU issue cross-link, that's fine with me ... I'll 🔪 it out if you think that's best and just leave the new sections in place.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/e52239c2b242ef75c5803c64e27c4ce60bcc2716/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and …
> Location override using the "Sensors" pane

- aspnetcore/blazor/components/class-libraries.md
Fixes #32453
Thanks @ghhv! 🚀 ... Let's see where this goes.
Dan, Artak ... It was several years ago that I had an RCL working in a Blazor Server app with pages/views and components. This PR updates the guidance on using the **Support pages and views** checkbox for those who do so. We instruct to **deselect** for pages and views but say that if you do that you also need to make changes to support components and explain those changes.
Also note that @ghhv said on the [PU issue](https://github.com/dotnet/aspnetcore/issues/53671#issuecomment-2081461812) that `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>` no-oped in a Blazor WASM app, so I didn't remark on it here.
~Versioning-wise, I'm a bit concerned. It looks like to me based on what I had here from several years ago that the 🧀 moved …
> RCLs for Blazor apps that support pages+views

- aspnetcore/blazor/components/class-libraries.md
Fixes #32513
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/b98ab177b3d79be5dfb579b2e02a6b06863adaf6/aspnetcore/blazor/components/class-libraries.md) | [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?branch=pr-en-us-32514) |
> Remove the guidance on supporting pages/views

- aspnetcore/blazor/hybrid/reuse-razor-components.md
Fixes #32518
cc: @BethMassi - Let me know if this requires a patch. To avoid any problems confusing devs working in 6.0/7.0, I originally had a remark in the sentence that the cross-linked content is for .NET 8 or later with a BWA. However, that approach will kind'a break over the years because I had to peg the destination at the 8.0 article. We don't really want to do that. It's best to just version the whole remark for 8.0 or later to harden this cross-link. ***Future generations of doc authors will thank us!*** 😆
---
|:--|:--|
| [aspnetcore/blazor/hybrid/reuse-razor-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/b047bcc0d99fb278f191992da24246fff6d580d0/aspnetcore/blazor/hybrid/reuse-razor-components.md) | [Reuse Razor components in ASP.NET …
> Add cross-link to new guidance

- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/first-web-api/includes/first-web-api3-7.md
Fixes #32280 
The **New Scaffolded Item** menu was translating to the equivalent of **New Build** in some cases, causing confusion. Moving it to inline no-loc.
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/2233bc0c563a2a4e21c786254ec0da37ea190f9d/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-32517) |
> First Web API: no loc correction for New Scaffolded Item menu

- aspnetcore/signalr/hubs.md
- aspnetcore/signalr/hubs/includes/hubs-2.1.md
- aspnetcore/signalr/hubs/includes/hubs-3-5.md
- aspnetcore/signalr/hubs/includes/hubs-6.md
- aspnetcore/signalr/hubs/includes/hubs-7.md
Fixes #32066 
The intro to the hubs topic emphasizes that a SignalR Hub API enables communication between client and server and does not really give the impression that a hub is also essential to facilitate client-to-client communication. Making that role a little more explicit here in the intro since it was causing some confusion.
---
|:--|:--|
| [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/336495fc1edd438519cee868fa79dc75d71b3e91/aspnetcore/signalr/hubs.md) | [Use hubs in SignalR for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/hubs?branch=pr-en-us-32516) |
> SignalR Hubs: Clarify hub essential part of client-to-client communication

- aspnetcore/blazor/components/data-binding.md
@guardrex 
Feel free to reject this, just trying to propose an alternative intro to the `ValueExpression` aspect.
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/e78ef4c341eef3dbc95299162a861f3045ac6764/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-32535) |
> [Blazor] Data binding - "Expressions" - alternative intro proposal

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
Review of the article created by #32529 
Mostly changes to conform to the style guide. 
On periods in bulleted lists, see https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=56575
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/11675822e527352508d3b1e5f0a355d644179355/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32562) |
> Post-PR review. 

- aspnetcore/tutorials/first-mvc-app/start-mvc.md
- aspnetcore/tutorials/first-mvc-app/start-mvc/includes/start-mvc7.md
Fixes #32039 
It was not clear that the project is not required to be in any particular place expected by .NET and can be put anywhere.  Clarifying it can be put anywhere for VS/VSCode/Mac, version 7 and up.  Not touching the older versions of this tutorial.
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/c03948e47158e0f888fff2318fb60dcb3efa9b81/aspnetcore/tutorials/first-mvc-app/start-mvc.md) | [Get started with ASP.NET Core MVC](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?branch=pr-en-us-32580) |
> First MVC: Clarify project location has no restriction

- .github/workflows/merge-live.yml
Don't run the merge-live workflow in forks.
This should prevent PRs like this one: https://github.com/martincostello/AspNetCore.Docs/pull/1
> Skip workflow in forks

- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/host-and-deploy/server.md
Fixes #32591
I ended up having to rework the entire presentation, and it might take a little more time.
The PR tries to address the problems by ...
* Divorcing the Azure Container Apps guidance into its own section.
* Removing mention of the Azure SignalR Service from Azure Container Apps guidance.
* Placing the session affinity guidance (app-side config) in the new section.
* Cross-link their article for the Azure Container Apps service configuration.
* Rework the Azure SignalR Service guidance for App Service to focus only on its configuration.
* Rework the non-Azure SignalR Service guidance for App Service to focus only on its configuration.
I'll need to take another look at this over the weekend.
Additional notes ...
* I have a separate tracking item to adopt "session affinity" as the …
> Azure Container Apps updates

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/fix-for-503s.md
Fixes #32596
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/055edaa0e3406a4e5e9639470984e645a09714e7/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32598) |
> What's new: Fix for 503's during app recycle in IIS.

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/hybrid-cache.md
Fixes #32370 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa54051e4dc7199933e0cbd84a4cb90b77eda1d4/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32593) |
> HybridCache in What's new doc

- aspnetcore/performance/caching/hybrid.md
- aspnetcore/performance/caching/hybrid/includes/overview.md
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/Program.cs
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/appsettings.Development.json
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/appsettings.json
- aspnetcore/performance/caching/overview.md
- aspnetcore/performance/caching/overview/includes/overview6.md
- aspnetcore/performance/caching/overview/includes/overview7-8.md
- aspnetcore/toc.yml
Fixes #32371 
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/724dfcab9698fb90f3854297b9ae5ec53c04bab1/aspnetcore/performance/caching/hybrid.md) | [aspnetcore/performance/caching/hybrid](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-32605) |
| [aspnetcore/performance/caching/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/724dfcab9698fb90f3854297b9ae5ec53c04bab1/aspnetcore/performance/caching/overview.md) | [Overview of caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/overview?branch=pr-en-us-32605) |
> Document .NET 9 new feature - HybridCache

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Addresses #32361
There will be a separate PR for the BWA+OIDC article+sample later, as I think we'll be implementing this new tech for that sample. I've made a separate tracking entry for it on the Blazor .NET 9 tracking issue.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/d293d296a5a5ec8f08a9d6f8195f6c85a9b8b94f/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32599) |
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/d293d296a5a5ec8f08a9d6f8195f6c85a9b8b94f/aspnetcore/blazor/security/server/index.md) | …
> Static SSR pages in a globally-interactive app

- aspnetcore/blazor/security/server/index.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/32599#discussion_r1607416286
cc: @danroth27 ... Applying your suggestion here. I was OOF when your review came in. BTW, "fine control of the render mode" merely referred to the name of the section before that other PR was merged. It has a better section name now, and your suggestion is spot on 👍.
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/af081a8b4ad90d4839a85ff8b439fa0c823df859/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-32613) |
> Update unauthorized content display while prerendering section

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
- aspnetcore/tutorials/getting-started-with-swashbuckle.md
Bump Swashbuckle.AspNetCore version to the latest release.
We shipped a [new release today](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.6.2) that fixed a number of user-reported issues.
/cc @captainsafia
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/eb2f8e6dad319b537bfa41af14fd859208e022ed/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32622) |
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/eb2f8e6dad319b537bfa41af14fd8592 …
> Bump Swashbuckle versions

- aspnetcore/host-and-deploy/iis/advanced.md
Fixes #32600 
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e390133fe36aa40709bf265d758174d76147cc5/aspnetcore/host-and-deploy/iis/advanced.md) | [Advanced configuration of the ASP.NET Core Module and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-32637) |
> Document ShutdownDelay

- aspnetcore/performance/response-compression.md
NGINX Docs has its own subdomain.
---
|:--|:--|
| [aspnetcore/performance/response-compression.md](https://github.com/dotnet/AspNetCore.Docs/blob/af3f7c8e07c0b785eb43e50ac4f0c223033d00d3/aspnetcore/performance/response-compression.md) | [Response compression in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/response-compression?branch=pr-en-us-32673) |
> Fix broken nginx link in response-compression.md

- aspnetcore/security/enforcing-ssl.md
Fixes #32670
@tmds please review. I meant to put this as the first linux dev H3
I moved it right after [Trust HTTPS certificate on Linux](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&tabs=visual-studio%2Clinux-ubuntu#trust-https-certificate-on-linux)
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/16dbad0d6ebd8397f3b1429d55a599f98052abac/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-32669) |
> move up  linux-dev-certs

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
Closes https://github.com/dotnet/AspNetCore.Docs/issues/32687.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/2ff73e7d595267af86eaa788ab03cd35ae4dad62/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32688) |
> Fix ReDoc link in OpenAPI docs

- aspnetcore/grpc/health-checks.md
Fixes: #31828
[Internal Preview to edited section here](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-8.0&branch=pr-en-us-32675#call-grpc-health-checks-service)
Added configure the client factory steps for the Health Checks Service section.
---
|:--|:--|
| [aspnetcore/grpc/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/88dc5743c02971b9e1dca4999e77823c3c426aa5/aspnetcore/grpc/health-checks.md) | [gRPC health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?branch=pr-en-us-32675) |
> gRPC Health Checks: Add client factory example

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
From [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/32634#issuecomment-2137681858)
> @Rick-Anderson @tdykstra This PR removed the install instructions from the `Microsoft.AspNetCore.OpenApi` package from the documentation. It's an important part of the setup. Can we revert this change?
@captainsafia  we don't add these instructions to anything but onboarding tutorials. 
Per the style guide, we don't have two different approaches to install the package. As it was, it wasn't clear you had to chose one approach.
I'd prefer to remove these instructions and just have:
`Install the `Microsoft.AspNetCore.OpenApi` package.`
But we can keep these if you like.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/do …
> Update install package instructions.

- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/fundamentals/signalr.md
Fixes #32696
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/b7962d7e2576257dc024bd44052bf2a6c62adc4f/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-32702) |
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/b7962d7e2576257dc024bd44052bf2a6c62adc4f/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32702) |
> Maximum parallel invocations per client remark

- aspnetcore/fundamentals/minimal-apis/test-min-api.md
- aspnetcore/includes/integrationTests.md
Fixes #32158 
This is not the right article for an introduction to unit testing and mocking. It assumes you have basic knowledge about unit testing because it provides a link for those who don't, but the article it links to doesn't talk about mocking. We don't have on the site a better unit testing intro that does talk about mocking, but I did the next best thing, adding a link to the unit testing best practices section on mock and fake terminology. As far as MockDb in particular is concerned, it's a class that's defined in the project, so anyone who opens the project will see what it is.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/test-min-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/7740b0c97c388d1986552429d7af1559b660d228/aspnetcore/fundam …
> Add a link

- aspnetcore/blazor/security/server/index.md
Fixes #32797
Addresses #32692
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/45d43bd6deceb1767d6dfe1a1aaa726d2709fcff/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-32799) |
> Simplified auth state serialization for BWAs

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Fixes #32792
Addresses #32692
Beth ... This should work ... *I think* 🤔🤞🍀. It should work ***IF*** the new project template *exactly matches* what we have in the article in terms of namespace suffixes, file locations and file names, code logic, etc. I still haven't created an app from the template (*YET*) just because I'm working full speed at the moment 🏃‍♂️🏃‍♂️🏃‍♂️ just to get everything covered in time for release tomorrow. I will create a local test app to compare; but if you can tell me about any deltas that exist between the article/sample app and the template, I hope I can work up the changes for this PR and put off creating a local project at the moment.
Here's what this PR is doing to the current coverage ...
* Version a new section to describe the .NET MAUI …
> New .NET MAUI Blazor Hybrid template

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #32789
Addresses #32692
Mackinnon, ~I'm blocked at the moment on working on the *What's New* side of this until another PR merges, but I'll have the *What's New* part for this updated (some coverage was placed that I'll be touching up) by EOD on a separate PR.~ 
**UPDATE: Not blocked any longer on What's New. I'll take care of it after the four reference article PRs are merged.**
WRT this coverage: It seems like we'd call the default logic "a computed backoff strategy" instead of "an exponential backoff strategy." However, your custom example is exponential, so I retain that language for the example.
I was curious about the default logic, and I think devs will be curious, too. The link goes here ...
https://github.com/search?q=repo%3Adotnet%2Faspnetcore%20computeDefa …
> Blazor Server reconnection coverage

- aspnetcore/blazor/components/render-modes.md
Fixes #32780
Addresses #32692
I hope I'm not making up my own 🦖 Blazor framework ... ***again!*** 🙈 
If either or both of my examples aren't best, give me your code for better examples. I figure we place two examples here, one for interactivity and one for assigned render mode.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/dce7ed7451bb781be1154c643386b92b4d83af1d/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32794) |
> Detect the current render mode at runtime

- aspnetcore/blazor/host-and-deploy/webassembly.md
Addresses #32308 
I'll be working on getting CentOS remarks out of the article soon ... perhaps even ***today***.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/1abb93c1e8cf07e15fb2eae1dff8013c8f99ee65/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-32816) |
> Fix spacing in Apache configuration example

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #32308
cc: @Rick-Anderson ... This does it for CentOS coverage. After this goes in, there are no references to CentOS on the entire repo, Blazor included.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/662cfde6c82313bb51f2c4fe6ca64e9b58ab6c85/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-32817) |
> Update Apache coverage (drop CentOS mentions)

- aspnetcore/blazor/components/prerendering-and-integration.md
- aspnetcore/blazor/fundamentals/signalr.md
Fixes #32818
---
|:--|:--|
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/438a13653eb785360cb425cdc99f6ba4832a5dd1/aspnetcore/blazor/components/prerendering-and-integration.md) | [Prerender and integrate ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?branch=pr-en-us-32820) |
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/438a13653eb785360cb425cdc99f6ba4832a5dd1/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32820) |
> Use 'reconnection UI' for all references

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Per offline discussion with Beth, a patch to the language to make it clear that the .NET CLI must be used to create an app with per-page/component interactivity location.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4c404480bdbb7504f35cc70f760c28f593bdc7b/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [Build a .NET MAUI Blazor Hybrid app with a Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-32821) |
> Clarify per-page/component scenario

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Per offline discussion with Beth, a patch to the language that removes the option for setting the location at all with the new template.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/3039ef2038052cb75d5473bfd2be8e351c209247/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [Build a .NET MAUI Blazor Hybrid app with a Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-32823) |
> Update .NET MAUI BH BWA tutorial

- aspnetcore/mobile/native-mobile-backend.md
I found a handful to fix the other way.
cc: @Rick-Anderson ... Tom indicated that they get set into uppercase but should be lowercase in markdown. It threw me off. We have these tho that really are incorrect.
---
|:--|:--|
| [aspnetcore/mobile/native-mobile-backend.md](https://github.com/dotnet/AspNetCore.Docs/blob/bd378097f6ab58afe148b320d6373725812e9fe1/aspnetcore/mobile/native-mobile-backend.md) | [Create backend services for native mobile apps with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?branch=pr-en-us-32849) |
> Lowercase the code name

- aspnetcore/blazor/includes/js-interop/js-collocation.md
- aspnetcore/blazor/javascript-interoperability/import-export-interop.md
Fixes #32618
Marek ... The article that covers JS location ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?view=aspnetcore-8.0
... is meant to cover all of the location scenarios, and it looks like it's just this ***one thing*** that isn't supported: Import-Export interop with collocated JS in an RCL.
If that's a correct interpretation, then I think a section should be added to the Import-Export article that just calls out that the collocation feature isn't supported, leaving the JS location article to continue to serve its purpose for both JS interop APIs. I'm adding that section here, and I'm cross-linking it from the JS location article where it talks about collocated JS from an RCL. 
Also, it seemed like a little advice can …
> Import-Export interop: collocated JS with RCL

- aspnetcore/docfx.json
Fixes #32710
This will yield correct issue management for these three Blazor articles. This system works on a last-one-wins strategy, so adding them at the end will give them the correct subservice.
> Specify three Blazor subservice articles

- aspnetcore/diagnostics/asp0018.md
Updating the documentation for error ASP0018 "" to add a type (string) to the example. Afaik the default type is HttpContext but I think the most likely use case for a route parameter in the path is a string, especially given the name is `id`. Not sure if this is a best practice or not. Feel free to reject!
---
|:--|:--|
| [aspnetcore/diagnostics/asp0018.md](https://github.com/dotnet/AspNetCore.Docs/blob/163bd51f54d17668f94ab0e164129ef989dcefcb/aspnetcore/diagnostics/asp0018.md) | [ASP0018: Unused route parameter](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018?branch=pr-en-us-32906) |
> Add type to code example for route param.

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Addresses #32802
Required at this time for two reasons:
* There's a namespace change to cover.
* The repo needs to drop the link to a file that will disappear when the sample project name changes later. If the link is left here, it has the capacity to break unrelated PRs when they're built.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/29959e7cfbaa120c818e76b8385b60ffc6db99c3/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [Build a .NET MAUI Blazor Hybrid app with a Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-32908) |
> Place code for sample cross-link in MAUI project

- aspnetcore/blazor/forms/index.md
Fixes #32733
Adding a section for ...
* General coverage on this subject.
* Inbound links from scaffolded `Create` and `Edit` component markup using the `blazor` generator. Today, these components point to the RP coverage ...
```razor
// To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
```
... which isn't much help given the landing section is https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-8.0#update-the-create-page with API and an approach that isn't available in a Razor component scenario.
Cross-refs:
* https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Create.tt#L66
* https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Blazor/Edit.tt#L92
I'll signal the …
> Mitigate overposting attacks

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32551
Mackinnion ... This PR arose because a dev, @Takhoffman, was using the BWA+OIDC sample app (it's global Auto) and hit a 💥 ***404*** trying to drop in a per-component-style interactive SSR component into the server project's `Components/Pages` folder. I told him that with that type of project ... global Auto ... that actually the component is placed (counter-intuitatively) into the `Pages` folder of the `.Client` project, which I think Steve told me about a while back IIRC 🤔.
Please confirm if that's correct. If so, see if the NOTE that I'm adding to the interactive SSR section of the *Render Modes* article and the new section in the BWA+OIDC article is explaining the scenario, the placement, and ***the reason*** for the 404 is all correct. I think the reason is due to the …
> Interactive SSR RCs in global WASM/Auto projects

- aspnetcore/blazor/debug.md
- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/security/includes/run-the-app.md
- aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
- aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-entra-id.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #32845
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/51bb4e9140d3a1f9e338878e327aa196004e252e/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-32909) |
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/51bb4e9140d3a1f9e338878e327aa196004e252e/aspnetcore/blazor/host-and-deploy/index.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-32909) |
| [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/51bb4e9140d3a1f9e338878e327aa196004e2 …
> Blazor CLI commands moving to `dotnet watch`

- aspnetcore/client-side/dotnet-interop.md
Fixes #32660
Marek ... ***UPDATE***: Making progress ...
* Version-specific language updates. Version new coverage for .NET 8+.
* Change from the `Microsoft.NET.Sdk` SDK to the `Microsoft.NET.Sdk.WebAssembly` SDK.
* Update code and language for .NET 8+.
* Update guidance for workload and template installation.  
See my latest comments on three items of concern :point_down:.
---
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/fca6875016950ab06398315fe2d1ec1f4a9e8ccf/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-32882) |
> .NET JS interop article updates

- aspnetcore/blazor/components/render-modes.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/dfc187a6b5c0341f5b5a8f7beff641ea29d78f76/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-33008) |
> [Blazor] Render-modes.md - null typography

- aspnetcore/blazor/components/class-libraries.md
- aspnetcore/blazor/components/css-isolation.md
- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/blazor/host-and-deploy/webassembly-caching/index.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
- aspnetcore/blazor/security/includes/troubleshoot-server.md
- aspnetcore/blazor/security/includes/troubleshoot-wasm.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #33005
Addresses #32960
~I still need to go through the full doc set and add/version the `href`s for static assets. However, should I just wait until the tilde-slash (`~/`) feature is implemented for the compiler before doing that? I think there might be like ... mmmmm 🤔 ... 50 or so spots to update. I'd like to wait and hit them on one pass if the `~/` feature will be implemented soon.~
The compiler feature won't make .NET 9. I'm versioning `href`s on this PR.
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/0ef32531574494afafd6022df8f489e8ce96cc7c/aspnetcore/blazor/components/class-libraries.md) | …
> [HOLD, Pre6] Blazor static asset delivery and fingerprinting

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Fixes #33013
Mackinnon ... Here are your original remarks :point_right: https://github.com/dotnet/aspnetcore/issues/53376#issuecomment-2215262524.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/675b5315d3c5ca566a4305f9d3c68cb57e68248b/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-33036) |
> Improve DotNetStreamReference disposal remarks

- aspnetcore/fundamentals/static-files/samples/9.x/StaticFilesSample/Program.cs
- aspnetcore/fundamentals/static-files/samples/9.x/WebRoot/Program.cs
> update to better snippet syntax

- aspnetcore/fundamentals/minimal-apis/includes/openapi9.md
This PR removes an extra closing parenthesis to fix a syntax error.
> Fix syntax error in openapi9.md

- aspnetcore/blazor/globalization-localization.md
Fixes #33077
Thanks @voroninp! 🚀 ... I'll open a new issue later to further work on this when they resolve the PU issue.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/0b64acd9f2488b73cbf9a02f490a091505fa213e/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-33100) |
> Add PU cross-link to note on loc resource loading

- aspnetcore/grpc/health-checks.md
Like https://github.com/dotnet/AspNetCore.Docs/pull/33092 but for health checks which is registered in a similar way.
Expert required to fix up the busted API links.
---
|:--|:--|
| [aspnetcore/grpc/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/a10c7a372181aa44fef45b7eb7107dc93784d6db/aspnetcore/grpc/health-checks.md) | [gRPC health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?branch=pr-en-us-33093) |
> gRPC health checks security

- aspnetcore/blazor/fundamentals/handle-errors.md
Fixes  #33091
Thanks @TimMurphy! 🚀 ... This PR has the section clarify that the alternative approach is only for Blazor WASM, Blazor Server, and BWAs that adopt a global interactive render mode. It includes an explanation on why that's the case with BWAs. I went with "`ProcessError`" for the component name to avoid a conflict with the `Error` component in the BWA template. The component's demonstration method is now "`LogError`." I also made some additional description improvements, and I resurfaced the Blazor Server coverage because we're still supporting Blazor Server ... it's just not a project template any longer.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/c22526e5dd811f5e8303fe895d5eb6e62 …
> Error handling section improvements

- aspnetcore/blazor/globalization-localization.md
Fixes #33077
@voroninp ... I performed some additional research on this, and the core problem is just that Blazor WebAssembly apps don't respect the current UI culture. I'm updating the note to state that. There's no need to change the code because the current UI culture setting just no-ops. I also update the title of the PU issue that I opened yesterday. I also added a repro project for them to look at. They're going to take a look at this situation for .NET 10.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/8157a0a509ce962f74bbe893b60c171fed984cf9/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and …
> Update note on localization resource loading

- aspnetcore/blazor/globalization-localization.md
Fixes #33078
Thanks @voroninp! 🚀 ... I'm not aware of how `IStringLocalizer` comes into the pattern, so I didn't remark on ...
> It also means that combining the usage of both `IStringLocalizer` and `IStringLocalizer<T>` when resources are placed differently won't work.
The section's approach only uses `IStringLocalizer<T>`. Do you want to suggest a line of text for the note on that? It can't state "combined usage of." It has to say which one isn't supported in this scenario, and it might add a remark on why.
cc: @hishamco ... Do you want to review?
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/31a2ef5da1a7cf4076e18953aca0b2f180a17a8a/aspnetcore/blazor/globalization-localization.md) | [ASP.NET …
> Clarify setting the resource path value

- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/fundamentals/static-files.md
- aspnetcore/fundamentals/static-files/includes/static-files8.md
Fixes #32891
Thanks @ventureaaron! 🚀 ... I tested the other approach earlier in the main doc set section with the physical file provider. That one worked ok in a BWA ... and both of them work in a Blazor Server app at 8.0. It looks like it was just the composite file provider that doesn't work in a BWA, so that's the focus of the PR.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/4407f6a25f3533349bcffcdbcb518efe2bf4544d/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33118) |
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/b …
> Add composite file provider guidance

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/lifecycle.md
Hello
I found several spelling issues in your docs.
Hope it helps.
Br, Elias.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa114b219a3f11002680c5c2a42df26faadb2ad1/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33133) |
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa114b219a3f11002680c5c2a42df26faadb2ad1/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-33133) |
| …
> Fix spelling issues

- aspnetcore/test/http-files.md
Mention that you don't get dynamic endpoint discovery until you have 17.11
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/4dbf150d5a3ebfec7d5d32cf3b06f76071847461/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-33138) |
> Dynamic endpoint discovery is in VS 17.11

- aspnetcore/security/authentication/add-user-data/samples/6.x/SampleApp/Areas/Identity/Pages/Account/Register.cshtml
When using the `form-floating` to enable floating labels with Bootstrap’s textual form fields, the `<input>` must come first, otherwise it might cause the labels overflow issue. Refer to this document: https://getbootstrap.com/docs/5.0/forms/floating-labels/
Fixes #33153
> Update the floating labels in Register.cshtml 

- aspnetcore/fundamentals/static-files.md
This link somehow got past the build and was merged, which I think is breaking the live merge ...
https://buildapi.docs.microsoft.com/Output/PullRequest/332f35cd-658d-4914-0f85-907e40ee89f0/202407250151226132-33050/BuildReport?accessString=a36de54572e65899527793f95eab7201f190f021e15d8c7388d7eb32ce2d027f
Trying to fix it here, but the build system isn't cooperating at the moment.
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/7148de58da5771b723827db8d896532f2645803f/aspnetcore/fundamentals/static-files.md) | [Static files in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-33198) |
> Fix bad link

- aspnetcore/tutorials/min-web-api.md
- aspnetcore/tutorials/min-web-api/includes/min-web-api6-7.md
- aspnetcore/tutorials/min-web-api/includes/min-web-api8.md
- aspnetcore/tutorials/min-web-api/samples/7.x/todo_SwaggerVersion/Program.cs
- aspnetcore/tutorials/min-web-api/samples/9.x/todoDTO_SwaggerVersion/Program.cs
- aspnetcore/tutorials/min-web-api/samples/9.x/todoGroup_SwaggerVersion/Program.cs
- aspnetcore/tutorials/min-web-api/samples/9.x/todoTypedResults_SwaggerVersion/Program.cs
- aspnetcore/tutorials/min-web-api/samples/9.x/todo_SwaggerVersion/Program.cs
fixes #32769
For VS Code tab version:
- Removed unneeded using statement for Nswag from code samples and removed instructions from topic.
- Updated code line highlights to match code update.
- Tested code by instructions for versions 7-9.
- Did side by side comparison of build version in browser to verify code, text and code highlighting correct.
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/698fc0d7746e752c1458274bacf3ca814a5661c7/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-33200) |
> Min Web API: Remove using statement update content & code

- aspnetcore/blazor/components/integration.md
Fixes #33216
Thanks @Rod-at-DOH! 🚀 ... 
* I've re-organized the sections. The one-off section that only applies to non-routable component integration with the Component Tag Helper is now first, and it's clarified in the section and in the lead-in remarks that it only applies to the narrow case it covers.
* I moved the section that included layout/styles to the full Blazor integration section (it's an H3 now in that H2 section), and I modified it to show how to set a layout and where to get Blazor project template resources from the product unit repo.
* I made remarks on the dev possibly having to add an `@using` statement to the `_Imports` file and to not sweat setting up stylesheet references for CSS isolation stylesheets.
---
|:--|:--|
| …
> Update Blazor integration guidance

- aspnetcore/includes/trustCertVSC.md
- aspnetcore/security/docker-compose-https.md
- aspnetcore/security/docker-https.md
- aspnetcore/security/enforcing-ssl.md
The dev experience should mostly match other platforms now, but I've added a section with caveats.
Firefox no longer seems to need special handling on Windows or macOS.  I strongly suspect that section could also be removed in the pre-6.0 doc, but I haven't had a chance to confirm.
Context: https://github.com/dotnet/aspnetcore/pull/56582
---
|:--|:--|
| [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8c64bc0717f68cdaec278484e8e11e180bbc1ea/aspnetcore/security/docker-compose-https.md) | [Hosting ASP.NET Core images with Docker Compose over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?branch=pr-en-us-33221) |
| [aspnetcore/security/docker-https.md](https://github.com/dotnet/ …
> Update Linux dev cert trust instructions

- aspnetcore/web-api/handle-errors.md
Change link section from "#pds7" to "#problem-details"
---
|:--|:--|
| [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/ff33a306a63df1997906c4d4fdea4bb83a3daac3/aspnetcore/web-api/handle-errors.md) | [Handle errors in ASP.NET Core controller-based web APIs](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?branch=pr-en-us-33213) |
> Fix Problem Details section link

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
Fixes #32512
Thanks @travaille-dev! 🎸 ...
* I'm going with two sections for this, one focused on roles for general OIDC providers and one for ME-ID.
* The ME-ID section includes guidance for Azure security/distribution groups (`groups` claims) and ME-ID built-in administrator roles (`wids` claims), which devs can then base authz policies on. A lot of devs want to know how to use these Azure/ME-ID features, but it can be difficult to track down the guidance in the Azure/ME-ID docs. *This should make it a snap!* ✨
* I also made an update to the sample apps to assign `roles` instead of `role` to the role claim type. I call out in the article that it's done for ME-ID and to consult their IdP docs on it.
---
|:--|:--|
| …
> Add roles/groups coverage to the BWA+OIDC article

- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/validation.md
Fixes #32639
* Calling out that `[Remote]` isn't supported.
* Calling out that `IValidatableObject` is supported but that it only runs on form submission and only when all other validation clears.
* A few additional minor updates.
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa5d9089864e2b460c0e0a7966485e3509577caa/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-33225) |
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa5d9089864e2b460c0e0a7966485e3509577caa/aspnetcore/blazor/forms/validation.md) | [ASP.NET Core Blazor forms …
> Enhance Blazor forms validation coverage

- aspnetcore/mvc/views/working-with-forms/sample/final/ViewModels/CountryViewModel.cs
Removed double space in `SelectListItem` object initialization.
Before:
```cs
new SelectListItem { Value = "US", Text = "USA"  }, // two spaces after "USA"
```
After:
```cs
new SelectListItem { Value = "US", Text = "USA" }, // one space after "USA"
```
> Removed double space in object initialization

- aspnetcore/fundamentals/portable-object-localization.md
A user was asking what was the syntax when additional arguments were provided. The fact that the `{0}` placeholder always represents the count is not obvious.
---
|:--|:--|
| [aspnetcore/fundamentals/portable-object-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/ea907291364aa6aff1fe5a9d98329176437490db/aspnetcore/fundamentals/portable-object-localization.md) | [Configure portable object localization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?branch=pr-en-us-33280) |
> Add plural localization examples for additional arguments

- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #30311
Thanks @macias! 🚀 ... I finally made it to the P3 priority issues after a rather grueling 8.0 release cycle. It's taken almost a ***year*** to reach this batch of issues, but I'm finally here 😅. I'm focusing this on the main remark that Javier made about your ask: fields of type function aren't supported. I see that you may have had a followup problem that wasn't resolved on the product unit issue, but I think that was probably related to some other aspect of your code (a different concept).
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/8fe20d7199456aef441b589751db765c020dfa38/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript …
> Class field of type function not supported

- aspnetcore/fundamentals/openapi/samples/9.x/ProducesProblem/Program.cs
- aspnetcore/release-notes/aspnetcore-9/includes/prob_validation.md
contributes to #33309
@captainsafia, this PR shows only the changes I made to [Problem and ValidationProblem result types support construction with IEnumerable<KeyValuePair<string, object?>> values](https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274516260):
* Copy/pasted [Problem and ValidationProblem result types support construction with IEnumerable<KeyValuePair<string, object?>> values](https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274516260) to an include file and project unchanged
* Merged the copy/paste PR so you can see all the changes I made in this PR. Copy/paste PR is #33329
> WN9 ProblemValidation on route groups /a

- aspnetcore/security/authentication/identity-enable-qrcodes.md
Fixes https://github.com/dotnet/aspnetcore/issues/14423
---
|:--|:--|
| [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/dotnet/AspNetCore.Docs/blob/de3a3313ce2801aee3d1303a11c621c627836915/aspnetcore/security/authentication/identity-enable-qrcodes.md) | [Enable QR code generation for TOTP authenticator apps in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?branch=pr-en-us-33373) |
> Document that TOTP codes can be reused before it expires

- aspnetcore/blazor/file-uploads.md
Fixes #33272
Notes ...
* The versioning assumes that the problems associated with multiple file uploads (and avoiding writing to a `MemoryStream`/byte array) and Autofac will be resolved for >=9.0.
* The <9.0 text won't dissuade writing to a `MemoryStream`/byte array any longer. However, I'm leaving the bits about how it can degrade performance and present a possible security risk.
* 🤔 I think the "security risk" that we were generically mentioning before is DoS, so I'm stating that explicitly now on this PR. Let me know if that's an incorrect guess. 👂 
* The sample app changes were made in the Blazor samples repo for Blazor Server and Blazor Web App samples. Here's an example :point_right: https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorSample_BlazorWebApp/Components/Pages/Fi …
> File uploads (writing to memory/Autofac content)

- aspnetcore/tutorials/min-web-api.md
- aspnetcore/tutorials/min-web-api/includes/min-web-api6-7.md
- aspnetcore/tutorials/min-web-api/includes/min-web-api8.md
The correct status code for successful POST requests is 201, not 200. Even the accompanying image shows 201 as opposed to 200. The presence of a location header is confirmation that the response code is 201 as 200 does not return that header.
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/d5a7af6b1e2d67f7363e586e89635d8a77f6c798/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-33394) |
> Replace HTTP 200 status code with 201 for POST

- aspnetcore/client-side/dotnet-interop/index.md
---
|:--|:--|
| [aspnetcore/client-side/dotnet-interop/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c59c5c18abb6331269f0bc99d05fd594773cae17/aspnetcore/client-side/dotnet-interop/index.md) | [JavaScript `[JSImport]`/`[JSExport]` interop in .NET WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop/index?branch=pr-en-us-33413) |
> Escape quotes in no-loc text

- aspnetcore/release-notes/aspnetcore-9/includes/websockets-keep-alive-timeout
Contributes to #33442
Moving to include and keeping the content as it was submitted in the Issue discussion so following PR updates diff are easy to discern.
In the next step, in a new PR this include will be edited, and code moved to a buildable project and then linked back in.
> What's New: Keep-Alive Timeout for WebWSockets: Draft to include

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #51698
Thanks @shrayasr! 🚀 ... and sorry that it took this long to reach the issue. .NET 8 was the largest Blazor release and set of doc updates that we've ever had. Fortunately, I've just about caught up ⛰️⛏️😅. 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/54bb86823d0531d563d9b20cd0acf7ce16023fa2/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-33467) |
> Cover workaround for AmbiguousMatchException

- aspnetcore/includes/environmentVarableColon.md
Fixes #33434 
Removed what appeared to be an unintended line break/bullet, along with a sentence fragment.
> Update environmentVarableColon.md - correct line break / fragment

- aspnetcore/tutorials/getting-started-with-swashbuckle.md
- aspnetcore/tutorials/getting-started-with-swashbuckle/includes/getting-started-with-swashbuckle8.md
Fixes #32864
Added a missing highlight in the code.
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/c65e8b63494ce0f973cb486a39cadc5e8dc2c10c/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?branch=pr-en-us-33464) |
> UUF: Get started with Swashbuckle: Add missing code highlight

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/websockets-keep-alive-timeout.md
- aspnetcore/release-notes/aspnetcore-9/samples/WebSocketsKeepAliveTimeoutExample/Controllers/WebSocketController.cs
- aspnetcore/release-notes/aspnetcore-9/samples/WebSocketsKeepAliveTimeoutExample/Program.cs
- aspnetcore/release-notes/aspnetcore-9/samples/WebSocketsKeepAliveTimeoutExample/WebSocketsSample.csproj
- aspnetcore/release-notes/aspnetcore-9/samples/WebSocketsKeepAliveTimeoutExample/wwwroot/index.html
Fixes #33462
Edit from original provided in discussion from Brennan for issue: https://github.com/dotnet/AspNetCore.Docs/issues/33442
Moved inline code samples to a project, using a bare bones of our original WebSockets sample already available.
The changes to aspnetcore/release-notes/aspnetcore-9.0.md are just so we can see what the include looks like in a build. 
That will be removed before merge.  We will add all the includes to the main document closer to publishing.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/489a4bb31f8005e1a611372827c3da8924ef1fa2/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/a …
> WN: WebSocket Keep-Alive Timeout: Edit & code moved to project

- aspnetcore/blazor/forms/binding.md
I'm proposing alternative names for the new custom input components.
@guardrex, feel free to reject this PR, if you find the original names more appropriate.
(`EngineeringApprovalInput1.razor` and `EngineeringApprovalInput2.razor` also works for me.)
(I will also propose a small change in text in separate PR. Give me few minutes.)
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/c681a57f4fad946dd79987a978b82a4245984df2/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-33494) |
> [Blazor] Binding - Custom input components - naming of demo components

- aspnetcore/blazor/forms/binding.md
I believe we should include a recommendation to use `InputBase<T>` as a basic approach to implement custom inputs.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ea7b53a7b1e9f0ec09bc5c6c59a9ea95a932785/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-33495) |
> [Blazor] Forms - Binding - Custom input components - InputBase recommendation

- aspnetcore/security/authentication/social/index.md
- aspnetcore/security/authentication/social/other-logins.md
- aspnetcore/security/authentication/social/twitter-logins.md
Fixes #33505
The OpenIddict documentation website now has a specific page for the `OpenIddict.Client.WebIntegration` package that lists the supported services and explains the differences between the OpenIddict providers and the older aspnet-contrib providers: https://documentation.openiddict.com/integrations/web-providers.
Note: the `.html` extension was deliberately removed as we now use "clean URLs" 😃  
---
|:--|:--|
| [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ee3a6bf6a586ca5acbb5b9d15e4867e5cde3cb87/aspnetcore/security/authentication/social/index.md) | [Facebook, Google, and external provider authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/s …
> Update the OpenIddict links to point to a more specific documentation page

- aspnetcore/security/authentication/certauth.md
Fixes #33525 
---
|:--|:--|
| [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/560af49ef98601dbaad68ff170912860183190fb/aspnetcore/security/authentication/certauth.md) | [Configure certificate authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?branch=pr-en-us-33526) |
> Update certauth.md to fix links to instructions for adding a root cert

- aspnetcore/blazor/fundamentals/static-files.md
Not sure how this item was meant, but minification is not included in Static Assets Middleware.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/46c8d7a53d421e70e887c2ab8dc4b4be6eefef74/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33528) |
> [Blazor] static-files - no minification included

- aspnetcore/tutorials/getting-started-with-swashbuckle.md
- aspnetcore/tutorials/getting-started-with-swashbuckle/includes/getting-started-with-swashbuckle8.md
Fixes #33296
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/e32115c991e03c61341bacc7ae8d470c3921a623/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?branch=pr-en-us-33545) |
> swashbuckle.aspnetcore being removed in dotnet 9

- aspnetcore/security/authentication/identity-api-authorization.md
---
|:--|:--|
| [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/e364c825a738b0458e6c45c4eae0a41d613d1000/aspnetcore/security/authentication/identity-api-authorization.md) | [How to use Identity to secure a Web API backend for SPAs](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?branch=pr-en-us-32994) |
> Provide stronger guidance for using identity cookies over tokens for security

- aspnetcore/security/authentication/certauth.md
"Per host" meaning "per SNI host name" can be inferred from the context, but it took me a second to figure out what was meant by "per host" when I was reading it today, so I figured it makes sense to clarify this.
---
|:--|:--|
| [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/40f0ddda95b5adc38cac7a1ad20ccd702df9f690/aspnetcore/security/authentication/certauth.md) | [Configure certificate authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?branch=pr-en-us-33561) |
> Clarify that "per host" means "per SNI host name" in certauth.md

- aspnetcore/blazor/forms/input-components.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #33556
Mackinnon ...
* This covers both the *9.0 What's New* article and the new section in the *Input Components* article.
* Sorry that I replaced your example. I'm trying to go with Star Trek-themed forms throughout the *Forms* node.
* Is there anything else that we need to tell devs in the article section?
---
|:--|:--|
| [aspnetcore/blazor/forms/input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/378ef5264bf06c9a358fce7da5917206c62d0375/aspnetcore/blazor/forms/input-components.md) | [ASP.NET Core Blazor input components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/input-components?branch=pr-en-us-33557) |
> Override InputNumber type attribute

- aspnetcore/security/enforcing-ssl.md
- aspnetcore/security/enforcing-ssl/includes/enforcing-ssl6-8.md
Fixes #33565 
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/165db7a59562d33d855ec6d05d765798eb5e78f7/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-33566) |
> Moniker prep for .NET 9 content in enforcing-ssl.md

- aspnetcore/includes/trustCertVSC.md
- aspnetcore/security/docker-compose-https.md
- aspnetcore/security/docker-https.md
- aspnetcore/security/enforcing-ssl.md
- aspnetcore/security/enforcing-ssl/includes/enforcing-ssl6-8.md
This PR reinstates #33221, which was reverted because it was merged too soon. It adds some text recognizing that the features documented in #33221 are going to be backported to 8.0.
The commits at present are as follows:
* [redo33221](https://github.com/dotnet/AspNetCore.Docs/commit/771ec41c110f4beb6ed9db2a853e1354ff7512d5) This reapplies the original PR by @amcasey which was reverted because it was merged too soon. This affects 5 files instead of the original 4 because the original made a change to the <.NET 6 version, which is now in an include file.
* [adjust ms.date](https://github.com/dotnet/AspNetCore.Docs/commit/53e901730971fdc1ea7fcf90ef541b57b96e67d8) Ignore, only affects ms.date.
* [Markdownlint](https://github.com/dotnet/AspNetCore.Docs/commit/e9a49c51965ae350a41cdd743ad776256ac …
> Reinstate #33221

- aspnetcore/security/index.md
Addresses #33555
Tom ...
Per DR's blessing offline, we need a link here that surfaces the Blazor *Security and Identity* overview and node. If you're ok with the language, this is all we probably need.
This PR merely "addresses" the issue because I'll be analyzing the main doc set next week for other spots where we need to mention something this effect, especially in the articles that appear before the Blazor node for those readers going right down the ToC to learn ASP.NET Core.
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/be632219b377c20077930bd1e0c583d7a586764b/aspnetcore/security/index.md) | [ASP.NET Core security topics](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-33558) …
> Cross-link Blazor's security node

- aspnetcore/blazor/fundamentals/static-files.md
Fixes #33571
Thanks @hwoodiwiss! 🚀 ... See if you think this captures the right sentiment. The added paragraph is versioned with the rest of the `MapStaticAssets` coverage, so it will appear for >=9.0.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d58e5bc7f4b916fc0e3a2869206b228d1b70c71/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33574) |
> Remark on UseBlazorFrameworkFiles with MapStaticAssets

- aspnetcore/includes/trustCertVSC.md
- aspnetcore/security/docker-compose-https.md
- aspnetcore/security/docker-https.md
- aspnetcore/security/enforcing-ssl/includes/enforcing-ssl6-8.md
Fixes #33579
---
|:--|:--|
| [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/45a274aa61af4cb8a7dd483da87800e938ebed4d/aspnetcore/security/docker-compose-https.md) | [Hosting ASP.NET Core images with Docker Compose over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?branch=pr-en-us-33580) |
| [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/45a274aa61af4cb8a7dd483da87800e938ebed4d/aspnetcore/security/docker-https.md) | [Hosting ASP.NET Core Images with Docker over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-https?branch=pr-en-us-33580) |
> Linux cert feature not in .NET 8 yet

- aspnetcore/blazor/fundamentals/handle-errors.md
Addresses #33492
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/588a03b5fff1d18b6520069831cabcd8da057a7a/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-33597) |
> Follow-up example update

- aspnetcore/blazor/fundamentals/handle-errors.md
@guardrex I don't think it makes sense to await `Task.CompletedTask`.  
(The first example won't even compile - you have to use `async` in the method definition when you want to use `await` inside.)
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/64fcca43e8f1d2199487d708dfcb792b765f78b6/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-33620) |
> [Blazor] handle-errors.md - overriding async method with sync code

- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/WebMinOpenApi.csproj
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/WebMinOpenApi.json
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/nuget.config
- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
This PR adds content to the .NET 9 OpenAPI section that describes how C# data types are rendered in the generated OpenAPI document. It also adds detail on schema transformers.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/e1d0983abc415425964fc3ed49a3495c52933f19/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33603) |
> Add content on data types and schema transformers

- aspnetcore/blazor/forms/binding.md
Fixes #33629
Javier ... Adding a bit to reflect your remarks at https://github.com/dotnet/aspnetcore/issues/51978#issuecomment-1814352531.
~The code is a bit long for such a simple concept, so we could have a pseudo-code version here (as you have in your PU issue remark), and I can cross-link to the Blazor sample app where this fully working component example can live. This would merely show ...~
```csharp
protected override void OnInitialized() => Model ??= new();
protected override void OnParametersSet()
{
if (Model!.Id == default)
{
LoadData();
}
}
```
~Mmmmmmmm 🤔 ... I do kind'a like that approach. Anyway, you can review this in this form, and I'll take care of moving it on a future commit.~
***Changed my mind on that ☝️!*** Our BWA sample adopts global interactive SSR, so it isn't …
> Initialize form data with static SSR

- aspnetcore/blazor/includes/js-interop/js-collocation.md
- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Fixes #33631
* For `<script>` tags, current directory path notation (`./`) isn't required.
* For JS interop module loading (`JS.InvokeAsync<IJSObjectReference>()`), current directory path notation (`./`) *IS* required.
This PR should fix the few rough spots that we have.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/location-of-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/48e7001d4b7b538d18cea5b60b155f9dc8af7fe3/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md) | [JavaScript location in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?branch=pr-en-us-33632) |
> Directory path notation (./) for RCL assets

- aspnetcore/blazor/javascript-interoperability/index.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/8edb1c1500bb5436ab3d04cd08cdf91f0c03059e/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-33636) |
> [Blazor] JS Interop - excessive ')' character

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/includes/prerendering.md
Fixes #33643
* API cross-link updates
* Article cross-link updates, especially "interactive routing" to the *Routing* article's section on *Static versus interactive routing*.
* Table updates
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/cafc479815054d312f8f1cb8119834283320083d/aspnetcore/blazor/components/prerender.md) | [Prerender ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-33644) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/cafc479815054d312f8f1cb8119834283320083d/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render …
> Routing article updates

- aspnetcore/host-and-deploy/azure-apps/index.md
Fixes #33234
Contributes to #32808
See [Override app configuration using the Azure Portal](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-8.0&branch=pr-en-us-33235&tabs=visual-studio#override-app-configuration-using-the-azure-portal) and compare to [current version](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-8.0&branch=pr-en-us-33235&tabs=visual-studio#override-app-configuration-using-the-azure-portal)
---
|:--|:--|
| [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3738bffe90fa65c01ab7082710ee9578a9536480/aspnetcore/host-and-deploy/azure-apps/index.md) | [Deploy ASP.NET Core apps to Azure App …
> ASP.NET Core Extensions and Generic host removed /7

- aspnetcore/security/authorization/secure-data.md
Fixes #33598
See [Test the completed app](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-8.0&branch=pr-en-us-33639#test-the-completed-app)
---
|:--|:--|
| [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e6379048dee0ba3fed1cd305952517247a558df/aspnetcore/security/authorization/secure-data.md) | [Create an ASP.NET Core web app with user data protected by authorization](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?branch=pr-en-us-33639) |
> ROPC on secure user data /2

- aspnetcore/security/cors.md
Fixes #33660 
Access-Control-Allow-Methods is a response header, not a request header
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/47dfd2928ebf3f547ffa6e631d79c0241150485e/aspnetcore/security/cors.md) | [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-33673) |
> Remove Access-Control-Allow-Methods from request header list

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
***EDIT by @Rick-Anderson to add preview link***
[Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-9.0&branch=pr-en-us-33656&tabs=visual-studio%2Cminimal-apis)
This PR just restructures the content in the OpenAPI section by adjusting head levels. The original structure looked like this:
```
```
and with these changes it looks like this:
```text
```
The key change was to group the metadata for endpoints and metadata for datatypes into their own sections.
I think the new structure is better but happy for feedback to make it even better.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/44663ab06adf4c8cfd630458 …
> Restructure OpenAPI content

- aspnetcore/blazor/components/index.md
It seems the intro text was originally not intended to be part of the sample code and somehow got included over time. In my opinion, the code samples work better without the intro HTML.
(Testing the code ownership without a mention. :-D)
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/0788963c7dbbb431ee2e4613427f4ac412b71f4b/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33675) |
> [Blazor] Components - loop samples - intro text removal

- aspnetcore/grpc/json-transcoding-openapi.md
- aspnetcore/grpc/json-transcoding-openapi/Program.cs
Fixed: Add missing curly brace in json transcoding openAPI [getting started](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?view=aspnetcore-8.0#get-started
) sample
Fixes #33694
---
|:--|:--|
| [aspnetcore/grpc/json-transcoding-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/daa8b4c86edacceb770b2ed790efd554df2c69c1/aspnetcore/grpc/json-transcoding-openapi.md) | [gRPC JSON transcoding documentation with Swagger / OpenAPI](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?branch=pr-en-us-33674) |
> Add missing curly brace in json transcoding openapi sample

- aspnetcore/blazor/webassembly-build-tools-and-aot.md
- aspnetcore/release-notes/aspnetcore-7.0.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #33707
I don't like using the Wikipedia page, but the MDN page just provides a quick definition with a cross-link to Wikipedia.
---
|:--|:--|
| [aspnetcore/blazor/webassembly-build-tools-and-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/07ac3489a0f80bafe369d89bc93873ad70f61e06/aspnetcore/blazor/webassembly-build-tools-and-aot.md) | [ASP.NET Core Blazor WebAssembly build tools and ahead-of-time (AOT) compilation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-build-tools-and-aot?branch=pr-en-us-33708) |
| [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/07ac3489a0f80bafe369d89bc93873ad70f61e06/aspnetcore/release-notes/aspnetcore-7.0.md) | [What's new in ASP.NET Core …
> Update SIMD cross-link

- aspnetcore/razor-pages/index.md
It says `CreateModel.cshtml` in https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-8.0&tabs=visual-studio-code but that doesn't seem to be a file (`Create Model` is the page model class in Create.cshtml.cs).
`Create.cshtml` seems to be the Razor page it's referring to
---
|:--|:--|
| [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b27705b1af3c857cc3bf16b135cef2ccbbd57980/aspnetcore/razor-pages/index.md) | [Introduction to Razor Pages in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/index?branch=pr-en-us-33712) |
> Fix typo of "CreateModel.cshtml" to "Create.cshtml"

- aspnetcore/blazor/fundamentals/startup.md
pi is 3.1415..., hence this should be 3.142
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/c4493957e664e161f35bc9a2f9a935c3c8cbfbce/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-33721) |
> fix: rounding error

- aspnetcore/security/authorization/secure-data.md
I think we should standardize on ROPC hits that have been fixed.
Fixes  #33727
---
|:--|:--|
| [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/fee61532efcb8ed614d415e222e4b75fc8ea82ff/aspnetcore/security/authorization/secure-data.md) | [Create an ASP.NET Core web app with user data protected by authorization](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?branch=pr-en-us-33726) |
> SFI:ROPC metadata

- quest-config.json
dotnet/docs-tools#413 enhances the config object to support different parents per semester. This adds the updated config for that purpose.
> Add semester changover information to quest

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
Pull updated sample code: https://github.com/dotnet/blazor-samples/pull/351
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/11b34e0871448bbe4542cc39ee4aed72f61af2e6/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-33770) |
> [Blazor] call-javascript-from-dotnet.md - pull sample code

- aspnetcore/grpc/performance.md
Fixes #33783
According to https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.http2limits.initialstreamwindowsize?view=aspnetcore-8.0#microsoft-aspnetcore-server-kestrel-core-http2limits-initialstreamwindowsize, the default size is 768 KB not 96 KB
---
|:--|:--|
| [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/a86bda1fc386e1dd40af40c11360ec16dab468c5/aspnetcore/grpc/performance.md) | [Performance best practices with gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/performance?branch=pr-en-us-33745) |
> Fix incorrect http/2 Kestrel's default stream window size

- aspnetcore/blazor/tutorials/movie-database-app/part-8.md
Fixes #33790
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-8.md](https://github.com/dotnet/AspNetCore.Docs/blob/c44762b5fde459723abcf8d8f19d7184dc24dcbe/aspnetcore/blazor/tutorials/movie-database-app/part-8.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-8](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-8?branch=pr-en-us-33791) |
> Fix tutorial's previous button text

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
This PR updates the section of the OpenAPI doc on excluding endpoints to describe how this can be done in controller-based apps.
fixes: https://github.com/dotnet/aspnetcore/issues/57425
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/31faf404a5b771572f19ab78bd775b27832cb9aa/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33773) |
> Add doc on excluding endpoints in controller-based apps

- aspnetcore/blazor/host-and-deploy/index.md
Fixes #33797
Thanks @tobbi! 🚀 ... I'll let this sit until Monday morning to give you a chance to look/comment on it.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/f4549e546f5aa4e6d0a2d5c7430a68e27a647578/aspnetcore/blazor/host-and-deploy/index.md) | [aspnetcore/blazor/host-and-deploy/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-33802) |
> Clarify best app base path (`<base>` tag) location

- aspnetcore/blazor/blazor-ef-core.md
Fixes #33799
Based on ...
* A passing mention in the [EF Core concurrency article](https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=fluent-api#native-database-generated-concurrency-tokens) that SQLite doesn't support dB-generated concurrency tokens.
* The sample doesn't demo concurrency in local test runs and is developed with both ...
* A requirement on native dB-concurrency tokens.
* The SQLite dB provider.
Will track on https://github.com/dotnet/EntityFramework.Docs/issues/4827 for additional info.
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/5bbeebe14e2c1805e8d12454acf7f6b7861dffa6/aspnetcore/blazor/blazor-ef-core.md) | [aspnetcore/blazor/blazor-ef-core](https://review.learn.microsoft.c …
> SQLite doesn't support automatic concurrency

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Update responses section to describe how to add OpenAPI response metadata for controller-based apps.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/426f73e446c0ecf7ea0717f332c6b916a6626d4e/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33739) |
> Update responses section with controllers metadata information

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/prerendering-and-integration.md
There’s no data protection on the prerendered state sent to the WASM client. The WASM client doesn’t have any keys to decrypt protected data.
You can use Data Protection on your own (and there may be scenarios where built-in features do this) if there are specific data pieces you don’t want the client to use directly but rather send back to the server unchanged (where it can be decrypted and processed).
I did a quick test. I took the value from the `` comment on the prerendered page, and it's just plain Base64-encoded JSON that I can decode and read.
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/78509bd1f1cbfba8b6f854839dfb87ff0bae24a3/aspnetcore/blazor/components/prerender.md) | [Prerender ASP.NET …
> [Blazor] prerender.md - no data protection on prerendered state

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Fixes #33509
Not sure if I can get away with this quite so easily, but I ...
* Copied the existing per-page/component Server/Auto interactivity sections that were versioned for <9.0 and made a new >=9.0 versioning block for them.
* In the >=9.0 sections, I renamed `MauiBlazorWeb.Maui` to `MauiBlazorWeb`.
Will that work?
... and BTW for 9.0 ...
The 9.0 sample updates for the [8.0 MauiBlazorWeb app](https://github.com/dotnet/blazor-samples/tree/main/8.0/MauiBlazorWeb) are just packages, correct? The API changes that you anticipated were pushed to .NET 10 IIRC.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/2060e0d88c45b271a216d9cc9dc7873c759e1001/aspnetcore/blazor/hybrid/tutorials/maui-bla …
> Per-page/component Server/Auto interactivity sections

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #33767
Still guessing a little on the exact phrasing.
cc: @hakenr 
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/96e569edfad6ae93bd01cf8aaa8a5d251f3af6e2/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-33819) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/96e569edfad6ae93bd01cf8aaa8a5d251f3af6e2/aspnetcore/blazor/components/prerendering-and-integration.md) | [aspnetcore/blazor/components/prerendering-and-integration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerenderin …
> Remark on DP protection of persisted component state

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31909
Fixes #33801
This gets ...
* The client secret handled by the Secret Manager tool, not via code in the app.
* Versions the `PersistingAuthenticationStateProvider`/`PersistentAuthenticationProvider` coverage for 8.0.
* Brings in `AddAuthenticationStateSerialization`/`AddAuthenticationStateDeserialization` for >=9.0.
* Sets the `name` claim name as a string to match what we just did in the sample app.
* Removes the hidden field for `ReturnUrl` in the *Redirect to the home page on signout* section because `/` is the default.
I think that covers everything 🤔.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b1a38f5a0295e17a2f80e697 …
> Update BWA+OIDC article updates for 9.0

- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
`OperatingSystem.IsBrowser()` API was introduced in .NET 5.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/bf604fa4f29eeb46e44a4395c170db2f451a9d21/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md) | [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?branch=pr-en-us-33846) |
> [Blazor] Call .NET from JS - OperatingSystem.IsBrowser()

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Fixes #33864
* I placed `diff`s for the `@using` statements for render modes.
* Sample cross-links placed for 9.0.
* Fixed a bad namespace (`MyApp.Shared.Services` 👉 `MauiBlazorWeb.Shared.Services`).
* Reorganized the versioning of the `FormFactor` coverage.
* The naming and section updates otherwise for 9.0, handled on earlier PRs, should be ok 🤞🍀. 
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a27f6ac4c40124d902dd25b1a7b4fd2e3446ad5/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-33865) …
> MAUI Blazor Hybrid + BWA article 9.0 updates

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #33873
Thanks @albi005! 🚀 ... I'll get this updated on the live site in a few minutes.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/2ecb0e24533ecf94039067fcee2b8f35f6ca00a8/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-33874) |
> Revert configuration key to original key name

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
This PR converts code-style references to .NET classes to xref references.
Prior to this there was a mix of code-style and xref references in this file.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/69ad691c81a1c7add04b682218d5c761fe426488/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33853) |
> Prefer xref over code-style

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
NIT fix of indentation under two bullets of each pivot.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/7f9161d02642e90253e7fd97a4011bc85bc366af/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-33878) |
> Fix indentation

- aspnetcore/fundamentals/servers/httpsys.md
- aspnetcore/fundamentals/servers/httpsys/includes/httpsys5-7.md
Applying sensitive terms with GUID changes as part of Content SFI and outlined in [Overview - Writing content securely - Platform Manual](https://review.learn.microsoft.com/en-us/help/platform/security-reference?branch=main). Changes are part of the Microsoft-wide SFI effort. Point of contact: @CelesteDG
DocuTune v1.5.2.0
CorrelationId: [ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db](https://github.com/dotnet/AspNetCore.Docs/pulls?q=is%3Apr+ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db+)
#docutune
---
|:--|:--|
| [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/94b02cd04df0e7916c28151eea93a3f81ac8de58/aspnetcore/fundamentals/servers/httpsys.md) | [HTTP.sys web server implementation in ASP.NET …
> [BULK] - DocuTune remediation - Sensitive terms with GUIDs

- aspnetcore/client-side/spa-services.md
- aspnetcore/client-side/spa-services/sample/SpaServicesSampleApp/ClientApp/app/components/home/home.component.html
- aspnetcore/client-side/spa/includes/angular3-7.md
- aspnetcore/client-side/spa/includes/intro6-7.md
- aspnetcore/includes/spa-templates-recommend-vs.md
- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/security/anti-request-forgery.md
- aspnetcore/security/authorization/limitingidentitybyscheme/samples/AuthScheme/ClientApp/src/app/home/home.component.html
- aspnetcore/tutorials/choose-web-ui.md
- aspnetcore/tutorials/choose-web-ui/includes/choose-web-ui3-7.md
Fixes #32992 
All references are updated, except the ones in example apps/code.
While updating the links I also noticed the links to the "old" React website.
The second commit (7efd129) updates these to the new react website, I can revert this change if wanted.
---
|:--|:--|
| [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/7efd129dc2f211c197801e9e0069fb116d4e23d8/aspnetcore/client-side/spa-services.md) | [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/spa-services?branch=pr-en-us-33871) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/7efd129dc2f211c197801e9e0069fb116d4e23d8/aspnetco …
> update Angular references to new website

- aspnetcore/blazor/debug.md
Fixes #33886
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a75a9e2dcf78302309c016b30bea073a612b0be/aspnetcore/blazor/debug.md) | [aspnetcore/blazor/debug](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-33887) |
> Minor updates to the Debug article

- aspnetcore/blazor/call-web-api.md
Fixes a small typo in code snippets where the quotes are missing.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/bb46096dc91c4029618c9b6938826824180e02dc/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-33894) |
> Fix typo in aspnetcore/blazor/call-web-api.md

- aspnetcore/tutorials/getting-started-with-swashbuckle/includes/getting-started-with-swashbuckle8.md
> remove erroneous text

- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
When reading this article, I found it difficult to understand the meaning of:
> - In server-side apps with multiple users concurrently using the same component.
Eventually, I realized it refers to the difference between calling static .NET methods (where any static state is shared across circuits) and instance .NET methods (where the instance is held by the component, which is part of an individual circuit).
I think updating the introductory sentence would help future readers better understand this context.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/69891ff038e57cba846d7b20bf89ff7c27bf5d02/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md …
> [Blazor] Calling .NET from JS - explanation of scenarios for DotNetObjectReference and instance methods

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
This PR updates the OpenAPI section of the API docs to describe how request bodies are generated in both Minimal APIs and controller-based apps.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/b23f2b8522dfa27eb7781d35c9f8002196e969e4/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33891) |
> Update OpenAPI doc for request bodies

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #33913
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/abdfe6bf4b60581cdadec8be051b0deb72059455/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-33914) |
> Update client section auth state provider remark

- aspnetcore/security/enforcing-ssl.md
- aspnetcore/security/enforcing-ssl/includes/enforcing-ssl8.md
Fixes #33915 
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/f245d8bd6d74ac6e5e029c87c804e1a17df5c0da/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-33916) |
> Fix link in enforcing-ssl

- .github/workflows/blazor-issue-processing.yml
- .github/workflows/issue-processing.yml
@adegeo (cc: @Rick-Anderson @tdykstra @wadepickett) ... I'll give this a shot and see what happens ...
* Moving the Blazor issue processing over to a new workflow.
* The new workflow will apply the `aspnet-core/svc` and `blazor/subsvc` labels, along with the usual job tasks that I do for Blazor issues: place a 'hello' comment, label it with `Blazor`, assign me to the issue, and remove the `Not Triaged` label (if present ... if Repoman ran and applied it).
* I'll try to run this workflow on an opened issue with a path of `aspnetcore/blazor/**`. I'm not sure about the `on` conditional checks because GH docs don't show an example of this combination working ... but we'll see soon enough! 😆
If this works, my recommendation will be to remove the initial labels that Repoman is applying and …
> GH Action for processing Blazor issues

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #33948
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/4da04b82c3e1dfa626d1f199bfa5cff3e4021dcd/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-33949) |
> Initialize the Secret Manger tool

- aspnetcore/tutorials/razor-pages/model.md
- aspnetcore/tutorials/razor-pages/model/includes/model3.md
- aspnetcore/tutorials/razor-pages/model/includes/model5.md
- aspnetcore/tutorials/razor-pages/model/includes/model6.md
- aspnetcore/tutorials/razor-pages/model/includes/model7.md
- aspnetcore/tutorials/razor-pages/model/includes/model8.md
Fixes #33895
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/362bfb1d31cbc1f0d405b51bd0883edc0b2aac58/aspnetcore/tutorials/razor-pages/model.md) | [aspnetcore/tutorials/razor-pages/model](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?branch=pr-en-us-33936) |
> ROPC for models RP /1

- .github/ISSUE_TEMPLATE/blank-issue.md
- README.md
Fixes #33946
Thanks @bukowa! 🚀 
Rick, Tom, Wade ... It might also help to add a section to the *Fundamenals* > *Overview*. I've been running for many years with one for Blazor that might be helping me a little bit ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-8.0#support-requests
If you'd like me to add a similar section tailored generally for the whole repo, let me know. 👂 I can add it to this PR.
~Also... ***Rick*** ... this SO link is lacking your "area" of SO tag thing that you place on your SO links that you give to folks. I couldn't find a quick example of that tag ... what tag/link do you give them ... is it this one ...~
```
https://stackoverflow.com/questions/tagged/asp.net-core
```
~Whatever it is, I'll update the SO link on this PR.~
I'm …
> Add 'How to open an issue' to the README

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/doc-issue.md
Touching up links because markdown isn't rendered in textareas. NO periods on the ends ... they screw up the link when the link is a cut-'n-paste into a browser address bar.
Actually, none of the markdown really makes sense here, but I'm heading OOF for the day, so that will have to wait for another time.
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/blank-issue.md](https://github.com/dotnet/AspNetCore.Docs/blob/70f9163690467408ad52ebb6450972a78b8f1fdf/.github/ISSUE_TEMPLATE/blank-issue.md) | [.github/ISSUE_TEMPLATE/blank-issue](https://review.learn.microsoft.com/en-us/aspnet/core/.github/ISSUE_TEMPLATE/blank-issue?branch=pr-en-us-33966) |
| [.github/ISSUE_TEMPLATE/doc-issue.md](https://github.com/dotnet/AspNetCore.Docs/blob/70f9163690467408ad52ebb6450972a78b8f1fdf/.g …
> Template updates

- aspnetcore/blazor/tutorials/build-a-blazor-app.md
Fixes #33968
Thanks @shiruide! 🚀 ... This is going to a bit of a patch fix. I'd like to drop all of the sample app code for this and just go with NRTs (nullable reference types) everywhere. They've been out since ASP.NET Core 6.0 (C# 10), and most folks are using NRTs now. I'll make a tracking item to work on the topic further. Thanks again for the report!
---
|:--|:--|
| [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a2ef5003ef89afab64aa3e115e1686209491178/aspnetcore/blazor/tutorials/build-a-blazor-app.md) | [aspnetcore/blazor/tutorials/build-a-blazor-app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?branch=pr-en-us-33969) |
> Inline code to drop namespace

- aspnetcore/migration/identity.md
- aspnetcore/migration/proper-to-2x/membership-to-core-identity.md
- aspnetcore/security/app-secrets.md
- aspnetcore/security/app-secrets/includes/app-secrets-3-5.md
- aspnetcore/security/authentication/customize-identity-model.md
- aspnetcore/security/authentication/identity-api-authorization/includes/identity-api-authorization3-7.md
- aspnetcore/security/authentication/identity-custom-storage-providers.md
- aspnetcore/security/authentication/mfa.md
- aspnetcore/security/authentication/mfa/includes/mfa-5-8.md
- aspnetcore/security/data-protection/implementation/key-storage-providers.md
- aspnetcore/security/key-vault-configuration.md
Fixes #33973 
---
|:--|:--|
| [aspnetcore/migration/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdef5219cc3b1122c512e7872ff08c22c1d1af58/aspnetcore/migration/identity.md) | [Migrate Authentication and Identity to ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/migration/identity?branch=pr-en-us-33972) |
| [aspnetcore/migration/proper-to-2x/membership-to-core-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdef5219cc3b1122c512e7872ff08c22c1d1af58/aspnetcore/migration/proper-to-2x/membership-to-core-identity.md) | [Migrate from ASP.NET Membership authentication to ASP.NET Core 2.0 Identity](https://review.learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/membership-to-core-identity?branch=pr-en-us-33972) | …
> ROPC remediation - 11 files

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/render-modes.md
Fixes #33982
... in association with https://github.com/dotnet/blazor-samples/pull/385.
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/abc45f8ff43a2d44fbe6226d34f759002185d13e/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-33983) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/abc45f8ff43a2d44fbe6226d34f759002185d13e/aspnetcore/blazor/components/render-modes.md) | [aspnetcore/blazor/components/render-modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-33983) |
> NavigationManger naming

- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
Fixes #33992
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/feed6877142588ee2e2f7920550885d66e30aaf4/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md) | [aspnetcore/blazor/security/webassembly/hosted-with-identity-server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?branch=pr-en-us-33993) |
> Add secure auth flows INCLUDE

- aspnetcore/performance/caching/distributed/samples/8.x/RedisCache/appsettings.json
- aspnetcore/security/app-secrets.md
- aspnetcore/security/app-secrets/includes/app-secrets-3-5.md
- aspnetcore/security/app-secrets/samples/2.x/UserSecrets/appsettings-unsecure.json
- aspnetcore/security/app-secrets/samples/3.x/UserSecrets/appsettings-unsecure.json
- aspnetcore/security/app-secrets/samples/6.x/UserSecrets/appsettings.Development.json
- aspnetcore/security/authentication/mfa/includes/mfa-5-8.md
- aspnetcore/security/data-protection/configuration/overview.md
- aspnetcore/signalr/redis-backplane.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane2.1.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane2.2.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane3.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane5.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane6.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane7.md
Fixes #33991 
---
|:--|:--|
| [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/88eb2bb3d0daf1f0d8ce3837251e42c88c71b3ee/aspnetcore/security/app-secrets.md) | [Safe storage of app secrets in development in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/app-secrets?branch=pr-en-us-33990) |
| [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/88eb2bb3d0daf1f0d8ce3837251e42c88c71b3ee/aspnetcore/security/data-protection/configuration/overview.md) | [Configure ASP.NET Core Data Protection](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=pr-en-us-33990) |
| …
> ROPC remediation - more files with connection strings

- aspnetcore/fundamentals/openapi/include-metadata.md
This PR adds just a bit more detail about enum metadata to the OpenAPI section of the docs. Specifically, it adds an example of the JsonConverter attribute and explains how flag enums are handled (and why).
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/cb97e6a3ede43bfe949f898589554bae2eec5762/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-33995) |
> Add details on enums in OpenAPI section

- aspnetcore/migration/80-90.md
Fixes #34000
[Internal ***REVIEW URL***](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-8.0&branch=pr-en-us-34004&tabs=visual-studio#replace-usestaticfiles-with-mapstaticassets)
---
|:--|:--|
| [aspnetcore/migration/80-90.md](https://github.com/dotnet/AspNetCore.Docs/blob/b54d886eaff467bdaed4c88fdb5b52f4b631a073/aspnetcore/migration/80-90.md) | [aspnetcore/migration/80-90](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?branch=pr-en-us-34004) |
> MapStaticAssets to migration /2

- aspnetcore/blazor/file-downloads.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/blazor/tutorials/movie-database-app/part-1.md
- aspnetcore/fundamentals/static-files.md
- aspnetcore/migration/80-90.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
- aspnetcore/release-notes/aspnetcore-9/includes/web_asset_delivery.md
Fixes #34008
Addresses #34002
Follow-up to #34004
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/e3e35b7a7293cccf15967dea14ad840df0ca9734/aspnetcore/blazor/file-downloads.md) | [aspnetcore/blazor/file-downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-34009) |
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/e3e35b7a7293cccf15967dea14ad840df0ca9734/aspnetcore/blazor/fundamentals/static-files.md) | [aspnetcore/blazor/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-34009) |
| …
> Map Static Assets updates

- aspnetcore/performance/caching/output/samples/7.x/Program.cs
Currently, output caching documentation reads as if in order to use DI in a custom `IOutputCachePolicy` consumers must register the policy via `AddBasePolicy(...)`, which is incorrect. This is misleading and may lead consumers to over-cache all endpoints and actions when they only want to override the default policy, while keeping the same behaviour as the default policy which requires the `[OutputCache]` attribute and gives more granular caching control.
The way to apply a policy on all of app's endpoints is already documented separately above: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output#default-output-caching-policy.
There is currently no issue for this PR. I am not commonly contributing. If I must open one please let me know. If I need to provide additional …
> Make alternatives 3b (non-DI) and 3c (DI) functionally identical

- aspnetcore/migration/80-90.md
I think we want a bit more verbiage around the migration guidance for updating to `MapStaticAssets` so that users understand what they are doing. Proposing some suggestions.
---
|:--|:--|
| [aspnetcore/migration/80-90.md](https://github.com/dotnet/AspNetCore.Docs/blob/90cd8d4a921dcce6a9d908410e6646723b484b52/aspnetcore/migration/80-90.md) | [aspnetcore/migration/80-90](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?branch=pr-en-us-34032) |
> .NET 9 migration guidance edit suggestions for MapStaticAssets

- aspnetcore/blazor/security/index.md
The sample code only demonstrates how to render different content for authorized and unauthorized users. We shouldn't mislead users by naming the button click handler `SecureMethod` or suggesting it's secure in the description below the sample.
Even in server-side Blazor, the method could still be called from other places (either explicitly or through some attack technique), and it doesn't provide any security protection on its own.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/db2aaab0f66fce0cdb0d13dae40b2bc2e57bad76/aspnetcore/blazor/security/index.md) | [aspnetcore/blazor/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-34031) |
> [Blazor] Security overview - SecureMethod correction

- aspnetcore/blazor/security/index.md
"Policy name" sounds appropriate and is more accurate in this case.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/a7153a48446183dc3272885acf10baa7ee81506a/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-34030) |
> [Blazor] Security overview - Policy name

- aspnetcore/migration/80-to-90/includes/blazor.md
Fixes #34007
cc: @Rick-Anderson ... I'll get any remaining Blazor migration items on here as they come to light in my discussion with Mackinnon.
Mackinnon ... I think outside of the ASP.NET Core-wide changes (TFM, packages, Map Static Assets routing endpoint conventions) that simplified authentication state serialization is the only migration item ... an optional feature but probably a good idea for devs to adopt. Can you think of any others?
BTW ... Although the project templates and Blazor sample apps for 9.0 adopt the latest Bootstrap version, that's a dev task in their own apps that might require other Bootstrap-specific implementation changes, not a MS product, and not on the same release cadence as .NET. Therefore, I'm not placing guidance on updating for latest Bootstrap.
> Add a migration scenario for Blazor

- aspnetcore/blazor/components/dynamiccomponent.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/host-and-deploy/configure-linker.md
- aspnetcore/blazor/progressive-web-app.md
- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
- aspnetcore/grpc/supported-platforms.md
- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/test/dev-tunnels.md
Hi @cmastr, @Rick-Anderson, @wadepickett, @tdykstra I have fixed the broken links, please verify, thanks。
https://dev.azure.com/msft-skilling/Content/_workitems/edit/335393/?view=edit
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/6573c89094f0aa5f733c2be7591952b22dd20c35/aspnetcore/blazor/components/dynamiccomponent.md) | [aspnetcore/blazor/components/dynamiccomponent](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-34001) |
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/6573c89094f0aa5f733c2be7591952b22dd20c35/aspnetcore/blazor/components/layouts.md) | …
> Q&M: Fix broken links identified by the Broken links report - fix aspnetcore.docs repo

- aspnetcore/blazor/progressive-web-app.md
Fixes #34013 
Turns out that I just need to go with the 6.0 branch for the assets, as it doesn't look like there were changes between 6.0 and 7.0.
---
|:--|:--|
| [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/d79561d9f07f7f8dc6767b693bf459ef23e8ba82/aspnetcore/blazor/progressive-web-app.md) | [aspnetcore/blazor/progressive-web-app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?branch=pr-en-us-34040) |
> Change PWA asset cross-link to 6.0

- aspnetcore/performance/caching/hybrid.md
- aspnetcore/release-notes/aspnetcore-9/includes/hybrid-cache.md
fixes https://github.com/dotnet/AspNetCore.Docs/issues/34042
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/a2c4994e6fc25b02e437582b441c1a43a29e9546/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-34043) |
> 9.0 HybridCache; clarify release status

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Addresses #34041
cc: @MackinnonBuck ... This is the other spot that had this content, which I'm removing at DR's request because he says that it's wrong. IIRC, we discussed this, and I thought that it was a supported scenario. Anyway ... removing it now. If you recall what scenario we were trying to cover where server components must be placed in the client project, I'm 👂 for notes on that scenario and if I need to try a again to cover it.
> Remove remarks

- aspnetcore/blazor/components/prerendering-and-integration.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/progressive-web-app.md
Fixes #34060
BTW @Rick-Anderson @wadepickett @tdykstra ...
I'm finding just a few NIT problems in the Blazor node for reference source links. For example, the `release/7.0` branch was dropped, but those assets can be obtained via the `v7.0.0` ***tag*** (**Tags** tab of **Switch branches or tags**).
When I search the whole repo, I see a number of remarks tied to reference source links that are pegged to old framework versions. I'm not performing an analysis on them, so perhaps they're fine, but it seems like a concern. For example, making a current-release remark about API but linking all the way back to the 3.1 or 6.0 reference source 😨. Idk if you want to open an issue to investigate ref source cross-linking.
The Blazor docs will be resolved with my work this morning. I found links with …
> Fix reference source cross-links

- aspnetcore/security/index.md
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/eb6fb98d6ea6d4b48a921f178a541ead315e6a75/aspnetcore/security/index.md) | [aspnetcore/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-34058) |
> Delete duplicate section

- aspnetcore/migration/80-90.md
- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
- aspnetcore/release-notes/aspnetcore-9/includes/web_asset_delivery.md
Fixes #34033
---
|:--|:--|
| [aspnetcore/migration/80-90.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d7ff82a935f13ef7d4141c0ea554b7b59bf5e93/aspnetcore/migration/80-90.md) | [aspnetcore/migration/80-90](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?branch=pr-en-us-34055) |
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d7ff82a935f13ef7d4141c0ea554b7b59bf5e93/aspnetcore/release-notes/aspnetcore-9.0.md) | [aspnetcore/release-notes/aspnetcore-9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-34055) |
> Feature static asset deliver /2

- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Removing mention of .NET 10 from the .NET 9 release notes. We'll announce what's on the .NET 10 roadmap once we're further along with planning.
> Removing mention of .NET 10 in .NET 9 release notes

- aspnetcore/blazor/security/server/static-server-side-rendering.md
Excessive characters removed.
---
|:--|:--|
| [aspnetcore/blazor/security/server/static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/f39be59f04a8cb3a568063da9e2af799848b32b8/aspnetcore/blazor/security/server/static-server-side-rendering.md) | [Threat mitigation guidance for ASP.NET Core Blazor static server-side rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/static-server-side-rendering?branch=pr-en-us-34065) |
> [Blazor] SSR Threats - N^2

- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
Fixes #34069
"Splatting" was already explained (including by example), but I'll make a change that should improve it.
---
|:--|:--|
| [aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/a9b85ef04c4f31538318db221af2c66f3c91cb59/aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md) | [aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/splat-attributes-and-arbitrary-parameters?branch=pr-en-us-34071) |
> Small change to 'splatting' explanation

- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
"calling splatting" => "called splatting"
---
|:--|:--|
| [aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/6009cd7c401ddf0a5308e98c29e2bf3b8a31363a/aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md) | [ASP.NET Core Blazor attribute splatting and arbitrary parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/splat-attributes-and-arbitrary-parameters?branch=pr-en-us-34074) |
> [Blazor] splat-attributes-and-arbitrary-parameters.md - typo

- aspnetcore/fundamentals/dotnet-scaffold-telemetry.md
- aspnetcore/toc.yml
Fixes #34066 
---
|:--|:--|
| [aspnetcore/fundamentals/dotnet-scaffold-telemetry.md](https://github.com/dotnet/AspNetCore.Docs/blob/a7ad69326a3fc8f6fc04a5954fb7496d1bcfefab/aspnetcore/fundamentals/dotnet-scaffold-telemetry.md) | [dotnet-scaffold telemetry](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dotnet-scaffold-telemetry?branch=pr-en-us-34067) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/a7ad69326a3fc8f6fc04a5954fb7496d1bcfefab/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34067) |
> Telemetry article for dotnet-scaffold CLI tool

- .openpublishing.publish.config.json
- aspnetcore/docfx.json
- aspnetcore/toc.yml
Fixes #33996
Add the configuration and TOC changes for publishing the breaking changes articles to the razor compiler.
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/774aed08f39a9ba4ef1c586b1ba4ba68f0d2fe0f/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34063) |
> Add breaking changes docs

- aspnetcore/signalr/dotnet-client.md
- aspnetcore/signalr/dotnet-client/sample/SignalRChat/Hubs/ChatHub.cs
I changed FAQ link to reference [article](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-resource-faq) instead of readme on [GitHub](https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#what-is-the-meaning-of-service-mode-defaultserverlessclassic-how-can-i-choose).
Minor code improvements in `dotnet-client.md`.
Fixes #34092
---
|:--|:--|
| [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/98c07dc66ded7431dba1b8b6be8d857f5a8fd5e0/aspnetcore/signalr/dotnet-client.md) | [ASP.NET Core SignalR .NET Client](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?branch=pr-en-us-34047) |
> [signalr/dotnet-client.md] Reference FAQ article instead of GitHub readme

- aspnetcore/diagnostics/asp0028.md
Adding the documentation on the [diagnostic ASP0028 added in this PR](https://github.com/dotnet/aspnetcore/pull/58872)
***EDIT*** Fixes #34089
---
|:--|:--|
| [aspnetcore/diagnostics/asp0028.md](https://github.com/dotnet/AspNetCore.Docs/blob/99dacb2611c7e9eff4466093d258b94880a5ec73/aspnetcore/diagnostics/asp0028.md) | [ASP0028: Consider using `IPAddress.IPv6Any` instead of `IPAddress.Any`](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0028?branch=pr-en-us-34084) |
> feat: ASP0028 diagnostic docs

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Tiny fix to the OpenAPI docs to remove the prerelease flags from the package install commands.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/aa6c58227895cd13ea9c3223a5ff7f9051edd7f5/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-34096) |
> Drop prerelease flags now that .NET 9 has shipped

- aspnetcore/includes/not-latest-version-without-not-supported-content.md
- aspnetcore/includes/not-latest-version.md
Fixes #34100
This version of the file doesn't include the not-supported content.
After this goes in, I'll update my Blazor PR to use this file, which only addresses the new Blazor articles at 8.0 that were versioned >=8.0 at the file level.
> Add a not-latest-version INCLUDE

- aspnetcore/blazor/components/render-modes.md
Fixes #34085
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/14b0084ea6352d4a98449ab4ad7ec07d4253f2e5/aspnetcore/blazor/components/render-modes.md) | [aspnetcore/blazor/components/render-modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-34116) |
> Add RendererInfo examples

- aspnetcore/blazor/tutorials/movie-database-app/part-1.md
- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Addresses #34121
Initial updates. More to come on a future PR after #34120 is resolved.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-1.md](https://github.com/dotnet/AspNetCore.Docs/blob/36c552be428bcb5d8aa28c2434ff4e4fd80bdddd/aspnetcore/blazor/tutorials/movie-database-app/part-1.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-1](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-1?branch=pr-en-us-34122) |
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/36c552be428bcb5d8aa28c2434ff4e4fd80bdddd/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.lear …
> Initial movie tutorial updates

- aspnetcore/blazor/components/data-binding.md
Fixes #34127
Thanks @willdean! 🚀 ... I'll hold it for sec while you check out the update. I'm not going to wait for the product unit on this one. I agree with your suggestion for the change.
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/451eb67f2ffc4bd65e46871c647fb2d48346dbbb/aspnetcore/blazor/components/data-binding.md) | [aspnetcore/blazor/components/data-binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-34128) |
> Fix `@bind:after` description

- aspnetcore/blazor/tutorials/movie-database-app/part-3.md
- aspnetcore/blazor/tutorials/movie-database-app/part-6.md
Fixes #34121
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-3.md](https://github.com/dotnet/AspNetCore.Docs/blob/676d8dda187449ea42c6c82d57d9e685582a566f/aspnetcore/blazor/tutorials/movie-database-app/part-3.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-3](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-3?branch=pr-en-us-34136) |
| [aspnetcore/blazor/tutorials/movie-database-app/part-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/676d8dda187449ea42c6c82d57d9e685582a566f/aspnetcore/blazor/tutorials/movie-database-app/part-6.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-6](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part- …
> Blazor movie dB tutorial updates

- aspnetcore/blazor/security/server/index.md
Fixes #34134
@hakenr ... See what you think of these "improvements" ... "improvements" in quotes because I might be making it ***worse!*** 😆 
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a58ef3ac5be340d8a1b2f5c3d7fa7aa923dead0/aspnetcore/blazor/security/server/index.md) | [aspnetcore/blazor/security/server/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-34135) |
> Improve article section

- aspnetcore/blazor/tutorials/movie-database-app/part-3.md
Fixes #34121
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-3.md](https://github.com/dotnet/AspNetCore.Docs/blob/00ef56892200a887cf0841613d35d49ecb6cf9aa/aspnetcore/blazor/tutorials/movie-database-app/part-3.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-3](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-3?branch=pr-en-us-34137) |
> Blazor movie tutorial article updates (final)

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Addresses #34120
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/706e16bafc175035636d5898d159d593469998e0/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34142) |
> Update VS regression remarks

- aspnetcore/migration/60-70.md
Fixes #34143
Thanks @dougclutter! 🚀 
... and I missed enabling a section on `@bind:get`/`@bind:set` modifiers for binding. It was commented out at the time because there was a bug in the framework at release. The bug was fixed in a patch later. I enabled the [new content in the 7.0 version of the binding article](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0#bind-across-more-than-two-components) when the patch landed, but I failed to enable it in this article.
This type of mistake likely won't happen again because now I use an approach to track content that I need to address during release. I place an HTML comment into the markdown to flag items like this. In this case, I would've placed something like "UPDATE 7.0 - Enable this when …
> Update 7.0 migration guidance

- aspnetcore/blazor/components/virtualization.md
Fixes #34149
Thanks @NikolaJacques! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b909f6ee4a5c20aa96d8f3f22cc6098b6d8b658/aspnetcore/blazor/components/virtualization.md) | [aspnetcore/blazor/components/virtualization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?branch=pr-en-us-34151) |
> Explain field used by example

- aspnetcore/blazor/includes/js-interop/js-collocation.md
- aspnetcore/blazor/includes/js-interop/synchronous-js-interop-call-js.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Addresses #34126
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0bc5c3466b890da45efe647157ecfcdde07cdc1/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md) | [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?branch=pr-en-us-34178) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0bc5c3466b890da45efe647157ecfcdde07cdc1/aspnetcore/blazor/javascript-interoperability/index.md) | [aspnetcore/blazor/javascript-interoperability/index](https://review.l …
> JS interop/circuit disposal updates

- aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
- aspnetcore/host-and-deploy/visual-studio-publish-profiles/samples/FolderProfile.pubxml
- aspnetcore/host-and-deploy/visual-studio-publish-profiles/samples/TP_before.pubxml
- aspnetcore/host-and-deploy/visual-studio-publish-profiles/samples/Web1.pubxml
Fixes #33861
Fixes #30013
Fixes #33759
Fixes #24852
Fixes #32721
Fixes #34131
I removed most information found in  [Microsoft.NET.Sdk.Publish](https://github.com/dotnet/sdk/tree/main/src/WebSdk), [Overview of Visual Studio Publish](https://review.learn.microsoft.com/en-us/visualstudio/deployment/publish-overview) and 
[MSBuild](https://review.learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-introduction)
---
|:--|:--|
| [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/d14f983400f776c9ebbae2f4df6d98392f55aac3/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md) | [aspnetcore/host-and-deploy/visual-studio-publish-profiles](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deplo …
> ROPC: dotnet publish /2

- aspnetcore/blazor/fundamentals/signalr.md
Azure SignalR now fully support stateful reconnect
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/3b419ced240b4929e9c19f8d84cc1c8fc633b408/aspnetcore/blazor/fundamentals/signalr.md) | [aspnetcore/blazor/fundamentals/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-34213) |
> Update signalr.md for Azure SignalR reconnect

- aspnetcore/blazor/components/quickgrid.md
Fixes #34211
This includes the border fix, if you wish to keep it. I'll track the empty data row template PU issue, possibly for .NET 10, which will lead to >=10 modifications to that part of the coverage here.
Do you want the movie dB tutorial to include the border workaround for empty rows?
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/7232da59853a689f3bdecceb621e8a6f7b2821bc/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-34214) |
> QuickGrid empty rows and border styling

- aspnetcore/blazor/state-management.md
I think the original explanation with "window" might be misinterpreted, as in the browser there’s a "New window" action, and users often open links in a new window (Shift+Click), which still shares the same `localStorage` scope.
---
|:--|:--|
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/4df7b518ae1cc0f81f19b0b386605a0318f84832/aspnetcore/blazor/state-management.md) | [aspnetcore/blazor/state-management](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/state-management?branch=pr-en-us-34220) |
> [Blazor] Stage management - localStorage explanation adjustment

- .github/workflows/blazor-issue-processing.yml
- .github/workflows/blazor-pr-processing.yml
@Rick-Anderson @tdykstra @wadepickett ... Hopefully 🤞🍀, this included PR processing will write a comment when the code owners action assigns me as a reviewer. *We'll see!* 
---
|:--|:--|
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/7cf23bd9b49c0c00a4dd524ca1312f7fd0dd4d80/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-issue-processing?branch=pr-en-us-34230) |
| [.github/workflows/blazor-pr-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/7cf23bd9b49c0c00a4dd524ca1312f7fd0dd4d80/.github/workflows/blazor-pr-processing.yml) | …
> Blazor issue/PR automation

- aspnetcore/performance/caching/hybrid.md
Fixes #34250
- Added a note indicating that removing cache entries by tag is still under development and is currently non-functional.
- Clarified that cache invalidation by key or tags affects only the current node and secondary storage, but not other nodes' in-memory cache.
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/08192e0acf12e12d978fdfde62a1f472456aabcf/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-34224) |
> Add important notes on HybridCache limitations and behavior

- aspnetcore/blazor/debug.md
styling
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9d8c73998dfe028e4cd3a7a1da9cf2a977a6d38/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-34240) |
> [Blazor] Debug - missing *

- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
The `Microsoft.AspNetCore.Components.Forms` package is already transitively referenced by `Microsoft.AspNetCore.Components.Web` package (which is included in the RCL template). No need to add explicit reference to `Forms` package.
---
|:--|:--|
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/e2a24fd658a0bebf94855c5264b3cf84bcdfd8d4/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?branch=pr-en-us-34242) |
> [Blazor] webassembly-lazy-load-assemblies.md - Forms package already referenced

- aspnetcore/fundamentals/owin.md
I would prefer to revert https://github.com/dotnet/AspNetCore.Docs/pull/19693, because by moving the Nowin sample, we removed any documentation on how to run ASP.NET Core using an OWIN server. But if we decide that isn't an important enough scenario to still document, since we don't know of any supported OWIN servers that run outside of .NET Framework, the "Run ASP.NET Core on an OWIN-based server and use its WebSockets support" section makes no sense. All it shows is bog standard WebSocket code. The only thing interesting about it was the code to make it work on Nowin which is thankfully still in the [sample directory](https://github.com/dotnet/AspNetCore.Docs/tree/9771604bd406c2415514f09a890d972b5ffb9a5f/aspnetcore/fundamentals/owin/sample/src/NowinWebSockets).
---
| 📄 File | 🔗 Preview …
> Remove Nowin WebSocket sample

- aspnetcore/blazor/javascript-interoperability/static-server-rendering.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #34086
Per https://github.com/dotnet/aspnetcore/issues/58630.
They seem straightforward enough. I didn't see tests for the new events in the framework. Do you have any specific example(s) that you'd like to show for them?
Also, I'm not sure if using the word "load" in the way that I have for the description is correct for `enhancedload`. 👀
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/static-server-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/777d6a978d79a8174d2df8324cd37282dcd58b5a/aspnetcore/blazor/javascript-interoperability/static-server-rendering.md) | [aspnetcore/blazor/javascript-interoperability/static-server-rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoper …
> Add Blazor enhanced nav events

- aspnetcore/blazor/forms/binding.md
Fixes #34078
Per https://github.com/dotnet/aspnetcore/issues/58869.
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e20dcabaf87392d8c409f0e4ec40a7c36137a57/aspnetcore/blazor/forms/binding.md) | [aspnetcore/blazor/forms/binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-34082) |
> Form name attribute coverage

- aspnetcore/host-and-deploy/linux-nginx.md
Fixes #33159
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/e2d5250cfc293a356dfd498bab62ad2557829804/aspnetcore/host-and-deploy/linux-nginx.md) | [Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-33132) |
> Fix instructions for setting up Nginx

- aspnetcore/blazor/performance.md
1. When I think back to what wasn’t entirely clear to me and I had to test and look up in the source code - the whole condition for primitive types in change detection applies to the parameters **used (set)** in a specific place, not to the component **having** non-primitive parameters.
2. Starting net9 EventCallbacks are included in change detection.
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/b79fd5034b4902ee7429e140f1aedf21c6fa2a00/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-34281) |
> [Blazor] Performance - Change detection - set parameters only

- aspnetcore/blazor/performance.md
relates to re-rendering discussed above in the article
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/5445e7b325a0463a0ca6b7532feaea42ecdd9dcc/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-34292) |
> [Blazor] Performance - IsFixed=true for `this` explanation

- aspnetcore/blazor/performance.md
I'm not sure what was meant by "event callbacks aren't supported" in this context.
This code with event callback works as expected:
```razor
@page "/counter"
@using Microsoft.Extensions.Logging
@inject ILogger<Counter> Logger
@MyRenderFragment
@code {
private RenderFragment? MyRenderFragment => @<button @onclick="HandleValidSubmit">Submit</button>;
private void HandleValidSubmit()
{
Logger.LogInformation("HandleValidSubmit called");
}
}
```
(Don't worry, this is my last PR for today. 😇)
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/aef6f508c6b6ced745a461b5fa46faf324392a4c/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/bla …
> [Blazor] Performance - Event callbacks in RenderFragments

- aspnetcore/fundamentals/openapi/using-openapi-documents.md
openapi scalar endpoint local
Got in the https://guides.scalar.com/scalar/scalar-api-references/net-integration
Print screen locally:
Thanks 😊
Fixes #34319
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/using-openapi-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/2599057c15baa1b4aeac0910b0337ac56584a582/aspnetcore/fundamentals/openapi/using-openapi-documents.md) | [aspnetcore/fundamentals/openapi/using-openapi-documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?branch=pr-en-us-34308) |
> openapi scalar endpoint local

- aspnetcore/blazor/components/data-binding.md
Fixes #33994
Thanks @adamgf1! 🚀
I'm bringing in Artak's sentiment from the discussion that `:get`/`:set` (`:set` specifically) binding means that you're notified in advance and get a chance to change the bound value. I'm also making a few phrasing changes and other minor updates.
I'm fleshing out the bit about the discarded task when using the `get`/`set` accessor approach in multiple component binding scenarios. If devs want to see that, they'll have a link here to take them back to the 6.0 version of the article, where they can study the `NestedChild` component of that era with its old skool approach ...
```csharp
private string BoundValue
{
get => ChildMessage ?? string.Empty;
set => ChildMessageChanged.InvokeAsync(value);
}
```
---
|:--|:--|
| …
> Improve binding guidance

- aspnetcore/blazor/hybrid/index.md
- aspnetcore/blazor/hybrid/security/index.md
- aspnetcore/blazor/hybrid/tutorials/maui.md
- aspnetcore/blazor/index.md
Fixes #34325
@wadepickett ... Had a few minutes to knock this out now 🤜😵. This resolves it for the "blazor" node articles. 
No review necessary. I found the replacement links; or in one case, the link was already there below the Xamarin remark, so I only had to remove the Xamarin cross-link.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4217eff73aae79d92dc352fff952039b05717d64/aspnetcore/blazor/hybrid/index.md) | [aspnetcore/blazor/hybrid/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/index?branch=pr-en-us-34328) |
| [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4217eff73aae79d92dc352fff952039b05717d64/aspnetcore/blazor/hybrid/security/in …
> Drop Xamarin from Blazor articles

- aspnetcore/blazor/includes/js-interop/synchronous-js-interop-call-js.md
1. When mentioning `IJSInProcessObjectReference`, we should demonstrate its usage in the sample, not just retrieve it. I’ve added the line `var value = module.Invoke<string>("javascriptFunctionIdentifier");` to address this.
2. When discussing the performance benefits of synchronous WASM calls over asynchronous code (as this file is part of the Blazor Performance article), the entire sample should be synchronous for consistency.
> [Blazor] synchronous-js-interop-call-js.md - fully synchronous code sample

- aspnetcore/blazor/state-management.md
> In a custom state management service, a callback invoked outside of Blazor's synchronization context must wrap the logic of the callback in [ComponentBase.InvokeAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.invokeasync) to move it onto the renderer's synchronization context.
There isn’t a straightforward way to use `ComponentBase.InvokeAsync` directly in a custom state management service. Instead, each component subscribed to the `OnChange` event must handle it by wrapping the `StateHasChanged` call in `InvokeAsync`. This means the responsibility for ensuring synchronization with Blazor’s rendering context falls on the components themselves.
---
|:--|:--|
| …
> [Blazor] State management - StateHasChanged+InvokeAsync

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #34208
Thanks @beachseeker! 🚀 ... If Dan decides to elaborate further, I'll place a follow-up PR.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe8acb472e288ef19d922b4caeae0e3a8965ef1d/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34347) |
> Clarify the goal of EF Core code-first

- aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md
Fixes #34348
Rolled into the sample apps on https://github.com/dotnet/blazor-samples/pull/402.
No need to update the overview, as this part of the cookie auth state provider isn't shown or mentioned.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/ec2546db5b135ea15fa47c95b83fbac39a18df06/aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md) | [aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps?branch=pr-en-us-34349) |
> Remove logger step

- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Even though repeated calls to `AssemblyLoader.LoadAssembliesAsync()` don't download the assembly multiple times or throw exception:  
- They still trigger asynchronous calls to JavaScript.  
- The `<Navigating>` content is rendered in the meantime, causing unnecessary UI flickering when navigating to the lazy-loaded area repeatedly.  
- The `lazyLoadedAssemblies` collection gets populated with duplicate entries.  
Therefore, lazy-loading should be guarded with an "already loaded" flag.
---
|:--|:--|
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/6d848125dd50a3e46c68b1ffc5b3243c5815803a/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [aspnetcore/blazor/webassembly-lazy-load-assemblies](https://rev …
> [Blazor] Lazy loading - Complete example - Prevent repeated loads

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/state-management.md
Addresses #34236
@hakenr ... Let's see if we can make some progress with obvious problems in the section just to get the ball rolling.
I placed some 🦖 ***RexHacks!™*** 🙈 on here to at least improve things while the thrust of your main suggestion is discussed on the issue.
Three goals of this ...
* Change the section heading to say what this is. The state provider is in the "common location," so I'm seeing if the heading as "*Factor out state preservation to a common provider*" works.
* Discuss the prerendering situation and update the code to deal with it.
* Explicitly call out that this isn't good for multiple components that modify/render the state on the same page.
BTW ... I don't speak to getting access to state from a provider ***during prerendering***, which is something to consider …
> State preservation (common provider) updates

- aspnetcore/blazor/state-management.md
In the first example, there’s no `isConnected` field.  
I think the `isConnected` must have sneaked in by copy-pasting from another section and doesn’t make sense here.
---
|:--|:--|
| [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/3b42cc413888627336e945438ed6b8149b6d4f07/aspnetcore/blazor/state-management.md) | [ASP.NET Core Blazor state management](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/state-management?branch=pr-en-us-34353) |
> [Blazor] state-management.md - isConnected vs. isLoaded

- aspnetcore/blazor/includes/js-interop/js-collocation.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
Fixes #34360
Thanks @ScarletKuro! 🚀 ... Thus far, this takes care of the last Blazor sample code from the samples repo (changing the date of the article pulls the new code). I'll make a sweep now to determine if there are any in-text examples to address.
**UPDATE**: Found a couple of more NITs.
WRT the coverage on "support" for returning a task in the *Event Handling* article, it's really just this one line ...
> * Asynchronous delegate event handlers that return a <xref:System.Threading.Tasks.Task> is supported.
I'll talk to the product unit about that in 25Q1. It will be tracked by my UE Tracking issue, so it won't get lost.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/ …
> Pull new sample code

- aspnetcore/fundamentals/middleware/index.md
- aspnetcore/fundamentals/middleware/index/includes/index3-7.md
Fixes #34382
Addresses #34356
Notes
* There are other options for the section heading. I recommend using "app type" language over "web UI" language.
* The rest of this article probably only requires minimal changes. The RP-based example in one of the sections requires minimal changes. I think the changes there can probably make the pipeline agnostic to app type.
* BTW ... Static Files Middleware was never addressed in this article for >=8.0. I guess that's tracked by some other issue ... just mentioning it FYI in case it isn't tracked somewhere.
---
|:--|:--|
| [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/64b82acab1e084a77c7c4a54a75a3ab98dfd4369/aspnetcore/fundamentals/middleware/index.md) | …
> Add section on middleware by app type

- aspnetcore/fundamentals/use-http-context.md
Fixes #34367
---
|:--|:--|
| [aspnetcore/fundamentals/use-http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/a3f92db15f01341abbcca5ff20e392564b0cbd20/aspnetcore/fundamentals/use-http-context.md) | [Use HttpContext in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?branch=pr-en-us-34368) |
> Add Blazor to lists of app types

- aspnetcore/fundamentals/openapi/include-metadata.md
Parameter descriptions are of class [DescriptionAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute?view=net-9.0) not of class [EndpointDescriptionAttribute](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.endpointdescriptionattribute?view=aspnetcore-9.0).
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/8d68439883f2f76307c200a61eaa8a2693ef9220/aspnetcore/fundamentals/openapi/include-metadata.md) | [Include OpenAPI metadata in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-34387) |
> OpenAPI DescriptionAttribute for parameters

- aspnetcore/blazor/fundamentals/environments.md
Fixes #34392
Thanks @nicholasyin! 🚀 ... This improves the guidance with WASM and the environment variable for local development runs. I also include some new guidance for Nginx and Apache file server hosting scenarios. I'm waiting for the product unit to get back to me; but if I don't hear from them by EOD, I'll probably go ahead and merge this. I'll patch it later based on my discussion with them. Thanks for writing in on this, and keep your 👁️ on https://github.com/dotnet/aspnetcore/issues/59456 for some possible improved control in a future release of Blazor.
**UPDATE**: I just heard back that they're too busy to look right now. I'll make a final pass on Thursday morning. Since this matches the behavior of the framework, I'll go ahead and merge it tomorrow morning. I'll patch it later …
> Improve Blazor environment guidance

- aspnetcore/blazor/components/quickgrid.md
Fixes #34401
Thanks @coderdnewbie! 🚀 ... This might help some folks in the meantime with the 9.0 scaffolder. It makes the point that they need the factory pattern right now. I have a tracking remark in the article to keep an 👁️ on your scaffolding issue for .NET 10.
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/f238ac52bc2bf775fba15a55ac033024dad3d172/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-34402) |
> QuickGrid scaffolding dB context remarks

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #34403
Thanks @pablosantosluaces! 🚀 ... I figured out the Blazor Server approach based on your BWA code and included the proper versioning for the section.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/a90fee2d363e498b774447f25c4556602630ecd4/aspnetcore/blazor/fundamentals/signalr.md) | [aspnetcore/blazor/fundamentals/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-34404) |
> Start Blazor circuit with custom URL

- aspnetcore/blazor/hosting-models.md
- aspnetcore/blazor/project-structure.md
Fixes #34440
---
|:--|:--|
| [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/640ea88a2bdd77057fb7722432012c31252e1114/aspnetcore/blazor/hosting-models.md) | [aspnetcore/blazor/hosting-models](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?branch=pr-en-us-34441) |
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/640ea88a2bdd77057fb7722432012c31252e1114/aspnetcore/blazor/project-structure.md) | [aspnetcore/blazor/project-structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-34441) |
> Framework JS files are static web assets

- aspnetcore/fundamentals/index/samples/9.0/BlazorWebAppMovies/Components/Pages/Weather.razor
- aspnetcore/fundamentals/openapi/overview.md
- aspnetcore/fundamentals/openapi/samples/9.x/AspireApp1/AspireApp1.Web/Components/Pages/Weather.razor
Fixes #34438
Rick (and Wade, you're on as the MS author of one of the articles/samples) ...
The PU didn't backport the spelling fix (it's 10.0+), and the new Aspire 10.0 sample won't likely be created for some time. However, I think we should go ahead and fix this now for 9.0+ and not sweat versioning the change. It's not going to be particularly noticeable that we have it spelled correctly ***here***, and it will avoid devs opening issues ***for us***. 😆
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/aecc14bd46c3570071c3f861575f6315708ecf7e/aspnetcore/fundamentals/openapi/overview.md) | [aspnetcore/fundamentals/openapi/overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openap …
> Fix misspelled word

- aspnetcore/blazor/hosting-models.md
- aspnetcore/blazor/includes/js-interop/js-collocation.md
- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/project-structure.md
Fixes #34414
Thanks @gregoryagu! 🚀 ... I won't merge this until tomorrow morning (Friday) to give you a chance to review it.
---
|:--|:--|
| [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/dbb863e45c81eeaec222de05c3eed5ed77e24ab3/aspnetcore/blazor/hosting-models.md) | [aspnetcore/blazor/hosting-models](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?branch=pr-en-us-34432) |
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/dbb863e45c81eeaec222de05c3eed5ed77e24ab3/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet](https: …
> Prohibition on `<script>` tags for modules

- README.md
This link needs to be removed, the Feedback repo has not been the standard site feedback channel for over three years.
> Update README.md - remove link to unmonitored feedback repo

- aspnetcore/grpc/troubleshoot.md
Fixes #34452
Minor fix:
Moniker range was missing a ">" for 8.0, instead of >= it was =.  Fixed.
---
|:--|:--|
| [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/ae65906d4dc44176a3207ed4e6680b63a0a89059/aspnetcore/grpc/troubleshoot.md) | [aspnetcore/grpc/troubleshoot](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?branch=pr-en-us-34454) |
> gRPC Troubleshoot: Fix moniker range

- aspnetcore/blazor/fundamentals/configuration.md
Fixes #34458
Thanks @gregoryagu! 🚀 ... How about this? It includes getting rid of the "MY" naming. I've been dropping "MY"-named things around here for years, and here's yet another one 😩 to get rid of.
The reason that this wasn't fleshed out in the first place is simply that the Blazor doc set is an ***add-on*** doc set. All of this is covered by the cross-linked *Options* article in the main doc set. However, it is nice to show the Razor component piece, and it may as well add the other pieces to make it work.
There's an effort underway to make the main doc set's *Fundamentals* node articles emphasize Razor component/Blazor examples. That's on-going work.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Doc …
> Enhance the Options config example

- aspnetcore/test/http-files.md
Fixes #33730 
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/0d16f8878fe2e528527e939dbb41685810f17b2a/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-34406) |
> Document shared environments in environment files

- aspnetcore/blazor/components/quickgrid.md
See <https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.name?view=net-8.0#remarks> which reads
> Do not use this property to get the value of the [Name](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.name?view=net-8.0) property. Use the [GetName](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.getname?view=net-8.0) method instead.
I think using `.Name` instead of `.GetName()` would return the resource key / non-localized version.
Note: I didn't verify the fix in a minimal project.
@guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/c3d023c3a32096 …
> Make QuickGrid section "Display name support" use correct way to determine display name

- aspnetcore/blazor/globalization-localization.md
@guardrex Probably there's a more concise and/or nicer way to express this in the docs, but I found it confusing to read
> Not supported: [...] Data Annotations localization [...]
despite code like this
```csharp
[Required(ErrorMessageResourceName = nameof(Resources.Strings.RequiredAttribute_ValidationError), ErrorMessageResourceType = typeof(Resources.Strings))]
[Display(Name = "Street", ResourceType = typeof(Resources.ViewModels.BaseAddressViewModel))]
public string? Street { get; set; }
```
works great with
```razor
<EditForm Model="Model" OnValidSubmit="HandleSubmit">
<DataAnnotationsValidator />
<ValidationSummary />
...
</EditForm>
```
and e.g. [`UseRequestLocalization`](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-9.0#server-side-lo …
> Draft: Update Blazor supported localization scenarios

- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/BackgroundTasksSample.csproj
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Program.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/README.md
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/BackgroundTaskQueue.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/ConsumeScopedServiceHostedService.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/MonitorLoop.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/QueuedHostedService.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/ScopedProcessingService.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/Services/TimedHostedService.cs
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/appsettings.Development.json
- aspnetcore/fundamentals/host/hosted-services/samples/8.0/BackgroundTasksSample/appsettings.json
Update Hosted Service Sample to .net8.0
> Update Hosted Service Sample to .net8.0

- aspnetcore/blazor/security/gdpr.md
- aspnetcore/security/gdpr.md
- aspnetcore/toc.yml
Fixes #34494
cc: @tdykstra ... **UPDATED**: I made the Blazor article >=6.0 (because it relies on collocated JS). The PR adds a line to the main doc set's article referencing the new Blazor article. This also updates the link to Microsoft's Trust Center page on GDPR ... the 🧀 moved on the link. I also added a link to the EU page in *Additional resources* to make the bullet list two items.
---
|:--|:--|
| [aspnetcore/blazor/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/d93fcfedca6e9d0ffe45f115ff0021965f113fa7/aspnetcore/blazor/security/gdpr.md) | [aspnetcore/blazor/security/gdpr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/gdpr?branch=pr-en-us-34499) |
| [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore …
> Blazor GDPR article

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #34461
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/68ec26461a847fa96243bd6b8f2a73716b15fe22/aspnetcore/blazor/host-and-deploy/webassembly.md) | [aspnetcore/blazor/host-and-deploy/webassembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-34493) |
> Update GitHub Pages guidance

- aspnetcore/blazor/blazor-ef-core.md
- aspnetcore/blazor/fundamentals/index.md
Fixes #34478
I'll drop the sample from the Blazor Samples repo on https://github.com/dotnet/blazor-samples/pull/441 after this merges.
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/3e25aa8ab8a75a168c72935ced0d611279a80a09/aspnetcore/blazor/blazor-ef-core.md) | [aspnetcore/blazor/blazor-ef-core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-34482) |
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3e25aa8ab8a75a168c72935ced0d611279a80a09/aspnetcore/blazor/fundamentals/index.md) | [aspnetcore/blazor/fundamentals/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/index?branch=pr-en-us-34482) |
> Drop sample from EF Core-Blazor article

- aspnetcore/fundamentals/index.md
From my understanding, only the lines of code containing `Use{Feature}` method should be highlighted, so that's what I fixed.
Fixes #34516
---
|:--|:--|
| [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c8390ab37bfcaff8467ed6ba4e4366ad0de6c5c0/aspnetcore/fundamentals/index.md) | [ASP.NET Core fundamentals overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/index?branch=pr-en-us-34506) |
> Fix inaccurate code snippet highlighting

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/d39720338f23ccbc305e4893426e07e40c4ec229/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [aspnetcore/security/authentication/configure-jwt-bearer-authentication](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-34522) |
> Add small fixes to JWT Bearer authentication page

- aspnetcore/fundamentals/dependency-injection.md
This line appears to have been included by accident and should be removed.
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/1afcfc39ea453c2f9e698552ecda12404b96946b/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-34527) |
> Remove an unintended file path

- aspnetcore/mvc/models/file-uploads.md
Fixes #34309 
---
|:--|:--|
| [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/168b4948514781fd76185abad18ba7b692c26d76/aspnetcore/mvc/models/file-uploads.md) | [Upload files in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?branch=pr-en-us-34491) |
> Update info about limit on number of temp file names

- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Fixes #34371
@hakenr ... This generalizes the reason ('the tag can't be updated dynamically') to just a recommendation not to place the tag and specifies the condition (static SSR w/o enhanced nav). I feel good about this update. How do you feel about it?
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/location-of-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/f5f419e699c4fabd8fe5499a69698381a86d2669/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md) | [aspnetcore/blazor/javascript-interoperability/location-of-javascript](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?branch=pr-en-us-34528) |
> Enhance location of `<script>` tags coverage

- aspnetcore/security/authentication/social/google-logins.md
using https://developers.google.com/identity/sign-in/web/sign-in old link lead me for wrong integration 
for that I search  for new links and found  it
for that I Contribute to help others to try this approach 
This is my fist Contribution in open source ,I hope I do great.
Fixes #33815
---
|:--|:--|
| [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/1568d6fc2694765c6bb26681c3c0724b121f6860/aspnetcore/security/authentication/social/google-logins.md) | [aspnetcore/security/authentication/social/google-logins](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?branch=pr-en-us-33710) |
> Update google-logins.md by using Google.Apis.Auth.AspNetCore3 package

- aspnetcore/tutorials/first-mongo-app.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app8.md
Fixes #34317
This PR "archives" the current docs in a new v8 page (copy-paste), and updates the current docs for ASP.NET 9.
Because Minimal API's have become the default, I updated the setup steps to use the controller-based API (similar to https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-9.0&tabs=visual-studio-code). 
It also removes the MAC setup for v9 because it isn't supported anymore and I noticed other docs also removed it.
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/2981ee78be96b348d934f6bf8a1ebc2e3b655c8b/aspnetcore/tutorials/first-mongo-app.md) | [Create a web API with ASP.NET Core and MongoDB](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials …
> update MongoDB controller based API tutorial to v9

- aspnetcore/tutorials/first-mvc-app/search.md
Fixes #34567
This line:
`![Network and Payload tabs of Chrome browser Developer Tools showing form data](~/tutorials/first-mvc-app/search/_static/9/f12_general90.png)`
should point to a different image that was already available:
`![Network and Payload tabs of Chrome browser Developer Tools showing form data](~/tutorials/first-mvc-app/search/_static/9/f12_form90.png)`
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/883273906f9ed35729495be0935fb635cf4da926/aspnetcore/tutorials/first-mvc-app/search.md) | [aspnetcore/tutorials/first-mvc-app/search](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?branch=pr-en-us-34569) |
> FirstMVC: Correct f12 image for search.md

- aspnetcore/security/anti-request-forgery.md
- aspnetcore/security/anti-request-forgery/samples_snapshot/vulnerable-form.html
Fixes #34565
Fixes #34557
---
|:--|:--|
| [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/8b74cf3c922f0cba4a64ac1b5b8e65043ea34a53/aspnetcore/security/anti-request-forgery.md) | [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?branch=pr-en-us-34568) |
> Update examples in anti-request-forgery documentation to use a consistent domain format

- aspnetcore/security/authorization/roles.md
Fixes #34525
Updates the description to match the example.
I also noticed the description was wrong for `< 6` versions.
---
|:--|:--|
| [aspnetcore/security/authorization/roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/a5845bc802976f20174b46326c488e4fa55552ad/aspnetcore/security/authorization/roles.md) | [Role-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?branch=pr-en-us-34533) |
> fix role access descriptions in authorization documentation

- aspnetcore/blazor/components/index.md
Fixes #34564
Thanks, @nicholasyin! 🚀 ... Hopefully, this will clarify the points. Whether or not you prefix for nonliterals is up to the dev. Per management's decision, we'll stick with the current approach and only prefix when necessary. The text and example updates here should help with these points. I've included an example now where there's a nonliteral (a count in `Count`) that doesn't receive a prefix (`Count="count"`), and there's new text to explain what's going on.
This goes along with sample app updates on https://github.com/dotnet/blazor-samples/pull/461.
You can see the new components for the examples here ...
* https://github.com/dotnet/blazor-samples/blob/main/9.0/BlazorSample_BlazorWebApp/Components/ParameterChild.razor
* …
> Clarification on using the `@` prefix

- aspnetcore/blazor/security/account-confirmation-and-password-recovery.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/account-confirmation-and-password-recovery.md
Fixes #34582
---
|:--|:--|
| [aspnetcore/blazor/security/account-confirmation-and-password-recovery.md](https://github.com/dotnet/AspNetCore.Docs/blob/7d8f4af430bb74dc4db9ccabbe21c36b6efbfb64/aspnetcore/blazor/security/account-confirmation-and-password-recovery.md) | [aspnetcore/blazor/security/account-confirmation-and-password-recovery](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/account-confirmation-and-password-recovery?branch=pr-en-us-34583) |
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/7d8f4af430bb74dc4db9ccabbe21c36b6efbfb64/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.co …
> Add AKV approach

- aspnetcore/tutorials/min-web-api.md
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/608df044b6d8ba852340caaa9d80efae7c28745f/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-34591) |
> Typo fix in min-web-api.md

- aspnetcore/blazor/components/index.md
Addresses #34564
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/303c92fd5ae1f08675d03398272d30ecce20eabd/aspnetcore/blazor/components/index.md) | [aspnetcore/blazor/components/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-34593) |
> Component name changes

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Fixes #34508
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/c73bb059531ba49dc75718c6a8aa31c61b38d2f5/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-34509) |
> Replace file destination instructions for OpenAPI build-time documentation so projects can build correctly 

- aspnetcore/includes/run-the-app9.0.md
- aspnetcore/tutorials/grpc/grpc-start.md
- aspnetcore/tutorials/grpc/grpc-start/includes/grpc-start8.md
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/GrpcGreeter.csproj
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/Program.cs
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/Protos/greet.proto
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/Services/GreeterService.cs
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/appsettings.Development.json
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeter/appsettings.json
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeterClient/GrpcGreeterClient.csproj
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeterClient/Program.cs
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/GrpcGreeterClient/Protos/greet.proto
- aspnetcore/tutorials/grpc/grpc-start/sample/sample9/readme.md
Closes #34560
This PR:
- Moves the existing .NET 8 docs to its separate file
- Updates the current article to .NET 9
- Removes instructions for Mac
- Updates references to .NET 9
- Updates VS code terminal link to new link (the old one gets redirected to this one)
- Updates logs
- Adds .NET 9 sample
- Removes unused using
- The issue #34560 mentions removing `using GrpcGreeterClient`, but this is required 
---
|:--|:--|
| [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/cd474da29da2717efff1ac446aa53018b2f0ecc8/aspnetcore/tutorials/grpc/grpc-start.md) | [aspnetcore/tutorials/grpc/grpc-start](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?branch=pr-en-us-34603) |
| …
> update grpc-start to .NET 9

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
This is fixing a markdown issue, https://learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?view=aspnetcore-9.0#implementing-jwt-bearer-token-authentication
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/d263228ff1bd90baee1f417949f8bef5f7a207eb/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [Configure JWT bearer authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-34608) |
> fix markdown for configure-jwt-bearer-authentication page

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
The docs mentioned `SetDefaultPolicy ` so the code should match as well. https://learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?view=aspnetcore-9.0#forcing-the-bearer-authentication
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/830ead1b987aee50b99ec1f80be74742ef3a9e49/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [Configure JWT bearer authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-34609) |
> Update configure-jwt-bearer-authentication so that code matches docs

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/zone-pivot-groups.yml
Fixes #34605
cc: @ngboardway ... It's a fairly simple chop-job 🔪 on the "without BFF pattern Auto" pivot. I just cut out the bits about the client project and client-server behaviors here and make a few language changes from "Auto" to "Server" rendering and two projects to one project. Everything else remains the same. I think Stephen will review this today before he takes off OOF. If so, I'll merge it and merge it LIVE ⚡ immediately for quick appearance in the article today.
The sample apps that I put up last night to go with this are at ...
* https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidcServer
* https://github.com/dotnet/blazor-samples/tree/main/9.0/BlazorWebAppOidcServer
WRT a ***BFF pivot*** server sample and "Server" section, we'll consider it if devs ask. …
> Add pivot for Server-rendering sample

- aspnetcore/blazor/debug.md
- aspnetcore/blazor/tooling.md
- aspnetcore/blazor/tutorials/build-a-blazor-app.md
- aspnetcore/blazor/tutorials/movie-database-app/part-1.md
- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
- aspnetcore/blazor/tutorials/movie-database-app/part-3.md
- aspnetcore/blazor/tutorials/movie-database-app/part-4.md
- aspnetcore/blazor/tutorials/movie-database-app/part-5.md
- aspnetcore/blazor/tutorials/movie-database-app/part-6.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
- aspnetcore/fundamentals/host/generic-host.md
- aspnetcore/host-and-deploy/linux-nginx.md
- aspnetcore/host-and-deploy/linux-nginx/includes/linux-nginx5.md
- aspnetcore/tutorials/first-mvc-app/adding-controller.md
- aspnetcore/tutorials/first-mvc-app/adding-controller/includes/adding-controller7.md
- aspnetcore/tutorials/first-mvc-app/adding-controller/includes/adding-controller8.md
- aspnetcore/tutorials/first-mvc-app/adding-model.md
- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model7.md
- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model8.md
- aspnetcore/tutorials/razor-pages/model.md
- aspnetcore/tutorials/razor-pages/model/includes/model7.md
- aspnetcore/tutorials/razor-pages/model/includes/model8.md
- aspnetcore/tutorials/razor-pages/razor-pages-start.md
- aspnetcore/tutorials/razor-pages/razor-pages-start/includes/razor-pages-start7.md
- aspnetcore/tutorials/razor-pages/razor-pages-start/includes/razor-pages-start8.md
Fixes #34610 
Thanks @segeda! 🚀 
Tom ... @segeda reported that the macOS keyboard shortcuts in one (a few really) Blazor docs are incorrect. I confirmed here ... Ctrl+C kills an app on macOS in the command shell. Further, Ctrl+F5 starts an app without the debugger in VSC.
For the *Generic Host* article, I left Windows and macOS as separate shortcuts in spite of them being the same because the Windows entries (or the sentence) mention "SIGTERM/SIGINT." Let me know if you prefer removing the "SIGTERM/SIGINT" language, leaving just Ctrl+C for all CLI coverage. 👂 
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/aecdf328fc0ec4d3f11dcc3bd75bb751ca01869e …
> Update macOS keyboard shortcuts

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #34618
Brennan ... Your original remarks on this :point_right: https://github.com/dotnet/aspnetcore/issues/25000#issuecomment-1877615925
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/7ea311b2f425f4fcb659a01f0408419d36146119/aspnetcore/blazor/fundamentals/signalr.md) | [aspnetcore/blazor/fundamentals/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-34621) |
> Impersonation for Windows Authentication

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Closes #34510
As the issue points out the section about Native AOT is also showing on `< aspnetcore-9.0` pages (at the top of the page).
This PR moves the section within the `>= aspnetcore-9.0` moniker range, as it was [released in v9.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#microsoftaspnetcoreopenapi-supports-trimming-and-native-aot)
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/218aa5ed593eb83eda42fffbead4e7fc68e7a0c4/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-34613) |
> include AOT support in v9 moniker

- aspnetcore/test/http-files.md
Fixes #34607
Fixes #33729 
Fixes #32668 
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/770007e92a7d375ea171bc0f3609c3fe275d07ca/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-34617) |
> Document request variables in .http files

- aspnetcore/tutorials/razor-pages/new-field.md
Fixes #34643
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/a39e4baf79b2ebf6d534281aa1e3c48aa1047020/aspnetcore/tutorials/razor-pages/new-field.md) | [aspnetcore/tutorials/razor-pages/new-field](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?branch=pr-en-us-34646) |
> Typo fix: Update new-field.md

- aspnetcore/test/http-files.md
Under Request variables heading, the example given is `# @name login` but under Example request variable usage heading is `#@name login` which doesn't have space between `#` and `@name` and it doesn't work in Visual Studio. It may confuse readers who jump directly to the Example request variable usage heading.
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/1698dc10b9b02dac6d51c5ba863eac25d6985342/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-34670) |
> Fix request variables section typo

- aspnetcore/fundamentals/minimal-apis.md
- aspnetcore/fundamentals/minimal-apis/9.0-samples/Snippets/Program.cs
- aspnetcore/fundamentals/minimal-apis/responses.md
Fixes #34471 
- Adds an example on how to modify headers to quick reference and create response pages
- Adds example on Problem details in the create response page, which was added in v9 https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#problem-and-validationproblem-result-types-support-construction-with-ienumerablekeyvaluepairstring-object-values
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/881e4de1598b39d1d7b38fc2eaa38c61d495b056/aspnetcore/fundamentals/minimal-apis.md) | [aspnetcore/fundamentals/minimal-apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-34666) |
| …
> add example to modify headers in Minimal APIs

- aspnetcore/performance/caching/hybrid.md
Additional clarifications on cache key usage, requested via internal API review
/cc @tdykstra in particular; is this reasonable and welcomed?
Fixes #34647
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/706798ef946e6f2159c868a438f5debccac0d831/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-34644) |
> HybridCache - additional guidance on cache key composition

- aspnetcore/blazor/components/quickgrid.md
Fixes #34658
@danroth27 ... The PU PR looks like it has a NIT 😈. The record there is ...
```csharp
record Person(int PersonId, string firstName, string lastName, DateOnly BirthDate);
```
Cross-ref: https://github.com/dotnet/aspnetcore/pull/59901/files
... and the [C# record guidance](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record) never does that given that these are properties, thus they should be Pascal case, which I'm going to do on this PR for the doc example.
Do you want me to open a PU issue to update the `SampleQuickGridComponent` component?
**UPDATE (2/11)**: I'm going to go ahead with this. Let me know if you have a change request. 👂 It will be added to the *What's New* article on a separate PR shortly.
--- …
> QuickGrid RowClass parameter

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #34701
Addresses #34622
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e40c9cc6f94ef8a6dd4d219721d0c15bf2650f5/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34706) |
> Blazor Preview 1 WN content

- aspnetcore/fundamentals/servers/yarp/extensibility.md
Fixes  #34713
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/a1b77b5ef77f4ef3e4e7931a565660cee1b5fee9/aspnetcore/fundamentals/servers/yarp/extensibility.md) | [Overview of YARP extensibility](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/extensibility?branch=pr-en-us-34711) |
> Fix duplicate alt text in yarp extensibility article

- aspnetcore/blazor/security/index.md
`@inject` and `[Inject]` are no longer the only options - we now have constructor injection as well.  
To avoid listing all injection possibilities (and having to distinguish them across different .NET versions), I simplified the text.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/637436af08785ba1d137682833a240085c7cf105/aspnetcore/blazor/security/index.md) | [aspnetcore/blazor/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-34747) |
> [Blazor] Security - service injection

- aspnetcore/fundamentals/servers/yarp/direct-forwarding.md
The CustomTransformer class is included twice in the example, once as an internal and once as a private class.  The corresponding sample project only has the internal, and I therefor propose to remove the private class definition
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/direct-forwarding.md](https://github.com/dotnet/AspNetCore.Docs/blob/b15de89dbb33f63608ea50d5679684c1c098b4a3/aspnetcore/fundamentals/servers/yarp/direct-forwarding.md) | [YARP Direct Forwarding](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/direct-forwarding?branch=pr-en-us-34751) |
> Remove semi-duplicated code-block from YARP documentation

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/security/includes/hosted-blazor-webassembly-notice.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles-net-5-to-7.md
- aspnetcore/blazor/tooling.md
Fixes #34742
Thanks @sussexrick! 🚀 ... and I've added a tracking item to take a closer look at content organization for securely calling a web API. In the meantime, see the links that I placed on the issue, especially the *Additional scenarios* article for WASM in the *Security and Identity* node. What I might end up doing is adding security coverage on the basics of calling a web API securely to the *Call web API* article and either cross-link to relevant existing samples and/or update one or more of the existing samples for that article to include security.
Pinging Dan to see if the INCLUDE language is what we'd like to say about hosted WASM at this point. This INCLUDE is only for the four relevant security articles that either completely focus on hosted WASM (three of them) or have …
> Hosted WASM notice for security articles

- aspnetcore/test/integration-tests.md
- aspnetcore/test/integration-tests/includes/integration-tests8.md
Fixes #34584
- first commit archives the v8 docs, and sets the moniker to v8
- second commits updates the v9 docs to use the v9 sample, the surrounding text looked fine to me so I didn't have to update it.
---
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/38a3df23db2818af5acd046f423fa9bb2045ef63/aspnetcore/test/integration-tests.md) | [Integration tests in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-34712) |
> upgrade integration tests to .NET 9

- aspnetcore/fundamentals/servers/yarp/yarp-overview.md
- aspnetcore/toc.yml
YARP doesn't have an overview page that can be linked from the website being created. AI did a good first draft of what the page should contain.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/yarp-overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/d2537b4f3e3734f4c7dc476e9663b8300be8edc6/aspnetcore/fundamentals/servers/yarp/yarp-overview.md) | [aspnetcore/fundamentals/servers/yarp/yarp-overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/yarp-overview?branch=pr-en-us-34764) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/d2537b4f3e3734f4c7dc476e9663b8300be8edc6/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34764) |
>  YARP overview page

- aspnetcore/security/authentication/social/index.md
The title of "Facebook and Google authentication in ASP.NET Core" is particularly bad considering this is the overview for using Identity any external login provider. And while this is already under "ASP.NET Core Identity" in the TOC, I still think it's worth calling out this is demonstrating external login with "Identity" in the title, because it is possible to use external login without identity as demonstrated in https://learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-oidc-web-authentication?view=aspnetcore-9.0.
---
|:--|:--|
| [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/56e4d220e36a5c82645cb08575ac1844a2d3fa2a/aspnetcore/security/authentication/social/index.md) | …
> Improve title for overview of Identity external login

- aspnetcore/tutorials/first-mvc-app/adding-model.md
Fixes #32720
Clarified the command window is opened in the project directory.   The last time we said to do that was in a previous tutorial in this series. By the time folks got to this step they were accidentally moving from that directory before running the EF install commands.
I am not adding this to the Add NuGet Packages include instead since in some tutorials we just get through instructing to navigate to the project directory in previous steps.
Go right to the section edited section for internal review: https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-9.0&branch=pr-en-us-34777&tabs=visual-studio-code#add-nuget-packages
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://gith …
> First MVC: Ensure command run at project directory for VSC

- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #34789
Addresses #34729
We don't need to call this incremental behavioral improvement out in the articles because we never commented on it in detail in the first place. All we've ever said about the scroll position is that (emphasis added) ...
> Blazor's enhanced navigation and form handling avoid the need for a full-page reload and preserves more of the page state, so pages load faster, *usually without losing the user's scroll position on the page*.
... and never remarked on it at all for `NavigateTo` coverage in the *Routing* article ... or anywhere else for that matter.
Therefore, we only need to mention this in the *What's New* article.
This will remain commented out until Preview 2 releases.
> `NavigateTo` no longer scrolls to the top

- aspnetcore/migration/inc/samples/wrapped/Program.cs
WrapAspNetCoreSession was changed to AddWrappedAspNetCoreSession in version 1.3.0 of SystemWebAdapters Pull Request: https://github.com/dotnet/systemweb-adapters/pull/424 1.3.0 Version Notes: https://github.com/dotnet/systemweb-adapters/releases/tag/v1.3.0
> Fix sample file for WrapAspNetCoreSession

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Addresses #34775
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/bad5c3df889d5401142d3df7f1e24566ec335dee/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34799) |
> Patch Blazor movie dB .NET CLI guidance

- aspnetcore/migration/inc/samples/wrapped/Program.cs
- aspnetcore/migration/inc/wrapped.md
Fixes #34794
---
|:--|:--|
| [aspnetcore/migration/inc/wrapped.md](https://github.com/dotnet/AspNetCore.Docs/blob/d93a57ea130e2eab763692813c1a5808e2053434/aspnetcore/migration/inc/wrapped.md) | [aspnetcore/migration/inc/wrapped](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/wrapped?branch=pr-en-us-34795) |
> AddWrappedAspNetCoreSession

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/state-management.md
Fixes #34236
Thanks @hakenr! 🎷 ... This is probably a bit rough in spots. If you have time to look, I'll address your feedback before pinging a PU engineer. If you're busy, no worries ... I'll get one of them on here early next week to put an 👁️ on this.
**UPDATE (Monday, 2/24)**: I pinged to ask if either Illona or Ondrej are available to take a look. If they're busy, I'll hit up either Pavel or Marek to look.
* Add a `CascadingValueSource<T>` with notifications (`INotifyPropertyChanged`/`NotifyChangedAsync`) approach to the *Cascading values and parameters* article. The basis for the example is code provided by @kzu on https://github.com/dotnet/aspnetcore/issues/53257 (***Thanks @kzu!*** 🎸) . Sanderson said it's supported at https://github.com/dotnet/aspnetcore/issues/53257#issuecomment- …
> Cascading values+params for state management

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #34807
Thanks @mtscreator! 🚀 ... This strategically-placed troubleshooting remark might have saved you, and I hope it helps prevent this from happening in the future.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf103d510268e87263692fa6769a68bb1fc74e53/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34810) |
> Add scaffolding troubleshooting remark

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Addresses #34775
Let's see if this looks better. I think with a minor update to this approach at 10.0 to remove the remark about .NET 10's release (and to update the link so that it just points to the downloads page at https://dotnet.microsoft.com/download), this is a better way to handle a tooling breaking change that will be patched for 10.0. ***Maybe!*** 🤔 ... best to sleep on it for sure 🛌💤.
cc: @Rick-Anderson @tdykstra ... Discussed further with Wade offline. I'm looking at a different approach here for this because this really is a temporary tooling (SDK) problem.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/5a97559abdeffc48dc2d1e4c1e0f918d90286721/aspnetcore/blazor/tutorials/movi …
> Update EF Core tooling breaking change

- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
I think the current sample is overloaded with placeholders, making it hard to read and deviating from the usual way we describe features in the docs (by example).
> [Blazor] What's new .NET10 - QuickGrid.RowClass sample adjustment

- aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md
Fixes #34188
Thanks @dipique! 🚀 ... I'm adding context to the first line of the article, including a cross-link for "Razor components" to the Razor components *Overview* article and a link to the Blazor landing page of the doc set. That should clarify things:
* Razor components are for Blazor.
* The *Overview* article describes the relationship between Razor components and other "Razor"-named things in .NET.
Thanks for the issue. This should help folks who land in the doc set from Internet search.
---
|:--|:--|
| [aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/122dbe7b4fa7953a398005110d6e753db4b5be62/aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md) | …
> Add context to introductory remarks

- aspnetcore/blazor/forms/index.md
Related: <https://github.com/dotnet/aspnetcore/issues/50994>
I was about to open an issue about this because I thought it was a bug before I found <https://github.com/dotnet/aspnetcore/issues/50994> and then thought it might be worth to mention this in the docs.
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/dd4f8cc255314a9bd87710665b90b924fafec4bc/aspnetcore/blazor/forms/index.md) | [aspnetcore/blazor/forms/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-34828) |
> Updates inside `OnInitializedAsync` not streamed for POSTs

- aspnetcore/fundamentals/configuration/index.md
Fixes #34824
cc: @JamesNK ... Tom is OOF, so I'll handle this one.
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/69b199c6aae03df534bee3656c8a2895e69e33e4/aspnetcore/fundamentals/configuration/index.md) | [aspnetcore/fundamentals/configuration/index](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-34825) |
> Silencing JSON comment errors

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
@thygesteffensen I brought your commit from #34755 here so when I S&M you'll get credit.
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/34803
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a91a89033e7909281e3a20125c76be066fa0998/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-34808) |
> Rick andy/open api/m2-2

- aspnetcore/migration/web_forms.md
Remove step for upgrading individual components that isn't supported. Clarify that migration from Web Forms isn't necessarily to MVC. Actually, a more likely migration target is Blazor.
---
|:--|:--|
| [aspnetcore/migration/web_forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/d87f7bf04baaabc9a748df8b86ca19e05d794cd8/aspnetcore/migration/web_forms.md) | [aspnetcore/migration/web_forms](https://review.learn.microsoft.com/en-us/aspnet/core/migration/web_forms?branch=pr-en-us-34853) |
> Update Web Forms incremental migration steps

- aspnetcore/fundamentals/servers/kestrel/endpoints.md
- aspnetcore/fundamentals/servers/kestrel/endpoints/samples/KestrelNamedEP/Program.cs
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/33455
**Internal review URL -->**  [Customize Kestrel named pipe endpoints](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-9.0&branch=pr-en-us-34640#customize-kestrel-named-pipe-endpoints)
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/f2548e806d656b6897f00b069d2f31814e15237d/aspnetcore/fundamentals/servers/kestrel/endpoints.md) | [aspnetcore/fundamentals/servers/kestrel/endpoints](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?branch=pr-en-us-34640) |
> Kestrel named pipes /n/1

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #34303
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/55d406f99347a6a47deb49033e5a5dca4ed27fba/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34892) |
> Update debugger break on `NavigateTo` guidance

- aspnetcore/blazor/components/quickgrid.md
Addresses #34881
Thanks @MagistratasHK! 🚀 ...
Cross-references:
* https://github.com/dotnet/aspnetcore/issues/60721
* https://github.com/dotnet/aspnetcore/issues/58716
I'm going to add a section to the QuickGrid article, and I'm even going to provide the full-blown replacement component for the `Index` component in the tutorial as the example here. That makes it easy to understand the before-and-after changes required. As Javier remarked, "[this] is not trivial." 😆 
I won't take the extreme measure of changing the entire component in the tutorial because the simpler component, prone to the error, is scaffolded into to the app. There's also a good chance that the original code won't change. I suspect that they'll fix the problem inside the items provider. That will make my work easy here …
> Multiple concurrent queries `InvalidOperationException`

- .github/workflows/quest-bulk.yml
Run Sequester monthly to catch all open issues that are still open. This will move them to the latest planned sprint, or the "backlog" sprint.
---
|:--|:--|
| [.github/workflows/quest-bulk.yml](https://github.com/dotnet/AspNetCore.Docs/blob/646d4e31136a9d2ef557b5255028654c77ca7966/.github/workflows/quest-bulk.yml) | [.github/workflows/quest-bulk](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/quest-bulk?branch=pr-en-us-34911) |
> Add monthly cron job

- aspnetcore/blazor/host-and-deploy/webassembly.md
Hey! 
Noticed a minor typo while reading the blazor wasm docs 😄 
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/43bb5d0d73daba62e53dc50c63193e3f1ac0900f/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-34910) |
> fix: ngnix -> nginx typo

- aspnetcore/performance/rate-limit.md
Fixes #34442
I think a short mention of it can already help, otherwise the docs structure needs to be changed to incorporate this note imho.
---
|:--|:--|
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/38f3cd19b179dfc29c91795e6868f9d7c434d98d/aspnetcore/performance/rate-limit.md) | [Rate limiting middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?branch=pr-en-us-34897) |
> mention queue limit can be set to 0

- aspnetcore/host-and-deploy/iis/advanced.md
Updating docs to indicate correct values and format.
This is doc bug in relationship to this issue in aspnetcore
https://github.com/dotnet/aspnetcore/issues/60762#issuecomment-2702460280
Contributes to #34922
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/2134975fc6bf8f536908237e5d282e5187fa5440/aspnetcore/host-and-deploy/iis/advanced.md) | [Advanced configuration of the ASP.NET Core Module and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-34920) |
> Documentation Provides Incorrect Values For Default Stack Size

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #34813
* I'm versioning all of the 10.0 or later content into one moniker range, and I'm disabling all of the existing content for <10.0. In the past, I broke up coverage into multiple moniker ranges because parts of the coverage changed (e.g., filenames, file locations).
* I'm using our standard approach for cross-linking reference source. I link the `main` branch, and I include the [guidance on selecting the correct release branch/tag](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/aspnetcore-repo-ref-source-links.md).
* Are the existing images still accurate? ***If not,*** I'll make a tracking note to snap and place new shots on Preview 2 release day because I'm not on nightly releases (*yet* anyway 😄).
* …
> Reconnect UI component

- aspnetcore/blazor/security/includes/troubleshoot-server.md
- aspnetcore/blazor/security/includes/troubleshoot-wasm.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/index.md
- aspnetcore/introduction-to-aspnet-core.md
- aspnetcore/security/authentication/2fa.md
Fixes #34945
In spite of the link loading their page, this will patch the ASPSMS link to get it out of our build reports ...
```diff
- [ASPSMS](https://www.aspsms.com/asp.net/identity/core/testcredits/)
+ ASPSMS (`https://www.aspsms.com/asp.net/identity/core/testcredits/`)
```
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdbf9cb8e963ff1cf6c8e9a372207bda1f714088/aspnetcore/blazor/security/webassembly/standalone-with-identity/index.md) | [aspnetcore/blazor/security/webassembly/standalone-with-identity/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity/index?branch=pr-en-us-34946) |
| …
> Patch broken links

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
I have also removed the `--preview` flag as it seems unnecessary. It's not necessary to add a preview package to get OpenAPI to be AOT compatible in .NET 9.
Fixes #34756
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/b3d952d12a585714fb67cfaa9f7808d555a3fbac/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Generate OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-34757) |
> Do not show unnecessary steps for creating AOT-compatible OpenAPI application when running in .NET 10

- aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor-hybrid.md
- aspnetcore/toc.yml
Fixes #34939
*Look'in good thus far!* 👍
* Draft particulars for this article ...
* **Title:** .NET MAUI Blazor Hybrid with a Blazor Web App and ASP.NET Core Identity
* **Description:** Learn about the .NET MAUI Blazor Hybrid with a Blazor Web App that manages authentication with ASP.NET Core Identity sample app.
* **UID:** `blazor/hybrid/security/maui-blazor-web-identity`
* **Path:** `\aspnetcore\blazor\hybrid\security\maui-blazor-web-identity.md`
* **URL:** `/blazor/hybrid/security/maui-blazor-web-identity`
* Looks like path lengths are starting to become a problem for these apps. I started by naming the projects `MauiBlazorWebIdentity` to match other sample app naming, but that 💥 in my face on generated path lengths when compiling the solution. Therefore, I merely placed the sample app …
> MAUI BH+BWA+Identity article

- aspnetcore/tutorials/min-web-api.md
Also address a few more minor things in the article:
- MD040 - Fenced code blocks should have a language specified
- Make the casing of HTTP verbs consistent with the text
Fixes: #34956
---
|:--|:--|
| [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/32909165c91ca595f2e031c8122d8633a2de5dcd/aspnetcore/tutorials/min-web-api.md) | [Tutorial: Create a minimal API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?branch=pr-en-us-34959) |
> Fix First Min Web API: missing ID in request body

- aspnetcore/blazor/components/layouts.md
Fixes #34957
Thanks @TanvirArjel! 🚀 ... Sorry for the ***very late*** coverage (https://github.com/dotnet/aspnetcore/issues/35068), but I didn't hear about this until @Rob-Houweling brought it up again a couple of days ago on https://github.com/dotnet/aspnetcore/issues/60912 and Javier pinged me.
We have a WARNING note in the coverage that touches on this recursion problem as it pertains to not applying a layout in the top-level `_Imports.razor` file because that file is applied to the app's default (and other) layouts. I'm extending that WARNING to say not to put layouts in the same folder as an `_Imports.razor` file applying one ... or else one gets the same ***loop of death*** 💀 recursion problem.
They might take this problem on as a fix in the framework for .NET 10. If not, it will …
> Layouts self-reference recursion

- aspnetcore/blazor/components/layouts.md
Addresses #34957
cc: @TanvirArjel @Rob-Houweling ... I'm going to update that text because it's too focused on the layout being ***in the same folder***. Actually, it can't be in the folder hierarchy of the `_Imports` file either. This new text is better. 👍 
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/b00af02d2809f93fbcce1f803aebdd6182be3aac/aspnetcore/blazor/components/layouts.md) | [aspnetcore/blazor/components/layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-34976) |
> Update remarks on layout recursion

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Addresses #34729
Fixes #34965
Fixes #34963
There's no reason to cross-link the feature coverage in the QuickGrid article because the reader wouldn't find more information there unless we add additional content.
WRT opt-out on the qs/framework matching behavior. Specifically, I assume that ...
```xml
AppContext.SetSwitch(
"Microsoft.AspNetCore.Components.Routing.NavLink.DisableMatchAllIgnoresLeftUriPart", true);
```
... goes into the `Program` file for app devs. Lib devs will follow the AppContext article. Do you want to show that exact line, or should we leave the text as it reads now?
***RESOLVED!*** ... ~Also, isn't the new behavior to ignore the ***right part*** of the URI (qs/fragment), and I also wonder why it isn't referring to the qs/fragment specifically?~
```xml …
```
> Blazor Pre2 release note additions

- aspnetcore/release-notes/aspnetcore-10/includes/OpenApiNetV2Prev7.md
Prep for moving the following What's new section from the issue to an include:
_Upgrade to OpenAPI.NET v2.0.0-preview7_
Leaving it as was provided in the issue comments, so that the PR on it that follows will allow reviewers to see any changes made.
Include is not added to the What's New doc in this prep step.
> Prep: WN 10 Prev 2 OpenAPI.NET include

- aspnetcore/release-notes/aspnetcore-10/includes/OpenApiPopulateXMLDocComments.md
For What's New .NET 10 Prev 2, move Open API XML Doc Comments draft from issue #34729 to an Include and do an edit pass.
> WN .NET 10 Prev 2: OpenAPI XML Doc Comments: Move to Include

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/MinApiEmptyStringInFormPost.md
Contributes to #34729
Moved section for Min API empty string in form post from issue to WN include and did an edit pass.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/456c67829d945935b0e5ed9bca510344d695f3f8/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34990) |
> WN update with include: Min Api empty string in form post

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/OpenApiPopulateXMLDocComments.md
Contributes to #34729 
Added remaining Open API link to include for PopulateXMLDocComments.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/e3a423d0e3b43094d495c525adf6981b5fa96f5b/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34991) |
> WN .NET 10 Prev 2: link to include for Open API

- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
cc: @wadepickett @Rick-Anderson ... This will only surface the Pre2 content in the INCLUDE. It won't get sucked into the release notes markdown file until the date (or something else) is changed in the release notes file.
> Surface Blazor Pre2 content in INCLUDE

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/index.md
Fixes #34586
Thanks @davisnw! 🚀 ... Your [product unit issue (`dotnet/aspnetcore` #60184)](https://github.com/dotnet/aspnetcore/issues/60184) will be reviewed by engineering for possible improvements to the framework in a future release. For the docs, I'm making the following updates:
* Cross-link existing sample apps that demo secure web API into the *Call web API* article.
* Add a section to the security node's *Overview* article on Auto render mode components/apps that adopt the two-service approach. Cross-link the new section in relevant locations.
I decided not to change the existing *Call web API* sample apps at this time. We have enough security examples that make secure web API calls, including WASM and server-based examples, to cover it. The problem was just that most of the …
> Secure data with Interactive Auto rendering

- .github/policies/pullRequestManagement-labelFiles.yml
The Blazor Hybrid label was added to a PR at #34944. I don't need it, so I'm striking that section. The following section with its `'(?i).*/blazor/.*'` filter should also capture the Blazor Hybrid node (`*/blazor/hybrid/*`) and just apply my reviewer assignment.
Curious about something, too ...
Why doesn't ...
```yml
- not:
targetsBranch:
branch: live
```
... target the specific branch `main`? ...
```yml
- and:
targetsBranch:
branch: main
```
---
|:--|:--|
| [.github/policies/pullRequestManagement-labelFiles.yml](https://github.com/dotnet/AspNetCore.Docs/blob/5b63d6510cf3a89ff1169a0b112386946ec820bb/.github/policies/pullRequestManagement-labelFiles.yml) | [.github/policies/pullRequestManagement-labelFiles](https://review.learn.microsoft.com/en-us/aspnet/core/.gi …
> Drop Blazor Hybrid from the PR mgmt policy

- aspnetcore/blazor/components/lifecycle.md
Trying to make the sentence clear for everyday developers.
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4df6d8dd6f3c0a38a327987174754ddaaedd1b8/aspnetcore/blazor/components/lifecycle.md) | [aspnetcore/blazor/components/lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-35006) |
> [Blazor] Lifecycle - OnInitializedAsync - minor adjustment to improve readability

- aspnetcore/mvc/models/model-binding.md
Correct a word that I think the author meant differently.
---
|:--|:--|
| [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a25c560480a1d032b73be22c90fbc643bf7eee3/aspnetcore/mvc/models/model-binding.md) | [Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=pr-en-us-35031) |
> Correct typo

- aspnetcore/blazor/fundamentals/static-files.md
I'm not sure why `<ImportMap />` wouldn't apply to applications using global Interactive WebAssembly rendering. JS modules can still benefit from mapping `import`s to fingerprinted URLs.
Maybe you meant Blazor WebAssembly standalone apps, where there's no ASP.NET Core hosting with the MapStaticAssets middleware?
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/9efd0700ece6d185329ca268e570057dc78eaaa3/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-35034) |
> [Blazor] static-files.md - ImportMap also applies for global WASM render-mode

- aspnetcore/diagnostics/asp0026.md
- aspnetcore/diagnostics/asp0028.md
I am working on creating the docs for the analyzer ASP0027.
Whilst starting this I spotted the title contains two hashes in both ASP0026 and ASP0028 but none of the other analyzers.
This causes the tab in the web browser to display with these hashes, which looks a little weird when the other analyzers don't have this.
If this is intended for some reason we can close this off.
https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0026
https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0028
---
|:--|:--|
| [aspnetcore/diagnostics/asp0026.md](https://github.com/dotnet/AspNetCore.Docs/blob/ec1e2cea81f8fbb7e3f4f00c9dac34da9410f9db/aspnetcore/diagnostics/asp0026.md) | [ASP0026: `[Authorize]` is overridden by `[AllowAnonymous]` from "farther …
> Removed misplaced hashes in the title for two analyzers

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/index.md
- aspnetcore/zone-pivot-groups.yml
Fixes #34927
cc: @mihirpatelipsos ... I'm adding a pivot to the BWA+Entra article for the BFF pattern.
Sample app: https://github.com/dotnet/blazor-samples/tree/main/9.0/BlazorWebAppEntraBff
**UPDATE (3/20)**: Awaiting final offline discussion to conclude.
Immediately after this goes *LIVE*, update the sample repo `README.md` file with the sample entry and cross-link to the live article.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4d83aa15c490cf12d06ba83b5f9818ef4967573/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35012) |
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://githu …
> Add BFF pattern pivot

- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/blazor-web-app-with-windows-authentication.md
- aspnetcore/toc.yml
Fixes #34707
Notes
* Adds a WinAuth sample app article to the Blazor *Security and Identity* node.
* The sample app is at https://github.com/dotnet/blazor-samples/tree/main/9.0/BlazorWebAppWinAuthServer.
❓***QUESTION:***❓ We want to show claims and how to set a policy for a Win SID. Is there anything else that we need this sample app to show, or is this enough to get folks going?
Thanks @markat1 for requesting this sample and coverage.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/72621fdfe011b12ea17b7051997502aa1e8ae46b/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/bla …
> BWA with WinAuth article

- aspnetcore/signalr/client-features.md
- aspnetcore/signalr/supported-platforms.md
- aspnetcore/signalr/swift-client.md
- aspnetcore/toc.yml
Add document about the SignalR Swift client. The source code is: https://github.com/dotnet/signalr-client-swift
---
|:--|:--|
| [aspnetcore/signalr/client-features.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3d1d80660cbb3cfc8610ba6aee3f36461a26f8c/aspnetcore/signalr/client-features.md) | [ASP.NET Core SignalR clients](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/client-features?branch=pr-en-us-34866) |
| [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3d1d80660cbb3cfc8610ba6aee3f36461a26f8c/aspnetcore/signalr/supported-platforms.md) | [ASP.NET Core SignalR supported platforms](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?branch=pr-en-us-34866) |
| …
> Add docs about SignalR swift client

- aspnetcore/fundamentals/openapi/include-metadata.md
Fixes #35010
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/a7de0ca903766bac63e75ac8de3c865ff3193b52/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35011) |
> Add link to Web API analyzers

- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #34978
Addresses #34948
Not necessary to inform the .NET Core docs team on this because they didn't make specific reference to it. They only cross-linked our *Release Notes* article for it. 
Cross-ref: https://learn.microsoft.com/dotnet/core/whats-new/dotnet-10/overview#aspnet-core
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/1d49775a5d02774b8bc7eeb5ecae8f2b72ca00ec/aspnetcore/blazor/fundamentals/routing.md) | [aspnetcore/blazor/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-35056) |
> [Pre3] Rename DisableMatchAllIgnoresLeftUriPart

- aspnetcore/diagnostics/asp0027.md
I have recently written the ASP0027 documentation.
After reviewing the [documentation](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0027?view=aspnetcore-10.0) I spotted there was a misplaced quotation mark.
---
|:--|:--|
| [aspnetcore/diagnostics/asp0027.md](https://github.com/dotnet/AspNetCore.Docs/blob/6c1a5b4b7fdfbba1abc24862c87237cb127fb376/aspnetcore/diagnostics/asp0027.md) | [ASP0027: Unnecessary `public Program` class declaration](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0027?branch=pr-en-us-35066) |
> Remove misplaced quotation in ASP0027

- aspnetcore/diagnostics/code-analysis.md
I spotted we were missing the links in the [code analysis page](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?view=aspnetcore-10.0) for ASP0027 & ASP0028.
This change includes these links.
---
|:--|:--|
| [aspnetcore/diagnostics/code-analysis.md](https://github.com/dotnet/AspNetCore.Docs/blob/bbac5357f02841e086c3bc0ef0c2428c43b406b8/aspnetcore/diagnostics/code-analysis.md) | [Code analysis in ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?branch=pr-en-us-35087) |
> Added missing ASP links in code analysis page

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
Stagger the cron job entry for running sequester in each repo according to [this table](https://github.com/dotnet/docs-tools/tree/main/actions/sequester#staggering-times)
In addition, fix one token error in the manual run script
---
|:--|:--|
| [.github/workflows/quest-bulk.yml](https://github.com/dotnet/AspNetCore.Docs/blob/a33aa641509d44e929a305b7014b9f453bb90433/.github/workflows/quest-bulk.yml) | [.github/workflows/quest-bulk](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/quest-bulk?branch=pr-en-us-35117) |
| [.github/workflows/quest.yml](https://github.com/dotnet/AspNetCore.Docs/blob/a33aa641509d44e929a305b7014b9f453bb90433/.github/workflows/quest.yml) | [.github/workflows/quest](https://review.learn.microsoft.com/en-us/aspnet/core/ …
> Stagger the run time

- aspnetcore/security/authentication/configure-oidc-web-authentication.md
Simple typo fix of "informaiton".
---
|:--|:--|
| [aspnetcore/security/authentication/configure-oidc-web-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/e584a7c5006997c0bc497734191f02e8125e86ae/aspnetcore/security/authentication/configure-oidc-web-authentication.md) | [Configure OpenID Connect Web (UI) authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-oidc-web-authentication?branch=pr-en-us-35124) |
> Fix typo in OIDC documentation

- aspnetcore/fundamentals/servers/yarp/diagnosing-yarp-issues.md
- aspnetcore/fundamentals/servers/yarp/extensibility-transforms.md
- aspnetcore/fundamentals/servers/yarp/extensibility.md
- aspnetcore/fundamentals/servers/yarp/getting-started.md
- aspnetcore/fundamentals/servers/yarp/grpc.md
- aspnetcore/fundamentals/servers/yarp/header-guidelines.md
- aspnetcore/fundamentals/servers/yarp/httpsys-delegation.md
- aspnetcore/fundamentals/servers/yarp/kubernetes-ingress.md
- aspnetcore/fundamentals/servers/yarp/middleware.md
- aspnetcore/fundamentals/servers/yarp/service-fabric-int.md
- aspnetcore/fundamentals/servers/yarp/timeouts.md
- aspnetcore/fundamentals/servers/yarp/websockets.md
- aspnetcore/fundamentals/servers/yarp/yarp-overview.md
As per this https://github.com/dotnet/AspNetCore.Docs/pull/35095#issuecomment-2766124854
A pass through 
- Resolving some of the spelling mistakes 
- Rewording where it made sense
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/diagnosing-yarp-issues.md](https://github.com/dotnet/AspNetCore.Docs/blob/dde6e4e0c679e24c1f28dded33eadb8b57b114e9/aspnetcore/fundamentals/servers/yarp/diagnosing-yarp-issues.md) | [aspnetcore/fundamentals/servers/yarp/diagnosing-yarp-issues](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/diagnosing-yarp-issues?branch=pr-en-us-35127) |
| [aspnetcore/fundamentals/servers/yarp/extensibility-transforms.md](https://github.com/dotnet/ …
> Corrected some spelling/wording in YARP node

- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/rendering.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/security/data-protection/implementation/key-storage-providers.md
- aspnetcore/signalr/redis-backplane.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane2.1.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane2.2.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane3.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane5.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane6.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane7.md
Fixes #35111
Thanks @divvjson! 🚀 ... I'll leave this up overnight to give you a chance to compare notes with what you may have done based on Javier's advice and what I came up with. The scenario that you're working with on the DIFF is in the *Global Interactive WebAssembly rendering without prerendering* section.
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/f40c3b640838c1913e63373388797e585aca6a91/aspnetcore/blazor/components/lifecycle.md) | [aspnetcore/blazor/components/lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-35126) |
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/f40c3b640838c1913e633733 …
> Additional loading indicator scenarios

- aspnetcore/grpc/native-aot.md
Correct `dotnet new` command for creating an aot grpc app
---
|:--|:--|
| [aspnetcore/grpc/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/eef5255abc9cc1e410f3705b496f652ed4f7750a/aspnetcore/grpc/native-aot.md) | [aspnetcore/grpc/native-aot](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/native-aot?branch=pr-en-us-35153) |
> Correct `dotnet new` command for creating an aot grpc app

- aspnetcore/blazor/components/index.md
- aspnetcore/diagnostics/bl0001.md
- aspnetcore/diagnostics/bl0002.md
- aspnetcore/diagnostics/bl0003.md
- aspnetcore/diagnostics/bl0004.md
- aspnetcore/diagnostics/bl0005.md
- aspnetcore/diagnostics/bl0006.md
- aspnetcore/diagnostics/bl0007.md
- aspnetcore/diagnostics/code-analysis.md
- aspnetcore/toc.yml
Fixes #35159
Thanks @jfoshee! 🚀 ... I had time this morning to resolve this. I'm going to slant this in the direction that it isn't safe to suppress the warning. We guide devs in the Blazor docs not to write to component parameters directly with a setter. I'm including some improvements to that coverage as part of this PR, and you can see that part of the *Component parameters* section (and will say with the changes) on the diff. I'll leave this up for a few hours before merging to give you a chance to take a look at the new article.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/616df77ce25567d60747a1f42ead3f26031d6578/aspnetcore/blazor/components/index.md) | …
> Add coverage for analyzer violation BL0007

- aspnetcore/tutorials/first-mongo-app.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app3-5.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app6.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app7.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app8.md
Fixes #35134
Fixes #35133
Fixes #35131
Fixes invalid path
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b6ef1fc5fa1263cad7205a8c1928f2b35a8dda1/aspnetcore/tutorials/first-mongo-app.md) | [Create a web API with ASP.NET Core and MongoDB](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-35163) |
> corrections in First mongo app

- aspnetcore/blazor/components/built-in-components.md
- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/fundamentals/map-static-files.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #35023
Addresses #34948
Fixes #35075
Covering two Blazor WASM features now on this PR ...
* Fingerprinting
* `<WasmApplicationEnvironmentName>` to set the environment
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/517a64adb10bc8bc2435bbc8f0347fea10c7cbc2/aspnetcore/blazor/components/built-in-components.md) | [aspnetcore/blazor/components/built-in-components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-35057) |
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/517a64adb10bc8bc2435bbc8f0347fea10c7cbc2/aspnetcore/blazor/fundamentals/environments.md) | …
> [Pre3] Blazor WASM fingerprinting and environment property

- aspnetcore/blazor/forms/input-components.md
Fixes #35168
Thanks @Iamnvincible! 🚀 ... This makes it very clear that it's automatic.
---
|:--|:--|
| [aspnetcore/blazor/forms/input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/050c991a95cddf060ae0f01eee8494444b9fea08/aspnetcore/blazor/forms/input-components.md) | [aspnetcore/blazor/forms/input-components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/input-components?branch=pr-en-us-35171) |
> Clarify automatic addition of the `multiple` attr

- aspnetcore/release-notes/aspnetcore-10/includes/webapiaotTemplateAddedOpenAPI.md
Contributes to #34948 
Prep only.  Moving draft of _Add Microsoft.AspNetCore.OpenApi to the webapiaot template_ in issue discussion of #34948 to an include as is so it can be compared in the next PR that has its edit pass.
> Prep only: WN .NET10 Prev 3: webapiaot template adds OpenAPI

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/webapiaotTemplateAddedOpenAPI.md
Contributes to #34948
- Edit pass on draft of _Add OpenAPI to webapiaot_ section provided in the issue discussion of https://github.com/dotnet/AspNetCore.Docs/issues/34948
- Moved it to an include file.
- Added the include file to the What's New release topic.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/87a70646f3de092fc7f6a06f7658f11e90515b1b/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35192) |
> WN .NET 10 Prev3: Add OpenAPI to webapiaot

- aspnetcore/fundamentals/openapi/include-metadata.md
The "What's new in .NET 10" release notes mention the new Description property I added, but the .NET 10 OpenAPI docs do not.
This commit adds consistency.
I've added examples for `ProducesResponseType` and `ProducesDefaultResponseType` to Minimal API and Controller docs. I know a team member doesn't like `ProducesDefault` (@mikekistler, https://github.com/dotnet/aspnetcore/issues/58719#issuecomment-2501581203 ). 
I also know that another team member (@captainsafia , https://github.com/dotnet/aspnetcore/issues/58724#issuecomment-2645886861) would prefer developers to use the endpoint-specific OpenAPI transformers (Which will be released in a future preview) instead of setting the `Description` for Minimal API's, as they are more extensible.
Therefore, I'd like to discuss the following:
- …
> Add ProducesResponseType Description documentation

- aspnetcore/tutorials/first-mongo-app.md
- aspnetcore/tutorials/first-mongo-app/includes/first-mongo-app8.md
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/BookStoreApi.csproj
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Controllers/BooksController.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Controllers/WeatherForecastController.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Models/Book.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Models/BookStoreDatabaseSettings.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Program.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/Services/BooksService.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/WeatherForecast.cs
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/appsettings.Development.json
- aspnetcore/tutorials/first-mongo-app/samples/9.x/BookStoreApi/appsettings.json
- aspnetcore/tutorials/first-mongo-app/samples_snapshot/9.x/Book.cs
Fixes #35179
After the upgrade, the application can still be rendered via swagger and retrieve data:
---
|:--|:--|
| [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/b282bb896a96d2cfa7d9a09a227785af4cfa36dc/aspnetcore/tutorials/first-mongo-app.md) | [aspnetcore/tutorials/first-mongo-app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?branch=pr-en-us-35189) |
> Adds .NET 9 sample to mongo app

- aspnetcore/fundamentals/minimal-apis/10.0-samples/MinimalServerSentEvents/HeartRateRecord.cs
- aspnetcore/fundamentals/minimal-apis/10.0-samples/MinimalServerSentEvents/MinimalServerSentEvents.http
- aspnetcore/fundamentals/minimal-apis/10.0-samples/MinimalServerSentEvents/Program.cs
- aspnetcore/fundamentals/minimal-apis/responses.md
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/sse.md
- aspnetcore/web-api/action-return-types/samples/10/ControllerSSE/ControllerSSE.csproj
- aspnetcore/web-api/action-return-types/samples/10/ControllerSSE/ControllerSSE.http
- aspnetcore/web-api/action-return-types/samples/10/ControllerSSE/Controllers/HeartRateController.cs
- aspnetcore/web-api/action-return-types/samples/10/ControllerSSE/HearRate.cs
- aspnetcore/web-api/action-return-types/samples/10/ControllerSSE/Program.cs
Fixes #35089
[Support for Server-Sent Events (SSE)](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0&branch=pr-en-us-35152#support-for-server-sent-events-sse)
[Responses: Server-Sent Events (SSE)](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-10.0&branch=pr-en-us-35152#server-sent-events-sse)
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/1da8e86cb555f6c32c9acb615d958544c499688b/aspnetcore/fundamentals/minimal-apis/responses.md) | [aspnetcore/fundamentals/minimal-apis/responses](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-35 …
> SSE return types /2

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/ValidationSupportMinAPI.md
Per [this comment in #34948](https://github.com/dotnet/AspNetCore.Docs/issues/34948#issuecomment-2762871086)
Contributes to #34948 
- Edit pass on draft of Validation Support for Minimal API provided in the issue discussion of  #34948
- Adds Validation Support for Minimal API to an include file.
- Adds the include file to the What's New release topic.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/9dc3c7065095566f21a23284567b2a5bc8b88695/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35188) |
> WN .NET 10 Prev 3: Validation Support Minimal API

- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
... just in under the wire! 😅 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/7cfd90cdee7698db3e26aa1eee0ad45eeb9d4c21/aspnetcore/blazor/fundamentals/routing.md) | [aspnetcore/blazor/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-35201) |
> Patch Blazor Pre3 API

- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/host-and-deploy/webassembly/deployment-layout.md
- aspnetcore/blazor/host-and-deploy/webassembly/iis.md
- aspnetcore/blazor/host-and-deploy/webassembly/index.md
- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #35207
Fixes #35196
@maraf ... I confirmed that our guidance on changing DLL extensions when Webcil is disabled is broken 💥. Why it's broken is unclear beyond the runtime failing to start with a console error message to the effect `[MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:2718, condition '<disabled>' not met`.
On this PR, I'm versioning the guidance out for 8.0 or later, when Webcil took over. Unlike the troubleshoot integrity PowerShell script, I'm not going to open an issue to determine if we should devise new DLL extension change guidance. For one thing since the release of .NET 8, no issues have been opened on the docs repo or on the ASP.NET Core product unit repo asking about changing DLL file extensions or blocked Webcil (`.wasm`) files. Let me know if …
> DLL file extension change updates

- aspnetcore/fundamentals/servers/yarp/grpc.md
fixes links to grpc docs, was missing .md extension
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/grpc.md](https://github.com/dotnet/AspNetCore.Docs/blob/d204c821ff2a2e9baa6efaefab41d309afee121b/aspnetcore/fundamentals/servers/yarp/grpc.md) | [YARP Proxying gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/grpc?branch=pr-en-us-35211) |
> fixes links to grpc repo docs

- aspnetcore/blazor/host-and-deploy/configure-trimmer.md
It seems that the `TrimMode` property was mistakenly placed under `ItemGroup` which doesn't work correctly.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/configure-trimmer.md](https://github.com/dotnet/AspNetCore.Docs/blob/e6a2e830a6335b370a35da6ee37b360b8255535c/aspnetcore/blazor/host-and-deploy/configure-trimmer.md) | [Configure the Trimmer for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?branch=pr-en-us-35216) |
> move `TrimMode` configuration to `PropertyGroup`

- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
@mikekistler this was the easiest way to get a clean diff.
> Update OpenAPI document generation details

- aspnetcore/blazor/fundamentals/static-files.md
Fixes #35228
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca84a1e88861e0775d43380681ed3d7f19135ee6/aspnetcore/blazor/fundamentals/static-files.md) | [aspnetcore/blazor/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-35229) |
> Clarify `ImportMap` component sections

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #35219
@oroztocil ... *ready for review.* 🎉 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/a20be48556d3c003c7613681ea30093f0e7da200/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-35220) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/a20be48556d3c003c7613681ea30093f0e7da200/aspnetcore/blazor/javascript-interoperability/index.md) | …
> [Pre4] New JavaScript interop features

- aspnetcore/fundamentals/openapi/customize-openapi.md
- aspnetcore/fundamentals/openapi/samples/9.x/WebMinOpenApi/Program.cs
This PR fixes the description of the execution order of Transformers, which is inaccurate in the current docs. The execution order is dependent on the type of the transformer, as well as the order in which they are added.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/customize-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/b8e2ef937e3fe7fa8c53e658a1de95175632dbc1/aspnetcore/fundamentals/openapi/customize-openapi.md) | [aspnetcore/fundamentals/openapi/customize-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/customize-openapi?branch=pr-en-us-35205) |
> Fix description of transformer execution order

- aspnetcore/fundamentals/openapi/include-metadata.md
This PR updates the information on how ASP.NET Core renders C# data types into OpenAPI schema in .NET 10.
This is a companion PR to #35214.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/aaa5fe4085c354f97d090ac721eb4a2687174a01/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35222) |
> Update info on rendering of C# data types to OpenAPI in .NET 10

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
- aspnetcore/fundamentals/openapi/includes/aspnetcore-openapi9.md
Contributes to #34754
[Preview URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-10.0&branch=pr-en-us-35242&tabs=visual-studio%2Cvisual-studio-code)
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/4253f618042f315208f3436fe507408f63358782/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-35242) |
> OpenApi 3.1 /1

- aspnetcore/security/preventing-open-redirects.md
Fixes #34759
@martincostello please review
---
|:--|:--|
| [aspnetcore/security/preventing-open-redirects.md](https://github.com/dotnet/AspNetCore.Docs/blob/c6b6afa4d351633bc5415fe2155f17e639a03b88/aspnetcore/security/preventing-open-redirects.md) | [aspnetcore/security/preventing-open-redirects](https://review.learn.microsoft.com/en-us/aspnet/core/security/preventing-open-redirects?branch=pr-en-us-35240) |
> isUrlLocal /3

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
This PR adds an explanation for the change in how `int` and `long` properties/parameters are represented in OpenAPI documents generated by .NET 10.
I also used this opportunity to consolidate the information about the breaking changes introduces by OpenApi.Net v2.
Fixes dotnet/aspnetcore#61038
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/7bfd410dd5a44da639bb28bbcc7c9d2f54fe16f6/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35214) |
> Explain OpenAPI representation of int and long types in .NET 10

- aspnetcore/blazor/forms/index.md
Fixed grammar in ## Clear a form or field section.
- Changed: Reset a form by clearing its model back its....
To: Reset a form by clearing its model back to its....
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/5dadc24e5daa5080ccd11f450bcb0170c87e3f72/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-35244) |
> Update index.md Fixed grammar issue

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
Fixes  #34754
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/c42b8193433a1fed81274a11341a24565c0e36fe/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-35247) |
> YAML in OpenAPI

- aspnetcore/performance/caching/memory.md
`MemoryCache.TryGetValue` can trigger a background scan for expired items.
https://github.com/dotnet/runtime/blob/d0e28e1c83d24ea41f7965d13dc01842ba1cf05a/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L284
Fixes #35250
---
|:--|:--|
| [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d748900e26c58e64491fa11d136ae199a6764c6/aspnetcore/performance/caching/memory.md) | [Cache in-memory in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?branch=pr-en-us-35245) |
> Include TryGetValue in activities that can trigger background scan

- aspnetcore/fundamentals/openapi/include-metadata.md
- aspnetcore/fundamentals/openapi/includes/include-metadata9.md
Fixes  #35254
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8af4c334e7b63de261db70d9eed987e279885fc/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35255) |
> Clean up moniker hell

- aspnetcore/fundamentals/openapi/include-metadata.md
Fixes #35081
@sander1095 please review
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/8f619bd6a7d2825db2f1f95663c3b1820b0c4103/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35257) |
> ASP.NET Core does not collect metadata from XML doc comments.

- aspnetcore/includes/benefits.md
- aspnetcore/introduction-to-aspnet-core.md
Fixes #34576
Promote Blazor as the first option for front end over Razor Pages.
---
|:--|:--|
| [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f74f5c1f5f567362cb1b4748373e082da7cfaf0/aspnetcore/introduction-to-aspnet-core.md) | [aspnetcore/introduction-to-aspnet-core](https://review.learn.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?branch=pr-en-us-35149) |
> Overview: Blazor over Razor Pages

- aspnetcore/blazor/host-and-deploy/webassembly/deployment-layout.md
- aspnetcore/data/scaffold_RP.md
Fixes #35294
Looks like the article can just lose the link. The sample there isn't specifically referenced by the text.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly/deployment-layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/fef139cb2a7829884fa6ceb90259182f9c9446fb/aspnetcore/blazor/host-and-deploy/webassembly/deployment-layout.md) | [aspnetcore/blazor/host-and-deploy/webassembly/deployment-layout](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly/deployment-layout?branch=pr-en-us-35296) |
| [aspnetcore/data/scaffold_RP.md](https://github.com/dotnet/AspNetCore.Docs/blob/fef139cb2a7829884fa6ceb90259182f9c9446fb/aspnetcore/data/scaffold_RP.md) | …
> Remove broken sample link

- aspnetcore/blazor/components/prerender.md
Fixes #35291
Thanks @hakenr! 🎷 ... I don't think the latter example requires anything further. There are a couple of lines under the code that remark on the main point before showing the example output.
> When the component executes, `currentCount` is only set once during prerendering. The value is restored when the component is rerendered. ...
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/5339da302a85cacbe1bf79afabb2079ef25c32d9/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-35298) |
> Remove lead-in pattern-based examples

- aspnetcore/fundamentals/http-logging/index.md
Fixes #35303
---
|:--|:--|
| [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc7759005f7cdd00396cb0e13da974b8e0ede190/aspnetcore/fundamentals/http-logging/index.md) | [aspnetcore/fundamentals/http-logging/index](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/index?branch=pr-en-us-35304) |
> Add API Browser cross-links

- aspnetcore/fundamentals/servers/kestrel/http3.md
Fixes #34880
In general, I tried to align the ASP.NET Core article with the .NET one ([Use HTTP/3 with HttpClient](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-http3))
- Moved the "HTTP/3 benefits" section before the "HTTP/3 requirements" section, since the requirements needs to reference QUIC protocol that is introduced there.
- Linked .NET docs on QUIC support that contains up-to-date information on platform requirements and installation steps.
- Also linked .NET HTTP/3 docs to the "Localhost testing" section where `HttpClient` is mentioned.
- Updated QUIC RFC link.
- Updated to use wording suggested by @adityamandaleeka in https://github.com/dotnet/AspNetCore.Docs/issues/34880#issuecomment-2819122995
cc @ManickaP PTAL
---
|:--|:--|
| …
> Updated Kestrel HTTP/3 docs

- aspnetcore/grpc/grpcweb.md
Mirror change at https://github.com/grpc/grpc-dotnet/pull/2631 to our docs.
---
|:--|:--|
| [aspnetcore/grpc/grpcweb.md](https://github.com/dotnet/AspNetCore.Docs/blob/4df6884b91509a652683af689987d9c61998ec26/aspnetcore/grpc/grpcweb.md) | [aspnetcore/grpc/grpcweb](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?branch=pr-en-us-35327) |
> Update grpcweb.md to remove obsolete configuration

- aspnetcore/security/includes/docker-compose-https7.md
> SFI  docker-compose-https7.md

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/index.md
Fixes #35346
Thanks @jrichmeier! 🚀 ... This turned out to be an excellent follow-up to the work last week that added separate web API projects to the sample apps. In addition to adding the token handler approach (OIDC) to the *Security* overview section, I'm also adding the MS Identity Web example with cross-links. I'm calling out the MS Identity Web bits in the *Call web API* article in a new section. It's '*Wow! Complicated!*' 😄 to get all of the pieces into place, but this should do the trick. I'll publish these updates within a few hours. *Thanks again for your issue!*
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/4df1b4e3b4e5d6408c815ccc6b0dab027fc7b3f7/aspnetcore/blazor/call-web-api.md) | …
> Additional ServerWeatherForecaster scenarios

- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/index.md
Fixes #35341
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/05aacf08228a950fe280f0f734ff5e70f14be4fa/aspnetcore/blazor/components/event-handling.md) | [aspnetcore/blazor/components/event-handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-35348) |
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/05aacf08228a950fe280f0f734ff5e70f14be4fa/aspnetcore/blazor/components/index.md) | [aspnetcore/blazor/components/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-35348) |
> Improve async void guidance

- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md
- aspnetcore/blazor/host-and-deploy/webassembly/azure-storage.md
- aspnetcore/blazor/host-and-deploy/webassembly/github-pages.md
Fixes #35338
Thanks @Rod-at-DOH! 🚀 ... I wasn't able to update the title of the WASM+IIS article to specify "standalone" because the article also has to cover hosted Blazor WebAssembly of .NET 7 or earlier. However .......
* I'll call out BWAs and Blazor Server apps explicitly for the server-side IIS cross-link.
* For WASM+IIS, I'm changing the link and the description because the content has shifted slightly. The WASM+IIS coverage is no longer in the overview article. It has its own article now. The description now calls out what's in the dedicated IIS article. Readers could still find this content, but it's best if this link points directly to the new WASM+IIS article with an exact description of what's there.
* I found some other scenarios with WASM hosting (Azure Static Web Apps, …
> Standalone WASM with IIS cross-links and content

- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35377
The samples work was performed on https://github.com/dotnet/blazor-samples/pull/536.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/5158f04238f2ef12cc24c6fd0da30c4928fd1cf4/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?branch=pr-en-us-35387) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/5158f04238f2ef12cc24c6fd0da30c4928fd1cf4/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.lear …
> Convert configuration of BWA+Entra samples

- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35388
The sample solutions were updated on https://github.com/dotnet/blazor-samples/pull/537.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/d6721c3064f1eb6e01d8d4333cc002a979574970/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?branch=pr-en-us-35389) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/d6721c3064f1eb6e01d8d4333cc002a979574970/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.l …
> Add OpenAPI/SwaggerUI

- aspnetcore/fundamentals/minimal-apis/responses.md
Fixes #35333
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/6770c62b5a9a7ca27d73b75d7dc2358bbfb4a329/aspnetcore/fundamentals/minimal-apis/responses.md) | [aspnetcore/fundamentals/minimal-apis/responses](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-35334) |
> Clean up sentence

- aspnetcore/test/integration-tests.md
---
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/ccf95722c67cfacf5eb7649991656fde60ee0333/aspnetcore/test/integration-tests.md) | [aspnetcore/test/integration-tests](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-35349) |
> Update link to reflect title of Testing in .NET article

- aspnetcore/client-side/bundling-and-minification.md
Fixes #20808
Removing the WebOptimizer recommendation from the Bundling and Minification topic.
---
|:--|:--|
| [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d67ce616243ec1c8c670699df24f574c6650bf1/aspnetcore/client-side/bundling-and-minification.md) | [aspnetcore/client-side/bundling-and-minification](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?branch=pr-en-us-35392) |
> Remove WebOptimizer recommendation from Bundling and Minificaition topic

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/OpenApiSchemasInTransformers.md
Contributes to #35393
**Prep only**: Moving initial draft from comments in WN to an include so a diff in edits can be seen after it is worked on in a new PR.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/8adb9b37a44cb4d48070afc9ff857cadf90629d6/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35413) |
> WN: Prep Only: OpenApiSchemas in transformers moved to include

- aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #35416
Thanks @snew3687! 🚀 ... Let's see if this clarification will work for folks. It seems clear now that the reason I haven't been pinged by the community on this before now is that this specific example shouldn't require it. It's when devs don't use `IHttpClientFactory` that they'll hit the 💥. Since this section's example uses `IHttpClientFactory`, it has been mostly ok without mentioning it. Where it was required in the next section, it was called out several years ago ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-9.0#configure-authorizationmessagehandler
... and I'm adding a remark to that, too, on why it's done there.
---
|:--|:--|
| …
> Clarify when the `InnerHandler` must be assigned

- aspnetcore/release-notes/aspnetcore-10/includes/xml-comment-generator.md
Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/35412
Prep only: Moving initial draft from comments in WN to an include so a diff in edits can be seen after it is worked on in a new PR.
> WN10P4 XML comment gen improvements - prep only, move original content from WN issue to include file

- aspnetcore/release-notes/aspnetcore-10/includes/doc-provider-in-di.md
WN10.P4 Support for OpenApiDocumentProvider in DI - prep only PR, moves original content from the WN issue to include file.
> WN10P4 Support OpenApiDocumentProvider in DI - prep only, move original content from WN issue to include file 

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/jsonPatch.md
Fixes #35373
[New JsonPatch Implementation with System.Text.Json](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0&branch=pr-en-us-35425#new-jsonpatch-implementation-with-systemtextjson)
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/5862d2ec046a604a28e7af09fbd2818d917e11ec/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35425) |
> JasonPatch /3

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
It seems more fitting to show sync variants of interop methods in the code example that creates `IJSInProcessObjectReference` using the sync `InvokeNew`.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/334cbe4234bcdd13563b5659c6b4620c629f2fd8/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-35452) |
> Use sync variants of interop methods in IJSInProcessObjectReference example

- aspnetcore/blazor/call-web-api.md
Fixes #35357
Sample updates were placed on https://github.com/dotnet/blazor-samples/pull/539.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/50832825a0216397f7ce83d9b4c9883d5e99d03a/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35456) |
> [Pre4, Blazor only] New PATCH w/`System.Text.Json`

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Addresses #35217
Fixes #35233
Fixes #35231
Fixes #35439
***This PR will be held until P4 releases.***
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/23b6a76ae5f3618e6f44afbaf251838a76b0fd46/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-35433) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/23b6a76ae5f3618e6f44afbaf251838a76b0fd46/aspnetcore/blazor/fundamentals/routing.md) | [aspnetcore/blazor/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en …
> [Pre4] Final round of Blazor content/WN updates

- aspnetcore/fundamentals/openapi/includes/api_endpoint_operation.md
- aspnetcore/fundamentals/openapi/overview.md
Fixes #34455
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/overview?view=aspnetcore-10.0&branch=pr-en-us-35325#api-v-endpoint-v-operation)
CoPilot got very verbose, it's probably TMI.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/c33acbb1ee149a859cd46f092b15a9e5420f3434/aspnetcore/fundamentals/openapi/overview.md) | [aspnetcore/fundamentals/openapi/overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/overview?branch=pr-en-us-35325) |
> API v endpoint v operation /1

- aspnetcore/release-notes/aspnetcore-10.0.md
Just a quick product name nit fix
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/053e281ee28413deb3a449c1b1e1248a62ed5005/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35472) |
> Correct casing of ASP.NET Core in release notes

- aspnetcore/performance/caching/output.md
- aspnetcore/test/integration-tests.md
- aspnetcore/test/integration-tests/includes/integration-tests9.md
- aspnetcore/test/integration-tests/snippets/mstest/CustomWebApplicationFactory.cs
- aspnetcore/test/integration-tests/snippets/mstest/IntegrationTests/AuthTests.cs
- aspnetcore/test/integration-tests/snippets/mstest/IntegrationTests/BasicTests.cs
- aspnetcore/test/integration-tests/snippets/mstest/IntegrationTests/IndexPageTests.cs
- aspnetcore/test/integration-tests/snippets/nunit/CustomWebApplicationFactory.cs
- aspnetcore/test/integration-tests/snippets/nunit/IntegrationTests/AuthTests.cs
- aspnetcore/test/integration-tests/snippets/nunit/IntegrationTests/BasicTests.cs
- aspnetcore/test/integration-tests/snippets/nunit/IntegrationTests/IndexPageTests.cs
- aspnetcore/test/integration-tests/snippets/xunit/CustomWebApplicationFactory.cs
- aspnetcore/test/integration-tests/snippets/xunit/IntegrationTests/AuthTests.cs
- aspnetcore/test/integration-tests/snippets/xunit/IntegrationTests/BasicTests.cs
- aspnetcore/test/integration-tests/snippets/xunit/IntegrationTests/IndexPageTests.cs
- aspnetcore/zone-pivot-groups.yml
This PR adds support for xUnit & NUnit into the integration tests documentation; including snippets for all three popular testing libraries (xUnit, MSTest, NUnit). This PR follows the examples of already exisiting MS documentation i.e. https://learn.microsoft.com/en-us/dotnet/aspire/testing/write-your-first-test?pivots=mstest
I'm submitting a PR as suggested by @tdykstra here: https://github.com/dotnet/AspNetCore.Docs/issues/35290#issuecomment-2822837077
Notes:
- I haven't updated the sample project in AspNetCore.Docs.Samples - this could be useful to add another two testing projects, but I wasn't sure what the scope of this PR should be.
- Some of the article text still references xUnit; as it's describing the samples project. I'm not sure if this is now confusing, as the pivot groups …
> Integration tests documentation add nunit mstest

- aspnetcore/blazor/fundamentals/routing.md
Fixes #35468
Ilona ... IMO, much better than what I had here. Your example concept is GrEaT! 🎉  A few notes ...
* This adopts my strategy of using fully working, cut-'n-paste examples for demos, which devs enjoy. Eventually, this example code will make its way into the Blazor sample apps.
* I changed some bits here and there, such as making the `Context` into a `Heading` property, and I'm 👂 for improvements.
* The *Routing* article is now too long and too full of advanced concepts, so I'll be creating a *Routing* node of articles or a single article in the reference docs and downsize this "fundamentals" article to focus on basic concepts. For now, we'll just place this new content here, but I think this will become an advanced scenario for a different article later. That …
> Improve `OnNotFound` example

- aspnetcore/grpc/performance.md
I'm going to be as clear as I can in this PR description about the symptoms we observed, in case it helps people Googling in the future.
Here's what happens when you copy-paste the client configuration from the keepalive docs:
* The default KeepAlive policy [is set at the HTTP level](https://github.com/dotnet/runtime/blob/b8752af999a212847b43034e7ef44cf6292b98c3/src/libraries/System.Net.Http/src/System/Net/Http/HttpHandlerDefaults.cs#L17) to "Always", which means that if you don't set a `KeepAlivePingPolicy` in the gRPC client settings but you *do* override `KeepAlivePingDelay` from its default of infinity ("don't send pings"), then the client will inherit the default "Always" and will send keepalives for the duration of the connection.
* `PooledConnectionIdleTimeout` in the docs snippet …
> Add warning about keepalives

- aspnetcore/blazor/performance/rendering.md
The component itself doesn't decide whether to rerender - this logic is handled by Blazor. A rerender happens if the received parameter values might have changed (e.g. they're mutable objects) **and** the component's `ShouldRender()` method returns `true` (which it does by default unless overridden).
---
|:--|:--|
| [aspnetcore/blazor/performance/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/246ad0ee29f01af43621c02e1ebc6150ecca6017/aspnetcore/blazor/performance/rendering.md) | [aspnetcore/blazor/performance/rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/rendering?branch=pr-en-us-35492) |
> [Blazor] Rendering - Rerender logic adjustments

- aspnetcore/blazor/performance/rendering.md
`ShouldRender` is a method, it is not being set, it returns a value.
I also added a part to clarify that you shouldn't always return false - only when the parameter values haven't changed. (Though feel free to cut that if it's too much detail.)
---
|:--|:--|
| [aspnetcore/blazor/performance/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/11816147f56c233c6c9a6058d2b884b6c2e2b6a3/aspnetcore/blazor/performance/rendering.md) | [ASP.NET Core Blazor rendering performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/rendering?branch=pr-en-us-35495) |
> [Blazor] rendering perf - ShouldRender nits

- aspnetcore/fundamentals/servers/yarp/extensibility-transforms.md
Improved the documentation for **request body transforms** by clarifying limitations, common pitfalls, and safe patterns of use.
- **Can only modify an existing request body**, not add one where none exists.
- Clearly documented:
- How to safely inject a new request body via custom middleware **before YARP**
- Necessary use of `IHttpRequestBodyDetectionFeature` to ensure ASP.NET Core and YARP recognize the new body
- Provided code examples for adding a new request body in middleware.
- dotnet/yarp#2809
- dotnet/yarp#2617
- The workaround leverages `IHttpRequestBodyDetectionFeature`, as recommended by @MihaZupan and @Tratcher in dotnet/yarp#2617.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/extensibility-transforms.md](https://github.com/dotnet/AspNetCor …
> Clarify request body transforms require existing body

- aspnetcore/fundamentals/minimal-apis.md
Fixes #35400
For topic: Minimal APIs quick reference
Add new section on validation support for both classes and record types, introduced in .NET 10 Prev 3 & 4 respectively.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/17a674dbe05b09b699f8aa3426ecf9a083efcaaa/aspnetcore/fundamentals/minimal-apis.md) | [aspnetcore/fundamentals/minimal-apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-35501) |
> Min API Quick Ref: Add validation support .NET 10 Prev4

- aspnetcore/blazor/fundamentals/startup.md
Fixes #35513
Thanks @frank-hoffman! 🚀 ... I'll open a follow-up issue in a minute to replace the approach for that example. This will at least get it out of the 8.0 version of the article for now.
**UPDATE**: ***Done!*** 👍 ... I opened #35515 to replace that example with something good for the 8.0 era. I'll get to that as soon as I can, and I might have some time next week to address it. Thanks again for the issue!
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8783e11dcc301edcdcbde2fe2e6a636588080bf/aspnetcore/blazor/fundamentals/startup.md) | [aspnetcore/blazor/fundamentals/startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-35514) |
> Version out example for 8.0

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #35494
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/12648e42327c47b235b4d9fb3fab563d8b32cf12/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35504) |
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/12648e42327c47b235b4d9fb3fab563d8b32cf12/aspnetcore/blazor/fundamentals/signalr.md) | [aspnetcore/blazor/fundamentals/signalr](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-35504) |
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/12648e42327c47b235 …
> In-memory/production distributed caches

- aspnetcore/blazor/components/httpcontext.md
- aspnetcore/blazor/fundamentals/startup.md
Fixes #35544
We have two spots to place guidance ...
* As you said, in the HTTP context article. Are the two example cases that I provide enough?
* In the *Startup* article, where we show how to set headers before the response has started.
I thought we had a remark on this subject somewhere, but I couldn't find anything when I searched.
---
|:--|:--|
| [aspnetcore/blazor/components/httpcontext.md](https://github.com/dotnet/AspNetCore.Docs/blob/d039b322296f714a67fdc45d27cf33cfde1954ab/aspnetcore/blazor/components/httpcontext.md) | [aspnetcore/blazor/components/httpcontext](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/httpcontext?branch=pr-en-us-35549) |
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Do …
> Setting headers after the response starts

- aspnetcore/blazor/security/additional-scenarios.md
`task.Result` is generaly a poor code and the `Task` should be awaited wherever possible (async methods).
---
|:--|:--|
| [aspnetcore/blazor/security/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/d08822dc2a201c474136cd3795866698674ce4d8/aspnetcore/blazor/security/additional-scenarios.md) | [aspnetcore/blazor/security/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/additional-scenarios?branch=pr-en-us-35560) |
> [Blazor] additional-scenarios.md - await async where possible

- aspnetcore/mvc/views/razor.md
Fixes #32916
Added a note explaining that Razor doesn't omit `data-` attributes with null or false values.
---
|:--|:--|
| [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/42704f831520a9a13ea92e021d037faa6c6a6858/aspnetcore/mvc/views/razor.md) | [aspnetcore/mvc/views/razor](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?branch=pr-en-us-35583) |
> Clarify Razor's handling of data- attributes

- aspnetcore/fundamentals/servers/kestrel/http3.md
The layout was broken.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/kestrel/http3.md](https://github.com/dotnet/AspNetCore.Docs/blob/c3cfc20cda2b7ff57e943d1b938759d64616b175/aspnetcore/fundamentals/servers/kestrel/http3.md) | [aspnetcore/fundamentals/servers/kestrel/http3](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?branch=pr-en-us-35591) |
> Fixed comparison table HTTP/2 <-> HTTP/3

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/httpsys.md
- aspnetcore/release-notes/aspnetcore-10/samples/HttpSysConfig/Program.cs
Fixes #35569 
This is just the what's new update; the update of the article in the servers section of the TOC will be next
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/9f74798d1667192d884f33a121a7b36d42a43c89/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core in .NET 10](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35595) |
> Customizable security descriptors for HTTP.sys

- aspnetcore/security/authentication/identity.md
Fixes #35526
Thanks for the issue, @silajim! 🚀 ... We want the main doc set to focus more on Blazor. I retain the Razor Pages section here, but I inject a new section on Identity with Blazor Web Apps. For both sections, I include a cross-link to where you can see either the Identity pages (Razor Pages) or Identity components (Blazor Web Apps). I also make a remark about how the Blazor security docs supersede or add to Identity and security content here. I may as well toss in MVC in case the dev is looking for that experience.
Sorry for all of the churn (email pings!). I thought this one would be a quick fix, but there was a lot to do to bring it up to speed. We're good now. It's much better than before. Thanks again for your issue!
---
|:--|:--|
| …
> Focus Identity on BWAs

- aspnetcore/fundamentals/servers/yarp/lets-encrypt.md
Fixes #35611
Thanks @danielwertheim! 🚀 
Here's the article ...
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/lets-encrypt?view=aspnetcore-9.0
@natemcmaster, Dan ... Archived mid-.NET 9, so I marked the article for up to 8.0. Is that what you'd like to do here?
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/lets-encrypt.md](https://github.com/dotnet/AspNetCore.Docs/blob/8dad23e862b41f45eec6dfc4ca115d678b97ebf6/aspnetcore/fundamentals/servers/yarp/lets-encrypt.md) | [aspnetcore/fundamentals/servers/yarp/lets-encrypt](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/lets-encrypt?branch=pr-en-us-35615) |
> Version the Let's Encrypt article

- aspnetcore/blazor/components/js-spa-frameworks.md
The `@page` directive isn't needed and is rather confusing in that context, where the component is clearly not used as page.
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b6aceb8386f7aabea73f98979d3c5c9ca8a1560/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-35651) |
> remove @page directive from sample component

- aspnetcore/security/authentication/ws-federation.md
- aspnetcore/security/authentication/ws-federation/samples/Startup21.cs
- aspnetcore/security/authentication/ws-federation/samples/Startup31.cs
- aspnetcore/security/authentication/ws-federation/samples/StartupNon21.cs
- aspnetcore/security/authentication/ws-federation/samples/StartupNon31.cs
Fixes #35650
Thanks @shectorwood! 🚀 ... The article was using an old approach for code cross-linking. I've updated it. I'll merge the updates into the live article in a few minutes, and they should be published in perhaps 15 minutes after that.
In the meantime, you can inspect the files manually in our source ...
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authentication/ws-federation/samples
* `StartupNon31.cs`
* `Startup31.cs`
This is some awfully old code (ASP.NET Core 3.1). The framework is out of support. Hopefully, the code examples are fine and will work well in the current release.
---
|:--|:--|
| [aspnetcore/security/authentication/ws-federation.md](https://github.com/dotnet/AspNetCore.Docs/blob/10d1666904915a185f9d3fda8f33d2 …
> Fix broken code snippets and links

- aspnetcore/grpc/diagnostics.md
- aspnetcore/signalr/diagnostics.md
dotnet-counters released a breaking change in v9.0.621003.
"Previously dotnet-counters allowed specifying a list of space separated counters prior to the -- token in collect/monitor mode. Counters must now be supplied explicitly in the --counters option as a list of comma-separated values." - https://github.com/dotnet/diagnostics/releases/tag/v9.0.621003
Fixes #35664
---
|:--|:--|
| [aspnetcore/grpc/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/acc66b6e7690974deec0b16f453d5b7a4e1c498c/aspnetcore/grpc/diagnostics.md) | [aspnetcore/grpc/diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/diagnostics?branch=pr-en-us-35647) |
| [aspnetcore/signalr/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/acc66b6e7690974deec0b …
> Update dotnet-counters cli options to supply counter provider

- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
Fixes #35667
Thanks @gavinltomra! 🚀 ... This should improve the text. We'll retain the "right-to-left" phrasing because that's the way that the product unit described the feature. I've added "first wins" language and additional explanation. I also made a few other changes, including an important change describing the first example, where fields are used, not component parameters. *Thanks again for your issue!*
---
|:--|:--|
| [aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e7d3973fb93c7ddf613e848375d85cbc613ed86/aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md) | [aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters](https://review.learn.microso …
> Improved attribute splatting guidance

- aspnetcore/blazor/security/account-confirmation-and-password-recovery.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
Addresses #35665
***Oooops!*** A 😈 got me on cut-'n-paste coverage. This should refer to the key vault, not blob storage, where the content was copied from.
---
|:--|:--|
| [aspnetcore/blazor/security/account-confirmation-and-password-recovery.md](https://github.com/dotnet/AspNetCore.Docs/blob/be4ccda0b1ac829d13bd571cc0cae6cafd62a495/aspnetcore/blazor/security/account-confirmation-and-password-recovery.md) | [aspnetcore/blazor/security/account-confirmation-and-password-recovery](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/account-confirmation-and-password-recovery?branch=pr-en-us-35671) |
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/be4ccda0b1ac829d13bd571cc0cae6cafd62a495/asp …
> Patch new coverage

- aspnetcore/signalr/background-service/samples/6.0/Server/ClockHub.cs
This change is intended to make it clearer that the ClockHub's method is called (used) only by clients.
I was going through the ["Host ASP.NET Core SignalR in background services"](https://learn.microsoft.com/en-us/aspnet/core/signalr/background-services) tutorial, but then wondered why `SendTimeToClients()` [isn't called anywhere](https://github.com/search?q=repo%3Adotnet%2FAspNetCore.Docs%20SendTimeToClients&type=code).
I first thought that this method is used by the server to send the current time to clients, but that's actually done by `_clockHubContext.Clients.All.ShowTime(DateTime.Now);`
Furthermore, it makes no sense that a(ny) client sends a time to all clients.
The tutorial would even work without this method, so `ClockHub` could be empty and everything runs as intended.
> Update ClockHub.cs - Clarify the method's purpose

- aspnetcore/log-mon/metrics/built-in.md
Links incorrectly pointed to client instead of server HTTP metrics.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/built-in.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a0c5b9a78a2710cdbef25581f985b7f8e60f7e3/aspnetcore/log-mon/metrics/built-in.md) | [aspnetcore/log-mon/metrics/built-in](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/built-in?branch=pr-en-us-35725) |
> Fix metrics links

- aspnetcore/grpc/grpcweb.md
- aspnetcore/grpc/grpcweb/sample/8.x/GrpcGreeter/Program.cs
Add `Grpc-Status-Details-Bin` to exposed headers in grpc web docs.
---
|:--|:--|
| [aspnetcore/grpc/grpcweb.md](https://github.com/dotnet/AspNetCore.Docs/blob/378489b325cfc0982194659f63f66ecd1bbd8039/aspnetcore/grpc/grpcweb.md) | [aspnetcore/grpc/grpcweb](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?branch=pr-en-us-35733) |
> docs: Add `Grpc-Status-Details-Bin` to exposed headers in grpcweb docs

- aspnetcore/fundamentals/host/web-host.md
---
|:--|:--|
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/e916a8fc3a934e0d7b570ca74d619168cbd77519/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-35750) |
> Added HTTP_PORTS

- aspnetcore/fundamentals/routing.md
I'd noticed very little documentation about the default route constraints that are added to and are available in an aspnetcore project. I believe it'd be a good approach to maintain an exhaustive list of the default constraints that are available, so users like myself wouldn't need to [trawl through the codebase](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/RouteOptions.cs#L102) to find them.
---
|:--|:--|
| [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/fcc6ded28afe1f0454eede006f240a2516c73630/aspnetcore/fundamentals/routing.md) | [aspnetcore/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-35838) |
> Add exhaustive list of default route constraints

- aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/index.md
Fixes #35837
Swashbuckle is no good for 9.0 or later. We'll just implement OpenAPI documentation for the time being. The samples work was performed on https://github.com/dotnet/blazor-samples/pull/565 and https://github.com/dotnet/blazor-samples/pull/566. I've placed a long-range tracking item to consider adding a visualization UI/endpoint tester at #34434.
Wade, Tom ... I only need one review, so I'll merge this after either you take a look.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/5189abf6dcb45d094dc5ff89cead669f09a1a756/aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md) | [aspnetcore/blazor/hybrid/security/maui-blazor-web-identity](https://review.learn.microsoft. …
> Version Swashbuckle/Swagger remarks

- aspnetcore/index.yml
Refreshed.  Updated migration links and removed a Razor getting started so Blazor is the only start point.
Fixes #35843 35843
Contributes to #35765
---
|:--|:--|
| [aspnetcore/index.yml](https://github.com/dotnet/AspNetCore.Docs/blob/0d5ce696264f9c7fb402697796ba2332a543e432/aspnetcore/index.yml) | [aspnetcore/index](https://review.learn.microsoft.com/en-us/aspnet/core/index?branch=pr-en-us-35841) |
> Refreshed index.md landing page

- aspnetcore/host-and-deploy/iis/hosting-bundle.md
Fixes #35860 
Refresh pass.
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/88c0b70e63076447a8a9abd9667a29a73b4ebb2e/aspnetcore/host-and-deploy/iis/hosting-bundle.md) | [aspnetcore/host-and-deploy/iis/hosting-bundle](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?branch=pr-en-us-35859) |
> Refresh IIS hosting-bundle.md

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles-net-5-to-7.md
- aspnetcore/release-notes/aspnetcore-5.0.md
Fixes #35857
For one article with today's date, I collapsed the 'not current' INCLUDE by a line. For another one, I found a double-space to fix.
Wade or Tom, could you pop open the *Call web API* review article to confirm that the build engine placed actual links, not XREFs, into the content?
An example from the live doc set is in this section (second bullet in the list) ...
https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-9.0#microsoft-identity-platform-for-web-api-calls
This is the review link that goes right there to confirm that those are ***real*** links now ...
https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35858#microsoft-identity-platform-for-web-api-calls
---
|:--|:--|
| …
> Update dates to rebuild articles

- aspnetcore/blazor/progressive-web-app/push-notifications.md
Fixes #35747
Tom, Wade ... Just need a single review on this one, too.
Originally, I planned to add a section on how to grab a Key Vault certificate's private and public keys for this, but there's just no time. I'm booked for several months between 10.0 and '*Blazorfy It!*'&trade; issues. I don't even want to keep a backlog issue on this because I wouldn't reach it until at least 2026. However, I did make a tracking entry on #34434 to consider it next year.
After trying a few different approaches, I've settled on ...
* Use some AI-generated content that I like for the *Establish public and private keys* section.
* Use my original CAUTION note with modification in the *Send a notification* section.
---
|:--|:--|
| …
> Update the security guidance

- aspnetcore/docfx.json
Update to fix invalid ms.author value in docfx.json for content in what's new in docs.
Contributes to https://github.com/dotnet/AspNetCore.Docs/issues/35827
> Fix invalid ms.author: Update docfx.json

- aspnetcore/mvc/models/file-uploads.md
Fixes #35874
Let's fix them this way. 🤔 I think the reason that they're failing is that they're marked "legacy." That's a wild guess tho.
I think these should be reported because API docs exist for them. Seems like the XREF links should still work for them.
---
|:--|:--|
| [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/8195034210a9d3fec40561bb83a1a824eedd4a3a/aspnetcore/mvc/models/file-uploads.md) | [aspnetcore/mvc/models/file-uploads](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?branch=pr-en-us-35875) |
> Fix legacy Azure SDK API links

- .github/copilot-instructions.md
Fixes #35798 
When we ask copilot to create a PR based on an issue, or to review a PR on this repo, copilot will use the instructions in this copilot-instructions.md to guide it and to facilitate workflow interaction with human authors or reviewers. The goal of the instructions is to help ensure Copilot's responses maintain consistent quality and follow established documentation standards and some minimal expected human Intractive workflow when assisting with ASP.NET Core documentation.
There isn't a way to preview or test the instructions locally before publishing them to the repository that I know of. This is because the instructions are processed by GitHub Copilot's systems when they're accessed from the repository.  However, this copilot-intruction.md can be pointed to as a link in …
> Add copilot-instructions to repo

- aspnetcore/fundamentals/openapi/includes/using-openapi-documents-9.md
Versioning  Prep Only: Moving the .NET 9 version of the topic to includes, starting a new one with the .NET 10 moniker range in prep for updating in new PR afterwards so diffs are easily seen.
Contributes to #35408
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/using-openapi-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/ed79a3be0dba737bcf54bf8e5d9c3af0bbe187af/aspnetcore/fundamentals/openapi/using-openapi-documents.md) | [Use openAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?branch=pr-en-us-35887) |
> Versioning  Prep Only: Using-openapi-documents.md

- aspnetcore/fundamentals/app-state.md
- aspnetcore/performance/caching/distributed.md
- aspnetcore/performance/caching/distributed/includes/distributed5.md
- aspnetcore/performance/caching/distributed/includes/distributed6-7.md
- aspnetcore/performance/caching/hybrid.md
- aspnetcore/performance/caching/overview.md
- aspnetcore/performance/caching/overview/includes/overview6.md
- aspnetcore/performance/caching/overview/includes/overview7-8.md
- aspnetcore/performance/caching/response.md
- aspnetcore/release-notes/aspnetcore-9/includes/hybrid-cache.md
We've recently released the Microsoft.Extensions.Caching.Postgres library and wanted to include this option in our docs.
---
|:--|:--|
| [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/8b9afdddccc931388e010abe3d400c97e4226874/aspnetcore/fundamentals/app-state.md) | [Session and state management in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?branch=pr-en-us-35889) |
| [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/8b9afdddccc931388e010abe3d400c97e4226874/aspnetcore/performance/caching/distributed.md) | [Distributed caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?branch=pr- …
> Including Distributed Postgres Cache information

- aspnetcore/client-side/dotnet-interop.md
Fixes #35900
Per https://github.com/dotnet/AspNetCore.Docs/issues/35882.
Marek, do we need anything else outside of a cross-link?
**UPDATE**: Should we link the non-Blazor article instead for this? We can link directly to the section that pertains to static assets ...
https://learn.microsoft.com/aspnet/core/razor-pages/ui-class#create-an-rcl-with-static-assets
**UPDATE**: *Yes!* Let me see if I can link both.
---
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/74e661740853aeea37c8323cdedaf867bf85b976/aspnetcore/client-side/dotnet-interop.md) | [aspnetcore/client-side/dotnet-interop](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-35901) |
> Add cross-link to RCL article

- aspnetcore/release-notes/aspnetcore-10/includes/avoid-cookie-login-redirects.md
Contributes to #35824 
Add include for 
Note:
To include in the What's New itself later the What's new needs a small sub section header change:
```
[!INCLUDE[](~/release-notes/aspnetcore-10/includes/avoid-cookie-login-redirects.md)]
```
> WN: Prev7: Add include: Avoid Cookie Login on API endpoint

- aspnetcore/release-notes/aspnetcore-10/includes/responseDescProducesResponseType.md
- aspnetcore/release-notes/aspnetcore-10/includes/webapiaotTemplateAddedOpenAPI.md
[EDIT by guardrex ... 🛑 ***HOLD*** 🛑 for Preview 7]
This PR removes the comment and fixes an incorrect reference to a community contributor.
Fixes #35751
> [Pre7] Remove comment about Minimal API's not supporting ProducesResponseType

- aspnetcore/fundamentals/servers/yarp/config-providers.md
Found a YARP file that still had an invalid ms.author and fixed it.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/config-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/cb14f510f52f5ec31eb398216a026840a35d734f/aspnetcore/fundamentals/servers/yarp/config-providers.md) | [YARP Extensibility: Configuration Providers](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/config-providers?branch=pr-en-us-35886) |
> Fix invalid ms.author value: YARP: config-providers.md

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Replace `InvokeNew`/`InvokeNewAsync` with `InvokeConstructor`/`InvokeConstructorAsync` due to changes in .NET 10 Preview 7.
Fixes #35948
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/2bce2d2b509b124c0ad8e804eb359a3da82c1ce3/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-35949) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2bce2d2b509b124c0ad8e804eb359a3da82c1ce3/aspnetco …
> Replace InvokeNew[Async] with InvokeConstructor[Async]

- aspnetcore/breadcrumb/toc.yml
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/toc.yml
It's useful to have links to the breaking changes alongside the release notes (what's new).
---
|:--|:--|
| [aspnetcore/breadcrumb/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/840521e169b2daceb3cc520d74fc3de1c7499647/aspnetcore/breadcrumb/toc.yml) | [aspnetcore/breadcrumb/toc](https://review.learn.microsoft.com/en-us/aspnet/core/breadcrumb/toc?branch=pr-en-us-35947) |
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/840521e169b2daceb3cc520d74fc3de1c7499647/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core in .NET 10](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35947) |
| …
> Add breaking changes to TOC

- .github/copilot-instructions.md
Quick patch update of the date format. It came up when Copilot suggested a change on my static files PR at https://github.com/dotnet/AspNetCore.Docs/pull/35967.
---
|:--|:--|
| [.github/copilot-instructions.md](https://github.com/dotnet/AspNetCore.Docs/blob/b2d5d8e0456b32b02257508304b0f13dcb930e48/.github/copilot-instructions.md) | [.github/copilot-instructions](https://review.learn.microsoft.com/en-us/aspnet/core/.github/copilot-instructions?branch=pr-en-us-35969) |
> Patch update date format

- aspnetcore/blazor/components/data-binding.md
Reverts dotnet/AspNetCore.Docs#35973
@georgehemmings ... I've opened #35978 to take a closer look. I don't think this was a mistake after all.
Wade ... Reverting one from this morning that I thought would be correct, but the text is probably right in its current form. I might just need to check the organization to where `bind:event` is covered. I'll work it on the new issue. For now, I just need to revert the change from this morning.
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/b6004cd6938ce0d914c32dfdb985ca397ebc4cee/aspnetcore/blazor/components/data-binding.md) | [aspnetcore/blazor/components/data-binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch …
> Revert "Correct comparison to @bind:set"

- aspnetcore/log-mon/metrics/built-in.md
The hosting provider had the initial text missing. I assume the moniker was making that part conditional and it was misplaced in the text.
---
|:--|:--|
| [aspnetcore/log-mon/metrics/built-in.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ef5886d36f53b0ee3e60426231a5f7a652551fc/aspnetcore/log-mon/metrics/built-in.md) | [ASP.NET Core built-in metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/built-in?branch=pr-en-us-35998) |
> Fix missing AspNetCore.Hosting provider built-in metrics doc

- aspnetcore/blazor/security/includes/redirecttologin-component.md
Fixes #35958
Thanks @jbw716! 🚀 
Mackinnon ... Updated per your guidance.
> Add RedirectToLogin configured login path

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/openapi-schema-enhancements.md
Fixes #36078
Adds RC1 OpenAPI schema generation enhancements to the the What's New topic as an include.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/da262caf46d28fe62fa858e0690449c6642fb188/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core in .NET 10](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-36081) |
> WN: v10 RC1: Add OpenAPI Schema Generation Enhancements

- aspnetcore/security/authentication/passkeys/blazor.md
- aspnetcore/security/authentication/passkeys/index.md
Fixes #36072
Let's go with the main coverage in the overview with a short blurb and cross-link in the Blazor article to make sure that we surface this well.
I'm also adding a small update to how some of the code is supplied in the Blazor article. It will make it easier for devs to copy-paste without using the DIFF code language.
---
|:--|:--|
| [aspnetcore/security/authentication/passkeys/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/83e4fcbf141388fe3f051c770129c40cbd7038e6/aspnetcore/security/authentication/passkeys/blazor.md) | [aspnetcore/security/authentication/passkeys/blazor](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/passkeys/blazor?branch=pr-en-us-36086) |
| …
> Mitigate `PublicKeyCredential.toJSON` error

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
Fixed a small typo: mutli -> multi
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/5af0aaf4b4496fa6799f5c8b0e63d638f6696d6e/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [Configure JWT bearer authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-36103) |
> Fix typo in configure-jwt-bearer-authentication.md

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/fundamentals/environments.md
Fixes #35904
Dan, I took a look at what we can obviously move, and I only see the *Environments* section that pertained to a server-side implementation of a normally client-side-only service. That makes a lot of sense to move because it's one of the ways devs can deal with prerendering that's listed in the *Prerendering* article (the fourth option). So ... that's moved here.
Otherwise, I think we hit a bit of a wall on the rest. The sprinkled-in coverage is tightly bound to the concepts covered for each feature/scenario. Speaking only to the prerendering aspects of these features well in advance of the feature coverage doesn't look like to me that it's going to work ... but ... perhaps we addressed your major concern from the other convo and moved most/all of what we need to move.
One …
> Prerendering guidance organization

- aspnetcore/blazor/state-management/prerendered-state-persistence.md
Fixes #36128
Thanks @jonhilt! 🚀 ... I had it correct in one spot ......
https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management/server?view=aspnetcore-10.0#circuit-state-persistence
... but not here. 🙈 
We'll get this merged and into the live article as soon as I can get a review ... ***which I used to not need to get important work done quickly here.*** 🐌💸😠
Tom, Wade ... I say ***AGAIN*** ... please apply pressure to the weak management decision on this. We've been making competent decisions on reviews for *many years* ... over eight years for me. This rule is slowing down work (and it's costly 💰 to the company) ... and in this case, it results in a bug sitting in a live article that I would've been able to fix immediately. For the very few problems that would slip through …
> Fix persistent state API bug

- aspnetcore/blazor/globalization-localization.md
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #35872
This one is a little late ... I should've had this in last week. 🙈🏃‍♂️😄 We won't link to a specific section from the *What's New* section because there isn't one to link to. This was just a NOTE in the article, so we'll version that content for <10.0 and [float on](https://www.youtube.com/watch?v=CTAud5O7Qqk).
Since it's a little late .........................
*Welcome to the party pal!* - John McClane ([Bruce Willis](https://www.imdb.com/name/nm0000246/)), [Die Hard](https://www.20thcenturystudios.com/movies/die-hard), &copy;1988 [20th Century Fox](https://www.20thcenturystudios.com/)
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/dd6b4b3150ed22d531eb0611393434f9d9862f4a/aspnetcore/b …
> [RC1] Blazor WASM respects UI culture setting

- aspnetcore/blazor/host-and-deploy/configure-trimmer.md
Fixes #36126
cc: @hakenr 
Let's see about filling in the additional detail following the work in #36094:
* Move the trimming granularity section up to facilitate the *Configuration* section cross-linking to it with more information.
* Explain the use of `<IsTrimmable>` in the *Configuration* section.
* Cross-link the "explicitly opted in" remark of the *Custom type* section to the *Configuration* section, and add "class libraries" to it to clarify what is being opted-in.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/configure-trimmer.md](https://github.com/dotnet/AspNetCore.Docs/blob/2ef7174f48bc353842359e2c668aeeea2930cce4/aspnetcore/blazor/host-and-deploy/configure-trimmer.md) | [aspnetcore/blazor/host-and-deploy/configure-trimmer](https://review.learn.mi …
> Further opt-in trimming guidance (class libs)

- aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md
Fixes #36137
Thanks @mvxproject! 🚀 
Tom, I had a minute here before wrapping things up for the day, so I thought I toss a quick PR in on this Peter Keller article.
* Fix up the items that are called out [here](https://github.com/dotnet/AspNetCore.Docs/issues/36137#issue-3439419075). Adding `vary-by-culture`, which is [supported back to 3.1](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.cachetaghelperbase.varybyculture).
* Alphabetize the entries.
* Code-fence the headings because they're HTML code.
* Centered the "Default" column.
* Lowercase the word "type" in table column headings.
* I used an em dash for the "Default" for `expires-after` to make sure that no other entry there confuses the reader. However, "None" works, too. Let me know if you prefer …
> Revise Cache Tag Helper documentation attributes

- aspnetcore/fundamentals/minimal-apis.md
- aspnetcore/fundamentals/minimal-apis/includes/parameter-binding10.md
- aspnetcore/fundamentals/minimal-apis/parameter-binding.md
- aspnetcore/includes/net10pipereader.md
- aspnetcore/mvc/models/model-binding.md
Fixes #36030
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/d22649e3c9ccc37962a4493b394d3522d6abd52c/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-36102) |
| [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/d22649e3c9ccc37962a4493b394d3522d6abd52c/aspnetcore/mvc/models/model-binding.md) | [Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=pr-en-us-36102) |
> Docs - Json+PipeReader deserialization support in MVC and Minimal APIs

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Fixes #36143
While working on #36071, I noticed that the article could use a quick edit pass to conform to our styles.
WRT the two links in the reference link list ...
> \[OpenAPI version 3.1]: https://spec.openapis.org/oas/v3.1.1.html
> \[JSON Schema draft 2020-12]: https://json-schema.org/specification-links#2020-12
The first one was only used twice, which I cut down to one use by changing the following line later in the article ...
```diff
- By default, OpenAPI document generation creates a document that is compliant with [OpenAPI version 3.1](https://spec.openapis.org/oas/v3.1.1.html).
+ By default, OpenAPI document generation creates a document that is compliant with the OpenAPI specification.
```
... which should work just as well. The second link was only used once. Therefore, I …
> Edit pass on 'Generate OpenAPI documents'
