- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/blazor/project-structure.md
Fixes #30866
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/394e7abda75101877d62b0ee698d744cd175118e/aspnetcore/blazor/fundamentals/environments.md) | [ASP.NET Core Blazor environments](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-30916) |
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/394e7abda75101877d62b0ee698d744cd175118e/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?branch=pr-en-us-30916) |
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/39 …
> XREFs for location of the Blazor script

- aspnetcore/security/authentication/certauth.md
Follow-up to #30926
---
|:--|:--|
| [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/478c320c2394b189bba5d4dd2f967d0a6a691698/aspnetcore/security/authentication/certauth.md) | [Configure certificate authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?branch=pr-en-us-30927) |
>  48MB --> 48KB

- aspnetcore/blazor/forms/validation.md
---
|:--|:--|
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/cd3c410452fea65c861ca7e32fe87777af561761/aspnetcore/blazor/forms/validation.md) | [ASP.NET Core Blazor forms validation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?branch=pr-en-us-30931) |
> Versioning patch

- aspnetcore/blazor/security/includes/troubleshoot.md
> Place code for test asset cross-link

- aspnetcore/data/entity-framework-6.md
Fixes #29800 
---
|:--|:--|
| [aspnetcore/data/entity-framework-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/d722edec1456a6fc69967364fbf3319b7dfcdea3/aspnetcore/data/entity-framework-6.md) | [ASP.NET Core and Entity Framework 6](https://review.learn.microsoft.com/en-us/aspnet/core/data/entity-framework-6?branch=pr-en-us-30948) |
> Add out-of-date warning

- aspnetcore/fundamentals/minimal-apis.md
Fixes #30878
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0&branch=pr-en-us-30934#validatescopes-and-validateonbuild)  ||  [source code](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/ValidateOnBuildWeb/Program.cs)
- unzip
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/f2966d025027577cfde2b3f34e9d940f2238d98d/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick …
> validate scopes /8

- aspnetcore/fundamentals/native-aot.md
Fixes #30908
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/db6840f83b62a0a2bfccdb40de6a74388ea73c57/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-30966) |
> Update AOT limitations /8

- aspnetcore/migration/70-80.md
Fixes #30971
[internal review url](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&branch=pr-en-us-30989&tabs=visual-studio#docker)
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/ff26797099b488115fe4e779091b572ed43f01b1/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-30989) |
> docker port changes /4

- aspnetcore/host-and-deploy/docker/building-net-docker-images.md
Fixes #30987
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/3071f9f651f82973341cb047e0066074831b4872/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [Docker images for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-30988) |
> Update docker for .NET 8 /3

- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30982
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/35dc991c3bf13bf87b3e4e0660eeb306882794b6/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30983) |
> What's new updates /8

- aspnetcore/fundamentals/aot/native-aot-tutorial.md
- aspnetcore/fundamentals/configuration/index.md
- aspnetcore/fundamentals/native-aot.md
Fixes #30215
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef02228837e8510516b63ab6daea7d7bfd683f7e/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-30991) |
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef02228837e8510516b63ab6daea7d7bfd683f7e/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-30991) |
| …
> config binder /5

- aspnetcore/security/authorization/claims.md
Fix grammar, improve wording consistency and readability. Not sure if "claim-based auth" was written as a singular to intentionally to distinguish it from "claims-based auth" so I left it alone.
---
|:--|:--|
| [aspnetcore/security/authorization/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/db664e0e14a6d9415cd98b728d9f0b34e37eb7fc/aspnetcore/security/authorization/claims.md) | [Claims-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/claims?branch=pr-en-us-30992) |
> Claims article language updates

- aspnetcore/migration/70-80.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Fixes #30979
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/39a582b370126cd27ae5956c66c7d6f1bd8697ce/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-31008) |
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/39a582b370126cd27ae5956c66c7d6f1bd8697ce/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31008) |
> Blazor Migration and What's New updates 8.0

- aspnetcore/release-notes/aspnetcore-8.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/6229d9386447abd76ab664d80f7a57671fc24c69/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31021) |
> Add blog post to What's New (addl resource)

- aspnetcore/tutorials/first-mongo-app.md
- aspnetcore/tutorials/first-mvc-app/adding-controller.md
- aspnetcore/tutorials/first-mvc-app/adding-model.md
- aspnetcore/tutorials/first-mvc-app/adding-view.md
- aspnetcore/tutorials/first-mvc-app/controller-methods-views.md
- aspnetcore/tutorials/first-mvc-app/details.md
- aspnetcore/tutorials/first-mvc-app/new-field.md
- aspnetcore/tutorials/first-mvc-app/search.md
- aspnetcore/tutorials/first-mvc-app/start-mvc.md
- aspnetcore/tutorials/first-mvc-app/validation.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql.md
- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/min-web-api.md
- aspnetcore/tutorials/razor-pages/da1.md
- aspnetcore/tutorials/razor-pages/index.md
- aspnetcore/tutorials/razor-pages/model.md
- aspnetcore/tutorials/razor-pages/new-field.md
- aspnetcore/tutorials/razor-pages/page.md
- aspnetcore/tutorials/razor-pages/razor-pages-start.md
- aspnetcore/tutorials/razor-pages/search.md
- aspnetcore/tutorials/razor-pages/sql.md
- aspnetcore/tutorials/razor-pages/validation.md
- aspnetcore/tutorials/signalr-typescript-webpack.md
Fixes #31013
Includes all topics I own that are multi-version using the new file by include system that did not yet have a not-latest-version.md include. (Not just the Razor getting started series this issue was originally filed on).
A few oddities to call out:  
- Even though the Razor Pages Getting Started series index.md (Overview) file is technically not multi-versioned by include file, I added the not-latest-version.md to be consistent for that whole series.
- There were also a few topics where the not-latestversion.md include was placed after the byline rather than directly after the H1.  So I fixed those as well to be consistent.
- I found two topics that needed to move to file by version yet.  There were no changes needed for them specific to version 7.0 or 8.0, so they were not …
> Include not-latest-version.md in multi-version topics

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
cc: @tdykstra ... Fixed! 👍
... *but there might be some more 😈 in the doc tho!* This was typed up ***awfully fast*** 🏃.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/94c8e25fe2fa14c5c792aef950f58f2f1b598eda/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-31034) |
> Update MapIdentityApi API remark

- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Addresses #31039
---
|:--|:--|
| [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/527d24011569cd6d6daa8099206858b3d5317052/aspnetcore/blazor/webassembly-lazy-load-assemblies.md) | [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?branch=pr-en-us-31040) |
> Add NOTE to WASM lazy load doc

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Addresses #31045
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/d6b405fe09e3691eb790cd20fd01a7f0d25fd884/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-31046) |
> Add role claim remarks

- aspnetcore/blazor/caching-issues.md
- aspnetcore/blazor/http-caching-issues.md
Addresses #31058
---
|:--|:--|
| [aspnetcore/blazor/caching-issues.md](https://github.com/dotnet/AspNetCore.Docs/blob/44b72fa9dbd6ddd1316e14e0804e81020c91d2f6/aspnetcore/blazor/caching-issues.md) | [Avoid HTTP caching issues when upgrading ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/caching-issues?branch=pr-en-us-31075) |
| [aspnetcore/blazor/http-caching-issues.md](https://github.com/dotnet/AspNetCore.Docs/blob/44b72fa9dbd6ddd1316e14e0804e81020c91d2f6/aspnetcore/blazor/http-caching-issues.md) | [aspnetcore/blazor/http-caching-issues](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/http-caching-issues?branch=pr-en-us-31075) |
> Change article name/URL

- .github/workflows/issue-processing.yml
> Update issue workflow processing

- .github/workflows/issue-processing.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/31044
> Update issue workflow process

- .github/workflows/issue-processing.yml
> Update workflow issue processing

- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/js-spa-frameworks.md
Fixes #31107
Thanks @zlajson! :rocket:
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4711321e8d360f28fedf4dc153738fa21e6ff29/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-31109) |
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/e4711321e8d360f28fedf4dc153738fa21e6ff29/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-3110 …
> Update additional Blazor start examples

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/host-and-deploy/index.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/server/interactive-server-side-rendering.md
Fixes #31113
Thanks @RobJDavey! 🚀 ... I'm going to fix the one spot on the auth attribute now. I'll be having a meeting with the product unit shortly on the hub configuration aspects. That meeting is already planned to occur within a week, so I've added some notes to the articles for `MapBlazorHub` to get the other handful of spots updated after I meet with them. Turns out that there are several related Blazor hub questions to address. Because the meeting and notes are tracked separately, I'll go ahead and close out your issue with this PR. Thanks again for the issue.
... and if the code that I gave you doesn't work, ping me back on your issue at #31113. I'll re-open that and hit up a product unit engineer for assistance. Of course, we won't be able to do that until next week, especially …
> Apply auth attribute update & Blazor hub notes

- aspnetcore/blazor/fundamentals/routing.md
Fixes #31092
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/a5732239d6b668e46de4b6accc14f1a5c1d6ca65/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-31127) |
> `<Navigating>` content update

- .github/ISSUE_TEMPLATE/doc-issue.md
Addresses #31144 
Thanks @Porkechebure! ... I'm updating the issue template here. Rick will get back to you on your routing issue shortly.
---
|:--|:--|
| [.github/ISSUE_TEMPLATE/doc-issue.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d2968b7be858cfc4fd75759e0f3bf794ce24768/.github/ISSUE_TEMPLATE/doc-issue.md) | [Before you open an issue](https://review.learn.microsoft.com/en-us/aspnet/core/.github/ISSUE_TEMPLATE/doc-issue?branch=pr-en-us-31146) |
> Update the doc issue template

- aspnetcore/docfx.json
See https://github.com/dotnet/docs/pull/38464
> Update docfx.json - fix feedback product name

- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Addresses #31153
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/4729ecf84f39a53f9f3fccb31d23bc73e24897a2/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-31166) |
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/4729ecf84f39a53f9f3fccb31d23bc73e24897a2/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?branch=pr-en-us-31166) |
| …
> API doc cross-link updates

- aspnetcore/blazor/components/render-modes.md
Fixing typo.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/bd8c404cb22064bff4940b81db3a2441bc41cd27/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-31169) |
> Improve render modes remark

- aspnetcore/blazor/components/event-handling.md
Fixes #31174
Thanks @puppetSpace! 🚀 ... I'll take this live a few minutes after it merges. It should appear on the live docs website within 15 minutes or so.
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/d93102bcc0e26866582104dfaf9e786ebf713520/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-31175) |
> Fix custom event example

- aspnetcore/log-mon/metrics/metrics.md
* Change link to built in metrics to use local documentation
* Link to dashboards on grafana.com
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/66997b9c99dd472bb17780875dbc86879b448069/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-31141) |
> Update ASP.NET Core metrics

- aspnetcore/diagnostics/asp0018.md
---
|:--|:--|
| [aspnetcore/diagnostics/asp0018.md](https://github.com/dotnet/AspNetCore.Docs/blob/9efb7a956e9e93ca2589889c191e9c8e487544a0/aspnetcore/diagnostics/asp0018.md) | [ASP0018: Unused route parameter](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018?branch=pr-en-us-31168) |
> Fix typo in asp0018.md and add solution

- aspnetcore/docfx.json
Corresponds to https://github.com/dotnet/docs/pull/38543 in the dotnet/docs repo.
> Update docfx.json - remove product description

- aspnetcore/tutorials/choose-web-ui.md
- aspnetcore/tutorials/choose-web-ui/includes/choose-web-ui3-7.md
Fixes #31032 
Changing topic to versioning by include file.  Minor change.
---
|:--|:--|
| [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/698ad13413b9f09fb4be580d06bf14f8b7212061/aspnetcore/tutorials/choose-web-ui.md) | [Choose an ASP.NET Core web UI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?branch=pr-en-us-31199) |
> ChooseWebUI versioning by include

- aspnetcore/razor-pages/ui-class/6samples/cli/WebApp1/Program.cs
- aspnetcore/razor-pages/ui-class/includes/ui-class6.md
Fixes #31142
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&branch=pr-en-us-31165&tabs=visual-studio#consume-content-from-a-referenced-rcl)
- unzip
> Fix .NET 6 case

- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/hybrid/tutorials/windows-forms.md
- aspnetcore/blazor/hybrid/tutorials/wpf.md
Fixes #30438
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/8ad2064c6be1c97ab74783d8d0bb10c5e010217b/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-31232) |
| [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/8ad2064c6be1c97ab74783d8d0bb10c5e010217b/aspnetcore/blazor/hybrid/tutorials/windows-forms.md) | [Build a Windows Forms Blazor app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?branch=pr-en-us-31232) |
| …
> Apply 'data-nosnippet' to error UI

- aspnetcore/blazor/components/event-handling.md
Fixes #31234
Thanks @markharwood101! 🚀
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/5511996f035b5691c03d7c9e7d6199e859870629/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-31235) |
> Improve language

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/hybrid/security/index.md
- aspnetcore/host-and-deploy/azure-apps/index.md
- aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md
- aspnetcore/migration/22-to-30.md
- aspnetcore/security/authentication/azure-active-directory/index.md
- aspnetcore/security/authentication/windowsauth.md
- aspnetcore/signalr/javascript-client.md
- aspnetcore/toc.yml
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b64ca32a3b21abedba1f0da7e3b5bc2ad99a9f3/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31249) |
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b64ca32a3b21abedba1f0da7e3b5bc2ad99a9f3/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values- …
> Code snippet updates

- aspnetcore/security/authentication/identity-api-authorization.md
Fixes #31196 
---
|:--|:--|
| [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/a860dba63cc334c03eff6e90fde3947b15809add/aspnetcore/security/authentication/identity-api-authorization.md) | [How to use Identity to secure a Web API backend for SPAs](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?branch=pr-en-us-31197) |
> Document `MapIdentityApi<TUser>` endpoints

- aspnetcore/security/enforcing-ssl.md
Fixes #31256
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/e79e19cf916852e838dd2b9b6dc819d87df3672b/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-31255) |
> Update guide on Ubuntu 21.10 Firefox snap changes

- .github/workflows/issue-processing.yml
> Issue processing update

- aspnetcore/blazor/javascript-interoperability/import-export-interop.md
- aspnetcore/client-side/dotnet-interop.md
Fixes #31291
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/7b07f8ec6238a7c67e0a8ecd2a7a89f80488aa8e/aspnetcore/blazor/javascript-interoperability/import-export-interop.md) | [JavaScript `[JSImport]`/`[JSExport]` interop with ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?branch=pr-en-us-31292) |
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/7b07f8ec6238a7c67e0a8ecd2a7a89f80488aa8e/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-3 …
> Link fixes

- aspnetcore/blazor/includes/location-client-and-server-pre-net8.md
> Removing the extra "the"

- aspnetcore/blazor/test.md
Fixes #31299
Thanks @egil! 🎷
---
|:--|:--|
| [aspnetcore/blazor/test.md](https://github.com/dotnet/AspNetCore.Docs/blob/714bb9caf9d0fda7e516fb19e111c372470430e3/aspnetcore/blazor/test.md) | [Test Razor components in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/test?branch=pr-en-us-31300) |
> Cross-link bUnit Oslo '22

- aspnetcore/blazor/javascript-interoperability/import-export-interop.md
Fixes #31331
Thanks @hawkerm! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/42579178d31612d1eb2a36b07b9aaeb061e89bea/aspnetcore/blazor/javascript-interoperability/import-export-interop.md) | [JavaScript `[JSImport]`/`[JSExport]` interop with ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?branch=pr-en-us-31332) |
> Improve lead-in remarks

- aspnetcore/blazor/includes/js-interop/js-collocation.md
> Language updates

- aspnetcore/security/cors.md
Fixes #31308 
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/67704d5df30d5b811addcd846c6adb67ab1062de/aspnetcore/security/cors.md) | [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-31338) |
> Move prior version include to end

- aspnetcore/fundamentals/minimal-apis/includes/webapplication8.md
Before fix example description was placed after code block in subsequent section. After fix its placed before example like in webapplication7.md
> Example description position fix

- aspnetcore/web-api/handle-errors.md
See https://github.com/dotnet/aspnetcore/issues/52414 for more info.
---
|:--|:--|
| [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/9725dc70b45fcbe9e8285e95611aea7102b396f3/aspnetcore/web-api/handle-errors.md) | [Handle errors in ASP.NET Core web APIs](https://review.learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?branch=pr-en-us-31345) |
> Update link to supported ProblemDetails RFC

- aspnetcore/host-and-deploy/health-checks.md
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Extensions/SampleHealthCheckBuilderExtensions.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthCheckPublishers/SampleHealthCheckPublisher.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecks/SampleHealthCheck.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecks/SampleHealthCheckWithArgs.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecks/SampleHealthCheckWithDI.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecks/StartupHealthCheck.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/HealthChecksSample.csproj
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Program.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Services/StartupBackgroundService.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Snippets/Program.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Snippets/SampleDbContext.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/Snippets/SampleHealthCheckOptions.cs
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/appsettings.Development.json
- aspnetcore/host-and-deploy/health-checks/samples/8.x/HealthChecksSample/appsettings.json
Sample prep for #31143
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/89e53c5870de62810adef4929d97863bda3234b0/aspnetcore/host-and-deploy/health-checks.md) | [Health checks in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-31356) |
> sample prep /8

- aspnetcore/blazor/components/index.md
"fist" -> "first"
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/f8c956ad1d2a2e2bb92c3245f681c08e4fec59f6/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-31358) |
> Minor typo

- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/input-components.md
- aspnetcore/blazor/forms/troubleshoot.md
- aspnetcore/blazor/forms/validation.md
Fixes  #31360
Thanks @sikora507! 🚀  ... I'll take this live right after it builds. It will pull the updated code examples from the `dotnet/blazor-samples` repo. That PR reverted the forms examples back to "`Id'" in the classes and components. Thanks again for the report. BTW - I'm using yesterday's date to trigger the rebuild here because I'm working on the sample apps right now, and I may have some other updates to perform later today and need to do this one more time with a date update. 
---
|:--|:--|
| [aspnetcore/blazor/forms/binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/731e5e0cdb720d6ec1753acc5be33b358890a287/aspnetcore/blazor/forms/binding.md) | [ASP.NET Core Blazor forms binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fo …
> Update forms articles

- aspnetcore/blazor/components/js-spa-frameworks.md
Fixes #31372
Thanks @josephaw1022! :rocket:
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0b7b602a2656da4c2eb64c6a888cf9771d1356c/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-31374) |
> Add component example

- aspnetcore/tutorials/first-mvc-app/adding-model.md
- aspnetcore/tutorials/first-mvc-app/adding-model/includes/adding-model7.md
- aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie70/Program.cs
- aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie80/Program.cs
Fixes #31367
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/5686c7d00a8afd1d89e688d3b5f782bda6d1250d/aspnetcore/tutorials/first-mvc-app/adding-model.md) | [Part 4, add a model to an ASP.NET Core MVC app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?branch=pr-en-us-31369) |
> First MVC: fix missing VSC code

- aspnetcore/grpc/interprocess-namedpipes.md
- aspnetcore/grpc/interprocess-uds.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2350
---
|:--|:--|
| [aspnetcore/grpc/interprocess-namedpipes.md](https://github.com/dotnet/AspNetCore.Docs/blob/f5c87a824e8c4bf3b5413f3aef54a032357a1ea8/aspnetcore/grpc/interprocess-namedpipes.md) | [Inter-process communication with gRPC and Named pipes](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-namedpipes?branch=pr-en-us-31362) |
| [aspnetcore/grpc/interprocess-uds.md](https://github.com/dotnet/AspNetCore.Docs/blob/f5c87a824e8c4bf3b5413f3aef54a032357a1ea8/aspnetcore/grpc/interprocess-uds.md) | [Inter-process communication with gRPC and Unix domain sockets](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-uds?branch=pr-en-us-31362) |
> Add note to IPC docs that it can't be combined with some channel features

- aspnetcore/host-and-deploy/linux-nginx.md
- aspnetcore/host-and-deploy/linux-nginx/includes/linux-nginx5.md
Fixes 
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/fa2253217e7e9b2e058cdfa1b8e087bc1b299f4d/aspnetcore/host-and-deploy/linux-nginx.md) | [Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-31399) |
> replace DOTNET_PRINT_TELEMETRY_MESSAGE with DOTNET_NOLOGO  /7

- aspnetcore/blazor/components/quickgrid.md
Fixes #31023
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/91c6c91feedff6ce32d1cb76779b5c4e9b49945b/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-31427) |
> Blazor CRUD/Quickgrid scaffolder

- aspnetcore/host-and-deploy/azure-apps/index.md
---
|:--|:--|
| [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/66ce02ebe0e12a11198bc494e8bb7811c14b0ef3/aspnetcore/host-and-deploy/azure-apps/index.md) | [Deploy ASP.NET Core apps to Azure App Service](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/index?branch=pr-en-us-31432) |
> Update doc author note

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/performance.md
Fixes #31449
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/1249fd3357caca40dd5eca022aea7c99a15115dc/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-31450) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/1249fd3357caca40dd5eca022aea7c99a15115dc/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-31450) |
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/1249fd33 …
> Calling base class methods

- aspnetcore/grpc/error-handling.md
- aspnetcore/toc.yml
Docs about gRPC error handling and the new rich error handing.
Ready for review, **not ready for merge** (waiting for error handling to be released).
---
|:--|:--|
| [aspnetcore/grpc/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/901de106e1fbe59b804875fc66aba58815af1d5c/aspnetcore/grpc/error-handling.md) | [aspnetcore/grpc/error-handling](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/error-handling?branch=pr-en-us-31386) |
---
|:--|:--|
| [aspnetcore/grpc/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/63dd44c8b3bcef1775ab86b71492e90d692dea27/aspnetcore/grpc/error-handling.md) | [aspnetcore/grpc/error-handling](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/error-handling?bra …
> Add gRPC error handling doc

- aspnetcore/security/authorization/resourcebased.md
Fixes #31486
---
|:--|:--|
| [aspnetcore/security/authorization/resourcebased.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a477949a6d3154d7d360c3e0c01177579cca583/aspnetcore/security/authorization/resourcebased.md) | [Resource-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?branch=pr-en-us-31491) |
> remove startup from resourcebased.md

- aspnetcore/blazor/components/virtualization.md
Fixes #31498
---
|:--|:--|
| [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/642a878adcd4a0bbde6baa8c04ebfff90843a1dd/aspnetcore/blazor/components/virtualization.md) | [ASP.NET Core Razor component virtualization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?branch=pr-en-us-31499) |
> Clarify 'content items' (placeholder content)

- aspnetcore/fundamentals/host/generic-host.md
- aspnetcore/fundamentals/host/web-host.md
Fixes #31493 
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/06cd0d498dc260ff5e354025d417f9cc3cfba316/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-31505) |
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/06cd0d498dc260ff5e354025d417f9cc3cfba316/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-31505) |
> Fix default value of PreferHostingUrls

- aspnetcore/migration/70-80.md
<!--
Added missing / for documentation. 
https://github.com/dotnet/AspNetCore.Docs/issues/31494#issuecomment-1900080814
> Added missing closing tag for package ref. 

- aspnetcore/client-side/spa/includes/angular3-7.md
- aspnetcore/client-side/spa/intro/samples/Ang_proxy.conf.js
- aspnetcore/client-side/spa/intro/samples/setupProxy.js
- aspnetcore/fundamentals/host/web-host.md
- aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker/samples/2.1/docker-compose.override.yml
- aspnetcore/security/authorization/limitingidentitybyscheme/samples/AuthScheme/ClientApp/proxy.conf.js
- aspnetcore/security/docker-https.md
- aspnetcore/security/enforcing-ssl.md
Fixes #31536
Addresses #31533
I think this gets all of them 😈.
---
|:--|:--|
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/f151ae1114338cb9761dba337de59b878d3b7019/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-31538) |
| [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/f151ae1114338cb9761dba337de59b878d3b7019/aspnetcore/security/docker-https.md) | [Hosting ASP.NET Core Images with Docker over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-https?branch=pr-en-us-31538) |
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/As …
> Update env var name

- aspnetcore/migration/60-70.md
Added missing "/" in two locations. 
---
|:--|:--|
| [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/12e2e5c586613078ade99a3af99c2eaa58351622/aspnetcore/migration/60-70.md) | [Migrate from ASP.NET Core 6.0 to 7.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/60-70?branch=pr-en-us-31550) |
> Update 60-70.md - added missing closing tag

- aspnetcore/tutorials/min-web-api/samples/8.x/todo/Message.cs
> Remove sample namespace

- aspnetcore/blazor/tooling.md
Fixes #31572
Thanks @jez9999! 🚀 
As @jez9999 implies, recommending the BWA template doesn't mirror any remarks elsewhere (Blazor *Overview* and *Hosting Models* docs in particular) that the choice between BWA or WASM has anything other than to do with the specification required by the organization for the app. There's no obvious cosmic reason to avoid WASM apps if they're a perfect fit for the spec.
Alternatively if there is some reason that I'm unaware of to favor BWAs outside of the benefits that we've already covered, I think we should state what that is, probably by also including it in the Blazor *Overview* and *Hosting Models* articles.
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/ba92006ed5c34ecaefed0b0c53f …
> Revise template recommendation

- aspnetcore/toc.yml
> Move "What's new in docs" to the end of the what's new section

- aspnetcore/fundamentals/minimal-apis/security.md
The sentence:
> Minimal **app's** support loading...
Should read:
> Minimal **apps** support loading...
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/c830a8f5dced74c69c30534fbe3b3b60f49da360/aspnetcore/fundamentals/minimal-apis/security.md) | [Authentication and authorization in minimal APIs](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?branch=pr-en-us-31581) |
> Fix typo in security.md

- aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #31534
Thanks @shui106! :rocket:
Not directly related to the fixes: The <6.0 code going away 🔪. I'm dropping the non-NRT in-text code examples everywhere these days.
Javier, I was hoping it would deserialize with ...
```csharp
User = await JS.InvokeAsync<Profile>("sessionStorage.getItem", "resumeSavingProfile");
```
... but that's apparently not a thing because it 💥 claiming it can't deserialize into the `Profile` type. I had to resort to taking the string from `getItem` and using a separate call to get `User`.
Here's a test component if you want to see the 💥, but I think you'll know why it fails for me just by looking at it ...
```razor
@page "/test"
@using System.Text.Json
@inject IJSRuntime JS
@inject NavigationManager Navigation
<EditForm Model="@User" OnSubmit="@OnSaveAsync"> …
```
> Update save app state example

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md
- aspnetcore/security/authentication/accconfirm.md
- aspnetcore/toc.yml
Fixes #31383
Thanks @DwayneSelsig! 🚀 
Stephen ...
It's a little rough around the edges given that I just typed this all up over the last few hours, but the good news is that it ...
Can you review the technical aspects and just make sure I haven't created any *Rex code smells* 💩👃😬?
... and I don't think we're going to carry guidance in this for the commented-out *Combine social and local login accounts* section. I'm probably going to 🔪 that in the morning.
cc: @Rick-Anderson ... This was based on your article with mods. I went with Mailchimp because SendGrid has some kind of nasty looking malware at their website according to Malwarebytes. Mailchimp (Mandrill.net) was easy to set up and use for a test, so I went with that. I don't think it matters all that much which …
> Account conf and PW recovery article

- aspnetcore/host-and-deploy/linux-nginx.md
Fixes #31590
Thanks @yogyogi! 🚀 
---
|:--|:--|
| [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f02b4041b53a4de265051e8f41010bb6d2f3bc9/aspnetcore/host-and-deploy/linux-nginx.md) | [Host ASP.NET Core on Linux with Nginx](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?branch=pr-en-us-31594) |
> Indicate shared framework package

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/blazor/fundamentals/configuration.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/progressive-web-app.md
- aspnetcore/blazor/security/content-security-policy.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/graph-api.md
Fixes #31600
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e7a7a3da82e9856abd699c8a72156be3df2079b/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31601) |
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e7a7a3da82e9856abd699c8a72156be3df2079b/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-31601) |
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e7a7a3da82e9856abd699c8a72156be3df2079b/aspnetcore/blazo …
> "Base address" clarifications for `HttpClient`

- aspnetcore/fundamentals/app-state.md
Fixes #31593 
---
|:--|:--|
| [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/365d0a10efeda3d2dec3a99fbbea60c71d123b04/aspnetcore/fundamentals/app-state.md) | [Session and state management in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?branch=pr-en-us-31605) |
> Microsoft.AspNetCore.Session package is deprecated

- aspnetcore/fundamentals/minimal-apis/security.md
Fixes dotnet#31610
For ASP.NET Core 8.0 documentation, replaced occurrence of word "authentication" by "authorization" in article "Authentication and authorization in minimal APIs".
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/99963ad3138489925e922dfba250565c9c6accbd/aspnetcore/fundamentals/minimal-apis/security.md) | [Authentication and authorization in minimal APIs](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?branch=pr-en-us-31611) |
> Change occurrence of word "authentication" for "authorization".

- aspnetcore/blazor/security/includes/troubleshoot.md
- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
Fixes #31586
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/407d61b5aa63182ee4d54175bb3731795bfde4eb/aspnetcore/blazor/security/webassembly/graph-api.md) | [Use Graph API with ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?branch=pr-en-us-31617) |
| [aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/407d61b5aa63182ee4d54175bb3731795bfde4eb/aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md) | [Microsoft Entra (ME-ID) groups, Administrator Roles, and App …
> Groups/roles article and Graph article updates

- aspnetcore/performance/caching/distributed.md
Fixes #31577 
---
|:--|:--|
| [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f9e92993e33ab634760dfdc17c0ca88842b308d/aspnetcore/performance/caching/distributed.md) | [Distributed caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?branch=pr-en-us-31607) |
> Add Azure Cosmos DB

- aspnetcore/mvc/views/view-components/sample6.x/ViewCompFinal/Views/ToDo/Index.cshtml
> Small typo corrected in Index view

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/hybrid/index.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/c452ccaea5182959e58a60d3ad0c6f3de403865b/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31630) |
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/c452ccaea5182959e58a60d3ad0c6f3de403865b/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA …
> Blazor 8.0 content updates

- aspnetcore/grpc/client.md
Improve docs based on offline questions about channels.
---
|:--|:--|
| [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/851f76b792dc4dd70e9c6d2c5d11685262dcc533/aspnetcore/grpc/client.md) | [Call gRPC services with the .NET client](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/client?branch=pr-en-us-31624) |
> gRPC channel reconnection

- aspnetcore/test/integration-tests.md
Fixes #31418
---
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/639cae9d4318a9a4e91ed000897ef05676669587/aspnetcore/test/integration-tests.md) | [Integration tests in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-31609) |
> Explain integration test  WebHostBuilderSection

- aspnetcore/fundamentals/minimal-apis.md
Fixes #31636
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/e403ae82d1802e3b1fecb6ed622df7a367b198a1/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-31637) |
> Add links to Fluent Validaton /2

- aspnetcore/security/authentication/individual.md
Fixes #31646 
---
|:--|:--|
| [aspnetcore/security/authentication/individual.md](https://github.com/dotnet/AspNetCore.Docs/blob/6eefe8d981353cba3865a1946e1d35cae6ec30d4/aspnetcore/security/authentication/individual.md) | [Articles based on ASP.NET Core projects created with individual user accounts](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/individual?branch=pr-en-us-31648) |
> Azure AD --> Entra ID

- aspnetcore/fundamentals/localization.md
- aspnetcore/fundamentals/localization/make-content-localizable.md
- aspnetcore/fundamentals/localization/provide-resources.md
- aspnetcore/fundamentals/localization/select-language-culture.md
Fixes 31426
---
|:--|:--|
| [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/d1cf7f99b947679de88f1bf58f9efc8c528149e3/aspnetcore/fundamentals/localization.md) | [Globalization and localization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?branch=pr-en-us-31606) |
| [aspnetcore/fundamentals/localization/make-content-localizable.md](https://github.com/dotnet/AspNetCore.Docs/blob/d1cf7f99b947679de88f1bf58f9efc8c528149e3/aspnetcore/fundamentals/localization/make-content-localizable.md) | [Make an ASP.NET Core app's content localizable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?branch=pr-en-us-31606) |
| …
> RouteDataRequestCultureProvider /8

- aspnetcore/security/authentication/individual.md
Fixes #31660 
---
|:--|:--|
| [aspnetcore/security/authentication/individual.md](https://github.com/dotnet/AspNetCore.Docs/blob/5bd83585ef434fa72b831922598cc45700f64bef/aspnetcore/security/authentication/individual.md) | [Articles based on ASP.NET Core projects created with individual user accounts](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/individual?branch=pr-en-us-31661) |
> Note that Entra External ID tenants also use SingleOrg for --auth option

- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #31674
Thanks @markarnolditpro! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/581bc52b3f43854e04c685d48a68d0f44cadb755/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-31675) |
> Update JS interop intro

- aspnetcore/blazor/security/index.md
Fixes #31681
Thanks @rouxjonathan! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/80a694f20ea9965af04ab04ecece2b6b065a59ad/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-31682) |
> Add a remarks on ClaimsPrincipal use

- aspnetcore/blazor/components/built-in-components.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/hybrid/root-component-parameters.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/security/index.md
Fixes #31679
Thanks @hakenr ! 🎸 ... Looking better. I also found a 😈 ... the *Routing* article's `NavMenu`/`NavLink` section dropped `NavMenu` content at some point, so that section can be renamed with cross-link updates. If you want to review, I intend to merge this on Monday morning 🏃‍♂️.
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe70b1b4b6a1ce3e11ce53301ebc7e776db1ce8a/aspnetcore/blazor/components/built-in-components.md) | [ASP.NET Core built-in Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-31684) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe70b1b4b6a1ce3e1 …
> Revise built-in components list

- aspnetcore/blazor/components/lifecycle.md
Fixes #31690
Thanks @ShaunCurtis! 🏍️ ... If you want to review, please look quickly. I'm experiencing quite a lot of churn right now in Blazor docs and wish to avoid ***merge conflicts*** 😈.
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/cf2427fda19e98d3f7e2deaacb2adca4a86270db/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-31695) |
> Lifecycle methods call ordering

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/newFeature1.md
Fixes #31698
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a12c954cfa0d7136fe2b566f746b548abd6465c/aspnetcore/release-notes/aspnetcore-9.0.md) | [aspnetcore/release-notes/aspnetcore-9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-31700) |
> What's new in ASP.NET Core 9.0 stub

- aspnetcore/data/ef-mvc/migrations.md
- aspnetcore/fundamentals/choose-aspnet-framework.md
- aspnetcore/fundamentals/host/platform-specific-configuration.md
- aspnetcore/razor-pages/sdk.md
- aspnetcore/razor-pages/ui-class.md
- aspnetcore/security/authentication/2fa.md
- aspnetcore/security/authentication/add-user-data.md
- aspnetcore/security/authentication/azure-active-directory/index.md
- aspnetcore/security/authentication/jwt-authn.md
- aspnetcore/security/authentication/social/facebook-logins.md
- aspnetcore/security/authentication/social/google-logins.md
- aspnetcore/security/authentication/windowsauth.md
- aspnetcore/security/authorization/secure-data.md
- aspnetcore/security/data-protection/extensibility/key-management.md
- aspnetcore/security/key-vault-configuration.md
- aspnetcore/tutorials/first-mongo-app.md
- aspnetcore/tutorials/first-mvc-app/adding-controller.md
- aspnetcore/tutorials/first-mvc-app/adding-model.md
- aspnetcore/tutorials/first-mvc-app/adding-view.md
- aspnetcore/tutorials/first-mvc-app/start-mvc.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql.md
Remove expired ms.custom values
CorrelationId: be4e6f69-4173-4365-a9c5-e7e7557a20cb
PointOfContact: @kcpitt
#docutune
---
|:--|:--|
| [aspnetcore/data/ef-mvc/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/data/ef-mvc/migrations.md) | [Tutorial: Part 5, apply migrations to the Contoso University sample](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?branch=pr-en-us-31656) |
| [aspnetcore/fundamentals/choose-aspnet-framework.md](https://github.com/dotnet/AspNetCore.Docs/blob/740e5091170adce9a1c4adb0a892b2e9e51fecda/aspnetcore/fundamentals/choose-aspnet-framework.md) | [Choose between ASP.NET 4.x …
> [BULK] - DocuTune - Remove expired ms.custom values

- aspnetcore/release-notes/aspnetcore-8.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d7625a3b909a5df9363e83878bdb83b05247b2ca/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-31719) |
> Fix heading level

- aspnetcore/razor-pages/ui-class.md
Fixes #24808
---
|:--|:--|
| [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/068f699de1cebaa53945a26afc6343ee292ecba7/aspnetcore/razor-pages/ui-class.md) | [Create reusable UI using the Razor class library project in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?branch=pr-en-us-31736) |
> RCL, adding static web assets

- aspnetcore/fundamentals/logging/index.md
Fixes #31732
---
|:--|:--|
| [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/95a78f67d4689e662ca77631faa9290638f61de8/aspnetcore/fundamentals/logging/index.md) | [Logging in .NET Core and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?branch=pr-en-us-31733) |
> Remove generic host

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
This will require 2 new keys that I'll need to configure with Rick's help.
> Add org level app keys

- aspnetcore/signalr/redis-backplane.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane6.md
- aspnetcore/signalr/redis-backplane/includes/redis-backplane7.md
Updated and tested for .NET 8
Fixes #31631
---
|:--|:--|
| [aspnetcore/signalr/redis-backplane.md](https://github.com/dotnet/AspNetCore.Docs/blob/4205f2f86d8d44db36e740fb87652f4e71965a64/aspnetcore/signalr/redis-backplane.md) | [Set up a Redis backplane for ASP.NET Core SignalR scale-out](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?branch=pr-en-us-31756) |
> SignalR Redis Backplane update and fix

- aspnetcore/blazor/fundamentals/environments.md
Fixes #31767
Thanks @Stra1ghter! 🚀 ... These updates won't necessarily help with your PU issue, but it will be clearer that we intend devs to access the main doc set's article for BWA environment configuration. I set that out now with a new section heading, and I call out for each approach covered for Blazor (that generally wouldn't be available to non-Blazor apps) what type of app each approach applies to.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/9c24f0c1a5fbb44b474163d10793e41e58a27f75/aspnetcore/blazor/fundamentals/environments.md) | [ASP.NET Core Blazor environments](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-31768) |
> Improve Blazor Environments article

- aspnetcore/data/ef-mvc/intro.md
Fixes #31761 
---
|:--|:--|
| [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/19b1ed258cc68f7da81b37bd060fe57626e99ceb/aspnetcore/data/ef-mvc/intro.md) | [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?branch=pr-en-us-31771) |
> Change reference to .NET 6 and 7 to .NET 6 and later

- aspnetcore/migration/70-80.md
- aspnetcore/migration/80-90.md
- aspnetcore/migration/80-to-90/includes/blazor.md
- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Addresses #31699
What do you guys think about using the INCLUDE approach for Migration guidance? The skeleton setup for it is on this PR. If not, no worries ... I'll back those pieces out of this. 👂
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/3617946ecca7770ccc883a5e36ca286079ec9296/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core 7.0 to 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-31762) |
| [aspnetcore/migration/80-90.md](https://github.com/dotnet/AspNetCore.Docs/blob/3617946ecca7770ccc883a5e36ca286079ec9296/aspnetcore/migration/80-90.md) | [aspnetcore/migration/80-90](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?branch=pr-en-us-31 …
> Blazor What's New guidance

- aspnetcore/fundamentals/aot/includes/aot_lib.md
- aspnetcore/fundamentals/aot/includes/aot_preview.md
- aspnetcore/fundamentals/aot/native-aot-tutorial.md
- aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md
- aspnetcore/fundamentals/aot/request-delegate-generator/rdg.md
- aspnetcore/fundamentals/host/hosted-services.md
- aspnetcore/fundamentals/native-aot.md
- aspnetcore/grpc/native-aot.md
- aspnetcore/release-notes/aspnetcore-8.0.md
Per docs https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows
---
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/d8c56521bbb4cd7e9b904d9993ccce7e3ab72def/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-31777) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md](https://github.com/dotnet/AspNetCore.Docs/blob/d8c56521bbb4cd7e9b904d9993ccce7e3ab72def/aspnetcore/fundamentals/aot/request-delegate-generator/rdg-ids.md) | [ASP.NET Core Request Delegate Generator (RDG) …
> Update to Native capitalization

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/data-binding.md
- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/hybrid/tutorials/maui.md
- aspnetcore/blazor/javascript-interoperability/import-export-interop.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/blazor/performance.md
- aspnetcore/blazor/progressive-web-app.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/security/includes/authentication-component.md
- aspnetcore/blazor/security/includes/fetchdata-component.md
- aspnetcore/blazor/security/includes/redirecttologin-component.md
- aspnetcore/blazor/security/includes/troubleshoot.md
- aspnetcore/blazor/security/includes/usermanager-signinmanager.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/server/index.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/blazor/state-management.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
Addresses #31773
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/f1e0498202c723e9498173e200a5c7ba1fdc790c/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31783) |
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/f1e0498202c723e9498173e200a5c7ba1fdc790c/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values- …
> Update "ASP.NET Core" references

- aspnetcore/diagnostics/asp0013.md
Fixes #31742
---
|:--|:--|
| [aspnetcore/diagnostics/asp0013.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f5e237be4186df9c852a6eb41527950f876ce78/aspnetcore/diagnostics/asp0013.md) | [ASP0013: Suggest switching from using Configure methods to WebApplicationBuilder.Configuration](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0013?branch=pr-en-us-31750) |
> Don't use Config with minimal APIs

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/debugger.md
- aspnetcore/release-notes/aspnetcore-9/includes/signalr.md
Fixes #31699 
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/52028861a6fa4db1b03a93d33761d271777fcaa1/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-31792) |
> .NET 9 Preview 1

- CONTRIBUTING.md
Fixes #31812
---
|:--|:--|
| [CONTRIBUTING.md](https://github.com/dotnet/AspNetCore.Docs/blob/8925aea2939f66d0ab02cbca4de1c0b18ffbc5e6/CONTRIBUTING.md) | [Contribute to the ASP.NET Core documentation](https://review.learn.microsoft.com/en-us/aspnet/core/CONTRIBUTING?branch=pr-en-us-31813) |
> fix: #31812 broken URL

- aspnetcore/blazor/webassembly-native-dependencies.md
Fixes #31818
---
|:--|:--|
| [aspnetcore/blazor/webassembly-native-dependencies.md](https://github.com/dotnet/AspNetCore.Docs/blob/f28a5ee37bb9eb28032f8f9c87a1ec5152a3b0f7/aspnetcore/blazor/webassembly-native-dependencies.md) | [ASP.NET Core Blazor WebAssembly native dependencies](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?branch=pr-en-us-31819) |
> fix: #31818 broken hyperlink

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #31816
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0ff6e5ac2b5ca91ea46db0d933a5bee546f294d/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-31817) |
> fix: #31816

- aspnetcore/grpc/supported-platforms.md
Fixes #31820
---
|:--|:--|
| [aspnetcore/grpc/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/3ece620c227a75c8bf48c0ab8e35b0b79c7116fb/aspnetcore/grpc/supported-platforms.md) | [gRPC on .NET supported platforms](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?branch=pr-en-us-31821) |
> fix: #31820 broken hyperlink

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31796
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/c3220be7d3206f0ac5fd28027c53f7371b5a3f24/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-31823) |
> Add additional resource link

- aspnetcore/blazor/javascript-interoperability/import-export-interop.md
- aspnetcore/client-side/dotnet-interop.md
- aspnetcore/fundamentals/startup/6.0_samples/WebAll/README.md
- aspnetcore/security/authorization/claims/samples/6.x/WebAll/README.md
- aspnetcore/security/authorization/roles/samples/6_0/WebAll/README.md
Fixes #31822
Thanks @stanimirovv! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/74d79807ecf45a15fd45a170ba786a250c124468/aspnetcore/blazor/javascript-interoperability/import-export-interop.md) | [JavaScript `[JSImport]`/`[JSExport]` interop with ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?branch=pr-en-us-31824) |
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/74d79807ecf45a15fd45a170ba786a250c124468/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-i …
> Update broken links

- aspnetcore/includes/net-prereqs-vsc-9.0.md
- aspnetcore/migration/80-90.md
- aspnetcore/toc.yml
Fixes #31790 
---
|:--|:--|
| [aspnetcore/migration/80-90.md](https://github.com/dotnet/AspNetCore.Docs/blob/5705b888b62135090946a3f83895d4b0ca1edb1d/aspnetcore/migration/80-90.md) | [Migrate from ASP.NET Core in .NET 8 to ASP.NET Core in .NET 9](https://review.learn.microsoft.com/en-us/aspnet/core/migration/80-90?branch=pr-en-us-31831) |
> Follow-up to 31806

- aspnetcore/security/authentication/azure-ad-b2c.md
- aspnetcore/security/authentication/azure-ad-b2c/sample/Program.cs
fixes https://github.com/dotnet/AspNetCore.Docs/issues/23287
Most was already fixed. cleaned up the dontet link and removed the AddControllers
Greetings Damien
---
|:--|:--|
| [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/d39e0077f1e0a4e376bd0c27d9f17458aef064a4/aspnetcore/security/authentication/azure-ad-b2c.md) | [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?branch=pr-en-us-31737) |
> Azure AD B2C, improve texts, use default dotnet download link

- aspnetcore/security/enforcing-ssl.md
Fixes  #31834
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/a1cf7736b5397349fe1f5909ead5f902577f2d5f/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-31833) |
> set URLs_7

- aspnetcore/blazor/components/quickgrid.md
Fixes #31842
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/004cb41acff2d3f6dee44e8a20e35063dc5331c6/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-31843) |
> Remove "preview" language

- aspnetcore/blazor/fundamentals/handle-errors.md
Grabbing the new sample code introduced on https://github.com/dotnet/blazor-samples/pull/199.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/5dca5482d86d340d5abf3438d031062a11986888/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-31848) |
> Draw new sample code into article

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #31672
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/304f2a1cb6dfcb1aac4af478a73565cd5eaa1dae/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-31850) |
> NSwag for WASM+Identity article

- aspnetcore/blazor/fundamentals/routing.md
addresses #31845
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/0621b376a150826403dcfbae46b4751e3968dfdb/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-31859) |
> #31845 Routing with optional parameters and fallback value - OnInitialized vs. OnParametersSet

- aspnetcore/blazor/components/index.md
Fixes #31860
@hakenr ... This is my interpretation of Steve's guidance. He didn't remark on [Artak's discussion with @mrlife](https://github.com/dotnet/aspnetcore/issues/22658), so we'll let that go.
Note tho that for ...
> \
> `<button type="button" @onclick="myComponent.DoSomething">Do Something</button>`
... I'm leaning toward remarking on that in passing here. Yeah ... I like that idea. I think I'll commit a remark. ***UPDATE***: Draft remark is done 👍. Let's look here on review and see if the phrasing is correct and clear. **OK** ... I think I'm done with it for now. I had to play with the wording a bit more.
The examples (8.0 shown here) are now ...
`ReferenceParent1` component:
```razor
﻿@page "/reference-parent-1"
<PageTitle>Reference Parent 1</PageTitle>
<h1>Reference Parent …
```
> Update component ref text and examples

- aspnetcore/signalr/security.md
- aspnetcore/signalr/security/includes/security6.md
- aspnetcore/signalr/security/includes/security7.md
[Internal Review: Link to edited section](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-9.0&branch=pr-en-us-31870#cross-origin-resource-sharing)
Fixes #31373
For the 1st CORS policy customization example, explicitly pointing to the topic on customizing CORS policies and Middleware for more information.
---
|:--|:--|
| [aspnetcore/signalr/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d66942034aa3615e87ab3fe19fd4e6873f18b5a/aspnetcore/signalr/security.md) | [Security considerations in ASP.NET Core SignalR](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/security?branch=pr-en-us-31870) |
> SignaR Security: Point to customizing CORS middleware

- aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/troubleshoot.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/webassembly-lazy-load-assemblies.md
Fixes #31741
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc688c501ed813b1e1ec87784eb12c833ac92433/aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md) | [ASP.NET Core Razor class libraries (RCLs) with static server-side rendering (static SSR)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries-and-static-server-side-rendering?branch=pr-en-us-31873) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc688c501ed813b1e1ec87784eb12c833ac92433/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component …
> Inline form updates for conventions

- aspnetcore/blazor/security/index.md
Fixes 
Thanks @cosmic-tiger! 🚀 ... Hopefully, just adding "client-side" here will make it clear that this is ***only*** referring to the client-side checks that auth makes, not ALL checks ... not server-side checks ... not server-side security measures and data encrypted by the server.
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/28b923810f80ab81ebb50f7453287a8e30e1f461/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-31889) |
> Clarify remark

- aspnetcore/security/app-secrets.md
Fixes #31862 
@roby70 please review.
---
|:--|:--|
| [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/e35aed0e4022b3fb7583fec6c3bf7b1e12489eb4/aspnetcore/security/app-secrets.md) | [Safe storage of app secrets in development in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/app-secrets?branch=pr-en-us-31893) |
> Manually set assembly info attribute

- aspnetcore/blazor/components/synchronization-context.md
draw samples updates from https://github.com/dotnet/blazor-samples/pull/213
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/synchronization-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/ac402469e80e8e1c2f19029ecb5edbc6d4d6f051/aspnetcore/blazor/components/synchronization-context.md) | [ASP.NET Core Blazor synchronization context](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/synchronization-context?branch=pr-en-us-31911) |
> Blazor Synchronization contxt - draw sample code

- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/synchronization-context.md
- aspnetcore/blazor/fundamentals/handle-errors.md
Fixes #31912
Thanks @hakenr! 🎸 
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/a86cdb6f705fe3b6bb169c63b316e76d22983d8b/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-31920) |
| [aspnetcore/blazor/components/synchronization-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/a86cdb6f705fe3b6bb169c63b316e76d22983d8b/aspnetcore/blazor/components/synchronization-context.md) | [ASP.NET Core Blazor synchronization context](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/synchronization-context?branch=pr-en-us-31920) |
| …
> Move handle errors section

- aspnetcore/blazor/components/layouts.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/75a9e30afad114c42320fa107d1b57a7b689eed8/aspnetcore/blazor/components/layouts.md) | [ASP.NET Core Blazor layouts](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?branch=pr-en-us-31928) |
> Blazor - layouts.md - folder names formatting fix

- aspnetcore/blazor/security/includes/troubleshoot-server.md
- aspnetcore/blazor/security/includes/troubleshoot-wasm.md
- aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
- aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-entra-id.md
Fixes #31936
---
|:--|:--|
| [aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/e135401746995643c40daac2ec7b4d305611ef9b/aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?branch=pr-en-us-31937) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/e135401746995643c40daac2ec7b4d305611ef9b/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active …
> Blazor troubleshooting guidance updates

- aspnetcore/blazor/call-web-api.md
Fixes #31941
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/0571044d2284f1f31bc3664771e337e4d78cd7d7/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31946) |
> Drop pivots and sample code

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Addresses #31770
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/952288cc00a29847593a034c5e407266ea2aedf5/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-31947) |
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/952288cc00a29847593a034c5e407266ea2aedf5/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-31947) |
> Update Blazor release notes for Preview 2

- aspnetcore/release-notes/aspnetcore-9.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/0fcf5a548be8c907554463ea12abecb4e4dfde71/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-31952) |
> Update What's New

- aspnetcore/blazor/components/cascading-values-and-parameters.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/f54e9fc241d8e873a1e565530cfb9739fa4a4fb7/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31954) |
> [Blazor] cascading-values-and-parameters.md - "JSON-serializable" typo

- aspnetcore/blazor/components/cascading-values-and-parameters.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/21e7286c50cd017929f97afb7f0ab96344d3fee7/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-31955) |
> [Blazor] cascading-values-and-parameters.md - "instructing" typo

- aspnetcore/blazor/components/data-binding.md
"After each keystroke" is an `oninput` event
* fixed the text
* fixed the sampleˇ
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/0c07cd2179c502d2d37c093786764203bcd6fdc0/aspnetcore/blazor/components/data-binding.md) | [ASP.NET Core Blazor data binding](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?branch=pr-en-us-31957) |
> Blazor - data-binding - event fix

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/fundamentals/middleware/request-response.md
- aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/todo/Program.cs
- aspnetcore/fundamentals/minimal-apis/includes/parameter-binding7.md
- aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
- aspnetcore/includes/response-caching-mid.md
- aspnetcore/performance/caching/middleware/samples/2.x/ResponseCachingMiddleware/Pages/Index.cshtml
- aspnetcore/performance/caching/middleware/samples/2.x/ResponseCachingMiddleware/README.md
- aspnetcore/performance/caching/middleware/samples/3.x/ResponseCachingMiddleware/Pages/Index.cshtml
- aspnetcore/performance/caching/middleware/samples/3.x/ResponseCachingMiddleware/README.md
- aspnetcore/performance/caching/response.md
- aspnetcore/performance/response-compression.md
- aspnetcore/performance/response-compression/samples/2.x/SampleApp/README.md
- aspnetcore/performance/response-compression/samples/3.x/SampleApp/README.md
- aspnetcore/security/cors.md
- aspnetcore/security/cors/includes/cors56.md
- aspnetcore/security/cors/includes/cors7.md
- aspnetcore/tutorials/first-web-api.md
- aspnetcore/web-api/advanced/custom-formatters.md
- aspnetcore/web-api/advanced/formatting.md
Fixes #31965 
The scope for this is any topic or file that refers to API testing tools.  Excluded from this scope is any topic that requires extensive rewriting.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/b695929d26123dcbf56b0df4f1f65cee488afb76/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31966) |
| [aspnetcore/blazor/forms/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/b695929d26123dcbf56b0df4f1f65cee488afb76/aspnetcore/blazor/forms/validation.md) | [ASP.NET Core Blazor forms validation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?branch …
> Update API Testing tool references

- aspnetcore/blazor/blazor-ef-core.md
Fixes #31975
Thanks @nivekh! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/79a137b2de68c1e99fc192fe4db77a3da435fd7f/aspnetcore/blazor/blazor-ef-core.md) | [ASP.NET Core Blazor with Entity Framework Core (EF Core)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-31976) |
> Clarify sample location

- aspnetcore/blazor/blazor-ef-core.md
- aspnetcore/blazor/components/control-head-content.md
- aspnetcore/blazor/components/data-binding.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/templated-components.md
- aspnetcore/blazor/file-downloads.md
- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/handle-errors.md
- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/images.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
- aspnetcore/blazor/project-structure.md
- aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
- aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #31977
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/91066df113d6800a8518ccaa678d57141b90067f/aspnetcore/blazor/blazor-ef-core.md) | [ASP.NET Core Blazor with Entity Framework Core (EF Core)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-31979) |
| [aspnetcore/blazor/components/control-head-content.md](https://github.com/dotnet/AspNetCore.Docs/blob/91066df113d6800a8518ccaa678d57141b90067f/aspnetcore/blazor/components/control-head-content.md) | [Control head content in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?br …
> Blazor-specific 'how to download' guidance

- aspnetcore/blazor/call-web-api.md
Addresses #31887
Follow-up work for typed and named clients.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9daa6b58140ea4559d8d9dbfc08143284a1b2ae/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31988) |
> Additional Call web API article updates

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md
Fixes #31973
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce40132deb2625b91df442856b9d833e6053cacb/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31991) |
| [aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce40132deb2625b91df442856b9d833e6053cacb/aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?branch=pr-en-us-31991) |
> Call (web) API security updates

- aspnetcore/test/load-tests.md
---
|:--|:--|
| [aspnetcore/test/load-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/24781362b1a39b94fdccd9d8187dafbb2e478a07/aspnetcore/test/load-tests.md) | [ASP.NET Core load/stress testing](https://review.learn.microsoft.com/en-us/aspnet/core/test/load-tests?branch=pr-en-us-31993) |
> Fix JMeter .NET DSL name

- aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md
*Ooooops!* Missed a change :smiling_imp:.
---
|:--|:--|
| [aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/e6a3e1449fa91869ee21c010b3a45b6b52dd5039/aspnetcore/blazor/security/server/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?branch=pr-en-us-31994) |
> NIT update for path change

- aspnetcore/blazor/call-web-api.md
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f3715149249e7c324c2f2f701cca865c5b9350c/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-31996) |
> Drop prop and field in examples

- aspnetcore/blazor/call-web-api.md
Fixes #31989
In conjunction with the sample app updates on https://github.com/dotnet/blazor-samples/pull/231.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/661d63dc3079646ff00a11fed4e5b087e506a387/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-32007) |
> PATCH section and other updates

- aspnetcore/blazor/components/overwriting-parameters.md
Addresses: #29855
Addresses: #31922
Addresses: #31788
@guardrex, If you approve/adjust the text, I will finish the samples for other versions and update the code refs.
---
|:--|:--|
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a8e758479b6ca50d8f1a44e0cd83687cadb6891/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-31999) |
> [Blazor] OverridingParameters - ShowMoreExpander, ToggleExpander

- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/test.md
My pleasure, @hakenr, for all of the contributions. Hopefully, it will direct a little traffic your way.
I also spotted one that I needed to fix. It's not supposed to have a colon on it. As you know by now, it's a constant ***fight*** against gremlins here 😠🤜😈.
I'll take this live right after it merges.
---
|:--|:--|
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/f991a24ed0dd1abda7e0064078c668644c231445/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-32010) |
| [aspnetcore/blazor/test.md](https://github.com/dotnet/AspNetCore.Docs/blo …
> Guardrex patch 3

- aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md
---
|:--|:--|
| [aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md](https://github.com/dotnet/AspNetCore.Docs/blob/cdc19fb822985eff2d6d991d9c3c73e0138f6d80/aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md) | [Account confirmation and password recovery in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/account-confirmation-and-password-recovery?branch=pr-en-us-32015) |
> Update email address in example

- aspnetcore/security/authentication/identity-api-authorization.md
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/APIforSPA.csproj
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/APIforSPA.http
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/ApplicationDbContext.cs
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/EmailSender.cs
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/Program.cs
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/WeatherForecast.cs
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/appsettings.Development.json
- aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/appsettings.json
Fixes #32002 
---
|:--|:--|
| [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/6017e05e58c5dcfb6f031e92b0b7885c2a8b7303/aspnetcore/security/authentication/identity-api-authorization.md) | [How to use Identity to secure a Web API backend for SPAs](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?branch=pr-en-us-32003) |
> Convert inline code to snippet references

- .openpublishing.redirection.json
- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/toc.yml
- aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod2.md
Fixes #32016
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/fbabfa38de04c71f471c84b60bd9c6afd1278a4c/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-32018) |
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fbabfa38de04c71f471c84b60bd9c6afd1278a4c/aspnetcore/blazor/fundamentals/index.md) | [ASP.NET Core Blazor fundamentals](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/index?branch=pr-en-us-32018) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/fbabfa38de04c71f471c84 …
> Move BWA+OIDC article

- aspnetcore/blazor/components/overwriting-parameters.md
@guardrex If you don't mind, linking to the Blazor component library for which I am the main maintainer would be more beneficial for me (potentially more relevant traffic). Thank you.
---
|:--|:--|
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/966b9cdd9d9b2a457e59bab7bc3c38524dd3371f/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-32024) |
> Blazor - overwriting-parameters - By line link update

- aspnetcore/blazor/security/server/additional-scenarios.md
Addresses #31691
---
|:--|:--|
| [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/d00d4a374e1f9df79972b3e4344f98e42e51ab6a/aspnetcore/blazor/security/server/additional-scenarios.md) | [Server-side ASP.NET Core Blazor additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?branch=pr-en-us-32031) |
> Temporarily surface PU issue for access tokens

- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
> Surface Blazor 9.0 Preview 2 content

- aspnetcore/blazor/host-and-deploy/server.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/tooling.md
- aspnetcore/fundamentals/servers/kestrel/http2.md
- aspnetcore/fundamentals/servers/kestrel/http3.md
- aspnetcore/grpc/troubleshoot.md
- aspnetcore/grpc/troubleshoot/includes/troubleshoot3-7.md
- aspnetcore/host-and-deploy/docker/building-net-docker-images.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images5.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images7.md
- aspnetcore/host-and-deploy/linux-apache.md
- aspnetcore/host-and-deploy/linux-nginx.md
- aspnetcore/host-and-deploy/linux-nginx/includes/linux-nginx5.md
- aspnetcore/host-and-deploy/proxy-load-balancer.md
- aspnetcore/security/enforcing-ssl.md
- aspnetcore/signalr/diagnostics.md
- aspnetcore/signalr/scale.md
Add ms.custom tags for horizontals
CorrelationId: c81e3608-8fcd-4296-8dea-28909aaeded4
PointOfContact: @dbradish-microsoft
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/b82b9110921b9b03ccab60edd889c8fe4bc9aca7/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-31998) |
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/b82b9110921b9b03ccab60edd889c8fe4bc9aca7/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core …
> [BULK UPDATE] DocuTune - Add ms.custom tags for horizontals

- aspnetcore/fundamentals/error-handling.md
- aspnetcore/fundamentals/error-handling/samples/7.x/ErrorHandlingSample/Snippets/Program.cs
Fixes #32047 
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/f80c6d4f7044e6a1d52d88c678132b0cbc51953a/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-32072) |
> Fix order of statements

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md
Fixes #32079
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/de6161a7696f483fdb48ff2c7c290d1d30317fb2/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32080) |
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/de6161a7696f483fdb48ff2c7c290d1d30317fb2/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-32080) |
| …
> Updates to 'click'-based remarks

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32077
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/466d40c67ec45c74b6e64551d8907472c077fe8d/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32081) |
> Nonce update for token refresh

- aspnetcore/blazor/components/event-handling.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/f4017d2460ae4e0cc9630cef5f161d875fd8b837/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-32084) |
> [Blazor] Event-handling - generic EventCallback<T> enhanced error feedback explanation

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32097
Thanks @cipherw0lf! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/7d42c0b1c22e8189c1b3b5b3a214add4ea814ed9/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32104) |
> Add VS prerequisite version

- aspnetcore/blazor/components/js-spa-frameworks.md
Fixes #29253
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/1acaa161b461fe0d75dabfdb7f677feafbb8456c/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-32105) |
> Add sample app cross-links to JS/SPA article

- aspnetcore/migration/http-modules/sample8/Program.cs
- aspnetcore/migration/http-modules/sample8/Snippets/GlobalSnippet.cs
- aspnetcore/migration/http-modules/sample8/Snippets/HttpModulePoolingSnippet.cs
- aspnetcore/migration/http-modules/sample8/Snippets/UseAuthenticationAndAuthorizationSnippet.cs
- aspnetcore/migration/http-modules/sample8/Web8Sample.csproj
- aspnetcore/migration/http-modules/sample8/appsettings.Development.json
- aspnetcore/migration/http-modules/sample8/appsettings.json
- aspnetcore/migration/http-modules/sample8/readme.txt
- aspnetcore/migration/inc/http-modules.md
Fixes #32087
---
|:--|:--|
| [aspnetcore/migration/inc/http-modules.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b5440e1e3a878838c12f06e5a3bf28583a220bc/aspnetcore/migration/inc/http-modules.md) | [ASP.NET to ASP.NET Core incremental IHttpModule migration](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/http-modules?branch=pr-en-us-32106) |
> move snippets to code sample

- aspnetcore/migration/http-modules.md
- aspnetcore/migration/http-modules/sample8/Snippets/GlobalSnippet.cs
- aspnetcore/migration/http-modules/sample8/Snippets/HttpModulePoolingSnippet.cs
- aspnetcore/migration/http-modules/sample8/Snippets/UseAuthenticationAndAuthorizationSnippet.cs
Fixes #32111
---
|:--|:--|
| [aspnetcore/migration/http-modules.md](https://github.com/dotnet/AspNetCore.Docs/blob/80480f147672307b998784851bc3c8959c06907d/aspnetcore/migration/http-modules.md) | [Migrate HTTP handlers and modules to ASP.NET Core middleware](https://review.learn.microsoft.com/en-us/aspnet/core/migration/http-modules?branch=pr-en-us-32112) |
> Snippet region to tag

- aspnetcore/blazor/components/lifecycle.md
Fixes #32117.
cc @guardrex
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/988732653e8a146ede6c560f8f3bf4c6f067a846/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32120) |
> [Blazor] Lifecycle - AfterRender.razor sample update + console output added

- aspnetcore/blazor/components/lifecycle.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/32120
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/76303585f7da3c6ee5feb8933629818a44c8294c/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32126) |
> Add a space to format block quote output

- aspnetcore/blazor/components/lifecycle.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/7d489cbc6354d9e084a9a050f91c1bc44395f052/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32131) |
> [Blazor] Lifecycle - StateHasChanged from Dispose or DisposeAsync

- aspnetcore/blazor/fundamentals/configuration.md
Fixes #32110
Thanks @xxAtrain223! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/77fa937604a46343bdc90f77024f347730fa8856/aspnetcore/blazor/fundamentals/configuration.md) | [ASP.NET Core Blazor configuration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?branch=pr-en-us-32135) |
> Clarify app settings file locations

- aspnetcore/test/integration-tests.md
- aspnetcore/test/integration-tests/includes/integration-tests7.md
Add missing angle brackets to this page: [Inject mock services](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0#inject-mock-services)
Fixes #32118
---
|:--|:--|
| [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/d84e0dc4afbd4d4c831f5e13b30ec160cb2232a0/aspnetcore/test/integration-tests.md) | [Integration tests in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?branch=pr-en-us-32113) |
> add missing angle brakets

- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/server/static-server-side-rendering.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
- aspnetcore/migration/70-80.md
Fixes #32159
Addresses #32138
Thanks @SeanFeldman! 🎸 ... Your call for improved migration guidance led me to find several spots to add coverage on how the services are added automatically when `AddRazorComponents` is called ***AND*** improve other aspects of the antiforgery coverage, including improved cross-links within articles and to the API docs.
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/a9973565fb03e588ea78b168cd19b45f34e14de3/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-32160) |
| …
> Add coverage on antiforgery services and middleware

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/toc.yml
Fixes #32162
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/c5e3fd7c6caecd74c764ac4828e0f9e7321bd448/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32163) |
> Add remark on ME-ID authority in server API config

- aspnetcore/blazor/components/render-modes.md
Fixes #32156
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/4ff3bfa9e4c553c0a63ad93220f466e4e7a6a96d/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32164) |
> Add remarks on standalone WASM

- aspnetcore/blazor/file-downloads.md
Fixes #32152
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/35a6fa1147b22b6a6b24548c755e3fee5749e483/aspnetcore/blazor/file-downloads.md) | [ASP.NET Core Blazor file downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-32165) |
> Clarify the guidance is for downloading (not opening) files

- aspnetcore/blazor/includes/compression-with-untrusted-data.md
- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #32166
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e09e7fab2aa06019595cbac8da4ba6357c4d1ca3/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-32167) |
> Updates to compression warning content

- aspnetcore/includes/not-current-version.md
- aspnetcore/includes/not-latest-version.md
> Update current version and latest version include files

- aspnetcore/blazor/host-and-deploy/server.md
Fixes #32199
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8c114ecf046c46bf8268c91580ea2e2c01bf95e/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-32204) |
> Update Azure SignalR Service remarks

- aspnetcore/blazor/call-web-api.md
Addresses https://github.com/dotnet/blazor-samples/pull/249
Addresses #32028
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/d5ef1a01e0858e608ef31d3f564c41d0129faf9d/aspnetcore/blazor/call-web-api.md) | [Call a web API from ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-32211) |
> Update service registration to match latest guidance

- aspnetcore/blazor/fundamentals/routing.md
Fixes #31212
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/4c0d4da0ceda560aefa434f94ce06442d5cbe00c/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-32219) |
> Guidance on dynamic NavLink generation

- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/includes/js-interop/blazor-page-script.md
- aspnetcore/blazor/javascript-interoperability/static-server-rendering.md
- aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md
- aspnetcore/security/authentication/identity-enable-qrcodes.md
- aspnetcore/toc.yml
Fixes #32186
Mackinnon ... I'm done messing around with it now. It's ready for a look :eyes:.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a56eba818c31fc223962715585bc6fd233e3fee/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-32206) |
| [aspnetcore/blazor/javascript-interoperability/static-server-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/7a56eba818c31fc223962715585bc6fd233e3fee/aspnetcore/blazor/javascript-interoperability/static-server-rendering.md) | [ASP.NET Core Blazor JavaScript with static server-side rendering (static …
> QR code generation article for BWAs

- aspnetcore/blazor/fundamentals/signalr.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/014067c55544a7fb35d6d04a3b8831e4a89ac8da/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-32234) |
> Add missing parentheses

- aspnetcore/diagnostics/asp0018.md
Fixes #31964
---
|:--|:--|
| [aspnetcore/diagnostics/asp0018.md](https://github.com/dotnet/AspNetCore.Docs/blob/b8ce077a2a31c811426a63343994b4b75664b583/aspnetcore/diagnostics/asp0018.md) | [ASP0018: Unused route parameter](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018?branch=pr-en-us-32230) |
> asp0018 exception

- aspnetcore/security/authentication/mfa.md
Fixes #32222 
---
|:--|:--|
| [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/0f8afab6aae568afa57cb20d9a5e4f2e43935ef2/aspnetcore/security/authentication/mfa.md) | [Multi-factor authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?branch=pr-en-us-32225) |
> Use .NET 9 code

- aspnetcore/security/authentication/mfa.md
Small spacing fix
https://github.com/dotnet/AspNetCore.Docs/issues/32222
https://github.com/dotnet/AspNetCore.Docs/pull/32225
---
|:--|:--|
| [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/39d984f2254961c73f2ba31fa551442765a5a23d/aspnetcore/security/authentication/mfa.md) | [Multi-factor authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?branch=pr-en-us-32253) |
> Spacing fix

- aspnetcore/mvc/advanced/custom-model-binding.md
Fixes #31985
Minor change: Remove single line Postman suggestion and replaced with curl for all versions of this topic.
---
|:--|:--|
| [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/f0603b84e60b582506e3378cf8f7f788b1b77fc6/aspnetcore/mvc/advanced/custom-model-binding.md) | [Custom Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?branch=pr-en-us-32252) |
> Update API test tool: Custom Model Binding

- aspnetcore/blazor/forms/index.md
- aspnetcore/mvc/views/razor.md
Fixes #32266
Thanks @chsienki! 🚀 ... Let's try this and see what it looks like. I'll wait until EOD before merging it to give you an opportunity to look it over and provide feedback.
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/30cd148f409d645edeaca388cfb933414fbd7f57/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-32274) |
| [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/30cd148f409d645edeaca388cfb933414fbd7f57/aspnetcore/mvc/views/razor.md) | [Razor syntax reference for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?branch=pr-en-u …
> Improve @formname coverage

- aspnetcore/fundamentals/minimal-apis/includes/parameter-binding8.md
- aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/ComplexBinding/Program.cs
> fix example of paramater binding with form checkboxes

- aspnetcore/blazor/components/index.md
Fixes #30406
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b8dfb7decfb43ff7a6672b85834cc64e76d3f4bb/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32300) |
> Distinguish Razor components

- aspnetcore/release-notes/aspnetcore-9.0.md
Matches the what's new in .net doc.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/158093c7cfa89ebdbd1b0f4da59cdecd7914212a/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32301) |
> Reference the specific release for what's new

- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/host-and-deploy/linux-apache.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/0d1942f50b908f76b16ee9b7d89997a20367fff2/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-32307) |
| [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/0d1942f50b908f76b16ee9b7d89997a20367fff2/aspnetcore/host-and-deploy/linux-apache.md) | [Restart service after 10 seconds if the dotnet service crashes:](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?branch=pr-en-us-32307) |
> Adding CentOS EOL caution

- aspnetcore/blazor/components/lifecycle.md
Fixes #32273
Thanks @runceel! 🎸 ... Mackinnon will be along in a bit to take a look 👀.
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/719e6ee2964dac244d936119d82a6b417a3fb574/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-32285) |
> Improve `SetParametersAsync` base method coverage

- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/tutorials/getting-started-with-swashbuckle.md
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.x/TodoApi.Swashbuckle/readme.md
Addresses #32308
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/90e383879eb9932f3c457e4c135c0175aac03d55/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-32322) |
| [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/90e383879eb9932f3c457e4c135c0175aac03d55/aspnetcore/tutorials/getting-started-with-swashbuckle.md) | [Get started with Swashbuckle and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?branch=pr-en-us-32322) |
| …
> Address CentOS EOL in Blazor

- aspnetcore/release-notes/aspnetcore-9.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e132b82a6f0646bb72b93ead3689a22863c4836/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32323) |
> Remove empty heading

- aspnetcore/blazor/forms/index.md
Fixes #31354
Thanks @KristinBethea! :rocket: ... I finally reached this for work 😅.
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/07645015eda4cf8f2877137c6a397fc7d980ccbe/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-32334) |
> Clear forms and fields

- aspnetcore/fundamentals/minimal-apis.md
- aspnetcore/fundamentals/minimal-apis/7.0-samples/WebMinAPIs/Program.cs
- aspnetcore/fundamentals/minimal-apis/includes/minimal-apis7.md
- aspnetcore/fundamentals/minimal-apis/samples/WebMinAPIs/Program.cs
- aspnetcore/fundamentals/use-http-context/samples/Program.cs
Assumes "Contoso" is sill the name of the example company
***EDIT BY @Rick-Anderson***
Fixes #32341
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/a8302a93c06f81a42f4770485ee5e743fd94778e/aspnetcore/fundamentals/minimal-apis.md) | [Minimal APIs quick reference](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-32340) |
> fix(minimal-apis): rename 'consoto' to 'contoso'

- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md
***EDIT by @Rick-Anderson*** Fixes #32345 Fixes #32346 Fixes #32347 Fixes #32348
@Rick-Anderson this PR updates the highlights after the samples were updated in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/253
Side note: I noticed that the rdg001 page isn't included in the sidebar
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md](https://github.com/dotnet/AspNetCore.Docs/blob/348ae2f16baf10916f7b902a5bbf0796547a281a/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md) | [RDG010: InvalidAsParameters Nullable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg010?branch=pr-en-us-32344) |
| …
> fix RDG highlights after code samples update

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
See https://github.com/dotnet/AspNetCore.Docs/issues/32042#issuecomment-2040200923
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/488d0f96c020c8b969e45b47c0160f8d2565efe2/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32349) |
> Add Blazor keyboard composition events to what's new

- aspnetcore/grpc/performance.md
---
|:--|:--|
| [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/818fd7c473dfb2f16adddcd4c9184cc843920036/aspnetcore/grpc/performance.md) | [Performance best practices with gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/performance?branch=pr-en-us-32355) |
> Add docs for WinHttpHandler and multiple connections

- aspnetcore/blazor/fundamentals/routing.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/242f5dba593cadc0d2ee66a9b028ff11d1431bba/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-32368) |
> Remove dagger

- aspnetcore/blazor/components/element-component-model-relationships.md
- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
- aspnetcore/blazor/components/synchronization-context.md
- aspnetcore/blazor/components/templated-components.md
---
|:--|:--|
| [aspnetcore/blazor/components/element-component-model-relationships.md](https://github.com/dotnet/AspNetCore.Docs/blob/80fa70ad7ea07b954fbcd1e18e8d9c1671651d5f/aspnetcore/blazor/components/element-component-model-relationships.md) | [Retain element, component, and model relationships in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?branch=pr-en-us-32380) |
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/80fa70ad7ea07b954fbcd1e18e8d9c1671651d5f/aspnetcore/blazor/components/overwriting-parameters.md) | [Avoid overwriting parameters in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/b …
> Add/move version warning INCLUDE files

- aspnetcore/fundamentals/websockets.md
- aspnetcore/fundamentals/websockets/includes/websockets3-5.md
- aspnetcore/fundamentals/websockets/includes/websockets6.md
- aspnetcore/fundamentals/websockets/includes/websockets7.md
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/Controllers/WebSocketController.cs
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/Program.cs
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/Snippets/BackgroundSocketProcessor.cs
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/Snippets/Program.cs
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/WebSocketsSample.csproj
- aspnetcore/fundamentals/websockets/samples/8.x/WebSocketsSample/wwwroot/index.html
Contributes to #32203, Refreshing my top ten topics in order of unique visitors.
Minor changes:
- 8.0 app sample only differs by the target .NET in the project file.  Nothing else needed to change in it after testing.
- Split up the topic to versioning by include.
- Updated the topic for version 8 to point to the version 8 sample and updated the ms.date to show it has been refreshed.
I did a visual and tool diff on all versions of the topic build to make sure there were no code or image dropouts.
---
|:--|:--|
| [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/ebbe76628dab17157f479ff3ea8877e438d0e6e1/aspnetcore/fundamentals/websockets.md) | [WebSockets support in ASP.NET …
> Refresh my top 10 topics: WebSockets

- aspnetcore/tutorials/web-api-javascript.md
Contributes to #32305 
Updated ms.date only to refresh.
Tested topic against latest First API app sample it refers to.  Works great, no changes needed. Already 8.0. 
---
|:--|:--|
| [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/58c35a7148005921a4a55156a6a3ce317bf66086/aspnetcore/tutorials/web-api-javascript.md) | [Tutorial: Call an ASP.NET Core web API with JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?branch=pr-en-us-32392) |
> Updated web-api-javascript.md freshness date after testing

- aspnetcore/security/authorization/roles.md
Fixes #32174
---
|:--|:--|
| [aspnetcore/security/authorization/roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/44d8e372984435495045bcf63e59435ab4eac10d/aspnetcore/security/authorization/roles.md) | [Role-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?branch=pr-en-us-32393) |
> Note required package and using directive

- aspnetcore/tutorials/getting-started-with-NSwag.md
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/40f1ff8e4536ca49ed29f334d1160ce701777fe3/aspnetcore/tutorials/getting-started-with-NSwag.md) | [Get started with NSwag and ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-NSwag?branch=pr-en-us-32400) |
> NSwag 14 supports only v3 of Swagger UI spec

- aspnetcore/security/authentication/cookie.md
Fixes #32155 
---
|:--|:--|
| [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/07f2f9b9ed1f8e3b36546abc95f5ca50d622ba70/aspnetcore/security/authentication/cookie.md) | [Use cookie authentication without ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?branch=pr-en-us-32401) |
> Note location of SignInAsync

- aspnetcore/tutorials/web-api-help-pages-using-swagger.md
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup.cs
- aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/2.0/TodoApi.NSwag/Startup2.cs
fixes #32407
includes https://github.com/dotnet/AspNetCore.Docs.Samples/pull/254
---
|:--|:--|
| [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/dotnet/AspNetCore.Docs/blob/b432751c4b95467c6853be27d9375df614e1a54f/aspnetcore/tutorials/web-api-help-pages-using-swagger.md) | [ASP.NET Core web API documentation with Swagger / OpenAPI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?branch=pr-en-us-32408) |
> SwagUI to dev mode

- aspnetcore/grpc/json-transcoding-openapi/Program.cs
> Move useSwaggerUI to dev mode only

- aspnetcore/test/troubleshoot-azure-iis.md
Just refreshed ms.date. This topic was recently updated but ms.date was not. 
Contributes to #32305   Improving health score.
Side note: This is a very high traffic topic, but notably, it is also high bounce.  Looking at the data it appears that when major sites generate an error for a page, that their customers may be looking up the error here and then bouncing out when they realize it is developer related.  Looking over the description and the way error ID's are provided in this topic I'm not sure we can improve on that situation.
---
|:--|:--|
| [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/497fd8608f7dfc1582662a7eb824809f9fd3f74a/aspnetcore/test/troubleshoot-azure-iis.md) | [Troubleshoot ASP.NET Core on Azure App …
> Refresh: Update troubleshoot-azure-iis.md

- aspnetcore/fundamentals/configuration/index.md
Contributes to #32305
Recently updated but ms.date needed to refresh.  High traffic.  Updating so health score more accurate.  Reviewed doc.
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ae24d2d03bd7bb8125e118ee7f55e752fd4e792c/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-32423) |
> Health Score: Review and refresh ms.date: Configration.md

- aspnetcore/fundamentals/environments.md
- aspnetcore/host-and-deploy/iis/index.md
- aspnetcore/security/authentication/identity.md
Contributes to #32305 
Just ms.date freshness updates.
Few topics that were very high traffic, had been updated recently, but the ms.date was a few years old. Reviewed topics and looked over data.
---
|:--|:--|
| [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c7d353de8e3d82b01e26e0d90d4708a606a5f5e/aspnetcore/fundamentals/environments.md) | [Use multiple environments in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?branch=pr-en-us-32424) |
| [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c7d353de8e3d82b01e26e0d90d4708a606a5f5e/aspnetcore/host-and-deploy/iis/index.md) | [Host ASP.NET Core on Windows with …
> Content Health: Update freshness

- aspnetcore/blazor/host-and-deploy/server.md
- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/toc.yml
- aspnetcore/tutorials/publish-to-iis.md
Fixes #32399
Thanks @developer-sintmaartencampus! 🚀 ... This is a set of improvements to our coverage, mostly IIS cross-linking. For general guidance and troubleshooting with ARR, you'll need to turn to ARR articles, ARR blogs, and public support channels. If you have a specific problem with Blazor and ARR, we can address it via product unit issue, but you'd need to explain/demo for the Blazor engineers how Blazor is related to ARR not working properly after following all of the guidance that we cross-link.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/5c5c0e060f6116424caccbb57db99c3a727ba7e9/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy server-side Blazor …
> Improve IIS crosslinking and additional deployment updates

- aspnetcore/blazor/components/index.md
Fixes #32452
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/809342833499560b96a021847a44ffcec97a1c91/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32465) |
> Clarify conditional HTML element attributes

- aspnetcore/blazor/host-and-deploy/webassembly.md
- aspnetcore/fundamentals/target-aspnetcore.md
- aspnetcore/migration/70-80.md
Fixes #32484
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/5da07080ab73cc3b0a1c611c429c98896beda963/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-32485) |
| [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/5da07080ab73cc3b0a1c611c429c98896beda963/aspnetcore/fundamentals/target-aspnetcore.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?branch=pr-en-us-32485) |
| …
> Remove space in "MS Build"

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32369
Thanks @bpsc-wkubis! 🚀 ... This cross-link will surface the product unit issue that you opened, and I left myself a note there to re-examine where they're at with it in the .NET 10 era, which will be next year.
As for them not responding to your last remark, I think you'll need to ping them on that issue for further discussion.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/b54c7c497fc358513fa6c0c632089bb76b95864c/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32486) |
> Add product unit issue cross-link

- aspnetcore/security/authentication/identity-api-authorization.md
Fixes #32141 
---
|:--|:--|
| [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/adf0e96de9ea494c3709454af014964c8e377706/aspnetcore/security/authentication/identity-api-authorization.md) | [How to use Identity to secure a Web API backend for SPAs](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?branch=pr-en-us-32491) |
> Implement IEmailSender to customize emails

- aspnetcore/security/authentication/community.md
Fixes #32175 
---
|:--|:--|
| [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/8d023f02421841171b79a6c02d4517bb1e59336d/aspnetcore/security/authentication/community.md) | [Community OSS authentication options for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/community?branch=pr-en-us-32494) |
> Explain acronyms on first use

- aspnetcore/security/authorization/simple.md
Fixes #32169 
---
|:--|:--|
| [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs/blob/c72ba7a60c99e89054a81e8c6ad68e38a8e22be6/aspnetcore/security/authorization/simple.md) | [Simple authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/simple?branch=pr-en-us-32495) |
> Add a Prerequisites section

- aspnetcore/blazor/hybrid/tutorials/index.md
Addresses #29880
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/cfe4202166046b5bd03c1f954dc38e859d42226c/aspnetcore/blazor/hybrid/tutorials/index.md) | [ASP.NET Core Blazor Hybrid tutorials](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/index?branch=pr-en-us-32507) |
> Surface new tutorial in tutorial list

- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #32490
Pulling code from the sample's repo.
cc: @nwoolls
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/a2bc1b4e3f036636c5a3e8e7ad74d98e6bfbac4e/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-32510) |
> Update article date to pull code

- .github/workflows/quest-bulk.yml
- .github/workflows/quest.yml
- .github/workflows/whats-new.yml
Copies https://github.com/dotnet/docs/pull/40729
Contributes to #32479
> Added the OIDC flow shared bits, and duration

- aspnetcore/migration/70-80.md
Addresses #32521
Thanks @hakenr! 🎷 ... Please follow this up with additional updates, including to what I'm doing here. I'll merge this shortly.
---
|:--|:--|
| [aspnetcore/migration/70-80.md](https://github.com/dotnet/AspNetCore.Docs/blob/665b871e44b608fca619c04497ff45983b38f86d/aspnetcore/migration/70-80.md) | [Migrate from ASP.NET Core in .NET 7 to .NET 8](https://review.learn.microsoft.com/en-us/aspnet/core/migration/70-80?branch=pr-en-us-32524) |
> Hosted WASM to BWA migration updates

- aspnetcore/security/authentication/community.md
- aspnetcore/security/authentication/social/index.md
- aspnetcore/security/authentication/social/twitter-logins.md
- aspnetcore/security/identity-management-solutions.md
The `AspNet.Security.OAuth.Providers` project is still maintained but given that the newer OpenIddict OAuth 2.0/OpenID Connect web providers are now a much better option for most scenarios, we decided to encourage using them for new applications (for more information, see https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/?tab=readme-ov-file#migrating-to-openiddict).
Note: I maintain both projects 😃 
Fixes #32527
---
|:--|:--|
| [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/62fc5f7a3010cb6ce6ca323b2b8a1b9532246ff1/aspnetcore/security/authentication/community.md) | [Community OSS authentication options for ASP.NET …
> List OpenIddict as an alternative to AspNet.Security.OAuth.Providers

- aspnetcore/security/data-protection/introduction.md
---
|:--|:--|
| [aspnetcore/security/data-protection/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/8ffcd0854d83a78893ef5f2e612bfc2df6da322e/aspnetcore/security/data-protection/introduction.md) | [ASP.NET Core Data Protection Overview](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?branch=pr-en-us-32546) |
> Update DPAPI introduction

- .github/workflows/quest.yml
> Copy https://github.com/dotnet/docs/pull/40790

- aspnetcore/includes/not-ga-yet.md
- aspnetcore/performance/caching/overview/includes/overview6.md
- aspnetcore/performance/caching/overview/includes/overview7-8.md
Fixes #32555 
---
|:--|:--|
| [aspnetcore/performance/caching/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/400221d1167b355a345b0216a20795e00119ed00/aspnetcore/performance/caching/overview.md) | [Overview of caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/overview?branch=pr-en-us-32556) |
> Moniker prep for 9.0 content

- aspnetcore/fundamentals/host/hosted-services.md
- aspnetcore/includes/worker-template-instructions-net6.md
Fixes #32558 
---
|:--|:--|
| [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/02a1864009f71c3b6ec2460b47093c822161fd98/aspnetcore/fundamentals/host/hosted-services.md) | [Background tasks with hosted services in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?branch=pr-en-us-32563) |
> Fix problem with tabs

- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/WebMinOpenApi.csproj
- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f08921bc1702d33f2cbc501bbb22f9abd2c0e1c/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32585) |
> Update Scalar docs to use Scalar.AspNetCore package

- aspnetcore/security/authentication/identity-api-authorization.md
---
|:--|:--|
| [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/019b7bbebd19c5ab0b24fc188aa8e6ce6d71c362/aspnetcore/security/authentication/identity-api-authorization.md) | [How to use Identity to secure a Web API backend for SPAs](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?branch=pr-en-us-32601) |
> Delete stray space

- aspnetcore/blazor/security/index.md
Fixes #32597
Thanks @BassFaceIV! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/be62c4d74ce5cde186757bc24e3ceac02672bd15/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-32603) |
> Update cascading auth state service requirements

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #32610
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/8d954d0f928ba6c7b2de6c1946eab3c21f57cc8b/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32611) |
> WN: Blazor OverscanCount

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/hybrid/class-libraries.md
- aspnetcore/blazor/hybrid/reuse-razor-components.md
- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #32614
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/a6bad9772f1018e1f6386377a0ad8e50ed917426/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-32617) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/a6bad9772f1018e1f6386377a0ad8e50ed917426/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32617) |
| [aspnetcore/blazor/hybrid/class-libraries.md](https://github.com/dotnet/AspNetCore.Do …
> Add OverscanCount to ref article

- aspnetcore/release-notes/aspnetcore-9/includes/hybrid-cache.md
- aspnetcore/release-notes/aspnetcore-9/includes/openApi.md
> Update link and language identifier

- aspnetcore/security/authentication/social/other-logins.md
Looks like I missed a page when submitting https://github.com/dotnet/AspNetCore.Docs/pull/32525, sorry 😅 
/cc @Rick-Anderson 
Fixes #32632
---
|:--|:--|
| [aspnetcore/security/authentication/social/other-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d11f418a41c6729998e8dc3d76e5db403c94eb7/aspnetcore/security/authentication/social/other-logins.md) | [External OAuth authentication providers](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?branch=pr-en-us-32630) |
> Update the other logins documentation to include OpenIddict

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
- aspnetcore/fundamentals/minimal-apis/includes/openapi9.md
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/1051cbf20504bcc15561dc6d52dcc21994e7fe05/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32624) |
> Update docs on OpenAPI-related metadata

- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/WebMinOpenApi.json
- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
- aspnetcore/release-notes/aspnetcore-9/samples/OpenApiExample/OpenApiExample.csproj
Fixes #32579 ~#32626~
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/b2c19da54fa09b213ea326733c516dcd16db4e56/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32634) |
> Edit OpenAPI doc

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
Fixes #32644
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/ed1db841c0dcf8a6787a51e4b33000e6750e54e3/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32631) |
> `scope` => `role`

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
Fixes #32626
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/422655260b41ae45132f14d6ac03477eb547a078/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32648) |
> Move up ## Customize OpenAPI endpoints with endpoint metadata

- aspnetcore/security/enforcing-ssl.md
Fixes #32564
@tmds please review
---
|:--|:--|
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/ce8307cec7aba9a5e4159bb9247b07386d032f25/aspnetcore/security/enforcing-ssl.md) | [Enforce HTTPS in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=pr-en-us-32649) |
> linux-dev-certs easy

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #32650
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/2fed3fc7325adb536626dc5e1e567fecfec5c7c4/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32677) |
> BlazorWebAppOidcBff Aspire article updates

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/tooling.md
Fixes #32663
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a020aca6830906e1d4a867bbb44769654ef9421/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32678) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a020aca6830906e1d4a867bbb44769654ef9421/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32678) |
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3a020aca6830906e1d4a …
> More hints on interactivity for doc components

- aspnetcore/blazor/security/server/index.md
Fixes #32684
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/894014b7c77d78a1c21ba5f62261c87606081a5d/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-32685) |
> Fix broken ref source links

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/44388d57736b26277dc09ea2f02c4f54a4c31af3/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32679) |
> Fix snippet for transformers demos

- aspnetcore/security/data-protection/configuration/overview.md
Fixes #32193
@mjoksa  please review
---
|:--|:--|
| [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/bc5c4966a4bd6ca668ec7e90210b290171db4cde/aspnetcore/security/data-protection/configuration/overview.md) | [Configure ASP.NET Core Data Protection](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?branch=pr-en-us-32651) |
> DataProtection Blob warning

- aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/e866421393d7459bb0f3e981e051a58bdbb50964/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?branch=pr-en-us-32695) |
> Bring back OpenAPI package installation instructions

- aspnetcore/tutorials/razor-pages/razor-pages-start/snapshot_sample/RazorPagesMovie/Pages/Movies/Index.cshtml
[Add a data model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio#add-a-data-model)
> ID change to Id

- aspnetcore/fundamentals/host/generic-host.md
Fixes #32704 
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/09fb3fa71b1f91ae4fc9d8ba1ec3d4f101aedfb2/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-32705) |
> Fix incorrect default value

- aspnetcore/host-and-deploy/docker/building-net-docker-images.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images5.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images7.md
- aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod4.md
Fixes #32723
Fixes #32727
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/caa2a301e16df8248f56f3ade2f9c5c980a8304c/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [Docker images for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-32738) |
| [aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod4.md](https://github.com/dotnet/AspNetCore.Docs/blob/caa2a301e16df8248f56f3ade2f9c5c980a8304c/aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod4.md) | ["ASP.NET Core docs: What's new for April 2024"](https://review.learn.microsoft.com/en-us/aspnet/core/whats-new/dotnet-AspNetCore.Docs-mod4?branch=pr …
> Remove CentOS /7

- aspnetcore/fundamentals/minimal-apis/7.0-samples/WebMinJson/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/Snippets/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/Snippets/Snippets.csproj
- aspnetcore/fundamentals/minimal-apis/9.0-samples/Snippets/appsettings.Development.json
- aspnetcore/fundamentals/minimal-apis/9.0-samples/Snippets/appsettings.json
- aspnetcore/fundamentals/minimal-apis/responses.md
Fixes #32278 
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/8bfc7923f86d5630804dfc870110821b249743c8/aspnetcore/fundamentals/minimal-apis/responses.md) | [How to create responses in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-32736) |
> Inline code --> snippet references

- .vscode/settings.json
- aspnetcore/performance/caching/hybrid.md
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Program.cs
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Protos/sample.proto
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Serializers.cs
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/appsettings.Development.json
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/appsettings.json
Fixes #32680 
The link to the sample app in the article won't work until the PR is merged.
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/15b867b632816c487d58640df4670201d1265bca/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-32681) |
> Add serialization sample app

- aspnetcore/grpc/client.md
Fixes https://github.com/grpc/grpc-dotnet/issues/2086
---
|:--|:--|
| [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/67b6150f1d20f1f38b372bf9d042a06e1c62c55f/aspnetcore/grpc/client.md) | [Call gRPC services with the .NET client](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/client?branch=pr-en-us-32740) |
> Dispose gRPC streaming calls

- aspnetcore/grpc/performance.md
- aspnetcore/grpc/performance/dispose-streaming-call.cs
More for https://github.com/grpc/grpc-dotnet/issues/2086
---
|:--|:--|
| [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/369f2d66b42802cb49a3805b762dfa323849a649/aspnetcore/grpc/performance.md) | [Performance best practices with gRPC](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/performance?branch=pr-en-us-32742) |
> Add gRPC perf docs around gracefully completing and disposing streaming calls

- aspnetcore/blazor/security/includes/authentication-component.md
- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
- aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-entra-id.md
Fixes #32758
Thanks @akleinaegis! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/7e5646b64c7d236f04da1a8c8a76f80c15b2e793/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [ASP.NET Core Blazor WebAssembly additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-32759) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/7e5646b64c7d236f04da1a8c8a76f80c15b2e793/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly …
> Update RemoteAuthenticatorView param value

- aspnetcore/client-side/using-browserlink.md
Fixes #30826 
---
|:--|:--|
| [aspnetcore/client-side/using-browserlink.md](https://github.com/dotnet/AspNetCore.Docs/blob/944b916b039285052167b6f0b13512e4921bc6fd/aspnetcore/client-side/using-browserlink.md) | [Browser Link in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?branch=pr-en-us-32752) |
> Package installation no longer needed

- aspnetcore/blazor/security/includes/authentication-component.md
> [Blazor] authentication-component.md - parameter name typo

- aspnetcore/blazor/components/event-handling.md
Fixes #32763
Thanks @codeshanks! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/3eff3995eb77fdaecf6bd4a70133a4952eb16ec8/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-32765) |
> Clarify interactive requirement for event handlers in BWAs

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/b4f9fc5bf424a17c268b8db43fe5a2a918173922/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32774) |
> blazor-web-app-with-oidc.md - missing “be”

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/fc88e82eb7e9403b795a99e7ebf6741c0aaf6040/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32777) |
> blazor-web-app-with-oidc.md - missing “be” and excessive “*” in BFF zone

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/32f9354a2fb560d5316fe225429d00f71f6a2a02/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-32776) |
> blazor-web-app-with-oidc.md - removed excessive “*”

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/current_component.md
- aspnetcore/release-notes/aspnetcore-9/includes/web_asset_delivery.md
Fixes #32781 Fixes #32783
[Detect the current component's render mode at runtime](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0&branch=pr-en-us-32787#detect-the-current-components-render-mode-at-runtime)
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/9a47f871ff491c0be0721c1f70a8f32aa02472b3/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-32787) |
> Render mode /8

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Addresses #32793
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/2e39769184fe010eacbca6b07b29e2f937a1d1a4/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [Build a .NET MAUI Blazor Hybrid app with a Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-32805) |
> Patch the Pre5 .NET MAUI Blazor Hybrid BWA coverage

- aspnetcore/fundamentals/static-files.md
- aspnetcore/fundamentals/static-files/includes/static-files8.md
Contributes to  #32782
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/b062bbbc80b05a389e8ad030e3006cee66ccf4a6/aspnetcore/fundamentals/static-files.md) | [Static files in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-32803) |
> moniker prep:

- aspnetcore/blazor/fundamentals/static-files.md
Surfaced on the merge-to-live build report.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/d9b1c37cfcd377657f184dd99705b1837870ccd5/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-32815) |
> Update link to point to API doc

- aspnetcore/tutorials/razor-pages/da1/includes/da1_8.md
- aspnetcore/tutorials/razor-pages/index.md
- aspnetcore/tutorials/razor-pages/model/includes/model8.md
- aspnetcore/tutorials/razor-pages/new-field/includes/new-field8.md
- aspnetcore/tutorials/razor-pages/page/includes/page8.md
- aspnetcore/tutorials/razor-pages/razor-pages-start/includes/razor-pages-start8.md
- aspnetcore/tutorials/razor-pages/search/includes/search8.md
- aspnetcore/tutorials/razor-pages/sql/includes/sql8.md
- aspnetcore/tutorials/razor-pages/validation/includes/validation8.md
Related to #32707 
Just the prep work of moving the .NET 8 versions to includes.  Then once merged, updating the series for .NET 9 in a different PR.  This makes the changes specific to .NET 9 very clear in the PR for review.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/b3af624b5e633d35455df4fc34198bf7a7693704/aspnetcore/tutorials/razor-pages/da1.md) | [Part 5, update the generated pages in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?branch=pr-en-us-32826) |
| [aspnetcore/tutorials/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b3af624b5e633d35455df4fc34198bf7a7693704/aspnetcore/tutorials/razor-pages/index.md) | [Tutorial: …
> .NET 9 update: Prep RP tutorial series

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
A few more NIT updates to make on the commands for creating the app from the template.
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/d04cab88ccba22d5e5180295c08dcc4d8c76aeb6/aspnetcore/blazor/components/render-modes.md) | [ASP.NET Core Blazor render modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-32829) |
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/d04cab88ccba22d5e5180295c08dcc4d8c76aeb6/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [Build a .NET MAUI Blazor Hybrid app with a Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tuto …
> .NET MAUI BH BWA tutorial updates

- aspnetcore/test/troubleshoot-azure-iis.md
- aspnetcore/test/troubleshoot-azure-iis/includes/troubleshoot-azure-iis7.md
Contributes to #32808
---
|:--|:--|
| [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/c5650ec0c1f17f5ab08c360bf2354e8c6f9c5f5e/aspnetcore/test/troubleshoot-azure-iis.md) | [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://review.learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?branch=pr-en-us-32835) |
> Mon prep Azure trouble

- aspnetcore/client-side/dotnet-interop.md
Fixes #29985
---
|:--|:--|
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/b8aee8575aca290984e98f67b78ad934920ac80c/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-32840) |
> Remove remark on article update plans

- aspnetcore/security/cors.md
- aspnetcore/security/cors/includes/cors56.md
- aspnetcore/security/cors/includes/cors7.md
Fixes #32842
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/a22ddcc6a8bc44ea2a42a2bf96ed572a25598751/aspnetcore/security/cors.md) | [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-32843) |
> Fix broken IIS blog link

- aspnetcore/blazor/components/event-handling.md
Fixes #32873
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/d998d8b8c9f88ca12a24601d7e35d7fe6121deae/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-32879) |
> Document reserved event names

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/fundamentals/includes/codegenerator-common-args.md
- aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md
- aspnetcore/includes/aspnet-codegenerator-args-md.md
- aspnetcore/security/authentication/social/other-logins.md
- aspnetcore/toc.yml
Fixes #32559
Tom ... I didn't intend this to go this far, but the article seems to have escaped an overhaul for several years 😈. Rick was mapped to this one, but I see you're handling it now. I gave it the full 🦖 ***Rex Treatment***&trade; 🦖, and I can back out/change whatever updates that you don't care for.
The major items are ...
* Add the Blazor and Blazor Identity generators.
* Add the MinimalAPI generator.
I checked open issues to see if there was anything else to do, but no other issues are open for this article.
The small updates are too numerous to list. There are a lot of little consistency updates. I pitch that this article should use the tool's actual name over only using the command ("*ASP.NET Core code generator tool (`aspnet-codegenerator `)*" over "*dotnet …
> Scaffolding tool doc overhaul with added generators

- aspnetcore/includes/not-latest-version.md
- aspnetcore/includes/out-of-support.md
- aspnetcore/introduction-to-aspnet-core.md
---
|:--|:--|
| [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/9fd69238643cb8a6927f0837177cba92c4eafb44/aspnetcore/introduction-to-aspnet-core.md) | [Overview of ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?branch=pr-en-us-32877) |
> Out of support

- aspnetcore/blazor/host-and-deploy/configure-trimmer.md
Fixes #32883
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/configure-trimmer.md](https://github.com/dotnet/AspNetCore.Docs/blob/96993ff5330b46d2aa1a8934ff9cd5e9cb0e0751/aspnetcore/blazor/host-and-deploy/configure-trimmer.md) | [Configure the Trimmer for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?branch=pr-en-us-32884) |
> Clarify Blazor trim mode

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/security/server/interactive-server-side-rendering.md
- aspnetcore/migration/70-80.md
Fixes #32887
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d29729242d8ddbbecefbb5a8bdbc85c204e77ab/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-32889) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d29729242d8ddbbecefbb5a8bdbc85c204e77ab/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-32889) |
| [aspnetcore/blazor/security/server/interactive-server-side-rendering.md](https://git …
> Follow-up .NET 8 updates

- aspnetcore/blazor/file-downloads.md
Fixes #32860
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/082d79bd922c775c53538d49b188ba3081049408/aspnetcore/blazor/file-downloads.md) | [ASP.NET Core Blazor file downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-32892) |
> Downloading files with static SSR

- aspnetcore/blazor/tutorials/signalr-blazor.md
Fixes #32778
---
|:--|:--|
| [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/02131e96a7888c2a87bcea87f5c34019c3c05b8e/aspnetcore/blazor/tutorials/signalr-blazor.md) | [Use ASP.NET Core SignalR with Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?branch=pr-en-us-32896) |
> Blazor SignalR tutorial updates

- aspnetcore/blazor/components/quickgrid.md
Fixes #32628
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/30f4091608784cb50a5928d9463298cfbf813b29/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-32911) |
> QuickGrid display name support

- aspnetcore/performance/caching/output.md
Fixes #32862 
---
|:--|:--|
| [aspnetcore/performance/caching/output.md](https://github.com/dotnet/AspNetCore.Docs/blob/91e90e2eb5d982601a76133e296ac6321ee17924/aspnetcore/performance/caching/output.md) | [Output caching middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/output?branch=pr-en-us-32913) |
> Note about code sample

- aspnetcore/grpc/grpcweb/sample/6.x/GrpcGreeter/Program.cs
- aspnetcore/grpc/grpcweb/sample/7.x/GrpcGreeter/Program.cs
- aspnetcore/grpc/grpcweb/sample/8.x/GrpcGreeter/Program.cs
> Fix misspellings in GRPC examples

- quest-config.json
> Fix json syntax error in quest-config.json

- aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md
Fixes #32969
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/f959ca90f11e1c1a524f57521d5d67bf3ba35514/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md) | [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?branch=pr-en-us-32971) |
> Update example response type to code flow

- aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md
- aspnetcore/blazor/security/webassembly/standalone-with-microsoft-entra-id.md
- aspnetcore/blazor/supported-platforms.md
Fixes #32968
Fixes #32973
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a8ea4589c3780cbd616c06b0482fcd481b47469/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md) | [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?branch=pr-en-us-32972) |
| [aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md](https://github.com/dotnet/AspNetCore.Docs/blob/0a8ea4589c3780cbd616c06b0482fcd481b47469/aspnetcore/blazor/security/webassembly/standalone-with-mic …
> Improve security guidance cross-link

- aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md
Fixes #32978
---
|:--|:--|
| [aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md](https://github.com/dotnet/AspNetCore.Docs/blob/01b7633d9a579b1cb876af7913624919b2b00389/aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md) | [Account confirmation and password recovery in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/account-confirmation-and-password-recovery?branch=pr-en-us-32979) |
> Fix code sample error

- aspnetcore/blazor/supported-platforms.md
Fixes #32975
---
|:--|:--|
| [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/9fa6fa64171323a3067b4a3c5ada8e129af329a1/aspnetcore/blazor/supported-platforms.md) | [ASP.NET Core Blazor supported platforms](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?branch=pr-en-us-32976) |
> Remove IE11/polyfill coverage

- aspnetcore/blazor/components/index.md
Per https://github.com/dotnet/AspNetCore.Docs/pull/32747/files#r1646575217.
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/dcce1eeaa24eac3fac3f62ca0cedf81b05122d62/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-32983) |
> Change directive definition wording

- aspnetcore/mvc/views/razor.md
Per DR recommendation at https://github.com/dotnet/AspNetCore.Docs/pull/32747#discussion_r1646575217.
---
|:--|:--|
| [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/589a0143cadfcde1716795408de4d4c0c1877e74/aspnetcore/mvc/views/razor.md) | [Razor syntax reference for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?branch=pr-en-us-32995) |
> Change word 'parsed' to 'compiled'

- aspnetcore/tutorials/first-web-api.md
- aspnetcore/tutorials/first-web-api/includes/first-web-api3-7.md
- aspnetcore/tutorials/first-web-api/samples/2.2/TodoApi/Controllers/TodoController.cs
- aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/5.x/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/Controllers/TodoItemsController.cs
- aspnetcore/tutorials/first-web-api/samples/7.0/TodoApi/Controllers/TodoItemsController.cs
Fixes #32982
---
|:--|:--|
| [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/621cd0759857d1705849ee34e3024e1834244f9a/aspnetcore/tutorials/first-web-api.md) | [Tutorial: Create a web API with ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?branch=pr-en-us-33000) |
> Fix PostTodoItem method

- aspnetcore/blazor/components/quickgrid.md
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/e40d8507861c96eb2408c3cf2e422c262cb43534/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-33009) |
> [Blazor] quickgrid.md - scaffolder typo

- aspnetcore/diagnostics/asp0026.md
- aspnetcore/diagnostics/code-analysis.md
- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/asp0026.md
- aspnetcore/release-notes/aspnetcore-9/includes/web_asset_delivery.md
- aspnetcore/toc.yml
Fixes #33011 
Fixes #33012 
---
|:--|:--|
| [aspnetcore/diagnostics/asp0026.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b2d8563dad8bf536091d1ca26d5510b4b770433/aspnetcore/diagnostics/asp0026.md) | [aspnetcore/diagnostics/asp0026](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0026?branch=pr-en-us-33014) |
| [aspnetcore/diagnostics/code-analysis.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b2d8563dad8bf536091d1ca26d5510b4b770433/aspnetcore/diagnostics/code-analysis.md) | [Code analysis in ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?branch=pr-en-us-33014) |
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/4b2d8563dad8bf536091d1ca26 …
> Document ASP0026

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/openAPI_completion.md
Contributes to #33016
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/0940343d447b8c3c0b8bbcacc7e8d90a7b07b6ec/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33015) |
> WN OpenAPI completion

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/openAPI_completion.md
- aspnetcore/release-notes/aspnetcore-9/includes/optimize-file-delivery.md
See https://github.com/dotnet/AspNetCore.Docs/issues/33019#issuecomment-2217511741
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b8707dc06cc99b2bfea56625b11090530bcd5c9/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33021) |
> Add file delivery optimization to WN

- aspnetcore/fundamentals/static-files.md
contributes to #32782
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/0429764060bd1a376921d863e534b6e0d67fa7e4/aspnetcore/fundamentals/static-files.md) | [Static files in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-33046) |
> point to 9.x samples

- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #33067'
Thanks @voroninp! 🎸
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/691e4c77920a72b8808bb0581860d984af6411cd/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-33068) |
> Reflection requirement for JSON serialization

- aspnetcore/blazor/javascript-interoperability/index.md
Addresses #33067
Thanks @voroninp! 🎸
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/1732694ec8bb444c7581438a53bde8a23bac3ed5/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-33069) |
> Update reflection requirement language

- aspnetcore/release-notes/aspnetcore-2.2.md
- aspnetcore/release-notes/aspnetcore-6.0.md
Flagged on the latest build report.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-2.2.md](https://github.com/dotnet/AspNetCore.Docs/blob/d0ff0da3c849f8adad6aad71202f4084695517f3/aspnetcore/release-notes/aspnetcore-2.2.md) | [What's new in ASP.NET Core 2.2](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?branch=pr-en-us-33079) |
| [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d0ff0da3c849f8adad6aad71202f4084695517f3/aspnetcore/release-notes/aspnetcore-6.0.md) | [What's new in ASP.NET Core 6.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?branch=pr-en-us-33079) |
> Remove broken links

- aspnetcore/toc.yml
> Remove Postman from TOC

- aspnetcore/security/authorization/policies.md
Fixes #33085 Fixes #31986
---
|:--|:--|
| [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/8e521f5012638c9740157455c48deaa935e86716/aspnetcore/security/authorization/policies.md) | [Policy-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?branch=pr-en-us-33094) |
> remove Postman

- aspnetcore/grpc/test-tools.md
Addresses https://github.com/grpc/grpc-dotnet/issues/2483
---
|:--|:--|
| [aspnetcore/grpc/test-tools.md](https://github.com/dotnet/AspNetCore.Docs/blob/3df317a9a7729a9214a7b51e2a2c6d0772829d3d/aspnetcore/grpc/test-tools.md) | [Test gRPC services with gRPCurl and gRPCui in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/test-tools?branch=pr-en-us-33092) |
> gRPC reflection security

- aspnetcore/performance/caching/hybrid.md
- aspnetcore/performance/caching/hybrid/includes/overview.md
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/Program.cs
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Program.cs
Fixes #33052
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f785f94eb32dbca19c7678e5bb6b09bf0a8a2cd/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-33053) |
> Preview 6 updates to HybridCache

- aspnetcore/grpc/authn-and-authz.md
Follow on from https://github.com/dotnet/AspNetCore.Docs/pull/33092
---
|:--|:--|
| [aspnetcore/grpc/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/70837d5c2eac04d61f307813b77fd90620e4c35f/aspnetcore/grpc/authn-and-authz.md) | [Authentication and authorization in gRPC for ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?branch=pr-en-us-33096) |
> gRPC authorization extension methods

- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/virtualization.md
- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
- aspnetcore/blazor/performance.md
Fixes #33051
---
|:--|:--|
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f32cbfdf5d8a85fe7859d79fe2ec9596e5e84cc/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [ASP.NET Core Blazor cascading values and parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?branch=pr-en-us-33121) |
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f32cbfdf5d8a85fe7859d79fe2ec9596e5e84cc/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33121) |
| …
> Remove @-prefixed component param values

- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md
- aspnetcore/host-and-deploy/health-checks.md
- aspnetcore/migration/70-80.md
Found a few more after https://github.com/dotnet/AspNetCore.Docs/pull/33129.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b4309ffabc21e9204e7d9fa1fc8d6707936ab3b/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-33131) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b4309ffabc21e9204e7d9fa1fc8d6707936ab3b/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md) | ["RDG009: Invalid nested …
> Remove double words

- aspnetcore/test/http-files.md
Fixes #32958 
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/bb795b72ca0678d132a85cd91c89b9c1ccb79862/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-33113) |
> Dynamic endpoints discovery in Endpoints Explorer

- aspnetcore/includes/scaffold-identity/install-pkg.md
- aspnetcore/includes/scaffold-identity/migrations.md
- aspnetcore/razor-pages/ui-class.md
- aspnetcore/security/authentication/scaffold-identity.md
Fixes #32351
Notes ...
* There were a couple of NITs on the RCL naming: It should be all caps ("Razor Class Library") only when referring directly to the project template. Otherwise, it appears with a proper adjective for "Razor" and lowercase "class library" ("Razor class library") ... and the acronym "RCL" after first mention is fine. This is per DR's instructions ... *I lost the argument on it* 🙈😆.
* For Blazor, the Identity components are all just dumped into the app. There's no further pick-and-choose scaffolding. Therefore, there's only a *Scaffold Identity into a Blazor project* section being added here.
* Prior Blazor coverage for <8.0 is fine in its present form.
* The lead-in remarks for 8.0+ must change for Blazor, so I created a pair of sections at the top of the article. It …
> Update Blazor Identity scaffolding guidance

- aspnetcore/grpc/troubleshoot.md
- aspnetcore/grpc/troubleshoot/includes/troubleshoot3-7.md
- aspnetcore/grpc/troubleshoot/sample/8.0/GrpcGreeterClient/Program.cs
From offline conversation.
Fixes #33148
---
|:--|:--|
| [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/dafd1323d8d2c426964d3a53e9276590a2ac4a02/aspnetcore/grpc/troubleshoot.md) | [Troubleshoot gRPC on .NET](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?branch=pr-en-us-33141) |
> Update gRPC troubleshooting with HttpClient.Timeout

- .openpublishing.redirection.json
- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
- aspnetcore/fundamentals/openapi/includes/openapi9.md
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/a6356c8a7af925a2e9383f1ce3f0bb08311f773d/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Get started with Microsoft.AspNetCore.OpenApi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33158) |
> Update Mike's openapi PR

- aspnetcore/test/troubleshoot-azure-iis.md
contributes to [#32851](https://github.com/dotnet/AspNetCore.Docs/issues/32851)
@tdykstra  This is an exact copy paste of the article so it appears twice. I'm going to merge it into my branch [IIS-refactor/rick](https://github.com/dotnet/AspNetCore.Docs/tree/IIS-refactor/rick) without review.
Then I'll pull origin on `IIS-refactor/rick`, create a new branch, and make changes. That way you can see what I'm changing.
Once you approve the changes, I'll again merge and create a new branch and move the refactored article to two topics (copy and paste, so no review required).
Once I'm done, I'm merge `IIS-refactor/rick` into main. 
We'll have to live with the Duplicate heading: 'H2 'App startup errors'' until I split the articles up.
> test refactor

- aspnetcore/blazor/hybrid/security/index.md
Addresses #33147
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/36aa4ec49d59522f44f25712d21a1f8905b0ba70/aspnetcore/blazor/hybrid/security/index.md) | [ASP.NET Core Blazor Hybrid authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/index?branch=pr-en-us-33169) |
> Add cross-links to external security articles

- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
Fixes #32541
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/e73f9d40b59c4f868c7cdc16304f44a969c947d7/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?branch=pr-en-us-33171) |
| [aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md](https://github.com/dotnet/AspNetCore.Docs/blob/e73f9d40b59c4f868c7cdc16304f44a969c947d7/aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md) | [Secure a …
> Remark on ownership to add API permission

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #32568
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/276e36740eaeb0fbee8ca67fca33f96202c1803f/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-33172) |
> Add subdomain+subapp hosting section

- aspnetcore/blazor/components/integration.md
Fixes #32672
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/4d373243a3834b5ba31bcb020e489a26ef6a7c31/aspnetcore/blazor/components/integration.md) | [Integrate ASP.NET Core Razor components into ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-33174) |
> Improve the Integration article introduction

- aspnetcore/blazor/globalization-localization.md
Fixes #33143
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/e67b5df406ede51d3f7dd9dfc4a080452cc35966/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-33175) |
> Mention the lang attribute in the glob/loc article

- aspnetcore/fundamentals/dependency-injection.md
Fixes #33177 
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/9e85e197a574df96bfa8c39d5635e519bcff8316/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-33178) |
> Link to .NET DI articles

- aspnetcore/tutorials/choose-web-ui.md
Small single line H2 Fix
Fixes #33188
---
|:--|:--|
| [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/32059084f5b9be2291a947aabb29a12b4be5bc09/aspnetcore/tutorials/choose-web-ui.md) | [Choose an ASP.NET Core web UI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?branch=pr-en-us-33189) |
> Choose Web UI: section title fix

- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/javascript-interoperability/index.md
- aspnetcore/blazor/security/includes/troubleshoot-server.md
- aspnetcore/blazor/security/includes/troubleshoot-wasm.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #33202
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/db6cb143ec4f9b020fb9bfa2acecf1e263da4b75/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?branch=pr-en-us-33211) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/db6cb143ec4f9b020fb9bfa2acecf1e263da4b75/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-33211) |
| …
> Update Mozilla tool doc links

- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/fundamentals/static-files.md
Fixes #32744
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdc9b44ed095f09949804b236987dd67e4797499/aspnetcore/blazor/fundamentals/routing.md) | [ASP.NET Core Blazor routing and navigation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-33212) |
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/fdc9b44ed095f09949804b236987dd67e4797499/aspnetcore/blazor/fundamentals/static-files.md) | [ASP.NET Core Blazor static files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33212) |
> Add section on avoiding file capture

- aspnetcore/host-and-deploy/iis/logging-and-diagnostics.md
contributes to #32851
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/logging-and-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b78258a5a2f719091c067ebc7f2d32a7c9c81cb/aspnetcore/host-and-deploy/iis/logging-and-diagnostics.md) | [Log creation and redirection](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?branch=pr-en-us-33199) |
> Fix Azure bouncing

- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #33220
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/b15ff1e2ddd512b7d2329f7ac6e91ee018494a75/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-33223) |
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b15ff1e2ddd512b7d2329f7ac6e91ee018494a75/aspnetcore/blazor/javascript-interoperability/index.md) | [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en- …
> Drop BWA coverage from JS-SPA article

- .github/CODEOWNERS
> new CODEOWNERS file

- aspnetcore/includes/not-latest-version.md
> Fix not-latest-version include file

- aspnetcore/fundamentals/index.md
- aspnetcore/fundamentals/index/includes/index3-7.md
Fixes #33232
---
|:--|:--|
| [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2a8e45d20cbe1f4b30560a37c9a04e5607a3d7ca/aspnetcore/fundamentals/index.md) | [ASP.NET Core fundamentals overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/index?branch=pr-en-us-33233) |
> Prep article for a .NET 8 moniker section

- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6b103fa63c840ac26c5ea3464105a61784c2/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-33256) |
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6b103fa63c840ac26c5ea3464105a61784c2/aspnetcore/blazor/forms/index.md) | [ASP.NET Core Blazor forms overview](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-33256) |
| [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/4f0e6 …
> Dropping 8.0 Blazor tracking

- aspnetcore/includes/trustCertVSC.md
- aspnetcore/security/docker-compose-https.md
- aspnetcore/security/docker-https.md
- aspnetcore/security/enforcing-ssl.md
Reverts dotnet/AspNetCore.Docs#33221
Once you give approval, I'll apply these commit to main & then merge to live.
---
|:--|:--|
| [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/e6042ed0c797680fbc6d4e1d06031fc18dd00235/aspnetcore/security/docker-compose-https.md) | [Hosting ASP.NET Core images with Docker Compose over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?branch=pr-en-us-33263) |
| [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/e6042ed0c797680fbc6d4e1d06031fc18dd00235/aspnetcore/security/docker-https.md) | [Hosting ASP.NET Core Images with Docker over HTTPS](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-ht …
> Revert "Update Linux dev cert trust instructions"

- aspnetcore/security/authorization/policies.md
Fixes #33288
---
|:--|:--|
| [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/874aa92d8d2a248aa72b86bf7597ed9c1876575b/aspnetcore/security/authorization/policies.md) | [Policy-based authorization in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?branch=pr-en-us-33285) |
> Use correct example for applying multiple policies to MVC controllers

- aspnetcore/client-side/bundling-and-minification.md
- aspnetcore/client-side/dotnet-interop.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/33290
---
|:--|:--|
| [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca368268232cf388ac8a8bac37a697a1809e4359/aspnetcore/client-side/bundling-and-minification.md) | [Bundle and minify static assets in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?branch=pr-en-us-33291) |
| [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca368268232cf388ac8a8bac37a697a1809e4359/aspnetcore/client-side/dotnet-interop.md) | [Run .NET from JavaScript](https://review.learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?branch=pr-en-us-33291) |
> Grammar updates

- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/performance.md
Fixes #33292
Guessing a bit on the coverage from the issues/PR.
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/ccd8ac2fcfadb96e67157d050ffec3d60e10cda2/aspnetcore/blazor/globalization-localization.md) | [ASP.NET Core Blazor globalization and localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-33293) |
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/ccd8ac2fcfadb96e67157d050ffec3d60e10cda2/aspnetcore/blazor/performance.md) | [ASP.NET Core Blazor performance best practices](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-33293) |
> Add timezone code/data control coverage

- aspnetcore/blazor/hybrid/security/index.md
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/fe6f850cbeb8335d0cbe8bd2373a2028e915c4ca/aspnetcore/blazor/hybrid/security/index.md) | [ASP.NET Core Blazor Hybrid authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/index?branch=pr-en-us-33297) |
> Add missing characters

- aspnetcore/fundamentals/native-aot/includes/native-aot8.md
Contributes to #33302
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/35c7c8659a001894592cf1af1a0c2ee7ea799d89/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for Native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-33304) |
> AOT Mon prep

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/customize-named-pipes.md
- aspnetcore/release-notes/aspnetcore-9/includes/exception-type-sets-http-status.md
- aspnetcore/release-notes/aspnetcore-9/includes/improved-kestrel-connection-metrics.md
- aspnetcore/release-notes/aspnetcore-9/includes/openapi-aot.md
- aspnetcore/release-notes/aspnetcore-9/includes/produces-problem.md
- aspnetcore/release-notes/aspnetcore-9/includes/transformer-registration.md
Fixes #33316 
Fixes #33314 
Fixes #33313 
Fixes #33311 
Fixes #33310 
Fixes #33308
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/3d57121d9a482fd9e97cb49fc2b9010d3f53fe50/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33317) |
> Add new features to What's new

- aspnetcore/log-mon/metrics/metrics.md
---
|:--|:--|
| [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/48145e40f1291246dc00438e896e05e25c581131/aspnetcore/log-mon/metrics/metrics.md) | [ASP.NET Core metrics](https://review.learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?branch=pr-en-us-33321) |
> riande to own metrics

- aspnetcore/blazor/components/js-spa-frameworks.md
- aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md
- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #32897
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/f89a53fa58d2e2dbc19e9147fe21bd0864dc1982/aspnetcore/blazor/components/js-spa-frameworks.md) | [Use Razor components in JavaScript apps and SPA frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-33335) |
| [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/f89a53fa58d2e2dbc19e9147fe21bd0864dc1982/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md) | [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blaz …
> Refactor JS event handler examples

- aspnetcore/fundamentals/native-aot.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/33302
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-9.0&branch=pr-en-us-33306#aspnet-core-and-native-aot-compatibility)
@eerhardt  note this is the .NET 9 file, .NET 8 stays the same.
---
|:--|:--|
| [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/cd2e0cb600718153483bfecf230790fae3b42a50/aspnetcore/fundamentals/native-aot.md) | [ASP.NET Core support for Native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-33306) |
> Add SignalR to AOT

- aspnetcore/release-notes/aspnetcore-2.2.md
- aspnetcore/release-notes/aspnetcore-9/includes/par.md
- aspnetcore/release-notes/aspnetcore-9/samples/PAR/Program.cs
Contributes to #33307
@josephdecock  please review
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-2.2.md](https://github.com/dotnet/AspNetCore.Docs/blob/14adef987bbf3ed1a02e8399b492fab9bc71fcd6/aspnetcore/release-notes/aspnetcore-2.2.md) | [What's new in ASP.NET Core 2.2](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?branch=pr-en-us-33334) |
> Include of PAR for WN9 /b

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/opt_out_metrics.md
- aspnetcore/release-notes/aspnetcore-9/samples/Metrics/Metrics.csproj
- aspnetcore/release-notes/aspnetcore-9/samples/Metrics/Program.cs
Contributes to #33315
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/93a821a4620fa77858e6b2017459fe95a881c20a/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33342) |
> WN9 : Opt/out/metrics/ra/3

- aspnetcore/release-notes/aspnetcore-9/includes/opt_out_metrics.md
- aspnetcore/release-notes/aspnetcore-9/samples/Metrics/Program.cs
> Opt out metrics/wn/4/ra

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/delete_keys.md
- aspnetcore/release-notes/aspnetcore-9/includes/opt_out_metrics.md
- aspnetcore/release-notes/aspnetcore-9/includes/par.md
Fixes #33307
Fixes #33312
Fixes #33315
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/a0f5b9fd77bbd55692ef5551db07370304c81ac8/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33344) |
> Update WN9 include links

- aspnetcore/blazor/components/quickgrid.md
Fixes #33347
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/5f752a1ab26fbae3e86867fcd2fc75abaed178c2/aspnetcore/blazor/components/quickgrid.md) | [ASP.NET Core Blazor `QuickGrid` component](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-33348) |
> Change paginator remark

- aspnetcore/release-notes/aspnetcore-9.0.md
Fixes #33350
VTP - verify all content from [P7 issue/notes](https://github.com/dotnet/AspNetCore.Docs/issues/33031) was added
OK to merge this
@tdykstra  you can use this for your VTP unless you have a better idea.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/edea34e546fcf1481146dda4a1baff520f4493e1/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33352) |
> VTP only, will not merge: WN 9.7 Verify all P7 content was added.

- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal/Program.cs
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/HCMinimal.csproj
- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Program.cs
Fixes #33339 
Merge Tuesday morning
> Preview 7 changes to HybridCache

- aspnetcore/performance/caching/hybrid.md
Follow-up to #33339 
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/517e16515afbfcd62a8d88791a21c809f364abe8/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-33358) |
> Update hybrid.md, specify pkg version to install

- aspnetcore/security/data-protection/implementation/key-management.md
Fixes #33365
---
|:--|:--|
| [aspnetcore/security/data-protection/implementation/key-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/891a9670ae61dc15f189cc965fefb05d165d44f6/aspnetcore/security/data-protection/implementation/key-management.md) | [Key management in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?branch=pr-en-us-33364) |
> Remove note about lack data protection deletion API

- aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/33373
---
|:--|:--|
| [aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/c2b3fdb7babf20d286747f335069d01e7d1151d8/aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md) | [Enable QR code generation for TOTP authenticator apps in an ASP.NET Core Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/qrcodes-for-authenticator-apps?branch=pr-en-us-33375) |
> Add TOTP security warning

- aspnetcore/security/authentication/claims.md
fixes https://github.com/dotnet/AspNetCore.Docs/issues/33332
---
|:--|:--|
| [aspnetcore/security/authentication/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/108625b884f5d29b431226954cbec7069a996d4d/aspnetcore/security/authentication/claims.md) | [Mapping, customizing, and transforming claims in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?branch=pr-en-us-33366) |
> .NET 9: OpenIdConnectHandler adds support for Pushed Authorization Requests (PAR) 

- aspnetcore/tutorials/choose-web-ui.md
---
|:--|:--|
| [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/270cac4eb60f3464befeae803a1cb31b74a872c2/aspnetcore/tutorials/choose-web-ui.md) | [Choose an ASP.NET Core web UI](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?branch=pr-en-us-33372) |
> Recommend Blazor for UI in .NET 9

- aspnetcore/fundamentals/environments.md
Fixes #33388
---
|:--|:--|
| [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ee7aa5dffe4205351383b2712b6d10452c8c4a4/aspnetcore/fundamentals/environments.md) | [Use multiple environments in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?branch=pr-en-us-33389) |
> Fix incorrect names of Azure portal UI elements

- aspnetcore/blazor/project-structure.md
Fixes #33393
Thanks @WILLEM-LENS! 🚀 ... I'm going to try a version of this that calls out the possible locations where the files/folders reside.
---
|:--|:--|
| [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/9066e28295829b432a5abbaf19c861c09e461235/aspnetcore/blazor/project-structure.md) | [ASP.NET Core Blazor project structure](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?branch=pr-en-us-33396) |
> Improve BWA project structure coverage

- aspnetcore/blazor/security/server/index.md
Fixes #32667
* Change the name to avoid confusion ... `AuthenticationService` :point_right: `CustomAuthenticationService`.
* Have the ctor use the new `AuthenticationState(user)` that was just created and assigned to `authenticationState`. Confirmed with Halter offline that this update is 👍.
> Improve custom auth service provider

- aspnetcore/blazor/images-and-documents.md
---
|:--|:--|
| [aspnetcore/blazor/images-and-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/dabd7f5979659cfeb5ba31f8f05d82cf249d1e83/aspnetcore/blazor/images-and-documents.md) | [Display images and documents in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/images-and-documents?branch=pr-en-us-33404) |
> Remove stray backslash

- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles-net-5-to-7.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
- aspnetcore/release-notes/aspnetcore-9/includes/signalr-trimming-aot.md
- aspnetcore/toc.yml
Fixes #33401
Thanks @Echostorm44! 🚀 ...
* The simplest way to address the situation was to make a new article for the old content. It's clearly labeled for ".NET 5 to .NET 7" with a NOTE telling readers to see the latest article for the most up-to-date information. The .NET 5-7 article will appear in the table of contents when the doc version selector is 5.0-7.0.
* There's a new sample app for this scenario at https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAssemblyEntraGroupsAndRoles.
* I'm going to 🛌💤 sleep on this and make final updates Wednesday morning before merging it. 
Thanks for the issue. I would've reached this article *eventually* ⛏️🗻😅 for a general overhaul, but I'm glad you reported the problem with the code now to perhaps save other devs trouble with the …
> Blazor ME-ID Groups & Roles article updates

- aspnetcore/blazor/includes/prerendering.md
Fixes  #32124
I'm going to go ahead with this @hakenr to clear it through in this week's batch of work.
Let me know if you spot any problems. 👂 Thanks for the issue.
> Simplify prerendered interop section

- aspnetcore/blazor/security/server/index.md
Fixes #32797
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e72d5d9fcc0c713356ce37058867bd57aaa02fc2/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-33419) |
> Authentication state management at sign out

- aspnetcore/fundamentals/best-practices.md
---
|:--|:--|
| [aspnetcore/fundamentals/best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/148406d7a92e51ab5a482cb3d7e80abb427c3684/aspnetcore/fundamentals/best-practices.md) | [ASP.NET Core Best Practices](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?branch=pr-en-us-33392) |
> Add links to Azure Service Bus where relevant

- aspnetcore/fundamentals/error-handling.md
- aspnetcore/fundamentals/error-handling/samples/9.x/ErrorHandlingSample/ErrorHandlingSample.csproj
- aspnetcore/fundamentals/error-handling/samples/9.x/ErrorHandlingSample/Program.cs
Fixes #33437 
---
|:--|:--|
| [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef25e1981169d23685ce01a16f6e7f8996347c2e/aspnetcore/fundamentals/error-handling.md) | [Handle errors in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-33438) |
> Add option to ExceptionHandlerMiddleware to choose status code based on exception

- aspnetcore/blazor/advanced-scenarios.md
- aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/forms/binding.md
- aspnetcore/blazor/forms/index.md
- aspnetcore/blazor/forms/input-components.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/blazor/fundamentals/routing.md
Fixes #33420
Samps updated on https://github.com/dotnet/blazor-samples/pull/343.
---
|:--|:--|
| [aspnetcore/blazor/advanced-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/32e1243133d531d863bdaa6a1e8f2fe24565753d/aspnetcore/blazor/advanced-scenarios.md) | [ASP.NET Core Blazor advanced scenarios (render tree construction)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?branch=pr-en-us-33443) |
| [aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/32e1243133d531d863bdaa6a1e8f2fe24565753d/aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md) | [ASP.NET Core Razor class libraries (RCLs) with static server-side …
> Make [SupplyParameterFrom{X}] props private

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
- aspnetcore/fundamentals/openapi/includes/aspnetcore-openapi6-8.md
Fixes #33432
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/8a56e6864012148543a6300e76c1c23ba35b1217/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Work with OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33433) |
> ProducesProblem not for route groups in .NET 8

- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/components/rendering.md
- aspnetcore/blazor/components/synchronization-context.md
- aspnetcore/blazor/components/virtualization.md
- aspnetcore/blazor/includes/prerendering.md
- aspnetcore/blazor/progressive-web-app.md
- aspnetcore/blazor/security/server/additional-scenarios.md
- aspnetcore/blazor/security/server/interactive-server-side-rendering.md
Fixes #33421
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/2fdd48e5e81bc834ca6685809c5e42239647d435/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-33452) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/2fdd48e5e81bc834ca6685809c5e42239647d435/aspnetcore/blazor/components/lifecycle.md) | [ASP.NET Core Razor component lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-33452) |
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotn …
> Clarify how StateHasChanged works

- aspnetcore/performance/caching/hybrid/samples/9.x/HCMinimal2/Program.cs
Use `AddSerializerFactory` instead of `WithSerializerFactory`
> HybridCache: Update code for using SerializerFactory

- aspnetcore/blazor/components/dynamiccomponent.md
Fixes #33453
Thanks @ShaunCurtis! 🚀 ... I'll wrap this up and get it merged on Wednesday morning.
---
|:--|:--|
| [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/5aff7c087b258b20bf3540cb9bbdbb71dc2a0842/aspnetcore/blazor/components/dynamiccomponent.md) | [Dynamically-rendered ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?branch=pr-en-us-33461) |
> Add section for DynamicComponent Instance property

- aspnetcore/blazor/host-and-deploy/webassembly.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/fca9a9fbdedefe21682ef7581794254e20248f96/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-33468) |
> Fix link reference

- aspnetcore/blazor/fundamentals/startup.md
Link to reference documentation of what the feature that can be disabled actually even is.
Without the link, the reader has to already know or search and discover for themselves what the concept even is.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/9d1421f65b9d86ebcd679b41d126879e76c4fcfd/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-33470) |
> Add reference link to enhanced navigation and form handling

- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/security/includes/troubleshoot-server.md
- aspnetcore/blazor/security/index.md
Fixes #33474
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/ad2cca5d06bf0a23298e8ce0493ef8d1f447eab6/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-33475) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/ad2cca5d06bf0a23298e8ce0493ef8d1f447eab6/aspnetcore/blazor/security/index.md) | [ASP.NET Core Blazor authentication and authorization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-33475) |
> Swap `.Any()` for `.Count()`

- aspnetcore/blazor/tooling.md
---
|:--|:--|
| [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/fadc7847e74cce53b30dfc1931556876f9bbcc34/aspnetcore/blazor/tooling.md) | [Tooling for ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tooling?branch=pr-en-us-33480) |
> fix typo (WebAssmebly -> WebAssembly)

- aspnetcore/blazor/images-and-documents.md
Fixes #33482
---
|:--|:--|
| [aspnetcore/blazor/images-and-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/00d676ac18bd9fa9acea1fa8c0132a93c122a729/aspnetcore/blazor/images-and-documents.md) | [Display images and documents in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/images-and-documents?branch=pr-en-us-33483) |
> Promote NOTE to article text

- aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md
Fixes #33484
---
|:--|:--|
| [aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/0f8d0cfcfe1fed034feec35a195b32b736b0d1ce/aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md) | [Enable QR code generation for TOTP authenticator apps in an ASP.NET Core Blazor Web App](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/qrcodes-for-authenticator-apps?branch=pr-en-us-33485) |
> Improve site (company) name setting coverage

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/host-and-deploy/server.md
Fixes #33486
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca60ccf236eba882ebc8aa29d6e0428ae458cc34/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-33487) |
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/ca60ccf236eba882ebc8aa29d6e0428ae458cc34/aspnetcore/blazor/host-and-deploy/server.md) | [Host and deploy server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-33487) |
> Use "session affinity" terminology

- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/Program.cs
- aspnetcore/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/WebMinOpenApi.csproj
- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
Fixes #33457 
Switch to .NET 9 in the internal preview to see the transformers section.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/77bd7e3758da7af784eb3cef6ff3b45e50e65f76/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [Work with OpenAPI documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-33463) |
> Improvements to transformer registration APIs in Microsoft.AspNetCore.OpenApi

- aspnetcore/migration/inc/usage_guidance.md
cc @Rick-Anderson 
---
|:--|:--|
| [aspnetcore/migration/inc/usage_guidance.md](https://github.com/dotnet/AspNetCore.Docs/blob/c4fcd6fa7f98e69cf7590eca9e91c0582a2c6938/aspnetcore/migration/inc/usage_guidance.md) | [Usage Guidance](https://review.learn.microsoft.com/en-us/aspnet/core/migration/inc/usage_guidance?branch=pr-en-us-33496) |
> Update usage_guidance.md - typo

- aspnetcore/release-notes/aspnetcore-9/includes/openapi-aot.md
- aspnetcore/release-notes/aspnetcore-9/includes/signalr-trimming-aot.md
> Native AOT capitalization

- aspnetcore/migration/20_21.md
- aspnetcore/migration/22-to-30.md
- aspnetcore/mvc/models/validation.md
- aspnetcore/mvc/models/validation/includes/validation6.md
- aspnetcore/mvc/views/view-compilation.md
- aspnetcore/razor-pages/ui-class/includes/ui-class6.md
- aspnetcore/release-notes/aspnetcore-2.1.md
- aspnetcore/security/authentication/customize-identity-model.md
- aspnetcore/security/authentication/identity.md
Fixes #33499
---
|:--|:--|
| [aspnetcore/migration/20_21.md](https://github.com/dotnet/AspNetCore.Docs/blob/010fe625cda41f0f49c982700725c7118c90c48a/aspnetcore/migration/20_21.md) | [Migrate from ASP.NET Core 2.0 to 2.1](https://review.learn.microsoft.com/en-us/aspnet/core/migration/20_21?branch=pr-en-us-33500) |
| [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/010fe625cda41f0f49c982700725c7118c90c48a/aspnetcore/migration/22-to-30.md) | [[Visual Studio](#tab/visual-studio)](https://review.learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?branch=pr-en-us-33500) |
| [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/010fe625cda41f0f49c982700725c7118c90c48a/aspnetcore/mvc/models/validation. …
> RCL casing

- aspnetcore/fundamentals/host/generic-host.md
- aspnetcore/fundamentals/host/generic-host/samples/6.x/GenericHostSample/Snippets/Program.cs
- aspnetcore/fundamentals/host/web-host.md
- aspnetcore/security/enforcing-ssl.md
Fixes #33380 
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/35c50038cad3a33e9a475fcfd3feebaa84fc963b/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-33489) |
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/35c50038cad3a33e9a475fcfd3feebaa84fc963b/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-33489) |
| [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/35c50038cad3a33e9a47 …
> Clarify meaning of {PREFIX}_HTTPS_PORTS vs. _PORT

- aspnetcore/blazor/blazor-ef-core.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/tutorials/movie-database-app/index.md
- aspnetcore/blazor/tutorials/movie-database-app/part-4.md
Fixes #33523
Addresses #33504
Notes ...
* There are two Blazor articles that pertain to use of a local dB, the new BWA tutorial and the old Blazor+EF Core article+sample.
* I couldn't make good use of an INCLUDE because I use different language between the tutorial and article.
* Sections made more sense than a NOTE in these cases.
* I definitely can't cross-link to what you guys are cross-linking ... implicit flow for SPAs 🤮😄. We'd need a PKCE cross-link for our Blazor scenarios. Since things are covered in the Blazor security node, that's where I cross-link.
* No period used after the word "node" in the lists or after article title text of the cross-links. These aren't complete sentences, and it's funky to period titles and phrases in pure lists IMO.
* I like the bit you placed, Rick, …
> ROPC for Blazor

- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #33530.
cc @guardrex 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/c2b2a29db051dcfd9c60a94581306b27b96e466d/aspnetcore/blazor/fundamentals/dependency-injection.md) | [ASP.NET Core Blazor dependency injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-33536) |
> [Blazor] Constructor injection updates

- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Relates to #33530.
...found one more instance of the sample (portion).
cc @guardrex
> What's new .NET 9 - Blazor constructor injection sample

- aspnetcore/blazor/webassembly-build-tools-and-aot.md
Fixes #33535
Thanks @ite-klass! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/webassembly-build-tools-and-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/9143655d7962f588f11fdbe45b4a050ec7423aaa/aspnetcore/blazor/webassembly-build-tools-and-aot.md) | [ASP.NET Core Blazor WebAssembly build tools and ahead-of-time (AOT) compilation](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-build-tools-and-aot?branch=pr-en-us-33540) |
> Add cross-links for exception handling docs

- aspnetcore/tutorials/first-mvc-app/working-with-sql.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql/includes/working-with-sql3-5.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql/includes/working-with-sql6.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql/includes/working-with-sql7.md
- aspnetcore/tutorials/first-mvc-app/working-with-sql/includes/working-with-sql8.md
Fixes #33543
Contributes to #33407
15 minutes, tiny way over estimates time
Exact same global find/replace as #33408 for the `sql.md` files.
---
|:--|:--|
| [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/48e94214fd49ef28243a7fbded5cbc07e2af953c/aspnetcore/tutorials/first-mvc-app/working-with-sql.md) | [Part 5, work with a database in an ASP.NET Core MVC app](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?branch=pr-en-us-33542) |
> MVC ROPC warning

- aspnetcore/fundamentals/host/generic-host.md
- aspnetcore/fundamentals/host/web-host.md
Fixes #33548 
---
|:--|:--|
| [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/529d5c2c7c4f831a80c1385e3bf5059318d83027/aspnetcore/fundamentals/host/generic-host.md) | [.NET Generic Host in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?branch=pr-en-us-33549) |
| [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/529d5c2c7c4f831a80c1385e3bf5059318d83027/aspnetcore/fundamentals/host/web-host.md) | [ASP.NET Core Web Host](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?branch=pr-en-us-33549) |
> Fix description of ASPNETCORE_HTTPS_PORT

- aspnetcore/docfx.json
Fixes #33567
Thanks @GioviQ! 🚀 ... This will take a few weeks to become effective because translation of articles is on a schedule and doesn't happen immediately.
> Update no-loc in docfx.json

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/trust_dev_cert_linux.md
[Trust the ASP.NET Core HTTPS development certificate on Linux](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0&branch=pr-en-us-33564)
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/7408d1038e8ef04261ae8a202ab9c356ae97eb01/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33564) |
> WN: certs /5

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/trust_dev_cert_linux.md
Fixes #33575
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/1d8818c6645b6c2136451fc79e28736cf2095b9f/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33576) |
> Connect Cert to TOC

- aspnetcore/blazor/debug.md
Fixes #33168
---
|:--|:--|
| [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/f3801037bd345b69e449c9b7ef77227049c33c67/aspnetcore/blazor/debug.md) | [Debug ASP.NET Core apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/debug?branch=pr-en-us-33170) |
> Drop debugger support section

- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/blazor/security/webassembly/graph-api.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles-net-5-to-7.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
Fixes #33539
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c4699584ac7a189259ef6fedd5cb73f7a7bc4ce8/aspnetcore/blazor/fundamentals/index.md) | [ASP.NET Core Blazor fundamentals](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/index?branch=pr-en-us-33573) |
| [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/c4699584ac7a189259ef6fedd5cb73f7a7bc4ce8/aspnetcore/blazor/security/webassembly/graph-api.md) | [Use Graph API with ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?branch=pr-en-us-33573) |
| [aspnetcore/blazor/security/webassembly/microsoft-entra-id-gr …
> MS Graph sample cross-links and article updates

- aspnetcore/blazor/security/server/interactive-server-side-rendering.md
Fixes #33581
---
|:--|:--|
| [aspnetcore/blazor/security/server/interactive-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/5417bdedeea23a3afacc839d8010c65c1c139461/aspnetcore/blazor/security/server/interactive-server-side-rendering.md) | [Threat mitigation guidance for ASP.NET Core Blazor interactive server-side rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/interactive-server-side-rendering?branch=pr-en-us-33582) |
> Surface Azure Application Gateway

- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/fundamentals/handle-errors.md
Fixes #33492
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/0674980b205e042a5b31b05deca198e3d838b169/aspnetcore/blazor/file-uploads.md) | [ASP.NET Core Blazor file uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-33585) |
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/0674980b205e042a5b31b05deca198e3d838b169/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-33585) |
> ErrorBoundary subclassing and context

- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
Fixes #33609
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/standalone-with-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/5517a3ef1b4212e3d892b8efa3d9a1973f7e0afc/aspnetcore/blazor/security/webassembly/standalone-with-identity.md) | [Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?branch=pr-en-us-33610) |
> Stronger guidance for using Identity cookies

- aspnetcore/blazor/fundamentals/environments.md
- aspnetcore/blazor/fundamentals/logging.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/globalization-localization.md
- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Fixes #33614
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/edfb8216f907895d2c2cb4f72a846d42a87f88e4/aspnetcore/blazor/fundamentals/environments.md) | [ASP.NET Core Blazor environments](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?branch=pr-en-us-33615) |
| [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/edfb8216f907895d2c2cb4f72a846d42a87f88e4/aspnetcore/blazor/fundamentals/logging.md) | [ASP.NET Core Blazor logging](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?branch=pr-en-us-33615) |
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/ed …
> Enhance placeholder lines

- aspnetcore/blazor/tutorials/movie-database-app/part-6.md
Fixes #33619
Thanks @sdtrip7s! 🚀 ... As soon as I merge this, I'll take it live. It will appear in the article in about ten minutes.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/74d2bd9db3013b0746404ec3b5786fe7d9d1d32a/aspnetcore/blazor/tutorials/movie-database-app/part-6.md) | [Build a Blazor movie database app (Part 6 - Add search)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-6?branch=pr-en-us-33621) |
> Update query string name

- aspnetcore/security/cors.md
- aspnetcore/security/cors/includes/cors56.md
- aspnetcore/security/cors/includes/cors7.md
Fixes #33519
I made the same changes in all the files via global search/replace.
---
|:--|:--|
| [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef5a82bf6dde7b8d3889321d2f326c3b25f513e7/aspnetcore/security/cors.md) | [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-33601) |
> remove Azure test site /3

- aspnetcore/blazor/fundamentals/handle-errors.md
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/c0cb8e2e9285d16bf22c346b27ea78bf7e5d7489/aspnetcore/blazor/fundamentals/handle-errors.md) | [Handle errors in ASP.NET Core Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?branch=pr-en-us-33628) |
> Patch example code

- aspnetcore/includes/managed-identities-test-non-production.md
- aspnetcore/security/index.md
- aspnetcore/tutorials/razor-pages/sql.md
Fixes #33518
SEE [Secure authentication flows](https://review.learn.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-8.0&branch=pr-en-us-33521#secure-authentication-flows) 
To see how it's used, see the warning above [this link](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-8.0&branch=pr-en-us-33521&tabs=visual-studio#sql-server-express-localdb)
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/32fe2efd9d6ace65a1cb2beaa274ec4180699871/aspnetcore/security/index.md) | [ASP.NET Core security topics](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-33521) |
| [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNe …
> Recommend against ROPC /2

- aspnetcore/fundamentals/app-state.md
- aspnetcore/fundamentals/configuration/index.md
- aspnetcore/fundamentals/dependency-injection.md
- aspnetcore/fundamentals/environments.md
- aspnetcore/fundamentals/error-handling.md
- aspnetcore/fundamentals/index.md
- aspnetcore/fundamentals/localization.md
- aspnetcore/fundamentals/logging/index.md
- aspnetcore/fundamentals/native-aot.md
- aspnetcore/fundamentals/routing.md
- aspnetcore/fundamentals/startup.md
- aspnetcore/fundamentals/static-files.md
- aspnetcore/getting-started/index.md
- aspnetcore/host-and-deploy/index.md
- aspnetcore/performance/overview.md
- aspnetcore/security/authentication/accconfirm.md
- aspnetcore/signalr/configuration.md
- aspnetcore/signalr/introduction.md
- aspnetcore/test/debug-aspnetcore-source.md
- aspnetcore/toc.yml
Fixes #33555
---
|:--|:--|
| [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/2b44a2199ccabd61700c2eb1a24a2978996d6d84/aspnetcore/fundamentals/app-state.md) | [Session and state management in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?branch=pr-en-us-33577) |
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2b44a2199ccabd61700c2eb1a24a2978996d6d84/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-33577) |
| …
> Blazor cross-links

- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/blazor/images-and-documents.md
Fixes #33647
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/3668f9eb93124e82d08043611103732746538cc0/aspnetcore/blazor/components/event-handling.md) | [ASP.NET Core Blazor event handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-33648) |
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/3668f9eb93124e82d08043611103732746538cc0/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33648) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/3668f9eb93 …
> Enhance loop variable rendering coverage

- aspnetcore/blazor/components/index.md
Addresses #33647
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c7487875dcde5168c2475ccb43cd8ce3567a199e/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33649) |
> Language updates to loop varaible content

- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/fundamentals/index.md
Fixes #33651
---
|:--|:--|
| [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bda1b4686de2dca9c098c180e787f11a248f0c96/aspnetcore/blazor/components/index.md) | [ASP.NET Core Razor components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/index?branch=pr-en-us-33652) |
| [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/bda1b4686de2dca9c098c180e787f11a248f0c96/aspnetcore/blazor/fundamentals/index.md) | [ASP.NET Core Blazor fundamentals](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/index?branch=pr-en-us-33652) |
> Blazor conventions updates

- aspnetcore/blazor/fundamentals/startup.md
Fixes #33657
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/11654b50b27990639d550b2ebaaa2c88f525808c/aspnetcore/blazor/fundamentals/startup.md) | [ASP.NET Core Blazor startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-33658) |
> Add link to runtime doc request issue

- aspnetcore/includes/managed-identities-test-non-production.md
- aspnetcore/tutorials/razor-pages/sql.md
This should be a warning, not a note.
---
|:--|:--|
| [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/2931dc84d1bf644b75dd7e9e23854ef2bf47ef9b/aspnetcore/tutorials/razor-pages/sql.md) | [Part 4 of tutorial series on Razor Pages](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?branch=pr-en-us-33638) |
> Update include  managed-identities-test-non-production.md

- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #33670
Thanks @Schaeri! 🚀 ... Hopefully, some folks will find this and understand what the plan is. This is probably going to be a regular question in the community.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d4e3b2e0bf4bac05192eeb64959a6e11a1110e77/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-33683) |
> Surface migration remark on multiple BWA support

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #33684
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/bebf3a8068fb063f229e1b639dae9c6e09e6a3c5/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [Build a Blazor movie database app (Part 2 - Add and scaffold a model)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-33685) |
> Drop trademark attribution

- aspnetcore/grpc/versioning.md
---
|:--|:--|
| [aspnetcore/grpc/versioning.md](https://github.com/dotnet/AspNetCore.Docs/blob/ea1903429795f7722373e6fedc63cf29941c5f2c/aspnetcore/grpc/versioning.md) | [Versioning gRPC services](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/versioning?branch=pr-en-us-33680) |
> Update grpc versioning to make point clearer

- aspnetcore/blazor/fundamentals/signalr.md
Fixes #33718
Thanks @garrettlondon1! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/2b804e57d8c6f0f0a3204ad195c397cb14df87d9/aspnetcore/blazor/fundamentals/signalr.md) | [ASP.NET Core Blazor SignalR guidance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?branch=pr-en-us-33719) |
> Improve session affinity remarks

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #33709
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/713e5c21011a22bd86843046d1ccff9306a2f347/aspnetcore/blazor/host-and-deploy/webassembly.md) | [Host and deploy ASP.NET Core Blazor WebAssembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-33720) |
> Add Azure Static Web Apps from VSC

- aspnetcore/blazor/security/webassembly/additional-scenarios.md
Fixes #33722
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/c5e99e9e0a84ed3a2a006e5494b33a0bd19dc247/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [ASP.NET Core Blazor WebAssembly additional security scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-33723) |
> Fix custom auth message handler example

- aspnetcore/migration/configuration.md
Fixes #33733
---
|:--|:--|
| [aspnetcore/migration/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/5e84509acccfbf02539ad1d7713fa717f4c400ac/aspnetcore/migration/configuration.md) | [Migrate configuration to ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/migration/configuration?branch=pr-en-us-33732) |
> Update configuration.md ropc

- aspnetcore/performance/caching/distributed.md
- aspnetcore/performance/caching/distributed/includes/distributed5.md
- aspnetcore/performance/caching/distributed/includes/distributed6-7.md
Fixes #33735
---
|:--|:--|
| [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/a9182b3bb13d5d4e1e01c59579df3ea8dd1d707e/aspnetcore/performance/caching/distributed.md) | [Distributed caching in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?branch=pr-en-us-33734) |
> ROPC caching

- quest-config.json
I had the wrong one in my previous PR
> fix default parent node

- aspnetcore/blazor/security/server/index.md
- aspnetcore/security/cors/includes/cors56.md
Fixes #33776
---
|:--|:--|
| [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/68383ba7cb7cbec822d379412526d942becbe32c/aspnetcore/blazor/security/server/index.md) | [Secure ASP.NET Core server-side Blazor apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/server/index?branch=pr-en-us-33777) |
> Blazor Identity UI description updates

- aspnetcore/blazor/components/generic-type-support.md
Fixes #33775
Thanks @macias! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/generic-type-support.md](https://github.com/dotnet/AspNetCore.Docs/blob/76930fa382d85cdb6cc3bb2f769126b28bd5496b/aspnetcore/blazor/components/generic-type-support.md) | [ASP.NET Core Razor component generic type support](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/generic-type-support?branch=pr-en-us-33778) |
> Remark on components as generic types

- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Fixes #33780
Thanks @gstoynev-arrowstream! 🚀 ... This PR will pull in the updated code from the [Blazor samples PR](https://github.com/dotnet/blazor-samples/pull/357).
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/location-of-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/08c047e6611d6d99cf2e0ff42f598d9ed95f3b06/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md) | [aspnetcore/blazor/javascript-interoperability/location-of-javascript](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?branch=pr-en-us-33781) |
> Pull updated code example into article

- aspnetcore/security/authorization/secure-data.md
Fixes #33701
---
|:--|:--|
| [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/aad99d0fe8caf0b586a85739d10ecaa4c691754a/aspnetcore/security/authorization/secure-data.md) | [Create an ASP.NET Core web app with user data protected by authorization](https://review.learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?branch=pr-en-us-33768) |
> change warning text in secure-data

- aspnetcore/fundamentals/openapi/includes/aspnetcore-openapi6-8.md
The link was broken, updated it.
Perhaps we should use a permalink here?
> Fix broken code link in OpenApi docs

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/prerendering-and-integration.md
Fixes #33767
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/7ac1fb3dded4dbfae0e52144aaa5ed844ec69ba1/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-33806) |
| [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/7ac1fb3dded4dbfae0e52144aaa5ed844ec69ba1/aspnetcore/blazor/components/prerendering-and-integration.md) | [aspnetcore/blazor/components/prerendering-and-integration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?branch=pr-en-us-33806) |
> Remark on DP protection of persisted component state

- aspnetcore/blazor/security/webassembly/additional-scenarios.md
- aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md
- aspnetcore/blazor/security/webassembly/hosted-with-microsoft-entra-id.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/migration/31-to-50.md
- aspnetcore/security/authentication/azure-ad-b2c.md
Fixes #33807
Found a few in the main doc set, too.
---
|:--|:--|
| [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/33a27fd21768c7aeff2ab39383961300d7e1dde6/aspnetcore/blazor/security/webassembly/additional-scenarios.md) | [aspnetcore/blazor/security/webassembly/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?branch=pr-en-us-33808) |
| [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/33a27fd21768c7aeff2ab39383961300d7e1dde6/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md) | …
> Correct capitalization

- aspnetcore/performance/caching/distributed/includes/distributed5.md
- aspnetcore/performance/caching/distributed/includes/distributed6-7.md
> Fix comment syntax

- aspnetcore/release-notes/aspnetcore-9.0.md
- aspnetcore/release-notes/aspnetcore-9/includes/updated-versions.md
Fixes #33810 
Contributes to #33713
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-9.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/c84ecd56028497d7e0934a4f98ec1eca9e1a9be9/aspnetcore/release-notes/aspnetcore-9.0.md) | [What's new in ASP.NET Core 9.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?branch=pr-en-us-33811) |
> Add include ref for updated versions

- aspnetcore/fundamentals/configuration/index.md
Fixes #33822 
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d8eaa01aa00a709a3162ddd96b7cfad99fe1db2/aspnetcore/fundamentals/configuration/index.md) | [Configuration in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?branch=pr-en-us-33825) |
> Fix text that introduces a CLI block

- aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md
@guardrex Please merge the PRs in `blazor-samples` first:
* https://github.com/dotnet/blazor-samples/pull/351
* https://github.com/dotnet/blazor-samples/pull/352
Hope the "future `ms.date`" won't cause any issue in the pipeline. :-D
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/d62272a421b4e9bff3e05a9e579bbcd84548975e/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md) | [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?branch=pr-en-us-33774) |
> [Blazor] call-javascript-from-dotnet.md - pull sample code updates

- aspnetcore/security/index.md
Fixes #33817
Per https://github.com/dotnet/AspNetCore.Docs/pull/33805#discussion_r1791047939
cc @guardrex 
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc9dd2c05ce866ce8c9b7d27e4ff3372d438eb1f/aspnetcore/security/index.md) | [aspnetcore/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-33816) |
> Update AKV and others per blowdart /2

- aspnetcore/blazor/globalization-localization.md
Fixes #33847
Thanks @Schoof-T! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/3e689251de35e7336f91bed169667143d63eb995/aspnetcore/blazor/globalization-localization.md) | [aspnetcore/blazor/globalization-localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-33848) |
> Request Localization MW processing location

- aspnetcore/toc.yml
Fix typo in TOC
NSWag => NSwag
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/9da60771c146fcb74a7e0784f8028f4e1b8427f1/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-33852) |
> Fix typo NSWag => NSwag

- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
Fixes #33851
Thanks @VR-Architect! 🚀 ... I'll try to get to the other issue and figure out roles/groups soon.
---
|:--|:--|
| [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/3546165eaf455b7ed7b77453d1c7d9aaa8b3514c/aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md) | [aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app?branch=pr-en-us-33855) |
> Add cross-link to MAUI security article

- aspnetcore/blazor/fundamentals/static-files.md
Fixes #33867
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/f92048f7e2f052a1ea49d7cc65259b65bb62ab7e/aspnetcore/blazor/fundamentals/static-files.md) | [aspnetcore/blazor/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?branch=pr-en-us-33868) |
> Cross-link main doc set Static Files article

- aspnetcore/blazor/components/built-in-components.md
- aspnetcore/blazor/components/cascading-values-and-parameters.md
- aspnetcore/blazor/components/control-head-content.md
- aspnetcore/blazor/components/data-binding.md
- aspnetcore/blazor/components/dynamiccomponent.md
- aspnetcore/blazor/components/element-component-model-relationships.md
- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/components/generic-type-support.md
- aspnetcore/blazor/components/index.md
- aspnetcore/blazor/components/layouts.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/overwriting-parameters.md
- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/rendering.md
- aspnetcore/blazor/components/splat-attributes-and-arbitrary-parameters.md
- aspnetcore/blazor/components/synchronization-context.md
- aspnetcore/blazor/components/templated-components.md
- aspnetcore/blazor/components/virtualization.md
Addresses #33869
---
|:--|:--|
| [aspnetcore/blazor/components/built-in-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/d93ac653339dc6e326dd5c15a51137a55da13f45/aspnetcore/blazor/components/built-in-components.md) | [aspnetcore/blazor/components/built-in-components](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?branch=pr-en-us-33870) |
| [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/d93ac653339dc6e326dd5c15a51137a55da13f45/aspnetcore/blazor/components/cascading-values-and-parameters.md) | [aspnetcore/blazor/components/cascading-values-and-parameters](https://review.l …
> Cross-link 9.0 sample code

- aspnetcore/blazor/blazor-ef-core.md
- aspnetcore/toc.yml
Fixes #33888
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/e217477f13ec8672df9e8bd22de167d410e6804d/aspnetcore/blazor/blazor-ef-core.md) | [aspnetcore/blazor/blazor-ef-core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-33889) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/e217477f13ec8672df9e8bd22de167d410e6804d/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-33889) |
> Cross-link movie tutorial in EF Core article

- aspnetcore/blazor/forms/index.md
Fixes #33890
---
|:--|:--|
| [aspnetcore/blazor/forms/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e270aa1ef317211fdf7e9bbc77029209ef463504/aspnetcore/blazor/forms/index.md) | [aspnetcore/blazor/forms/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/forms/index?branch=pr-en-us-33892) |
> jQuery unobtrusive validation isn't supported

- aspnetcore/fundamentals/localization.md
- aspnetcore/fundamentals/localization/includes/localization35.md
- aspnetcore/fundamentals/localization/includes/make-content-localizable5.md
- aspnetcore/fundamentals/localization/includes/provide-resources5.md
- aspnetcore/fundamentals/localization/includes/select-language-culture5.md
- aspnetcore/fundamentals/localization/includes/select-language-culture67.md
- aspnetcore/fundamentals/localization/make-content-localizable.md
- aspnetcore/fundamentals/localization/provide-resources.md
- aspnetcore/fundamentals/localization/select-language-culture.md
- aspnetcore/security/authentication/azure-ad-b2c.md
- aspnetcore/security/ip-safelist.md
Switching away from twitter
---
|:--|:--|
| [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/025f01d86762644660d5f1dc78dfbc5a2d91e3d2/aspnetcore/fundamentals/localization.md) | [aspnetcore/fundamentals/localization](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?branch=pr-en-us-33905) |
| [aspnetcore/fundamentals/localization/make-content-localizable.md](https://github.com/dotnet/AspNetCore.Docs/blob/025f01d86762644660d5f1dc78dfbc5a2d91e3d2/aspnetcore/fundamentals/localization/make-content-localizable.md) | [aspnetcore/fundamentals/localization/make-content-localizable](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?branch=pr-en-us-339 …
> Update social links Damien Bowden

- aspnetcore/security/index.md
Fixes #33904
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/1d9365d4a067d0c4d91a1daaf9a48bb1826228ee/aspnetcore/security/index.md) | [aspnetcore/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-33903) |
> env variables not encryped

- .github/workflows/blazor-issue-processing.yml
@adegeo @Rick-Anderson @tdykstra @wadepickett ... *Pinged to 💀.* I probably just should've pinged you at the very end of all of this churn.
What I'll do is finish my work without pinging you guys further), and then I'll open a new issue for discussion on refactoring initial issue labeling to use an Action instead of Repoman for reliability (***IF*** I can get this conditional-based approach to work).
> Condition Blazor job on comment body

- aspnetcore/blazor/blazor-ef-core.md
*I'm LOSING IT!* 🙈😆 *I need a vacation!* 🏖️ 
---
|:--|:--|
| [aspnetcore/blazor/blazor-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/9e4fa8f30beeb31bdf6278e980821ef17e43cbd7/aspnetcore/blazor/blazor-ef-core.md) | [aspnetcore/blazor/blazor-ef-core](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?branch=pr-en-us-33944) |
> Update EF Core article spelling

- .github/workflows/blazor-issue-processing.yml
---
|:--|:--|
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/ccea076a6fc9096bdcd828fc17aef4f2d130a384/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-issue-processing?branch=pr-en-us-33951) |
> Update Blazor issue processing

- aspnetcore/security/index.md
Use rich diff.
---
|:--|:--|
| [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/eeba623322f52354b140b8ef37d8ecb0d80eacd7/aspnetcore/security/index.md) | [aspnetcore/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/security/index?branch=pr-en-us-33918) |
> Secure auth flow update

- .github/workflows/blazor-issue-processing.yml
Addresses #34006
We'll go with a more sophisticated conditional check to prevent accidental issue processing. This is a test. If this works, I'll fix up the rest of the checks here and in the Blazor Hybrid issue processing YAML file.
---
|:--|:--|
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/14769bc1acca92b890f21e7973c04e041fca5093/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-issue-processing?branch=pr-en-us-34014) |
> Issue processing test

- .github/workflows/blazor-issue-processing.yml
Addresses #34006
A `\n` didn't work. I'll try a `<br>` ............
---
|:--|:--|
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/eba5723a8f2034cd16dd6334634b1cc5d67b9316/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-issue-processing?branch=pr-en-us-34016) |
> Second attempt at Blazor issue processing

- .github/workflows/blazor-hybrid-issue-processing.yml
- .github/workflows/blazor-issue-processing.yml
Fixes #34006
The other attempts didn't work, so I'll check on just the GH link.
The first attempt really should've worked ...
---
|:--|:--|
| [.github/workflows/blazor-hybrid-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/b152d57302ca88090dce9253e7aad9daa5f49ae3/.github/workflows/blazor-hybrid-issue-processing.yml) | [.github/workflows/blazor-hybrid-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-hybrid-issue-processing?branch=pr-en-us-34020) |
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/b152d57302ca88090dce9253e7aad9daa5f49ae3/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.m …
> Final solution for Blazor issue processing

- aspnetcore/blazor/components/js-spa-frameworks.md
Fixes #34034 
Thanks for the report @wujido! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/7f10c6711466bea42206ebf946c1382f07c4698e/aspnetcore/blazor/components/js-spa-frameworks.md) | [aspnetcore/blazor/components/js-spa-frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-34036) |
> Fix bad identifier

- aspnetcore/blazor/file-downloads.md
Fixes #34038
---
|:--|:--|
| [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/9a8c86af810a87c4b4959b26daae74d305da1403/aspnetcore/blazor/file-downloads.md) | [aspnetcore/blazor/file-downloads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?branch=pr-en-us-34039) |
> Remove unnecessary information

- aspnetcore/fundamentals/openapi/include-metadata.md
This PR adds content on how to specify attributes on record parameters and how the set of required properties is determined for a class/struct/record.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/62bac442e095c6c1facac91304f6c24870b20ce8/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-34023) |
> Describe attribute on record parameters and explain required

- aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md
- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md
- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/components/sections.md
- aspnetcore/blazor/hybrid/troubleshoot.md
- aspnetcore/blazor/hybrid/tutorials/maui-blazor-web-app.md
- aspnetcore/blazor/javascript-interoperability/static-server-rendering.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md
- aspnetcore/blazor/security/server/qrcodes-for-authenticator-apps.md
- aspnetcore/blazor/security/server/static-server-side-rendering.md
- aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity.md
- aspnetcore/blazor/tutorials/movie-database-app/index.md
- aspnetcore/blazor/tutorials/movie-database-app/part-1.md
- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
- aspnetcore/blazor/tutorials/movie-database-app/part-3.md
- aspnetcore/blazor/tutorials/movie-database-app/part-4.md
- aspnetcore/blazor/tutorials/movie-database-app/part-5.md
- aspnetcore/blazor/tutorials/movie-database-app/part-6.md
- aspnetcore/blazor/tutorials/movie-database-app/part-7.md
- aspnetcore/blazor/tutorials/movie-database-app/part-8.md
---
|:--|:--|
| [aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/d29bf0bd326200c080a22f47aa3373fe75ed50b0/aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering.md) | [aspnetcore/blazor/components/class-libraries-and-static-server-side-rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries-and-static-server-side-rendering?branch=pr-en-us-34099) |
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/d29bf0bd326200c080a22f47aa3373fe75ed50b0/aspnetcore/blazor/components/integration.md) | …
> Activate preview notices

- aspnetcore/fundamentals/index/includes/index8.md
---
|:--|:--|
| [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/1d408e538326af05caab472e2050c1e24f61c2d5/aspnetcore/fundamentals/index.md) | [ASP.NET Core fundamentals overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/index?branch=pr-en-us-34111) |
> WIP: Moniker prep Fundamentals overview

- aspnetcore/blazor/tutorials/movie-database-app/part-1.md
Fixes #34117
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-1.md](https://github.com/dotnet/AspNetCore.Docs/blob/856745a076d7a262f564f6445effa40346398713/aspnetcore/blazor/tutorials/movie-database-app/part-1.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-1](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-1?branch=pr-en-us-34118) |
> Temporarily use 8.0 framework

- aspnetcore/includes/out-of-support.md
Fixes #34153
I didn't realize it when making updates to the not-latest-version INCLUDE that this INCLUDE also requires a 9.0 update.
> Update the out-of-support INCLUDE file

- aspnetcore/toc.yml
Fixes #34177 
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/90e2dbb7c9898571a7284110b256a856b795da30/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-oidc-web-authentication?view=aspnetcore-9.0&branch=pr-en-us-34184) |
> Fix OIDC node in TOC

- aspnetcore/host-and-deploy/windows-service.md
Fixes #34197 
---
|:--|:--|
| [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/69f0c9ca5741f0b5a952824c778846390944a8f3/aspnetcore/host-and-deploy/windows-service.md) | [Host ASP.NET Core in a Windows Service](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?branch=pr-en-us-34206) |
> highlight correct lines

- aspnetcore/signalr/introduction.md
This topic has been updated but the metadata ms.date was not.  Reviewed to make sure it is still good as-is for freshness.
Minor change, updated the metadata:
- ms.date: changed to current date.
- author: bradyg to wpickett.  Brady does not want to be on it.
---
|:--|:--|
| [aspnetcore/signalr/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/a85b178f4e422330f9371a870f97861e5edb6acc/aspnetcore/signalr/introduction.md) | [aspnetcore/signalr/introduction](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/introduction?branch=pr-en-us-34256) |
> Freshness review - SignalR Overivew

- aspnetcore/blazor/javascript-interoperability/static-server-rendering.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/34101#pullrequestreview-2474007697
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/static-server-rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/cafa883ade77548e9c12a6f0a878229f668ddfee/aspnetcore/blazor/javascript-interoperability/static-server-rendering.md) | [aspnetcore/blazor/javascript-interoperability/static-server-rendering](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?branch=pr-en-us-34262) |
> Patch Blazor enhanced nav events

- aspnetcore/fundamentals/aot/native-aot-tutorial.md
- aspnetcore/test/http-files.md
- aspnetcore/tutorials/first-mvc-app/start-mvc.md
- aspnetcore/tutorials/min-web-api.md
- aspnetcore/tutorials/razor-pages/razor-pages-start.md
Fixes #34263
|:--|:--|
| [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/2c096f60181d12d2caf81f39cf6293aa68856c5f/aspnetcore/fundamentals/aot/native-aot-tutorial.md) | [Tutorial: Publish an ASP.NET Core app using Native AOT](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?branch=pr-en-us-34209) |
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/2c096f60181d12d2caf81f39cf6293aa68856c5f/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en-us-34209) |
| [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Do …
> Update .NET 9 Preview to .NET 9

- aspnetcore/blazor/test.md
Addresses #34271
@egil ... How's this look?
... and I'll ping you back on that issue probably the first week of February.
---
|:--|:--|
| [aspnetcore/blazor/test.md](https://github.com/dotnet/AspNetCore.Docs/blob/c12efee51c675caef8e2b14e93e5462abdef0350/aspnetcore/blazor/test.md) | [aspnetcore/blazor/test](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/test?branch=pr-en-us-34274) |
> Swap video link

- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/host-and-deploy/server.md
- aspnetcore/blazor/hybrid/class-libraries.md
- aspnetcore/blazor/hybrid/reuse-razor-components.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/index.md
- aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md
- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #34272
---
|:--|:--|
| [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/d483f88ee2d30b0c47f6e4e13e7f4df5bd4cfd87/aspnetcore/blazor/file-uploads.md) | [aspnetcore/blazor/file-uploads](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?branch=pr-en-us-34277) |
| [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/d483f88ee2d30b0c47f6e4e13e7f4df5bd4cfd87/aspnetcore/blazor/host-and-deploy/server.md) | [aspnetcore/blazor/host-and-deploy/server](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?branch=pr-en-us-34277) |
| [aspnetcore/blazor/hybrid/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/d483f …
> Blazor 9.0 updates

- aspnetcore/host-and-deploy/index.md
Fixes #33618
---
|:--|:--|
| [aspnetcore/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/887f0e9c3db298f2a3f2ee55f018f03e818d2e77/aspnetcore/host-and-deploy/index.md) | [Host and deploy ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/index?branch=pr-en-us-34254) |
> Link to /dotnet/core/deploying

- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/rendering.md
- aspnetcore/migration/80-to-90/includes/blazor.md
Fixes #34300
---
|:--|:--|
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/df49885fe2a25df3e0529bfaa1c755b5283d9f31/aspnetcore/blazor/components/lifecycle.md) | [aspnetcore/blazor/components/lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-34305) |
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/df49885fe2a25df3e0529bfaa1c755b5283d9f31/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-34305) |
| [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/ …
> Prerendering waits for quiescence

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #34205
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/be5dbfb2c993396407766383b8e5d52b8fe50369/aspnetcore/blazor/host-and-deploy/webassembly.md) | [aspnetcore/blazor/host-and-deploy/webassembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-34304) |
> Add context on calling fetch with no-cache

- aspnetcore/blazor/host-and-deploy/index.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/6870d8ce9af079be830758aa879126a780d9c8b5/aspnetcore/blazor/host-and-deploy/index.md) | [aspnetcore/blazor/host-and-deploy/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-34330) |
> [Blazor] Host and Deploy - {TARGET FRAMEWORK} placeholder + naming

- aspnetcore/blazor/host-and-deploy/index.md
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/b67cb13d8d5878753c350134f4fbeb1ef11da5d4/aspnetcore/blazor/host-and-deploy/index.md) | [aspnetcore/blazor/host-and-deploy/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-34331) |
> Line patch

- aspnetcore/blazor/host-and-deploy/index.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/34330/files#r1879145393
Just going to place it for the first mention in each list.
cc: @hakenr ... Got it. I should've just waited until morning. It's late here (8pm👴🙈) , and I'm headed to 🛌💤. 
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/5457002727230b79907dd474ee67d2c25ecedf76/aspnetcore/blazor/host-and-deploy/index.md) | [aspnetcore/blazor/host-and-deploy/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/index?branch=pr-en-us-34334) |
> Placeholder line updates

- aspnetcore/blazor/globalization-localization.md
Addresses #32020
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/c6a6772af036413ef6c964a91a9eccbafe269bff/aspnetcore/blazor/globalization-localization.md) | [aspnetcore/blazor/globalization-localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-34338) |
> Blazor glob/loc aritcle updates

- aspnetcore/blazor/performance.md
---
|:--|:--|
| [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a61f450cfb5e14abf44ed7e7654abe052b32582/aspnetcore/blazor/performance.md) | [aspnetcore/blazor/performance](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance?branch=pr-en-us-34291) |
> [Blazor] Performance - Parameter values bundling vs. change detection

- aspnetcore/blazor/components/overwriting-parameters.md
Addresses #34360
Pulling new code examples from the samples repo.
---
|:--|:--|
| [aspnetcore/blazor/components/overwriting-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/75243aa0567c3e182a52253930e503fc38175609/aspnetcore/blazor/components/overwriting-parameters.md) | [aspnetcore/blazor/components/overwriting-parameters](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?branch=pr-en-us-34362) |
> Pull new code examples

- aspnetcore/fundamentals/startup.md
Fixes #34358 
---
|:--|:--|
| [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/1207206c1071e391fe4c6ad4cd5c441e021c986a/aspnetcore/fundamentals/startup.md) | [App startup in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?branch=pr-en-us-34359) |
> Add Blazor to the list of app types

- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Improving the section in advance of additional updates TBD based on an offline convo with the product unit.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/3714da6be6ceff7e748fd1af98def75c69e4e1a1/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?branch=pr-en-us-34370) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/3714da6be6ceff7e748fd1af98def75c69e4e1a1/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://r …
> Improve the redirect on logout section

- aspnetcore/blazor/javascript-interoperability/index.md
Fixes #33842
Thanks @hakenr! ⛄ ... Here's a synthesis of your discussion with Steve for the end of the section.
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/8c4b5de65e2b9e7ae3f44ae7b0a28a9fd1190acf/aspnetcore/blazor/javascript-interoperability/index.md) | [aspnetcore/blazor/javascript-interoperability/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/index?branch=pr-en-us-34379) |
> MutationObserver and DOM element removal

- aspnetcore/security/cross-site-scripting.md
Tom ... Patch update as I was passing through looking for a spot to discuss Map Static Assets routing conventions and CSP headers. Blazor has a dedicated CSP article, but the main doc set doesn't, so I'm passing that issue to Rick for the main *Static Assets* article. Anyway, I was passing through here a noticed some NITs 😈 to touch in the *XSS* article.
* All of the characters for HTML attribute encoding can be listed, as there's only four of them (for the `HttpUtility` class anyway). Probably best to just list them. The current line ends ...
> ... characters such as " and ".
... which doesn't make sense.
* HTML attribute encoding isn't a superset. It doesn't contain more characters. It contains fewer, so that should be a "subset."
* Missing period from one line.
I didn't convert any of …
> Updates to XSS article

- .github/workflows/blazor-hybrid-issue-processing.yml
- .github/workflows/blazor-issue-processing.yml
@tdykstra @wadepickett @Rick-Anderson ... This will activate my annual OOF message on new Blazor issues, and they'll be labeled, assigned, and placed into their projects as usual. I intend to let them sit until I get back from some much needed R&R 🏖️. ***I'm toast!*** 😩😆 Email me tho if you need anything. *Happy Holidays!!!* 🎁 
---
|:--|:--|
| [.github/workflows/blazor-hybrid-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/6f1ad0d39f8fc3b1638fea386bab460f265e8c95/.github/workflows/blazor-hybrid-issue-processing.yml) | [.github/workflows/blazor-hybrid-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-hybrid-issue-processing?branch=pr-en-us-34408) |
| …
> Activate holiday message for Blazor issue processing

- aspnetcore/fundamentals/middleware/index.md
Fixes #33662 
---
|:--|:--|
| [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/c12959aa223abe71d03b5ad85690c26ce7787368/aspnetcore/fundamentals/middleware/index.md) | [ASP.NET Core Middleware](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?branch=pr-en-us-34405) |
> Fix reference to terminal middleware

- aspnetcore/blazor/globalization-localization.md
Fixes #34426
Thanks @gregoryagu! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/31a89533ef6765ce63231b5acc9cb657d89db706/aspnetcore/blazor/globalization-localization.md) | [aspnetcore/blazor/globalization-localization](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?branch=pr-en-us-34430) |
> Remove NOTE on broswer UI language

- aspnetcore/fundamentals/dependency-injection.md
Fixes #34417
Contributes to #34356 
---
|:--|:--|
| [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/4643d4fe0d07ac3ee629a374f7b21c5ea1fb4012/aspnetcore/fundamentals/dependency-injection.md) | [Dependency injection in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?branch=pr-en-us-34418) |
> Update ASP.NET Core fundamentals DI doc to highlight Blazor

- aspnetcore/toc.yml
Fixes #34333 
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/5265fb17b9aa15f40df218897a4a23ac5dfb8274/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/rdg-ids?view=aspnetcore-9.0&branch=pr-en-us-34397) |
> Move RDG analyzers in TOC to analyzers area

- aspnetcore/data/ef-rp/intro.md
Fixes #34420 
---
|:--|:--|
| [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/892fc46d4fa3c8d840f295d8588a1120452f8993/aspnetcore/data/ef-rp/intro.md) | [aspnetcore/data/ef-rp/intro](https://review.learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?branch=pr-en-us-34421) |
> fix sqlite option for aspnet codegenerator

- aspnetcore/fundamentals/target-aspnetcore.md
- aspnetcore/grpc/client.md
- aspnetcore/grpc/netstandard.md
- aspnetcore/grpc/supported-platforms.md
- aspnetcore/signalr/messagepackhubprotocol.md
- aspnetcore/signalr/supported-platforms.md
- aspnetcore/whats-new/index.yml
Fixes #34324
Removed or updated references to Xamarin in this repository.
---
|:--|:--|
| [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/3555c7a77bc4949b8800bc92b075ac349ed24a13/aspnetcore/fundamentals/target-aspnetcore.md) | [aspnetcore/fundamentals/target-aspnetcore](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?branch=pr-en-us-34460) |
| [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/3555c7a77bc4949b8800bc92b075ac349ed24a13/aspnetcore/grpc/client.md) | [aspnetcore/grpc/client](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/client?branch=pr-en-us-34460) |
| [aspnetcore/grpc/netstandard.md](https://github.com/dotnet/AspNetCore.Docs/blob/35 …
> Xamarin reference updates

- aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md
Fixes #34500
---
|:--|:--|
| [aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b8788881f6a3abd1a590caf0d199faf6dbe2f1b/aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md) | [aspnetcore/blazor/security/qrcodes-for-authenticator-apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/qrcodes-for-authenticator-apps?branch=pr-en-us-34501) |
| [aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/5b8788881f6a3abd1a590caf0d199faf6dbe2f1b/aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md) | …
> TOTP time skew section

- aspnetcore/blazor/javascript-interoperability/location-of-javascript.md
Addresses #34371
---
|:--|:--|
| [aspnetcore/blazor/javascript-interoperability/location-of-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a146dd0ca6b15861437908581731c1111f7d80b/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md) | [aspnetcore/blazor/javascript-interoperability/location-of-javascript](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?branch=pr-en-us-34517) |
> Minor script tag guidance language change

- aspnetcore/blazor/components/event-handling.md
- aspnetcore/blazor/includes/js-interop/js-collocation.md
Fixes #34548
---
|:--|:--|
| [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a48bd586cde99ab2aa9432543936bce7edf5167/aspnetcore/blazor/components/event-handling.md) | [aspnetcore/blazor/components/event-handling](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?branch=pr-en-us-34549) |
> Remark on async delegate event handler examples

- aspnetcore/blazor/webassembly-native-dependencies.md
Fixes #34552
---
|:--|:--|
| [aspnetcore/blazor/webassembly-native-dependencies.md](https://github.com/dotnet/AspNetCore.Docs/blob/9b60ca3050c5f4082a2dc62d3942bc8958e90ea0/aspnetcore/blazor/webassembly-native-dependencies.md) | [aspnetcore/blazor/webassembly-native-dependencies](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?branch=pr-en-us-34553) |
> WASM Native Dependencies article UE pass

- aspnetcore/grpc/index.md
Minor update to ms.date.
This topic is up to date, changed the ms.date to indicate that is so.
---
|:--|:--|
| [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/7026685cfa6c5e416dbb179f8940a0263d7c4023/aspnetcore/grpc/index.md) | [aspnetcore/grpc/index](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/index?branch=pr-en-us-34562) |
> gRPC overview: freshness review - minor change -date update

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/44a5c54470115795ca69775caed68594434343e7/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [Configure JWT bearer authentication in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-34597) |
> fix: #34596 typo

- aspnetcore/security/anti-request-forgery.md
No associated issue. The fix levels up the minimal APIs section out of [JavaScript, AJAX, and SPAs] so it will occur in the table of contents.
Fixes #34627
---
|:--|:--|
| [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/297329e0d62675aad2cf2d2aa69a62d3484b3bb8/aspnetcore/security/anti-request-forgery.md) | [aspnetcore/security/anti-request-forgery](https://review.learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?branch=pr-en-us-34589) |
> Add minimal APIs section to contents of anti-request-forgery.md

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/security/index.md
Fixes #34630
Thanks again, @silajim 🚀  and @MarkusKirschnerLumivero! 🚀 
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/983633b860c84fe6eab2950d9d3c0a34c99ab0a9/aspnetcore/blazor/components/render-modes.md) | [aspnetcore/blazor/components/render-modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-34631) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/983633b860c84fe6eab2950d9d3c0a34c99ab0a9/aspnetcore/blazor/security/index.md) | [aspnetcore/blazor/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-34631) |
> Static SSR in interactive apps improvements

- aspnetcore/toc.yml
Fixes #34649 
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/26f7a429b51d9f461ed5433369fc4cfb1330daaf/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34648) |
> Update toc.yml to add what's new in 10

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/fundamentals/servers/kestrel/includes/kestrel6.md
- aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md
- aspnetcore/grpc/performance.md
- aspnetcore/host-and-deploy/proxy-load-balancer.md
- aspnetcore/migration/inc/abtesting.md
- aspnetcore/migration/inc/overview.md
- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
Fixes #34661
cc: @wadepickett @tdykstra @Rick-Anderson ... Popped up on a build report this morning, and I'm fixing them across the repo.
> Fix broken YARP cross-link

- aspnetcore/fundamentals/minimal-apis.md
Typo on ms.date corrected from last update.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/736aa9433e30dcee64d6e7c711078c2cbdad1eb8/aspnetcore/fundamentals/minimal-apis.md) | [aspnetcore/fundamentals/minimal-apis](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?branch=pr-en-us-34671) |
> Update ms.date typo on minimal-apis.md

- aspnetcore/tutorials/getting-started-with-NSwag.md
This topic is no longer being carried forward with updates.  Reviewed for freshness considering it is to be frozen.  Updated ms.date
---
|:--|:--|
| [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3bc14e533aadb509696a2d450ddc2bb0699a663/aspnetcore/tutorials/getting-started-with-NSwag.md) | [aspnetcore/tutorials/getting-started-with-NSwag](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-NSwag?branch=pr-en-us-34672) |
> Update ms.date for frozen getting-started-with-NSwag.md

- aspnetcore/fundamentals/localization/select-language-culture.md
Fixes #30655
---
|:--|:--|
| [aspnetcore/fundamentals/localization/select-language-culture.md](https://github.com/dotnet/AspNetCore.Docs/blob/cb0d0bd3b3c5dc86484180f6f2796bc158a84c74/aspnetcore/fundamentals/localization/select-language-culture.md) | [aspnetcore/fundamentals/localization/select-language-culture](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?branch=pr-en-us-34677) |
> Clarify the provided cultures in CookieRequestCultureProvider

- aspnetcore/fundamentals/servers/yarp/extensibility.md
- aspnetcore/toc.yml
Fixes #34693
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/2f0af8b950107255b4aa06844c53226b3c8239d0/aspnetcore/fundamentals/servers/yarp/extensibility.md) | [aspnetcore/fundamentals/servers/yarp/extensibility](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/extensibility?branch=pr-en-us-34694) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/2f0af8b950107255b4aa06844c53226b3c8239d0/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34694) |
> Add overview of extensibility part 1

- aspnetcore/toc.yml
Fixes #34686 
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/6365808865d25bd689b19f5ddd5cb3ea3d717331/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34696) |
> Remove redundant YARP from TOC

- aspnetcore/release-notes/aspnetcore-10.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/6f73709120da00c13a92b2dffcf122fe0b580cb2/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34720) |
> Add OpenAPI

- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
- aspnetcore/release-notes/aspnetcore-10/includes/responseDescProducesResponseType.md
- aspnetcore/release-notes/aspnetcore-10/includes/testAppsTopLevel.md
> MikeKistler OpenAPI etc migration to WN 10

- aspnetcore/toc.yml
Late additions to the issue that were missed earlier.
https://github.com/dotnet/AspNetCore.Docs/issues/34686#issuecomment-2649685514
https://github.com/dotnet/AspNetCore.Docs/issues/34686#issuecomment-2649626100
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/3ef8d3f26e203c34c2795860ce7111929a12aa38/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34721) |
> Update toc.yml -- Follow-up to #34686

- aspnetcore/mvc/models/model-binding.md
Fixes #34733 
---
|:--|:--|
| [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/dc1d8375919d0dc3e530b99e8d26c09ef92a4941/aspnetcore/mvc/models/model-binding.md) | [Model Binding in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?branch=pr-en-us-34738) |
> Fix syntax error in example in model-binding.md

- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
> openAPI drop two samples, use diff only

- aspnetcore/release-notes/aspnetcore-10.0.md
Fixes #34749
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/d8362ff55a5c168e99253181a5f325baa9711d09/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34758) |
> WN: IsLocalUrl

- aspnetcore/grpc/json-transcoding-openapi.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/34771
---
|:--|:--|
| [aspnetcore/grpc/json-transcoding-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/f225d474e32bf37b2bdc622c2d29d3788f767438/aspnetcore/grpc/json-transcoding-openapi.md) | [aspnetcore/grpc/json-transcoding-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?branch=pr-en-us-34772) |
> Link to gRPC JSON transcoding getting started instructions

- aspnetcore/grpc/json-transcoding-openapi.md
This document was just updated today by JamesNK (See PR #34772) but I forgot to update the ms.date, so doing it now.  Very minor change, just the ms.date
---
|:--|:--|
| [aspnetcore/grpc/json-transcoding-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/62e409d479d327ad7abf387e333d26d142199709/aspnetcore/grpc/json-transcoding-openapi.md) | [aspnetcore/grpc/json-transcoding-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?branch=pr-en-us-34773) |
> ms.date update:  json-transcoding-openapi.md

- aspnetcore/fundamentals/servers/yarp/yarp-overview.md
Merges into #34764
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/yarp-overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/bebe9deb9063b410fa660ca9f12a6c9028d6249b/aspnetcore/fundamentals/servers/yarp/yarp-overview.md) | [aspnetcore/fundamentals/servers/yarp/yarp-overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/yarp-overview?branch=pr-en-us-34768) |
> Update YARP overview date- branch off of samsp

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Fixes #34775
Thanks @kemundos! 🚀 ... and sorry for the trouble. This wasn't a problem in 8.0 AFAIK. I'll discuss it with management and possibly the EF Core folks. For now, this will unblock everyone with the tutorial. I'll take it live after this builds.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/554c3c89d38b81b3fb818309be1594e7c44ae434/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-34780) |
> Update EF Core package install guidance

- aspnetcore/fundamentals/servers/yarp/extensibility.md
Fixes #34797
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/563ed8f259e06fcc1c884d3ae1e70f0ea8dd7b40/aspnetcore/fundamentals/servers/yarp/extensibility.md) | [aspnetcore/fundamentals/servers/yarp/extensibility](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/extensibility?branch=pr-en-us-34796) |
> Update image paths in YARP extensibility doc

- aspnetcore/blazor/forms/validation.md
Fixes #34785
Thanks @nicholasyin! 🎸 ... This is a nice improvement to the coverage. We have the basics of assigning an handler to the `OnValidationRequested` event right at the top of the article, but we really didn't show how to integrate it with DA as you asked about. I'm adding a section that refers back to the `Starship8` component example, showing how to add a few lines of code to it to demo the behaviors we discussed ...
* Manual validation in C# code with `OnValidationRequested`.
* Automatic validation with DA (the DA component and a validation attribute).
* The form processes all validation only when the user submits the form.
* The submit method doesn't execute at all unless form validation passes.
I also call out `EnableDataAnnotationsValidation` for enabling DA in code, and I …
> Improve custom form validation coverage

- aspnetcore/blazor/components/quickgrid.md
Addresses #34818
*NEW* doc author lesson learned 👉 *Don't create a PR while wearing weight lifting gloves!* 😆 
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/9ef574eb7b143af480045d71958c3cd4ed7f8998/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-34819) |
> Patch the QuickGrid row style example

- aspnetcore/security/authentication/2fa.md
- aspnetcore/security/cors/includes/cors56.md
Fixes #34851
Fixes #34850
Fixes #34849
---
|:--|:--|
| [aspnetcore/security/authentication/2fa.md](https://github.com/dotnet/AspNetCore.Docs/blob/93d4ac9b4ebeb606ada1c81ff5f18f3787dc0d46/aspnetcore/security/authentication/2fa.md) | [aspnetcore/security/authentication/2fa](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?branch=pr-en-us-34852) |
> Clean up link errors

- aspnetcore/security/authentication/social/microsoft-logins.md
Fixes #34863
---
|:--|:--|
| [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/a57b65b059525d255fd4f9c8fa469163b5914dde/aspnetcore/security/authentication/social/microsoft-logins.md) | [aspnetcore/security/authentication/social/microsoft-logins](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?branch=pr-en-us-34862) |
> Update tenant portion of Wades PR

- aspnetcore/security/authentication/social/microsoft-logins.md
- aspnetcore/security/authentication/social/social-code/6.x/ProgramMS.cs
Fixs #34466
Replaced portal specific instruction with links to latest and maintained instruction on Entra.
Note: The previously available Azure topics are now forwarding to similar topics on Entra.
---
|:--|:--|
| [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/a7d11f70248bb59b277dc17bfbbe04d8951b0beb/aspnetcore/security/authentication/social/microsoft-logins.md) | [aspnetcore/security/authentication/social/microsoft-logins](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?branch=pr-en-us-34669) |
> Microsoft Account external login: Move Portal steps to links

- aspnetcore/security/authentication/social/google-logins.md
Fixing some typos and adjusting for readability.
---
|:--|:--|
| [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/9bd575008d110d0022261ae4aaa8599870cd053d/aspnetcore/security/authentication/social/google-logins.md) | [aspnetcore/security/authentication/social/google-logins](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?branch=pr-en-us-34887) |
> Typos, readability

- aspnetcore/grpc/client.md
- aspnetcore/grpc/performance.md
Improve performance docs for gRPC with details about blocking.
---
|:--|:--|
| [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/6230f1f4468d045384fc3203cf98ada255aabc1c/aspnetcore/grpc/client.md) | [aspnetcore/grpc/client](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/client?branch=pr-en-us-34902) |
| [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/6230f1f4468d045384fc3203cf98ada255aabc1c/aspnetcore/grpc/performance.md) | [aspnetcore/grpc/performance](https://review.learn.microsoft.com/en-us/aspnet/core/grpc/performance?branch=pr-en-us-34902) |
> Add perf docs about making gRPC calls with async

- aspnetcore/fundamentals/servers/yarp/yarp-overview.md
TSL should presumably be TLS.
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/yarp-overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/6b80a304b05f370b1f995cfdc3772311fbcc30a7/aspnetcore/fundamentals/servers/yarp/yarp-overview.md) | [aspnetcore/fundamentals/servers/yarp/yarp-overview](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/yarp-overview?branch=pr-en-us-34909) |
> Update yarp-overview.md for tyops

- aspnetcore/performance/rate-limit-samples.md
- aspnetcore/performance/rate-limit.md
Use
The HUGE chunk change is just adding two spaces.
@samsp-msft we like to depersonalize docs in this repo and remove `you` and `your` unless it's needed to make the sentence more readable.
`@davidfowl`'s 3rd cousin, who is an consultant, reads our docs for his customers, and it's their app, not his.
---
|:--|:--|
| [aspnetcore/performance/rate-limit-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/67b78050c3bc117b41a39c4006589678d0f89d96/aspnetcore/performance/rate-limit-samples.md) | [aspnetcore/performance/rate-limit-samples](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit-samples?branch=pr-en-us-34926) |
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/67b78050c3bc117b41a39c4006589 …
> Rick's branch off Sams rate limit PR

- aspnetcore/host-and-deploy/iis/advanced.md
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/34922
See https://github.com/dotnet/AspNetCore.Docs/pull/34923/commits/29e0173cf3aa5fbc5bbaeeb71ccde77c2f091012 for my changes to the .NET 9 doc
I merged #34920 -- this PR shows my changes, add  (.NET 9 and earlier)
Please use the suggestion feature to any changes 
@clintwar please review
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/1fab6daab80464557f09e25d3c23d3f1d73d7773/aspnetcore/host-and-deploy/iis/advanced.md) | [aspnetcore/host-and-deploy/iis/advanced](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-34923) |
> Update buffer size

- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
> Fix a couple typos in openApi.md

- aspnetcore/data/scaffold_RP.md
- aspnetcore/toc.yml
Fixes #34195
---
|:--|:--|
| [aspnetcore/data/scaffold_RP.md](https://github.com/dotnet/AspNetCore.Docs/blob/327f90e8b9f15a437a4ff32383da1ca791bc2e43/aspnetcore/data/scaffold_RP.md) | [aspnetcore/data/scaffold_RP](https://review.learn.microsoft.com/en-us/aspnet/core/data/scaffold_RP?branch=pr-en-us-34971) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/327f90e8b9f15a437a4ff32383da1ca791bc2e43/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34971) |
> Ad scaffold tool to TOC

- aspnetcore/fundamentals/static-files.md
This is a quickie.
Closes #34916
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/7b78782cc4cf8c1c67b7bd742fb98541952a3279/aspnetcore/fundamentals/static-files.md) | [Static files in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-34967) |
> Clarify wording in static-files.md regarding asset optimization process

- aspnetcore/performance/rate-limit-samples.md
- aspnetcore/performance/rate-limit.md
Added a bunch of ai-assisted content
Moved the samples out to a separate doc to reduce the code spam
Todo:
- TOC changes to create sub nodes and include the samples topic as a new child
- Add a contents section to this topic as its still really long?
---
|:--|:--|
| [aspnetcore/performance/rate-limit-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/1bf8c7cb5a72bcba108577568b314f990c13306c/aspnetcore/performance/rate-limit-samples.md) | [aspnetcore/performance/rate-limit-samples](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit-samples?branch=pr-en-us-34925) |
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/1bf8c7cb5a72bcba108577568b314f990c13306c/aspnetcore/performance/rate-limit.md) | …
> Adding more context to the rate limiting topic

- aspnetcore/release-notes/aspnetcore-10/includes/OpenApiPopulateXMLDocComments.md
Prep only.  Moved text from issue conversation to an include.
After merging, changes to that include will be made in a new PR so it is clear what is changed during any editing.
> Prep: WN .NET 10: OpenAPI: XML doc comments

- aspnetcore/release-notes/aspnetcore-10.0.md
cc: @Rick-Anderson @wadepickett  ... Updating the date to suck my Blazor INCLUDE file updates (and anything else) into it.
I'll wait to confirm that any commented out stuff has been addressed in any of your INCLUDE files.
If so, then just close and re-open this to rebuild.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/877e86c4521b30c7c8c10b5bbb056817c34ee22a/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-34999) |
> Update release notes article date

- aspnetcore/release-notes/aspnetcore-10.0.md
fixes #35001
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/53d0000448954a9c668a845aea8c630446608cdf/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35003) |
> Add AuthN/AuthZ metrics

- aspnetcore/blazor/components/component-disposal.md
---
|:--|:--|
| [aspnetcore/blazor/components/component-disposal.md](https://github.com/dotnet/AspNetCore.Docs/blob/b969de546b1eb7d405667ba8f59acd846f163514/aspnetcore/blazor/components/component-disposal.md) | [aspnetcore/blazor/components/component-disposal](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/component-disposal?branch=pr-en-us-35007) |
> [Blazor] component-disposal.md - typos

- aspnetcore/blazor/tutorials/movie-database-app/part-4.md
Fixes #35013
Thanks @sandrowy! 🚀 ... I'm changing the sentence to force a new Chinese translation.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-4.md](https://github.com/dotnet/AspNetCore.Docs/blob/f2d66db3fe49a118ca687e583beea40e7684582e/aspnetcore/blazor/tutorials/movie-database-app/part-4.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-4](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-4?branch=pr-en-us-35015) |
> Update sentence to trigger re-loc

- aspnetcore/blazor/fundamentals/signalr.md
- aspnetcore/blazor/fundamentals/startup.md
- aspnetcore/blazor/fundamentals/static-files.md
- aspnetcore/blazor/hybrid/security/security-considerations.md
- aspnetcore/blazor/security/content-security-policy.md
- aspnetcore/blazor/security/interactive-server-side-rendering.md
- aspnetcore/fundamentals/map-static-files.md
- aspnetcore/release-notes/aspnetcore-9/includes/blazor.md
Fixes #34098
Rick ...
* I'm fixing up some external CSP cross-links along the way here.
* I left a little CSP-related content here (commented-out) that I'm going to pick up with on my next PR, which will flesh out some nonce and subresource integrity approaches for the inline script tag generated by the `ImportMap` component in Blazor apps.
* The main thing here is to move general Map Static Assets coverage out of the Blazor *Static Files* article and into the new *Map Static Assets* article. You'll see a couple of big blocks of text being moved over and some light touches here and there in the new article.
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/68845aadaa639aaa9246fd07b5c34bc10d0d50a1/aspnetcor …
> Move Map Static Assets content

- aspnetcore/fundamentals/servers/yarp/kubernetes-ingress.md
- aspnetcore/toc.yml
Fixes #34994
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/kubernetes-ingress.md](https://github.com/dotnet/AspNetCore.Docs/blob/efd90424a5fc1d19dc8e9440651d19a5ec02ecc0/aspnetcore/fundamentals/servers/yarp/kubernetes-ingress.md) | [aspnetcore/fundamentals/servers/yarp/kubernetes-ingress](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/kubernetes-ingress?branch=pr-en-us-34996) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/efd90424a5fc1d19dc8e9440651d19a5ec02ecc0/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-34996) |
> add kubernetes-ingress.md to TOC

- aspnetcore/razor-pages/ui-class.md
- aspnetcore/razor-pages/ui-class/remove.xml
---
|:--|:--|
| [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/bd415d9c710c3977cf20560192f84add7b6030fe/aspnetcore/razor-pages/ui-class.md) | [Create reusable UI using the Razor class library project in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?branch=pr-en-us-35028) |
> Fix invalid XML in an example

- aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md
Fixed an xref link that was requested in the last review but missed. <xref:System.Text.StringBuilder>
---
|:--|:--|
| [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md](https://github.com/dotnet/AspNetCore.Docs/blob/404f0779bfd51a2663ae7aefb28a43fb3747d400/aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md) | [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/ai-powered-group-chat/ai-powered-group-chat?branch=pr-en-us-35029) |
> Minor, xref link fix.

- aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md
Reverts dotnet/AspNetCore.Docs#35029
---
|:--|:--|
| [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md](https://github.com/dotnet/AspNetCore.Docs/blob/f1a4cd077885c5a852340f0e4c3220ea3174df1e/aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md) | [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/ai-powered-group-chat/ai-powered-group-chat?branch=pr-en-us-35038) |
> Revert "Minor, xref link fix."

- aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md
Addresses #35029
cc: @wadepickett ... It worked 🎉, and I'm making that XREF change here.
---
|:--|:--|
| [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md](https://github.com/dotnet/AspNetCore.Docs/blob/dbf82101138780271918a64aa1ab9e6d2608a6e9/aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat.md) | [aspnetcore/tutorials/ai-powered-group-chat/ai-powered-group-chat](https://review.learn.microsoft.com/en-us/aspnet/core/tutorials/ai-powered-group-chat/ai-powered-group-chat?branch=pr-en-us-35039) |
> Minor, xref link fix

- aspnetcore/blazor/images-and-documents.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/content-security-policy.md
- aspnetcore/blazor/tutorials/movie-database-app/part-7.md
Minor article updates from a review of recently published articles.
---
|:--|:--|
| [aspnetcore/blazor/images-and-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/deb51fe9d862d84ca6a0cbd11a598dcd00493b46/aspnetcore/blazor/images-and-documents.md) | [aspnetcore/blazor/images-and-documents](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/images-and-documents?branch=pr-en-us-35043) |
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/deb51fe9d862d84ca6a0cbd11a598dcd00493b46/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?branch= …
> Minor article updates

- .github/workflows/blazor-hybrid-issue-processing.yml
- .github/workflows/blazor-issue-processing.yml
Updating the issue messages for Blazor issues.
---
|:--|:--|
| [.github/workflows/blazor-hybrid-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/9610f1ed1e9c32a90f767415204b044ea95a37a4/.github/workflows/blazor-hybrid-issue-processing.yml) | [.github/workflows/blazor-hybrid-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-hybrid-issue-processing?branch=pr-en-us-35053) |
| [.github/workflows/blazor-issue-processing.yml](https://github.com/dotnet/AspNetCore.Docs/blob/9610f1ed1e9c32a90f767415204b044ea95a37a4/.github/workflows/blazor-issue-processing.yml) | [.github/workflows/blazor-issue-processing](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/blazor-issue-processing?branch …
> Update Blazor issue messages

- aspnetcore/blazor/host-and-deploy/webassembly.md
Fixes #35051
Thanks @dimodi! 🚀 ... I'll leave this up for a bit to give you a chance to look and comment before I merge it.
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/cd76b878d0dce031489605641c9e3bbac678ceb2/aspnetcore/blazor/host-and-deploy/webassembly.md) | [aspnetcore/blazor/host-and-deploy/webassembly](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?branch=pr-en-us-35052) |
> Add `limit_req_zone` to Nginx hosting config

- aspnetcore/diagnostics/asp0027.md
- aspnetcore/toc.yml
Added documentation for ASP0027
Fixes #35037
---
|:--|:--|
| [aspnetcore/diagnostics/asp0027.md](https://github.com/dotnet/AspNetCore.Docs/blob/152f8b01a283bc307e27e6fd14e9f1aececa56d2/aspnetcore/diagnostics/asp0027.md) | [aspnetcore/diagnostics/asp0027](https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0027?branch=pr-en-us-35061) |
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/152f8b01a283bc307e27e6fd14e9f1aececa56d2/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-35061) |
> Added ASP0027 documentation

- aspnetcore/blazor/security/additional-scenarios.md
Addresses #31691
---
|:--|:--|
| [aspnetcore/blazor/security/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/b8fa431fbb4a74cb45ef2fcfcc6ab39946d45f73/aspnetcore/blazor/security/additional-scenarios.md) | [aspnetcore/blazor/security/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/additional-scenarios?branch=pr-en-us-35067) |
> Update the passing tokens guidance

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35072
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/8fb818b12682e027888c9a5d1168e1cfed1be888/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35073) |
> Add PAR support configuration

- quest-config.json
> remove Di parents, add Br parents

- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg003.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg004.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg005.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg006.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg007.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg008.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg009.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg011.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg012.md
- aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg013.md
Similar to PR #35062 but for the RDG files.
More neatly formatting the tables we have in these files to make them more readable at first look of the file.
---
|:--|:--|
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md](https://github.com/dotnet/AspNetCore.Docs/blob/160ccbf7437276bac2aa1e37e6c4f3186d061c14/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg001.md) | [RDG001: Unable to resolve route pattern](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg001?branch=pr-en-us-35086) |
| [aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg002.md](https://github.co …
> Updated md table formatting of rdg files

- aspnetcore/performance/rate-limit.md
Fixes #35084
@jeffpapp please review
---
|:--|:--|
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/b649c9658d5826213b4d36dc5b460476cc581af0/aspnetcore/performance/rate-limit.md) | [aspnetcore/performance/rate-limit](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?branch=pr-en-us-35092) |
> Remove nuGet from Rate limiter

- aspnetcore/signalr/supported-platforms.md
Fixes #35112 
- Update the link to the Swift Client topic.
- Remove link to 3rd party Swift client
---
|:--|:--|
| [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/fc296d767f8fcce97ca65a235c768d959fa5389f/aspnetcore/signalr/supported-platforms.md) | [aspnetcore/signalr/supported-platforms](https://review.learn.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?branch=pr-en-us-35113) |
> Update Swift Client links

- aspnetcore/host-and-deploy/iis/advanced.md
Fixes #34937
---
|:--|:--|
| [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/0b15a4ecb28464fc9319709f6616e510ada8029a/aspnetcore/host-and-deploy/iis/advanced.md) | [aspnetcore/host-and-deploy/iis/advanced](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?branch=pr-en-us-35103) |
> Default stack size

- aspnetcore/fundamentals/servers/yarp/config-providers.md
- aspnetcore/fundamentals/servers/yarp/dests-health-checks.md
- aspnetcore/fundamentals/servers/yarp/diagnosing-yarp-issues.md
- aspnetcore/fundamentals/servers/yarp/grpc.md
- aspnetcore/fundamentals/servers/yarp/http-client-config.md
- aspnetcore/fundamentals/servers/yarp/load-balancing.md
- aspnetcore/fundamentals/servers/yarp/middleware.md
- aspnetcore/fundamentals/servers/yarp/session-affinity.md
- aspnetcore/fundamentals/servers/yarp/transforms-response.md
- aspnetcore/fundamentals/servers/yarp/transforms.md
- aspnetcore/fundamentals/servers/yarp/yarp-overview.md
As per this https://github.com/dotnet/AspNetCore.Docs/pull/35095#issuecomment-2766124854.
A quick first pass at the first point of incorrect spacing, picked up some other little bits along the way like capitalizations and formatting
Fixes #35120
---
|:--|:--|
| [aspnetcore/fundamentals/servers/yarp/config-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/b7aa4f58669bc7537967c9bd8cb6c00de88c8c69/aspnetcore/fundamentals/servers/yarp/config-providers.md) | [aspnetcore/fundamentals/servers/yarp/config-providers](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/yarp/config-providers?branch=pr-en-us-35119) |
| …
> Quick pass at some YARP improvements

- .github/workflows/quest.yml
Removed a typo letter "s" at the end of a line.
---
|:--|:--|
| [.github/workflows/quest.yml](https://github.com/dotnet/AspNetCore.Docs/blob/bb02a1d6216346a508f2102d323c19275f2bafb6/.github/workflows/quest.yml) | [.github/workflows/quest](https://review.learn.microsoft.com/en-us/aspnet/core/.github/workflows/quest?branch=pr-en-us-35122) |
> Update quest.yml - fix typo

- aspnetcore/blazor/tutorials/movie-database-app/part-3.md
Fixes #35140
Thanks @aarondev42! 🚀 ... I'll merge this into the live article as soon as this PR merges to the `main` branch.
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-3.md](https://github.com/dotnet/AspNetCore.Docs/blob/b1a73b41d7b5b9f43ee44d8e32de60024ff172c3/aspnetcore/blazor/tutorials/movie-database-app/part-3.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-3](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-3?branch=pr-en-us-35141) |
> Update path to the `Routes` component

- aspnetcore/fundamentals/http-logging/index.md
- aspnetcore/fundamentals/http-logging/samples/8.x/HttpLoggingSample.csproj
- aspnetcore/fundamentals/http-logging/samples/8.x/MyTaxonomyClassifications.cs
- aspnetcore/fundamentals/http-logging/samples/8.x/Program.cs
Fixes #35181
Moved from #35178
**[Redacting sensitive data](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-10.0&branch=pr-en-us-35182#redacting-sensitive-data)**
---
|:--|:--|
| [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/cb3bfeb74f540d4d76a4ebea64065f3cb46bf0ac/aspnetcore/fundamentals/http-logging/index.md) | [aspnetcore/fundamentals/http-logging/index](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/index?branch=pr-en-us-35182) |
> R a/mariam/redaction

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/fundamentals/routing.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Addresses #34948
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/292b559a64edd6ec86732abfb2270931fa52ebb5/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35200) |
| [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/292b559a64edd6ec86732abfb2270931fa52ebb5/aspnetcore/blazor/fundamentals/routing.md) | [aspnetcore/blazor/fundamentals/routing](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?branch=pr-en-us-35200) |
> Blazor Pre3 final updates for release

- aspnetcore/release-notes/aspnetcore-10.0.md
Just changed the ms.date since the topic is ready publish with the Preview 3 Update.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/4402a50a0ed826a3fb9c7b50895fe58f0209482d/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35202) |
> Publish WN 10 Prev 3: Update aspnetcore-10.0.md

- aspnetcore/blazor/components/integration.md
- aspnetcore/blazor/components/lifecycle.md
- aspnetcore/blazor/components/prerender.md
Addresses #35071
---
|:--|:--|
| [aspnetcore/blazor/components/integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/7df5af98d1a2564aa1e3237b01a37ceca8bc8e16/aspnetcore/blazor/components/integration.md) | [aspnetcore/blazor/components/integration](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?branch=pr-en-us-35210) |
| [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/7df5af98d1a2564aa1e3237b01a37ceca8bc8e16/aspnetcore/blazor/components/lifecycle.md) | [aspnetcore/blazor/components/lifecycle](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?branch=pr-en-us-35210) |
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCor …
> Declarative persistent component state updates

- aspnetcore/fundamentals/openapi/using-openapi-documents.md
Fixes #35100
Fixes #34817
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/using-openapi-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8a04be0c5e99ebb09e6cb2138a1ef1ec8d010bd/aspnetcore/fundamentals/openapi/using-openapi-documents.md) | [aspnetcore/fundamentals/openapi/using-openapi-documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?branch=pr-en-us-35101) |
> Suggest not using UI in production for OpenAPI

- aspnetcore/fundamentals/openapi/aspnetcore-openapi.md
- aspnetcore/fundamentals/openapi/includes/aspnetcore-openapi9.md
Moniker prep
contributes to #34754
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/aspnetcore-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/2d9376c08e4309193de343b6351bf54f944fe342/aspnetcore/fundamentals/openapi/aspnetcore-openapi.md) | [aspnetcore/fundamentals/openapi/aspnetcore-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?branch=pr-en-us-35241) |
> OpenApi 3.1 /1

- aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
Fixes #35258
This adds the new article cross-link for 9.0 or later.
I'll preserve the auth0 cross-link, but the first mention should be to our Microsoft content.
---
|:--|:--|
| [aspnetcore/security/authentication/configure-jwt-bearer-authentication.md](https://github.com/dotnet/AspNetCore.Docs/blob/1dd79b0e1a4e85d48724dce5f4f0d5e66b453d58/aspnetcore/security/authentication/configure-jwt-bearer-authentication.md) | [aspnetcore/security/authentication/configure-jwt-bearer-authentication](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-jwt-bearer-authentication?branch=pr-en-us-35259) |
> Update YARP section

- aspnetcore/fundamentals/configuration/options.md
- aspnetcore/fundamentals/configuration/options/samples/6.x/OptionsSample/Models/PositionOptionsWithConfigurationKeyName.cs
- aspnetcore/fundamentals/configuration/options/samples/6.x/OptionsSample/appsettings.KN.json
Fixes #34767
---
|:--|:--|
| [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/d5b4716fc74e7f8ea7ad2623fcb00e122b7e7289/aspnetcore/fundamentals/configuration/options.md) | [aspnetcore/fundamentals/configuration/options](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?branch=pr-en-us-35274) |
> document ConfigurationKeyName

- aspnetcore/host-and-deploy/docker/building-net-docker-images.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images10.md
Prep only for updating to .NET 10:
Created a new include file for version 10 so the following PR will clearly show any changes.
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/b6536c2530d497d2d104d921fc6c82fd1e13021a/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [aspnetcore/host-and-deploy/docker/building-net-docker-images](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-35281) |
> Prep only: .NET 10 udpate: Run in Docker Container

- aspnetcore/host-and-deploy/docker/building-net-docker-images.md
- aspnetcore/host-and-deploy/docker/includes/building-net-docker-images10.md
Fixes #35065
Updated for .NET 10
Include for v 10 was added in previous prep only PR #35281.
---
|:--|:--|
| [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/740880f79ee879be4cdeb861b944917c3603f833/aspnetcore/host-and-deploy/docker/building-net-docker-images.md) | [aspnetcore/host-and-deploy/docker/building-net-docker-images](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?branch=pr-en-us-35285) |
> Run Docker: Update .NET 10

- aspnetcore/log-mon/metrics/built-in/includes/built-in10.md
- aspnetcore/log-mon/metrics/built-in/includes/built-in8.md
Fixes #35295
Thanks for the report, @timdeschryver! 🎸 ... Their site has been hacked and is hosting a bunch of evil stuff! 👿 I found a good replacement set of links at https://www.geeksforgeeks.org.
> Change OSI links

- aspnetcore/fundamentals/openapi/include-metadata.md
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/Controllers/TestController.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/DayOfWeek.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/Program.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/WebJson.csproj
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/WebJson.http
- aspnetcore/fundamentals/openapi/samples/10.x/WebJson/v1.json
Fixes #34316
[Internal review URL](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?view=aspnetcore-10.0&branch=pr-en-us-35280&tabs=minimal-apis#set-json-serialization-options-globally)
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/3282837a136e55eb5068a8afb2c15fe7cdb34122/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35280) |
> config JsonOptions globally /3

- aspnetcore/fundamentals/logging/index/samples/6.x/TodoApiDTO/Pages/About.cshtml
Fixes #35311
Thanks @mthanson8333! 🚀
> Remove message display from UI

- aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md
Fixes #35310
Thanks @maraf! 🎷... I also updated the sample app on https://github.com/dotnet/blazor-samples/pull/522.
cc: @BethMassi 
---
|:--|:--|
| [aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/494bacfa6d695a98d681a371337f0a4201109060/aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md) | [aspnetcore/blazor/hybrid/security/maui-blazor-web-identity](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/maui-blazor-web-identity?branch=pr-en-us-35314) |
> Update service registration

- aspnetcore/security/docker-compose-https.md
@mvelosop please review. I need to guarantee the PW is invalid and can't be used.
---
|:--|:--|
| [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/75491493588ca86d5f6221bb8ce9fb9afda60edb/aspnetcore/security/docker-compose-https.md) | [aspnetcore/security/docker-compose-https](https://review.learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?branch=pr-en-us-35308) |
> SFI docker-compose-https.md

- aspnetcore/fundamentals/openapi/include-metadata.md
- aspnetcore/release-notes/aspnetcore-10/includes/openApi.md
Closes #35292 
This PR also includes:
- Other snippets are also made tablet friendly (iPad pro)
- Fixed typos (thanks Copilot)
- Removed an empty highlighted line that shouldn't be highlighted
- There's also a sample that's updated at https://github.com/dotnet/AspNetCore.Docs.Samples/pull/278
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e3dc2f028ed5a9203c41fd94e1cb3729405b532/aspnetcore/fundamentals/openapi/include-metadata.md) | [Include OpenAPI metadata in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35321) |
> make snippet tablet-friendly

- aspnetcore/test/troubleshoot/code/5.x/Program.cs
- aspnetcore/test/troubleshoot/includes/troubleshoot5.md
Contributes to #32926
---
|:--|:--|
| [aspnetcore/test/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/a12f934b6b5ab3363863426fe3e04a29ff7a3ba2/aspnetcore/test/troubleshoot.md) | [aspnetcore/test/troubleshoot](https://review.learn.microsoft.com/en-us/aspnet/core/test/troubleshoot?branch=pr-en-us-35337) |
> mon prep debug remove startup /2

- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/index.md
Fixes #35358
Companion samples PR to set `SerializeAllClaims` to `true` :point_right: https://github.com/dotnet/blazor-samples/pull/531
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-entra.md](https://github.com/dotnet/AspNetCore.Docs/blob/374843dc44645b7cca240dbdb8efc608bf740384/aspnetcore/blazor/security/blazor-web-app-with-entra.md) | [aspnetcore/blazor/security/blazor-web-app-with-entra](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?branch=pr-en-us-35362) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/374843dc44645b7cca240dbdb8efc608bf740384/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | …
> Auth state serialization/deserialization updates

- aspnetcore/blazor/call-web-api.md
Fixes #35318
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/ea8708450c5c4f5443b1baf2554a7bf0daf26c2a/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35363) |
> MS Identity Web Downstream API coverage

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35322
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8c5caadf3241e6b26b43fcf4a4361de45d37b54/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35378) |
> Section on app settings configuration

- aspnetcore/fundamentals/websockets/includes/websockets8.md
Related to #35374
Prep only.  Needed to move version 8 of the topic to an include file per our versioning setup.  Then I will create a new PR based on that for some updates for version 9 so a diff can be seen in review for changes.
---
|:--|:--|
| [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/e7281d270724bae05cc21041e0b0bb39292dbb95/aspnetcore/fundamentals/websockets.md) | [aspnetcore/fundamentals/websockets](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?branch=pr-en-us-35383) |
> Prep only: Websockets: Move verson 8 to include file

- aspnetcore/performance/caching/hybrid.md
Additional notes from security usage review; no public issue number
---
|:--|:--|
| [aspnetcore/performance/caching/hybrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/bed7598c734487a1c1711dc5c4e9fa90d1667128/aspnetcore/performance/caching/hybrid.md) | [HybridCache library in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?branch=pr-en-us-35379) |
> HybridCache - Additional notes on key and tag usage

- aspnetcore/fundamentals/openapi/using-openapi-documents.md
Fixes #35384
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/using-openapi-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/e8f9554453c5cc5b4f319ff17b30d8c77a5e2651/aspnetcore/fundamentals/openapi/using-openapi-documents.md) | [aspnetcore/fundamentals/openapi/using-openapi-documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?branch=pr-en-us-35386) |
> Guidance on launching the tools

- aspnetcore/performance/rate-limit-samples.md
Fixes typo in RateLimiter docs
---
|:--|:--|
| [aspnetcore/performance/rate-limit-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/58f76eeabdb7603156150b665be3b8a47ae00133/aspnetcore/performance/rate-limit-samples.md) | [Rate limiter samples](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit-samples?branch=pr-en-us-35414) |
> Fixes typo

- aspnetcore/blazor/components/prerender.md
- aspnetcore/blazor/components/render-modes.md
Fixes #35382
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef1407c42bddeb1cb0372b7250ec6d2d85ce8f5b/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-35430) |
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/ef1407c42bddeb1cb0372b7250ec6d2d85ce8f5b/aspnetcore/blazor/components/render-modes.md) | [aspnetcore/blazor/components/render-modes](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?branch=pr-en-us-35430) |
> Update prerendering cross-links

- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
> [Pre4] `NavigateTo` no longer throws navigation exception

- aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/35434#issuecomment-2872901402
---
|:--|:--|
| [aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/91461920b498926b6f0d64634469013210a6a7ba/aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md) | [aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/webassembly-browser-developer-tools-diagnostics?branch=pr-en-us-35437) |
> Improve callspec coverage

- aspnetcore/release-notes/aspnetcore-10/includes/MinimalAPIValidationRecordTypes.md
Contributes to #35397 
PREP ONLY:
Moved comments for this feature in WN tracking issue to an include so edits in the next PR will show a diff and be easier to review.
> Prep Only: v10p4: Min API Validation: Record types

- aspnetcore/release-notes/aspnetcore-10/includes/jsonPatch.md
> Update jsonPatch.md ExpandoObject

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/xml-comment-generator.md
[Improvements to the XML comment generator](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-9.0&branch=pr-en-us-35420#improvements-to-the-xml-comment-generator)
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/35412
Edit pass on original WN comments for .NET 10 Prev 4
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/92b6601851c064a042a8258357263844d0da71b9/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core 10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35420) |
> WN10.P4 edit pass for XML comment gen improvements

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/doc-provider-in-di.md
Fixes #35407 
Edit pass/rewrite of the [comment in the What's New 10 Preview 4 issue](https://github.com/dotnet/AspNetCore.Docs/issues/35217#issuecomment-2853119436)
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/ff2f8a5f1e5158945d9145cf5625ba05e1fcd071/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35428) |
> WN10.P4 Support IOpenApiDocumentProvider in DI container

- aspnetcore/blazor/performance/webassembly-event-pipe-diagnostics.md
---
|:--|:--|
| [aspnetcore/blazor/performance/webassembly-event-pipe-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/b94174117590a427c1b760eaaecead5a9b60942c/aspnetcore/blazor/performance/webassembly-event-pipe-diagnostics.md) | [aspnetcore/blazor/performance/webassembly-event-pipe-diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/webassembly-event-pipe-diagnostics?branch=pr-en-us-35434) |
> Improve docs for WasmPerfInstrumentation

- aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md
Fixes #35450
---
|:--|:--|
| [aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/99083c0ae3d22269832ca1c64efadac76d14b2f3/aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md) | [aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/webassembly-browser-developer-tools-diagnostics?branch=pr-en-us-35451) |
> Remove section and apply further updates

- aspnetcore/release-notes/aspnetcore-10.0.md
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/20a08a75f4db1885deff62ed7865cd7db6603bab/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35459) |
> Grab What's New latest content

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Addresses #35452
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/1a05f615e32af582733064a81a550f9939715eb7/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35460) |
> Update sync variants

- aspnetcore/blazor/tutorials/movie-database-app/part-2.md
Addresses #35232
---
|:--|:--|
| [aspnetcore/blazor/tutorials/movie-database-app/part-2.md](https://github.com/dotnet/AspNetCore.Docs/blob/f420f9821d47bb76988373c9bee6eb8550d7225f/aspnetcore/blazor/tutorials/movie-database-app/part-2.md) | [aspnetcore/blazor/tutorials/movie-database-app/part-2](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?branch=pr-en-us-35462) |
> Update EF Core tooling breaking change remarks

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/MinimalAPIValidationRecordTypes.md
Fixes #35397
Move content from WN comments to an include, edited, and provided a code example.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/33cdbdf2fab7ec8319a080d46f9e509ffdb438aa/aspnetcore/release-notes/aspnetcore-10.0.md) | [aspnetcore/release-notes/aspnetcore-10.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35448) |
> WN v10prev4: Min API Validation supports record types

- aspnetcore/fundamentals/openapi/customize-openapi.md
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/Controllers/WeatherForecastController.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/Program.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/TransformerJsonNode.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/WeatherForecast.cs
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/WebAppOpenAPI10.csproj
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/WebAppOpenAPI10.http
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/appsettings.Development.json
- aspnetcore/fundamentals/openapi/samples/10.x/WebAppOpenAPI10/appsettings.json
Fixes #35394
- Added new section:
- Support for generating OpenApiSchemas in transformers
- Added app sample for .NET 10 prev 4
- Cleaned up with some edits throughout the doc original to get the Acrolynx score up to well above passing.
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/customize-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/dab19256adf45fab1d0498bc847a997eb4818cf4/aspnetcore/fundamentals/openapi/customize-openapi.md) | [aspnetcore/fundamentals/openapi/customize-openapi](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/customize-openapi?branch=pr-en-us-35478) |
> Customize OpenAPI: OpenAPISchemas in transformers

- aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md
Fixes #35486
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/72d7dd1b6ed68f16bb7ba8e97d38b6f7e8f2b827/aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md) | [aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly/azure-static-web-apps?branch=pr-en-us-35487) |
> Update scenario cross-links

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
Fixes #35483
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/321690666afdc00c0f47681bb2337ab766f9aaf5/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35488) |
> Remark on BWA auth article+sample improvements

- aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md
Improved example to show separator
@guardrex 
---
|:--|:--|
| [aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/4e0af87878c0c48f226755456e7e3eba7a0d6ac8/aspnetcore/blazor/performance/webassembly-browser-developer-tools-diagnostics.md) | [ASP.NET Core Blazor WebAssembly browser developer tools diagnostics](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/performance/webassembly-browser-developer-tools-diagnostics?branch=pr-en-us-35496) |
> WasmProfilers example

- aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md
Fixes #35499
---
|:--|:--|
| [aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md](https://github.com/dotnet/AspNetCore.Docs/blob/0198c33e4fd70f535cf7dd4d68747e4438e2a4db/aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps.md) | [aspnetcore/blazor/host-and-deploy/webassembly/azure-static-web-apps](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly/azure-static-web-apps?branch=pr-en-us-35503) |
> Add fallback app config

- aspnetcore/host-and-deploy/health-checks.md
Fixes #31330
Thanks @KalleOlaviNiemitalo! Sorry for the delay.
---
|:--|:--|
| [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/6be7ea783101b0b6db48ab5452a40d25affbe06f/aspnetcore/host-and-deploy/health-checks.md) | [aspnetcore/host-and-deploy/health-checks](https://review.learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?branch=pr-en-us-35518) |
> Update Docker command

- aspnetcore/blazor/fundamentals/startup.md
Fixes #35515
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/7e47327d20a8787d7d08171d37f127da4bef983e/aspnetcore/blazor/fundamentals/startup.md) | [aspnetcore/blazor/fundamentals/startup](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?branch=pr-en-us-35532) |
> Return content loading global WASM example

- aspnetcore/fundamentals/middleware/index.md
- aspnetcore/fundamentals/middleware/index/includes/index3-7.md
Fixes #33303 
---
|:--|:--|
| [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/e3bddae1efbb5c38aa1719c4a4e6fff633ccbba5/aspnetcore/fundamentals/middleware/index.md) | [ASP.NET Core Middleware](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?branch=pr-en-us-35520) |
> Add antiforgery to middleware table

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/additional-scenarios.md
- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35552
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/6c73925bd667e0dbbdca59863d22de6964d0500d/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35554) |
| [aspnetcore/blazor/security/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/6c73925bd667e0dbbdca59863d22de6964d0500d/aspnetcore/blazor/security/additional-scenarios.md) | [aspnetcore/blazor/security/additional-scenarios](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/additional-scenarios?branch=pr-en-us-35554) |
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspN …
> Update example for NRTs + cross-linking

- aspnetcore/blazor/fundamentals/dependency-injection.md
Fixes #35553
---
|:--|:--|
| [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/b9b97da4070ca57e78157e38b1e42e690a18e506/aspnetcore/blazor/fundamentals/dependency-injection.md) | [aspnetcore/blazor/fundamentals/dependency-injection](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?branch=pr-en-us-35555) |
> Add extension call to example

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
- aspnetcore/blazor/security/index.md
Addresses #31691
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3df165b7a3c514cb0bd429bcd2b0200500b4868/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35557) |
| [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/d3df165b7a3c514cb0bd429bcd2b0200500b4868/aspnetcore/blazor/security/index.md) | [aspnetcore/blazor/security/index](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/index?branch=pr-en-us-35557) |
> Patch using statement use

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/components/quickgrid.md
- aspnetcore/blazor/file-uploads.md
- aspnetcore/blazor/forms/validation.md
- aspnetcore/blazor/hybrid/security/maui-blazor-web-identity.md
- aspnetcore/blazor/security/webassembly/index.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/account-confirmation-and-password-recovery.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/index.md
- aspnetcore/blazor/security/webassembly/standalone-with-identity/qrcodes-for-authenticator-apps.md
Fixes #35565
Sample work was performed on https://github.com/dotnet/blazor-samples/pull/548.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e567d2b1f1da12edc852a56e2bf331ab6fcb4ba/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35566) |
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e567d2b1f1da12edc852a56e2bf331ab6fcb4ba/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-35566) |
| …
> Apply `using` statements and disposal section

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35608
Thanks @mr5z! 🚀 ... I checked the whole repo, and these were the only spots the sneaky 😈 got by me. I'll merge this into the live doc in a few minutes. Thanks again for the report!
I also updated the sample apps in the samples repo for this article.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/57e3f44c2debc1d730cbb22f160041c2c42e2120/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35609) |
> Fix token handler example

- aspnetcore/fundamentals/openapi/include-metadata.md
- aspnetcore/fundamentals/openapi/includes/include-metadata9.md
Fixes #34641
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/dfc14e762ac9aba1ed540bfaac38c3a691a5d216/aspnetcore/fundamentals/openapi/include-metadata.md) | [aspnetcore/fundamentals/openapi/include-metadata](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?branch=pr-en-us-35619) |
> Surface controller attribute requirement

- aspnetcore/security/authentication/social/google-logins.md
- aspnetcore/security/authentication/social/social-code/6.x/ProgramGoogle.cs
Fixes #34532
---
|:--|:--|
| [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/05178a7945b59352fc3efa7e01fe760eefd6c433/aspnetcore/security/authentication/social/google-logins.md) | [aspnetcore/security/authentication/social/google-logins](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?branch=pr-en-us-35545) |
> update google logins

- aspnetcore/toc.yml
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/33981
---
|:--|:--|
| [aspnetcore/toc.yml](https://github.com/dotnet/AspNetCore.Docs/blob/feb0acafa977490623ca42e67c2a76569d221a85/aspnetcore/toc.yml) | [aspnetcore/toc](https://review.learn.microsoft.com/en-us/aspnet/core/toc?branch=pr-en-us-35645) |
> Move Best Practices to a better place in the TOC

- aspnetcore/security/authentication/ws-federation.md
Fixes #35656
---
|:--|:--|
| [aspnetcore/security/authentication/ws-federation.md](https://github.com/dotnet/AspNetCore.Docs/blob/a785c825ae0a187e2704979dda35d62337814b61/aspnetcore/security/authentication/ws-federation.md) | [aspnetcore/security/authentication/ws-federation](https://review.learn.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?branch=pr-en-us-35657) |
> Update WS-Fed article versioning

- aspnetcore/blazor/components/js-spa-frameworks.md
Fixes #35653
---
|:--|:--|
| [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a3d50655c906a51aac548a20afde5b9a97c13a7/aspnetcore/blazor/components/js-spa-frameworks.md) | [aspnetcore/blazor/components/js-spa-frameworks](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?branch=pr-en-us-35659) |
> Update BWA feature tracking notes

- aspnetcore/blazor/call-web-api.md
- aspnetcore/blazor/security/account-confirmation-and-password-recovery.md
- aspnetcore/blazor/security/blazor-web-app-with-entra.md
- aspnetcore/security/data-protection/configuration/overview.md
- aspnetcore/security/data-protection/implementation/key-storage-providers.md
Fixes #35665
Includes updates for local dev/testing with VS-supplied credentials for the encrypted, distributed token cache coverage.
---
|:--|:--|
| [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/07d21236c8b1fdd78d68155d25276e4281f313cc/aspnetcore/blazor/call-web-api.md) | [aspnetcore/blazor/call-web-api](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?branch=pr-en-us-35670) |
| [aspnetcore/blazor/security/account-confirmation-and-password-recovery.md](https://github.com/dotnet/AspNetCore.Docs/blob/07d21236c8b1fdd78d68155d25276e4281f313cc/aspnetcore/blazor/security/account-confirmation-and-password-recovery.md) | [aspnetcore/blazor/security/account-confirmation-and-password-recovery](https://review.le …
> AKV client secret using a Managed Identity

- aspnetcore/release-notes/aspnetcore-10/includes/blazor.md
> Add additional version segments

- aspnetcore/blazor/components/quickgrid.md
Addresses #34881
Based on https://github.com/dotnet/aspnetcore/issues/58716#issuecomment-3057562654.
---
|:--|:--|
| [aspnetcore/blazor/components/quickgrid.md](https://github.com/dotnet/AspNetCore.Docs/blob/50fa250da515b5b866dfc43b15d06eb4f2de25a1/aspnetcore/blazor/components/quickgrid.md) | [aspnetcore/blazor/components/quickgrid](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?branch=pr-en-us-35736) |
> Surface section until .NET 11

- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-10/includes/memory-eviction.md
Fixes #35661
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/c05522c05f78afc120e8343761b8d8074ff13f22/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core in .NET 10](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35676) |
> Memory eviction - WN 10 P6

- aspnetcore/fundamentals/openapi/include-metadata.md
[<img width="3210" height="1742" alt="image" src="https://github.com/user-attachments/assets/fa0a2cfa-a5a2-419f-b29b-58bfe2626e87" />](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?view=aspnetcore-9.0&tabs=minimal-apis#describe-the-request-body)
- https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?view=aspnetcore-9.0&tabs=minimal-apis#describe-the-request-body
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/include-metadata.md](https://github.com/dotnet/AspNetCore.Docs/blob/4a9a00f36ef5ec610ecaeec84f1019056e393c2b/aspnetcore/fundamentals/openapi/include-metadata.md) | [Include OpenAPI metadata in an ASP.NET Core app](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/i …
> Fix xref typo

- aspnetcore/release-notes/aspnetcore-10.0.md
Contributes to #35824
Just adding include lines and changing Auth section title.
---
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-10.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/854f9522b6e604a8f98f72ecbe9b87836b7ec82b/aspnetcore/release-notes/aspnetcore-10.0.md) | [What's new in ASP.NET Core in .NET 10](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?branch=pr-en-us-35929) |
> WN:OpenAPI and Validation include lines

- README.md
- aspnetcore/fundamentals/includes/apis6.md
Small update to improve documentation clarity for testing purposes.
> Minor documentation improvement

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35896
I just need one review to get this in.
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/a098dfca3697e6e2a0dd826a5dd1b73bf5a3bf3f/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [aspnetcore/blazor/security/blazor-web-app-with-oidc](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35953) |
> Improve app registration guidance

- .github/copilot-instructions.md
Fixes #35956
Copilot needed to be aware of how to handle file redirection, so it actively takes care of it when assigned an issue.
---
|:--|:--|
| [.github/copilot-instructions.md](https://github.com/dotnet/AspNetCore.Docs/blob/1e9cc7737ae80ebcf63187656a03f556b512af42/.github/copilot-instructions.md) | [Copilot Instructions for `dotnet/AspNetCore.Docs`](https://review.learn.microsoft.com/en-us/aspnet/core/.github/copilot-instructions?branch=pr-en-us-35955) |
> Update copilot-instructions.md: Handling File Redirection

- aspnetcore/blazor/fundamentals/index.md
- aspnetcore/fundamentals/index.md
- aspnetcore/migration/20_21.md
- aspnetcore/migration/21-to-22.md
- aspnetcore/migration/22-to-30.md
- aspnetcore/migration/30-to-31.md
- aspnetcore/migration/31-to-50.md
- aspnetcore/migration/31-to-60.md
- aspnetcore/migration/50-to-60-samples.md
- aspnetcore/migration/50-to-60.md
- aspnetcore/migration/60-70.md
- aspnetcore/migration/70-80.md
- aspnetcore/migration/80-90.md
- aspnetcore/release-notes/aspnetcore-1.1.md
- aspnetcore/release-notes/aspnetcore-10.0.md
- aspnetcore/release-notes/aspnetcore-2.0.md
- aspnetcore/release-notes/aspnetcore-2.1.md
- aspnetcore/release-notes/aspnetcore-2.2.md
- aspnetcore/release-notes/aspnetcore-3.0.md
- aspnetcore/release-notes/aspnetcore-3.1.md
- aspnetcore/release-notes/aspnetcore-5.0.md
- aspnetcore/release-notes/aspnetcore-6.0.md
- aspnetcore/release-notes/aspnetcore-7.0.md
- aspnetcore/release-notes/aspnetcore-8.0.md
- aspnetcore/release-notes/aspnetcore-9.0.md
Addresses #35958
Thanks @jbw716! 🚀 ... This only pertains to the 'breaking changes' part of your remarks. About all we can do is place a couple of additional cross-links. "`.net breaking changes`" in Google search brings up the right page. I don't think that there's much else we can do.
Tom, Wade ... This pitches that we have a short section on breaking changes in *Fundamentals* overview articles, which we could drop if you feel it isn't going to be helpful to anyone. I'm on-the-fence 🤔 about it. It might be helpful to some ... it might not. Otherwise, I seek to simplify our breaking changes section/cross-links in the *Migration* articles, and I think we should call it out with a consistent format in the *What's New* articles.
BTW ... The passkeys PR will add a *Migrations* article for …
> Simplify and extend breaking changes guidance

- aspnetcore/fundamentals/openapi/using-openapi-documents.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/35899#issuecomment-3201713375
---
|:--|:--|
| [aspnetcore/fundamentals/openapi/using-openapi-documents.md](https://github.com/dotnet/AspNetCore.Docs/blob/1f8733417caa0c923fb4e5b39a9609a4fdb8cac2/aspnetcore/fundamentals/openapi/using-openapi-documents.md) | [aspnetcore/fundamentals/openapi/using-openapi-documents](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?branch=pr-en-us-35966) |
> Fix API cross-link

- aspnetcore/blazor/security/blazor-web-app-with-oidc.md
Fixes #35892 
---
|:--|:--|
| [aspnetcore/blazor/security/blazor-web-app-with-oidc.md](https://github.com/dotnet/AspNetCore.Docs/blob/cfd4da4f7818f1ef99d7ffd975e1c2574391e477/aspnetcore/blazor/security/blazor-web-app-with-oidc.md) | [Secure an ASP.NET Core Blazor Web App with OpenID Connect (OIDC)](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?branch=pr-en-us-35961) |
> Duende Access Token Management 

- aspnetcore/docfx.json
Contributes to #35962
Setting the metadata for ms.update-cycle: values across the repo
> Set Freshness ms.update-cycle

- .github/copilot-instructions.md
This PR updates example URL and text alignment.
- Updated example URL to correct ones
- Adjusted spacing for better readability
---
|:--|:--|
| [.github/copilot-instructions.md](https://github.com/dotnet/AspNetCore.Docs/blob/a0b7814e6f795cdad04e5756332a9c8ad14f94a5/.github/copilot-instructions.md) | [.github/copilot-instructions](https://review.learn.microsoft.com/en-us/aspnet/core/.github/copilot-instructions?branch=pr-en-us-35997) |
> Fix: update URL and correct text alignment

- aspnetcore/security/data-protection/implementation/key-storage-providers.md
Fixes #36047
Sorry about this one! A 😈 got me!!! 😄
---
|:--|:--|
| [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/38a20ac48fe98d1d11810cd0a7ddd2b7c7b0e6d4/aspnetcore/security/data-protection/implementation/key-storage-providers.md) | [aspnetcore/security/data-protection/implementation/key-storage-providers](https://review.learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?branch=pr-en-us-36048) |
> Patch broken NOTE

- aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/Models/SeedData.cs
> Delete duplicate new Movie object

- aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie90/Pages/Movies/Details.cshtml
> Add description term element for Rating field

- aspnetcore/migration/fx-to-core/inc/remote-app-setup.md
Fixes #36082
---
|:--|:--|
| [aspnetcore/migration/fx-to-core/inc/remote-app-setup.md](https://github.com/dotnet/AspNetCore.Docs/blob/81650f7a4d4a2305c4da0db1e165084fbe07e880/aspnetcore/migration/fx-to-core/inc/remote-app-setup.md) | [Remote app setup](https://review.learn.microsoft.com/en-us/aspnet/core/migration/fx-to-core/inc/remote-app-setup?branch=pr-en-us-36114) |
> Fix service provider property in migration sample

- aspnetcore/blazor/components/prerender.md
Proposing some simplifications to the Blazor prerendering doc.
---
|:--|:--|
| [aspnetcore/blazor/components/prerender.md](https://github.com/dotnet/AspNetCore.Docs/blob/d9da4601de62f730680e2c44886fafcaf2237c36/aspnetcore/blazor/components/prerender.md) | [aspnetcore/blazor/components/prerender](https://review.learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?branch=pr-en-us-36111) |
> Blazor prerendering edits

- aspnetcore/test/http-files.md
Fixes #36061 
Also Closes #36115
PS: I prompted Copilot in VS Code to elaborate on the possible variable values.
This was more detailed than this PR, and included information about the variable name.
Unfortunately, it also contained some false information (e.g. mentioned the variable name must start with a letter or underscore, which is false because a number is also valid).
But... it pointed out that we could also enhance that part of the docs, which I tried to do in this PR.
---
|:--|:--|
| [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/113e5ca5ec7a28865caf20010651f6c139929416/aspnetcore/test/http-files.md) | [Use .http files in Visual Studio 2022](https://review.learn.microsoft.com/en-us/aspnet/core/test/http-files?branch=pr-en …
> add more info about null values in variables

- aspnetcore/fundamentals/static-files.md
Addresses #35810
---
|:--|:--|
| [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/ddf6a98afa55dcaf0379e43e86a440cad190680a/aspnetcore/fundamentals/static-files.md) | [aspnetcore/fundamentals/static-files](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?branch=pr-en-us-36117) |
> Add `StaticWebAssetContentTypeMapping` example

- aspnetcore/blazor/components/render-modes.md
- aspnetcore/blazor/fundamentals/dependency-injection.md
- aspnetcore/blazor/security/webassembly/index.md
Fixes #35718
Tom, Wade ... Only need one review to get this in, and we're making these updates per [these work items for the article](https://github.com/dotnet/AspNetCore.Docs/issues/35718#issuecomment-3304784156).
Also, I found one spot where I had "import file" capitalized, so I'm fixing that along the way to make it consistent with what I've done elsewhere.
If you want to see the INCLUDE file contents, which we aren't changing and is also used by Blazor's SignalR article ...
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/includes/closure-of-circuits.md
---
|:--|:--|
| [aspnetcore/blazor/components/render-modes.md](https://github.com/dotnet/AspNetCore.Docs/blob/7d4b9a58fa7febe3f4141b871c9d4ff20ddc329c/aspnetcore/blazor/components/render- …
> Render Modes article improvements

- aspnetcore/fundamentals/minimal-apis/responses.md
- aspnetcore/fundamentals/minimal-apis/test-min-api.md
Follow up of https://github.com/dotnet/AspNetCore.Docs/pull/36107#discussion_r2349713164 
Instead of elaborating on the test setup, I think it's better to refer to the testing page.
This way, all test-related information is grouped together instead of shattered across multiple pages.
---
|:--|:--|
| [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/f8cf73b41af712b49faded30e17e5481192981f4/aspnetcore/fundamentals/minimal-apis/responses.md) | [How to create responses in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?branch=pr-en-us-36134) |
| [aspnetcore/fundamentals/minimal-apis/test-min-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/f8cf73b41af712 …
> Refer to testing docs in favor of inline example
